### PR TITLE
Adding novnc license exclusion

### PR DESCRIPTION
**Pull request by davidjumani**
## Description
Adding novnc license exclusion to the rat plugin

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by DaanHoogland** [comment]
for dealing with a missed rat issue in #3967 all code is under MPL 2.0 (cat A)

**Comment by DaanHoogland** [comment]
ai ai, mistake MPL 2.0 is cat B. That does not mean we can't release with this but may have to add a notice to our README.md
I don't think that is in scope for this PR but will have to be dealt with before 4.15. @svenvogel can you keep an eye? (created #4098 )

**Comment by svenvogel** [comment]
@DaanHoogland yes i will track this and remind to add this in 4.15

**Comment by DaanHoogland** [comment]
ok, @svenvogel than can you approve of this one and merge?

**Pull request merged**
