### PR TITLE
[CLOUDSTACK-10257]Create template/volume does not allow to specify HVM requirements

### PR DESCRIPTION
**Pull request by rafaelweingartner**
When creating a template from a snapshot of a ROOT volume, which has a PV operating system, ACS creates the template with flag HVM=1, which may cause problems to deploy the aforementioned template in environments that do not have hosts that support HVM. When creating templates from Snapshots or volumes an option to specify if the template that is going to be created needs HVM or not should be presented.

### CODE REVIEW

**Comment by DaanHoogland** [comment]
and some javascript refactoring along the way :+1:

**Comment by rafaelweingartner** [comment]
It is not as much refactoring as it is extracting duplicated code to a common method.

BTW, the JavaScript part of ACS looks like created by someone that was charging by the lines.... I have never seen so many repeated code in my whole life.

**Comment by rafaelweingartner** [comment]
This PR will create add the HVM option as illustrated in the following image. The option will appear in both, create template from snapshot and create template from volume buttons.

image

**Comment by rafaelweingartner** [comment]
@khos2ow would you mind reviewing this one?

**Comment by rafaelweingartner** [comment]
Thanks @khos2ow.
@DaanHoogland are you ok here?

**Pull request merged**
