### PR TITLE
CLOUDSTACK-9057 remove old system vm upgrade code

### PR DESCRIPTION
**Pull request by DaanHoogland**
the upgrade step to 4.5 system templates is removed for 4.6 in this. validation would be to install any 4.4.2 or lower version and upgrade to 4.6. It would only require the templates for 4.6 and not the ones for 4.5. as it would before this patch. only unittests performed hence for all practical purposes untested.

### CODE REVIEW

**Comment by ustcweizhou** [comment]
LGTM
that is what we did for previous versions

**Comment by remibergsma** [comment]
Since this code is only needed if you upgrade to `4.5` not when you hit this code if you upgrade from say `4.4` and jump forward to `4.6`. This code is still needed in the `4.5` branch but not here.

We should run an upgrade test to verify.

**Comment by wilderrodrigues** [comment]
I will test the upgrade, @DaanHoogland and LGTM afterwards.

Cheers,
Wilder

**Comment by DaanHoogland** [comment]
@remibergsma @wilderrodrigues @karuturi is anything to be done with this?

**Comment by remibergsma** [comment]
@DaanHoogland Yes, please make this PR towards 4.6 please.

**Comment by DaanHoogland** [comment]
#1072 contains this code to be merged on 4.6 (and rebased on post-release commit)

**Pull request closed without merging**
