### PR TITLE
ui: fix handle action API response

### LINKED ISSUE #5284: deleting a networkoffering succeeds with exception
when going into a network offering, that is disabled or unused, deleting it leads to a 403 page.

image

image

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### STEPS TO REPRODUCE

~~~
see description
~~~

##### EXPECTED RESULTS

~~~
a refresh to the network offering overview.
~~~

##### ACTUAL RESULTS

~~~
see screenshot above
~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #5284
Fix for handling action API response

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### How Has This Been Tested?

pr5285

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan ui

**Review by davidjumani — APPROVED** [review]

**Review by DaanHoogland — APPROVED** [review]
great @shwstppr , tnx

**Comment by DaanHoogland** [comment]
@shwstppr should we check 4.15 for this or is the origin known to be newer?

**Comment by shwstppr** [comment]
@DaanHoogland issue is not there in 4.15. It crept in with https://github.com/apache/cloudstack/commit/66e7bdedac76fb2c3f8d87e537e482c73af4799a which was trying to fix ui build failure after 4.15 forward merge into main

**Review by nvazquez — APPROVED** [review]

**Comment by nvazquez** [comment]
LGTM manually tested - merged based on approvals

**Pull request merged**
