### PR TITLE
Allow users (User account Role) to delete / archive events

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

This PR fixes: https://github.com/apache/cloudstack/issues/5519. Users unable to archive / delete their events.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### How Has This Been Tested?
Was able to delete / archive events  when logged in with user account role.

image

### CODE REVIEW

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
@blueorangutan ui

**Comment by rhtyd** [comment]
@blueorangutan ui

**Comment by rhtyd** [comment]
@Pearl1594 somehow the qa.cloudstack.cloud URL with this PR fails on log in (says caught issue) but it works on the normal URL. Can you check?

**Comment by Pearl1594** [comment]
Could it be some caching issue @rhtyd ? As I was able to login just fine:
image

**Review by nvazquez — APPROVED** [review]
LGTM manually tested

**Pull request merged**
