### PR TITLE
UI: fix default network is not passed to deployvm API

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes a critical issue on UI that the default network is not passed to deployvm API, so the default network is always the first network.

This line was changed in #5080, but reverted in #5151

This issue exists in 4.17, 4.18 and main

workaround
- create a vm on default network (do not start it)
- add vm to other networks
- start the vm

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [x] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by NuxRo — APPROVED** [review]
LGTM

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
@NuxRo @weizhouapache feel free to merge/close this when tested
@blueorangutan ui

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by harikrishna-patnala — APPROVED** [review]
LGTM

**Comment by weizhouapache** [comment]
@NuxRo @harikrishna-patnala 
can one of you guys test it ? thanks !

**Comment by kiranchavala** [comment]
@blueorangutan  ui

**Comment by harikrishna-patnala** [comment]
I could reproduce the issue and also the verified the fix, it is working fine. LGTM

**Comment by weizhouapache** [comment]
thanks @harikrishna-patnala for the testing
merging

**Pull request merged**
