### PR TITLE
CLOUDSTACK-9410 Data Disk shown as detached in XS

### PR DESCRIPTION
**Pull request by yvsubhash**

### CODE REVIEW

**Comment by wido** [comment]
Thanks! Is there a issue attached to this PR or any additional information on why 'detached' isn't correct?

**Comment by yvsubhash** [comment]
@wido  Replacing the original name with 'detached is not correct as it is confusing. Anyway data disk being detached is captured in the state of the volume

**Comment by chiradeep** [comment]
I believe that http://dl.openvm.eu/cloudstack/ has modern templates that have the appropriate userdata / ssh key and password change agents built in. I have raised https://issues.apache.org/jira/browse/CLOUDSTACK-9414 to track this. Does @NuxRo  run the openvm.eu service?

**Comment by syed** [comment]
agree with @yvsubhash. I don't see an need to set the name-label to `detached` the code LGTM

**Comment by koushik-das** [comment]
code change LGTM

**Comment by cloudmonger** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 122
 Hypervisor xenserver
 NetworkType Advanced
 Passed=101
 Failed=3
 Skipped=5

_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/yj3wnzbceo9uef2/AAB6u-Iap-xztdm6jHX9SjPja?dl=0


**Failed tests:**
* test_non_contigiousvlan.py

 * test_extendPhysicalNetworkVlan Failed

* test_deploy_vm_iso.py

 * test_deploy_vm_from_iso Failing since 7 runs

* test_vm_life_cycle.py

 * test_10_attachAndDetach_iso Failing since 8 runs


**Skipped tests:**
test_01_test_vm_volume_snapshot
test_vm_nic_adapter_vmxnet3
test_static_role_account_acls
test_3d_gpu_support
test_deploy_vgpu_enabled_vm

**Passed test suits:**
test_deploy_vm_with_userdata.py
test_affinity_groups_projects.py
test_portable_publicip.py
test_over_provisioning.py
test_global_settings.py
test_scale_vm.py
test_service_offerings.py
test_routers_iptables_default_policy.py
test_loadbalance.py
test_routers.py
test_reset_vm_on_reboot.py
test_snapshots.py
test_deploy_vms_with_varied_deploymentplanners.py
test_network.py
test_router_dns.py
test_login.py
test_list_ids_parameter.py
test_public_ip_range.py
test_multipleips_per_nic.py
test_regions.py
test_affinity_groups.py
test_network_acl.py
test_pvlan.py
test_volumes.py
test_ssvm.py
test_nic.py
test_deploy_vm_root_resize.py
test_resource_detail.py
test_secondary_storage.py
test_disk_offerings.py

**Comment by yvsubhash** [comment]
@cloudmonger None of the test failures are related to the code change

**Comment by yvsubhash** [comment]
@syed @koushik-das can one of you please merge this

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by koushik-das** [comment]
Merging as all the required LGTMs are there.

**Pull request merged**
