### PR TITLE
systemvm: check if patchfile exists and is valid tarball before patching

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

Occasionally system vms (CPVM/SSVM) took long time (15~20 mins) to be Up, which happened if the network is slow.

/var/log/cloud.log shows
```
root@s-1-VM:~# grep sum /var/log/cloud.log
Fri 08 Sep 2023 10:25:51 AM UTC Scripts checksum detected: oldmd5=da16d6a2533fd19960304152dd78e02c newmd5=da16d6a2533fd19960304152dd78e02c
Fri 08 Sep 2023 10:26:44 AM UTC Scripts checksum detected: oldmd5=da16d6a2533fd19960304152dd78e02c newmd5=d41d8cd98f00b204e9800998ecf8427e
Fri 08 Sep 2023 10:39:09 AM UTC Scripts checksum detected: oldmd5=d41d8cd98f00b204e9800998ecf8427e newmd5=0ec9117c206d7440309ba9d531e59e4d
Fri 08 Sep 2023 10:39:13 AM UTC Scripts checksum detected: oldmd5=d41d8cd98f00b204e9800998ecf8427e newmd5=0ec9117c206d7440309ba9d531e59e4d
```

`d41d8cd98f00b204e9800998ecf8427e` is the md5sum value of empty file.
```
d41d8cd98f00b204e9800998ecf8427e  /dev/null
```

We need to wait until the transfer of patchfile is finished.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@rohityadavcloud 
this is a minor issue. It requires a new systemvm template.
let's merge into 4.18.2.0

**Review by Pearl1594 — APPROVED** [review]
LGTM, 
Just to clarify, does this mean that if the patch file exists but only partially scp'd into the systemvm, `tar tf` will help identify it's not completely transferred?

**Comment by weizhouapache** [comment]
> LGTM, Just to clarify, does this mean that if the patch file exists but only partially scp'd into the systemvm, `tar tf` will help identify it's not completely transferred?

exactly @Pearl1594 

the patchfile is very small (139166 bytes), so normally it is not a problem.
but I have seen the issue more than five times.

**Comment by Pearl1594** [comment]
> > LGTM, Just to clarify, does this mean that if the patch file exists but only partially scp'd into the systemvm, `tar tf` will help identify it's not completely transferred?
> 
> exactly @Pearl1594
> 
> the patchfile is very small (139166 bytes), so normally it is not a problem. but I have seen the issue more than five times.

makes perfect sense..

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by harikrishna-patnala — APPROVED** [review]
Code LGTM

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
clgtm, tried some tar commands to see the result but did not test this in the system.

**Comment by weizhouapache** [comment]
@blueorangutan test matrix

**Comment by weizhouapache** [comment]
@blueorangutan LLtest matrix

**Comment by DaanHoogland** [comment]
@blueorangutan test rocky8 vmware-67u3

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan LLtest matrix

**Comment by weizhouapache** [comment]
thanks @DaanHoogland for merging
the trillian test results looks nice :-D

@shwstppr @rohityadavcloud 
as I remember this requires a new systemvm template

**Pull request merged**
