### PR TITLE
Volume encryption support for StorPool plug-in

### PR DESCRIPTION
**Pull request by slavkap**
### Description

Support of volume encryption for the StorPool plugin

Supported Virtual machine operations:
- live migration of VM to another host
- virtual machine snapshots (group snapshots without memory)
- revert VM snapshot
- delete VM snapshot

 Supported Volume operations:
- attach/detach volume
- live migrate volume between two StorPool primary storages
- volume snapshot
- delete snapshot
- revert snapshot

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [X] Major
- [ ] Minor

### How Has This Been Tested?

Environment: 
CS mgmt - Rocky Linux
2 KVM hypervisors - Rocky

Smoke and manual tests

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@slavkap
the code not related to storpool looks goood to me.

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
CLGTM

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Pull request merged**
