### PR TITLE
host affinity: fix vm cannot be started if a vm is stopped in the affinity group

### LINKED ISSUE #6933: VMs using strict host affinity cannot be started
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.18
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

When all VMs using the same strict host affinity group are stopped, they cannot be started anymore.

##### STEPS TO REPRODUCE

~~~
1. Create a new strict host affinity group
2. Deploy two VMs which use this affinity group
3. Stop both VMs
4. Try to start any of the VMs
~~~

##### EXPECTED RESULTS

~~~
The VMs should start normally.
~~~

##### ACTUAL RESULTS

~~~
The VMs cannot be started anymore. 
~~~

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR  fixes #6933 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by vladimirpetrov** [comment]
@blueorangutan package

**Review by vladimirpetrov — APPROVED** [review]
LGTM based on manual testing.

**Comment by weizhouapache** [comment]
@blueorangutan test

**Review by BryanMLima — APPROVED** [review]

**Pull request merged**
