### PR TITLE
WIP: CLOUDSTACK-4757:  support for multidisk OVA files

### PR DESCRIPTION
**Pull request by abhinandanprateek**
Signed-off-by: Abhinandan Prateek <abhinandan.prateek@shapeblue.com>

### CODE REVIEW

**Comment by serg38** [comment]
@abhinandanprateek I am curious if this PR will allow deploying VM with Data disk attached?

**Comment by abhinandanprateek** [comment]
@serg38 Yes, the aim of the PR is to enable deployment from templates with multiple data disks.

**Comment by abhinandanprateek** [comment]
@blueorangutan package

**Comment by abhinandanprateek** [comment]
@blueorangutan test vmware

**Comment by abhinandanprateek** [comment]
@blueorangutan test vmware-55u3

**Comment by abhinandanprateek** [comment]
@blueorangutan test centos7 vmware-55u3

**Comment by abhinandanprateek** [comment]
@blueorangutan cancel

**Comment by abhinandanprateek** [comment]
@blueorangutan package

**Comment by abhinandanprateek** [comment]
@blueorangutan package

**Comment by abhinandanprateek** [comment]
@blueorangutan package

**Comment by abhinandanprateek** [comment]
@blueorangutan package

**Comment by abhinandanprateek** [comment]
@blueorangutan package

**Comment by abhinandanprateek** [comment]
@blueorangutan package

**Comment by abhinandanprateek** [comment]
@blueorangutan package

**Comment by abhinandanprateek** [comment]
@blueorangutan package

**Comment by GabrielBrascher** [comment]
@abhinandanprateek thanks for your work.

Could you please append the Jira issue CLOUDSTACK-4757 with the PR title (https://issues.apache.org/jira/browse/CLOUDSTACK-4757).

For instance _CLOUDSTACK-4757: Support OVA files with multiple disks for templates_.

**Comment by GabrielBrascher** [comment]
Unless I missed something and this PR does not address the same issue at CLOUDSTACK-4757. In this case, I am sorry.

**Comment by abhinandanprateek** [comment]
This PR is basically merging https://git-wip-us.apache.org/repos/asf?p=cloudstack.git;a=shortlog;h=refs/heads/multiple-disk-ova. And continue to build on it.

**Pull request closed without merging**
