### PR TITLE
CLOUDSTACK-10319: Prefer TLSv1.2, deprecate TLSv1.0,1.1

### PR DESCRIPTION
**Pull request by rhtyd**
This deprecates and remove TLS 1.0 and 1.1 from preferred list of
protocols and keeps only TLSv1.2.

@blueorangutan package

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-65

**Comment by wido** [comment]
LGTM based on the code

**Comment by rhtyd** [comment]
Test LGTM, no failures seen. The only affected public facing services are browser related - (1) apache2 on systemvms and (2) jetty powered mgmt server. Given the UI does not support IE, we've been testing against modern browsers such as Chrome and Firefox only, acceptance of the PR should not cause new failures for users. If admins want to enable TLS support (1.0+1.1) for browsers for the UI, they may configure the java.security.ciphers file or explicitly set the `jdk.tls.disabledAlgorithms= SSLv2Hello, SSLv3` option to allow both TLSv1, v1.1. With Java8, TLS1.2 is enabled by default.

**Comment by rhtyd** [comment]
Merging this PR based on test results and code reviews, thanks.

**Comment by rafaelweingartner** [comment]
@rhtyd have you tested this one against XenServer 6.5?

**Comment by rhtyd** [comment]
@rafaelweingartner no, let me kick one explicitly on latest 4.11 via #2376

**Comment by rafaelweingartner** [comment]
Ok, thanks.
I had a problem with these changes and XenServer 6.5. XS 6.5 is using TLSV1.

**Comment by rhtyd** [comment]
@rafaelweingartner @PaulAngus and others this seems to break older xenservers and vmware 5.x vcenters which expects to connect via TLS 1.0. I think instead to do this system-wide we may only fix it for public facing services such as - (a) apache2 in systemvms, (b) console proxy server, (c) management server. I'll partially revert this.

**Pull request merged**
