### PR TITLE
Allow set IPv6 when deploying advanced network  Zone with SG via UI

### PR DESCRIPTION
**Pull request by GabrielBrascher**
## Description

Advanced Network with Security Groups is a great option for deploying a Zone with IPv6 address support. However, it is not possible to set **IPv6 DNS** + **IPv6 CIDR** + **IPv6 gateway** via the zoneWizard UI.

Currently, the workaround is to either (i) create a new network (the default guest network would not support IPv6), (ii) deploy a zone via API, or (iii) to run a MySQL update query to set the default guest network IPv6 config.

This PR adds a small enhancement on the UI Zone deployment to allow deploying a Zone with Advanced Network with Security Groups + IPv6 CIDR, IPv6 gateway, and IPv6 DNS.

Note that API [[1]](https://cloudstack.apache.org/api/apidocs-4.13/apis/createNetwork.html) offers full support for such action, therefore there is no need for changing the API. It is just a small enhancement on UI that might be useful in the meantime that we wait for the new ACS UI.

[1] https://cloudstack.apache.org/api/apidocs-4.13/apis/createNetwork.html

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## Screenshots (if appropriate):
zoneWizard
ip6Guest
ip6GuestDetails
zoneNetwork

## How Has This Been Tested?

1. Create a new Zone with advanced network and security groups 
2. Configure ipv6 dns, ipv6 cidr, and ipv6 gateway
3. Check that guest network has been created as expected

### CODE REVIEW

**Comment by DaanHoogland** [comment]
Assuming you want this in 4.15, @GabrielBrascher ; can you provide a primate PR, please?

**Comment by GabrielBrascher** [comment]
You are right @DaanHoogland, this will be for 4.15 (maybe 4.14.1, but I am considering this more a enhancement than a bugfix).

Sure, I will check how I can add this to primate and ensure that we have proper IPv6 support there as well.

**Comment by rhtyd** [comment]
@GabrielBrascher can you check and send PR to https://github.com/apache/cloudstack-primate as well

**Comment by GabrielBrascher** [comment]
@rhtyd just linking the Draft PR [#343](https://github.com/apache/cloudstack-primate/pull/343) created at the CloudStack Primate project.

**Pull request merged**
