### PR TITLE
marvin: fix smoke test failures if mgmt server is Ubuntu and hosts are VMware

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes the smoke test failures when mgmt server is ubuntu.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test ubuntu22 vmware-70u3

**Comment by DaanHoogland** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Comment by weizhouapache** [comment]
@blueorangutan test ubuntu22 vmware-70u3

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 vmware-70u3

**Review by DaanHoogland — APPROVED** [review]
clgtm, should work on all platforms and is extensively tested in the smoke tests

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 vmware-70u3

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
@weizhouapache are the intermittent failures related or can we merge this? Thanks.

**Comment by weizhouapache** [comment]
> @weizhouapache are the intermittent failures related or can we merge this? Thanks.

@rohityadavcloud 
not related I think. let's merge it

**Pull request merged**
