### PR TITLE
CLOUDSTACK-8993: DHCP fails with "no address available" when an IP is…

### PR DESCRIPTION
**Pull request by serbaut**
… reused

Repopulate /etc/dhcphosts.txt to remove old entries with the same IP address.

### CODE REVIEW

**Comment by wido** [comment]
Is there any way we can test this automatically? I think there is no Unit Test for this, right?

I currently don't have a setup to test this, but can you explain how you tested this?

**Comment by serbaut** [comment]
I tested this manually. I did not manage to get any test environment to work but there is some tests in test/systemvm/test_update_config.py that could probably be extended to test this. Not sure where to start with running those tests though :(

**Comment by remibergsma** [comment]
pinging @wilderrodrigues to have a look

**Comment by serbaut** [comment]
Thanks, I will have another go at running the tests to see if I can write a test for it.

**Comment by serbaut** [comment]
Getting errors when running test/systemvm/test_update_config.py.

        from envassert import file, process, package, user, group, port, cron, detect, ip
    ImportError: cannot import name ip

Got other errors when setting up devcloud by following https://cwiki.apache.org/confluence/display/CLOUDSTACK/devcloud-kvm but I managed to work around it.

    Exception Occurred Under createLogs :['Traceback (most recent call last):\n', '  File "/usr/local/lib/python2.7/site-packages/Marvin-4.6.0_SNAPSHOT-py2.7.egg/marvin/marvinLog.py", line 157, in createLogs\n    (\'LogFolderPath\' in log_cfg.__dict__.keys()) and\n', "Attri
    buteError: 'list' object has no attribute '__dict__'\n"]

Not sure how to proceed. Are these tests supposed to work at all?

**Comment by wilderrodrigues** [comment]
Hi @serbaut ,

Could you write an integration test with marvin to cover this change? If you don't have a test environment or are not familiar with Marvin tests, I can provide some help. But for that to happen I would need some direction/steps. For example: how to reproduce it?

Cheers,
Wilder

**Comment by serbaut** [comment]
In our environment it was really easy to reproduce.
* Deploy instance 1, got IP 10.7.32.101
* Delete and expunge instance 1
* Deploy instance 2, got IP 100.7.32.101

/etc/dhcphosts.txt now looked like

    mac1,10.7.32.101,infinite
    mac2,10.7.32.101,infinite

And ndsmasq failed with a warning about duplicates and "no address available".

I am still trying to get marvin tests inside devcloud to work. Is there a way to reach you if I need assistance. Are the tests i tried to run above (test_update_config.py) supposed to work or are the deprecated?

**Comment by remibergsma** [comment]
LGTM, based on a set of tests that I run on this branch (which I rebased myself first):

```
nosetests --with-marvin --marvin-config=${marvinCfg} -s -a tags=advanced,required_hardware=true \
component/test_vpc_redundant.py \
component/test_routers_iptables_default_policy.py \
component/test_routers_network_ops.py \
component/test_vpc_router_nics.py \
smoke/test_loadbalance.py \
smoke/test_internal_lb.py \
smoke/test_ssvm.py \
smoke/test_network.py

```

Result:

```
Create a redundant VPC with two networks with two VMs in each network ... === TestName: test_01_create_redundant_VPC_2tiers_4VMs_4IPs_4PF_ACL | Status : SUCCESS ===
ok
Create a redundant VPC with two networks with two VMs in each network and check default routes ... === TestName: test_02_redundant_VPC_default_routes | Status : SUCCESS ===
ok
Test iptables default INPUT/FORWARD policy on RouterVM ... === TestName: test_02_routervm_iptables_policies | Status : SUCCESS ===
ok
Test iptables default INPUT/FORWARD policies on VPC router ... === TestName: test_01_single_VPC_iptables_policies | Status : SUCCESS ===
ok
Stop existing router, add a PF rule and check we can access the VM ... === TestName: test_isolate_network_FW_PF_default_routes | Status : SUCCESS ===
ok
Test redundant router internals ... === TestName: test_RVR_Network_FW_PF_SSH_default_routes | Status : SUCCESS ===
ok
Create a VPC with two networks with one VM in each network and test nics after destroy ... === TestName: test_01_VPC_nics_after_destroy | Status : SUCCESS ===
ok
Create a VPC with two networks with one VM in each network and test default routes ... === TestName: test_02_VPC_default_routes | Status : SUCCESS ===
ok
Test to create Load balancing rule with source NAT ... === TestName: test_01_create_lb_rule_src_nat | Status : SUCCESS ===
ok
Test to create Load balancing rule with non source NAT ... === TestName: test_02_create_lb_rule_non_nat | Status : SUCCESS ===
ok
Test for assign & removing load balancing rule ... === TestName: test_assign_and_removal_lb | Status : SUCCESS ===
ok
Test to verify access to loadbalancer haproxy admin stats page ... === TestName: test02_internallb_haproxy_stats_on_all_interfaces | Status : SUCCESS ===
ok
Test create, assign, remove of an Internal LB with roundrobin http traffic to 3 vm's ... === TestName: test_01_internallb_roundrobin_1VPC_3VM_HTTP_port80 | Status : SUCCESS ===
ok
Test SSVM Internals ... === TestName: test_03_ssvm_internals | Status : SUCCESS ===
ok
Test CPVM Internals ... === TestName: test_04_cpvm_internals | Status : SUCCESS ===
ok
Test stop SSVM ... === TestName: test_05_stop_ssvm | Status : SUCCESS ===
ok
Test stop CPVM ... === TestName: test_06_stop_cpvm | Status : SUCCESS ===
ok
Test reboot SSVM ... === TestName: test_07_reboot_ssvm | Status : SUCCESS ===
ok
Test reboot CPVM ... === TestName: test_08_reboot_cpvm | Status : SUCCESS ===
ok
Test destroy SSVM ... === TestName: test_09_destroy_ssvm | Status : SUCCESS ===
ok
Test destroy CPVM ... === TestName: test_10_destroy_cpvm | Status : SUCCESS ===
ok
Test for port forwarding on source NAT ... === TestName: test_01_port_fwd_on_src_nat | Status : SUCCESS ===
ok
Test for port forwarding on non source NAT ... === TestName: test_02_port_fwd_on_non_src_nat | Status : SUCCESS ===
ok
Test for reboot router ... === TestName: test_reboot_router | Status : SUCCESS ===
ok
Test for Router rules for network rules on acquired public IP ... === TestName: test_network_rules_acquired_public_ip_1_static_nat_rule | Status : FAILED ===
FAIL
Test for Router rules for network rules on acquired public IP ... === TestName: test_network_rules_acquired_public_ip_2_nat_rule | Status : FAILED ===
FAIL
Test for Router rules for network rules on acquired public IP ... === TestName: test_network_rules_acquired_public_ip_3_Load_Balancer_Rule | Status : FAILED ===
FAIL
----------------------------------------------------------------------
Ran 27 tests in 11818.695s

FAILED (failures=3)

```

The 3 errors at the bottom are due to CLOUDSTACK-8991 and unrelated to this PR.

And:

```
nosetests --with-marvin --marvin-config=${marvinCfg} -s -a tags=advanced,required_hardware=false \
smoke/test_routers.py \
smoke/test_network_acl.py \
smoke/test_privategw_acl.py \
smoke/test_reset_vm_on_reboot.py \
smoke/test_vm_life_cycle.py \
smoke/test_vpc_vpn.py \
smoke/test_service_offerings.py \
component/test_vpc_offerings.py \
component/test_vpc_routers.py
```

Result:

```
Test router internal advanced zone ... === TestName: test_02_router_internal_adv | Status : SUCCESS ===
ok
Test restart network ... === TestName: test_03_restart_network_cleanup | Status : SUCCESS ===
ok
Test router basic setup ... === TestName: test_05_router_basic | Status : SUCCESS ===
ok
Test router advanced setup ... === TestName: test_06_router_advanced | Status : SUCCESS ===
ok
Test stop router ... === TestName: test_07_stop_router | Status : SUCCESS ===
ok
Test start router ... === TestName: test_08_start_router | Status : SUCCESS ===
ok
Test reboot router ... === TestName: test_09_reboot_router | Status : SUCCESS ===
ok
test_privategw_acl (integration.smoke.test_privategw_acl.TestPrivateGwACL) ... === TestName: test_privategw_acl | Status : SUCCESS ===
ok
Test reset virtual machine on reboot ... === TestName: test_01_reset_vm_on_reboot | Status : SUCCESS ===
ok
Test advanced zone virtual router ... === TestName: test_advZoneVirtualRouter | Status : SUCCESS ===
ok
Test Deploy Virtual Machine ... === TestName: test_deploy_vm | Status : SUCCESS ===
ok
Test Multiple Deploy Virtual Machine ... === TestName: test_deploy_vm_multiple | Status : SUCCESS ===
ok
Test Stop Virtual Machine ... === TestName: test_01_stop_vm | Status : SUCCESS ===
ok
Test Start Virtual Machine ... === TestName: test_02_start_vm | Status : SUCCESS ===
ok
Test Reboot Virtual Machine ... === TestName: test_03_reboot_vm | Status : SUCCESS ===
ok
Test destroy Virtual Machine ... === TestName: test_06_destroy_vm | Status : SUCCESS ===
ok
Test recover Virtual Machine ... === TestName: test_07_restore_vm | Status : SUCCESS ===
ok
Test migrate VM ... === TestName: test_08_migrate_vm | Status : SUCCESS ===
ok
Test destroy(expunge) Virtual Machine ... === TestName: test_09_expunge_vm | Status : SUCCESS ===
ok
Test Remote Access VPN in VPC ... === TestName: test_vpc_remote_access_vpn | Status : SUCCESS ===
ok
Test VPN in VPC ... === TestName: test_vpc_site2site_vpn | Status : SUCCESS ===
ok
Test to create service offering ... === TestName: test_01_create_service_offering | Status : SUCCESS ===
ok
Test to update existing service offering ... === TestName: test_02_edit_service_offering | Status : SUCCESS ===
ok
Test to delete service offering ... === TestName: test_03_delete_service_offering | Status : SUCCESS ===
ok
Test for delete account ... === TestName: test_delete_account | Status : SUCCESS ===
ok
Test for Associate/Disassociate public IP address for admin account ... === TestName: test_public_ip_admin_account | Status : SUCCESS ===
ok
Test for Associate/Disassociate public IP address for user account ... === TestName: test_public_ip_user_account | Status : SUCCESS ===
ok
Test for release public IP address ... === TestName: test_releaseIP | Status : SUCCESS ===
ok
Test create VPC offering ... === TestName: test_01_create_vpc_offering | Status : SUCCESS ===
ok
Test VPC offering without load balancing service ... === TestName: test_03_vpc_off_without_lb | Status : SUCCESS ===
ok
Test VPC offering without static NAT service ... === TestName: test_04_vpc_off_without_static_nat | Status : SUCCESS ===
ok
Test VPC offering without port forwarding service ... === TestName: test_05_vpc_off_without_pf | Status : SUCCESS ===
ok
Test VPC offering with invalid services ... === TestName: test_06_vpc_off_invalid_services | Status : SUCCESS ===
ok
Test update VPC offering ... === TestName: test_07_update_vpc_off | Status : SUCCESS ===
ok
Test list VPC offering ... === TestName: test_08_list_vpc_off | Status : SUCCESS ===
ok
test_09_create_redundant_vpc_offering (integration.component.test_vpc_offerings.TestVPCOffering) ... === TestName: test_09_create_redundant_vpc_offering | Status : SUCCESS ===
ok
Test start/stop of router after addition of one guest network ... === TestName: test_01_start_stop_router_after_addition_of_one_guest_network | Status : SUCCESS ===
ok
Test reboot of router after addition of one guest network ... === TestName: test_02_reboot_router_after_addition_of_one_guest_network | Status : SUCCESS ===
ok
Test to change service offering of router after addition of one guest network ... === TestName: test_04_chg_srv_off_router_after_addition_of_one_guest_network | Status : SUCCESS ===
ok
Test destroy of router after addition of one guest network ... === TestName: test_05_destroy_router_after_addition_of_one_guest_network | Status : SUCCESS ===
ok
Test to stop and start router after creation of VPC ... === TestName: test_01_stop_start_router_after_creating_vpc | Status : SUCCESS ===
ok
Test to reboot the router after creating a VPC ... === TestName: test_02_reboot_router_after_creating_vpc | Status : SUCCESS ===
ok
Tests to change service offering of the Router after ... === TestName: test_04_change_service_offerring_vpc | Status : SUCCESS ===
ok
Test to destroy the router after creating a VPC ... === TestName: test_05_destroy_router_after_creating_vpc | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 44 tests in 8945.589s

OK
```

The actual change of this PR was not tested, it just shows nothing else was broken by this commit.

@serbaut Thanks for the fix! Please force-push your commits again to trigger another Jenkins test. Once it is green and we have a review from @wilderrodrigues we can continue.

**Comment by serbaut** [comment]
Thanks. I still haven't given up on writing a test for this. Just found one issue with running

    python2.7 marvin/marvin/deployDataCenter.py -i devcloud-kvm/devcloud-kvm-advanced.cfg

That config uses a logger config that doesn't work with marvin.

Now I can't get nose to use python2.7, even when running nosetest2.7:

    [root@devcloud-kvm cloudstack]# nosetests-2.7 --with-marvin --marvin-config=tools/devcloud-kvm/devcloud-kvm-advanced.cfg -a tags='devcloud'
    ==== Marvin Init Started ====

    === Marvin Parse Config Successful ===

    === Marvin Setting TestData Successful===

    ==== Log Folder Path: /tmp//MarvinLogs//Oct_28_2015_05_10_35_QWNYQ4. All logs will be available here ====

    === Marvin Init Logging Successful===

    ==== Marvin Init Successful ====
    Traceback (most recent call last):
      File "/root/cloudstack/test/integration/component/find_hosts_for_migration.py", line 21, in <module>
        from nose.plugins.attrib import attr
    ImportError: cannot import name attr
    Traceback (most recent call last):
      File "/root/cloudstack/test/integration/component/maint/test_bugs.py", line 19, in <module>
        from marvin.cloudstackTestCase import cloudstackTestCase, unittest
    ImportError: No module named marvin.cloudstackTestCase
    ^C  File "/root/cloudstack/test/integration/component/maint/test_dedicate_guest_vlan_ranges.py", line 26, in <module>
        from nose.plugins.attrib import attr

Is there a better/simpler way to run the tests? Should i not use devcloud-kvm? Should I not use advanced networking? Just trying to follow https://cwiki.apache.org/confluence/display/CLOUDSTACK/devcloud-kvm

A "make test" that just worked would have been nice :)

**Comment by miguelaferreira** [comment]
Hi @serbaut I sometimes have trouble with nose after installing marvin. So what I do, is to install marvin, and then reinstall nose (forcing it to actually reinstall).
Could you please try that to see if the error goes away?

**Comment by remibergsma** [comment]
Hi @serbaut Did the deployDatacenter.py actually work?

**Comment by serbaut** [comment]
Yes I have a running zone with advanced networking. Giving up on the tests, too much breakage everywhere. I must be doing something wrong.

**Comment by remibergsma** [comment]
@serbaut Sorry to hear that! Good that the deploy actually works. I'm not using DevCloud so I cannot help with that. I do know that I have no issues running Marvin tests from CentOS 7.

**Comment by serbaut** [comment]
Wtf Jenkins, no means no.

**Comment by wilderrodrigues** [comment]
Thanks for the details, @serbaut!

I will test you PR as well.

Cheers,
Wilder

**Comment by serbaut** [comment]
Thank you. Sorry I could not write a test for it. Maybe the instructions for running tests need to be updated because I ran into all sorts of problems. Can't even get Jenkins to execute the tests it seems :(

**Comment by wilderrodrigues** [comment]
Hi @serbaut and @remibergsma 

First tests have been executed. I got 1 error, related to private gateway ACL, but I think it was just a weird glitch on Marvin. Why? First thing, the test worked fine with @remibergsma's tests; Second, the error only says None etc.

Test Results:

```
Test start/stop of router after addition of one guest network ... === TestName: test_01_start_stop_router_after_addition_of_one_guest_network | Status : SUCCESS ===
ok
Test reboot of router after addition of one guest network ... === TestName: test_02_reboot_router_after_addition_of_one_guest_network | Status : SUCCESS ===
ok
Test to change service offering of router after addition of one guest network ... === TestName: test_04_chg_srv_off_router_after_addition_of_one_guest_network | Status : SUCCESS ===
ok
Test destroy of router after addition of one guest network ... === TestName: test_05_destroy_router_after_addition_of_one_guest_network | Status : SUCCESS ===
ok
Test to stop and start router after creation of VPC ... === TestName: test_01_stop_start_router_after_creating_vpc | Status : SUCCESS ===
ok
Test to reboot the router after creating a VPC ... === TestName: test_02_reboot_router_after_creating_vpc | Status : SUCCESS ===
ok
Tests to change service offering of the Router after ... === TestName: test_04_change_service_offerring_vpc | Status : SUCCESS ===
ok
Test to destroy the router after creating a VPC ... === TestName: test_05_destroy_router_after_creating_vpc | Status : SUCCESS ===
ok
Test router internal advanced zone ... === TestName: test_02_router_internal_adv | Status : SUCCESS ===
ok
Test restart network ... === TestName: test_03_restart_network_cleanup | Status : SUCCESS ===
ok
Test router basic setup ... === TestName: test_05_router_basic | Status : SUCCESS ===
ok
Test router advanced setup ... === TestName: test_06_router_advanced | Status : SUCCESS ===
ok
Test stop router ... === TestName: test_07_stop_router | Status : SUCCESS ===
ok
Test start router ... === TestName: test_08_start_router | Status : SUCCESS ===
ok
Test reboot router ... === TestName: test_09_reboot_router | Status : SUCCESS ===
ok
test_privategw_acl (integration.smoke.test_privategw_acl.TestPrivateGwACL) ... === TestName: test_privategw_acl | Status : FAILED ===
FAIL
Test reset virtual machine on reboot ... === TestName: test_01_reset_vm_on_reboot | Status : SUCCESS ===
ok
Test advanced zone virtual router ... === TestName: test_advZoneVirtualRouter | Status : SUCCESS ===
ok
Test Deploy Virtual Machine ... === TestName: test_deploy_vm | Status : SUCCESS ===
ok
Test Multiple Deploy Virtual Machine ... === TestName: test_deploy_vm_multiple | Status : SUCCESS ===
ok
Test Stop Virtual Machine ... === TestName: test_01_stop_vm | Status : SUCCESS ===
ok
Test Start Virtual Machine ... === TestName: test_02_start_vm | Status : SUCCESS ===
ok
Test Reboot Virtual Machine ... === TestName: test_03_reboot_vm | Status : SUCCESS ===
ok
Test destroy Virtual Machine ... === TestName: test_06_destroy_vm | Status : SUCCESS ===
ok
Test recover Virtual Machine ... === TestName: test_07_restore_vm | Status : SUCCESS ===
ok
Test migrate VM ... SKIP: At least two hosts should be present in the zone for migration
Test destroy(expunge) Virtual Machine ... === TestName: test_09_expunge_vm | Status : SUCCESS ===
ok
Test Remote Access VPN in VPC ... === TestName: test_vpc_remote_access_vpn | Status : SUCCESS ===
ok
Test VPN in VPC ... === TestName: test_vpc_site2site_vpn | Status : SUCCESS ===
ok
Test to create service offering ... === TestName: test_01_create_service_offering | Status : SUCCESS ===
ok
Test to update existing service offering ... === TestName: test_02_edit_service_offering | Status : SUCCESS ===
ok
Test to delete service offering ... === TestName: test_03_delete_service_offering | Status : SUCCESS ===
ok
Test create VPC offering ... === TestName: test_01_create_vpc_offering | Status : SUCCESS ===
ok
Test VPC offering without load balancing service ... === TestName: test_03_vpc_off_without_lb | Status : SUCCESS ===
ok
Test VPC offering without static NAT service ... === TestName: test_04_vpc_off_without_static_nat | Status : SUCCESS ===
ok
Test VPC offering without port forwarding service ... === TestName: test_05_vpc_off_without_pf | Status : SUCCESS ===
ok
Test VPC offering with invalid services ... === TestName: test_06_vpc_off_invalid_services | Status : SUCCESS ===
ok
Test update VPC offering ... === TestName: test_07_update_vpc_off | Status : SUCCESS ===
ok
Test list VPC offering ... === TestName: test_08_list_vpc_off | Status : SUCCESS ===
ok
test_09_create_redundant_vpc_offering (integration.component.test_vpc_offerings.TestVPCOffering) ... === TestName: test_09_create_redundant_vpc_offering | Status : SUC
CESS ===
ok
```

The error I got was this one:

```
======================================================================
FAIL: test_privategw_acl (integration.smoke.test_privategw_acl.TestPrivateGwACL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/git/cs1/cloudstack/test/integration/smoke/test_privategw_acl.py", line 199, in test_privategw_acl
    self.createPvtGw()
  File "/data/git/cs1/cloudstack/test/integration/smoke/test_privategw_acl.py", line 275, in createPvtGw
    self.fail("Failed to create Private Gateway ==> %s" % e)
AssertionError: Failed to create Private Gateway ==> Execute cmd: createprivategateway failed, due to: errorCode: 530, errorText:None
```

I will re-run the pvt gw test  just to make sure!

Cheers,
Wilder

**Comment by wilderrodrigues** [comment]
@remibergsma and @serbaut 

There might have been some garbage in my environment. I cleaned it up and re-run the test. All fine!

```
test_privategw_acl (integration.smoke.test_privategw_acl.TestPrivateGwACL) ... === TestName: test_privategw_acl | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 1 test in 243.898s

OK
/tmp//MarvinLogs/test_privategw_acl_JLJG18/results.txt (END)
```

I will now run the tests that require hardware.

Cheers,
Wilder

**Comment by wilderrodrigues** [comment]
Ping @serbaut and @remibergsma

Tests results

* Management Server + MySQL on CentOS 7.1
* One KVM host on CentOS 7.1
* ACS Agent + Common RPMs built from source

Three tests failed, but those are irrelevant since the PR #989 which fixes it is not part of this PR.

So, based on all the test done, this PR LGTM :+1: 

```
Test for port forwarding on source NAT ... === TestName: test_01_port_fwd_on_src_nat | Status : SUCCESS ===
ok
Test for port forwarding on non source NAT ... === TestName: test_02_port_fwd_on_non_src_nat | Status : SUCCESS ===
ok
Test for reboot router ... === TestName: test_reboot_router | Status : SUCCESS ===
ok
Test for Router rules for network rules on acquired public IP ... === TestName: test_network_rules_acquired_public_ip_1_static_nat_rule | Status : FAILED ===
FAIL
Test for Router rules for network rules on acquired public IP ... === TestName: test_network_rules_acquired_public_ip_2_nat_rule | Status : FAILED ===
FAIL
Test for Router rules for network rules on acquired public IP ... === TestName: test_network_rules_acquired_public_ip_3_Load_Balancer_Rule | Status : FAILED ===
FAIL
Create a redundant VPC with two networks with two VMs in each network ... === TestName: test_01_create_redundant_VPC_2tiers_4VMs_4IPs_4PF_ACL | Status : SUCCESS ===
ok
Create a redundant VPC with two networks with two VMs in each network and check default routes ... === TestName: test_02_redundant_VPC_default_routes | Status : SUCCESS ===
ok
Test iptables default INPUT/FORWARD policy on RouterVM ... === TestName: test_02_routervm_iptables_policies | Status : SUCCESS ===
ok
Test iptables default INPUT/FORWARD policies on VPC router ... === TestName: test_01_single_VPC_iptables_policies | Status : SUCCESS ===
ok
Create a VPC with two networks with one VM in each network and test nics after destroy ... === TestName: test_01_VPC_nics_after_destroy | Status : SUCCESS ===
ok
Create a VPC with two networks with one VM in each network and test default routes ... === TestName: test_02_VPC_default_routes | Status : SUCCESS ===
ok
Test to verify access to loadbalancer haproxy admin stats page ... === TestName: test02_internallb_haproxy_stats_on_all_interfaces | Status : SUCCESS ===
ok
Test create, assign, remove of an Internal LB with roundrobin http traffic to 3 vm's ... === TestName: test_01_internallb_roundrobin_1VPC_3VM_HTTP_port80 | Status : SUCCESS ===
ok
Stop existing router, add a PF rule and check we can access the VM ... === TestName: test_isolate_network_FW_PF_default_routes | Status : SUCCESS ===
ok
Test redundant router internals ... === TestName: test_RVR_Network_FW_PF_SSH_default_routes | Status : SUCCESS ===
ok
Test SSVM Internals ... === TestName: test_03_ssvm_internals | Status : SUCCESS ===
ok
Test CPVM Internals ... === TestName: test_04_cpvm_internals | Status : SUCCESS ===
ok
Test stop SSVM ... === TestName: test_05_stop_ssvm | Status : SUCCESS ===
ok
Test stop CPVM ... === TestName: test_06_stop_cpvm | Status : SUCCESS ===
ok
Test reboot SSVM ... === TestName: test_07_reboot_ssvm | Status : SUCCESS ===
ok
Test reboot CPVM ... === TestName: test_08_reboot_cpvm | Status : SUCCESS ===
ok
Test destroy SSVM ... === TestName: test_09_destroy_ssvm | Status : SUCCESS ===
ok
Test destroy CPVM ... === TestName: test_10_destroy_cpvm | Status : SUCCESS ===
ok
Test to create Load balancing rule with source NAT ... === TestName: test_01_create_lb_rule_src_nat | Status : SUCCESS ===
ok
Test to create Load balancing rule with non source NAT ... === TestName: test_02_create_lb_rule_non_nat | Status : SUCCESS ===
ok
Test for assign & removing load balancing rule ... === TestName: test_assign_and_removal_lb | Status : SUCCESS ===
ok
```

Cheers,
Wilder

**Comment by wilderrodrigues** [comment]
ping @serbaut @remibergsma 

Can you please do a force push to see if we get Jenkins green? I know is a pain in the ass to depend on Jenkins/Travis that sometimes simply avoids us - believe me, I had the same with my latest PR. However, getting both of them green is kinda cool.

If it fails again after you force push, I will suggest to ignore it and get your PR merged!

Cheers,
Wilder

**Comment by remibergsma** [comment]
@serbaut Will merge when Travis and Jenkins are green.

**Comment by wilderrodrigues** [comment]
@serbaut 

I created a tested to cover your fix! :)

It's on PR #1002 

Cheers,
Wilder

**Comment by serbaut** [comment]
Sorry, been busy. Running tests now.

**Comment by resmo** [comment]
is 4.5 also affected by this issue?

**Comment by serbaut** [comment]
Afaict, the DHCP code is rewritten in 4.6 so this exact issue shouldn't affect 4.5.

**Pull request merged**
