### PR TITLE
Fixup: Optimize getRouterHealthChecksConfig method

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR optimizes the query in getRouterHealthChecksConfig by moving the state filter from for loop to the query itself.

Possibly related issues: #8055 , #8201 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by vishesh92** [comment]
@blueorangutan packge

**Comment by vishesh92** [comment]
@blueorangutan test

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Pull request merged**
