### PR TITLE
CLOUDSTACK-10104:Optimize database transactions in ListDomain API to improve performance

### PR DESCRIPTION
**Pull request by PranaliM**
**Description:**
While creating the response object for the 'listDomain' API, several database calls are triggered to fetch details like parent domain, project limit, IP limit, etc. These database calls are triggered for each record found in the main fetch query, which is causing the response to slow down.

**Fix:**
The database transactions are reduced to improve response of the Listdomain API

### CODE REVIEW

**Comment by mrunalinikankariya** [comment]
Test result

Time taken before fix
2017-10-04 18:43:46,995 DEBUG [c.c.a.ApiServlet] (qtp474210166-23:ctx-ee054a9c) (logid:d4e25726) ===START===  10.11.100.107 -- GET  command=listDomains&response=json&listAll=true&details=min&_=1507104583475
2017-10-04 18:43:47,083 DEBUG [c.c.a.ApiServlet] (qtp474210166-23:ctx-ee054a9c ctx-bd38118f) (logid:d4e25726) ===END===  10.11.100.107 -- GET  command=listDomains&response=json&listAll=true&details=min&_=1507104583475

Time taken : 88ms

Time taken after fix
2017-10-04 20:55:46,401 DEBUG [c.c.a.ApiServlet] (qtp474210166-23:ctx-4213fa41) (logid:55e7c104) ===START===  10.11.100.107 -- GET  command=listDomains&response=json&listAll=true&details=min&_=1507112502766
2017-10-04 20:55:46,450 DEBUG [c.c.a.ApiServlet] (qtp474210166-23:ctx-4213fa41 ctx-dd1b1f51) (logid:55e7c104) ===END===  10.11.100.107 -- GET  command=listDomains&response=json&listAll=true&details=min&_=1507112502766

Time taken :  49ms

With only 20 domains, time taken to get the list of domains is similar. We can find the difference with bulk data.

Test LGTM

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@PranaliM can you fix conflicts?

**Comment by PranaliM** [comment]
I have fixed the conflicts @rhtyd

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by PranaliM** [comment]
@rhtdy, The failing test case is related to fenced HA when host crashes, and is not related to this change related to ListDomain. So do I have an action item on this?

**Comment by rhtyd** [comment]
@PranaliM I'll rekick tests.
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
Tests LGTM, the failure is env related. One more code lgtm is needed to get this merged, additional review requested.

**Comment by rhtyd** [comment]
Merging this based on code reviews and test results.

**Pull request merged**
