### PR TITLE
CLOUDSTACK-9460: For long running transactions, if the connection is

### PR DESCRIPTION
**Pull request by abhinandanprateek**
timed out by the mysql server then refresh it

### CODE REVIEW

**Comment by rhtyd** [comment]
@abhinandanprateek can you reopen/edit the PR for 4.9? thanks.
LGTM. /cc @jburwell @karuturi

**Comment by rhtyd** [comment]
@abhinandanprateek please edit the base branch to 4.9.

**Comment by abhinandanprateek** [comment]
@rhtyd rebased with 4.9

**Comment by rhtyd** [comment]
Thanks @abhinandanprateek LGTM.

**Comment by jburwell** [comment]
@abhinandanprateek this fix seems like it would also be beneficial for 4.8.2.0.  How difficult would it be to re-target it to the 4.8 branch?

**Comment by abhinandanprateek** [comment]
@jburwell should i open a new PR for 4.8 branch ? I think it should be easy and good for 4.8 too.

**Comment by rhtyd** [comment]
@jburwell yes that is possible, @abhinandanprateek please edit the PR and change the base branch, then rebase your PR branch against 4.8 branch.

**Comment by abhinandanprateek** [comment]
@jburwell created a new PR for 4.8 here https://github.com/apache/cloudstack/pull/1674. I was getting many conflicts due to which I decided to create a new PR and cherry picked the  commit.

**Comment by rhtyd** [comment]
@abhinandanprateek since we've a new PR #1674 for 4.8 which would be fwd-merged, this PR can be closed. I've kicked a packaging job.

**Pull request closed without merging**
