### PR TITLE
Fix spelling, word case, duplicate words in code comments only

### PR DESCRIPTION
**Pull request by jbampton**
### Description

This PR cleans up the docs.  Only touched code comments.

A small PR and perhaps we can merge more quickly.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [X] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by jbampton** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]

**Review by sureshanaparti — APPROVED** [review]
lgtm

**Comment by jbampton** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
are you still working on this @jbampton ?

**Comment by jbampton** [comment]
Ready for review @DaanHoogland

**Pull request merged**
