### PR TITLE
router: fix routing table for marked packets

### PR DESCRIPTION
**Pull request by rhtyd**
This fixes python code that applies NAT/address rules. This fixes routing rules based on ip addresses received to ensure that marked packets will have a routing rule. Thereby, this fixes the issue of
public IP NAT access from other VMs in the VPC.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

- Create a VPC and deployed two VMs in a single tier in 10.1.1.1/24, allow_all policy (egress/ingress)
- Added a public IP for the VPC enabled SNAT of that public IP to the VM1, similarly for VM2
- Before the fix, I was unable to SSH from VM1 to VM2's public SNAT IP
- After the fix ssh/ping/access via public IP works

## Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
Testing
- [ ] I have added tests to cover my changes.
- [x] All relevant new and existing integration tests have passed.
- [x] A full integration testsuite with all test that can run on my environment has passed.

@blueorangutan package

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@rafaelweingartner based on @ustcweizhou 's comment, I've updated and tested the code to add routing rules for fwmarked (MARK-ed) packets. This will fix routing issues that you observed in your env.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
Great, thanks for the review and testing @rafaelweingartner

**Comment by ustcweizhou** [comment]
nice, code looks good to me!
not tested yet.

**Comment by DaanHoogland** [comment]
code lgtm, just wondering about the test_04_restart_network_wo_cleanup failures above. looking into the vmware one now

**Comment by DaanHoogland** [comment]
the failure on test_04_restart_network_wo_cleanup is genuine 14 mins uptime instead of <3 mins. I am not sure that logic is valid though. I can not find a timestamp for the start of the test and that would be the real test (had it been restarted since)

**Comment by rhtyd** [comment]
@DaanHoogland I checked `test_04_restart_network_wo_cleanup` and others test failures are not related to this PR, I'm seeing them on 4.11 - https://github.com/apache/cloudstack/pull/2376. The router related failures on xenserver are not seen but not caused by this PR.

I'll go ahead and merge this based on your reviews from Daan, Wei and Rafael and try to address test failures in a separate PR.

**Pull request merged**
