### PR TITLE
Changed test failure to warning

### PR DESCRIPTION
**Pull request by Spaceman1984**
## Description

The test was failing due to a time out, changed it to a warning instead.

Fixes: #4261 

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

This was tested by running the smoke test

### CODE REVIEW

**Comment by Spaceman1984** [comment]
@blueorangutan package

**Comment by Spaceman1984** [comment]
> LGTM, instead of wait and check; could we do something else like wait until and on no output skip?

I'll take a look @rhtyd

**Comment by Spaceman1984** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by rhtyd** [comment]
@Spaceman1984 the `test_02_enableHumanReadableLogs` still failed, can you check and make changes? Thanks.

**Comment by Spaceman1984** [comment]
@rhtyd this looks like another env issue, it's failing to do an http connection.

**Comment by Spaceman1984** [comment]
@blueorangutan package

**Comment by Spaceman1984** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by Spaceman1984** [comment]
@blueorangutan test vmware-67u3

**Comment by Spaceman1984** [comment]
@blueorangutan test vmware-67u3

**Comment by Spaceman1984** [comment]
@blueorangutan test centos7 vmware-67u3

**Pull request merged**
