### PR TITLE
Set version to 4.7.2-SNAPSHOT in 4.7 branch

### PR DESCRIPTION
**Pull request by remibergsma**
After releasing 4.7.1, next version is 4.7.2-SNAPSHOT in 4.7 branch.

### CODE REVIEW

**Comment by remibergsma** [comment]
I'll also add the upgrade paths to this PR

**Comment by remibergsma** [comment]
Tried upgrade from `4.7.1` to `4.7.2` and that was successful:

```
2016-01-26 12:47:32,170 DEBUG [c.c.u.d.VersionDaoImpl] (main:null) (logid:) Checking to see if the database is at a version before it was the version table is created
2016-01-26 12:47:32,196 INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) DB version = 4.7.1 Code Version = 4.7.2-SNAPSHOT
2016-01-26 12:47:32,197 INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Database upgrade must be performed from 4.7.1 to 4.7.2-SNAPSHOT
2016-01-26 12:47:32,197 DEBUG [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Running upgrade Upgrade471to472 to upgrade from 4.7.1-4.7.2 to 4.7.2
2016-01-26 12:47:32,201 DEBUG [c.c.u.s.Script] (main:null) (logid:) Looking for db/schema-471to472.sql in the classpath
2016-01-26 12:47:32,201 DEBUG [c.c.u.s.Script] (main:null) (logid:) System resource: null
2016-01-26 12:47:32,202 DEBUG [c.c.u.s.Script] (main:null) (logid:) Classpath resource: file:/data/git/cs2/cloudstack/client/target/utilities/scripts/db/db/schema-471to472.sql
2016-01-26 12:47:32,202 DEBUG [c.c.u.s.Script] (main:null) (logid:) Absolute path =  /data/git/cs2/cloudstack/client/target/utilities/scripts/db/db/schema-471to472.sql
2016-01-26 12:47:32,203 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- Licensed to the Apache Software Foundation (ASF) under one
2016-01-26 12:47:32,203 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- or more contributor license agreements.  See the NOTICE file
2016-01-26 12:47:32,204 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- distributed with this work for additional information
2016-01-26 12:47:32,204 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- regarding copyright ownership.  The ASF licenses this file
2016-01-26 12:47:32,204 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- to you under the Apache License, Version 2.0 (the
2016-01-26 12:47:32,204 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- "License"); you may not use this file except in compliance
2016-01-26 12:47:32,204 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- with the License.  You may obtain a copy of the License at
2016-01-26 12:47:32,204 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) --
2016-01-26 12:47:32,204 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) --   http://www.apache.org/licenses/LICENSE-2.0
2016-01-26 12:47:32,204 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) --
2016-01-26 12:47:32,204 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- Unless required by applicable law or agreed to in writing,
2016-01-26 12:47:32,204 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- software distributed under the License is distributed on an
2016-01-26 12:47:32,204 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
2016-01-26 12:47:32,204 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- KIND, either express or implied.  See the License for the
2016-01-26 12:47:32,204 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- specific language governing permissions and limitations
2016-01-26 12:47:32,204 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- under the License.
2016-01-26 12:47:32,204 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) --;
2016-01-26 12:47:32,204 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- Schema upgrade from 4.7.1 to 4.7.2;
2016-01-26 12:47:32,204 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) --;
2016-01-26 12:47:32,214 INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Cleaning upgrades because all management server are now at the same version
2016-01-26 12:47:32,216 DEBUG [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Upgrading to version 4.7.2...
2016-01-26 12:47:32,216 INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Cleanup upgrade Upgrade471to472 to upgrade from 4.7.1-4.7.2 to 4.7.2
2016-01-26 12:47:32,217 DEBUG [c.c.u.s.Script] (main:null) (logid:) Looking for db/schema-471to472-cleanup.sql in the classpath
2016-01-26 12:47:32,217 DEBUG [c.c.u.s.Script] (main:null) (logid:) System resource: null
2016-01-26 12:47:32,217 DEBUG [c.c.u.s.Script] (main:null) (logid:) Classpath resource: file:/data/git/cs2/cloudstack/client/target/utilities/scripts/db/db/schema-471to472-cleanup.sql
2016-01-26 12:47:32,217 DEBUG [c.c.u.s.Script] (main:null) (logid:) Absolute path =  /data/git/cs2/cloudstack/client/target/utilities/scripts/db/db/schema-471to472-cleanup.sql
2016-01-26 12:47:32,218 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- Licensed to the Apache Software Foundation (ASF) under one
2016-01-26 12:47:32,218 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- or more contributor license agreements.  See the NOTICE file
2016-01-26 12:47:32,218 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- distributed with this work for additional information
2016-01-26 12:47:32,218 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- regarding copyright ownership.  The ASF licenses this file
2016-01-26 12:47:32,218 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- to you under the Apache License, Version 2.0 (the
2016-01-26 12:47:32,218 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- "License"); you may not use this file except in compliance
2016-01-26 12:47:32,218 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- with the License.  You may obtain a copy of the License at
2016-01-26 12:47:32,218 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) --
2016-01-26 12:47:32,218 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) --   http://www.apache.org/licenses/LICENSE-2.0
2016-01-26 12:47:32,218 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) --
2016-01-26 12:47:32,218 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- Unless required by applicable law or agreed to in writing,
2016-01-26 12:47:32,218 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- software distributed under the License is distributed on an
2016-01-26 12:47:32,218 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
2016-01-26 12:47:32,218 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- KIND, either express or implied.  See the License for the
2016-01-26 12:47:32,218 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- specific language governing permissions and limitations
2016-01-26 12:47:32,218 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- under the License.
2016-01-26 12:47:32,218 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) --;
2016-01-26 12:47:32,218 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- Schema cleanup from 4.7.1 to 4.7.2;
2016-01-26 12:47:32,218 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) --;
2016-01-26 12:47:32,219 DEBUG [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Cleanup script /data/git/cs2/cloudstack/client/target/utilities/scripts/db/db/schema-471to472-cleanup.sql is executed successfully
2016-01-26 12:47:32,233 DEBUG [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Upgrade completed for version 4.7.2
```

**Comment by remibergsma** [comment]
Ping @DaanHoogland @borisroman Please review.

**Comment by pdion891** [comment]
LGTM, it's just a version number change.

**Comment by rafaelweingartner** [comment]
I looked at the changes, just the upgrade of versions.
The PR LGTM

**Pull request merged**
