### PR TITLE
Fix: copy to clipboard console url for safari

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR fixes https://github.com/apache/cloudstack/issues/9368

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by vishesh92** [comment]
@blueorangutan ui

**Comment by vishesh92** [comment]
@blueorangutan ui

**Review by DaanHoogland — APPROVED** [review]
copy works on both FF and Chrome on linux

**Comment by DaanHoogland** [comment]
I suppose you tested on Safari @rohityadavcloud ?

**Comment by rohityadavcloud** [comment]
LGTM, tested OK

**Comment by rohityadavcloud** [comment]
sorry doesn't work @vishesh92 cc @DaanHoogland

**Comment by vishesh92** [comment]
Covered in https://github.com/apache/cloudstack/pull/9381/

**Pull request closed without merging**
