### PR TITLE
API: Fix listing Userdata by keyword or name

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

This PR fixes https://github.com/apache/cloudstack/issues/9686 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### CODE REVIEW

**Review by rohityadavcloud — APPROVED** [review]

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test keepEnv

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Review by DaanHoogland — CHANGES_REQUESTED** [review]
code looks good, but testing doesn't yield good results. need to look further

**Comment by DaanHoogland** [comment]
> code looks good, but testing doesn't yield good results. need to look further

seems to have been me :( test ok :)

**Pull request merged**
