### PR TITLE
Adding Datastore cluster as primary storage should check if the child datastores are in Up state

### PR DESCRIPTION
**Pull request by harikrishna-patnala**
### Description
This fix ensures when datastore cluster in VMware is added as a primary storage pool in CloudStack then all the child datastores (which already exists in CS) should be in Up state.

For example:

1. Datastore Cluster DS has two child datastores A and B in vCenter. (B is already added as a storage pool in CloudStack)
2. Now try to add datastore cluster DS into CloudStack as a primary storage pool
3. CloudStack tries to add child datastores A and B in CloudStack, since B is already there in CloudStack, it will reuse the existing storagepool entry and will keep under parent Storage pool DS.

During Step 3 we are now checking if B is Up state or not.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Review by rajujith — APPROVED** [review]
Validated the fix by adding a datastore cluster with a child datastore with maintenance mode in the cloudstack, the operation fails. LGTM. 

```
com.cloud.utils.exception.CloudRuntimeException: Cannot synchronise datastore cluster 0c0b5ce3-8912-3d7f-939a-5dea18228df7 because primary storage with id 51aca5e9-f22a-3a53-b2e9-03d83ca7088c is not in Up state, current state is Maintenance
        at com.cloud.storage.StorageManagerImpl.validateChildDatastoresToBeAddedInUpState(StorageManagerImpl.java:1909)
```

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Pull request merged**
