### PR TITLE
KVM: Fix plugging ip addresses to the wrong interface

### PR DESCRIPTION
**Pull request by remibergsma**
Fix for KVM, where the public ip would be added to the guest network. Reason is because it used 'broadcastUrl' as an index, which turned out not to be unique in all cases and was overwritten. This resulted in the public ip address being added to the wrong interface (see screenshots).

Problem:
kvm-wrong-interface-1

After patch:
kvm-wrong-interface-2

The `192.168.23.0/24` range is used as 'public' in this lab.

### CODE REVIEW

**Comment by kiwiflyer** [comment]
Strangely enough, I just ran into this problem yesterday.I'll pull it in. Thanks Remi!

**Comment by remibergsma** [comment]
Jenkins error says: `Unable to instrument project`, seems like a workspace issue or such.

**Comment by remibergsma** [comment]
This time around Jenkins is happy and Travis times out :-s
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

**Comment by remibergsma** [comment]
Force pushed a final time, else I give up on this.

**Comment by remibergsma** [comment]
@kiwiflyer Sorry but this seems to have issues. We run this in prod with Cosmic but apparently some other patch is missing here in order for this to work properly. Unfortunately I have no more time to work on this now.

**Comment by ustcweizhou** [comment]
this does not work for me as well.
If there are multiple public interfaces in the VR, only the last one works.

**Pull request closed without merging**
