### PR TITLE
Refactoring to remove duplicate code (by Frank/Nuage)

### PR DESCRIPTION
**Pull request by rhtyd**
The https://github.com/apache/cloudstack/pull/3537 would revert the merged PR #3152 as we're close to 4.13 RC1 and have low confidence on what other regressions it might add. This simply re-creates PR #3152 using the same source fork/branch. We can work on this PR and attempt again to merge towards 4.14 after fixing discovered regressions and a more thorough review and testing.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by rhtyd** [comment]
@fmaximus please see https://github.com/apache/cloudstack/pull/3537, we'll need to revert your PR #3152 for this purpose I've reopened your PR from the original branch. Kindly help test and fix regressions discovered in your branch, esp around registration and upload of archived templates and iso (templates/isos that are extractable liike *.bz2, *gz etc).

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@fmaximus thanks for self assigning, can you help fix the conflict? I'll try and help you to get this merge now that master is not frozen anymore.

**Comment by fmaximus** [comment]
@rhtyd Conflict is resolved.
Jenkins build has failed due to some build node issues: 
`FATAL: Couldn't find any executable in /home/jenkins/tools/maven/apache-maven-3.3.3`

**Comment by rhtyd** [comment]
Thanks @fmaximus I'll kick a build
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
(el6 failure expected)
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by svenvogel** [comment]
@fmaximus @rhtyd does this also remove this global settings?

image

**Comment by fmaximus** [comment]
@svenvogel No, that's not part of it. This was a change I had been working on, 
which I still wanted to offer the community.

**Comment by svenvogel** [comment]
@fmaximus thanks for answer. will this removed from you in a seperated PR or should the community track this?

**Comment by fmaximus** [comment]
@svenvogel That should go in a separate PR for sure, as it's a bugfix which should be fixed in the same release as Remove Nuage Plugin.

**Comment by rhtyd** [comment]
CentOS7 job failed, rekicking
@blueorangutan test

**Comment by rhtyd** [comment]
LGTM, tests LGTM as well. Using lgtms from the original PR, merging this.

**Pull request merged**
