### PR TITLE
Add Service Ip to listManagementServers API response

### PR DESCRIPTION
**Pull request by kishankavala**
### Description

This PR fixes # https://github.com/apache/cloudstack/issues/7338
Added Mgmt server Service IP to listManagementServers API response

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### How Has This Been Tested?
Test API response with cmk

```
(local) 🐱 > list managementservers
{
  "count": 1,
  "managementserver": [
    {
      "id": "76942b7f-00cc-4ff6-89ec-0d16bdcf2919",
      "javadistribution": "Ubuntu",
      "javaversion": "11.0.18+10-post-Ubuntu-0ubuntu122.04",
      "lastboottime": "2023-03-25T18:14:53+0530",
      "lastserverstart": "2023-03-28T14:10:19+0530",
      "lastserverstop": "2023-03-28T14:02:23+0530",
      "name": "KK.",
      "osdistribution": "Ubuntu 22.04.1 LTS",
      "serviceip": "127.0.0.1",
      "state": "Up",
      "version": "4.18.1.0-SNAPSHOT"
    }
  ]
}
```

### CODE REVIEW

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by harikrishna-patnala — APPROVED** [review]
verified it locally. LGTM

(localcloud) 🐱 > list managementservers
{
  "count": 1,
  "managementserver": [
    {
      "id": "b35efde0-355c-438d-a6ea-bcbd80c780be",
      "javadistribution": "Red Hat, Inc.",
      "javaversion": "11.0.18+10-LTS",
      "lastboottime": "2023-03-23T16:05:25+0000",
      "lastserverstart": "2023-03-28T10:57:44+0000",
      "lastserverstop": "2023-03-27T10:49:57+0000",
      "name": "ref-trl-4713-k-M7-harikrishna-patnala-mgmt1.shapeblue.com",
      "osdistribution": "CentOS Linux 7 (Core)",
      "serviceip": "10.0.x.y",
      "state": "Up",
      "version": "4.19.0.0-SNAPSHOT"
    }
  ]
}

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Comment by vishesh92** [comment]
Checking this PR in a bit

**Review by kiranchavala — APPROVED** [review]
Tested the build, The api call is working fine LGTM

(cmk) 🐱 > list managementservers 
{
  "count": 2,
  "managementserver": [
    {
      "id": "c752ddd8-fa57-420f-9672-a5f54ba1003c",
      "javadistribution": "Red Hat, Inc.",
      "javaversion": "11.0.18+10-LTS",
      "lastboottime": "2023-03-29T00:01:34+0000",
      "lastserverstart": "2023-03-29T12:08:31+0000",
      "lastserverstop": "2023-03-29T12:08:29+0000",
      "name": "pr7374-t6333-kvm-centos7-mgmt1.sofia.shapeblue.com",
      "osdistribution": "CentOS Linux 7 (Core)",
      "serviceip": "10.0.33.218",
      "state": "Up",
      "version": "4.18.1.0-SNAPSHOT"
    },
    {
      "id": "6ee9efd6-f57a-4252-8307-2fed851b8c92",
      "javadistribution": "Red Hat, Inc.",
      "javaversion": "11.0.18+10-LTS",
      "lastboottime": "2023-03-29T00:02:00+0000",
      "lastserverstart": "2023-03-29T12:08:31+0000",
      "lastserverstop": "2023-03-29T12:08:29+0000",
      "name": "pr7374-t6333-kvm-centos7-mgmt2.sofia.shapeblue.com",
      "osdistribution": "CentOS Linux 7 (Core)",
      "serviceip": "10.0.35.124",
      "state": "Up",
      "version": "4.18.1.0-SNAPSHOT"
    }
  ]
}

**Comment by weizhouapache** [comment]
merging based on 3 approvals and 2 manual testing

**Pull request merged**
