### PR TITLE
Improve logs when searching one storage pool to allocate a new volume

### PR DESCRIPTION
**Pull request by SadiJr**
### Description

The process of searching a storage pool to allocate a new volume does not have enough logs for effective troubleshooting. Thus, new logs were added in this process, aiming to facilitate future troubleshooting.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### How Has This Been Tested?
It was tested in a local lab:

1. I deployed new VMs, and also created new datadisks and attached to this VMs;
2. I read the logs to see if they were improved;
3. Before, the logs did not have enough information to perform an efficient troubleshooting;
4. Now, with improved logs, the troubleshooting will be easier.

### CODE REVIEW

**Review by stephankruggg — APPROVED** [review]
CLGTM, not manually tested

**Comment by kiranchavala** [comment]
@SadiJr 

Could you please provide a sample snippet of the new improved logs so that i can verify it.

**Comment by SadiJr** [comment]
> @SadiJr
> 
> Could you please provide a sample snippet of the new improved logs so that i can verify it.

@kiranchavala sorry for the delay to answer you, sure I can provide some samples:

```log
2023-08-21 11:15:21,778 DEBUG [c.c.d.DeploymentPlanningManagerImpl] (API-Job-Executor-17:ctx-e7a47918 job-7326 ctx-5edada67) (logid:c4f1b70c) Trying to find suitable pools to allocate volume [29013bb4-c675-4e7b-ad2a-c782d0982b20] necessary to deploy VM [8a6c342c-e34c-4579-b5cb-15c254bddd50], using StoragePoolAllocator: [LocalStoragePoolAllocator].
2023-08-21 11:15:21,783 DEBUG [o.a.c.s.a.AbstractStoragePoolAllocator] (API-Job-Executor-17:ctx-e7a47918 job-7326 ctx-5edada67) (logid:c4f1b70c) Checking if storage pool [{"name":"datastore.201","uuid":"93dd766c21904b4cb58e8aa958a06bb2"}] is suitable to disk [DskChr[ROOT|21474836480|]].
2023-08-21 11:15:21,787 DEBUG [c.c.s.StorageManagerImpl] (API-Job-Executor-17:ctx-e7a47918 job-7326 ctx-5edada67) (logid:c4f1b70c) Volume [Vol[873|name=ROOT-874|vm=874|ROOT]] is not allocated to any pool. Cannot check compatibility with pool [{"name":"datastore.201","uuid":"93dd766c21904b4cb58e8aa958a06bb2"}].
2023-08-21 11:15:21,793 INFO  [c.c.s.StorageManagerImpl] (API-Job-Executor-17:ctx-e7a47918 job-7326 ctx-5edada67) (logid:c4f1b70c) Storage pool datastore.201 (11) does not supply IOPS capacity, assuming enough capacity
2023-08-21 11:15:21,796 DEBUG [c.c.s.StorageManagerImpl] (API-Job-Executor-17:ctx-e7a47918 job-7326 ctx-5edada67) (logid:c4f1b70c) Checking pool 11 for storage, totalSize: 590021132288, usedBytes: 5811208192, usedPct: 0.009849152638762512, disable threshold: 0.85
2023-08-21 11:15:21,796 DEBUG [c.c.s.StorageManagerImpl] (API-Job-Executor-17:ctx-e7a47918 job-7326 ctx-5edada67) (logid:c4f1b70c) Destination pool id: 11
2023-08-21 11:15:21,818 DEBUG [c.c.s.StorageManagerImpl] (API-Job-Executor-17:ctx-e7a47918 job-7326 ctx-5edada67) (logid:c4f1b70c) Pool ID for the volume with ID 873 is null
2023-08-21 11:15:21,824 DEBUG [c.c.s.StorageManagerImpl] (API-Job-Executor-17:ctx-e7a47918 job-7326 ctx-5edada67) (logid:c4f1b70c) Found storage pool datastore.201 of type VMFS with overprovisioning factor 2
2023-08-21 11:15:21,824 DEBUG [c.c.s.StorageManagerImpl] (API-Job-Executor-17:ctx-e7a47918 job-7326 ctx-5edada67) (logid:c4f1b70c) Total over provisioned capacity calculated is 2 * (549.50 GB) 590021132288
2023-08-21 11:15:21,825 DEBUG [c.c.s.StorageManagerImpl] (API-Job-Executor-17:ctx-e7a47918 job-7326 ctx-5edada67) (logid:c4f1b70c) Total capacity of the pool datastore.201 with ID 11 is (1.0732 TB) 1180042264576
2023-08-21 11:15:21,826 DEBUG [c.c.s.StorageManagerImpl] (API-Job-Executor-17:ctx-e7a47918 job-7326 ctx-5edada67) (logid:c4f1b70c) Checking pool: 11 for storage allocation , maxSize : (1.0732 TB) 1180042264576, totalAllocatedSize : (24.88 GB) 26717716480, askingSize : (20.00 GB) 21474836480, allocated disable threshold: 0.85
2023-08-21 11:15:21,826 DEBUG [o.a.c.s.a.LocalStoragePoolAllocator] (API-Job-Executor-17:ctx-e7a47918 job-7326 ctx-5edada67) (logid:c4f1b70c) Found suitable local storage pool [Pool[11|VMFS]] to allocate disk [DskChr[ROOT|21474836480|]] to it, adding to list.
2023-08-21 11:15:21,827 DEBUG [o.a.c.s.a.AbstractStoragePoolAllocator] (API-Job-Executor-17:ctx-e7a47918 job-7326 ctx-5edada67) (logid:c4f1b70c) Checking if storage pool [{"name":"datastore.200","uuid":"2ba84f326b2e36c8a0f3ce298558b23a"}] is suitable to disk [DskChr[ROOT|21474836480|]].
2023-08-21 11:15:21,829 DEBUG [c.c.s.StorageManagerImpl] (API-Job-Executor-17:ctx-e7a47918 job-7326 ctx-5edada67) (logid:c4f1b70c) Volume [Vol[873|name=ROOT-874|vm=874|ROOT]] is not allocated to any pool. Cannot check compatibility with pool [{"name":"datastore.200","uuid":"2ba84f326b2e36c8a0f3ce298558b23a"}].
2023-08-21 11:15:21,831 INFO  [c.c.s.StorageManagerImpl] (API-Job-Executor-17:ctx-e7a47918 job-7326 ctx-5edada67) (logid:c4f1b70c) Storage pool datastore.200 (12) does not supply IOPS capacity, assuming enough capacity
2023-08-21 11:15:21,832 DEBUG [c.c.s.StorageManagerImpl] (API-Job-Executor-17:ctx-e7a47918 job-7326 ctx-5edada67) (logid:c4f1b70c) Checking pool 12 for storage, totalSize: 590021132288, usedBytes: 96072630272, usedPct: 0.16282913444040037, disable threshold: 0.85
2023-08-21 11:15:21,832 DEBUG [c.c.s.StorageManagerImpl] (API-Job-Executor-17:ctx-e7a47918 job-7326 ctx-5edada67) (logid:c4f1b70c) Destination pool id: 12
2023-08-21 11:15:21,838 DEBUG [c.c.s.StorageManagerImpl] (API-Job-Executor-17:ctx-e7a47918 job-7326 ctx-5edada67) (logid:c4f1b70c) Pool ID for the volume with ID 873 is null
2023-08-21 11:15:21,842 DEBUG [c.c.s.StorageManagerImpl] (API-Job-Executor-17:ctx-e7a47918 job-7326 ctx-5edada67) (logid:c4f1b70c) Found storage pool datastore.200 of type VMFS with overprovisioning factor 2
2023-08-21 11:15:21,842 DEBUG [c.c.s.StorageManagerImpl] (API-Job-Executor-17:ctx-e7a47918 job-7326 ctx-5edada67) (logid:c4f1b70c) Total over provisioned capacity calculated is 2 * (549.50 GB) 590021132288
2023-08-21 11:15:21,842 DEBUG [c.c.s.StorageManagerImpl] (API-Job-Executor-17:ctx-e7a47918 job-7326 ctx-5edada67) (logid:c4f1b70c) Total capacity of the pool datastore.200 with ID 12 is (1.0732 TB) 1180042264576
2023-08-21 11:15:21,843 DEBUG [c.c.s.StorageManagerImpl] (API-Job-Executor-17:ctx-e7a47918 job-7326 ctx-5edada67) (logid:c4f1b70c) Checking pool: 12 for storage allocation , maxSize : (1.0732 TB) 1180042264576, totalAllocatedSize : (64.88 GB) 69667389440, askingSize : (20.00 GB) 21474836480, allocated disable threshold: 0.85
2023-08-21 11:15:21,843 DEBUG [o.a.c.s.a.LocalStoragePoolAllocator] (API-Job-Executor-17:ctx-e7a47918 job-7326 ctx-5edada67) (logid:c4f1b70c) Found suitable local storage pool [Pool[12|VMFS]] to allocate disk [DskChr[ROOT|21474836480|]] to it, adding to list.
2023-08-21 11:15:21,844 DEBUG [o.a.c.s.a.AbstractStoragePoolAllocator] (API-Job-Executor-17:ctx-e7a47918 job-7326 ctx-5edada67) (logid:c4f1b70c) LocalStoragePoolAllocator is returning [2] suitable storage pools [[{"name":"datastore.201","uuid":"93dd766c21904b4cb58e8aa958a06bb2"}, {"name":"datastore.200","uuid":"2ba84f326b2e36c8a0f3ce298558b23a"}]].
2023-08-21 11:15:21,845 DEBUG [c.c.d.DeploymentPlanningManagerImpl] (API-Job-Executor-17:ctx-e7a47918 job-7326 ctx-5edada67) (logid:c4f1b70c) StoragePoolAllocator [LocalStoragePoolAllocator] find 2 suitable pools to allocate volume [29013bb4-c675-4e7b-ad2a-c782d0982b20] necessary to deploy VM [8a6c342c-e34c-4579-b5cb-15c254bddd50].
2023-08-21 11:15:23,037 DEBUG [c.c.d.DeploymentPlanningManagerImpl] (Work-Job-Executor-26:ctx-a4f3804e job-7326/job-7327 ctx-9cf60e64) (logid:c4f1b70c) Trying to find suitable pools to allocate volume [29013bb4-c675-4e7b-ad2a-c782d0982b20] necessary to deploy VM [8a6c342c-e34c-4579-b5cb-15c254bddd50], using StoragePoolAllocator: [LocalStoragePoolAllocator].
2023-08-21 11:15:23,041 DEBUG [o.a.c.s.a.AbstractStoragePoolAllocator] (Work-Job-Executor-26:ctx-a4f3804e job-7326/job-7327 ctx-9cf60e64) (logid:c4f1b70c) Checking if storage pool [{"name":"datastore.200","uuid":"2ba84f326b2e36c8a0f3ce298558b23a"}] is suitable to disk [DskChr[ROOT|21474836480|]].
2023-08-21 11:15:23,042 DEBUG [c.c.s.StorageManagerImpl] (Work-Job-Executor-26:ctx-a4f3804e job-7326/job-7327 ctx-9cf60e64) (logid:c4f1b70c) Volume [Vol[873|name=ROOT-874|vm=874|ROOT]] is not allocated to any pool. Cannot check compatibility with pool [{"name":"datastore.200","uuid":"2ba84f326b2e36c8a0f3ce298558b23a"}].
2023-08-21 11:15:23,045 INFO  [c.c.s.StorageManagerImpl] (Work-Job-Executor-26:ctx-a4f3804e job-7326/job-7327 ctx-9cf60e64) (logid:c4f1b70c) Storage pool datastore.200 (12) does not supply IOPS capacity, assuming enough capacity
2023-08-21 11:15:23,047 DEBUG [c.c.s.StorageManagerImpl] (Work-Job-Executor-26:ctx-a4f3804e job-7326/job-7327 ctx-9cf60e64) (logid:c4f1b70c) Checking pool 12 for storage, totalSize: 590021132288, usedBytes: 96072630272, usedPct: 0.16282913444040037, disable threshold: 0.85
2023-08-21 11:15:23,047 DEBUG [c.c.s.StorageManagerImpl] (Work-Job-Executor-26:ctx-a4f3804e job-7326/job-7327 ctx-9cf60e64) (logid:c4f1b70c) Destination pool id: 12
2023-08-21 11:15:23,054 DEBUG [c.c.s.StorageManagerImpl] (Work-Job-Executor-26:ctx-a4f3804e job-7326/job-7327 ctx-9cf60e64) (logid:c4f1b70c) Pool ID for the volume with ID 873 is null
2023-08-21 11:15:23,058 DEBUG [c.c.s.StorageManagerImpl] (Work-Job-Executor-26:ctx-a4f3804e job-7326/job-7327 ctx-9cf60e64) (logid:c4f1b70c) Found storage pool datastore.200 of type VMFS with overprovisioning factor 2
2023-08-21 11:15:23,058 DEBUG [c.c.s.StorageManagerImpl] (Work-Job-Executor-26:ctx-a4f3804e job-7326/job-7327 ctx-9cf60e64) (logid:c4f1b70c) Total over provisioned capacity calculated is 2 * (549.50 GB) 590021132288
2023-08-21 11:15:23,058 DEBUG [c.c.s.StorageManagerImpl] (Work-Job-Executor-26:ctx-a4f3804e job-7326/job-7327 ctx-9cf60e64) (logid:c4f1b70c) Total capacity of the pool datastore.200 with ID 12 is (1.0732 TB) 1180042264576
2023-08-21 11:15:23,060 DEBUG [c.c.s.StorageManagerImpl] (Work-Job-Executor-26:ctx-a4f3804e job-7326/job-7327 ctx-9cf60e64) (logid:c4f1b70c) Checking pool: 12 for storage allocation , maxSize : (1.0732 TB) 1180042264576, totalAllocatedSize : (64.88 GB) 69667389440, askingSize : (20.00 GB) 21474836480, allocated disable threshold: 0.85
2023-08-21 11:15:23,060 DEBUG [o.a.c.s.a.LocalStoragePoolAllocator] (Work-Job-Executor-26:ctx-a4f3804e job-7326/job-7327 ctx-9cf60e64) (logid:c4f1b70c) Found suitable local storage pool [Pool[12|VMFS]] to allocate disk [DskChr[ROOT|21474836480|]] to it, adding to list.
2023-08-21 11:15:23,060 DEBUG [o.a.c.s.a.AbstractStoragePoolAllocator] (Work-Job-Executor-26:ctx-a4f3804e job-7326/job-7327 ctx-9cf60e64) (logid:c4f1b70c) LocalStoragePoolAllocator is returning [1] suitable storage pools [[{"name":"datastore.200","uuid":"2ba84f326b2e36c8a0f3ce298558b23a"}]].
2023-08-21 11:15:23,061 DEBUG [c.c.d.DeploymentPlanningManagerImpl] (Work-Job-Executor-26:ctx-a4f3804e job-7326/job-7327 ctx-9cf60e64) (logid:c4f1b70c) StoragePoolAllocator [LocalStoragePoolAllocator] find 1 suitable pools to allocate volume [29013bb4-c675-4e7b-ad2a-c782d0982b20] necessary to deploy VM [8a6c342c-e34c-4579-b5cb-15c254bddd50].
```

Please tell me if you need more information.

**Review by JoaoJandre — APPROVED** [review]
CLGTM, these will help troubleshooting a lot

**Comment by kiranchavala** [comment]
@blueorangutan package

**Review by kiranchavala — APPROVED** [review]
LGTM, Tested it manually and found the log messages are improved. the storage pool name and uuid is included in the logs 


Before the fix

```
2023-09-28 11:21:30,104 DEBUG [o.a.c.s.a.LocalStoragePoolAllocator] (API-Job-Executor-22:ctx-f48de3b6 job-714 ctx-8ccf0016) (logid:87badcb9) LocalStoragePoolAllocator is returning null since the disk profile does not use local storage and bypassStorageTypeCheck is false.
2023-09-28 11:21:30,104 DEBUG [o.a.c.s.a.ClusterScopeStoragePoolAllocator] (API-Job-Executor-22:ctx-f48de3b6 job-714 ctx-8ccf0016) (logid:87badcb9) Looking for pools in dc [1], pod [1] and cluster [1]. Disabled pools will be ignored.
2023-09-28 11:21:30,105 DEBUG [o.a.c.s.a.ClusterScopeStoragePoolAllocator] (API-Job-Executor-22:ctx-f48de3b6 job-714 ctx-8ccf0016) (logid:87badcb9) Found pools [[Pool[1|NetworkFilesystem]]] that match with tags [[]].
2023-09-28 11:21:30,105 DEBUG [o.a.c.s.a.AbstractStoragePoolAllocator] (API-Job-Executor-22:ctx-f48de3b6 job-714 ctx-8ccf0016) (logid:87badcb9) Checking if storage pool is suitable, name: ref-trl-5653-k-M7-kiran-chavala-kvm-pri1 ,poolId: 1
2023-09-28 11:21:30,106 INFO  [c.c.s.StorageManagerImpl] (API-Job-Executor-22:ctx-f48de3b6 job-714 ctx-8ccf0016) (logid:87badcb9) Storage pool ref-trl-5653-k-M7-kiran-chavala-kvm-pri1 (1) does not supply IOPS capacity, assuming enough capacity
2023-09-28 11:21:30,107 DEBUG [c.c.s.StorageManagerImpl] (API-Job-Executor-22:ctx-f48de3b6 job-714 ctx-8ccf0016) (logid:87badcb9) Checking pool 1 for storage, totalSize: 2197949513728, usedBytes: 1165863419904, usedPct: 0.5304323018441622, disable threshold: 0.95
2023-09-28 11:21:30,107 DEBUG [c.c.s.StorageManagerImpl] (API-Job-Executor-22:ctx-f48de3b6 job-714 ctx-8ccf0016) (logid:87badcb9) Destination pool id: 1
2023-09-28 11:21:30,113 DEBUG [c.c.s.StorageManagerImpl] (API-Job-Executor-22:ctx-f48de3b6 job-714 ctx-8ccf0016) (logid:87badcb9) Pool ID for the volume with ID 57 is null
2023-09-28 11:21:30,115 DEBUG [c.c.s.StorageManagerImpl] (API-Job-Executor-22:ctx-f48de3b6 job-714 ctx-8ccf0016) (logid:87badcb9) Found storage pool ref-trl-5653-k-M7-kiran-chavala-kvm-pri1 of type NetworkFilesystem with overprovisioning factor 2
2023-09-28 11:21:30,115 DEBUG [c.c.s.StorageManagerImpl] (API-Job-Executor-22:ctx-f48de3b6 job-714 ctx-8ccf0016) (logid:87badcb9) Total over provisioned capacity calculated is 2 * (1.9990 TB) 2197949513728
2023-09-28 11:21:30,115 DEBUG [c.c.s.StorageManagerImpl] (API-Job-Executor-22:ctx-f48de3b6 job-714 ctx-8ccf0016) (logid:87badcb9) Total capacity of the pool ref-trl-5653-k-M7-kiran-chavala-kvm-pri1 with ID 1 is (3.9980 TB) 4395899027

```




After the fix 


```
2023-09-28 11:25:58,229 DEBUG [c.c.d.DeploymentPlanningManagerImpl] (API-Job-Executor-27:ctx-36c13530 job-31 ctx-8d381d6f) (logid:b79c25c2) Calling StoragePoolAllocators to find suitable pools
2023-09-28 11:25:58,230 DEBUG [o.a.c.s.a.LocalStoragePoolAllocator] (API-Job-Executor-27:ctx-36c13530 job-31 ctx-8d381d6f) (logid:b79c25c2) LocalStoragePoolAllocator is returning null since the disk profile does not use local storage and bypassStorageTypeCheck is false.
2023-09-28 11:25:58,231 DEBUG [o.a.c.s.a.ClusterScopeStoragePoolAllocator] (API-Job-Executor-27:ctx-36c13530 job-31 ctx-8d381d6f) (logid:b79c25c2) Looking for pools in dc [1], pod [1] and cluster [1]. Disabled pools will be ignored.
2023-09-28 11:25:58,232 DEBUG [o.a.c.s.a.ClusterScopeStoragePoolAllocator] (API-Job-Executor-27:ctx-36c13530 job-31 ctx-8d381d6f) (logid:b79c25c2) Found pools [[Pool[2|NetworkFilesystem], Pool[3|NetworkFilesystem]]] that match with tags [[]].
2023-09-28 11:25:58,233 DEBUG [o.a.c.s.a.AbstractStoragePoolAllocator] (API-Job-Executor-27:ctx-36c13530 job-31 ctx-8d381d6f) (logid:b79c25c2) Checking if storage pool [{"name":"ref-trl-5739-k-M7-kiran-chavala-kvm-pri1","uuid":"374453df-869e-3530-9ec1-a0c23a7917fd"}] is suitable to disk [DskChr[ROOT|8589934592|]].

2023-09-28 11:25:58,234 DEBUG [c.c.s.StorageManagerImpl] (API-Job-Executor-27:ctx-36c13530 job-31 ctx-8d381d6f) (logid:b79c25c2) Volume [Vol[3|name=ROOT-3|vm=3|ROOT]] is not allocated to any pool. Cannot check compatibility with pool [{"name":"ref-trl-5739-k-M7-kiran-chavala-kvm-pri1","uuid":"374453df-869e-3530-9ec1-a0c23a7917fd"}].
2023-09-28 11:25:58,234 INFO  [c.c.s.StorageManagerImpl] (API-Job-Executor-27:ctx-36c13530 job-31 ctx-8d381d6f) (logid:b79c25c2) Storage pool ref-trl-5739-k-M7-kiran-chavala-kvm-pri1 (2) does not supply IOPS capacity, assuming enough capacity
2023-09-28 11:25:58,235 DEBUG [c.c.s.StorageManagerImpl] (API-Job-Executor-27:ctx-36c13530 job-31 ctx-8d381d6f) (logid:b79c25c2) Checking pool 2 for storage, totalSize: 2197949513728, usedBytes: 1171369492480, usedPct: 0.5329373969528578, disable threshold: 0.95
2023-09-28 11:25:58,235 DEBUG [c.c.s.StorageManagerImpl] (API-Job-Executor-27:ctx-36c13530 job-31 ctx-8d381d6f) (logid:b79c25c2) Destination pool id: 2
2023-09-28 11:25:58,241 DEBUG [c.c.s.StorageManagerImpl] (API-Job-Executor-27:ctx-36c13530 job-31 ctx-8d381d6f) (logid:b79c25c2) Pool ID for the volume with ID 3 is null
2023-09-28 11:25:58,243 DEBUG [c.c.s.StorageManagerImpl] (API-Job-Executor-27:ctx-36c13530 job-31 ctx-8d381d6f) (logid:b79c25c2) Found storage pool ref-trl-5739-k-M7-kiran-chavala-kvm-pri1 of type NetworkFilesystem with overprovisioning factor 2
2023-09-28 11:25:58,243 DEBUG [c.c.s.StorageManagerImpl] (API-Job-Executor-27:ctx-36c13530 job-31 ctx-8d381d6f) (logid:b79c25c2) Total over provisioned capacity calculated is 2 * (1.9990 TB) 2197949513728
2023-09-28 11:25:58,243 DEBUG [c.c.s.StorageManagerImpl] (API-Job-Executor-27:ctx-36c13530 job-31 ctx-8d381d6f) (logid:b79c25c2) Total capacity of the pool ref-trl-5739-k-M7-kiran-chavala-kvm-pri1 with ID 2 is (3.9980 TB) 4395899027456
```

**Pull request merged**
