### PR TITLE
Add e2e tests for listing resources

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR adds e2e tests for listing resources

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
tests look good, just the UI build failed, which is unrelated (annoying though)

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan test

**Comment by rohityadavcloud** [comment]
@blueorangutan ui

**Comment by vishesh92** [comment]
@blueorangutan help

**Comment by vishesh92** [comment]
@blueorangutan test keepEnv

**Comment by vishesh92** [comment]
@blueorangutan test keepEnv

**Comment by vishesh92** [comment]
@blueorangutan test keepEnv

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan test

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan test keepEnv

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@shwstppr This PR only contains changes in tests. Can we have this PR in 4.19.0?

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Review by shwstppr — APPROVED** [review]
LGT, only test related change

**Comment by DaanHoogland** [comment]
@blueorangutan test alma9 vmware-70u3

**Comment by weizhouapache** [comment]
@blueorangutan test matrix

**Comment by shwstppr** [comment]
@vishesh92 similar failures in VMware test results. Anything related?

**Comment by vishesh92** [comment]
> @vishesh92 similar failures in VMware test results. Anything related?

No. It doesn't have anything related to my changes.

**Comment by vishesh92** [comment]
@shwstppr I checked a few failures and most of them seem related to the environment itself or some error while cleaning up resources.

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
> > @vishesh92 similar failures in VMware test results. Anything related?
> 
> No. It doesn't have anything related to my changes.

Considering the current smoke tests are mostly very stable (based on the results of health check PRs), can we revisit this after 4.19 release ?
@shwstppr @vishesh92

**Comment by vishesh92** [comment]
@blueorangutan test matrix

**Comment by vishesh92** [comment]
> > > @vishesh92 similar failures in VMware test results. Anything related?
> > 
> > 
> > No. It doesn't have anything related to my changes.
> 
> Considering the current smoke tests are mostly very stable (based on the results of health check PRs), can we revisit this after 4.19 release ? @shwstppr @vishesh92

@weizhouapache Just rebuilt the packages again. Last time there was some issues while packaging. Let's wait again for the results after packaging.

**Comment by weizhouapache** [comment]
smoke tests look ok. the failures might be caused by the busy trillian envs.

**Comment by weizhouapache** [comment]
@blueorangutan LLtest matrix

**Comment by shwstppr** [comment]
Based on a discussion with contributors involved in https://github.com/apache/cloudstack/pull/8392, I'm reverting this for now. We will revisit e2e tests later

**Pull request merged**
