### PR TITLE
CLOUDSTACK-9695: VM snapshot is disabled if the VM Instance is off

### PR DESCRIPTION
**Pull request by rashmidixit**
Refer to [CLOUDSTACK-9695](https://issues.apache.org/jira/browse/CLOUDSTACK-9695) for more details.

### CODE REVIEW

**Comment by rashmidixit** [comment]
As part of this fix, added a new property called "isDisabled" for a field in a dialog. If this function returns true, then the field will be disabled.

**Comment by rhtyd** [comment]
@rashmidixit change the PR's base branch to 4.9 please.

**Comment by rashmidixit** [comment]
@rhtyd This is a minor improvement and hence in master. I have updated the corresponding bugs' fix version.

**Comment by koushik-das** [comment]
@rashmidixit Code LGTM. Please provide screenshots of the changes.

**Comment by ustcweizhou** [comment]
why not change vmActionfilter in ui/scripts/instances.js ?
it will be much simple.

**Comment by rashmidixit** [comment]
@ustcweizhou The reason for not putting this in vmActionFilter is that the snapshot action itself is allowed when a VM is shut down. We only want to disable the option for memory snapshot which is not valid in this case. Hope this clarifies.

**Comment by Divyanimmagadda** [comment]
Tested the functionality, working as desired. 

instances

**Comment by Divyanimmagadda** [comment]
vm in stopped state


vm in running state

**Comment by Divyanimmagadda** [comment]
Test results are as desired. LGTM

**Comment by ramkatru** [comment]
tag:mergeready

**Comment by resmo** [comment]
LGTM (based on code review)

**Pull request merged**
