### PR TITLE
CLOUDSTACK-10144: fix possible NPE in listVlanIpRanges

### PR DESCRIPTION
**Pull request by resmo**
Prevent NPE for querying a deleted project.

### CODE REVIEW

**Comment by ustcweizhou** [comment]
code LGTM.

However, could you please add some code to release vlan and ip ranges while delete a project ?
If it is not an issue anymore, please ignore my comment :)

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by resmo** [comment]
rollback transaction on releasing vlan and ip ranges while delete a project was the root cause getting into this state. Unsure yet, while that happened. 

However, preventing an NPE can not be wrong.

**Comment by ustcweizhou** [comment]
@resmo agreed. let's merge this at first.

It would be nice to fix the issue you said.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Simple npe check, merging based to Travis and packaging validations.

**Pull request merged**
