### PR TITLE
Hypervisor as class

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR moves HypervisorType from an Enum to a class that is largely compatible with Enum. This will allow for custom hypervisor plugins to be added dynamically.

The changes are similar to what was done for StorageType in https://github.com/apache/cloudstack/pull/8544.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan test matrix

**Comment by vishesh92** [comment]
@blueorangutan package

**Review by sureshanaparti — APPROVED** [review]
Code LGTM

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
Merging based on code reviews and manual QA as nudged by @borisstoyanov to me.

**Review by borisstoyanov — COMMENTED** [review]
LGTM

**Pull request merged**
