### PR TITLE
Improve some UserVmManagerImpl's methods name and docs

### PR DESCRIPTION
**Pull request by GutoVeronezi**
### Description

This PR renames some `UserVmManagerImpl`'s methods and improve their javadocs to make them more intuitive.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by GutoVeronezi** [comment]
@GaOrtiga @weizhouapache I did some improvements to the methods names and javadocs in order to avoid confusion in the future.

**Comment by GutoVeronezi** [comment]
@blueorangutan package

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Review by GaOrtiga — APPROVED** [review]
Good clarifications.

CLTM.

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by weizhouapache** [comment]
Merging as this just renames some methods.

**Pull request merged**
