### PR TITLE
Updated some offensive words in kubernetes plugin/service with inclusive words/terms.

### PR DESCRIPTION
**Pull request by sureshanaparti**
### Description
This PR replaces some offensive words in kubernetes plugin/service with inclusive words/terms.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):
Manually tested API / Response.

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan test

**Review by Pearl1594 — COMMENTED** [review]
Code LGTM. References to k8s master have either been replaced or marked as deprecated. Smoke test run should cover if the changes breaks anything.

**Comment by Pearl1594** [comment]
@blueorangutan test

**Review by Pearl1594 — APPROVED** [review]

**Review by shwstppr — APPROVED** [review]

**Comment by sureshanaparti** [comment]
> Code LGTM. References to k8s master have either been replaced or marked as deprecated. Smoke test run should cover if the changes breaks anything.

no issues with kubernetes tests

**Review by davidjumani — APPROVED** [review]

**Review by vladimirpetrov — APPROVED** [review]
LGTM based on code review and actual testing.

**Pull request merged**
