### PR TITLE
[4.9] Latest health test run

### PR DESCRIPTION
**Pull request by rhtyd**
Dummy PR to trigger tests on latest 4.9 branch

@blueorangutan package

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by serg38** [comment]
@rhtyd All the new failures are due to inability to SSH to VMs. Can we re-run this to filter environmental issue or recent PR merge?

**Comment by rhtyd** [comment]
@serg38 Likely environment related, I'll check that /cc @PaulAngus 
Meanwhile I'll kick another round.
@blueorangutan package

**Comment by serg38** [comment]
@rhtyd Both 4.9 and 4.10 now fail as well as PR based on 4.9 e.g. PR 1659 with 13 tests on KVM but PRs based on 4.8 succeed e.g. PR1710 and PR1753. Might be some interference from one of the last merges.

**Comment by serg38** [comment]
@rhtyd 4.10 tests started failing after 11/23

**Comment by rhtyd** [comment]
@serg38 thanks, that's my opinion as well, I'll kick one more round just to be sure, and will bisect recently merged changes and revert any changes if necessary.
@blueorangutan test matrix

**Comment by serg38** [comment]
@rhtyd Only 2 PRs were merged in the interval between last successful run and failure: PR1766 and PR1545
1766 was merged to 4.8 and was hypervisor agnostic so all points at PR1545  'Add channel to Instances for Qemu Guest Agent' which was conveniently KVM specific.

**Comment by rhtyd** [comment]
@serg38 thanks, I'll bisect them today.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@serg38 I looked across PRs merged since 23rd Nov, and found an issue with fwd-merging a PR that caused an issue in CsDhcp.py. I've fixed the issue now, and kicked test runs. So, far it looks promising. We'll have results soon. Thanks.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by borisstoyanov** [comment]
KVM and Xen are looking good, I've re-run manually the vmware and they passed
```
Test Snapshot Root Disk ... === TestName: test_01_snapshot_root_disk | Status : SUCCESS ===
ok
----------------------------------------------------------------------
Ran 1 test in 316.252s
OK
```

```
Test create public & private template ... === TestName: test_01_create_template | Status : SUCCESS ===
ok
Test when createTemplate is used to create templates having the same name all of them get ... === TestName: test_CreateTemplateWithDuplicateName | Status : SUCCESS ===
ok
Test Edit template ... === TestName: test_02_edit_template | Status : SUCCESS ===
ok
Test delete template ... === TestName: test_03_delete_template | Status : SUCCESS ===
ok
Test for extract template ... === TestName: test_04_extract_template | Status : SUCCESS ===
ok
Update & Test for template permissions ... === TestName: test_05_template_permissions | Status : SUCCESS ===
ok
Test for copy template from one zone to another ... SKIP: Not enough zones available to perform copy template
Test only public templates are visible to normal user ... === TestName: test_07_list_public_templates | Status : SUCCESS ===
ok
Test System templates are not visible to normal user ... === TestName: test_08_list_system_templates | Status : SUCCESS ===
ok
----------------------------------------------------------------------
Ran 9 tests in 1428.642s

```

LGTM

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
Checked mostr

**Pull request closed without merging**
