### PR TITLE
ui: fix create user domain, account selection

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

- Fixes domain, account selection for new user
- Refreshes user details on configuring SAML SSO

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):

domainaccountfilter

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan ui

**Review by utchoang — APPROVED** [review]
LGTM!

**Comment by sureshanaparti** [comment]
@blueorangutan ui

**Comment by sureshanaparti** [comment]
Hi @shwstppr When changing the domain, the account shown/selected doesn't change while the account list items reflects new accounts from the changed domain. Please check.

**Comment by shwstppr** [comment]
@blueorangutan ui

@sureshanaparti fixed

**Comment by sureshanaparti** [comment]
@blueorangutan ui

**Comment by sureshanaparti** [comment]
Verified accounts listed in the selected domain while creating user from UI. LGTM.

**Review by sureshanaparti — APPROVED** [review]

**Pull request merged**
