### PR TITLE
VR live patching: Allow live patch of VPC VRs even if networks are in allocated / shutdown state

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

This PR attempts to live-patch VPC VRs even when the tier networks are not in the implemented state, i.e., there are no records in the router_network_ref table. Currently when they are in any other state than Implemented, live-patch fails 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [X] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?
1. Create a few VPC networks in say a 4.15.2 env 
2. Create a tier network in one of the VPCs such that it is in allocated state
3. Create a tier network in another VPC, create a VM and either destroy / shutdown the VM such that the n/w garbage collector will put the network tier in Shutdown state
4. Upgrade to main branch and then live-patch these VPCs
It should successfully have patched

### CODE REVIEW

**Comment by rohityadavcloud** [comment]
@Pearl1594 can you raise this for 4.18 branch?

**Comment by Pearl1594** [comment]
> @Pearl1594 can you raise this for 4.18 branch?

done..

**Review by harikrishna-patnala — APPROVED** [review]
Code LGTM

**Comment by weizhouapache** [comment]
code lgtm

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by shwstppr — APPROVED** [review]
Code LGTM

**Review by rohityadavcloud — APPROVED** [review]
LGTM - didn't test it though

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Pull request merged**
