### PR TITLE
Updated invalid parameter/value error with proper exception

### LINKED ISSUE #9436: Some java classes use "java.security.InvalidParameterException" which should be "com.cloud.exception.InvalidParameterValueException"
just for cleanup 

##### ISSUE TYPE

 * Bug Report
 * Improvement Request
 * Enhancement Request
 * Feature Idea
 * Documentation Report
 * Other

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~
4.20
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

### PR DESCRIPTION
**Pull request by sureshanaparti**
### Description

This PR updates invalid parameter/value  error with proper exception, to com.cloud.exception.InvalidParameterValueException (from java.security.InvalidParameterException).

Fixes #9436 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Review by weizhouapache — APPROVED** [review]
thanks @sureshanaparti 
lgtm

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Review by FelipeM525 — APPROVED** [review]
LGTM!

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
> [SF] Trillian test result (tid-11201) Environment: kvm-ol8 (x2), Advanced Networking with Mgmt server ol8 Total time taken: 51791 seconds Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr9455-t11201-kvm-ol8.zip Smoke tests completed. 138 look OK, 1 have errors, 0 did not run Only failed and skipped tests results shown below:
> 
> Test	Result	Time (s)	Test File
> test_01_redundant_vpc_site2site_vpn	`Failure`	434.50	test_vpc_vpn.py

failure not related to the changes here

**Pull request merged**
