### PR TITLE
Bug-ID: CLOUDSTACK-8654: Added guest_os mappings for CoreOS

### PR DESCRIPTION
**Pull request by kishankavala**
Tested CoreOS Vm deploy in Xenserver, KVM and VMware hypervisors
Tested upgrade with new guest OS mappings

### CODE REVIEW

**Comment by DaanHoogland** [comment]
LGTM, not tested

**Comment by bhaisaab** [comment]
@kishankavala please rebase against latest master and move the sqls to the recent sql paths

**Comment by rajesh-battala** [comment]
LGTM.

**Comment by koushik-das** [comment]
@kishankavala The changes needs to be moved to the latest sql upgrade files.

**Comment by rhtyd** [comment]
@kishankavala can you rebase against latest master and share state of your PR, thanks; the changes also need to be moved to 481-490 schema file

**Comment by rhtyd** [comment]
tag:easypr

**Comment by rhtyd** [comment]
This needs to be rebased @kishankavala

**Comment by sateesh-chodapuneedi** [comment]
@rhtyd I think this would be useful for 4.9. 
@kishankavala Can you please rebase this fix?

**Comment by rhtyd** [comment]
@kishankavala can you move the sql changes to setup/db/db/schema-490to4910.sql ?

**Pull request closed without merging**
