### PR TITLE
Vmdk findbugs

### PR DESCRIPTION
**Pull request by DaanHoogland**
these are two of the findbugs errors coming out of our jenkins all the time. The author seems to be unavailable so I kicked and screamed at it.
notice that this is noredist code. I did the compile without it. there is one with running.

### CODE REVIEW

**Comment by DaanHoogland** [comment]
note that jenkins isn't responding to the PR (so far)

**Comment by wido** [comment]
Seems good to me looking at it. Don't know how to test it properly, but code-wise the changes look sane to me.

**Comment by bhaisaab** [comment]
LGTM, did not test it.

**Comment by bvbharatk** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 120
 Hypervisor xenserver
 NetworkType Advanced
 Passed=106
 Failed=12
 Skipped=4

_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/yj3wnzbceo9uef2/AAB6u-Iap-xztdm6jHX9SjPja?dl=0


**Failed tests:**

**Skipped tests:**
test_vm_nic_adapter_vmxnet3
test_deploy_vgpu_enabled_vm
test_06_copy_template
test_06_copy_iso

**Passed test suits:**
integration.smoke.test_deploy_vm_with_userdata.TestDeployVmWithUserData
integration.smoke.test_affinity_groups_projects.TestDeployVmWithAffinityGroup
integration.smoke.test_portable_publicip.TestPortablePublicIPAcquire
integration.smoke.test_over_provisioning.TestUpdateOverProvision
integration.smoke.test_global_settings.TestUpdateConfigWithScope
integration.smoke.test_guest_vlan_range.TestDedicateGuestVlanRange
integration.smoke.test_scale_vm.TestScaleVm
integration.smoke.test_service_offerings.TestCreateServiceOffering
integration.smoke.test_loadbalance.TestLoadBalance
integration.smoke.test_routers.TestRouterServices
integration.smoke.test_reset_vm_on_reboot.TestResetVmOnReboot
integration.smoke.test_snapshots.TestSnapshotRootDisk
integration.smoke.test_deploy_vms_with_varied_deploymentplanners.TestDeployVmWithVariedPlanners
integration.smoke.test_network.TestDeleteAccount
integration.smoke.test_non_contigiousvlan.TestUpdatePhysicalNetwork
integration.smoke.test_deploy_vm_iso.TestDeployVMFromISO
integration.smoke.test_public_ip_range.TestDedicatePublicIPRange
integration.smoke.test_multipleips_per_nic.TestDeployVM
integration.smoke.test_regions.TestRegions
integration.smoke.test_affinity_groups.TestDeployVmWithAffinityGroup
integration.smoke.test_network_acl.TestNetworkACL
integration.smoke.test_pvlan.TestPVLAN
integration.smoke.test_volumes.TestCreateVolume
integration.smoke.test_ssvm.TestSSVMs
integration.smoke.test_nic.TestNic
integration.smoke.test_deploy_vm_root_resize.TestDeployVM
integration.smoke.test_resource_detail.TestResourceDetail
integration.smoke.test_secondary_storage.TestSecStorageServices
integration.smoke.test_vm_life_cycle.TestDeployVM
integration.smoke.test_disk_offerings.TestCreateDiskOffering

**Comment by koushik-das** [comment]
+1 for code changes and based on the test report from @bvbharatk.
Since the changes are specific to VMware and the test results are for XS, not sure how to take this forward.

**Comment by rhtyd** [comment]
@DaanHoogland can you rebase it once again and push -f

Once CI tested, we should be able to merge this cc @swill 

tag:easypr

**Comment by swill** [comment]
@rhtyd & @DaanHoogland  I don't have the ability to test this as I have a KVM setup, can one of you post some test results using VMware?

**Comment by rhtyd** [comment]
@DaanHoogland I'm seeing a lot of commits, can you rebase against 4.7?

**Comment by DaanHoogland** [comment]
@rhtyd you are right, I rebased against master instead of 4.7, sorry, will close and reopen against master

**Pull request closed without merging**
