### PR TITLE
[wip] CLOUDSTACK-8677: use wrapper classes for gson serialisation

### PR DESCRIPTION
**Pull request by DaanHoogland**
non functional change with great risk: replace all basic type fields of json serializable objects to wrapper class type fields. It is needed for gson upgrade which is needed for phone home functionality.

### CODE REVIEW

**Comment by wido** [comment]
To add to the PR, it's not only needed for the Call-Home functionality, but we are using a very, very old version of Gson.

**Comment by DaanHoogland** [comment]
@wido absolutly right. i'm not burning all these hours (both personal and sponsorred) just for the sake of this great marketing tool ;)

**Comment by wido** [comment]
@borisroman Can we run the tests on this one?

**Comment by borisroman** [comment]
@widi already building

**Comment by rhtyd** [comment]
@DaanHoogland can you rebase against latest master; it's huge change, advise how to test and review it

**Comment by DaanHoogland** [comment]
I'd rather redo it then try to port forward. Testing means validating each command in an integration test. If unit testing is required; for each command and response that can go to an agent serialising and deserialising needs to be tested.

**Pull request closed without merging**
