### PR TITLE
README: that time of the year! 🎄

### PR DESCRIPTION
**Pull request by rhtyd**
That time of the year :christmas_tree: - let's merge this without tests?

## Screenshots (if appropriate):

Screenshot from 2019-12-16 21-14-27

### CODE REVIEW

**Comment by rhtyd** [comment]
To all of the CloudStack contributors - Happy Christmas and holidays!
/cc alphabetically-ish @alexandremattioli @andrijapanicsb @borisstoyanov @bwsw @chiradeep @DaanHoogland @davidjumani @GabrielBrascher @gsirett @harikrishna-patnala @K0zka @kiwiflyer @PaulAngus @mlsorensen @mike-tutkowski @milamberspace @msinhore @nathanejohnson @NuxRo @nvazquez @Pearl1594 @pdion891 @ravening @shwstppr @Spaceman1984 @steveroles @sureshanaparti @svenvogel @swill @syed @vladimirpetrov @weizhouapache @wido and so many others! (sorry guys in case I missed any of your handles - you're in thoughts as well)

**Comment by ravening** [comment]
LGTM

**Comment by imduffy15** [comment]
LGTM @rhtyd :)

**Comment by Spaceman1984** [comment]
Thanks @rhtyd Merry Christmas an happy holidays to you too.

**Review by davidjumani — APPROVED** [review]

**Comment by steveroles** [comment]
+1

Happy holidays all! Here’s to a better 2021

Best regards,

**Comment by gsirett** [comment]
Happy Christmas & New Year everybody. Its been great collaborating with everybody in this crazy year. 

Please merge the 2021 PR as quickly as possible :-)

**Review by borisstoyanov — APPROVED** [review]

**Review by Pearl1594 — APPROVED** [review]

**Review by weizhouapache — APPROVED** [review]

**Review by vladimirpetrov — APPROVED** [review]

**Review by shwstppr — APPROVED** [review]
Merry Christmas and a very Happy New Year all!

**Comment by DaanHoogland** [comment]
grinch this :( 👎 unless we want of course rc3 and or 4.15 tinted...

**Comment by slavkap** [comment]
Thanks, @rhtyd, Merry Christmas and happy holidays to all! :)

**Comment by syed** [comment]
Merry Christmas and happy holidays to everyone!

**Comment by alexandremattioli** [comment]
+1
All the best everyone.

**Comment by onitake** [comment]
Happy holidays, I'll ACK this once the Travis CI errors have been addressed. :rofl:

**Comment by svenvogel** [comment]
+1

Christmas than the other years but I which all you guys very Christmas !!!

**Review by svenvogel — APPROVED** [review]

**Review by sureshanaparti — APPROVED** [review]
+1

Happy Christmas / Holidays and a very Happy New Year!

**Comment by rhtyd** [comment]
Once again - happy Christmas, holidays, and new year! Let's merge this.

**Comment by DaanHoogland** [comment]
I retract my minus grinch ;)

**Pull request merged**
