### PR TITLE
AutoScaling: update smoke test and consider db upgrade from a fork

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes the smoke test as per Daan's comments (see https://github.com/apache/cloudstack/pull/6571#pullrequestreview-1204572347).

This PR also fixes an issue that "supports_vm_autoscaling" needs to be updated only if all network offerings has supports_vm_autoscaling = 0 .
(this might be an issue if upgrade from a fork to community version)

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Review by stephankruggg — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Pull request merged**
