### PR TITLE
unittesting: test resolution is not guaranteed to be exact

### PR DESCRIPTION
**Pull request by DaanHoogland**
a lot of validation pull requests are failing over this test. It should pass but it's failure is environmental in any observed case so far.

### CODE REVIEW

**Comment by wilderrodrigues** [comment]
Thanks, @DaanHoogland!

LGTM :+1:

**Comment by bhaisaab** [comment]
LGTM

**Comment by miguelaferreira** [comment]
@DaanHoogland @wilderrodrigues @bhaisaab 

What's the purpose of having this unit test?

I've just seen this unit test fail in a travis build (https://travis-ci.org/miguelaferreira/cloudstack/jobs/77300485). What needs to be done in response to this failure?

**Comment by DaanHoogland** [comment]
@miguelaferreira it is proven to be of no use. For what I am concerned we should remove it totally. We can not guarantee any kind of realtime result in/with this test.
The period checked for had been lengthened beyond the 2 ms. If we lengthen the test period over 3 milisecs when testing 2 there is no longer any test being done.

**Comment by miguelaferreira** [comment]
@DaanHoogland: @wilderrodrigues will make a PR to remove it

**Pull request merged**
