### PR TITLE
CLOUDSTACK-9336 surround the execution of baremetal-vr.py with condition

### PR DESCRIPTION
**Pull request by DaanHoogland**

### CODE REVIEW

**Comment by DaanHoogland** [comment]
integration tests pending

**Comment by DaanHoogland** [comment]
two failures. they seem unrelated but double ckecking
[1463.results.network.txt](https://github.com/apache/cloudstack/files/205002/1463.results.network.txt)
[1463.results.vpc_routers.txt](https://github.com/apache/cloudstack/files/205003/1463.results.vpc_routers.txt)

**Comment by DaanHoogland** [comment]
I replayed the functionality tested in the second test and it is working. Will have to look into the test code to see what is happening.

retesting the first one now

**Comment by DaanHoogland** [comment]
@harikrishna-patnala can you test this as well, somehow?

**Comment by rhtyd** [comment]
@DaanHoogland what is the logic here, if any empty router is configured than start baremetal-vr server?

**Comment by rhtyd** [comment]
tag:needlove

**Comment by DaanHoogland** [comment]
@rhtyd better tag with tag:easypr

the logic is that this need not be executed on ssvm or cpvm

**Comment by rhtyd** [comment]
LGTM, @swill @wido @resmo @nvazquez @nlivens @koushik-das and others - one more LGTM needed

tag:easypr

**Comment by nvazquez** [comment]
Code LGTM

**Comment by swill** [comment]
Thanks @nvazquez, I think this one is ready now...

**Comment by resmo** [comment]
lgtm

**Comment by nlivens** [comment]
LGTM

**Comment by kiwiflyer** [comment]
@swill  4 x LGTM + CI from Daan. 
This is Ready to Merge

**Comment by swill** [comment]
Yes, this one is ready.  I just need to verify master is in a good state before I continue merging into master.  We had a merge conflict yesterday which we resolved, but we need to validate master is stable before I do more merging for now.

**Pull request merged**
