### PR TITLE
CLOUDSTACK-9261: Query to traffic sentinel requesting for usage stats…

### PR DESCRIPTION
**Pull request by kansal**
… is too long resulting in traffic sentinel sending HTTP 414 error response - Fixed

Root Cause Analysis:
In the current implementation, we are using GET method to send the request tom the traffic sentinel instance. Thus, if there are many IP's that need to be queried, the request becomes too long and the HTTP Error 414 is thrown. 

Fix: Changed the GET request to the POST request.

### CODE REVIEW

**Comment by alexandrelimassantana** [comment]
Hi @kansal, can you make a test with this change? Try issuing an request with more than 2048 characters to see if everything still works fine then.

**Comment by kansal** [comment]
@alexandrelimassantana , I am not sure of how to simulate the actual traffic sentinel resource. I can create a request with 20148 or more, but the actual error is encountered when the request reaches the resource.

**Comment by GabrielBrascher** [comment]
@kansal Could you please consider the following adjustments?
- create a method for the "Part 1" (lines 213-219). With the command as parameter and returning the connection to be used for "Part 2" (lines 221-223);
- create a method for "Part 2", returning the output stream and receiving as parameter the connection and post data.

I think that with these two methods, the code would be more readable.

Thanks.

**Comment by kansal** [comment]
@GabrielBrascher These adjustments can be done, but I don't see any point of introducing the function calls. Anyhow this code is not used anywhere else in the whole project. As far as readability is concerned, I think with the proper comments it should be just fine.

**Comment by kishankavala** [comment]
@kansal 
LGTM. See if you can add an integration test.  
Actual response from traffic sentinel resource in the logs will also help.

**Comment by GabrielBrascher** [comment]
@kansal create methods would also help to test the behavior of this code, using unit test and integration test (to verify if the methods that have unit test are called in the correct order by a more generic method).

For example, you could create a method `queryTrafficSentinel`, this method calls the part 1, 2 and 3 in this exact sequence and one time each (you can use [InOrder](https://mockito.googlecode.com/hg-history/1.6/javadoc/org/mockito/InOrder.html) to ensure the order and times that a method was called). Methods that would do the part 1, 2 and 3 could have unit tests.

At the end, you could create a Javadoc for those methods using all four comment blocks that you created.

Thanks.

**Comment by rhtyd** [comment]
@kansal please rebase against latest master

tag:needlove

**Comment by kansal** [comment]
@rhtyd Rebased.

**Comment by bvbharatk** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 148
 Hypervisor xenserver
 NetworkType Advanced
 Passed=70
 Failed=1
 Skipped=3

_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/yj3wnzbceo9uef2/AAB6u-Iap-xztdm6jHX9SjPja?dl=0


**Failed tests:**
* test_service_offerings.py

 * ContextSuite context=TestServiceOfferings>:setup Failing since 8 runs


**Skipped tests:**
test_vm_nic_adapter_vmxnet3
test_static_role_account_acls
test_deploy_vgpu_enabled_vm

**Passed test suits:**
test_deploy_vm_with_userdata.py
test_affinity_groups_projects.py
test_portable_publicip.py
test_vpc_vpn.py
test_over_provisioning.py
test_global_settings.py
test_scale_vm.py
test_routers_iptables_default_policy.py
test_routers.py
test_reset_vm_on_reboot.py
test_snapshots.py
test_deploy_vms_with_varied_deploymentplanners.py
test_login.py
test_list_ids_parameter.py
test_public_ip_range.py
test_multipleips_per_nic.py
test_regions.py
test_affinity_groups.py
test_network_acl.py
test_pvlan.py
test_volumes.py
test_nic.py
test_deploy_vm_root_resize.py
test_resource_detail.py
test_secondary_storage.py
test_vm_life_cycle.py
test_disk_offerings.py

**Pull request closed without merging**
