### PR TITLE
schema: revert incorrect removal of oauth changes in #7417

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes OAuth(2) schema changes removed in Database VIEW Management improvement #7417

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [x] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
looks good

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by harikrishna-patnala — APPROVED** [review]
LGTM, thanks for catching and fixing it @shwstppr

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by weizhouapache** [comment]
@DaanHoogland @shwstppr 
should we merge this now ?
I think all other PRs against main branch might be impacted by the issue.

**Comment by DaanHoogland** [comment]
I think we can, but would like to await the package job

**Comment by weizhouapache** [comment]
> I think we can, but would like to await the package job

ok @DaanHoogland , let's wait.
The simulator CI looks fine btw

**Pull request merged**
