### PR TITLE
Lint modified files only with Super-Linter

### PR DESCRIPTION
**Pull request by jbampton**
https://github.com/github/super-linter#standard-image

### Description

This PR changes the Super Linter to only lint files in the pull request.

Should run much faster too.

refs #6529 
refs #6528 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [X] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@jbampton it seems it is failing anyway (see github checks on this PR) any idea if this can be fixed without disabling the superlinter completely (as in #6528 )

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
Do we need this on 4.17 branch as well @jbampton @DaanHoogland ?

**Comment by rohityadavcloud** [comment]
I'll raise the issue again if I see failures on 4.17 PRs. For now let's merge this to unblock incorrect failures on other PRs.

**Comment by jbampton** [comment]
> Do we need this on 4.17 branch as well @jbampton @DaanHoogland ?

Yes @rohityadavcloud we do need this change on 4.17 branch.  

Seems it takes 11 minutes there: refs #7016

**Pull request merged**
