### PR TITLE
Fix spelling. Change `Occured` to `Occurred`

### PR DESCRIPTION
**Pull request by jbampton**
### Description

Fix typos

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [X] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [X] Trivial

### CODE REVIEW

**Review by rohityadavcloud — APPROVED** [review]
+1
It occurred to me we don't know how to spell :)

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Review by nvazquez — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
Test failures appear intermittent and don't seem related to this PR.

**Pull request merged**
