### PR TITLE
CLOUDSTACK-9192: UpdateVpnCustomerGateway is failing

### PR DESCRIPTION
**Pull request by nitin-maharana**
Reproducible Steps:
================
1.Create a customer gateway for a VPC.
2.Edit it using UI(API call is UpdateVpnCustomerGateway).
3.When we try to update the customer vpn gateway with connection state is not in "Error", we see the API error but that won't be reflected to the user in UI.

Actual Behaviour:
==============
The API throws error. But UI doesn't show it to user.

Expected Behaviour:
================
The UI should show the error to user.

Fix:
===
TypeError: json.updatecustomergatewayresponse is undefined
The response name was wrong so corrected it.
It should be json.updatevpncustomergatewayresponse.
Added the error function.

### CODE REVIEW

**Comment by nitin-maharana** [comment]
Reference #1264 (The PR against master).

**Comment by remibergsma** [comment]
LGTM

Didn't work before:
cloudstack_pr1300_1

Did work in this PR:
cloudstack_pr1300_3

Also, error handling is working and showing in the UI:
cloudstack_pr1300_2

Thanks @nitin-maharana :-)

**Comment by nitin-maharana** [comment]
@kishankavala @koushik-das : Can you please review this. Thanks.

**Comment by pdube** [comment]
Code changes LGTM, looked in the UpdateVpnGatewayCmd and checked the response name (it is 'updatevpngatewayresponse').

**Comment by wilderrodrigues** [comment]
Ping @remibergsma 

LGTM, please proceed with merge.

Cheers,
Wilder

**Pull request merged**
