### PR TITLE
[CLOUDSTACK-10226] CloudStack is not importing Local storage properly

### PR DESCRIPTION
**Pull request by rafaelweingartner**
CloudStack is importing as Local storage any XenServer SR that is of type LVM or EXT. This causes a problem when one wants to use both Direct attach storage and local storage. Moreover, CloudStack was not importing all of the local storage that a host has available when local storage is enabled. It was only importing the First SR it sees.

To fix the first problem we started ignoring SRs that have the flag shared=true when discovering local storages. SRs configured to be shared are used as direct attached storage, and therefore should not be imported again as local ones.

To fix the second problem, we started loading all Local storage and importing them accordingly to ACS.

Tip for reviewers: the code changes is mainly in `CitrixResourceBase`, method `initializeLocalSR`

### CODE REVIEW

**Comment by rafaelweingartner** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan help

**Comment by DaanHoogland** [comment]
@blueorangutan test centos7 xenserver-71

**Comment by rafaelweingartner** [comment]
@blueorangutan package

**Comment by rafaelweingartner** [comment]
@DaanHoogland it seems that the tests you executed here were successful (despite the errors presented). Can you confirm it?

**Comment by DaanHoogland** [comment]
I think it is @rafaelweingartner let me rekick anyway, you can download the logs and examine them.
@blueorangutan test

**Comment by rafaelweingartner** [comment]
I checked the logs. The problems did not seem to be related to the PR.
However, it is always good to have the feedback of an expert ;)

**Comment by rafaelweingartner** [comment]
@DaanHoogland I checked this last log result. Can I consider that the tests is successful then?

**Comment by DaanHoogland** [comment]
@rafaelweingartner , i'm cautious here. This one seems consistent. Did you explain the cause of the failure?
@mike-tutkowski can you review this (and add yourself to the apache org)?

**Comment by rafaelweingartner** [comment]
@DaanHoogland I checked the error, and I still do not understand how it could be related to the code of this PR. Here I am only changing how local storages are detected and loaded to the system. Whereas, the error is related to redundant VRs in VPCs.

Anyways, I am trying to run the tests locally with simulator, but I am getting this error:
```
ERROR: do_vpc_test (integration.smoke.test_vpc_redundant.TestVPCRedundancy)
----------------------------------------------------------------------
TypeError: do_vpc_test() takes exactly 2 arguments (1 given)
-------------------- >> begin captured stdout << ---------------------
=== TestName: do_vpc_test | Status : EXCEPTION ===
```
I am not understanding the cause of that error. This is the command I am using to execute the test:
`nosetests --with-marvin --marvin-config=/root/marvinCloudStackConfig.cfg --hypervisor=simulator /root/cloudstack/test/integration/smoke/test_vpc_redundant.py`

Am I missing something else that is required to run tests?

**Comment by rafaelweingartner** [comment]
@mike-tutkowski could you share your wisdom with us here?

**Comment by mike-tutkowski** [comment]
Sorry @DaanHoogland - I didn't seem to get notified when you tagged me. I just noticed this PR when @rafaelweingartner tagged me today. Let me review this PR and think about it.

**Comment by mike-tutkowski** [comment]
I do not see how the VPC issue would be related to the code of this PR either. The PR code LGTM.

**Comment by rafaelweingartner** [comment]
@borisstoyanov  and @DaanHoogland shall we execute the tests again?

**Comment by DaanHoogland** [comment]
I don't think it makes sense but no hurt
@blueorangutan centos7 xenserver-71

**Comment by rafaelweingartner** [comment]
@DaanHoogland I do not think @blueorangutan heard your request for testing here...

**Comment by borisstoyanov** [comment]
@blueorangutan test centos7 xenserver-71

**Comment by rhtyd** [comment]
@rafaelweingartner I scanned PRs merged on master but not 4.11 and came across this PR, do you think this would be useful for 4.11? If so, can you help create a backport PR for 4.11?

**Comment by rafaelweingartner** [comment]
I do not think so. It seems that no other people had this necessity so far. This PR enables people to use local storage and pre-setup storage at the same time. Moreover, I organized things, and now it is possible to have more than a single local storage per host.

**Comment by rhtyd** [comment]
@rafaelweingartner fair enough, but this seems a useful fix for LTS nonetheless. I'll leave the decision of backporting to you on this (and other PRs).

**Pull request merged**
