### PR TITLE
CLOUDSTACK-9077 Fix injectkeys.sh to work on CentOS7

### PR DESCRIPTION
**Pull request by remibergsma**
Fix regression from commit 3381154fafb7fa4f0a61d538f7c2550e48247787

The error seen on CentOS 7:

```
2015-11-20 21:51:16,161 DEBUG [c.c.s.ConfigurationServerImpl] (localhost-startStop-1:null) No loop device found, skipping ssh key insertion in systemvm.iso
```

Instead of detecting `/dev/loop0` this checks if we run inside Docker.

Tested on CentOS 7 and that now works again as expected.

```
2015-11-23 16:20:16,777 DEBUG [c.c.s.ConfigurationServerImpl] (localhost-startStop-1:null) Executing: /bin/bash /var/lib/tomcat/webapps/client/WEB-INF/classes/scripts/vm/systemvm/injectkeys.sh /home/cloud/.ssh/id_rsa.pub /home/cl
oud/.ssh/id_rsa /var/lib/tomcat/webapps/client/WEB-INF/classes/vms/systemvm.iso
2015-11-23 16:20:16,821 DEBUG [c.c.s.ConfigurationServerImpl] (localhost-startStop-1:null) Execution is successful.
2015-11-23 16:20:16,827 INFO  [c.c.s.ConfigurationServerImpl] (localhost-startStop-1:null) Injected public and private keys into systemvm iso with result : null
```

Pinging @pdion891 to have a look.

### CODE REVIEW

**Comment by pdion891** [comment]
@remibergsma  Thanks for this PR, this will break the injection of the ssh key in the initial build of the docker container. But I will submit a PR to fix the initial build of the image that work with this PR. So please go ahead with this PR, seams to make more sense then previous "in a container check".

**Comment by pdion891** [comment]
@remibergsma can you update this PR with following update:
It still need to look for ``/dev/loop0`` inside docker to know if it can update the sshkey at the template creation process.

right after line 87
```
# if running into Docker as unprivileges, skip ssh verification as iso cannot be mounted due to missing loop device.
if [ -f /.dockerinit ]; then
  if [ -e /dev/loop0 ]; then
    # it's a docker instance with privileges.
    inject_into_iso systemvm.iso $newpubkey
    [ $? -ne 0 ] && exit 5
    copy_priv_key $newprivkey
  else
    # this mean it's a docker instance, ssh key cannot be verify.
    echo "We run inside Docker, skipping ssh key insertion in systemvm.iso"
  fi
else
  inject_into_iso systemvm.iso $newpubkey
  [ $? -ne 0 ] && exit 5
  copy_priv_key $newprivkey
fi
```


Thanks

**Comment by remibergsma** [comment]
@pdion891 Thanks, please have a look.

**Comment by pdion891** [comment]
Quickly tested for the docker images, behave correctly. 

LGTM

Thanks!

**Comment by DaanHoogland** [comment]
reviewed the code. except for the use of English in comments it looks fine.

LGTM

**Comment by bhaisaab** [comment]
@wido @remibergsma do we want this on 4.5?

**Pull request merged**
