### PR TITLE
CLOUDSTACK-9848: Added  exit status checking for the iptables commands

### PR DESCRIPTION
**Pull request by jayapalu**
Added the checking exist status of iptables command.
On exception return error so that it will be populated to management server.
Also cleaned some of the repeated iptables commands.

### CODE REVIEW

**Comment by bvbharatk** [comment]
code changes LGTM.

**Comment by wido** [comment]
Can you explain a bit more why you are changing the iptable rules? As they can break a lot of things by accident.

**Comment by jayapalu** [comment]
@wido 
In the patch it can be observed that  it  is ("-A FIREWALL_%s DROP" % ) running without '-j' and it is not caught. There is duplicate rule due this the impact is not seen. 

So I have added the checking the iptables add command exit status, with this iptables add command failure are caught.  If there is error or exception then it error will be returned to management server.

**Comment by wido** [comment]
Understood! Looks good to me.

LGTM

**Comment by jayapalu** [comment]
tag:mergeready

**Comment by rhtyd** [comment]
@jayapalu do you think this affects 4.9 VR? If so, can you please change PR's base branch to 4.9?
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-55u3

**Comment by karuturi** [comment]
test failures. Can you check?

**Comment by rhtyd** [comment]
It might be regressions due to the change, I can help rekick them.
@blueorangutan package

**Comment by jayapalu** [comment]
few of the cleanup of test cases are failing and these are not related my changes.
@borisstoyanov  Can you trigger the tests again.

**Comment by borisstoyanov** [comment]
@blueorangutan test centos7 vmware-55u3

**Comment by jayapalu** [comment]
Most of the test failures for because of the hidden bugs in iptables configuration. 
Please see the below logs from the VR, ACL_INBOUND_eth1 chain is not created. Added rule into this chain got failed.


2017-05-08 11:11:13,546  CsHelper.py execute2:209 Executing: iptables -t filter -I FORWARD -o eth1 -d 10.147.46.0/24 -j ACL_INBOUND_eth1
2017-05-08 11:11:13,551  configure.py main:1031 Exception while configuring router
Traceback (most recent call last):
  File "/opt/cloud/bin/configure.py", line 1015, in main
    nf.compare(config.get_fw())
  File "/opt/cloud/bin/cs/CsNetfilter.py", line 180, in compare
    raise Exception("iptables command got failed with error: %s " %error)
Exception: iptables command got failed with error:

==============
# cat /var/log/cloud.log | grep 'ACL_INBOUND_eth1'
2017-05-08 11:11:13,546  CsNetfilter.py compare:159 Checking if the rule already exists: rule={u'-d': u'10.147.46.0/24', u'-o': u'eth1', u'-A': u'FORWARD', u'-j': u'ACL_INBOUND_eth1'} table=filter chain=FORWARD
2017-05-08 11:11:13,546  CsNetfilter.py compare:164 Add: rule=-A FORWARD -o eth1 -d 10.147.46.0/24 -j ACL_INBOUND_eth1 table=filter
2017-05-08 11:11:13,546  CsHelper.py execute2:209 Executing: iptables -t filter -I FORWARD -o eth1 -d 10.147.46.0/24 -j ACL_INBOUND_eth1
root@r-36-QA:~#

**Comment by jayapalu** [comment]
@borisstoyanov  I have updated the PR. Can you please trigger the Trillian

**Comment by borisstoyanov** [comment]
Sure @jayapalu 
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test centos7 vmware-55u3

**Comment by jayapalu** [comment]
I think few of the failures and errors are because of the test issues not because of changes.

**Comment by rhtyd** [comment]
@jayapalu we'll need to reference the failures against baseline, I'll re-run the tests
@blueorangutan package

**Comment by jayapalu** [comment]
In my local test test_02_redundant_VPC_default_routes is passed. 

Create a redundant VPC with two networks with two VMs in each network and check default routes ... === TestName: test_02_redundant_VPC_default_routes | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 1 test in 795.766s
OK

=======================In Trillian it is failred because the VPC creation failed.=========
Create a redundant VPC with two networks with two VMs in each network and check default routes ... === TestName: test_02_redundant_VPC_default_routes | Status : EXCEPTION ===
ERROR
Create a redundant VPC with two networks with two VMs in each network ... === TestName: test_03_create_redundant_VPC_1tier_2VMs_2IPs_2PF_ACL_reboot_routers | Status : FAILED ===
FAIL
Create a redundant VPC with 1 Tier, 1 VM, 1 ACL, 1 PF and test Network GC Nics ... === TestName: test_04_rvpc_network_garbage_collector_nics | Status : FAILED ===
FAIL
Create a redundant VPC with 1 Tier, 1 VM, 1 ACL, 1 PF and test Network GC Nics ... === TestName: test_05_rvpc_multi_tiers | Status : FAILED ===
FAIL
=== TestName: test_05_rvpc_multi_tiers | Status : EXCEPTION ===
ERROR

======================================================================
ERROR: Create a redundant VPC with two networks with two VMs in each network
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/marvin/tests/smoke/test_vpc_redundant.py", line 318, in setUp
    domainid=self.account.domainid)
  File "/usr/lib/python2.7/site-packages/marvin/lib/base.py", line 4344, in create
    return VPC(apiclient.createVPC(cmd).__dict__)
  File "/usr/lib/python2.7/site-packages/marvin/cloudstackAPI/cloudstackAPIClient.py", line 2048, in createVPC
    response = self.connection.marvinRequest(command, response_type=response, method=method)
  File "/usr/lib/python2.7/site-packages/marvin/cloudstackConnection.py", line 379, in marvinRequest
    raise e
Exception: Job failed: {jobprocstatus : 0, created : u'2017-05-04T17:28:42+0000', jobresult : {errorcode : 530, errortext : u'**Failed to create VPC**'}, cmd : u'org.apache.cloudstack.api.command.admin.vpc.CreateVPCCmdByAdmin', userid : u'42cfe558-308f-11e7-9381-06dcb4010722', jobstatus : 2, jobid : u'd2bf42c3-76f1-403d-81cc-a5f660859faa', jobresultcode : 530, jobresulttype : u'object', jobinstancetype : u'None', accountid : u'42cfd80c-308f-11e7-9381-06dcb4010722'}
-------------------- >> begin captured stdout << ---------------------
=== TestName: test_01_create_redundant_VPC_2tiers_4VMs_4IPs_4PF_ACL | Status : EXCEPTION ===

**Comment by borisstoyanov** [comment]
@blueorangutan test centos7 vmware-55u3

**Comment by cloudmonger** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 684
 Hypervisor xenserver
 NetworkType Advanced
 Passed=111
 Failed=1
 Skipped=12

_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/r2si930m8xxzavs/AAAzNrnoF1fC3auFrvsKo_8-a?dl=0

**Failed tests:**
* test_network.py

 * test_public_ip_admin_account Failed


**Skipped tests:**
test_vm_nic_adapter_vmxnet3
test_01_verify_libvirt
test_02_verify_libvirt_after_restart
test_03_verify_libvirt_attach_disk
test_04_verify_guest_lspci
test_05_change_vm_ostype_restart
test_06_verify_guest_lspci_again
test_static_role_account_acls
test_11_ss_nfs_version_on_ssvm
test_nested_virtualization_vmware
test_3d_gpu_support
test_deploy_vgpu_enabled_vm

**Passed test suits:**
test_deploy_vm_with_userdata.py
test_affinity_groups_projects.py
test_portable_publicip.py
test_vm_snapshots.py
test_over_provisioning.py
test_global_settings.py
test_scale_vm.py
test_service_offerings.py
test_routers_iptables_default_policy.py
test_loadbalance.py
test_routers.py
test_reset_vm_on_reboot.py
test_deploy_vms_with_varied_deploymentplanners.py
test_router_dns.py
test_non_contigiousvlan.py
test_login.py
test_deploy_vm_iso.py
test_list_ids_parameter.py
test_public_ip_range.py
test_multipleips_per_nic.py
test_metrics_api.py
test_regions.py
test_affinity_groups.py
test_network_acl.py
test_pvlan.py
test_volumes.py
test_nic.py
test_deploy_vm_root_resize.py
test_resource_detail.py
test_secondary_storage.py
test_vm_life_cycle.py
test_routers_network_ops.py
test_disk_offerings.py

**Comment by jayapalu** [comment]
test_public_ip_admin_account is failed because of test setup issue. I have run the test locally it is passed. So marking merge-ready label.

$ cat  /tmp//MarvinLogs/test_network_WK9OKJ/results.txt 
Test for Associate/Disassociate public IP address for admin account ... === TestName: test_public_ip_admin_account | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 1 test in 72.100s

OK

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
This is a major change, may lead to severe regressions I would also like to run another round of regression tests.

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-55u3

**Comment by jayapalu** [comment]
@rhtyd  Currently In this PR  I have removed few incorrect/error iptables rules and logging the exit status of the commands. This will gives the errors in the VR logs.

**Comment by jayapalu** [comment]
@borisstoyanov  Can you please comment on the test failures, I feel the test  failures are because of the setup or test issues or intermittent failures. If you look at 'test_01_create_volume' I haven't done any changes related to that. 'test_04_rvpc_privategw_static_routes' it is failing in other PRs as well PR #1995. Can you look at failure tests so that I can mark merge ready.


test_01_create_volume 	Failure 	189.58 	test_volumes.py
test_04_rvpc_privategw_static_routes 	Failure 	915.18 	test_privategw_acl.py
test_03_vpc_privategw_restart_vpc_cleanup 	Failure 	222.43 	test_privategw_acl.py
test_01_vpc_privategw_acl 	Failure 	121.93 	test_privategw_acl.py
test_04_rvpc_network_garbage_collector_nics 	Error 	136.77 	test_vpc_redundant.py
test_01_primary_storage_nfs 	Error 	0.19 	test_primary_storage.py
ContextSuite context=TestStorageTags>:setup 	Error 	0.37 	test_primary_storage.py
ContextSuite context=TestDeployVmRootSize>:setup 	Error 	0.00

**Comment by jayapalu** [comment]
The test cases failures are not only seen this PR in other PRs also these test failures are seen. 
Marking this PR for merge ready

**Comment by rhtyd** [comment]
@jayapalu hmm, some of the vpc-related tests are known failures but can you check why `test_01_create_volume` failed. I'll kick another round with kvm:
@blueorangutan test

**Comment by jayapalu** [comment]
@rhtyd  PR changes are related VR scripts.  test_01_create_volume failure may be intermittent. Anyway in latest results test_01_create_volume is passed.

**Comment by rhtyd** [comment]
@jayapalu @karuturi based on several failures (intermittent or otherwise), some further testing on this change was needed and given some folks have raised objection on this it was perhaps not in a state to be merged. However, let's continue testing.

**Pull request merged**
