### PR TITLE
Fix login issue after logout from Configuration page

### PR DESCRIPTION
**Pull request by harikrishna-patnala**
### Description

This PR fixes the issue https://github.com/apache/cloudstack/issues/7187 of login after logout operation from configuration page.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### How Has This Been Tested?

- Logout from configuration page
- We should not see any error notifications regarding session
- Immediate login without refresh should work

### CODE REVIEW

**Comment by harikrishna-patnala** [comment]
@blueorangutan ui

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Review by rohityadavcloud — APPROVED** [review]

**Review by weizhouapache — APPROVED** [review]
verified OK

**Comment by DaanHoogland** [comment]
no backend changes so smoke tests won't give us more info
2lgtm and tested; merging

**Pull request merged**
