### PR TITLE
Userdata MySQL changes to use procedures to avoid duplicates

### PR DESCRIPTION
**Pull request by harikrishna-patnala**
### Description

This PR fixes the issue of user_data table sql queries to use procedures to avoid duplicates

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [x] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Review by borisstoyanov — APPROVED** [review]
LGTM manually upgraded

**Pull request merged**
