### PR TITLE
NPE guard

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR fixes an NPE incase a template has no size

Fixes: #7474

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [x] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
LGTM, simple enough null check
@blueorangutan test

**Comment by rajujith** [comment]
I am unable to reproduce the original issue anymore.

**Comment by DaanHoogland** [comment]
> I am unable to reproduce the original issue anymore.

That might be a timing issue or a strange corner-case prerequisite. I think we should merge this anyway.

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by rajujith** [comment]
@DaanHoogland  I couldn't verify this PR since the reported issue couldn't be reproduced.

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Pull request merged**
