### PR TITLE
CLOUDSTACK-8893: Fixing script as per the latest functionality

### PR DESCRIPTION
**Pull request by sanju1010**
Please check https://issues.apache.org/jira/browse/CLOUDSTACK-8893 for more details.

### CODE REVIEW

**Comment by sanju1010** [comment]
@Desc: Test that Volume snapshot for root volume not allowed ... === TestName: test_01_test_vm_volume_snapshot | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 1 test in 165.417s

OK

**Comment by nitt10prashant** [comment]
LGTM!!

**Comment by pavanb018** [comment]
@Desc: Test that Volume snapshot for root volume not allowed ... === TestName: test_01_test_vm_volume_snapshot | Status : SUCCESS ===
ok

Sanju1010 , is the above description part of script ? The description looks misleading with the current functionality. If it is not part of the code then LGTM !! , else please modify the description so that it wont be confusing.

**Comment by pavanb018** [comment]
LGTM !!

**Comment by remibergsma** [comment]
@pavanb018 @nitt10prashant Could you please add what you tested next time? A LGTM without any explanation doesn't really tell me anything to be honest.

**Comment by pavanb018** [comment]
An LGTM is given after going through the code and understanding what the code is accomplishing. The PR already has the test results and if i am not wrong an LGTM is for reviewing the code to make sure the functionality is working as expected ?

**Comment by nitt10prashant** [comment]
@remibergsma Next time sure  I will add some details .for this PR i have updated my comments .

**Comment by runseb** [comment]
@pavanb018 it always helps other folks reviewing to know what you did. For example. 
Did you just check the Travis green light ? Did you just check the code through github ? Did you pull the patch, apply and compile ? Did you do the build then run the tests. It may sound obvious to you what you did by giving the copy paste form a test, but writing a small friendly sentence for the next reviewer will go a long way to help us merge those fixes as a group.

thanks

**Comment by nvazquez** [comment]
Hi @sanju1010,

@serg38 and I are working on this PR #1677 which solves vm snapshot creation issue. After running `test_vm_snapshots.py` we're getting exception on `test_01_test_vm_volume_snapshot` as it was expected before your changes in this PR.

We're getting: `'CloudstackAPIException: Execute cmd: createsnapshot failed, due to: errorCode: 431, errorText:Volume snapshot is not allowed, please detach it from VM with VM Snapshots\n']`

This is consistent with `VolumeApiServiceImpl.allocSnapshot` method, in which it is:
```
        if (volume.getInstanceId() != null) {
            // Check that Vm to which this volume is attached does not have VM Snapshots
            if (_vmSnapshotDao.findByVm(volume.getInstanceId()).size() > 0) {
                throw new InvalidParameterValueException("Volume snapshot is not allowed, please detach it from VM with VM Snapshots");
            }
        }
```

Do you want us to adapt `test_vm_snapshots.py` in mentioned PR to support this or would you like to address it yourself?

Thanks

**Comment by serg38** [comment]
@jburwell @rhtyd @karuturi @nvazquez I assume the current code doesn’t allow volume snapshots on the top of vmsnapshots on purpose. In that case is it best to revert PR871 or create a new PR to address the Marvin script?

**Pull request merged**
