### PR TITLE
CLOUDSTACK-8830 - [Vmware] VM snapshot fails for 12 min after instance creation (Targeted for 4.9)

### PR DESCRIPTION
**Pull request by nvazquez**
Continuing work by @maneesha-p in #798 

This closes #798

### CODE REVIEW

**Comment by nvazquez** [comment]
@jburwell I took code from @maneesha-p and added some changes from your review in last PR

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@jburwell @rhtyd could you please review this? As problem is that vCenter sends recents tasks with null name, I simply added `StringUtils.isNotBlank` check before comparing task's name, do you agree with this solution?

**Comment by jburwell** [comment]
@nvazquez this fix appears to get rid of the exception, but I'd like to understand why we can't take a snapshot for exactly 12 minutes after a VM starts.  Is a VMware thing or is it a more fundamental CloudStack problem?

**Comment by nvazquez** [comment]
@jburwell actually with this small changes vm snapshots can be taken, I already tested manually and succeeds. This problem was related to Vmware API, which sends a task with null name within 12 minutes after vm starts in its recent tasks and if not checked, when iterating through this tasks, NullPointerException caused the whole procedure to fail

**Comment by serg38** [comment]
@jburwell Just to add, this is to address changes in backend task processing introduced in ESX 6. In 5.5 and before processing task had always had a name. In 6 it doesn't and competed task is kept in the API queue for exactly 12 min.

**Comment by jburwell** [comment]
@nvazquez @serg38 thank you for the background information -- we are working around a quirk in the VMware SDK not obscuring a CloudStack bug.  Do our current snapshot tests cover this condition or should we add another test when running VMware 6 to validate taking snapshots immediately after starting a VM and waiting 12 minutes?

**Comment by serg38** [comment]
@jburwell Yes our VM snapshot test covers this (with the exception of the issue that @nvazquez asked in PR871 which is unrelated to this PR ) . We will post results of vmsnaphsot test run on ESX6 hypervisor which previously were failing.

**Comment by jburwell** [comment]
@serg38 I will kick a blueorganutan run to regression test VMware 5.5.  Are the tests necessary to verify this PR part of the smoke test run or do we need to run additional component tests?

**Comment by serg38** [comment]
@jburwell This issue doesn't manifest on ESX 5.5. We already confirmed it resolves the issue to up to 4.5 branch. test_vm_snapshot which fails on ESX 6 now works fine. I can post test suite results shortly

**Comment by jburwell** [comment]
@serg38 I understand it is not an issue on ESXi 5.5.  From a regression test perspective, we need to run to regression tests to ensure this change does not introduce an issue with ESXi 5.5.  Which tests are you running to verify the change on ESXi 6?  I will run those on 5.5 to verify that no regressions have been introduced.

**Comment by serg38** [comment]
@jburwell  test_vm_snaphot only. Originally all 4 tests inside it would fail. With the fix one test still fails but it is unrelated to this issue and a conversation started in PR871. We would need either revert PR871 or open a new PR to resolve 4th test failure.

Test to create VM snapshots ... === TestName: test_01_create_vm_snapshots | Status : SUCCESS ===
Test to revert VM snapshots ... === TestName: test_02_revert_vm_snapshots | Status : SUCCESS ===
Test to delete vm snapshots ... === TestName: test_03_delete_vm_snapshots | Status : SUCCESS ===
=== TestName: test_01_test_vm_volume_snapshot | Status : EXCEPTION ===

**Comment by serg38** [comment]
@jburwell It would be nice to include this PR to the upcoming release. Are there anything else needed ?

**Comment by jburwell** [comment]
@blueorangutan test centos7 vmware55u3

**Comment by jburwell** [comment]
@serg38 I just kicked a smoke test run on VMware.  Assuming that passes, it will be good for 4.9.1.0.

**Comment by jburwell** [comment]
@serg38 @nvazquez tests for #1692 may have exposed a number of smoke test issues.  We are investigating the root causes to ensure that they are environmental not due to bugs.  Once we have that PR merged, I would like to get this PR rebased and run the smoke tests.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@jburwell @rhtyd we have rebased 4.9 branch, will start running tests

**Comment by serg38** [comment]
@rhtyd @murali-reddy @PaulAngus @jburwell Thanks for fixing all outstanding Marvin test issues. We have now 100% passing score on Marvin integration tests on RHEL 6 management server , advanced networking, Vmware 5.5/6.0 hypervisors. Please find results for this PR

**Comment by serg38** [comment]
LGTM for testing
```
2016-10-24 20:52:55 47 test files ro run
2016-10-24 20:52:55 Running test file: test/integration/smoke/test_affinity_groups_projects.py
2016-10-24 20:56:07 Running test file: test/integration/smoke/test_affinity_groups.py
2016-10-24 20:59:18 Running test file: test/integration/smoke/test_deploy_vgpu_enabled_vm.py
2016-10-24 20:59:19 Running test file: test/integration/smoke/test_deploy_vm_iso.py
2016-10-24 21:16:20 Running test file: test/integration/smoke/test_deploy_vm_root_resize.py
2016-10-24 21:16:44 Running test file: test/integration/smoke/test_deploy_vms_with_varied_deploymentplanners.py
2016-10-24 21:21:22 Running test file: test/integration/smoke/test_deploy_vm_with_userdata.py
2016-10-24 21:24:32 Running test file: test/integration/smoke/test_disk_offerings.py
2016-10-24 21:24:33 Running test file: test/integration/smoke/test_dynamicroles.py
2016-10-24 21:24:34 Running test file: test/integration/smoke/test_global_settings.py
2016-10-24 21:24:35 Running test file: test/integration/smoke/test_guest_vlan_range.py
2016-10-24 21:24:59 Running test file: test/integration/smoke/test_hosts.py
2016-10-24 21:25:00 Running test file: test/integration/smoke/test_internal_lb.py
2016-10-24 22:05:15 Running test file: test/integration/smoke/test_iso.py
2016-10-24 22:10:16 Running test file: test/integration/smoke/test_list_ids_parameter.py
2016-10-24 22:24:18 Running test file: test/integration/smoke/test_loadbalance.py
2016-10-24 22:45:45 Running test file: test/integration/smoke/test_login.py
2016-10-24 22:46:09 Running test file: test/integration/smoke/test_multipleips_per_nic.py
2016-10-24 22:48:45 Running test file: test/integration/smoke/test_network_acl.py
2016-10-24 22:51:21 Running test file: test/integration/smoke/test_network.py
2016-10-24 23:23:44 Running test file: test/integration/smoke/test_nic_adapter_type.py
2016-10-24 23:23:52 Running test file: test/integration/smoke/test_nic.py
2016-10-24 23:33:13 Running test file: test/integration/smoke/test_non_contigiousvlan.py
2016-10-24 23:33:30 Running test file: test/integration/smoke/test_over_provisioning.py
2016-10-24 23:33:31 Running test file: test/integration/smoke/test_password_server.py
2016-10-24 23:37:44 Running test file: test/integration/smoke/test_portable_publicip.py
2016-10-24 23:39:07 Running test file: test/integration/smoke/test_primary_storage.py
2016-10-24 23:39:08 Running test file: test/integration/smoke/test_public_ip_range.py
2016-10-24 23:39:17 Running test file: test/integration/smoke/test_pvlan.py
2016-10-24 23:39:23 Running test file: test/integration/smoke/test_regions.py
2016-10-24 23:39:25 Running test file: test/integration/smoke/test_reset_vm_on_reboot.py
2016-10-24 23:42:47 Running test file: test/integration/smoke/test_resource_detail.py
2016-10-24 23:43:00 Running test file: test/integration/smoke/test_router_dhcphosts.py
2016-10-24 23:47:42 Running test file: test/integration/smoke/test_routers_iptables_default_policy.py
2016-10-24 23:54:49 Running test file: test/integration/smoke/test_routers.py
2016-10-25 00:02:55 Running test file: test/integration/smoke/test_scale_vm.py
2016-10-25 00:06:15 Running test file: test/integration/smoke/test_secondary_storage.py
2016-10-25 00:06:18 Running test file: test/integration/smoke/test_service_offerings.py
2016-10-25 00:10:42 Running test file: test/integration/smoke/test_snapshots.py
2016-10-25 00:15:15 Running test file: test/integration/smoke/test_ssvm.py
2016-10-25 00:33:50 Running test file: test/integration/smoke/test_staticroles.py
2016-10-25 00:34:31 Running test file: test/integration/smoke/test_templates.py
2016-10-25 00:50:07 Running test file: test/integration/smoke/test_usage_events.py
2016-10-25 00:50:08 Running test file: test/integration/smoke/test_vm_life_cycle.py
2016-10-25 01:05:18 Running test file: test/integration/smoke/test_vm_snapshots.py
2016-10-25 01:20:58 Running test file: test/integration/smoke/test_volumes.py
2016-10-25 01:38:21 Running test file: test/integration/smoke/test_vpc_vpn.py

Test to update a physical network and extend its vlan ... === TestName: test_extendPhysicalNetworkVlan | Status : SUCCESS ===
ok
Test Site 2 Site VPN Across redundant VPCs ... === TestName: test_01_redundant_vpc_site2site_vpn | Status : SUCCESS ===
ok
Test Remote Access VPN in VPC ... === TestName: test_01_vpc_remote_access_vpn | Status : SUCCESS ===
ok
Test Site 2 Site VPN Across VPCs ... === TestName: test_01_vpc_site2site_vpn | Status : SUCCESS ===
ok
Test to create service offering ... === TestName: test_01_create_service_offering | Status : SUCCESS ===
ok
Test to update existing service offering ... === TestName: test_02_edit_service_offering | Status : SUCCESS ===
ok
Test to delete service offering ... === TestName: test_03_delete_service_offering | Status : SUCCESS ===
ok
Test to change service to a small capacity ... === TestName: test_04_change_offering_small | Status : SUCCESS ===
ok
Test to deploy vm with a first fit offering ... === TestName: test_deployvm_firstfit | Status : SUCCESS ===
ok
Test deploy VMs using user concentrated planner ... === TestName: test_deployvm_userconcentrated | Status : SUCCESS ===
ok
Test deploy VMs using user dispersion planner ... === TestName: test_deployvm_userdispersing | Status : SUCCESS ===
ok
Test create public & private template ... === TestName: test_01_create_template | Status : SUCCESS ===
ok
Test when createTemplate is used to create templates having the same name all of them get ... === TestName: test_CreateTemplateWithDuplicateName | Status : SUCCESS ===
ok
Test Edit template ... === TestName: test_02_edit_template | Status : SUCCESS ===
ok
Test delete template ... === TestName: test_03_delete_template | Status : SUCCESS ===
ok
Test for extract template ... === TestName: test_04_extract_template | Status : SUCCESS ===
ok
Update & Test for template permissions ... === TestName: test_05_template_permissions | Status : SUCCESS ===
ok
Test for copy template from one zone to another ... SKIP: Not enough zones available to perform copy template
Test only public templates are visible to normal user ... === TestName: test_07_list_public_templates | Status : SUCCESS ===
ok
Test System templates are not visible to normal user ... === TestName: test_08_list_system_templates | Status : SUCCESS ===
ok
test update configuration setting at zone level scope ... === TestName: test_UpdateConfigParamWithScope | Status : SUCCESS ===
ok
Test create, assign, remove of an Internal LB with roundrobin http traffic to 3 vm's in a Single VPC ... === TestName: test_01_internallb_roundrobin_1VPC_3VM_HTTP_port80 | Status : SUCCESS ===
ok
Test create, assign, remove of an Internal LB with roundrobin http traffic to 3 vm's in a Redundant VPC ... === TestName: test_02_internallb_roundrobin_1RVPC_3VM_HTTP_port80 | Status : SUCCESS ===
ok
Test to verify access to loadbalancer haproxy admin stats page ... === TestName: test_03_vpc_internallb_haproxy_stats_on_all_interfaces | Status : SUCCESS ===
ok
Test to verify access to loadbalancer haproxy admin stats page ... === TestName: test_04_rvpc_internallb_haproxy_stats_on_all_interfaces | Status : SUCCESS ===
ok
Test volume detail ... === TestName: test_01_updatevolumedetail | Status : SUCCESS ===
ok
Test router internal basic zone ... === TestName: test_01_router_internal_basic | Status : SUCCESS ===
ok
Test router internal advanced zone ... === TestName: test_02_router_internal_adv | Status : SUCCESS ===
ok
Test restart network ... === TestName: test_03_restart_network_cleanup | Status : SUCCESS ===
ok
Test restart network without cleanup ... === TestName: test_04_restart_network_wo_cleanup | Status : SUCCESS ===
ok
Test router basic setup ... === TestName: test_05_router_basic | Status : SUCCESS ===
ok
Test router advanced setup ... === TestName: test_06_router_advanced | Status : SUCCESS ===
ok
Test stop router ... === TestName: test_07_stop_router | Status : SUCCESS ===
ok
Test start router ... === TestName: test_08_start_router | Status : SUCCESS ===
ok
Test reboot router ... === TestName: test_09_reboot_router | Status : SUCCESS ===
ok
Test Deploy Virtual Machine from ISO ... === TestName: test_deploy_vm_from_iso | Status : SUCCESS ===
ok
Test to add and update added nic to a virtual machine ... === TestName: test_01_nic | Status : SUCCESS ===
ok
Test scale virtual machine ... SKIP: Skipping scale VM operation because                    VMware tools are not installed on the VM
test DeployVM in anti-affinity groups for project ... === TestName: test_DeployVmAntiAffinityGroup_in_project | Status : SUCCESS ===
ok
Test Deploy Virtual Machine ... SKIP: Skipping test because suitable hypervisor/host not                    present
Test reset virtual machine on reboot ... === TestName: test_01_reset_vm_on_reboot | Status : SUCCESS ===
ok
test_create_pvlan_network (test_pvlan.TestPVLAN) ... === TestName: test_create_pvlan_network | Status : SUCCESS ===
ok
Test Volume creation for all Disk Offerings (incl. custom) ... === TestName: test_01_create_volume | Status : SUCCESS ===
ok
Attach a created Volume to a Running VM ... === TestName: test_02_attach_volume | Status : SUCCESS ===
ok
Download a Volume attached to a VM ... === TestName: test_03_download_attached_volume | Status : SUCCESS ===
ok
Delete a Volume attached to a VM ... === TestName: test_04_delete_attached_volume | Status : SUCCESS ===
ok
Detach a Volume attached to a VM ... === TestName: test_05_detach_volume | Status : SUCCESS ===
ok
Download a Volume unattached to an VM ... === TestName: test_06_download_detached_volume | Status : SUCCESS ===
ok
Test resize (negative) non-existent volume ... SKIP: Resize Volume is unsupported on VmWare and Hyper-V
Test resize a volume ... SKIP: Resize Volume is unsupported on VmWare and Hyper-V
Delete a Volume unattached to an VM ... === TestName: test_09_delete_detached_volume | Status : SUCCESS ===
ok
Test advanced zone virtual router ... === TestName: test_advZoneVirtualRouter | Status : SUCCESS ===
ok
Test Deploy Virtual Machine ... === TestName: test_deploy_vm | Status : SUCCESS ===
ok
Test Multiple Deploy Virtual Machine ... === TestName: test_deploy_vm_multiple | Status : SUCCESS ===
ok
Test Stop Virtual Machine ... === TestName: test_01_stop_vm | Status : SUCCESS ===
ok
Test Start Virtual Machine ... === TestName: test_02_start_vm | Status : SUCCESS ===
ok
Test Reboot Virtual Machine ... === TestName: test_03_reboot_vm | Status : SUCCESS ===
ok
Test destroy Virtual Machine ... === TestName: test_06_destroy_vm | Status : SUCCESS ===
ok
Test recover Virtual Machine ... === TestName: test_07_restore_vm | Status : SUCCESS ===
ok
Test migrate VM ... === TestName: test_08_migrate_vm | Status : SUCCESS ===
ok
Test destroy(expunge) Virtual Machine ... === TestName: test_09_expunge_vm | Status : SUCCESS ===
ok
Test for attach and detach ISO to virtual machine ... === TestName: test_10_attachAndDetach_iso | Status : SUCCESS ===
ok
Test iptables default INPUT/FORWARD policy on RouterVM ... === TestName: test_02_routervm_iptables_policies | Status : SUCCESS ===
ok
Test iptables default INPUT/FORWARD policies on VPC router ... === TestName: test_01_single_VPC_iptables_policies | Status : SUCCESS ===
ok
Test guest vlan range dedication ... === TestName: test_dedicateGuestVlanRange | Status : SUCCESS ===
ok
Test userdata as GET, size > 2k ... === TestName: test_deployvm_userdata | Status : SUCCESS ===
ok
Test userdata as POST, size > 2k ... === TestName: test_deployvm_userdata_post | Status : SUCCESS ===
ok
Test create public & private ISO ... === TestName: test_01_create_iso | Status : SUCCESS ===
ok
Test Edit ISO ... === TestName: test_02_edit_iso | Status : SUCCESS ===
ok
Test delete ISO ... === TestName: test_03_delete_iso | Status : SUCCESS ===
ok
Test for extract ISO ... === TestName: test_04_extract_Iso | Status : SUCCESS ===
ok
Update & Test for ISO permissions ... === TestName: test_05_iso_permissions | Status : SUCCESS ===
ok
Test for copy ISO from one zone to another ... SKIP: Not enough zones available to perform copy template
Test delete ISO ... === TestName: test_07_list_default_iso | Status : SUCCESS ===
ok
Test for create region ... === TestName: test_createRegion | Status : SUCCESS ===
ok
Test for delete account ... === TestName: test_delete_account | Status : SUCCESS ===
ok
Test for port forwarding on source NAT ... === TestName: test_01_port_fwd_on_src_nat | Status : SUCCESS ===
ok
Test for port forwarding on non source NAT ... === TestName: test_02_port_fwd_on_non_src_nat | Status : SUCCESS ===
ok
Test for Associate/Disassociate public IP address for admin account ... === TestName: test_public_ip_admin_account | Status : SUCCESS ===
ok
Test for Associate/Disassociate public IP address for user account ... === TestName: test_public_ip_user_account | Status : SUCCESS ===
ok
Test for reboot router ... === TestName: test_reboot_router | Status : SUCCESS ===
ok
Test for release public IP address ... === TestName: test_releaseIP | Status : SUCCESS ===
ok
Test for Router rules for network rules on acquired public IP ... === TestName: test_network_rules_acquired_public_ip_1_static_nat_rule | Status : SUCCESS ===
ok
Test for Router rules for network rules on acquired public IP ... === TestName: test_network_rules_acquired_public_ip_2_nat_rule | Status : SUCCESS ===
ok
Test for Router rules for network rules on acquired public IP ... === TestName: test_network_rules_acquired_public_ip_3_Load_Balancer_Rule | Status : SUCCESS ===
ok
test_nic_secondaryip_add_remove (test_multipleips_per_nic.TestDeployVM) ... === TestName: test_nic_secondaryip_add_remove | Status : SUCCESS ===
ok
Test to create Load balancing rule with source NAT ... === TestName: test_01_create_lb_rule_src_nat | Status : SUCCESS ===
ok
Test to create Load balancing rule with non source NAT ... === TestName: test_02_create_lb_rule_non_nat | Status : SUCCESS ===
ok
Test for assign & removing load balancing rule ... === TestName: test_assign_and_removal_lb | Status : SUCCESS ===
ok
Test public IP range dedication ... === TestName: test_dedicatePublicIpRange | Status : SUCCESS ===
ok
Check the password file in the Router VM ... === TestName: test_isolate_network_password_server | Status : SUCCESS ===
ok
Test List secondary storage VMs ... === TestName: test_01_list_sec_storage_vm | Status : SUCCESS ===
ok
Test List console proxy VMs ... === TestName: test_02_list_cpvm_vm | Status : SUCCESS ===
ok
Test SSVM Internals ... === TestName: test_03_ssvm_internals | Status : SUCCESS ===
ok
Test CPVM Internals ... === TestName: test_04_cpvm_internals | Status : SUCCESS ===
ok
Test stop SSVM ... === TestName: test_05_stop_ssvm | Status : SUCCESS ===
ok
Test stop CPVM ... === TestName: test_06_stop_cpvm | Status : SUCCESS ===
ok
Test reboot SSVM ... === TestName: test_07_reboot_ssvm | Status : SUCCESS ===
ok
Test reboot CPVM ... === TestName: test_08_reboot_cpvm | Status : SUCCESS ===
ok
Test destroy SSVM ... === TestName: test_09_destroy_ssvm | Status : SUCCESS ===
ok
Test destroy CPVM ... === TestName: test_10_destroy_cpvm | Status : SUCCESS ===
ok
Test to ensure 4 default roles cannot be deleted ... SKIP: Dynamic Role-Based API checker not enabled, skipping test
Test to check role, role permissions and account life cycles ... SKIP: Dynamic Role-Based API checker not enabled, skipping test
Test for role-rule enforcement in case of multiple mgmt servers ... SKIP: Dynamic Role-Based API checker not enabled, skipping test
Test to ensure role in use cannot be deleted ... SKIP: Dynamic Role-Based API checker not enabled, skipping test
Tests normal lifecycle operations for roles ... SKIP: Dynamic Role-Based API checker not enabled, skipping test
Tests role update ... SKIP: Dynamic Role-Based API checker not enabled, skipping test
Tests that default four roles exist ... SKIP: Dynamic Role-Based API checker not enabled, skipping test
Tests role update ... SKIP: Dynamic Role-Based API checker not enabled, skipping test
Tests role update when role is in use by an account ... SKIP: Dynamic Role-Based API checker not enabled, skipping test
Tests concurrent order updation of role permission ... SKIP: Dynamic Role-Based API checker not enabled, skipping test
Tests creation of role permission ... SKIP: Dynamic Role-Based API checker not enabled, skipping test
Tests deletion of role permission ... SKIP: Dynamic Role-Based API checker not enabled, skipping test
Tests listing of default role's permission ... SKIP: Dynamic Role-Based API checker not enabled, skipping test
Tests order updation of role permission ... SKIP: Dynamic Role-Based API checker not enabled, skipping test
Test to acquire a provisioned public ip range ... === TestName: test_createPortablePublicIPAcquire | Status : SUCCESS ===
ok
Test to create a portable public ip range ... === TestName: test_createPortablePublicIPRange | Status : SUCCESS ===
ok
@Desc: Test that Volume snapshot for root volume is not allowed ... === TestName: test_01_test_vm_volume_snapshot | Status : SUCCESS ===
ok
Test to create VM snapshots ... === TestName: test_01_create_vm_snapshots | Status : SUCCESS ===
ok
Test to revert VM snapshots ... === TestName: test_02_revert_vm_snapshots | Status : SUCCESS ===
ok
Test to delete vm snapshots ... === TestName: test_03_delete_vm_snapshots | Status : SUCCESS ===
ok
Test deploy virtual machine with root resize ... === TestName: test_00_deploy_vm_root_resize | Status : SUCCESS ===
ok
Test proper failure to deploy virtual machine with rootdisksize of 0 ... === TestName: test_01_deploy_vm_root_resize | Status : SUCCESS ===
ok
Test proper failure to deploy virtual machine with rootdisksize less than template size ... === TestName: test_02_deploy_vm_root_resize | Status : SUCCESS ===
ok
Check that the /etc/dhcphosts.txt doesn't contain duplicate IPs ... === TestName: test_router_dhcphosts | Status : SUCCESS ===
ok
test DeployVM in anti-affinity groups ... === TestName: test_DeployVmAntiAffinityGroup | Status : SUCCESS ===
ok
# 1. Register a template for VMware with nicAdapter vmxnet3 ... SKIP: VCenter API Integration Remaining
Test network ACL lists and items in VPC ... === TestName: test_network_acl | Status : SUCCESS ===
ok
Tests allowed APIs for common account types ... === TestName: test_static_role_account_acls | Status : SUCCESS ===
ok
Test to create disk offering ... === TestName: test_01_create_disk_offering | Status : SUCCESS ===
ok
Test to create  a sparse type disk offering ... === TestName: test_02_create_sparse_type_disk_offering | Status : SUCCESS ===
ok
Test to create  a sparse type disk offering ... === TestName: test_04_create_fat_type_disk_offering | Status : SUCCESS ===
ok
Test to update existing disk offering ... === TestName: test_02_edit_disk_offering | Status : SUCCESS ===
ok
Test to delete disk offering ... === TestName: test_03_delete_disk_offering | Status : SUCCESS ===
ok
Test listing Volumes using 'ids' parameter ... === TestName: test_01_list_volumes | Status : SUCCESS ===
ok
Test listing Templates using 'ids' parameter ... === TestName: test_02_list_templates | Status : SUCCESS ===
ok
Test listing Snapshots using 'ids' parameter ... === TestName: test_03_list_snapshots | Status : SUCCESS ===
ok
Tests that SAML users are not allowed CloudStack local log in ... === TestName: login_test_saml_user | Status : SUCCESS ===
ok
test update configuration setting at storage scope ... === TestName: test_UpdateStorageOverProvisioningFactor | Status : SUCCESS ===
ok
Test primary storage pools - XEN. Not Supported for kvm,hyperv,vmware ... SKIP: iscsi primary storage not supported on kvm, VMWare, Hyper-V, or LXC
Test primary storage pools - XEN, KVM, VMWare. Not Supported for hyperv ... === TestName: test_01_primary_storage_nfs | Status : SUCCESS ===
ok
Test system VM start ... === TestName: test_01_sys_vm_start | Status : SUCCESS ===
ok
Test system templates are ready ... === TestName: test_02_sys_template_ready | Status : SUCCESS ===
ok
Test Snapshot Root Disk ... === TestName: test_01_snapshot_root_disk | Status : SUCCESS ===
ok

Ran 47 test files: 47 OK, 0 failed
```

**Comment by jburwell** [comment]
@blueorangutan test centos7 vmware55u3

**Comment by jburwell** [comment]
@rhtyd could you check into the status of the test run for this PR?

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan centos7 vmware-55u3

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware55u3

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-55u3

**Comment by serg38** [comment]
@rhtyd @karuturi All LGTM are in order. Can we merge this one?

**Pull request merged**
