### PR TITLE
cks: Fix when deployed on a nw without internet access

### PR DESCRIPTION
**Pull request by davidjumani**
### Description

Fixes the issue of CKS clusters not being able to come up in a network without internet access by :
- Loading the images in the k8s.io namespace
- Setting the sandbox image of containerd to the pause image required by the current kube version

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

TODO

### CODE REVIEW

**Review by rohityadavcloud — APPROVED** [review]

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Review by nvazquez — APPROVED** [review]

**Comment by davidjumani** [comment]
Env related failures. Have re-run the cks related tests, all passing

```
Test to check for failure while tying to upgrade a Kubernetes cluster to a lower version ... === TestName: test_01_invalid_upgrade_kubernetes_cluster | Status : SUCCESS ===
ok
Test to deploy a new Kubernetes cluster and upgrade it to newer version ... === TestName: test_02_upgrade_kubernetes_cluster | Status : SUCCESS ===
ok
Test to deploy a new Kubernetes cluster and check for failure while tying to scale it ... === TestName: test_03_deploy_and_scale_kubernetes_cluster | Status : SUCCESS ===
ok
Test to enable autoscaling a Kubernetes cluster ... === TestName: test_04_autoscale_kubernetes_cluster | Status : SUCCESS ===
ok
Test to deploy a new Kubernetes cluster ... === TestName: test_05_basic_lifecycle_kubernetes_cluster | Status : SUCCESS ===
ok
Test to delete an existing Kubernetes cluster ... === TestName: test_06_delete_kubernetes_cluster | Status : SUCCESS ===
ok
Test to deploy a new Kubernetes cluster ... === TestName: test_07_deploy_kubernetes_ha_cluster | Status : SUCCESS ===
ok
Test to upgrade a Kubernetes cluster to newer version ... === TestName: test_08_upgrade_kubernetes_ha_cluster | Status : SUCCESS ===
ok
Test to delete a HA Kubernetes cluster ... === TestName: test_09_delete_kubernetes_ha_cluster | Status : SUCCESS ===
ok

----------------------------------------------------------------------
XML: /root/results.xml
----------------------------------------------------------------------
Ran 9 tests in 1952.280s

OK
```

**Pull request merged**
