### PR TITLE
Upgrade Tomcat embed version

### PR DESCRIPTION
**Pull request by nvazquez**
### Description

This PR upgrades Tomcat embed version to the closest patched version according to the CVE
Fixes: #5969 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
tomcat is only used by rdpconsole. it has minor impact.
we can upgrade to latest tomcat 10.x or 8.5.75

**Comment by nvazquez** [comment]
I can explore the upgrade to 10.0.2 - choose 8.5.63 as its the closest patched version according to the CVE: https://github.com/advisories/GHSA-j39c-c8hj-x4j3

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@nvazquez 
do you know a way to test console proxy rdp client ?
it seems only available in hyperv environment.

**Comment by nvazquez** [comment]
No @weizhouapache - checked and it seems to be only hyperv as you said

**Review by weizhouapache — APPROVED** [review]
code lgtm
I have no chance to test rdp client for hyperv which is the only component using tomcat in cloudstack.

**Review by rohityadavcloud — APPROVED** [review]
Lgtm me need to check if this causes any regression in cpvm

**Comment by rohityadavcloud** [comment]
@nvazquez @weizhouapache this will require manual testing of console for the main three hypervisors

**Review by DaanHoogland — APPROVED** [review]

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Review by weizhouapache — APPROVED** [review]

**Comment by weizhouapache** [comment]
@blueorangutan test centos7 vmware-70u3 keepEnv

**Pull request merged**
