### PR TITLE
cleanup of unused code and cleanup of cleanup procedure

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR cleans up an integration  smoke test

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by sureshanaparti** [comment]
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
@blueorangutan test keepEnv

**Comment by rhtyd** [comment]
@blueorangutan package

**Review by GabrielBrascher — APPROVED** [review]
Looks Good. Not many risks with these tests cleanups and the previous Trillian test result looks good.

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Review by sureshanaparti — APPROVED** [review]
cleanup code lgtm

**Comment by sureshanaparti** [comment]
@blueorangutan test keepEnv

**Comment by sureshanaparti** [comment]
Verified the modified test results, looks good.

**Pull request merged**
