### PR TITLE
ui: fix user create featured template from volume

### LINKED ISSUE #9241: Users have the permission to create featured templates
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Template
~~~

##### CLOUDSTACK VERSION

~~~
4.19
~~~

##### CONFIGURATION

A new cloudstack deployment with advanced networking, kvm for compute, nfs for secondary storage, ceph for primary storage

##### OS / ENVIRONMENT

ubuntu server 22.04 for all servers, kvm, management and storage

##### SUMMARY

On the cloudstack documentation, it specifies that `Only an administrator can make a Template Featured.`, that holds true for the most part, in a way that for users with User and Domain admin role the featured checkbox when registering a template or ISO isn't visible. But when users with the above roles try to create a template from an existing volume they are given the permission to make the template a featured one.

##### STEPS TO REPRODUCE

~~~
1. Create an instance with a root disk
2. Stop the instance and navigate to it's volume
3. Click on create template from volume button
4. Here whether you are a root admin, domain admin, or user you will see the featured option and you are able to set the template as featured
~~~

##### EXPECTED RESULTS

~~~
for users with the User role the featured option should not be visible and the user shouldn't have the permission to set a template featured
~~~

##### ACTUAL RESULTS

~~~
users with the User role can set the featured option, and it will allow them to create a featured template that is 
~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #9241

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan ui

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@shwstppr , I tried in qa but see no featured field: 

with change it looks good but without (qa without PR uri) it looks the same. Any extra condition I am missing maybe?
image

**Review by rohityadavcloud — APPROVED** [review]

**Comment by shwstppr** [comment]
@DaanHoogland I was able to see featured selection option in UI without fix in QA server.
Go to ROOT volume of a stopped VM and create template option.

Before:
Screenshot from 2024-06-18 13-36-10


After:
image

**Comment by DaanHoogland** [comment]
ok @shwstppr , probably I'm creating the wrong template. I'll try again.

**Comment by DaanHoogland** [comment]
indeed I think I was at the wrong location. however the create template from volume works in the before situation and not in the PR specific code. 
image
pressing it gives no popup. I tried with clear cache and in private window. Also I tried edge and chrome.

**Comment by shwstppr** [comment]
@DaanHoogland there was a js error earlier. I forgot to kick UI build

@blueorangutan ui

**Review by DaanHoogland — APPROVED** [review]
verified to work

**Pull request merged**
