### PR TITLE
userdata: fix append scenarios

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

- Fixes case of appending userdata when both template and vm data are either shellscript or cloudconfig
- Fixes error when appending gzip userdata
- Fixes case when userdata manual text from VM is not getting decoded-encoded correctly.
- Fixes case of appending multipart data when both template and vm data contain same format types.
- Refactor - moved validateUserData method to UserDataManager class
- Refactor userdata test to check resultant multipart userdata thoroughly

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Review by harikrishna-patnala — COMMENTED** [review]
code LGTM.

@shwstppr can we target this to 4.18.1 ?

**Comment by shwstppr** [comment]
@harikrishna-patnala based it on `main` as https://github.com/apache/cloudstack/pull/7643 was merged on main

**Review by harikrishna-patnala — APPROVED** [review]
Code LGTM, did not test it though

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Review by kiranchavala — APPROVED** [review]
LGTM, manually tested all the possible scenarios 


| Registerd Userdata1 format | Registered   Userdata2 format | Vm-userdata | Content   of userdata | Result | Comments |
|---|---|---|---|---|---|
| Cloud-config   (text/cloud-config) |   |   | Plain text | Pass |   |
| Cloud-config   (text/cloud-config) | Shellscript |   | Mime   type  | Pass |   |
| Shell   script | Cloud-config   (text/cloud-config) |   | Mime   type  | Pass |   |
| Cloud-config   (text/cloud-config) | gzip   (user-data) |   |   | Pass | Error attempting to merge user data as a multipart user data.   Reason: Gzipped user data can not be used together with other user data   formats |
| gzip   (user-data) |   |   | Gzip data | Pass |   |
|   |   | Cloud-config   (mimetype) | Mime type |   |   |
| Cloud-config   (mimetype) |   |   | Mime type | Pass |   |
|   |   |   |   |   |   |
| Cloud-config   (mimetype) | gzip   (user-data) |   |   | Pass | Error attempting to merge user data as a multipart user data.   Reason: Gzipped user data can not be used together with other user data   formats |
| Shell   script  | gzip   (user-data) |   |   | Pass | Error attempting to merge user data as a multipart user data.   Reason: Gzipped user data can not be used together with other user data   formats |
| Cloud-config   (mimetype) | Shell   script  |   | Mime type | Pass |   |
| Shell   script  |   | Cloud-config   (mimetype) |   | Pass |   |
|   |   |   |   |   |   |
| Cloud-config   (text/cloud-config) | Cloud-config   (text/cloud-config) |   | Plain text | Pass |   |
| Cloud-config   (text/cloud-config) |   | Cloud-config   (text/cloud-config) | Plain text | Pass |   |
| Cloud-config   (text/cloud-config) |   | Shell   script (directly pasting in the UI ) | Mime   type  | Pass |   |
| Shell   script  |   | Cloud-config   (text/cloud-config)directly pasting in the UI | Mime   type  | Pass |   |
| Cloud-config   (mimetype) | Cloud-config   (mimetype) |   | Mime type | Pass |   |

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by kiranchavala** [comment]
@blueorangutan test

**Review by harikrishna-patnala — APPROVED** [review]
Code LGTM

**Pull request merged**
