### PR TITLE
ui: fix columns for exportacls csv

### LINKED ISSUE #8862: Export ACL List is missing some data
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
Improvement Request (UI, Functionality)
~~~

##### CLOUDSTACK VERSION

~~~
4.19
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Note: This ticket is broken down as requested from the origianl post, https://github.com/apache/cloudstack/issues/8841

**Export ACL List is missing some data**

- For example, 'Ports' are not available in the exported CSV when exported.
- There may be others that are missing from the CSV output too.
- Exporting the full list as CV makes it very convenient to study, review the rules all at one go using excel. 
- If it paired together with 'Import ACL from CSV' https://github.com/apache/cloudstack/issues/8858 , it would make ACL much easier to use all round.

##### STEPS TO REPRODUCE

N/A

~~~
N/A
~~~

##### EXPECTED RESULTS

~~~
To be able to manage ACL Rules more easily for large scale projects
~~~

##### ACTUAL RESULTS

~~~
Challenging to use ACL rules for large scale projects.
~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #8862

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):
ACL rules
image

CSV
image

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan ui

**Comment by weizhouapache** [comment]
thanks @shwstppr 

tested on https://qa.cloudstack.cloud/simulator/pr/9118/#/acllist/5f3185d4-4b78-4cc1-83fd-2fe141f730f2?tab=acl.list.rules
it looks startport and endport are missing
image

**Comment by shwstppr** [comment]
@weizhouapache should be fixed now

image


@blueorangutan ui

**Comment by weizhouapache** [comment]
thanks @shwstppr 

it works now

image

**Review by weizhouapache — APPROVED** [review]

**Review by vishesh92 — APPROVED** [review]
clgtm

**Pull request merged**
