### PR TITLE
Fix for an issue introduced in this commit: 336df84f1787de962a67d0a34…

### PR DESCRIPTION
**Pull request by mike-tutkowski**
…551f9027303040e and also a fix for VMware + managed storage

### CODE REVIEW

**Comment by mike-tutkowski** [comment]
All managed-storage tests pass successfully:

TestAddRemoveHosts.py:

test_add_remove_host_with_solidfire_plugin_1 (TestAddRemoveHosts.TestAddRemoveHosts) ... === TestName: test_add_remove_host_with_solidfire_plugin_1 | Status : SUCCESS ===
ok
test_add_remove_host_with_solidfire_plugin_2 (TestAddRemoveHosts.TestAddRemoveHosts) ... === TestName: test_add_remove_host_with_solidfire_plugin_2 | Status : SUCCESS ===
ok
test_add_remove_host_with_solidfire_plugin_3 (TestAddRemoveHosts.TestAddRemoveHosts) ... === TestName: test_add_remove_host_with_solidfire_plugin_3 | Status : SUCCESS ===
ok
test_add_remove_host_with_solidfire_plugin_4 (TestAddRemoveHosts.TestAddRemoveHosts) ... === TestName: test_add_remove_host_with_solidfire_plugin_4 | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 4 tests in 3036.238s

OK

TestManagedSystemVMs.py:

test_01_create_system_vms_on_managed_storage (TestManagedSystemVMs.TestManagedSystemVMs) ... === TestName: test_01_create_system_vms_on_managed_storage | Status : SUCCESS ===
ok
test_02_failure_to_create_service_offering_with_customized_iops (TestManagedSystemVMs.TestManagedSystemVMs) ... === TestName: test_02_failure_to_create_service_offering_with_customized_iops | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 2 tests in 1864.418s

OK

TestVMMigrationWithStorage.py:

test_01_storage_migrate_root_and_data_disks (TestVMMigrationWithStorage.TestVMMigrationWithStorage) ... === TestName: test_01_storage_migrate_root_and_data_disks | Status : SUCCESS ===
ok
test_02_storage_migrate_root_and_data_disks (TestVMMigrationWithStorage.TestVMMigrationWithStorage) ... === TestName: test_02_storage_migrate_root_and_data_disks | Status : SUCCESS ===
ok
test_03_storage_migrate_root_and_data_disks_fail (TestVMMigrationWithStorage.TestVMMigrationWithStorage) ... === TestName: test_03_storage_migrate_root_and_data_disks_fail | Status : SUCCESS ===
ok
test_04_storage_migrate_root_disk_fails (TestVMMigrationWithStorage.TestVMMigrationWithStorage) ... === TestName: test_04_storage_migrate_root_disk_fails | Status : SUCCESS ===
ok
test_05_storage_migrate_data_disk_fails (TestVMMigrationWithStorage.TestVMMigrationWithStorage) ... === TestName: test_05_storage_migrate_data_disk_fails | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 5 tests in 2346.416s

OK

TestVMSnapshots.py:

test_01_take_VM_snapshot (TestVMSnapshots.TestVMSnapshots) ... === TestName: test_01_take_VM_snapshot | Status : SUCCESS ===
ok
test_02_take_VM_snapshot_with_data_disk (TestVMSnapshots.TestVMSnapshots) ... === TestName: test_02_take_VM_snapshot_with_data_disk | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 2 tests in 869.646s

OK

TestVolumes.py (no resign):

test_00_check_template_cache (TestVolumes.TestVolumes) ... === TestName: test_00_check_template_cache | Status : SUCCESS ===
ok
Attach a volume to a stopped virtual machine, then start VM ... === TestName: test_01_attach_new_volume_to_stopped_VM | Status : SUCCESS ===
ok
Attach, detach, and attach volume to a running VM ... === TestName: test_02_attach_detach_attach_volume | Status : SUCCESS ===
ok
Attach volume to running VM, then reboot. ... === TestName: test_03_attached_volume_reboot_VM | Status : SUCCESS ===
ok
Detach volume from a running VM, then reboot. ... === TestName: test_04_detach_volume_reboot | Status : SUCCESS ===
ok
Detach volume from a stopped VM, then start. ... === TestName: test_05_detach_vol_stopped_VM_start | Status : SUCCESS ===
ok
Attach a volume to a stopped virtual machine, then start VM ... === TestName: test_06_attach_volume_to_stopped_VM | Status : SUCCESS ===
ok
Destroy and expunge VM with attached volume ... === TestName: test_07_destroy_expunge_VM_with_volume | Status : SUCCESS ===
ok
Delete volume that was attached to a VM and is detached now ... === TestName: test_08_delete_volume_was_attached | Status : SUCCESS ===
ok
Attach a data disk to a VM in one account and attach another data disk to a VM in another account ... === TestName: test_09_attach_volumes_multiple_accounts | Status : SUCCESS ===
ok
Attach more than one disk to a VM ... === TestName: test_10_attach_more_than_one_disk_to_VM | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 11 tests in 1326.838s

OK

TestVolumes.py (resign):

test_00_check_template_cache (TestVolumes.TestVolumes) ... === TestName: test_00_check_template_cache | Status : SUCCESS ===
ok
Attach a volume to a stopped virtual machine, then start VM ... === TestName: test_01_attach_new_volume_to_stopped_VM | Status : SUCCESS ===
ok
Attach, detach, and attach volume to a running VM ... === TestName: test_02_attach_detach_attach_volume | Status : SUCCESS ===
ok
Attach volume to running VM, then reboot. ... === TestName: test_03_attached_volume_reboot_VM | Status : SUCCESS ===
ok
Detach volume from a running VM, then reboot. ... === TestName: test_04_detach_volume_reboot | Status : SUCCESS ===
ok
Detach volume from a stopped VM, then start. ... === TestName: test_05_detach_vol_stopped_VM_start | Status : SUCCESS ===
ok
Attach a volume to a stopped virtual machine, then start VM ... === TestName: test_06_attach_volume_to_stopped_VM | Status : SUCCESS ===
ok
Destroy and expunge VM with attached volume ... === TestName: test_07_destroy_expunge_VM_with_volume | Status : SUCCESS ===
ok
Delete volume that was attached to a VM and is detached now ... === TestName: test_08_delete_volume_was_attached | Status : SUCCESS ===
ok
Attach a data disk to a VM in one account and attach another data disk to a VM in another account ... === TestName: test_09_attach_volumes_multiple_accounts | Status : SUCCESS ===
ok
Attach more than one disk to a VM ... === TestName: test_10_attach_more_than_one_disk_to_VM | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 11 tests in 1547.541s

OK

TestSnapshots.py (environment issued caused a failure in two tests, which I ran again and they passed):

test_01_create_volume_snapshot_using_sf_snapshot (TestSnapshots.TestSnapshots) ... === TestName: test_01_create_volume_snapshot_using_sf_snapshot | Status : SUCCESS ===
ok
test_02_create_volume_snapshot_using_sf_volume (TestSnapshots.TestSnapshots) ... === TestName: test_02_create_volume_snapshot_using_sf_volume | Status : SUCCESS ===
ok
test_03_create_volume_snapshot_using_sf_volume_and_sf_snapshot (TestSnapshots.TestSnapshots) ... === TestName: test_03_create_volume_snapshot_using_sf_volume_and_sf_snapshot | Status : EXCEPTION ===
ERROR
test_04_create_volume_snapshot_using_sf_snapshot_and_archiving (TestSnapshots.TestSnapshots) ... === TestName: test_04_create_volume_snapshot_using_sf_snapshot_and_archiving | Status : EXCEPTION ===
ERROR
test_05_create_volume_snapshot_using_sf_snapshot_and_revert_volume_to_snapshot (TestSnapshots.TestSnapshots) ... === TestName: test_05_create_volume_snapshot_using_sf_snapshot_and_revert_volume_to_snapshot | Status : SUCCESS ===
ok

Re-run of the two tests that failed for environmental reasons (now passed):

test_03_create_volume_snapshot_using_sf_volume_and_sf_snapshot (TestSnapshots.TestSnapshots) ... === TestName: test_03_create_volume_snapshot_using_sf_volume_and_sf_snapshot | Status : SUCCESS ===
ok
test_04_create_volume_snapshot_using_sf_snapshot_and_archiving (TestSnapshots.TestSnapshots) ... === TestName: test_04_create_volume_snapshot_using_sf_snapshot_and_archiving | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 2 tests in 2952.535s

OK

**Comment by wido** [comment]
Can't really say much about the code, but @karuturi , could you take a look? As this is a -1 by Mike now.

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by karuturi** [comment]
need another LGTM. @borisstoyanov @rhtyd @anshul-gangwar Can you review?

**Comment by karuturi** [comment]
@mike-tutkowski 
I see some failures in the posted test results. Are they related?
test_03_create_volume_snapshot_using_sf_volume_and_sf_snapshot (TestSnapshots.TestSnapshots) ... === TestName: test_03_create_volume_snapshot_using_sf_volume_and_sf_snapshot | Status : EXCEPTION ===
ERROR
test_04_create_volume_snapshot_using_sf_snapshot_and_archiving (TestSnapshots.TestSnapshots) ... === TestName: test_04_create_volume_snapshot_using_sf_snapshot_and_archiving | Status : EXCEPTION ===
ERROR

**Comment by anshul1886** [comment]
code LGTM.
My bad missed the managed storage part.

**Comment by rhtyd** [comment]
Should n't this be targeted against master? /cc @mike-tutkowski

**Comment by mike-tutkowski** [comment]
Hi @karuturi - Yeah, I had noted those failed for environmental reasons. I had re-run them successfully. Here is a copy/paste from above:

Re-run of the two tests that failed for environmental reasons (now passed):

test_03_create_volume_snapshot_using_sf_volume_and_sf_snapshot (TestSnapshots.TestSnapshots) ... === TestName: test_03_create_volume_snapshot_using_sf_volume_and_sf_snapshot | Status : SUCCESS ===
ok
test_04_create_volume_snapshot_using_sf_snapshot_and_archiving (TestSnapshots.TestSnapshots) ... === TestName: test_04_create_volume_snapshot_using_sf_snapshot_and_archiving | Status : SUCCESS ===
ok

**Comment by karuturi** [comment]
@mike-tutkowski Can you rebase this to master?

**Comment by mike-tutkowski** [comment]
I created the following new PR against master (and referenced the old one in it): https://github.com/apache/cloudstack/pull/2147

**Pull request closed without merging**
