### PR TITLE
Use MegaLinter for better performances

### PR DESCRIPTION
**Pull request by nvuillam**
### Description

A simple test to compare performances between SuperLinter and [MegaLinter,](https://megalinter.github.io/latest/) with the same scope

SuperLinter: 12mn -> https://github.com/apache/cloudstack/runs/5793039795?check_suite_focus=true
MegaLinter: 2mn -> https://github.com/nvuillam/cloudstack/runs/5795833342?check_suite_focus=true

As this PR was unsollicited, please feel free to refuse it, no problem :)

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### CODE REVIEW

**Comment by nvazquez** [comment]
Thanks for the PR @nvuillam - @jbampton can I please get your feedback/review on this PR?

**Comment by jbampton** [comment]
Seems `GitHub` make the Super-Linter so from the Apache Infra page it is allowed.  I am not sure whether the Mega-Linter is allowed.  Anyway from what I have heard the Mega-Linter is faster.

From the `infra` page:

"Notice: December 27, 2020: We only allow Actions that are official "Made by GitHub" or local to the Apache org on GitHub, to address a potential security vulnerability. This is an incident-related policy change. We are researching the situation, and the policy may evolve based on what we learn."

https://infra.apache.org/github-actions-secrets.html

https://github.com/github/super-linter
https://github.com/megalinter/megalinter

https://github.com/marketplace/actions/super-linter
https://github.com/marketplace/actions/megalinter

**Review by weizhouapache — COMMENTED** [review]
I would prefer to use the official linter from `github`
(12 minutes is acceptable to me)

just my opinion.

**Comment by nvuillam** [comment]
No problem, it was mainly to check performances :)
Have a good day :)

**Pull request closed without merging**
