### PR TITLE
CLOUDSTACK-9322: Support for Internal LB fuctionality with Nuage VSP SDN Plugin including Marvin test coverage

### PR DESCRIPTION
**Pull request by prashanthvarma**
Task: https://issues.apache.org/jira/browse/CLOUDSTACK-9322

PR contents:
1) UI changes to support LB provider “InternalLbVm” during VPC offering creation.
2) Bug fix for CLOUDSTACK-9320.
3) Nuage VSP SDN Plugin related enhancements for VPC network functionality.
4) Marvin test coverage for Internal LB support on master with Nuage VSP SDN Plugin.
5) Enhancements on our exiting Marvin test code (nuagevsp plugins directory).
6) PEP8 & PyFlakes compliance with our Marvin test code.

Test run:
CloudStack$ nosetests --with-marvin --marvin-config=nuage_ant.cfg test/integration/plugins/nuagevsp/ -a tags=nuagevsp

Test results:
Test user data and password reset functionality with Nuage VSP SDN plugin ... === TestName: test_nuage_UserDataPasswordReset | Status : SUCCESS ===
ok
Test Nuage VSP VPC Offering with different combinations of LB service providers ... === TestName: test_01_nuage_internallb_vpc_Offering | Status : SUCCESS ===
ok
Test Nuage VSP VPC Network Offering with and without Internal LB service ... === TestName: test_02_nuage_internallb_vpc_network_offering | Status : SUCCESS ===
ok
Test Nuage VSP VPC Networks with and without Internal LB service ... === TestName: test_03_nuage_internallb_vpc_networks | Status : SUCCESS ===
ok
Test Nuage VSP VPC Internal LB functionality with different combinations of Internal LB rules ... === TestName: test_04_nuage_internallb_rules | Status : SUCCESS ===
ok
Test Nuage VSP VPC Internal LB functionality by performing (wget) traffic tests within a VPC ... === TestName: test_05_nuage_internallb_traffic | Status : SUCCESS ===
ok
Test Nuage VSP VPC Internal LB functionality with different LB algorithms by performing (wget) traffic tests ... === TestName: test_06_nuage_internallb_algorithms_traffic | Status : SUCCESS ===
ok
Test Nuage VSP VPC Internal LB functionality with restarts of VPC network components by performing (wget) ... === TestName: test_07_nuage_internallb_vpc_network_restarts_traffic | Status : SUCCESS ===
ok
Test Nuage VSP VPC Internal LB functionality with InternalLbVm appliance operations by performing (wget) ... === TestName: test_08_nuage_internallb_appliance_operations_traffic | Status : SUCCESS ===
ok
Test Basic VPC Network Functionality with Nuage VSP SDN plugin ... === TestName: test_nuage_vpc_network | Status : SUCCESS ===
ok
Test Nuage VSP SDN plugin with basic Isolated Network functionality ... === TestName: test_nuage_vsp | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 11 tests in 12094.705s

OK

Test run logs:
[results.txt](https://github.com/apache/cloudstack/files/187587/results.txt)
[runinfo.txt](https://github.com/apache/cloudstack/files/187588/runinfo.txt)

Test config file:
[nuage_ant.txt](https://github.com/apache/cloudstack/files/222711/nuage_ant.txt)

Note: Attached the Marvin config file as .txt instead of .cfg.

PEP8 & PyFlakes Compliance:
CloudStack$ pep8 --max-line-length=150 test/integration/plugins/nuagevsp/*.py
CloudStack$ pyflakes test/integration/plugins/nuagevsp/nuageTestCase.py
CloudStack$ pyflakes test/integration/plugins/nuagevsp/test_nuage_password_reset.py
CloudStack$ pyflakes test/integration/plugins/nuagevsp/test_nuage_vpc_internal_lb.py
CloudStack$ pyflakes test/integration/plugins/nuagevsp/test_nuage_vpc_network.py
CloudStack$ pyflakes test/integration/plugins/nuagevsp/test_nuage_vsp.py
CloudStack$ pyflakes test/integration/plugins/nuagevsp/*.py

#CLOUDSTACK-9322

### CODE REVIEW

**Comment by pedro-martins** [comment]
Hi @prashanthvarma.

How about to use String.format() to create the strings in the loggers? The use of String format will turn the strings in the logs more legible.

Also, at line 344, could you use Collection.isEmpty(internalLbVms) instead of "internalLbVms == null || internalLbVms.isEmpty()" ?

Ty.

**Comment by nlivens** [comment]
@pedro-martins Updated the PR

**Comment by pedro-martins** [comment]
@nlivens great! And sorry for the delay =)
I saw that you used the String.format as I suggested, but and about the using of CollectionUtils.isEmpty() in the class org.apache.cloudstack.network.element.InternalLoadBalancerElement.java at line 344? Did you don't like the suggestion or you just has forgotten to change?

Thanks !

**Comment by nlivens** [comment]
@pedro-martins, I do like it, but we didn't change that code, we just restructured it a bit so I didn't want to touch the original code, I can still make that change though, that's not an issue :)

**Comment by KrisSterckx** [comment]
Hi @DaanHoogland  is this PR still in the candidate list of 4.9.0 ?

If there is anything that I & the team can facilitate in doing, pls let me know.

Thanks, Kris

**Comment by DaanHoogland** [comment]
@KrisSterckx I think so but not sure. @swill can you put this in?

**Comment by swill** [comment]
It seems to be in pretty good order.  I would like some code reviews and since there are changes to logic outside of the tests, I would like a full CI run against it.  @DaanHoogland are you setup to run at least the networking stuff against this?

**Comment by DaanHoogland** [comment]
started the suite now but keep in mind that no sdn specific tests are done in it, @swill

**Comment by DaanHoogland** [comment]
did the tests and again two failures, replay succeeded

[1452.results.network.txt](https://github.com/apache/cloudstack/files/222681/1452.results.network.txt)
[1452.results.vpc_routers.txt](https://github.com/apache/cloudstack/files/222683/1452.results.vpc_routers.txt)

[1452.results.routers_network_ops.txt](https://github.com/apache/cloudstack/files/222682/1452.results.routers_network_ops.txt)

```
# ssh 192.168.23.5
The authenticity of host '192.168.23.5 (192.168.23.5)' can't be established.
ECDSA key fingerprint is a6:38:aa:5b:07:f9:53:8c:c0:57:19:c7:8f:e4:f1:a7.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '192.168.23.5' (ECDSA) to the list of known hosts.
root@192.168.23.5's password: 
# ping -c 3 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=46 time=24.347 ms
64 bytes from 8.8.8.8: seq=1 ttl=46 time=23.389 ms
64 bytes from 8.8.8.8: seq=2 ttl=46 time=26.818 ms

--- 8.8.8.8 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 23.389/24.851/26.818 ms
```

**Comment by DaanHoogland** [comment]
@prashanthvarma  can you publish nuage_ant.cfg?

**Comment by prashanthvarma** [comment]
@DaanHoogland Sure, here is an example Nuage VSP SDN plugin specific Marvin tests config file contents:

{
    "zones": [
        {
            "name": "MyZone",
            "guestcidraddress": "10.1.1.0/24", 
            "dns2": "8.8.6.6", 
            "dns1": "10.10.0.10", 
            "physical_networks": [
                {
                    "broadcastdomainrange": "Zone", 
                    "isolationmethods": [
                        "VLAN"
                    ], 
                    "name": "Management Network", 
                    "traffictypes": [
                        {
                            "kvm": "mgmtbr0", 
                            "typ": "Management"
                        }, 
                        {
                            "kvm": "mgmtbr0", 
                            "typ": "Public"
                        }, 
                        {
                            "kvm": "mgmtbr0", 
                            "typ": "Storage"
                        }
                    ], 
                    "providers": [
                        {
                            "broadcastdomainrange": "ZONE", 
                            "name": "VirtualRouter"
                        }
                    ]
                }, 
                {
                    "broadcastdomainrange": "Zone", 
                    "isolationmethods": [
                        "VSP"
                    ], 
                    "name": "Nuage Network", 
                    "traffictypes": [
                        {
                            "kvm": "alubr0", 
                            "typ": "Guest"
                        }
                    ], 
                    "providers": [
                        {
                            "broadcastdomainrange": "ZONE", 
                            "name": "VirtualRouter"
                        }, 
                        {
                            "broadcastdomainrange": "ZONE", 
                            "name": "NuageVsp", 
                            "devices": [
                                {
                                    "username": "csproot", 
                                    "retryinterval": "60", 
                                    "hostname": "10.30.35.129",
                                    "apiversion": "v3_2", 
                                    "retrycount": "4", 
                                    "password": "csproot", 
                                    "port": 8443
                                }
                            ]
                        }, 
                        {
                            "broadcastdomainrange": "ZONE", 
                            "name": "VpcVirtualRouter"
                        }, 
                        {
                            "broadcastdomainrange": "ZONE", 
                            "name": "InternalLbVm"
                        }
                    ]
                }
            ], 
            "securitygroupenabled": "false", 
            "ipranges": [
                {
                    "startip": "10.29.1.1", 
                    "endip": "10.29.9.255", 
                    "netmask": "255.255.0.0", 
                    "gateway": "10.29.0.1"
                }
            ], 
            "networktype": "Advanced", 
            "pods": [
                {
                    "endip": "10.20.15.255", 
                    "name": "P0", 
                    "startip": "10.20.8.0", 
                    "netmask": "255.255.0.0", 
                    "clusters": [
                        {
                            "clustername": "P0C0", 
                            "hypervisor": "kvm", 
                            "hosts": [
                                {
                                    "username": "root", 
                                    "url": "http://test-kvm", 
                                    "password": "password"
                                }
                            ], 
                            "clustertype": "CloudManaged", 
                            "primaryStorages": [
                                {
                                    "url": "nfs://10.20.128.14/primary", 
                                    "name": "P0C0-primaryStorage"
                                }
                            ]
                        }
                    ], 
                    "gateway": "10.20.0.1"
                }
            ], 
            "internaldns1": "10.10.0.10", 
            "internaldns2": "", 
            "secondaryStorages": [
                {
                    "url": "nfs://10.20.128.14/secondary", 
                    "provider": "NFS"
                }
            ]
        }
    ], 
    "dbSvr": {
        "dbSvr": "csc-1",
        "passwd": "cloud", 
        "db": "cloud", 
        "port": 3306, 
        "user": "cloud"
    }, 
    "logger":
        {
            "LogFolderPath": "/tmp/"
        },
    "globalConfig": [
        {
            "name": "storage.cleanup.interval", 
            "value": "300"
        }, 
        {
            "name": "direct.agent.load.size", 
            "value": "1000"
        }, 
        {
            "name": "default.page.size", 
            "value": "10000"
        }, 
        {
            "name": "instance.name", 
            "value": "VM"
        }, 
        {
            "name": "workers", 
            "value": "10"
        }, 
        {
            "name": "vm.op.wait.interval", 
            "value": "5"
        }, 
        {
            "name": "account.cleanup.interval", 
            "value": "600"
        }, 
        {
            "name": "guest.domain.suffix", 
            "value": "test.d1c.nuagenetworks.net"
        }, 
        {
            "name": "expunge.delay", 
            "value": "60"
        }, 
        {
            "name": "vm.allocation.algorithm", 
            "value": "random"
        }, 
        {
            "name": "expunge.interval", 
            "value": "60"
        }, 
        {
            "name": "expunge.workers", 
            "value": "3"
        }, 
        {
            "name": "secstorage.allowed.internal.sites", 
            "value": "10.0.0.0/16"
        }, 
        {
            "name": "check.pod.cidrs", 
            "value": "true"
        }
    ], 
    "mgtSvr": [
        {
            "mgtSvrIp": "csc-1",
            "port": 8096,
            "user": "root",
            "passwd": "password"
        }
    ]
}

Let me know, if you need anything else from our side.

**Comment by DaanHoogland** [comment]
thanks @prashanthvarma , mostly usefull for users of your sdn solution. Hopefully some of them will test ;)

**Comment by prashanthvarma** [comment]
@DaanHoogland you are right, that is the main motive :). Let me know, if you want me to publish it elsewhere as well for easier user access.

Thank you !!

**Comment by DaanHoogland** [comment]
@prashanthvarma maybe you can incorporate it in the project dir for the plugin somehow. It seems to me to be the best place for it. maybe accompanied with a readme on how to install/test?

**Comment by DaanHoogland** [comment]
@swill LGTM based on testing and code walkthrough

**Comment by prashanthvarma** [comment]
@DaanHoogland That's a good suggestion. We will discuss on the optimal location in the plugin's project directory, and incorporate them in the next PR.

Thank you for the review and suggestions !!

**Comment by swill** [comment]
I think this is ready pending 1 more LGTM code review...

**Comment by DaanHoogland** [comment]
@pedro-martins can you live with the present state?

**Comment by prashanthvarma** [comment]
@DaanHoogland, We haven't heard from @pedro-martins in a while. Let's hope, he responds soon (or) someone form the community reviews our code.

**Comment by DaanHoogland** [comment]
@swill I think this one has enough LGTM and testing and the only question I see remaining has been answerred. @pedro-martins is not responded anymore so let's merge.

**Pull request merged**
