### PR TITLE
Fix rule duplication with static NAT rules

### PR DESCRIPTION
**Pull request by richardlawley**
## Description

The VR code has provision for inserting rules at the top or bottom by specifying "front" as the second parameter to `self.fw.append`.  However, there are a number of cases where someone has been unaware of this and added a rule with the pattern `self.fw.append(["mangle", "", "-I PREROUTING"...`.  This causes the code to check for the rule already being present to fail, and duplicate rules end up being added.

This PR fixes two of these cases which apply to adding static NAT rules.  I am aware of more of these cases, but I don't have the ability to easily test the outcome of fixing them.  I'm happy to add these in if you're confident that the automated tests will be sufficient.  Searching for "-I (case sensitive) finds these.

The [code for dealing with "front"](https://github.com/apache/cloudstack/blob/master/systemvm/debian/opt/cloud/bin/cs/CsNetfilter.py#L166) is included below to show that this shouldn't have any ill effects:

~~~
if fw[1] == "front":
    cpy = cpy.replace('-A', '-I')
~~~

Fixes: #3177 

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

Local tests were performed (see #3177 for details of symptoms), and we have had this fix deployed in production on advanced networks for a couple of months.

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Can you review this - @ustcweizhou @anuragaw @shwstppr ?
@blueorangutan package

**Comment by rhtyd** [comment]
Thanks for the PR @richardlawley - do you think it can cause regression when the VR has multiple public IPs (i.e multiple public nics) as this reverts changes from https://github.com/apache/cloudstack/commit/40d77460386342126fb5533a9139bf6d08137d1d

**Comment by rhtyd** [comment]
Nevermind I compared your changes with what Jayapal was trying to do, LGTM.

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by ustcweizhou** [comment]
I was just testing it. it works fine.

**Pull request merged**
