### PR TITLE
ui/quota: Make the quota UI plugin icon gray

### PR DESCRIPTION
**Pull request by bhaisaab**
Makes the quota ui plugin icon gray, based on comment at:
https://github.com/apache/cloudstack/pull/768#issuecomment-163364606

### CODE REVIEW

**Comment by bhaisaab** [comment]
cc @remibergsma @DaanHoogland

**Comment by borisroman** [comment]
@wilderrodrigues @remibergsma @DaanHoogland LGTM :+1: 

Better styling this way.

No unit or integration tests run. Though in this case I don't think it's necessary.

**Comment by wilderrodrigues** [comment]
I don't think it is. :D

Would be nice to see a review from a colour-blind person though. :D

LGTM

Cheers,
Wilder

**Comment by DaanHoogland** [comment]
I like angry fruit salads, how about a grey icon that colours all up on hovering?

serious? ok, i'm fine with both.

**Comment by remibergsma** [comment]
LGTM
screen shot 2015-12-10 at 14 50 08

**Pull request merged**
