### PR TITLE
UI: Make 'ACL' field as mandatory and add warning message for default_allow and default_deny

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR improves the user experience of ‘ACL’ field in the dialog of creating a new VPC tier on UI.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):

'ACL' is a mandatory field (no selection by default).

warning message is displayed for in-built ACL policies (default_allow and default_deny)

image

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan  ui

**Comment by Pearl1594** [comment]
@blueorangutan ui

**Comment by weizhouapache** [comment]
@blueorangutan help

**Comment by weizhouapache** [comment]
@blueorangutan build

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by Pearl1594 — APPROVED** [review]
LGTM

**Review by utchoang — APPROVED** [review]

**Review by GabrielBrascher — APPROVED** [review]
LGTM

**Review by davidjumani — APPROVED** [review]

**Review by vladimirpetrov — APPROVED** [review]
Tested with allow, deny and custom ACLs, also after upgrade - LGTM.

**Comment by alexandremattioli** [comment]
LGTM

**Pull request merged**
