### PR TITLE
Provide encryption key for DATA volume type (in addition to ROOT) to copy volume.

### PR DESCRIPTION
**Pull request by mprokopchuk**
ScaleIO plugin fails to migrate encrypted DATA Volume between clusters:
```
Unable to convert/copy from <REDACTED> to <REDACTED>, due to: qemu-img: Could not open 'file.filename=/dev/disk/by-id/emc-vol-<REDACTED>': Parameter 'encrypt.key-secret' is required for cipher].
	at org.apache.cloudstack.engine.orchestration.VolumeOrchestrator.migrateVolume(VolumeOrchestrator.java:1382)
	at org.apache.cloudstack.engine.orchestration.VolumeOrchestrator.storageMigration(VolumeOrchestrator.java:1493)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

Added change to provide passkey not only for ROOT but for DATA Volume as well.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### How Has This Been Tested?

Tested manually.

### CODE REVIEW

**Comment by mprokopchuk** [comment]
@blueorangutan test

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Review by rohityadavcloud — APPROVED** [review]

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by rohityadavcloud** [comment]
@JoaoJandre since this is a bugfix, causing failure when migrating encrypted DATA Volume between clusters - can we consider it?

**Comment by JoaoJandre** [comment]
@rohityadavcloud since it is a bugfix we can consider it. But we need the author to describe their tests and/or have some 3rd party testing.

**Comment by rohityadavcloud** [comment]
Thanks @JoaoJandre we've asked our @borisstoyanov to do some QA.

**Review by borisstoyanov — APPROVED** [review]
LGTM, 

Manually tested in and cross cluster migrations with PF of data and root volumes, also did regression test with normal volumes on PF and NFS (NFS migration of encrypted volumes is not possible at the moment). I think we should explore to enable NFS encrypted volumes migration in future as volume migration is essential feature IMHO.

**Pull request merged**
