### PR TITLE
WIP perform config drive creation on primary storage (CLOUDSTACK-10290)

### PR DESCRIPTION
**Pull request by DaanHoogland**
## Description
The present configdrive generation happens on secondary storage, which is also used in public facing functionality. For those that wnat it can be processed on primary storage. This will be optional for now as using localstorage will complicate things when migrating.

First phase is factoring out the config drive creation code into a separate project (done)
next it will be made available to the host agent (KVM only)
finally the decision to look for a primary storage to do the processing on will be implemented on the basis of a global setting.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

this is tested manually in a kvm env with a custom network offering that has everything in the VR except userdata. An isolated network created has been created using this offering. Finally a VM was succesfully deployed in this network.

## Checklist:

- [ ] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
Testing
- [ ] I have added tests to cover my changes.
- [ ] All relevant new and existing integration tests have passed.
- [ ] A full integration testsuite with all test that can run on my environment has passed.

### CODE REVIEW

**Comment by rhtyd** [comment]
This is still in WIP, we are not in a state to test/merge by end of this week so I'll move to 4.11.2.0. In case this change we can consider this for 4.11.1.0 before RC1 is cut.

**Comment by DaanHoogland** [comment]
@rhtyd this is an issue on 4.11 and needs to go in 4.11.1. If it is not done on release it is time to remove the milestone, not in advance.

**Comment by rhtyd** [comment]
@DaanHoogland is this ready for testing and review, as per our schedule we were hoping to cut RC1 starting next week (mid May) I'm cutting down on the scope and limiting to completed PRs and blockers. I'll re-add the milestone on your remark.

**Comment by GabrielBrascher** [comment]
@DaanHoogland @rhtyd Is this still a work in progress? I can help to review if it is ready for testing and review.

**Comment by DaanHoogland** [comment]
@GabrielBrascher it is not fully functional yet. I would like review.
The problem I am facing is that ConfigDrive is part of network configuration and no Primary storage is know yet before creating or (re-)starting a VM, so no where to create the ConfigDrive on. I need to solve that. Ideas welcome.

**Comment by rhtyd** [comment]
Rebased against latest 4.11 branch.

**Comment by GabrielBrascher** [comment]
@DaanHoogland I see your point. It is tricky indeed. If I can think of a design to help you I will ping you. A code review is on way as well.

**Comment by rhtyd** [comment]
This can be closed, new PR that is ready for review now: https://github.com/apache/cloudstack/pull/2651

**Pull request closed without merging**
