### PR TITLE
UI: Improve router listing page

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR fixes https://github.com/apache/cloudstack/issues/8008

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):
Before patch:
<details><summary>Details</summary>
<p>

image

</p>
</details> 

After patch:
<details><summary>Details</summary>
<p>

image

</p>
</details>

### CODE REVIEW

**Comment by vishesh92** [comment]
@blueorangutan ui

**Comment by vishesh92** [comment]
@blueorangutan ui

**Review by weizhouapache — APPROVED** [review]
the latest UI looks good to me

@vishesh92 @DaanHoogland

**Review by DaanHoogland — APPROVED** [review]

**Comment by vishesh92** [comment]
@blueorangutan ui

**Comment by DaanHoogland** [comment]
tested in qa

**Pull request merged**
