### PR TITLE
ui: Adding option to choose between name and displayname

### PR DESCRIPTION
**Pull request by davidjumani**
### Description
Adds an option to choose between name and displayname

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

### Screenshots (if appropriate):

Screenshot from 2021-06-01 15-43-17
Screenshot from 2021-06-01 15-43-24

### CODE REVIEW

**Comment by rhtyd** [comment]
-0 we need to ask what others thing. I like that unnecessary column can be toggled; but don't like the new toggle button (the nav bar is already crowded)

**Comment by DaanHoogland** [comment]
+0 but i agree with @rhtyd , is it possible to make the column header a drop down?

**Comment by davidjumani** [comment]
@DaanHoogland Will try but not sure that is natively supported. @utchoang Any idea how to have a table header cell with a dropdown ?

**Comment by utchoang** [comment]
@davidjumani 
I think you can try to use a custom header with the slot by image (1) and add 1 drop down similar to the header filter by image (2). Then catch the event and reload the table?

**Comment by davidjumani** [comment]
@DaanHoogland @rhtyd Would it be better to have an option to let the user select which columns to be displayed ? And any idea where to place it ?
General idea :

Screenshot from 2021-06-22 10-00-47

**Comment by DaanHoogland** [comment]
@davidjumani do we want to let the user configure this (in a cookie) on individual basis, and/or do we want to let the operator set restrictions?
your ui design looks good at first sight but a setting of defaults could work as well.

**Comment by davidjumani** [comment]
> @davidjumani do we want to let the user configure this (in a cookie) on individual basis, and/or do we want to let the operator set restrictions?
> your ui design looks good at first sight but a setting of defaults could work as well.

Yes, on a per user basis saved in the browser storage

**Comment by rhtyd** [comment]
I like the approach to allow users to select the columns they want to see, but it's still not necesary. Maybe useful for smaller screens such as mobiles. In my opinion this may be closed.

**Comment by rhtyd** [comment]
-1 let's discuss in dev@, the name and displayname may be used different cases by operators/providers; the list of columns are only huge for root admins and not normal users who are only shown a subset of the list of columns.

**Comment by nvazquez** [comment]
@davidjumani I'm removing it from the 4.16 milestone for now. Please discuss it in dev@ and add it back to the milestone if needed

**Comment by rhtyd** [comment]
I'm closing this @davidjumani kindly discuss on dev@ first and reopen in future if we can gather consensus. Thanks.

**Pull request closed without merging**
