### PR TITLE
UI: Fixes UI style on Microsoft Edge browser

### PR DESCRIPTION
**Pull request by utchoang**
### Description

This PR for fixes https://github.com/apache/cloudstack/issues/6787

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by DaanHoogland — COMMENTED** [review]
Code look good to me, but I´d really want a regular Edge user to try this.

**Review by rohityadavcloud — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@kohrar can you test this?

**Comment by kohrar** [comment]
@DaanHoogland That seemed to have done the trick! Thanks for this PR.

I do notice that there's a little discrepancy with the way the dropdown menu is being rendered. Sometimes it renders OK, but other times, the dropdown selection gets rendered on top of the dropdown element. I'm not sure what the correct terminology is, so forgive me. See the two screenshots below.

On a clean refresh or at (what seems to be) like at random times, it looks correct:
Screenshot 2022-10-03 112725

However, most of the time, just clicking on the dropdown causes the bottom to be chopped off and the selector gets rendered on top of the dropdown element:
Screenshot 2022-10-03 112707

Just clicking on / clicking away from the dropdown menu makes it render correctly maybe 20% of the time. I'm not sure why this is happening. This is not a huge issue since it's still functional, but thought I'd just bring this up.

**Comment by RodrigoDLopez** [comment]
I guess this is not the cause of the error seen. I have an env with the previous version of ACS, and I can not reproduce it.

furthermore, the proposed solution makes the listing stay above the menu, I think this is not the expected behavior (reproduced with the latest Firefox, Chromium, and Opera). The same behavior can be seen in the VPC view when you click to choose the page in the tabs `Public IP Address`, Ǹetwork ACL List`, `Private gateway`, `VPN connection`, `Virtual routers`, `Events`

**Comment by DaanHoogland** [comment]
> @DaanHoogland That seemed to have done the trick! Thanks for this PR.
> 
> I do notice that there's a little discrepancy with the way the dropdown menu is being rendered. Sometimes it renders OK, but other times, the dropdown selection gets rendered on top of the dropdown element. I'm not sure what the correct terminology is, so forgive me. See the two screenshots below.
> 
> On a clean refresh or at (what seems to be like) random times, it looks correct:
> Screenshot 2022-10-03 112725
> 
> However, most of the time, just clicking on the dropdown causes the bottom to be chopped off and the selector gets rendered on top of the dropdown element:
> Screenshot 2022-10-03 112707
> 
> Just clicking on / clicking away from the dropdown menu makes it render correctly maybe 20% of the time. I'm not sure why this is happening. This is not a huge issue since it's still functional, but thought I'd just bring this up.

@utchoang do you have an answer for @kohrar on this?

**Comment by utchoang** [comment]
> > @DaanHoogland That seemed to have done the trick! Thanks for this PR.
> > I do notice that there's a little discrepancy with the way the dropdown menu is being rendered. Sometimes it renders OK, but other times, the dropdown selection gets rendered on top of the dropdown element. I'm not sure what the correct terminology is, so forgive me. See the two screenshots below.
> > On a clean refresh or at (what seems to be like) random times, it looks correct:
> > Screenshot 2022-10-03 112725
> > However, most of the time, just clicking on the dropdown causes the bottom to be chopped off and the selector gets rendered on top of the dropdown element:
> > Screenshot 2022-10-03 112707
> > Just clicking on / clicking away from the dropdown menu makes it render correctly maybe 20% of the time. I'm not sure why this is happening. This is not a huge issue since it's still functional, but thought I'd just bring this up.
> 
> @utchoang do you have an answer for @kohrar on this?
This is the property of the ant-design plugin, it will auto-scale according to the screen height so I think it is not necessary to edit it.

**Comment by rohityadavcloud** [comment]
Thanks @kohrar for testing

**Pull request merged**
