### PR TITLE
CLOUDSTACK-9175: [VMware DRS] Adding new host to DRS cluster does not participate in load balancing.

### PR DESCRIPTION
**Pull request by sureshanaparti**
Summary: When a new host is added to a cluster, Cloudstack doesn't create all the port groups (created by cloudstack earlier in other hosts) present in the cluster. Since the new host doesn't have all the necessary networking port groups of cloudstack, it is not eligible to participate in DRS load balancing or HA.

Solution: When adding a host to the cluster in Cloudstack, use VMware API to find the list of unique port groups on a previously added host (older host in the cluster) if exists and then create them on the new host.

### CODE REVIEW

**Comment by resmo** [comment]
`older` is a bit misleading, what about `existent` e.g. findExistentHypervisorHostInCluster?

**Comment by sureshanaparti** [comment]
@resmo, Out of all the running hosts present in the cluster, the port groups are fetched from the host which was first added to the cloudstack, assuming that it has all the cloudstack created port groups. So existent may not be the right word. Any other?

**Comment by resmo** [comment]
@sureshanaparti  Ok, I see. then I would indeed use old but suggest `oldest` : `findExistentHypervisorHostInCluster`. Would you mind rebasing to get a clean PR without merge commits and reverts?

**Comment by sureshanaparti** [comment]
@resmo, You mean findOldestExistentHypervisorHostInCluster. I'm OK with it. 
Shall I create new PR without all these merges?

**Comment by resmo** [comment]
@sureshanaparti that would be great. appreciate your work on vmware parts!

**Comment by sureshanaparti** [comment]
@resmo Sure. I'll do that. Thanks.

**Comment by sureshanaparti** [comment]
@resmo Raised a clean PR: https://github.com/apache/cloudstack/pull/1257.
Shall I close this one?

**Comment by resmo** [comment]
since #1257 replaces this PR I would do so, yes.

**Comment by sureshanaparti** [comment]
@resmo ok sure. thanks!

**Comment by sureshanaparti** [comment]
@resmo  Shall I close this PR  (as #1257 replaces this one)?

**Comment by resmo** [comment]
@sureshanaparti yes, that would be great

**Comment by rhtyd** [comment]
@sureshanaparti can you rebase against latest master and share state of your PR, thanks; squash all changes into a single commit

tag:vmware-pickup

**Comment by bvbharatk** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 74
 Hypervisor xenserver
 NetworkType Advanced
 Passed=73
 Failed=0
 Skipped=3

_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/yj3wnzbceo9uef2/AAB6u-Iap-xztdm6jHX9SjPja?dl=0


**Failed tests:**

**Skipped tests:**
test_vm_nic_adapter_vmxnet3
test_static_role_account_acls
test_deploy_vgpu_enabled_vm

**Passed test suits:**
test_deploy_vm_with_userdata.py
test_affinity_groups_projects.py
test_portable_publicip.py
test_vpc_vpn.py
test_over_provisioning.py
test_global_settings.py
test_scale_vm.py
test_service_offerings.py
test_routers_iptables_default_policy.py
test_routers.py
test_reset_vm_on_reboot.py
test_snapshots.py
test_deploy_vms_with_varied_deploymentplanners.py
test_login.py
test_list_ids_parameter.py
test_public_ip_range.py
test_multipleips_per_nic.py
test_regions.py
test_affinity_groups.py
test_network_acl.py
test_pvlan.py
test_volumes.py
test_nic.py
test_deploy_vm_root_resize.py
test_resource_detail.py
test_secondary_storage.py
test_vm_life_cycle.py
test_disk_offerings.py

**Comment by sureshanaparti** [comment]
This PR is no longer valid since #1257 replaces this. Closing...

**Pull request closed without merging**
