### PR TITLE
CLOUDSTACK-8648: Do not configure the ImageFormat Processor when fetc…

### PR DESCRIPTION
**Pull request by wido**
…hing filesize

It will throw an exception and that's needed.

Also, make the log show about which file we are talking about

Signed-off-by: Wido den Hollander <wido@widodh.nl>

### CODE REVIEW

**Comment by karuturi** [comment]
while I agree with the code change based on the current implementations of getVirtualSize, should we just pass the storage layer in the params so that any new implementation if required can use the storage layer?
```
Map<String, Object> params = new HashMap<String, Object>();
params.put(StorageLayer.InstanceConfigKey, _storage);
processor.configure("template processor", new HashMap<String, Object>());
```

**Comment by wido** [comment]
Shouldn't we then pass "params" to the configure method? That seems to be missing in your example.

**Comment by karuturi** [comment]
yes. copy paste error :)

**Comment by karuturi** [comment]
Yes. Copy paste error :)

-----Original Message-----

**Comment by wido** [comment]
@karuturi Fixed that. See the new commit

**Comment by karuturi** [comment]
Thanks for the update. changes looks good :+1: 
Some unit/marvin tests would be good

**Comment by DaanHoogland** [comment]
LGTM

**Pull request closed without merging**
