### PR TITLE
Warn Basic network end of life

### PR DESCRIPTION
**Pull request by GabrielBrascher**
## Description

This PR addresses the discussion in the mailing list and at the PR #2720. The message warns that Basic network will no longer be supported on CloudStack 5.0.

Note that this pull request was submitted against CloudStack `4.11` as it will be added on 4.11.2. The proposed roadmap for Basic network end of life defines that users will not be able to create a basic network in 4.12 and should be warned about end of life on 4.11.2.

Documentation and release notes should be updated as well to warn the Basic network end of life.

The result of this PR can be seen in the following images when selecting the Basic network or Advanced network.

From a new CloudStack environment the user might be interested in going through the basic installation.
intro

In this case, he/she will be able to read a warn message and choose on proceeding or going back to the intro page.
warnbasicinstallationreduced

When creating a new zone in the "usual" way, the user will also be warned about basic network end of life.
addzonebasic

If the user click on the Advanced network checkbox, the warning message is hidden.
addzoneadvanced

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
Testing
- [ ] I have added tests to cover my changes.
- [ ] All relevant new and existing integration tests have passed.
- [ ] A full integration testsuite with all test that can run on my environment has passed.

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@GabrielBrascher @rafaelweingartner How about, "Basic networking functionality will be implemented as 'shared' network' in version post 5.0\nSelect advanced networking to configure this option."?
cc @rhtyd @PaulAngus @wido

**Comment by PaulAngus** [comment]
To be honest I'm not sure about such a message in general when there is no timetable to have a 5.0...

cc @rhtyd @PaulAngus @wido @rafaelweingartner @DaanHoogland

**Comment by rhtyd** [comment]
That's true, we don't have a timeline. I'll remove this PR from 4.11.2.0 milestone, depending on how everyone agrees we may/maynot include this in 4.11.2.0 but 4.12.0.0+.

**Comment by GabrielBrascher** [comment]
I am ok with both ways; might be better to change it to 4.12.

**Pull request closed without merging**
