### PR TITLE
UI: Add router links to notifications and show error description

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

Add router links to the notification list - which aids in traversing to the respective resource in case of failed jobs/ operations. This was added as part of #5034; however, during recent refactor of the UI around header notices, this minor enhancement was reverted. This PR also brings back the old behavior of showing the error description in the notification list so that one may not have to filter through events to see the reason for a failure

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Current Behavior:
image

#### New Behavior:
image

### CODE REVIEW

**Comment by Pearl1594** [comment]
@blueorangutan ui

**Comment by Pearl1594** [comment]
@blueorangutan ui

**Review by utchoang — APPROVED** [review]
LGTM!

**Review by nvazquez — APPROVED** [review]
LGTM thanks @Pearl1594, manually tested

**Pull request merged**
