### PR TITLE
component test ports/fixes in python3

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR fixes marvin component tests to run in ported marvin framework for python3

part of #3195

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [x] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

Work to do:

##### new failures in python3
- [x] test_egress_fw_rules.py
- [x] test_configdrive.py
- [x] test_lb_secondary_ip.py
- [x] test_deploy_vm_userdata_reg.py
- [x] test_multiple_ips_per_nic.py
- [x] test_ps_domain_limits.py
- [x] test_ps_limits.py
- [x] test_ps_resize_volume.py
- [x] test_snapshots.py
- [x] test_ss_max_limits.py
- [x] test_volume_destroy_recover.py
- [x] test_vpc_network_lbrules.py
- [x] test_vpc_network_pfrules.py
- [x] test_vpc_network.py
- [x] test_vpc_network_staticnatrule.py
- [x] test_vpc_offerings.py
- [x] test_vpc_on_host_maintenance.py

##### different results:
- [ ] test_configdrive.py
- [ ] test_ps_resource_limits_volume.py
- [ ] test_vpc_network_internal_lbrules.py
- [ ] test_vpc_network_pfrules.py
- [ ] test_vpc_network.py
- [ ] test_vpc_network_staticnatrule.py
- [ ] test_vpc_offerings.py

##### different times:
- [ ] test_egress_fw_rules.py
- [ ] test_add_remove_network.py
- [ ] test_affinity_groups_projects.py
- [ ] test_affinity_groups.py
- [ ] test_base_image_updation.py
- [ ] test_blocker_bugs.py
- [ ] test_implicit_planner.py
- [ ] test_browse_templates.py
- [ ] test_configdrive.py
- [ ] test_escalation_listTemplateDomainAdmin.py
- [ ] test_escalations_ipaddresses.py
- [ ] test_escalations_networks.py
- [ ] test_escalations_volumes.py
- [ ] test_escalations_vpncustomergateways.py
- [ ] test_multiple_public_interfaces.py
- [ ] test_organization_states.py
- [ ] test_persistent_networks.py
- [ ] test_portable_ip.py
- [ ] test_redundant_router_cleanups.py
- [ ] test_reset_ssh_keypair.py
- [ ] test_rootvolume_resize.py
- [ ] test_shared_networks.py
- [ ] test_snapshots.py
- [ ] test_ss_limits.py
- [ ] test_ss_max_limits.py
- [ ] test_ss_project_limits.py
- [ ] test_stopped_vm.py
- [ ] test_storage_motion.py
- [ ] test_tags.py
- [ ] test_volumes.py
- [ ] test_vpc_network_internal_lbrules.py
- [ ] test_vpc_vms_deployment.py
- [ ] test_vpn_service.py
- [ ] test_vpn_users.py
- [ ] test_vr_metadata.py
- [ ] test_bugs.py
- [ ] test_dedicate_guest_vlan_ranges.py
- [ ] test_dedicate_public_ip_range.py
- [ ] test_escalations_hosts.py
- [ ] test_escalation_templates.py
- [ ] test_explicit_dedication.py
- [ ] test_ha_pool_maintenance.py
- [ ] test_high_availability.py
- [ ] test_ip_resource_count_for_vpc.py
- [ ] test_vpc_vms_deployment.py
- [ ] test_redundant_router_deployment_planning.py
- [ ] test_redundant_router_network_rules.py
- [ ] test_redundant_router.py

##### exact matches:
- [ ] test_dhcp_dns_offload.py
- [ ] test_browse_volumes.py
- [ ] test_escalations_networks.py
- [ ] test_multiple_public_interfaces.py
- [ ] test_organization_states.py
- [ ] test_vpc_routers.py
- [ ] test_vpc_vm_life_cycle.py
- [ ] test_vpc_host_maintenance.py
- [ ] test_vpc_vms_deployment.py
- [ ] test_zone_level_local_storage_setting.py

####### only in python2:
- [ ] test_browse_templates2.py
- [ ] test_deploy_vgpu_vm.py
- [ ] test_escalations_volumes.py
- [ ] test_snapshots.py
- [ ] test_ss_limits.py
- [ ] test_dedicate_public_ip_range.py

### CODE REVIEW

**Comment by DaanHoogland** [comment]
```
Test completed. 104 look ok, 68 have errors
```

however
```
# ls tests/component/ | wc
    159     159    4106
```
still to investigate the discrepency between 104+68 and 159 ???

cc @borisstoyanov @rhtyd

**Comment by DaanHoogland** [comment]
> still to investigate the discrepency between 104+68 and 159 ???

found it but it yield a discrepency the other direction:
```
# ls -RF1  | grep "test_.*.py" | wc
    187     187    4993
```
seems 5 test_suites either don't have tests or are not being run.

**Comment by DaanHoogland** [comment]
compared to a python2 baseline the differences are:
python2: `Test completed. 112 look ok, 60 have errors`
python3: `Test completed. 104 look ok, 68 have errors`

`Test completed` here means 8 test-*suites*. The actual difference in number of tests failing or erroring are 
```
$ wc -l py2-components.txt py3-components.txt 
  202 py2-components.txt
  257 py3-components.txt
```
hence 55.

There are however tests that failed in python2 and passed in python3 as well, so it is a bit more complicated. The categories of differnces are:

- failure in both python2 and python3
- - shorter duration in python3
- - shorter duration in pyhton2
- - not the same duration but less than 50% and a second difference
- failure in python2 and error in python3
- error in python2 and failure in python3
- failure only in python3
- error only in python3

and last and least
- faileure or error only in python2 (these are less interesting for us)


I'll edit this comment with updates

**Comment by DaanHoogland** [comment]
reconsiddering (and re-running) configdrive tests on py2 and py3 I get

- py2:
Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_configdrive_isolated_network | `Failure` | 0.99 | test_configdrive.py
test_configdrive_isolated_network_hypervisor_hostname_exposed | `Error` | 3.48 | test_configdrive.py
test_configdrive_shared_network | `Failure` | 2.17 | test_configdrive.py
test_configdrive_vpc_network | `Failure` | 6.96 | test_configdrive.py

- py3
Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_configdrive_isolated_network | `Failure` | 1.73 | test_configdrive.py
test_configdrive_isolated_network_hypervisor_hostname_exposed | `Error` | 6.95 | test_configdrive.py
test_configdrive_shared_network | `Failure` | 5.17 | test_configdrive.py
test_configdrive_vpc_network | `Failure` | 17.17 | test_configdrive.py
test_configdrive_vpc_network_verify_metadata | `Failure` | 9.70 | test_configdrive.py

these are too similar to give it priority now (@rhtyd)

**Comment by DaanHoogland** [comment]
test_egress_fw_rules.py in a new env shows the new failure succeeding, skipping this test (for now):
```
Test Create Egress rule without CIDR ... === TestName: test_06_egress_fr6 | Status : SUCCESS ===
ok
```

**Comment by DaanHoogland** [comment]
multiple ips per nic:

python2:
```
Add secondary IP to NIC of a VM ... === TestName: test_add_ip_to_nic_1_SHARED | Status : SUCCESS ===
ok
Test listing nics associated with the ip address ... === TestName: test_list_nics_1_ISOLATED | Status : SUCCESS ===
ok
Test listing nics associated with the ip address ... === TestName: test_list_nics_2_SHARED | Status : SUCCESS ===
ok
Test listing nics associated with the ip address ... === TestName: test_list_nics_3_VPC | Status : SUCCESS ===
ok
Test basic operations using non root admin apii client ... === TestName: test_operations_non_root_admin_api_client_1_ISOLATED | Status : SUCCESS ===
ok
Test basic operations using non root admin apii client ... === TestName: test_operations_non_root_admin_api_client_2_SHARED | Status : SUCCESS ===
ok
Test basic operations using non root admin apii client ... === TestName: test_operations_non_root_admin_api_client_3_VPC | Status : SUCCESS ===
ok
Remove invalid ip ... === TestName: test_remove_invalid_ip | Status : SUCCESS ===
ok
Remove secondary IP from NIC of a VM ... === TestName: test_remove_ip_from_nic_1_ISOLATED | Status : SUCCESS ===
ok
Remove secondary IP from NIC of a VM ... === TestName: test_remove_ip_from_nic_2_SHARED | Status : SUCCESS ===
ok
Remove secondary IP from NIC of a VM ... === TestName: test_remove_ip_from_nic_3_VPC | Status : EXCEPTION ===
ERROR
=== TestName: test_remove_ip_from_nic_3_VPC | Status : EXCEPTION ===
ERROR
=== TestName: test_remove_ip_from_nic_3_VPC | Status : EXCEPTION ===
ERROR
=== TestName: test_remove_ip_from_nic_3_VPC | Status : EXCEPTION ===
ERROR
```

and py3 
```
Add secondary IP to NIC of a VM ... === TestName: test_add_ip_to_nic_1_SHARED | Status : SUCCESS ===
ok
Test listing nics associated with the ip address ... === TestName: test_list_nics_1_ISOLATED | Status : SUCCESS ===
ok
Test listing nics associated with the ip address ... === TestName: test_list_nics_2_SHARED | Status : SUCCESS ===
ok
Test listing nics associated with the ip address ... === TestName: test_list_nics_3_VPC | Status : SUCCESS ===
ok
Test basic operations using non root admin apii client ... === TestName: test_operations_non_root_admin_api_client_1_ISOLATED | Status : SUCCESS ===
ok
Test basic operations using non root admin apii client ... === TestName: test_operations_non_root_admin_api_client_2_SHARED | Status : SUCCESS ===
ok
Test basic operations using non root admin apii client ... === TestName: test_operations_non_root_admin_api_client_3_VPC | Status : SUCCESS ===
ok
Remove invalid ip ... === TestName: test_remove_invalid_ip | Status : SUCCESS ===
ok
Remove secondary IP from NIC of a VM ... === TestName: test_remove_ip_from_nic_1_ISOLATED | Status : SUCCESS ===
ok
Remove secondary IP from NIC of a VM ... === TestName: test_remove_ip_from_nic_2_SHARED | Status : SUCCESS ===
ok
Remove secondary IP from NIC of a VM ... === TestName: test_remove_ip_from_nic_3_VPC | Status : SUCCESS ===
ok
Add secondary IP to NIC of a VM ... === TestName: test_add_PF_rule_1_ISOLATED | Status : FAILED ===
FAIL
Add secondary IP to NIC of a VM ... === TestName: test_add_PF_rule_2_SHARED | Status : FAILED ===
FAIL
Add secondary IP to NIC of a VM ... === TestName: test_add_PF_rule_3_VPC | Status : FAILED ===
FAIL
Add secondary IP to NIC of a VM ... === TestName: test_add_static_nat_rule_1_ISOLATED | Status : FAILED ===
FAIL
=== TestName: test_add_static_nat_rule_1_ISOLATED | Status : EXCEPTION ===
ERROR
Add secondary IP to NIC of a VM ... === TestName: test_add_static_nat_rule_2_SHARED | Status : EXCEPTION ===
ERROR
=== TestName: test_add_static_nat_rule_2_SHARED | Status : EXCEPTION ===
ERROR
Add secondary IP to NIC of a VM ... === TestName: test_add_static_nat_rule_3_VPC | Status : EXCEPTION ===
ERROR
Add secondary IP to NIC of a VM ... === TestName: test_delete_PF_nat_rule_1_ISOLATED | Status : EXCEPTION ===
ERROR
=== TestName: test_delete_PF_nat_rule_1_ISOLATED | Status : EXCEPTION ===
Add secondary IP to NIC of a VM ... === TestName: test_delete_PF_nat_rule_2_SHARED | Status : EXCEPTION ===
ERROR
=== TestName: test_delete_PF_nat_rule_2_SHARED | Status : EXCEPTION ===
ERROR
Add secondary IP to NIC of a VM ... === TestName: test_delete_PF_nat_rule_3_VPC | Status : EXCEPTION ===
ERROR
Add secondary IP to NIC of a VM ... === TestName: test_disable_static_nat_1_ISOLATED | Status : EXCEPTION ===
ERROR
=== TestName: test_disable_static_nat_1_ISOLATED | Status : EXCEPTION ===
ERROR
Add secondary IP to NIC of a VM ... === TestName: test_disable_static_nat_2_SHARED | Status : EXCEPTION ===
ERROR
=== TestName: test_disable_static_nat_2_SHARED | Status : EXCEPTION ===
ERROR
Add secondary IP to NIC of a VM ... === TestName: test_disable_static_nat_3_VPC | Status : EXCEPTION ===
ERROR
Add secondary IP to NIC of a VM ... === TestName: test_disassociate_ip_mapped_to_secondary_ip_through_PF_rule_1_ISOLATED | Status : EXCEPTION ===
ERROR
=== TestName: test_disassociate_ip_mapped_to_secondary_ip_through_PF_rule_1_ISOLATED | Status : EXCEPTION ===
ERROR
Add secondary IP to NIC of a VM ... === TestName: test_disassociate_ip_mapped_to_secondary_ip_through_PF_rule_2_SHARED | Status : EXCEPTION ===
ERROR
=== TestName: test_disassociate_ip_mapped_to_secondary_ip_through_PF_rule_2_SHARED | Status : EXCEPTION ===
ERROR
Add secondary IP to NIC of a VM ... === TestName: test_disassociate_ip_mapped_to_secondary_ip_through_PF_rule_3_VPC | Status : EXCEPTION ===
ERROR
=== TestName: test_disassociate_ip_mapped_to_secondary_ip_through_PF_rule_3_VPC | Status : EXCEPTION ===
ERROR
Test delete VM and verify network rules are cleaned up ... === TestName: test_delete_vm_1_ISOLATED | Status : EXCEPTION ===
ERROR
=== TestName: test_delete_vm_1_ISOLATED | Status : EXCEPTION ===
ERROR
Test delete VM and verify network rules are cleaned up ... === TestName: test_delete_vm_2_SHARED | Status : EXCEPTION ===
ERROR
Test delete VM and verify network rules are cleaned up ... === TestName: test_delete_vm_3_VPC | Status : EXCEPTION ===
ERROR
Test network restart (cleanup True) with VM having secondary IPs and related network rules ... === TestName: test_network_restart_cleanup_false_1_ISOLATED | Status : EXCEPTION ===
ERROR
=== TestName: test_network_restart_cleanup_false_1_ISOLATED | Status : EXCEPTION ===
ERROR
Test network restart (cleanup True) with VM having secondary IPs and related network rules ... === TestName: test_network_restart_cleanup_false_2_SHARED | Status : EXCEPTION ===
ERROR
Test network restart (cleanup True) with VM having secondary IPs and related network rules ... === TestName: test_network_restart_cleanup_false_3_VPC | Status : EXCEPTION ===
ERROR
Test network restart (cleanup True) with VM having secondary IPs and related network rules ... === TestName: test_network_restart_cleanup_true_1_ISOLATED | Status : EXCEPTION ===
ERROR
=== TestName: test_network_restart_cleanup_true_1_ISOLATED | Status : EXCEPTION ===
ERROR
Test network restart (cleanup True) with VM having secondary IPs and related network rules ... === TestName: test_network_restart_cleanup_true_2_SHARED | Status : EXCEPTION ===
ERROR
Test network restart (cleanup True) with VM having secondary IPs and related network rules ... === TestName: test_network_restart_cleanup_true_3_VPC | Status : EXCEPTION ===
ERROR
Test reboot router and persistence of network rules ... === TestName: test_reboot_router_VM_1_ISOLATED | Status : EXCEPTION ===
ERROR
=== TestName: test_reboot_router_VM_1_ISOLATED | Status : EXCEPTION ===
ERROR
Test reboot router and persistence of network rules ... === TestName: test_reboot_router_VM_2_SHARED | Status : EXCEPTION ===
ERROR
Test reboot router and persistence of network rules ... === TestName: test_reboot_router_VM_3_VPC | Status : EXCEPTION ===
ERROR
Test recover VM operation with VM having secondary IPs ... === TestName: test_recover_vm_1_ISOLATED | Status : EXCEPTION ===
ERROR
=== TestName: test_recover_vm_1_ISOLATED | Status : EXCEPTION ===
ERROR
Test recover VM operation with VM having secondary IPs ... === TestName: test_recover_vm_2_SHARED | Status : EXCEPTION ===
ERROR
Test recover VM operation with VM having secondary IPs ... === TestName: test_recover_vm_3_VPC | Status : EXCEPTION ===
ERROR

```

So in conclusion more successes in absolute numbers but much more are run and a lot of exceptions extra. We'll have to revisit this.

**Comment by DaanHoogland** [comment]
test_templates brought up to par; py2:
```
Test create VM, Snapshot and Template ... === TestName: test_01_createVM_snapshotTemplate | Status : SUCCESS ===
ok
Test snapshot events ... === TestName: test_05_snapshot_events | Status : SUCCESS ===
ok
Test Creating snapshot from volume having spaces in name(KVM) ... === TestName: test_01_volume_from_snapshot | Status : FAILED ===
FAIL
Test Snapshot Data Disk ... === TestName: test_02_snapshot_data_disk | Status : SUCCESS ===
ok
Test snapshot from detached disk ... === TestName: test_03_snapshot_detachedDisk | Status : SUCCESS ===
ok
Test Delete Snapshot ... === TestName: test_04_delete_snapshot | Status : SUCCESS ===
ok
Create Template from snapshot ... === TestName: test_07_template_from_snapshot | Status : EXCEPTION ===
ERROR
```

and py3:
```
Test create VM, Snapshot and Template ... === TestName: test_01_createVM_snapshotTemplate | Status : SUCCESS ===
ok
Test snapshot events ... === TestName: test_05_snapshot_events | Status : SUCCESS ===
ok
Test Creating snapshot from volume having spaces in name(KVM) ... === TestName: test_01_volume_from_snapshot | Status : FAILED ===
FAIL
Test Snapshot Data Disk ... === TestName: test_02_snapshot_data_disk | Status : SUCCESS ===
ok
Test snapshot from detached disk ... === TestName: test_03_snapshot_detachedDisk | Status : SUCCESS ===
ok
Test Delete Snapshot ... === TestName: test_04_delete_snapshot | Status : SUCCESS ===
ok
Create Template from snapshot ... === TestName: test_07_template_from_snapshot | Status : SUCCESS ===
ok
```

The failure is strange and I am not sure but I think it is in the test, have spent too much time on this one for now, and the goal is being on par with py2 for now.

**Comment by DaanHoogland** [comment]
the test_vpc_* failures show a failure to ssh into a vm or router or do a wget that fails.
in python2 the wget gives no error but this seems a false positive. When removing the leanup from the tests the remaining envs do not allow for wget and on the marvin box a file named test.html remains with the contents,
```
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>
```
, indicating that the wget indeed failed even though the test reports success. I'm going to rebase the full test suites for both python2 and python3 and re-run the full comparison.

**Comment by DaanHoogland** [comment]
@GabrielBrascher @rhtyd I am running a new comparison between the py2 and py3 tests now, to verify we are at least at par. will let you know.
can you please review?
thanks

**Comment by rhtyd** [comment]
Will review soon, but +1 great work @DaanHoogland we've always had components test but never run them. With your work, we finally wil have verified list of tests/cases that we expect to work which will further help with running such component tests on weekly basis to review/monitor branch health.

I suppose there are still some work left but I would want to get something merged soon that could help 4.16, for example:
- limit scope of the remaining component tests and fix that limited scope of tests, such that they pass for kvm/vmware/xenserver at least with adv zone (preferably the case of adv zone + SG too)
- move all failing tests that can't be fixed (takes another couple of years :) ) with a different attribute to be fixed in future
- add/update component tests that missing to Travis
- integrate fix BO to run component tests (that are known to pass), something like @bo test componentmatrix to kick component only tests across kvm/vmware/xenserver?

**Comment by DaanHoogland** [comment]
> * limit scope of the remaining component tests and fix that limited scope of tests, such that they pass for kvm/vmware/xenserver at least with adv zone (preferably the case of adv zone + SG too)

this scope is not yet clear and I would like to do that in a future PR.

> 
> * move all failing tests that can't be fixed (takes another couple of years :) ) with a different attribute to be fixed in future

good idea, will do

> 
> * add/update component tests that missing to Travis

Travis is already taking a long time (and we are probably not like by travis or the rest of apache) Let's discuss this

> 
> * integrate fix BO to run component tests (that are known to pass), something like @bo test componentmatrix to kick component only tests across kvm/vmware/xenserver?

yes, but this also seems a separate PR. (and internal to BO mostly, not ACS)

thanks for the suggestions @rhtyd

**Comment by DaanHoogland** [comment]
```
==> cts-kvm-py2.20210817 <==
Component tests completed. 40 look OK, 126 have errors

==> cts-kvm-py3.20210817 <==
Component tests completed. 125 look OK, 35 have errors

==> cts-vmware-py2.20210817 <==
Component tests completed. 51 look OK, 115 have errors

==> cts-vmware-py3.20210817 <==
Component tests completed. 91 look OK, 69 have errors

==> cts-xen-py2.20210817 <==
Component tests completed. 54 look OK, 112 have errors

==> cts-xen-py3.20210817 <==
Component tests completed. 89 look OK, 71 have errors
```
re-running tests now as a lot of lab issues were encountered.
so far kvm on python3 looks best followed by the other python3 runs, so basically we are in a better place than with the old python2 runs of the component tests.

cc @nvazquez @rhtyd @GabrielBrascher, I can carry this on, but I feel this could be merged now as well, and the remaining work done in a new PR. What do you guys say?

**Comment by GabrielBrascher** [comment]
@DaanHoogland I am OK with merging it how it is and open new PRs for remaining works.

**Comment by GabrielBrascher** [comment]
@DaanHoogland should/could this one be placed as "ready for review"?

**Comment by DaanHoogland** [comment]
> @DaanHoogland should/could this one be placed as "ready for review"?

Yes, If travis is running ok I will put it in review.

**Comment by DaanHoogland** [comment]
@GabrielBrascher you are free to review now, btw. I just want to prevent merging when one of the component tests being used in travis might have a regression.

@nvazquez @rhtyd I gathered the py2 and py3 outputs:
```
09:45:14 [dahn@blimbing cloudstack]$ head -1 cts-*-py?.20210818
09:48:57
==> cts-kvm-py2.20210818 <==
Component tests completed. 105 look OK, 61 have errors

==> cts-kvm-py3.20210818 <==
Component tests completed. 129 look OK, 31 have errors

==> cts-vmware-py2.20210818 <==
Component tests completed. 51 look OK, 115 have errors

==> cts-vmware-py3.20210818 <==
Component tests completed. 93 look OK, 67 have errors

==> cts-xen-py2.20210818 <==
Component tests completed. 54 look OK, 113 have errors

==> cts-xen-py3.20210818 <==
Component tests completed. 90 look OK, 70 have errors
```

as y'all can see it is an improvements in all three hypervisor, but not done yet. I will now abandon testing the py2 versions all together and use these py3 results as my new baseline for further improvements. Any objections?

**Comment by nvazquez** [comment]
@DaanHoogland good work, +1 for the proposed approach

**Comment by GabrielBrascher** [comment]
@DaanHoogland thanks, good work!

**Comment by DaanHoogland** [comment]
opening this for review now as travis job 2 and 4 are regulars in the failure lists and don't seem to have to do with any work here. The rest should be fine now

**Review by rhtyd — APPROVED** [review]
LGTM - I'm +1 to get the first pass of component tests merged that show siginificant progress in which ones can we run now (and they pass). The next steps:
1. check/update these against Travis yml i.e. check and include any tests which aren't already added to the list which pass in Travis
2. Figure out a subset that can be worked upon as phase2

**Comment by DaanHoogland** [comment]
smoke tests and java code have not changed, but still:
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix keepEnv

**Comment by nvazquez** [comment]
@blueorangutan test matrix keepEnv

**Review by GabrielBrascher — APPROVED** [review]
LGTM based on the CI test results and overall code review.
Agree with the idea of merging how it is and work incrementally on new PR(s).

**Comment by rhtyd** [comment]
LGTM as Gabriel and others have said let's merge this. We don't normally run component tests, but getting incremental PRs merged is a good approach. Smoketests on this have passed (the errors are not related to this PR, these are tests that shouldn't run).

**Comment by rhtyd** [comment]
@DaanHoogland pl create another PR to continue any further work. Thanks.

**Pull request merged**
