### PR TITLE
Provide cleanup option to force deleting a project

### PR DESCRIPTION
**Pull request by ravening**
## Description

Provide an option to user which when selected
deletes all the resources in the project.
If not selected then the project is not deleted if
all the resources are not yet cleaned up

## Types of changes

- [X] Enhancement (improves an existing feature and functionality)

## Screenshots (if appropriate):

Screenshot 2020-11-06 at 14 25 38
]

### CODE REVIEW

**Review by weizhouapache — APPROVED** [review]

**Comment by DaanHoogland** [comment]
code looks ok, but needs tests and primate UI

**Comment by ravening** [comment]
> code looks ok, but needs tests and primate UI

@DaanHoogland I have already created pr for ui changes

**Review by davidjumani — APPROVED** [review]
LGTM. Unable to delete a project if it has resources but can do so by passing cleanup as true
There could be other checks for resources such as ssh keys, etc but the basics are covered

**Comment by weizhouapache** [comment]
@ravening can you resolve the conflicts, and make primate ui change ?

**Comment by ravening** [comment]
@ustcweizhou created new pr https://github.com/apache/cloudstack/pull/4617

**Pull request closed without merging**
