### PR TITLE
Fix test_vm_schedule's intermittent failures

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR...

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by vishesh92** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
seems a more sturdy way of checking in nested environments, let's test a few times.

**Review by harikrishna-patnala — APPROVED** [review]
code LGTM.

**Comment by vishesh92** [comment]
@blueorangutan test

**Comment by vishesh92** [comment]
I added test_vm_schedule as part of github actions.
@DaanHoogland Can you rerun this workflow `Simulator CI / build (smoke/test_router_dhcphosts smoke/test_router_dns smoke/test_router_dnsservice smoke/...`?

**Comment by vishesh92** [comment]
@blueorangutan test

**Review by rohityadavcloud — APPROVED** [review]

**Pull request merged**
