### PR TITLE
Unify templates/ISOs checksum API output

### PR DESCRIPTION
**Pull request by nvazquez**
## Description
Unify checksum API output for templates and ISOs: not list the checksum algorithm on:

- KVM direct downloads

- On in progress normal template downloads. The algorithm is shown on the `listtemplates` API, but after it is downloaded it is not shown anymore:
````
(qa11) 🐵 > list templates id=0699767e-ce21-4967-a53a-3c0f37fe9154 templatefilter=all filter=status,checksum
{
  "count": 1,
  "template": [
    {
      "checksum": "{SHA-256}ae490ce8b7a55fa92365f72e7581c3eed651da710794989f263f3816b9dc2ea9",
      "status": "50% Downloaded",
    }
  ]
}
(qa11) 🐵 > list templates id=0699767e-ce21-4967-a53a-3c0f37fe9154 templatefilter=all
{
  "count": 1,
  "template": [
    {
      "checksum": "ae490ce8b7a55fa92365f72e7581c3eed651da710794989f263f3816b9dc2ea9",
      "status": "Download Complete",
    }
  ]
}
````

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

- KVM direct downloads:
````
(local) SBCM5> list templates templatefilter=all id=7713ca67-cf3a-4281-82fb-58b5ddc25d6b filter=status,checksum
{
  "count": 1,
  "template": [
    {
      "checksum": "6952e58f39b470bd166ace11ffd20bf479bed936",
      "status": "Bypassed Secondary Storage"
    }
  ]
}
````

- Non direct downloads:
````
(local) SBCM5> list templates templatefilter=all filter=status,checksum id=c612129c-0fd0-449e-81f6-4d69ab11e5cb
{
  "count": 1,
  "template": [
    {
      "checksum": "6952e58f39b470bd166ace11ffd20bf479bed936",
      "status": "84% Downloaded"
    }
  ]
}
(local) SBCM5> list templates templatefilter=all filter=status,checksum id=c612129c-0fd0-449e-81f6-4d69ab11e5cb
{
  "count": 1,
  "template": [
    {
      "checksum": "6952e58f39b470bd166ace11ffd20bf479bed936",
      "status": "Download Complete"
    }
  ]
}
````

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@nvazquez don't we want to see the algorithm?

**Comment by nvazquez** [comment]
@DaanHoogland I prefer not showing it, as it is important for the template registration, and at that point the user can control which algorithm to provide. But after the template gets registered it does not give any other value IMHO.

**Pull request merged**
