### PR TITLE
Add agent name in received response

### PR DESCRIPTION
**Pull request by ustcweizhou**
Before change:

2015-10-15 12:55:34,268 DEBUG [c.c.a.t.Request] (RouterStatusMonitor-1:ctx-d2b917a4) Seq 20-2693152577167557361: Sending  { Cmd , MgmtId: 345051313197, via: 20(KVM015), Ver: v1, Flags: 100011, [{"com.cloud.agent.api.routing.GetRouterAlertsCommand":{"previousAlertTimeStamp":"1970-01-01 00:00:00","accessDetails":{"router.ip":"169.254.3.13"},"wait":0}}] }
2015-10-15 12:55:34,416 DEBUG [c.c.a.t.Request] (AgentManager-Handler-7:null) Seq 20-2693152577167557361: Processing:  { Ans: , MgmtId: 345051313197, via: 20, Ver: v1, Flags: 10, [{"com.cloud.agent.api.GetRouterAlertsAnswer":{"result":true,"wait":0}}] }
2015-10-15 12:55:34,416 DEBUG [c.c.a.t.Request] (RouterStatusMonitor-1:ctx-d2b917a4) Seq 20-2693152577167557361: Received:  { Ans: , MgmtId: 345051313197, via: 20, Ver: v1, Flags: 10, { GetRouterAlertsAnswer } }

After change:

2015-10-15 13:31:04,562 DEBUG [c.c.a.t.Request] (RouterStatusMonitor-1:ctx-cf9a7691) Seq 22-6444651066767179831: Sending  { Cmd , MgmtId: 345051313197, via: 22(node12), Ver: v1, Flags: 100011, [{"com.cloud.agent.api.routing.GetRouterAlertsCommand":{"previousAlertTimeStamp":"1970-01-01 00:00:00","accessDetails":{"router.ip":"169.254.3.89"},"wait":0}}] }
2015-10-15 13:31:04,676 DEBUG [c.c.a.t.Request] (AgentManager-Handler-4:null) Seq 22-6444651066767179831: Processing:  { Ans: , MgmtId: 345051313197, via: 22, Ver: v1, Flags: 10, [{"com.cloud.agent.api.GetRouterAlertsAnswer":{"result":true,"wait":0}}] }
2015-10-15 13:31:04,677 DEBUG [c.c.a.t.Request] (RouterStatusMonitor-1:ctx-cf9a7691) Seq 22-6444651066767179831: Received:  { Ans: , MgmtId: 345051313197, via: 22(node12), Ver: v1, Flags: 10, { GetRouterAlertsAnswer } }

### CODE REVIEW

**Comment by DaanHoogland** [comment]
Code LGTM, as testing is a drag at this moment I think we should put this in a batch and test a combination of small PRs to report on. This one is candidate!

**Comment by wido** [comment]
With @DaanHoogland code-wise is LGTM

**Comment by remibergsma** [comment]
LGTM, built infra and run this test:

```
nosetests --with-marvin --marvin-config=${marvinCfg} -s -a tags=advanced,required_hardware=false smoke/test_vm_life_cycle.py
```

Results:
```
[root@cs3 integration]# cat /tmp//MarvinLogs/test_vm_life_cycle_X1KMH8/results.txt 
Test advanced zone virtual router ... === TestName: test_advZoneVirtualRouter | Status : SUCCESS ===
ok
Test Deploy Virtual Machine ... === TestName: test_deploy_vm | Status : SUCCESS ===
ok
Test Multiple Deploy Virtual Machine ... === TestName: test_deploy_vm_multiple | Status : SUCCESS ===
ok
Test Stop Virtual Machine ... === TestName: test_01_stop_vm | Status : SUCCESS ===
ok
Test Start Virtual Machine ... === TestName: test_02_start_vm | Status : SUCCESS ===
ok
Test Reboot Virtual Machine ... === TestName: test_03_reboot_vm | Status : SUCCESS ===
ok
Test destroy Virtual Machine ... === TestName: test_06_destroy_vm | Status : SUCCESS ===
ok
Test recover Virtual Machine ... === TestName: test_07_restore_vm | Status : SUCCESS ===
ok
Test migrate VM ... === TestName: test_08_migrate_vm | Status : SUCCESS ===
ok
Test destroy(expunge) Virtual Machine ... === TestName: test_09_expunge_vm | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 10 tests in 1557.153s

OK
```

Checked functionality, saw this in logs now:

```
MgmtId: 90520732674659, via: 1(kvm3)
```

**Comment by borisroman** [comment]
@remibergsma Did the same :) KVM Basic setup though. Integeration test: smoke/test_vm_life_cycle.py returned all success!

LGTM :+1:

**Pull request merged**
