### PR TITLE
Removed deprecated instruction MAINTAINER

### PR DESCRIPTION
**Pull request by OlegChuev**
### Description

This PR...

Removes deprecated MAINTAINER instruction from all Dockerfiles and uses LABEL instead
https://docs.docker.com/reference/dockerfile/#maintainer-deprecated

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [X] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [X] Trivial

### CODE REVIEW

**Comment by OlegChuev** [comment]
Not sure which version or branch I should target to resolve conflicts :/

**Comment by DaanHoogland** [comment]
@OlegChuev ,Did you test this? can you add test description(s)?

**Comment by OlegChuev** [comment]
> @OlegChuev ,Did you test this? can you add test description(s)?

Tested only `tools/docker/Dockerfile`, but I believe it should be OK since there're only changes in `LABEL` instruction

I manually build container with `docker buildx build -f tools/docker/Dockerfile -t cloudstack/simulator:4.18.X.0 --platform linux/arm64 .`

And as a result I got `cloudstack/simulator:4.18.X.0` image with the following information in image metadata:

```
 › docker image inspect cloudstack/simulator:4.18.X.0
[
    {
        "Id": "sha256:176b6bb5080fb20f25d3e507fb7622f0ef1ada6c672cb0d3760fb7fdd4494755",
        "RepoTags": [
            "cloudstack/simulator:4.18.X.0"
        ],
        "RepoDigests": [],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2024-04-01T12:14:12.237046882Z",
        "Container": "",
        "ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "5050/tcp": {},
                "8080/tcp": {},
                "8096/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/usr/bin/supervisord"
            ],
            "ArgsEscaped": true,
            "Image": "",
            "Volumes": {
                "/var/lib/mysql": {}
            },
            "WorkingDir": "/root",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "Author": "Apache CloudStack <dev@cloudstack.apache.org>",
                "License": "ApacheV2",
                "Vendor": "Apache.org",
                "Version": "4.18.1.0",
                "org.opencontainers.image.ref.name": "ubuntu",
                "org.opencontainers.image.version": "22.04"
            }
        },
        "Architecture": "arm64",
        "Os": "linux",
        "Size": 1711037341,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/mnv9kxp2htic0we90nnoatc4h/diff:/var/lib/docker/overlay2/4mbscd8jd3moee7cah0aud9zr/diff:/var/lib/docker/overlay2/pv944s0j3us6m2zouv41h294h/diff:/var/lib/docker/overlay2/ku313uwqmflr2xrj9mx29lqsn/diff:/var/lib/docker/overlay2/iabin3w7bw0oxc3qihtlnfom3/diff:/var/lib/docker/overlay2/338764ee9608e6de265778f10d9e8d2e7caab468151ce7fbde88864c553a303d/diff",
                "MergedDir": "/var/lib/docker/overlay2/u4hhtllaebotsyzydnes918e4/merged",
                "UpperDir": "/var/lib/docker/overlay2/u4hhtllaebotsyzydnes918e4/diff",
                "WorkDir": "/var/lib/docker/overlay2/u4hhtllaebotsyzydnes918e4/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:a510ae0f066c65d73f523d5821fe048a6858e53360ecb8d39b7b931162f11479",
                "sha256:6e015d01dff4e9d0bab341006b29b80859a30ca173c1213caa72081d4931c8c4",
                "sha256:9c89726988b69e5bd777517ab28ec9cab81e7b5e0f11623929ec9691306964a8",
                "sha256:8a3b8ae7f74e2a204bef0e9a0ce366ac2103c5d3c65398cb0f2c86929ff41b84",
                "sha256:5df74e25c08ec82cecb4631593de346d4388d9c8a149fb0dac4b69bff1dd8dfe",
                "sha256:d3b168531e0d6a92d0bc4bfafec9edc570c54faaafd0f05e8b54161ed186b0d1",
                "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef"
            ]
        },
        "Metadata": {
            "LastTagTime": "2024-04-01T12:14:12.935076632Z"
        }
    }
]
```

**Review by DaanHoogland — APPROVED** [review]

**Review by sureshanaparti — APPROVED** [review]
changes lgtm

**Pull request merged**
