### PR TITLE
CLOUDSTACK-8527: Skipping VPC tests on HyperV

### PR DESCRIPTION
**Pull request by gauravaradhye**
Skipping tests as VPC is not supported on HyperV

### CODE REVIEW

**Comment by DaanHoogland** [comment]
LGTM. any test data on the test code;)

**Comment by gauravaradhye** [comment]
This is tested on HyperV and test case skipped successfully.


Test start/stop of router after addition of one guest network ... SKIP: VPC is not supported on hyperv
Test reboot of router after addition of one guest network ... SKIP: VPC is not supported on hyperv
Test migrate of router after addition of one guest network ... SKIP: VPC is not supported on hyperv
Test to change service offering of router after addition of one guest network ... SKIP: VPC is not supported on hyperv
Test destroy of router after addition of one guest network ... SKIP: VPC is not supported on hyperv
Test to stop and start router after creation of VPC ... SKIP: VPC is not supported on hyperv
Test to reboot the router after creating a VPC ... SKIP: VPC is not supported on hyperv
Test migration of router to another host after creating VPC ... SKIP: VPC is not supported on hyperv
Tests to change service offering of the Router after ... SKIP: VPC is not supported on hyperv
Test to destroy the router after creating a VPC ... SKIP: VPC is not supported on hyperv

----------------------------------------------------------------------
Ran 10 tests in 0.004s

OK (SKIP=10)

**Comment by DaanHoogland** [comment]
:D

**Comment by gauravaradhye** [comment]
:-)

**Pull request closed without merging**
