### PR TITLE
Fix orphan entry on ldap trust map after account removal

### PR DESCRIPTION
**Pull request by nvazquez**
### Description

Fixes: #4673 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### How Has This Been Tested?
- Set up LDAP AD on Windows 2016 server
- Create a domain
- Configure LDAP on CloudStack to the created domain
- Link account to LDAP
- Remove account

### CODE REVIEW

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by nvazquez** [comment]
@blueorangutan test ubuntu18 kvm-ubuntu18

**Review by DaanHoogland — APPROVED** [review]
this can work (code looks good) but effectively ldap is no longer a plugin. Is there some kind of publish/subscribe mechanism or an event fire/event handler construct to keep the loose coupling intact as much as possible? [discuss]

**Comment by rhtyd** [comment]
@nvazquez can you rebase the PR branch against 4.15

> this can work (code looks good) but effectively ldap is no longer a plugin. Is there some kind of publish/subscribe mechanism or an event fire/event handler construct to keep the loose coupling intact as much as possible? [discuss]

There's the command-answer pattern, and message bus if we need that within ldap/CloudStack plugin, but I'm not sure how/where it fits wrt this PR.

**Comment by rhtyd** [comment]
... if it helps @nvazquez @DaanHoogland here's an example of how one part/operation can be used to link to other part of the codebase by means of message passing: https://github.com/shapeblue/hackerbook/blob/master/hack/com.md#message-bus

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
Great thanks @rhtyd @DaanHoogland, refactored in favour of message bus

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
LGTM let's wait for some manual test/confirmation cc @borisstoyanov @vladimirpetrov

**Comment by borisstoyanov** [comment]
LGTM, manually verified this

```
(localcloud) SBCM5> > link accounttoldap account=dom-admin domainid=3bdaff06-4a44-45a0-a644-50f563c1b3e2  accounttype=2 ldapdomain=people type=ou
{
  "linkAccountToLdap": {
    "account": "dom-admin",
    "accountid": "7f934e06-73b6-41ba-aa5b-03c7386325f7",
    "accounttype": 2,
    "domainid": "3bdaff06-4a44-45a0-a644-50f563c1b3e2",
    "ldapdomain": "people",
    "type": "OU"
  }
}

MariaDB [cloud]> select * from ldap_trust_map;
+----+-----------+------+--------+--------------+------------+
| id | domain_id | type | name   | account_type | account_id |
+----+-----------+------+--------+--------------+------------+
|  1 |         2 | OU   | people |            2 |          5 |
+----+-----------+------+--------+--------------+------------+
1 row in set (0.00 sec)


(localcloud) SBCM5> > delete account id=7f934e06-73b6-41ba-aa5b-03c7386325f7
{
  "success": true
}
(localcloud) SBCM5> >

MariaDB [cloud]> select * from ldap_trust_map;
Empty set (0.00 sec)

MariaDB [cloud]>
```

**Review by borisstoyanov — APPROVED** [review]
LGTM, manually verified this

```
(localcloud) SBCM5> > link accounttoldap account=dom-admin domainid=3bdaff06-4a44-45a0-a644-50f563c1b3e2  accounttype=2 ldapdomain=people type=ou
{
  "linkAccountToLdap": {
    "account": "dom-admin",
    "accountid": "7f934e06-73b6-41ba-aa5b-03c7386325f7",
    "accounttype": 2,
    "domainid": "3bdaff06-4a44-45a0-a644-50f563c1b3e2",
    "ldapdomain": "people",
    "type": "OU"
  }
}

MariaDB [cloud]> select * from ldap_trust_map;
+----+-----------+------+--------+--------------+------------+
| id | domain_id | type | name   | account_type | account_id |
+----+-----------+------+--------+--------------+------------+
|  1 |         2 | OU   | people |            2 |          5 |
+----+-----------+------+--------+--------------+------------+
1 row in set (0.00 sec)


(localcloud) SBCM5> > delete account id=7f934e06-73b6-41ba-aa5b-03c7386325f7
{
  "success": true
}
(localcloud) SBCM5> >

MariaDB [cloud]> select * from ldap_trust_map;
Empty set (0.00 sec)

MariaDB [cloud]>
```

**Comment by rhtyd** [comment]
Merged based on Daan's review, Bobby's review and testing and smoketests.

**Pull request merged**
