### PR TITLE
Fix Successfully typo

### PR DESCRIPTION
**Pull request by coliff**
## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## Checklist:

- [ ] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

@blueorangutan package

### CODE REVIEW

**Comment by rafaelweingartner** [comment]
@coliff thanks for the typo fix.
Can you force push again just to make Jenkins happy?

**Comment by coliff** [comment]
@rafaelweingartner I'm using GitHub.com web interface so not sure how to do a force push here...

**Comment by DaanHoogland** [comment]
seeing if jenkins will pick up

**Comment by rafaelweingartner** [comment]
@DaanHoogland I thought the same :)

However, for me, the problem in that class is even bigger. Unit tests do not need to log; so, why is this file logging/writing to the console? To tell you the truth, I do not even consider that class and its hierarchy unit tests.  They are so daam complicated...

I do believe we can merge this as well.
Thanks @coliff. Please keep contributing with other PRs :)

Wish you a Happy Easter!

**Pull request merged**
