### PR TITLE
Update listVirtualMachines API documentation with 'projectid=-1' to list all VMs in projects.

### PR DESCRIPTION
**Pull request by GabrielBrascher**
### [Update November 2021] PR Scope changed
Considering the reviews and discussion, I changed the scope of this PR to documentation update. I think that at least the documentation changes are mandatory as the documentation is not clear and already let to some internal issues.

Looking into the [listVirtualMachines API command documentation](https://cloudstack.apache.org/api/apidocs-4.14/apis/listVirtualMachines.html) there is the following description:

> listall: If set to false, list only resources belonging to the command's caller; if set to true - list resources that the caller is authorized to see. Default value is false

The documentation is clear about the fact that when parameter `listall=true` then `listVirtualMachines` lists resources that the caller is authorized to see. Therefore, this PR considers that the ADMIN is _authorized to see_ all VMs, including those on projects.

Fixes: #4267

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality) 
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

I tested it via CloudMonkey and CloudStack UI. CloudMonkey output example:
```
cmk > list virtualmachines filter=id,account,project,name,state listall=true 
id                                    account  project      name                                     state 
86ba5f14-b783-4e66-b511-ba617ca88d38  gabriel                VM-86ba5f14-b783-4e66-b511-ba617ca88d38  Running 
717f2e13-c207-4861-af0a-619ba1552f57  admin                  test-02                                  Running 
c15f35aa-2343-47c3-9d57-36b3ba16d885  gabriel                VM-c15f35aa-2343-47c3-9d57-36b3ba16d885  Running 
1b1047ed-8c29-40f5-bd2d-cd979adc668d  admin                  ha-01-shared                             Running 
da787937-e3aa-409b-97b2-36ba4c45eb67  gabriel                VM-da787937-e3aa-409b-97b2-36ba4c45eb67  Running 
a40b8e98-29c7-4bf4-8209-2563d9c3db48            testproject  test-01                                  Running 
ca76ff8c-36f7-4183-b984-513106391db3  gabriel                VM-ca76ff8c-36f7-4183-b984-513106391db3  Running 
1f6b4fc6-f44f-4084-8ddd-14b916ada345  gabriel                VM-1f6b4fc6-f44f-4084-8ddd-14b916ada345  Running 
e17b9817-bea1-4b98-a153-7b272ff99745  gabriel                VM-e17b9817-bea1-4b98-a153-7b272ff99745  Running 
75b2e67e-2bda-4a55-b84a-91e69476a893  gabriel                VM-75b2e67e-2bda-4a55-b84a-91e69476a893  Running
4a226a80-8899-4ea7-80ea-220667c2b46d  gabriel                VM-4a226a80-8899-4ea7-80ea-220667c2b46d  Running
eebb96fd-7320-4f91-8881-3c75aff9e9cc            testproject  vm-on-project01                          Running
50215261-dbcb-47d7-bb3b-5e7626f1379f  admin                  test-00                                  Running
7d314232-0c60-4b1f-89b6-e63626134628  admin                  test-u18-p3                              Running
31f087dc-622a-412c-97cf-7e38d51643d0  admin                  tiny-py3                                 Running
54aa67ab-d106-47f8-8e3c-26a2496828d8  admin                  test-vr-py3                              Running
85b3b81b-7ce4-4087-b791-a7e92f0c365c  admin                  medium-local                             Running
701c73fb-35a1-4840-8db6-c90d41b95601            testproject  vm-project-02                            Running
38a2cfa3-02ba-44bb-92c6-6c5a32e38aa9  gabriel                VM-38a2cfa3-02ba-44bb-92c6-6c5a32e38aa9  Running
```

### CODE REVIEW

**Comment by rhtyd** [comment]
I think what you're trying to do is OK but could potentially break the listAPI for some environment. If you want we can show a toggle slider/radio in Primate list view which when checked can send the list VM API with listall=true and projectid=-1 which effectively would show the expected output.

**Comment by GabrielBrascher** [comment]
@rhtyd I understand your point. However, I think that either the documentation is incomplete or the `listAll=true` does not match with the documented/expected behavior.

Regarding the UI, I think that adding a toggle slider/radio in Primate would be nice indeed.

**Comment by wido** [comment]
@rhtyd The documentation currently states otherwise. The 'listall' parameter should now be called: 'listallexceptinstancesinprojects'

This seems like an oversight during implementation (a bug) rather then a feature.

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@rhtyd @RodrigoDLopez @wido do this get your LGTMs?

**Comment by DaanHoogland** [comment]
cc @svenvogel ^^?

**Comment by RodrigoDLopez** [comment]
> @rhtyd @RodrigoDLopez @wido do this get your LGTMs?

Hi @DaanHoogland   
I agree with this approuch
Code LGTM

**Comment by wido** [comment]
I am LGTM with this. 'listAll' should do as it implies: List all Virtual Machines

We need to update the changelog properly though

**Comment by DaanHoogland** [comment]
> We need to update the changelog properly though

what exactly do you have in mind?

**Comment by wido** [comment]
> > We need to update the changelog properly though
> 
> what exactly do you have in mind?

We need to mention something like:

<pre>The listAll parameter of listVirtualMachines now also lists all Instances which are under a project. Previously these would only be returned when *projectid=-1* was supplied as a parameter</pre>

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@GabrielBrascher can you have a look at #4469 and see if this is still needed or needs adjusting?

**Comment by GabrielBrascher** [comment]
@DaanHoogland PR #4469 regards listing projects, correct?

This PR is different, altering the `listVirtualMachines` command result in order to include all VMs from projects as well when the admin lists VMs with `listall=true`. The motivation is due to the API command `listAll` description: https://cloudstack.apache.org/api/apidocs-4.14/apis/listVirtualMachines.html

**Comment by Pearl1594** [comment]
@GabrielBrascher while it does make sense to do this to comply with what the documentation states wrt listall parameter, wouldn't it require us to handle this scenario for all resources owned by projects for the sake of consistency. Otherwise it may possibly lead to ambiguity when we list VMs with listall set to true vs listing networks with listall=true.

**Comment by DaanHoogland** [comment]
As @Pearl1594  raised a valid concern here I am moving this to 4.16 for now

**Comment by GabrielBrascher** [comment]
@Pearl1594 I agree, as far as I know all the list calls that have `listall` parameters (e.g. `listVOlumes`, `listTemplates`, `listNetworks`) describe `listall` in the same way.

Either we change the documentation of them all, or we allow them to return all resources of the respective owner.

**Comment by wido** [comment]
> @GabrielBrascher while it does make sense to do this to comply with what the documentation states wrt listall parameter, wouldn't it require us to handle this scenario for all resources owned by projects for the sake of consistency. Otherwise it may possibly lead to ambiguity when we list VMs with listall set to true vs listing say networks with listall=true.

Yes, we probably want to double check that. But it's good that we have this discussion. As right now it's difficult for an Admin to find all resources when they are in a project.

**Comment by DaanHoogland** [comment]
I think changing for all list APIs makes the most sense.

**Comment by rhtyd** [comment]
+1 the general theme, I would only worry about the change in behaviour if it can be tuned per env (by admins what they want)

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Review by sureshanaparti — APPROVED** [review]
code LGTM

**Comment by rhtyd** [comment]
LGTM - but this may break something in UI, for example in UI listall=true is passed; so as a root admin user/account you'll be now able to see all VMs across all projects; and some actions may require the passing of projectid when doing some operation with resources owned by a project. A failure case may be, in UI we see all VMs, and root admin selects a VM that belongs to a project and tries to say attach a volume or network to the VM that doesn't belong to the project -> some error/exception/security issue could be caused. Maybe I'm overthinking, @GabrielBrascher can you explore in this direction and advise if this could cause any regression in UI or operation issue like I've described.

**Comment by GabrielBrascher** [comment]
@rhtyd I will double-check this.

**Comment by nvazquez** [comment]
@GabrielBrascher please advise after your checks

**Comment by nvazquez** [comment]
@GabrielBrascher maybe this can be solved by PR https://github.com/apache/cloudstack/pull/4828?

**Comment by rhtyd** [comment]
@GabrielBrascher changed the milestone based on base `main` branch, if this is 4.16 pl fix PR base branch and advise.

**Comment by GabrielBrascher** [comment]
@rhtyd no problem in having this at 4.17.0.0.
This PR initially proposed changing the API, but later, after the feedback, I changed the scope to updating API documentation.; thus, ensuring that the `projectid=-1` option is explicit and clear in the API documentation.

**Review by DaanHoogland — APPROVED** [review]
looks good, no code.

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Review by Pearl1594 — APPROVED** [review]
LGTM

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Pull request merged**
