### PR TITLE
agent: Compare indirect agent lb algorithm when cloudstack agent conn…

### PR DESCRIPTION
**Pull request by ustcweizhou**
## Description

Compare not only the list of management servers but also the lb algorithm when agent connects.

Fixes: #3895

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Review by nvazquez — APPROVED** [review]
Code LGTM

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
@Spaceman1984 the fix is in, can you test this PR?
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by Spaceman1984** [comment]
> @Spaceman1984 the fix is in, can you test this PR?
> @blueorangutan package

On it

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
Tests LGTM, will merge once @Spaceman1984 can confirm manual testing

**Comment by Spaceman1984** [comment]
Tested, LGTM

**Pull request merged**
