### PR TITLE
Removed Unused Void Class

### PR DESCRIPTION
**Pull request by rodrigo93**
Removed the class _Void.java_ from _/cloud-framework-ipc/src/org/apache/cloudstack/framework/async/Void.java_ since the method _public void AsyncMethod(Object realParam,
AsyncCompletionCallback<Void> callback)_ does not exist and it does not seem to be used in another place.
Also, removed an unnecessary comment in
_/cloudstack-framework/ipc/test/org/apache/cloudstack/framework/codestyle/AsyncSampleListenerStyleCaller.java_

### CODE REVIEW

**Comment by rhtyd** [comment]
LGTM, a CI testing would confirm if PR can be accepted

tag:easypr

**Comment by nlivens** [comment]
LGTM

**Comment by swill** [comment]
### CI RESULTS

```
Tests Run: 85
  Skipped: 0
   Failed: 0
   Errors: 0
 Duration: 9h 08m 44s
```



**Associated Uploads**

**`/tmp/MarvinLogs/DeployDataCenter__May_07_2016_07_22_48_R3H25Y:`**
* [dc_entries.obj](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1440/tmp/MarvinLogs/DeployDataCenter__May_07_2016_07_22_48_R3H25Y/dc_entries.obj)
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1440/tmp/MarvinLogs/DeployDataCenter__May_07_2016_07_22_48_R3H25Y/failed_plus_exceptions.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1440/tmp/MarvinLogs/DeployDataCenter__May_07_2016_07_22_48_R3H25Y/runinfo.txt)

**`/tmp/MarvinLogs/test_network_MSZ3SB:`**
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1440/tmp/MarvinLogs/test_network_MSZ3SB/failed_plus_exceptions.txt)
* [results.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1440/tmp/MarvinLogs/test_network_MSZ3SB/results.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1440/tmp/MarvinLogs/test_network_MSZ3SB/runinfo.txt)

**`/tmp/MarvinLogs/test_vpc_routers_32L4E9:`**
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1440/tmp/MarvinLogs/test_vpc_routers_32L4E9/failed_plus_exceptions.txt)
* [results.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1440/tmp/MarvinLogs/test_vpc_routers_32L4E9/results.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1440/tmp/MarvinLogs/test_vpc_routers_32L4E9/runinfo.txt)


Uploads will be available until `2016-07-09 02:00:00 +0200 CEST`

*Comment created by [`upr comment`](https://github.com/cloudops/upr).*

**Comment by swill** [comment]
CI has come back clean.  👍 I will add this to my merge queue.  Thx...

**Comment by rodrigo93** [comment]
Thanks for the help! =)

**Pull request merged**
