### PR TITLE
Chinese language pack

### PR DESCRIPTION
**Pull request by rohityadavcloud**
Submitting this on behalf of @luwei1970  from this remote https://github.com/luwei1970/cloudstack
And previous PR https://github.com/apache/cloudstack/pull/6573

### CODE REVIEW

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@luwei1970 can you test this on http://qa.cloudstack.cloud:8080/client/pr/6653
I don't think we need any other testing on this than the view of a native chinese reader.

**Review by weizhouapache — APPROVED** [review]
had a quick view on http://qa.cloudstack.cloud:8080/client/pr/6653
looks fine

**Review by rohityadavcloud — COMMENTED** [review]
LGTM - don't see any break; counting on Wei's remarks

**Pull request merged**
