### PR TITLE
CLOUDSTACK-10077: allow to have different VPN customer gateway configs for same gateway IP

### PR DESCRIPTION
**Pull request by resmo**
See https://issues.apache.org/jira/browse/CLOUDSTACK-10077

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
Additional code review requested and please also see Travis failures.

**Comment by resmo** [comment]
travis build error looks unrelated to me. Trilian test failure, AFAICS, are also unrelated.

**Comment by rhtyd** [comment]
Thanks @resmo, test LGTM, additional code review is requested after which this can be merged.

**Comment by resmo** [comment]
FYI: we use this patch on 4.5.2 in production

**Comment by resmo** [comment]
We seeing an issue after a VPC restart. After a VPC restart, only the last VPN will get established.

**Comment by rhtyd** [comment]
@resmo is that a regression of sorts, we holding this PR?

**Comment by resmo** [comment]
not sure yet, we are investigating the root cause

**Comment by resmo** [comment]
issue is unrelated, ready_to_merge

**Comment by resmo** [comment]
rebased

**Comment by resmo** [comment]
asking for review @DaanHoogland @rhtyd @marcaurele @swill

**Comment by rhtyd** [comment]
LGTM, not sure any side-effects on this change. Others may help review - @DaanHoogland @marcaurele @swill @PaulAngus ?

**Comment by rhtyd** [comment]
Merged based on prod test recommendation and regression test results.

**Pull request merged**
