### PR TITLE
CKS: add created to k8s cluster and k8s version

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR adds `created` info to the response of kubernetes clusters and kubernetes supported version.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by davidjumani — APPROVED** [review]

**Review by shwstppr — APPROVED** [review]
Code LGTM

**Review by sureshanaparti — APPROVED** [review]
code LGTM

**Review by Pearl1594 — APPROVED** [review]

**Comment by nvazquez** [comment]
@blueorangutan test

**Pull request merged**
