### PR TITLE
bugfix ui/scripts/accounts.js L1339

### PR DESCRIPTION
**Pull request by wolf29**
This is a fix for one of the 2 problems in the first file in the stopper list for the https://analysis.apache.org/component_issues?id=org.apache.cloudstack%3Acloudstack#resolved=false|severities=BLOCKER

### CODE REVIEW

**Comment by ustcweizhou** [comment]
@wolf29  Can you create a PR with ALL related changes ?
it is convenient for review and merge

**Comment by wolf29** [comment]
@ustcweizhou - I can.  I have never done one of these before, and wanted to make sure I understood the process before doing a whole lot of changes.

**Comment by wolf29** [comment]
I have added in the second fix on that file, which should also fix the generated script file, I believe.

**Comment by bhaisaab** [comment]
LGTM, though are the additional commas causing any issue for you?

**Comment by DaanHoogland** [comment]
@bhaisaab I think @wolf29 is trying to triage the sonarqube issues. @wolf29 We would like a ref to an issue with a patch, jira, coverity, findbugs is all fine.

**Comment by bhaisaab** [comment]
@wolf29  please rebase against latest and meld commits into a single commit

**Comment by rhtyd** [comment]
@wolf29 can you rebase against latest master and share state of your PR, thanks

LGTM

tag:easypr

**Comment by rhtyd** [comment]
@wolf29 can you rebase

**Comment by rhtyd** [comment]
This needs to be rebased @wolf29

**Comment by kiwiflyer** [comment]
@wolf29 Please rebase with latest master.

**Comment by rhtyd** [comment]
Compared diff, issue merged fixed by some other PR/person. Closing this.

**Pull request closed without merging**
