### PR TITLE
Coverity Issue: Null pointer dereferencing fixed

### PR DESCRIPTION
**Pull request by kansal**
This is in continuation with the PR #618.

### CODE REVIEW

**Comment by DaanHoogland** [comment]
h @kansal, please add a ref to the issue in the commit message, thanks

**Comment by remibergsma** [comment]
@kansal Any update on this? Please rebase with current master.

**Comment by bhaisaab** [comment]
@kansal LGTM, can you rebase against master; then we can merge this. Thanks.

**Comment by koushik-das** [comment]
LGTM. Looks like travis failures are unrelated

**Comment by koushik-das** [comment]
2 LGTMs, merging

**Pull request merged**
