### PR TITLE
Security Group: add secondary ips to the correct ipset based on ip family (4.11)

### PR DESCRIPTION
**Pull request by RPDiep**
## Description

Currently secondary ipv6 addresses are added to the ipv4 ipset in security_group.py.
This doesn't work, so this patch adds a function to split a set of ips in ipv4 and ipv6 addresses.
Both the `default_network_rules` and `network_rules_vmSecondaryIp` functions now utilise this function and add the ips to the appropriate ipsets.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

Tried on a 4.11 hypervisor. Results were as expected

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
Jenkins is to busy waiting for itself. we probably started to many PR verification builds.

**Comment by rafaelweingartner** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@wido are you lgtm on the changes and is this tested in prod?
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
three time a charm...?
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by RPDiep** [comment]
Sorry, just pushed two commits that were fixing a bug in security_group.py , hadn't considered this open PR .
```
2018-11-22 08:11:49,447 - Failed to network rule !
Traceback (most recent call last):
  File "/usr/share/cloudstack-common/scripts/vm/network/security_group.py", line 1023, in add_network_rules
    default_network_rules(vmName, vm_id, vm_ip, vm_ip6, vmMac, vif, brname, sec_ips)
  File "/usr/share/cloudstack-common/scripts/vm/network/security_group.py", line 514, in default_network_rules
    if ips[0] == "0":
IndexError: list index out of range
```
ips was empty and it wasn't checked against.
Needed to fix this as we were having issues but should have put them in another branch.
Do you need me to revert this and open another PR based on this one?

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Pull request merged**
