### PR TITLE
Display vlan ip range for specified domainid

### PR DESCRIPTION
**Pull request by ravening**
### Description
Currently if we try to list vlan ip range by passing
domainid then it lists for all domain. Make sure that
it lists only for that domain

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### Screenshots (if appropriate):
Before the changes

```
(local) 🐱 > list vlanipranges domainid=4aa4c-f694-45c0-8844-8d9a129
{
  "count": 14,
  "vlaniprange": [
```

After the changes
```
(local) 🐱 > list vlanipranges domainid=4560c-f694-45c0-8844-8d94129
{
  "count": 1,
  "vlaniprange": [
```

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@ravening, do you intend this for master/4.16 only or do you want this on older versions?

**Comment by ravening** [comment]
> @ravening, do you intend this for master/4.16 only or do you want this on older versions?

@DaanHoogland 4.16 is good

**Review by DaanHoogland — COMMENTED** [review]
no comment on this PR but all this `DAO` code really shouldn't be in the `ManagementServer`

**Comment by rhtyd** [comment]
ping @ravening

**Comment by ravening** [comment]
> no comment on this PR but all this `DAO` code really shouldn't be in the `ManagementServer`

@DaanHoogland any idea where else I can add this ?

**Comment by DaanHoogland** [comment]
> > no comment on this PR but all this `DAO` code really shouldn't be in the `ManagementServer`
> 
> @DaanHoogland any idea where else I can add this ?

`DomainVlanMapDaoImpl`, i'd say.

**Comment by DaanHoogland** [comment]
@ravening you have a new conflict

**Comment by nvazquez** [comment]
@ravening can you move the logic to the DAO layer and fix the conflicts?

**Comment by ravening** [comment]
> > > no comment on this PR but all this `DAO` code really shouldn't be in the `ManagementServer`
> > 
> > 
> > @DaanHoogland any idea where else I can add this ?
> 
> `DomainVlanMapDaoImpl`, i'd say.

@DaanHoogland Im using the same code which is used by `account` and `pod` also which are present above and below of this code. So even they needs to be moved away?

I searched in other places in the same file and they are also using the same logic. for eg: publicipaddress, loadbalancer, resourcetag, vlan, guestos

**Comment by DaanHoogland** [comment]
> > > > no comment on this PR but all this `DAO` code really shouldn't be in the `ManagementServer`
> > > 
> > > 
> > > @DaanHoogland any idea where else I can add this ?
> > 
> > 
> > `DomainVlanMapDaoImpl`, i'd say.
> 
> @DaanHoogland Im using the same code which is used by `account` and `pod` also which are present above and below of this code. So even they needs to be moved away?
> 
> I searched in other places in the same file and they are also using the same logic. for eg: publicipaddress, loadbalancer, resourcetag, vlan, guestos

@ravening the rest of the code is not perfect and should be in DAOs as well. I'm not asking that of you now as I don't expect you to fix everything in one go, just to not add to the technical debt we have.

**Comment by rhtyd** [comment]
Ping @ravening can you address review and fix conflicts, thanks

**Comment by weizhouapache** [comment]
> > > > > no comment on this PR but all this `DAO` code really shouldn't be in the `ManagementServer`
> > > > 
> > > > 
> > > > @DaanHoogland any idea where else I can add this ?
> > > 
> > > 
> > > `DomainVlanMapDaoImpl`, i'd say.
> > 
> > 
> > @DaanHoogland Im using the same code which is used by `account` and `pod` also which are present above and below of this code. So even they needs to be moved away?
> > I searched in other places in the same file and they are also using the same logic. for eg: publicipaddress, loadbalancer, resourcetag, vlan, guestos
> 
> @ravening the rest of the code is not perfect and should be in DAOs as well. I'm not asking that of you now as I don't expect you to fix everything in one go, just to not add to the technical debt we have.

@DaanHoogland 
 
there are more than ten Dao.search() or Dao.searchAndCount() in ManagementServerImpl.java, and much more in QueryManagerImpl.java
we do not need to move everything into DAO, especially for the searches in multiple (more than 2) tables.

**Comment by ravening** [comment]
> Ping @ravening can you address review and fix conflicts, thanks

@rhtyd done

**Comment by DaanHoogland** [comment]
> > > > > > no comment on this PR but all this `DAO` code really shouldn't be in the `ManagementServer`
> > > > > 
> > > > > 
> > > > > @DaanHoogland any idea where else I can add this ?
> > > > 
> > > > 
> > > > `DomainVlanMapDaoImpl`, i'd say.
> > > 
> > > 
> > > @DaanHoogland Im using the same code which is used by `account` and `pod` also which are present above and below of this code. So even they needs to be moved away?
> > > I searched in other places in the same file and they are also using the same logic. for eg: publicipaddress, loadbalancer, resourcetag, vlan, guestos
> > 
> > 
> > @ravening the rest of the code is not perfect and should be in DAOs as well. I'm not asking that of you now as I don't expect you to fix everything in one go, just to not add to the technical debt we have.
> 
> @DaanHoogland
> 
> there are more than ten Dao.search() or Dao.searchAndCount() in ManagementServerImpl.java, and much more in QueryManagerImpl.java
> we do not need to move everything into DAO, especially for the searches in multiple (more than 2) tables.

no, but those single table transactions that can we should.

**Comment by weizhouapache** [comment]
> > > > > > > no comment on this PR but all this `DAO` code really shouldn't be in the `ManagementServer`
> > > > > > 
> > > > > > 
> > > > > > @DaanHoogland any idea where else I can add this ?
> > > > > 
> > > > > 
> > > > > `DomainVlanMapDaoImpl`, i'd say.
> > > > 
> > > > 
> > > > @DaanHoogland Im using the same code which is used by `account` and `pod` also which are present above and below of this code. So even they needs to be moved away?
> > > > I searched in other places in the same file and they are also using the same logic. for eg: publicipaddress, loadbalancer, resourcetag, vlan, guestos
> > > 
> > > 
> > > @ravening the rest of the code is not perfect and should be in DAOs as well. I'm not asking that of you now as I don't expect you to fix everything in one go, just to not add to the technical debt we have.
> > 
> > 
> > @DaanHoogland
> > there are more than ten Dao.search() or Dao.searchAndCount() in ManagementServerImpl.java, and much more in QueryManagerImpl.java
> > we do not need to move everything into DAO, especially for the searches in multiple (more than 2) tables.
> 
> no, but those single table transactions that can we should.

@DaanHoogland agree .

as you can see in the code changes of this pr, the search on vlans has some join tables (DomainVlanMapDao, AccountVlanMapDao, PodVlanMapDao)

**Comment by nvazquez** [comment]
@DaanHoogland @weizhouapache let's get a consensus on this PR to try moving it forward as it seems the requested changes may not be applied. Would that be a reason for a -1 on this PR for any of you?
@blueorangutan package

**Comment by rhtyd** [comment]
If it's fixing a bug then +1 (sounds like you can't list Vlans for a domain?) but this would need testing

**Comment by davidjumani** [comment]
@blueorangutan test suse15 kvm-suse15

**Review by davidjumani — APPROVED** [review]
Verified, only returns for the respective domainid if passed and empty set if not reserved

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Review by nvazquez — APPROVED** [review]
LGTM

**Comment by nvazquez** [comment]
Manually tested + 2xLGTM - ready for merge after tests pass

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
-0 if we allow for a mix of concerns in manager implementations we will increase the number of code conflict we will get over time. We should strive for better separation as much as possible. I'm not going to block this simple fix over this but it is an increasing concern. Calls to DAOs could have been made.

**Comment by sureshanaparti** [comment]
> -0 if we allow for a mix of concerns in manager implementations we will increase the number of code conflict we will get over time. We should strive for better separation as much as possible. I'm not going to block this simple fix over this but it is an increasing concern. Calls to DAOs could have been made.

@DaanHoogland want to add this to cwiki / issues (as improvement) to track it later?

**Comment by sureshanaparti** [comment]
> Manually tested + 2xLGTM - ready for merge after tests pass

Merging based on LGTMs, and manual / smoke tests.

**Pull request merged**
