### PR TITLE
Fixed box location on vagrant files for devcloud4 (CLOUDSTACK-8898)

### PR DESCRIPTION
**Pull request by pdube**
The centos-6.5 is no longer available

### CODE REVIEW

**Comment by pdion891** [comment]
@pdube, we forgot to review that earlier but I think ```binary-installation-advanced``` and  ```binary-installation-basic``` need to be updated as well. Can you update your PR ?  thanks!

**Comment by karuturi** [comment]
I faced the same issue and using bento/centos6.7 fixed it.
:+1: tested only in advanced

**Comment by pdube** [comment]
Thank you @pdion891 @karuturi. Fixed in the last commit

**Comment by pdion891** [comment]
LGTM

**Comment by karuturi** [comment]
:+1: merging..

**Pull request merged**
