### PR TITLE
Validate host tags on VM live scale

### PR DESCRIPTION
**Pull request by BryanMLima**
### Description

Currently, ACS does not validate host tags on running VMs that have their computing resources increased via Scale VM command. Therefore, if a service offering with host tags deploys on a host with the same host tags, it is permitted to live scale this VM to another service offering with another host tags. This PR aims to fix this bug, verifying the host tags on a VM live scaling.
### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### How Has This Been Tested?
This was tested in a local lab with the following scenario:

1. VM deployed with a service offering with host tags `hdd`.
2. Tried to live scale the VM with another service offering with host tags `ssd`.
3. An error occurred while scaling the VM, as expected.

### CODE REVIEW

**Review by GutoVeronezi — APPROVED** [review]
CLGTM

**Comment by GutoVeronezi** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Review by JoaoJandre — APPROVED** [review]
CLGTM

**Review by RodrigoDLopez — APPROVED** [review]
clgtm

**Comment by BryanMLima** [comment]
@DaanHoogland @GutoVeronezi Could you take another look on this one? I think this PR is already good to merge.

**Comment by DaanHoogland** [comment]
trusting the developers tests on this one

**Comment by rohityadavcloud** [comment]
cc @DaanHoogland milestone missing

**Comment by rohityadavcloud** [comment]
Also manual tests if any required missing cc @shwstppr @harikrishna-patnala

**Pull request merged**
