### PR TITLE
Fix the poll for the API ReadyForShutdown even after logout

### PR DESCRIPTION
**Pull request by harikrishna-patnala**
### Description

This PR fixes the issue of continuous poll of ReadyForShutdown API even after logout. 
This poll is causing issues after logout with unnecessary login error messages and API calls

image

Steps to reproduce the issue or test the fix
1. Login into CloudStack
2. Observe the Networks tab in browser development console, observe "readyForShutdown" API calls
3. Logout from CloudStack

Observe that calling "readyForShutdown" API still continues. This PR clears that polling job.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
code looks good (/me testing)

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by kiranchavala — APPROVED** [review]
LGTM, Tested it manually the ready-for-shutdown api  is not called after logout

**Review by rohityadavcloud — APPROVED** [review]
Didn't test it but LGTM

**Comment by DaanHoogland** [comment]
> LGTM, Tested it manually the ready-for-shutdown api is not called after logout

thanks for taking this off my hands @kiranchavala , I am running a smoke test run in the background and will merge if successful.

**Pull request merged**
