### PR TITLE
[KVM] Skip volumes on shared storage when live migrating VM with local volumes (root / datadisk)

### PR DESCRIPTION
**Pull request by GabrielBrascher**
### Description

The new release [Libvirt-Java v0.5.3](https://gitlab.com/libvirt/libvirt-java/-/tags/v0.5.3) now supports `virDomainMigrate3`[[1]](https://gitlab.com/libvirt/libvirt-java/),[[2]](https://gitlab.com/libvirt/libvirt-java/-/commit/e45d3fb8bccab2d3048f902f0be74308afc923df), a powerful and flexible _domain migrate_ command in Libvirt. This command allows pointing just the Root volume to be migrated, saving a lot of compute resources, network bandwidth, and time. 

Likely, data disks hold TBs of data, while Root volumes hundreds of GBs. This allows saving crucial time, bandwidth, and processing.

It can easily save several hours to offload a KVM machine depending on the amount of VMs to be migrated and data disks attached to the respective VMs.

[[1] Libvirt-Java](https://gitlab.com/libvirt/libvirt-java/)
[[2] commit that added `virtDomainMigrate3` into the Libvirt-Java](https://gitlab.com/libvirt/libvirt-java/-/commit/e45d3fb8bccab2d3048f902f0be74308afc923df)
Fore reference, PR https://github.com/apache/cloudstack/pull/6472 added `libvirt-java v0.5.3` into CloudStack.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [X] Major
- [ ] Minor

### How Has This Been Tested?

Tested migration of VM with local Root (50GB) + data-disk (100GB)
1. As an example, this is a scenario without this PR:
```
~# virsh domjobinfo i-2-345-VM
Job type:         Unbounded   
Operation:        Outgoing migration
Time elapsed:     17063        ms
Data processed:   2.938 GiB
Data remaining:   147.065 GiB
Data total:       150.004 GiB
File processed:   2.938 MiB
File remaining:   147.065 GiB
File total:       150.004 GiB
```
**Data total 150.004  GiB**

2. When testing the same migration but with the changes of the PR:
```
~# virsh domjobinfo i-2-345-VM
Job type:         Unbounded   
Operation:        Outgoing migration
Time elapsed:     10300        ms
Data processed:   952.000 MiB
Data remaining:   49.070 GiB
Data total:       50.000 GiB
File processed:   952.000 MiB
File remaining:   49.070 GiB
File total:       50.000 GiB
```
**Data total 50.000 GiB**

### CODE REVIEW

**Review by RodrigoDLopez — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@GabrielBrascher can you have a look on the conflicts

**Comment by GabrielBrascher** [comment]
@DaanHoogland I was going to fix the branch conflict but then realise that it happens on main but not on 4.17.

Do you guys feel like this would be fine to be added in 4.17.1? @harikrishna-patnala @rohityadavcloud @DaanHoogland @wido @nvazquez others
Or should I target it to the main?


It could be placed as bugfix (since cloudstack migrates disks that are not desired due to Libvirt-Java 0.5.2 limitations).
Could also be argued as an enhancement PR as migrations were working (but taking waaay too long).

**Comment by GabrielBrascher** [comment]
I see some work recently done that allows multiple volumes on local storage. I will double-check these new PRs and see potential risks as I've considered 1 local volume (root) to be mapped.

**Comment by DaanHoogland** [comment]
> I see some work recently done that allows multiple volumes on local storage. I will double-check these new PRs and see potential risks as I've considered 1 local volume (root) to be mapped in the new Libvirt migration flow.

so should we move this to draft, @GabrielBrascher ?

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@GabrielBrascher Can you the fix these audit errors.

```
[ERROR] /jenkins/workspace/acs-centos7-pkg-builder/dist/rpmbuild/BUILD/cloudstack-4.18.0.0-SNAPSHOT/plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapper.java:27:8: Unused import - java.util.Collections. [UnusedImports]
[ERROR] /jenkins/workspace/acs-centos7-pkg-builder/dist/rpmbuild/BUILD/cloudstack-4.18.0.0-SNAPSHOT/plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapper.java:38:8: Unused import - java.util.stream.Collectors. [UnusedImports]
```

**Comment by shwstppr** [comment]
Hi @GabrielBrascher, should we consider this for 4.17.1.0? Currently, it has conflicts, can you please check

**Pull request closed without merging**
