### PR TITLE
VM.CREATE/VOLUME.DELETE/VOLUME.DESTROY not being emitted

### PR DESCRIPTION
**Pull request by mprokopchuk**
### Description

deployVirtualMachine can be provided with disk offerings for data disks, and destroyVirtualMachine can be set to expunge data disks. This specific circumstance is not publishing volume delete event.

This radar is similar to https://github.com/apache/cloudstack/pull/6939

Create VM with Volume
Delete VM and set expunge and add Volume to be removal as well

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### Screenshots (if appropriate):
Create VM:
244826799-5476685d-573a-4067-96b3-fc008a813f83

Create VM auto-start:
244826925-59026ef7-f77b-4fdb-bc04-caf0c22418b9

Delete VM:
244826828-8a1ba4a8-4a72-4cf9-a647-3a1c8da47a66

Expunge VM:
244826895-ee997c67-d27f-4bdd-ac18-876c5ea39b35

### How Has This Been Tested?

Tested manually.

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Review by rohityadavcloud — APPROVED** [review]
LGTM didn't test it though

**Comment by shwstppr** [comment]
Should this go into 4.18? @mprokopchuk cc @rohityadavcloud @DaanHoogland

**Comment by mprokopchuk** [comment]
Yes, I would like it to be merged to 4.18 if that is possible.

**Comment by DaanHoogland** [comment]
@mprokopchuk you'll need to rebase your code onto 4.18-head and force push your branch. 

> Yes, I would like it to be merged to 4.18 if that is possible.

**Comment by mprokopchuk** [comment]
> @mprokopchuk you'll need to rebase your code onto 4.18-head and force push your branch.
>

**Comment by mprokopchuk** [comment]
> > @mprokopchuk you'll need to rebase your code onto 4.18-head and force push your branch.

Rebased onto 4.18

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@mprokopchuk @mlsorensen the branch isn't rebased against 4.18, we are seeing many additional commits. Can you cherry-pick commits to a 4.18 branch and force push, or want us to assist? cc @DaanHoogland

**Pull request closed without merging**
