### PR TITLE
CLOUDSTACK-8457: SAML auth plugin improvements for production usage

### PR DESCRIPTION
**Pull request by bhaisaab**
Squashed branch saml-production-grade branch to one commit for easy merge/commit. Open for review but please don't merge it yet as I'm yet to improve some UI changes.

### CODE REVIEW

**Comment by bhaisaab** [comment]
open for review

**Comment by terbolous** [comment]
I can test your changes against ADFS if you want to, not sure if I can find time this week though.

**Comment by bhaisaab** [comment]
@terbolous I plan to build and share a repo tomorrow that you can use

**Comment by bhaisaab** [comment]
@terbolous doing some UI changes now

**Comment by terbolous** [comment]
Excellent, let me know when you consider it ready and I'll give it a spin.

Erik

Den torsdag 25. juni 2015 skrev Rohit Yadav <notifications@github.com>
følgende:

**Comment by bhaisaab** [comment]
With the plugin enabled, only then users are shown a choice of login options:
screen shot 2015-06-25 at 5 32 07 pm

Localization example with local login selected:
screen shot 2015-06-25 at 5 32 29 pm

After user selects a IDP server, they may optionally pass a domain path if they have multiple accounts across various domains for the authorized IDP server:
screen shot 2015-06-25 at 5 26 30 pm

**Pull request closed without merging**
