### PR TITLE
VMware: Guest OS Mappings fix

### PR DESCRIPTION
**Pull request by andrijapanicsb**
In past, we added Debian 10 32bit guest_os entry with ID 292, (282 is RHEL 7.3) but then added (by mistake) entries in guest_os_hypervisor table for VMware and "debian10Guest" that points to guest_os_id 282 (RHEL 7.3), instead of 292 (Debian10)

Also fix centos6Guest mapping for Vmware 5.5 which does not exist in that version.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## Screenshots (if appropriate):
Bug example (for VMware 6.5, but same for 6.7, 6.7.1.2.3)
image

## How Has This Been Tested?
image

image

### CODE REVIEW

**Review by yadvr — APPROVED** [review]

**Review by nvazquez — APPROVED** [review]
LGTM

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-65u3

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-65u2

**Pull request merged**
