### PR TITLE
Set version to 4.8.1-SNAPSHOT in 4.8 branch

### PR DESCRIPTION
**Pull request by remibergsma**
After releasing 4.8.0, next version is 4.8.1-SNAPSHOT in 4.8 branch.

### CODE REVIEW

**Comment by remibergsma** [comment]
I'll also add the upgrade paths to this PR

**Comment by remibergsma** [comment]
Tested upgrade from `4.7.2` to `4.8.1` and that succeeded:

```
2016-01-26 13:06:13,421 INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) DB version = 4.7.2 Code Version = 4.8.1-SNAPSHOT
2016-01-26 13:06:13,422 INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Database upgrade must be performed from 4.7.2 to 4.8.1-SNAPSHOT
2016-01-26 13:06:13,422 DEBUG [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Running upgrade Upgrade471to480 to upgrade from 4.7.1-4.8.0 to 4.8.0
2016-01-26 13:06:13,425 DEBUG [c.c.u.s.Script] (main:null) (logid:) Looking for db/schema-471to480.sql in the classpath
2016-01-26 13:06:13,425 DEBUG [c.c.u.s.Script] (main:null) (logid:) System resource: null
2016-01-26 13:06:13,426 DEBUG [c.c.u.s.Script] (main:null) (logid:) Classpath resource: file:/data/git/cs2/cloudstack/client/target/utilities/scripts/db/db/schema-471to480.sql
2016-01-26 13:06:13,426 DEBUG [c.c.u.s.Script] (main:null) (logid:) Absolute path =  /data/git/cs2/cloudstack/client/target/utilities/scripts/db/db/schema-471to480.sql
2016-01-26 13:06:13,428 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- Licensed to the Apache Software Foundation (ASF) under one
2016-01-26 13:06:13,428 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- or more contributor license agreements.  See the NOTICE file
2016-01-26 13:06:13,428 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- distributed with this work for additional information
2016-01-26 13:06:13,428 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- regarding copyright ownership.  The ASF licenses this file
2016-01-26 13:06:13,428 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- to you under the Apache License, Version 2.0 (the
2016-01-26 13:06:13,428 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- "License"); you may not use this file except in compliance
2016-01-26 13:06:13,428 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- with the License.  You may obtain a copy of the License at
2016-01-26 13:06:13,428 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) --
2016-01-26 13:06:13,428 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) --   http://www.apache.org/licenses/LICENSE-2.0
2016-01-26 13:06:13,428 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) --
2016-01-26 13:06:13,428 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- Unless required by applicable law or agreed to in writing,
2016-01-26 13:06:13,428 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- software distributed under the License is distributed on an
2016-01-26 13:06:13,428 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
2016-01-26 13:06:13,428 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- KIND, either express or implied.  See the License for the
2016-01-26 13:06:13,428 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- specific language governing permissions and limitations
2016-01-26 13:06:13,428 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- under the License.
2016-01-26 13:06:13,428 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) --;
2016-01-26 13:06:13,428 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- Schema upgrade from 4.7.1 to 4.8.0;
2016-01-26 13:06:13,428 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) --;
2016-01-26 13:06:13,428 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) ALTER TABLE `cloud`.`nicira_nvp_router_map` DROP INDEX `logicalrouter_uuid`  
2016-01-26 13:06:13,483 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) ALTER TABLE `cloud`.`volume_host_ref` MODIFY COLUMN `url` varchar(2048) 
2016-01-26 13:06:13,496 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) ALTER TABLE `cloud`.`object_datastore_ref` MODIFY COLUMN `url` varchar(2048) 
2016-01-26 13:06:13,507 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) ALTER TABLE `cloud`.`image_store` MODIFY COLUMN `url` varchar(2048) 
2016-01-26 13:06:13,523 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) ALTER TABLE `cloud`.`template_store_ref` MODIFY COLUMN `url` varchar(2048) 
2016-01-26 13:06:13,533 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) ALTER TABLE `cloud`.`volume_store_ref` MODIFY COLUMN `url` varchar(2048) 
2016-01-26 13:06:13,544 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) ALTER TABLE `cloud`.`volume_store_ref` MODIFY COLUMN `download_url` varchar(2048) 
2016-01-26 13:06:13,568 DEBUG [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Running upgrade Upgrade480to481 to upgrade from 4.8.0-4.8.1 to 4.8.1
2016-01-26 13:06:13,569 DEBUG [c.c.u.s.Script] (main:null) (logid:) Looking for db/schema-480to481.sql in the classpath
2016-01-26 13:06:13,569 DEBUG [c.c.u.s.Script] (main:null) (logid:) System resource: null
2016-01-26 13:06:13,570 DEBUG [c.c.u.s.Script] (main:null) (logid:) Classpath resource: file:/data/git/cs2/cloudstack/client/target/utilities/scripts/db/db/schema-480to481.sql
2016-01-26 13:06:13,570 DEBUG [c.c.u.s.Script] (main:null) (logid:) Absolute path =  /data/git/cs2/cloudstack/client/target/utilities/scripts/db/db/schema-480to481.sql
2016-01-26 13:06:13,570 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- Licensed to the Apache Software Foundation (ASF) under one
2016-01-26 13:06:13,570 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- or more contributor license agreements.  See the NOTICE file
2016-01-26 13:06:13,570 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- distributed with this work for additional information
2016-01-26 13:06:13,570 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- regarding copyright ownership.  The ASF licenses this file
2016-01-26 13:06:13,570 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- to you under the Apache License, Version 2.0 (the
2016-01-26 13:06:13,570 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- "License"); you may not use this file except in compliance
2016-01-26 13:06:13,570 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- with the License.  You may obtain a copy of the License at
2016-01-26 13:06:13,570 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) --
2016-01-26 13:06:13,571 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) --   http://www.apache.org/licenses/LICENSE-2.0
2016-01-26 13:06:13,571 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) --
2016-01-26 13:06:13,571 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- Unless required by applicable law or agreed to in writing,
2016-01-26 13:06:13,571 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- software distributed under the License is distributed on an
2016-01-26 13:06:13,571 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
2016-01-26 13:06:13,571 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- KIND, either express or implied.  See the License for the
2016-01-26 13:06:13,571 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- specific language governing permissions and limitations
2016-01-26 13:06:13,571 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- under the License.
2016-01-26 13:06:13,571 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) --;
2016-01-26 13:06:13,571 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- Schema upgrade from 4.8.0 to 4.8.1;
2016-01-26 13:06:13,571 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) --;
2016-01-26 13:06:13,574 INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Cleaning upgrades because all management server are now at the same version
2016-01-26 13:06:13,576 DEBUG [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Upgrading to version 4.8.0...
2016-01-26 13:06:13,576 INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Cleanup upgrade Upgrade471to480 to upgrade from 4.7.1-4.8.0 to 4.8.0
2016-01-26 13:06:13,577 DEBUG [c.c.u.s.Script] (main:null) (logid:) Looking for db/schema-471to480-cleanup.sql in the classpath
2016-01-26 13:06:13,577 DEBUG [c.c.u.s.Script] (main:null) (logid:) System resource: null
2016-01-26 13:06:13,578 DEBUG [c.c.u.s.Script] (main:null) (logid:) Classpath resource: file:/data/git/cs2/cloudstack/client/target/utilities/scripts/db/db/schema-471to480-cleanup.sql
2016-01-26 13:06:13,578 DEBUG [c.c.u.s.Script] (main:null) (logid:) Absolute path =  /data/git/cs2/cloudstack/client/target/utilities/scripts/db/db/schema-471to480-cleanup.sql
2016-01-26 13:06:13,578 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- Licensed to the Apache Software Foundation (ASF) under one
2016-01-26 13:06:13,579 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- or more contributor license agreements.  See the NOTICE file
2016-01-26 13:06:13,579 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- distributed with this work for additional information
2016-01-26 13:06:13,579 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- regarding copyright ownership.  The ASF licenses this file
2016-01-26 13:06:13,579 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- to you under the Apache License, Version 2.0 (the
2016-01-26 13:06:13,579 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- "License"); you may not use this file except in compliance
2016-01-26 13:06:13,579 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- with the License.  You may obtain a copy of the License at
2016-01-26 13:06:13,579 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) --
2016-01-26 13:06:13,579 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) --   http://www.apache.org/licenses/LICENSE-2.0
2016-01-26 13:06:13,579 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) --
2016-01-26 13:06:13,579 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- Unless required by applicable law or agreed to in writing,
2016-01-26 13:06:13,579 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- software distributed under the License is distributed on an
2016-01-26 13:06:13,579 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
2016-01-26 13:06:13,579 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- KIND, either express or implied.  See the License for the
2016-01-26 13:06:13,579 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- specific language governing permissions and limitations
2016-01-26 13:06:13,579 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- under the License.
2016-01-26 13:06:13,579 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) --;
2016-01-26 13:06:13,579 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- Schema cleanup from 4.7.1 to 4.8.0;
2016-01-26 13:06:13,579 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) --;
2016-01-26 13:06:13,579 DEBUG [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Cleanup script /data/git/cs2/cloudstack/client/target/utilities/scripts/db/db/schema-471to480-cleanup.sql is executed successfully
2016-01-26 13:06:13,592 DEBUG [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Upgrade completed for version 4.8.0
2016-01-26 13:06:13,599 DEBUG [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Upgrading to version 4.8.1...
2016-01-26 13:06:13,599 INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Cleanup upgrade Upgrade480to481 to upgrade from 4.8.0-4.8.1 to 4.8.1
2016-01-26 13:06:13,599 DEBUG [c.c.u.s.Script] (main:null) (logid:) Looking for db/schema-480to481-cleanup.sql in the classpath
2016-01-26 13:06:13,599 DEBUG [c.c.u.s.Script] (main:null) (logid:) System resource: null
2016-01-26 13:06:13,601 DEBUG [c.c.u.s.Script] (main:null) (logid:) Classpath resource: file:/data/git/cs2/cloudstack/client/target/utilities/scripts/db/db/schema-480to481-cleanup.sql
2016-01-26 13:06:13,602 DEBUG [c.c.u.s.Script] (main:null) (logid:) Absolute path =  /data/git/cs2/cloudstack/client/target/utilities/scripts/db/db/schema-480to481-cleanup.sql
2016-01-26 13:06:13,602 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- Licensed to the Apache Software Foundation (ASF) under one
2016-01-26 13:06:13,602 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- or more contributor license agreements.  See the NOTICE file
2016-01-26 13:06:13,602 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- distributed with this work for additional information
2016-01-26 13:06:13,602 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- regarding copyright ownership.  The ASF licenses this file
2016-01-26 13:06:13,602 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- to you under the Apache License, Version 2.0 (the
2016-01-26 13:06:13,602 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- "License"); you may not use this file except in compliance
2016-01-26 13:06:13,602 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- with the License.  You may obtain a copy of the License at
2016-01-26 13:06:13,602 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) --
2016-01-26 13:06:13,602 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) --   http://www.apache.org/licenses/LICENSE-2.0
2016-01-26 13:06:13,602 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) --
2016-01-26 13:06:13,603 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- Unless required by applicable law or agreed to in writing,
2016-01-26 13:06:13,603 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- software distributed under the License is distributed on an
2016-01-26 13:06:13,603 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
2016-01-26 13:06:13,603 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- KIND, either express or implied.  See the License for the
2016-01-26 13:06:13,603 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- specific language governing permissions and limitations
2016-01-26 13:06:13,603 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- under the License.
2016-01-26 13:06:13,603 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) --;
2016-01-26 13:06:13,603 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) -- Schema cleanup from 4.8.0 to 4.8.1;
2016-01-26 13:06:13,603 DEBUG [c.c.u.d.ScriptRunner] (main:null) (logid:) --;
2016-01-26 13:06:13,604 DEBUG [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Cleanup script /data/git/cs2/cloudstack/client/target/utilities/scripts/db/db/schema-480to481-cleanup.sql is executed successfully
2016-01-26 13:06:13,604 DEBUG [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Upgrade completed for version 4.8.1
```

**Comment by remibergsma** [comment]
Ping @borisroman @DaanHoogland Please review.

**Comment by pdion891** [comment]
LGTM,  release number change.

**Comment by rafaelweingartner** [comment]
LGTM giving  that it is a simple upgrade of version.

**Pull request merged**
