### PR TITLE
Fix Listing backup schedules

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

This PR fixes the issue with listing backup schedules caused by https://github.com/apache/cloudstack/pull/9451

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [X] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
clgtm and logic seems fair. @weizhouapache @sureshanaparti can you review as well? @JoaoJandre this is a regression, so I think we should considder this a BLOCKER issue.

**Review by rohityadavcloud — APPROVED** [review]

**Review by JoaoJandre — APPROVED** [review]
LGTM

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by weizhouapache — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@blueorangutan test keepEnv

**Comment by JoaoJandre** [comment]
@Pearl1594 could you describe what happened before this patch and what tests were made to validate that this patch fixes the issue?

**Comment by JoaoJandre** [comment]
> @JoaoJandre because of the incorrect check, it never listed any backup schedules even if there were present.

@Pearl1594 I see. So did you test that the solution fixes the issue completely? I ask because there are no tests on the PR description and nowhere else on the PR.

**Comment by Pearl1594** [comment]
Yes, unfortunately this class wasn't covered with tests, and I didn't add any either. But this has at this point been manually tested considering the release is on-going. Probably I could add tests in a subsequent enhancement PR that I have already opened for 4.20.1.

**Comment by JoaoJandre** [comment]
> Yes, unfortunately this class wasn't covered with tests, and I didn't add any either. But this has at this point been manually tested considering the release is on-going. Probably I could add tests in a subsequent enhancement PR that I have already opened for 4.20.1.

@Pearl1594 What I meant in my previous messages is that the PR is missing the description of the steps that you made to verify that this PR fixes the described issue, something like this: https://github.com/apache/cloudstack/pull/9662#pullrequestreview-2296340166

**Comment by Pearl1594** [comment]
Ah, my bad. I didn't quite understand it.
Manual test done:
1. Created a Backup offering
2. Created a VM and associated it to a backup offering
3. Configured backup Schedule for the VM
4. After Creating the schedule, move to the Scheduled Backups tab in the pop-up window. You should now be able to see the schedule(s) created.

**Pull request merged**
