### PR TITLE
Localization: Hellenic (Greek) Translation

### PR DESCRIPTION
**Pull request by fermosan**
Modifications in TranslationMenu.vue as well

### Description

This PR...

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### CODE REVIEW

**Comment by fermosan** [comment]
@rhtyd 
Hello again. I uploaded the wrong file by mistake. Sorry. Now should be fine. 👍

**Comment by rhtyd** [comment]
@blueorangutan ui

**Review by utchoang — APPROVED** [review]
LGTM! Thanks @fermosan

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
Tested the UI build as well as reverse translation of some Greek strings to English. LGTM.
Thanks @fermosan merged on 4.15, this will make into 4.15.1.0.

**Comment by fermosan** [comment]
tyvm all. :) Happy 4.15.1.0 🥳

**Pull request merged**
