### PR TITLE
create template from snapshot regression (partly reverted)

### PR DESCRIPTION
**Pull request by DaanHoogland**
## Description

see #3723 for details. backport after merging

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by GabrielBrascher** [comment]
@DaanHoogland If I understood it correctly, this PR should go to 4.13.1.0. If so, can you please change the target branch to 4.13?

**Comment by borisstoyanov** [comment]
Have I missed something here? Where did take snapshot button go? 
Screenshot 2019-12-13 at 15 18 46

**Comment by DaanHoogland** [comment]
tnx @GabrielBrascher 
@borisstoyanov I have no idea, this PR is about creating templates from snapshots, not about creating snapshots. seems like you have another issue there.

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
I double checked the changes in this PR @borisstoyanov . These exact changes are in master so if the bug is not on master there is something else wrong either in 4.13 or inyour env. I'm testing in simulator as well.

**Pull request merged**
