### PR TITLE
[4.10/master] Smoketests Health

### PR DESCRIPTION
**Pull request by rhtyd**
@blueorangutan package

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@karuturi these are latest qa results on master. Looks like some new intermittent errors on vmware. The redundant-vpc related errors are known and ignorable.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@karuturi @swill @wido @mike-tutkowski and others -- please have a look at some of the failing tests in the last test run above ^^  for latest 4.10/master.

**Comment by wido** [comment]
I see that a VPC test is failing. #2089 isn't merged, so that can't be the case.

I have no VPC experience, so I can't tell why it would be failing.

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test matrix

**Pull request closed without merging**
