### PR TITLE
README: that time of the year! 🎄

### PR DESCRIPTION
**Pull request by rohityadavcloud**
Screenshot for changes:
Screenshot 2023-12-15 at 7 21 25 PM

Hope this can be merged without packaging or smoketests before end of the year ;)

To all of the CloudStack contributors - Happy Christmas and holidays!

/cc alphabetically-ish @abh1sar @alexandremattioli @andrijapanicsb @borisstoyanov @BryanMLima @chiradeep @DaanHoogland @GabrielBrascher @GaOrtiga @gsirett @GutoVeronezi @harikrishna-patnala @hsato03 @rajujith @jbampton @JoaoJandre @kiwiflyer @kiranchavala @kishankavala @mlsorensen @msinhore @NuxRo @nvazquez @Pearl1594 @PeterBackroll @pdion891 @RodrigoDLopez @rp- @SadiJr @shwstppr @slavkap @soreana @steveroles @SadiJr @sureshanaparti @svenvogel @swill @syed @utchoang @vishesh92 @vladimirpetrov @winterhazel @weizhouapache @wido  and so many others! (I may have missed quite a few - you're all in my thoughts)

### CODE REVIEW

**Review by vishesh92 — APPROVED** [review]

**Review by NuxRo — APPROVED** [review]
LGTM! Merry Christmas, happy holidays etc!

**Review by borisstoyanov — APPROVED** [review]

**Review by vladimirpetrov — APPROVED** [review]
Happy holidays everyone!!!

**Comment by weizhouapache** [comment]
Merry Christmas and happy new year!

**Review by BryanMLima — APPROVED** [review]
Happy holidays!! :christmas_tree:

**Review by JoaoJandre — APPROVED** [review]
LGTM 
Happy holidays !!

**Review by slavkap — APPROVED** [review]
Happy holidays everyone! :christmas_tree:

**Review by soreana — APPROVED** [review]
Manually tested! LGTM! Happy holidays 🥳

**Review by Pearl1594 — APPROVED** [review]
LGTM.

Happy Holidays!

**Comment by gsirett** [comment]
LGTM

A very happy Christmas (to those who celebrate) and a peaceful new year to all

**Review by winterhazel — APPROVED** [review]
Happy holidays!!

**Comment by msinhore** [comment]
LGTM. Enjoy the holidays and happy new year!

**Review by hsato03 — APPROVED** [review]
LGTM

Happy holidays, guys! 🎉

**Review by shwstppr — APPROVED** [review]
Happy Christmas and happy new year to all!

**Review by GaOrtiga — APPROVED** [review]
Happy Holidays!!

**Review by nvazquez — APPROVED** [review]
Happy holidays everyone!

**Comment by rp-** [comment]
🎄

**Pull request merged**
