### PR TITLE
WIP: CLOUDSTACK-10118 Domain level settings

### PR DESCRIPTION
**Pull request by DaanHoogland**
The intentions with domain level settings is to make the ldap functionality configurable on a per domain basis. This will allow for business units or customers to maintain their own users.

Config enum unused methods removed

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@borisstoyanov I added a jira ticket. This is in itself not usefull, though. It requires use by some opther feature. I think it can be tested but no tests are available. CLOUDSTACK-10117 is the reason it is needed.

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@DaanHoogland can you rebase this and advise if this is ready for review/testing?

**Comment by DaanHoogland** [comment]
@rhtyd i will rebase but this change is structural for the ldap changes I am doing and does not have any merrit on it's own. It is here to keep an eye on integration. Marking it with WIP

**Comment by DaanHoogland** [comment]
closing in favour of #2369

**Pull request closed without merging**
