### PR TITLE
CLOUDSTACK-10072: Remove unused code from "com.cloud.vm.UserVmManagerImpl"

### PR DESCRIPTION
**Pull request by GabrielBrascher**
# Introduction

All changes in this PR started by removing unused methods from the "UserVmManagerImpl" class. That results in changing  two (2) of its implemented interfaces ("UserVmManager" and "UserVmService").

Also, the "UserVmManagerImplTest" class had small changes.

One unused interface was removed ("BareMetalVmService").
# Detailed work

Changes at the interface "com.cloud.vm.UserVmManager":
- removed method "com.cloud.vm.UserVmManager.getVirtualMachines(long)"
  that is not used at the class that implements this interface;
- removed method "com.cloud.vm.UserVmManager.stopVirtualMachine(long,
  long)" as it is not used at the "UserVmManagerImpl" class;

Changes at the class "com.cloud.vm.UserVmManagerImpl":
- "com.cloud.vm.UserVmManagerImpl.UserVmCloneType" enum access level
  from public to private;
- removed unused method
  "com.cloud.vm.UserVmManagerImpl.getVirtualMachines(long)";
- removed unused method
  "com.cloud.vm.UserVmManagerImpl.stopVirtualMachine(long, long)";
- removed unused method
  "com.cloud.vm.UserVmManagerImpl.deletePrivateTemplateRecord(Long)";
- removed unused method
  "com.cloud.vm.UserVmManagerImpl.getHypervisorTypeOfUserVM(long)";
- removed unused method
  "com.cloud.vm.UserVmManagerImpl.isDisplayResourceEnabled(Long)";
- changed access level certain global variables to protected or private
  (if possible);
- removed duplicated injected dependencies;
- removed null atributions to dependency injection objects (as by);
- removed unused variables.

Class "com.cloud.vm.UserVmManagerImpl.VmIpAddrFetchThread":
- changed variables access from public to private.

Class "com.cloud.vm.UserVmManagerTest":
- Used @InjectMocks to inject all
  "com.cloud.vm.UserVmManagerTest._userVmMgr" dependencies, allowing the
  cleaning of "manual injections" at the @Before block code
  ("com.cloud.vm.UserVmManagerTest.setup()").

It was removed the unused interface "com.cloud.vm.BareMetalVmService".

Interface "com.cloud.vm.UserVmService":
- removed the
  "com.cloud.vm.UserVmService.deletePrivateTemplateRecord(Long)" method
  that is unused at the class implementing this interface
  ("UserVmManagerImpl")
- removed the unused method
  "com.cloud.vm.UserVmService.isDisplayResourceEnabled(Long)";
- removed the unused method
  "com.cloud.vm.UserVmService.getHypervisorTypeOfUserVM(long)";
- removed the unused method
  "com.cloud.vm.UserVmService.createVirtualMachine(DeployVMCmd)";

Changes at the class "com.cloud.vm.UserVmManagerImpl.VmAndCountDetails":
- removed unused method
  "com.cloud.vm.UserVmManagerImpl.VmAndCountDetails.setRetrievalCount(int)";
- removed unused method
  "com.cloud.vm.UserVmManagerImpl.VmAndCountDetails.setVmId(long)";

### CODE REVIEW

**Comment by rhtyd** [comment]
@GabrielBrascher can you fix the conflicts, thanks

**Comment by rhtyd** [comment]
@GabrielBrascher can you rebase against latest master

**Comment by GabrielBrascher** [comment]
Thanks for reminding @rhtyd! I will do it.

**Comment by GabrielBrascher** [comment]
@rhtyd rebased against latest master.

**Comment by rhtyd** [comment]
@blueorangutan package

**Pull request closed without merging**
