### PR TITLE
[4.10/master] Smoketest Health

### PR DESCRIPTION
**Pull request by rhtyd**
@blueorangutan package

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
/cc @karuturi  -- I'm running health check for latest master/4.10 RC1 cut from current HEAD
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@karuturi based on the latest Trillian tests on current master, I see a regression in vmware env for:

======================================================================
FAIL: @Desc: Test that Volume snapshot for root volume is not allowed
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/marvin/tests/smoke/test_vm_snapshots.py", line 408, in test_01_test_vm_volume_snapshot
    volume_id=volume.id)
AssertionError: Exception not raised
-------------------- >> begin captured stdout << ---------------------
=== TestName: test_01_test_vm_volume_snapshot | Status : FAILED ===

Otherwise, LGTM.

**Comment by serg38** [comment]
@rhtyd @karuturi This is a new  improvement introduced in PR1941 that allows volume and VM snapshots to coexist. Now, test test_01_test_vm_volume_snapshot in test_vm_snapshots.py needs to be reversed

 @Desc: Test that Volume snapshot for root volume is not allowed
        when VM snapshot is present for the VM
        @Steps:
        1: Deploy a VM and create a VM snapshot for VM
        2: Try to create snapshot for the root volume of the VM,
        It should expect Exception
        """

**Comment by karuturi** [comment]
@rhtyd Thanks for running the tests and the report. I might request you again once the blockers are fixed :)
@serg38 Thanks for finding the PR. I will try and request the PR author to fix this. But, if there is no response, not sure what can be done.

**Comment by rhtyd** [comment]
Thanks @serg38 
@karuturi sure :)

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix
/cc @karuturi running another round of testing 4.10/master after fixing the master build/packaging regression

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
/cc @karuturi running some tests given several failures in recent/last set of tests
@blueorangutan test matrix

**Comment by serg38** [comment]
@rhtyd @karuturi @nathanejohnson test_deploy_virtio_scsi_vm fails because template is no longer available at URL hardcoded in the test
http://dl.openvm.eu/cloudstack/ubuntu/vanilla/16.04/x86_64/ubuntu-16.04-server-cloudimg-amd64-disk1-kvm.qcow2.bz2

**Comment by nathanejohnson** [comment]
@serg @karuturi @rhtyd 

Can someone suggest an more appropriate url?  I need a modern template to run parts of the test, something new enough to have support out of the box for virtio scsi.

**Comment by borisstoyanov** [comment]
@blueorangutan test centos6 mgmt + xs65sp1

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
(tests did not run :( )
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
Will create  a new PR, this has too many comments now.

**Comment by rhtyd** [comment]
New: https://github.com/apache/cloudstack/pull/2114

**Pull request closed without merging**
