### PR TITLE
Fix and enable tests for storage plugins

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR fixes and disables skipTests for storage plugins

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan test

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Review by shwstppr — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@shwstppr can you please add the reason of your approval? (just review or test etc)

**Comment by shwstppr** [comment]
> @shwstppr can you please add the reason of your approval? (just review or test etc)

My reasons:
- Only a cleanup PR
- Build passes with unit test changes
- Smoke test passes, https://github.com/apache/cloudstack/pull/7657#issuecomment-1602246658
- I like the fact that tests are not skipped

**Pull request merged**
