### PR TITLE
[CLOUDSTACK-10314] Add Text-Field to each ACL Rule

### PR DESCRIPTION
**Pull request by rafaelweingartner**
It is interesting to have a text field (e.g. CHAR-256) added to each ACL rule, which allows to enter a "reason" for each FW Rule created. This is valuable for customer documentation, as well as best practice for an evidence towards auditing the system.

Attached are some pictures showing how the UI looks like with this new field.
tablewithrasonfield

editaclwithreasonfield

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@rafaelweingartner did you have a look at the annotations feature for adding comments? These allow for audit trails as well.

**Comment by rafaelweingartner** [comment]
@DaanHoogland yes I did, but I did not quite understand their purpose. I was not sure if the goal was to be used as the tag system we have in ACS for host and storage. Also, they are quite limited in the UI if you need to write something more than a few words.

**Comment by rafaelweingartner** [comment]
So, that option has nothing to do with ACS tagging system?

**Comment by rafaelweingartner** [comment]
I was checking that tag thing there, and it is a bit too generic in my opinion. I could change the UI to use those fields (I would also need to increase the size of those fields), but I do prefer a not so generic solution as this one, where the description/history field becomes part of the ACL rule API.

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by rafaelweingartner** [comment]
@khos2ow and @marcaurele  can you guys give your opinions here?

**Comment by rafaelweingartner** [comment]
That is an interesting suggestion. I have not thought about "description" to name that field.

**Comment by marcaurele** [comment]
It would be helpful for SG rules too for example, for IP aliases, snapshots...

**Comment by marcaurele** [comment]
Yeah, it wasn't aimed to this PR, more as a general idea.

I'm ok with this change. If you think `description` is better than `reason` and you're willing to modify your PR, let us know otherwise we'll merge it.

**Comment by rafaelweingartner** [comment]
I am still thinking about the change you mentioned. As soon as I have some feedback I tell you guys.

**Comment by rafaelweingartner** [comment]
I am going to leave it as is. If we change the "reason" field name, I would need to change all references (JS, CSS, and labels) to make a more concise change. Maybe, if we feel that description is better, I can change that in the near future with another PR.

**Pull request merged**
