### PR TITLE
VR: add rules for traffic between static nat and private gateway static routes

### LINKED ISSUE #6144: Static nat hampers prive gateway access
Having two VPCs connected through their respective private gateways should allow instances from the one to connect to the other (given the proper firewall rules). When a static nat is assigned an instance in one of the VPC will stop that instance from being able to reach the other VPC.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
networking
~~~

##### CLOUDSTACK VERSION

~~~
4.15.2
~~~

##### CONFIGURATION

VPC A:
    10.10.10.0/24
        PG-IP: 10.10.30.1
        PG-GW: 10.10.30.2
            tier 1: 10.10.10.0/25
                instance 1.a: 10.10.10.11

VPC B:
    10.10.20.0/24
        PG-IP: 10.10.30.2
        PG-GW: 10.10.30.1
            tier 1: 10.10.20.0/25
                instance 1.b: 10.10.20.22

##### STEPS TO REPRODUCE

~~~
create two VPCs
create a tier in each of them
deploy an instance in each of the tiers
create a private gateway in each of the VPCs with the same vlan and each others adresses as gateway
assign static routes for the other VPC in each of the PGs
ping the one instance fro the other (should work)
assign a static IP address (StaticNat) to the instance from which you ping 
restart the ping
~~~

##### EXPECTED RESULTS

~~~
ping works
~~~

##### ACTUAL RESULTS

~~~
ping go through
~~~

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #6144 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
thanks @weizhouapache , looks good. hope that's all there is to it.

**Comment by DaanHoogland** [comment]
@weizhouapache I think this applies to 4.15 and up, can you rebase on an older branch?

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
> @weizhouapache I think this applies to 4.15 and up, can you rebase on an older branch?

@DaanHoogland 
according to https://cwiki.apache.org/confluence/display/CLOUDSTACK/LTS, 4.15.x will be EOL on 1 July 2022
I will change target to 4.16.

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Review by nvazquez — APPROVED** [review]

**Comment by nvazquez** [comment]
Ping for review @rohityadavcloud @DaanHoogland @Pearl1594

**Review by DaanHoogland — APPROVED** [review]

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Review by NuxRo — APPROVED** [review]
Works for me

**Pull request merged**
