### PR TITLE
CLOUDSTACK-9365 : updateVirtualMachine with userdata should not error…

### PR DESCRIPTION
**Pull request by nlivens**
… when a VM is attached to multiple networks from which one or more doesn't support userdata

### CODE REVIEW

**Comment by nlivens** [comment]
@DaanHoogland, @remibergsma, @swill, @jburwell, these are rather small changes, if any of you could review, that would be great!

**Comment by DaanHoogland** [comment]
thought the code looks sane, could you be bothered to show the error in a marvin test, Nick. It seems a good candidate to enter the regression suite.

**Comment by nlivens** [comment]
@DaanHoogland, you already have a UserData test script, do you want us to add this test to the same script, or create a new one for it?

**Comment by DaanHoogland** [comment]
@nlivens I don't care for more scripts, just for a test showing the problem so we no it doesn't regress. Whatever meets the goal easiest.

**Comment by cristofolini** [comment]
@nlivens May I suggest extracting lines 2501-2514 to their own separate method? That would also allow you to create separate test cases for each possibility in that if statement.

**Comment by alexandrelimassantana** [comment]
@cristofolini that would not be that simple, there is userDataApplied variable which is extern to the loop. It would be better to turn lines 2496-2515 intto a Nic's class method which returns a boolean in this case. @nilves you should do a simple testcase to this problem, that would minimize the ammount of scripts needed to test such features.

**Comment by nlivens** [comment]
@cristofolini, @alexandrelimassantana, I've extracted the internal loop logic to a separate method and I've added a unit test for this behavior. This logic couldn't be implemented in the Nic class itself since this just a model class and shouldn't contain any logic :)

**Comment by alexandrelimassantana** [comment]
That seems fair... But I think you could make 3 unit tests instead of 1 so each one would have only 1 assert and only one behavior each. Other than that it all looks fine. As Daan said, the code seems sane and the tests prove it's functionality.

**Comment by nlivens** [comment]
@alexandrelimassantana, you're right, I've splitted up the 3 different test cases.

**Comment by singalrahul** [comment]
test_deploy_vm_userdata_MultiNic.py script is added for the verification of this Bug. It will verify that a user can deploy MultiNic VM when non-default nic does not have userdata service and can also update vm userdata.

Before Fix, below was the result:-

Test userdata update when non default nic is without userdata ... === TestName: test_deployvm_multiNic | Status : FAILED ===
FAIL

======================================================================
FAIL: Test userdata update when non default nic is without userdata
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pmanthen/test_deploy_vm_userdata_MultiNic.py", line 183, in test_deployvm_multiNic
    self.fail("Failed to update userdata: %s" % e)
AssertionError: Failed to update userdata: Execute cmd: updatevirtualmachine failed, due to: errorCode: 530, errorText:Service UserData is not supported in the network id=237
-------------------- >> begin captured stdout << ---------------------
=== TestName: test_deployvm_multiNic | Status : FAILED ===

[failed_plus_exceptions.txt](https://github.com/apache/cloudstack/files/245103/failed_plus_exceptions.txt)
[results.txt](https://github.com/apache/cloudstack/files/245104/results.txt)
[runinfo.txt](https://github.com/apache/cloudstack/files/245105/runinfo.txt)


After the Fix:-

Test userdata update when non default nic is without userdata for deploy and update ... === TestName: test_deployvm_multinic | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 1 test in 40.583s

OK


[results.txt](https://github.com/apache/cloudstack/files/245106/results.txt)
[runinfo.txt](https://github.com/apache/cloudstack/files/245107/runinfo.txt)

**Comment by koushik-das** [comment]
LGTM. Verified before and after fix and things are working as expected. The integration test works fine and properly cleans up stuff on completion.

**Comment by nlivens** [comment]
@DaanHoogland, @alexandrelimassantana, could you review the PR once again please?

**Comment by DaanHoogland** [comment]
@nlivens thanks for the extra test effort you put into this. Can you rename the marvin test to adhere to python naming standards (i.e. no camal case underscores mix) For marvin in this case test_deploy_vm_userdata_multinic.py or test_deploy_vm_userdata_multi_nic.py would both be fine I guess. otherwise LGTM
@swill, can you schedule this one?

**Comment by nlivens** [comment]
@DaanHoogland, the file has been renamed to make use of the python naming standards

**Comment by swill** [comment]
I will get this one into my CI queue.  Thx...

**Comment by swill** [comment]
### CI RESULTS

```
Tests Run: 86
  Skipped: 0
   Failed: 0
   Errors: 1
 Duration: 10h 57m 48s
```

**Summary of the problem(s):**
```
ERROR: Test to verify access to loadbalancer haproxy admin stats page
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/git/cs1/cloudstack/test/integration/smoke/test_internal_lb.py", line 854, in tearDown
    raise Exception("Cleanup failed with %s" % e)
Exception: Cleanup failed with Job failed: {jobprocstatus : 0, created : u'2016-05-17T05:54:41+0200', jobresult : {errorcode : 530, errortext : u'Failed to delete network'}, cmd : u'org.apache.cloudstack.api.command.user.network.DeleteNetworkCmd', userid : u'fc7333fa-1bb3-11e6-926a-5254001daa61', jobstatus : 2, jobid : u'10bceca3-1855-4f65-a3d6-7142c17e38d7', jobresultcode : 530, jobresulttype : u'object', jobinstancetype : u'Network', accountid : u'fc731e29-1bb3-11e6-926a-5254001daa61'}
----------------------------------------------------------------------
Additional details in: /tmp/MarvinLogs/test_network_A1IVQ2/results.txt
```



**Associated Uploads**

**`/tmp/MarvinLogs/DeployDataCenter__May_17_2016_00_20_22_76X5IB:`**
* [dc_entries.obj](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1523/tmp/MarvinLogs/DeployDataCenter__May_17_2016_00_20_22_76X5IB/dc_entries.obj)
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1523/tmp/MarvinLogs/DeployDataCenter__May_17_2016_00_20_22_76X5IB/failed_plus_exceptions.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1523/tmp/MarvinLogs/DeployDataCenter__May_17_2016_00_20_22_76X5IB/runinfo.txt)

**`/tmp/MarvinLogs/test_deploy_vm_userdata_multi_nic_Z4EAPH:`**
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1523/tmp/MarvinLogs/test_deploy_vm_userdata_multi_nic_Z4EAPH/failed_plus_exceptions.txt)
* [results.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1523/tmp/MarvinLogs/test_deploy_vm_userdata_multi_nic_Z4EAPH/results.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1523/tmp/MarvinLogs/test_deploy_vm_userdata_multi_nic_Z4EAPH/runinfo.txt)

**`/tmp/MarvinLogs/test_network_A1IVQ2:`**
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1523/tmp/MarvinLogs/test_network_A1IVQ2/failed_plus_exceptions.txt)
* [results.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1523/tmp/MarvinLogs/test_network_A1IVQ2/results.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1523/tmp/MarvinLogs/test_network_A1IVQ2/runinfo.txt)


Uploads will be available until `2016-07-17 02:00:00 +0200 CEST`

*Comment created by [`upr comment`](https://github.com/cloudops/upr).*

**Comment by swill** [comment]
This one is in good order and will make it in...

**Comment by nlivens** [comment]
Great, thanks @swill!

**Pull request merged**
