### PR TITLE
ui: add tooltips for actions in tab

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Adds tooltips for buttons in tabs

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):
**Before**
Screenshot from 2021-03-19 11-44-12

**After**
Screenshot from 2021-03-19 11-44-16

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by rhtyd** [comment]
@shwstppr is this ready for review/testing?

**Comment by shwstppr** [comment]
@rhtyd yes
> @shwstppr is this ready for review/testing?

**Review by utchoang — APPROVED** [review]
LGTM!

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
LGTM - but needs one more test/confirmation cc @davidjumani  @Pearl1594

**Review by Pearl1594 — COMMENTED** [review]
@shwstppr In the details view of a specific user, the button to copy api / secret keys to clipboard is no longer visible i.e.,
On the QA server without this PR:
image

With the fix:
image

**Comment by shwstppr** [comment]
@Pearl1594 fixed

@blueorangutan ui

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by Pearl1594** [comment]
@blueorangutan ui

**Comment by Pearl1594** [comment]
@shwstppr Rest looks good, found a couple of issues

1. In the LoadBalancing view, the action buttons seem to be missing:

QA server without PR fix:
image


With changes:
image

2. In the Project -> Accounts Tab, accounts added with a Regular user role have the option to promote as well as demote them to and from project admin role respectively - due to a missing check for the role type

Without Changes:
image

With Changes:
image


3. Project -> Project Roles Tab: Remove Project role button icon seems to be incorrect

Without Changes:
image


With Changes:
image

**Comment by shwstppr** [comment]
@Pearl1594 thanks a lot for testing

@blueorangutan ui

**Review by Pearl1594 — APPROVED** [review]
Tested. LGTM

**Pull request merged**
