### PR TITLE
packaging: use modern systemctl enable/disable

### PR DESCRIPTION
**Pull request by rohityadavcloud**
This fixes spec files to use systemctl enable|disable instead of on|off.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Review by sureshanaparti — APPROVED** [review]
code LGTM

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Pull request merged**
