### PR TITLE
Fix the name of the column used to hold IPv4 range in 'vlan' table.

### PR DESCRIPTION
**Pull request by rafaelweingartner**
The title says everything...

### CODE REVIEW

**Comment by rhtyd** [comment]
Can you check the build  failures @rafaelweingartner?

**Comment by rafaelweingartner** [comment]
The problems are due to that issue with the agent-lb component. As soon as we merge that, we fix all of these issues.

**Comment by DaanHoogland** [comment]
@rafaelweingartner package

**Comment by DaanHoogland** [comment]
@rafaelweingartner you are free to help if you wish but
@blueorangutan package

**Comment by rafaelweingartner** [comment]
Sorry, I did not understand. 
Do you need help for something?

**Comment by DaanHoogland** [comment]
i commented @rafaelweingartner package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by nitin-maharana** [comment]
Thanks for the fix. Code LGTM.

**Comment by rafaelweingartner** [comment]
@nitin-maharana can you use the Github review/approval method? It facilitate for us when checking if a BR is ready to be managed.

Thanks for the reviews.

**Comment by DaanHoogland** [comment]
@nitin-maharana it's fine for now but @rafaelweingartner is right that it is easier to see if a PR is ready for merge if you use the review button.... reviewing the failed tests to see if these are structural.

**Comment by DaanHoogland** [comment]
all failures seem unrelated to this code, rerunning to get another hint
@blueorangutan test

**Comment by rafaelweingartner** [comment]
Yes I have. Why do you think it can be problematic? 
The problem is not with this PR per se, but the same old discussion, the way we are using to manage data model scrips.

The upgrade path from 4.11 to 4.12 was created before the 4.11 to 4.11.1. This will create for sure a problem, which I am not sure how to handle yet.

**Comment by rhtyd** [comment]
@rafaelweingartner it will depend on which version gets out of the door first. Usually, you would do something like: 4.11.0.0-> 4.11.1.0 -> 4.12.0.0 assuming 4.11.1.0 gets out of the door before 4.12.0.0, in which case the 4.11.0.0->4.12.0.0 file names could be renamed to reflect `4.11.1.0`->`4.12.0.0`. There are no changes required from your end wrt this PR.

**Comment by rafaelweingartner** [comment]
I agree with @rhtyd.
@borisstoyanov are those errors intermittent ones? I think I have seen similar ones in other PRs.

**Comment by borisstoyanov** [comment]
yes @rafaelweingartner we've seen them before.

**Comment by rafaelweingartner** [comment]
Can I consider then that everything is ok, and merge this PR?

**Comment by rhtyd** [comment]
I see some new failures, let me re-kick tests one more time.
@blueorangutan test centos7 vmware-65

**Comment by rafaelweingartner** [comment]
errors changes again... I believe this is a good sign somehow...

**Comment by rafaelweingartner** [comment]
@borisstoyanov are these errors intermittent ones?

**Comment by borisstoyanov** [comment]
These errors aren't reported frequently.. but I don't think they're related... don't see any reason to..

**Comment by rafaelweingartner** [comment]
I have seen this `test_04_rvpc_network_garbage_collector_nics` test failing in other PRs as well. @borisstoyanov would you like to run some more tests, or you are ok with the results so far?

**Pull request merged**
