### PR TITLE
CLOUDSTACK-9765: centos: packaging: fix missing path in spec file

### PR DESCRIPTION
**Pull request by resmo**
Related to 6051fa503a2da7b96256f21e6b7c42aa1f3cb01e

/cc @rhtyd (shapeblue)

### CODE REVIEW

**Comment by rhtyd** [comment]
Thanks @resmo can you re-target this PR for 4.9 branch? Let's get this in both 4.9 and master.

**Comment by resmo** [comment]
@rhtyd done. changed base to 4.9 ;)

**Comment by borisstoyanov** [comment]
@blueoranguten package

**Comment by resmo** [comment]
@borisstoyanov is there a way to get the packages build by @blueorangutan?

**Comment by borisstoyanov** [comment]
Unfortunately no at this stage, but we can talk about this with @rhtyd

**Comment by rhtyd** [comment]
LGTM. @karuturi not a blocker, but then we'll need to document the workaround (manual fix) in the release notes. If RC1 has any blockers, let's include this in RC2.

**Comment by Slair1** [comment]
This LGTM too, we hit this issue during our upgrade

**Pull request merged**
