### PR TITLE
UI: fix security group lists in project view

### LINKED ISSUE #7135: Advanced Zone with SG: Security Groups not shown in Create Instance UI (Project View)
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.17.2
~~~

##### CONFIGURATION

Cloudstack 4.17.2 environment Advanced Zone with Security Groups. Default View and Projects are used in this setup.

##### OS / ENVIRONMENT

RHEL 8 is used for cloudstack management servers and hosts.

##### SUMMARY

When creating an instance in the Default View, users can see their Security Groups from which they can choose when initially creating a VM. In The Projects View, the list of Security Groups are not shown in the Create Instance UI.

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #7135 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### Screenshots (if appropriate):

old
image

new
image

### CODE REVIEW

**Review by rohityadavcloud — APPROVED** [review]

**Review by DaanHoogland — APPROVED** [review]
code looks good

**Comment by vladimirpetrov** [comment]
@blueorangutan package

**Review by stephankruggg — APPROVED** [review]
CLGTM, did not manually test it

**Comment by DaanHoogland** [comment]
@blueorangutan ui

**Comment by DaanHoogland** [comment]
didn´t investigate (yet), but in qa i get; 
image

**Comment by vladimirpetrov** [comment]
I'm able to login normally on my test env, @DaanHoogland .

**Review by vladimirpetrov — APPROVED** [review]
LGTM based on manual testing.

**Pull request merged**
