### PR TITLE
Fix docker image build for cloudstack-management

### PR DESCRIPTION
**Pull request by pdion891**
CLOUDSTACK-9651

Fix Docker images build for 4.10.0.0:
- simulator
- marvin
- management_centos6

Squashed version of #1435.

### CODE REVIEW

**Comment by rhtyd** [comment]
@pdion891 thanks, how may I test this?

**Comment by rhtyd** [comment]
@pdion891 @resmo @swill @sebgoa can you help review, test this? thanks.

**Comment by sebgoa** [comment]
LGTM

but really the database should be outside the mgt server container and we should not be using supervisord.

**Comment by pdion891** [comment]
@sebgoa , I agree with you, it's just the easiest way to have a cloudstack with simulator preconfigured ready to work. We should not use package for the image management also.

I've made basic tests while doing the PR has I got images that were working. But I haven't test using the management server managing real hypervisors.

**Comment by resmo** [comment]
IMHO this is not meant for production, but quick fire up a docker having the current state of development. The image will be huge but for non-devs (like me) a easy way to get a running devel cloudstack in minutes.

**Comment by rhtyd** [comment]
Thanks, @pdion891 are you satisfied with the changes or you want to improve them. I'm LGTM on this, can merge on your conclusion. Thanks.

**Comment by pdion891** [comment]
Thanks @rhtyd, let merge it so we have the simulator back online on docker hub and let's improve our Docker images...

@jburwell, @rhtyd , do I merge it or you do it? I'm just wondering since we are close from a release. 

Thanks

**Comment by rhtyd** [comment]
I've not verified this but I'll proceed with merging this based on review/test/feedback from @pdion891 @resmo and @sebgoa .

**Comment by pdion891** [comment]
Thanks @rhtyd !

**Pull request merged**
