### PR TITLE
remove stale project cloud-systemvm

### PR DESCRIPTION
**Pull request by DaanHoogland**

### CODE REVIEW

**Comment by bhaisaab** [comment]
@DaanHoogland just want to confirm if we are in anyway using those files in systemvm.iso generation or other places?

**Comment by bhaisaab** [comment]
Since this removes cloud-systemvm project completely, I'll wait for at least one more person to confirm/review before we can merge this into master.

**Comment by DaanHoogland** [comment]
good point, will have to check that, thanks

On Tue, Mar 24, 2015 at 12:22 PM, Rohit Yadav <notifications@github.com>
wrote:

> @DaanHoogland <https://github.com/DaanHoogland> just want to confirm if
> we are in anyway using those files in systemvm.iso generation or other
> places?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/cloudstack/pull/126#issuecomment-85455210>.
>



-- 
Daan

**Comment by DaanHoogland** [comment]
closing this one, it was overzealous. some of the contents needs to be deleted but some brainwork needs to go into that.

**Pull request closed without merging**
