### PR TITLE
Squashing two commits in to single commit

### PR DESCRIPTION
**Pull request by pritisarap12**
CLOUDSTACK-8717: Failed to start instance after restoring the running instance
	-Modified code to add tag to aonly one cluster wide SP
	-Added validateList function
	-Added code to clear tags in tearDown class

### CODE REVIEW

**Comment by remibergsma** [comment]
Thanks! LGTM, based on #667.

I'd suggest though to make the commit message and PR title more descriptive.

**Comment by DaanHoogland** [comment]
@sanjeevneelarapu If you LGTM this there are 2 LGTM here so please go ahead and merge.

**Comment by runseb** [comment]
@DaanHoogland @sanjeevneelarapu you guys are writing the code so I have nothing to say...but @remibergsma asked for updating the PR message and nothing was done. Now we have a commit in our history with the message "squashing two commits" , I would be a BD I would revert this.

**Comment by DaanHoogland** [comment]
@runseb very sorry but I saw @remibergsma LGTM above here in this PR. please revert. I have not looked into this PR.

**Comment by sanju1010** [comment]
I have reverted this  merge commit 
commit d159af93b4e6485b30424026e1a84ce85a3c7abf
Author: sanjeev <sanjeev@apache.org>
Date:   Wed Feb 17 11:53:07 2016 +0530

    Revert "Merge pull request #1411 from pritisarap12/CLOUDSTACK-8717-Failed-to-start-instance-after-restoring-the-running-instance"

    This reverts commit 13f4e5a253c6fac8ff38ffc0a43d237be290d084, reversing
    changes made to 7332e88ec935f7bdcec4e0659dfac88d537d898a.

**Pull request merged**
