### PR TITLE
Ovmsupport 3.2.1/3.3.x rebased and condensed in one single commit.

### PR DESCRIPTION
**Pull request by snuf**
@bhaisaab

Rebasing the other stuff was a pain (4400 commits behind is no pleasure). Decided to do a "re-implement" against master after two rebase attempts, and this is the result.

This replaces https://github.com/apache/cloudstack/pull/99

Cheers,

Funs

### CODE REVIEW

**Comment by bhaisaab** [comment]
Hey @snuf thanks for that! It makes it easier to everyone to review and merge your stuff. First thing tomorrow morning!

**Comment by bhaisaab** [comment]
@snuf after a quick look at the diff I feel so emotional with the code I'm seeing, neat stuff :) :astonished:

**Comment by snuf** [comment]
@bhaisaab thanks man!, it's bound to have some bugs and nasty bits here and there. Already have NSX/NVP integration on the map for the next iteration though :)
I'll update the wiki tomorrow with the correct information and how the hypervisor is supposed to be configured.

**Comment by runseb** [comment]
That's ok @bhaisaab you will be fine, @snuf is the huggy type you two can get emotional about that code at the next cloudstack day.

**Comment by bhaisaab** [comment]
@runseb true that :)

@snuf we're good as long as the bugs are in the plugin itself and don't affect the core. Looking at the code, does not look like the several core changes at all.

Built with noredist, able to deploy a KVM zone without any issues (just to check any side effects). Merging now.

**Comment by likitha** [comment]
Seems to have caused the RAT check to fail. I do see the license headers in the new files, so I guess the format is not an exact match? (https://builds.apache.org/job/cloudstack-rat-master/6275/artifact/target/rat.txt)

**Comment by snuf** [comment]
@likitha Hmm the format is indeed different, though the content is the same, mine is the one that comes with eclipse and has a full line of * at the top and bottom and is missing some spaces. Should I change it or should RAT accept it as it is a valid license ?

**Comment by bhaisaab** [comment]
@snuf @likitha yeah, RAT expects a certain format. Just fixed.

**Comment by snuf** [comment]
@bhaisaab @likitha cool thanks!

**Pull request closed without merging**
