### PR TITLE
simulator: fix travis failure after merging volume destroy/recover 

### PR DESCRIPTION
**Pull request by ustcweizhou**
## Description

Do not merge

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by rhtyd** [comment]
Thanks @weizhouapache some tests against Travis/simulator are still failing, I've kicked those again.

@blueorangutan package

**Comment by rhtyd** [comment]
Travis failures still seen can you check @weizhouapache?

**Comment by weizhouapache** [comment]
> Travis failures still seen can you check @weizhouapache?

sure

**Comment by weizhouapache** [comment]
in simulator
```
2020-02-12 10:16:35,140 DEBUG [c.c.a.t.Request] (qtp897714044-33:ctx-b7704e56 ctx-760496a3 ctx-34ed6aad) (logid:42762538) Seq 4-4696691461394006046: Executing:  { Cmd , MgmtId: 7491597374312, via: 4(SimulatedAgent.751f5311-866b-44e3-a7e7-a7f3b3471232), Ver: v1, Flags: 100011, [{"org.apache.cloudstack.storage.command.DeleteCommand":{"data":{"org.apache.cloudstack.storage.to.VolumeObjectTO":{"uuid":"e82e04ff-2289-48e8-9955-93b3f032109f","volumeType":"DATADISK","dataStore":{"org.apache.cloudstack.storage.to.PrimaryDataStoreTO":{"uuid":"0bbd54fe-b348-3e3d-9b91-b453a21bc43a","id":3,"poolType":"NetworkFilesystem","host":"10.147.28.6","path":"/export/home/sandbox/primary2","port":2049,"url":"NetworkFilesystem://10.147.28.6/export/home/sandbox/primary2/?ROLE=Primary&STOREUUID=0bbd54fe-b348-3e3d-9b91-b453a21bc43a","isManaged":false}},"name":"Test Volume-W7S6ZJ","size":1073741824,"path":"Test Volume-W7S6ZJ","volumeId":6,"accountId":4,"provisioningType":"THIN","id":6,"hypervisorType":"Simulator"}},"wait":0}}] }
2020-02-12 10:16:35,140 DEBUG [c.c.a.m.DirectAgentAttache] (DirectAgent-28:ctx-696c4aab) (logid:fb85385f) Seq 4-4696691461394006046: Executing request
2020-02-12 10:16:35,140 DEBUG [c.c.a.m.SimulatorManagerImpl] (DirectAgent-28:ctx-696c4aab) (logid:42762538) Simulate command org.apache.cloudstack.storage.command.DeleteCommand
2020-02-12 10:16:35,145 DEBUG [c.c.u.d.T.Transaction] (DirectAgent-28:ctx-696c4aab) (logid:42762538) Rolling back the transaction: Time = 3 Name =  -SimulatorManagerImpl.simulate:215-AgentRoutingResource.executeRequestInContext:98-AgentResourceBase$1.runInContext:254-ManagedContextRunnable$1.run:49-DefaultManagedContext$1.call:56-DefaultManagedContext.callWithContext:103-DefaultManagedContext.runWithContext:53-ManagedContextRunnable.run:46-AgentResourceBase.executeRequest:256-DirectAgentAttache$Task.runInContext:315-ManagedContextRunnable$1.run:49-DefaultManagedContext$1.call:56; called by -TransactionLegacy.rollback:890-TransactionLegacy.removeUpTo:833-TransactionLegacy.close:657-MockStorageManagerImpl.Delete:839-SimulatorManagerImpl.simulate:381-AgentRoutingResource.executeRequestInContext:98-AgentResourceBase$1.runInContext:254-ManagedContextRunnable$1.run:49-DefaultManagedContext$1.call:56-DefaultManagedContext.callWithContext:103-DefaultManagedContext.runWithContext:53-ManagedContextRunnable.run:46





2020-02-12 10:16:35,146 DEBUG [c.c.a.t.Request] (DirectAgent-28:ctx-696c4aab) (logid:42762538) Seq 4-4696691461394006046: Processing:  { Ans: , MgmtId: 7491597374312, via: 4(SimulatedAgent.751f5311-866b-44e3-a7e7-a7f3b3471232), Ver: v1, Flags: 10, [{"com.cloud.agent.api.Answer":{"result":false,"details":"can't find object to delete:Test Volume-W7S6ZJ","wait":0}}] }
2020-02-12 10:16:35,147 DEBUG [c.c.a.t.Request] (qtp897714044-33:ctx-b7704e56 ctx-760496a3 ctx-34ed6aad) (logid:42762538) Seq 4-4696691461394006046: Received:  { Ans: , MgmtId: 7491597374312, via: 4(SimulatedAgent.751f5311-866b-44e3-a7e7-a7f3b3471232), Ver: v1, Flags: 10, { Answer } }
2020-02-12 10:16:35,175 WARN  [o.a.c.s.d.ObjectInDataStoreManagerImpl] (qtp897714044-33:ctx-b7704e56 ctx-760496a3 ctx-34ed6aad) (logid:42762538) Unsupported data object (VOLUME, org.apache.cloudstack.storage.datastore.PrimaryDataStoreImpl@4b59bca1), no need to delete from object in store ref table
2020-02-12 10:16:35,205 DEBUG [c.c.a.ApiServlet] (qtp897714044-33:ctx-b7704e56 ctx-760496a3 ctx-34ed6aad) (logid:42762538) ===END===  0:0:0:0:0:0:0:1 -- GET  signature=yFw611wFZVaBuSGO9QVOBmKDCc8%3D&apiKey=D8lqWaEcvYVyF28m55O6s4vjL79lcUguRv4uZl4NfW-5yN1wHY4m2zwGZn3Z6g6dQrrjZHuVFIYVIzxpcQr6UA&command=deleteVolume&id=e82e04ff-2289-48e8-9955-93b3f032109f&response=json
```

**Comment by rhtyd** [comment]
Okay was that some exception/error causing this, are you able to fix this @weizhouapache ?

**Comment by weizhouapache** [comment]
> Okay was that some exception/error causing this, are you able to fix this @weizhouapache ?

@rhtyd checking
it seems to be something wrong in plugins/hypervisor/simulator

**Comment by weizhouapache** [comment]
@rhtyd travis should be good with this pr.

**Pull request merged**
