### PR TITLE
Improve log when live patching fails

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

This PR improves error log message when scp fails during system VM live patching

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?
Before Fix:
```
2022-04-27 12:02:22,647 ERROR [c.c.s.ManagementServerImpl] (API-Job-Executor-1:ctx-f000200b job-40 ctx-161ff677) (logid:52d49a16) Failed to patch systemVM v-1-VM due to Failed to scp files to system VM, retrying, retrying, retrying
```

After Fix:
```
2022-04-27 13:15:16,189 ERROR [c.c.s.ManagementServerImpl] (API-Job-Executor-1:ctx-4cfd7ab1 job-62 ctx-23bea220) (logid:dffe10d7) Failed to patch systemVM s-2-VM due to Failed to scp files to system VM due to, Remote scp terminated with error (scp: /tmp//agent.zip: No space left on device).
```
image

### CODE REVIEW

**Review by nvazquez — APPROVED** [review]

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan test

**Comment by Pearl1594** [comment]
^ test failed due to dns issue in the lab

**Comment by Pearl1594** [comment]
@blueorangutan test

**Pull request merged**
