### PR TITLE
ui: Show vm name in info card in deployvm

### PR DESCRIPTION
**Pull request by davidjumani**
### Description

This PR shows the name of the VM in the info card next to the avatar rather than in the title

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Before :
Screenshot from 2021-03-10 14-54-11

#### After :
Screenshot from 2021-03-10 14-50-43

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan ui

**Comment by utchoang** [comment]
@davidjumani can you change the base branch of the PR and rebase your PR branch to 4.15?

**Comment by utchoang** [comment]
@davidjumani can you change the base branch of the PR and rebase your PR branch to 4.15?

**Comment by davidjumani** [comment]
@utchoang Done!

**Comment by rhtyd** [comment]
LGTM

**Pull request merged**
