### PR TITLE
ui: fix select networks for template nic

### LINKED ISSUE #5927: [UI][VMware][Deploy-as-is] - Drop down does not show all networks
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI - Deploy VM
~~~

##### CLOUDSTACK VERSION

~~~
4.15.x
~~~

##### CONFIGURATION

~~~
Advanced Networking
~~~

##### OS / ENVIRONMENT

~~~
VMWare
~~~

##### SUMMARY

In an environment having more than 10 networks, deploying a VM using a template registered with 'Read VM settings from OVA' in VMware set to true, doesn't list all the networks in the drop-down menu, but rather lists the last 10.

##### EXPECTED RESULTS

~~~
Drop down menu should list all the available networks
~~~

##### ACTUAL RESULTS

~~~
Drop-down menu lists only 10
~~~

List of the networks displayed in the drop-down menu:
drop-down-1
drop-down-2

Total networks available:
total_network

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #5927

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):
Screenshot from 2022-02-04 14-40-04

Screenshot from 2022-02-04 14-40-26

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by DaanHoogland** [comment]
testing this will require a real vmware host, so
@blueorangutan package

**Comment by DaanHoogland** [comment]
> testing this will require a real vmware host, so @blueorangutan package

confusing @shwstppr 's PRs . this one doesn't need a real vmware host

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan ui

**Comment by sureshanaparti** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by shwstppr** [comment]
Purely UI changes so I'm not sure if smoke test results will catch any errors

**Comment by sureshanaparti** [comment]
> Purely UI changes so I'm not sure if smoke test results will catch any errors

correct, will validate the changes in the env. no need to check the smoke tests.

**Review by rohityadavcloud — APPROVED** [review]
LGTM needs manual testing

**Comment by DaanHoogland** [comment]
@sureshanaparti @rohityadavcloud this one has been confusing me, We don't need smoke tests but we do need a real vmware env to test this. A simulated environment like Qa.... won't let us do the action needed on a vmware template.

**Review by Pearl1594 — APPROVED** [review]
verified fix. LGTM.

**Review by utchoang — APPROVED** [review]
LGTM!

**Comment by sureshanaparti** [comment]
@shwstppr Networks section also shows only last 10 (in the scroll), please check.

**Comment by sureshanaparti** [comment]
> @shwstppr Networks section also shows only last 10 (in the scroll), please check. No issues in the nic drop down list.

confused due to page size, could see all networks in the subsequent pages. LGTM

**Pull request merged**
