### PR TITLE
[UI] Addressing Dynamically Scale of KVM VMs

### PR DESCRIPTION
**Pull request by BryanMLima**
### Description

This PR addresses the UI component of dynamically scale of KVM VMs partially implemented in the [PR](https://github.com/apache/cloudstack/pull/5703). The component Scale VM was showing all compute offering, which would lead the users to trial and error processes. Therefore, we changed it to display only the current compute offer for KVM VMs when the VM is running. If the VM is running and has a fixed offering, then it is displayed an error message. Furthermore, when a compute offering has a CPU Speed field, it defaults to the current speed of the VM offer, as oppose to zero, which is the current default behavior.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### Screenshots (if appropriate):
image

### How Has This Been Tested?
This was tested in a local lab with VMs using KVM.
VM1:
Fixed offering

VM2:
Custom offering

While VM1 was running, the scale displayed the error message. When it was in the stopped state, the scale showed all available compute offerings.

While VM2 was running, the scale only showed the current compute offering, and it shows the current CPU Speed. When it was in the stopped state, the scale showed all available offerings.

### CODE REVIEW

**Comment by sureshanaparti** [comment]
Hi @BryanMLima Is this PR good to go in 4.16.1? If so, please rebase with 4.16. Thanks.

**Comment by BryanMLima** [comment]
@sureshanaparti There's no need, I'm happy going to main.

**Review by utchoang — APPROVED** [review]
Code LGTM!

**Comment by utchoang** [comment]
@blueorangutan ui

**Review by GutoVeronezi — COMMENTED** [review]
CLGTM

**Review by GutoVeronezi — APPROVED** [review]

**Comment by nvazquez** [comment]
@blueorangutan ui

**Review by nvazquez — APPROVED** [review]

**Pull request merged**
