### PR TITLE
CLOUDSTACK-9377: Fix metrics pagesize issue

### PR DESCRIPTION
**Pull request by rhtyd**
Fixes listing of clusters and host to list all clusters/hosts by passing
pagesize=-1.

/cc @koushik-das @swill @DaanHoogland -- fixes the issue raised on dev@ ML by Rashmi

### CODE REVIEW

**Comment by rhtyd** [comment]
tag:easypr

**Comment by swill** [comment]
Can we get screenshots or something to verify this works?  Thanks...

**Comment by rhtyd** [comment]
@swill screenshots to prove it does not break the existing; in the screenshot we see pagesize passed as -1 (i.e lists all). The pagesize change is only in zone and cluster metrics view.

Zone metrics view:
screenshot from 2016-05-13 09-17-48

Cluster metrics view:
screenshot from 2016-05-13 09-18-00

**Comment by swill** [comment]
@rhtyd can you re push to try to get jenkins green.  I would like at least one LGTM and I will count my own.  We won't need CI as it is a UI change.

**Comment by DaanHoogland** [comment]
LGTM based on code and screenshots

**Comment by rhtyd** [comment]
@swill done, closed and reopened to kick CIs

**Comment by koushik-das** [comment]
@rhtyd While the change looks simple, what happens in case there are say > 1K hosts, > 10K VMs with this fix?

**Comment by swill** [comment]
Looks like travis is complaining.  Not sure why...

```
======================================================================
ERROR: test suite for <class 'integration.component.test_acl_listsnapshot.TestSnapshotList'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/.local/lib/python2.7/site-packages/nose/suite.py", line 228, in run
    self.tearDown()
  File "/home/travis/.local/lib/python2.7/site-packages/nose/suite.py", line 351, in tearDown
    self.teardownContext(ancestor)
  File "/home/travis/.local/lib/python2.7/site-packages/nose/suite.py", line 367, in teardownContext
    try_run(context, names)
  File "/home/travis/.local/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/home/travis/build/apache/cloudstack/test/integration/component/test_acl_listsnapshot.py", line 374, in tearDownClass
    cls.domain_2.delete(cls.apiclient,cleanup="true")
  File "/home/travis/.local/lib/python2.7/site-packages/marvin/lib/base.py", line 78, in delete
    apiclient.deleteDomain(cmd)
  File "/home/travis/.local/lib/python2.7/site-packages/marvin/cloudstackAPI/cloudstackAPIClient.py", line 703, in deleteDomain
    response = self.connection.marvinRequest(command, response_type=response, method=method)
  File "/home/travis/.local/lib/python2.7/site-packages/marvin/cloudstackConnection.py", line 379, in marvinRequest
    raise e
Exception: Job failed: {jobprocstatus : 0, created : u'2016-05-14T06:35:33+0000', cmd : u'org.apache.cloudstack.api.command.admin.domain.DeleteDomainCmd', userid : u'7ff2d4e4-199b-11e6-bc3d-42010a80001f', jobstatus : 2, jobid : u'f9286556-a479-47e2-847c-5ab9b384af6a', jobresultcode : 530, jobresulttype : u'object', jobresult : {errorcode : 530, errortext : u'Failed to clean up domain resources and sub domains, delete failed on domain D2-ZIJ741 (id: 15).'}, accountid : u'7ff2b764-199b-11e6-bc3d-42010a80001f'}
```

I don't think it is related to this since it is only a UI change, but I am not sure what to do about this...  Do I just make a judgement call and force merge some of these?

**Comment by rhtyd** [comment]
@koushik-das I'm assuming, pragmatically no one should have 1k or 10k hosts in a `single` cluster; or similarly 1k or 10k clusters in a `single` zone.

@swill I'll push -f

**Comment by GabrielBrascher** [comment]
The idea and screenshot seem nice, the code is ok. LGTM.

**Comment by swill** [comment]
Man something is up with Jenkins now days.  We have a completely different set of errors now.  There seems to be two or three different situations that different PRs seem to be hitting and I am not sure what to do about it.  :(

**Comment by rhtyd** [comment]
@swill I looked at recent Jenkins errors and they seem to be environment related:

1. Jenkins failed during initialization to checkout the git tag/sha, it fails to do a clean up. I would do a git clean -fdx && git checkout -- . && git fetch origin; before checking out target branch and applying the PR. I don't know who has access to the Jenkins job and can fix it.

2. There seem be a recurring NPE issue with corbertura maven plugin, I don't know how to fix it. We can perhaps try to update the version to latest (this probably is a Jenkins plugin, so INFRA needs to fix it).

```
Exception in thread "main" java.lang.NullPointerException
	at net.sourceforge.cobertura.coveragedata.CoverageDataFileHandler.saveCoverageData(CoverageDataFileHandler.java:138)
	at net.sourceforge.cobertura.coveragedata.CoverageDataFileHandler.saveCoverageData(CoverageDataFileHandler.java:115)
	at net.sourceforge.cobertura.instrument.Main.parseArguments(Main.java:404)
	at net.sourceforge.cobertura.instrument.Main.main(Main.java:421)
```

**Comment by rhtyd** [comment]
@swill it's all green now

**Comment by rhtyd** [comment]
@swill let's merge this? thanks

**Comment by swill** [comment]
Ya, sorry, I had a backlog of commits that were ready while I sorted out some merge conflicts doing a forward merge from 4.8 and then testing the resulting master to make sure nothing was broken.  I got a bunch of PRs merged in this morning.  Thanks for the patience.  :)

**Comment by rhtyd** [comment]
Thanks @swill

**Pull request merged**
