### PR TITLE
test: fix unknown parameter hostid in test_vm_life_cycle.py

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes the error message
```
Received unknown parameters for command listHosts. Unknown parameters : hostid
```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
:eyes:

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by weizhouapache** [comment]
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
@blueorangutan test alma9 xenserver-74

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Review by rohityadavcloud — APPROVED** [review]

**Comment by weizhouapache** [comment]
only 1 failure now

Test	Result	Time (s)	Test File
test_01_events_resource	Error	421.25	test_events_resource.py

**Pull request merged**
