### PR TITLE
ui: fix create menu item access

### LINKED ISSUE #9099: VPC link present under Create Menu when account has no permission
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.19.0.1
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

Ubuntu 22.04
Single-node Management Server
MySQL 5.7

##### SUMMARY

When setting all permissions for VPC networks to deny, the link to create a VPC is still present under create menu.   I have attached a screenshot.
image
##### STEPS TO REPRODUCE

Set all permissions on role for VPC to deny.  This was tested on both Domain Admins and User roles types.  The link to create a VPC is still present under create menu and if you click on the link it brings up a 404-error page since user has no permissions to VPC networks.  The link on the left nav does disappear as expected.

~~~
N/A
~~~

##### EXPECTED RESULTS

~~~
VPC link not be present in the create dropdown when user has no permission to do anything with VPC networks.
~~~

##### ACTUAL RESULTS

~~~
VPC link is present in the create dropdown when user has no permission to do anything with VPC networks.
~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #9099

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by weizhouapache** [comment]
@blueorangutan ui

**Comment by shwstppr** [comment]
@blueorangutan ui

**Review by DaanHoogland — APPROVED** [review]
clgtm and does what it says on the tin (in qa)
one sugestion for improvement is that if the create menu is empty the button should not be there:
image

Ad: this is an empty menu ^

**Comment by shwstppr** [comment]
@DaanHoogland I'll create a separate PR for hiding `Create` button when no menu items present. It may require some additional changes in menu structure

**Pull request merged**
