### PR TITLE
Fix issue when multiple cidrs with different sizes are assigned on a VR

### PR DESCRIPTION
**Pull request by RPDiep**
Without this patch, the VR uses the netmask of the primary network for all assigned cidrs.
This patch correctly applies the corresponding netmask.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## GitHub Issue/PRs

No issue has yet been reported. We came across this today.
## How Has This Been Tested?

I've live patched the virtual router and rebooted it. Before, `/etc/dnsmasq.d/cloud.conf` had wrong netmasks for several networks. After, the networks were set correctly.

## Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
Testing
- [ ] I have added tests to cover my changes.
- [ ] All relevant new and existing integration tests have passed.
- [ ] A full integration testsuite with all test that can run on my environment has passed.

### CODE REVIEW

**Comment by RPDiep** [comment]
Before patch:
```
root@r-29920-VM:~# grep 'eth0-[0-9],1,' /etc/dnsmasq.d/cloud.conf
dhcp-option=tag:interface-eth0-0,1,255.255.255.128
dhcp-option=tag:interface-eth0-1,1,255.255.255.128
dhcp-option=tag:interface-eth0-2,1,255.255.255.128
dhcp-option=tag:interface-eth0-3,1,255.255.255.128
dhcp-option=tag:interface-eth0-4,1,255.255.255.128
```

After patch:
```
root@r-29920-VM:~# grep 'eth0-[0-9],1,' /etc/dnsmasq.d/cloud.conf
dhcp-option=tag:interface-eth0-0,1,255.255.254.0
dhcp-option=tag:interface-eth0-1,1,255.255.255.128
dhcp-option=tag:interface-eth0-2,1,255.255.255.128
dhcp-option=tag:interface-eth0-3,1,255.255.255.0
dhcp-option=tag:interface-eth0-4,1,255.255.255.0
```

**Comment by wido** [comment]
@RPDiep Thanks! As we want this to go into 4.11, could you maybe rebase against 4.11 and change it in the PR? We'll forward merge it from the 4.11 branch into master so that it reaches 4.12 then as well.

**Comment by RPDiep** [comment]
Should be good now @wido

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Pull request merged**
