### PR TITLE
CLOUDSTACK-9876: Removed test test_01_test_vm_volume_snapshot

### PR DESCRIPTION
**Pull request by anshul1886**
As we no longer have that restriction and now after fix for CLOUDSTACK-8663 we allow VM and volume snapshots to exist together

### CODE REVIEW

**Comment by karuturi** [comment]
@rhtyd @serg38 can you review?

**Comment by serg38** [comment]
LGTM on the code change.
@borisstoyanov @rhtyd @DaanHoogland Can we re-kick vmware test for this PR?

**Comment by rhtyd** [comment]
LGTM. @anshul1886 this needs to go into 4.9 as well since the enhacement PR was for 4.9 and merged on 4.9, fwd-merged on master.

**Comment by rhtyd** [comment]
Ping @anshul1886

**Comment by anshul1886** [comment]
@rhtyd @karuturi @serg38 Changed the base to 4.9 branch.

**Comment by rhtyd** [comment]
Thanks @anshul1886 lgtm

**Pull request merged**
