### PR TITLE
Update de_DE Localization. Now Web UI 4.6 is fully translated in German

### PR DESCRIPTION
**Pull request by milamberspace**
Last update to have 100% on German in Web UI

Please 2 LGTM before the RC1!

Thanks @resmo 

cc @remibergsma @DaanHoogland @karuturi

### CODE REVIEW

**Comment by runseb** [comment]
+1 LGTM just looking at the translated strings. did not build it.

**Comment by bhaisaab** [comment]
+1 LGTM (ignore jenkins, one of the modules crashed due to jvm issue not code issues)
@remibergsma include this?

**Comment by DaanHoogland** [comment]
@bhaisaab I agree that this run on jenkins can be ignored but let's see a successful compile anyhow. I have it in my queue but I will forgive anybody that beats me to it.

**Comment by bhaisaab** [comment]
@DaanHoogland I figured Travis is green and changes were just in properties file, so looked good to me

**Comment by DaanHoogland** [comment]
ok, travis green does not mean it actually does anything, does it? In this case I think it did compile but none of the tests were run. Maybe that's enough for this one @remibergsma ?

**Comment by remibergsma** [comment]
Shouldn't we at least try a compile and see if the UI shows up?

**Comment by DaanHoogland** [comment]
Just did LGTM (logging in as a sturmbahn....)

**Comment by remibergsma** [comment]
@DaanHoogland A picture or it didn't happen! ;-)

**Comment by DaanHoogland** [comment]
untitled

**Pull request merged**
