### PR TITLE
CLOUDSTACK-8395: vmops plugin should work on both XS 6.5 and 6.2

### PR DESCRIPTION
**Pull request by bhaisaab**
This fixes the issue of Security Groups not working in case of XenServer 6.5;
- Uses nethash ipset data-structure to store CIDRs (efficient than iphash and
  avoids overflow errors in case users add /8 /4 ingress/egress cidrs)
- Support for ipset versions both on 6.2 and 6.5, both have different outputs. This
  fixes the issue of destroy_network_rules_for_vm failing
- Implements defensive filtering of list, instead of popping last item without
  checking if it's None or empty
- Greps using names that are 'quoted' to avoid bash errors
- Before setting up new network rule, tries to clean and remove old ipset entry
- Idents, whitespace and naming fixes

PS. This is my 1000th commit to the :monkey_face: project :)

Signed-off-by: Rohit Yadav <rohit.yadav@shapeblue.com>

### CODE REVIEW

**Comment by xenserverarmy** [comment]
This looks solid, but I'd update line 457 to tick-quote the vmchain as you've done elsewhere

**Comment by bhaisaab** [comment]
@xenserverarmy thanks Tim for a quick review, I've fixed the case you've mentioned.

**Comment by agneya2001** [comment]
Reviewed it, looks good.

**Comment by bhaisaab** [comment]
@xenserverarmy @agneya2001 the latest update I did was to flush iptables rules before setting up ipset rules, this removes ipset references so easier to remove old iphash based ipset (when swapping). This way, the solutions works irrespective of upgrades issues, disconnects/reconnects etc.

**Pull request merged**
