### PR TITLE
kvm: add support nicAdapter detail for vm and template settings for KVM

### LINKED ISSUE #6533: Allow users to specify nicController for KVM VMs
Like other VM instance properties, add a new property nicController both in template and instance properties to allow users/admins to specify the nic controller of a VM for KVM.

##### ISSUE TYPE

 * Feature Idea

##### COMPONENT NAME

~~~
KVM, template, VM
~~~

### PR DESCRIPTION
**Pull request by rohityadavcloud**
Fixes #6533

This adds the option returned in API which in turn shows the option and possible values in the UI.

### CODE REVIEW

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Review by sureshanaparti — APPROVED** [review]
code LGTM, needs testing (mainly, with nic adapter and root disk controller options)

**Comment by harikrishna-patnala** [comment]
Changes wrt PR looks good and I can see the "nicAdapter" from VM settings. When I change/set the nicAdapter the interface is set accordingly on the VM.

One observation I've made with the "rootDiskController" during this testing is,
If rootDiskController is changed to "ide" then it is not reflected on VM. 
@sureshanaparti do you think it's an issue to be fixed, not in this PR but as a separate one.

cc @rohityadavcloud @GabrielBrascher @weizhouapache any suggestion here.

**Review by harikrishna-patnala — APPROVED** [review]

**Comment by Pearl1594** [comment]
@harikrishna-patnala wrt to rootdiskcontroller setting, if the root disk and data disk controller settings are already defined on the template, then they take precedence over the setting on the VM - PR: https://github.com/apache/cloudstack/pull/6276 attempts to fix that anomaly.

**Review by Pearl1594 — APPROVED** [review]
LGTM

**Comment by rohityadavcloud** [comment]
Thanks for review/testing @harikrishna-patnala @Pearl1594 @sureshanaparti

**Pull request merged**
