### PR TITLE
server: do not display 'Default Egress Policy' for vpc tiers

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR removes the 'Default Egress Policy' for vpc tiers.

The ingress/egress access of vpc tiers are controlled by network acl. the default egress policy is not applicable for vpc tiers.
therefore it would be better to remove it in api/ui.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Review by Pearl1594 — APPROVED** [review]
LGTM

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by shwstppr — APPROVED** [review]

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by nvazquez — APPROVED** [review]

**Comment by nvazquez** [comment]
@blueorangutan test

**Pull request merged**
