### PR TITLE
UI - Fixes Pod, Cluster selected is incorrect on addHost dialog

### PR DESCRIPTION
**Pull request by utchoang**
### Description

This PR fixes https://github.com/apache/cloudstack/issues/5864

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by sureshanaparti** [comment]
@blueorangutan ui

**Review by sureshanaparti — APPROVED** [review]
code LGTM

**Comment by sureshanaparti** [comment]
@blueorangutan ui

**Comment by sureshanaparti** [comment]
Hi @utchoang when changing the zone, the pod name shown/selected in the list box doesn't change, but the list items of the 'Pod name' are updated with new pod names. Also, when changing the pod, the cluster name shown and  list items of the 'Cluster Name' doesn't change. Please check.

**Comment by utchoang** [comment]
@sureshanaparti I have checked and it is working properly, can you check again?
https://user-images.githubusercontent.com/13766648/149729519-d22bafa2-9b66-46a8-8736-ea15706d5721.mp4

**Comment by sureshanaparti** [comment]
Check this @utchoang 

https://user-images.githubusercontent.com/12028987/149732112-03fed2a4-ebbc-4569-b37b-a41900d4d2fb.mov

**Comment by DaanHoogland** [comment]
@utchoang I think you fixed a bug, for sure. Just not the one I reported. As @sureshanaparti describes, the options of clusters should also change when a different Pod is chosen. My guess is that something similar probably happens when a cluster is chosen (for hosts).

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by utchoang** [comment]
@sureshanaparti @DaanHoogland I've fixed. Please test again. Thanks.

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by sureshanaparti** [comment]
@blueorangutan ui

**Comment by sureshanaparti** [comment]
@utchoang clusters name list is not updated properly when there are no clusters in the pod. please check.

https://user-images.githubusercontent.com/12028987/149763010-b35dd0fd-764b-42b4-bb1a-d860703d6391.mov

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by sureshanaparti** [comment]
Hi @utchoang Can you check with 'DummySGBasic' zone (in _http://qa.cloudstack.cloud/_), which doesn't have pods and clusters. I still notice cluster names are loaded in the list view, instead empty.

PR5869_test_18jan2022

**Comment by utchoang** [comment]
@sureshanaparti Sorry for the complexity, please check it again. Thanks.

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by sureshanaparti** [comment]
Verified. LGTM.

**Review by sureshanaparti — APPROVED** [review]

**Review by DaanHoogland — APPROVED** [review]
LGTM

**Pull request merged**
