### PR TITLE
Fix Management server comments PR 7379 UI issue

### PR DESCRIPTION
**Pull request by kishankavala**
### Description

This PR adds support for annotations to be added for the management server as a resource/type.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by kishankavala** [comment]
@blueorangutan ui

**Comment by kiranchavala** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Review by kiranchavala — APPROVED** [review]
LGTM able to view the comments for the management servers in the UI

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Review by rohityadavcloud — APPROVED** [review]

**Review by rohityadavcloud — APPROVED** [review]
LGTM on changes, let's wait until smoketests come back.

**Comment by kishankavala** [comment]
@blueorangutan package

**Comment by kishankavala** [comment]
@blueorangutan test

**Comment by kiranchavala** [comment]
@kishankavala  Normal user is able to add comments to the Management servers  via the api call 

Could you please look into it

**Comment by kishankavala** [comment]
> @kishankavala Normal user is able to add comments to the Management servers via the api call
> 
> Could you please look into it

Added check to deny non-admin users

**Comment by kiranchavala** [comment]
@blueorangutan package

**Comment by kishankavala** [comment]
@blueorangutan test

**Review by rohityadavcloud — APPROVED** [review]

**Comment by weizhouapache** [comment]
@kishankavala  @rohityadavcloud 
do we need this to backport to 4.18 ?

**Pull request merged**
