### PR TITLE
Travis - fix test failures observed

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

This PR fixes a subset of travis test failures as indicated in: https://github.com/apache/cloudstack/issues/6115
They include:
component/test_acl_sharednetwork_deployVM-impersonation:
- test_deployVM_in_sharedNetwork_as_regularuser_scope_all_anotherusersamedomain
- test_deployVM_in_sharedNetwork_as_regularuser_scope_all_crossdomain

component/test_acl_isolatednetwork
- test_19_deployvm_user_foruserinsamedomain
- test_20_deployvm_user_foruserincrossdomain
- test_29_restartNetwork_user_foruserinsamedomain
- test_30_restartNetwork_user_foruserinotherdomain

component/test_acl_isolatednetwork_delete
- test_deleteNetwork_user_foruserinotherdomain
- test_deleteNetwork_user_foruserinsamedomain

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### CODE REVIEW

**Review by rohityadavcloud — APPROVED** [review]

**Review by weizhouapache — APPROVED** [review]

**Comment by weizhouapache** [comment]
@Pearl1594 
since the travis test fails on 4.16, can you re-target to 4.16 ?

as we discussed internally, it would be better to create all bug fixes for LTS version then merge forward to main branch.

**Comment by Pearl1594** [comment]
Sure @weizhouapache I'll target this PR against 4.16. Thanks.

**Review by nvazquez — APPROVED** [review]

**Comment by nvazquez** [comment]
Merging based on approvals and Travis test results since this PR fixes them

**Comment by nvazquez** [comment]
@Pearl1594 given #6126, does this PR need to be reverted as well?

**Comment by Pearl1594** [comment]
These test failures didn't pertain to the changes made in #6126

**Pull request merged**
