### PR TITLE
ui: Adding option to select columns to display

### PR DESCRIPTION
**Pull request by davidjumani**
### Description

Fixes https://github.com/apache/cloudstack/issues/5555
Allows users to customize columns to display in the listView

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

### Screenshots (if appropriate):

Screenshot from 2022-02-17 13-08-39

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan ui

**Review by utchoang — COMMENTED** [review]
@davidjumani I think the dropdown should be displayed when the user clicks on it instead of hovering over it. In addition, it is possible to allow multiple selections once instead of having to select each item (now each selection will turn off the dropdown).

**Comment by davidjumani** [comment]
@blueorangutan ui

**Comment by davidjumani** [comment]
@blueorangutan ui

**Review by utchoang — APPROVED** [review]
LGTM!

**Review by nvazquez — APPROVED** [review]
LGTM - manually tested OK

**Pull request merged**
