### PR TITLE
api: Prevent modifying acl rules order for default ACLs

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

This PR fixes the NullPointerException seen when trying to move the rules of a default ACL
```
2022-03-31 06:59:15,323 ERROR [c.c.a.ApiAsyncJobDispatcher] (API-Job-Executor-42:ctx-d9a17d05 job-53) (logid:47b12a5e) Unexpected exception while executing org.apache.cloudstack.api.command.user.network.MoveNetworkAclItemCmd
java.lang.NullPointerException
        at com.cloud.user.AccountManagerImpl.checkAccess(AccountManagerImpl.java:579)
        at com.cloud.user.AccountManagerImpl.checkAccess(AccountManagerImpl.java:567)
        at jdk.internal.reflect.GeneratedMethodAccessor309.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
        at com.sun.proxy.$Proxy130.checkAccess(Unknown Source)
        at com.cloud.network.vpc.NetworkACLServiceImpl.validateMoveAclRulesData(NetworkACLServiceImpl.java:1149)
```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### How Has This Been Tested?
image

### CODE REVIEW

**Comment by Pearl1594** [comment]
@blueorangutan package

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by weizhouapache** [comment]
@blueorangutan test

**Review by DaanHoogland — COMMENTED** [review]
clgtm, but does this ask for an extra (unit)test

**Review by rohityadavcloud — APPROVED** [review]

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Review by nvazquez — APPROVED** [review]

**Pull request merged**
