### PR TITLE
server: detach data disks before destroying vms

### LINKED ISSUE #4902: Destroy VM should detach the volumes from VM and recover VM should not try to attach the volumes again
This is an improvement ticket in which volumes of a VM which are not intended to be deleted (when VM is tried to destroy) are going to be detached from VM during destroy VM operation.

CloudStack volumes are first-class citizens, they do not belong to a VM. Therefore data disks must be detached from the destroyed VM and either be expunged (if that is what the user requested) or be left detached and available for any volume actions - attach, expunge, extract, etc.

The existing behaviour is upon on destroy of VM (having datadisks) and data disks are not selected to delete, then during VM destroy these disks are still marked as attached to VM. Only during VM expunge of VM these volumes are detached from the VM. 

##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### EXPECTED RESULTS

~~~
- When destroy VM with expunge or without expunge and no data disk is selected for deletion
          Data disks will be detached from VM during destroy VM itself
~~~

##### ACTUAL RESULTS

~~~
- When destroy VM without expunge and when no data disk is selected for deletion
          VM is stopped and data disks will still shown as attached to original VM
          When tried to recover the VM, the VM is made ready along with its data disks as before.

- When destroy VM without expunge and when one or more data disks are selected for deletion
          VM is stopped and data disks which are selected for deletion will be deleted and other data disks will still remain attached
          When tried to recover the VM, the VM is made ready along with remaining data disks which are not deleted

- When destroy VM with expunge and when no data disk is selected for deletion
          All data disks are detached from VM
          VM will be destroyed and expunged completely

- When destroy VM with expunge and few data disks are selected for deletion
         Data disks marked for deletion are deleted and the remaining disks are detached from VM
         VM will be destroyed and expunged completely.

~~~

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #4902 

The testing results with this change:

- When destroy VM without expunge and when no data disk is selected for deletion
        destroy vm: VM is stopped, data disk is detached from vm (in Ready state)
        recover vm: vm is ready only with root disk.

- When destroy VM without expunge and when one or more data disks are selected for deletion
        destroy vm: VM is stopped, Data disks marked for deletion are detached and in Destroy state . the remaining disks are detached from VM
        recover vm: vm is ready only with root disk.
        recover data disk in Destroy: volume is ready, and not attached to vm.

- When destroy VM with expunge and when no data disk is selected for deletion
        VM is destroyed and expunged completely.
        data disks are detached from vm.

- When destroy VM with expunge and few data disks are selected for deletion
         VM is destroyed and expunged completely.
         Data disks marked for deletion are deleted. the remaining disks are detached from VM

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by nvazquez — APPROVED** [review]
LGTM - needs testing

**Comment by nvazquez** [comment]
@weizhouapache can you target this PR to the main branch?

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Review by davidjumani — APPROVED** [review]
Tested with multiple DataDisks, all 4 scenarios work as expected

**Pull request merged**
