### PR TITLE
Skip Coverage Check when forks are updated

### PR DESCRIPTION
**Pull request by jbampton**
### Description

This PR skips the coverage check instead of failing when forks are updated.

After this PR is merged and forks are updated it should skip the check.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [X] Trivial

### Screenshots (if appropriate):

Shows the failing check

Screen Shot 2023-02-08 at 1 20 49 am

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@jbampton why do we want this?
will it skip coverage checks on PRs when the fork they come from is updated?

**Review by DaanHoogland — COMMENTED** [review]
code looks good, but I wonder ow this works on PRs

**Comment by weizhouapache** [comment]
> @jbampton why do we want this? will it skip coverage checks on PRs when the fork they come from is updated?

actually there is a line in the yaml file
```
on: [pull_request, push]
```

so this check is not performed on the github forks.

However, if you push to your own repository, the check will be performed.
in this case, you need to add codecov token in your project, and codecov should work.
you can look at my repo where codecov works.  @jbampton 
https://github.com/weizhouapache/cloudstack-new/actions/workflows/codecov.yml

**Comment by weizhouapache** [comment]
in short, I am 0 on this PR. I did not see benefit/harmless for cloudstack project.

@jbampton can you add the check on other checks (e.g. main-sonar-check.yml, ui.yml, ci.yml) as well ?

**Review by rohityadavcloud — APPROVED** [review]

**Review by weizhouapache — APPROVED** [review]

**Comment by weizhouapache** [comment]
> in short, I am 0 on this PR. I did not see benefit/harmless for cloudstack project.
> 
> @jbampton can you add the check on other github actions (e.g. main-sonar-check.yml, ui.yml, ci.yml) as well ?

no worries. created a PR to follow up : #7199

**Pull request merged**
