### PR TITLE
Updating Alert codes

### PR DESCRIPTION
**Pull request by dcarbone**
Updating codes per values present here: https://github.com/apache/cloudstack/blob/4.8/api/src/org/apache/cloudstack/alert/AlertService.java#L39

### CODE REVIEW

**Comment by wido** [comment]
Can maybe @rhtyd comment on this one?

**Comment by rhtyd** [comment]
We'll need to check this against the consumers of the response, based on present alert codes we may need to update it. We'll also need to see when the alert code diverged, why some of the alert codes changed (for example HOST etc.)

**Comment by jburwell** [comment]
I would like to get this PR merged as part of the 4.8.2.0 release, but we don't have much time to get it completed.

@dcarbone could you please create a JIRA ticket explaining the bug/enhancement motivation of this PR?  Also, could you please investigate the cause of the Travis build failure?

@rhtyd were you able to complete your analysis?

**Comment by dcarbone** [comment]
@jburwell: JIRA ticket created: https://issues.apache.org/jira/browse/CLOUDSTACK-9468

**Comment by rhtyd** [comment]
@dcarbone can you squash your commits and rebase against latest, thanks. Please also amend git commit message to include the JIRA ID.
@jburwell I did not start my analysis, I'll do that once we've sorted out above.

**Comment by jburwell** [comment]
@rhtyd @dcarbone given that we are trying to get a 4.8 RC cut ASAP (we are week late already), I think it is best to push this PR to 4.9.2.0.  Would you mind re-pointing it to the 4.9 branch?

**Comment by dcarbone** [comment]
squashed, pointing at 4.9, and commit amended.

**Comment by jburwell** [comment]
@rhtyd have you had a chance to analyze?  I would like to include this change in 4.9.1.0 and 4.10.0.0 for which we are planning to cut RCs on 25 Sept 2016.

**Comment by rhtyd** [comment]
LGTM @jburwell I checked the changes against the values defined in `AlertService` and they check out perfectly.

**Comment by rhtyd** [comment]
@jburwell we can merge this, since it's a doc change no tests are needed.

**Comment by rhtyd** [comment]
LGTM, this is only a comment change. Changes have been verified, so I'll proceed with merging this.

**Pull request merged**
