### PR TITLE
Allow scaling VM to a service offering having different storage tags

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

This PR addresses https://github.com/apache/cloudstack/issues/5512

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Test 1
With the global setting - `match.storage.pool.tags.with.disk.offering` set to true, scaling a VM to an offering with a different storage tag isn't possible. 
Fails with the following exception (tried via cmk):
```
(localcloud) 🐱 > scale virtualmachine id=ce2897f9-90c0-46de-b3b5-0478175c8d0f serviceofferingid=d5b68cac-415d-4343-bef2-36b4b9787abf 
{
  "accountid": "138951c3-8e39-11ec-a631-1e00fb00013b",
  "cmd": "org.apache.cloudstack.api.command.admin.vm.ScaleVMCmdByAdmin",
  "completed": "2022-02-15T09:20:06+0000",
  "created": "2022-02-15T09:20:06+0000",
  "jobid": "faa4faf1-83c5-4927-b135-89431c110782",
  "jobprocstatus": 0,
  "jobresult": {
    "errorcode": 431,
    "errortext": "Unable to upgrade virtual machine; the current service offering  should have tags as subset of the new service offering tags. Current service offering tags: [pool2]; new service offering tags: [pool1]"
  },
  "jobresultcode": 530,
  "jobresulttype": "object",
  "jobstatus": 2,
  "userid": "138a5a9a-8e39-11ec-a631-1e00fb00013b"
}
🙈 Error: async API failed for job faa4faf1-83c5-4927-b135-89431c110782

```

Also, the UI doesn't list the compute offering:
image

#### Test 2
With the global setting - `match.storage.pool.tags.with.disk.offering` set to false, scaling a VM to an offering with a different storage tag is possible with the `automigrate` option set to true. The UI also displays the other compute offerings - those with different storage tags, during scale operation:

image

Successfully scaled the VM & migrated the volume to the appropriate pool

### CODE REVIEW

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan test

**Comment by Pearl1594** [comment]
@blueorangutan test

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan package

**Review by harikrishna-patnala — APPROVED** [review]
Code changes LGTM

**Comment by weizhouapache** [comment]
@Pearl1594 
did you test with 4.16 or 4.17 ?

I faced an issue when I tested this PR in 4.17 by following steps
(1) create a service offering with storage tag
(2) update storage tag of pool to same tag
(3) scale vm to new service offering, works
(4) change global setting to `false`, when scale vm to default "Small Instance". got an exception: "The new disk offering requires that a size be specified."

I think it is caused by @harikrishna-patnala 's PR #5008

**Comment by Pearl1594** [comment]
I had tested it with mai - but using non customized offering.

**Comment by harikrishna-patnala** [comment]
Yes @weizhouapache, you are correct. And @Pearl1594 's last commit will fix that issue of "The new disk offering requires that a size be specified."

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
> Yes @weizhouapache, you are correct. And @Pearl1594 's last commit will fix that issue of "The new disk offering requires that a size be specified."

@harikrishna-patnala  thanks. that's great. 
 @Pearl1594 thanks for the fix

**Review by weizhouapache — APPROVED** [review]
manually tested ok

**Review by sureshanaparti — APPROVED** [review]
code LGTM

**Pull request merged**
