### PR TITLE
Add scss to css compiler

### PR DESCRIPTION
**Pull request by webermaximilian92**
## Description

This adds an gulp tasks, to build existing css files out of scss files and enables advantages for working with style rules. 
Also this will reduce the complexibility of heavy css files **in all future css changes**.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

(This changes modify and unify the structure of css code only.)
All we have to check yet, is if .css file-changes include only: indentation, spaces and quotes.

It's very useful to reduce the diff to non whitespace changes here:
Screenshot 2019-04-26 at 16 23 44

### CODE REVIEW

**Comment by rafaelweingartner** [comment]
@webermaximilian92 thanks for the PR!

Can you provide some more details about the changes this PR is providing? I mean, how this will play out in ACS. When will the CSS compilation take place? At runtime when the page is being loaded? What are the benefits that we get with these changes?

**Comment by webermaximilian92** [comment]
Hey Rafael,

- sass and scss are preprocessors of css. Similar to ES6 or TypeScript for JavaScript.
- SCSS provides us many logical functions and advantages to organise CSS rules more easily
- Using css is not the common standard for such complex pages like cloudstack anymore.
- We can make the css code more modular and maintainable with sass/scss, by splitting files.
- We could also split css files, but this is not best prectice, since many css files will result in many server requests, and with sass it's possible to compile many files into one css file in just under a second after scss change.
- Later we could minify the final css file automatically, this will enhance loading times of pages.

**Comment by rafaelweingartner** [comment]
Thanks @webermaximilian92.
Can you check the licensing issues?
https://builds.apache.org/job/cloudstack-pr-analysis/8442/artifact/target/rat.txt

**Comment by webermaximilian92** [comment]
Very sorry I had to create new PR after running in problems with my forked cloudstack after switching my username.
https://github.com/apache/cloudstack/pull/3307

**Pull request closed without merging**
