### PR TITLE
Create profiles to download systemvm-templates

### PR DESCRIPTION
**Pull request by GutoVeronezi**
### Description
As I pointed on thread [[VOTE] Apache Cloudstack 4.16.0.0 RC1](https://lists.apache.org/thread.html/rc061a4da7bd50b49ff99b41f059cb4088b998929033755e4b87f631d%40%3Cdev.cloudstack.apache.org%3E), regarding the auto upgrading `systemvms-templates`; the code will  `autoupgrade` the `systemvm-templates` if the templates are found locally. To generate the template during the build, one has to activate the `noredist profile` when building the packages, which is necessary (normally used to) only to VMWare.

Some people, might not want the noredist JARs from VMware, and therefore will not build with this profile. Furthermore, package `cloudstack-management` goes from **~100Mb** to more than **1.5Gb** when using the `noredist` while executing the 4.16.0.0 build. It happens due to `cloudstack/engine/schema/pom.xml` automatically downloading XenServer, KVM, and VMware `systemvms-templates`. Every time that we build the packages, it will download all these systemvms-templates, and we are unable to decide which one is necessary.

This PR intends to create specific profiles for each systemvm-template. Therefore, one can build ACS only for the hypervisor it needs, and if it needs to use the auto update of the system VM templates; one can decide not to use this feature and keep manually registering the templates only when they are needed.

### Types of changes
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale
- [ ] Major
- [x] Minor

### How Has This Been Tested?
I built the packages with all the profiles:
- `-DdownloadKvmSystemVmTemplate`
- `-DdownloadHypervSystemVmTemplate`
- `-DdownloadVmwareSystemVmTemplate`
- `-DdownloadXenserverSystemVmTemplate`
- `-DdownloadOvmSystemVmTemplate`

And then I built them separately.

### CODE REVIEW

**Comment by rhtyd** [comment]
My point being, people building noredist pkgs - get all-inclusive pkgs. We can discuss and change the `noredist` build profile name, however, what I'm asking is a build profile that allows bundilng of all hypervisors - maybe consider a new profile like `-D systemvm-all` that is triggered set when `-D noredist` is passed?

**Comment by PaulAngus** [comment]
I'm not sure where this fits into the conversation,  but i think i'd be a good idea to have a separate (and optional) cloudstack-systemvms rpm.
ie
`yum install cloudstack-management cloudstack-systemvms`

it stops the 'standard' install bloating massively while still simplifying the installation.

**Comment by GabrielBrascher** [comment]
@rhtyd I agree, it makes total sense to have a build profile that allows bundling of packages that would work on all/any hypervisors. The system VM packaging also looks nice; for many users, it would be easier to upgrade/deploy.

But I think that it would be great if the project offers flexibility in regards to such profiles.
I Imagine that's what @GutoVeronezi is aiming for.

As an example, users would by default have SystemVM in the package and the `noredist` set in order to pack in VMware or any other hypervisor.

However, "advanced users" could do a fine setup that would match their requirements.
For instance, build for a specific hypervisor and choose if the System VM template will be automatically injected or manually placed.

**Comment by rhtyd** [comment]
We're coming with a new design doc that will reduce the cloudstack-management pkg by more than 1GB in size and introduce a single mvn flag that will bundle a template for only one type of hypervisor. (we tested and found we don't need to bundle all three hypervisor templates, as qemu-img can be used to convert formats on the fly which is what we currently, for example qemu-img takes 10-20s to convert say a vmdk to qcow2 or vmdk to vhd).
Early draft here: https://cwiki.apache.org/confluence/display/CLOUDSTACK/SystemVM+Optimisations

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
After experimenting with some strategies @Pearl1594 concluded that bundling just one (kvm) template and converting on the way upon installation/download/seeding may not give more benefit as part of https://cwiki.apache.org/confluence/display/CLOUDSTACK/SystemVM+Optimisations
Therefore, your PR @GutoVeronezi would make sense and we can fix the packaging specs/configuration to enable the three -D flags to bundle all three hypervisor templates by default, while allow users to export the flags via some env variable so they can customise their packaging requirements. cc @Pearl1594

**Comment by GutoVeronezi** [comment]
@blueorangutan package

**Comment by GutoVeronezi** [comment]
@rohityadavcloud do we need to work on anything else in this PR? cc: @nvazquez @Pearl1594

**Review by GabrielBrascher — APPROVED** [review]
Thanks for the PR @GutoVeronezi.
I am +1 on this approach, LGTM

**Comment by nvazquez** [comment]
Thanks @GutoVeronezi I think it is fine now, @Pearl1594 please advise if necessary

**Comment by nvazquez** [comment]
@blueorangutan test matrix

**Comment by Pearl1594** [comment]
Apologies for the delay in response. This PR looks good to me, but before we go ahead and merge it, we'd need to add support to Blueorangutan and consequently the packaging job to take additional flags to bundle the appropriate templates. I'll work on it sometime later this week and keep you'll posted.

**Comment by GutoVeronezi** [comment]
Hi @Pearl1594, any update about this one?

**Comment by Pearl1594** [comment]
my apologies @GutoVeronezi I haven't had time to make the necessary changes to the packaging job yet. Hopefully, I can work on it early next week, if that's alright.

**Comment by Pearl1594** [comment]
@GutoVeronezi was working on adding support to include the flags in the package jobs, ad realized that there is a need to add support to the packaging script (package.sh) as well to pass the flags during rpm builds. Something like this - https://github.com/apache/cloudstack/commit/690d2573ab9c4207c441eb7372e06ebe5bf2f483 would probably need to be done.

**Comment by GutoVeronezi** [comment]
@Pearl1594 I made a cherry-pick of your commit, thank you.

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by Pearl1594** [comment]
@blueorangutan package kvm,xen

**Comment by Pearl1594** [comment]
@blueorangutan package kvm,xen

**Comment by Pearl1594** [comment]
@blueorangutan package kvm,xen

**Comment by Pearl1594** [comment]
@blueorangutan package kvm,xen

**Comment by Pearl1594** [comment]
@blueorangutan package kvm,xen

**Comment by Pearl1594** [comment]
@blueorangutan package kvm

**Comment by Pearl1594** [comment]
@blueorangutan package kvm,vmware

**Comment by Pearl1594** [comment]
@blueorangutan package kvm,vmware

**Comment by Pearl1594** [comment]
@blueorangutan package kvm,xen

**Comment by Pearl1594** [comment]
@blueorangutan package kvm,xen

**Comment by Pearl1594** [comment]
Was able to finally get bo to pass the extended choice parameters - 
centos7 packaging job output - which will be same for centos8/rocky8 and suse:
```
Adding flags to package requested templates
++ rpm --eval '-Dsystemvm-kvm -Dsystemvm-xen'
+ FLAGS=' -Dnoredist -Dsystemvm-kvm -Dsystemvm-xen'
+ mvn -Psystemvm,developer -Dnoredist -Dsystemvm-kvm -Dsystemvm-xen clean package
/root/.mavenrc: line 1: /usr/libexec/java_home: No such file or directory
OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0

[INFO] Scanning for projects...

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
```

debian pkg output:
```
make[1]: Entering directory '/jenkins/workspace/deb-pkg-flags'
mvn clean package -Psystemvm,developer -Dsystemvm \
    -Dcs.replace.properties=replace.properties.tmp \
    -Dmaven.repo.local=/root/.m2/repository \
     -Dnoredist -Dnonoss  -Dsystemvm-kvm -Dsystemvm-xen
/usr/bin/mvn: 1: /root/.mavenrc: /usr/libexec/java_home: not found
OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0

[INFO] Scanning for projects...
[INFO] ------------------------------------------------
```
FYI, failures you see in centos8 and suse packing jobs are expected as they aren't created - for testing

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Review by nvazquez — APPROVED** [review]

**Comment by nvazquez** [comment]
Merging based on approvals and test results (failure not related to this PR)

**Pull request merged**
