### PR TITLE
Fix deploy from ISO with custom disk offering

### PR DESCRIPTION
**Pull request by nvazquez**
### Description

This PR fixes deploy from ISO with a custom disk offering, the size parameter is not honoured
Fixes: #6440 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [x] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?
Deploy VM from ISO - select custom disk offering
Deploy VM from template - select custom data disk offering

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
Removing the blocker tag, since there are 2 workarounds:
- Pass the 'rootdisksize' parameter to the deployVM API
- Use a fixed offering with the expected size

**Review by sureshanaparti — APPROVED** [review]
Verified fix, LGTM.

**Review by Pearl1594 — APPROVED** [review]
Verified. LGTM

**Comment by bugoff** [comment]
Hi, is it possible this issue still exists for templates? Do you want me to create a new issue for this?

**Pull request merged**
