### PR TITLE
Add if not exists constraint to create table on upgrade paths

### PR DESCRIPTION
**Pull request by nvazquez**
## Description
Simply add 'IF NOT EXISTS' constraint to 'CREATE TABLE' SQLs on upgrade paths. This avoids upgrade paths to fail if there had been previous failures on the upgrade process.

Fixes: #3891 

## Types of changes
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by borisstoyanov** [comment]
@blueoranguran package

**Comment by borisstoyanov** [comment]
@blueoranguran package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by andrijapanicsb** [comment]
wow.... what, why?

-1 

If there was previous failure on upgrade, bunch of other things will fail, like extending the existing table or such. I saw the issue which this PR is supposed to fix, and I vote for closing both.

The correct action is failed upgrade --> roll back DB --> start again.

**Comment by andrijapanicsb** [comment]
To further explain myself - if you attempt the upgrade on top of DB which previously failed to be upgraded, you might end up with duplicate entries trying to be inserted and that would be chaos.
The only "normal" way (acceptable in production) to proceed with the failed upgrade, is to start clean (drop DB, restore DB) and try again.

**Comment by DaanHoogland** [comment]
@andrijapanicsb I almost agree with you. There is a possibility that two upgrade paths produce conflicting table definitions. In those cases (and in principle) the "CREATE IF NOT EXISTS" pattern is very good to hav as a standard. Double entries are a whole different issue.

**Pull request closed without merging**
