### PR TITLE
linstor/kvm: Workaround a qemu bug and IDE bus discard enabled.

### PR DESCRIPTION
**Pull request by rp-**
### Description

qemu has a bug versions prior 7.0 with discard enabled and using the IDE bus.
It would crash the qemu process and kill the virtual machine, this is most noticeable on installing a windows guest from the Windows ISO installer.

bug link:
https://bugzilla.redhat.com/show_bug.cgi?id=2029980

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [x] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

Tested in a local Linstor cluster and added unittests to check the combinations.

### CODE REVIEW

**Comment by rp-** [comment]
@JoaoJandre As the Linstor discard support was included in 4.20/main,
I appreciate it if you would also think about get this included.

**Review by DaanHoogland — APPROVED** [review]

**Review by JoaoJandre — APPROVED** [review]
@rp- Yes, we can add it to 4.20

**Comment by JoaoJandre** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Review by slavkap — APPROVED** [review]
CLGTM

**Pull request merged**
