### PR TITLE
Fixup startVM on simulator

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

If we stop and start the VM again on another host, simulator doesn't update the host id in simulator database. This PR updates the host id and other parameters which might change for a VM.

#### Steps to reproduce
1. Start a VM. (Let's say the VM started on host H1)
2. Stop the above VM and start it on any other host (let's say H2).
3. VM gets started on the specified host H2.
4. After some time, host for the VM changes back to H1.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
clgtm and simulator only. I see no reason not to merge.

**Comment by DaanHoogland** [comment]
@vishesh92 can you check the GHA failures quickly and merge if these are easily explained?

**Comment by vishesh92** [comment]
> @vishesh92 can you check the GHA failures quickly and merge if these are easily explained?

Simulator CI jobs failed due to failure in publishing results to codecov.
There was a test failure in `Coverage Check / codecov (pull_request)` which doesn't seem to be related to this PR. I have triggered the job again for verification.

**Comment by vishesh92** [comment]
```java
Error:  Tests run: 33, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 10.176 s <<< FAILURE! - in org.apache.cloudstack.api.response.QuotaResponseBuilderImplTest
Error:  validateEndDateOnCreatingNewQuotaTariffTestSetValidEndDate(org.apache.cloudstack.api.response.QuotaResponseBuilderImplTest)  Time elapsed: 0.02 s  <<< ERROR!
com.cloud.exception.InvalidParameterValueException: The quota tariff's end date [Tue Jun 11 08:34:00 UTC 2024] cannot be less than now [Tue Jun 11 08:34:00 UTC 2024].
	at org.apache.cloudstack.api.response.QuotaResponseBuilderImplTest.__CLR4_4_1z0nq4d18x(QuotaResponseBuilderImplTest.java:335)
	at org.apache.cloudstack.api.response.QuotaResponseBuilderImplTest.validateEndDateOnCreatingNewQuotaTariffTestSetValidEndDate(QuotaResponseBuilderImplTest.java:331)
```
@DaanHoogland the above test is failing and is not related to this PR. I am creating another PR to fix the unit test failure.

**Comment by vishesh92** [comment]
@DaanHoogland Looks like updating the branch fixed the issue.

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Pull request merged**
