### PR TITLE
.github: run all gha on ubuntu latest

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR...

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [x] ci/build
#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@DaanHoogland 
I remember @rohityadavcloud changed from latest to 22.04 in some yaml files.

I think it is better to use 22.04. For now, ubuntu:latest is same as 22.04, but if it changes (for example to 24.04) build might fail.

**Comment by DaanHoogland** [comment]
> @DaanHoogland I remember @rohityadavcloud changed from latest to 22.04 in some yaml files.
> 
> I think it is better to use 22.04. For now, ubuntu:latest is same as 22.04, but if it changes (for example to 24.04) build might fail.

@weizhouapache I think we can change/fix when it fails, the reverse might be true as well as latest is the one best maintained. It used to be 20.04 for a long time after 22.04 was already introduced.

**Comment by weizhouapache** [comment]
> > @DaanHoogland I remember @rohityadavcloud changed from latest to 22.04 in some yaml files.
> > I think it is better to use 22.04. For now, ubuntu:latest is same as 22.04, but if it changes (for example to 24.04) build might fail.
> 
> @weizhouapache I think we can change/fix when it fails, the reverse might be true as well as latest is the one best maintained. It used to be 20.04 for a long time after 22.04 was already introduced.

@DaanHoogland 
the latest is well maintained, as well as the ubuntu 22.04 and 20.04 which are LTS.
I'd like to use a fixed version which we know it works, then upgrade to next LTS version if required, instead of fixing possible issues after upgrade by 3rd party.
The idea is similar as: many users use cloudstack 4.15/4.16, then upgrade to newer 4.17 at proper time.

**Comment by rohityadavcloud** [comment]
@DaanHoogland I think the ubuntu-latest is buggy in how Github Actions interprets it, it's better to be specific and move everything to ubuntu-22.04.

**Review by weizhouapache — APPROVED** [review]
all github workflows run on ubuntu 22.04 with this PR :+1: 

```
(HEAD detached at origin/pr/7091))$ git grep ubuntu .github
.github/boring-cyborg.yml:  "distro:ubuntu":
.github/workflows/build.yml:    runs-on: ubuntu-22.04
.github/workflows/ci.yml:    runs-on: ubuntu-22.04
.github/workflows/codecov.yml:    runs-on: ubuntu-22.04
.github/workflows/linter.yml:    runs-on: ubuntu-22.04
.github/workflows/linter.yml:    runs-on: ubuntu-22.04
.github/workflows/main-sonar-check.yml:    runs-on: ubuntu-22.04
.github/workflows/merge-conflict-checker.yml:    runs-on: ubuntu-22.04
.github/workflows/rat.yml:    runs-on: ubuntu-22.04
.github/workflows/sonar-check.yml:    runs-on: ubuntu-22.04
.github/workflows/ui.yml:    runs-on: ubuntu-22.04
```

**Review by rohityadavcloud — APPROVED** [review]

**Pull request merged**
