### PR TITLE
ui: prevent scheduling readyforshutdown job when api inaccessible

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Non-admin accounts may not have access to the readyForShutdown API therefore UI should not schedule the job.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):
Without fix errors can be seen for the readyForShutdown API call when logged in as normal account,
Screenshot from 2024-01-05 11-57-55

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan ui

**Review by harikrishna-patnala — COMMENTED** [review]
@shwstppr agree for the issue and fix but I don't see this getting called for admin account also, anything we are missing here ?

image

I've verified on other server and there I can see that at regular intervals but not in above case

image

**Comment by shwstppr** [comment]
@harikrishna-patnala did you try on qa server?
QA server (its management server) is on 4.18 and readyForShutDown feature is in main/4.19. Probably that's why it is not showing. Otherwise, I'll check

**Comment by harikrishna-patnala** [comment]
> @harikrishna-patnala did you try on qa server? QA server (its management server) is on 4.18 and readyForShutDown feature is in main/4.19. Probably that's why it is not showing. Otherwise, I'll check

I've tried on the env built on top this PR @shwstppr https://qa.cloudstack.cloud/simulator/pr/8448

**Comment by shwstppr** [comment]
@harikrishna-patnala let me build an env

@blueorangutan package

**Review by Pearl1594 — APPROVED** [review]
LGTM

**Pull request merged**
