### PR TITLE
Compabitility fix for Docker >= 1.11 (docker/docker#19490)

### PR DESCRIPTION
**Pull request by moul**

### CODE REVIEW

**Comment by wido** [comment]
LGTM

Very simple Docker fix

**Comment by swill** [comment]
@moul can you post some verification that this fix works?

**Comment by moul** [comment]
@swill, this solution is backward compatible, the `.dockerinit` file always cohabited with `.dockerenv`, until recently, `.dockerinit` was removed while `.dockerenv` is still there

**Comment by swill** [comment]
@moul can you close and reopen the PR or rebase and force push in order to kick off Jenkins again so we can get this all green?

@pdion891 I think you have spent enough time with Docker to give me the the missing LGTM vote.  Thanks...

**Comment by pdion891** [comment]
LGTM

**Comment by dmabry** [comment]
LGTM based code review.  This is a very straight forward change.

**Comment by bvbharatk** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 190
 Hypervisor xenserver
 NetworkType Advanced
 Passed=72
 Failed=1
 Skipped=3

_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/yj3wnzbceo9uef2/AAB6u-Iap-xztdm6jHX9SjPja?dl=0


**Failed tests:**
* test_vm_life_cycle.py

 * test_10_attachAndDetach_iso Failing since 2 runs


**Skipped tests:**
test_vm_nic_adapter_vmxnet3
test_static_role_account_acls
test_deploy_vgpu_enabled_vm

**Passed test suits:**
test_deploy_vm_with_userdata.py
test_affinity_groups_projects.py
test_portable_publicip.py
test_vpc_vpn.py
test_over_provisioning.py
test_global_settings.py
test_scale_vm.py
test_service_offerings.py
test_routers_iptables_default_policy.py
test_routers.py
test_reset_vm_on_reboot.py
test_snapshots.py
test_deploy_vms_with_varied_deploymentplanners.py
test_login.py
test_list_ids_parameter.py
test_public_ip_range.py
test_multipleips_per_nic.py
test_regions.py
test_affinity_groups.py
test_network_acl.py
test_pvlan.py
test_volumes.py
test_nic.py
test_deploy_vm_root_resize.py
test_resource_detail.py
test_secondary_storage.py
test_disk_offerings.py

**Comment by moul** [comment]
Rebased for Travis

**Comment by karuturi** [comment]
merging this now

**Pull request merged**
