### PR TITLE
CLOUDSTACK-9597: Should not fetch resource count for removed entity

### PR DESCRIPTION
**Pull request by marcaurele**
Fetch the number of resourceCount by domain and account excluding the removed ones.

Signed-off-by: Marc-Aurèle Brothier <m@brothier.org>

### CODE REVIEW

**Comment by marcaurele** [comment]
Will fix the checks in `ConfigurationServerImpl`:
- https://github.com/apache/cloudstack/blob/master/server/src/com/cloud/server/ConfigurationServerImpl.java#L1426
- https://github.com/apache/cloudstack/blob/master/server/src/com/cloud/server/ConfigurationServerImpl.java#L1455

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by marcaurele** [comment]
@jburwell I did the rebase on 4.9. There isn't any test for now. I will work on that.

**Comment by rhtyd** [comment]
Thanks @marcaurele 
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by borisstoyanov** [comment]
Tested the fix manually it looks OK. Smoketests results also looking good.

**Comment by rhtyd** [comment]
@marcaurele can you add the JIRA id in the git commit message, and push -f to re-kick Travis?

**Pull request merged**
