### PR TITLE
interpret /etc/redhat-release better

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR fixes the way /etc/redhat-release is read to return host attributes

Fixes: #7547

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

tested on a host manually by editting the /etc/redhat-release file and verifying different outputs.

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@blueorangutan test r8 kvm-rocky8

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Comment by weizhouapache** [comment]
looks good.

checked two rocky8 environment

- without this PR

```
mysql> select * from host_details where name not in ('username','password');
+----+---------+----------------------------------------------------+---------------------------+
| id | host_id | name                                               | value                     |
+----+---------+----------------------------------------------------+---------------------------+
|  1 |       1 | Host.OS.Kernel.Version                             | 6.3.6-1.el8.elrepo.x86_64 |
|  2 |       1 | com.cloud.network.Networks.RouterPrivateIpStrategy | HostLocal                 |
|  3 |       1 | Host.OS.Version                                    | 8.4                       |
|  4 |       1 | host.volume.encryption                             | true                      |
|  5 |       1 | secured                                            | true                      |
|  6 |       1 | Host.OS                                            | Rocky                     |
| 15 |       2 | Host.OS.Kernel.Version                             | 6.3.6-1.el8.elrepo.x86_64 |
| 16 |       2 | com.cloud.network.Networks.RouterPrivateIpStrategy | HostLocal                 |
| 17 |       2 | Host.OS.Version                                    | 8.4                       |
| 18 |       2 | host.volume.encryption                             | true                      |
| 19 |       2 | secured                                            | true                      |
| 20 |       2 | Host.OS                                            | Rocky                     |
```

- with this PR

 ```
mysql> select * from host_details where name not in ('username','password');
+----+---------+----------------------------------------------------+---------------------------+
| id | host_id | name                                               | value                     |
+----+---------+----------------------------------------------------+---------------------------+
|  1 |       1 | Host.OS.Kernel.Version                             | 6.3.6-1.el8.elrepo.x86_64 |
|  2 |       1 | com.cloud.network.Networks.RouterPrivateIpStrategy | HostLocal                 |
|  3 |       1 | Host.OS.Version                                    | 8.4                       |
|  4 |       1 | host.volume.encryption                             | true                      |
|  5 |       1 | secured                                            | true                      |
|  6 |       1 | Host.OS                                            | Rocky Linux               |
| 15 |       2 | Host.OS.Kernel.Version                             | 6.3.6-1.el8.elrepo.x86_64 |
| 16 |       2 | com.cloud.network.Networks.RouterPrivateIpStrategy | HostLocal                 |
| 17 |       2 | Host.OS.Version                                    | 8.4                       |
| 18 |       2 | host.volume.encryption                             | true                      |
| 19 |       2 | secured                                            | true                      |
| 20 |       2 | Host.OS                                            | Rocky Linux               |
```

**Review by weizhouapache — APPROVED** [review]

**Comment by mlsorensen** [comment]
FY @DaanHoogland @rohityadavcloud @weizhouapache I - this may break upgrades since the host OS details needs to match the rest of the cluster for agents to join. See #7742

**Comment by DaanHoogland** [comment]
@mlsorensen , Your method will certainly work, but I think we need to add an example query to the release notes for this explaining why it happens and how to fix it. I think we need to keep guaranteeing only one version of hosts in a cluster and if we want to add a new host we can not ignore the hosts OS and this method is not going to work.  Do you agree?

**Pull request merged**
