### PR TITLE
CLOUDSTACK-7151: Support multiple physical networks at cluster level for guest traffic over VMware deployments.

### PR DESCRIPTION
**Pull request by sureshanaparti**
CLOUDSTACK-7151: Support multiple physical networks at cluster level for guest traffic over VMware deployments. Changes done =>

1. API Changes: 
- addCluster and updateCluster - new optional parameter physicalnetworktrafficlabels added
- listClusters - new optional parameter showtrafficlabelinfo to show the cluster override traffic details. This is required to support the GUI.

2. VMware resource changes
3. Database and Upgrade changes
4. UI changes

Currently, in cloudstack, the support for cluster level override settings (introduced in 4.2.0 with VMware DVS Integration) for guest and public traffic types blocks support for multiple physical networks defined in the zone for these traffic types over VMware deployments. It is required to support multiple physical networks defined in the zone for these traffic types at zone and cluster level(when defined) without impacting existing cluster level override settings. This would also fix the issue CLOUDSTACK-7151 - vmware: Type of vSwitch was not detected correctly while preparing public/guest virtual networks.

Also, renaming of vSwitch name for guest and public traffic type overridden at cluster in current cloudstack deployment has become troublesome, requiring manual update to database. This need to be addressed such that admin would be able to seamlessly re-name vSwitch name at cluster in Cloudstack whenever required, even in production cloud.

Design change for existing cluster level traffic override settings. FS/Design details: https://cwiki.apache.org/confluence/display/CLOUDSTACK/Support+multiple+physical+networks+at+cluster+level+for+guest+traffic+over+VMware+deployments

### CODE REVIEW

**Comment by sureshanaparti** [comment]
Tested database upgrade and updated API cmds addcluster and updatecluster to support multiple physical networks at cluster level.

**Comment by rhtyd** [comment]
@sureshanaparti please rebase against latest master, squash your commits into one and push -f, update on status of your PR

tag:vmware-pickup

**Comment by sateesh-chodapuneedi** [comment]
@sureshanaparti Can you please resolve the conflicts and rebase? I am looking forward to review this.

**Comment by sureshanaparti** [comment]
@sateesh-chodapuneedi Rebased with latest master. Please review.

**Comment by sureshanaparti** [comment]
@borisstoyanov Can you please kickoff VMware trillian tests on this PR.

**Comment by borisstoyanov** [comment]
@sureshanaparti could you please resolve the merge conflicts first and I'll build/test it.

**Comment by sureshanaparti** [comment]
@borisstoyanov Resolved the merge conflicts. Please run the tests. Thanks.

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
@borisstoyanov Can you kick off tests on VMware env as this PR changes are particular to VMware.

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test centos7 vmware-55u3

**Comment by sureshanaparti** [comment]
Above intermitten failures are not related to this PR code changes.

**Comment by wido** [comment]
This Pull Requests just got the label 'closable' for not seeing any activity for a long period.

The CloudStack project is in a transition from the Apache Foundation's Git infrastructure to Github. This has created a very large backlog of PRs. A lot of them don't merge anymore and didn't get attention.

To filter these PRs we are adding the tag closable to them to make a distinction between PRs which need our attention and which are a candidate to be closed.

It's not our intention to say that we don't value the PR, but it's a way to get a overview of which PRs need our resources and attention.

If you think closing this PR is a mistake, please add a comment and let us know! If you do that, could you please make sure that the PR merges against the branch it was submitted against?

Thank you very much for your understanding and cooperation!

**Comment by DaanHoogland** [comment]
@sureshanaparti closing, please rebase and re-open if still relevant

**Pull request closed without merging**
