### PR TITLE
Set version 4.7.1-SNAPSHOT in 4.7 branch

### PR DESCRIPTION
**Pull request by remibergsma**
- setnextversion.sh
- upgrade path

Build succeeds:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10:04 min
[INFO] Finished at: 2015-12-21T20:37:29+01:00
[INFO] Final Memory: 126M/1635M
[INFO] ------------------------------------------------------------------------
```

### CODE REVIEW

**Comment by remibergsma** [comment]
Tested an upgrade from `4.7.0` to `4.7.1` and that works:

```
INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) DB version = 4.7.0 Code Version = 4.7.1-SNAPSHOT
INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Database upgrade must be performed from 4.7.0 to 4.7.1-SNAPSHOT
INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Cleaning upgrades because all management server are now at the same version
INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Cleanup upgrade Upgrade470to471 to upgrade from 4.7.0-4.7.1 to 4.7.1
INFO  [o.a.c.s.l.CloudStackExtendedLifeCycle] (main:null) (logid:) Configuring CloudStack Components
```

Ping @DaanHoogland @wilderrodrigues to review.

**Comment by remibergsma** [comment]
@DaanHoogland Jenkins failed, seems not related to PR. Is this y our experiment?
```
FATAL: Unable to find coverage results
java.io.IOException: remote file operation failed: /home/jenkins/jenkins-slave/workspace/cloudstack-pr-analysis at hudson.remoting.Channel@175e0556:ubuntu3: java.io.IOException: /home/jenkins/jenkins-slave/workspace/cloudstack-pr-analysis/.travis.yml is not an XML file, please check your report pattern
```

**Comment by remibergsma** [comment]
Once this is merged (and fwd-merged to master, I will create the upgrade paths for `4.8`.

**Comment by borisroman** [comment]
LGTM :+1: 

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5:27.676s (Wall Clock)
[INFO] Finished at: Mon Dec 21 21:37:53 CET 2015
[INFO] Final Memory: 98M/808M
[INFO] ------------------------------------------------------------------------
```
```
INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) DB version = 4.7.0 Code Version = 4.7.1-SNAPSHOT
INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Database upgrade must be performed from 4.7.0 to 4.7.1-SNAPSHOT
INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Cleaning upgrades because all management server are now at the same version
INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Cleanup upgrade Upgrade470to471 to upgrade from 4.7.0-4.7.1 to 4.7.1
INFO  [o.a.c.s.l.CloudStackExtendedLifeCycle] (main:null) (logid:) Configuring CloudStack Components
```

**Comment by pdube** [comment]
Nothing out of the ordinairy. LGTM

**Comment by pdion891** [comment]
LGTM

**Pull request merged**
