### PR TITLE
list VMs by displayname instead of name

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR addresses https://github.com/apache/cloudstack/issues/4654#issuecomment-1889174291 TBD

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

#### How did you try to break this feature and the system with this change?

in qa

### CODE REVIEW

**Comment by weizhouapache** [comment]
@DaanHoogland 
both ?

**Comment by DaanHoogland** [comment]
Or not, to be discussed

**Comment by DaanHoogland** [comment]
@blueorangutan ui

**Comment by sureshanaparti** [comment]
@blueorangutan ui

**Comment by shwstppr** [comment]
@blueorangutan ui

**Review by vishesh92 — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@blueorangutan ui

**Comment by rohityadavcloud** [comment]
As far as I know that weren't regressions; As part of https://github.com/apache/cloudstack/pull/7833 since the display and name are the same for most users, having two redundant columns - so one of the two were removed as part of polish idea on #7833: `Standardise most resources to show state/status columns right after resource name (wherever applicable)` and `Remove displayname column in VM list view, add cpu number and memory by default`

**Review by rohityadavcloud — COMMENTED** [review]
I actually prefer name to display name; but I've no objection if everybody agrees with the changes.

**Comment by DaanHoogland** [comment]
@andrijapanicsb can you give your uncensored input on this?

**Comment by DaanHoogland** [comment]
ping @andrijapanicsb

**Comment by andrijapanicsb** [comment]
I did RTFM the whole thing, and the original issue/comments.

LGTM - I think redundancy makes no sense (having both fields), especially since VMs created by UI have identical values for both.

**Review by andrijapanicsb — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@blueorangutan ui

**Comment by kiranchavala** [comment]
@blueorangutan ui

**Review by kiranchavala — APPROVED** [review]
LGTM, name is changed to displayname


Before 

displayname-before

displayname-before2

After 


displayname

Screenshot 2024-06-12 at 6 24 45 PM

**Review by GaOrtiga — APPROVED** [review]

**Comment by DaanHoogland** [comment]
display name is filled with name is not provides as far as I know, I'll check the code.

**Comment by DaanHoogland** [comment]
> @DaanHoogland is name used for instances when displayname may be empty or not returned by the API? (or perhaps is it handled by the backend API?)

I see no mitigation of this possibility in a generic execution branch. The only path I encounter is 
```
        if (displayName == null) {
            displayName = vm.getDisplayName();
        }
```

So I created a PR to deal with it : #9719  . I think this is not necessary as I have never seen an empty displayname before, but better safe than sorry ;)

**Pull request merged**
