### PR TITLE
UI: Keyboard shortcuts

### PR DESCRIPTION
**Pull request by apurv-1**
### Description
Issue #4798 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### Screenshots (if appropriate):

Screenshot (174)

### CODE REVIEW

**Comment by apurv-1** [comment]
This is just an initial version for the keyboard shortcuts, Is it good to have a Modal like this to have quick look at the shortcut keys?
Also, I'm sceptical about the position of the `Keyboard Shortcut [F6]` button.

**Comment by DaanHoogland** [comment]
code and functionality look promising, your commit list not so much ;) any idea what happened there @apurv-1 ?

**Comment by apurv-1** [comment]
@DaanHoogland it was multiple attempts to fetch the upstream main branch! 😅

**Comment by DaanHoogland** [comment]
> @DaanHoogland it was multiple attempts to fetch the upstream main branch! sweat_smile

ok @apurv-1 , maybe rebase and force push. Let us know if you want review. I never give drafts much attention unless I'm involved.

**Comment by apurv-1** [comment]
> > @DaanHoogland it was multiple attempts to fetch the upstream main branch! sweat_smile
> 
> ok @apurv-1 , maybe rebase and force push. Let us know if you want review. I never give drafts much attention unless I'm involved.

Actually, I was working on the same keyboard shortcuts but now the idea is to show the labels like it's on Vimium. So, I made another branch for the same, I'll ping you once it is ready. Thankyou :)

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Pull request closed without merging**
