### PR TITLE
CLOUDSTACK-8304: disable snapshots from non-snapshot repositories

### PR DESCRIPTION
**Pull request by K0zka**
Signed-off-by: Laszlo Hornyak <laszlo.hornyak@gmail.com>

### CODE REVIEW

**Comment by bhaisaab** [comment]
LGTM. @K0zka please merge it on both master and 4.5!

**Comment by karuturi** [comment]
I dont think this fixes the issue. we are specifying a version number. maven will not check for snapshots.

**Comment by bhaisaab** [comment]
Not a maven expert, leaving for someone to review/merge who is.

**Comment by K0zka** [comment]
@karuturi So the problem that it adresses is this:  We have SNAPSHOT dependencies, since snapshots are not disabled on those repositories, they will be checked. Now the problem is that if one of those servers is not available, that is breaking the build.

**Comment by karuturi** [comment]
understood. This will definitely save build time. (will do the merge in sometime)
But, the build will fail irrespective of whether snapshot is enabled right? if the server goes offline, we will not get the dependency jar as well(in this case libvirt).

**Comment by K0zka** [comment]
@karuturi Correct, if you do not have the libvirt jar and libvirt.org goes down, the build will still fail. It would be nice if we could use only the central repository, but that will need some work with the ceph and libvirt team.

**Pull request closed without merging**
