### PR TITLE
kvm: support qemu-system-x86>=5.2

### LINKED ISSUE #5350: Drop Agent dependency on qemu-kvm for Ubuntu
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
Agent, Core
~~~

##### CLOUDSTACK VERSION

~~~
4.16.0-Snapshot
~~~

##### CONFIGURATION

Built the latest qemu version from source

##### OS / ENVIRONMENT

Ubuntu 20.04 and newer

##### SUMMARY

CS Agent requires `qemu-kvm` installation. However, newer versions of `qemu` have dropped dependency on `qemu-kvm` in favor of `qemu-system-x86`. 

If I build and install the latest `qemu` from source, I'm unable to install the CloudStack Agent due to  its dependency on `qemu-kvm`, which was dropped in recent releases of `qemu`.

Thus, I can't use the latest release of `qemu`, since trying to `apt install -y qemu-kvm` yields in the following error :
```
bku@ttx0:~/work/qemu/build$ sudo apt install -y qemu-kvm
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'qemu-system-x86' instead of 'qemu-kvm'
qemu-system-x86 is already the newest version (1:5.2+dfsg-9ubuntu3.1).
qemu-system-x86 set to manually installed.
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 cloudstack-agent : Depends: qemu-kvm (>= 2.5)
                    Depends: ebtables but it is not going to be installed
                    Depends: vlan but it is not going to be installed
                    Depends: ipset but it is not going to be installed
                    Depends: python3-libvirt but it is not going to be installed
                    Depends: ethtool but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

```

##### STEPS TO REPRODUCE

~~~
1. Clone qemu repository
2. Build and install qemu from master
3. Install a stock libvirt for Ubuntu
3. Validate qemu and virsh installation: `qemu-img --version` , `libvirtd --version`
4. Try to install CloudStack Agent on the node
5. Observe error installing the CS agent
~~~

##### EXPECTED RESULTS

~~~
Agent works with the latest qemu and libvirt
~~~

##### ACTUAL RESULTS

~~~
Fail to install CS Agent  on the node with the latest `qemu` is installed
~~~

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #5350 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Review by sureshanaparti — APPROVED** [review]
LGTM

**Review by DaanHoogland — APPROVED** [review]
lgtm, how does this relate to the qemu-kvm-ev package? can/should we include that as well as a acceptable dependency?

**Comment by weizhouapache** [comment]
> lgtm, how does this relate to the qemu-kvm-ev package? can/should we include that as well as a acceptable dependency?

@DaanHoogland 
debian/control has only impact on Debian-based systems, e.g. Ubuntu, Debian.

I have not tested Ubuntu 21.04 (which has qemu-system-x86 but does not have qemu-kvm) . Without this PR, cloudstack-agent cannot be installed.

**Comment by DaanHoogland** [comment]
> > lgtm, how does this relate to the qemu-kvm-ev package? can/should we include that as well as a acceptable dependency?
> 
> @DaanHoogland debian/control has only impact on Debian-based systems, e.g. Ubuntu, Debian.
> 
> I have not tested Ubuntu 21.04 (which has qemu-system-x86 but does not have qemu-kvm) . Without this PR, cloudstack-agent cannot be installed.

ok, so the qemu-kvm-ev discussion only applies to redhat varieties? tnx

**Comment by weizhouapache** [comment]
> > > lgtm, how does this relate to the qemu-kvm-ev package? can/should we include that as well as a acceptable dependency?
> > 
> > 
> > @DaanHoogland debian/control has only impact on Debian-based systems, e.g. Ubuntu, Debian.
> > I have not tested Ubuntu 21.04 (which has qemu-system-x86 but does not have qemu-kvm) . Without this PR, cloudstack-agent cannot be installed.
> 
> ok, so the qemu-kvm-ev discussion only applies to redhat varieties? tnx

@DaanHoogland exactly.

**Review by rohityadavcloud — APPROVED** [review]
LGTM - we'll need to maintain the arm build to have `qemu-system-arm` then.

**Comment by rohityadavcloud** [comment]
LGTM, checked packages.ubuntu.com - this will ensure qemu-system/x86 is installed on ubuntu 21.04 and later.

**Pull request merged**
