### PR TITLE
Sync precommit config from main

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR syncs the pre-commit config from main branch. As of now forward merging of 4.18 to main is causing lint checks to fail for main.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
clgtm, a lot of conflicts will arise in PRs (and some in merge forward ) but better than all the conflicts on merge forward per PR :|

**Comment by vishesh92** [comment]
List of files with conflicts while merging with main
image

**Comment by DaanHoogland** [comment]
@weizhouapache can you agree with this?

**Comment by weizhouapache** [comment]
> @weizhouapache can you agree with this?

@DaanHoogland 
yes, looks good

**Review by weizhouapache — APPROVED** [review]

**Review by harikrishna-patnala — APPROVED** [review]
code LGTM

**Pull request merged**
