### PR TITLE
[WIP] UI: Integrate Tungsten Fabric

### PR DESCRIPTION
**Pull request by utchoang**
### Description

This PR for adding new UI of Tungsten Fabric

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):
image
image

### CODE REVIEW

**Comment by weizhouapache** [comment]
@utchoang 
what's the status of this PR ? Is it ready for review and testing ?

**Comment by utchoang** [comment]
@weizhouapache This PR is not ready for review as it is related to PR https://github.com/apache/cloudstack/pull/4205 which needs to be completed first.

**Comment by DaanHoogland** [comment]
@utchoang (cc @weizhouapache @radu-stefanache ) does it make sense to merge these PRs? the TF PR contains reference to the phased out UI and needs this to be usefull to the layman.

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by kiwiflyer** [comment]
@utchoang Can you rebase and fix the conflicts?  

cc: @svenvogel

**Comment by nvazquez** [comment]
@kiwiflyer @utchoang I've fixed the conflicts and had to create a new PR to push the changes: #7166. Please feel free to close mine if you plan to continue working on this PR

**Pull request closed without merging**
