### PR TITLE
Copy on pool host when storage pool has ScopeType.HOST

### PR DESCRIPTION
**Pull request by rg9975**
### Description

This PR fixes an issue with storage volume migrations when a storage pool (source or destination) has ScopeType.HOST set.  Prior to this PR, the code in StorageSystemDataMotionStrategy selected any host in the cluster if the source storage pool did not have a cluster ID, or a host in the cluster if it did.  This effectively breaks ScopeType.HOST copies except when the selection resulted in the specific host the other storage pool resides on.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [X] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?
Performed copies between a local KVM storage pool and a FiberChannelAdapter storage pool.

### CODE REVIEW

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Review by shwstppr — APPROVED** [review]
Code LGTM

**Comment by rohityadavcloud** [comment]
@blueorangutan test matrix

**Comment by rohityadavcloud** [comment]
@blueorangutan test matrix

**Comment by sureshanaparti** [comment]
> [SF] Trillian test result (tid-10782) Environment: kvm-centos7 (x2), Advanced Networking with Mgmt server 7 Total time taken: 45887 seconds Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr9356-t10782-kvm-centos7.zip Smoke tests completed. 129 look OK, 3 have errors, 0 did not run Only failed and skipped tests results shown below:
> 
> Test	Result	Time (s)	Test File
> test_01_secure_vm_migration	`Error`	134.11	test_vm_life_cycle.py
> test_01_secure_vm_migration	`Error`	134.11	test_vm_life_cycle.py
> test_02_cancel_host_maintenace_with_migration_jobs	`Error`	239.15	test_host_maintenance.py
> test_hostha_kvm_host_fencing	`Error`	108.47	test_hostha_kvm.py

verified locally, there are intermittent. _test_01_secure_vm_migration_ fails during tear down of VM as router is in Starting start (and unable to update the rules).

**Pull request merged**
