### PR TITLE
Allow specifying disk size, min/max iops for offering linked with custom disk offering

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

This PR fixes the issue noticed when trying to scale a VM to an offering with custom disk offering. 
UI doesn't provide an option to pass the disk size & iops values
image

Post Fix:
image

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### CODE REVIEW

**Review by sureshanaparti — APPROVED** [review]
code LGTM

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan test

**Review by harikrishna-patnala — APPROVED** [review]

**Review by nvazquez — APPROVED** [review]
LGTM

**Pull request merged**
