### PR TITLE
CLOUDSTACK-10311 Agent Log Rotate variable replace bug

### PR DESCRIPTION
**Pull request by Slair1**
PR2094 made the log path a variable.  The cloudstack-agent was modified to use the @AGENTLOG@ variable entry, but the pom.xml file was not correct to do the replacement of the @AGENTLOG@.

Line 62 of the pom.xml handles the replacement with the rename in place

### CODE REVIEW

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by rafaelweingartner** [comment]
@Slair1 can you take a look into travis failures?

**Comment by Slair1** [comment]
Since this is the same as #2429, should we just back-merge that?

**Comment by rhtyd** [comment]
Can you check the build failures @Slair1 ? (See travis for details, or confirm you're able to build without failures?).

@blueorangutan package

**Comment by Slair1** [comment]
Travis errors look unrelated?

**Comment by rafaelweingartner** [comment]
Can you rebase? I have fixed a code that was causing travis errors.

**Comment by Slair1** [comment]
@rafaelweingartner sure, just did

**Comment by Slair1** [comment]
@rafaelweingartner still seeing some unrelated errors in the travis

**Comment by rafaelweingartner** [comment]
Hmmm, may I ask you why did you open the PR against 4.9?

**Comment by Slair1** [comment]
@rafaelweingartner as said in the other comments, there is already a PR that addresses this issue in future versions.  We are running 4.9.3 right now in our environment.

**Comment by rhtyd** [comment]
@Slair1 the changes are already in 4.11, master branches. By future version, do you expect the fix to be in a future 4.9.x version (likely 4.9.4.0)?

**Comment by Slair1** [comment]
@rafaelweingartner yep, i was hoping it would be included in 4.9.4.0

**Comment by Slair1** [comment]
@rafaelweingartner how do i increase the travis timeouts?

**Comment by rafaelweingartner** [comment]
Timeouts can be changed in `.travil.yml`.
Are we going to have a 4.9.4.0? The version 4.9 is EOL.

**Comment by Slair1** [comment]
@rafaelweingartner thanks for info on increasing the travis timeout. 

I guess i thought there would be a 4.9.4.0, there have been other PRs merged in 4.9 and the POMs for it have been updated to 4.9.4.0 it looks like at least.

**Comment by Slair1** [comment]
@rafaelweingartner sorry for the newbie question, but i updated the .travis.yml file and it now shows up in my commit, is that correct?

**Pull request merged**
