### PR TITLE
L10N update before 4.7.0 RC1

### PR DESCRIPTION
**Pull request by milamberspace**
Some sentences (mainly for the new quota plugin) needs to be translated before the 4.7.0 release candidate (planned for 14th december)
https://www.transifex.com/ke4qqq/CloudStack_UI/47xmessagesproperties/

Stats:
German (Germany)            100%
French (France)             100%
Portuguese (Brazil)          98%
Norwegian Bokmål (Norway)    98%
Dutch (Netherlands)          98%
Chinese (China)              97%
Japanese (Japan)             97%
Hungarian                    96%
(only languages over 90%)

Ping me after adding the L10N strings into transifex, I will update this PR.

Thanks

cc @remibergsma @agneya2001 @DaanHoogland @nvazquez @barunhalder1234 @K0zka

### CODE REVIEW

**Comment by terbolous** [comment]
ping @milamberspace Norwegian updated :-)

**Comment by agneya2001** [comment]
@milamberspace pt_BR updated.

**Comment by milamberspace** [comment]
Thanks @terbolous and @agneya2001 
The PR has been updated

**Comment by bhaisaab** [comment]
LGTM (just code review)

**Comment by bhaisaab** [comment]
@milamberspace squash them into one commit please, or logically split per lang translation

**Comment by milamberspace** [comment]
@bhaisaab squash done.

**Comment by DaanHoogland** [comment]
@milamberspace Dutch complemented

**Comment by milamberspace** [comment]
Thanks @DaanHoogland 
PR updated.

**Comment by borisroman** [comment]
@milamberspace @remibergsma @DaanHoogland LGTM :+1:

Only did code review.

**Comment by remibergsma** [comment]
@milamberspace Are we good to merge this?

**Comment by milamberspace** [comment]
@remibergsma Probably yes, no more update on Transifex since the Dutch. You can merge this just before the start of RC process. Thanks.

**Pull request merged**
