### PR TITLE
Jacoco: fix no coverage result in server and some other modules

### PR DESCRIPTION
**Pull request by weizhouapache**
According to https://www.eclemma.org/jacoco/trunk/doc/prepare-agent-mojo.html
we need to add "@{argLine}" to argLine if it exists in pom.xml

### Description

This PR fixes missing jacoco coverage report in some modules

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]

**Review by rohityadavcloud — APPROVED** [review]
Thanks for finding @weizhouapache, I think I had removed this on root pom.xml due to some historic reason (I forgot)

**Comment by rohityadavcloud** [comment]
@weizhouapache maybe worth checking local jacoco? I don't see any difference reported by sonarbot (not sure why codecov didn't kick in)

**Comment by weizhouapache** [comment]
> @weizhouapache maybe worth checking local jacoco? I don't see any difference reported by sonarbot (not sure why codecov didn't kick in)

@rohityadavcloud 
I have added this change to my PR for vm autoscaling

the following page shows coverage result of changes on java files in `server` module.
https://sonarcloud.io/component_measures?id=apache_cloudstack&pullRequest=6571&metric=new_coverage&view=list

**Comment by rohityadavcloud** [comment]
w00t @weizhouapache good find, and well done. I suspect, adding argLine on `server` alone would have addressed a lot of missed unit tests. @shwstppr I suppose we can merge this as this doesn't change the code essentially but how coverage is analysed and args used in the surefire plugin, but does that still require us to fix the powermock issue?

**Pull request merged**
