### PR TITLE
ui: Add guest IP ranges

### PR DESCRIPTION
**Pull request by utchoang**
### Description

Fixes https://github.com/apache/cloudstack/issues/4697

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### Screenshots (if appropriate):
image
image

### CODE REVIEW

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by rhtyd** [comment]
@blueorangutan ui

**Review by Pearl1594 — APPROVED** [review]
LGTM

**Comment by rhtyd** [comment]
@utchoang can you address:
- Fix the tab to be only shown for shared networks, it's showing for L2 as well (ex. http://qa.cloudstack.cloud:8080/client/pr/4716/#/guestnetwork/6463e120-c36a-4569-aaa7-729922a55825?tab=guest.ip.range)
- When we go to Infra -> zones -> phy network -> traffic type -> add router-link in the network name (for ex. http://qa.cloudstack.cloud:8080/client/pr/4716/#/physicalnetwork/d3249fba-8282-4ede-823c-2c1393bff05b?tab=traffic.types)

**Comment by utchoang** [comment]
@rhtyd In the traffic type tab, if guest network is a `Isolated | L2` then will not have router-link?
image

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by davidjumani** [comment]
@blueorangutan ui

**Review by DaanHoogland — APPROVED** [review]
clgtm and small monkeytest looks ok as well

**Comment by rhtyd** [comment]
LGTM tested the live URL

**Pull request merged**
