### PR TITLE
Metrics views for CloudStack UI

### PR DESCRIPTION
**Pull request by bhaisaab**
FS: https://cwiki.apache.org/confluence/display/CLOUDSTACK/Metrics+Views+for+CloudStack+UI
JIRA: https://issues.apache.org/jira/browse/CLOUDSTACK-9020

### CODE REVIEW

**Comment by bhaisaab** [comment]
For screenshots, please see the FS: https://cwiki.apache.org/confluence/display/CLOUDSTACK/Metrics+Views+for+CloudStack+UI

**Comment by DaanHoogland** [comment]
@bhaisaab the sprites seem not to have changed. Should the sprite.png be in this change?

**Comment by milamberspace** [comment]
selection_172
@DaanHoogland see the capture

**Comment by bhaisaab** [comment]
@DaanHoogland yes, the metrics view brings in new state icons that can be used in other places;
orange for alert, migrate etc. yellow for allocated, in transition etc. See metrics.js for state string to icon translations.

**Comment by DaanHoogland** [comment]
thanks guys, missed that. Should I do anything more then just run with this change? an option some where? I am not seeing the metrix bottun in the zone view.

**Comment by bhaisaab** [comment]
@DaanHoogland this is an admin only feature, just do a clean install and you should see this logged in as an admin

**Comment by DaanHoogland** [comment]
@bhaisaab haven't got it working yet. I am trying as admin.

**Comment by bhaisaab** [comment]
@DaanHoogland I build the branch today from scratch, it seems to be working for me; see the screenshot:

screenshot from 2015-11-07 12-58-34

**Comment by bhaisaab** [comment]
@wido I've included instance count on the host view page now
@NuxRo the container width has been increased by 200px now, no more horizontal scrolls and more wider space in general for all UI, and logos has 'cloudmonkey' now - booyah!

**Comment by NuxRo** [comment]
yeah baby!

**Comment by DaanHoogland** [comment]
@bhaisaab trying anew and still don't get the metrics button. I destroyed the vm on which the test cloud is running, checked out the pr 1038 as bracnh compiled and started it. I started Safari (not my default browser), deleted all history and opened the page.
screen shot 2015-11-08 at 11 05 09

I am now investigating the page source to see if I can recognise code from the pr in there.

**Comment by DaanHoogland** [comment]
The ui does not contain the metric button even hidden: 
screen shot 2015-11-08 at 11 19 04

I am sure I need some extra tweeking or an extra commit not in the PR.

**Comment by bhaisaab** [comment]
@DaanHoogland thanks for taking time to review this, on my system I'm still able to get the metrics button on Chrome/Firefox/Safari. Can you simply take the shapeblue:metrics-master repo/branch which is where the PR is created form, there is no hidden or missing commit. In the html source (of index.jsp being rendered) can you find metrics.js and metricsView.js included somewhere? Can you confirm if you're building and running mgmt server with mvn or testing using an rpm? It might be an environment issue, or browser caching issue or that your test branch is missing commits from the PR (something went wrong with applying the PR?)

See, I'm able to see the metrics button/views and note that UI is wider than before:
screen shot 2015-11-08 at 8 03 52 pm

screen shot 2015-11-08 at 8 05 27 pm

screen shot 2015-11-08 at 8 06 46 pm

Another place you can check is to go see if you see a viewMetrics codeblock in instances.js (or system.js, or storage.js) in scripts/, like this: (this code is like an API for rendering the metrics button, navigation, setting up view etc)

screen shot 2015-11-08 at 8 08 07 pm

Also, is anyone else able to reproduce the issue Daan is facing? cc @wido @wilderrodrigues @abhinandanprateek @NuxRo and others?

**Comment by DaanHoogland** [comment]
@bhaisaab I saw you added four new commits, so I'll restart the test in a minute.
I am running in a bubble which does a jetty run from mvn. (mvn -pl :cloud-client-ui jetty:run)
view page source does show metrics.js and metricsView.js!
I have tried chrome and safari with cleared cache and firefox with private browser window. As the pge source from the browser shows the scripts and the labels, I don't think it is a caching issue.

**Comment by bhaisaab** [comment]
@DaanHoogland thanks, the new commits are nothing but some squashed commits (found minor issues with sorting logic and another view/model issue). If this still does not work for you, share with me your OS/browser/java/maven versions. After you pull back, do a mvn clean install -pl client and then, mvn -pl client jetty:run.

**Comment by DaanHoogland** [comment]
@bhaisaab I am doing a fresh checkout (this time) to ensure no remnants of older code/tests is there. Update in a few...

**Comment by bhaisaab** [comment]
@DaanHoogland thanks, we can merge this once master is unfrozen and 4.6 branch is cut.

**Comment by remibergsma** [comment]
Nice logo @bhaisaab :-)
screen shot 2015-11-10 at 16 54 01

Deployed this to our employee cloud to give it a test drive.

**Comment by remibergsma** [comment]
I've run this for some time and it is really cool, thanks @bhaisaab LGTM

If you consider back porting this to 4.5.3, then I think we should also include it in 4.6.1, shouldn't we? Ping @karuturi.

In that case, can you make a PR against the 4.6 branch so we can merge it there and then fwd-merge it to master (so it will be in 4.7 and onwards as well).

**Comment by DaanHoogland** [comment]
@remibergsma this is a very cool *feature*. why do you suggest it be put in 4.6?

**Comment by remibergsma** [comment]
@DaanHoogland Because @bhaisaab wants it in 4.5.3. Otherwise people will upgrade from 4.5.3 to say 4.6.2 and lose a feature.

**Comment by DaanHoogland** [comment]
hm, this is breaking our policy hard. I have some things of Wei's laying around....

**Comment by NuxRo** [comment]
Right, so what now?
Can't we just postpone this till 6.7 and perhaps provide some easy patches in the meanwhile for whoever wants to use in 4.5 and 4.6?

--
Sent from the Delta quadrant using Borg technology!

Nux!
www.nux.ro

----- Original Message -----

**Comment by bhaisaab** [comment]
Guys can we get some +1s on this, so let's at least merge on master? cc @wilderrodrigues @DaanHoogland @NuxRo @wido @abhinandanprateek and others

@DaanHoogland I'm interested in getting some of the commits related to UI width, sorting of tables etc. on 4.5 (we can remove the metrics view related commits). The reasoning here is that this does not change existing mgmt server core code, nor the schema. It's UI changes that improve existing experience for users.

**Comment by NuxRo** [comment]
+1 to merge on master

**Comment by wido** [comment]
I would like to give a LGTM, but my JavaScript skills aren't that good.

The small Java changes look good to me.

**Comment by abhinandanprateek** [comment]
+1 have tried the feature and used bits of it in revamped quota UI.

**Comment by bhaisaab** [comment]
@remibergsma rebased again the branch against latest master, created PRs;
4.6: #1090 
4.5: #1091

**Comment by karuturi** [comment]
Hi @bhaisaab 
you should create PRs for (4.5 and 4.6) OR (master). Not for all the branches. 
Based on the discussion and votes above I think the decision was to include in master only(4.7). So the PRs for other branches(4.5 and 4.6) are not necessary.

**Comment by bhaisaab** [comment]
@karuturi Remi asked for a 4.6 based PR. Given some votes and if we don't have an objections should I go ahead and merge on master?

**Comment by remibergsma** [comment]
@bhaisaab I'm OK with merging this to master now, but that will also mean it will not end up in 4.6. I think @DaanHoogland already said that no new features should go into 4.6 (as we agreed before) so merging to master is fine with me. I like your idea about porting back some of the patches to 4.5 and 4.6 to make the UI wider and such.

I asked for 4.6 version because I thought we wanted to back port all of the metrics thing to 4.5 and then I find it weird to not have it in 4.6. But let's stick to what we said, let's merge it to master and move on.

It is a great feature!

All agree to merge on master and back port only some of the UI tweaks?

**Comment by borisroman** [comment]
@remibergsma Agree.

**Comment by bhaisaab** [comment]
@remibergsma alright, merging on master now. If there is no objection, I would like to merge this on 4.5 as whole, if that's not acceptable at least the other useful commits minus the metrics features. Comments?

**Comment by serverchief** [comment]
+1, please merge

**Comment by serverchief** [comment]
The metrics UI is not really a major feature in my opinion. We are not changing the core and any apis.

All we are doing is re-presenting already presented data in UI in slightly different and much better manner. 

I've tried it extensively in fairly large environments on back ported 4.5, i can attest it works as expected.

It would certainly help the project and new folks trying out ACS. I'm supporting the back port into 4.6 - as i'd consider this UI enhancement and not new major feature..

**Pull request merged**
