### PR TITLE
List service offerings without host tags when filtering VM

### PR DESCRIPTION
**Pull request by GutoVeronezi**
### Description

When one is using API  [listServiceOfferings](https://cloudstack.apache.org/api/apidocs-4.16/apis/listServiceOfferings.html) passing the parameter `virtualmachineid` (like when scaling up a VM via UI), only the available offerings for the VM are listed. If the current VM's offering has host tags, only offerings with compatible host tags are listed. Offerings that do not have host tags can be used in any host; therefore, independent of the host tags of the current VM's offering, they also should be available for the VM.

This PR intends to change  API listServiceOfferings to also list offerings without host tags when filtering the VM.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

### How Has This Been Tested?

It was tested in a local lab.

I created 3 compute offerings:
1. Host tags: `t1`;
2. Host tags: `t2`;
3. Host tags: without tags;

I created a VM with the first offering. Before the changes, listServiceOfferings only listed the first offering. After the changes, listServiceOfferings listed the third offering too.

### CODE REVIEW

**Comment by GutoVeronezi** [comment]
Could anyone review this one?

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-67u3

**Review by JoaoJandre — APPROVED** [review]
CLGTM

**Pull request merged**
