### PR TITLE
[4.9] Backported fixes for 4.9.3.0 release effort

### PR DESCRIPTION
**Pull request by rhtyd**
This would backport some critical bugfixes and improvements in 4.9 that were merged on master/4.10. This is based on some regressions seen in the 4.9 health check run #1837

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by karuturi** [comment]
this would make fwd merging complex. We shouldn't be doing this.

**Comment by rhtyd** [comment]
@karuturi fwd merging won't be complex, when merging we can choose ours vs theirs strategy to make sure fwd-merging does not cause conflicts etc. Some blockers/fixes are much needed.

**Comment by remibergsma** [comment]
I thought we weren't doing backports any more? https://cwiki.apache.org/confluence/display/CLOUDSTACK/Release+principles+for+Apache+CloudStack+4.6+and+up

**Comment by rhtyd** [comment]
@remibergsma we've discussed this on ML before. For more information, see: https://cwiki.apache.org/confluence/display/CLOUDSTACK/LTS

4.9 is a LTS branch and LTS branch will receive blocker/critical/major fixes. If there are any objections on a particular commit/patch being backported, we can discuss and remove them.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
Test results look okay to me, however most errors on XenServer are related to r/vpc based tests and may be ignored.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
KVM and VMware tests look OK. Waiting for XenServer results.

**Comment by rhtyd** [comment]
Re: XenServer test results:
The VPC related test failures for Xenserver are known intermittent failures and ignore-able.
The `test_nic` failed due to ` errortext : u'Unable to start a VM due to insufficient capacity'}` and is ignorable env issue.
The `test_network` failed due to `Resource [Host:2] is unreachable: Host 2: Unable to start instance due to Unable to start  VM:7565a8fc-2131-4984-add7-3f288d05ee27 due to error in finalizeStart, not retrying'`. 

With this, I don't see any blocker issue. I'll proceed with merging these backported changes and work towards fixing any issues/tests, and with option to revert any of the changes. The branch will be fwd-merged using `-X ours` strategy so there will be no changes/issues in 4.10/master branches.

**Pull request merged**
