### PR TITLE
Retrieve only resource count on user dashboard

### PR DESCRIPTION
**Pull request by GutoVeronezi**
### Description

The user's dashboard presents the user's amount of running VMs, stopped VMs, total VMs, volumes, networks, and public IP addresses. The APIs `listVirtualMachines`, `listVolumes`, `listNetworks`, and `listPublicIpAddresses` process and return the whole data, which can be slow when dealing with a great number of resources. However, for the user's dashboard context, we just need the count of resources.

This PR intends to create a new parameter (`retrieveonlyresourcecount`) in those APIs to skip the data processing and return only the resource count.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

### How Has This Been Tested?

I created several VMs in my environment, logged in with a domain admin, and observed how much time the dashboard was taking to completely load. Before the changes, it was taking more than 30 seconds to load and the time would increase according to the amount of resources:

before

image

With the changes it is taking around 2 seconds to completely load:

after

image

### CODE REVIEW

**Comment by GutoVeronezi** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@GutoVeronezi 
Is it better to create a separate API to list all resource counts ?

**Comment by GutoVeronezi** [comment]
> @GutoVeronezi Is it better to create a separate API to list all resource counts ?

@weizhouapache, as the APIs we have today already return the data we need; we would just need to improve the processes [with the new parameter]. Therefore, I believe there is no need for a new API [to maintain] that would do the same function as the others.

**Comment by weizhouapache** [comment]
> > @GutoVeronezi Is it better to create a separate API to list all resource counts ?
> 
> @weizhouapache, as the APIs we have today already return the data we need; we would just need to improve the processes [with the new parameter]. Therefore, I believe there is no need for a new API [to maintain] that would do the same function as the others.

@GutoVeronezi 
I think it is better to get all resource counts/limitations by a single API call, not multiple api calls as you can see on the UI source code. You can refer to
https://cloudstack.apache.org/api/apidocs-4.18/apis/listInfrastructure.html
https://cloudstack.apache.org/api/apidocs-4.18/apis/listZonesMetrics.html

**Comment by GutoVeronezi** [comment]
@weizhouapache, creating an API to return a handful of resource counts will limit the users to the data we (the developers) define the API to return; for new use cases, we would have to extend the API to return a new resource count, which makes it a limited approach. 

On the other hand, creating the proposed parameter in those APIs will give users the flexibility to combine the API parameters the way they want. The user's dashboard is just an example of where we can use the parameter; however, we have to remember that users can and will consume the APIs in different ways. Therefore, with that in addition to my initial point, I believe that the parameter creation in this scenario is a better approach rather than creating an API, as it brings flexibility for the users.

**Comment by weizhouapache** [comment]
@GutoVeronezi 
I think an API is better. 

back to your pr, I think it would be better to create an abstract class .

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test keepEnv

**Review by JoaoJandre — APPROVED** [review]
LGTM, tested manually.

**Review by BryanMLima — APPROVED** [review]
CLGTM

**Review by DaanHoogland — APPROVED** [review]
clgtm+ small monkeytest

**Comment by DaanHoogland** [comment]
@weizhouapache are your concerns addressed?

**Comment by GutoVeronezi** [comment]
ping @weizhouapache

**Comment by GutoVeronezi** [comment]
Errors in https://github.com/apache/cloudstack/actions/runs/5249960611/jobs/9861114168?pr=7617 does not seem related to this PR; merging this one based on the package results, test results and approval.

**Comment by rohityadavcloud** [comment]
Sorry I'm late to the discussion, this PR wasn't really needed. The information we need is largely in the listAccounts API, which is then used to display the account usage/quota/limits. For ex, see: https://qa.cloudstack.cloud/simulator/#/account/36b4c0a4-b339-40f0-9991-b17282a686a9?tab=resources

A single API call would also save from calling too many API calls for the user/project dashboard. I think we can optimise things in future with this approach.

**Comment by GutoVeronezi** [comment]
@rohityadavcloud, `listAccounts` returns only the resources belonging to the account, which produces a different result than the expected: resources that the account has access to.

Anyways, the PR is not limited to the dashboard case, as I pointed in https://github.com/apache/cloudstack/pull/7617#issuecomment-1586403372, and still is a valid use case that adds to ACS. Also, the PR complied with the community requirements (approval and test passing); therefore, the opinion of a specific person is not mandatory.

**Pull request merged**
