### PR TITLE
Fix error message for checkVolume command

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR fixes the error message shown when the `checkVolume` command fails.
Before:
```json
{
  "accountid": "f7a7493c-ecd7-11ee-a883-1e00a700045b",
  "cmd": "org.apache.cloudstack.api.command.user.volume.CheckAndRepairVolumeCmd",
  "completed": "2024-03-28T10:34:49+0000",
  "created": "2024-03-28T10:34:47+0000",
  "jobid": "6f452658-b61d-4983-9528-87fd4b2f9f29",
  "jobinstanceid": "2090adf0-5889-4299-95ea-e104074d9e9a",
  "jobinstancetype": "Volume",
  "jobprocstatus": 0,
  "jobresult": {
    "errorcode": 530,
    "errortext": "Unexpected exception"
  },
  "jobresultcode": 530,
  "jobresulttype": "object",
  "jobstatus": 2,
  "userid": "f7a84e5a-ecd7-11ee-a883-1e00a700045b"
}
```

After:
```json
{
  "accountid": "f7a7493c-ecd7-11ee-a883-1e00a700045b",
  "cmd": "org.apache.cloudstack.api.command.user.volume.CheckAndRepairVolumeCmd",
  "completed": "2024-03-28T10:34:49+0000",
  "created": "2024-03-28T10:34:47+0000",
  "jobid": "6f452658-b61d-4983-9528-87fd4b2f9f29",
  "jobinstanceid": "2090adf0-5889-4299-95ea-e104074d9e9a",
  "jobinstancetype": "Volume",
  "jobprocstatus": 0,
  "jobresult": {
    "errorcode": 530,
    "errortext": "Unexpected exception: Unable to find Up hosts to run the check volume command"
  },
  "jobresultcode": 530,
  "jobresulttype": "object",
  "jobstatus": 2,
  "userid": "f7a84e5a-ecd7-11ee-a883-1e00a700045b"
}
```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

### How Has This Been Tested?
1. Disable all hosts
2. Run `checkVolume` command on a volume

### CODE REVIEW

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test alma9 kvm-alma9

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by vishesh92** [comment]
@blueorangutan test alma9 kvm-alma9

**Review by sureshanaparti — APPROVED** [review]
code lgtm

**Review by borisstoyanov — APPROVED** [review]
Manually checked, that whenever there is no suitable host to carry out the check the proper error message appears.

**Pull request merged**
