### PR TITLE
[4.6] CLOUDSTACK-9020: UI enhancements from metrics view

### PR DESCRIPTION
**Pull request by bhaisaab**
- Sortable columns
- Logos with cloudmonkey
- Wider UI
- CSS fixes and new status icons
- Configurable UI list api requests page size
- IP address column on instances page
- Listview widget enhancements

cc @remibergsma @karuturi

### CODE REVIEW

**Comment by remibergsma** [comment]
Thanks @bhaisaab will test soon.

**Comment by karuturi** [comment]
verified on 4.6.. working fine..
screen shot 2015-11-26 at 5 59 33 pm

:+1:

**Comment by karuturi** [comment]
I think #1119 can be closed as this PR will be fwd-merged

**Comment by bhaisaab** [comment]
Thanks @karuturi will close once this is merged, and 4.6 is fwd-merged.

**Comment by bhaisaab** [comment]
ping @remibergsma

**Comment by remibergsma** [comment]
LGTM, works fine and I was able to sort columns (example global settings).

screen shot 2015-11-28 at 13 04 27 pm

Be careful when merging to 4.6: we should first do a fwd-merge from 4.6 to master and then merge this PR to master, then do another fwd-merge. This one will get some conflicts, which we may want to address in a PR. Do you have time to help with this @karuturi ?

**Comment by remibergsma** [comment]
@bhaisaab had a busy week, so took a little longer ;-)

**Comment by bhaisaab** [comment]
Thanks @remibergsma  :)

**Pull request merged**
