### PR TITLE
Fix Quota plugin state on QuotaSummaryResponse

### PR DESCRIPTION
**Pull request by BryanMLima**
### Description

This PR aims to fix a feature introduced in PR[#6690](https://github.com/apache/cloudstack/pull/6690). It was added the parameter `quotaenabled` to the response of the Quota Summary  API. However, this parameter was not set, and thus, always returned false. This PR fix this behavior, returning the correct value according to the configuration value.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### How Has This Been Tested?
This was tested in a local lab with user `dom01`  with the Quota plugin enabled and with user `dom02` with the plugin disabled. The image below presents the correct behavior for Quota summary response.

image

### CODE REVIEW

**Comment by BryanMLima** [comment]
Hey @DaanHoogland, this is the one line PR fix mentioned in the mailing list.

**Comment by DaanHoogland** [comment]
Looks trivial @BryanMLima . Is this covered by an existing test? Or can we add a trivial test or assert somewhere?

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
Didn't check/test this, but clgtm

**Comment by DaanHoogland** [comment]
@BryanMLima , I'd love to add this but at this stage I really want some prove included

> Looks trivial @BryanMLima . Is this covered by an existing test? Or can we add a trivial test or assert somewhere?

**Comment by BryanMLima** [comment]
> @BryanMLima , I'd love to add this but at this stage I really want some prove included
> 
> > Looks trivial @BryanMLima . Is this covered by an existing test? Or can we add a trivial test or assert somewhere?

Sorry for the delay, I am taking a look in to this. I will probably add a integration test in `test_quota.py`.

**Comment by DaanHoogland** [comment]
> > @BryanMLima , I'd love to add this but at this stage I really want some prove included
> > > Looks trivial @BryanMLima . Is this covered by an existing test? Or can we add a trivial test or assert somewhere?
> 
> Sorry for the delay, I am taking a look in to this. I will probably add a integration test in `test_quota.py`.

seems like overkill for this @BryanMLima . As only a response field is added it would suffice to assert its presence in an existing test.

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Pull request merged**
