### PR TITLE
README: that time of the year! :christmas_tree:

### PR DESCRIPTION
**Pull request by rohityadavcloud**
Screenshot for changes:
Screenshot 2022-12-13 at 5 27 11 PM

Hope this can be merged without packaging or smoketests before end of the year ;)

To all of the CloudStack contributors - Happy Christmas and holidays!
/cc alphabetically-ish @alexandremattioli @andrijapanicsb @borisstoyanov @BryanMLima @chiradeep @csquire @DaanHoogland @davidjumani @DK101010 @Damans227 @GabrielBrascher @gsirett @GutoVeronezi @harikrishna-patnala @jbampton @JoaoJandre @kiwiflyer @kishankavala @mlsorensen @msinhore @nathanejohnson @NuxRo @nvazquez @Pearl1594 @pdion891 @rahulbcn27 @ravening @radu-todirica @rp- @SadiJr @shwstppr @slavkap @soreana @steveroles @SadiJr @sureshanaparti @svenvogel @swill @syed @utchoang @vladimirpetrov @weizhouapache @wido @alexandru-bagu @kricud @edikevich @xuanyuanaosheng @tampler @div8cn and so many others! (may have missed quite a few - you're all in my thoughts)

### CODE REVIEW

**Comment by msinhore** [comment]
LGTM! Merry Christmas and Happy New Year all!

**Review by weizhouapache — APPROVED** [review]
Merry xmas and happy new year !

**Review by vladimirpetrov — APPROVED** [review]
Happy holidays everyone!

**Comment by soreana** [comment]
Merry Christmas everyone. Hope you all log4j bug free holidays :-)

**Review by nvazquez — APPROVED** [review]
Merry Christmas and Happy New Year everyone! 🎅🏼 🎁 🎉 💪🏼

**Comment by gsirett** [comment]
A very Happy Christmas and a peaceful New Year everybody

**Review by slavkap — APPROVED** [review]
Happy holidays, everyone! :) 
LGTM

**Review by stephankruggg — APPROVED** [review]
Merry Christmas!!

**Comment by andrijapanicsb** [comment]
+1
Merry Christmas and a Happy New Year all :)

**Comment by rahulbcn27** [comment]
+1

Merry Christmas !!

**Review by jbampton — APPROVED** [review]
Happy Christmas and a Merry New Year !!

**Review by DaanHoogland — APPROVED** [review]

**Review by DaanHoogland — CHANGES_REQUESTED** [review]
I mean, good ending and a happy new year! Grinch

**Review by JoaoJandre — APPROVED** [review]
Merry Christmas and happy New Year :D

**Pull request merged**
