### PR TITLE
CLOUDSTACK-9720: [VMware] template_spool_ref table is not getting updated with correct template physical size in template_size column.

### PR DESCRIPTION
**Pull request by sureshanaparti**
Updated the template_spool_ref table with the correct template (VMware - OVA file) size.

### CODE REVIEW

**Comment by sureshanaparti** [comment]
Validated that the template_size is getting updated correctly in template_spool_ref table.
Prior to the fix, the size was logged as 0 =>
mysql> select id,template_id,template_size from template_spool_ref;
---------------------------------
id	template_id	template_size
---------------------------------
1	8	0
2	202	0
3	7	0
7	8	0
10	8	0
15	8	0
23	202	0
25	202	0
---------------------------------

After the fix correct size is getting updated=>
mysql> select id,template_id,template_size from template_spool_ref;
---------------------------------
id	template_id	template_size
---------------------------------
1	8	2621440000
2	202	3145728000
3	7	2147483648
---------------------------------
3 rows in set (0.00 sec)

**Comment by karuturi** [comment]
@blueorangutan package

**Comment by sateesh-chodapuneedi** [comment]
@sureshanaparti Travis tests ended with timeout. Can you please try force push?
```The job exceeded the maximum time limit for jobs, and has been terminated.```

**Comment by karuturi** [comment]
@blueorangutan test centos7 vmware-55u3

**Comment by sureshanaparti** [comment]
@rhtyd Can you run VMware CI on this PR.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-55u3

**Comment by sureshanaparti** [comment]
@rhtyd Can you please kick off the tests again.

**Comment by sateesh-chodapuneedi** [comment]
LGTM for code changes.

**Comment by harikrishna-patnala** [comment]
LGTM for the code changes.

**Comment by sureshanaparti** [comment]
@borisstoyanov @rhtyd Can you please run VMware tests of this PR.

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test centos7 vmware-55u3

**Comment by sureshanaparti** [comment]
The above tests failure are not related to this PR. These are failing most for the other PRs.

**Pull request merged**
