### PR TITLE
Ubuntu 20.04: restart libvirtd instead of libvirt-bin

### PR DESCRIPTION
**Pull request by ustcweizhou**
## Description

libvirt-bin does not exist any more in Ubuntu 20.04, restart libvirtd instead of libvirt-bin after configuration when add a host.

in summary:
ubuntu 16.04: libvirt-bin
ubuntu 18.04: libvirt-bin and libvirtd (they are same)
ubuntu 20.04: libvirtd

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Review by rhtyd — APPROVED** [review]

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
Changes LGTM
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Review by davidjumani — APPROVED** [review]
LGTM!

**Comment by Pearl1594** [comment]
@blueorangutan pacakge

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Manually kicked smoketests against Ubuntu 18.04 (mgmt server + kvm host)

**Comment by rhtyd** [comment]
Verified manually lgtm

**Pull request merged**
