### PR TITLE
usage backup: Raw usage/usage display to record time duration of usage

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

This PR ensure consistency between usage details stored across different resource types. For the sake of consistency, backup usage record will show the time duration of backup usage in the raw_usage / usage_display fields.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@Pearl1594 does this pr fix #4982 ? is it ready for review ?

@nvazquez

**Comment by nvazquez** [comment]
Hi @Pearl1594, @weizhouapache has created PR #5259 to fix #4982, can you please sync to work on a unified solution?

**Comment by Pearl1594** [comment]
Will do @nvazquez @weizhouapache - Thanks.

**Comment by nvazquez** [comment]
Hi @Pearl1594 any update on this? Can both PRs be integrated into a single one to fix the issue #4982?

**Comment by Pearl1594** [comment]
Hi @nvazquez - was held up in other tasks, hence wasn't able to test #5259. However, on doing a code review, I believe, both PRs solve the same issue, and @weizhouapache's solution would be less disruptive and more apt to address the issue - so maybe we could go ahead with #5259. I'll spend some time testing it as well. Apologies for the delay.

**Comment by rhtyd** [comment]
@Pearl1594 tentatively moving to 4.15.2.0 milestone - please advise if it's feasible/ready for 4.15?

**Comment by Pearl1594** [comment]
Since PR #5259 addresses the same issue - I'll close this PR

**Pull request closed without merging**
