### PR TITLE
[FUTURE]CLOUDSTACK-8907: POD Gateway optional

### PR DESCRIPTION
**Pull request by borisroman**
A gateway might not always be available. For instance, when the management network is an isolated network without internet access or inter domain/vlan routing.

How to test:
1. Deploy ACS
2. Add POD without gateway.
3. Let the systemvms deploy -> They don't have a gateway but can correctly connect to the management server.

### CODE REVIEW

**Comment by wido** [comment]
Seems good to me, in Basic Networking it's not always required.

I see that Travis CI timed out, any reason for that?

Based on the code a LGTM from me, I've run into this multiple times.

**Comment by borisroman** [comment]
@wido I've force pushed my last commit to let Travis rerun the tests.

**Comment by borisroman** [comment]
@wido Travis passing fine now.

**Comment by remibergsma** [comment]
@borisroman Can you have a look and resolve the conflict? When we find another reviewer we can merge this in 4.7. Pinging @DaanHoogland @bhaisaab

**Comment by DaanHoogland** [comment]
code looks good but I don't see the use case; in an isolated network without internet access there would still be a gateway, would there?

**Comment by borisroman** [comment]
When the network stack get's refactored this won't be necessary anymore.

**Pull request closed without merging**
