### PR TITLE
pre-commit: standardize more line endings to `lf`

### PR DESCRIPTION
**Pull request by jbampton**
https://github.com/pre-commit/pre-commit-hooks#mixed-line-ending

### Description

This PR extends the "mixed line endings" pre-commit hook to apply to more file types.

Just trying to create a code standard to follow.

You can test locally from the repo root with:

`pre-commit run --all-files`

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [X] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [X] Trivial

### CODE REVIEW

**Comment by jbampton** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
lgtm, though a lot of the touched files seem unmaintained

**Comment by DaanHoogland** [comment]
> > lgtm, though a lot of the touched files seem unmaintained
> 
> We could also "exclude" files/folders from this check perhaps for this case of unmaintained files

as long as it passes, never mind

**Review by shwstppr — APPROVED** [review]
code changes look good. Lets run a round of smoke test as the number of files changed

@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Pull request merged**
