### PR TITLE
Add new way to create a volume snapshot from instance quick view tooltip

### PR DESCRIPTION
**Pull request by NicoWohlfarth**
## Description

Added a shortcut to take a volume snapshot of a VM directly from the instance view. Therefor an option was added to the quick view tooltip. On activation a new dialog will pop up, which is based on the original dialog for creating a volume snapshot (Storage > Volumes > Take snapshot) extended with a select menu to choose the desired snapshot volume of the VM.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## Screenshots:
New shortcut to take a volume snapshot of a VM
CS1
The dialog is based on the original from Storage > Volumes > Take snapshot
CS2

## How Has This Been Tested?
Deployed to local environment and tested functionality.

### CODE REVIEW

**Comment by DennisKonrad** [comment]
Hi, @shwstppr @anuragaw. 
I saw you previously checked UI related PRs. I would appreciate it if you took a look at this PR.

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by svenvogel** [comment]
ping @rhtyd ready to merge?

**Comment by rhtyd** [comment]
Let's do it @svenvogel cheers

**Pull request merged**
