### PR TITLE
vmware: get recommended disk controller only when root or data disk controller is osdefault

### LINKED ISSUE #5100: CloudStack doesn't respect rootDiskController in template settings
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
management
~~~

##### CLOUDSTACK VERSION

~~~
4.14.1
~~~

##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

vCenter 6.5

##### SUMMARY

CloudStack tries to deploy VM from template by using osdefault as the value for rootdiskcontroller and doesn't respect rootDiskController in the template settings.

##### STEPS TO REPRODUCE

1. Create a template from root disk of a VM
2. Set the OS of the template to 'Other SUSE Linux(64-bit)'
3. Set rootDiskController of the template to pvscsi in settings tab
4. Create a VM from the template.

##### EXPECTED RESULTS

Create a new VM from the template with pvscsi disk controller

##### ACTUAL RESULTS

CloudStack cannot create the VM and raise this error in logs

~~~
2021-06-10 02:39:06,210 ERROR [c.c.h.v.m.ClusterMO] (DirectAgent-249:ctx-b8c83045 host01, job-15403/job-15409, cmd: StartCommand) (logid:249f18c6) Unable to retrieve recommended disk controller for guest OS : suse64Guest in cluster Cluster01
2021-06-10 02:39:06,211 INFO  [c.c.h.v.u.VmwareHelper] (DirectAgent-249:ctx-b8c83045 host01, job-15403/job-15409, cmd: StartCommand) (logid:249f18c6) [ignored]failed to get message for exception: Unable to retrieve recommended disk controller for guest OS : suse64Guest in cluster Cluster01
2021-06-10 02:39:06,211 WARN  [c.c.h.v.r.VmwareResource] (DirectAgent-249:ctx-b8c83045 host01, job-15403/job-15409, cmd: StartCommand) (logid:249f18c6) StartCommand failed due to Exception: com.cloud.utils.exception.CloudRuntimeException
Message: Unable to retrieve recommended disk controller for guest OS : suse64Guest in cluster Cluster01

com.cloud.utils.exception.CloudRuntimeException: Unable to retrieve recommended disk controller for guest OS : suse64Guest in cluster Cluster01
        at com.cloud.hypervisor.vmware.mo.ClusterMO.getRecommendedDiskController(ClusterMO.java:744)
        at com.cloud.hypervisor.vmware.mo.HostMO.getRecommendedDiskController(HostMO.java:1113)
        at com.cloud.hypervisor.vmware.mo.HypervisorHostHelper.createBlankVm(HypervisorHostHelper.java:1472)
        at com.cloud.hypervisor.vmware.mo.HostMO.createBlankVm(HostMO.java:798)
        at com.cloud.hypervisor.vmware.resource.VmwareResource.execute(VmwareResource.java:1884)
        at com.cloud.hypervisor.vmware.resource.VmwareResource.executeRequest(VmwareResource.java:530)
        at com.cloud.agent.manager.DirectAgentAttache$Task.runInContext(DirectAgentAttache.java:315)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
~~~

### PR DESCRIPTION
**Pull request by weizhouapache**
If vm/template has specified non-osdefault disk controller for both root and data disk, we can skip the step to get recommend disk controller (by os descriptor).

### Description

This PR fixes #5100 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by shwstppr — APPROVED** [review]
Code LGTM

**Comment by weizhouapache** [comment]
@blueorangutan test centos7 vmware-65u2

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Review by nvazquez — COMMENTED** [review]
@weizhouapache I've tested creating 2 templates from a snapshot, set root disk controller to 'pvsci' on both, but selected different OS: one as (1) 'Other SUSE Linux(64-bit)' and the other (2) 'Other Linux (64-bit)'. The first fails and the second works as expected, seems like it still looks for the recommended controller ignoring the one on the template settings:

(1) VM error
````
2021-07-30 16:35:51,198 ERROR [c.c.h.v.m.ClusterMO] (DirectAgent-171:ctx-c2677036 10.0.35.205, job-37/job-39, cmd: StartCommand) (logid:ff2533e1) Unable to retrieve recommended disk controller for guest OS : suse64Guest in cluster p1-c1
2021-07-30 16:35:51,201 INFO  [c.c.h.v.u.VmwareHelper] (DirectAgent-171:ctx-c2677036 10.0.35.205, job-37/job-39, cmd: StartCommand) (logid:ff2533e1) [ignored]failed to get message for exception: Unable to retrieve recommended disk controller for guest OS : suse64Guest in cluster p1-c1
2021-07-30 16:35:51,201 WARN  [c.c.h.v.r.VmwareResource] (DirectAgent-171:ctx-c2677036 10.0.35.205, job-37/job-39, cmd: StartCommand) (logid:ff2533e1) StartCommand failed due to Exception: com.cloud.utils.exception.CloudRuntimeException
Message: Unable to retrieve recommended disk controller for guest OS : suse64Guest in cluster p1-c1

com.cloud.utils.exception.CloudRuntimeException: Unable to retrieve recommended disk controller for guest OS : suse64Guest in cluster p1-c1
	at com.cloud.hypervisor.vmware.mo.ClusterMO.getRecommendedDiskController(ClusterMO.java:744)
	at com.cloud.hypervisor.vmware.mo.HostMO.getRecommendedDiskController(HostMO.java:1122)
	at com.cloud.hypervisor.vmware.mo.HypervisorHostHelper.createBlankVm(HypervisorHostHelper.java:1534)
	at com.cloud.hypervisor.vmware.mo.HostMO.createBlankVm(HostMO.java:798)
	at com.cloud.hypervisor.vmware.resource.VmwareResource.execute(VmwareResource.java:1906)
	at com.cloud.hypervisor.vmware.resource.VmwareResource.executeRequest(VmwareResource.java:545)
	at com.cloud.agent.manager.DirectAgentAttache$Task.runInContext(DirectAgentAttache.java:315)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:48)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:45)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
````

(2) VM deployed fine
image

**Comment by DaanHoogland** [comment]
@nvazquez the k8 tests are known to fail, but the redundant vpc tests should succeed. I see them fail on different PRs though. Do you know if something changed that could cause this?

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-65u2

**Comment by weizhouapache** [comment]
The issue in #5100 and NPE mentioned by @nvazquez have been fixed by this PR.
Unfortunately vm cannot be started in such setting
(1) template OS type is 'Other SUSE Linux(64-bit)'
(2) rootdiskcontroller and datadiskcontroller are both "pvscsi"

Got the following exception
```
2021-08-02 08:51:51,855 INFO  [c.c.v.VirtualMachineManagerImpl] (Work-Job-Executor-5:ctx-e4552c75 job-83/job-85 ctx-44664662) (logid:d465daf7) Unable to start VM on Host[-2-Routing] due to StartCommand failed due to Exception: java.lang.RuntimeException
Message: The guest operating system 'suse64Guest' is not supported.
```

it looks like 'suse64Guest' is not a valid guest os descriptor in vmware 6.5.

**Comment by nvazquez** [comment]
Thanks @weizhouapache, I can see it listed on the guest OS enum for 6.5 with different description `Suse Linux (64 bit)`: https://code.vmware.com/apis/196/vsphere/doc/vim.vm.GuestOsDescriptor.GuestOsIdentifier.html. Let's sync about this

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by weizhouapache** [comment]
travis failure is not related
```
2021-08-02 10:07:43,386 - CRITICAL - FAILED: test_21_create_tag_stopped_vm: ['Traceback (most recent call last):\n', '  File "/usr/lib/python2.7/unittest/case.py", line 329, in run\n    testMethod()\n', '  File "/home/travis/build/apache/cloudstack/test/integration/component/test_tags.py", line 2320, in test_21_create_tag_stopped_vm\n    self.fail("Exception occured - %s" % e)\n', '  File "/usr/lib/python2.7/unittest/case.py", line 410, in fail\n    raise self.failureException(msg)\n', 'AssertionError: Exception occured - Execute cmd: deletetags failed, due to: errorCode: 530, errorText:None\n']
```

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by nvazquez** [comment]
@blueorangutan test centos7 vmware-67u3

**Review by nvazquez — APPROVED** [review]
LGTM - manually tested and root disk controller is honoured

**Comment by rhtyd** [comment]
@weizhouapache @shwstppr can you fix conflict and repkg+kick tests?

**Comment by shwstppr** [comment]
@blueorangutan pacakge

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by nvazquez** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by nvazquez** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by nvazquez** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by nvazquez** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by nvazquez** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-67u3

**Pull request merged**
