### PR TITLE
UI: deploy VM - FIX missing custom iops field

### PR DESCRIPTION
**Pull request by utchoang**
### Description

Fixes https://github.com/apache/cloudstack/issues/5192

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### Screenshots (if appropriate):
image

### CODE REVIEW

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by harikrishna-patnala** [comment]
@utchoang thanks for working on the fix. 

I've checked on the QA env above and also on my local environment I don't see the new changes coming up on UI. Can you please quickly check that. I did not debug much in the code apart from testing the PR.

I've tried to check to create a data disk directly and through the deploy VM wizard, but did not see the UI changes.

**Comment by utchoang** [comment]
@harikrishna-patnala I tested on QA and it shows up, can you check again?
image

**Comment by harikrishna-patnala** [comment]
I tried different browsers and different system too, but not seeing this.
image

**Comment by shwstppr** [comment]
Visible now @harikrishna-patnala?
Screenshot from 2021-07-12 11-05-55

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by harikrishna-patnala** [comment]
with new build I can see the changes @utchoang, thanks.

I found few more things to fix, can you please look into them.
1. Disk offering with custom IOPS only (with disk size specified in disk offering) is not listing IOPS fields in deploy VM wizard
image

2. "Create Volume" needs a complete fix I think
image

**Comment by harikrishna-patnala** [comment]
just noticed, we need to add custom IOPS flag in the UI response

image

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by utchoang** [comment]
@harikrishna-patnala Please check again? Thanks.
image
image

**Comment by harikrishna-patnala** [comment]
Thanks @utchoang for doing all the changes.

I did further testing and deployed VM with disk offering having custom IOPS and observed the parameter that are set. 
"details[0].minIops=1&details[0].maxIops=2"

1. In case of data disk, the IOPS values should go into "minIopsDo" and "maxIopsDo"
2. In case of VM deployed from ISO or if the values are meant for root disk then these have to go in "minIops" and "minIops"

**Comment by utchoang** [comment]
@blueorangutan ui

**Review by harikrishna-patnala — APPROVED** [review]
Tested custom IOPS UI changes and APIs. LGTM.

**Review by rhtyd — APPROVED** [review]
LGTM based on Hari's review/testing

**Pull request merged**
