### PR TITLE
vmware: filter managed instances for existing dc for listVmwareDcVms

### LINKED ISSUE #8474: Managed VMware instances are listed as unmanaged for Import instances from VMware into a KVM cluster
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VM import
~~~

##### CLOUDSTACK VERSION

~~~
cloudstack-management-4.19.0.0-SNAPSHOT.20240109
~~~

##### SUMMARY

UI lists the managed VMware instances under the unmanaged tab in UI for Import instances from VMware into a KVM cluster.

Screenshot 2024-01-09 at 2 30 23 PM

##### STEPS TO REPRODUCE

~~~
1. Add an existing VMware DC with VMs to a zone with KVM cluster.
2. Click on [Import-Export Instances], select action 'Migrate existing instances to KVM'
~~~

### PR DESCRIPTION
**Pull request by shwstppr**
When listVmwareDcVms API is called for an existing VMware DC, filter instances that are already managed by CloudStack.

Fixes #8474

### Description

This PR...

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
clgtm. I am not well versed enough on the subject to suggest a lambda implementation for this, but it seems a good candidate. Dinosaur that I am I approve of this code ;)

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Review by rajujith — COMMENTED** [review]
With this change the managed instances are filtered out. I would still prefer to to see the managed instances, but in its own group if it is a valid use case for migration.

Screenshot 2024-01-10 at 12 01 38 PM

**Comment by shwstppr** [comment]
Filtering may not be needed if we allow importing existing managed VMware VM to KVM. Maybe we just need to update UI.

**Comment by shwstppr** [comment]
Closing this for now

**Pull request closed without merging**
