### PR TITLE
UI: Search view - Fixes the color style of the filter icon

### PR DESCRIPTION
**Pull request by utchoang**
### Description

Fixes the color style of the filter icon

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### Screenshots (if appropriate):
BEFORE:
image
image

AFTER:
image
image

### CODE REVIEW

**Comment by utchoang** [comment]
@blueorangutan ui

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
@utchoang would this not be in `blue` colour if some search query is already set - for example, somebody searching but then the form is not displayed, would have the icon turned blue? (for ex. with refresh and pages/navigation)

**Review by shwstppr — APPROVED** [review]
Looks good.
Blue icon when filtering is active
Screenshot from 2021-04-13 18-00-22
Even when form is not displaying
Screenshot from 2021-04-13 18-02-27


Normal icon when no filtering
Screenshot from 2021-04-13 18-00-31

**Comment by rhtyd** [comment]
I think I didn't get that, so the fix is to ensure the style is enforced when filtering is used.

**Comment by rhtyd** [comment]
Merging based on @shwstppr 's testing and review, and my review.

**Pull request merged**
