### PR TITLE
scripts: mark multipath scripts as executable

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR marks the multipath scripts as executable.

This fixes the issue that in 4.19.0.0-RC2, vms can not be stopped in ubuntu hosts.

```
2024-01-17 12:56:26,061 ERROR [c.c.v.VmWorkJobHandlerProxy] (Work-Job-Executor-4:ctx-e3503563 job-38/job-39 ctx-42706275) (logid:81ede4e9) Invocation exception, caused by: com.cloud.utils.exception.CloudRuntimeException: Unable to stop the virtual machine due to java.lang.NullPointerException
        at com.cloud.utils.script.Script.getExitValue(Script.java:74)
        at com.cloud.hypervisor.kvm.storage.MultipathSCSIAdapterBase.runScript(MultipathSCSIAdapterBase.java:476)
        at com.cloud.hypervisor.kvm.storage.MultipathSCSIAdapterBase.disconnectPhysicalDiskByPath(MultipathSCSIAdapterBase.java:226)
        at com.cloud.hypervisor.kvm.storage.KVMStoragePoolManager.disconnectPhysicalDiskByPath(KVMStoragePoolManager.java:205)
        at com.cloud.hypervisor.kvm.resource.LibvirtComputingResource.cleanupDisk(LibvirtComputingResource.java:3335)
        at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtStopCommandWrapper.execute(LibvirtStopCommandWrapper.java:101)
        at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtStopCommandWrapper.execute(LibvirtStopCommandWrapper.java:49)
        at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtRequestWrapper.execute(LibvirtRequestWrapper.java:78)
        at com.cloud.hypervisor.kvm.resource.LibvirtComputingResource.executeRequest(LibvirtComputingResource.java:1903)
```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
lgtm, needs testing

**Comment by weizhouapache** [comment]
@blueorangutan test ubuntu22 kvm-ubuntu22

**Review by rohityadavcloud — APPROVED** [review]
LGTM (or even the scripts could be made chmod +x as part of packaging? still worth checking during packaging the executable scripts are retained)

**Comment by weizhouapache** [comment]
> LGTM (or even the scripts could be made chmod +x as part of packaging? still worth checking during packaging the executable scripts are retained)

yes, `chmod +x` is another option. (it is used in cloud.spec, so there is no issues with rocky/alma environments)

the mode flag is kept during the packaging for ubuntu. there is no smoke test failures on ubuntu22 environment.

**Comment by DaanHoogland** [comment]
@weizhouapache , setting this for 4.19.1 (tentatively)

**Review by shwstppr — APPROVED** [review]
LGTM

**Comment by DaanHoogland** [comment]
@weizhouapache @shwstppr are we considering this a blocker indeed/should we set milestone 4.19.0.0 for this?

**Pull request merged**
