### PR TITLE
marvin: Fix deployDataCenter's cleanup

### PR DESCRIPTION
**Pull request by vishesh92**
### Description
This PR fixes TypeError. The file is written in a binary format and needs to be read in binary format as well.
```
TypeError: a bytes-like object is required, not 'str'
```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@vishesh92 
can you verify if the config file is a binary file in some environments ?

**Comment by vishesh92** [comment]
@weizhouapache Do we need to do that? We are writing the file as a binary in L74
https://github.com/apache/cloudstack/pull/7521/files#diff-787c1203eca5bb50aa8e7383efac1ac4ee03f6be034905aeabb18e2b9795f160R74

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
> @weizhouapache Do we need to do that? We are writing the file as a binary in L74 https://github.com/apache/cloudstack/pull/7521/files#diff-787c1203eca5bb50aa8e7383efac1ac4ee03f6be034905aeabb18e2b9795f160R74

@vishesh92 
ok, thanks for pointing out. code looks good to me.

**Review by weizhouapache — APPROVED** [review]
@vishesh92 
can you rebase with 4.18 and change target branch to 4.18 ?

**Comment by vishesh92** [comment]
> @vishesh92 can you rebase with 4.18 and change target branch to 4.18 ?

Done.

**Pull request merged**
