### PR TITLE
fix typo c&p bug in externalId feature UI

### PR DESCRIPTION
**Pull request by DaanHoogland**
see #2533

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## Checklist:

- [ ] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
Testing
- [ ] I have added tests to cover my changes.
- [ ] All relevant new and existing integration tests have passed.
- [ ] A full integration testsuite with all test that can run on my environment has passed.

@blueorangutan package

### CODE REVIEW

**Comment by resmo** [comment]
@DaanHoogland just a hint, if you use the keyword "closes <issue>" github will close the issue after merge of the PR.

**Comment by DaanHoogland** [comment]
simple github rebase won't work

**Comment by rafaelweingartner** [comment]
@DaanHoogland did this before. You will need to do the following:
* get the branch `DaanHoogland-patch-1`
* `reset --hard origin/4.11`
* checrry-pick your commits here to top of 4.11 (conflicts may arise here)
* execute a `push -f` to this branch
* change the target branch here to 4.11

**Comment by DaanHoogland** [comment]
Yeah thanks @rafaelweingartner . I just recreated copying those few lines. Won't mess the end result any way.
see #2536

**Pull request closed without merging**
