### PR TITLE
Adapted HypervisorUtilsTest to no longer give false positives

### PR DESCRIPTION
**Pull request by nlivens**

### CODE REVIEW

**Comment by nlivens** [comment]
@bhaisaab, this is the PR for the test adaptation discussed in PR#1142

**Comment by bhaisaab** [comment]
Great thanks, LGTM.
cc @remibergsma  - let's merge this, just so to have less Travis failures? (possibly also merge on 4.6?)

**Comment by remibergsma** [comment]
@nlivens @bhaisaab If you guys want this in 4.6 as well (which seems like a good idea) please open a PR against 4.6. That will then be forward merged to master.

**Comment by bhaisaab** [comment]
Good idea. @nlivens please open the same patch/PR again 4.6 branch, thanks.

**Comment by bhaisaab** [comment]
LGTM, I hit the unit test failure today with Jenkins while building master branch (4.7) and @nlivens 's fix worked for me :)
cc @DaanHoogland @remibergsma pl do merge this

**Pull request closed without merging**
