### PR TITLE
UI - zone wizard - fix undefined property when setting RBD primary storage

### PR DESCRIPTION
**Pull request by utchoang**
### Description

Fixes https://github.com/apache/cloudstack/issues/5166

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by utchoang** [comment]
@blueorangutan ui

**Review by shwstppr — APPROVED** [review]
Code changes LGTM
Minor suggestion if we want to address #4956 these changes can be modified to
`let path = this.prefillContent.primaryStoragePath?.value || ''`

**Comment by davidjumani** [comment]
@blueorangutan ui

**Comment by rhtyd** [comment]
LGTM

**Review by GabrielBrascher — APPROVED** [review]
LGTM

**Comment by sureshanaparti** [comment]
Merging this based on approvals, and reviews.

**Pull request merged**
