### PR TITLE
CLOUDSTACK-9525 add support for windows 10 guest os in xenserver 6.5

### PR DESCRIPTION
**Pull request by karuturi**
added guest_os and guest_os_hypervisor mappings for windows10 and xenserver 6.5.0

### CODE REVIEW

**Comment by serg38** [comment]
@karuturi  @rhtyd  I might be mistaken but we also need to add mapping into
    cloudstack/vmware-base/src/com/cloud/hypervisor/vmware/util/VmwareGuestOsMapper and/or
plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/KVMGuestOsMapper

    In the past if not added on vmware it would create VM with 'Other-64 bit' OS type instead e.g. this Jira ticket
    'CLOUDSTACK-5922:Incorrect handling RHEL guests for 5.5 to 5.9'

The same concern is for recently merged PR1696.

**Comment by serg38** [comment]
@karuturi Can we add mappings for Windows 10 for Vmware hypervisors as well?

**Comment by jburwell** [comment]
@serg38 @karuturi can you also include the mappings for KVM and HyperV?

**Comment by karuturi** [comment]
@serg38 @jburwell I will take a look and add. But, I dont have the hardware to test those.

**Comment by serg38** [comment]
On Vmware they are Windows 10 is supported only starting ESX 6 so only 3 extra lines would be needed. I will help with testing on vmware:
INSERT IGNORE INTO `cloud`.`guest_os_hypervisor` (uuid,hypervisor_type, hypervisor_version, guest_os_name, guest_os_id, created) VALUES (UUID(),'VMware', '6.0', 'windows9_64Guest', 258, utc_timestamp());
INSERT IGNORE INTO `cloud`.`guest_os_hypervisor` (uuid,hypervisor_type, hypervisor_version, guest_os_name, guest_os_id, created) VALUES (UUID(),'VMware', '6.0', 'windows9Guest', 257, utc_timestamp());
INSERT IGNORE INTO `cloud`.`guest_os_hypervisor` (uuid,hypervisor_type, hypervisor_version, guest_os_name, guest_os_id, created) VALUES (UUID(),'VMware', '6.0', 'windows9Server64Guest', 259, utc_timestamp())

**Comment by karuturi** [comment]
@serg38 thanks for the queries. added them in a new commit.

**Comment by cloudmonger** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 110
 Hypervisor xenserver
 NetworkType Advanced
 Passed=100
 Failed=3
 Skipped=4

_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/yj3wnzbceo9uef2/AAB6u-Iap-xztdm6jHX9SjPja?dl=0


**Failed tests:**
* test_non_contigiousvlan.py

 * test_extendPhysicalNetworkVlan Failing since 2 runs

* test_deploy_vm_iso.py

 * test_deploy_vm_from_iso Failed

* test_vm_life_cycle.py

 * test_10_attachAndDetach_iso Failed


**Skipped tests:**
test_vm_nic_adapter_vmxnet3
test_static_role_account_acls
test_3d_gpu_support
test_deploy_vgpu_enabled_vm

**Passed test suits:**
test_deploy_vm_with_userdata.py
test_affinity_groups_projects.py
test_portable_publicip.py
test_over_provisioning.py
test_global_settings.py
test_scale_vm.py
test_service_offerings.py
test_routers_iptables_default_policy.py
test_loadbalance.py
test_routers.py
test_reset_vm_on_reboot.py
test_snapshots.py
test_deploy_vms_with_varied_deploymentplanners.py
test_network.py
test_router_dns.py
test_login.py
test_list_ids_parameter.py
test_public_ip_range.py
test_multipleips_per_nic.py
test_regions.py
test_affinity_groups.py
test_network_acl.py
test_pvlan.py
test_volumes.py
test_ssvm.py
test_nic.py
test_deploy_vm_root_resize.py
test_resource_detail.py
test_secondary_storage.py
test_disk_offerings.py

**Comment by serg38** [comment]
LGTM

**Comment by koushik-das** [comment]
Sql changes LGTM

**Comment by cloudmonger** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 111
 Hypervisor xenserver
 NetworkType Advanced
 Passed=98
 Failed=3
 Skipped=4

_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/yj3wnzbceo9uef2/AAB6u-Iap-xztdm6jHX9SjPja?dl=0


**Failed tests:**
* test_service_offerings.py

 * ContextSuite context=TestServiceOfferings>:setup Failing since 15 runs

* test_deploy_vm_iso.py

 * test_deploy_vm_from_iso Failing since 2 runs

* test_vm_life_cycle.py

 * test_10_attachAndDetach_iso Failing since 2 runs


**Skipped tests:**
test_vm_nic_adapter_vmxnet3
test_static_role_account_acls
test_3d_gpu_support
test_deploy_vgpu_enabled_vm

**Passed test suits:**
test_deploy_vm_with_userdata.py
test_affinity_groups_projects.py
test_portable_publicip.py
test_over_provisioning.py
test_global_settings.py
test_scale_vm.py
test_routers_iptables_default_policy.py
test_loadbalance.py
test_routers.py
test_reset_vm_on_reboot.py
test_snapshots.py
test_deploy_vms_with_varied_deploymentplanners.py
test_network.py
test_router_dns.py
test_non_contigiousvlan.py
test_login.py
test_list_ids_parameter.py
test_public_ip_range.py
test_multipleips_per_nic.py
test_regions.py
test_affinity_groups.py
test_network_acl.py
test_pvlan.py
test_volumes.py
test_ssvm.py
test_nic.py
test_deploy_vm_root_resize.py
test_resource_detail.py
test_secondary_storage.py
test_disk_offerings.py

**Comment by karuturi** [comment]
executed the above failed tests manually and were successful. looks like an environment issue. merging this now

**Pull request merged**
