### PR TITLE
UI: Fixes some issues from zone wizard with VMWare hypervisor

### PR DESCRIPTION
**Pull request by utchoang**
### Description

This PR for fixes some issues from zone wizard with VMWare hypervisor (https://github.com/apache/cloudstack/issues/6479)

1. Hide the warning HTML in the message when using vue-i18n
2. Hide IP address step with VMWare hypervisor
3. Fill the value of input on the edit tariff label form
4. Close edit tariff label modal when clicking icon-close
5. Auto change cluster name if submit error with VMWare hypervisor

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):
image
image
image
image
image

### CODE REVIEW

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by borisstoyanov** [comment]
@blueorangutan help

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test centos7 vmware-70u3 keepEnv

**Review by rohityadavcloud — APPROVED** [review]
LGTM didn't test it though

**Review by shwstppr — APPROVED** [review]
Tested basic flow in zone wizard and add cluster form

**Comment by harikrishna-patnala** [comment]
@utchoang regarding the add cluster form, are you trying to fix the case where cluster name is getting appended on every error ? I still see the name getting appended after the fix too. Please correct me if I'm wrong

image

**Comment by harikrishna-patnala** [comment]
@utchoang looks like it is not applied properly on the qa setup. I've tested it with my environment and looks good. 
image

**Review by harikrishna-patnala — APPROVED** [review]

**Pull request merged**
