### PR TITLE
Fix: Update rootdisksize detail on restore VM

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR fixes the below issue:
1. Register two VM templates, small and large.
2. Deploy VM using smaller template while overriding the rootdisksize
3. Start VM if not started
4. Stop VM
5. Reinstall VM to larger VM template
6. Observe new root is the size of old volume. This is happening because the `rootdisksize` detail for VM overrides the template's size.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Comment by borisstoyanov** [comment]
@blueorangutan test keepEnv

**Review by borisstoyanov — APPROVED** [review]
LGTM

**Pull request merged**
