### PR TITLE
Hide option to upload volume when user does not have permission

### PR DESCRIPTION
**Pull request by GaOrtiga**
### Description

Uploading a local volume is made possible through the API `getUploadParamsForVolume`. However, the UI still shows this button even if the user's role does not have access to this API, returning the error 404 if the user tries to press it. A validation was added to hide this button when the user does not have permission to use the API.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### Screenshots (if appropriate):
When user is allowed to use the API `getUploadParamsForVolume`:
image

When user is not allowed to use the API `getUploadParamsForVolume`:
image

### CODE REVIEW

**Comment by GaOrtiga** [comment]
> Can you make similar changes for template/ios ?

Done

**Comment by GaOrtiga** [comment]
hey @weizhouapache are we good to go or there is anything else needed?

**Review by weizhouapache — APPROVED** [review]
code lgtm
not tested yet

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@blueorangutan ui

**Comment by DaanHoogland** [comment]
@blueorangutan ui

**Comment by weizhouapache** [comment]
this works in my local build

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by vladimirpetrov — COMMENTED** [review]
LGTM based on manual testing.

**Comment by weizhouapache** [comment]
@GaOrtiga 
   is it applicable for 4.18 as well ?

**Pull request merged**
