### PR TITLE
create mode 1777 instead of 0777

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR sets sticky bits on new files.

Fixes: #6867

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by rohityadavcloud — APPROVED** [review]
LGTM did n't test it, and I don't know the impact for this on ssvm/secondary storage operations/lifecycles

**Comment by vladimirpetrov** [comment]
Not sure if this is related, but I'm unable to detach a volume from a VM once it's attached.

**Comment by harikrishna-patnala** [comment]
> Not sure if this is related, but I'm unable to detach a volume from a VM once it's attached.

@vladimirpetrov I tried the same operation on your environment and seems to be issue with the template used. When I try with default template attach and detach are working fine.
When I use macchinina template I get the below error 
"Could not detach volume after sending the command and waiting for [10000] milliseconds. Probably the VM does not support the sent detach command or the device is busy at the moment. Try again in a couple of minutes."

So I think its not related to these changes.

**Review by harikrishna-patnala — APPROVED** [review]
Code LGTM. Let's see the complete test matrix results.

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by vladimirpetrov** [comment]
No sticky bit on a KVM environment and it's still possible to delete templates from secondary storage.

**Comment by DaanHoogland** [comment]
> No sticky bit on a KVM environment and it's still possible to delete templates from secondary storage.

as a user not member the same groups as the original ones?

**Comment by vladimirpetrov** [comment]
```
bash-4.2$ ls -lad template/tmpl/1/3/f6b95db4-d5f6-3d48-8d1f-dfb59588e36d.qcow2 
-rw-rw-rw-. 1 root root 460521472  3 юли 15,48 template/tmpl/1/3/f6b95db4-d5f6-3d48-8d1f-dfb59588e36d.qcow2
bash-4.2$ pwd
/acs/secondary/ref-trl-5087-k-Mu20-vladimir-petrov/sec2
bash-4.2$ rm template/tmpl/1/3/f6b95db4-d5f6-3d48-8d1f-dfb59588e36d.qcow2
bash-4.2$ ls -la template/tmpl/1/3/
total 4
drwxrwxrwx. 2 root root  33  4 юли 16,16 .
drwxrwxrwx. 4 root root  24  3 юли 15,46 ..
-rw-rw-rw-. 1 root root 325  3 юли 15,48 template.properties
bash-4.2$ id
uid=1000(sbcloud) gid=1000(sbcloud) groups=1000(sbcloud) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
```
@DaanHoogland

**Comment by DaanHoogland** [comment]
ah, ok @vladimirpetrov , lets revisit this change. It does not make any sense like this.

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
no way forward

**Pull request closed without merging**
