### PR TITLE
reuse ip for non redundant VPC

### PR DESCRIPTION
**Pull request by DaanHoogland**
As rolling restart does not deallocate an IP before configuring it on a new VR,
 the code must allow it to be reused on a non-redundant VPCs gateway nic.

## Description

removed the condition to only look for reuse of IP on redundant VPCs

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
Testing
- [ ] I have added tests to cover my changes.
- [x] All relevant new and existing integration tests have passed.
- [x] A full integration testsuite with all test that can run on my environment has passed.

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by PaulAngus** [comment]
@DaanHoogland have you looked at the VPC private gateway test failures?

**Comment by DaanHoogland** [comment]
The failure is a failure to ping. This may have many causes. I think we need to manually test this functionality, to see if either the test or the private gateway (or acl/fw) functionality needs fixing, @PaulAngus

**Comment by PaulAngus** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
After some more testing locally I see that sometimes restart with cleanup works and sometimes it doesn't. At one occasion I tried to make a VPC redundant and ...
screenshot from 2018-06-20 14-31-38

at later occasions restarts just worked. The use case in the test is to have two VPCs connected through their private gateways and static routes added towards each other. Then a VPC is restarted with cleanup and it is tested whether the VMs are still pingable.

I am now convinced that the improvement in this PR does not solve everything but neither does it cause the errors in the restart.

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
Ran tests manually with increased ping thresholds: (rebased against 4.11, no changes to the original commit by Daan)
```
test_vpc_router_nics.py:
Create a VPC with two networks with one VM in each network and test nics after destroy ... === TestName: test_01_VPC_nics_after_destroy | Status : SUCCESS ===
ok
Create a VPC with two networks with one VM in each network and test default routes ... === TestName: test_02_VPC_default_routes | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 2 tests in 566.266s

OK

test_privategw_acl.py:

other tests in progress -- will update as it goes
```

**Comment by DaanHoogland** [comment]
thanks @rhtyd so we merge? (cc @PaulAngus )

**Comment by rhtyd** [comment]
Still working/testing @DaanHoogland I'll confirm and post once results are here.

**Comment by rhtyd** [comment]
The `test_03_vpc_privategw_restart_vpc_cleanup | Status : FAILED ===` test has been consistently failing for me. What I observe is that post restart with cleanup=true of the VPC VR it is unable to connect to the guest VM. I'm investigating this case now.

**Comment by DaanHoogland** [comment]
I know about test_03_vpc_privategw_restart_vpc_cleanup @rhtyd . The only time I got this functionality to work was on manual testing. I think there is something with the order of applying interface and addresses that makes it work or fail :(

**Comment by rhtyd** [comment]
There was no clear solution for fixing the nic/ip sequencing/application issue, I could reproduce the error sometimes and sometimes the test would pass when the sequence applied cleanly. Given a workaround for the non-redundant restart VPC with private gateway enabled exists in case a sequence issue is hit (i.e. user should manually destroy the VPC VR and restart the VPC without cleanup selected), I'll merge this /cc @PaulAngus. I verified that the issue does not arise in case of redundant VPCs.

**Comment by rhtyd** [comment]
Issue logged - https://github.com/apache/cloudstack/issues/2719

**Pull request merged**
