### PR TITLE
CLOUDSTACK-9265 cleanup around httpclient versions

### PR DESCRIPTION
**Pull request by DaanHoogland**
some cleanup done
- replaced HttpStatus from org.apache.commons.httpclient with that from org.apache.http
- removed unthrown HttpException
- left auto reformat in place

### CODE REVIEW

**Comment by bhaisaab** [comment]
LGTM (just did code review, no regression tests)

**Comment by rafaelweingartner** [comment]
Hi Daan, 
Since you are cleaning things up, what about changing those “pokemons” try-catches for specific ones?

**Comment by DaanHoogland** [comment]
@rafaelweingartner very fine but really out of scope now. Can you be more specific? I suspect these are in code where an automatic 'final' policy was applied.

**Comment by rafaelweingartner** [comment]
No problem Daan, I understand.
I was referring to the try-catches at lines 58, 65 and 140 of “ClusterServiceServletHttpHandler”; and at line 472 of “BrocadeVcsApi”

**Comment by DaanHoogland** [comment]
catch Throwable is really evil, I agree. :(
At least the catch Exception of BrocadeVcsApi is re-thrown.

**Comment by bvbharatk** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 103
 Hypervisor xenserver
 NetworkType Advanced
 Passed=103
 Failed=16
 Skipped=4

**The follwing tests have known issues**
test_vpc_remote_access_vpn
test_vpc_site2site_vpn
test_01_test_vm_volume_snapshot
test_02_vpc_privategw_static_routes
test_03_rvpc_privategw_static_routes
test_04_change_offering_small
ContextSuite context=TestNiciraContoller>:setup
test_01_primary_storage_iscsi
test02_internallb_haproxy_stats_on_all_interfaces
test_01_internallb_roundrobin_1VPC_3VM_HTTP_port80
ContextSuite context=TestDeployVM>:setup
test_04_extract_template
test_04_extract_Iso
test_07_list_default_iso


_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/yj3wnzbceo9uef2/AAB6u-Iap-xztdm6jHX9SjPja?dl=0


**Failed tests:**
* integration.smoke.test_guest_vlan_range.TestDedicateGuestVlanRange

 * test_dedicateGuestVlanRange Failing since 3 runs

 * ContextSuite context=TestDedicateGuestVlanRange>:teardown Failing since 2 runs

* <nose.suite

 * ContextSuite context=TestSnapshotRootDisk>:setup Failed

* integration.smoke.test_non_contigiousvlan.TestUpdatePhysicalNetwork

 * test_extendPhysicalNetworkVlan Failed


**Skipped tests:**
test_vm_nic_adapter_vmxnet3
test_deploy_vgpu_enabled_vm
test_06_copy_template
test_06_copy_iso

**Passed test suits:**
integration.smoke.test_deploy_vm_with_userdata.TestDeployVmWithUserData
integration.smoke.test_affinity_groups_projects.TestDeployVmWithAffinityGroup
integration.smoke.test_portable_publicip.TestPortablePublicIPAcquire
integration.smoke.test_over_provisioning.TestUpdateOverProvision
integration.smoke.test_global_settings.TestUpdateConfigWithScope
integration.smoke.test_scale_vm.TestScaleVm
integration.smoke.test_service_offerings.TestCreateServiceOffering
integration.smoke.test_loadbalance.TestLoadBalance
integration.smoke.test_routers.TestRouterServices
integration.smoke.test_reset_vm_on_reboot.TestResetVmOnReboot
integration.smoke.test_deploy_vms_with_varied_deploymentplanners.TestDeployVmWithVariedPlanners
integration.smoke.test_network.TestDeleteAccount
integration.smoke.test_deploy_vm_iso.TestDeployVMFromISO
integration.smoke.test_public_ip_range.TestDedicatePublicIPRange
integration.smoke.test_multipleips_per_nic.TestDeployVM
integration.smoke.test_regions.TestRegions
integration.smoke.test_affinity_groups.TestDeployVmWithAffinityGroup
integration.smoke.test_network_acl.TestNetworkACL
integration.smoke.test_pvlan.TestPVLAN
integration.smoke.test_volumes.TestCreateVolume
integration.smoke.test_ssvm.TestSSVMs
integration.smoke.test_nic.TestNic
integration.smoke.test_deploy_vm_root_resize.TestDeployVM
integration.smoke.test_resource_detail.TestResourceDetail
integration.smoke.test_secondary_storage.TestSecStorageServices
integration.smoke.test_vm_life_cycle.TestDeployVM
integration.smoke.test_disk_offerings.TestCreateDiskOffering

**Comment by rhtyd** [comment]
@DaanHoogland rebase against latest master thanks

tag:easypr

**Comment by swill** [comment]
Missing one code review on this one.  @rafaelweingartner?  I saw you post in this thread, so I am calling you out.  :P

**Comment by rafaelweingartner** [comment]
Hi @swill no problem, you might be calling me on other PRs, and I might have not answered you. Sadly, duty is calling these days, few papers were accepted and now I have to work with all of those bureaucracy and also I have to get a camera ready version; that I why I haven't had much time to be around here lately. If it is something important you can send me an email.

I have just re-checked this one.
Although I find the addition of “final” everywhere something that was not needed; @DaanHoogland knows that I am very picky sometimes ;). What was promised by the PR description was implemented here, and I am ok with that. 

LGTM here too.

**Comment by swill** [comment]
@rafaelweingartner thanks.  I understand completely...

I know the `final` stuff is debatable, but I don't think that should block a PR.  :)

I think this one is ready.

**Comment by swill** [comment]
Can you do a force push again.  Jenkins has been in this state for 3 days now.  Thx...

**Comment by swill** [comment]
@DaanHoogland can you force push this one again so we can kick off Jenkins again.  It has been stuck in this state for a week.  Thx...

**Comment by DaanHoogland** [comment]
@swill I closed and reopened. It started building anew but is now stuck in the archiving phase for quite some time.
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 40:46 min
[INFO] Finished at: 2016-05-11T10:07:41+00:00
[INFO] Final Memory: 181M/1862M
[INFO] ------------------------------------------------------------------------
[CHECKSTYLE] Collecting checkstyle analysis files...
[CHECKSTYLE] Finding all files that match the pattern **/checkstyle-result.xml
[CHECKSTYLE] Parsing 96 files in /home/jenkins/jenkins-slave/workspace/cloudstack-pr-analysis
```
I am trying to find where it got stuck. At least aftyer duplicate code analysis...:|

**Comment by swill** [comment]
@DaanHoogland it finished!!!  :P

**Comment by DaanHoogland** [comment]
It was stuck due to another jenkins job running. I am still not sure I saw what I saw. when I stopped 1252, shortly after 1253 through 1256 finished.

**Pull request merged**
