### PR TITLE
kvm: consider provisioning type for local data volumes

### LINKED ISSUE #8644: Unable to create data disk of provisioning type as Fat
ISSUE TYPE

BUG 

Component Name

Storage

CLOUDSTACK VERSION

Cloudstack version 4.18, 4.19 

SUMMARY

Unable to create data disk of provisioning type as Fat

Steps to reproduce the issue

1. Create a disk offering with Provisioning type as fat and storage type  as local

Screenshot 2024-02-13 at 10 07 11 AM

2. Create a data disk based on the disk offering and attach it to a  running vm

3. Check the data disk size using "qemu-img" command 

The actual disk size is thin instead of thick

```

[root@ol8 agent]# qemu-img info /localstorage/655c8f16-1574-420f-bfd1-adbf8e7ca90d
image: /localstorage/655c8f16-1574-420f-bfd1-adbf8e7ca90d
file format: qcow2
virtual size: 10 GiB (10737418240 bytes)
disk size: 196 KiB
cluster_size: 65536
Format specific information:
    compat: 1.1
    compression type: zlib
    lazy refcounts: false
    refcount bits: 16
    corrupt: false
    extended l2: false

```

Logs 

```
2024-02-12 12:30:04,757 DEBUG [cloud.agent.Agent] (agentRequest-Handler-5:null) (logid:1637c086) Request:Seq 1-7785597855816746741:  { Cmd , MgmtId: 32988167406101, via: 1, Ver: v1, Flags: 100011, [{"org.apache.cloudstack.storage.command.CreateObjectCommand":{"data":{"org.apache.cloudstack.storage.to.VolumeObjectTO":{"uuid":"655c8f16-1574-420f-bfd1-adbf8e7ca90d","volumeType":"DATADISK","dataStore":{"org.apache.cloudstack.storage.to.PrimaryDataStoreTO":{"uuid":"2284dd6f-8bc7-431e-afa8-e247bfe1e940","name":"ol8.localdomain-local-2284dd6f","id":"1","poolType":"Filesystem","host":"10.0.35.197","path":"/localstorage","port":"0","url":"Filesystem://10.0.35.197/localstorage/?ROLE=Primary&STOREUUID=2284dd6f-8bc7-431e-afa8-e247bfe1e940","isManaged":"false"}},"name":"test-kiran-local","size":"(10.00 GB) 10737418240","volumeId":"21","accountId":"2","provisioningType":"FAT","poolId":"1","id":"21","cacheMode":"NONE","hypervisorType":"KVM","directDownload":"false","deployAsIs":"false"}},"wait":"0","bypassHostMaintenance":"false"}}] }

2024-02-12 12:30:04,757 DEBUG [cloud.agent.Agent] (agentRequest-Handler-5:null) (logid:1637c086) Processing command: org.apache.cloudstack.storage.command.CreateObjectCommand

2024-02-12 12:30:04,757 DEBUG [storage.resource.StorageSubsystemCommandHandlerBase] (agentRequest-Handler-5:null) (logid:1637c086) Executing command CreateObjectCommand: [{"data":{"org.apache.cloudstack.storage.to.VolumeObjectTO":{"uuid":"655c8f16-1574-420f-bfd1-adbf8e7ca90d","volumeType":"DATADISK","dataStore":{"org.apache.cloudstack.storage.to.PrimaryDataStoreTO":{"uuid":"2284dd6f-8bc7-431e-afa8-e247bfe1e940","name":"ol8.localdomain-local-2284dd6f","id":1,"poolType":"Filesystem","host":"10.0.35.197","path":"/localstorage","port":0,"url":"Filesystem://10.0.35.197/localstorage/?ROLE=Primary&STOREUUID=2284dd6f-8bc7-431e-afa8-e247bfe1e940","isManaged":false}},"name":"test-kiran-local","size":10737418240,"volumeId":21,"accountId":2,"provisioningType":"FAT","poolId":1,"id":21,"cacheMode":"NONE","hypervisorType":"KVM","directDownload":false,"deployAsIs":false}},"wait":0,"bypassHostMaintenance":false}].


2024-02-12 12:30:04,761 DEBUG [utils.script.Script] (agentRequest-Handler-5:null) (logid:1637c086) Executing: qemu-img create -f qcow2 /localstorage/655c8f16-1574-420f-bfd1-adbf8e7ca90d 10737418240

**2024-02-12 12:30:04,778 DEBUG [utils.script.Script] (agentRequest-Handler-5:null) (logid:1637c086) Formatting '/localstorage/655c8f16-1574-420f-bfd1-adbf8e7ca90d', fmt=qcow2 cluster_size=65536 extended_l2=off compression_type=zlib size=10737418240 lazy_refcounts=off refcount_bits=16**
```

Actual Behaviour

The size of the data disk is not thick 

Expected Behaviour

The size of the data disk should be thick

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #8644

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by weizhouapache** [comment]
@blueorangutan test

**Review by rohityadavcloud — APPROVED** [review]
LGTM didn't test it

**Review by borisstoyanov — APPROVED** [review]
LGTM, was able to get the correct size

```
[root@ref-trl-6778-k-Mr8-boris-stoyanov-kvm1 localstorage]# qemu-img info 35676ed8-a183-418c-975b-694b25282855
image: 35676ed8-a183-418c-975b-694b25282855
file format: qcow2
virtual size: 5 GiB (5368709120 bytes)
disk size: 5 GiB
cluster_size: 65536
Format specific information:
    compat: 1.1
    compression type: zlib
    lazy refcounts: false
    refcount bits: 16
    corrupt: false
    extended l2: false
[root@ref-trl-6778-k-Mr8-boris-stoyanov-kvm1 localstorage]#
```

**Pull request merged**
