### PR TITLE
Consistence POM version for 4.11.x.y

### PR DESCRIPTION
**Pull request by khos2ow**
## Description

This is to make POM version of `4.11` branch consistence since we have 4 digits in version.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

## Checklist:

- [ ] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
Testing
- [ ] I have added tests to cover my changes.
- [ ] All relevant new and existing integration tests have passed.
- [ ] A full integration testsuite with all test that can run on my environment has passed.

### CODE REVIEW

**Comment by khos2ow** [comment]
@PaulAngus this is essentially a fix on your commit (8ba318d), feel free to close or merge this.

**Comment by khos2ow** [comment]
@DaanHoogland that's exactly my point, at some point we might need to use the forth digit for security patches, so technically our version is always 4 digits (the last one being 0 most of the time). Otherwise the versions are not consistence:

- 4.11.0.0
- 4.11.1.0
- 4.11.2
- 4.11.2.1 (hypothetical future security release)
- 4.11.3    (hypothetical future normal release)

They sure look weird!

**Comment by rhtyd** [comment]
@DaanHoogland that breaks what we've been following. I disagree, we should keep the next version to 4.11.2.0, just like 4.11.1.0 was done.

**Comment by rhtyd** [comment]
Thanks for taking away -1 @DaanHoogland. For the note, the master is set to 4.12.0.0-SNAPSHOT in poms etc. I'll merge this as this should have been done as part of the release process to set the next version consistent with the versioning pattern (https://cwiki.apache.org/confluence/display/CLOUDSTACK/Release+Procedure).

**Comment by khos2ow** [comment]
@DaanHoogland I agree, i believe 3 digit would have been enough considering number and frequency of times we release. But since it's already there as @rhtyd mentioned this was only for consistency and requires further discussion if we want to drop the 4th digit altogether.

**Pull request merged**
