### PR TITLE
CLOUDSTACK-10046 checksum validation for any java supported Digests-type

### PR DESCRIPTION
**Pull request by DaanHoogland**
This fixes a very old regression where the checksum wouldn't be checked on downloaded templates.

It checks again now but also allows to specify an algorithm like "{SHA-1}98765....". No algorithm assumes md5 ("MD5") for now

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by borisstoyanov** [comment]
@NuxRo Hi, I'm about to create some tests for this and was looking at here: http://dl.openvm.eu/cloudstack/macchinina/x86_64/
are we expecting changes, if no I might hardcode some numbers in tests?

**Comment by NuxRo** [comment]
Hi, I don't plan on making any changes. What exactly do you want to hard code?

**Comment by borisstoyanov** [comment]
@NuxRo we need to create tests that verify cloudstack checksum. so when registering template we pass the checksum and it checks it when downloaded.

**Comment by NuxRo** [comment]
I am publishing sums here http://dl.openvm.eu/cloudstack/macchinina/x86_64/sha1sum.txt
Can't that be used? Would it help if I upload individual sum files for each file?
Just trying to future-proof a bit.

**Comment by borisstoyanov** [comment]
we're looking to check not just sha-1 but md5 and sha-256

**Comment by NuxRo** [comment]
All required sums generated, use them if it helps. In any case, I do not see changes coming.

**Comment by borisstoyanov** [comment]
Thanks @NuxRo !

**Comment by borisstoyanov** [comment]
@DaanHoogland I've added tests, can you please resolve the merge conflicts?

**Comment by DaanHoogland** [comment]
tnx @borisstoyanov will do

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by borisstoyanov** [comment]
@blueorangutan test centos7 xen65sp1

**Comment by borisstoyanov** [comment]
@blueorangutan test centos7 xenserver-65sp1

**Comment by borisstoyanov** [comment]
@blueorangutan test centos7 vmware-55u3

**Comment by rhtyd** [comment]
@nvazquez @borisstoyanov can you review the code, tests?

**Comment by borisstoyanov** [comment]
Sure @rhtyd I'm waiting for vmware and xen hypervisors to complete

**Comment by borisstoyanov** [comment]
@NuxRo do you happen to have plans to upload an ISO for macchinina at http://dl.openvm.eu/ ? I've been struggling to find an iso available on the internet for these tests...

**Comment by NuxRo** [comment]
Well, I wouldn't even know where to begin. All I'm doing is use buildroot to generate a working layout and stick syslinux on it.
Why would you want an ISO? Maybe there's a way around it etc.

**Comment by borisstoyanov** [comment]
@NuxRo We've implemented a checksum validation for templates and ISOs, that checksum is done after downloading. We already have tests for templates now we're thinking to create tests for ISOs as well. Machinina is small and that makes our tests run fast, thats it :)

**Comment by NuxRo** [comment]
What is expected of this ISO exactly? Does it need to boot, execute anything etc?

**Comment by borisstoyanov** [comment]
@NuxRo nope, just installable in Cloudstack I have an iso file if you wish?

[macchinina-kvm.iso.zip](https://github.com/apache/cloudstack/files/1264323/macchinina-kvm.iso.zip)

**Comment by NuxRo** [comment]
I'll see if I can make an iso with Macchinina.
In the meantime I have added an actual working file with TinyCore:
http://dl.openvm.eu/cloudstack/iso/

**Comment by borisstoyanov** [comment]
Great, thank you very much @NuxRo, the tiny-core iso would be good enough for the purpose of these tests.

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test matrix

**Comment by cloudmonger** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 1191
 Hypervisor xenserver
 NetworkType Advanced
 Passed=113
 Failed=8
 Skipped=40

_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/r2si930m8xxzavs/AAAzNrnoF1fC3auFrvsKo_8-a?dl=0

**Failed tests:**
* test_router_dnsservice.py

 * test_router_dns_guestipquery Failed

* test_scale_vm.py

 * ContextSuite context=TestScaleVm>:setup Failing since 46 runs

* test_non_contigiousvlan.py

 * test_extendPhysicalNetworkVlan Failing since 2 runs

* test_volumes.py

 * test_06_download_detached_volume Failed

* test_routers_network_ops.py

 * test_01_isolate_network_FW_PF_default_routes_egress_true Failing since 52 runs

 * test_02_isolate_network_FW_PF_default_routes_egress_false Failing since 179 runs

 * test_01_RVR_Network_FW_PF_SSH_default_routes_egress_true Failing since 172 runs

 * test_02_RVR_Network_FW_PF_SSH_default_routes_egress_false Failing since 172 runs


**Skipped tests:**
test_vm_nic_adapter_vmxnet3
test_01_verify_libvirt
test_02_verify_libvirt_after_restart
test_03_verify_libvirt_attach_disk
test_04_verify_guest_lspci
test_05_change_vm_ostype_restart
test_06_verify_guest_lspci_again
test_disable_oobm_ha_state_ineligible
test_hostha_configure_default_driver
test_hostha_enable_ha_when_host_disabled
test_hostha_enable_ha_when_host_disconected
test_hostha_enable_ha_when_host_in_maintenance
test_hostha_kvm_host_degraded
test_hostha_kvm_host_fencing
test_hostha_kvm_host_recovering
test_remove_ha_provider_not_possible
test_configure_ha_provider_invalid
test_configure_ha_provider_valid
test_ha_configure_enabledisable_across_clusterzones
test_ha_disable_feature_invalid
test_ha_enable_feature_invalid
test_ha_list_providers
test_ha_multiple_mgmt_server_ownership
test_ha_verify_fsm_available
test_ha_verify_fsm_degraded
test_ha_verify_fsm_fenced
test_ha_verify_fsm_recovering
test_hostha_configure_default_driver
test_hostha_configure_invalid_provider
test_hostha_disable_feature_valid
test_hostha_enable_feature_valid
test_hostha_enable_feature_without_setting_provider
test_list_ha_for_host
test_list_ha_for_host_invalid
test_list_ha_for_host_valid
test_static_role_account_acls
test_11_ss_nfs_version_on_ssvm
test_nested_virtualization_vmware
test_3d_gpu_support
test_deploy_vgpu_enabled_vm

**Passed test suits:**
test_deploy_vm_with_userdata.py
test_affinity_groups_projects.py
test_portable_publicip.py
test_vm_snapshots.py
test_over_provisioning.py
test_global_settings.py
test_service_offerings.py
test_routers_iptables_default_policy.py
test_loadbalance.py
test_routers.py
test_reset_vm_on_reboot.py
test_deploy_vms_with_varied_deploymentplanners.py
test_network.py
test_router_dns.py
test_outofbandmanagement_nestedplugin.py
test_portforwardingrules.py
test_login.py
test_deploy_vm_iso.py
test_list_ids_parameter.py
test_public_ip_range.py
test_multipleips_per_nic.py
test_metrics_api.py
test_regions.py
test_affinity_groups.py
test_network_acl.py
test_pvlan.py
test_nic.py
test_deploy_vm_root_resize.py
test_resource_detail.py
test_secondary_storage.py
test_vm_life_cycle.py
test_disk_offerings.py

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@DaanHoogland @borisstoyanov @nvazquez we happy with the review, tests?
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by borisstoyanov** [comment]
I've re-run the tests and they are passing... 
@blueorangutan test

**Comment by rhtyd** [comment]
LGTM, @DaanHoogland @borisstoyanov advise if we're happy with the PR. I'll merge on your confirmation.

**Comment by DaanHoogland** [comment]
@rhtyd on request i'll improve the API doc strings and then we can merge. thanks

**Comment by rhtyd** [comment]
@DaanHoogland I've not requested for any further change, I've already shared my LGTM on this. I'm not sure if any more work is needed or if we're satisfied with the changes, on your confirmation we can merge this.

**Comment by DaanHoogland** [comment]
@rhtyd these were requested off-line not by you. I've added the extra commit now and am re-spawning packaging and tests. I'm fine with merging if these pass.
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Pull request merged**
