### PR TITLE
loop optimisation in bash

### PR DESCRIPTION
**Pull request by DaanHoogland**
## Description

A small optimisation as suggested by the user in #4449 . I'm not convinced this is actually reducing the memory usage as they suggest. the code itself seems rathrer risk-free. let's discuss.

Fixes: #4449 

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@GabrielBrascher @weizhouapache @rhtyd @wido let's discuss this. I've seen issues in large isolated nets on startup but I doubt this is going to be a big help. thoughts?

**Review by rhtyd — APPROVED** [review]
LGTM, needs testing and maybe new tests that could simulate that scale (1k+ fw rules?)

**Comment by wido** [comment]
I'm not sure if this fixes it. Not against changing it, but I don't know if this is the root-cause.

**Review by davidjumani — APPROVED** [review]
Code works, LGTM

**Comment by davidjumani** [comment]
@rhtyd @DaanHoogland Would splitting the file and processing each part sequentially work ?

**Comment by DaanHoogland** [comment]
@davidjumani I like the idea, do we have a good logical splitting of the file? the problem states that many firewall rules cause the issue , so splitting over functional parts wouldn't solve this.

**Comment by davidjumani** [comment]
@DaanHoogland Assuming that the rules are in multiple lines, loading all the lines in memory and processing them would kill the VR. Instead splitting the file into smaller ones and reading them could solve the memory issue

**Comment by DaanHoogland** [comment]
Again @davidjumani I like the idea. What is the criterium? (no of lines, sections some combination of criterea) can we be sure that lines are self contained and do not require context or order of executing and can we guarantee that?

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@DaanHoogland @rhtyd 
I suggest not to merge this pr into 4.15.0.0

**Comment by rhtyd** [comment]
Yes @weizhouapache, it's marked against 4.15.1.0; (I'm) just kicking tests on PRs.

**Comment by DaanHoogland** [comment]
> @DaanHoogland @rhtyd
> I suggest not to merge this pr into 4.15.0.0

I agree, and would say let's not merge at all until we have knowledge if this is making a difference at all.

**Comment by rhtyd** [comment]
@DaanHoogland @weizhouapache @wido should we merge this for 4.15.1.0 (targetting Q2)?

**Comment by DaanHoogland** [comment]
I don't care for this code @rhtyd . I don't know but i don't think it is an improvement/optimisation

**Comment by weizhouapache** [comment]
> I don't care for this code @rhtyd . I don't know but i don't think it is an improvement/optimisation

same to me.

**Comment by rhtyd** [comment]
Considering all I could find, the pipe based thing would be better compared to redirection as it would avoid memory exhaustion; the pipe/buffer synchronisation (https://stackoverflow.com/questions/9553628/piping-and-redirection). Let's merge this in 4.15 and test over next few weeks, we can revisit and revert if necessary.

**Pull request merged**
