### PR TITLE
server: use ed25519 instead of rsa when generate public/private keys

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

RSA has been considered as insecure and 'ssh-rsa' signature algorithm has been deprecated in OpenSSH.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by rohityadavcloud — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Review by DaanHoogland — APPROVED** [review]
clgtm (functionality as well ;)

**Review by sureshanaparti — APPROVED** [review]
changes lgtm

**Pull request merged**
