### PR TITLE
api: rename ListUsageRecords file name to ListUsageRecordsCmd

### PR DESCRIPTION
**Pull request by dhlaluku**
## Description

Refactor file name to be consistent with the API name. 

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by dhlaluku** [comment]
@blueorangutan package

**Comment by dhlaluku** [comment]
@rafaelweingartner @GabrielBrascher @rhtyd @wido @DaanHoogland please review

**Comment by dhlaluku** [comment]
@blueorangutan package

**Comment by dhlaluku** [comment]
@blueorangutan package

**Comment by GabrielBrascher** [comment]
@blueorangutan test

**Comment by dhlaluku** [comment]
@blueorangutan test

**Comment by dhlaluku** [comment]
@rhtyd @rafaelweingartner @GabrielBrascher any thoughts on this while we are here?

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by dhlaluku** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
All OK, merging this since master is unfrozen now.

**Pull request merged**
