### PR TITLE
Fix KVM imported unmanaged VMs disks path

### PR DESCRIPTION
**Pull request by nvazquez**
### Description

This PR fixes the volumes path on KVM import unmanaged instances

Fixes: #8479 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?
- Create VM on KVM
- Unmanage VM
- Import unmanaged VM from the same template
- Verify disks path
- Destroy/expunge VM and verify there are no leftover disks

### CODE REVIEW

**Comment by nvazquez** [comment]
@blueorangutan test

**Review by harikrishna-patnala — APPROVED** [review]
code LGTM

@nvazquez just a side question about datastore name
`disk.setDatastoreName(imagePath.substring(imagePath.lastIndexOf("/")))`
is this right! as I see we are setting filebasename with the same value except /

**Review by shwstppr — APPROVED** [review]
Code LGTM

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@nvazquez can you look at the conflict?

**Comment by shwstppr** [comment]
Tested KVM import before and after.

Before - ROOT volume is leftover in destroy state
https://github.com/apache/cloudstack/assets/153340/880bb802-fbfe-47ee-b5b0-0d9838738517

After - no leftover volume
https://github.com/apache/cloudstack/assets/153340/32242ca6-2be1-447d-b4de-9da823f14048

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Pull request merged**
