### PR TITLE
CLOUDSTACK-8996: Reducing Virual Machine Deployments

### PR DESCRIPTION
**Pull request by pritisarap12**
Combining testcases to reduce the VM deployments wherever possible.

### CODE REVIEW

**Comment by borisroman** [comment]
@pritisarap12 Thanks for the test! Does this test actually replace other integration tests? I assume it does so, which tests does it make abundant?

**Comment by bhaisaab** [comment]
@pritisarap12 I don't see any changes on the "Files changed" tab is the file plaintext with 0644 file mod, or is it already merged on master?

**Comment by borisroman** [comment]
@bhaisaab It's a new file with more then 2k lines, so github doesn't show it right away. Though if you click on view you can see it.

https://github.com/pritisarap12/cloudstack/blob/CLOUDSTACK-8996-Reducing-Virual-Machine-Deployments/test/integration/testpaths/testpath_reduce_vm_deployments.py

**Comment by bhaisaab** [comment]
@borisroman cool thanks, weird though as I've seen github show the entire file in some of the previous PRs

**Comment by pvr9711** [comment]
@borisroman , @bhaisaab , this refactoring helps speed up BVT runs by reducing the number of VM deployments.  we should get the test results to close on this PR though.   
@pritisarap12, can you please post the test results ?

**Comment by rhtyd** [comment]
@pritisarap12 can you rebase against latest master and share state of your PR, thanks

**Comment by bvbharatk** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 88
 Hypervisor xenserver
 NetworkType Advanced
 Passed=70
 Failed=3
 Skipped=3

_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/yj3wnzbceo9uef2/AAB6u-Iap-xztdm6jHX9SjPja?dl=0


**Failed tests:**
* test_vpc_vpn.py

 * ContextSuite context=TestRVPCSite2SiteVpn>:setup Failing since 5 runs

 * ContextSuite context=TestVpcRemoteAccessVpn>:setup Failing since 6 runs

 * ContextSuite context=TestVpcSite2SiteVpn>:setup Failing since 6 runs


**Skipped tests:**
test_vm_nic_adapter_vmxnet3
test_static_role_account_acls
test_deploy_vgpu_enabled_vm

**Passed test suits:**
test_deploy_vm_with_userdata.py
test_affinity_groups_projects.py
test_portable_publicip.py
test_over_provisioning.py
test_global_settings.py
test_scale_vm.py
test_service_offerings.py
test_routers_iptables_default_policy.py
test_routers.py
test_reset_vm_on_reboot.py
test_snapshots.py
test_deploy_vms_with_varied_deploymentplanners.py
test_login.py
test_list_ids_parameter.py
test_public_ip_range.py
test_multipleips_per_nic.py
test_regions.py
test_affinity_groups.py
test_network_acl.py
test_pvlan.py
test_volumes.py
test_nic.py
test_deploy_vm_root_resize.py
test_resource_detail.py
test_secondary_storage.py
test_vm_life_cycle.py
test_disk_offerings.py

**Pull request closed without merging**
