### PR TITLE
accountresponse: Fix domainpath description

### PR DESCRIPTION
**Pull request by davidjumani**
### Description

Fixing the description of `domainpath`

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Review by sureshanaparti — APPROVED** [review]
minor label/name updates, code LGTM.

**Comment by davidjumani** [comment]
@blueorangutan package

**Review by weizhouapache — APPROVED** [review]

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
Doc changes only, no smoketests necessary.

**Comment by DaanHoogland** [comment]
travis maven download failure in one of the builds but the others went fine, merging.

**Pull request merged**
