### PR TITLE
Marvin: Fix codegenerator to work with API discovery

### PR DESCRIPTION
**Pull request by rhtyd**
This fixes Marvin cloudstackAPI generator to work with a live running mgmt server's api discovery.

### CODE REVIEW

**Comment by wido** [comment]
This is just there to get the ground work done for Marvin to it's own repo?

**Comment by rhtyd** [comment]
@wido yes, with this PR we can split marvin to its own repository. As an example to show it's doable, here is a repository I extracted from cloudstack master -- https://github.com/rhtyd/marvin

**Comment by wido** [comment]
Understood. LGTM

**Comment by rhtyd** [comment]
The initiative to split marvin into its own repository has been dropped for now. Meanwhile, this PR can still be accepted as it fixed the code-generator to work against the api discovery. I'll send another PR that will add marvin and integration test as a separate rpm/deb package.

/cc @swill @syed @bvbharat @resmo @PaulAngus

**Comment by rhtyd** [comment]
Pinging for review - @wido @koushik-das @karuturi @abhinandanprateek @jburwell 
This enables `cloudstackAPI` api cmd/resp classes generation against a live running mgmt server.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Pinging for review -- @karuturi @jburwell @koushik-das @swill @pdion891 and others. Thanks.

**Comment by pdion891** [comment]
The code seams to make sense.  I like the idea of api auto-discovery so it's a LGTM I guest.
I'm a bit out of context on this one but if it's usefull lets merge it.

Cheers,

**Comment by jburwell** [comment]
@rhtyd Is my understanding correct that auto discovery was implemented in a previous commit and this PR fixes an defect in that work?  If so, could you please provide a detailed explanation of the issue fixed by this commit?

**Comment by rhtyd** [comment]
@jburwell yes, this PR does not implement API-discovery based generation but rather fixes the fields that the (api discovery based)  codegenerator should produce in the generated python classes (cmd and response classes per api/module). The issue was the autogenerated `cloudstackAPI` differed between api-based and apidocs-based code generation. With this PR the generated classes match exactly thereby allowing us to go with either methods to generate `cloudstackAPI`.

**Comment by rhtyd** [comment]
@jburwell the Travis build failed due to tearDown error in one of the tests:
=== TestName: test_listVM_by_id_as_user_vmsfromotherdomain | Status : EXCEPTION ===

I'll re-kick it. The PR does not change any part of CloudStack, nor are the changes in the normal codegenerator used to generate `cloudstackAPI` in the marvin library.

**Comment by jburwell** [comment]
@rhtyd that explanation makes sense, and the code seems to address that issue.  Could you please amend the explanation to the commit message?

**Comment by rhtyd** [comment]
@jburwell fixed.

**Comment by jburwell** [comment]
@rhtyd thanks for the expanded commit message.  The change makes complete sense to me now.  LGTM for code.

**Comment by rhtyd** [comment]
Due to changes in marvin, specifically the code generator that runs during build-time and is not used with either Travis or otherwise, manual tests have confirmed the functionality working. With enough reviews, I'll merge this. Thanks all.

**Pull request merged**
