### PR TITLE
UI: fix error message when create load balancer as a normal user

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This fixes an error message when create load balancer as a normal user

image

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
code looks good, not sure how to test though

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
@blueorangutan ui

**Comment by DaanHoogland** [comment]
@msinhore does this test ok for you?

**Comment by msinhore** [comment]
> @msinhore does this test ok for you?

Yes, it is working as expected now. Thank you @weizhouapache @DaanHoogland

**Pull request merged**
