### PR TITLE
Create event TEMPLATE_UPDATE for virtual machine image update calls.

### PR DESCRIPTION
**Pull request by mprokopchuk**
### Description
This PR allows to create events of type TEMPLATE_UPDATE for "edit image" functionality (in addition to "create image" and "delete image").

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):
174351015-44685c49-058b-4b66-b042-ee01945957a9

### How Has This Been Tested?

Manually tested.

### CODE REVIEW

**Review by mlsorensen — APPROVED** [review]
LGTM

**Review by sureshanaparti — APPROVED** [review]
code LGTM

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Review by rohityadavcloud — APPROVED** [review]

**Pull request merged**
