### PR TITLE
Added new logs to volume creation

### PR DESCRIPTION
**Pull request by JoaoJandre**
### Description

This PR improves and adds new logs to volume creation to facilitate future troubleshooting.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?
This was tested in a local lab, by creating volumes and checking if the logs were all correct.

### CODE REVIEW

**Review by BryanMLima — APPROVED** [review]
CLGTM

**Review by GutoVeronezi — APPROVED** [review]
CLGTM

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by GutoVeronezi** [comment]
Merging this one based in the approvals and test results.

**Pull request merged**
