### PR TITLE
CLOUDSTACK-9088: Update the description for migrateVirtualMachineWithVolume api

### PR DESCRIPTION
**Pull request by anshul1886**
https://issues.apache.org/jira/browse/CLOUDSTACK-9088

### CODE REVIEW

**Comment by bhaisaab** [comment]
LGTM

**Comment by DaanHoogland** [comment]
It seems to me this text is only suitable for use with cloudmonkey or maybe python clients. I don't think it makes sense to format it this way in the java annotation.

**Comment by anshul1886** [comment]
@DaanHoogland Could you suggest a better way of putting this information in API documents in current scenario?

**Comment by DaanHoogland** [comment]
There is two problems to solve here;
1. how to document the api in a concise way. The information you are providing is very useful and I think it makes sense to put it there
2. how to use the api. the formatting of the information is specific to the client so I would try to use a more formal format or as in my exmple below in json. I don't have a universal answer to this but in this case I would say, though it is somewhate oververbose:
```
migrateto : [ {
    volume: '71f43cd6-69b0-4d3b-9fbc-67f50963d60b',
    pool: 'a382f181-3d2b-4413-b92d-b8931befa7e1'
},
{
    volume: '88de0173-55c0-4c1c-a269-83d0279eeedf',
    pool: '95d6e97c-6766-4d67-9a30-c449c15011d1'
},
{
    volume: '1b331390-59f2-4796-9993-bf11c6e76225',
    pool: '41fdb564-9d3b-447d-88ed-7628f7640cbc'
} ]

This example in cloudmoney:
    migrateto[0].volume=<71f43cd6-69b0-4d3b-9fbc-67f50963d60b>&migrateto[0].pool=<a382f181-3d2b-4413-b92d-b8931befa7e1>&migrateto[1].volume=<88de0173-55c0-4c1c-a269-83d0279eeedf>&migrateto[1].pool=<95d6e97c-6766-4d67-9a30-c449c15011d1>&migrateto[2].volume=<1b331390-59f2-4796-9993-bf11c6e76225>&migrateto[2].pool=<41fdb564-9d3b-447d-88ed-7628f7640cbc>
```

**Comment by anshul1886** [comment]
@DaanHoogland I don't understand how json format is helping here?

**Comment by DaanHoogland** [comment]
@anshul1886 It is a language independent description of the parameters and applicable to all API client implementations. It can also be view as a more generic/formal description of the parameter format. Users of powershell or go implementation will probably need to format their commandline differently. Seeing the data in a second format will prevent to some extend prejudice on how the data is to be formatted.

**Comment by bhaisaab** [comment]
LGTM anyone, needs one more?

**Comment by rajesh-battala** [comment]
Gone through the code. 
API change for the description param is good.

**Comment by swill** [comment]
We need to be doing this to more API calls, so I am happy we are starting to look at this.

@DaanHoogland I don't think JSON adds much value here.  I think the main thing that needs to be in this documentation is how the URL query looks.  I have run into many situation where the URL query is very hard to figure out and I have spent way too much time doing trial and error on this.  I think the information presented here is the correct format and is useful.

I will add this to my merge queue.  Thanks...

**Pull request merged**
