### PR TITLE
CLOUDSTACK-8971 - Improve the current test_privategw_acls.py

### PR DESCRIPTION
**Pull request by wilderrodrigues**
- Read cofiguration from the zone: template id; template id; and domain id
   - Create Account and VPC Offering
   - Add cleanup resources

### CODE REVIEW

**Comment by wilderrodrigues** [comment]
Ping @remibergsma @michaelandersen @miguelaferreira @karuturi @DaanHoogland @wido 

Test results:

```
test_privategw_acl (integration.smoke.test_privategw_acl.TestPrivateGwACL) ... === TestName: test_privategw_acl | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 1 test in 301.406s

OK
```

**Comment by borisroman** [comment]
@wilderrodrigues Ran tests. OK.

```
=== TestName: test_privategw_acl | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 1 test in 250.320s
```

OK

**Comment by wilderrodrigues** [comment]
Thanks, @borisroman !

Cheers,
Wilder

**Comment by michaelandersen** [comment]
LGTM!

**Comment by remibergsma** [comment]
@michaelandersen Can you please let us know what you tested / reviewed? Thanks!

**Comment by wilderrodrigues** [comment]
@remibergsma @michaelandersen 

I added the wrong ACS issue to the PR title and the commit. I already edited the title, will now amend the commit and force push. Sorry for that!

Cheers,
Wilder

**Comment by michaelandersen** [comment]
@remibergsma @wilderrodrigues  LGTM'ed this one too soon, was a bit too enthusiastic. sorry about that.  Ran the test just now, but it's failing!

nosetests --with-marvin --log-folder-path=/tmp/marvin/ --marvin-config=../../../mct-zone1-kvm1.cfg -a tags=advanced,required_hardware=false  test_privategw_acl.py


=== Marvin Init Logging Successful===
Creating Admin Account for Domain ID ==> 01634a5a-726d-11e5-9395-5254001daa62
Creating a VPC offering..
Enabling the VPC offering created
Creating a VPC network in the account: test-TestPrivateGwACL-test_privategw_acl-KZ68F5
cCreate NetworkOffering
Created and Enabled NetworkOffering
Adding Network={'netmask': '255.255.255.0', 'displaytext': 'Test Network', 'name': 'NETWORK-10.1.1.1'}
Created network with ID: b8914c96-9a92-4bbb-8e6b-51b1ed74a803
===final results are now copied to: /tmp/marvin//MarvinLogs/test_privategw_acl_GYMPT8===


----

test_privategw_acl (integration.smoke.test_privategw_acl.TestPrivateGwACL) ... === TestName: test_privategw_acl | Status : FAILED ===
FAIL

======================================================================
FAIL: test_privategw_acl (integration.smoke.test_privategw_acl.TestPrivateGwACL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mandersen/Projects/cloudstack/test/integration/smoke/test_privategw_acl.py", line 199, in test_privategw_acl
    self.createPvtGw()
  File "/Users/mandersen/Projects/cloudstack/test/integration/smoke/test_privategw_acl.py", line 275, in createPvtGw
    self.fail("Failed to create Private Gateway ==> %s" % e)
AssertionError: Failed to create Private Gateway ==> Execute cmd: createprivategateway failed, due to: errorCode: 530, errorText:None
-------------------- >> begin captured stdout << ---------------------
=== TestName: test_privategw_acl | Status : FAILED ===

**Comment by michaelandersen** [comment]
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): cs2.cloud.lan
requests.packages.urllib3.connectionpool: DEBUG: "GET /client/api?physicalnetworkid=200&vpcid=f2839995-7ebb-49be-b466-ad1da9274c7d&sourcenatsupported=true&aclid=420b9956-1ce3-4a7e-ac12-03615dcb09a2&vlan=30&gateway=10.147.30.1&netmask
=255.255.255.0&apiKey=m5d8bqnS-qAVICCTlFiUHwPKd_dWXSOkKEnd8ur_UO-1Kcza8fD3a97OqDDB96NuElYmNY_4q4klE7sdpgJYWQ&command=createPrivateGateway&signature=uD9jjAKOWv%2B%2F3oRHIhWU3VBSW%2Bc%3D&ipaddress=10.147.30.200&response=json HTTP/1.1" 
530 83
test_privategw_acl (integration.smoke.test_privategw_acl.TestPrivateGwACL): ERROR: Exception:['Traceback (most recent call last):\n', '  File "/Library/Python/2.7/site-packages/marvin/cloudstackConnection.py", line 306, in __parseAnd
GetResponse\n    response_cls)\n', '  File "/Library/Python/2.7/site-packages/marvin/jsonHelper.py", line 151, in getResultObj\n    raise cloudstackException.CloudstackAPIException(respname, errMsg)\n', 'CloudstackAPIException: Execu
te cmd: createprivategateway failed, due to: errorCode: 530, errorText:None\n']
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/marvin/cloudstackConnection.py", line 306, in __parseAndGetResponse
    response_cls)
  File "/Library/Python/2.7/site-packages/marvin/jsonHelper.py", line 151, in getResultObj
    raise cloudstackException.CloudstackAPIException(respname, errMsg)
CloudstackAPIException: Execute cmd: createprivategateway failed, due to: errorCode: 530, errorText:None

**Comment by michaelandersen** [comment]
from the mgt server log:
WARN  [c.c.a.d.ParamGenericValidationWorker] (709693495@qtp-265638379-0:ctx-dfba94e8 ctx-8090674b ctx-c8da340d) Received unknown parameters for command createNetworkACL. Unknown p
arameters : cidr
INFO  [o.a.c.f.j.i.AsyncJobMonitor] (API-Job-Executor-5:ctx-8ec951c2 job-1957) Add job-1957 into job monitoring
WARN  [c.c.a.d.ParamGenericValidationWorker] (API-Job-Executor-5:ctx-8ec951c2 job-1957 ctx-173033b6) Received unknown parameters for command createNetworkACL. Unknown parameters :
 cidr
INFO  [o.a.c.f.j.i.AsyncJobMonitor] (API-Job-Executor-5:ctx-8ec951c2 job-1957) Remove job-1957 from job monitoring
WARN  [c.c.a.d.ParamGenericValidationWorker] (709693495@qtp-265638379-0:ctx-f8a13dcf ctx-86f02aa9 ctx-57be2ff6) Received unknown parameters for command createNetworkOffering. Unkn
own parameters : usevpc
ERROR [c.c.a.ApiServer] (709693495@qtp-265638379-0:ctx-ac06c612 ctx-aacaf035 ctx-2f37a8d5) unhandled exception executing api command: [Ljava.lang.String;@9976afa
java.lang.NullPointerException
        at com.cloud.network.vpc.VpcManagerImpl.createVpcPrivateGateway(VpcManagerImpl.java:1610)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at org.apache.cloudstack.network.contrail.management.EventUtils$EventInterceptor.invoke(EventUtils.java:106)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161)
        at com.cloud.event.ActionEventInterceptor.invoke(ActionEventInterceptor.java:51)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
        at com.sun.proxy.$Proxy148.createVpcPrivateGateway(Unknown Source)
        at org.apache.cloudstack.api.command.admin.vpc.CreatePrivateGatewayCmd.create(CreatePrivateGatewayCmd.java:150)

**Comment by remibergsma** [comment]
It works fine for me:

```
nosetests --with-marvin --marvin-config=${marvinCfg} -s -a tags=advanced,required_hardware=false smoke/test_privategw_acl.py
```

Result:
```
test_privategw_acl (integration.smoke.test_privategw_acl.TestPrivateGwACL) ... === TestName: test_privategw_acl | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 1 test in 223.325s

OK
```

Based on the above: LGTM

@michaelandersen are you sure it isn't a local problem? Maybe try to deploy again? I'll hold this PR until tomorrow morning.

**Comment by wilderrodrigues** [comment]
@michaelandersen 

Could you give some details on how you executed the tests? It looks like env issues.

Did you...

* checked out the PR
* built ACS and RPMs
* installed RPMs on KVM
* cleaned the DB
* deployed DC
* ran the tests

...?

Or was it executed towards an existing/running environment?

As you can see in the Python stack trace, it says errorTest: None

```
AssertionError: Failed to create Private Gateway ==> Execute cmd: createprivategateway failed, due to: errorCode: 530, errorText:None
```

When you ran it, were the templates ready? Could you please follow steps above and try again? I will also try on my side.

Cheers,
Wilder

**Comment by wilderrodrigues** [comment]
@remibergsma @michaelandersen 

New results:

```
test_privategw_acl (integration.smoke.test_privategw_acl.TestPrivateGwACL) ... === TestName: test_privategw_acl | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 1 test in 243.665s

OK
/tmp//MarvinLogs/test_privategw_acl_4TCQBF/results.txt (END)
```

Cheers,
Wilder

**Comment by michaelandersen** [comment]
yes @wilderrodrigues it is most likely an environment issue. don't wait on me for this PR.

**Pull request merged**
