### PR TITLE
UI: Fixes UI break with SAML authentication

### PR DESCRIPTION
**Pull request by utchoang**
### Description

This PR for fixes https://github.com/apache/cloudstack/issues/6459

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by rohityadavcloud** [comment]
@utchoang can you rebase/change base of the PR branch to 4.17, as this needs fixing in 4.17.1.0

**Comment by nvazquez** [comment]
Thanks for the fix @utchoang! @kohrar can you please test this PR?

**Comment by kohrar** [comment]
Awesome work. Thanks @utchoang for the quick fix.

**Review by rohityadavcloud — APPROVED** [review]

**Review by shwstppr — COMMENTED** [review]
code LGTM

**Pull request merged**
