### PR TITLE
Improve vm.allocation.algorithm global setting description

### PR DESCRIPTION
**Pull request by hsato03**
### Description

To make the `vm.allocation.algorithm` setting more intuitive, its description has been updated.

Furthermore, the configuration has been adapted to `ConfigKey`.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested:

In the UI, I accessed the `Global Settings` tab and filtered for `vm.allocation.algorithm`. So I checked that the description was up to date.

### CODE REVIEW

**Comment by jbampton** [comment]
@blueorangutan package

**Review by sureshanaparti — APPROVED** [review]
code lgtm

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Review by DaanHoogland — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@sureshanaparti , I tend to think this is sufficiently tested in the smoke tests. The implementation of the config key has changed along with the description (for the better). Do you agree we can merge this now?

**Comment by JoaoJandre** [comment]
ping @sureshanaparti

**Pull request merged**
