### PR TITLE
UI: show button for dynamic Scaling for VM in case of KVM hypervisor

### PR DESCRIPTION
**Pull request by harikrishna-patnala**
### Description

Enabled UI button for Dynamic scaling of VM which are on KVM. API support is already here https://github.com/apache/cloudstack/pull/4878

There are few constraints with KVM support for dynamic scaling like it has to be custom compute offering and need to set maxmemory, but showing it in UI adds value. It fails with an appropriate error when fixed compute offering is used, so it is worth adding to UI. We can also disable the button in such cases but it may confuse users why it is disabled.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by slavkap** [comment]
LGTM, I did a few manual tests

**Comment by utchoang** [comment]
@blueorangutan ui

**Review by utchoang — APPROVED** [review]
code LGTM!

**Review by GutoVeronezi — COMMENTED** [review]
CLGTM

**Review by GutoVeronezi — APPROVED** [review]

**Review by rhtyd — APPROVED** [review]

**Pull request merged**
