### PR TITLE
UI: hide Cleanup/Expunge when delete a CloudManaged CKS cluster

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR hides the destroy/expunge option for CloudManaged CKS cluster

prior to this change
image

with this change
image

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
Code looks good @weizhouapache , but what is the reason?
And if we want this don't we want to prevent it on the API?

**Comment by weizhouapache** [comment]
> Code looks good @weizhouapache , but what is the reason?
> And if we want this don't we want to prevent it on the API?

@DaanHoogland 
Destroy/expunge are only applicable on ExternalManaged clusters, not CloudManaged clusters (traditional cks clusters)
cc @vishesh92

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by vishesh92 — COMMENTED** [review]
clgtm.

@weizhouapache There is an additional commit from https://github.com/apache/cloudstack/pull/8482. Can you please remove that?

**Comment by weizhouapache** [comment]
> clgtm.
> 
> @weizhouapache There is an additional commit from #8482. Can you please remove that?

thanks for review @vishesh92 
it does not matter actually, as 4.18/4.19 already has the commit.

**Comment by weizhouapache** [comment]
@blueorangutan ui

**Review by DaanHoogland — APPROVED** [review]

**Review by vishesh92 — APPROVED** [review]
clgtm

**Comment by weizhouapache** [comment]
Merging
thanks @DaanHoogland @vishesh92 for review

**Pull request merged**
