### PR TITLE
CLOUDSTACK-8433: Remove awsapi

### PR DESCRIPTION
**Pull request by bhaisaab**
Following actions from discussions on dev ML regarding removing awsapi and preferring ec2stack. Reference from last PR: https://github.com/apache/cloudstack/pull/44 Opening a new one as master has changed since then and rebasing caused several conflicts so this PR consists of 3 patches (to make rebasing easier).

    - Removes awsapi and awsapi-setup
    - Removes awsapi packaging rules for debian, centos63, centos7, fedora 20/21
    - Removes catalina port 7080 service configs
    - Fixes build replace properties for AWSAPILOG
    - Removes maven profile for building awsapi and deploying db in developer profile
    - Removes awsapi db properties usage across codebase
    - Removes references from spring xmls, test cases and TransactionLegacy
    - Adds sql command to drop database cloudbridge in schema-451to460-cleanup.sql

CentOS 7, CentOS 6.3, Debian repository: http://packages.bhaisaab.org/cloudstack/nukeawsapi
TravisCI: https://travis-ci.org/apache/cloudstack/builds/60704658

### CODE REVIEW

**Comment by bhaisaab** [comment]
@runseb -  Sure. I was testing 4.5 today and the awsapi service did not work for me, after wasting almost 2 hours to make it work, I tried ec2stack which worked out of the box. I thought it would be a good idea to get rid of it and promote ec2stack :)

I’ve split the changes in 3 commits to make it easier to rebase/merge. I’ll keep this open and hope to merge it next week but am interested in merge it now to avoid rebasing efforts again. If ec2stack will get its own git repo like docs repos or cloudmonkey - does it matter if we merge this now or next week and will this block 4.6 release management?

**Comment by runseb** [comment]
-Sebastien

> On 30 Apr 2015, at 18:12, Rohit Yadav <notifications@github.com> wrote:
> 
> @runseb - Sure. I was testing 4.5 today and the awsapi service did not work for me, after wasting almost 2 hours to make it work, I tried ec2stack which worked out of the box. I thought it would be a good idea to get rid of it and promote ec2stack :)
> 
> I’ve split the changes in 3 commits to make it easier to rebase/merge. I’ll keep this open and hope to merge it next week but am interested in merge it now to avoid rebasing efforts again. If ec2stack will get its own git repo like docs repos or cloudmonkey - does it matter if we merge this now or next week and will this block 4.6 release management?
> 
Nothing technical, just a better process in my view. To be sure we dont have a period with no official ec2 interface.

Lets talk it over a bit and decide mud next week . That should not causr too much rebase headache.

Ok ?

**Comment by bhaisaab** [comment]
Copy that.

**Comment by bhaisaab** [comment]
@runseb is this good to go now that ec2stack is an apache cloudstack sub-project? I'll rebase and do some tests again if it's okay merge this PR.

**Comment by runseb** [comment]
let's go for it, there has been enough warning. So if you can rebase, make Travis happy….and squash everything that would be good.

**Comment by runseb** [comment]
Maybe do it after Daan merges 4.5.1….?

**Comment by bhaisaab** [comment]
merging 4.5.1 looks like will cause a lot of conflicts; I'm merging it after rebasing and pushing to master and if travis and packaging works

**Comment by bhaisaab** [comment]
All green, merging now.

**Pull request merged**
