### PR TITLE
Externalize vm stats increment in memory

### PR DESCRIPTION
**Pull request by SadiJr**
### Description

CloudStack has a feature to keep and increment the VM metrics in memory. This PR intends to externalize one new configuration, `vm.stats.increment.metrics.in.memory` to allow operators to choose if they want to increment VM metrics or not.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

### How Has This Been Tested?

KVM hypervisor:
- I created a VM in CloudStack and maked Network and Disk I/O operations
- I changed the value of configuration `vm.stats.increment.metrics.in.memory`
- I checked that the metrics weren't incrementing in memory

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
clgtm, not sure of the usefulness of the feature but fine by me.

**Comment by SadiJr** [comment]
Thanks @DaanHoogland for the review. This feature will allow operators to see real time statistics, what was not possible before. I can't say it will be useful or not, but the important thing, from my point of view, is that this option exists, in case anyone wants to use it.

**Review by shwstppr — APPROVED** [review]
LGTM! Externalize * configs are great improvements

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by GabrielBrascher — APPROVED** [review]
The new global settings name is aligned with current stats collector parameters and despite a simple change, it might add some flexibility to ADMINs.
Code LGTM.

**Review by nvazquez — APPROVED** [review]

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Pull request merged**
