### PR TITLE
Update NiciraNvpGuestNetworkGuru.java

### PR DESCRIPTION
**Pull request by sspans**
Add support for VXLAN as isolation method

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@sspans any testing done?

**Comment by DaanHoogland** [comment]
does every version of nvp support vxlan?

**Comment by sspans** [comment]
Daan: any supported release of vmware nsx will support VXLAN.
People running older releases probably already have an STT setup running, and should not encounter problems following these changes.

**Comment by sspans** [comment]
Testing and a unit-test will still be added.

We need this feature because we're planning to roll out new zones with VXLAN,
which if the changes remain small would ideally also be backported to 4.4.

**Comment by DaanHoogland** [comment]
@sspans yes but they might be tempted to do some vxlanning after upgrading ACS not upgrading NSX . what would happen?

**Comment by sspans** [comment]
The plugin would fail, similar to how it fails now when you ask ik to do vxlan when it only supports STT.
The encapsulation type is something that you first configure in NSX and then in cloudstack.
So the scenario you're trying to propose is really very unrealistic.

NB: NSX releases supporting only STT don't seem to be available for download anymore.

**Comment by DaanHoogland** [comment]
ok

**Comment by kishankavala** [comment]
@sspans 
Since Test case is updated to cover VXLAN also, LGTM.

**Pull request merged**
