### PR TITLE
[CLOUDSTACK-10406] fix bugs that may cause program crash, change mkdir to mkdirs

### PR DESCRIPTION
**Pull request by bd2019us**
## Description
Fixes: [#CLOUDSTACK-10406](https://issues.apache.org/jira/browse/CLOUDSTACK-10406)

## Types of changes
- [x ] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by bd2019us** [comment]
retest please, the code change should not cause any test case failing.

**Comment by DaanHoogland** [comment]
@bd2019us the test are not reliable. code looks good, we'll run some integration tests in surplus.
Please use github issues in the future, we stopped using jira (which doesn't matter in this case as you came up with your own fix ;)
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by bd2019us** [comment]
@DaanHoogland Thanks for your information.

**Comment by rhtyd** [comment]
Failures not related to the change.

**Pull request merged**
