### PR TITLE
Allow download of system vm templates

### PR DESCRIPTION
**Pull request by GaOrtiga**
### Description

Currently, ACS does not allow the user to download System VM Templates,  even though it may be usefull as it can speed up the registration process of the template for production once the homologation is done beforehand. This PR changes this, allowing the user to download said VM Templates

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

### How Has This Been Tested?

I built the code with the respective changes in a local lab. After that, I copied the Uuid from one of the System VM templates. Then, using CloudMonkey, I utilized the command 'extract template' with the copied Uuid. CloudMonkey then generated a link for the download of the template, confirming that the alteration was successful.

### CODE REVIEW

**Comment by rohityadavcloud** [comment]
Thanks for the PR - can you explain the use case as the systemvmtemplate aren't for public/general consumption for users? The systemvmtemplates are also publicly available so if anybody wants they can register using such links.

**Review by GutoVeronezi — APPROVED** [review]

**Comment by GaOrtiga** [comment]
@rohityadavcloud 
Access to the official repositories may be slow at time; therefore, being able to perform a direct download can speed up this process in some use cases. Also since access to these templates is already public, there should be no problem in allowing the downloads to be performed from within the platform itself.

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by DaanHoogland — APPROVED** [review]
code looks good and I'm fine with it functionaly

**Comment by DaanHoogland** [comment]
> Thanks for the PR - can you explain the use case as the systemvmtemplate aren't for public/general consumption for users? The systemvmtemplates are also publicly available so if anybody wants they can register using such links.

is this a :-1: , @rohityadavcloud ?

**Comment by rohityadavcloud** [comment]
@DaanHoogland no just a question, really trying to understand why we're making this public? (historically this has been private/hidden to users, or at least the download button isn't it?)

**Comment by DaanHoogland** [comment]
@rohityadavcloud it is a valid question but I think @GaOrtiga 's argument makes sense. Do we merge?

**Review by SadiJr — APPROVED** [review]
CLGTM, and I agree with @DaanHoogland and @GaOrtiga arguments

**Comment by DaanHoogland** [comment]
@rohityadavcloud I need to test but i think that the system vm template will not be visible to the normal user so no download button either. Only root admins should be able to download it this way. (not sure about the API)
We can verify. Is there any other blocking concern you have?

**Comment by GaOrtiga** [comment]
@DaanHoogland you are correct, the download button will not be visible in the UI as shown below:
image (1)

Furthermore, even through CloudMonkey download will only be available to Root Admins, as shown below:
Running the command with a Root Admin account:
downloadRootAdmin


Running the command with a user-level account:
downloaduser


With this being said, I still do not understand why allowing operators to download said templates is a concern. These images are publicly available, and operators are the ones registering them in ACS. Therefore, it makes sense to allow them to download directly from ACS if they wish so.

**Comment by rohityadavcloud** [comment]
Makes sense, LGTM, let's merge this.

**Pull request merged**
