### PR TITLE
server: delete template on storage over capacity threshold

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

While deleting a template for a specific zone, the check should be done only for secondary storages and not for storages with the available capacity threshold.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Review by DaanHoogland — APPROVED** [review]
code lgtm

**Review by rhtyd — APPROVED** [review]
LGTM, let's wait for @Pearl1594 's LGTM who has worked on the secondary storage management feature

**Comment by Pearl1594** [comment]
@shwstppr atm deletion of templates is supported across all stores, so maybe we can omit the check for writable stores or we disable deletion of templates on read-only stores? We may also need the strictness of this check to be reduced for deletion of Isos?

**Comment by shwstppr** [comment]
@Pearl1594 I've added changes for ISO deletion
I can remove the writable check but there seems another issue. If there is only a single zone with a read-only secondary store and a template is deleted from UI (or with API using zoneid param), entry from cloud.vm_template is not marked removed first. Calling the API again second time with the same parameters deletes the template completely and marks it removed in DB.

@rhtyd @DaanHoogland should we allow deleting templates, ISOs on read-only stores?

**Comment by rhtyd** [comment]
Yes I think so @shwstppr - possible the read only secondary storage is more towards adding new templates than removing existing ones, @Pearl1594 is my assumption correct?

**Comment by Pearl1594** [comment]
That's right @rhtyd. The idea behind read-only stores is to prevent any further resources from being downloaded onto that store.

**Comment by shwstppr** [comment]
made the change to remove writable store check @Pearl1594 @rhtyd 
@blueorangutan package

**Review by Pearl1594 — APPROVED** [review]
LGTM

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Pull request merged**
