### PR TITLE
Marvin Tests: fix expected return string for successful pings.

### PR DESCRIPTION
**Pull request by PaulAngus**
fix expected return string for successful pings.  these pings are from the test instance inside the isolated networks. The original response was searched for was that which would be seen on a Mac.

### CODE REVIEW

**Comment by rhtyd** [comment]
LGTM.

**Comment by koushik-das** [comment]
@PaulAngus Refer to #1563. In that PR it was mentioned that ping response varies based on OS. So hard coding based on some specific environment is not the right way to fix this.

**Comment by PaulAngus** [comment]
The best way to fix this would be a ping function that gets called. 
However, that's not something that i can personally do and this will work for (at least) Ubuntu, CentOS/RHEL and macchinina - making it infinitely better that it was.

**Comment by serg38** [comment]
Debian returns: 1 packets transmitted, 1 packets received, 0% packet loss
CentOs returns: 1 packets transmitted, 1 received, 0% packet loss, time 4ms

Between those 2 we could be  simply checking for 0% loss: check_string = ", 0% packet loss"

**Comment by PaulAngus** [comment]
that works for me. I'll adjust the PR.

**Comment by rhtyd** [comment]
LGTM
@koushik-das All tests are written to be execute on a Linux based environment, though if you look at the test it does ssh into the guest VM and then executes the ping. Afaik, we don't run osx/mac vms on cloudstack for integration testing yet.

**Comment by rhtyd** [comment]
@PaulAngus please squash you commits, thanks.

**Comment by koushik-das** [comment]
@rhtyd Please go through #1563 as mentioned in my previous comment to get the context. As @serg38 also mentioned the response differs between debian and centos which needs to be addressed, leave aside osx. Also the comment about "100% packet loss" needs to be addressed.

**Comment by serg38** [comment]
LGTM for testing
Before 
sshClient: DEBUG: {Cmd: ping -c 3 8.8.8.8 via Host: 10.140.12.103} {returns: [u'PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.', u'64 bytes from 8.8.8.8: icmp_seq=1 ttl=54 time=4.
72 ms', u'64 bytes from 8.8.8.8: icmp_seq=2 ttl=54 time=4.66 ms', u'64 bytes from 8.8.8.8: icmp_seq=3 ttl=54 time=4.61 ms', u'', u'--- 8.8.8.8 ping statistics ---', u'3 packets transmitted, 3 received, 0% packet loss, time 2001ms', u'rtt min/avg/max/mdev = 4.611/4.666/4.723/0.091 ms']}
TestRouterDHCPHosts: DEBUG: SSH result: [u'PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.', u'64 bytes from 8.8.8.8: icmp_seq=1 ttl=54 time=4.72 ms', u'64 bytes from 8.8.8.8: icmp_seq=2 ttl=54 time=4.66 ms', u'64 bytes from 8.8.8.8: icmp_seq=3 ttl=54 time=4.61 ms', u'', u'--- 8.8.8.8 ping statistics ---', u'3 packets transmitted, 3 received, 0% packet loss, time 2001ms', u'rtt min/avg/max/mdev = 4.611/4.666/4.723/0.091 ms']; COUNT is ==> 0
test_router_dhcphosts (integration.smoke.test_router_dhcphosts.TestRouterDHCPHosts): CRITICAL: FAILED: test_router_dhcphosts: ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python2.7/unittest/case.py", line 331, in run\n    testMethod()\n', '  File "/home/t_vazqnadmin/cloudstack/test/integration/smoke/test_router_dhcphosts.py", line 356, in test_router_dhcphosts\n    self.test_ssh_command(self.vm_1, nat_rule1, "natrule1")\n', '  File "/home/t_vazqnadmin/cloudstack/test/integration/smoke/test_router_dhcphosts.py", line 201, in test_ssh_command\n    "Ping to outside world from VM should be successful"\n', '  File "/usr/local/lib/python2.7/unittest/case.py", line 515, in assertEqual\n    assertion_func(first, second, msg=msg)\n', '  File "/usr/local/lib/python2.7/unittest/case.py", line 508, in _baseAssertEqual\n    raise self.failureException(msg)\n', 'AssertionError: **## Ping to outside world from VM should be successful**\n']

After
sshClient: DEBUG: ====Trying SSH Connection: Host:10.144.31.41 User:root                                   Port:22 RetryCnt:60===
paramiko.transport: DEBUG: starting thread (client mode): 0x4206310L
paramiko.transport: INFO: Connected (version 2.0, client OpenSSH_5.3)
paramiko.transport: DEBUG: kex algos:[u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'ssh-dss'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] client mac:[u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
paramiko.transport: DEBUG: Ciphers agreed: local=aes128-ctr, remote=aes128-ctr
paramiko.transport: DEBUG: using kex diffie-hellman-group14-sha1; server key type ssh-rsa; cipher: local aes128-ctr, remote aes128-ctr; mac: local hmac-sha1, remote hmac-sha1; compression: local none, remote none
paramiko.transport: DEBUG: Switch to new keys ...
paramiko.transport: DEBUG: Adding ssh-rsa host key for 10.144.31.41: f662631595339bcea0d93948261bf655
paramiko.transport: DEBUG: Trying SSH agent key 9523f82115a1b2102b669b21e8a1084f
paramiko.transport: DEBUG: userauth is OK
paramiko.transport: INFO: Authentication (publickey) failed.
paramiko.transport: DEBUG: userauth is OK
paramiko.transport: INFO: Authentication (password) successful!
sshClient: DEBUG: ===SSH to Host 10.144.31.41 port : 22 SUCCESSFUL===

**Comment by borisstoyanov** [comment]
LGTM.

**Comment by serg38** [comment]
@rhtyd @jburwell @swill @koushik-das @rafaelweingartner @wido This PR has enough of everything. Can one of the committers merge it?

**Comment by rafaelweingartner** [comment]
@serg38, @PaulAngus, @jburwell I was checking this PR, do we need this history of commits? Wouldn't it be better a single commit in this case?

**Comment by jburwell** [comment]
@rafaelweingarter I prefer squashed commits with a commit message with an 80 character summary as the first line and a paragraphs/bullets following explaining the reason for the change and any important details.

**Comment by rafaelweingartner** [comment]
@jburwell me too ;)
I like the idea of a single commit with a commit message of 80 characters, and then a paragraph description, bullets or both that describe the whole work that has been done here.

**Comment by serg38** [comment]
@PaulAngus @jburwell Can we squash commits and merge this one? This will allow us to include 5 more integration test results for other PRs

**Comment by jburwell** [comment]
@serg38 @PaulAngus has been on vacation for the past week.  Since this problem is present in 4.8 and 4.9, could you please retarget this PR to the 4.8 release branch?  Also, as @serg38 suggests, please squash your commits.  We plan to cut the 4.8.2.0, 4.9.1.0, and 4.10.0.0 PRs on 25 Sept 2016,  Therefore, I would like to get this change merged in time for testing of these RCs.

**Comment by serg38** [comment]
@PaulAngus @jburwell @rhtyd This PR was closed without merging. Are we still on track to include the fix to 4.9.1 ?  I can ask @nvazquez to pick this one up if needed.

**Comment by PaulAngus** [comment]
My git foo abandoned me and left a mess ☹
.  I’ll be sending a clean pr later today…


Kind regards,

Paul Angus



VP Technology
paul.angus@shapeblue.com
www.shapeblue.com

**Pull request closed without merging**
