### PR TITLE
UI: Fix route to domain details

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

This PR fixes router link to domain details

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [X] Trivial

### CODE REVIEW

**Comment by Pearl1594** [comment]
@blueorangutan ui

**Comment by shwstppr** [comment]
@Pearl1594 don't think it is related but getting error on navigation,
nav-error

**Comment by Pearl1594** [comment]
Yes @shwstppr  that's something I've been investigating.. It's not related to this PR.. I noticed this on the QA server too..

**Review by utchoang — APPROVED** [review]

**Comment by nvazquez** [comment]
Hi @utchoang have any hint on what could be causing the navigation to back issue? It seems like when clicking the back button the wrong UUID is sent. Anyways this would need a separate issue

**Review by nvazquez — APPROVED** [review]
LGTM

**Pull request merged**
