### PR TITLE
Disable shrinking QCOW2 volumes

### PR DESCRIPTION
**Pull request by ravening**
### Description
Since QCOW2 volumes cannot be resized to lower value in any case,
just disable it in backend.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [X] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [X] Trivial

### CODE REVIEW

**Review by weizhouapache — APPROVED** [review]

**Review by DaanHoogland — COMMENTED** [review]
looks good but can you please put it in a new method with a good descriptive name?

**Comment by shwstppr** [comment]
@ravening I think we can have this in 4.15.1

**Comment by rhtyd** [comment]
ping @ravening ^^

**Comment by rhtyd** [comment]
Ping @ravening

**Comment by ravening** [comment]
> Ping @ravening

@rhtyd done

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Review by rhtyd — APPROVED** [review]

**Comment by slavkap** [comment]
Hi all!
Not so sure how to proceed on this. I spoke with @svenvogel and he confirmed that the SolidFire's volumes are kept in the DB in `QCOW2` format, but their actual format is RAW.  According to the code, this will affect the shrinking of So'slidfire volumes. The same is the case with our plugin (StorPool). Is it alright to revert this change until a better solution is proposed or somebody with this version of CS and Solidfire as primary storage to confirm the problem?

**Comment by shwstppr** [comment]
@slavkap is it better to check format directly in `plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtResizeVolumeCommandWrapper.java' and raise an exception if resize isn't possible?

**Comment by slavkap** [comment]
Yes, this sounds OK. Thanks for the answer and the suggestion, @shwstppr!  :)

**Comment by svenvogel** [comment]
@shwstppr @ravening Sound interesting but its breaks our actually functionality with storepool and solidfire storages. how about revert this change until we have another fix for that. at the moment there is no backward functionality.

**Comment by slavkap** [comment]
@shwstppr, do you want to add a fix (because you propose it), or could I work on a fix for this?

**Comment by shwstppr** [comment]
Not sure but will be easier to test for you @slavkap. I'm happy if you can work on it else I can do it

**Comment by slavkap** [comment]
Thanks, @shwstppr. I will do the fix then :)

**Pull request merged**
