### PR TITLE
ui,api: fix api resourcename and user/project event resource

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

For user and project dashborad event resource details were not showing as shown in admin dashboard.
API, UI shows name of the resource as event resourcename. Changed it to displaytext of the resource for consistency.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):
Before:
Screenshot from 2022-04-26 12-41-39
Screenshot from 2022-04-26 12-43-27

After:
Screenshot from 2022-04-26 12-41-54
Screenshot from 2022-04-26 13-18-14

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by utchoang — APPROVED** [review]
UI Code LGTM!

**Comment by shwstppr** [comment]
@blueorangutan test

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Review by nvazquez — APPROVED** [review]

**Pull request merged**
