### PR TITLE
Fixed Coverity issue "Dereference null return value"

### PR DESCRIPTION
**Pull request by manuiiit**
Fixed Coverity issue "Dereference null return value"

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@manuiiit your change has checkstyle error, can you look at these? (at least I see tabs instead of spaces)

**Comment by manuiiit** [comment]
@mike-tutkowski  I did not find any other possibility where createPhysicalDisk would return null unless is called from NfsManagedStorageAdaptor class.Please correct me if I am wrong.Thanks.

**Comment by mike-tutkowski** [comment]
That is very well true, but I "worry" that a comment that specific would not be updated should the time come when another adaptor does, in fact, return null here.

Also, I think it's possible for people to provide these adaptors to their CloudStack users without donating the code to the ASF. That being the case, we really don't know if anyone's implementation returns null besides that of NfsManagedStorageAdaptor.

It's certainly not a big deal to me (this comment) either way.

You make the call. You have a LGTM from me. :)

**Comment by manuiiit** [comment]
@mike-tutkowski I understood what u said.Updated.Will keep it in mind from next time.Thanks :) .

**Comment by DaanHoogland** [comment]
@mike-tutkowski LGTM if LGTY

**Comment by remibergsma** [comment]
@manuiiit Could you squash the commits as they have no value as separate commits.

@mike-tutkowski @DaanHoogland Let me double check.. you both say LGTM here?

**Comment by DaanHoogland** [comment]
I am alright with this. I was curious if @mike-tutkowski is.

**Comment by mike-tutkowski** [comment]
LGTM

**Pull request merged**
