### PR TITLE
CLOUDSTACK-9835 : To make management server and SSVM to be in time sync

### PR DESCRIPTION
**Pull request by harikrishna-patnala**
Added a new configuration paremetar "ntp.server.list" to configure NTP server ip in NTP settings of SSVM

### CODE REVIEW

**Comment by kishankavala** [comment]
Code LGTM

**Comment by DaanHoogland** [comment]
this seems like a good functionality to me. It would be a shame to limit this to the SSVM. other components would benifit as well. Most noticably the KVM agent, other implementations would be probably to hypervisor specific. thoughts @kishankavala @wido @ustcweizhou?

**Comment by wido** [comment]
I would not touch the KVM Agent. Tools like Puppet, Salt, Chef and such are more then capable to handle the NTP config on a KVm Agent.

So keep this to the SSVM only

**Comment by DaanHoogland** [comment]
ok, we can add anytime anyway
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by harikrishna-patnala** [comment]
Thank you @DaanHoogland  @wido @kishankavala . 
Can we get another LGTM on this PR.

**Comment by rohit57** [comment]
Global setting "ntp.server.list" sucessfully updates "/etc/ntp.conf" in the SSVM. The new pool of NTP servers are added to the existing list making the management server and the SSVM be in time sync with the same pool of NTP servers. 


screenshot 30
screenshot 31

Manually tested. LGTM.

**Comment by cloudmonger** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 787
 Hypervisor xenserver
 NetworkType Advanced
 Passed=107
 Failed=3
 Skipped=12

_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/r2si930m8xxzavs/AAAzNrnoF1fC3auFrvsKo_8-a?dl=0

**Failed tests:**
* test_list_ids_parameter.py

 * ContextSuite context=TestListIdsParams>:setup Failing since 25 runs

* test_volumes.py

 * test_06_download_detached_volume Failed

* test_routers_network_ops.py

 * test_03_RVR_Network_check_router_state Failed


**Skipped tests:**
test_vm_nic_adapter_vmxnet3
test_01_verify_libvirt
test_02_verify_libvirt_after_restart
test_03_verify_libvirt_attach_disk
test_04_verify_guest_lspci
test_05_change_vm_ostype_restart
test_06_verify_guest_lspci_again
test_static_role_account_acls
test_11_ss_nfs_version_on_ssvm
test_nested_virtualization_vmware
test_3d_gpu_support
test_deploy_vgpu_enabled_vm

**Passed test suits:**
test_deploy_vm_with_userdata.py
test_affinity_groups_projects.py
test_portable_publicip.py
test_vm_snapshots.py
test_over_provisioning.py
test_global_settings.py
test_scale_vm.py
test_service_offerings.py
test_routers_iptables_default_policy.py
test_loadbalance.py
test_routers.py
test_reset_vm_on_reboot.py
test_deploy_vms_with_varied_deploymentplanners.py
test_network.py
test_router_dns.py
test_non_contigiousvlan.py
test_login.py
test_deploy_vm_iso.py
test_public_ip_range.py
test_multipleips_per_nic.py
test_metrics_api.py
test_regions.py
test_affinity_groups.py
test_network_acl.py
test_pvlan.py
test_nic.py
test_deploy_vm_root_resize.py
test_resource_detail.py
test_secondary_storage.py
test_vm_life_cycle.py
test_disk_offerings.py

**Pull request merged**
