### PR TITLE
client/pom.xml: fix code coverage is not updated in some modules

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes that code coverage is not updated in some modules

The following modules should have better code coverage with this PR
- cloud-agent
- cloud-api
- cloud-core
- cloud-framework-cluster
- cloud-framework-config
- cloud-framework-db
- cloud-framework-events
- cloud-framework-jobs
- cloud-framework-managed-context
- cloud-framework-security
- cloud-usage
- cloud-utils

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test matrix

**Review by vishesh92 — APPROVED** [review]

**Review by DaanHoogland — APPROVED** [review]
clgtm (for coverage, these dependencies would not be needed in a straight up build)

**Comment by weizhouapache** [comment]
> clgtm (for coverage, these dependencies would not be needed in a straight up build)

I have checked the build logs of current main, the dependecies are actually included in the shaded jar when build client project. 
Except cloud-usage, which is included in cloudstack-usage package.

**Comment by weizhouapache** [comment]
@blueorangutan test matrix

**Comment by weizhouapache** [comment]
@shwstppr 
can you review this ?
smoke tests look ok

**Review by shwstppr — APPROVED** [review]

**Pull request merged**
