### PR TITLE
Make template flags isPublic, isFeatured, isExtractable editable in ui

### PR DESCRIPTION
**Pull request by DK101010**
### Description
This PR add template flags isPublic, isFeatured, isExtractable to ui 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### How Has This Been Tested?

own vmware env

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@DK101010 did you test this as admin? and also as user? did you try to get weird access right issues, i mean?

**Comment by DK101010** [comment]
> @DK101010 did you test this as admin? and also as user? did you try to get weird access right issues, i mean?

Only as admin and to be honest, I have no clue what do you mean. :D

**Comment by DaanHoogland** [comment]
> > @DK101010 did you test this as admin? and also as user? did you try to get weird access right issues, i mean?
> 
> Only as admin and to be honest, I have no clue what do you mean. :D

ok, not sure if a user is allowed the same on template flags as the admin, hence my question. testing will have to prove the pudding

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by DK101010** [comment]
> > > @DK101010 did you test this as admin? and also as user? did you try to get weird access right issues, i mean?
> > 
> > 
> > Only as admin and to be honest, I have no clue what do you mean. :D
> 
> ok, not sure if a user is allowed the same on template flags as the admin, hence my question. testing will have to prove the pudding

Hmm ... good question. Have no Idea. These flags already existed in the old ui. How was it there?

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by davidjumani** [comment]
There exist APIs `updateIsoPermissions` and `updateTemplatePermissions` which do pretty much the exact same thing
It is also available in the UI

Screenshot from 2022-01-27 13-10-39

Screenshot from 2022-01-27 13-10-48

**Comment by DK101010** [comment]
> There exist APIs `updateIsoPermissions` and `updateTemplatePermissions` which do pretty much the exact same thing It is also available in the UI
> 
> Screenshot from 2022-01-27 13-10-39
> 
> Screenshot from 2022-01-27 13-10-48

Oh ok, that is new for me. Thanks for the hint. I'll  close the PR.

**Pull request closed without merging**
