### PR TITLE
Volume migration

### PR DESCRIPTION
**Pull request by DaanHoogland**
## Description

rebase of #3959 to apply on 4.13 first

Fixes: #3958

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@div8cn please find you change here

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by borisstoyanov** [comment]
Looks good, I've managed to reproduce your case by having the secondary storage occupied with more than 90% and then migrated a detached volume to an available primary pool. 

Before migration in pool2 
```
[root@SBLabNestedNFS ref-trl-857-k-M7-boris-stoyanov-kvm-pri2]# ll -lahi
87949354 -rw-r--r--. 1 root root 193K Apr 23 16:39 c2546555-8fc1-4167-b881-15d918072215
```

Migrated to pool1, immediately failed with this in management: 
```
2020-04-23 15:46:32,423 ERROR [c.c.a.ApiAsyncJobDispatcher] (API-Job-Executor-9:ctx-8531963e job-71) (logid:6ce344d9) Unexpected exception while executing org.apache.cloudstack.api.command.admin.volume.MigrateVolumeCmdByAdmin
com.cloud.utils.exception.CloudRuntimeException: Resource [StoragePool:1] is unreachable: Migrate volume failed: can't find a nfs (or cifs) image store to satisfy the need for a staging store
```

And then file was still available in Cloudstack: 
```
[root@SBLabNestedNFS ref-trl-857-k-M7-boris-stoyanov-kvm-pri2]# ll -lahi
87949354 -rw-r--r--. 1 root root 193K Apr 23 16:39 c2546555-8fc1-4167-b881-15d918072215

```

**Comment by andrijapanicsb** [comment]
2 x LGTM/Approval - code changes dead simple, manual functional tests fine.

Merging now in order to cut 4.13.1 RC3, but will get back to the tests that are running atm and anyway run the full test matrix for 4.13.1.0 RC3 once it's out.

**Comment by andrijapanicsb** [comment]
@blueorangutan test

**Pull request merged**
