### PR TITLE
CLOUDSTACK-8761: Replace some profiler.getDuration with profiler.getDurationInMillis fter commit 5557ad55

### PR DESCRIPTION
**Pull request by ustcweizhou**
We got a lot of debugging information in management server log because of this.

### CODE REVIEW

**Comment by karuturi** [comment]
The changes look good to me :+1: from my end.
But, I would like @wilderrodrigues to review this as the profiler was refactored by him in commit 5557ad55880f981c2621a4f411b80e4301469104 (the behavior of getDuration hasnt changed in the refactoring but want to double check)

@ustcweizhou, looks like clustered management server behavior would be affected due to this as the interpretation of config value `cluster.heartbeat.interval` has changed from ns to ms. Can you please log a defect with the actual issue and link it here?

**Comment by ustcweizhou** [comment]
@karuturi @wilderrodrigues I just created a ticket for it. https://issues.apache.org/jira/browse/CLOUDSTACK-8761

**Comment by remibergsma** [comment]
@ustcweizhou Thanks for fixing this!

**Comment by wilderrodrigues** [comment]
@ustcweizhou is just calling the wrapper for the system in millis, which was added to the profiler. For the remaining cases, the nano time will be used (getDuration()).

His use of getDurationInMillis() looks good because inside the method I convert the nanoseconds to milliseconds:

(stopTickNanoSeconds - startTickNanoSeconds) / (long)Math.pow(MILLIS_FACTOR, EXPONENT);

LGTM :+1: 

Cheers,
Wilder

**Comment by karuturi** [comment]
Hi @ustcweizhou Can you use the merge-pr script next time? 

scripts is at https://github.com/apache/cloudstack/blob/master/tools/git/git-pr 
wiki explaining the usage https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61311655

**Comment by ustcweizhou** [comment]
@karuturi Sure, I tried before the merge, but got the following message:

[root@git (master)]# git pr 730
/root/git/master/tools/git/730.json
ERROR: We couldn't grab the PR author. Something went wrong querying the GitHub API.

**Comment by karuturi** [comment]
interesting... I do not see any such error while merging this pr
It uses python to get the author info on the contents of the url https://api.github.com/repos/apache/cloudstack/pulls/730 
```
curl -s https://api.github.com/repos/apache/cloudstack/pulls/730 > ${jsonTmp}
prAuthor=$(cat ${jsonTmp} | python -c "
try:
  import sys, json
  print json.load(sys.stdin)['user']['login'].encode('utf-8').decode('ascii','ignore')
except:
  print ''
")
```

Can you check if the above works manually? 
@remibergsma have you seen any such issue with git pr script?

**Comment by miguelaferreira** [comment]
@karuturi Just tried the code you posted, and this was the result:

```zsh
jsonTmp=pr.json
prAuthor=$(cat ${jsonTmp} | python -c "
try:
  import sys, json
  print json.load(sys.stdin)['user']['login'].encode('utf-8').decode('ascii','ignore')
except:
  print ''
")
echo $prAuthor 

ustcweizhou
```

**Comment by ustcweizhou** [comment]
@remibergsma @karuturi @miguelaferreira 
The 730.json is empty. I finally find the repoName (folder name) should be "cloudstack". In my env, it it not. I will change it. Thanks for you help!

**Comment by miguelaferreira** [comment]
@ustcweizhou good catch!

The idea of that script was to be a simple collection of git commands and assumed that people already understood git. But then we iterated many times over it, adding more and more logic to make it "easier to use". The issue you just bumped into is the downside: the script became to tied up in small details!

We should fix this structurally in the script.

**Comment by ustcweizhou** [comment]
@miguelaferreira good to know it. Thanks.

**Comment by remibergsma** [comment]
@miguelaferreira Yes, this is used for the cloudstack-docs project and such.

**Comment by miguelaferreira** [comment]
Then everyone should align in the name of the repository directory, while having people align in the name of the remotes was too much to ask. Ohhhh the irony...

**Comment by remibergsma** [comment]
@miguelaferreira it seems the default directory name 'cloudstack' (which matches the repo name) makes sense to most people, whereas remotes are defined manually later. I don't see the benefit of renaming it, but that could just be me. I propose not to fix the script, because any more fixing results in more problems later. I've done too many of them recently ;-) Let's document how we expect things to be and that's it.

**Comment by miguelaferreira** [comment]
lets just hope we keep this approach from now on

**Pull request merged**
