### PR TITLE
CLOUDSTACK-9726 Update state is not changed to UPDATE_FAILED in case …

### PR DESCRIPTION
**Pull request by bvbharatk**
…when Host is put in Maintenance Mode.

### CODE REVIEW

**Comment by borisstoyanov** [comment]
@bvbharatk is there unit tests for this change?
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by bvbharatk** [comment]
@borisstoyanov 
We do not have any unit tests for this, but we have rvr  marvin test, to test the basic functionality. 
test/integration/component/maint/test_redundant_router.py .

**Comment by borisstoyanov** [comment]
Thanks @bvbharatk, have you run any tests? If so, could you please share results?

**Comment by bvbharatk** [comment]
@borisstoyanov 
I have only run BVTs, same as what you have already posted. Will also run the above mentioned test and post the results.
thanks,
Bharat.

**Comment by bvbharatk** [comment]
@borisstoyanov 
ran test/integration/component/maint/test_redundant_router.py .

Test create network with non-default guest cidr with redundant routers ... === TestName: test_createRvRNetwork | Status : SUCCESS ===
ok
Test create RvR supported network offering ... === TestName: test_createRvRNetworkOffering | Status : SUCCESS ===
ok
Test redundant router internals ... === TestName: test_redundantVR_internals | Status : SUCCESS ===
ok
Test stop master RVR ... === TestName: test_01_stopMasterRvR | Status : SUCCESS ===
ok
Test stop backup RVR ... === TestName: test_02_stopBackupRvR | Status : SUCCESS ===
ok
Test reboot master RVR ... === TestName: test_03_rebootMasterRvR | Status : SUCCESS ===
ok
Test reboot backup RVR ... === TestName: test_04_rebootBackupRvR | Status : SUCCESS ===
ok
Test stop backup RVR and start instance ... === TestName: test_05_stopBackupRvR_startInstance | Status : SUCCESS ===
ok
Test update network and check if VRs are updated in sequence ... === TestName: test_06_updateVRs_in_sequence | Status : SUCCESS ===
ok

**Comment by harikrishna-patnala** [comment]
Did code review and based on the test result posted by @bvbharat , PR LGTM

Test update network and check if VRs are updated in sequence ... === TestName: test_06_updateVRs_in_sequence | Status : SUCCESS ===
ok

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by Nikhil-99** [comment]
Ran marvin test /test/integration/component/maint/test_redundant_router.py. Test Results:
Test create network with redundant routers ... === TestName: test_createRvRNetwork | Status SUCCESS===
ok
Test create network with non-default guest cidr with redundant routers ... === TestName: test_createRvRNetwork | Status : SUCCESS ===
ok
Test create RvR supported network offering ... === TestName: test_createRvRNetworkOffering | Status : SUCCESS ===
ok
Test redundant router internals ... === TestName: test_redundantVR_internals | Status : SUCCESS ===
ok
Test stop master RVR ... === TestName: test_01_stopMasterRvR | Status : SUCCESS ===
ok
Test stop backup RVR ... === TestName: test_02_stopBackupRvR | Status : SUCCESS ===
ok
Test reboot master RVR ... === TestName: test_03_rebootMasterRvR | Status : SUCCESS ===
ok
Test reboot backup RVR ... === TestName: test_04_rebootBackupRvR | Status : SUCCESS ===
ok
Test stop backup RVR and start instance ... === TestName: test_05_stopBackupRvR_startInstance | Status : SUCCESS ===
ok
Test update network and check if VRs are updated in sequence ... === TestName: test_06_updateVRs_in_sequence | Status : SUCCESS ===
ok

Also manually tested the patch and failed the update network (by enabling maintenance on primary storage). Observed the update state of routers as "UPDATE_FAILED".

img

Results are as expected. LGTM

**Pull request merged**
