### PR TITLE
[DISCUSS] CLOUDSTACK-8652: remove old upgrade code

### PR DESCRIPTION
**Pull request by DaanHoogland**
driven by coverity reported issues with resource leaks in it

### CODE REVIEW

**Comment by wilderrodrigues** [comment]
Excellent, @DaanHoogland! 

LGTM :+1:

**Comment by bhaisaab** [comment]
-1 - this break upgrade-ability for really old cloudstack installations. There is no *necessity* to remove the code, you can choose to ignore coverity and other static analysis issues instead of breaking upgrade paths for really old installations.

Currently, I'm aware of few large cloudstack installations who are going to upgrade from 3.0.x (you might have even noticed a recent fix I made to allow one of such upgrades from 3.0.x to 4.5.x) to 4.5.x or 4.6.x

**Comment by abhinandanprateek** [comment]
I am not sure how severe are the coverity reported issues. If there are customers who may want to upgrade then it is better to wait before depreciating this code. Also if we know of such old cloudstack deployment maybe we can mail them to upgrade or loose the upgrade path.
But till then it will be better if we let this code hang around.

**Comment by jburwell** [comment]
-1 @DaanHoogland what is the reasoning for removing the old upgrade code (please amend the commit to explain the reasoning for posterity)?  As far as I know, we don't have a policy regarding how far back we support upgrades.  Minimally, this commit should include a documentation update that explains how far back upgrades are supported, and the steps required for older users to get up-to-date (e.g. a multi-step upgrade).

**Comment by pdion891** [comment]
+1 for the concept, we need to get rid of old crappy stuff, none of those upgrade path are tested during RC and dev a release. Some of them have been removed from 4.5 release notes because they were not tested.

Although, some upgrade path should remain, maybe from 4.3.x. also, I wouldn't add this in 4.6 but maybe the next one 4.7 or 5.0? Out of curiosity, where the database structure get created/updated from removed code? 

In theory if someone want's to upgrade from something as old a 3.x to 4.6, he would probably need to do some intermediary upgrade, which is fairly standard in the firmware world and anyway, he wouldn't have just cloudstack to upgrade but far probably the hypervisor stack too.

My 2 cents ;)  I'm more in favor of a much more solid app confirmed by coverity then outdated upgrade path to a so-so version.

**Comment by remibergsma** [comment]
@DaanHoogland Shall we close this PR and discuss on list what we want to do?

**Comment by DaanHoogland** [comment]
No momentum or consensus for this kind of work. discussion on dev@ is fine but I expect no technical solution and political/marketing impasse.

**Pull request closed without merging**
