### PR TITLE
Honour isrecursive above listall

### PR DESCRIPTION
**Pull request by davidjumani**
### Description

Fixes https://github.com/apache/cloudstack/issues/4868

Prior to this, if `listall` was set to true, it would recursively list all resources irrespective of the value of `isrecursive`. This PR fixes it

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

#### Before : 
```
(localhost) 🐱 > list accounts filter=name,domain listall=true isrecursive=false
{
  "account": [
    {
      "domain": "ROOT",
      "name": "admin"
    },
    {
      "domain": "ROOT",
      "name": "baremetal-system-account"
    },
    {
      "domain": "domain",
      "name": "domain"
    },
    {
      "domain": "sub",
      "name": "user"
    }
  ],
  "count": 4
}

```

#### After :
```
(localhost) 🐱 > list accounts filter=name,domain listall=true isrecursive=false
{
  "account": [
    {
      "domain": "ROOT",
      "name": "admin"
    },
    {
      "domain": "ROOT",
      "name": "baremetal-system-account"
    }
  ],
  "count": 2
}

```

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@davidjumani , would it make sense to let `isRecursive()` return a different default value, depending on whether `listall` is given? this seems like a very elaborate way to guard against a discrepancy, introducing a lot of null.
I would think an extra bit of check in the existing getter, will greatly reduce the size of the change as well as the complexity of it, and it will limit the check to the API, where I think it belongs.

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@DaanHoogland Good point! I'll make the changes

**Review by DaanHoogland — APPROVED** [review]
code looks good

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan test

**Review by rohityadavcloud — APPROVED** [review]
LGTM but requires manual testing or check/add new unit/marvin tests to cover the new changes.

**Comment by nvazquez** [comment]
@davidjumani can you please fix the conflicts?

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan test

**Comment by davidjumani** [comment]
@blueorangutan test

**Review by nvazquez — APPROVED** [review]
LGTM - manually tested:

- Test domains defined as:
Screen Shot 2022-03-10 at 23 47 17

- Created an account per domain

- As ROOT admin: isrecursive being honoured over listall:
````
(localcloud) 🐱 > list accounts filter=id,name,domain listall=true isrecursive=false
{
  "account": [
    {
      "domain": "ROOT",
      "id": "2ffb598d-9d5e-11ec-8765-0200346f0009",
      "name": "admin"
    },
    {
      "domain": "ROOT",
      "id": "89b3f8d1-8a9d-42fa-8249-b85dc86e29e6",
      "name": "baremetal-system-account"
    }
  ],
  "count": 2
}
(localcloud) 🐱 > list accounts filter=id,name,domain listall=true isrecursive=true
{
  "account": [
    {
      "domain": "ROOT",
      "id": "2ffb598d-9d5e-11ec-8765-0200346f0009",
      "name": "admin"
    },
    {
      "domain": "ROOT",
      "id": "89b3f8d1-8a9d-42fa-8249-b85dc86e29e6",
      "name": "baremetal-system-account"
    },
    {
      "domain": "sub",
      "id": "e7da4a05-1224-4518-9379-1096962173b2",
      "name": "user"
    },
    {
      "domain": "subsub",
      "id": "1fae52cd-bbcf-43bc-8c4b-e41c7197b349",
      "name": "subsubdomadmin"
    },
    {
      "domain": "nested",
      "id": "140e22a8-859d-4ee8-a34c-e198cad9417d",
      "name": "nesteduser"
    }
  ],
  "count": 5
}
````

- As a user on domain sub:
- if 'allow.users.view.all.domain.accounts' = true:
````
(localcloud) 🐱 > list accounts filter=id,name,domain listall=true isrecursive=true
{
  "account": [
    {
      "domain": "sub",
      "id": "e7da4a05-1224-4518-9379-1096962173b2",
      "name": "user"
    }
  ],
  "count": 1
}
(localcloud) 🐱 > list accounts filter=id,name,domain listall=true isrecursive=false
{
  "account": [
    {
      "domain": "sub",
      "id": "e7da4a05-1224-4518-9379-1096962173b2",
      "name": "user"
    }
  ],
  "count": 1
}
````

**Pull request merged**
