### PR TITLE
Fixes for KVM unmanaged instances import on advanced network and VNC password

### PR DESCRIPTION
**Pull request by nvazquez**
### Description

This PR fixes a regression caused by #8465 on advanced zones, import fails with:

````
2024-01-10 12:13:33,234 DEBUG [o.a.c.e.o.NetworkOrchestrator] (API-Job-Executor-3:ctx-991bbe9f job-128 ctx-f49517d4) (logid:d7b8e716) Allocating nic for vm 142272e8-9e2e-407b-9d7e-e9a03b81653c in network Network {"id": 204, "name": "Isolated", "uuid": "9679fac5-e3ac-4694-a57b-beb635340f39", "networkofferingid": 10} during import
2024-01-10 12:13:33,239 ERROR [o.a.c.v.UnmanagedVMsManagerImpl] (API-Job-Executor-3:ctx-991bbe9f job-128 ctx-f49517d4) (logid:d7b8e716) Failed to import NICs while importing vm: i-2-31-VM
com.cloud.exception.InsufficientVirtualNetworkCapacityException: Unable to acquire Guest IP  address for network Network {"id": 204, "name": "Isolated", "uuid": "9679fac5-e3ac-4694-a57b-beb635340f39", "networkofferingid": 10}Scope=interface com.cloud.dc.DataCenter; id=1
	at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator.importNic(NetworkOrchestrator.java:4582)
	at org.apache.cloudstack.vm.UnmanagedVMsManagerImpl.importNic(UnmanagedVMsManagerImpl.java:859)
	at org.apache.cloudstack.vm.UnmanagedVMsManagerImpl.importVirtualMachineInternal(UnmanagedVMsManagerImpl.java:1198)
	at org.apache.cloudstack.vm.UnmanagedVMsManagerImpl.importUnmanagedInstanceFromHypervisor(UnmanagedVMsManagerImpl.java:1511)
	at org.apache.cloudstack.vm.UnmanagedVMsManagerImpl.baseImportInstance(UnmanagedVMsManagerImpl.java:1342)
	at org.apache.cloudstack.vm.UnmanagedVMsManagerImpl.importUnmanagedInstance(UnmanagedVMsManagerImpl.java:1282)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
````

Also, addresses the VNC password field set instead of a fixed string

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by shwstppr** [comment]
Lot many changes to core NIC import logic. This would need testing for both KVM and VMware for different scenarios - advanced/basic zone, with/without user provided IP, different network types.

@nvazquez cc @DaanHoogland would it make sense to revert #8465 and document basic zone support as a limitation at this point? Common code for both KVM and VMware seems to be causing new regressions each day :smile:

**Comment by nvazquez** [comment]
@shwstppr I think we can have this fix without reverting the basic zone support, I have already verified basic and advanced KVM import in automatic and manual cases, will need to double check Vmware imports

**Comment by shwstppr** [comment]
Tested the following cases for VMware VM import in an advanced zone:

1. Import VM with single L2 network NIC - OK
2. Import VM with single Isolated network NIC with auto IP assignment - OK
3. Import VM with single Isolated network NIC with user-provided IP assignment - OK
4. Import VM with single Isolated network NIC with user-provided already taken IP assignment - OK (Fails)
5. Import VM with single Isolated network NIC with user-provided outside range IP assignment - OK (Fails)
6. Import VM with single Shared network NIC with auto IP assignment - OK
7. Import VM with single Shared network NIC with user-provided IP assignment - OK
8. Import VM with single Shared network NIC with user-provided already taken IP assignment - OK (Fails)
9. Import VM with single Shared network NIC with user-provided outside range IP assignment - OK? (Not sure if this should work)
10. Import VM with a L2 network NIC and a shared network NIC with auto IP assignment - OK
11. Import VM with an isolated network NIC and a shared network NIC with auto IP assignment - OK

I guess we also allow VM deployment similar to case#9 (IP outside range)

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by slavkap — APPROVED** [review]
Tested with advanced network with KVM and works with NFS/StorPool/Ceph.
code LGTM

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test matrix

**Comment by shwstppr** [comment]
Merging based on manual testing and trillain results from backend,

```
[SF] Trillian test result (tid-8811)

Environment: vmware-67u3 (x2), Advanced Networking with Mgmt server r8

Total time taken: 48240 seconds

Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr8492-t8811-vmware-67u3.zip

Smoke tests completed. 120 look OK, 1 have errors, 0 did not run

Only failed and skipped tests results shown below:





Test | Result | Time (s) | Test File

--- | --- | --- | ---

test_02_balanced_drs_algorithm | `Failure` | 138.23 | test_cluster_drs.py



[SF] Trillian test result (tid-8810)

Environment: xenserver-71 (x2), Advanced Networking with Mgmt server 7

Total time taken: 43357 seconds

Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr8492-t8810-xenserver-71.zip

Smoke tests completed. 120 look OK, 1 have errors, 0 did not run

Only failed and skipped tests results shown below:





Test | Result | Time (s) | Test File

--- | --- | --- | ---

test_01_cancel_host_maintenace_with_no_migration_jobs | `Error` | 308.71 | test_host_maintenance.py
```

**Review by shwstppr — APPROVED** [review]

**Pull request merged**
