### PR TITLE
[For Tests] Xcp-ng 8.1 support

### PR DESCRIPTION
**Pull request by shwstppr**
## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@shwstppr cc @andrijapanicsb was this for testing only, can this be closed if changes are in #4068 ?

**Comment by shwstppr** [comment]
@rhtyd yes only for tests, can be closed

**Pull request closed without merging**
