### PR TITLE
Honor network.dns.basiczone.updates setting when sending DHCP config …

### PR DESCRIPTION
**Pull request by wido**
…to VRs

When sending the DHCP offerings to the VRs this setting wasn't read properly which made
it default to 'all'.

This causes all DHCP offerings to be send to all VRs instead of just those in the POD.

As VR provisioning can be very time consuming this can drastically reduce deployment time
of the VR.

Signed-off-by: Wido den Hollander <wido@widodh.nl>

### CODE REVIEW

**Comment by wido** [comment]
Ping @rhtyd and @resmo and @ustcweizhou

**Comment by rhtyd** [comment]
@wido can you push -f or rekick Travis, I see some failure.

**Comment by rhtyd** [comment]
LGTM, otherwise (did not test it)

**Comment by wido** [comment]
Done @rhtyd, I changed the name of the variable.

This is running in production at PCextreme's cloud right now with major performance improvements.

**Comment by rhtyd** [comment]
LGTM, thanks @wido 
@blueorangutan package

**Comment by karuturi** [comment]
@rhtyd can you run tests in this?

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by karuturi** [comment]
tests look good. merging

**Comment by luhaijiao** [comment]
Thank you Rajani !


Do you think this one is ready for merging too ?


CLOUDSTACK-9690: Scale CentOS7 VM fails with error #1849




在2017年05月09 11时49分, "Rajani Karuturi"<notifications@github.com>写道:



Thank you @luhaijiao. RC2 is coming :)

**Comment by karuturi** [comment]
@luhaijiao done

**Pull request merged**
