### PR TITLE
FIX s2svpn connection stuck on Pending state

### PR DESCRIPTION
**Pull request by ravening**
## Description

When we try to reset the site 2 site vpn connection while
the VR's are being restarted, the connection enters the
PENDING state and we cant reset the connection.

So change the state from PENDING to disconnected.

Steps to reproduce the issue

1.create a VPC with a tier (vpc-001-001 in vpc-001), create a vm
2.create a VPC with a tier (vpc-002-001 in vpc-002) with different cidr, create a vm
3.create custom gateway for both vpn
4.enable site-to-site vpn on both vpn, and add vpn connection to each other. both should be "Connected"
5.restart vpc-001 with cleanup and monitor it
6.when the first router is destroyed, go to site-to-site vpn page and reset vpn connection.
7.we will get an error "Resource [DataCenter:1] is unreachable: Unable to apply site 2 site VPN configuration, virtual router is not in the right state"
and vpn connection is stuck at Pending
8.When vpc is restarted, go to site-to-site vpn page and reset vpn connection.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
code lgtm

**Comment by DaanHoogland** [comment]
@ravening are you intending this to make it in before 4.15?

**Comment by DaanHoogland** [comment]
cc @PaulAngus @rhtyd

**Comment by ravening** [comment]
> @ravening are you intending this to make it in before 4.15?

@DaanHoogland the base branch is 4.14. so it should make it to 4.15 right?

**Comment by DaanHoogland** [comment]
> > @ravening are you intending this to make it in before 4.15?
> 
> @DaanHoogland the base branch is 4.14. so it should make it to 4.15 right?

only if it gets merged in time

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@rhtyd, is this bug fix ok, to you?

**Review by rhtyd — APPROVED** [review]
LGTM, the issue is in case of intermittent issues; this will cycle and always cause vpn to restart; so it could annoy s2s/connected parties

**Pull request merged**
