### PR TITLE
manual mapped ldap fix

### PR DESCRIPTION
**Pull request by DaanHoogland**
## Description
ldap accounts that where not automatically imported but mapped manually were not able to login. fixed.

see https://lists.apache.org/thread.html/43ef6cc4bcf12340f8ac1c05fbcb7bf3afc3d6ed3b05ff509b9c6152@%3Cusers.cloudstack.apache.org%3E

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

this has only unit tests as an integration test requires an external system

it was tested manually using an openldap and a microsoft ad implementation

## Checklist:

- [ ] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

@blueorangutan package

### CODE REVIEW

**Comment by rafaelweingartner** [comment]
@DaanHoogland you are missing the licensing at `LdapAuthenticatorTest.java`

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by PaulAngus** [comment]
LGTM
Tested with login to Active Directory on Windows 2012r2 Server.
Could log in with user account, where previously could not.

**Pull request merged**
