### PR TITLE
CLOUDSTACK-9025: Fixed Unable to deploy VM instance from template if …

### PR DESCRIPTION
**Pull request by anshul1886**
…template spin from linked clone snapshot

Re-introduce the code to send CopyCommand to hypervisor host instead of SSVM which was changed due to code cleanup in PR #1124.

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rafaelweingartner** [comment]
@rhtyd this PR can be closed as we are all working towards a solution for this problem at  #2315 .

**Comment by rhtyd** [comment]
The PR author is requested to take suitable actions.

**Comment by DaanHoogland** [comment]
@anshul1886 do you agree to close this PR?

**Pull request closed without merging**
