### PR TITLE
UI: Support to upload resource icons

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

This PR provides support for adding resource icons/ images for Zones, templates, ISOs, UserVMs, Networks, VPCs, Domains, Projects, Accounts and users which will helps users/admins in future to identify special-purpose templates and VMs using custom icons in UI. Some of the attributes of this feature includes:
- Users will inherit the account's icon if not present. 
- Isolated networks tiers of a VPC network will inherit the Icon of the VPC network if present.
- Resources that support uploading custom icons have a small symbol    image against the logo.
- Users with permission to access resources can upload/update and delete the icons. If no icons have been provided, it follows the normal behavior. Info Card view will also display the corresponding resource's icons if present.
- The Deploy VM wizard will show the list of zones in the form of cards in the number of zones are <= 8
image
Else, it defaults to the usual list view but will display the icon beside the zone name 

- The capacity dashboard view will also display the zone icons beside the zone names as shown above
- The project list view (Used for switching to different projects available, on the Dashboard page) will also list the project icons beside the project names
test4

- List view of all resources that support resource icons will now display the icons beside the name
- The user/account icon will be displayed at the top right corner of the landing / dashboard page 
test3

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

### CODE REVIEW

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
\o/

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan test

**Comment by Pearl1594** [comment]
@blueorangutan test

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan test

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan test

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan ui

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan test matrix

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan test centos7 vmware-65u2

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan test

**Comment by Pearl1594** [comment]
@blueorangutan test

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan test

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan ui

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan ui

**Comment by Pearl1594** [comment]
@blueorangutan ui

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by vladimirpetrov** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan ui

**Comment by vladimirpetrov** [comment]
@blueorangutan package

**Comment by vladimirpetrov** [comment]
@blueorangutan test keepEnv

**Comment by vladimirpetrov** [comment]
@blueorangutan package

**Comment by vladimirpetrov** [comment]
@blueorangutan test keepEnv

**Comment by vladimirpetrov** [comment]
@blueorangutan package

**Comment by vladimirpetrov** [comment]
@blueorangutan package

**Comment by vladimirpetrov** [comment]
@blueorangutan test

**Comment by vladimirpetrov** [comment]
Manual tests:

Support for adding/removing resource icons for Zones, templates, ISOs, UserVMs, Networks, VPCs, Domains, Projects, Accounts and users - OK

Users should inherit the account's icon if not present - OK

Isolated networks tiers of a VPC network should inherit the Icon of the VPC network if present - OK

Resources that support uploading custom icons should have a small symbol image against the logo - OK

Regular users should be also able to add/remove resource icons - OK

Info Card view will also display the corresponding resource's icons if present - OK

The Deploy VM wizard should show the list of zones in the form of cards in the number of zones less than 8. Otherwise, it defaults to the usual list view but will display the icon beside the zone name - OK

The capacity dashboard view should also display the zone icons beside the zone names on the selection drop-down - OK

The project list view should list the project icons beside the project names - OK

List view of all resources that support resource icons will now display the icons beside the name - OK

The user/account icon will be displayed at the top right corner of the landing / dashboard page - OK

VM from default/custom template and ISO custom icon inheritance - OK

**Comment by vladimirpetrov** [comment]
@blueorangutan test

**Review by vladimirpetrov — APPROVED** [review]
LGTM based on manual and automated testing.

**Comment by alexandremattioli** [comment]
LGTM

**Comment by rhtyd** [comment]
@Pearl1594 can you fix the conflicts?

**Comment by Pearl1594** [comment]
Sorry @rhtyd I don't see any conflicts

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan test

**Review by shwstppr — APPROVED** [review]

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan test

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
LGTM - this has passed manual and smoketests + 2xLGTMs; can be merged after the final smoketests run.

**Review by nvazquez — APPROVED** [review]
LGTM

**Comment by rhtyd** [comment]
Nice!

**Pull request merged**
