### PR TITLE
CID-1338387: Deletion of method endPointSelector.selectHypervisorHost

### PR DESCRIPTION
**Pull request by rafaelweingartner**
Following the discussions and analysis presented on PR #1056 create by @DaanHoogland
This PR is intended to push those changes that were discussed there regarding the of endPointSelector.selectHypervisorHost method.

### CODE REVIEW

**Comment by DaanHoogland** [comment]
LGTM: less is more, an integrations test run on it is of course the minimum. @remibergsma can you queue it?

**Comment by rafaelweingartner** [comment]
I have being wanting to ask you guys about those integration tests. Isn´t it possible for us to run those tests automatically every time a PR is created or when it receives new commits?

**Comment by runseb** [comment]
@rafaelweingartner there has been lots of discussion on the list about testing. The TravisCI setup is supposed to do part of it, and we can also trigger the tests as jenkins Jobs.There are problems with the TravisCI setup, it might be a good item to have your group tackle.

**Comment by rafaelweingartner** [comment]
I was thinking about that. Starting in January we will have some extra time, then we might have a look at that.

**Comment by remibergsma** [comment]
LGTM based on these tests:

```
nosetests --with-marvin --marvin-config=${marvinCfg} -s -a tags=advanced,required_hardware=true \
component/test_vpc_redundant.py \
component/test_routers_iptables_default_policy.py \
component/test_routers_network_ops.py \
component/test_vpc_router_nics.py \
smoke/test_loadbalance.py \
smoke/test_internal_lb.py \
smoke/test_ssvm.py \
smoke/test_network.py

```

Result:

```
Create a redundant VPC with two networks with two VMs in each network ... === TestName: test_01_create_redundant_VPC_2tiers_4VMs_4IPs_4PF_ACL | Status : SUCCESS ===
ok
Create a redundant VPC with two networks with two VMs in each network and check default routes ... === TestName: test_02_redundant_VPC_default_routes | Status : SUCCESS ===
ok
Create a redundant VPC with two networks with two VMs in each network ... === TestName: test_03_create_redundant_VPC_1tier_2VMs_2IPs_2PF_ACL_reboot_routers | Status : SUCCESS ===
ok
Test iptables default INPUT/FORWARD policy on RouterVM ... === TestName: test_02_routervm_iptables_policies | Status : SUCCESS ===
ok
Test iptables default INPUT/FORWARD policies on VPC router ... === TestName: test_01_single_VPC_iptables_policies | Status : SUCCESS ===
ok
Test redundant router internals ... === TestName: test_01_isolate_network_FW_PF_default_routes_egress_true | Status : SUCCESS ===
ok
Test redundant router internals ... === TestName: test_02_isolate_network_FW_PF_default_routes_egress_false | Status : SUCCESS ===
ok
Test redundant router internals ... === TestName: test_01_RVR_Network_FW_PF_SSH_default_routes_egress_true | Status : SUCCESS ===
ok
Test redundant router internals ... === TestName: test_02_RVR_Network_FW_PF_SSH_default_routes_egress_false | Status : SUCCESS ===
ok
Create a VPC with two networks with one VM in each network and test nics after destroy ... === TestName: test_01_VPC_nics_after_destroy | Status : SUCCESS ===
ok
Create a VPC with two networks with one VM in each network and test default routes ... === TestName: test_02_VPC_default_routes | Status : SUCCESS ===
ok
Check the password file in the Router VM ... === TestName: test_isolate_network_password_server | Status : SUCCESS ===
ok
Check that the /etc/dhcphosts.txt doesn't contain duplicate IPs ... === TestName: test_router_dhcphosts | Status : SUCCESS ===
ok
Test to create Load balancing rule with source NAT ... === TestName: test_01_create_lb_rule_src_nat | Status : SUCCESS ===
ok
Test to create Load balancing rule with non source NAT ... === TestName: test_02_create_lb_rule_non_nat | Status : SUCCESS ===
ok
Test for assign & removing load balancing rule ... === TestName: test_assign_and_removal_lb | Status : SUCCESS ===
ok
Test to verify access to loadbalancer haproxy admin stats page ... === TestName: test02_internallb_haproxy_stats_on_all_interfaces | Status : SUCCESS ===
ok
Test create, assign, remove of an Internal LB with roundrobin http traffic to 3 vm's ... === TestName: test_01_internallb_roundrobin_1VPC_3VM_HTTP_port80 | Status : SUCCESS ===
ok
Test SSVM Internals ... === TestName: test_03_ssvm_internals | Status : SUCCESS ===
ok
Test CPVM Internals ... === TestName: test_04_cpvm_internals | Status : SUCCESS ===
ok
Test stop SSVM ... === TestName: test_05_stop_ssvm | Status : SUCCESS ===
ok
Test stop CPVM ... === TestName: test_06_stop_cpvm | Status : SUCCESS ===
ok
Test reboot SSVM ... === TestName: test_07_reboot_ssvm | Status : SUCCESS ===
ok
Test reboot CPVM ... === TestName: test_08_reboot_cpvm | Status : SUCCESS ===
ok
Test destroy SSVM ... === TestName: test_09_destroy_ssvm | Status : SUCCESS ===
ok
Test destroy CPVM ... === TestName: test_10_destroy_cpvm | Status : SUCCESS ===
ok
Test Remote Access VPN in VPC ... === TestName: test_vpc_remote_access_vpn | Status : SUCCESS ===
ok
Test VPN in VPC ... === TestName: test_vpc_site2site_vpn | Status : SUCCESS ===
ok
Test for port forwarding on source NAT ... === TestName: test_01_port_fwd_on_src_nat | Status : SUCCESS ===
ok
Test for port forwarding on non source NAT ... === TestName: test_02_port_fwd_on_non_src_nat | Status : SUCCESS ===
ok
Test for reboot router ... === TestName: test_reboot_router | Status : SUCCESS ===
ok
Test for Router rules for network rules on acquired public IP ... === TestName: test_network_rules_acquired_public_ip_1_static_nat_rule | Status : SUCCESS ===
ok
Test for Router rules for network rules on acquired public IP ... === TestName: test_network_rules_acquired_public_ip_2_nat_rule | Status : SUCCESS ===
ok
Test for Router rules for network rules on acquired public IP ... === TestName: test_network_rules_acquired_public_ip_3_Load_Balancer_Rule | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 34 tests in 18242.963s

OK
```


And:

```
nosetests --with-marvin --marvin-config=${marvinCfg} -s -a tags=advanced,required_hardware=false \
smoke/test_routers.py \
smoke/test_network_acl.py \
smoke/test_privategw_acl.py \
smoke/test_reset_vm_on_reboot.py \
smoke/test_vm_life_cycle.py \
smoke/test_vpc_vpn.py \
smoke/test_service_offerings.py \
component/test_vpc_offerings.py \
component/test_vpc_routers.py
```

Result:

```
Test router internal advanced zone ... === TestName: test_02_router_internal_adv | Status : SUCCESS ===
ok
Test restart network ... === TestName: test_03_restart_network_cleanup | Status : SUCCESS ===
ok
Test router basic setup ... === TestName: test_05_router_basic | Status : SUCCESS ===
ok
Test router advanced setup ... === TestName: test_06_router_advanced | Status : SUCCESS ===
ok
Test stop router ... === TestName: test_07_stop_router | Status : SUCCESS ===
ok
Test start router ... === TestName: test_08_start_router | Status : SUCCESS ===
ok
Test reboot router ... === TestName: test_09_reboot_router | Status : SUCCESS ===
ok
test_privategw_acl (integration.smoke.test_privategw_acl.TestPrivateGwACL) ... === TestName: test_privategw_acl | Status : SUCCESS ===
ok
Test reset virtual machine on reboot ... === TestName: test_01_reset_vm_on_reboot | Status : SUCCESS ===
ok
Test advanced zone virtual router ... === TestName: test_advZoneVirtualRouter | Status : SUCCESS ===
ok
Test Deploy Virtual Machine ... === TestName: test_deploy_vm | Status : SUCCESS ===
ok
Test Multiple Deploy Virtual Machine ... === TestName: test_deploy_vm_multiple | Status : SUCCESS ===
ok
Test Stop Virtual Machine ... === TestName: test_01_stop_vm | Status : SUCCESS ===
ok
Test Start Virtual Machine ... === TestName: test_02_start_vm | Status : SUCCESS ===
ok
Test Reboot Virtual Machine ... === TestName: test_03_reboot_vm | Status : SUCCESS ===
ok
Test destroy Virtual Machine ... === TestName: test_06_destroy_vm | Status : SUCCESS ===
ok
Test recover Virtual Machine ... === TestName: test_07_restore_vm | Status : SUCCESS ===
ok
Test migrate VM ... === TestName: test_08_migrate_vm | Status : SUCCESS ===
ok
Test destroy(expunge) Virtual Machine ... === TestName: test_09_expunge_vm | Status : SUCCESS ===
ok
Test to create service offering ... === TestName: test_01_create_service_offering | Status : SUCCESS ===
ok
Test to update existing service offering ... === TestName: test_02_edit_service_offering | Status : SUCCESS ===
ok
Test to delete service offering ... === TestName: test_03_delete_service_offering | Status : SUCCESS ===
ok
Test for delete account ... === TestName: test_delete_account | Status : SUCCESS ===
ok
Test for Associate/Disassociate public IP address for admin account ... === TestName: test_public_ip_admin_account | Status : SUCCESS ===
ok
Test for Associate/Disassociate public IP address for user account ... === TestName: test_public_ip_user_account | Status : SUCCESS ===
ok
Test for release public IP address ... === TestName: test_releaseIP | Status : SUCCESS ===
ok
Test create VPC offering ... === TestName: test_01_create_vpc_offering | Status : SUCCESS ===
ok
Test VPC offering without load balancing service ... === TestName: test_03_vpc_off_without_lb | Status : SUCCESS ===
ok
Test VPC offering without static NAT service ... === TestName: test_04_vpc_off_without_static_nat | Status : SUCCESS ===
ok
Test VPC offering without port forwarding service ... === TestName: test_05_vpc_off_without_pf | Status : SUCCESS ===
ok
Test VPC offering with invalid services ... === TestName: test_06_vpc_off_invalid_services | Status : SUCCESS ===
ok
Test update VPC offering ... === TestName: test_07_update_vpc_off | Status : SUCCESS ===
ok
Test list VPC offering ... === TestName: test_08_list_vpc_off | Status : SUCCESS ===
test_09_create_redundant_vpc_offering (integration.component.test_vpc_offerings.TestVPCOffering) ... === TestName: test_09_create_redundant_vpc_offering | Status : SUCCESS ===
ok
Test start/stop of router after addition of one guest network ... === TestName: test_01_start_stop_router_after_addition_of_one_guest_network | Status : SUCCESS ===
ok
Test reboot of router after addition of one guest network ... === TestName: test_02_reboot_router_after_addition_of_one_guest_network | Status : SUCCESS ===
ok
Test to change service offering of router after addition of one guest network ... === TestName: test_04_chg_srv_off_router_after_addition_of_one_guest_network | Status : SUCCESS ===
ok
Test destroy of router after addition of one guest network ... === TestName: test_05_destroy_router_after_addition_of_one_guest_network | Status : SUCCESS ===
ok
Test to stop and start router after creation of VPC ... === TestName: test_01_stop_start_router_after_creating_vpc | Status : SUCCESS ===
ok
Test to reboot the router after creating a VPC ... === TestName: test_02_reboot_router_after_creating_vpc | Status : SUCCESS ===
ok
Tests to change service offering of the Router after ... === TestName: test_04_change_service_offerring_vpc | Status : SUCCESS ===
ok
Test to destroy the router after creating a VPC ... === TestName: test_05_destroy_router_after_creating_vpc | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 42 tests in 8828.081s

OK
```

I didn't test the actual feature. This just shows it didn't break anything else.

**Comment by bhaisaab** [comment]
LGTM, @rafaelweingartner can you please rebase against latest master so we can merge this

**Comment by rafaelweingartner** [comment]
@bhaisaab rebased

**Comment by bhaisaab** [comment]
@rafaelweingartner thanks; @remibergsma should we let this be merged considering your integration test result, or you want to re-run them?

**Comment by rafaelweingartner** [comment]
@DaanHoogland what do you think about this one ?
Tests were executed, reviews done.
I think we forgot it, should we go ahead and merge it?

**Comment by DaanHoogland** [comment]
@rafaelweingartner , There is a question addressed to @remibergsma awaiting answer. Other then that, yes.

**Comment by rafaelweingartner** [comment]
That is right, sorry I did not pay much attention.
I will be waiting his answer

**Comment by rafaelweingartner** [comment]
@swill, @DaanHoogland 
What about this one?
I have just rebased it.

**Comment by rhtyd** [comment]
@rafaelweingartner please rebase against master and update on status of your PR?

Looks like this can be merged once CI tested by @swill 

tag:easypr

**Comment by swill** [comment]
I can prioritize CI on this one as it is ready otherwise.  It is worth doing a test run since a lot has happened since this was rebased.  Thx...

**Comment by swill** [comment]
### CI RESULTS

```
Tests Run: 85
  Skipped: 0
   Failed: 2
   Errors: 0
 Duration: 4h 37m 42s
```

**Summary of the problem(s):**
```
FAIL: Check the password file in the Router VM
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/git/cs1/cloudstack/test/integration/smoke/test_password_server.py", line 348, in test_isolate_network_password_server
    self.test_password_file_not_empty(self.vm_1, router)
  File "/data/git/cs1/cloudstack/test/integration/smoke/test_password_server.py", line 229, in test_password_file_not_empty
    "Password file is empty or doesn't exist!")
AssertionError: Password file is empty or doesn't exist!
----------------------------------------------------------------------
Additional details in: /tmp/MarvinLogs/test_network_UOPAVK/results.txt
```

```
FAIL: Test redundant router internals
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/git/cs1/cloudstack/test/integration/smoke/test_routers_network_ops.py", line 483, in test_02_RVR_Network_FW_PF_SSH_default_routes_egress_false
    "Attempt to retrieve google.com index page should be successful once rule is added!"
AssertionError: Attempt to retrieve google.com index page should be successful once rule is added!
----------------------------------------------------------------------
Additional details in: /tmp/MarvinLogs/test_network_UOPAVK/results.txt
```



**Associated Uploads**

**`/tmp/MarvinLogs/DeployDataCenter__May_10_2016_05_41_43_JOKZE2:`**
* [dc_entries.obj](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1124/tmp/MarvinLogs/DeployDataCenter__May_10_2016_05_41_43_JOKZE2/dc_entries.obj)
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1124/tmp/MarvinLogs/DeployDataCenter__May_10_2016_05_41_43_JOKZE2/failed_plus_exceptions.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1124/tmp/MarvinLogs/DeployDataCenter__May_10_2016_05_41_43_JOKZE2/runinfo.txt)

**`/tmp/MarvinLogs/test_network_UOPAVK:`**
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1124/tmp/MarvinLogs/test_network_UOPAVK/failed_plus_exceptions.txt)
* [results.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1124/tmp/MarvinLogs/test_network_UOPAVK/results.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1124/tmp/MarvinLogs/test_network_UOPAVK/runinfo.txt)

**`/tmp/MarvinLogs/test_vpc_routers_PSKY63:`**
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1124/tmp/MarvinLogs/test_vpc_routers_PSKY63/failed_plus_exceptions.txt)
* [results.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1124/tmp/MarvinLogs/test_vpc_routers_PSKY63/results.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1124/tmp/MarvinLogs/test_vpc_routers_PSKY63/runinfo.txt)


Uploads will be available until `2016-07-10 02:00:00 +0200 CEST`

*Comment created by [`upr comment`](https://github.com/cloudops/upr).*

**Comment by swill** [comment]
This one is good to go.  The connectivity issue is related to my environment.  I reran the password test and it passed the second time, so that is not a problem either.  I will add this to the merge queue...

**Comment by anshul1886** [comment]
@rafaelweingartner @DaanHoogland Removing method has reintroduced bug https://issues.apache.org/jira/browse/CLOUDSTACK-9025. Main purpose of `getCommandHostDelegation` method is served through this method `endPointSelector.selectHypervisorHost`. For example by default `CopyCommand` involving only image stores goes to SSVM but for some hypervisors there is some optimisation done and can be directly handled by hypervisor agent. With this method we can change that default behaviour. And the removed method was giving us that different endpoint.

**Comment by rafaelweingartner** [comment]
Hi @anshul1886, 
I have reviewed this method in depth with @DaanHoogland and it was not doing what you described.
The whole discussion is found here: https://github.com/apache/cloudstack/pull/1056

The work flow you describe makes sense and I understand why one would implement it. However, that is not what the removed method was doing. There were no guarantees on which "hosts" would be taken to execute methods; that was quite odd.
I would suggest adding the workflow you described as a new feature if we do not have something similar yet.

**Comment by anshul1886** [comment]
@rafaelweingartner I have already gone through that discussion. I agree with you that in some scenarios that method may not work. But in most of the scenarios that method would work as most of the times user have only one kind of hypervisor in a zone. As you have observed that method is selecting one host with hypervisor_type not null i.e. we are ignoring system VMs. My intention to comment here was to point out scenario if we are not sure of reason for introduction of method then we cannot simply delete it as that may break something which has happened.

**Comment by rafaelweingartner** [comment]
I do not know what was(is?) broken. Can you explain some things for me?

You say:

> For example by default CopyCommand involving only image stores goes to SSVM but for some hypervisors there is some optimisation done and can be directly handled by hypervisor agent. With this method we can change that default behaviour. And the removed method was giving us that different endpoint.


And you also said that this was reported in https://issues.apache.org/jira/browse/CLOUDSTACK-9025.
Is the PR responsible to close the #CloudStack-9025 ticket the #1030/#1176 that is linked to that ticket?
Reading that ticket:

> As default, CloudStack create linked clone snapshot for VM instance . When we take a snapshot for the VM, and create a template based on such snapshot, CloudStack only download incremental VHD as template file, as a result, the VM instance fail to deploy as it is incomplete.

For me, the ticket you mention does not seem to be related to the optimization you are talking about. If I only consider the ticket information, nothing should be working right (by that ticket VMs should not start without that fix)? You said that this PR removed the code introduced to solve the aforementioned ticket. The interesting part is that we did not remove the code introduced in #1030/#1176, the code is still there. We are only not using a method that was and is (at least for me) not making much sense. The removed method is not introduced in #1030/#1176.

We only removed the method
`EndPoint` ep = endPointSelector.selectHypervisorHost(new ZoneScope(host.getDataCenterId()));`

BTW: I use, and I know quite some production systems that use multiple hypervisors types per zone, so CloudStack has to decide if it adversities that multiple are supported, but not per zone, then this has to be clear.

**Pull request merged**
