### PR TITLE
ui: fix add zone dialog for fix errors

### LINKED ISSUE #7194: No way to fix errors after a failure on 'Add zone' dialog
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.18 nightly
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

If there's a problem during the 'Add zone' process and the user tries to go back to fix them, the dialog gets stuck.

##### STEPS TO REPRODUCE

~~~
Try to add a new advanced (core) zone and deliberately leave some errors in the dialog. After the error message while creating the zone, try to fix them.
~~~

##### EXPECTED RESULTS

~~~
There should be a way to fix the errors.
~~~

##### ACTUAL RESULTS

~~~
The dialog gets stuck with no way to fix the errors. NOTE: It works fine on 4.17.
~~~

One example of an error during zone creation:
image

and the dialog when you try to fix the error:
image

another example - after a different kind of error:
image

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #7194

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):

https://user-images.githubusercontent.com/153340/218449970-d2df73be-c284-4ffa-bb48-1dce8af1d149.mp4

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan ui

**Review by nvazquez — APPROVED** [review]
LGTM - manually tested adding an invalid zone, Fix errors gets back to the previous steps to fix the issues

**Comment by DaanHoogland** [comment]
> LGTM - manually tested adding an invalid zone, Fix errors gets back to the previous steps to fix the issues

same here, tested in qa and code looks good

**Review by DaanHoogland — APPROVED** [review]

**Comment by weizhouapache** [comment]
verified ok.

**Pull request merged**
