### PR TITLE
fix failures with test_multiple_nic_support.py

### PR DESCRIPTION
**Pull request by ustcweizhou**
### Description

This PR fixes a failure with integration test test_multiple_nic_support.py

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [X] Trivial

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
merely skipping when the right conditions aren't met. lgtm

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
@blueorangutan package

**Review by rhtyd — APPROVED** [review]

**Comment by DaanHoogland** [comment]
only change is in a component test so running smoke tests is not relevant. @borisstoyanov @vladimirpetrov care to do the honours?

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@blueorangutan test centos7 kvm-centos7 keepEnv

**Pull request merged**
