### PR TITLE
UI: Upgrade ant-design-vue to version 3.x

### PR DESCRIPTION
**Pull request by utchoang**
### Description
This PR for Fixes https://github.com/apache/cloudstack/issues/6342. Upgrade ant-design-vue to version 3.x. Related https://www.antdv.com/docs/vue/migration-v3.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by rohityadavcloud** [comment]
ping @utchoang is this ready for review/testing or needs more work?

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan ui

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
ping @utchoang can you fix the conflicts?

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by rohityadavcloud** [comment]
@blueorangutan ui

**Comment by rohityadavcloud** [comment]
Ping Hi @utchoang can you advise if this is finally ready for review and testing? Asking as we can then target for 4.18.0.0 (in H2 this year) or move to 4.19.0.0 (next year)?

**Comment by utchoang** [comment]
@rohityadavcloud It is ready for review now. Thanks.

**Comment by rohityadavcloud** [comment]
Thanks @utchoang
Assigned to @shwstppr @harikrishna-patnala cc @borisstoyanov @vladimirpetrov , to advice if review/testing with some confidence is achievable for 4.18.0.0 or should this be moved to the next milestone. (I think a full test plan executing will be required for this)
https://github.com/apache/cloudstack-primate/blob/master/.github/ISSUE_TEMPLATE/smoke_test_plan.md
https://github.com/apache/cloudstack-primate/blob/master/.github/ISSUE_TEMPLATE/test_full_plan.md

**Review by RodrigoDLopez — CHANGES_REQUESTED** [review]
I ran some manual tests with this patch and verified that some filters are not working properly by throwing an exception in the browser console.
For example, on the Volumes screen, when you try to filter by name. Several other pages have the same behavior, `Public IP addresses`, `Templates`, `ISOs`, `Events`, `Roles`, `Accounts`, `Infrastructure -> Zones -> Events`, `Hosts`, `Global Settings`. Therefore, I ask you to check with other filters within the system and correct them if necessary.

The `Network service provider` menu inside `Physical network` has broken the position of list elements. The spacing between elements has also undergone unwanted changes.

The buttons to add new service, disk and network offerings (i.e. `add disk offering`, `add service offering`, `add vpc`, `add compute offering`) do not load the form as expected, in addition to throwing errors in the browser console.

Could you re-check the changes and notify us when you're ready for review again?

**Comment by utchoang** [comment]
@RodrigoDLopez Thank you for your review. I have rechecked according to the issues you mentioned but found no similar error:
1. The filters still work fine:
image
image

2. Network service providers -> fixed
image

3. The form adding new offerings still work fine:
image

About (1) and (3) I find it still working fine, you can update to the latest and try again, or you can try here http://qa.cloudstack.cloud:8080/client/pr/6369

**Comment by RodrigoDLopez** [comment]
> @RodrigoDLopez Thank you for your review. I have rechecked according to the issues you mentioned but found no similar error:
> 
> 1. The filters still work fine:
>    image
>    image
> 2. Network service providers -> fixed
>    image
> 3. The form adding new offerings still work fine:
>    image
> 
> About (1) and (3) I find it still working fine, you can update to the latest and try again, or you can try here http://qa.cloudstack.cloud:8080/client/pr/6369

I expressed myself badly, the error occurs (in some pages) when we try to order the list, per example by name.  The style of the Network service providers page has been corrected. And the form error could not be reproduced again, I believe it was caused by some inconsistency in my lab.

image

I will take some free time to re-evaluate your proposal and report back if I find any errors.

**Review by shwstppr — CHANGES_REQUESTED** [review]
@utchoang I'm facing few issues:
- On any view with table when I click on the column header for sorting, view becomes unusable and list disappears
[lists.webm](https://user-images.githubusercontent.com/153340/182573720-5eb27a35-7b3f-45b2-ac8f-bc8032715d9c.webm)

- On Import-export Instance view, similar issue as soon as I select an item
[import-export.webm](https://user-images.githubusercontent.com/153340/182573778-2ef15749-8b1b-4070-8d74-95a4e990287c.webm)

**Comment by utchoang** [comment]
@shwstppr Thank you for your comment. About table sort, I've fixed it in https://github.com/apache/cloudstack/pull/6369/commits/48123e3c25f54682868b1248f452ede987db302e
And the Import-export Instance view. I'll check it.

**Comment by rohityadavcloud** [comment]
@utchoang could you try and execute a whole and thorough UI test plan for example - https://github.com/apache/cloudstack-primate/blob/master/.github/ISSUE_TEMPLATE/test_full_plan.md
Otherwise, I worry we merge this and spend the next quarter fixing bugs from migrating to new version of andv/vue.

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by utchoang** [comment]
@rohityadavcloud @shwstppr I have run the test according to the UI test plan and have a few tweaks. Please review again. Thanks.

**Comment by rohityadavcloud** [comment]
@utchoang can you fix the conflicts then we can perhaps test this again cc @shwstppr ?

**Comment by rohityadavcloud** [comment]
@utchoang can you confirm if you've done a round of full tests [1] as root admin, domain admin and normal account user. Very interested to getting this in soon, thanks for your PR.

[1] see https://github.com/apache/cloudstack/blob/main/ui/docs/full-test-plan.template.md

**Comment by utchoang** [comment]
@rohityadavcloud Starting today, I will stop working at Cloudstack due to a job change. I will leave this PR as a reference for the following members. Hopefully, it will help other members continue with this.

**Comment by rohityadavcloud** [comment]
@utchoang thanks for letting us know, I hope to see you around (psst. we're hiring in case ;)).

**Comment by rohityadavcloud** [comment]
Closing this as this is continued at https://github.com/apache/cloudstack/pull/7306

**Pull request closed without merging**
