### PR TITLE
Update debian packaging

### PR DESCRIPTION
**Pull request by rsafonseca**
This fixes build issue with  http://jenkins.buildacloud.org/view/4.4/job/cloudstack-4.4-package-deb/
Reduce source package size (was including .git)
Fix a couple of dpkg-buildpackage warnings
Remove dependency on changing version on changelog to be able to build package after changing pom.xml
Remove nasty hack for snapshot versions on debian/rules

### CODE REVIEW

**Comment by DaanHoogland** [comment]
getting impatient; debian packaging is not testied in travic and asfbot says go; merging

**Comment by bhaisaab** [comment]
@rsafonseca somehow asfgit failed to close this PR; please close it manually; the PR is merged on 4.4 now: e6f81dbbbc8b597755007d9e6d247d2d6ec6c74c

**Comment by rsafonseca** [comment]
yeah.. asfbot seems to only monitor master :)
closing...

**Comment by DaanHoogland** [comment]
there is a ticket open for that at infra

On Thu, Jun 4, 2015 at 12:23 AM, Rafael da Fonseca <notifications@github.com
> wrote:

> yeah.. asfbot seems to only monitor master :)
> closing...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/cloudstack/pull/339#issuecomment-108631632>.
>



-- 
Daan

**Pull request closed without merging**
