### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by radu-stefanache**
Spotted this using Elasticsearch .

### CODE REVIEW

**Comment by milamberspace** [comment]
Good catch!
LGTM

**Comment by remibergsma** [comment]
@radu-stefanache Thanks! Could you please remove the merge commit? You can do so by squashing them together and force push to your branch. The PR will then get updated after which I'll merge it.

**Comment by resmo** [comment]
+1

**Comment by wido** [comment]
LGTM

**Pull request merged**
