### PR TITLE
VR: skip dhcp/dns health check in some cases

### LINKED ISSUE #5536: VPC redundant routers healthcheck giving errors for services which aren't part of  VPC offering
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
- Redundant virutal router in VPC - Offering
~~~

##### CLOUDSTACK VERSION

~~~
4.15.2
~~~

##### CONFIGURATION

- advanced networking
- custome VPC offering

##### OS / ENVIRONMENT

- Ubuntu Server 20.04. LTS for all servers

##### SUMMARY

I am setting up a redundant VPC from a customized service offering.
The following service provided by the VPC / the virtual routers:
- Portforwarding
- Network ACL
- SourceNAT
- VPN
- StaticNat

Deployment works well but i am now getting constantly alerts that healthchecks are not successfull.
Currently failing healtchecks:
-webserver.service
-dhcp_check.py
-dns_check.py

in regards of the webserver, it seems that that the apache2 is terminated due to missing ssl certificates for the network domain (?).

##### STEPS TO REPRODUCE

~~~
- create new offering for redundant VPC
- deploy VPC
- wait till the healthchecks are starting 
~~~

##### EXPECTED RESULTS

~~~
-Healthchecks are performed depending on the offered services (or as fuctionality is needed elsewhere)
~~~

##### ACTUAL RESULTS

~~~
- getting alearts with every healthcheck 
~~~

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR  fixes #5536

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@nvazquez @sureshanaparti 
added to 4.16.0.0

**Comment by vladimirpetrov** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Review by nvazquez — APPROVED** [review]

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
Last test lgtm, the host ha failure are intermittent and not caused by this PR.

**Pull request closed without merging**
