### PR TITLE
pre-commit: add hook to check for the existence of private keys

### PR DESCRIPTION
**Pull request by jbampton**
https://github.com/pre-commit/pre-commit-hooks#detect-private-key

The "exclude" list is the list of "keys" currently found by this hook

### Description

This PR adds another pre-commit hook or "test" to check for "keys" in the codebase

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [X] Trivial

### How Has This Been Tested?

You can test locally with pre-commit from the repo root:

`pre-commit run --all-files`

To just test this hook run:

`pre-commit run detect-private-key --all-files`

### CODE REVIEW

**Comment by jbampton** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
looks good, not sure if the console proxy should be excluded though

**Comment by jbampton** [comment]
> looks good, not sure if the console proxy should be excluded though

Hey @DaanHoogland when you run this new hook for the first time it finds that list of keys in the codebase.

So I was then excluding them assuming they were all valid keys that we need.

**Comment by DaanHoogland** [comment]
> > looks good, not sure if the console proxy should be excluded though
> 
> Hey @DaanHoogland when you run this new hook for the first time it finds that list of keys in the codebase.
> 
> So I was then excluding them assuming they were all valid keys that we need.

yeah, makes sense and I have no doubts about most (systemvm and tests) . I'll need to look at the consoleproxy one.

**Comment by DaanHoogland** [comment]
> > > looks good, not sure if the console proxy should be excluded though
> > 
> > 
> > Hey @DaanHoogland when you run this new hook for the first time it finds that list of keys in the codebase.
> > So I was then excluding them assuming they were all valid keys that we need.
> 
> yeah, makes sense and I have no doubts about most (systemvm and tests) . I'll need to look at the consoleproxy one.

false alarm (didn't notice this is in a test dir as well)

**Review by stephankruggg — APPROVED** [review]
LGTM

**Pull request merged**
