### PR TITLE
Host is counted twice if it has multiple host tags in Prometheus exporter

### PR DESCRIPTION
**Pull request by ustcweizhou**
## Description

If hosts have multiple host tags, the total/up/down hosts in prometheus exporter are not correct.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@ustcweizhou @DaanHoogland 
Seems like the build failure is because it is unable to resolve HostVO and hostDao isn't injected
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project cloud-plugin-integrations-prometheus-exporter: Compilation failure: Compilation failure: 
[ERROR] /jenkins/workspace/acs-pr-centos7-pkg-builder/dist/rpmbuild/BUILD/cloudstack-4.14.1.0-SNAPSHOT/plugins/integrations/prometheus/src/main/java/org/apache/cloudstack/metrics/PrometheusExporterImpl.java:[103,33] error: cannot find symbol
[ERROR]   symbol:   variable hostDao
[ERROR]   location: class PrometheusExporterImpl
[ERROR] /jenkins/workspace/acs-pr-centos7-pkg-builder/dist/rpmbuild/BUILD/cloudstack-4.14.1.0-SNAPSHOT/plugins/integrations/prometheus/src/main/java/org/apache/cloudstack/metrics/PrometheusExporterImpl.java:[103,19] error: cannot find symbol
[ERROR]   symbol:   class HostVO
[ERROR]   location: class PrometheusExporterImpl
[ERROR] -> [Help 1]
```

**Comment by GabrielBrascher** [comment]
@blueorangutan package

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
LGTM, changes are strictly in promethus plugin; merging based on lgtms and travis tests.

**Pull request merged**
