### PR TITLE
UI: allow new keys for VM details

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR...

~~Fixes: #6937~~
Fixes: #7700 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by harikrishna-patnala** [comment]
@DaanHoogland does this mean, we now allow empty values for the settings?

**Comment by weizhouapache** [comment]
@DaanHoogland 
after some thinking, I think it is not a UI bug, but a missing feature.

actually when I add a vm setting "extraconfig", it failed
```
Failed to update VM, due to: 'extraconfig' should not be included in details as key
```

in the EditVM dialog, we need to add a new field "extraconfig"

**Comment by DaanHoogland** [comment]
> @DaanHoogland does this mean, we now allow empty values for the settings?

good question. If the API accepts it we do, i guess.

**Review by harikrishna-patnala — COMMENTED** [review]
what I observed with this fix is

1. We are not allowing empty values even after the fix. The observed fix is, we are now handling this properly in UI without any errors in the debugger console. In my opinion, this is good.
image

2. We could now add extra custom details which are not predefined. Not sure if this is the intention of this fix, but this is also good, there is another issue raised to allow custom keys https://github.com/apache/cloudstack/issues/7700
image

3. Specific to the key value "extraconfig" mentioned in the original issue, intentionally are not allowing it in the backend, not sure about the reason.
https://github.com/apache/cloudstack/blob/981d74825a87727d7f8e397cad75877986c96d79/server/src/main/java/com/cloud/vm/UserVmManagerImpl.java#L2772-L2774

@DaanHoogland am I correct with these points ? specifically point 1, it is contradicting the subject

**Comment by DaanHoogland** [comment]
> what I observed with this fix is
> 
>     1. We are not allowing empty values even after the fix. The observed fix is, we are now handling this properly in UI without any errors in the debugger console. In my opinion, this is good.

yes

>     2. We could now add extra custom details which are not predefined. Not sure if this is the intention of this fix, but this is also good, there is another issue raised to allow custom keys [VM Settings validation blocks custom key value pairs #7700](https://github.com/apache/cloudstack/issues/7700)

yes, it is

>     3. Specific to the key value "extraconfig" mentioned in the original issue, intentionally we are not allowing it in the backend, not sure about the reason.

functionally i am not sure, but the intention was to allow any key. I did not test with this particular string :face_with_head_bandage: .

> 
> @DaanHoogland am I correct with these points ? specifically point 1, it is contradicting the subject

I will change the subject.

@weizhouapache @rohityadavcloud @vishesh92 @nvazquez , what do and do we not  want to allow?

**Comment by nvazquez** [comment]
Hi @DaanHoogland @harikrishna-patnala, I think the reason the 'extraconfig' key is not allowed is because it is a parameter on the deployVirtualMachine API. In case the user passes extra config, those are persisted as VM details with the key 'extraconfig' which can cause issues

**Comment by weizhouapache** [comment]
> 
> So I think what we can do here is (if at all we decide to allow extraconfig from UI) to check if the detail key is "extraconfig" and then send the value in API parameter "extraconfig" (not the "details").

this looks like a good solution. @harikrishna-patnala @DaanHoogland

**Comment by nvazquez** [comment]
The 'extraconfig' parameter was introduced by this feature: https://cwiki.apache.org/confluence/display/CLOUDSTACK/Enable+additional+configuration+metadata+to+virtual+machines. It lacks UI support, so was only possible to set it in the API. I think that it can be a good partial solution as the way the extra config is stored on the vm_details table is using either named keys such as: extraconfig-NAME1, extraconfig-NAME2 or numerical: extraconfig-1, extraconfig-2. So the updateVirtualMachine API may allow editing the first time but not the second time as the details will be split into multiple details with the extraconfig prefix (all this needs to be tested, I had tested it long ago :) )

**Comment by weizhouapache** [comment]
> The 'extraconfig' parameter was introduced by this feature: https://cwiki.apache.org/confluence/display/CLOUDSTACK/Enable+additional+configuration+metadata+to+virtual+machines. It lacks UI support, so was only possible to set it in the API. I think that it can be a good partial solution as the way the extra config is stored on the vm_details table is using either named keys such as: extraconfig-NAME1, extraconfig-NAME2 or numerical: extraconfig-1, extraconfig-2. So the updateVirtualMachine API may allow editing the first time but not the second time as the details will be split into multiple details with the extraconfig prefix (all this needs to be tested, I had tested it long ago :) )

thanks @nvazquez for the info

it looks we need to investigate more on #6937 before. sorry @DaanHoogland , I thought it is a simple bug fix

**Comment by harikrishna-patnala** [comment]
> > The 'extraconfig' parameter was introduced by this feature: https://cwiki.apache.org/confluence/display/CLOUDSTACK/Enable+additional+configuration+metadata+to+virtual+machines. It lacks UI support, so was only possible to set it in the API. I think that it can be a good partial solution as the way the extra config is stored on the vm_details table is using either named keys such as: extraconfig-NAME1, extraconfig-NAME2 or numerical: extraconfig-1, extraconfig-2. So the updateVirtualMachine API may allow editing the first time but not the second time as the details will be split into multiple details with the extraconfig prefix (all this needs to be tested, I had tested it long ago :) )
> 
> thanks @nvazquez for the info
> 
> it looks we need to investigate more on #6937 . sorry @DaanHoogland , I thought it is a simple bug fix

@weizhouapache this PR can still be merged as this is fixing the other issue https://github.com/apache/cloudstack/issues/7700 to allow custom keys, also this PR handles the errors that are coming in the debugger console. We can handle #6937 separately.

**Comment by weizhouapache** [comment]
> 

ok @harikrishna-patnala ,thanks for pointing it out
this lgtm

**Review by weizhouapache — APPROVED** [review]
tested ok

**Review by harikrishna-patnala — APPROVED** [review]
LGTM. I've verified the fix for the issue #7700

**Comment by weizhouapache** [comment]
> LGTM. I've verified the fix for the issue #7700

thanks @harikrishna-patnala . merging

**Pull request merged**
