### PR TITLE
Add IOPS to disk offerings details

### PR DESCRIPTION
**Pull request by hsato03**
### Description

When listing disk offerings through the UI, IOPS and read/write data for these offerings is not presented, making it difficult to access information about them.

For this reason, `Disk Read Rate (IOPS)`, `Disk Write Rate (IOPS)`, `Disk Read Rate (BPS)`, `Disk Write Rate (BPS)` and `Max IOPS` data has been added to the disk offering details.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

1. I created a disk offering with customized write and read rate values using the `hypervisor` QoS type in the creation form;
2. I created a disk offering with max IOPS using the `storage` QoS type in the creation form;
3. I accessed these disk offerings and verified that the `Disk Read Rate (IOPS)`, `Disk Write Rate (IOPS)`, `Disk Read Rate (BPS)`, `Disk Write Rate (BPS)` data were in the disk offering created in the step 1 and the `Max IOPS` data was in the disk offering created in the step 2.

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@blueorangutan ui

**Comment by DaanHoogland** [comment]
not sure why, but in qa this doesn't work, @hsato03. I will try building a 4.19 env to double check. (qa is 4.18.1)

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by hsato03** [comment]
> not sure why, but in qa this doesn't work, @hsato03. I will try building a 4.19 env to double check. (qa is 4.18.1)

@DaanHoogland thanks. I have tested on https://qa.cloudstack.cloud/simulator/pr/8447 and it seems to be working.

Screenshot from 2024-01-05 14-43-50

Could you explain how you did the tests?

**Comment by DaanHoogland** [comment]
yes verified. don't know what happened.

**Comment by kiranchavala** [comment]
@blueorangutan ui

**Review by kiranchavala — COMMENTED** [review]
@hsato03 

Could you please  include "miniops"  in the disk offering details.

If a disk offering is created with min IOPS using the storage QoS

**Comment by kiranchavala** [comment]
@blueorangutan ui

**Review by kiranchavala — APPROVED** [review]
LGTM , Please find the screenshots 

diskofferingdetails1

diskofferingdetails3

**Comment by hsato03** [comment]
Hello guys,

Any other concerns about this one?

**Pull request merged**
