### PR TITLE
engine-schema: fix options for host.allocators.order config

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

With https://github.com/apache/cloudstack/commit/d8c7e34b383d6e6ab4d00f3a07e3b2ab467eca36 options were added to the host.allocators.order config. Currently, it allows adding only FirstFitRouting as the value **in the UI**. This PR fixes the behaviour and allows other host allocators to be added.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):
Current behaviour:
image

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by rohityadavcloud — APPROVED** [review]

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@blueorangutan test keepEnv

**Review by vishesh92 — APPROVED** [review]
clgtm.
Tested in my local environment. Before the changes, UI displayed only `FirstFitRouting`. After the changes, I could see all the possible host allocators in the drop down.
image

**Pull request merged**
