### PR TITLE
UI: Fixes asynchronous when destroying wrong item VM

### PR DESCRIPTION
**Pull request by utchoang**
### Description

This PR fixes https://github.com/apache/cloudstack/issues/5883

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by DaanHoogland** [comment]
thanks @utchoang , I'll give it a test.

**Comment by DaanHoogland** [comment]
not sure if it is the qa env or your PR @utchoang , but I can;t get a delete dialogue at all atm! It stalls at loading:
image

**Comment by DaanHoogland** [comment]
I just checked in the general qa site. Delete doesn't work there, but the dialog fully loads in it.

**Comment by utchoang** [comment]
@DaanHoogland It's worked for now. Please review it again. Thanks

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by DaanHoogland** [comment]
@utchoang I think your fix is good for destroy VM calls. It does not adress the generic race condition that is in the UI on any delete action. I have seen this on different types of offerings and it could also happen on for instance allert, event, account, user, network, ...

That said, I could not test this in the QA environment, so I'd need to install a dedicated environment. If someone else manages to test this in the qa env, please.

code looks good but as said, the solution only applies to the destroyVM API.

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by utchoang** [comment]
@DaanHoogland You can use my latest commit to retest this case. This change will apply to other similar cases.

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
LGTM, I have tried to reproduce the issue on disks, VMs and offerings and could not in any case, tnx @utchoang

**Review by sureshanaparti — APPROVED** [review]
Verified in the instances, volumes and disk offerings pages. No issues.

**Review by shwstppr — APPROVED** [review]

**Pull request merged**
