### PR TITLE
CLOUDSTACK-8714 Restore VM (Re-install VM) with enable.storage.migration set to false fails

### PR DESCRIPTION
**Pull request by manuiiit**
.....later fails to start up VM too

Author: Prachi Damle

Changes:
- Try to use the last_host if it has free capacity but no reserved capacity

Signed-off-by: Maneesha.P <maneesha.papireddygari@citrix.com>

### CODE REVIEW

**Comment by remibergsma** [comment]
Thanks! Can you please rewrite the commit message and use the CLOUDSTACK issue ID?

**Comment by remibergsma** [comment]
LGTM. I tested it on a VM running on KVM and it works fine now with enable.storage.migration=false. The VM restore itself also still works.

Please see my previous comment about the commit message.

**Comment by manuiiit** [comment]
@remibergsma  It was an internal bug reported hence created a new issue and updated .Thanks for the review.

**Comment by wido** [comment]
LGTM

**Pull request merged**
