### PR TITLE
server: clean network offerings for domain on remove

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR...

Fixes: #7773 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by weizhouapache — APPROVED** [review]
code lgtm

checked the SQL in https://github.com/apache/cloudstack/blob/4.18.0.0/engine/schema/src/main/resources/META-INF/db/schema-41720to41800.sql, this PR looks ok
there are some other solutions, but seem not better than this.

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@DaanHoogland 
can you fix the unit test failures ? thanks
```
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    DomainManagerImplTest.deleteDomain:273
Error:    DomainManagerImplTest.deleteDomainCleanup:306
[INFO] 
Error:  Tests run: 1450, Failures: 2, Errors: 0, Skipped: 9
```

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Comment by weizhouapache** [comment]
@DaanHoogland 
is it ready for review ? do we need QA to test it ?

**Review by harikrishna-patnala — APPROVED** [review]
Code LGTM

**Comment by DaanHoogland** [comment]
> @DaanHoogland is it ready for review ? do we need QA to test it ?

yes it is, I was waiting for smoke tests, but there is a backend issue. will need to investigate that

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by kiranchavala — APPROVED** [review]
LGTM, tested manually 

```
Created domain
Created network offering or vpc offering assoicated with the domain
Deleted the domain
The network and vpc offerings were also cleaned up
```

**Pull request merged**
