### PR TITLE
Remove "self-injection" of AccountManagerImpl

### PR DESCRIPTION
**Pull request by rafaelweingartner**
## Description

While working on other PRs I noticed that the singleton AccountManagerImpl had a reference for itself. That is not needed. Therefore, I removed it.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [X] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?
Smoke tests

## Checklist:

- [X] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
Testing
- [ ] I have added tests to cover my changes.
- [X] All relevant new and existing integration tests have passed.
- [ ] A full integration testsuite with all test that can run on my environment has passed.

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rafaelweingartner** [comment]
@rhtyd you did not need to package again. I forced a new commit only to push Jenkins to build again. 

BTW, do you know why we keep getting this constant Jenkins failures. Quite often I get a 404 when accessing Jenkins build that failed. It looks like the builds are being deleted.

**Comment by rhtyd** [comment]
Okay @rafaelweingartner, I saw a force push I thought something changed. I'll kick tests now.
@blueorangutan test

**Pull request merged**
