### PR TITLE
server: fix NPE in travis and merge #6305

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes the NPE in travis test

image

see https://app.travis-ci.com/github/apache/cloudstack/jobs/567879122

this includes #6305

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
this does not fix travis, but would be good to have

**Comment by nvazquez** [comment]
@blueorangutan package

**Review by nvazquez — APPROVED** [review]

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
Travis check fixed

**Pull request merged**
