### PR TITLE
Replace string libraries with org.apache.commons.lang3.StringUtils

### PR DESCRIPTION
**Pull request by GutoVeronezi**
### Description

We have a current discussion about using `commons.lang3` or our facade `com.cloud.utils` on the code, however a third implementation has been added (`google.common.base`), which end up adding more complexity to the discussion. The two variables of this discussion already implements all we need, therefore adding a third one does not make sense.

This PR primary intends to change `com.google.common.base.Strings`'s calls for `org.apache.commons.lang3.StringUtils`'s calls and after that, upgrade `org.apache.commons.lang.StringUtils`'s calls to `org.apache.commons.lang3.StringUtils`'s calls.  Also, it will improve some minor codes related to `org.apache.commons.lang3.StringUtils` methods;

I choose `org.apache.commons.lang3.StringUtils` because our facade `com.cloud.utils.StringUtils` has a lack of methods to be a really facade of `org.apache.commons.lang3.StringUtils` and the methods it already implements are `deprecated`.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

### How Has This Been Tested?
-

---
EDIT 1

As we discussed in thread [[Discussion] String libs](https://lists.apache.org/thread.html/r806cd10b3de645c150e5e0e3d845c5a380a700197143f57f0834d758%40%3Cdev.cloudstack.apache.org%3E), voted in [[VOTE] Standard string lib](https://lists.apache.org/thread.html/rf8c21f7d8af2c85369c7ce2f8205dc8f1b24ebd0a24417ba501b79a0%40%3Cdev.cloudstack.apache.org%3E) and resulted in [[RESULT] [VOTE] Standard string lib](https://lists.apache.org/thread.html/r5898f717d506a0e160b9dc766b65769e2fe2f07f9cba70825843e272%40%3Cdev.cloudstack.apache.org%3E):
- `commons.lang3` will be our standard String library;
- `commons.lang` will be updated to `commons.lang3`;
- Unnecessary libraries will be replaced with `commons.lang3`;
- Unnecessary libraries will be added in module `IllegalImport`, in `checkstyle`;
- For String operations not covered by `commons.lang3`, we'll use our facade `com.cloud.utils.StringUtils`;
- In other PRs I will update code conventions and wiki/docs;

### CODE REVIEW

**Comment by rhtyd** [comment]
I like the readability of Strings.isNullOrEmpty than isEmpty

**Comment by GutoVeronezi** [comment]
> I like the readability of Strings.isNullOrEmpty than isEmpty, maybe refactor everything to use cloud-utils's StringsUtils that wraps whatever favourite utility dependency you want to propose. Discuss on dev@ as Daan suggests.

I agree that some methods can be more intuitive than others, however the point is to standardize what we're using. Soon I will start a discussion on the dev list, as @DaanHoogland suggested.

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by GutoVeronezi** [comment]
@DaanHoogland could we re-run the tests?

**Comment by DaanHoogland** [comment]
sure @GutoVeronezi and I'll keep an eye on why it fails
@blueorangutan test centos7 vmware-70u1

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test centos7 vmware-70u1

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by GutoVeronezi** [comment]
Restart Jenkins...

**Review by GabrielBrascher — APPROVED** [review]
LGTM

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
@GutoVeronezi is this ready for merging? And does it have a checkstyle or mvn check to ensure only this library is used throughout?

@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by GutoVeronezi** [comment]
> @GutoVeronezi is this ready for merging? And does it have a checkstyle or mvn check to ensure only this library is used throughout?

@rhtyd yes, it is ready. 

About the checkstyle checks, they were introduced through commit [Prohibit others string libs](https://github.com/apache/cloudstack/pull/5386/commits/13d3a029ec4d246ee9b77202a13a10d5d113b8d8).

**Comment by rhtyd** [comment]
Okay let's kick smoketest and merge the PR if they pass.
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Review by rhtyd — APPROVED** [review]
Tests lgtm - let's stay vigilant if this causes any regresssion that smoketests don't cover, after merging this @GutoVeronezi

**Pull request merged**
