### PR TITLE
debian/control: build packages on ubuntu 22.04

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR supports cloudstack packaging on ubuntu 22.04

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

### CODE REVIEW

**Review by kiranchavala — COMMENTED** [review]
Hi @weizhouapache  

Can you make  nodejs (>= 14) 

Since nodejs 12 is not supported by ubuntu 22.04 release and is deprecated

https://deb.nodesource.com/node_12.x/dists/

There is ubuntu 22.04 -Jammy in node_14.x which is LTS

https://deb.nodesource.com/node_14.x/dists/

-------------------------------
Also is "dh-systemd" required for a successful build ?

As per https://bugs.debian.org/822670, the dh-systemd package has been merged with the main debhelper package since version 9.20160709


On Ubuntu 22.04 (Jammy) the dh-systemd package has been completely removed,

**Comment by weizhouapache** [comment]
> Hi @weizhouapache
> 
> Can you make nodejs (>= 14)
> 
> Since nodejs 12 is not supported by ubuntu 22.04 release and is deprecated
> 
> https://deb.nodesource.com/node_12.x/dists/
> 
> There is ubuntu 22.04 -Jammy in node_14.x which is LTS
> 
> https://deb.nodesource.com/node_14.x/dists/
> 
> Also is "dh-systemd" required for a successful build ?
> 
> As per https://bugs.debian.org/822670, the dh-systemd package has been merged with the main debhelper package since version 9.20160709
> 
> On Ubuntu 22.04 (Jammy) the dh-systemd package has been completely removed,

@kiranchavala 
thanks for your review.

since debian/control is also used when build package on ubuntu 20.04, it should be compatible with ubuntu 20.04 as well 22.04

for example, `dh-systemd | debhelper (>= 13)` means both dh-systemd (on ubuntu 20.04) and debhelper (>=13) on ubuntu 22.04 work.

The change for nodejs makes sense. The version has been update in PR #6956 
https://github.com/apache/cloudstack/pull/6956/files#diff-6e8c08cff231f603dfa7a4d5f873a6fee6e5c730d431c113bbf5b1180c6983e4

However, I need to check if nodejs verison has been changed in our container for deb packaging. 
If it still uses nodejs12, the packaging jobs will fail if this is merged.

**Comment by wido** [comment]
Code LGTM

**Review by wido — APPROVED** [review]

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Review by kiranchavala — APPROVED** [review]
Tested the Changes LGTM

**Pull request merged**
