### PR TITLE
 Adding button to toggle fullscreen in noVNC console 

### PR DESCRIPTION
**Pull request by davidjumani**
## Description
 Adding button to toggle fullscreen in the noVNC console UI

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## Screenshots (if appropriate):
Screenshot from 2020-09-09 19-06-02
Screenshot from 2020-09-09 19-06-10

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@davidjumani if it's not too much work could this be provided as a toolbar option like upstream novnc does (let user decide if the console needs to be scaled down or not)?

Screenshot from 2020-09-09 15-53-57

**Comment by davidjumani** [comment]
@rhtyd Right not using the vnc_lite.html not the vnc.html to prevent users from unknowingly changing settings which could break stuff. Can look into creating a fullscreen button

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@rhtyd Added a button on the noVNC page to toggle fullscreen mode!

**Comment by davidjumani** [comment]
Closing in favour of https://github.com/apache/cloudstack/pull/4323

**Pull request closed without merging**
