### PR TITLE
Avoid Null pointer at DomainChecker and enhance AssignVMCmd

### PR DESCRIPTION
**Pull request by GabrielBrascher**
## Description

When executing request [assignVirtualMachine](https://cloudstack.apache.org/api/apidocs-4.14/apis/assignVirtualMachine.html) with null `domainID` and a valid `projectID` then a `NullPointerException` happens at [DomainChecker.java](https://github.com/apache/cloudstack/blob/bb73bedb5511880c91abaa409462ba879cb0d7b7/server/src/main/java/com/cloud/acl/DomainChecker.java#L109).

Command example:
```
assign virtualmachine virtualmachineid=vmID projectid=projectID account=admin
```

The `NullPointerException` that is thrown at `DomainChecker` is handled at [AssignVMCmd.java#L142](https://github.com/apache/cloudstack/blob/bb73bedb5511880c91abaa409462ba879cb0d7b7/api/src/main/java/org/apache/cloudstack/api/command/admin/vm/AssignVMCmd.java#L142), resulting in the following log message: `Failed to move vm null`.

**My question is:** does it make sense to assign VM to a project with `domainID=null`? If so, then the handling should be different. However, I think that it should not be `null` and therefore I added a proper log message.

Prior to commit 
## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?
Request of API command  [assignVirtualMachine](https://cloudstack.apache.org/api/apidocs-4.14/apis/assignVirtualMachine.html) with project ID and `null` domainID.

```
assign virtualmachine virtualmachineid=vmID projectid=projectID account=admin
```

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan package

**Review by davidjumani — APPROVED** [review]
Code LGTM

**Review by rhtyd — APPROVED** [review]

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
Test manually rekicked

**Comment by rhtyd** [comment]
LGTM merging this based on Travis tests pass.

**Pull request merged**
