### PR TITLE
Add47xmessagesproperties transifex

### PR DESCRIPTION
**Pull request by milamberspace**
Now master branch is the next 4.7 release. Open the 4.7 resources files on Transifex.

Update the transifex client config file.

Small PR outside the build path.

cc @remibergsma @DaanHoogland

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@milamberspace looks ok, but ii know not enough of the transifex mechs to be sure. Can you add some explanation?

**Comment by milamberspace** [comment]
@DaanHoogland I don' known the best way to explain the transifex process.

For all versions of CloudStack, we have a version of resources files on Transifex [1].

When you update the main resource file with the new version, the transifex config file is updated with all languages with already translated.

I don't know the best way to explain the internal behavior of the transifex client, but the config file is update after the first download of the main resource file (en_US) and the upload of the current L10N files to the new L10N files for the new versions. This PR reflect the changes.

You can retry the behavior from the master (up to date 2015/11/21) with theses commands:

To fetch the latest original L10N file form Transifex (already done because I'm put the 4.7 main resource files on the TX website today)
cd tools/transifex/
 ./sync-transifex-ui.sh download-source-language CloudStack_UI.47xmessagesproperties

To upload all L10N translations files (from 4.6 files) to transifex (already done by me today, but you can re-made the work during few days before the translator team changes the strings on Transifex)
./sync-transifex-ui.sh upload-l10n-languages CloudStack_UI.47xmessagesproperties


[1]https://www.transifex.com/ke4qqq/CloudStack_UI/content/

**Comment by DaanHoogland** [comment]
Tnx Do we have a page on cwiki on this already?

**Comment by milamberspace** [comment]
@DaanHoogland I've just update this wiki page:
https://cwiki.apache.org/confluence/display/CLOUDSTACK/Update+L10N+files+from+Transifex+to+git+repo

I hope that this page explains the process, otherwise tell me the issue with the transifex client.

**Comment by bhaisaab** [comment]
LGTM

**Comment by remibergsma** [comment]
@milamberspace Do you want to update this PR before we merge it?

**Comment by milamberspace** [comment]
@remibergsma Yes I want! The update of localization files is done.

**Comment by bhaisaab** [comment]
@milamberspace is this still valid, now that we've a 4.8 and master's on 4.9? cc @remibergsma

**Comment by milamberspace** [comment]
@bhaisaab see PR #1374 #1375 and #1376

**Comment by bhaisaab** [comment]
Thanks @milamberspace

**Pull request closed without merging**
