### PR TITLE
CLOUDSTACK-10017: Adding 'quick-test' attribute to list of smoketests…

### PR DESCRIPTION
**Pull request by borisstoyanov**
… and adding 'vpc', 'templates', 'deploy-vm', 'roles', 'service-offerings', 'storage', 'routers', 'networks', 'usage', 'accounts' tags

quick-test label aims to provide quick feedback of recent changes to the developer, instead of waiting for the whole smoketest to execute(24h+). This execution lasts about 1.5h at Trillian environments.

The categories aim to offer more efficient way to slice through tests in both smoke and component tests. Let's say as a developer you've made a change in the accounts. You can simply trigger marvin tests with tag=accounts pointing all the tests for example:
```

nosetests --with-marvin --marvin-config=[config] --hypervisor=xenserver -a tags=accounts /tests/integration/*/*.*

```
https://cwiki.apache.org/confluence/display/CLOUDSTACK/Test+Categories+and+Quick-test+in+Marvin

### CODE REVIEW

**Comment by rhtyd** [comment]
Good effort, @borisstoyanov can you rebase Github is such a complainer :)

**Comment by borisstoyanov** [comment]
Thanks @rhtyd, I've rebased and squashed all the commits

**Comment by borisstoyanov** [comment]
ping @DaanHoogland @nvazquez @PaulAngus for review

**Comment by rhtyd** [comment]
I must share that as a developer I don't see any value in this, as for any change I would do I would run a full smoketest anyway, and for component/resource specific test run I can already run a single test file which are already grouped by resource/component, for example vm_lifecycle test is all related to a vm etc so I could run that individual test.

@borisstoyanov can you pull rebase against latest master?

**Comment by borisstoyanov** [comment]
I've just rebased @rhtyd, a full smoketest would take day+ and this label gives you a real quick feedback if your changes brake anything fundamentally. 

Actually in theory smoketests should be really quick and should give near instant result back. Their main outcome should be yes/no answer to 'is the build testable' question (as per common testing practice). I think this is where we got this wrong and kept on adding and adding more items to the suite, instead it should be the other way around, having a really short smoketest and more extensive regression testing suite.

**Comment by PaulAngus** [comment]
in theory i agree @borisstoyanov - the problem there is how do you define fundamental.
and given how large the component suite is (and how badly broken), results from component tests tend to get ignored.

We could split the tests in to 3 categories 

- a set of true smoke tests basic vm lifecycle and network tests that take just a hour or two to run
- a set of known good component tests - the remainder of smoke tests and known good component tests
- broken tests - ones that rarely, if ever pass

The broken tests can live in a separate directory, and as they get fixed, can be moved into the known good directory to be run in future.

but by hook or by crook we need to get to a point where a failure *_really_* means a code issue.

then we can be much more boolean about quality.

**Comment by DaanHoogland** [comment]
@borisstoyanov please rebase and re-open if still relevant

**Pull request closed without merging**
