### PR TITLE
Removed check on SSLEngine client mode

### PR DESCRIPTION
**Pull request by Spaceman1984**
## Description

The SSL engine defaults to "Server mode" when doing handshaking. This PR removes the check on the mode which was causing tests to fail.

This behavior was changed in OpenJDK 11.0.8
```
JDK-8245077: Default SSLEngine Created in Server Role
=====================================================
In JDK 11 and later, `javax.net.ssl.SSLEngine` by default used client
mode when handshaking.  As a result, the set of default enabled
protocols may differ to what is expected. `SSLEngine` would usually be
used in server mode. From this JDK release onwards, `SSLEngine` will
default to server mode. The
`javax.net.ssl.SSLEngine.setUseClientMode(boolean mode)` method may be
used to configure the mode.
```

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

This was tested by building Cloudstack and allowing the tests to run.

### CODE REVIEW

**Comment by Spaceman1984** [comment]
@blueorangutan package

**Comment by Spaceman1984** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by Spaceman1984** [comment]
> I had some issues on master, where the test checks for true `Assert.assertTrue(e.getUseClientMode()); `, not `assertFalse`. will this be forwarded to master as well?

@GabrielBrascher , I will create a pull request for master.

**Comment by GabrielBrascher** [comment]
PR closed in favor of #4226

**Pull request closed without merging**
