### PR TITLE
increase log detail for limit checking, fix getDomainReservation()

### PR DESCRIPTION
**Pull request by oscaralvaro**
### Description

In troubleshooting ops issues we see logs like:

Maximum domain resource limits of Type 'user_vm' for Domain Id = 763 is exceeded: Domain Resource Limit = (1 bytes) 1, Current Domain Resource Amount = (0 bytes) 0, Requested Resource Amount = (1 bytes) 1."

However there is one missing value (currentResourceReservation) that is used in the calculation of limit check but it is not logged, which leads to confusion. Above we see we are using “0” and requested 1, with our limit being 1, but was rejected. Without logging all the values used in the calculation we don’t understand why it failed.

Additionally, if we had this log above it would be clearer that a second bug is occurring. When we query for domain level resource reservations in “getDomainReservation” the actual SearchBuilder is the listAccountAndTypeSearch, not the listDomainAndTypeSearch. As a result, when we call getDomainReservation the query returns any outstanding domain reservation for any account, as domain ID is not a valid filter for the account search.

This PR:

- Increases detailed information in log for checking resource limit to include reservations information for functions: checkDomainResourceLimit() and checkAccountResourceLimit

- Fixes getDomainReservation() to use listDomainAndTypeSearch instead of listAccountAndTypeSearch

#### Testing
Log generation manually tested

#### Log samples

Before the change

(logprefix) ... Checking if amount of resources of Type = 'user_vm' for Account Name = domainadmin_user in Domain Id = 1 is exceeded: Account Resource Limit = 20, Current Account Resource Amount = 0, Requested Resource Amount = 1.
(logprefix) ... Checking if amount of resources of Type = 'cpu' for Account Name = domainadmin_user in Domain Id = 1 is exceeded: Account Resource Limit = 40, Current Account Resource Amount = 0, Requested Resource Amount = 1.
(logprefix) ... Checking if amount of resources of Type = 'memory' for Account Name = domainadmin_user in Domain Id = 1 is exceeded: Account Resource Limit = 40960, Current Account Resource Amount = 0, Requested Resource Amount = 512.
(logprefix) ... Checking if amount of resources of Type = 'volume' for Account Name = domainadmin_user in Domain Id = 1 is exceeded: Account Resource Limit = 20, Current Account Resource Amount = 0, Requested Resource Amount = 1.
(logprefix) ... Checking if amount of resources of Type = 'primary_storage' for Account Name = domainadmin_user in Domain Id = 1 is exceeded: Account Resource Limit = (200.00 GB) 214748364800, Current Account Resource Amount = (0 bytes) 0, Requested Resource Amount = (5.00 GB) 5368709120.

After the change

(logprefix) ... Checking if amount of resources of Type = 'user_vm' for Account Name = domainadmin_user in Domain Id = 1 is exceeded: Account Resource Limit = 20, Current Account Resource Amount = 1, Current Account Resource Reservation = 0, Requested Resource Amount = 1.
(logprefix) ... Checking if amount of resources of Type = 'cpu' for Account Name = domainadmin_user in Domain Id = 1 is exceeded: Account Resource Limit = 40, Current Account Resource Amount = 1, Current Account Resource Reservation = 0, Requested Resource Amount = 1.
(logprefix) ... Checking if amount of resources of Type = 'memory' for Account Name = domainadmin_user in Domain Id = 1 is exceeded: Account Resource Limit = 40960, Current Account Resource Amount = 512, Current Account Resource Reservation = 0, Requested Resource Amount = 512.
(logprefix) ... Checking if amount of resources of Type = 'volume' for Account Name = domainadmin_user in Domain Id = 1 is exceeded: Account Resource Limit = 20, Current Account Resource Amount = 1, Current Account Resource Reservation = 0, Requested Resource Amount = 1.
(logprefix) ... Checking if amount of resources of Type = 'primary_storage' for Account Name = domainadmin_user in Domain Id = 1 is exceeded: Account Resource Limit = (200.00 GB) 214748364800, Current Account Resource Amount = (5.00 GB) 5368709120, Current Account Resource Reservation = (0 bytes) 0, Requested Resource Amount = (5.00 GB) 5368709120.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Review by rohityadavcloud — APPROVED** [review]
LGTM - needs testing though. Thanks @oscaralvaro

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by mlsorensen** [comment]
Tested this manually.

To confirm bug, I set up current version, created 10 domains, set their VM limit to 1.  Then ran a script to create 1 VM in each of these domains in parallel. Only one succeeded, the rest claimed we had hit our domain limits. This confirmed that the resource limit accounting for domains is considering all active in-flight VM resources, not just domain scoped (per the issue described in `getDomainReservation`).


```
% ./cbench -benchmark vmcreate -workers 10 -jobs 1
Starting 10 workers to create 10 total VMs
Starting worker 9 to create 1 VMs
Starting worker 5 to create 1 VMs
Starting worker 8 to create 1 VMs
Starting worker 7 to create 1 VMs
Starting worker 0 to create 1 VMs
Starting worker 4 to create 1 VMs
Starting worker 6 to create 1 VMs
Starting worker 2 to create 1 VMs
Starting worker 1 to create 1 VMs
Starting worker 3 to create 1 VMs
Error while deploying VM with worker 2: CloudStack API error 535 (CSExceptionErrorCode: 9999): Maximum domain resource limits of Type 'user_vm' for Domain Id = 4 is exceeded: Domain Resource Limit = (1 bytes) 1, Current Domain Resource Amount = (0 bytes) 0, Requested Resource Amount = (1 bytes) 1., <nil>
Error while deploying VM with worker 5: CloudStack API error 535 (CSExceptionErrorCode: 9999): Maximum domain resource limits of Type 'user_vm' for Domain Id = 7 is exceeded: Domain Resource Limit = (1 bytes) 1, Current Domain Resource Amount = (0 bytes) 0, Requested Resource Amount = (1 bytes) 1., <nil>
Error while deploying VM with worker 6: CloudStack API error 535 (CSExceptionErrorCode: 9999): Maximum domain resource limits of Type 'user_vm' for Domain Id = 8 is exceeded: Domain Resource Limit = (1 bytes) 1, Current Domain Resource Amount = (0 bytes) 0, Requested Resource Amount = (1 bytes) 1., <nil>
Error while deploying VM with worker 7: CloudStack API error 535 (CSExceptionErrorCode: 9999): Maximum domain resource limits of Type 'user_vm' for Domain Id = 9 is exceeded: Domain Resource Limit = (1 bytes) 1, Current Domain Resource Amount = (0 bytes) 0, Requested Resource Amount = (1 bytes) 1., <nil>
Error while deploying VM with worker 4: CloudStack API error 535 (CSExceptionErrorCode: 9999): Maximum domain resource limits of Type 'user_vm' for Domain Id = 6 is exceeded: Domain Resource Limit = (1 bytes) 1, Current Domain Resource Amount = (0 bytes) 0, Requested Resource Amount = (1 bytes) 1., <nil>
Error while deploying VM with worker 0: CloudStack API error 535 (CSExceptionErrorCode: 9999): Maximum domain resource limits of Type 'user_vm' for Domain Id = 2 is exceeded: Domain Resource Limit = (1 bytes) 1, Current Domain Resource Amount = (0 bytes) 0, Requested Resource Amount = (1 bytes) 1., <nil>
Error while deploying VM with worker 9: CloudStack API error 535 (CSExceptionErrorCode: 9999): Maximum domain resource limits of Type 'user_vm' for Domain Id = 11 is exceeded: Domain Resource Limit = (1 bytes) 1, Current Domain Resource Amount = (0 bytes) 0, Requested Resource Amount = (1 bytes) 1., <nil>
Error while deploying VM with worker 3: CloudStack API error 535 (CSExceptionErrorCode: 9999): Maximum domain resource limits of Type 'user_vm' for Domain Id = 5 is exceeded: Domain Resource Limit = (1 bytes) 1, Current Domain Resource Amount = (0 bytes) 0, Requested Resource Amount = (1 bytes) 1., <nil>
Error while deploying VM with worker 1: CloudStack API error 535 (CSExceptionErrorCode: 9999): Maximum domain resource limits of Type 'user_vm' for Domain Id = 3 is exceeded: Domain Resource Limit = (1 bytes) 1, Current Domain Resource Amount = (0 bytes) 0, Requested Resource Amount = (1 bytes) 1., <nil>
Worker 8 created 1 VMs in 16.576664292s
Total time elapsed: 16.577598917s
```

Then applied patched version and re-ran the same test. All domains were able to create their 1 VM.

```
% ./cbench -benchmark vmcreate -workers 10 -jobs 1
Starting 10 workers to create 10 total VMs
Starting worker 9 to create 1 VMs
Starting worker 0 to create 1 VMs
Starting worker 5 to create 1 VMs
Starting worker 1 to create 1 VMs
Starting worker 2 to create 1 VMs
Starting worker 7 to create 1 VMs
Starting worker 6 to create 1 VMs
Starting worker 3 to create 1 VMs
Starting worker 4 to create 1 VMs
Starting worker 8 to create 1 VMs
Worker 0 created 1 VMs in 23.058241333s
Worker 1 created 1 VMs in 23.0738885s
Worker 6 created 1 VMs in 23.120527416s
Worker 4 created 1 VMs in 23.133709958s
Worker 8 created 1 VMs in 23.234045041s
Worker 2 created 1 VMs in 23.359964625s
Worker 3 created 1 VMs in 23.385948792s
Worker 5 created 1 VMs in 23.472282208s
Worker 9 created 1 VMs in 23.497680333s
Worker 7 created 1 VMs in 30.463185125s
Total time elapsed: 30.464112541s
```

**Review by mlsorensen — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
Thanks for sharing test results @mlsorensen let me help kick smoketests on this
@blueorangutan test

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Pull request merged**
