### PR TITLE
zone wizard: allow only one untagged physical network with guest traffic type

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR fixes https://github.com/apache/cloudstack/issues/8279 by allowing to specify tags for physical networks and adding checks to ensure that there can be only one untagged physical network having guest traffic.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):
image

image

### CODE REVIEW

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
> @vishesh92 can we add a new field in the wizard to specify the tag ? the API supports tags: https://cloudstack.apache.org/api/apidocs-4.19/apis/createPhysicalNetwork.html

@weizhouapache I have already added this.

**Comment by vishesh92** [comment]
> > @vishesh92 can we add a new field in the wizard to specify the tag ? the API supports tags: https://cloudstack.apache.org/api/apidocs-4.19/apis/createPhysicalNetwork.html
> 
> @weizhouapache I have already added this.

Let me add a snapshot for the same.

**Comment by vishesh92** [comment]
> if the error happens, will the "Fix errors" button appear and go to the step (in the screenshot) if click the button ?

I am not able to reproduce an issue in which it has to return to Physical Network creation page. I didn't make a lot of changes, so it shouldn't break any existing behavior.

**Comment by weizhouapache** [comment]
> > if the error happens, will the "Fix errors" button appear and go to the step (in the screenshot) if click the button ?
> 
> I am not able to reproduce an issue in which it has to return to Physical Network creation page. I didn't make a lot of changes, so it shouldn't break any existing behavior.

@vishesh92 
create two physical networks (both have Guest traffic) without tags ?

**Comment by vishesh92** [comment]
> @vishesh92 create two physical networks (both have Guest traffic) without tags ?

I have added a validation forcing the user to add tags to physical networks. So, can't reproduce with this scenario.

image

**Comment by weizhouapache** [comment]
> > @vishesh92 create two physical networks (both have Guest traffic) without tags ?
> 
> I have added a validation forcing the user to add tags to physical networks. So, can't reproduce with this scenario.
> 
> image

good
thanks @vishesh92 for sharing

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by andrijapanicsb** [comment]
I don't know if the first part of the message comes from some work from before or not, but the wording is not the best. Trafic labels are completely optional and the wording is wrong:
image
"...each **network** should have a label" should be "...each **traffic type** should have a label".

**Pull request merged**
