### PR TITLE
test_templates issue

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR improves test_templates.py. It is also meant for trouble shooting the template failures in smoke tests as in https://github.com/apache/cloudstack/pull/7345#issuecomment-1758790298.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by shwstppr — APPROVED** [review]
Code LGTM

**Review by rohityadavcloud — APPROVED** [review]
LGTM - let's test it

**Comment by DaanHoogland** [comment]
already tested it guys, and it reveals a real issue in the deploy as is test sequence. I'll give fixing it a go next week.

**Comment by rohityadavcloud** [comment]
Pl go ahead and merge if/when ready @DaanHoogland @shwstppr

**Comment by shwstppr** [comment]
@DaanHoogland cc @rohityadavcloud sorry but I created a new PR #8096 which fixes the template issues

**Comment by DaanHoogland** [comment]
obsolete

**Pull request closed without merging**
