### PR TITLE
On Upgrade, Replace the DB properties having master and slave(s), with source and replica(s) respectively for inclusiveness

### PR DESCRIPTION
**Pull request by sureshanaparti**
### Description
The following DB parameters are already updated as part of inclusivity changes (Refer: commit fe4a5b6e938e2f677d5d78cb5e6a12dce60a4a00 [1]). The new options 'secondsBeforeRetrySource', 'queriesBeforeRetrySource' works with mysql connector 8.0 [2][3] and supported for MySQL Server 5.6, 5.7 and 8.0.

- db.cloud.slaves => db.cloud.replicas
- db.cloud.secondsBeforeRetryMaster =>	db.cloud.secondsBeforeRetrySource
- db.cloud.queriesBeforeRetryMaster => db.cloud.queriesBeforeRetrySource
- db.usage.slaves => db.usage.replicas
- db.usage.secondsBeforeRetryMaster => db.usage.secondsBeforeRetrySource
- db.usage.queriesBeforeRetryMaster => db.usage.queriesBeforeRetrySource

This PR replaces these DB properties having master and slave(s), with source and replica(s) respectively on upgrade (for inclusiveness).

[1] https://github.com/apache/cloudstack/pull/4922/commits/fe4a5b6e938e2f677d5d78cb5e6a12dce60a4a00
[2] https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-config-failover.html
[3] https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-configuration-properties.html

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?
Manually tested with packages upgrade

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Review by rhtyd — APPROVED** [review]
LGTM in the draft - the changes in the db.properties file can be automated via upgrade handling of rpms. @sureshanaparti can you also check for debian packaging?

**Review by DaanHoogland — APPROVED** [review]
looks good, and what @rhtyd said; deb must have a similar mech.

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
> LGTM in the draft - the changes in the db.properties file can be automated via upgrade handling of rpms. @sureshanaparti can you also check for debian packaging?

updated @rhtyd

**Comment by weizhouapache** [comment]
@sureshanaparti 
to avoid potential issue, would it better to strictly search string in sed/grep commands, for example use "grep -w" and/or add "^","$" or space  ?, or use the full string in search, like 'db.cloud.slaves=' ?

**Review by DaanHoogland — APPROVED** [review]
looks good

**Comment by sureshanaparti** [comment]
> @sureshanaparti
> to avoid potential issue, would it better to strictly search string in sed/grep commands, for example use "grep -w" and/or add "^","$" or space ?, or use the full string in search, like '^db.cloud.slaves=' ?

@weizhouapache there are few params with master / slaves (mentioned in the description), and all these have to be replaced (for inclusiveness). I tested it, and no issues there. These terms have to be avoided in any property defined later.

**Review by vladimirpetrov — APPROVED** [review]
LGTM in this particular case, but I do agree with @weizhouapache - more safety is never a bad idea.

**Comment by weizhouapache** [comment]
> > @sureshanaparti
> > to avoid potential issue, would it better to strictly search string in sed/grep commands, for example use "grep -w" and/or add "^","$" or space ?, or use the full string in search, like '^db.cloud.slaves=' ?
> 
> @weizhouapache there are few params with master / slaves (mentioned in the description), and all these have to be replaced (for inclusiveness). I tested it, and no issues there. These terms have to be avoided in any property defined later.

@sureshanaparti in 99.99% cases it should work without any issue.
But, for example, if db user or db password contains "Master" or "slaves", will there be issues after uprgade ?

**Comment by sureshanaparti** [comment]
> LGTM in this particular case, but I do agree with @weizhouapache - more safety is never a bad idea.

@vladimirpetrov Updated changes as per @weizhouapache suggestion.

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
> > LGTM in this particular case, but I do agree with @weizhouapache - more safety is never a bad idea.
> 
> @vladimirpetrov Updated changes as per @weizhouapache suggestion.

@sureshanaparti great! code lgtm

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
> Trillian test result (tid-1176)
> Environment: kvm-centos7 (x2), Advanced Networking with Mgmt server 7
> Total time taken: 42990 seconds
> Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr5162-t1176-kvm-centos7.zip
> Intermittent failure detected: /marvin/tests/smoke/test_diagnostics.py
> Intermittent failure detected: /marvin/tests/smoke/test_loadbalance.py
> Intermittent failure detected: /marvin/tests/smoke/test_routers_network_ops.py
> Intermittent failure detected: /marvin/tests/smoke/test_vpc_redundant.py
> Smoke tests completed. 86 look OK, 2 have error(s)
> Only failed tests results shown below:
> 
> Test	Result	Time (s)	Test File
> test_05_ping_in_cpvm_success	`Failure`	14.32	test_diagnostics.py
> test_03_create_redundant_VPC_1tier_2VMs_2IPs_2PF_ACL_reboot_routers	`Failure`	472.14	test_vpc_redundant.py
> test_05_rvpc_multi_tiers	`Failure`	516.21	test_vpc_redundant.py

these failures are not related to this PR

**Comment by sureshanaparti** [comment]
merging this based on lgtms, manual and smoke tests

**Pull request merged**
