### PR TITLE
Fix a typo when performing network operations

### PR DESCRIPTION
**Pull request by zap51**
Fix a typo where the word "Security" is misspelled as "Secrity".

### Description

This PR fixes a typo of the word "Security".

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### CODE REVIEW

**Review by weizhouapache — APPROVED** [review]

**Review by DaanHoogland — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@zap51 if you want you can rebase on an earlier branch, otherwise it will be for 4.17.

**Review by GabrielBrascher — APPROVED** [review]

**Comment by sureshanaparti** [comment]
> @zap51 if you want you can rebase on an earlier branch, otherwise it will be for 4.17.

@zap51 Can you confirm whether this is good to go in 4.16.1.

**Review by sureshanaparti — APPROVED** [review]
typo correction, lgtm

**Comment by zap51** [comment]
> > @zap51 if you want you can rebase on an earlier branch, otherwise it will be for 4.17.
> 
> @zap51 Can you confirm whether this is good to go in 4.16.1.

@sureshanaparti Yes. Thanks!

**Comment by sureshanaparti** [comment]
> > > @zap51 if you want you can rebase on an earlier branch, otherwise it will be for 4.17.
> > 
> > 
> > @zap51 Can you confirm whether this is good to go in 4.16.1.
> 
> @sureshanaparti Yes. Thanks!

@zap51 ok, can you please rebase with '4.16' branch.

**Review by GutoVeronezi — APPROVED** [review]
LGTM

**Comment by sureshanaparti** [comment]
ping @zap51 can you rebase with '4.16'. thanks.

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
Merging based on travis job#1 as this is just doc/string change.

**Pull request merged**
