### PR TITLE
Fixes raw templates not downloading

### PR DESCRIPTION
**Pull request by Spaceman1984**
## Description

This PR fixes an error where raw template files are not being downloaded

Fixes: #2820 
## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

This was tested by adding a raw template to be downloaded from the UI

### CODE REVIEW

**Comment by Spaceman1984** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
testing, very risk poor change (downloading/image store only.

**Comment by andrijapanicsb** [comment]
LGTM

Tested with  http://download.cloudstack.org/testing/CentOS-7-x86_64-GenericCloud-1511.raw.bz2 (temp abuse of the hosting, due to lack of availability of raw.bz2 images online on plain HTTP)

Works fine, downloaded, unpacked, and eventually Ready.
image

image

**Comment by andrijapanicsb** [comment]
2 x approvals, automated regression tests fine, manual (fix) tests fine.

Merging based on ^^^

**Pull request merged**
