### PR TITLE
4.13.0.0/master: health checks smoketests

### PR DESCRIPTION
**Pull request by yadvr**
Dummy commit for health checks

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-65u2

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test centos7 xenserver-71

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan test centos7 xenserver-71

**Comment by shwstppr** [comment]
VMware router start failure is with,
```
2019-08-05 15:41:04,252 ERROR [c.c.u.s.SshHelper] (DirectAgent-177:ctx-8fff0c25 10.2.2.141, job-1912/job-1913, cmd: AggregationControlCommand) (logid:cf1e62b8) SSH execution of command /opt/cloud/bin/vr_cfg.sh -c /var/cache/cloud/VR-0eb49049-ddcc-4176-9b97-ad1cac301d3b.cfg has an error status code in return. Result output: 
2019-08-05 15:41:04,252 DEBUG [c.c.h.v.r.VmwareResource] (DirectAgent-177:ctx-8fff0c25 10.2.2.141, job-1912/job-1913, cmd: AggregationControlCommand) (logid:cf1e62b8) vr_cfg.sh execution result: false
```
On manual stop/start VR, script execution returns true with following output,
```
P[true:Error: argument "table" is wrong: node type value is invalid

RTNETLINK answers: File exists
Error: argument "table" is wrong: node type value is invalid

RTNETLINK answers: File exists
Error: argument "table" is wrong: node type value is invalid

RTNETLINK answers: File exists
Error: argument "table" is wrong: node type value is invalid

RTNETLINK answers: File exists
[Wed Aug  7 12:44:20 2019] (pid=2105) [ERROR] can't open config file `/etc/conntrackd/conntrackd.conf'
]
```
Will further investigate

**Comment by rhtyd** [comment]
Last run, all pass: https://github.com/apache/cloudstack/pull/3547#issuecomment-520387823

**Comment by rhtyd** [comment]
@blueorangutan

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan test centos7 xenserver-71

**Comment by rhtyd** [comment]
@blueorangutan test centos7 xenserver-71

**Comment by DaanHoogland** [comment]
@blueorangutan sweep

**Pull request closed without merging**
