### PR TITLE
Add action button to enable/disable Oauth provider

### PR DESCRIPTION
**Pull request by abh1sar**
### Description

Fixes: https://github.com/apache/cloudstack/issues/8501

1. Action button to enable/disable Oauth2 provider
2. Trim extra spaces from clientid, uri and secretkey

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):
Screenshot from 2024-06-13 14-02-12
Screenshot from 2024-06-13 14-02-24
Screenshot from 2024-06-13 14-02-46
Screenshot from 2024-06-13 14-02-57

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Review by shwstppr — APPROVED** [review]
Code LGTM

**Comment by rohityadavcloud** [comment]
LGTM
@blueorangutan ui

**Comment by kiranchavala** [comment]
@blueorangutan package

**Comment by abh1sar** [comment]
@blueorangutan package

**Review by rohityadavcloud — APPROVED** [review]

**Review by kiranchavala — APPROVED** [review]
LGTM, 

Before the fix, disable/enable the oauth provider was in the form

296233267-7ac42e71-a006-42a5-a425-633ecd9fdc19

After the fix disable/enable is moved to the top right corner action item



enable:disable

---
Also the extra spaces were removed

Before the fix, if the credentials contained a trailing space at the end, they were passed

Screenshot 2024-06-13 at 1 49 36 PM


After the fix , the trailing spaces are removed

Screenshot 2024-06-14 at 1 11 37 PM

**Comment by kiranchavala** [comment]
@blueorangutan test

**Pull request merged**
