### PR TITLE
vr: ipsec/l2tp vpn secret with no ID selectors

### LINKED ISSUE #4281: Problem with L2TP remote VPN
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME
L2TP VPN

##### CLOUDSTACK VERSION

4.14

##### CONFIGURATION
VPC network system vm version: 4.14.0

##### OS / ENVIRONMENT
Mac OS, Windows 10.

##### SUMMARY
I have got problem with remote VPN feature in VPC. Probably script generate bad config file at VPC VM:
/etc/ipsec.d/ipsec.any.secrets 

PUBLIC IP %any : PSK "PRESHAREDKEY"
When i edit it to:
 : PSK "PRESHAREDKEY and do ipsec rereadsecrets via shell at vac it starts to work.

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

according to https://wiki.strongswan.org/projects/strongswan/wiki/Ipsecsecrets , the ID selector is optional.

Not sure if this PR fixes #4281

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by rhtyd** [comment]
For testing on osx, with kvm - https://github.com/foxlet/macOS-Simple-KVM

**Review by sureshanaparti — APPROVED** [review]
@weizhouapache Tested on OS X, LGTM.

**Comment by weizhouapache** [comment]
> @weizhouapache Tested on OS X, LGTM.

thanks @sureshanaparti for testing !

**Comment by rhtyd** [comment]
Lgtm

**Pull request merged**
