### PR TITLE
CLOUDSTACK-10303 : test data to nuage_test_data.py + run all tests against simulator

### PR DESCRIPTION
**Pull request by smeetsr**

### CODE REVIEW

**Comment by smeetsr** [comment]
All tests in test/integration/plugins/nuagevsp have been executed for simulator See 
[results.txt](https://github.com/apache/cloudstack/files/1802846/results.txt)
and also on testbed with KVM hypervisors.

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by fmaximus** [comment]
@DaanHoogland Thanks for the review
Can we merge, or do we need CI?
All changes are in either Simulator, or our marvin tests,
so technically, running smoke isn't impacted.

**Comment by rhtyd** [comment]
Given all the changes are nuage specific tests related, and simulator has passed no additional integration testing is needed.

**Pull request merged**
