### PR TITLE
Clean up the duplicate volume (after failed migration) when the destination managed volume creation failed

### PR DESCRIPTION
**Pull request by sureshanaparti**
### Description

Duplicated volumes after failed migration in Allocated state

Fix: Clean up the duplicate volume when the destination managed volume creation failed on migrate volume operation

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

Manually tested the fix with failed migration, confirmed that the duplicate volume (in Allocated state) is cleaned up.

### CODE REVIEW

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Review by borisstoyanov — APPROVED** [review]
LGTM
Manually verified, needs to see smoketests results.

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
Some issue with smoketest (many failures, taking more than 10hrs), rekicking
@blueorangutan test

**Pull request merged**
