### PR TITLE
Fix a quote issue with Spanish L10N (from transifex translation)

### PR DESCRIPTION
**Pull request by milamberspace**
This fix is for the 4.8 branch.

### CODE REVIEW

**Comment by jburwell** [comment]
@milamberspace the Jenkins build build failed.  Could you please force push the change to trigger another attempt?

**Comment by milamberspace** [comment]
@jburwell I repush with force, but the build error still alive on Travis
"========> Processing SQL file at /home/travis/build/apache/cloudstack/developer/target/db/templates.simulator.sql

Unable to execute /home/travis/build/apache/cloudstack/developer/target/db/templates.simulator.sql: Unknown column 'state' in 'field list'"

I suppose it's an issue on 4.8 branch?

**Comment by jburwell** [comment]
@rhtyd do you any insight about the database schema issue @milamberspace is encountering in the Travis build?

**Comment by jburwell** [comment]
@milamberspace could you add a JIRA ticket for this issue and prefix the title of the commit message and PR title with the ID?

**Comment by rhtyd** [comment]
@jburwell @milamberspace due to version change in poms already merged on 4.8 without a valid db upgrade path (which I had added in a separate PR), we'll see db failures for all PRs targeting 4.8 branch. Please fix and merge #1654  first.

**Comment by milamberspace** [comment]
Thanks for reply @rhtyd I will wait the merge of #1654 before force to re-check this PR by travis/jenkins

**Comment by milamberspace** [comment]
@jburwell @rhtyd Since #1654 has been merged. Travis and Jenkins tests have passed. Ready to merge this small PR.

**Comment by jburwell** [comment]
@milamberspace I am trying to get this PR merged, but am running into some issues the git-pr script.  I am working with @rhtyd to figure out what I am doing wrong.

**Comment by rhtyd** [comment]
LGTM.

**Pull request merged**
