### PR TITLE
VR: remove apache2 config for removed VPC tiers

### LINKED ISSUE #7968: VR webserver apache2 failing to start
* Bug Report

COMPONENT NAME

VR - webserver.service

~~~

~~~

CLOUDSTACK VERSION

4.15.2

~~~

~~~

##### CONFIGURATION

Advanced Zone with KVM hypervisor - no security groups. VPC's with Redundant VR's

##### OS / ENVIRONMENT
All KVM hosts and MGMT/MySQL 8 servers are running Ubuntu 20.04. VR is default template

##### SUMMARY
We have recently started to see VR health check failures on the VR webserver.service. The error from the systemctl status apache2.service command is : cannot define multiple listeners on the same IP:port

##### STEPS TO REPRODUCE

Not sure how the issue is being caused but a VPC restart with cleanup seems to fix it

~~~

~~~

##### EXPECTED RESULTS
@weizhouapache 
Attached as requested are the /etc/apache2/ conf files
[apache2.tar.gz](https://github.com/apache/cloudstack/files/12618190/apache2.tar.gz)

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #7968

Steps to reproduce the issue
- create vpc with redundant VRs (cidr: 172.24.0.0/20)
- create vpc tier1 with 172.24.1.0/24, create vm1 on it
- create vpc tier2 with 172.24.2.0/24, create vm2 on it
- destroy vm2, delete vpc tier2
- create vpc tier2-new1 with 172.24.2.0/24, create vm2-new1 on it
- destroy vm2-new1, delete vpc tier2-new1
- create vpc tier2-new2 with 172.24.2.0/24, create vm2-new2 on it
- check apache2 config files in /etc/apache2/site-enabled

expected: there are only config files for tier1 and tier2-new2 
actual: there are config files for tier1, tier2, tier2-new1, tier2-new2

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
clgtm and seems to address the issue. Need to test

**Comment by weizhouapache** [comment]
@blueorangutan test

**Review by kiranchavala — APPROVED** [review]
LGTM, Tested the issue manually for both default vpc and redundant vpc offering

Followed the steps, and only the config files for the active tiers are present


1.     create vpc with redundant VRs (cidr: 172.24.0.0/20)
2.     create vpc tier1 with 172.24.1.0/24, create vm1 on it
3.     create vpc tier2 with 172.24.2.0/24, create vm2 on it
4.     destroy vm2, delete vpc tier2
5.     create vpc tier2-new1 with 172.24.2.0/24, create vm2-new1 on it
6.     destroy vm2-new1, delete vpc tier2-new1
7.     create vpc tier2-new2 with 172.24.2.0/24, create vm2-new2 on it
8.     check apache2 config files in /etc/apache2/site-enabled

**Comment by weizhouapache** [comment]
> LGTM, Tested the issue manually for both default vpc and redundant vpc offering
> 
> Followed the steps, and only the config files for the active tiers are present
> 
> ```
> 
> 1.     create vpc with redundant VRs (cidr: 172.24.0.0/20)
> 2.     create vpc tier1 with 172.24.1.0/24, create vm1 on it
> 3.     create vpc tier2 with 172.24.2.0/24, create vm2 on it
> 4.     destroy vm2, delete vpc tier2
> 5.     create vpc tier2-new1 with 172.24.2.0/24, create vm2-new1 on it
> 6.     destroy vm2-new1, delete vpc tier2-new1
> 7.     create vpc tier2-new2 with 172.24.2.0/24, create vm2-new2 on it
> 8.     check apache2 config files in /etc/apache2/site-enabled
> ```

thanks @kiranchavala for the testing

**Pull request merged**
