### PR TITLE
Refactor updateDiskOffering API

### PR DESCRIPTION
**Pull request by hsato03**
### Description

This PR intends to refactor the `updateDiskOffering` API due to its size. 

This method was separated into others in order to improve the readability of the disk offering update process.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [X] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

I called the `updateDiskOffering` API and it is working as it did before the refactoring. I also created some unit tests to maintain the current behavior and avoid regressions in the future.

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
clgtm and unit tests added

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by GutoVeronezi — APPROVED** [review]
CLGTM

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Pull request merged**
