### PR TITLE
ui: Consider overprovisioning when displaying allocated progress

### PR DESCRIPTION
**Pull request by davidjumani**
### Description

This PR fixes the UI info card by considering the overprovisioning factor while displaying the disk allocated progress bar

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

#### Before: 

Screenshot from 2021-03-20 10-26-53

#### After:

Screenshot from 2021-03-20 10-26-37

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan ui

**Review by shwstppr — APPROVED** [review]

**Review by utchoang — APPROVED** [review]
LGTM

**Comment by rhtyd** [comment]
@shwstppr @utchoang have you tested VM, volume, storage pool, snapshot and/or anything related to disk/storage?

**Comment by shwstppr** [comment]
@rhtyd I compared primary storage capacity with and without changes
Screenshot from 2021-03-22 13-30-15
Primary storages were the only place in UI where I could find these progress bars displayed

**Comment by davidjumani** [comment]
Primary storages is the only place where disksizeallocatedgb is used

**Comment by utchoang** [comment]
@rhtyd Tested in the primary storage.

**Comment by rhtyd** [comment]
Thanks all I'll merge based on your remarks and testing

**Pull request merged**
