### PR TITLE
Add missing HA config keys (#3776)

### PR DESCRIPTION
**Pull request by DaanHoogland**
## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by svenvogel** [comment]
@DaanHoogland how it looks like?

**Comment by DaanHoogland** [comment]
@svenvogel it passed all tests on 4.13. it had merge conflict so i'll run tests again here.
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@andrijapanicsb this is forward merged from the 4.13 branch and had LGTMs and tests. It had merge conflicts however but all looks fine now. merge?

**Comment by andrijapanicsb** [comment]
You know your stuff @DaanHoogland - so if you are happy, yes.

**Pull request merged**
