### PR TITLE
Backport #9708

### PR DESCRIPTION
**Pull request by JoaoJandre**
### Description

This PR backports #9708 to 4.20

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by JoaoJandre** [comment]
Could you check if its ok @abh1sar ?

**Comment by weizhouapache** [comment]
@JoaoJandre
If there is no conflicts, I think you can backport the commits by 'git cherry-pick' command and push to the repo directly

**Review by abh1sar — APPROVED** [review]
Thanks for doing the back port @JoaoJandre

**Review by rohityadavcloud — APPROVED** [review]

**Comment by JoaoJandre** [comment]
@weizhouapache Ok, I'll do it like that next time

**Pull request merged**
