### PR TITLE
make NoopDbUpgrade do a systemvm template check

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR adds systemvm upgrade check to the noop upgrade
Fixes: #6980

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
Needs another review and perhaps testing, LGTM

**Comment by DaanHoogland** [comment]
> Needs another review and perhaps testing, LGTM

@vladimirpetrov promised some testing, let's see what he finds.

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
running an upgrade test from 4.14 to this...

**Review by vladimirpetrov — APPROVED** [review]
LGTM based on manual testing. I did various upgrades and found no issues.

**Pull request merged**
