### PR TITLE
[CLOUDSTACK-9444] Fix a little issue from PR1610 if the db.properties file hasn't EOL c…

### PR DESCRIPTION
**Pull request by milamberspace**
…haracter at the end of file

And some improvements about the dir/file using variables

cc @wido @rhtyd

### CODE REVIEW

**Comment by rhtyd** [comment]
LGTM thanks @milamberspace

**Comment by wido** [comment]
LGTM!

Thanks for the fix. Could you also open one for master? It needs to be fixed there as well.

**Comment by karuturi** [comment]
We dont need a PR for master. It will be forward merged. 
If you can create a jira ticket for this (even better would be to reuse the one used in PR1610), it will be useful.

**Comment by milamberspace** [comment]
Jira ticket done.
CLOUDSTACK-6671

**Comment by rhtyd** [comment]
The changes won't be tested by Trillian as it does not support upgrade tests yet. Based on the packaging result, we can accept it if anyone has performed an upgrade test manually. /cc @karuturi @jburwell

**Comment by jburwell** [comment]
@borisstoyanov do you have the bandwidth to manually test upgrading 4.8 to 4.9 using this patch?

**Comment by borisstoyanov** [comment]
@jburwell I can do it late next week, pretty stacked up currently.

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by jburwell** [comment]
I would like to get this PR into 4.9.1.0.

@borisstoyanov have you gotten a change to test this PR?

@rhtyd @milamberspace could you investigate the cause of the Travis build failure?

**Comment by rhtyd** [comment]
@jburwell the cause of failure is due to an env issue (`java.lang.OutOfMemoryError: PermGen space issue`), @milamberspace can you close and open the PR, or do a push -f to force Travis to run again?

**Comment by borisstoyanov** [comment]
LGTM

**Comment by milamberspace** [comment]
@rhtyd @jburwell The travis and jenkins builds are OK now. 3 LGTM. Ready to merge.

**Comment by rhtyd** [comment]
Thanks @milamberspace for the PR, I'll merge it now.

**Pull request merged**
