### PR TITLE
add logs to ipallocation attempt

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR...

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [x] extra logging
- [ ] 
#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by vishesh92 — APPROVED** [review]
clgtm

This might need some changes while forward merging

**Review by JoaoJandre — APPROVED** [review]
CLGTM

**Comment by DaanHoogland** [comment]
@JoaoJandre , will we merge this after an RC or before?

**Comment by JoaoJandre** [comment]
> @JoaoJandre , will we merge this after an RC or before?

@DaanHoogland only after the release.

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test alma9 kvm-alma9

**Comment by weizhouapache** [comment]
code lgtm

**Pull request merged**
