### PR TITLE
revert dedicate vlan code removal

### LINKED ISSUE #2545: dedicatePublicIpRange to domain doesn't work
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME

~~~
Network (Public)
~~~

##### CLOUDSTACK VERSION

~~~
4.11.0.0
~~~

##### CONFIGURATION
advanced networking

##### OS / ENVIRONMENT
Ubuntu 16.04 (Management/Hypervisor)
KVM

##### SUMMARY
dedicate a public IP range to a domain doesn't work

##### STEPS TO REPRODUCE

~~~
create a new (should not be the first) public IP range  
dedicate this range to a domain
acquire a new public IP in a project which is located in the specified domain
~~~

##### EXPECTED RESULTS

~~~
get a IP which is located in the specified IP range for this domain
~~~

##### ACTUAL RESULTS

~~~
ip is acquired from an other public pool (first created public IP range - with no assignment for domain)
~~~

### PR DESCRIPTION
**Pull request by DaanHoogland**
## Description

this supposedly fixes #2545, as reported by the issuer. Testing will need to be added as of now. 

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## GitHub Issue/PRs

Fixes: #2545

## Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
Testing
- [ ] I have added tests to cover my changes.
- [ ] All relevant new and existing integration tests have passed.
- [ ] A full integration testsuite with all test that can run on my environment has passed.

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by borisstoyanov** [comment]
It says 'Fixes: #2545', I think we're all happy on this one can we merge?

**Comment by DaanHoogland** [comment]
@rafaelweingartner it reverts only a small (four line) part of a more than 1800 line change

**Comment by rafaelweingartner** [comment]
I see. Thanks.

**Comment by rhtyd** [comment]
This looks like we're in violent agreement on this. I'll merge this so as to not block RC1, based on reviews and Travis okay. If smoketests have a new error, we'll reconsider a fix as another PR.

**Pull request merged**
