### PR TITLE
CPVM: move focus on input area after clearing clipboard

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

When click "Clear" button in the clipboard dialog on vm console, the input area is cleared but the page still focuses on the "Clear" button. 
It is inconvenient for end users as normally users want to re-input after clearing the input. 

This PR moves the focus on the input area after clearing.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@blueorangutan ui

**Comment by DaanHoogland** [comment]
actually, a simulated test env is not useful for this...

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
> actually, a simulated test env is not useful for this...

@DaanHoogland 
indeed, need a real cpvm for testing

**Review by rohityadavcloud — APPROVED** [review]

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
tested in a lab env; can enter any command and send it. If followed by a newline it will be executed. pressing clear will focus on the edit box and a new command can be entered.

(too bad paste from the console back doesn't work)

**Pull request merged**
