### PR TITLE
writeIfNotHere requires an array of strings, not a string

### PR DESCRIPTION
**Pull request by hogniRunar**

### CODE REVIEW

**Comment by pdube** [comment]
Hi @hogniRunar,

The code change LGTM. I verified for references to the function, but did not test it. Could you create a JIRA ticket for it please? Could you also add some information as to how do you reproduce the error, and how to test the fix?

Thanks

**Comment by hogniRunar** [comment]
To reproduce it you just need to set up a basic baremetal zone, start an instance and on the bootserver for baremetal you can look at /var/www/html/metadata/<IP of instance>/meta-data. As for testing I am not sure what would be the best way other than looking at that same file once the fix has been implemented.

Ticket:
https://issues.apache.org/jira/browse/CLOUDSTACK-9330

**Comment by swill** [comment]
### CI RESULTS

```
Tests Run: 85
  Skipped: 0
   Failed: 1
   Errors: 0
 Duration: 4h 19m 54s
```

**Summary of the problem(s):**
```
FAIL: Test redundant router internals
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/git/cs1/cloudstack/test/integration/smoke/test_routers_network_ops.py", line 483, in test_02_RVR_Network_FW_PF_SSH_default_routes_egress_false
    "Attempt to retrieve google.com index page should be successful once rule is added!"
AssertionError: Attempt to retrieve google.com index page should be successful once rule is added!
----------------------------------------------------------------------
Additional details in: /tmp/MarvinLogs/test_network_MVU2HC/results.txt
```



**Associated Uploads**

**`/tmp/MarvinLogs/DeployDataCenter__May_12_2016_05_55_59_X571TZ:`**
* [dc_entries.obj](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1456/tmp/MarvinLogs/DeployDataCenter__May_12_2016_05_55_59_X571TZ/dc_entries.obj)
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1456/tmp/MarvinLogs/DeployDataCenter__May_12_2016_05_55_59_X571TZ/failed_plus_exceptions.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1456/tmp/MarvinLogs/DeployDataCenter__May_12_2016_05_55_59_X571TZ/runinfo.txt)

**`/tmp/MarvinLogs/test_network_MVU2HC:`**
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1456/tmp/MarvinLogs/test_network_MVU2HC/failed_plus_exceptions.txt)
* [results.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1456/tmp/MarvinLogs/test_network_MVU2HC/results.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1456/tmp/MarvinLogs/test_network_MVU2HC/runinfo.txt)

**`/tmp/MarvinLogs/test_vpc_routers_9QM5ZD:`**
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1456/tmp/MarvinLogs/test_vpc_routers_9QM5ZD/failed_plus_exceptions.txt)
* [results.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1456/tmp/MarvinLogs/test_vpc_routers_9QM5ZD/results.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1456/tmp/MarvinLogs/test_vpc_routers_9QM5ZD/runinfo.txt)


Uploads will be available until `2016-07-12 02:00:00 +0200 CEST`

*Comment created by [`upr comment`](https://github.com/cloudops/upr).*

**Comment by swill** [comment]
Can I get another code review so this can be merged?

**Comment by DaanHoogland** [comment]
LGTM

**Pull request merged**
