### PR TITLE
Fix resource count discrepancy while associating IP address to a network

### LINKED ISSUE #9464: Race condition in resource count while associating IP address to a network
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Resource Limits Manager for public_ip
~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### SUMMARY

Due to certain race conditions between checking and incrementing of resource counts, the check can be bypassed. This leads to cases where account's allocated resources exceeds the accounts limit.

##### STEPS TO REPRODUCE

1. Create an account with public ip limit to 2
2. Create a network and deploy a VM (This will increase the public_ip count by 1 for the account).
3. Allocate different IPs to the same network in parallel (around 4-5 requests).

This sometimes leads to allocated resources exceeding the account's limit.

~~~

~~~

##### EXPECTED RESULTS

~~~
Count of allocated resources  should not exceed the account's limit.

~~~

##### ACTUAL RESULTS

Count of allocated resources  exceeded the account's limit.

~~~

~~~

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR fixes #9464

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan test

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Comment by sureshanaparti** [comment]
@vishesh92 linked issue targeted for 4.19.2, can rebase this with 4.19 branch?

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by DaanHoogland — APPROVED** [review]
clgtm, i'll try to reproduce (issue and fix)

**Comment by DaanHoogland** [comment]
before:
```
for i in 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 ; do   cmk associate ipaddress account=ACSUser domainid=0138c7b1-75d6-11ef-85da-1e00d40003a2 networkid=60a9f348-5d07-4614-a2b3-4422f48c4972 zoneid=93d46e79-8af4-429c-adec-da9500ab16ea ipaddress=10.0.54.$i & done 
```
leads to 
Screenshot from 2024-09-19 10-39-29
Screenshot from 2024-09-19 10-39-52

after applying the patch I tried several times to get more than one IP address, with the above script, but failed.

**Pull request merged**
