### PR TITLE
cloudstack: bump to use 4.18.1.0 systemvmtemplate

### PR DESCRIPTION
**Pull request by rohityadavcloud**
Use new 4.18.1.0 systemvmtemplate, that addresses many new pkgs with security/improvement fixes. 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by rohityadavcloud** [comment]
Kicking a build on jenkins;
Screenshot 2023-08-08 at 4 26 24 PM

Will consult and upload the systemvmtemplate builds first on download.cloudstack.org @weizhouapache @DaanHoogland before we run pkg with this PR

**Comment by rohityadavcloud** [comment]
Uploaded at https://download.cloudstack.org/systemvm/4.18/ pl check @DaanHoogland @weizhouapache - and suggest if we need to mirror them in the jenkins/staging server before we use BO to build pkgs/kick tests?

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan test matrix

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Review by pdion891 — APPROVED** [review]
lgtm

**Comment by pdion891** [comment]
@rohityadavcloud , I'm currently trying to build the systemvm template for 4.18 and it's failing because  apt package 'python' does not exist anymore. should it be replaced by 'python-is-python3' and update python-netaddr by python3-netaddr ?

**Comment by rohityadavcloud** [comment]
Hi @pdion891 thanks for the review, are you using Debian 11 or 12 (bookworm) ISO or which distro as the host?

This uses Debian 11 ISO and for building the systemvmtemplate, I used a Ubuntu 20.04.6 server + Jenkins + packer v1.8.5

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by pdion891** [comment]
Hi @rohityadavcloud , 

so I've just tried to build a systemvm template from 4.18.0 today using https://cdimage.debian.org/mirror/cdimage/archive/11.7.0/amd64/iso-cd/debian-11.7.0-amd64-netinst.iso, and python package was not found. so there must be something off on my side since your build log do not complain and fail the same way.

Using Packer v1.9.2

I'll retry the build with rebased 4.18 branch with this new iso url...

Cheers,

**Comment by rohityadavcloud** [comment]
My build server is based on old Ubuntu 20.04 so it’s possible python meant python2, perhaps you could put a symlink to python2 for python and try again ?

**Comment by pdion891** [comment]
sorry for the confusion, 

I'm referring to python package installation in the systemvm in packer: https://github.com/apache/cloudstack/blob/main/tools/appliance/systemvmtemplate/scripts/install_systemvm_packages.sh#L56

I had package not found issue but changing it to 'python-is-python3' and changing 'python-netaddr' by 'python3-netaddr' was fixing building error during the package installation. But I've just retest the systemvm build from the community 4.18 branch using this updated URL for the ISO and it work just fine, so please ignore my issue :-)

**Comment by rohityadavcloud** [comment]
@blueorangutan test matrix

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by weizhouapache** [comment]
@blueorangutan test centos7 xenserver-71

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Comment by weizhouapache** [comment]
all look good
Checked the log, the md5sum of system templates are correct.
Merging

**Pull request merged**
