### PR TITLE
pom.xml: correct url of libvirt maven2

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR...

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
clgrtm, and I can reach https://download.libvirt.org/maven2

**Comment by DaanHoogland** [comment]
@weizhouapache the old one is still not reachable and the new one is, do we merge this?

**Comment by weizhouapache** [comment]
> @weizhouapache the old one is still not reachable and the new one is, do we merge this?

@DaanHoogland 
the old one was not reachable  yesterday, but now it is redirected to same url.
so this PR is not needed any more

**Comment by DaanHoogland** [comment]
> > @weizhouapache the old one is still not reachable and the new one is, do we merge this?
> 
> @DaanHoogland the old one was not reachable yesterday, but now it is redirected to same url. so this PR is not needed any more

You are right, I tried without the trailing / :( it works again

**Pull request closed without merging**
