### PR TITLE
Improvements after jquery update

### PR DESCRIPTION
**Pull request by NicoWohlfarth**
## Description
Fixed issues occurring with [this PR](https://github.com/apache/cloudstack/pull/3069)
Added jQuery ui CSS to the project and adapt existing stylings
Removed unnecessary styling definitions from cloudstack.css
Swap no longer recommended jQuery method

## Types of changes
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?
We deployed the changes to our test environment and tested the UI functionality by clicking through the affected views

### CODE REVIEW

**Comment by svenvogel** [comment]
@GabrielBrascher @borisstoyanov @rhtyd @rafaelweingartner can you check please 👍

**Comment by svenvogel** [comment]
@wido @GabrielBrascher @borisstoyanov @rhtyd @rafaelweingartner can anybody add a ui symbol and review it?

**Comment by svenvogel** [comment]
this pr fixes the following problems.

Bildschirmfoto 2019-03-12 um 11 37 06
image

**Comment by svenvogel** [comment]
Bildschirmfoto 2019-03-12 um 11 43 50

fix3

**Comment by svenvogel** [comment]
Bildschirmfoto 2019-03-12 um 11 46 44

fix4

**Comment by DaanHoogland** [comment]
@NicoWohlfarth Can you explain what these pictures are making clear? not all of them are selfevident.
@rafaelweingartner aren't these bugfixes, instead of enhancements?
LGTM overall, thanks @NicoWohlfarth .

**Comment by rafaelweingartner** [comment]
@DaanHoogland I selected the wrong label. Thanks Daan.

**Comment by DennisKonrad** [comment]
image

This is how it looks now

**Comment by PaulAngus** [comment]
@blueorangutan package

**Comment by PaulAngus** [comment]
@blueorangutan test

**Comment by NicoWohlfarth** [comment]
Hi @borisstoyanov.
I can't reproduce your indicated behavior even without my changes.
Without my changes you still would need to select the radio button directly to be able to navigate between the options with the arrow keys.

**Comment by borisstoyanov** [comment]
@NicoWohlfarth if you click on the text you select the option, but your not able to navigate with arrows, if you click on the radio button you'll be able to use the arrows, that's what I see on my Chrome for Mac.

**Comment by svenvogel** [comment]
@borisstoyanov We are speaking about it internally and i come back ;)

**Comment by PaulAngus** [comment]
@blueorangutan package

**Comment by PaulAngus** [comment]
Manually checked the changes LGTM - can we get this merged. Even if it is not perfect, it is better, so lets merge and then everyone can add further fixes on top..

cc @borisstoyanov @rhtyd

**Comment by rhtyd** [comment]
@PaulAngus let me review this later today/tomorrow, several css rules have been removed which needs checking as they could potentially add regression.

**Comment by svenvogel** [comment]
@PaulAngus @rhtyd should be ok. We create after that a new one to add another changes. We changed ui to a jquery library to make it easier in the future.

**Comment by svenvogel** [comment]
@rhtyd some news about that? further changes we would make a new pr. ;)

**Comment by rhtyd** [comment]
@svenvogel I think we may accept the changes based on manual testing. cc @borisstoyanov  - can you help with testing when you've time this week, thanks.

@svenvogel in your last reply you hinted that you're creating a new UI library? Can you elaborate, is it already part of this PR?

**Comment by svenvogel** [comment]
@rhtyd Hi Rohit, yes the the library are always included in cloudstack because they are a part of JQuery UI. we took a upgrade for any month #3069. Yes please look over it so that we can merge it. we will make a new PR for new changes. 

@PaulAngus Can you approve it too?

**Comment by DennisKonrad** [comment]
We are using this for weeks now and the library update works just fine. LGTM

@rhtyd Nearly all of the UI fixes here are not caused by the jQuery update. We will fix them anyway but in another PR. This one is for the jQeury libraries.

 I think this one is very good now :)

**Comment by DennisKonrad** [comment]
> @svenvogel in your last reply you hinted that you're creating a new UI library? Can you elaborate, is it already part of this PR?

No new UI library. We try to get the existing code into good shape. Therefor the jQuery library updates.

**Comment by svenvogel** [comment]
@DennisKonrad i wrote that already above

**Comment by svenvogel** [comment]
> @NicoWohlfarth if you click on the text you select the option, but you're not able to navigate with arrows, if you click on the radio button you'll be able to use the arrows, that's what I see on my Chrome for Mac.

https://github.com/apache/cloudstack/pull/3183#issuecomment-473906611

@borisstoyanov Hi Boris, this we will do in a another pr. its the best like Paul said to merge and we create new ones for other changes.

@GabrielBrascher can you take also a look on this?

**Comment by DennisKonrad** [comment]
@borisstoyanov Do you agree on fixing the "arrow down scrolling in templates" in another PR? If yes could you re-review?

We would like to get this merged. We will fix problems one by one.

**Comment by rafaelweingartner** [comment]
People discussed, reviewed and approved the PR.

It is pure JS and CSS changes. Therefore, the integration tests (that test Java code)  are not relevant in this context.

Thank you all for the reviews and code changes

**Pull request merged**
