### PR TITLE
[4.11/master] Smoketest Health Check

### PR DESCRIPTION
**Pull request by rhtyd**
@blueorangutan package

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
I found an issue with `bind.interface` being empty that makes mgmt server listen on 127.0.0.1:8080 and causes trilian failures. Using comments/discussion from #2226 I've added a fix on master - 8c515df3e412591b58091862062d81009676041d

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-55u3

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@borisstoyanov good find, under what params/API cases this happens and it's not failing for KVM/Vmware?

**Comment by rhtyd** [comment]
Thanks @borisstoyanov I found a potential NPE causing code and fixed in #2211

**Comment by borisstoyanov** [comment]
Maybe it's a good idea to address each issue in a separate PR, just in case #2211 drops out of 4.11, thoughts @rhtyd ?

**Comment by rhtyd** [comment]
@borisstoyanov I disagree, #2211 already should qualify for merging -- we've all smoke tests passing on KVM, all smoke (except for one vpc_redundant test case) tests passing on XenServer. Given lab related IO issues, we've some failing tests on VMware and we've about a month to freeze date.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Pull request closed without merging**
