### PR TITLE
CLOUDSTACK-8781 : Superfluous field during VPC creation

### PR DESCRIPTION
**Pull request by nlivens**

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@wilderrodrigues I agree. @nlivens maybe a conditional display can be concocted. I suppose you made this because the dropdown was hindering your eyesight..?

**Comment by nlivens** [comment]
@wilderrodrigues, @DaanHoogland, I removed the field since it's not used at all in the code.
No matter what you select in that dropdown, the value will be ignored. Therefore I thought it would be good to just remove the field since it can only create confusion for the users. That's the only reason for this PR :)

**Comment by wilderrodrigues** [comment]
As @DaanHoogland suggested, if one should not see the Netscaler option, then I fix should be put in place where a condition is checked and upon that the drop-box will be showed or not.

The PR should not be merged with the fix it contains because it will remove the  Netscaler support for VPCs form the UI, making it possible only via API/CloudMonkey

:-1: 

Cheers,
Wilder

**Comment by nlivens** [comment]
@wilderrodrigues, this change doesn't remove the Netscaler support for VPCs from the UI. The actual Public Load Balancer provider is derived from the VPC offering, and not from this extra field "Public Load Balancer Provider". So, this field has no use at all since it's completely ignored.

**Comment by wilderrodrigues** [comment]
Hi @nlivens 

Okay... I will have a look at the code. Very weird to have it there and not use it. :)

Cheers,
Wilder

**Comment by rhtyd** [comment]
@nlivens please rebase against latest master and push -f

LGTM, the removed code (publicLoadBalancerProvider key) is not referenced in any of the actions or dataProviders to create and send the `data` payload

tag:easypr

**Comment by nlivens** [comment]
@rhtyd, rebased against latest master

**Comment by bvbharatk** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 132
 Hypervisor xenserver
 NetworkType Advanced
 Passed=70
 Failed=1
 Skipped=3

_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/yj3wnzbceo9uef2/AAB6u-Iap-xztdm6jHX9SjPja?dl=0


**Failed tests:**
* test_service_offerings.py

 * ContextSuite context=TestServiceOfferings>:setup Failing since 7 runs


**Skipped tests:**
test_vm_nic_adapter_vmxnet3
test_static_role_account_acls
test_deploy_vgpu_enabled_vm

**Passed test suits:**
test_deploy_vm_with_userdata.py
test_affinity_groups_projects.py
test_portable_publicip.py
test_vpc_vpn.py
test_over_provisioning.py
test_global_settings.py
test_scale_vm.py
test_routers_iptables_default_policy.py
test_routers.py
test_reset_vm_on_reboot.py
test_snapshots.py
test_deploy_vms_with_varied_deploymentplanners.py
test_login.py
test_list_ids_parameter.py
test_public_ip_range.py
test_multipleips_per_nic.py
test_regions.py
test_affinity_groups.py
test_network_acl.py
test_pvlan.py
test_volumes.py
test_nic.py
test_deploy_vm_root_resize.py
test_resource_detail.py
test_secondary_storage.py
test_vm_life_cycle.py
test_disk_offerings.py

**Comment by prashanthvarma** [comment]
@rhtyd, rebased against latest master

**Comment by rhtyd** [comment]
I'm not sure about the changes, but if the mentioned field is not consumed anywhere, it LGTM. Can we have a manual UI screenshot to confirm changes since this is a pure UI change?

**Comment by prashanthvarma** [comment]
@rhtyd Here are the screen-shots without and with this UI bug fix:

6a4ded44-adb4-4821-bceb-3eb8c44c79f8

rsz_screenshot_from_2016-11-21_15-15-52

As pointed out by @nlivens in the previous comment, "The actual Public Load Balancer provider is derived from the VPC offering, and not from this extra field "Public Load Balancer Provider". So, this field has no use at all since it's completely ignored."

The cleaner implementation for this UI tab would be to only list "Public Load Balancer Providers" mentioned in the selected VPC offering. Moreover, don't show this tab, if there are no "Public Load Balancer Providers" being mentioned in the selected VPC offering. Finally, make use of the selected  "Public Load Balancer Provider" in the actual implementation of the VPC.

**Comment by rhtyd** [comment]
Thanks, merging this now.

**Pull request merged**
