### PR TITLE
Remove condition that are prevent resizing for root volumes (vmware)

### PR DESCRIPTION
**Pull request by DK101010**
### Description

Remove condition that are prevent resizing for root volumes (vmware).

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?
Tested in own VMware Environment. Works without errors and root disk is correct resized

### CODE REVIEW

**Comment by mib1185** [comment]
@blueorangutan test centos7 vmware-65u2

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-65u2

**Comment by mib1185** [comment]
@shwstppr I guess that these error are not related to changes from this PR 🤔

**Comment by shwstppr** [comment]
@mib1185 yes they don't seem to be related. Moreover,  2nd and 3rd failure in that list should be fixed by #5170

**Comment by mib1185** [comment]
@blueorangutan package

**Comment by mib1185** [comment]
@blueorangutan test centos7 vmware-65u2

**Comment by mib1185** [comment]
@blueorangutan test centos7 vmware-65u2

**Comment by mib1185** [comment]
@blueorangutan

**Comment by mib1185** [comment]
@blueorangutan help

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-65u2

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan test centos7 vmware-65u2

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by nvazquez** [comment]
@davidjumani can you please test this PR?

**Review by davidjumani — APPROVED** [review]
Able to resize the root volume on a running VM with rootDiskController=scsi

**Comment by nvazquez** [comment]
Thanks @davidjumani 
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test centos7 vmware-65u2

**Review by nvazquez — APPROVED** [review]

**Pull request merged**
