### PR TITLE
Fix: rpm dependencies: which and file

### PR DESCRIPTION
**Pull request by annProg**
### Description
`createtmplt.sh` will use `file`, and `setup-sysvm-tmplt` will use `which`. this is log:

```
/usr/share/cloudstack-common/scripts/storage/secondary/setup-sysvm-tmplt: line 74: which: command not found
/usr/share/cloudstack-common/scripts/storage/secondary/createtmplt.sh: line 56: file: command not found
/usr/share/cloudstack-common/scripts/storage/secondary/createtmplt.sh: line 75: file: command not found
/usr/share/cloudstack-common/scripts/storage/secondary/createtmplt.sh: line 42: file: command not found
/usr/share/cloudstack-common/scripts/storage/secondary/setup-sysvm-tmplt: line 74: which: command not found
/usr/share/cloudstack-common/scripts/storage/secondary/createtmplt.sh: line 56: file: command not found
/usr/share/cloudstack-common/scripts/storage/secondary/createtmplt.sh: line 75: file: command not found
/usr/share/cloudstack-common/scripts/storage/secondary/createtmplt.sh: line 42: file: command not found
```
when no `which` and `file`, systemvm template can not be import correctly(not decompressed, stay bzip2), then `libvirtd` will report error:

```
Could not open backing file: Image is not in qcow2 format
```

Then systemvm can not be started.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@annProg what version did you find this in and in which version would you like to see it? you are now basing this off of main which means it will go into 4.18 at the soonest.

**Comment by annProg** [comment]
> @annProg what version did you find this in and in which version would you like to see it? you are now basing this off of main which means it will go into 4.18 at the soonest.

`4.16.1.0`. I can install them manually, so 4.18 is ok

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by rohityadavcloud — APPROVED** [review]

**Review by DaanHoogland — APPROVED** [review]

**Pull request merged**
