### PR TITLE
vmware cks: Guard k8s cluster root disk resize if no root disk size passed

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

This PR prevents k8s cluster nodes' root disks from being resized on VMware if root disk size isn't provided and addresses a test regression on scale vm. 
```
2021-04-27 06:26:28,971 ERROR [c.c.k.c.a.KubernetesClusterActionWorker] (API-Job-Executor-8:ctx-8126598d job-803 ctx-9a6a3ae2) (logid:f9bfd370) Provisioning the master VM failed in the Kubernetes cluster : k8s
com.cloud.exception.InvalidParameterValueException: Going from existing size of 4756340736 to size of 0 would shrink the volume.Need to sign off by supplying the shrinkok parameter with value of true.
	at com.cloud.storage.VolumeApiServiceImpl.resizeVolume(VolumeApiServiceImpl.java:1077)
	at com.cloud.storage.VolumeApiServiceImpl.resizeVolume(VolumeApiServiceImpl.java:192)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [X] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?
Deployed a Kubernetes cluster without passing any root disk size - and it deployed successfully

### CODE REVIEW

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan test centos7 vmware-67u3

**Review by rhtyd — APPROVED** [review]

**Comment by shwstppr** [comment]
@Pearl1594 test_scale_vm will need some fixing for vmw

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan test matrix

**Review by shwstppr — APPROVED** [review]
LGTM. Tested cluster deployment with and without node rootdisk resize,
```
(localcloud) SBCM5> > list kubernetesclusters filter=id,name,virtualmachines,
{
  "count": 2,
  "kubernetescluster": [
    {
      "id": "d3e676ee-b09f-4b8c-999d-abcc3251723b",
      "name": "c1",
      "virtualmachines": [
        {
          "account": "admin",
          "affinitygroup": [],
          "created": "2021-04-28T05:09:39+0000",
          "details": {
            "Message.ReservedCapacityFreed.Flag": "true",
            "cpuOvercommitRatio": "2.0",
            "dataDiskController": "osdefault",
            "memoryOvercommitRatio": "1.0",
            "rootDiskController": "lsilogic"
          },
          "displayname": "c1-master",
          "displayvm": true,
          "domain": "ROOT",
          "domainid": "89597c05-92b4-11eb-9b07-1e0053000169",
          "guestosid": "89703585-92b4-11eb-9b07-1e0053000169",
          "haenable": false,
          "hostid": "f04a4cf9-915c-45f5-b717-748040361623",
          "hostname": "10.0.32.213",
          "hypervisor": "VMware",
          "id": "00b2c203-4e22-4d84-bc33-a7befa852336",
          "instancename": "i-2-19-VM",
          "isdynamicallyscalable": false,
          "name": "c1-master",
          "nic": [
            {
              "broadcasturi": "vlan://1500",
              "extradhcpoption": [],
              "gateway": "10.1.1.1",
              "id": "0c2632bb-9005-4e4f-b447-3d6c912a47b0",
              "ipaddress": "10.1.1.230",
              "isdefault": true,
              "isolationuri": "vlan://1500",
              "macaddress": "02:00:0a:b0:00:02",
              "netmask": "255.255.255.0",
              "networkid": "431e8670-3f10-4a7f-83bc-8a3831ae4514",
              "networkname": "c1-network",
              "secondaryip": [],
              "traffictype": "Guest",
              "type": "Isolated"
            }
          ],
          "osdisplayname": "Other Linux (64-bit)",
          "ostypeid": "89703585-92b4-11eb-9b07-1e0053000169",
          "securitygroup": [],
          "state": "Running",
          "tags": [],
          "userid": "a0d68685-92b4-11eb-9b07-1e0053000169",
          "username": "admin",
          "zoneid": "251398d0-707d-4e5a-9298-2a97a1eff534",
          "zonename": "pr4758-t323-vmware-65u2"
        },
        {
          "account": "admin",
          "affinitygroup": [],
          "created": "2021-04-28T05:10:22+0000",
          "details": {
            "Message.ReservedCapacityFreed.Flag": "true",
            "cpuOvercommitRatio": "2.0",
            "dataDiskController": "osdefault",
            "memoryOvercommitRatio": "1.0",
            "rootDiskController": "lsilogic"
          },
          "displayname": "c1-node-1",
          "displayvm": true,
          "domain": "ROOT",
          "domainid": "89597c05-92b4-11eb-9b07-1e0053000169",
          "guestosid": "89703585-92b4-11eb-9b07-1e0053000169",
          "haenable": false,
          "hostid": "4d627038-eb66-4a93-891a-b937572855d5",
          "hostname": "10.0.33.186",
          "hypervisor": "VMware",
          "id": "cd6ae76d-71d0-475a-ad6f-f7f01cc2506c",
          "instancename": "i-2-20-VM",
          "isdynamicallyscalable": false,
          "name": "c1-node-1",
          "nic": [
            {
              "broadcasturi": "vlan://1500",
              "extradhcpoption": [],
              "gateway": "10.1.1.1",
              "id": "d8e96e76-41ba-4401-ac35-7d4d684411cd",
              "ipaddress": "10.1.1.116",
              "isdefault": true,
              "isolationuri": "vlan://1500",
              "macaddress": "02:00:57:fe:00:03",
              "netmask": "255.255.255.0",
              "networkid": "431e8670-3f10-4a7f-83bc-8a3831ae4514",
              "networkname": "c1-network",
              "secondaryip": [],
              "traffictype": "Guest",
              "type": "Isolated"
            }
          ],
          "osdisplayname": "Other Linux (64-bit)",
          "ostypeid": "89703585-92b4-11eb-9b07-1e0053000169",
          "securitygroup": [],
          "state": "Running",
          "tags": [],
          "userid": "a0d68685-92b4-11eb-9b07-1e0053000169",
          "username": "admin",
          "zoneid": "251398d0-707d-4e5a-9298-2a97a1eff534",
          "zonename": "pr4758-t323-vmware-65u2"
        }
      ]
    },
    {
      "id": "e79b074f-2216-4acf-a779-ffa64172f77b",
      "name": "c5",
      "virtualmachines": [
        {
          "account": "admin",
          "affinitygroup": [],
          "created": "2021-04-28T05:36:05+0000",
          "details": {
            "cpuOvercommitRatio": "2.0",
            "dataDiskController": "osdefault",
            "memoryOvercommitRatio": "1.0",
            "rootDiskController": "lsilogic",
            "rootdisksize": "12"
          },
          "displayname": "c5-master",
          "displayvm": true,
          "domain": "ROOT",
          "domainid": "89597c05-92b4-11eb-9b07-1e0053000169",
          "guestosid": "89703585-92b4-11eb-9b07-1e0053000169",
          "haenable": false,
          "hostid": "f04a4cf9-915c-45f5-b717-748040361623",
          "hostname": "10.0.32.213",
          "hypervisor": "VMware",
          "id": "a8352f4d-e56e-4b18-a545-0cf7ba92ecb7",
          "instancename": "i-2-28-VM",
          "isdynamicallyscalable": false,
          "name": "c5-master",
          "nic": [
            {
              "broadcasturi": "vlan://1488",
              "extradhcpoption": [],
              "gateway": "10.1.1.1",
              "id": "0263f999-852a-443e-8860-fd49195e9f25",
              "ipaddress": "10.1.1.123",
              "isdefault": true,
              "isolationuri": "vlan://1488",
              "macaddress": "02:00:3b:1b:00:02",
              "netmask": "255.255.255.0",
              "networkid": "ace55022-dd50-4bf8-a196-f4b79bd20b3d",
              "networkname": "c5-network",
              "secondaryip": [],
              "traffictype": "Guest",
              "type": "Isolated"
            }
          ],
          "osdisplayname": "Other Linux (64-bit)",
          "ostypeid": "89703585-92b4-11eb-9b07-1e0053000169",
          "securitygroup": [],
          "state": "Running",
          "tags": [],
          "userid": "a0d68685-92b4-11eb-9b07-1e0053000169",
          "username": "admin",
          "zoneid": "251398d0-707d-4e5a-9298-2a97a1eff534",
          "zonename": "pr4758-t323-vmware-65u2"
        },
        {
          "account": "admin",
          "affinitygroup": [],
          "created": "2021-04-28T05:36:32+0000",
          "details": {
            "cpuOvercommitRatio": "2.0",
            "dataDiskController": "osdefault",
            "memoryOvercommitRatio": "1.0",
            "rootDiskController": "lsilogic",
            "rootdisksize": "12"
          },
          "displayname": "c5-node-1",
          "displayvm": true,
          "domain": "ROOT",
          "domainid": "89597c05-92b4-11eb-9b07-1e0053000169",
          "guestosid": "89703585-92b4-11eb-9b07-1e0053000169",
          "haenable": false,
          "hostid": "4d627038-eb66-4a93-891a-b937572855d5",
          "hostname": "10.0.33.186",
          "hypervisor": "VMware",
          "id": "e3d2114e-6700-467c-a4de-be6b8508239a",
          "instancename": "i-2-29-VM",
          "isdynamicallyscalable": false,
          "name": "c5-node-1",
          "nic": [
            {
              "broadcasturi": "vlan://1488",
              "extradhcpoption": [],
              "gateway": "10.1.1.1",
              "id": "984fd2af-e2c7-4e35-a793-4ef00e052f6f",
              "ipaddress": "10.1.1.31",
              "isdefault": true,
              "isolationuri": "vlan://1488",
              "macaddress": "02:00:10:16:00:03",
              "netmask": "255.255.255.0",
              "networkid": "ace55022-dd50-4bf8-a196-f4b79bd20b3d",
              "networkname": "c5-network",
              "secondaryip": [],
              "traffictype": "Guest",
              "type": "Isolated"
            }
          ],
          "osdisplayname": "Other Linux (64-bit)",
          "ostypeid": "89703585-92b4-11eb-9b07-1e0053000169",
          "securitygroup": [],
          "state": "Running",
          "tags": [],
          "userid": "a0d68685-92b4-11eb-9b07-1e0053000169",
          "username": "admin",
          "zoneid": "251398d0-707d-4e5a-9298-2a97a1eff534",
          "zonename": "pr4758-t323-vmware-65u2"
        }
      ]
    }
  ]
}
```

**Pull request merged**
