### PR TITLE
Add support for keyword in listSSHKeyPairs command search (#2920)

### PR DESCRIPTION
**Pull request by anuragaw**
## Description

Adds support for keyword search that was ignored by listsshkeypairs command.

Fixes: #2920 
## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by anuragaw** [comment]
@blueorangutan package

**Comment by anuragaw** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@anuragaw since this is a bugfix can you rebase against edit PR branch against 4.11? Thanks.

**Comment by rafaelweingartner** [comment]
@anuragaw do you want to send this to master or to 4.11.3? You are targeting master, but the version in the PR says 4.11.3.

**Comment by anuragaw** [comment]
@rhtyd / @rafaelweingartner - I wanted to confirm this if I have interpreted correctly - I should edit the PR to be merged with 4.11.3 branch and do any rebase as necessary against 4.11?

**Comment by anuragaw** [comment]
@rafaelweingartner - thanks! Your explanation helps me in planning future PRs I make.

@rhtyd - I have rebased and made the PR towards 4.11. Thanks!

**Comment by rhtyd** [comment]
@blueorangutan package

**Pull request merged**
