### PR TITLE
HAproxy based load balancer customization

### LINKED ISSUE #3789: TCP load balancer ability to set custom connect/client/server timeout
##### ISSUE TYPE

 * Enhancement Request

##### COMPONENT NAME

~~~
* API
* VR
~~~

##### CLOUDSTACK VERSION

~~~
4.11.3
~~~

##### CONFIGURATION

* Virtual Routers
* VMware

##### SUMMARY

Our Problem is that the default TCP timeouts aren't working for some of our usecases.

###### First Idea
The idea is to add three custom timeout parameter to the `createLoadBalancer` method.
* `timeout connect`
* `timeout client`
* `timeout server`

###### Second Idea
The second idea is to take a custom parameter to extend the `listen` section in haproxy.
This custom parameter would be an array of configuration strings which get validated with haproxy configtest.

Here the parameter matrix for haproxy 1.7 https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#4.1

### PR DESCRIPTION
**Pull request by ravening**
Add new feature for load balancers based on haproxy

code ported from https://github.com/apache/cloudstack/pull/4141

### Description
As discussed in mailing list, create this PR for haproxy config customization.

FS: https://cwiki.apache.org/confluence/display/CLOUDSTACK/VR+haproxy+customization+in+CloudStack

Fixes #3789

It supports (or will support)

Basic haproxy configurations:
haproxy statistics uri, auth, enable/disable
global maxconn and maxpipes
Basic configurations on rule
timeout connection, client ,server globally and per rule
http, httpalive per rule
maxconn, fullconn per rule
maxconn, minconn, maxqueue per server in rule
advanced features
transparent load balancer
SSL offloading
http2 support
Variable SSL configurations

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [X] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):

Adding networks level haproxy configs

Screenshot 2021-12-21 at 16 38 52

Adding load balancer level configs
Screenshot 2021-12-21 at 16 39 36

Screenshot 2021-12-21 at 16 39 56
Screenshot 2021-12-21 at 16 40 12

### CODE REVIEW

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
Hi @ravening is this PR ready for review? Can you please fix the conflicts?

**Comment by ravening** [comment]
> Hi @ravening is this PR ready for review? Can you please fix the conflicts?

@nvazquez done

**Comment by nvazquez** [comment]
Thanks @ravening 
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by nvazquez** [comment]
Sorry @ravening there are some conflicts again, can you please fix?

**Comment by ravening** [comment]
> Sorry @ravening there are some conflicts again, can you please fix?

@nvazquez fixed it

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Pull request closed without merging**
