### PR TITLE
Sync the storage pool stats in DB with the actual stats from stats collector

### PR DESCRIPTION
**Pull request by sureshanaparti**
### Description

This PR syncs the pool stats in DB with the actual stats from stats collector if there are any discrepancies with in-memory or DB stats - both  capacity (`disksizetotal`) and used (`disksizeused`) bytes.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

Checked the pool stats after updating capacitybytes for the pool - DB sync-ed with the actual capacitybytes from stats collector.

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Review by borisstoyanov — APPROVED** [review]
LGTM

**Pull request merged**
