### PR TITLE
Use long instead of int in DB statistics for Queries and Uptime.

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR fixes server statistics for long running systems

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by rohityadavcloud — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@rohityadavcloud , I am assuming your approval is based on code review?

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@DaanHoogland 
as discussed, I still got exception in management server
```
java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Integer (java.lang.Long and java.lang.Integer are in module java.base of loader 'bootstrap')
    at org.apache.cloudstack.metrics.MetricsServiceImpl.getQueryHistory(MetricsServiceImpl.java:810)
    at org.apache.cloudstack.metrics.MetricsServiceImpl.listDbMetrics(MetricsServiceImpl.java:797)
    at org.apache.cloudstack.api.ListDbMetricsCmd.execute(ListDbMetricsCmd.java:41)
......
```

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by weizhouapache — APPROVED** [review]
manually tested ok.

```
mysql> SHOW STATUS WHERE FIND_IN_SET(Variable_name,'Queries,Uptime');
+---------------+-----------+
| Variable_name | Value     |
+---------------+-----------+
| Queries       | 230159230 |
| Uptime        | 3436300   |
+---------------+-----------+
2 rows in set (0.00 sec)
```

cmk
```
(localcloud) 🐱 > list dbmetrics 
{
  "dbMetrics": {
    "collectiontime": "2023-01-25T12:54:43+0000",
    "connections": 237927,
    "dbloadaverages": [
      58,
      52,
      66
    ],
    "hostname": "10.0.34.189",
    "queries": 230167211,
    "replicas": [
      "localhost",
      "localhost"
    ],
    "tlsversions": "TLSv1.2,TLSv1.3",
    "uptime": 3436443,
    "version": "8.0.31-0ubuntu0.22.04.1",
    "versioncomment": "(Ubuntu)"
  }
}
```

**Review by stephankruggg — APPROVED** [review]
CLGTM

**Pull request merged**
