### PR TITLE
Add projectid to project details page

### PR DESCRIPTION
**Pull request by pdion891**
Display the project ID on the details view of a project.

### CODE REVIEW

**Comment by rhtyd** [comment]
LGTM, @pdion891 can we have a screenshot to confirm regression testing?

**Comment by pdion891** [comment]
I've added some more information in the project detail page as on following screenshot:

prj1
prj2

**Comment by rhtyd** [comment]
LGTM.

**Comment by swill** [comment]
LGTM

**Comment by rhtyd** [comment]
Manually tested, LGTM. We can merge this, the failing Travis tests are not related to the change (which is purely UI).

**Pull request merged**
