### PR TITLE
[Bug-Id: CLOUDSTACK-9306]Replace testdata with services

### PR DESCRIPTION
**Pull request by sanju1010**
Replaced people.apache.org with home.apache.org in test_usage services class and test_data.py file.

Test Create/Delete a ISO and verify its usage is generated correctly ... === TestName: test_01_ISO_usage | Status : SUCCESS ===
ok

---

Ran 1 test in 76.650s

OK

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@sanju1010 Sanju can you please use the full id of the jira issue instead of CS-9306? At first I thought it was a private issue but then I woke up and tried CLOUDSTACK-9306 ;) I have to apologise for whatever you didn't hear me think.

**Comment by pavanb018** [comment]
Doesn't seem to be much of a code(functionality) change. The changes made in testdata.py LGTM !!

**Comment by DaanHoogland** [comment]
LGTM. one remark out of scope: let's consider externalizing the urls to facilitate handling such issues in the future.

**Comment by swill** [comment]
I will test this as soon as my CI is up and running.  If anyone else has had a chance to test this and can post the results I will merge it right away.  Thx...

**Comment by sanju1010** [comment]
@swill, did you get a chance to run CI on this PR?

**Comment by swill** [comment]
Just got my CI back up and running.  I will be getting it running against a few PRs ASAP.

**Comment by swill** [comment]
### CI RESULTS

```
Tests Run: 9
  Skipped: 0
   Failed: 0
   Errors: 2
```

**Summary of the problem(s):**
```
ERROR: Test Create/Delete a manual snap shot and verify
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/git/cs2/cloudstack/test/integration/component/test_usage.py", line 1419, in test_01_snapshot_usage
    snapshot = Snapshot.create(self.apiclient, volumes[0].id)
  File "/usr/lib/python2.7/site-packages/marvin/lib/base.py", line 1014, in create
    return Snapshot(apiclient.createSnapshot(cmd).__dict__)
  File "/usr/lib/python2.7/site-packages/marvin/cloudstackAPI/cloudstackAPIClient.py", line 797, in createSnapshot
    response = self.connection.marvinRequest(command, response_type=response, method=method)
  File "/usr/lib/python2.7/site-packages/marvin/cloudstackConnection.py", line 379, in marvinRequest
    raise e
CloudstackAPIException: Execute cmd: createsnapshot failed, due to: errorCode: 530, errorText:KVM Snapshot is not supported: 1
----------------------------------------------------------------------
Additional details in: /tmp/MarvinLogs/test_usage_Y07AFO/results.txt
```

```
ERROR: Test Create/delete a volume and verify correct usage is recorded
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/git/cs2/cloudstack/test/integration/component/test_usage.py", line 689, in test_01_volume_usage
    "url"] = self.services["coreos_volume"]["urlkvm"]
KeyError: 'coreos_volume'
----------------------------------------------------------------------
Additional details in: /tmp/MarvinLogs/test_usage_Y07AFO/results.txt
```



**Associated Uploads**

**`/tmp/MarvinLogs/DeployDataCenter__Apr_22_2016_22_59_43_BLA4UL:`**
* [dc_entries.obj](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1436/tmp/MarvinLogs/DeployDataCenter__Apr_22_2016_22_59_43_BLA4UL/dc_entries.obj)
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1436/tmp/MarvinLogs/DeployDataCenter__Apr_22_2016_22_59_43_BLA4UL/failed_plus_exceptions.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1436/tmp/MarvinLogs/DeployDataCenter__Apr_22_2016_22_59_43_BLA4UL/runinfo.txt)

**`/tmp/MarvinLogs/test_usage_Y07AFO:`**
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1436/tmp/MarvinLogs/test_usage_Y07AFO/failed_plus_exceptions.txt)
* [results.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1436/tmp/MarvinLogs/test_usage_Y07AFO/results.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1436/tmp/MarvinLogs/test_usage_Y07AFO/runinfo.txt)


Uploads will be available until `2016-06-23 02:00:00 +0200 CEST`

*Comment created by [`upr comment`](https://github.com/cloudops/upr).*

**Comment by swill** [comment]
Please review the details of the CI run.  I am using a KVM [bubble](https://github.com/MissionCriticalCloud/bubble-toolkit) to test this and I have not tried to manually take a snapshot yet in this environment.

**Comment by swill** [comment]
@sanju1010 please review the CI run results when you have a second.  Thanks...

**Comment by swill** [comment]
@sanju1010 can you please review this?  I am not worried about the issue with `` because I have verified that issue already existed.  However, the following problem seems to have been introduced in this PR.

```
ERROR: Test Create/delete a volume and verify correct usage is recorded
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/git/cs2/cloudstack/test/integration/component/test_usage.py", line 689, in test_01_volume_usage
    "url"] = self.services["coreos_volume"]["urlkvm"]
KeyError: 'coreos_volume'
----------------------------------------------------------------------
Additional details in: /tmp/MarvinLogs/test_usage_Y07AFO/results.txt
```

Thanks...

**Comment by swill** [comment]
@sanju1010 unfortunately I can not get this into 4.9 with the current bug in it.  I am willing to test this and try to get it in if you fix the issues, but we are in the final hours before freeze...

**Comment by swill** [comment]
@sanju1010 ping...

**Comment by bvbharatk** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 145
 Hypervisor xenserver
 NetworkType Advanced
 Passed=73
 Failed=0
 Skipped=3

_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/yj3wnzbceo9uef2/AAB6u-Iap-xztdm6jHX9SjPja?dl=0


**Failed tests:**

**Skipped tests:**
test_vm_nic_adapter_vmxnet3
test_static_role_account_acls
test_deploy_vgpu_enabled_vm

**Passed test suits:**
test_deploy_vm_with_userdata.py
test_affinity_groups_projects.py
test_portable_publicip.py
test_vpc_vpn.py
test_over_provisioning.py
test_global_settings.py
test_scale_vm.py
test_service_offerings.py
test_routers_iptables_default_policy.py
test_routers.py
test_reset_vm_on_reboot.py
test_snapshots.py
test_deploy_vms_with_varied_deploymentplanners.py
test_login.py
test_list_ids_parameter.py
test_public_ip_range.py
test_multipleips_per_nic.py
test_regions.py
test_affinity_groups.py
test_network_acl.py
test_pvlan.py
test_volumes.py
test_nic.py
test_deploy_vm_root_resize.py
test_resource_detail.py
test_secondary_storage.py
test_vm_life_cycle.py
test_disk_offerings.py

**Comment by rhtyd** [comment]
@sanju1010 can you fix the conflicts?

**Comment by DaanHoogland** [comment]
@sanju1010 can you rebase and re-open if still relevant?

**Pull request closed without merging**
