### PR TITLE
log4j2: Use size based triggering instead of time based

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR changes the triggering policy for log4j from time based to size based. This helps prevents issues where disk gets full due to logs on the disk and the application becomes unavailable.

I have set the max file size to 100 MB and the maximum number of old logs files to be retained to 10. At max the storage required for a single log file will be 100MB * (10 old log files + 1 current log file) = 1100MB. The actual size would be less since the old log files are gzipped.

Added these 2 variables which are configured in replace.properties:

`LOGMAXINDEX` - Maximum number of old files to retain.
`LOGMAXFILESIZE` - Maximum size of the log file before rotation

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

### CODE REVIEW

**Comment by weizhouapache** [comment]
@vishesh92 
what's the purpose of this change ? anyone complained about it ?

the new file names are not user-friendly. It will be difficult to find the logs of a specific date.

**Review by rohityadavcloud — CHANGES_REQUESTED** [review]
@vishesh92 maybe we can keep the default triggering policy to be time based but document how size based policy could be used? So the PR is essentially changes in replace.properties & a separate doc PR to given examples on configuration of logging.

**Comment by weizhouapache** [comment]
> @vishesh92 maybe we can keep the default triggering policy to be time based but document how size based policy could be used? So the PR is essentially changes in replace.properties & a separate doc PR to given examples on configuration of logging.

actually we could add both policies in the packages and install on mgmt server and agent, and let user to choose.
The old time-based policy should be default. as @rohityadavcloud and @harikrishna-patnala said

I also agree with @NuxRo that it would be better to add the timestamp to the filename, instead of `%i%. 
@vishesh92 is it possible ?

`LOGMAXINDEX=10` is too small in my opinion. the compression size of a 100MB log could be smaller than 10MB.

**Review by rohityadavcloud — CHANGES_REQUESTED** [review]
Let's remove size based trigger policy from the PR - but instead create a doc PR for users who would want it, on how to do that.

**Comment by vishesh92** [comment]
> Let's remove size based trigger policy from the PR - but instead create a doc PR for users who would want it, on how to do that.

Created a doc PR for this here: https://github.com/apache/cloudstack-documentation/pull/450

Closing this PR.

**Pull request closed without merging**
