### PR TITLE
server: fix dualstack ipv6 networks for vxlan

### LINKED ISSUE #7926: IPv6 subnet assignment fails for guest network
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Networking IP Address provision 
~~~

##### CLOUDSTACK VERSION

~~~
4.18
~~~

##### CONFIGURATION

Advanced Zone
VXLAN isolation
Isolated Network with IPv6 Support

##### OS / ENVIRONMENT

UBUNTU 22.04.3

##### SUMMARY

When applying a dual stack networking offering to an existing or new network the guest ipv6 network is not properly assigned.
The UI in the Details of the Guest Network is indicating "undefined via 2a0f:ffc0:......".  
The Virtual Router has no IPv6 address assigned on the guest network. The public IPv6 address is applied and working as expected. 
The Management server log  doesn't report any relevant errors. 
##### STEPS TO REPRODUCE

Create a new Zone with VXLAN isolation method
Add host
Define IPv4 / IPv6 guest/public networks
Create a dual stack network offering
Create a new guest network 
Create a new VM Instance, assign it to the network and start it

Setup of the PUBLIC network in the Zone
Screenshot 2023-08-31 015017

Setup of the Guest network in the Zone
Screenshot 2023-08-31 015910

Status of Guest Network
Screenshot 2023-08-31 020033

~~~

~~~

##### EXPECTED RESULTS

~~~
The Guest network should be assigned a /64 IPv6 Prefix
~~~

##### ACTUAL RESULTS

~~~

~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #7926

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

Tested dualstack isolated network deployment with an advanced zone (*simulator*) having VXLAN isolation

### CODE REVIEW

**Comment by weizhouapache** [comment]
code lgtm

need testing

**Comment by weizhouapache** [comment]
@blueorangutan test

**Review by rohityadavcloud — APPROVED** [review]
LGTM didn't test it though

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan LLpackage

**Comment by weizhouapache** [comment]
@blueorangutan LLtest matrix

**Review by weizhouapache — APPROVED** [review]
Verified OK

image

**Pull request merged**
