### PR TITLE
Fix shutdown header to match antdv design

### PR DESCRIPTION
**Pull request by davidjumani**
### Description

This PR ensures the shutdown header matches the ant design specs

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### Screenshots (if appropriate):

Screenshot from 2023-04-13 10-23-30

### CODE REVIEW

**Review by shwstppr — APPROVED** [review]

**Comment by shwstppr** [comment]
@blueorangutan ui

**Review by rohityadavcloud — APPROVED** [review]

**Comment by shwstppr** [comment]
Tested. LGTM

Screenshot from 2023-04-17 11-50-12

**Comment by weizhouapache** [comment]
@shwstppr  @rohityadavcloud
   do we need this to backport to 4.18 ?

**Comment by shwstppr** [comment]
@weizhouapache I don't think so. From what I remember shutdown feature is added only in main right now

**Comment by weizhouapache** [comment]
@shwstppr 
thanks for your reply !

**Pull request merged**
