### PR TITLE
CLOUDSTACK-9450: Network Offering for VPC based on DB flag

### PR DESCRIPTION
**Pull request by prashanthvarma**
Co-Authored-By: Prashanth Manthena prashanth.manthena@nuagenetworks.net

Bug: https://issues.apache.org/jira/browse/CLOUDSTACK-9398

Design Document: https://cwiki.apache.org/confluence/display/CLOUDSTACK/Network+Offering+for+VPC+based+on+DB+flag

### CODE REVIEW

**Comment by prashanthvarma** [comment]
PEP8 & PyFlakes compliance of our marvin test code:

CloudStack$
CloudStack$ pep8 test/integration/plugins/nuagevsp/.py
CloudStack$
CloudStack$ pyflakes test/integration/plugins/nuagevsp/.py
CloudStack$

Validations:

Marvin test results:

=> nosetests --with-marvin --marvin-config=nuage.cfg nuagevsp/test_nuage_static_nat.py

Test Nuage VSP Public IP Range creation and deletion ... === TestName: test_01_nuage_StaticNAT_public_ip_range | Status : SUCCESS ===
ok
Test Nuage VSP Nuage Underlay (underlay networking) enabled Public ... === TestName: test_02_nuage_StaticNAT_underlay_public_ip_range | Status : SUCCESS ===
ok
Test Nuage VSP Isolated networks with different combinations of ... === TestName: test_03_nuage_StaticNAT_isolated_networks | Status : SUCCESS ===
ok
Test Nuage VSP VPC networks with different combinations of Static ... === TestName: test_04_nuage_StaticNAT_vpc_networks | Status : SUCCESS ===
ok
Test Nuage VSP Static NAT functionality for Isolated network by ... === TestName: test_05_nuage_StaticNAT_isolated_networks_traffic | Status : SUCCESS ===
ok
Test Nuage VSP Static NAT functionality for VPC network by ... === TestName: test_06_nuage_StaticNAT_vpc_network_traffic | Status : SUCCESS ===
ok
Test Nuage VSP Static NAT functionality with different Egress ... === TestName: test_07_nuage_StaticNAT_acl_rules_traffic | Status : SUCCESS ===
ok
Test Nuage VSP Static NAT functionality with VM NIC operations by ... === TestName: test_08_nuage_StaticNAT_vm_nic_operations_traffic | Status : SUCCESS ===
ok
Test Nuage VSP Static NAT functionality with VM migration by ... === TestName: test_09_nuage_StaticNAT_vm_migration_traffic | Status : SUCCESS ===
ok
Test Nuage VSP Static NAT functionality with network restarts by ... === TestName: test_10_nuage_StaticNAT_network_restarts_traffic | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 10 tests in 10713.290s

OK

[results.txt](https://github.com/apache/cloudstack/files/840912/results.txt)
[runinfo.txt](https://github.com/apache/cloudstack/files/840911/runinfo.txt)

=> nosetests --with-marvin --marvin-config=nuage.cfg nuagevsp/test_nuage_source_nat.py

Test Nuage VSP Isolated networks with different combinations of ... === TestName: test_01_nuage_SourceNAT_isolated_networks | Status : SUCCESS ===
ok
Test Nuage VSP VPC networks with different combinations of Source ... === TestName: test_02_nuage_SourceNAT_vpc_networks | Status : SUCCESS ===
ok
Test Nuage VSP Source NAT functionality for Isolated network by ... SKIP: Configured Nuage VSP SDN platform infrastructure does not support underlay networking: skipping test
Test Nuage VSP Source NAT functionality for VPC network by ... SKIP: Configured Nuage VSP SDN platform infrastructure does not support underlay networking: skipping test
Test Nuage VSP Source NAT functionality with different Egress ... SKIP: Configured Nuage VSP SDN platform infrastructure does not support underlay networking: skipping test
Test Nuage VSP Source NAT functionality with VM NIC operations by ... SKIP: Configured Nuage VSP SDN platform infrastructure does not support underlay networking: skipping test
Test Nuage VSP Source NAT functionality with VM migration by ... SKIP: Configured Nuage VSP SDN platform infrastructure does not support underlay networking: skipping test
Test Nuage VSP Source NAT functionality with network restarts by ... SKIP: Configured Nuage VSP SDN platform infrastructure does not support underlay networking: skipping test

----------------------------------------------------------------------
Ran 8 tests in 1490.621s

OK (SKIP=6)

[results.txt](https://github.com/apache/cloudstack/files/840914/results.txt)
[runinfo.txt](https://github.com/apache/cloudstack/files/840915/runinfo.txt)

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by fmaximus** [comment]
Our internal CI was OK, and the errors reported by Trillian don't seem related to the changes, 
and the XenServer errors are the same as in the baseline #2289.

**Pull request merged**
