### PR TITLE
Feature add scss to css compiler

### PR DESCRIPTION
**Pull request by webermaximilian92**
## Description
_Copy of https://github.com/apache/cloudstack/pull/3301 because I run into troubles after changing my username_

This adds an gulp tasks, to build existing css files out of scss files and enables advantages for working with style rules. 
Also this will reduce the complexibility of heavy css files **in all future css changes**.

- Using CSS is no longer the common standard for complex pages like cloudstack
- SASS (https://sass-lang.com/) or SCSS are preprocessors of CSS. Similar to ES6 or TypeScript for JavaScript.
- SCSS files are compiled to CSS files ones while development or deployment, and not on every page request
- SCSS provides us many logical functions and advantages to organise CSS rules more easily and less redundand with features like variables and so called mixins
- SCSS let us work more modular and is better maintainable
- We could split CSS files too, but this is not best practice, since many CSS files will result in many server requests and with SCSS it's possible to compile many files into one single CSS file (full automatically in just under a second after any SCSS changes)
- This compiled CSS file could also get minified, which will enhance loading times of cloudstack pages.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

(This changes modify and unify the structure of css code only.)
All we have to check yet, is if .css file-changes include only: indentation, spaces and quotes.

It's very useful to reduce the diff to non whitespace changes here:
Screenshot 2019-04-26 at 16 23 44

### CODE REVIEW

**Comment by webermaximilian92** [comment]
@rafaelweingartner

**Comment by svenvogel** [comment]
@rafaelweingartner can you run you check script again?

**Comment by rafaelweingartner** [comment]
We still have a problem here: 
```
Unapproved licenses:
ui/css/src/scss/token-input-facebook.scss
```

The license is:
```
* Copyright (c) 2009 James Smith (http://loopj.com)
* Licensed jointly under the GPL and MIT licenses,
* choose which one suits your project best!
```

We need to handle this license differently. I am not sure if this license if compatible with Apache's one.

**Comment by DaanHoogland** [comment]
@rafaelweingartner MIT is compatible with apache v2.
ui/css/src/scss/token-input-facebook.scss needs to be added to the ignore-list, though i'd prefer dynamic (build time) addition.

**Comment by DaanHoogland** [comment]
@webermaximilian92 @svenvogel ^^

**Comment by rafaelweingartner** [comment]
@DaanHoogland thanks for the feedback!
I did not know that. I recall some e-mail in the past regarding incompatible licenses, but I was not sure which licenses are compatible with Apache 2.0.

Also, instead of ignoring, I would prefer to configure MIT licenses in the `maven-rats` plugin.

**Comment by svenvogel** [comment]
@rafaelweingartner @DaanHoogland thanks i dont that too. it sounds good. whats better "maven-rats" or  "ignore-list" and where we found them?

**Comment by rafaelweingartner** [comment]
the maven-rats configs can be found in the pom.xml of "cloudstack" java project

**Comment by webermaximilian92** [comment]
@rafaelweingartner @DaanHoogland 
I added the file to the maven rats list

**Comment by rafaelweingartner** [comment]
@DennisKonrad next time please you "squash+merge" option on Github.

**Comment by DennisKonrad** [comment]
@rafaelweingartner ok, will do so 👍

**Pull request merged**
