### PR TITLE
GetUsageRecordsCmd - NewInputFormat for START_DATE and END_DATE

### PR DESCRIPTION
**Pull request by svscorp**
It is extremely useful to be able to narrow the output to the specific time range within a date.

### CODE REVIEW

**Comment by bhaisaab** [comment]
LGTM! Thanks for the PR @svscorp 
I'll wait if @kishankavala wants to review

**Comment by svscorp** [comment]
After making more tests, there is one more commit added to remove unnecessary adjustToDayStart/End code, since ParamProcessWorker is actually taking care of building proper date in new format.

**Comment by kishankavala** [comment]
@svscorp  Commit looks good to me.

**Comment by bhaisaab** [comment]
@svscorp Thanks, do you want to merge this on 4.5 branch as well?

**Comment by svscorp** [comment]
@bhaisaab Oh yes, it would be perfect. Should I make a PR, Rohit?

**Comment by bhaisaab** [comment]
@svscorp yes please, I tried to cherry-pick the change but it failed.

**Pull request closed without merging**
