### PR TITLE
Display numeric value in exception instead of variable name

### PR DESCRIPTION
**Pull request by ravening**
## Description

If the disk size of the VM to be created is greater
then the volume size, then the exception message should
display the numeric value instead of the variable name

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## Screenshots (if appropriate):
Below is the exception which is thrown when error happens while creating a VM

Screenshot 2020-01-17 at 13 14 54

After the fix, below is the message which is displayed

Screenshot 2020-01-17 at 13 18 29

## How Has This Been Tested?

Set the global setting ```custom.diskoffering.size.max``` to lower value and try to create a vm with disk size greater the value of setting ```custom.diskoffering.size.max```

### CODE REVIEW

**Comment by weizhouapache** [comment]
I think we do not need trillian test for this, right ? @DaanHoogland @rhtyd

**Comment by DaanHoogland** [comment]
I'm fine with it like this but just an earmark: any scrapping of logs or exception messages might break. not a big chance as it in not the essence of the message and it is a fix. I'm fine with merging it like this.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@rhtyd do you need to see smoke tests for this (log message improvement only)?

**Comment by rhtyd** [comment]
@DaanHoogland I'm okay to merge this once Travis passes.

**Pull request merged**
