### PR TITLE
CKS: check access when get kubernetescluster config

### LINKED ISSUE #7618: Get All Access Info Of a Cluster Kubernetes Through API Key's User
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API, Kubernetes
~~~

##### CLOUDSTACK VERSION

~~~
4.18.0.0
~~~

##### CONFIGURATION

- Apply role to the user: User role(default role on Cloustack)
- Generate keys for the user

##### OS / ENVIRONMENT

Ubuntu 22.04

##### SUMMARY

Any user can get access info of a cluster from another one if they have the ID of the cluster 

##### STEPS TO REPRODUCE

~~~
- Set role to a user: Default User role on Cloudstack
- Generate keys for the user
- Get access  info of  a cluster from another user (e.g. xxx is the ID cluster of user A, but user B can get info of xxx cluster through API of user B (B has the ID cluster of A) )
~~~

##### EXPECTED RESULTS

~~~
Can't get info of a cluster Kubernetes if they not own
~~~

##### ACTUAL RESULTS

~~~
Get all of info of a cluster if we have ID of any cluster
~~~

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #7618 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by rohityadavcloud — APPROVED** [review]
LGTM, haven't tested it

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Comment by weizhouapache** [comment]
@kiranchavala 
can you please test it ? thanks

**Comment by weizhouapache** [comment]
> 5. Execute API call with user 2 API key and secret key and k8s cluster's ID get from User1

thanks @kiranchavala for the testing

merging

**Pull request merged**
