### PR TITLE
Fix #6263 Cannot scale VM with custom offering

### LINKED ISSUE #6263: Cannot scale VM with custom offering
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.17
~~~

##### CONFIGURATION

- VM has a custom service offering

##### STEPS TO REPRODUCE

~~~
- configure a VM with a custom service offering
- scale the CPU and/or Memory configuration of the VM (thus, keeping the same offering, but updating the VMs compute resources)
~~~

##### EXPECTED RESULTS

~~~
- Successfully updates the VM's Memory and CPU allocated resources
~~~

##### ACTUAL RESULTS

~~~
- Exception is thrown due to "Volume already having the new disk offering provided"
~~~

### PR DESCRIPTION
**Pull request by GabrielBrascher**
### Description

This PR fixes #6263.
The issue is that an Exception is thrown when scaling a customized offering, changing the CPU/Memory but keeping the same disk offering.

This PR proposes a fix for this issue by skipping the volume "upgrade" process in such situations, avoiding any operations and also the thrown exception.

Considering that the disk offering is the same, there is no need to run all actions of the respective method.
The skipped actions are, in summary:
1. run DB updates matching the "new offering";
2. publish EVENT_VOLUME_RESIZE;
3. if volume migration is required (and allowed), find a suitable pool to migrate volume in case the current pool does not match the new offering needs;
4. return a "Volume" object containing all the changes.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [X] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

- Scale (via UI or API) a VM with the custom offering, keeping the same offering but updating the Memory and/or CPU.
- After skipping the validation, all worked out fine.

### CODE REVIEW

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by nvazquez** [comment]
@blueorangutan test

**Review by nvazquez — APPROVED** [review]
LGTM - manually tested on the UI for scaling custom constrained and custom unconstrained offerings

**Review by rohityadavcloud — APPROVED** [review]

**Pull request merged**
