### PR TITLE
CLOUDSTACK-9915  ListSnapshots API does not provide virtual size information of the snapshots

### PR DESCRIPTION
**Pull request by vedulasantosh**
ListSnapshot API response has only physical size information. It is not having virtual size information of the snapshots.

### CODE REVIEW

**Comment by SowjanyaPatha** [comment]
LGTM for Testing.
listSnapshot API response is showing Virtual size information.

**Comment by jayakarteek** [comment]
code LGTM

**Comment by vedulasantosh** [comment]
tag:MergeReady

**Comment by wido** [comment]
LGTM based on the code

**Comment by rhtyd** [comment]
LGTM.

**Pull request merged**
