### PR TITLE
UI - Cancel all requests api, async jobs when user logs out

### PR DESCRIPTION
**Pull request by utchoang**
### Description

This PR fixes https://github.com/apache/cloudstack/issues/5652

When the user performs tasks related to API requests or runs async jobs, as soon as the user logs out, the API requests and async jobs will be canceled immediately.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by PaulAngus** [comment]
@utchoang Can you add some description of what you're actually trying to achieve here please.

The title reads like this - if a user sets off an async job like a volume snapshot,  and then logs out,  that async job (volume snapshot) would then be canceled.

**Comment by PaulAngus** [comment]
> @utchoang Can you add some description of what you're actually trying to achieve here please.
> 
> The title reads like this - if a user sets off an async job like a volume snapshot, and then logs out, that async job (volume snapshot) would then be canceled.

is the thumbsup to say 'yes, if a user logs out when a snapshot is taking place, then the job is cancelled' ?

**Comment by rhtyd** [comment]
No, it won't cancel the job - just UI will cancelling its internal polls for async job results.

**Comment by rhtyd** [comment]
@blueorangutan ui

**Review by rhtyd — APPROVED** [review]
LGTM needs testing

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by rohityadavcloud** [comment]
@blueorangutan ui

**Review by shwstppr — APPROVED** [review]

**Comment by sureshanaparti** [comment]
Hi @utchoang I deployed few VMs from UI and logged out. Noticed the job progress still displayed after logout. Please check.

CS-UI_Logout_Check

**Comment by utchoang** [comment]
@sureshanaparti How did you create that multiple requests?

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by sureshanaparti** [comment]
> @sureshanaparti How did you create that multiple requests?

I've deployed these VMs from 'Add Instance' form in the UI.

**Review by shwstppr — APPROVED** [review]

**Comment by sureshanaparti** [comment]
Verified. LGTM.

**Review by sureshanaparti — APPROVED** [review]

**Pull request merged**
