### PR TITLE
Mock Scanner, instead of scan the computer running the test.

### PR DESCRIPTION
**Pull request by GabrielBrascher**
This allows computers with Windows or MacOS to run the tests without scanning for `/proc/meminfo` path.

At the class [MemStat.java](https://github.com/apache/cloudstack/blob/c496c84c6c727a84862cbbe2d870ff57939488b4/plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/linux/MemStat.java#L71), the `refresh()` method (called in MemStat constructor) has the following lines:

```
public void refresh() {
        File f = new File(MEMINFO_FILE);
        try (Scanner scanner = new Scanner(f,"UTF-8")) {
            parseFromScanner(scanner);
        } catch (FileNotFoundException ex) {
            throw new RuntimeException("File " + MEMINFO_FILE + " not found:" + ex.toString());
        }
}
```
When executing `Scanner scanner = new Scanner(f,"UTF-8")` it scans the file _MEMINFO_FILE_ (`/proc/meminfo`); however, if the OS running this test is not a Linux then it throws `FileNotFoundException`, failing the test.

Thus, by Mocking the Scanner constructor, the `new Scanner(f,"UTF-8")` execution returns the desired Scanner.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by GabrielBrascher** [comment]
Ping for review @kiwiflyer @nathanejohnson @DaanHoogland and others.

**Comment by nathanejohnson** [comment]
Still getting failures on mac:

```
  <testcase name="getMemInfoParseTest" classname="org.apache.cloudstack.utils.linux.MemStatTest" time="0.058">
    <error message="File /proc/meminfo not found:java.io.FileNotFoundException: /proc/meminfo (No such file or directory)" type="java.lang.RuntimeException">java.lang.RuntimeException: File /proc/meminfo not found:java.io.FileNotFoundException: /proc/meminfo (No such file or directory)
        at org.apache.cloudstack.utils.linux.MemStatTest.getMemInfoParseTest(MemStatTest.java:43)
</error>
  </testcase>
```

[mac_mem_test_fail.tar.gz](https://github.com/apache/cloudstack/files/2852307/mac_mem_test_fail.tar.gz)

**Comment by GabrielBrascher** [comment]
Updated the code with a _setup_ method and removed a variable that I left without mocking. Thanks for testing @nathanejohnson. Could you please test it again to make sure that it has been fixed?

**Comment by nathanejohnson** [comment]
still getting failures, but in a new place.  I've attached logs

[mac_test_fail.tar.gz](https://github.com/apache/cloudstack/files/2852491/mac_test_fail.tar.gz)

**Comment by DaanHoogland** [comment]
@GabrielBrascher I tried your branch and it still doesn't compile:
```
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   LibvirtComputingResourceTest.diskUuidToSerialTest:437 » Runtime File /proc/mem...
[ERROR]   LibvirtComputingResourceTest.testAddExtraConfigComponentEmptyExtraConfig:5235 » Runtime
[ERROR]   LibvirtComputingResourceTest.testAddExtraConfigComponentNotEmptyExtraConfig:5242 » Runtime
[ERROR]   LibvirtComputingResourceTest.testCreateVMFromSpec:324 » Runtime File /proc/mem...
[ERROR]   LibvirtComputingResourceTest.testCreateVMFromSpecLegacy:224 » Runtime File /pr...
[ERROR]   LibvirtComputingResourceTest.testCreateVMFromSpecWithTopology4:288 » Runtime F...
[ERROR]   LibvirtComputingResourceTest.testCreateVMFromSpecWithTopology6:256 » Runtime F...
[ERROR]   LibvirtComputingResourceTest.testGetVmStat:509 » Runtime File /proc/meminfo no...
[ERROR]   LibvirtComputingResourceTest.testIsInterface:5118 » Runtime File /proc/meminfo...
[ERROR]   LibvirtComputingResourceTest.testKnownCommand:5222 » Runtime File /proc/meminf...
[ERROR]   LibvirtComputingResourceTest.testMemoryFreeInKBsDomainReturningNoMemoryStatistics:5149 » Runtime
[ERROR]   LibvirtComputingResourceTest.testMemoryFreeInKBsDomainReturningOfSomeMemoryStatistics:5138 » Runtime
[ERROR]   LibvirtComputingResourceTest.testSetQuotaAndPeriod:5178 » Runtime File /proc/m...
[ERROR]   LibvirtComputingResourceTest.testSetQuotaAndPeriodMinQuota:5202 » Runtime File...
[ERROR]   LibvirtComputingResourceTest.testSetQuotaAndPeriodNoCpuLimitUse:5190 » Runtime
[ERROR]   LibvirtComputingResourceTest.testUUID:444 » Runtime File /proc/meminfo not fou...
[ERROR]   LibvirtComputingResourceTest.testUnknownCommand:5210 » Runtime File /proc/memi...
[ERROR]   LibvirtVifDriverTest.setUp:54 » Runtime File /proc/meminfo not found:java.io.F...
[ERROR]   LibvirtVifDriverTest.setUp:54 » Runtime File /proc/meminfo not found:java.io.F...
[ERROR]   LibvirtVifDriverTest.setUp:54 » Runtime File /proc/meminfo not found:java.io.F...
[ERROR]   LibvirtVifDriverTest.setUp:54 » Runtime File /proc/meminfo not found:java.io.F...
[ERROR]   LibvirtVifDriverTest.setUp:54 » Runtime File /proc/meminfo not found:java.io.F...
[ERROR]   LibvirtVifDriverTest.setUp:54 » Runtime File /proc/meminfo not found:java.io.F...
[ERROR]   LibvirtVifDriverTest.setUp:54 » Runtime File /proc/meminfo not found:java.io.F...
[ERROR]   LibvirtMigrateCommandWrapperTest.deleteOrDisconnectDisksOnSourcePoolTest:410 » Runtime
[ERROR]   LibvirtMigrateCommandWrapperTest.testMigrationUri:333 » Runtime File /proc/mem...
[ERROR]   LibvirtMigrateCommandWrapperTest.testMigrationUriException »  Unexpected excep...
[ERROR]   LibvirtNetworkElementCommandWrapperTest.setUp:217 » Runtime File /proc/meminfo...
[ERROR]   LibvirtNetworkElementCommandWrapperTest.setUp:217 » Runtime File /proc/meminfo...
[ERROR]   LibvirtReplugNicCommandWrapperTest.setUp:189 » Runtime File /proc/meminfo not ...
[ERROR]   MemStatTest.getMemInfoParseTest:43 » Runtime File /proc/meminfo not found:java...
[INFO]
[ERROR] Tests run: 214, Failures: 0, Errors: 31, Skipped: 2
```

**Comment by GabrielBrascher** [comment]
@blueorangutan package

**Comment by GabrielBrascher** [comment]
@blueorangutan test

**Comment by GabrielBrascher** [comment]
> still getting failures, but in a new place. I've attached logs

@nathanejohnson that is good. At least this PR fixed the test failures from `MemStatTest.java`.
It looks like we have more tests to take a look into as well.

**Comment by DaanHoogland** [comment]
MemStatTest passes @GabrielBrascher . The following remains:
```
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   LibvirtComputingResourceTest.diskUuidToSerialTest:437 » Runtime File /proc/mem...
[ERROR]   LibvirtComputingResourceTest.testAddExtraConfigComponentEmptyExtraConfig:5235 » Runtime
[ERROR]   LibvirtComputingResourceTest.testAddExtraConfigComponentNotEmptyExtraConfig:5242 » Runtime
[ERROR]   LibvirtComputingResourceTest.testCreateVMFromSpec:324 » Runtime File /proc/mem...
[ERROR]   LibvirtComputingResourceTest.testCreateVMFromSpecLegacy:224 » Runtime File /pr...
[ERROR]   LibvirtComputingResourceTest.testCreateVMFromSpecWithTopology4:288 » Runtime F...
[ERROR]   LibvirtComputingResourceTest.testCreateVMFromSpecWithTopology6:256 » Runtime F...
[ERROR]   LibvirtComputingResourceTest.testGetVmStat:509 » Runtime File /proc/meminfo no...
[ERROR]   LibvirtComputingResourceTest.testIsInterface:5118 » Runtime File /proc/meminfo...
[ERROR]   LibvirtComputingResourceTest.testKnownCommand:5222 » Runtime File /proc/meminf...
[ERROR]   LibvirtComputingResourceTest.testMemoryFreeInKBsDomainReturningNoMemoryStatistics:5149 » Runtime
[ERROR]   LibvirtComputingResourceTest.testMemoryFreeInKBsDomainReturningOfSomeMemoryStatistics:5138 » Runtime
[ERROR]   LibvirtComputingResourceTest.testSetQuotaAndPeriod:5178 » Runtime File /proc/m...
[ERROR]   LibvirtComputingResourceTest.testSetQuotaAndPeriodMinQuota:5202 » Runtime File...
[ERROR]   LibvirtComputingResourceTest.testSetQuotaAndPeriodNoCpuLimitUse:5190 » Runtime
[ERROR]   LibvirtComputingResourceTest.testUUID:444 » Runtime File /proc/meminfo not fou...
[ERROR]   LibvirtComputingResourceTest.testUnknownCommand:5210 » Runtime File /proc/memi...
[ERROR]   LibvirtVifDriverTest.setUp:54 » Runtime File /proc/meminfo not found:java.io.F...
[ERROR]   LibvirtVifDriverTest.setUp:54 » Runtime File /proc/meminfo not found:java.io.F...
[ERROR]   LibvirtVifDriverTest.setUp:54 » Runtime File /proc/meminfo not found:java.io.F...
[ERROR]   LibvirtVifDriverTest.setUp:54 » Runtime File /proc/meminfo not found:java.io.F...
[ERROR]   LibvirtVifDriverTest.setUp:54 » Runtime File /proc/meminfo not found:java.io.F...
[ERROR]   LibvirtVifDriverTest.setUp:54 » Runtime File /proc/meminfo not found:java.io.F...
[ERROR]   LibvirtVifDriverTest.setUp:54 » Runtime File /proc/meminfo not found:java.io.F...
[ERROR]   LibvirtMigrateCommandWrapperTest.deleteOrDisconnectDisksOnSourcePoolTest:410 » Runtime
[ERROR]   LibvirtMigrateCommandWrapperTest.testMigrationUri:333 » Runtime File /proc/mem...
[ERROR]   LibvirtMigrateCommandWrapperTest.testMigrationUriException »  Unexpected excep...
[ERROR]   LibvirtNetworkElementCommandWrapperTest.setUp:217 » Runtime File /proc/meminfo...
[ERROR]   LibvirtNetworkElementCommandWrapperTest.setUp:217 » Runtime File /proc/meminfo...
[ERROR]   LibvirtReplugNicCommandWrapperTest.setUp:189 » Runtime File /proc/meminfo not ...
[INFO]
[ERROR] Tests run: 214, Failures: 0, Errors: 30, Skipped: 2
```

**Comment by rhtyd** [comment]
Is this good to merge @GabrielBrascher @wido ?

**Comment by DaanHoogland** [comment]
@rhtyd I submitted some additions to @GabrielBrascher . I hope these can be included in this PR.

**Comment by GabrielBrascher** [comment]
@rhtyd @DaanHoogland I updated the branch with the changes proposed by Daan.

**Comment by DaanHoogland** [comment]
@nathanejohnson can you give this a test, please? #worksforme

**Comment by DaanHoogland** [comment]
travis test run 7 always seems to fail, lately :(

**Comment by GabrielBrascher** [comment]
@DaanHoogland yes, test 7 has been failing constantly, not only in this PR. #3267 looks like a fix for the Travis-CI timeout.

**Comment by GabrielBrascher** [comment]
@nathanejohnson are you ok with this PR?

**Comment by nathanejohnson** [comment]
@GabrielBrascher sorry for the late response, builds on my machine now!  LGTM!

**Pull request merged**
