### PR TITLE
Display VM snapshot tags on usage records

### LINKED ISSUE #3558: VMsnapshot tags are not visible in list usage response
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
USAGE
~~~

##### CLOUDSTACK VERSION

~~~
master
~~~

##### SUMMARY

list usagerecords startdate=2015-01-01 enddate=2019-08-13 includetags=true type=25
{
"account": "admin",
"accountid": "29728169-ba9e-11e9-8e85-1e0050010765",
"description": "VMSnapshot on primary storage usage for VM multi-disk-asa-andrija (b73a99b1-04d6-4bd4-b6b6-dacc683efc27) with size 21743271936",
"domain": "ROOT",
"domainid": "f89085e7-ba9d-11e9-8e85-1e0050010765",
"enddate": "2019-08-13'T'11:58:15+00:00",
"name": "i-2-21-VM_VS_20190813114616",
"rawusage": "0.198085",
"size": 21743271936,
"startdate": "2019-08-13'T'11:46:22+00:00",
"tags": [],
"usage": "0.198085 Hrs",
"usagetype": 27,
"virtualmachineid": "b73a99b1-04d6-4bd4-b6b6-dacc683efc27",
"zoneid": "873d6c1e-34e4-43fe-a809-1193e3fdabb8"
},

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~
Tags should be there
~~~

##### ACTUAL RESULTS

~~~
not appearing
~~~

### PR DESCRIPTION
**Pull request by nvazquez**
## Description

Fixes #3558

Problem: Tags are not visible on listUsageRecords type=25/27 (VM snapshots) even though there are tags on the VM snapshot

````
list usagerecords startdate=2015-01-01 enddate=2019-08-13 includetags=true type=25
{
"account": "admin",
"accountid": "29728169-ba9e-11e9-8e85-1e0050010765",
"description": "VMSnapshot on primary storage usage for VM multi-disk-asa (b73a99b1-04d6-4bd4-b6b6-dacc683efc27) with size 21743271936",
"domain": "ROOT",
"domainid": "f89085e7-ba9d-11e9-8e85-1e0050010765",
"enddate": "2019-08-13'T'11:58:15+00:00",
"name": "i-2-21-VM_VS_20190813114616",
"rawusage": "0.198085",
"size": 21743271936,
"startdate": "2019-08-13'T'11:46:22+00:00",
"tags": [],
"usage": "0.198085 Hrs",
"usagetype": 27,
"virtualmachineid": "b73a99b1-04d6-4bd4-b6b6-dacc683efc27",
"zoneid": "873d6c1e-34e4-43fe-a809-1193e3fdabb8"
}
````

Solution: Tags included while listing usage recods:
````
list usagerecords startdate=2015-01-01 enddate=2019-08-13 includetags=true type=25
{
"account": "admin",
"accountid": "29728169-ba9e-11e9-8e85-1e0050010765",
"description": "VMSnapshot on primary storage usage for VM multi-disk-asa (b73a99b1-04d6-4bd4-b6b6-dacc683efc27) with size 21743271936",
"domain": "ROOT",
"domainid": "f89085e7-ba9d-11e9-8e85-1e0050010765",
"enddate": "2019-08-13'T'11:58:15+00:00",
"name": "i-2-21-VM_VS_20190813114616",
"rawusage": "0.198085",
"size": 21743271936,
"startdate": "2019-08-13'T'11:46:22+00:00",
"tags": [
        {
          "key": "key2",
          "value": "val2"
        },
        {
          "key": "key1",
          "value": "val1"
        }
],
"usage": "0.198085 Hrs",
"usagetype": 27,
"virtualmachineid": "b73a99b1-04d6-4bd4-b6b6-dacc683efc27",
"zoneid": "873d6c1e-34e4-43fe-a809-1193e3fdabb8"
}


````

## Types of changes
- [x] Enhancement (improves an existing feature and functionality)

## How Has This Been Tested?
- Take VM Snapshots
- Assign tags to VM snapshots
- Generate usage records
- List usage records and verify tags are displayed

### CODE REVIEW

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by borisstoyanov** [comment]
fixes #3558

**Comment by nvazquez** [comment]
@borisstoyanov yes, as I have just pasted the output from the problem described above. Let me add new output for the fixed one

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test matrix

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
Thanks @borisstoyanov 
@blueorangutan test matrix

**Pull request merged**
