### PR TITLE
Updated the code to access the primary color from config.json.

### LINKED ISSUE #7056: UI user icon not using primary-color setting
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.17.2.0
~~~

##### SUMMARY

After login into UI the top right user icon does not use @primary-color from theme section of config.json

### PR DESCRIPTION
**Pull request by ilhamalrahm**
This PR is related to the issue #7056.
 
backgroundColor of user-menu-avatar was hardcoded to primary color value instead of accessing it from @primary-color in config.json file. 

### Description

This PR resolves #7056.

 backgroundColor of user-menu-avatar was hardcoded to primary color value instead of accessing @primary-color in config.json file. 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by rohityadavcloud** [comment]
@blueorangutan ui

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by ilhamalrahm** [comment]
Is there anything else that i have to do?

**Comment by DaanHoogland** [comment]
> Is there anything else that i have to do?

@ilhamalrahm , You need a second LGTM and test verification. Best is to look at `git blame` to see who else modified the code in that area and ask them for a review.
It also help to fill the How was this tested section, so it will be easy for someone else to replicate.

**Comment by ilhamalrahm** [comment]
@davidjumani and @utchoang worked last in that area. How can i request for a review?

**Comment by ilhamalrahm** [comment]
Anything i can do?

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by ilhamalrahm** [comment]
👀

**Comment by soreana** [comment]
Tested manually, works as expected.

### Before change:
Screenshot 2023-06-20 at 16 13 23


### After change:

Screenshot 2023-06-20 at 16 13 35

**Review by soreana — APPROVED** [review]

**Pull request merged**
