### PR TITLE
CLOUDSTACK-8964: Fix KVM snap to vol and snap to templ, no delegate for Ovm3..

### PR DESCRIPTION
**Pull request by snuf**
Snapshot to volume, snapshot to template was tested with KVM.

Ovm3 does not have this functionality yet. The Ovm3HypervisorGuru was however giving an incorrect answer to a delegation request, which should never have been implemented.

### CODE REVIEW

**Comment by snuf** [comment]
Eh that's odd, it's supposed to wait for 2 seconds, waited for 1.002 and then fails because it waited too short ? what am I missing here ? :)

**Comment by karuturi** [comment]
Thanks for taking this up @snuf. I am out of office and will be able to test it only on Monday. 
@NuxRo Can you try this please?

**Comment by NuxRo** [comment]
I've built EL6 RPMs from https://github.com/snuf/cloudstack/archive/6efe627e8e11c18acf62ff02b85007de122a917c and "yum reinstall" management and agent. 
(am I testing the right thing?)

No go.

Volume creation from snapshot still fails with this: http://fpaste.org/282421/44552050/raw/

Template creation from snapshot works OK.

Do note I have removed the Ovm3Guru from the hypervisor guru, excluding it again does not make a difference.

**Comment by snuf** [comment]
@NuxRo interesting... I'm checking out my commit again and rebuilding to test again, I'm running both at the same time though... so that might explain something perhaps..

**Comment by borisroman** [comment]
@snuf The org.apache.cloudstack.utils.hypervisor.HypervisorUtilsTest.checkVolumeFileForActivityTest(HypervisorUtilsTest.java:70) test is IMHO a known issue. Are you building against JDK 8 or 7?

**Comment by snuf** [comment]
@borisroman problem is that some of our jenkins build slaves ("our" are the project ones) fail, so "restarting" it and hoping you'll end up on a build slave that does work is kind of what i did.... *cough*.

**Comment by snuf** [comment]
@NuxRo tested all the scenarios and I'm getting different results as before and different results than you, this is an excerpt of the log testing the various options: http://fpaste.org/282859/45595257/raw/
Oddly enough almost none of the OVM3 options work anymore, but all the KVM ones do in my case, I think we have a different problem, as in it's not one guru that's screwing up, but that's just my hunch will investigate further.

**Comment by NuxRo** [comment]
@Snuf is there a list of all hv gurus? I'd like to exclude all of them (bar kvm), see if that helps.

**Comment by snuf** [comment]
@NuxRo here's a list, there is no KVM Guru... ?
funs@cs-mgmt:~/cloudstack/plugins/hypervisors$ find . -type f -name *.xml | xargs grep -A 1 Guru | grep property | awk -F: '{ print $2 }' | uniq
        <property name="name" value="XenServerGuru" />
        <property name="name" value="OvmGuru" />
        <property name="name" value="VMwareGuru" />
        <property name="name" value="Ovm3Guru" />
        <property name="name" value="Simulator Guru"/>
        <property name="name" value="HypervGuru" />
        <property name="name" value="BaremetalGuru" />

**Comment by snuf** [comment]
@NuxRo @karuturi Superseded by #975 and in . Closing this one!

**Comment by karuturi** [comment]
@snuf @NuxRo KVMGuru and LXCGuru are defined at https://github.com/apache/cloudstack/blob/master/server/resources/META-INF/cloudstack/server-compute/spring-server-compute-context.xml

**Pull request closed without merging**
