### PR TITLE
UI: Minor UI improvements

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR makes minor UI improvements.
##### While editing zone, use  “Default network domain for Isolated networks” instead of “Network Domain” & use “Default Guest CIDR for Isolated Networks” instead of “guest CIDR”
<details><summary>Before</summary>
<p>

image

</p>
</details> 
<details><summary>After</summary>
<p>

image

</p>
</details>

##### While deploying a VM, selectively change "launch" to "created" on the button when "start instance" is set to OFF.
<details><summary>Before</summary>
<p>

image

</p>
</details> 
<details><summary>After</summary>
<p>

image
image

</p>
</details> 

##### Add space between system vm toggle & account while adding IP range for Public Traffic Type.
<details><summary>Before</summary>
<p>

image

</p>
</details> 
<details><summary>After</summary>
<p>

image

</p>
</details> 

##### Fix static NAT IP appearing twice
<details><summary>Before</summary>
<p>

image

</p>
</details> 
<details><summary>After</summary>
<p>

image

</p>
</details> 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by vishesh92** [comment]
@blueorangutan ui

**Review by rohityadavcloud — APPROVED** [review]
LGTM didn’t test it but screenshots look good. I think since they are only presentational, we should target 4.19 branch.

**Comment by vishesh92** [comment]
@blueorangutan ui

**Comment by vishesh92** [comment]
@blueorangutan ui

**Comment by vishesh92** [comment]
@blueorangutan ui

**Review by andrijapanicsb — APPROVED** [review]
LGTM, tested

**Pull request merged**
