### PR TITLE
kvm available memory calculation optimization

### PR DESCRIPTION
**Pull request by div8cn**
### Description
Add buffer memory to Available memory for kvm

Fixes: #5523

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@div8cn please fix the checkstyle error
```
[ERROR] /data/git/cloudstack/plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/linux/MemStat.java:69: Line has trailing spaces. [RegexpSingleline]

```

**Comment by sureshanaparti** [comment]
@div8cn Can you check/fix the unit test failure.

```
[INFO] Running org.apache.cloudstack.utils.linux.MemStatTest
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.602 s <<< FAILURE! - in org.apache.cloudstack.utils.linux.MemStatTest
[ERROR] getMemInfoParseTest(org.apache.cloudstack.utils.linux.MemStatTest)  Time elapsed: 0.011 s  <<< FAILURE!
java.lang.AssertionError: expected:<3164520448> but was:<2829840384>
	at org.apache.cloudstack.utils.linux.MemStatTest.getMemInfoParseTest(MemStatTest.java:51)

[ERROR] Failures: 
[ERROR]   MemStatTest.getMemInfoParseTest:51 expected:<3164520448> but was:<2829840384>
```

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Review by sureshanaparti — APPROVED** [review]
code LGTM

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@nvazquez should we consider this for 4.16?

**Comment by sureshanaparti** [comment]
> @nvazquez should we consider this for 4.16?

I think, this is good to go.

**Review by nvazquez — APPROVED** [review]
LGTM

**Pull request merged**
