### PR TITLE
Readd custom css

### PR DESCRIPTION
**Pull request by pbankonier**
## Description
This readds the custom.css file to overwrite the default cloudstack styles.
Currently this is only possible by adding them to the custom.scss in the repository and compile them into the cloudstack3.css.
Now there is an empty custom.css created when compiling the scss source. This custom.css can be overwritten with the custom styles afterwards.
This functionality was broken by https://github.com/apache/cloudstack/pull/3328.

## Types of changes
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?
Deployed this to our test environment and tested functionality.

### CODE REVIEW

**Comment by svenvogel** [comment]
@anuragaw @shwstppr can you take a look?

**Comment by rhtyd** [comment]
Can someone confirm testing?
This does not need to have smoketests as it is purely UI change.

**Comment by svenvogel** [comment]
@anuragaw i see the same like you.

**Comment by svenvogel** [comment]
@rhtyd yes i test it locally and it works.

**Pull request merged**
