### PR TITLE
ui: fix vpc tier redirect to show details

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

When redirecting to VPC tier from VPC view, details tab should be active by default

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):
Before:
Screenshot from 2022-03-30 13-31-08

After:
Screenshot from 2022-03-30 13-31-26

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan ui

**Review by weizhouapache — APPROVED** [review]
tested ok

**Review by weizhouapache — APPROVED** [review]
tested ok !!

**Review by utchoang — APPROVED** [review]
LGTM!

**Comment by weizhouapache** [comment]
@blueorangutan ui

**Pull request merged**
