### PR TITLE
UI: Fixes page size changer doesn't show up on mobile mode

### PR DESCRIPTION
**Pull request by utchoang**
### Description
This PR for fixes page size changer doesn't show up on mobile mode

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### Screenshots (if appropriate):
After fixed:
image

### CODE REVIEW

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by rhtyd** [comment]
@blueorangutan ui

**Comment by davidjumani** [comment]
@utchoang Could you remove https://github.com/apache/cloudstack/pull/4765/commits/d998f2709f1cf1ea5fa957e0b90dfff1b46c17f9 and push ? Thanks

**Comment by davidjumani** [comment]
@blueorangutan ui

**Review by davidjumani — APPROVED** [review]

**Review by rhtyd — APPROVED** [review]

**Pull request merged**
