### PR TITLE
verify that when createTemplate is ued to create templates with same …

### PR DESCRIPTION
**Pull request by manasaveloori**
…name,

all of them fet unique_name under vm_template table so that templates with
same name does not get deleted during template sync

### CODE REVIEW

**Comment by manasaveloori** [comment]
Test when createTemplate is used to create templates having the same name all of them get ... === TestName: test_CreateTemplateWithDuplicateName | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 1 test in 442.896s

OK

**Comment by bhaisaab** [comment]
LGTM

**Comment by nitt10prashant** [comment]
LGTM

**Comment by remibergsma** [comment]
Sanjeev, thanks! Can you please use the git merge script located in ./tools/git/git-pr? See: https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61311655
Let me know if you need help. Thanks!

**Pull request closed without merging**
