### PR TITLE
CLOUDSTACK-9554 Juniper Contrail plug-in is publishing events to wron…

### PR DESCRIPTION
**Pull request by yvsubhash**
Juniper Contrail plug-in is publishing events to message bus instead of event bus

### CODE REVIEW

**Comment by rhtyd** [comment]
LGTM. @yvsubhash can you rebase the branch and edit the PR to base branch 4.9?

**Comment by yvsubhash** [comment]
@rhtyd How abt rebasing it against branch 4.8 and edit the PR to base it to the same?

**Comment by rhtyd** [comment]
okay

**Comment by yvsubhash** [comment]
@rhtyd PR pointed to 4.8 branch

**Comment by cloudmonger** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 130
 Hypervisor xenserver
 NetworkType Advanced
 Passed=101
 Failed=4
 Skipped=6

_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/yj3wnzbceo9uef2/AAB6u-Iap-xztdm6jHX9SjPja?dl=0


**Failed tests:**
* test_non_contigiousvlan.py

 * test_extendPhysicalNetworkVlan Failed

* test_deploy_vm_iso.py

 * test_deploy_vm_from_iso Failing since 15 runs

* test_nic.py

 * test_01_nic Failed

* test_vm_life_cycle.py

 * test_10_attachAndDetach_iso Failing since 16 runs


**Skipped tests:**
test_01_test_vm_volume_snapshot
test_vm_nic_adapter_vmxnet3
test_static_role_account_acls
test_11_ss_nfs_version_on_ssvm
test_3d_gpu_support
test_deploy_vgpu_enabled_vm

**Passed test suits:**
test_deploy_vm_with_userdata.py
test_affinity_groups_projects.py
test_portable_publicip.py
test_over_provisioning.py
test_global_settings.py
test_scale_vm.py
test_service_offerings.py
test_routers_iptables_default_policy.py
test_loadbalance.py
test_routers.py
test_reset_vm_on_reboot.py
test_snapshots.py
test_deploy_vms_with_varied_deploymentplanners.py
test_network.py
test_router_dns.py
test_login.py
test_list_ids_parameter.py
test_public_ip_range.py
test_multipleips_per_nic.py
test_regions.py
test_affinity_groups.py
test_network_acl.py
test_pvlan.py
test_volumes.py
test_deploy_vm_root_resize.py
test_resource_detail.py
test_secondary_storage.py
test_routers_network_ops.py
test_disk_offerings.py

**Comment by rhtyd** [comment]
I don't have the specific hardware to trigger and run regression tests on the changes. Can we get a second code review and then we can merge this. /cc @karuturi @jburwell and others?

**Comment by rhtyd** [comment]
Merging based on code review and Travis, regression tests.

**Pull request merged**
