### PR TITLE
Make networkofferingid required in migrateNetwork

### PR DESCRIPTION
**Pull request by krissterckx**
Fix issue #2851

## Description

Made networkofferingid required in migrateNetwork

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## GitHub Issue/PRs

Fixes: ##2851

## Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
Testing
- [ ] I have added tests to cover my changes.
- [ ] All relevant new and existing integration tests have passed.
- [ ] A full integration testsuite with all test that can run on my environment has passed.

### CODE REVIEW

**Comment by rafaelweingartner** [comment]
@krissterckx can you explain further how making the networkofferingid required in migrateNetwork affects/solves the issue #2657 "KVM hosts are being reset by a script"?

**Comment by rhtyd** [comment]
Moved to 4.11.2.0, in case this bug fix can get in time for RC2.
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by krissterckx** [comment]
Thanks @rhtyd !

**Comment by rhtyd** [comment]
Merging based on code reviews and tests. This API was added by Nuage in 4.11.0 and changes to required settings can be accepted as I assume this API is not used by others yet (breaking their scripts/integration). (ref CLOUDSTACK-10024: Network migration support)

**Pull request merged**
