### PR TITLE
CLOUDSTACK-8180 - RouterVM does no longer provide X-ForwardedFor header with Loadbalancer

### PR DESCRIPTION
**Pull request by wilderrodrigues**
Hi @remibergsma and @DaanHoogland 

The "option forwardfor" in the haproxy has been fixed.

- Make sure the "option forwardfor" is always available by not removing it
- If keepalived is enabled, then set "no option forceclose"

Could you please have a look at this PR?

The first commit is about formatting the code, can be ignored. The second commit is the actual change.

Cheers,
Wilder

### CODE REVIEW

**Comment by remibergsma** [comment]
Thanks for fixing it, LGTM.
Small comment: I see two commits with the same first line. Personally I'd prefer to see from the first line what a commit implements.

**Comment by wilderrodrigues** [comment]
@remibergsma 

I also think it's a bit annoying the commits with the same message, but we have to inform the jira issue.

Next time I will add the jira issue number but not the whole description. Instead of the description I will add the commit message... It will clarify things.

Thanks for the review.

Cheers,
Wilder

**Comment by bhaisaab** [comment]
@wilderrodrigues LGTM, meld the commits to one maybe?

**Comment by miguelaferreira** [comment]
@wilderrodrigues @remibergsma @bhaisaab why not just put the the ticket ID in the commit message?
something like: 
* 	CLOUDSTACK-8180: adding this
* 	CLOUDSTACK-8180: changing that

**Comment by remibergsma** [comment]
I agree, ticket id is enough.

**Comment by wilderrodrigues** [comment]
Yep... Agree.

That's what I also suggested in my reply.

We are getting better... Next one will be perfect. :)

Thanks, guys!

Cheers,
Wilder

Sent from my iPhone

On 01 Jul 2015, at 22:17, Remi Bergsma <notifications@github.com<mailto:notifications@github.com>> wrote:

I agree, ticket id is enough.

**Pull request closed without merging**
