### PR TITLE
SAML2: add cookie with HttpOnly too

### LINKED ISSUE #10003: Unable to change the domain when a user is authenticated by SAML
ISSUE TYPE

BUG

COMPONENT NAME

Component:  Bug

CLOUDSTACK VERSION

Cloudstack version 4.18.2.5, 4.19.1.3

SUMMARY

Unable to change the domain when a user is authenticated by SAML 

Steps to reproduce the issue 

On 4.19.1.3  environment 

1. Enable SAML authentication 
2. Create 2 domains (domain 1 and domain 2)
3. Create Account in each domain and authorize Saml

account-creation

account-creation2

4. Login as single sign-on

single

 

5. Change the domain

changedomain

6. Exception message 

exception

Video recording 

https://www.loom.com/share/7dd809008a7649e7907bdf10c56af185?sid=86038cae-f441-4d8f-b76a-0db59486bf0b

--------------

Followed, the same steps on 4.18.1.1 and found  no issue on 4.18.1.1

Video recording 

https://www.loom.com/share/6cc8b0625c324976b338965ae679ae26?sid=01b0d96e-5b6d-4d77-bacd-e81c62e66610

Expected Behaviour

Cloudstack saml configured users should be able to change the domain 

Actual Behaviour

Cloudstack saml configured users are not able to change the domain

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #10003 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [x] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by DaanHoogland — COMMENTED** [review]
this looks ok, but I have no idea if it results in the desired behaviour. (needs-testing)

**Comment by DaanHoogland** [comment]
@kiranchavala , maybe we can look at testing this together?

**Comment by weizhouapache** [comment]
@blueorangutan test keepEnv

**Review by kiranchavala — APPROVED** [review]
LGTM, tested manually and the saml user is able to switch the domains successfully 

Video recording 

https://www.loom.com/share/bd87a0752712429eaf60f5490af3c3dc?sid=70d14bdc-a27f-4d92-99c0-0e4a024d547c

**Comment by weizhouapache** [comment]
> LGTM, tested manually and the saml user is able to switch the domains successfully
> 
> Video recording
> 
> https://www.loom.com/share/bd87a0752712429eaf60f5490af3c3dc?sid=70d14bdc-a27f-4d92-99c0-0e4a024d547c

thanks @kiranchavala for testing !

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Pull request merged**
