### PR TITLE
ui: Remove misleading anchor tags for users

### PR DESCRIPTION
**Pull request by davidjumani**
### Description

Removes <a> tags which can appear as links and mislead users

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### Screenshots (if appropriate):

Screenshot from 2022-03-23 13-31-22

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan ui

**Review by utchoang — APPROVED** [review]
LGTM!

**Comment by nvazquez** [comment]
@davidjumani can you please fix the conflicts?

**Comment by davidjumani** [comment]
@blueorangutan ui

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
Code LGTM - pl run some manual tests before merging cc @nvazquez and 4.17 team

**Review by nvazquez — APPROVED** [review]
LGTM manually tested OK

**Pull request merged**
