### PR TITLE
4.9 mvn version safeupgradeonly

### PR DESCRIPTION
**Pull request by rhtyd**
Upgrades maven dependencies versions that can be safely upgraded without breaking console-proxy/crypto usage.

Bisected changes from: https://github.com/apache/cloudstack/pull/1397

cc @swill @DaanHoogland

### CODE REVIEW

**Comment by bhaisaab** [comment]
With this change we would be able to use JDK8 for building cloudstack once we fix the build issues of F5 plugin (that's the only component that fails to build with javac 1.8 now).

**Comment by bhaisaab** [comment]
@swill please include this PR in your list, thanks

**Comment by swill** [comment]
@bhaisaab yep, already got it.  👍

**Comment by jburwell** [comment]
@bhaisaab @swill it is important to note that Spring 3 only supports running JDK8 for applications built using a target version of 1.7.  Applications built using Spring 3 a 1.8 version target will be unstable and eventually crash.

**Comment by DaanHoogland** [comment]
@swill busy on this one yet? I am looking to run it as well

**Comment by swill** [comment]
go ahead.  I am trying to get to the bottom of marvin being strange right now.

**Comment by rhtyd** [comment]
@swill thanks, this can be merged first as we wait for bountycastle related changes to work with openjdk 1.7.0_95+

**Comment by swill** [comment]
### CI RESULTS

```
Tests Run: 85
  Skipped: 0
   Failed: 0
   Errors: 0
```



**Associated Uploads**

**`/tmp/MarvinLogs/DeployDataCenter__Apr_26_2016_20_17_04_VKI7EV:`**
* [dc_entries.obj](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1510/tmp/MarvinLogs/DeployDataCenter__Apr_26_2016_20_17_04_VKI7EV/dc_entries.obj)
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1510/tmp/MarvinLogs/DeployDataCenter__Apr_26_2016_20_17_04_VKI7EV/failed_plus_exceptions.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1510/tmp/MarvinLogs/DeployDataCenter__Apr_26_2016_20_17_04_VKI7EV/runinfo.txt)

**`/tmp/MarvinLogs/test_network_0G1KRM:`**
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1510/tmp/MarvinLogs/test_network_0G1KRM/failed_plus_exceptions.txt)
* [results.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1510/tmp/MarvinLogs/test_network_0G1KRM/results.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1510/tmp/MarvinLogs/test_network_0G1KRM/runinfo.txt)

**`/tmp/MarvinLogs/test_vpc_routers_JIBRWD:`**
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1510/tmp/MarvinLogs/test_vpc_routers_JIBRWD/failed_plus_exceptions.txt)
* [results.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1510/tmp/MarvinLogs/test_vpc_routers_JIBRWD/results.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1510/tmp/MarvinLogs/test_vpc_routers_JIBRWD/runinfo.txt)


Uploads will be available until `2016-06-27 02:00:00 +0200 CEST`

*Comment created by [`upr comment`](https://github.com/cloudops/upr).*

**Comment by swill** [comment]
This one is ready pending at least one LGTM vote...

**Comment by rhtyd** [comment]
@DaanHoogland @wido @jburwell review/lgtm please?

**Comment by wido** [comment]
Compiled the code using JDK8 (1.8.0_65) and ran unit tests, works on my system.

Based on the code changes: LGTM

**Comment by DaanHoogland** [comment]
LGTM, i had run the tests as well, with no more then the usual problems &*%(^%. Note that part of the change is mine when you take my lgtm for it;)

**Comment by swill** [comment]
Thank you gentlemen.  I think this one is ready now.  👍

**Pull request merged**
