### PR TITLE
UI: Improve filtering of VM and template settings

### LINKED ISSUE #8074: UI: only the previous vm/template setting is present in the dropdown when add a new setting
When add a setting to a template or vm, if try to add another setting, only the previous setting is present in the dropdown

This is a very common UI bug, for example when add settings to template

image

for add setting to vm

image

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~
4.19
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

### PR DESCRIPTION
**Pull request by bernardodemarco**
### Description

When manipulating VM and template settings, the UI provides a dropdown with the available setting names and values. However, if a user first adds a setting and then tries to add another, the dropdown only shows the previously added setting's name and value.

Furthermore, whenever the user types a character into the setting name input field, a Vue warning is thrown in the console, stating that an incorrect value type has been passed to the `options` prop of the `a-auto-complete` component.

Therefore, this PR improves VM and template settings filtering by always displaying the available setting names and their values, even when a setting has already been added. Besides that, the Vue warning has been properly fixed.

---

Fixes #8074

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [X] Trivial

### Screenshots (if appropriate):

image

image

### How Has This Been Tested?

1. When adding the first setting of a VM/template, I verified that all available setting names and their values were displayed correctly in the dropdowns.
2. I then added another setting, and all available setting names and their values were also displayed correctly.
3. When typing the setting name in the input field, I confirmed that no warnings were thrown.

### CODE REVIEW

**Comment by bernardodemarco** [comment]
@blueorangutan ui

**Review by DaanHoogland — APPROVED** [review]
lgtm, tested in qa

**Review by rohityadavcloud — APPROVED** [review]
LGTM didn't test it though

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Pull request merged**
