### PR TITLE
CLOUDSTACK-10014: Fix test accounts remove secret key check

### PR DESCRIPTION
**Pull request by borisstoyanov**
…_same_account: remove secret key checks since it was removed from the API response
Removing secret key as it's not part of the api response any more. The changed test is passing:

screen shot 2017-07-24 at 4 58 25 pm

Ping @rhtyd @DaanHoogland @PaulAngus @jayapalu for review

### CODE REVIEW

**Comment by rhtyd** [comment]
@borisstoyanov can you instead call the other API (getUserKeys from https://github.com/apache/cloudstack/pull/1996) to do the checks?

**Comment by borisstoyanov** [comment]
yes @rhtyd, makes sense.

**Comment by borisstoyanov** [comment]
@rhtyd done

**Comment by rhtyd** [comment]
LGTM, @borisstoyanov Travis failed for some reason.

**Pull request merged**
