### PR TITLE
Removed check on SSLEngine client mode

### PR DESCRIPTION
**Pull request by Spaceman1984**
## Description

The SSL engine defaults to "Server mode" when doing handshaking. This PR removes the check on the mode which was causing tests to fail.

This behavior was changed in OpenJDK 11.0.8
```
JDK-8245077: Default SSLEngine Created in Server Role
=====================================================
In JDK 11 and later, `javax.net.ssl.SSLEngine` by default used client
mode when handshaking.  As a result, the set of default enabled
protocols may differ to what is expected. `SSLEngine` would usually be
used in server mode. From this JDK release onwards, `SSLEngine` will
default to server mode. The
`javax.net.ssl.SSLEngine.setUseClientMode(boolean mode)` method may be
used to configure the mode.
```

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

This was tested by building Cloudstack and allowing the tests to run.

### CODE REVIEW

**Comment by Spaceman1984** [comment]
@GabrielBrascher I have created the pull request for 4.14 because this is JDK 11 specific, it will go to master as well.

**Comment by Spaceman1984** [comment]
@blueorangutan package

**Comment by Spaceman1984** [comment]
@blueorangutan test

**Comment by RodrigoDLopez** [comment]
Code LGTM.

**Comment by rhtyd** [comment]
@spaceman1984 can you check why the tests are failing, I'll kick tests again
@blueorangutan test

**Comment by Spaceman1984** [comment]
I'll take a look why tests are failing @rhtyd

**Comment by rhtyd** [comment]
Thanks @Spaceman1984 I've verified this fixes the immediate unit test failure and will merge it. If you find the failng test due to regression pl send a new PR.

**Pull request merged**
