### PR TITLE
Update GPU support for V100,T4,A5500.

### PR DESCRIPTION
**Pull request by pdion891**
### Description

Update GPU and vGPU support for Nvidia  V100, T4 and A5500 cards.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@pdion891 could  you advice on how to test this, or report on your own testing?

**Review by shwstppr — COMMENTED** [review]
code LGTM.

In UI, however, with new options for GPU interface looks not so good. Radio button could be converted to select item,

```
-          <a-radio-group
+          <a-select
             v-model:value="form.pcidevice"
-            buttonStyle="solid"
-            @change="selected => { handleGpuChange(selected.target.value) }">
-            <a-radio-button v-for="(opt, optIndex) in gpuTypes" :key="optIndex" :value="opt.value">
+            showSearch
+            optionFilterProp="label"
+            :filterOption="(input, option) => {
+              return option.children[0].children.toLowerCase().indexOf(input.toLowerCase()) >= 0
+            }"
+            :placeholder="$t('label.gpu')"
+            @change="handleGpuChange">
+            <a-select-option v-for="(opt, optIndex) in gpuTypes" :key="optIndex" :value="opt.value">
               {{ opt.title }}
-            </a-radio-button>
-          </a-radio-group>
+            </a-select-option>
+          </a-select>
```
Screenshot from 2022-08-16 13-59-41

With select,
Screenshot from 2022-08-16 14-00-27

**Comment by pdion891** [comment]
@DaanHoogland , I didn't test this yet, this is just a backport from previous version / UI. 
I'll comment once tested and remove the PR from draft mode.

**Comment by shwstppr** [comment]
Accidentally marked this ready for review yesterday, moved it back to draft

**Comment by rohityadavcloud** [comment]
ping @pdion891 @shwstppr is this still relevant?

**Comment by pdion891** [comment]
@rohityadavcloud  yes, but at this point it would make sense to update it with recent GPU model.
I will rebase this PR and add some more GPU to it.

**Comment by shwstppr** [comment]
@pdion891 any update on this?

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by DaanHoogland** [comment]
@pdion891 I updated the branch. Can you comment on the state of this PR?

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by pdion891** [comment]
@shwstppr I've added your snippet suggestion.

Here are some highlight about this PR: it remove vGPU support from legacy grid card not supported by recent NVIDIA driver.
because of the passthrough generic, any GPU passthrough is working but vGPU need to be defined. 

This PR include known vGPU offering for A2, A10, A40, A5500, V100, T4 GPU card.

Some tests where done on XenServer 8.2cu1 with nvidia RTX driver 16.1. Not all vGPU definition have been tested, only made sure vGPU definition exist on XenServers.

**Review by DaanHoogland — COMMENTED** [review]
clgtm, just wondering if encoding vGPUs in the UI is a good thing?

**Comment by pdion891** [comment]
> clgtm, just wondering if encoding vGPUs in the UI is a good thing?

it's not, it prevent us to easily add new GPU support. Currently, any GPU offering in passthrough mode can be created thru the API, but cannot thru the UI, they must be define like in this PR. ideally we would be able to define them a bit like GuestOS type works.

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by DaanHoogland** [comment]
@shwstppr this has backend changes as well. Do you want to just test the UI?

**Comment by shwstppr** [comment]
@DaanHoogland missed those 

@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test keepEnv

**Review by DaanHoogland — APPROVED** [review]
looks good

image

and then

image

I think the way that vgpu is decided on needs an overhaul but would pull that out of scope of this PR

**Review by shwstppr — APPROVED** [review]
LGTM

**Pull request merged**
