### PR TITLE
Revert of the "Revert "Fix virtual template size for managed storage for KVM / refactor cloud-install-sys-tmplt""

### PR DESCRIPTION
**Pull request by andrijapanicsb**
The original PR #3371  was merged without Trillian tests being done, so I have reverted the merge by creating (via GitHub) the PR #3771 

Then, tests were done on the original PR 3371, showing NO regression (77 tests fine, 0 failed), so it is (with all the other LGTMs) safe to merge it after all.

I'm thus creating this PR which is the revert of the revert (3771) of the original PR 3371 - i.e. same PR as the original one.

Will run tests again and ask for LGTMs before finally merging it.

### CODE REVIEW

**Comment by andrijapanicsb** [comment]
@blueorangutan package

**Comment by andrijapanicsb** [comment]
@svenvogel @DennisKonrad please review this PR (revert of the revert = same PR as the original one #3371 that you guys created.

I'm doing another round of automated tests on this one and will be ready for merging based on all LGTMs on the original PR

@weizhouapache may I kindly ask you for the opinion if PR looks good (equivalent to original PR 3371) - I've done checks myslef, but prefer another opinion please.

**Comment by andrijapanicsb** [comment]
@blueorangutan test

**Comment by syed** [comment]
LGTM :+1:

**Comment by andrijapanicsb** [comment]
Tests failed silently, re-running:

@blueorangutan test

**Comment by andrijapanicsb** [comment]
@blueorangutan package

**Comment by andrijapanicsb** [comment]
@blueorangutan package

**Comment by andrijapanicsb** [comment]
@blueorangutan test

**Comment by andrijapanicsb** [comment]
You have to LOVE!!! the Epel repo issues 🤦‍♂ 

@blueorangutan test

**Comment by svenvogel** [comment]
@andrijapanicsb whaaat? okay i understand. so i can add this to spec file as a dependency. can i update my PR if its under your name?

**Comment by andrijapanicsb** [comment]
no @svenvogel - there are constant issues with EPEL repo (which Trillian is using for some packages), mirrors don't sync properly due to soruce issues - so the Trillian build jobs just fails...
running a new one again now... no changes on your end.

**Comment by andrijapanicsb** [comment]
ok tests are finally running... need a few hours for the results.

**Comment by andrijapanicsb** [comment]
Based on all the LGTMs on this one (and the original #3371) and the KVM automated tests - I'm merging this one.

**Pull request merged**
