### PR TITLE
server: fix vm_stats records are not removed if batchsize is 0

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

Prior to this change
```
2024-10-17T10:32:55,455 DEBUG [c.c.v.d.VmStatsDaoImpl] (StatsCollector-5:[ctx-ec4b3698]) (logid:708dd27c) Starting to remove all vm_stats rows older than [Wed Oct 16 22:32:55 UTC 2024].
2024-10-17T10:32:55,456 INFO  [c.c.v.d.VmStatsDaoImpl] (StatsCollector-5:[ctx-ec4b3698]) (logid:708dd27c) Removed a total of [0] vm_stats rows older than [Wed Oct 16 22:32:55 UTC 2024].
```

With this change
```
2024-10-17T10:41:33,315 DEBUG [c.c.v.d.VmStatsDaoImpl] (StatsCollector-5:[ctx-dd8d7e09]) (logid:338dd659) Starting to remove all vm_stats rows older than [Wed Oct 16 22:41:33 UTC 2024].
2024-10-17T10:43:03,184 INFO  [c.c.v.d.VmStatsDaoImpl] (StatsCollector-5:[ctx-dd8d7e09]) (logid:338dd659) Removed a total of [1661329] vm_stats rows older than [Wed Oct 16 22:41:33 UTC 2024].

```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [x] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by rohityadavcloud — APPROVED** [review]
LGTM didn't test it

**Review by rohityadavcloud — APPROVED** [review]

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
related to 
@JoaoJandre 's PR #8740
 @shwstppr 's PR #8999 
@vishesh92 's merge commit https://github.com/apache/cloudstack/commit/3923f80c225c593a79e32cc7d9d5567fb63ecca2#diff-1ccbb9294e1b4e876df4f865c95f8f302ccea7a2ce6cfe574d0efa76e8f88868R1238

**Review by JoaoJandre — APPROVED** [review]
LGTM

**Comment by vishesh92** [comment]
@weizhouapache We need this change in 4.19 since the PRs you mentioned are part of 4.19 branch.

**Review by shwstppr — APPROVED** [review]
code lgtm

**Comment by weizhouapache** [comment]
> @weizhouapache We need this change in 4.19 since the PRs you mentioned are part of 4.19 branch.

4.19 has similar change introduced in #8740 , it works

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@blueorangutan test

**Pull request merged**
