### PR TITLE
Host capacity calculation: use VM creation time if update time is null.

### PR DESCRIPTION
**Pull request by mprokopchuk**
CapacityManagementImpl.updateCapacityForHost(..) use VM update time in capacity calculation.

VM update time is nullable in DB and can cause NullPointerException if record in vm_instance has defined last_host_id and undefined update_time.

Added logic to check whether update_time is null and use created time instead (which is not null).

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [X] Trivial

### How Has This Been Tested?

Tested manually.

### CODE REVIEW

**Comment by mprokopchuk** [comment]
@blueorangutan package

**Comment by mprokopchuk** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Review by rohityadavcloud — APPROVED** [review]

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@JoaoJandre since this is a bugfix, causing NPE exception can we consider it?

**Comment by kiranchavala** [comment]
@blueorangutan test

**Review by kiranchavala — APPROVED** [review]
LGTM, Steps to reproduce the issue 

Before fix 

1. Stop a running vm 

2. Manually update the database with the following sql query 

mysql>update vm_instance set update_time=NULL where id=20;


3. Execute the list capacity api call with fetchlatest=true

https://cloudstack.apache.org/api/apidocs-4.19/apis/listCapacity.html

4. Null pointer exception in the logs

```
2024-09-11 09:38:53,428 DEBUG [c.c.a.ApiServlet] (qtp660017404-18:ctx-031e6e67) (logid:4fab4036) ===START===  10.0.3.251 -- GET  apiKey=l1_SR4uC25TftqakF--jG9Su3VhMIeR6nvTZairizwO-ZEx_du9PRQsg8efhUP5THn_4vPM1IfzABYMmfkwYig&command=listCapacity&fetchlatest=true&response=json&signature=T8%2FBKjc9uZmnGlCkiAn21RCy6qU%3D


2024-09-11 09:38:53,456 ERROR [c.c.a.AlertManagerImpl] (qtp660017404-18:ctx-031e6e67 ctx-60961f1a) (logid:4fab4036) Caught exception in recalculating capacity
java.lang.NullPointerException
	at com.cloud.capacity.CapacityManagerImpl.updateCapacityForHost(CapacityManagerImpl.java:714)
	at com.cloud.alert.AlertManagerImpl.recalculateCapacity(AlertManagerImpl.java:286)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```



After fix 

1. No Null pointer exceptinon observed 


Logs

```

2024-09-11 10:27:01,862 DEBUG [c.c.a.ApiServlet] (qtp253011924-22:[ctx-8d67dfb3]) (logid:91763e20) ===START===  10.0.3.251 -- GET  apiKey=l1_SR4uC25TftqakF--jG9Su3VhMIeR6nvTZairizwO-ZEx_du9PRQsg8efhUP5THn_4vPM1IfzABYMmfkwYi&command=listCapacity&fetchlatest=true&response=json&signature=p5x0bMfDYCzQyGsSHP4v2PSouGc%3D

2024-09-11 10:27:01,932 INFO  [c.c.a.ApiServlet] (qtp253011924-22:[ctx-8d67dfb3, ctx-ca9e43a9]) (logid:91763e20) (userId=2 accountId=2 sessionId=node01wqd73ie98jsaho1i4b0xibv4) 10.0.3.251 -- GET apiKey=l1_SR4uC25TftqakF--jG9Su3VhMIeR6nvTZairizwO-ZEx_du9PRQsg8efhUP5THn_4vPM1IfzABYMmfkwYi&command=listCapacity&fetchlatest=true&response=json&signature=p5x0bMfDYCzQyGsSHP4v2PSouGc%3D 200 {"listcapacityresponse":{"count":10,"capacity":[{"type":0,"name":"MEMORY","zoneid":"3d129b60-79b8-43aa-bf87-f06d2341b9aa","zonename":"ref-trl-7311-k-Mol8-kiran-chavala","capacityallocated":2684354560,"capacityused":2684354560,"capacitytotal":7228305408,"percentused":"37.14"},{"type":1,"name":"CPU","zoneid":"3d129b60-79b8-43aa-bf87-f06d2341b9aa","zonename":"ref-trl-7311-k-Mol8-kiran-chavala","capacityallocated":2000,"capacityused":2000,"capacitytotal":12600,"percentused":"15.87"},{"type":2,"name":"STORAGE","zoneid":"3d129b60-79b8-43aa-bf87-f06d2341b9aa","zonename":"ref-trl-7311-k-Mol8-kiran-chavala","capacityused":1250223456256,"capacitytotal":2197949513728,"percentused":"56.88"},{"type":3,"name":"STORAGE_ALLOCATED","zoneid":"3d129b60-79b8-43aa-bf87-f06d2341b9aa","zonename":"ref-trl-7311-k-Mol8-kiran-chavala","capacityused":24318968016,"capacitytotal":4395899027456,"percentused":"0.55"},{"type":4,"name":"VIRTUAL_NETWORK_PUBLIC_IP","zoneid":"3d129b60-79b8-43aa-bf87-f06d2341b9aa","zonename":"ref-trl-7311-k-Mol8-kiran-chavala","capacityused":3,"capacitytotal":20,"percentused":"15"},{"type":5,"name":"PRIVATE_IP","zoneid":"3d129b60-79b8-43aa-bf87-f06d2341b9aa","zonename":"ref-trl-7311-k-Mol8-kiran-chavala","capacityused":2,"capacitytotal":20,"percentused":"10"},{"type":6,"name":"SECONDARY_STORAGE","zoneid":"3d129b60-79b8-43aa-bf87-f06d2341b9aa","zonename":"ref-trl-7311-k-Mol8-kiran-chavala","capacityused":1250222407680,"capacitytotal":2197949513728,"percentused":"56.88"},{"type":7,"name":"VLAN","zoneid":"3d129b60-79b8-43aa-bf87-f06d2341b9aa","zonename":"ref-trl-7311-k-Mol8-kiran-chavala","capacityused":1,"capacitytotal":20,"percentused":"5"},{"type":19,"name":"GPU","zoneid":"3d129b60-79b8-43aa-bf87-f06d2341b9aa","zonename":"ref-trl-7311-k-Mol8-kiran-chavala","capacityused":0,"capacitytotal":0,"percentused":"0"},{"type":90,"name":"CPU_CORE","zoneid":"3d129b60-79b8-43aa-bf87-f06d2341b9aa","zonename":"ref-trl-7311-k-Mol8-kiran-chavala","capacityallocated":4,"capacityused":4,"capacitytotal":3,"percentused":"133.33"}]}}

2024-09-11 10:27:01,932 DEBUG [c.c.a.ApiServlet] (qtp253011924-22:[ctx-8d67dfb3, ctx-ca9e43a9]) (logid:91763e20) ===END===  10.0.3.251 -- GET  apiKey=l1_SR4uC25TftqakF--jG9Su3VhMIeR6nvTZairizwO-ZEx_du9PRQsg8efhUP5THn_4vPM1IfzABYMmfkwYi&command=listCapacity&fetchlatest=true&response=json&signature=p5x0bMfDYCzQyGsSHP4v2PSouGc%3D
```

**Pull request merged**
