### PR TITLE
Support migration of VM imported from a remote host

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

This PR fixes: https://github.com/apache/cloudstack/issues/8827
Importing a VM from a remote host uses a dummy VM template which is not present on the secondary store, leading to NPEs when migrating the VM. This PR enables migrating oly the volume (not the template)

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [X] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
CLGTM

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@Pearl1594 Is this live migration of the volume, or offline?

**Comment by Pearl1594** [comment]
live migration @sureshanaparti

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
Tested the PR. Was able to reproduce the issue. Not able to reproduce it after this patch.

**Pull request merged**
