### PR TITLE
Use project version on pom dependencies

### PR DESCRIPTION
**Pull request by nvazquez**
### Description

This PR fixes the POM dependencies from a hardcoded value to the project.version property on dependencies

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by nvazquez** [comment]
@blueorangutan package

**Review by shwstppr — APPROVED** [review]
Code LGTM

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
looks good and if it works fine, but why these four? looking for "<version>.*</version>" gives a lot more occurrences of hardcoded project versions (107+ in my current 4.18 workspace)

**Comment by nvazquez** [comment]
@DaanHoogland these were only on dependencies, could be fixed as well for the parent pom definition but that may be conflicting and require more testing - I can test it and propose it for 4.20 on a separate PR

**Review by weizhouapache — COMMENTED** [review]
@nvazquez 
good

there is one more in 
./plugins/affinity-group-processors/non-strict-host-anti-affinity/pom.xml

**Comment by nvazquez** [comment]
Thanks @weizhouapache, added

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
Packaging and GH CI should be enough here @nvazquez?

**Comment by nvazquez** [comment]
LGTM @shwstppr

**Review by Pearl1594 — APPROVED** [review]

**Pull request merged**
