### PR TITLE
Revert "Externalize kvm agent storage timeout configuration"

### PR DESCRIPTION
**Pull request by DaanHoogland**
Reverts apache/cloudstack#4585

this has been tested locally, #4585 introduced a regression where KVM hosts could not be added to a zone. It was not found in older smoke tests setups, so probably introduced in combination with some other PR that got merged between the smoketest run and the merge of #4585.

### CODE REVIEW

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Review by nvazquez — APPROVED** [review]
LGTM

**Review by harikrishna-patnala — APPROVED** [review]
I see @GutoVeronezi also agreed to revert PR#4585 now. So LGTM

**Comment by rhtyd** [comment]
Lgtm

**Pull request merged**
