### PR TITLE
Revert "parallel nic adding"

### PR DESCRIPTION
**Pull request by nvazquez**
Reverts apache/cloudstack#5541

PR is reverted as the issues is not fixed completely, another issue raised: https://github.com/apache/cloudstack/issues/5651. The fix for it introduces regressions on Travis runs: https://github.com/apache/cloudstack/pull/5658

### CODE REVIEW

**Review by weizhouapache — APPROVED** [review]
lgtm

**Comment by nvazquez** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
just the constraint needs to be removed, but this will work. note that #5499 is re-opened with this (cc @div8cn)

**Comment by nvazquez** [comment]
Travis passed, merging based on approvals and packaging, no smoke tests needed

**Review by hsdgd — COMMENTED** [review]
hayesy

**Pull request merged**
