### PR TITLE
Automation for CLOUDSTACK-9214 , detect wrong GW or NM

### PR DESCRIPTION
**Pull request by pavanb018**
Automation for CLOUDSTACK-9214

This script automates the validation of  network address or broadcast address given for gateway or wrong netmask is given during network creation,

### CODE REVIEW

**Comment by DaanHoogland** [comment]
looks good on first sight, buiding an env to test.

**Comment by DaanHoogland** [comment]
nosetests --with-marvin --marvin-config=/data/shared/marvin/mct-zone1-kvm1-kvm2-zwps-sg.cfg -s -a tags=advanced,required_hardware=false /data/git/cs1/cloudstack/test/integration/component/test_invalid_gw_nm.py

==== Marvin Init Started ====

=== Marvin Parse Config Successful ===

=== Marvin Setting TestData Successful===

==== Log Folder Path: /tmp//MarvinLogs//Jan_07_2016_10_55_08_UKK65V. All logs will be available here ====

=== Marvin Init Logging Successful===

==== Marvin Init Successful ====
=== TestName: test_isolated_nw_invalid_gw | Status : SUCCESS ===

**Comment by shwetaag** [comment]
LGTM

**Comment by DaanHoogland** [comment]
@shwetaag a LGTM without justification of what verification is done won't be accepted. Please specify what you did to come to this conclusion.

**Comment by shwetaag** [comment]
@DaanHoogland  I did the code review by code walk through and the code looks good to me

**Comment by DaanHoogland** [comment]
LGTM too, thanks @shwetaag

**Pull request merged**
