### PR TITLE
maven: bump up vmware sdk jar to 6.7

### PR DESCRIPTION
**Pull request by rhtyd**
This bumps up the vmware jar dependency to 6.7.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
Testing
- [ ] I have added tests to cover my changes.
- [x] All relevant new and existing integration tests have passed.
- [x] A full integration testsuite with all test that can run on my environment has passed.

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package
@borisstoyanov when you've time this/next week, can you help investigate why packaging is failing?

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-55u3

**Comment by onitake** [comment]
@rhtyd @borisstoyanov Can you rerun the tests against ESXi 6.5 (and/or 6.0 and 6.7) to be sure it works in all supported and soon-to-be-supported (4.11.3) configurations?
Or am I missing something here?

**Comment by rhtyd** [comment]
I had recently ran tests against vmware 6.5u2, no regressions seen other than usual intermittent environment caused failures @onitake

**Pull request merged**
