### PR TITLE
Ip manager refactor

### PR DESCRIPTION
**Pull request by DaanHoogland**
## Description

A refactor of ipAddressManagerImpl for investigating failures with test_nic and retrieval of ip addresses in our cloud

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@DaanHoogland trillian maintenance downtime, will rekick
@blueorangutan test

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@DaanHoogland any work on this or is this abandoned (in which case close this)?

**Comment by DaanHoogland** [comment]
I won't close this or work on it soon. It is a constant reminder of one of the more un-maintainable pieces of code. And I will revisit when work on the IP manager will be needed.

**Comment by DaanHoogland** [comment]
retry sometime later

**Pull request closed without merging**
