### PR TITLE
CLOUDSTACK-9114: restartnetwork with cleanup should restart the RVRs …

### PR DESCRIPTION
**Pull request by DaanHoogland**
…one by one

Testing results:

(1) before change:
job started at 2015-12-09 09:26:07,570, ended at 2015-12-09 09:28:25,524
38 packets lost (333 packets transmitted, 295 received, 11% packet loss, time 332284ms)

(2) after change:
job started at 2015-12-09 09:32:00,543, ended at 2015-12-09 09:34:26,535
1 packet lost (623 packets transmitted, 622 received, 0% packet loss, time 622598ms)

### CODE REVIEW

**Comment by DaanHoogland** [comment]
This is an old PR by Wei (@ustcweizhou ) I have no clue as to why this was never merged. It swhould have been.

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@rhtyd do you want this on 4.11 as well?

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
I'll re-submit a PR that will reduce VR downtime during upgrade, will close this one, have stolen the commit from this PR originally by Wei ;)

**Pull request closed without merging**
