### PR TITLE
UI: Add filter to list encrypted volumes

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

This PR fixes: https://github.com/apache/cloudstack/issues/9130

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

### How Has This Been Tested?

Added toggle button for filtering only encrypted volumes:
image

When set to true, passes 'isencrypted' parameter to the listVolumes API call:
image

When set to false, returns all non-encrypted volumes:
image

### CODE REVIEW

**Comment by Pearl1594** [comment]
@blueorangutan ui

**Review by DaanHoogland — APPROVED** [review]
clgtm and tested in qa, but I think it can do with more testing (with real encrypted volumes)

**Review by FelipeM525 — APPROVED** [review]
I tested this PR using the simulator build and it looks good to me!



<details>
<summary>
images
</summary>

image


image

image

image

</details>

**Comment by FelipeM525** [comment]
@DaanHoogland  In order to address your comment, I've also tested this PR in a local environment by creating an encrypted volume and testing the new filter.

<details>
<summary>
Images
</summary>

image

image

image

</details>

**Pull request merged**
