### PR TITLE
maven: configure toolchains based on ASF infra jdk names

### PR DESCRIPTION
**Pull request by rhtyd**
This adds toolchain configuration for CloudStack to use specific
toolchain for building per ASF infra's configured toolchain.
Reference: https://issues.apache.org/jira/browse/INFRA-19817

### CODE REVIEW

**Comment by rhtyd** [comment]
Experimental to see if would work to build/pass the Jenkins job as well work on one's laptop, build servers etc.

@blueorangutan package

**Comment by rhtyd** [comment]
Jenkins/asf failed at:
```
[ERROR] Failed to execute goal org.codehaus.mojo:cobertura-maven-plugin:2.7:instrument (default-cli) on project checkstyle: Execution default-cli of goal org.codehaus.mojo:cobertura-maven-plugin:2.7:instrument failed: Plugin org.codehaus.mojo:cobertura-maven-plugin:2.7 or one of its dependencies could not be resolved: Could not find artifact com.sun:tools:jar:0 at specified path /usr/local/asfpackages/java/jdk-11.0.6/../lib/tools.jar -> [Help 1]
[ERROR] 
```

**Comment by DaanHoogland** [comment]
ok, that was quick, i removed cobertura and all reporting marked as deprecated by Jenkins. I think we have too little left now :(

**Comment by rhtyd** [comment]
Alright as far as I can tell, both Jenkins and Travis are green.

**Comment by DaanHoogland** [comment]
also figuring out the replacement of findbugs: spotbugs

**Comment by DaanHoogland** [comment]
changes still look good (if i may say so) but the build seems to have slowed down considerably. Looking at profiles for to move the analysis to. also reporting is as of yet slobby, needs attention.

**Comment by DaanHoogland** [comment]
If we merge the toolchain bit, we'll need to do it in master as well as any open 4.13 so we can see jdk11 be used in master and jdk8 in 4.13

**Comment by rhtyd** [comment]
The PR is only against master @DaanHoogland, do you me to raise against 4.13?

**Comment by DaanHoogland** [comment]
WHo-ever @rhtyd I can do as well but just wanted to note that for testing toolchain to meet our objectives we need bot PRs to work.

**Comment by DaanHoogland** [comment]
FYI: I cleanup up to enable the site -, and -Penablefindbugs runs (again)

**Comment by rhtyd** [comment]
@DaanHoogland can we just solve the jdk11 issue first for now? And address the jococo/cobertura issue separately?

**Comment by DaanHoogland** [comment]
@rhtyd I think we should tell infra that we are not going for their toolchains plugin (as it requires to many people and installations to adjust). Thoughts?
btw I agree we should separate the jdk/qa tools issues. I was a bit optimistic, sorry

**Comment by rhtyd** [comment]
You've my support @DaanHoogland, maybe discuss a workaround - perhaps we did not understand the usage/configuration of toolchains well?

**Comment by DaanHoogland** [comment]
removing from the milestone. this is a general maintnance issue that we need to keep giving tlc.

**Comment by rhtyd** [comment]
Closing this as @DaanHoogland  has created https://github.com/apache/cloudstack/pull/3887

**Pull request closed without merging**
