### PR TITLE
fix ping tests to properly recognise successful ping test

### PR DESCRIPTION
**Pull request by PaulAngus**
fix ping tests to properly recognise successful ping test

### CODE REVIEW

**Comment by serg38** [comment]
LGTM for testing

Before 
sshClient: DEBUG: {Cmd: ping -c 3 8.8.8.8 via Host: 10.140.12.103} {returns: [u'PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.', u'64 bytes from 8.8.8.8: icmp_seq=1 ttl=54 time=4.
72 ms', u'64 bytes from 8.8.8.8: icmp_seq=2 ttl=54 time=4.66 ms', u'64 bytes from 8.8.8.8: icmp_seq=3 ttl=54 time=4.61 ms', u'', u'--- 8.8.8.8 ping statistics ---', u'3 packets transmitted, 3 received, 0% packet loss, time 2001ms', u'rtt min/avg/max/mdev = 4.611/4.666/4.723/0.091 ms']}
TestRouterDHCPHosts: DEBUG: SSH result: [u'PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.', u'64 bytes from 8.8.8.8: icmp_seq=1 ttl=54 time=4.72 ms', u'64 bytes from 8.8.8.8: icmp_seq=2 ttl=54 time=4.66 ms', u'64 bytes from 8.8.8.8: icmp_seq=3 ttl=54 time=4.61 ms', u'', u'--- 8.8.8.8 ping statistics ---', u'3 packets transmitted, 3 received, 0% packet loss, time 2001ms', u'rtt min/avg/max/mdev = 4.611/4.666/4.723/0.091 ms']; COUNT is ==> 0
test_router_dhcphosts (integration.smoke.test_router_dhcphosts.TestRouterDHCPHosts): CRITICAL: FAILED: test_router_dhcphosts: ['Traceback (most recent call last):\n', ' File "/usr/local/lib/python2.7/unittest/case.py", line 331, in run\n testMethod()\n', ' File "/home/t_vazqnadmin/cloudstack/test/integration/smoke/test_router_dhcphosts.py", line 356, in test_router_dhcphosts\n self.test_ssh_command(self.vm_1, nat_rule1, "natrule1")\n', ' File "/home/t_vazqnadmin/cloudstack/test/integration/smoke/test_router_dhcphosts.py", line 201, in test_ssh_command\n "Ping to outside world from VM should be successful"\n', ' File "/usr/local/lib/python2.7/unittest/case.py", line 515, in assertEqual\n assertion_func(first, second, msg=msg)\n', ' File "/usr/local/lib/python2.7/unittest/case.py", line 508, in _baseAssertEqual\n raise self.failureException(msg)\n', 'AssertionError: ## Ping to outside world from VM should be successful\n']

After
sshClient: DEBUG: ====Trying SSH Connection: Host:10.144.31.41 User:root Port:22 RetryCnt:60===
paramiko.transport: DEBUG: starting thread (client mode): 0x4206310L
paramiko.transport: INFO: Connected (version 2.0, client OpenSSH_5.3)
paramiko.transport: DEBUG: kex algos:[u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'ssh-dss'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] client mac:[u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
paramiko.transport: DEBUG: Ciphers agreed: local=aes128-ctr, remote=aes128-ctr
paramiko.transport: DEBUG: using kex diffie-hellman-group14-sha1; server key type ssh-rsa; cipher: local aes128-ctr, remote aes128-ctr; mac: local hmac-sha1, remote hmac-sha1; compression: local none, remote none
paramiko.transport: DEBUG: Switch to new keys ...
paramiko.transport: DEBUG: Adding ssh-rsa host key for 10.144.31.41: f662631595339bcea0d93948261bf655
paramiko.transport: DEBUG: Trying SSH agent key 9523f82115a1b2102b669b21e8a1084f
paramiko.transport: DEBUG: userauth is OK
paramiko.transport: INFO: Authentication (publickey) failed.
paramiko.transport: DEBUG: userauth is OK
paramiko.transport: INFO: Authentication (password) successful!
sshClient: DEBUG: ===SSH to Host 10.144.31.41 port : 22 SUCCESSFUL===

**Comment by jburwell** [comment]
@PaulAngus can you open a JIRA ticket for this issue and amend your commit message to reference it?  Also, this change would be beneficial to testing the upcoming 4.8.2.0 and 4.9.1.0 releases as well.  Could you [change the base branch](https://github.com/blog/2224-change-the-base-branch-of-a-pull-request) of this PR to be 4.8?

**Comment by murali-reddy** [comment]
Just ran in to this issue. Fix LGTM.

**Comment by jburwell** [comment]
Since this PR is superseded by #1693, @PaulAngus can you close this one?

**Pull request closed without merging**
