### PR TITLE
Cloudstack 8656: do away with silently ignoring exceptions

### PR DESCRIPTION
**Pull request by DaanHoogland**

### CODE REVIEW

**Comment by mike-tutkowski** [comment]
Aside from a few comments on 04e9083c3199effa295e47bc617b9b406adb6109, LGTM.

**Comment by wilderrodrigues** [comment]
LGTM :+1:

**Comment by DaanHoogland** [comment]
@mike-tutkowski are you alright with this now (merge-level allright;)?

**Comment by DaanHoogland** [comment]
@mike-tutkowski sorry didn't notice your reply, I added a view more. Can you have a look?

**Comment by mike-tutkowski** [comment]
I just had a comment on 87ae150.

**Comment by DaanHoogland** [comment]
two lgtm and succesful travis, merge gives no conflicts but will do a local build before push anyway

**Pull request merged**
