### PR TITLE
Updated pod response, grouped the parameters: "startip, endip, vlanid, forsystemvms" as ip range response and added to ipranges parameter.

### PR DESCRIPTION
**Pull request by sureshanaparti**
### Description
This PR updates the pod response, grouped the parameters: startip, endip, vlanid, forsystemvms as ip range response and added to ipranges parameter (a new parameter to hold the list of IP range details).

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### Screenshots (if appropriate):

Pod_IpRanges

### How Has This Been Tested?

Manually tested the updated API response.

Before changes:

```
(cloudcmk) > list pods
{
  "count": 1,
  "pod": [
    {
      "allocationstate": "Enabled",
      "endip": [
        "10.0.36.60",
        "10.0.36.69"
      ],
      "forsystemvms": [
        "0",
        "1"
      ],
      "gateway": "10.0.32.1",
      "hasannotations": false,
      "id": "43ffd982-8942-4c9a-88f3-002dc7f5d411",
      "name": "Pod1",
      "netmask": "255.255.240.0",
      "startip": [
        "10.0.36.41",
        "10.0.36.67"
      ],
      "vlanid": [
        "vlan://untagged",
        "vlan://untagged"
      ],
      "zoneid": "be8e7d3e-2f57-433d-9c93-208949e2ec1d",
      "zonename": "ref-trl-1773-k-M7-suresh-anaparti"
    }
  ]
}
```

After changes: New parameter ipranges holds the list of ip ranges. Old parameters would be deprecated (kept for backward compatibility).

```
(cloudcmk) > list pods
{
  "count": 1,
  "pod": [
    {
      "allocationstate": "Enabled",
      "endip": [
        "10.0.36.60",
        "10.0.36.69"
      ],
      "forsystemvms": [
        "0",
        "1"
      ],
      "gateway": "10.0.32.1",
      "hasannotations": false,
      "id": "43ffd982-8942-4c9a-88f3-002dc7f5d411",
      "ipranges": [
        {
          "endip": "10.0.36.60",
          "forsystemvms": "0",
          "startip": "10.0.36.41",
          "vlanid": "vlan://untagged"
        },
        {
          "endip": "10.0.36.69",
          "forsystemvms": "1",
          "startip": "10.0.36.67",
          "vlanid": "vlan://untagged"
        }
      ],
      "name": "Pod1",
      "netmask": "255.255.240.0",
      "startip": [
        "10.0.36.41",
        "10.0.36.67"
      ],
      "vlanid": [
        "vlan://untagged",
        "vlan://untagged"
      ],
      "zoneid": "be8e7d3e-2f57-433d-9c93-208949e2ec1d",
      "zonename": "ref-trl-1773-k-M7-suresh-anaparti"
    }
  ]
}
```

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Review by shwstppr — COMMENTED** [review]
I'm not sure if this helps to address the original issue. Moreover, this further complicates it by again changing the listPods API response.
In my opinion, we can just update the description for the `startip` and `endip` params of the response, stating that they will return lists (and not a single IP)

**Comment by sureshanaparti** [comment]
> I'm not sure if this helps to address the original issue. Moreover, this further complicates it by again changing the listPods API response.
> In my opinion, we can just update the description for the `startip` and `endip` params of the response, stating that they will return lists (and not a single IP)

@shwstppr I think, It is better to keep the parameters "startip, endip, vlanid, forsystemvms" as a group, instead maintaining as separate lists and relating these by the list index.

**Comment by sureshanaparti** [comment]
> I'm not sure if this helps to address the original issue. Moreover, this further complicates it by again changing the listPods API response.
> In my opinion, we can just update the description for the `startip` and `endip` params of the response, stating that they will return lists (and not a single IP)

The original issue doesn't make sense as the Pod can hold multiple ip ranges, and I'm (-1) with changing the description. The response then doesn't maintain proper relation between the range parameters, instead these have changed to List from String (I feel, that is not the correct way).

**Comment by shwstppr** [comment]
@sureshanaparti I'm okay with whatever others decide or the _correct_ way is but if the original issue doesn't make sense as you said then this PR should say that it fixes the issue.

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by resmo** [comment]
LGTM, the api response is much clearer now and much easier to adjust on client side.

**Comment by rhtyd** [comment]
@sureshanaparti pl fix conflicts

**Comment by rhtyd** [comment]
@sureshanaparti pl fix conflicts

**Review by nvazquez — APPROVED** [review]
Code LGTM, I'm for removing the deprecated fields on the API response but understand is kept for backward compatibility

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by nvazquez** [comment]
@shwstppr @rhtyd @weizhouapache can you review this one?

**Comment by rhtyd** [comment]
Sure, I'll start but this may need some manual testing too.

**Comment by DaanHoogland** [comment]
> Sure, I'll start but this may need some manual testing too.

why would this need manual testing @rhtyd , the response has been changed and can be verified in an automated test. some automated test can (and should) be updated.

**Comment by rhtyd** [comment]
@DaanHoogland I saw no changes or introduction of a new marvin test and given the automated tests passed, this suggests there are no specific test that consume/rely on the API response - which is why I suggested somebody to manually test the UI/API.

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
Nevermind my last comment, I saw Suresh's before and after API response change is additive - LGTM.

**Comment by DaanHoogland** [comment]
hm, my comment stands though. even trusting Suresh we need some to find how tests that use this and update them.

**Pull request merged**
