### PR TITLE
CLOUDSTACK-10365: Change the "getXXX" boolean-related method names to…

### PR DESCRIPTION
**Pull request by BruceKuiLiu**
… "isXXX".

These boolean-return methods are named as "getXXX".
Other boolean-return methods are named as "isXXX".
Considering there methods will return boolean values, it should be more clear and consistent to rename them as "isXXX".
(rebase #2602)

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@rafaelweingartner @fmaximus we had a discussion about readability vs consistency in #2602. I am allright with this, in spite of my minor remarks there. How bout you guys?
@blueorangutan package

**Comment by rafaelweingartner** [comment]
@DaanHoogland I recall that @fmaximus mentioned some possible problem with the home made JPA implementation we use. If this PR is not breaking anything, let's push it forward. Otherwise, there is not much we can do.

**Comment by DaanHoogland** [comment]
right, let's see, ...
@blueorangutan test

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@BruceKuiLiu sorry to bother again, but can you rebase?

**Comment by BruceKuiLiu** [comment]
@DaanHoogland I am sorry, my remote branch was removed. I rebased it in the new request #2847.

**Comment by DaanHoogland** [comment]
i see @BruceKuiLiu , better keep it till it's merged ;) We are kind of slow here a lot, so no guarantee we won't ask you again.

**Pull request closed without merging**
