### PR TITLE
VR: fix warning Expected X answers while executing SetXXXCommand but Y

### LINKED ISSUE #6757: Warning statement for SetMonitorServiceCommand command sent to VR due to additional answers received
Unnecessary warning statement was seen for SetMonitorServiceCommand command sent to VR (for health checks), as 3 answer sent but one expected:

2022-09-21 12:39:34,773 WARN  [resource.virtualnetwork.VirtualRoutingResource] (agentRequest-Handler-4:null) (logid:d5969a8f) <b>Expected 1 answers while executing SetMonitorServiceCommand but received 3</b>
2022-09-21 12:39:34,775 DEBUG [cloud.agent.Agent] (agentRequest-Handler-4:null) (logid:d5969a8f) Seq 214-1179380152417660442:  { Ans: , MgmtId: 12345, via: 214, Ver: v1, Flags: 10, [{"com.cloud.agent.api.routing.GroupAnswer":{"results":["null - success: Creating file in VR, with ip: a.b.c.d, file: monitor_service.json.1d4987b3-85ef-481a-8d48-33b5b853fa5e","null - success: ","null - success: "],"result":"true","wait":"0","bypassHostMaintenance":"false"}}] }

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VR
~~~

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #6757 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test keepEnv

**Comment by weizhouapache** [comment]
> @weizhouapache how does this occur? i tried to reproduce but couldn´t

@DaanHoogland 
I can find some errors (not only for SetMonitorServiceCommand, but also other network commands) in agent.log
the errors do not exist in management-server.log

for example
```
2023-01-04 08:02:20,597 WARN  [resource.virtualnetwork.VirtualRoutingResource] (agentRequest-Handler-3:null) (logid:3a53f158) Expected 1 answers while executing SetMonitorServiceCommand but received 3
2023-01-04 09:00:17,210 WARN  [resource.virtualnetwork.VirtualRoutingResource] (agentRequest-Handler-4:null) (logid:e0da5128) Expected 1 answers while executing SetupGuestNetworkCommand but received 2
2023-01-04 09:00:20,345 WARN  [resource.virtualnetwork.VirtualRoutingResource] (agentRequest-Handler-4:null) (logid:e0da5128) Expected 1 answers while executing DhcpEntryCommand but received 2
2023-01-04 09:00:20,911 WARN  [resource.virtualnetwork.VirtualRoutingResource] (agentRequest-Handler-1:null) (logid:e0da5128) Expected 1 answers while executing SavePasswordCommand but received 2
2023-01-04 09:00:21,436 WARN  [resource.virtualnetwork.VirtualRoutingResource] (agentRequest-Handler-1:null) (logid:e0da5128) Expected 1 answers while executing VmDataCommand but received 2
```

**Review by rohityadavcloud — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test keepEnv

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test keepEnv

**Review by DaanHoogland — APPROVED** [review]
tested by executing `zgrep "answers while executing" /var/log/cloudstack/agent/agent.log*` on the hosts after a full smoke test run.

**Pull request merged**
