### PR TITLE
server: allow copy cross-zone templates to other zone

### PR DESCRIPTION
**Pull request by ustcweizhou**
### Description

This PR fixes the issue that cross-zone templates cannot be copied to new zone.

steps to reproduce the issue
(1) register a cross-zone template
(2) when it is done, remote it from http server
(3) create a new zone
(4) template cannot be downloaded to new zone, as it has been removed from http server
(5) copy template from first zone to new zone

Expected result: succeed
Actual result: API succeed, but nothing changed, logs: "Template 300  is cross-zone, don't need to copy"

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
right, that has definately had some heads scratching. clgtm

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan test

**Comment by Pearl1594** [comment]
@blueorangutan test

**Review by Pearl1594 — APPROVED** [review]
Verified behavior. LGTM

**Review by rhtyd — APPROVED** [review]

**Pull request merged**
