### PR TITLE
[AGENT] host os accepted if only the first word is defined for the cluster

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR...

Fixes: #7616

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
> @weizhouapache , architecturally I don't whink this is the best solution but it will allow running environments to keep running. I don't know of an example where two different OSses use the same first word in their name, but if that exists, this won't work (i think for our Rocky and Red instances it will work).

@DaanHoogland 
this might work, at least restarting cloudstack-agent should.
when all cloudstack-agent are started, all agent should have the correct Host.OS in host_details

I will test it

another option might be updating existing Host.OS in host_details (mostly rocky/rhel). is alma impacted?

**Comment by DaanHoogland** [comment]
> I will test it

thanks

> another option might be updating existing Host.OS in host_details (mostly rocky/rhel). is alma impacted?

I was thinking of that as well, but we cannot be sure to be complete and correct with this strategy. Rocky and Red make us make assumptions that might not be correct and as you mentioned, I forgot about Alma. This is not a problem btw as it is called "AlmaLinux".

To be sure we would need to check every possible host type that is supported and query "Host.OS" from the host_details tables. Can we be sure about the limits of this?

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test keepEnv

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Review by harikrishna-patnala — APPROVED** [review]
LGTM.

Tried looking for other possible solutions, but this seems to be fair with the existing list of OSes I can think of.

**Review by borisstoyanov — APPROVED** [review]
LGTM

**Pull request merged**
