### PR TITLE
ui: fix dashboard limit format

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

An undefined variable `item` was used.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):
Before:
image

After:
image

### CODE REVIEW

**Review by rohityadavcloud — APPROVED** [review]
Didn't test but LGTM

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Comment by sureshanaparti** [comment]
@blueorangutan ui

**Review by vishesh92 — APPROVED** [review]
clgtm

**Review by rohityadavcloud — APPROVED** [review]
Didn’t test though

**Comment by DaanHoogland** [comment]
@shwstppr , I see no difference between your before and after pictures. Can you highlight what has changed, please?

**Comment by shwstppr** [comment]
@DaanHoogland there is a difference in before and after screens. There is no percentage label for unlimited resource types (check Instances label)

More importantly in certain scenarios, the code itself is incorrect using the wrong variables. It may log an error similar to that reported in #9045 in certain cases while trying to find `undefinedlimit` property
https://private-user-images.githubusercontent.com/110984295/328852853-5ca04e09-eaa8-4466-bc2d-5df59fad1973.png

**Pull request merged**
