### PR TITLE
CLOUDSTACK-8964: Can't create template or volume from snapshot on KVM

### PR DESCRIPTION
**Pull request by ustcweizhou**

### CODE REVIEW

**Comment by DaanHoogland** [comment]
Wei, this code looks sensible but can you ad a small explenation as it is actually two small fixes. It is one a the test in a bunch PRs to me.
The jenkins failure is due to the illegal state bug in hudson code that is byting us at times, not in this PR.

**Comment by ustcweizhou** [comment]
Daan, I just edited the commit message to describe the issue.
This two issue looks small, but the functions are called by many other functions. hence it may have large impact on other processes.

**Comment by karuturi** [comment]
after excluding ovm3 hypervisor using the "hypervisor.gurus.exclude" global setting, template creation from snapshot on kvm is successful. 
I dont think we should do the change in 096f7104045d20db5e6e425122222ada39493681 
Ovm3 hypervisor guru should be fixed https://github.com/apache/cloudstack/blob/master/plugins/hypervisors/ovm3/src/main/java/com/cloud/hypervisor/ovm3/resources/Ovm3HypervisorGuru.java#L110

**Comment by ustcweizhou** [comment]
@karuturi what you did is a workaround for KVM.
The request on KVM should not be processed by ovm3hypervisorguru, but KvmHypervisorGuru.

**Comment by NuxRo** [comment]
BTW excluding ovm3 in hypervisor.gurus.exclude doesn't fix anything for me. The problem remains.
I'll re-build with Wei's patches and test.

**Comment by karuturi** [comment]
Which why I think the fix should be in ovm3hypervisorguru

-----Original Message-----

**Comment by karuturi** [comment]
What value did you give? It should be ovm3guru

-----Original Message-----

**Comment by NuxRo** [comment]
I used ovm3 initially and now I tried with ovm3guru, no luck, both operations fail (create volume, create template).

**Comment by karuturi** [comment]
@NuxRo This is the exact value I used and which worked for me "Ovm3Guru" 
Just a check, did you restart the Management Server after changing the config?

**Comment by NuxRo** [comment]
Ovm3Guru made a difference! I could create a template from the snapshot, however not a volume.
Here's the error I got when trying to create a volume: 
http://fpaste.org/281894/45433338/raw/

**Comment by ustcweizhou** [comment]
@NuxRo Can you check if the original volume is removed ? This is what my second commit wants to fix.

**Comment by NuxRo** [comment]
Wei,

These operations are done on a snapshot of a ROOT volume that does not exist any more.

That VM has long been deleted, but the snapshot is OK, on the secondary storage.

**Comment by NuxRo** [comment]
So to clarify:

FAIL - create volume from snapshot whose original volume has been deleted
PASS - create volume from snapshot whose original volume has not been deleted

PASS - Creating a template from a snapshot whose original volume has been deleted used to fail as well, but excluding Ovm3Guru in hypervisor.gurus.exclude fixed that.

**Comment by snuf** [comment]
karuturi yep you're right! looking at the code something went wrong with lifting it over.

**Comment by DaanHoogland** [comment]
Ran 40 tests in 7009.763s

FAILED (errors=3)
these are the lb tests that have been failing constantly. 
as for the load balance tests:
----------------------------------------------------------------------
Ran 11 tests in 7473.971s

OK

haven't seen the loadbalancer test pass while the lb tests in the vpc suite fail before.

Not sure what need s fixing. but trusting @snuf and @karuturi   enough to not give an LGTM as is

**Comment by snuf** [comment]
@karuturi @NuxRo @ustcweizhou could you please check [#962](https://github.com/apache/cloudstack/pull/962) for the details as #954 could then be closed and #962 could be merged if all LGTY ?

**Comment by NuxRo** [comment]
I can confirm Wei's modifications fixes my problem.
Both operations (create tmpl and create vol from snapshot) succeed with RPMs built from https://github.com/ustcweizhou/cloudstack/tree/CLOUDSTACK-8964 

Not sure how we should proceed next, but for now I am happy functionality is restored.

**Comment by remibergsma** [comment]
@NuxRo Thanks! I'll count it as a LGTY? :-)

**Comment by NuxRo** [comment]
Count it, but @karuturi gave me the impression she was going for a different kind of fix, on the ovm3 side of things, might want to check with her.

**Comment by remibergsma** [comment]
@NuxRo I agree, I want a solution that you, @snuf and @karuturi agree on :-)

**Comment by snuf** [comment]
@NuxRo @remi it works like a charm and also prevents little accidents from happening. The interesting thing is that the XenserverGuru.java contains the exact same code albeit with a small difference form the Ovm3HypervisorGuru.java code *cough*. Both don't check if it's actually being called from the right hypervisor, the fix @ustcweizhou did prevents this.

**Comment by snuf** [comment]
@Nuxro @remibergsma @karuturi by adding a simple log line to the XenServerGuru.java you get the following when doing a snap to vol and a snap to temp:
'2015-10-23 19:53:42,226 DEBUG [c.c.h.o.r.Ovm3HypervisorGuru] (API-Job-Executor-1:ctx-636e6088 job-36 ctx-d57104a0) getCommandHostDelegation: class org.apache.cloudstack.
storage.command.CopyCommand'
'2015-10-23 19:53:42,226 DEBUG [c.c.h.XenServerGuru] (API-Job-Executor-1:ctx-636e6088 job-36 ctx-d57104a0) getCommandHostDelegation: class org.apache.cloudstack.storage.c
ommand.CopyCommand'

**Comment by remibergsma** [comment]
@snuf, if I understand correctly this PR only calls the Guru of whatever hypervisor you use, and doesn't call the others. I can remember a certain outage that was caused by interference of another Guru than the one that was being used. If this is the case, I say :+1: Are there any drawbacks of such a change?

**Comment by snuf** [comment]
@remibergsma not for the HypervisorGuru, as they are really specific, It does however conflict with the original idea behind the Gurus if I'm not mistaken, as a Guru is well ehr, a Guru.

**Comment by borisroman** [comment]
@snuf @remibergsma I like this idea. I actually think we should have this kind behavior everywhere...

Here's another example of non-deterministic behavior:
https://github.com/apache/cloudstack/blob/fddf59f8852000c5f3905197508d4cd129f6cc1b/services/secondary-storage/server/src/org/apache/cloudstack/storage/template/DownloadManagerImpl.java#L474

It loops over all processors and the first one to return a non null answer wins!

**Comment by jburwell** [comment]
This seems like a pragmatic fix for 4.6.  In the long term, I am concerns that the method provides an inaccurate view of system state.  When no answer is found, it says that the passed host processed it when, in fact, it was not processed.  Since this problem is existing, we can address it post-4.6.

Additionally, I don't see any reason why this fixed should be two commits.  It would be nice to see it squashed to reduce clutter on the master branch log.

**Comment by borisroman** [comment]
@jburwell I think it should be 2 commits... They fix 2 different things. The first fixes the Guru issue, while the second one makes it possible to create snapshots from removed volumes, right?

**Comment by jburwell** [comment]
@borisroman it fixes one ticket -- it should be one commit.  In the grand scheme of the master log, the distinction is not valuable -- it only obfuscates the intention.

**Comment by ustcweizhou** [comment]
@borisroman yes, you are right. Should I seperate this PR to two ?

**Comment by borisroman** [comment]
@ustcweizhou You may do so! Then also separate the ticket.

**Comment by ustcweizhou** [comment]
@borisroman done. #954 and #976

**Comment by remibergsma** [comment]
FYI: Had been running tests but now that the PR changed I restarted. Will report results when done, probably somewhere during the weekend.

**Comment by remibergsma** [comment]
LGTM, based on a set of tests that I run on this branch (on a KVM cluster):

```
nosetests --with-marvin --marvin-config=${marvinCfg} -s -a tags=advanced,required_hardware=true \
component/test_vpc_redundant.py \
component/test_routers_iptables_default_policy.py \
component/test_routers_network_ops.py \
component/test_vpc_router_nics.py \
smoke/test_loadbalance.py \
smoke/test_internal_lb.py \
smoke/test_ssvm.py

```

Result:

```
[root@cs2 MarvinLogs]# less test_ssvm_S1LNSF/results.txt 
Create a redundant VPC with two networks with two VMs in each network ... === TestName: test_01_create_redundant_VPC_2tiers_4VMs_4IPs_4PF_ACL | Status : SUCCESS ===
ok
Create a redundant VPC with two networks with two VMs in each network and check default routes ... === TestName: test_02_redundant_VPC_default_routes | Status : SUCCESS ===
ok
Test iptables default INPUT/FORWARD policy on RouterVM ... === TestName: test_02_routervm_iptables_policies | Status : SUCCESS ===
ok
Test iptables default INPUT/FORWARD policies on VPC router ... === TestName: test_01_single_VPC_iptables_policies | Status : SUCCESS ===
ok
Stop existing router, add a PF rule and check we can access the VM ... === TestName: test_isolate_network_FW_PF_default_routes | Status : SUCCESS ===
ok
Test redundant router internals ... === TestName: test_RVR_Network_FW_PF_SSH_default_routes | Status : SUCCESS ===
ok
Create a VPC with two networks with one VM in each network and test nics after destroy ... === TestName: test_01_VPC_nics_after_destroy | Status : SUCCESS ===
ok
Create a VPC with two networks with one VM in each network and test default routes ... === TestName: test_02_VPC_default_routes | Status : SUCCESS ===
ok
Test to create Load balancing rule with source NAT ... === TestName: test_01_create_lb_rule_src_nat | Status : SUCCESS ===
ok
Test to create Load balancing rule with non source NAT ... === TestName: test_02_create_lb_rule_non_nat | Status : SUCCESS ===
ok
Test for assign & removing load balancing rule ... === TestName: test_assign_and_removal_lb | Status : SUCCESS ===
ok
Test to verify access to loadbalancer haproxy admin stats page ... === TestName: test02_internallb_haproxy_stats_on_all_interfaces | Status : SUCCESS ===
ok
Test create, assign, remove of an Internal LB with roundrobin http traffic to 3 vm's ... === TestName: test_01_internallb_roundrobin_1VPC_3VM_HTTP_port80 | Status : SUCCESS ===
ok
Test SSVM Internals ... === TestName: test_03_ssvm_internals | Status : SUCCESS ===
ok
Test CPVM Internals ... === TestName: test_04_cpvm_internals | Status : SUCCESS ===
ok
Test stop SSVM ... === TestName: test_05_stop_ssvm | Status : SUCCESS ===
ok
Test stop CPVM ... === TestName: test_06_stop_cpvm | Status : SUCCESS ===
ok
Test reboot SSVM ... === TestName: test_07_reboot_ssvm | Status : SUCCESS ===
ok
Test reboot CPVM ... === TestName: test_08_reboot_cpvm | Status : SUCCESS ===
ok
Test destroy SSVM ... === TestName: test_09_destroy_ssvm | Status : SUCCESS ===
ok
Test destroy CPVM ... === TestName: test_10_destroy_cpvm | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 21 tests in 10645.291s

OK

```

And:

```
nosetests --with-marvin --marvin-config=${marvinCfg} -s -a tags=advanced,required_hardware=false \
smoke/test_routers.py \
smoke/test_network_acl.py \
smoke/test_privategw_acl.py \
smoke/test_reset_vm_on_reboot.py \
smoke/test_vm_life_cycle.py \
smoke/test_vpc_vpn.py \
smoke/test_service_offerings.py \
component/test_vpc_offerings.py \
component/test_vpc_routers.py
```
Result:

```
Test router internal advanced zone ... === TestName: test_02_router_internal_adv | Status : SUCCESS ===
ok
Test restart network ... === TestName: test_03_restart_network_cleanup | Status : SUCCESS ===
ok
Test router basic setup ... === TestName: test_05_router_basic | Status : SUCCESS ===
ok
Test router advanced setup ... === TestName: test_06_router_advanced | Status : SUCCESS ===
ok
Test stop router ... === TestName: test_07_stop_router | Status : SUCCESS ===
ok
Test start router ... === TestName: test_08_start_router | Status : SUCCESS ===
ok
Test reboot router ... === TestName: test_09_reboot_router | Status : SUCCESS ===
ok
test_privategw_acl (integration.smoke.test_privategw_acl.TestPrivateGwACL) ... === TestName: test_privategw_acl | Status : SUCCESS ===
ok
Test reset virtual machine on reboot ... === TestName: test_01_reset_vm_on_reboot | Status : SUCCESS ===
ok
Test advanced zone virtual router ... === TestName: test_advZoneVirtualRouter | Status : SUCCESS ===
ok
Test Deploy Virtual Machine ... === TestName: test_deploy_vm | Status : SUCCESS ===
ok
Test Multiple Deploy Virtual Machine ... === TestName: test_deploy_vm_multiple | Status : SUCCESS ===
ok
Test Stop Virtual Machine ... === TestName: test_01_stop_vm | Status : SUCCESS ===
ok
Test Start Virtual Machine ... === TestName: test_02_start_vm | Status : SUCCESS ===
ok
Test Reboot Virtual Machine ... === TestName: test_03_reboot_vm | Status : SUCCESS ===
ok
Test destroy Virtual Machine ... === TestName: test_06_destroy_vm | Status : SUCCESS ===
ok
Test recover Virtual Machine ... === TestName: test_07_restore_vm | Status : SUCCESS ===
ok
Test migrate VM ... === TestName: test_08_migrate_vm | Status : SUCCESS ===
ok
Test destroy(expunge) Virtual Machine ... === TestName: test_09_expunge_vm | Status : SUCCESS ===
ok
Test Remote Access VPN in VPC ... === TestName: test_vpc_remote_access_vpn | Status : SUCCESS ===
ok
Test VPN in VPC ... === TestName: test_vpc_site2site_vpn | Status : SUCCESS ===
ok
Test to create service offering ... === TestName: test_01_create_service_offering | Status : SUCCESS ===
ok
Test to update existing service offering ... === TestName: test_02_edit_service_offering | Status : SUCCESS ===
ok
Test to delete service offering ... === TestName: test_03_delete_service_offering | Status : SUCCESS ===
ok
Test create VPC offering ... === TestName: test_01_create_vpc_offering | Status : SUCCESS ===
ok
Test VPC offering without load balancing service ... === TestName: test_03_vpc_off_without_lb | Status : EXCEPTION ===
ERROR
Test VPC offering without static NAT service ... === TestName: test_04_vpc_off_without_static_nat | Status : EXCEPTION ===
ERROR
Test VPC offering without port forwarding service ... === TestName: test_05_vpc_off_without_pf | Status : EXCEPTION ===
ERROR
Test VPC offering with invalid services ... === TestName: test_06_vpc_off_invalid_services | Status : SUCCESS ===
ok
Test update VPC offering ... === TestName: test_07_update_vpc_off | Status : SUCCESS ===
ok
Test list VPC offering ... === TestName: test_08_list_vpc_off | Status : SUCCESS ===
ok
test_09_create_redundant_vpc_offering (integration.component.test_vpc_offerings.TestVPCOffering) ... === TestName: test_09_create_redundant_vpc_offering | Status : SUCCESS ===
ok
Test start/stop of router after addition of one guest network ... === TestName: test_01_start_stop_router_after_addition_of_one_guest_network | Status : SUCCESS ===
ok
Test reboot of router after addition of one guest network ... === TestName: test_02_reboot_router_after_addition_of_one_guest_network | Status : SUCCESS ===
ok
Test to change service offering of router after addition of one guest network ... === TestName: test_04_chg_srv_off_router_after_addition_of_one_guest_network | Status : SUCCESS ===
ok
Test destroy of router after addition of one guest network ... === TestName: test_05_destroy_router_after_addition_of_one_guest_network | Status : SUCCESS ===
ok
Test to stop and start router after creation of VPC ... === TestName: test_01_stop_start_router_after_creating_vpc | Status : SUCCESS ===
ok
Test to reboot the router after creating a VPC ... === TestName: test_02_reboot_router_after_creating_vpc | Status : SUCCESS ===
ok
Tests to change service offering of the Router after ... === TestName: test_04_change_service_offerring_vpc | Status : SUCCESS ===
ok
Test to destroy the router after creating a VPC ... === TestName: test_05_destroy_router_after_creating_vpc | Status : SUCCESS ===
ok
----------------------------------------------------------------------
Ran 40 tests in 8394.478s

FAILED (errors=3)
```

The 3 errors are due to cleanup problems that are were broken on master when this was branched off. It was fixed in PR #967.

@karuturi Can you please also review this again and let us know if you agree? Thanks!

**Comment by karuturi** [comment]
I was concerned the code change is against the initial design and we may be doing it without understanding all the implications. But, since we dont have any better solution and the current set of tests we have are positive with the change, I would :+1:  this. Though, we should keep in mind that this may lead to some regressions like CLOUDSTACK-3681 or CLOUDSTACK-6478

@mike-tutkowski Can you also test if the vmware snapshot-from-template issue you faced is fixed by this?

@ustcweizhou Thanks for fixing it very quickly. A little description would have saved me sometime in trying to find the root cause :)

**Comment by karuturi** [comment]
copy-pasting mike's response from email ( http://markmail.org/message/bptis5kitr2chqcn ). looks like its still not working for him with vmware-managed storage
> 4.5 should be OK. I tested this kind of stuff back then and didn't notice
> anything.
> 
> Let me make sure I'm running with the most recent system VM template for
> 4.6.
> 
> Prior to using your PR, I was not able to deploy a VM to local storage on
> VMware.
> 
> With your PR, I was able to perform such a deployment, but I still saw
> exceptions in the console.
> Both with and without your PR, I was not able to deploy a VM using managed
> storage with VMware. The only way I can get this to work right now is if I
> set a breakpoint in VMwareGuru and make sure the CopyCommand is sent to the
> VMware server resource inside of the management server (as opposed to that
> command going to the SSVM).

**Comment by remibergsma** [comment]
Just talked to @karuturi and we think we should merge this now and look into the remaining VMware issue (as reported bu @mike-tutkowski) as a separate issue. Can you file an issue with details please, Mike?

**Comment by remibergsma** [comment]
OK @mike-tutkowski thanks! I'll merge this now so you can build it from master. Please let us know if you still have issues, as I'd love to resolve those as well.

**Comment by mike-tutkowski** [comment]
Once I re-build my CS env in the morning, I'll run through a bunch of tests
in the morning and afternoon and get back to you.

On Sunday, October 25, 2015, Remi Bergsma <notifications@github.com> wrote:

> OK @mike-tutkowski <https://github.com/mike-tutkowski> thanks! I'll merge
> this now so you can build it from master. Please let us know if you still
> have issues, as I'd love to resolve those as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/cloudstack/pull/954#issuecomment-151028340>.
>


-- 
*Mike Tutkowski*
*Senior CloudStack Developer, SolidFire Inc.*
e: mike.tutkowski@solidfire.com
o: 303.746.7302
Advancing the way the world uses the cloud
<http://solidfire.com/solution/overview/?video=play>*™*

**Comment by mike-tutkowski** [comment]
Hi Remi,

I have rebuilt my entire 4.6 CS environment from scratch and re-run my
tests.

I'm happy to report that I no longer see the issues I was seeing earlier.
I'm able to successfully deploy a VM on ESXi both on local and managed
storage now.

Talk to you later!
Mike

On Sun, Oct 25, 2015 at 11:36 PM, Mike Tutkowski <
mike.tutkowski@solidfire.com> wrote:

> Once I re-build my CS env in the morning, I'll run through a bunch of
> tests in the morning and afternoon and get back to you.
>
>
> On Sunday, October 25, 2015, Remi Bergsma <notifications@github.com>
> wrote:
>
>> OK @mike-tutkowski <https://github.com/mike-tutkowski> thanks! I'll
>> merge this now so you can build it from master. Please let us know if you
>> still have issues, as I'd love to resolve those as well.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/apache/cloudstack/pull/954#issuecomment-151028340>.
>>
>
>
> --
> *Mike Tutkowski*
> *Senior CloudStack Developer, SolidFire Inc.*
> e: mike.tutkowski@solidfire.com
> o: 303.746.7302
> Advancing the way the world uses the cloud
> <http://solidfire.com/solution/overview/?video=play>*™*
>
>


-- 
*Mike Tutkowski*
*Senior CloudStack Developer, SolidFire Inc.*
e: mike.tutkowski@solidfire.com
o: 303.746.7302
Advancing the way the world uses the cloud
<http://solidfire.com/solution/overview/?video=play>*™*

**Pull request merged**
