### PR TITLE
BUG-ID: CLOUDSTACK-8849: Usage job should stop usage generation in ca…

### PR DESCRIPTION
**Pull request by yvsubhash**
…se of any exception

### CODE REVIEW

**Comment by rodrigo93** [comment]
Hi @yvsubhash, could you make a Jira?
Sorry to ask you, but, why did you remove the tries and catches? It should throw exceptions if that part of the code can be executed, should it not? How did you test it?

**Comment by rhtyd** [comment]
@yvsubhash please rebase against latest master and push -f, update on status of your PR

We'll need more information on why we should ignore/stop usage generation, in case we don't handle exception this will not generate usage for other kinds of resources

**Comment by bvbharatk** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 123
 Hypervisor xenserver
 NetworkType Advanced
 Passed=73
 Failed=0
 Skipped=3

_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/yj3wnzbceo9uef2/AAB6u-Iap-xztdm6jHX9SjPja?dl=0


**Failed tests:**

**Skipped tests:**
test_vm_nic_adapter_vmxnet3
test_static_role_account_acls
test_deploy_vgpu_enabled_vm

**Passed test suits:**
test_deploy_vm_with_userdata.py
test_affinity_groups_projects.py
test_portable_publicip.py
test_vpc_vpn.py
test_over_provisioning.py
test_global_settings.py
test_scale_vm.py
test_service_offerings.py
test_routers_iptables_default_policy.py
test_routers.py
test_reset_vm_on_reboot.py
test_snapshots.py
test_deploy_vms_with_varied_deploymentplanners.py
test_login.py
test_list_ids_parameter.py
test_public_ip_range.py
test_multipleips_per_nic.py
test_regions.py
test_affinity_groups.py
test_network_acl.py
test_pvlan.py
test_volumes.py
test_nic.py
test_deploy_vm_root_resize.py
test_resource_detail.py
test_secondary_storage.py
test_vm_life_cycle.py
test_disk_offerings.py

**Comment by bvbharatk** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 176
 Hypervisor xenserver
 NetworkType Advanced
 Passed=73
 Failed=0
 Skipped=3

_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/yj3wnzbceo9uef2/AAB6u-Iap-xztdm6jHX9SjPja?dl=0


**Failed tests:**

**Skipped tests:**
test_vm_nic_adapter_vmxnet3
test_static_role_account_acls
test_deploy_vgpu_enabled_vm

**Passed test suits:**
test_deploy_vm_with_userdata.py
test_affinity_groups_projects.py
test_portable_publicip.py
test_vpc_vpn.py
test_over_provisioning.py
test_global_settings.py
test_scale_vm.py
test_service_offerings.py
test_routers_iptables_default_policy.py
test_routers.py
test_reset_vm_on_reboot.py
test_snapshots.py
test_deploy_vms_with_varied_deploymentplanners.py
test_login.py
test_list_ids_parameter.py
test_public_ip_range.py
test_multipleips_per_nic.py
test_regions.py
test_affinity_groups.py
test_network_acl.py
test_pvlan.py
test_volumes.py
test_nic.py
test_deploy_vm_root_resize.py
test_resource_detail.py
test_secondary_storage.py
test_vm_life_cycle.py
test_disk_offerings.py

**Comment by yvsubhash** [comment]
@rodrigo93 
Exception in this part of code should stop further usage generation. Catching it here is suppressing the exception. The fix is tested manually by simulating the scenario
@rhtyd 
it is rebased to 4.8

**Comment by ustcweizhou** [comment]
@yvsubhash  Sorry, I disagree with you. The usage server should not stop even an exception is raised.

**Comment by yvsubhash** [comment]
@ustcweizhou  In case we continue with usage generation, we may miss out some of the records which actually resulted in exception and would in turn lead to wrong usage numbers. stopping after the exception can help in running the usage server once the errors are fixed can result in proper usage generation. May I know the reason for you to think usage generation should not be stopped

**Comment by ustcweizhou** [comment]
@yvsubhash yes, we will miss some records if we skip the exception, but we will miss all others records if we stop the usage server. For me, it is important that usage server will still be running in case of exception.

**Comment by yvsubhash** [comment]
@ustcweizhou By stopping the usage server, we can fix the records and continue in the next run. If we simply skip we wont come to know abt the records with errors.

**Comment by yvsubhash** [comment]
@ustcweizhou Do you still have some queries on it?

**Comment by ustcweizhou** [comment]
@yvsubhash Sorry I still disagree with it.

**Comment by yvsubhash** [comment]
Closing this PR

**Pull request closed without merging**
