### PR TITLE
systemd: fix services to allow TLS configurations via java.security.ciphers

### LINKED ISSUE #3140: CloudStack management java.security.ciphers has no effect on JVM process
The `/etc/cloudstack/management/java.security.ciphers` has no effect on the list of disabled TLS algorithms in the management server JVM process. For example, on port 8250 TLS1.0, 1.1 are still allowed/supported protocols. (Tested using `openssl s_client -connect localhost:8250 -tls1`)

However, workaround exists to configure `jdk.tls.disabledAlgorithms` in the global security file: `$JRE_HOME/lib/security/java.security`.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Management Server
~~~

##### CLOUDSTACK VERSION

~~~
4.11
~~~

### PR DESCRIPTION
**Pull request by rhtyd**
This fixes the management server and systemd services to allow the
java.security.ciphers file to configure disabled TLS protocols and
algorithms. This also cleans up systemd service files for agent and
usage server, and deprecates use of `jsvc` when systemd can be used
directly.

This fixes #3140

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

Deploy systemd based environments using CentOS7 and Ubuntu 18.04. Verified first that TLS settings has no effect, then with the changes applied found in both usage, kvm agent and management server that systemd service works OK and TLS was configurable again.

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@GabrielBrascher please consider including this in 4.12.0.0 as this fixes the TLS configuration security issue.

**Comment by rhtyd** [comment]
Forward merging-note: master does not support ubuntu 14.04 and older, therefore jsvc dependency can be removed from master's `debian/`.

**Comment by GabrielBrascher** [comment]
We are on tight schedule for 4.12; thus, I am trying to keep as short as possible the list of PRs aiming the 4.12 release.

Considering this; @rhtyd do you think that this PR is a blocker for 4.12? If so, could you please register this PR as a blocker on the mailing list thread '[PROPOSE] RM for 4.12'? Thanks!

**Comment by rhtyd** [comment]
Yes @GabrielBrascher because the tls disabled settings is no longer honoured, it's a security issue. Will propose on the list.

**Pull request merged**
