### PR TITLE
[4.8] Latest health test run

### PR DESCRIPTION
**Pull request by rhtyd**
Dummy PR to trigger tests on 4.8 branch

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@murali-reddy can you check why `test_router_dhcp_opts (test_router_dhcphosts.py)` failed, this test is failing intermittently on 4.9, master as well.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by borisstoyanov** [comment]
Xen and KVM test runs seem not have introduced any new failure, 
regarding vmware:
test_temaplate errors seem to be caused by a timeout issue 
`com.cloud.exception.OperationTimedoutException: Commands 241787004994453513 to Host 5 timed out after 1800'`
test_snapshots - failed to create snapshot due to internal error. 
test_iso - `Unable to create a link for entity at template/tmpl/16/206/206-16-f0a23a90-3c64-3bf3-8495-7dd3f83f59ec.iso on ssvm,No remote endpoint to send command, check if host or ssvm is down?'` maybe resource was down at that point for some reason...

I'll deploy a test bed to verify them manually now. 
cc: @rhtyd

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Pull request closed without merging**
