### PR TITLE
CLOUDSTACK-8717: Failed to start instance after restoring the running instance 

### PR DESCRIPTION
**Pull request by pritisarap12**
Changing PR title and commit message 
In continuation with PR #1411  and  #667

### CODE REVIEW

**Comment by sanju1010** [comment]
LGTM based on PR #667

**Comment by pritisarap12** [comment]
@DaanHoogland  Please give one LGTM to close the PR as it is just the change in commit message and PR title .

**Comment by DaanHoogland** [comment]
please ask @remibergsma and @runseb , as they had opinions on it before.

**Comment by pritisarap12** [comment]
@remibergsma and @runseb  Please give one LGTM to close the PR as it is just the change in commit message and PR title .

**Pull request merged**
