### PR TITLE
Remove SNI option in _run.sh, as it is correct as default.

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR...

Fixes: #9962 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by rohityadavcloud — APPROVED** [review]

**Comment by DaanHoogland** [comment]
> [SF] Trillian test result (tid-11840) Environment: kvm-ol8 (x2), Advanced Networking with Mgmt server ol8 Total time taken: 52094 seconds Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr10028-t11840-kvm-ol8.zip Smoke tests completed. 129 look OK, 4 have errors, 0 did not run Only failed and skipped tests results shown below:
> Test 	Result 	Time (s) 	Test File
> test_02_list_cpvm_vm 	`Failure` 	0.05 	test_ssvm.py
> test_04_cpvm_internals 	`Failure` 	0.05 	test_ssvm.py
> test_01_secure_vm_migration 	`Error` 	134.41 	test_vm_life_cycle.py
> test_01_secure_vm_migration 	`Error` 	134.41 	test_vm_life_cycle.py
> test_06_download_detached_volume 	`Failure` 	436.36 	test_volumes.py
> test_01_redundant_vpc_site2site_vpn 	`Failure` 	421.60 	test_vpc_vpn.py

some of these errors seem completely unrelated and some might be, re-running for comparison

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
test_01_secure_vm_migration fails as "Unable to deploy the VM as the host: ol8.localdomain is not in the right state" is consistent, however I am not sure if it is related as I have seen this error in other PRs as well ... needs investigation.

**Comment by weizhouapache** [comment]
> test_01_secure_vm_migration fails as "Unable to deploy the VM as the host: ol8.localdomain is not in the right state" is consistent, however I am not sure if it is related as I have seen this error in other PRs as well ... needs investigation.

@DaanHoogland 
seems unrelated. 

I recall we have faced the issue before
```
2024-12-05 19:22:41,560 DEBUG [c.c.h.Status] (AgentConnectTaskPool-13:ctx-1c122273) (logid:0523be08) Unable to update host for event:Ready. Name=ol8.localdomain; New=[status=Up:msid=null:lastpinged=1692799264]; Old=[status=Connecting:msid=null:lastpinged=1692799264]; DB=[status=Connecting:msid=32987513095075:lastpinged=1692799259:old update count=45]
2024-12-05 19:22:41,561 INFO  [c.c.u.e.CSExceptionErrorCode] (AgentConnectTaskPool-15:ctx-b814e2d3) (logid:b85f4adb) Could not find exception: com.cloud.exception.ConnectionException in error code list for exceptions
2024-12-05 19:22:41,561 DEBUG [c.c.a.m.ClusteredAgentManagerImpl] (AgentTaskPool-9:ctx-d2c55a62) (logid:315eb3a2) Notifying other nodes of to disconnect
2024-12-05 19:22:41,562 DEBUG [c.c.a.m.AgentManagerImpl] (AgentConnectTaskPool-15:ctx-b814e2d3) (logid:b85f4adb) Failed to handle host connection:
com.cloud.exception.ConnectionException: Unable to acquire lock on host 1922ce9f-4d1d-453e-bf1f-4676592379a4
    at com.cloud.agent.manager.AgentManagerImpl.sendReadyAndGetAttache(AgentManagerImpl.java:1155)
    at com.cloud.agent.manager.AgentManagerImpl.handleConnectedAgent(AgentManagerImpl.java:1168)
    at com.cloud.agent.manager.AgentManagerImpl$HandleAgentConnectTask.runInContext(AgentManagerImpl.java:1252)
    at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:48)
    at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
    at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
    at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
    at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:45)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)
```

cc @vishesh92

**Comment by DaanHoogland** [comment]
ok @weizhouapache @vishesh92 do we merge this and create a new issue for this?

> > test_01_secure_vm_migration fails as "Unable to deploy the VM as the host: ol8.localdomain is not in the right state" is consistent, however I am not sure if it is related as I have seen this error in other PRs as well ... needs investigation.
> 
> @DaanHoogland seems unrelated.
> 
> I recall we have faced the issue before
> 
> ```
> 2024-12-05 19:22:41,560 DEBUG [c.c.h.Status] (AgentConnectTaskPool-13:ctx-1c122273) (logid:0523be08) Unable to update host for event:Ready. Name=ol8.localdomain; New=[status=Up:msid=null:lastpinged=1692799264]; Old=[status=Connecting:msid=null:lastpinged=1692799264]; DB=[status=Connecting:msid=32987513095075:lastpinged=1692799259:old update count=45]
> 2024-12-05 19:22:41,561 INFO  [c.c.u.e.CSExceptionErrorCode] (AgentConnectTaskPool-15:ctx-b814e2d3) (logid:b85f4adb) Could not find exception: com.cloud.exception.ConnectionException in error code list for exceptions
> 2024-12-05 19:22:41,561 DEBUG [c.c.a.m.ClusteredAgentManagerImpl] (AgentTaskPool-9:ctx-d2c55a62) (logid:315eb3a2) Notifying other nodes of to disconnect
> 2024-12-05 19:22:41,562 DEBUG [c.c.a.m.AgentManagerImpl] (AgentConnectTaskPool-15:ctx-b814e2d3) (logid:b85f4adb) Failed to handle host connection:
> com.cloud.exception.ConnectionException: Unable to acquire lock on host 1922ce9f-4d1d-453e-bf1f-4676592379a4
>     at com.cloud.agent.manager.AgentManagerImpl.sendReadyAndGetAttache(AgentManagerImpl.java:1155)
>     at com.cloud.agent.manager.AgentManagerImpl.handleConnectedAgent(AgentManagerImpl.java:1168)
>     at com.cloud.agent.manager.AgentManagerImpl$HandleAgentConnectTask.runInContext(AgentManagerImpl.java:1252)
>     at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:48)
>     at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
>     at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
>     at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
>     at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:45)
>     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>     at java.base/java.lang.Thread.run(Thread.java:829)
> ```
> 
> cc @vishesh92

**Comment by weizhouapache** [comment]
> ok @weizhouapache @vishesh92 do we merge this and create a new issue for this?
> 
> > >

I think we can merge

**Comment by DaanHoogland** [comment]
thanks @weizhouapache merged. I will keep an I on the HealthCheck PR for this one.

**Pull request merged**
