### PR TITLE
UI - Deploy VM with params from the template, iso, network pages

### PR DESCRIPTION
**Pull request by utchoang**
### Description

This PR fixes https://github.com/apache/cloudstack/issues/5639

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by rhtyd** [comment]
I think the specific parameter should be passed to the url and be picked up by the form.

**Comment by utchoang** [comment]
@rhtyd Will now pass the template id, network id on the URL, and will auto-select it on the form.

**Comment by rhtyd** [comment]
@blueorangutan ui

**Comment by sureshanaparti** [comment]
@blueorangutan ui

**Review by rohityadavcloud — COMMENTED** [review]
LGTM, but needs testing

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by sureshanaparti** [comment]
@blueorangutan ui

**Comment by rohityadavcloud** [comment]
@blueorangutan ui

**Comment by sureshanaparti** [comment]
@blueorangutan ui

**Comment by sureshanaparti** [comment]
@blueorangutan ui

**Comment by sureshanaparti** [comment]
Verified deploy VM from template and network. LGTM.

**Review by sureshanaparti — APPROVED** [review]

**Review by weizhouapache — APPROVED** [review]
tested ok. thanks for fixing.

**Pull request merged**
