### PR TITLE
engine/schema: fix findActiveAccountById in AccountDaoImpl.java

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes an issue with findActiveAccountById in AccountDaoImpl.java

This method is used in some processes. The impact is unknown.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
cc @weizhouapache pl check for failures, I'll rekick pkging 
@blueorangutan package

**Review by sureshanaparti — APPROVED** [review]
code LGTM

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@weizhouapache code looks ok, but what is the sense of searching for a bunch of fields *and* the id. The id is unique so this search makes no sense to me. Do you know how it is used and why it is a bug there?

**Comment by weizhouapache** [comment]
> @weizhouapache code looks ok, but what is the sense of searching for a bunch of fields _and_ the id. The id is unique so this search makes no sense to me. Do you know how it is used and why it is a bug there?

@DaanHoogland 
as I said in description, the issue is with findActiveAccountById

https://github.com/apache/cloudstack/blob/85373e62191ce18b9d968d366661d3e2efa5909d/engine/schema/src/main/java/com/cloud/user/dao/AccountDaoImpl.java#L199-L203

this method search records by id, but "id" is not supported in AllFieldsSearch.
therefore the result is same as (id/accountid is ignored)

```
    @Override
    public Account findActiveAccountById(Long accountId, Long domainId) {
        SearchCriteria<AccountVO> sc = AllFieldsSearch.create();
        sc.setParameters("domainId", domainId);
        return findOneBy(sc);
    }
```

**Comment by DaanHoogland** [comment]
> > @weizhouapache code looks ok, but what is the sense of searching for a bunch of fields _and_ the id. The id is unique so this search makes no sense to me. Do you know how it is used and why it is a bug there?
> 
> @DaanHoogland as I said in description, the issue is with findActiveAccountById
> 
> https://github.com/apache/cloudstack/blob/85373e62191ce18b9d968d366661d3e2efa5909d/engine/schema/src/main/java/com/cloud/user/dao/AccountDaoImpl.java#L199-L203
> 
> this method search records by id, but "id" is not supported in AllFieldsSearch. therefore the result is same as (id/accountid is ignored)
> 
> ```
>     @Override
>     public Account findActiveAccountById(Long accountId, Long domainId) {
>         SearchCriteria<AccountVO> sc = AllFieldsSearch.create();
>         sc.setParameters("domainId", domainId);
>         return findOneBy(sc);
>     }
> ```

Ah, you are right. I was confusing `SearchBuilder` with `SearchCriteria`.
Nowhere else in the file the `id` is used in conjunction with the `AllFieldsSearch` so I think we are good.

**Review by DaanHoogland — APPROVED** [review]

**Comment by weizhouapache** [comment]
Merged based on 2 approvals and trillian test result

**Pull request merged**
