### PR TITLE
Add toggle button on the UI for list including elements in projects.

### PR DESCRIPTION
**Pull request by GabrielBrascher**
### Description

This PR allows listing elements that are in projects when in the Default view.
Nowadays, Admins cannot list in the UI many relevant data, unless entering in each of the projects, which can be humanly not feasible considering 10s or 100s of projects.

For example, one Admin cannot list all VMs, SSH keys, affinity groups, volumes, not even events that happen in a project in order to track all the events.

The UI tabs that are considered for this proposed PR are:
1. 'vm',
2. 'vmgroup',
3. 'ssh',
4. 'affinitygroup',
5. 'volume',
6. 'snapshot',
7. 'vmsnapshot',
8. 'guestnetwork',
9. 'vpc',
10. 'securitygroups',
11. 'publicip',
12. 'vpncustomergateway',
13. 'template',
14. 'iso',
15. 'event'

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [X] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

#### VMs
image

image

#### Events
image

image

### How Has This Been Tested?

- Build and run new UI
- Log in with admin account
- check tabs on default view
- check tabs on a project
- log with a "normal" user
- ensure that the user can list only elements in his own project

### CODE REVIEW

**Comment by GabrielBrascher** [comment]
@blueorangutan ui

**Review by utchoang — APPROVED** [review]

**Comment by GutoVeronezi** [comment]
@GabrielBrascher, thanks for the PR!

CLGTM, I'm just wondering if, when also listing elements that are in projects, users will be able to distinguish which project each resource belongs to.

**Comment by GabrielBrascher** [comment]
Thanks for the review, @GutoVeronezi.
It is possible to check which project a VM is by getting into the respective VM UI tab.

For example, this is one of the VMs I had for this test:
image

**Comment by GutoVeronezi** [comment]
@GabrielBrascher, understood.

Regarding to UX and in case of listing also project elements, I think we should add the project info into the list. Perhaps we should create an issue to address it in the future, as it will require more analysis and hard work.

**Comment by rohityadavcloud** [comment]
LGTM - should this be on 4.16  @GabrielBrascher since it's a minor UI change and (some) backend APIs already supports listing with projectid=-1?
@GabrielBrascher suggestions:
1. maybe add an account column in user resources such as VM, volumes, networks etc (as those belonging to a project will list the name of the project as account?)
2. should this be a global switch on the top, besides the project selector dropdown? (or left of the translation button)

**Comment by GabrielBrascher** [comment]
@blueorangutan ui

**Review by GutoVeronezi — COMMENTED** [review]
CLGTM

**Review by GutoVeronezi — APPROVED** [review]

**Review by rohityadavcloud — APPROVED** [review]
LGTM, needs UI/API testing cc @sureshanaparti @shwstppr @Pearl1594 @davidjumani - let's merge with a quick round of testing, thnx.

**Comment by rohityadavcloud** [comment]
@blueorangutan ui

**Comment by sureshanaparti** [comment]
Verified changes. @GabrielBrascher Can you change the toggle button label to 'Projects' from 'All Projects'?

**Comment by GabrielBrascher** [comment]
@sureshanaparti thanks for the testing and review.
Sure, I can change the label to just Projects.

**Comment by GabrielBrascher** [comment]
@sureshanaparti I've added a commit addressing your review:
_Change switch button name from 'All Projects' to just 'Projects'_. e1a94a9

**Review by sureshanaparti — APPROVED** [review]

**Pull request merged**
