### PR TITLE
CLOUDSTACK-8623: CPVM fails to start after MS is restarted during its…

### PR DESCRIPTION
**Pull request by koushik-das**
… initial start-up process

If SSVM cannot be started then the existing entry is removed and a new SSVM gets created. Made similar changes for CPVM as well.
Also cleaned up some log messages in SSVM and CPVM manager code.

### CODE REVIEW

**Comment by kishankavala** [comment]
LGTM.

**Comment by karuturi** [comment]
Can you add some unit tests or marvin tests?

**Comment by bhaisaab** [comment]
LGTM.

**Comment by DaanHoogland** [comment]
I would like to see tests with such a change as well

**Comment by koushik-das** [comment]
@karuturi @DaanHoogland Added unit tests for CPVM allocation.

**Comment by DaanHoogland** [comment]
test logic makes sense; LGTM

waiting for travis

**Comment by koushik-das** [comment]
Although RAT build status is showing ABORTED, the report is clean. Also the build failed due to some random test failure. Since travis is green, I am going ahead with the merge.

**Comment by koushik-das** [comment]
Manually closing PR. I did a rebase to do away with unnecessary merge commit.

**Pull request closed without merging**
