### PR TITLE
ui: fix tags for security group rules

### LINKED ISSUE #7412: Remove the option of Edit tags insecurity group (Ingress rules/Egress rules)
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

component:UI

##### SUMMARY

Remove the option to Edit tags a security group (Ingress rules/Egress rules)

Steps to reproduce the issue

1. Create a basic zone

2. Network >Security Group> Select any Security  Group > Ingress rule /Egress rule 

3. Click on Action item (edit tags)

4. End user will be unable to add any tag as there is no supporting api call 

[Screencast from 06-04-23 03:21:24 PM IST.webm](https://user-images.githubusercontent.com/1401014/230342291-91b90617-28c4-4749-9d97-7f5016440e02.webm)

The backend api call doesn't support tags

https://cloudstack.apache.org/api/apidocs-4.18/apis/authorizeSecurityGroupEgress.html

https://cloudstack.apache.org/api/apidocs-4.18/apis/authorizeSecurityGroupIngress.html
https://cloudstack.apache.org/api/apidocs-4.18/apis/revokeSecurityGroupEgress.html
https://cloudstack.apache.org/api/apidocs-4.18/apis/revokeSecurityGroupIngress.html

##### EXPECTED RESULTS

No option should be provided in the UI to edit security group ingress/Egrees rules

##### ACTUAL RESULTS

Option is provided in the UI to edit security group ingress/Egrees rules

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #7412

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
This may need some more changes as currently adding/deleting refreshes the whole page

**Review by rohityadavcloud — APPROVED** [review]
LGTM, will need testing against SG env

**Comment by rohityadavcloud** [comment]
@blueorangutan ui

**Comment by kiranchavala** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
thanks @shwstppr for the fix
thanks @kiranchavala for testing

merging

**Pull request merged**
