### PR TITLE
Scope setting changes in ldap and utils pom.xml files

### PR DESCRIPTION
**Pull request by harikrishna-patnala**
### Description

This PR fixes the issue https://github.com/apache/cloudstack/issues/6259.
We have changed the scope of the artifacts embedded-ldap-junit and commons-io as appropriate.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Review by rohityadavcloud — APPROVED** [review]
LGTM, if build passes

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@harikrishna-patnala do we also need to check the suggestion:
```
in server\pom.xml, mysql:mysql-connector-java scope should be compile instead of test.

```

**Comment by harikrishna-patnala** [comment]
> @harikrishna-patnala do we also need to check the suggestion:
> 
> ```
> in server\pom.xml, mysql:mysql-connector-java scope should be compile instead of test.
> ```

This is already at default scope "compile"

**Pull request merged**
