### PR TITLE
start transition of CI according to apache infra reqs

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR transitions from travis to gha. it is trying to follow https://docs.github.com/en/actions/migrating-to-github-actions/migrating-from-travis-ci-to-github-actions

An alternative approach would be to use: https://github.com/marketplace/actions/run-travis-yml (parallel PR?)

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] Platfor/build maintenance
- [ ] Other: ...

#### Feature/Enhancement Scale

- [x] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

so far only in the original branch on the PR repo. It can be replicated to your own.

### CODE REVIEW

**Comment by DaanHoogland** [comment]
matrix is working but hanging on install (build) with error:
```
Error: The operation was canceled
```
https://github.com/actions/runner-images/issues/1918 gives some clues but I am not sure how to 
```
--memory-swap -1
```
after this I am sure the actual script runner will need some love as well

**Comment by rohityadavcloud** [comment]
Thanks for starting this @DaanHoogland I saw on the PMCs/announce list they're killing Travis by '22 end.

**Comment by DaanHoogland** [comment]
@potiuk can you have a look at this?

**Comment by DaanHoogland** [comment]
closing in favour of #6896

**Pull request closed without merging**
