### PR TITLE
Fixed the Description coloumn in the UI for Quota traffic page

### PR DESCRIPTION
**Pull request by kiranchavala**
### Description

This PR fixes the description column output in the ui for the quota Tariff page

The following PR #5909 changed the response for the  quotaTariffList api call 

https://cloudstack.apache.org/api/apidocs-4.18/apis/quotaTariffList.html

In 4.17 the response for the quotaTariffList api call contains the "description" feild
```


<quotatariff>
<usageType>1</usageType>
<usageName>RUNNING_VM</usageName>
<usageUnit>Compute-Month</usageUnit>
<usageDiscriminator/>
<tariffValue>0.00000</tariffValue>
<effectiveDate>2010-05-04T00:00:00+0000</effectiveDate>
<description>Running Vm Usage</description>
<currency>$</currency>
</quotatariff>
```

Screenshot

quota2

In 4.18 the response for the quotaTariffList api call contains the "usageTypeDescription" field due to that there is no response in the Description coloumn

```
<quotatariff>
<usageType>1</usageType>
<usageName>RUNNING_VM</usageName>
<usageUnit>Compute*Month</usageUnit>
<usageDiscriminator/>
<tariffValue>0.00000</tariffValue>
<effectiveDate>2010-05-04T00:00:00+0000</effectiveDate>
<usageTypeDescription>Running Vm Usage</usageTypeDescription>
<currency>$</currency>
<name>RUNNING_VM</name>
<uuid>115dca9d-d2a5-11ed-b49d-1e00cd000444</uuid>
</quotatariff>
```

Screenshot
quota1

Steps to reproduce the issue

1. Enable the "quota.enable.service)" to true
2. Restart the management server
3. Go to UI >Quota > Tariff

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### How Has This Been Tested?

Tested on the 4.18 docker simulator

Screenshot
quota3

### CODE REVIEW

**Comment by kiranchavala** [comment]
Not able to fix the column Name after making the change 

Need help to fix the Name to Description 

quota4

**Comment by shwstppr** [comment]
> Not able to fix the column Name after making the change
> 
> Need help to fix the Name to Description
> 
> quota4

@kiranchavala add a key in `ui/public/locales/en.json`,
```
"label.usageTypeDescription": "Usage description",
```

**Comment by kiranchavala** [comment]
@shwstppr Thanks it working now

quota4

**Comment by kiranchavala** [comment]
@shwstppr shall i retarget this fix to 4.18 branch ?

**Comment by shwstppr** [comment]
@kiranchavala yes, that would be better since backend changes are there in 4.18

**Comment by kiranchavala** [comment]
@shwstppr Done, can you check if I performed the steps correctly, as it's showing 19 commits

I had done only 2 commits

**Review by shwstppr — APPROVED** [review]

**Comment by shwstppr** [comment]
@blueorangutan ui

**Review by rohityadavcloud — APPROVED** [review]

**Pull request merged**
