### PR TITLE
server: Calculate fresh capacity per VM

### PR DESCRIPTION
**Pull request by rhtyd**
This fixes and ensures that every VM has its capacity individually
calculated, with the initial override of 1.0f as overcommit ratio.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
Testing
- [ ] I have added tests to cover my changes.
- [x] All relevant new and existing integration tests have passed.
- [x] A full integration testsuite with all test that can run on my environment has passed.

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@PaulAngus @wido @DaanHoogland @borisstoyanov I can kick test, however, can we provisionally accept it based on reviews and travis result?
@blueorangutan test

**Comment by DaanHoogland** [comment]
@rhtyd the old behaviour is a bug, the new might be correct and won't be worse. Let's test during RC testing.

**Comment by borisstoyanov** [comment]
I think this one can be merged with the current reviews

**Comment by borisstoyanov** [comment]
@rhtyd I think we can merge this now.

**Pull request merged**
