### PR TITLE
UI: fix NIC table on instance view

### PR DESCRIPTION
**Pull request by mib1185**
### Description

This PR fixes a small UI bug, where `a-descriptions` is used by `NicsTable` but component is not registered properly, so UI looks bad and erros were thrown in debug console:

```
[Vue warn]: Unknown custom element: <a-descriptions> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### Screenshots (if appropriate):
Screenshot prior this change:
grafik

Screenshot with this change:
grafik

### How Has This Been Tested?

Local with CS simulator

### CODE REVIEW

**Comment by mib1185** [comment]
@blueorangutan package

**Comment by mib1185** [comment]
@blueorangutan ui

**Comment by mib1185** [comment]
@blueorangutan thanks

**Review by utchoang — APPROVED** [review]
LGTM! thanks @mib1185

**Review by Pearl1594 — APPROVED** [review]
LGTM

**Comment by shwstppr** [comment]
@mib1185 good to have in 4.15 branch?

**Comment by mib1185** [comment]
@shwstppr yeah sure, it is a quiet small fix 🙂

**Comment by mib1185** [comment]
@blueorangutan ui

**Review by shwstppr — APPROVED** [review]

**Review by davidjumani — APPROVED** [review]

**Pull request merged**
