### PR TITLE
ui: deployvm - Add option to stay on page

### PR DESCRIPTION
**Pull request by davidjumani**
### Description

Adds the option to stay on the deploy VM page

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

### How Has This Been Tested?

Screenshot from 2021-07-01 12-42-49

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan ui

**Review by utchoang — APPROVED** [review]
LGTM!

**Comment by rhtyd** [comment]
-1 we need to discuss what's the best way to address this or if users would need this at all. If users need to deploy multiple VMs we can consider a different UX, or ideally users should use APIs/cmk for automation.

**Comment by davidjumani** [comment]
@rhtyd This is intended for when a user might want to deploy multiple VMs with different templates, networks etc. This prevents the page from going back and keeps the form data so the user can change only what he wants

**Review by shwstppr — APPROVED** [review]
Not sure about the utility for a real user but the change work fine.
Useful for testing though. Maybe the option can be hidden by default and enabled on some config change.

**Comment by DaanHoogland** [comment]
@rhtyd this is a good case for displaying the APIs being called during the dialog as cmk script!?

**Comment by rhtyd** [comment]
@DaanHoogland sorry didn't get your comment,, what is cmk to do with the UI change?

**Comment by DaanHoogland** [comment]
> @DaanHoogland sorry didn't get your comment,, what is cmk to do with the UI change?

It doesn't and it doesn't relate to this change. But this change description by @davidjumani is a good argument for having a cmk CLI description of what you do in the UI. This can be convenient for operators that are learning or setting up new environments.

**Comment by rhtyd** [comment]
@davidjumani while I disagree with the change, I don't want to block if everyone agrees with the feature. Pl start a discussion on dev and users ML.

**Comment by nvazquez** [comment]
Hi @davidjumani are you still working on this PR?

**Comment by davidjumani** [comment]
@nvazquez It's ready but I'll send a mail on the ML to get consensus on  this PR

**Comment by shwstppr** [comment]
@davidjumani just a though, will it better to tweak UI something like following to make the option bit more subtle?
Screenshot from 2021-06-25 15-38-16

**Comment by davidjumani** [comment]
@blueorangutan ui

**Review by andrijapanicsb — APPROVED** [review]
Good change, someone will find this usable for sure.

LGTM

**Comment by rhtyd** [comment]
This creates a slight confusion, I would normally want the drop down to select first and then click the button (examples in other forms such as send email in Gmail or outlook where you toggle/select between send now or later and then click the button later to send the email).

**Pull request merged**
