### PR TITLE
ui bug fix: cannot assign vms to internal lb in VPC

### PR DESCRIPTION
**Pull request by ustcweizhou**
## Description

This fixes the issue that cannot assign VMs in Internal LB in VPC.
listView is overwritten due to commit 2e2b670 (#3161)

Fixes: #3827

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by weizhouapache** [comment]
> ok, i see your fix, $listView gets written as a new var and addressed as the old var in line 172 👍

@DaanHoogland yes exactly

**Comment by rhtyd** [comment]
Needs someone to manually test the UI cc @andrijapanicsb @DaanHoogland @borisstoyanov

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Tested against a 4.13.0.0 env, to assign VM to an internal LB:
Screenshot from 2020-01-31 15-22-23

**Pull request merged**
