### PR TITLE
CLOUDSTACK-9986: Use host table to iterate for zone/cluster metrics

### PR DESCRIPTION
**Pull request by rhtyd**
The host_view may contain duplicate entries when hosts have tags.
Changing the host_view may cause unseen regressions so
to fix the issues we've modified the zone/cluster metrics code to use
the `host` table (hostdao) to iterate through the list of hosts in a
cluster during zone/cluster metrics listing.

@blueorangutan package

### CODE REVIEW

**Comment by rhtyd** [comment]
The changes are specific to metrics plugin, Travis test results are sufficient to validate the change.
Please review - @DaanHoogland @nvazquez @borisstoyanov and others.

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@borisstoyanov we can run smoke tests, however the changes are limited to plugin and travis tests are enough to validate this. I'll still kick them ;)

@blueorangutan test

**Comment by GabrielBrascher** [comment]
Code LGTM. Thanks for the PR, @rhtyd.

**Comment by rhtyd** [comment]
Thanks @GabrielBrascher for the review. However, perhaps another way to solve the issue is to fix `host_view`.

**Comment by rhtyd** [comment]
Merging based on tests and review. Thanks all.

**Pull request merged**
