### PR TITLE
CLOUDSTACK-8838: Allow ensX format for nics in CentOS 7

### PR DESCRIPTION
**Pull request by giraffeforestg**

### CODE REVIEW

**Comment by remibergsma** [comment]
@giraffeforestg can you please add a bit more descriptive title? 

Something like:
CLOUDSTACK-8838: Allow ensX format for nics in CentOS 7

**Comment by giraffeforestg** [comment]
Hi.
Thank you for your advice.
I corrected the title.

**Comment by remibergsma** [comment]
@giraffeforestg Thanks. Is it an idea to add all possible systemd names to prevent more issues in the future?

```
With systemd 197 we have added native support for a number of different naming policies into systemd/udevd proper and made a scheme similar to biosdevname's (but generally more powerful, and closer to kernel-internal device identification schemes) the default. The following different naming schemes for network interfaces are now supported by udev natively:

Names incorporating Firmware/BIOS provided index numbers for on-board devices (example: eno1)
Names incorporating Firmware/BIOS provided PCI Express hotplug slot index numbers (example: ens1)
Names incorporating physical/geographical location of the connector of the hardware (example: enp2s0)
Names incorporating the interfaces's MAC address (example: enx78e7d1ea46da)
Classic, unpredictable kernel-native ethX naming (example: eth0)
```
Source: http://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/

Shall we add: enoX enpX enxX as well?

**Comment by giraffeforestg** [comment]
OK.
I will modify the code.

**Comment by remibergsma** [comment]
@giraffeforestg Awesom! You may also leave the PR open and push more commits once done. Whatever suits you :-)

**Comment by giraffeforestg** [comment]
sorry.
I am not familiar.
https://github.com/apache/cloudstack/pull/812

**Pull request closed without merging**
