### PR TITLE
CLOUDSTACK-10296: Find time different from last timestamp

### PR DESCRIPTION
**Pull request by rhtyd**
This fixes a difference issue in rVR heartbeat check script raised
recently on dev@.

@blueorangutan package

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by wido** [comment]
Code LGTM

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
Trillian env has been failing due to this change. Thanks for sharing @ustcweizhou, let me apply and test your fix. 
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
Merging this based on test results and review LGTMs.

**Comment by DaanHoogland** [comment]
wow, blueorangutan came back with a stale package result after merge! need more oil in the machine, something got stuck

**Comment by rhtyd** [comment]
No @DaanHoogland it's the trigger that is sometimes caused by github that kicks these pkging jobs post merge.

**Pull request merged**
