### PR TITLE
FIX Network with SG Disabled still has security group script adding rules on KVM

### LINKED ISSUE #5047: Network with SG Disabled still has security group script adding rules on KVM
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Security Group
~~~

##### CLOUDSTACK VERSION

~~~
4.15.0.0
~~~

##### CONFIGURATION

Zone deployed with Advanced Network and Security Group enabled.

##### OS / ENVIRONMENT

N/A

##### SUMMARY

We have been seeing the default security group rules being applied to VMs that are using a network **with no SG**. It is expected that when a network has Security Grouping turned off, it wouldn't execute this script at all.

For instance, if the network offering is the DefaultSharedNetworkOffering which does not list Security Grouping as a supported service, and VMs are rebooted CloudStack sends the command for KVM nodes to apply SG rules which can cause an outage for all the VMs on the respective network on that hypervisor.

###### LOG EXAMPLE
Checking the logs in the **MGMT** there are logs of SG Ruleset being scheduled and later sent to the KVM node; however, there are also validations detecting that SG is not supported for the network.

```
DEBUG [c.c.n.s.SecurityGroupManagerImpl] Security Group Mgr v2: scheduling ruleset updates for 1 
...
DEBUG [c.c.n.NetworkModelImpl] Service SecurityGroup is not supported in the network id=XYZ.
...
DEBUG [c.c.n.s.SecurityGroupManagerImpl] SecurityGroupManager v2: sending ruleset update for vm i-123-4567-VM:ingress ....
```

At the **KVM**, matching the send commands from **MGMT** there are some logs:
```
DEBUG [kvm.resource.LibvirtComputingResource] Checking default network rules for vm i-123-4567-VM
DEBUG [kvm.resource.LibvirtComputingResource] Executing: /usr/share/cloudstack-common/scripts/vm/network/security_group.py add_network_rules --vmname i-123-4567-VM --vmid 4567 --vmip ....
```

##### STEPS TO REPRODUCE

~~~
1. Deploy VM on a network with DefaultSharedNetworkOffering, at a zone that has Security Group enabled.
2. restart VM
~~~

##### EXPECTED RESULTS

~~~
VM is running and there are **NO** security group rules have been applied
~~~

##### ACTUAL RESULTS

~~~
VM is running but security group rules have been wrongly applied
~~~

### PR DESCRIPTION
**Pull request by GabrielBrascher**
### Description
This PR fixes #5047 which can be reproduced on Zones with _(I) Advanced Networks, (II) Security Groups enabled for the Zone, (III)  network offering without Security Groups_; for instance, `DefaultSharedNetworkOffering` which does not list Security Group as supported service.

The issue is due to the following code inside the method `VirtualMachineManagerImpl.orchestrateReboot`:
[VirtualMachineManagerImpl.java#L3340](https://github.com/apache/cloudstack/blob/280c13a4bb103dd748ec304bfe0714a148c24602/engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java#L3340).

```
  final Answer rebootAnswer = cmds.getAnswer(RebootAnswer.class);
  if (rebootAnswer != null && rebootAnswer.getResult()) {
      if (dc.isSecurityGroupEnabled() && vm.getType() == VirtualMachine.Type.User) {
          List<Long> affectedVms = new ArrayList<Long>();
          affectedVms.add(vm.getId());
          _securityGroupManager.scheduleRulesetUpdateToHosts(affectedVms, true, null);
      }
      return;
  }
```

As the Data Center was deployed enabling Security group, it is expected column `is_security_group_enabled = 1`; therefore,  `dc.isSecurityGroupEnabled()` is `true`; which combined with VM of type User schedules a Ruleset update to the KVM node where the VM is being rebooted at. This particular scenario is not wanted if the VM's network has no SG.

When testing SG for 4.15.0.0 RCs as well as testing/reviewing any PR within KVM/SG scope the tests looked good due to the fact that I was always using networks with SG.

The issue can be seen only on networks that have no SG enabled but the `dc.isSecurityGroupEnabled()` is `true`.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale
N/A

#### Bug Severity

- [X] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

:alert: Tests will be done soon. PR is a draft opened as soon as possible.

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
it looks this is a regression issue of my pr #3639
would you mind to backport the pr to 4.14 ? @GabrielBrascher

**Comment by weizhouapache** [comment]
code lgtm

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by GabrielBrascher** [comment]
@weizhouapache no problem, the base branch has been changed from `4.15` to `4.14`.

**Comment by rhtyd** [comment]
@weizhouapache since it's related to your PR - are you lgtm on the changes, or have tested them?

**Review by rhtyd — APPROVED** [review]
LGTM based on description and code changes, and smoketests (which don't cover SG, but at least confirm no regressions otherwise)

**Comment by rhtyd** [comment]
@GabrielBrascher the PR is in draft - are you working on additional changes?

**Comment by weizhouapache** [comment]
> @weizhouapache since it's related to your PR - are you lgtm on the changes, or have tested them?

@rhtyd code lgtm. I will test it on monday.

**Review by wido — APPROVED** [review]
Code LGTM

**Comment by rhtyd** [comment]
Wei can confirmed testing, merging based on that.

**Pull request merged**
