### PR TITLE
CLOUDSTACK-9854: Fix test_primary_storage test failure due to live migration

### PR DESCRIPTION
**Pull request by nvazquez**
Fix for test_primary_storage integration tests on simulator.

When finding storage pool migration options for volume on running vm, API returns None as hypervisor doesn't support live migration.

````
2017-03-28 06:07:55,958 - DEBUG - ========Sending GET Cmd : findStoragePoolsForMigration=======
2017-03-28 06:07:55,977 - DEBUG - Response : None
2017-03-28 06:07:55,983 - CRITICAL - EXCEPTION: test_03_migration_options_storage_tags: ['Traceback (most recent call last):\n', '  File "/opt/python/2.7.12/lib/python2.7/unittest/case.py", line 329, in run\n    testMethod()\n', '  File "/home/travis/.local/lib/python2.7/site-packages/marvin/lib/decoratorGenerators.py", line 30, in test_wrapper\n    return test(self, *args, **kwargs)\n', '  File "/home/travis/build/apache/cloudstack/test/integration/smoke/test_primary_storage.py", line 547, in test_03_migration_options_storage_tags\n    pools_suitable = filter(lambda p : p.suitableformigration, pools_response)\n', "TypeError: 'NoneType' object is not iterable\n"]
````

So we simply stop vm before sending findStoragePoolsForMigration command

### CODE REVIEW

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by nvazquez** [comment]
Thanks @borisstoyanov, I made little refactor due to failure, can you please re kick tests?

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by karuturi** [comment]
@nvazquez PR #2019 is merged. Can you force push and kick travis again?

**Comment by nvazquez** [comment]
@karuturi sure, done! I rebased master and pushed, now Travis passes!

**Comment by SudharmaJain** [comment]
LGTM for the code changes

**Comment by karuturi** [comment]
Wonderful. Seeing green travis after a long time :) 👍  
Thanks @nvazquez and @SudharmaJain 
merging now

**Pull request merged**
