### PR TITLE
Change exception when orchestrating VM start

### PR DESCRIPTION
**Pull request by lucas-a-martins**
### Description

When attempting to start a VM, if an error occurs, the exception displayed to users is the same as what is being logged, which can expose information about the environment.

This PR addresses this issue by keeping the current message to be sent to the logs and adding a new one for the exception shown to users.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

### Screenshots (if appropriate):

<details>
    <summary>Exception before the proposed changes</summary>

  old-exception
</details>

<details>
    <summary>Exception after the proposed changes</summary>

  
new-exception

</details>

### How Has This Been Tested?

Using a stopped VM, I changed the _Compute Offering_ to a offering with `Host Tags` incompatible with every host in my environment in order to force the exception, then I tried to start the VM. An exception was thrown as shown in the screenshots above.

I also checked the logs in both cases and the only changes was log level and the removal of a duplicated message at the end of the log related to the exception.

Old log:

```
2024-05-06T19:19:34,582 WARN [c.c.v.ClusteredVirtualMachineManagerImpl] (Work-Job-Executor-35:[ctx-613c449f, job-326/job-327, ctx-6739b946]) (logid:c2b5e46f) Unable to orchestrate start VM instance {"id":32,"instanceName":"i-2-32-VM","type":"User","uuid":"0447f7cc-d6be-4999-875b-391ecf529fe4"} due to [No suitable host found.]. com.cloud.utils.exception.CloudRuntimeException: No suitable host found.
```

New log:

```
2024-05-07T18:26:38,697 ERROR [c.c.v.ClusteredVirtualMachineManagerImpl] (Work-Job-Executor-69:[ctx-73d78bb7, job-563/job-564, ctx-1b492476]) (logid:55146be5) Unable to orchestrate start VM instance {"id":47,"instanceName":"i-2-47-VM","type":"User","uuid":"e07b123d-51b2-4c5e-845c-880da28b7518"} due to [No suitable host found.].
```

### CODE REVIEW

**Review by vishesh92 — APPROVED** [review]
clgtm. didn't test.

**Comment by vishesh92** [comment]
@blueorangutan package

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by lucas-a-martins** [comment]
Hey @DaanHoogland 

I checked the logs and seems like the failed tests are unrelated to this PR. Could you please run the tests again?

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
> [SF] Trillian test result (tid-10733) Environment: kvm-centos7 (x2), Advanced Networking with Mgmt server 7 Total time taken: 58828 seconds Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr9062-t10733-kvm-centos7.zip Smoke tests completed. 109 look OK, 28 have errors, 0 did not run Only failed and skipped tests results shown below:

I've seen this number of errors before in main. not sure why but certainly not related to this change. Trying one more

**Comment by DaanHoogland** [comment]
@blueorangutan test alma9 kvm-alma9

**Comment by DaanHoogland** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Pull request merged**
