### PR TITLE
fill volume attached field

### PR DESCRIPTION
**Pull request by DK101010**
### Description
This PR fills the volume attached field during the ingest. Is needed for automation purposes to get the same behavior
between ingested vm's and in cs created vm's.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

Tested in own VMware env

### CODE REVIEW

**Comment by sureshanaparti** [comment]
Hi @DK101010 Is this PR good to go in 4.16.1? If so, please rebase with 4.16. Thanks.

**Review by shwstppr — APPROVED** [review]
LGTM

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
cltgm

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
it seems the tests are failing due to some environmental issues, re-triggering tests

@blueorangutan test

**Pull request merged**
