### PR TITLE
Remove unused StrategyPriority.PLUGIN

### PR DESCRIPTION
**Pull request by GabrielBrascher**
## Description

Remove unused `StrategyPriority.PLUGIN` enum. The **PLUGIN** Strategy priority is not used, except by three JUnit test methods.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by GabrielBrascher** [comment]
@rhtyd @DaanHoogland @nvazquez can some of you guys run integrations tests on this PR? Packagin is ok and ready for testing.
Thanks in advance :+1:

**Comment by nvazquez** [comment]
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
I am not to sure about this one. changing an enum, potentially changes the meaning of all of it values. I think this one is never persisted but still I don't like the principle. Is it really needed?

**Comment by rhtyd** [comment]
I'm okay to remove the enum if it's not used by anything or stored in db.

**Comment by GabrielBrascher** [comment]
@DaanHoogland there is no pratical need to remove this enum. I was just implementing KVM local to local storage migration and got a bit conserned if the `PLUGIN` priority could impact on my storage data motion strategy `canHandle` implementation. After looking into it I noticed that the respective enum is not used in any of our data motion strategy `canHandle` and decided to clean this up.

**How it was verified:**
Used Eclipse IDE to search for any reference for the `StrategyPriority.PLUGIN` enum. As I could not find any reference (except by the JUnit tests), I decided to play safe and run some file search looking for the text `PLUGIN` on CloudStack. The returned ones were not related to this enum. Thus, we don't have any sort of code (e.g. sql) running to set the strategy as "PLUGIN".

Variables or values that contain the string `PLUGIN`: `NUAGE_VSP_PLUGIN_ERROR_MESSAGE`, `STORAGEPLUGINXML`, `PLUGINPATH`, `NFSPLUGIN`, `SAML2-PLUGIN` and `QUOTA-PLUGIN`.

**Comment by DaanHoogland** [comment]
ok, tnx @GabrielBrascher . Let's do it

**Comment by GabrielBrascher** [comment]
Are you ok with this PR @nvazquez @rhtyd @DaanHoogland?

**Pull request merged**
