### PR TITLE
NSX: add back removed code for NSX

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

The code snippet has been removed in the merge forward of PR #9240 in commit 90fe1d5fdcc2909130b5de6803b57feeff194f54

This PR adds the code back.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Review by Pearl1594 — APPROVED** [review]
LGTM

**Comment by rohityadavcloud** [comment]
@nvazquez @Pearl1594 can there be some unit tests or integration to catch this?
@blueorangutan package

**Comment by nvazquez** [comment]
Merging based on approvals

**Pull request merged**
