### PR TITLE
network: allow icmp code 16 in firewall rules

### LINKED ISSUE #3349: Validation on Router Advertisement for Firewall Rules
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
Firewall Rules for VMs

~~~

##### CLOUDSTACK VERSION
Latest

##### CONFIGURATION
N/A


##### OS / ENVIRONMENT
N/A


##### SUMMARY
https://github.com/apache/cloudstack/blob/master/server/src/main/java/com/cloud/network/vpc/NetworkACLServiceImpl.java/#LC527

The code on this page uses the function NetUtils.validateIcmpCode to validate that the code is between 0-15. 
However there is a case in our system where an apparently valid code is 16. 

If you look at the spec for Type 9 Router Advertisement: 
https://www.iana.org/assignments/icmp-parameters/icmp-parameters.xhtml#icmp-parameters-codes-9/#table-icmp-parameters-ext-classes

The valid codes are 0 and 16. 

Not sure if this is intended to eliminate this option or not.

Actual place to update appears to be here:
https://github.com/apache/cloudstack/blob/master/utils/src/main/java/com/cloud/utils/net/NetUtils.java/#LC1214

### PR DESCRIPTION
**Pull request by rhtyd**
This allows for icmp code range 0-16.

Type 9 Router advertisement reference:
https://www.iana.org/assignments/icmp-parameters/icmp-parameters.xhtml#icmp-parameters-codes-9/#table-icmp-parameters-ext-classes

Fixes #3349

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by ustcweizhou** [comment]
LGTM

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Pull request merged**
