### PR TITLE
add remove tag to remove acl item method

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR cleans resource tags when deleting a network acl item.

Fixes: #7744

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### How Has This Been Tested?

tested by checking the DB contents for the tables `network_acl_item` vs. `resourece_tags`

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@shwstppr can you review? both myself and @NuxRo tested.

**Review by shwstppr — APPROVED** [review]
Code LGTM. Would be good to have some unit test covering updated methods

**Comment by DaanHoogland** [comment]
> Code LGTM. Would be good to have some unit test covering updated methods

I'll have a look but the actual issue involved persistence (would be good to use an in memory db for unit tests)

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Pull request merged**
