### PR TITLE
CLOUDSTACK-9989: Extend smoketests suite

### PR DESCRIPTION
**Pull request by borisstoyanov**
Adding few areas of tests to the smoketests since they are not covered when doing PR testing but important at the same time.

### CODE REVIEW

**Comment by rhtyd** [comment]
@borisstoyanov can you confirm if these tests run okay with Trillian? I've had moved some component tests to run part of Travis that you may consider to include as well, however keep in mind some tests run longer than half a day, while a typical Trillian smoke tests may take about half a day or less.

**Comment by borisstoyanov** [comment]
Yes @rhtyd, I've run them on a Trillian env before moving them in the smoketests

**Comment by borisstoyanov** [comment]
ping @DaanHoogland @nvazquez @PaulAngus for review

**Comment by rhtyd** [comment]
@borisstoyanov as part of moving these tests, maybe we can include them in .travis.yml too?

**Comment by borisstoyanov** [comment]
Thanks @rhtyd, I've pushed the change in travis yml file.

**Comment by rhtyd** [comment]
okay @borisstoyanov  we might need to refactor/rearrange them at some point, I'll fire some tests.
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
LGTM, the travis job `TestStorageTags:tearDown` failure is known intermittent failure.

**Pull request merged**
