### PR TITLE
Improving code readability  using optional chaining

### PR DESCRIPTION
**Pull request by Yashikaone**
**DESCRIPTION**

  This PR is related to issue #4956. 
  This is my first contribution on Github and I have no experience with javascript and vue.js therefore I have tried changing a single file for now. 
  Please let me know if there is an error I will make sure to rectify it as soon as possible.
 Thank you.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by utchoang** [comment]
@Yashikaone Optional chaining is not recommended for <template> elements. Because this will cause the build to fail.

**Comment by Yashikaone** [comment]
@utchoang Thank you for the review, I will keep this in mind. 
Also I have a question, does optional chaining works for only null references ?

**Comment by utchoang** [comment]
@Yashikaone Yes. As far as I remember it works with null reference

**Comment by Yashikaone** [comment]
Okay Thank you for your help. I will close this PR now.

**Pull request closed without merging**
