### PR TITLE
python3 and nose2 first step

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR grades python up from 2 to 3 and nose to nose2
this is yet another part of #3195

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [x] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

- [ ] This will be tested by running a smoke test run.
- [ ] This will be tested by travis
- [ ] this will be tested by starting individual tests or sets of tests

some considerations:
1. [ ] init structure need re-design. the nose override configure(self, options, conf) is not called in nose2 instead a callback is provided for cli args being passed. (preferred is config file, but our tests are to dynamicly dependent on env definition and tags)
1. [ ] __init__() now is filling internal data with None, should be resonable defaults according to the nose2 doc
1. [x] argline definition is changed 
1. [ ] test selection through nose2 -A and -E options work
1. [ ] ssh client for verification
1. [ ] db client for verification
1. [ ] MarvinLogs get only `runinfo.txt` filled, `results.txt` and `failed_plus_exceptions.txt` remain empty
1. [ ] ...

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
this is yet another part of #3195

**Comment by DaanHoogland** [comment]
@blueorangutan test cetos7 kvm-centos7 keepEnv

**Comment by DaanHoogland** [comment]
@blueorangutan test centos7 kvm-centos7 keepEnv

**Comment by DaanHoogland** [comment]
output is false negatives, no tests were run!

**Comment by DaanHoogland** [comment]
some considerations:
1. [ ] init structure need re-design. the nose override configure(self, options, conf) is not called in nose2 instead a callback is provided for cli args being passed. (preferred is config file, but our tests are to dynamicly dependent on env definition and tags)
1. [ ] __init__() now is filling internal data with None, should be resonable defaults according to the nose2 doc
1. [x] argline definition is changed 
1. [ ] ...

**Comment by DaanHoogland** [comment]
```
# python3 -m pip list --format=columns
Package                Version
---------------------- -----------------
2to3                   1.0
bcrypt                 3.2.0
certifi                2020.11.8
cffi                   1.14.3
chardet                3.0.4
coverage               5.3
cryptography           3.2.1
ddt                    1.4.1
dnspython              2.0.0
idna                   2.10
importlib-resources    3.3.0
ipmisim                0.8
linecache2             1.0.0
lxml                   4.6.1
Marvin                 4.15.0.0-SNAPSHOT
mysql-connector-python 8.0.22
netaddr                0.8.0
nose                   1.3.7
nose2                  0.9.2
paramiko               2.7.2
pip                    9.0.3
protobuf               3.14.0
pycparser              2.20
pycrypt                0.7.2
pyghmi                 1.2.16
PyNaCl                 1.4.0
pyOpenSSL              19.1.0
pytz                   2020.4
pyvmomi                7.0.1
requests               2.25.0
retries                1.0
setuptools             39.2.0
six                    1.15.0
traceback2             1.4.0
unittest2              1.1.0
urllib3                1.26.2
zipp                   3.4.0
```
not all of these are needed!

**Comment by DaanHoogland** [comment]
the attr decorator is removed so we need to implement it somewhere in marvi:
```
def attr(*args, **kwargs):
    """Decorator that adds attributes to classes or functions
    for use with the Attribute (-a) plugin.
    """
    def wrap_ob(ob):
        for name in args:
            setattr(ob, name, True)
        for name, value in kwargs.items():
            setattr(ob, name, value)
        return ob
    return wrap_ob

```

**Comment by DaanHoogland** [comment]
as it seems more and more clear that nose2 is a dead end, I will create a new PR that purely focusses on porting nosetest and marvin to python3. updating our test framework will have to follow on that work.

**Comment by rhtyd** [comment]
Migration to py3 only here - https://github.com/apache/cloudstack/pull/4543/files

**Comment by DaanHoogland** [comment]
nose2 change will not be implemented

**Pull request closed without merging**
