### PR TITLE
Routed mode: minor improvements and fixes

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR
- adds a global setting to enable/disable the Static/Dynamic routing feature
- add some unit tests
- fixes the issue that frr.conf has no settings when VR is restarted.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by kiranchavala — APPROVED** [review]
LGTM, tested manually the setting "routed.network.vpc.enabled" both at zone and global level

If the setting at global level is false, admin user is unable to create network and vpc offering with routed mode option, only the default Natted mode option is show 

Screenshot 2024-10-01 at 12 59 46 PM


If the setting at global level is true, both natted and routed option is show





Screenshot 2024-10-01 at 1 12 08 PM


Also the  following settings are honoured by the global setting 

Network > AS number > 
Network> Ipv4subnet

**Comment by kiranchavala** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Pull request merged**
