### PR TITLE
Add start button for multiple instances in list view

### PR DESCRIPTION
**Pull request by pbankonier**
## Description
This adds a start button on top of the instance list view which makes it possible to start multiple instances at once.

## Types of changes
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## Screenshots:
instances_start_button

## How Has This Been Tested?
Deployed to our test environment and tested functionality.

### CODE REVIEW

**Comment by svenvogel** [comment]
@rhtyd @rafaelweingartner @GabrielBrascher can you check this? 👍

**Comment by borisstoyanov** [comment]
Thanks for this neat feature. 
@blueorangutan package

**Comment by svenvogel** [comment]
@GabrielBrascher @rhtyd can we merge it?

**Comment by GabrielBrascher** [comment]
@svenvogel  I had postponed this as it is not a critical fix and needed to cut off such PRs and issues in order to keep the schedule. I think that I added this by mistake on the list of merged PRs.

**Comment by svenvogel** [comment]
@GabrielBrascher ah no problem. can you check the pr if it looks okay from your side?

**Pull request merged**
