### PR TITLE
CLOUDSTACK-8766: Fix infinite scrolling pagination for zonal template…

### PR DESCRIPTION
**Pull request by bhaisaab**
… listing

Uses listViewDataProvider to implement pagination on listTemplates API
requests in the UI, when a template's zone tab is viewed.

(cherry picked from commit 95c76efc3944aab9a620559a026fe37e53d8f53d)

This from the other PR, for master branch.

### CODE REVIEW

**Comment by karuturi** [comment]
What is the page size? can you attach a screenshot?

**Comment by bhaisaab** [comment]
@karuturi the sharedFunctions.js defines a global pagesize (fixed to value 20)

See in the screenshot; the listTemplates call does not call the API with a page, pagesize - this causes the infinite scroll to flood the list every time to drag it if the number of zones exceed what could fit in that table view. This patch fixes that.

screen shot 2015-08-25 at 12 50 04 pm

**Comment by bhaisaab** [comment]
@karuturi this is the screenshot from chrome devtools with the UI fix, as you can see pagination is implemented

screenshot from 2015-08-25 12 54 50

**Comment by karuturi** [comment]
tested it and confirm the behaviour in the screenshots before and after the fix. :+1:

**Comment by bhaisaab** [comment]
I've updated the PR to fix the same issue for listing isos and also addition code to de-dupe list iso and template results.

**Comment by abhinandanprateek** [comment]
LGTM

**Comment by remibergsma** [comment]
LGTM

**Pull request merged**
