### PR TITLE
CLOUDSTACK-8602. MigrateVirtualMachineWithVolume leaves old chain dat…

### PR DESCRIPTION
**Pull request by likitha**
…a for volume.

Update chain info of a volume after  migration.

### CODE REVIEW

**Comment by sateesh-chodapuneedi** [comment]
LGTM.
I see this patch is updating chain information for all 3 cases of storage migration, 
1) volume migration
2) vm migration with storage within cluster
3) vm migration across storage within cluster

**Comment by sureshanaparti** [comment]
Code changes to update the volume chain info are perfect.

**Comment by DaanHoogland** [comment]
code changes good or not, let's not accept any changes without (unit) tests any more.

**Comment by remibergsma** [comment]
Who wants to step in and finish this work? It seems the original author is not able to finish it. If no one steps in, we'll have to close the PR without merging it so please help :-).

**Comment by bhaisaab** [comment]
LGTM

**Pull request closed without merging**
