### PR TITLE
ui: fix related key for section

### LINKED ISSUE #5928: UI - Missing view Accounts button in domain view
##### ISSUE TYPE

 * Bug

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15.x
~~~

##### SUMMARY

View Accounts Button missing when selecting a domain. 
In the old UI there is an option to view accounts when you've selected a domain. In the New UI this option is missing.
This option is however visible when we traverse to the Domain view, from the Accounts list view.

In the domain View: No "view Accounts" button visible
image

Traversing to the Domain, from the accounts list view , displays the button:
image

It would be a good improvement to have the view Accounts button visible on direct traversal to the Domain (Domain -> Specific Domain)

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Pass related key of section to route
Fixes #5928

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

Screenshot from 2022-02-03 17-07-32

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan ui

**Review by DaanHoogland — APPROVED** [review]
code looks good
tested in qa... works

**Review by GabrielBrascher — APPROVED** [review]
Code LGTM

**Review by sureshanaparti — APPROVED** [review]
Verified. LGTM.

**Pull request merged**
