### PR TITLE
CKS: fix /opt/bin/deploy-cloudstack-secret in CKS control nodes

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes the typos in deploy-cloudstack-secret script.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by vishesh92 — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
this is a help string update, 2 lgtm, gha passed; merging

**Pull request merged**
