### PR TITLE
set python explicit during transistion

### PR DESCRIPTION
**Pull request by DaanHoogland**
this will allow for easier switching back and forth during development on python 3 functionality

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

regular use on a default python3 platform

### CODE REVIEW

**Review by yadvr — APPROVED** [review]
I'm not sure if we use this as pyenv is not used generally in our workflows

**Comment by DaanHoogland** [comment]
we don't use pyenv from mvn do we?

**Review by GabrielBrascher — COMMENTED** [review]
@DaanHoogland unfortunately mvn build is failing due to pyenv version:

```
pyenv: version `2.7.18' is not installed (set by /home/travis/build/apache/cloudstack/.python-version)
```

**Comment by DaanHoogland** [comment]
@GabrielBrascher then you have to change your version to the one you did install, or not set it at all. I have to switch between 2 and 3 as well. That is exactly the point of the change. after transistion it should read some 3 version or be deleted if we want to... I'm not sure if just 2 or just 3 works.

if there is no interest in this, I'll just close.

**Comment by GabrielBrascher** [comment]
@DaanHoogland I have no particular issue with this change, considering it is meant to the transition from Python 2 to 3.

The issue that I raised is that if this PR gets merged then Travis will fail for all PRs based on the master.

We should then check what version Travis has installed and set to that version or see what we can do to change Travis version. Otherwise, all PRs will have the following issue ```pyenv: version '2.7.18' is not installed (set by /home/travis/build/apache/cloudstack/.python-version).```

**Review by GabrielBrascher — APPROVED** [review]
I don't see why not having it for this period of transition Python 2 to 3.
LGTM.

**Comment by rhtyd** [comment]
@DaanHoogland can this be closed?

**Pull request closed without merging**
