### PR TITLE
CLOUDSTACK-8840: Systemd service for the Usage Server

### PR DESCRIPTION
**Pull request by wido**
There already was a uncompleted systemd service file for the Usage
Server.

This new one replaces sysvinit and the old systemd service file.

### CODE REVIEW

**Comment by remibergsma** [comment]
@wido I get this error when I run `./package.sh -d centos7`

```
install: cannot stat ‘packaging/cloudstack-usage.service’: No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.biFx59 (%install)
```

**Comment by wido** [comment]
@remibergsma Yes, stupid. Fixed that. Pushed a new commit

**Comment by wido** [comment]
@remibergsma @bhaisaab Could you take a look? It's almost similar to the Agent systemd profile :)

**Comment by bhaisaab** [comment]
@wido looks similar so looking at the changes LGTM, but I lack infra and time to test it out right now

**Comment by wido** [comment]
@bhaisaab Tnx! I tested it on a CentOS 7 system:

```
[root@vm-d818122e-51ca-479f-9618-051b4eed7c10 system]# systemctl status cloudstack-usage
cloudstack-usage.service - CloudStack Usage Server
   Loaded: loaded (/etc/systemd/system/cloudstack-usage.service; disabled)
   Active: active (running) since wo 2015-09-16 10:38:48 CEST; 3s ago
     Docs: http://www.cloudstack.org/
 Main PID: 2492 (sh)
   CGroup: /system.slice/cloudstack-usage.service
```

@remibergsma Can you verify if the packages now build properly? I would love to get this into 4.6 so that we are systemdified :)

**Comment by remibergsma** [comment]
@wido Sure, will do my tests again today!

**Comment by remibergsma** [comment]
@wido No luck yet:

```
error: File not found: /data/git/cs2/cloudstack/dist/rpmbuild/BUILDROOT/cloudstack-4.6.0-SNAPSHOT.el7.centos.x86_64/usr/sbin/cloudstack-usage-sysd

RPM build errors:
    Binaries arch (1) not matching the package arch (2).
    File not found: /data/git/cs2/cloudstack/dist/rpmbuild/BUILDROOT/cloudstack-4.6.0-SNAPSHOT.el7.centos.x86_64/usr/sbin/cloudstack-usage-sysd
RPM Build Failed 
```

**Comment by wido** [comment]
@remibergsma Thank you for testing. Stupid mistake indeed. That should be fixed now.

I checked on a CentOS 7 machine:

```
+ exit 0
RPM Build Done
```

**Comment by remibergsma** [comment]
@wido Yep, works fine now!

```
+ exit 0
RPM Build Done
```

Here they are:

```
[root@cs4 packaging]# ls -la ../dist/rpmbuild/RPMS/x86_64/
total 288928
drwxr-xr-x. 2 root root      4096 Sep 16 18:44 .
drwxr-xr-x. 3 root root      4096 Sep 16 18:43 ..
-rw-r--r--. 1 root root  50700428 Sep 16 18:44 cloudstack-agent-4.6.0-SNAPSHOT.el7.centos.x86_64.rpm
-rw-r--r--. 1 root root      5364 Sep 16 18:44 cloudstack-baremetal-agent-4.6.0-SNAPSHOT.el7.centos.x86_64.rpm
-rw-r--r--. 1 root root     38276 Sep 16 18:44 cloudstack-cli-4.6.0-SNAPSHOT.el7.centos.x86_64.rpm
-rw-r--r--. 1 root root 111008452 Sep 16 18:44 cloudstack-common-4.6.0-SNAPSHOT.el7.centos.x86_64.rpm
-rw-r--r--. 1 root root  88693724 Sep 16 18:43 cloudstack-management-4.6.0-SNAPSHOT.el7.centos.x86_64.rpm
-rw-r--r--. 1 root root  45395296 Sep 16 18:44 cloudstack-usage-4.6.0-SNAPSHOT.el7.centos.x86_64.rpm
```

LGTM

**Pull request merged**
