### PR TITLE
CLOUDSTACK-8748: VM UUID accessible in CreateVMSnapshotCommand and Re…

### PR DESCRIPTION
**Pull request by bhaisaab**
…vertToVMSnapshotCommand

This patch makes it possible to expose VM UUID to subsystems, this can be
useful for implementing VM Snapshots for KVM in future.

### CODE REVIEW

**Comment by jburwell** [comment]
LGTM

**Comment by remibergsma** [comment]
LGTM

**Comment by karuturi** [comment]
master build broken with the below error http://jenkins.buildacloud.org/job/build-master-slowbuild/2101/consoleText
```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/jenkins/acs/workspace/build-master-slowbuild/plugins/hypervisors/xenserver/test/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixRequestWrapperTest.java:[1581,51] error: constructor CreateVMSnapshotCommand in class CreateVMSnapshotCommand cannot be applied to given types;
[ERROR]   required: String,String,VMSnapshotTO,List<VolumeObjectTO>,String
  found: String,VMSnapshotTO,List<VolumeObjectTO>,String
  reason: actual and formal argument lists differ in length
/home/jenkins/acs/workspace/build-master-slowbuild/plugins/hypervisors/xenserver/test/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixRequestWrapperTest.java:[1623,53] error: no suitable constructor found for RevertToVMSnapshotCommand(String,VMSnapshotTO,List<VolumeObjectTO>,String)
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
```

**Comment by remibergsma** [comment]
@karuturi I reverted the commit to master (044e685c92ef98d08771f04c766ec42d97fe5c35)

**Comment by karuturi** [comment]
Thanks @remibergsma

**Comment by bhaisaab** [comment]
Merged on master through: https://github.com/apache/cloudstack/pull/722

**Pull request merged**
