### PR TITLE
PR1102 regression fix; half the annotation was removed

### PR DESCRIPTION
**Pull request by DaanHoogland**
I am having troubles getting this to work but it passes the point at which the master slowbuild is broken.

### CODE REVIEW

**Comment by DaanHoogland** [comment]
The error occurs in 4.6 as well, so I think this PR should go through

**Comment by DaanHoogland** [comment]
the problem seems to be only in using java8.

**Comment by DaanHoogland** [comment]
```
mvn -P developer,systemvm clean install -Dnoredist
```
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:40 min
[INFO] Finished at: 2015-11-23T19:22:21+01:00
[INFO] Final Memory: 85M/810M
[INFO] ------------------------------------------------------------------------
```

**Comment by rafaelweingartner** [comment]
@DaanHoogland, I have just ran "mvn clean install -Dnoredist -P developer,systemvm" with java 8 and everything was ok. What version of java 8 are you using?

mine is: Java version: 1.8.0_66, vendor: Oracle Corporation

**Comment by DaanHoogland** [comment]
macosx 10.11.1:
```
$ java -version
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
```

btw: It was the f5 plugin project not compiling

**Comment by rafaelweingartner** [comment]
That is the plugin, here everything compiled without problems.
~$ mvn -version
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.8.0_66, vendor: Oracle Corporation
Java home: /home/rafael/Java/jdk1.8.0_66/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-68-generic", arch: "amd64", family: "unix"

**Comment by DaanHoogland** [comment]
retried but it is repeatable :')
```
$ mvn -version
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: /usr/local/Cellar/maven/3.3.3/libexec
Java version: 1.8.0_66, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.1", arch: "x86_64", family: "mac"
```

**Comment by remibergsma** [comment]
Guys, why didn't we get 2x LGTM on this?

**Comment by DaanHoogland** [comment]
My bad @remibergsma I counted @ProjectMoon as lgtm

**Comment by rafaelweingartner** [comment]
@DaanHoogland , I have just checked with @cristofolini, I also had the problem you described here. I did not see that before because I had compiled without using “-Dnoredist -P developer,systemvm” parameters, then eclipse had already built the f5 plugin using Java 7. Then when I used “mvn install -Dnoredist -P developer,systemvm", without “clean” in my command line, I did not get that error.

We found out that, this problem occurs with java 1.8.0_66, which is the Java version that you, me and critofolini are using. I tried the Java version 1.8.0_5 that I had here, and the f5 plugin project compiled. Have you tried with different versions of java 1.8?

**Comment by DaanHoogland** [comment]
i have some lying around:
```
    1.8.0_25, x86_64:	"Java SE 8"	/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home
    1.8.0_05, x86_64:	"Java SE 8"	/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home
```
will give them a spin.

**Comment by DaanHoogland** [comment]
1.8.0_05 works, 1.8.0_25 doesn't

**Comment by rafaelweingartner** [comment]
Interesting, so it looks like a Java problem

**Comment by ProjectMoon** [comment]
This build problem happens to me on Java 1.7. Isn't this just a syntax error? The annotation markers are missing.

**Comment by rafaelweingartner** [comment]
this problem, was solved when this PR was merged. The problem we were talking about was the build of f5 plugin project that is not building with Java 1.8.0_66 and 1.8.0_25.
We tried with 1.8.0_5 and it worked.

**Pull request merged**
