### PR TITLE
Changed AddressFormat elements to reflect changes in IPv4 and IPv6 refactor.

### PR DESCRIPTION
**Pull request by borisroman**
See issue CLOUDSTACK-8736 for ongoing effort to clean up network code.

### CODE REVIEW

**Comment by wido** [comment]
LGTM

**Comment by remibergsma** [comment]
@borisroman If I run this `grep -r Ip4 *` I see many references to `Ip4`. Isn't this going to be confusing to rename a part of it only? Or am I missing something?

**Comment by borisroman** [comment]
@remibergsma You are correct. Those are all not related to the AddressFormat enum. Of course all should be renamed, but doing so in 1 time will also will not benefit the process of making the code more readable.

I'll will stack up some commits before making a new pr.

**Comment by remibergsma** [comment]
@borisroman I suggest you close this PR and do all the refactor work in a separate branch, as discussed. Thanks!

**Comment by borisroman** [comment]
Will do.

**Pull request closed without merging**
