### PR TITLE
ui: allow clearing dns during zone update

### LINKED ISSUE #7273: Clearing DNS entry and saving zone does not persist changes if empty
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION
~~~
4.17.1.0
~~~

##### STEPS TO REPRODUCE
Open zone that has DNS entries.  In test example, the goal was to remove DNS2 entry and leave DNS1.
Click OK after clearing one of the DNS fields entry.
Should get a green check mark dialog "Edit Zone - [zone name]".  Indicating a successful update.
Refresh zone, value is still present in field, and in database.

##### EXPECTED RESULTS
~~~
Expected the cleared entries were saved to the database.
Possibly even a dialog message saying all VR's in zone needed to be restarted along with all VM's to pick up changes.
Possibly a dialog offering to bounce them?
~~~

##### ACTUAL RESULTS
~~~
DNS fields still had data in them.
~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #7273

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
Not sure if we can have a generic solution when a parameter value is explicitly set to empty,
```
diff --git a/ui/src/views/AutogenView.vue b/ui/src/views/AutogenView.vue
index 78e68ae34a..0d93992c3b 100644
--- a/ui/src/views/AutogenView.vue
+++ b/ui/src/views/AutogenView.vue
@@ -510,7 +510,8 @@ export default {
       confirmDirty: false,
       firstIndex: 0,
       modalWidth: '30vw',
-      promises: []
+      promises: [],
+      originalItemValuesBeforeEdit: {}
     }
   },
   beforeUnmount () {
@@ -1226,6 +1227,7 @@ export default {
         fieldValue = this.resource[fieldName] ? this.resource[fieldName] : null
         if (fieldValue) {
           this.form[field.name] = fieldValue
+          this.originalItemValuesBeforeEdit[field.name] = fieldValue
         }
       })
     },
@@ -1351,6 +1353,12 @@ export default {
         resolve(false)
       })
     },
+    paramValueClearedWithUpdate (param) {
+      if (!this.originalItemValuesBeforeEdit || Object.keys(this.originalItemValuesBeforeEdit).length === 0) {
+        return false
+      }
+      return this.originalItemValuesBeforeEdit[param] !== ''
+    },
     execSubmit (e) {
       e.preventDefault()
       this.formRef.value.validate().then(() => {
@@ -1367,15 +1375,12 @@ export default {
               continue
             }
             if (input === undefined || input === null ||
-              (input === '' && !['updateStoragePool', 'updateHost', 'updatePhysicalNetwork', 'updateDiskOffering', 'updateNetworkOffering', 'updateServiceOffering', 'updateZone'].includes(action.api))) {
+              (input === '' && this.paramValueClearedWithUpdate(key))) {
               if (param.type === 'boolean') {
                 params[key] = false
               }
               break
             }
-            if (input === '' && !['tags', 'hosttags', 'storagetags', 'dns2', 'ip6dns1', 'ip6dns2'].includes(key)) {
-              break
-            }
             if (action.mapping && key in action.mapping && action.mapping[key].options) {
               params[key] = action.mapping[key].options[input]
```

**Comment by kiranchavala** [comment]
@blueorangutan ui

**Comment by kiranchavala** [comment]
@shwstppr  Able to clear DNS2, IPV6 DNS1, IPV6 DNS2

Not able to clear the internal dns 2
dns

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by kiranchavala** [comment]
@shwstppr tested the changes LGTM

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by DaanHoogland** [comment]
@blueorangutan ui

**Comment by shwstppr** [comment]
@blueorangutan ui

**Review by rohityadavcloud — APPROVED** [review]

**Pull request merged**
