### PR TITLE
CLOUDSTACK-10434:Some APIs should have access check

### PR DESCRIPTION
**Pull request by lujiefsi**
### Description

This PR fixes the CLOUDSTACK-10434. I think some APIs in  VolumeApiServiceImpl  lack access check. I will list them in below table. I also give the pattch to add the access check for the api in this table. Anyone chould change this table, If you think the APIs do not need access check and change their lable as "no".

|  API   | Lack?  |
|  ----  | ----  |
| VolumeApiServiceImpl # updateVolume  | yes |
| VolumeApiServiceImpl # detachVolumeViaDestroyVM  | yes |
| VolumeApiServiceImpl # takeSnapshot  | yes |
| VolumeApiServiceImpl # migrateVolume  | yes |
| AccountManagerImpl#createApiKeyAndSecretKey | yes |
| LoadBalancingRulesManagerImpl#applyLBStickinessPolicy | yes |
| LoadBalancingRulesManagerImpl#applyLBHealthCheckPolicy| yes |
| TemplateManagerImpl#createPrivateTemplate| yes |
| SnapshotManagerImpl#updateSnapshotPolicy| yes |

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [x] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [x] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@lujiefsi why do you think this "solves" CLOUDSTACK-10434? I can not find that, it redirects me to [CLOUDSTACK-10431](https://issues.apache.org/jira/projects/CLOUDSTACK/issues/CLOUDSTACK-10431), the highest ticket number to date.
Note that the jira board is only used for GSoC currently and issues are at [github](https://github.com/apache/cloudstack/issues)

this is in no way a comment on the code or the functionality of your PR!

**Comment by rhtyd** [comment]
@lujiefsi can you change base branch to 4.15 as it's marked bug fix

**Comment by lujiefsi** [comment]
> @lujiefsi why do you think this "solves" CLOUDSTACK-10434? I can not find that, it redirects me to [CLOUDSTACK-10431](https://issues.apache.org/jira/projects/CLOUDSTACK/issues/CLOUDSTACK-10431), the highest ticket number to date.
> Note that the jira board is only used for GSoC currently and issues are at [github](https://github.com/apache/cloudstack/issues)
> 
> this is in no way a comment on the code or the functionality of your PR!



> @lujiefsi why do you think this "solves" CLOUDSTACK-10434? I can not find that, it redirects me to [CLOUDSTACK-10431](https://issues.apache.org/jira/projects/CLOUDSTACK/issues/CLOUDSTACK-10431), the highest ticket number to date.
> Note that the jira board is only used for GSoC currently and issues are at [github](https://github.com/apache/cloudstack/issues)
> 
> this is in no way a comment on the code or the functionality of your PR!

The issuse link is:
https://issues.apache.org/jira/browse/CLOUDSTACK-10434

**Comment by lujiefsi** [comment]
> @lujiefsi can you change base branch to 4.15 as it's marked bug fix

YES, i will!

**Comment by lujiefsi** [comment]
> @lujiefsi can you change base branch to 4.15 as it's marked bug fix

done see https://github.com/apache/cloudstack/pull/4859/files

**Comment by rhtyd** [comment]
@lujiefsi this PR may be closed in favour of https://github.com/apache/cloudstack/pull/4859
Generally if a PR exists for older branch, we can review/test merge it and forward-merge it until master branch.

**Comment by lujiefsi** [comment]
@rhtyd i will close this this pull request and move the description to https://github.com/apache/cloudstack/pull/4859

**Pull request closed without merging**
