### PR TITLE
fix macchinina template specificied for vmware in Marvin tests

### PR DESCRIPTION
**Pull request by PaulAngus**
fix macchinina template specificied for vmware - .vmdk.bz2 is not valid… for CloudStack. edit to use .ova

### CODE REVIEW

**Comment by rhtyd** [comment]
LGTM.

**Comment by jburwell** [comment]
@abhinandanprateek are these two test suites where we should be using ``vm.instance`` config variable instead specifying the template directly in the test suite?

**Comment by serg38** [comment]
We tried macchinina template during test cases on ESX with E1000 adapter and VMs doesn't come with eth0 causing test_internal_lb.py and test_vpc_vpn.py to fail on a real hypervisor test. Has anyone actually tried it running on Vmware?

**Comment by jburwell** [comment]
@PaulAngus @abhinandanprateek could you investigate the VMware issue described by @serg38?

**Comment by jburwell** [comment]
@PaulAngus this issue seems to affect 4.8+.  Since we have one more 4.8 (4.8.2.0) release, it would be nice to have this fix for those test runs.  Therefore, could you re-point it to the 4.8 branch?

**Comment by rhtyd** [comment]
LGTM. @abhinandanprateek is the changes okay, or we should refactor move them to the default test_data file?

**Comment by rhtyd** [comment]
I've moved the changes to PR #1692  this can be closed now.

**Comment by rhtyd** [comment]
This has been merged/fixed with #1692 and fwd-merges, please close this @PaulAngus

**Pull request closed without merging**
