### PR TITLE
[WIP] Add Datera storage plugin

### PR DESCRIPTION
**Pull request by jcsdatera**
Features:

1. Zone-wide and cluster-wide primary storage support
2. VM template caching automatically on Datera, the subsequent VMs can be created instantaneously by fast cloning the root volume.
3. Rapid storage-native snapshot
4. Multiple managed primary storages can be created with a single Datera cluster to provide better management of
      - Total provisioned capacity
      - Default storage QoS values
      - Replica size ( 1 to 5 )
      - IP pool assignment for iSCSI target
      - Volume Placement ( hybrid, single_flash, all_flash )
 5. Volume snapshot to VM template
 6. Volume to VM template
 7. Volume size increase using service policy
 8. Volume QoS change using service policy
 9. Enabled KVM support
10. New Datera app_instance name format to include ACS volume name
11. VM live migration

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [*] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by swill** [comment]
I would like to add a little context to this PR and why it is opened against the `4.11` branch.

CloudOps originally developed this plugin for Datera, after which point, the Datera version and the CloudOps versions diverged as new functionality was added to both.  This PR is an effort to consolidate the Datera and CloudOps implementations such that a mutual customer (who is running on the 4.11 LTS branch) may leverage the functionality.  

Here is the plan for release:
- CloudOps will create a PR on this PR to add the functionality that we have developed on top of this.
- Once the combined functionality has been validated, our mutual customer will pull the working PR on the 4.11 branch into their code base.
- This PR will then be rebased against the `master` branch for formal inclusion in the upstream ACS code base.
- Datera will maintain this plugin in the upstream code base going forward.

Let me know if you have any questions or concerns and I will work to facilitate the inclusion of this code upstream.

**Comment by rhtyd** [comment]
@swill thanks for sharing and being open about it. I was going to kick tests on the PR, I guess I'll wait until this gets re-posted against master branch.

**Comment by swill** [comment]
@rhtyd thank you.  We will get this PR updated with the additional functionality soon.  Cheers...

**Comment by rhtyd** [comment]
Can we close this @jcsdatera @swill in favour of https://github.com/apache/cloudstack/pull/3410 ?

**Comment by rhtyd** [comment]
Closing this in favour of https://github.com/apache/cloudstack/pull/3410 new PR against master

**Comment by jcsdatera** [comment]
Ping @rhtyd, @swill 
Could we reopen this PR as we are still waiting for CloudOps to add functionality on top of this?

Thank you

**Comment by rhtyd** [comment]
@jcsdatera we cannot accept changes towards 4.11 branch, kindly submit a new PR for master, or use an existing PR against master for adding functionality.

**Pull request closed without merging**
