### PR TITLE
Added domain path to all entities

### PR DESCRIPTION
**Pull request by harikrishna-patnala**
### Description

This PR fixes the ticket #8086. Added domain path to all the responses whereever domain and domain names are already used.

Added domain path to all the responses which implements the interfaces ControlledViewEntityResponse and ControlledEntityResponse

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### How did you try to break this feature and the system with this change?

(localcloud) 🐱 > list virtualmachines filter=name,domainpath,domain
{
  "count": 6,
  "virtualmachine": [
    {
      "domain": "ROOT",
      "domainpath": "/",
      "name": "Vm1N1"
    },
    {

List of responses where we have added the domain paths are

From ControlledEntityResponse:

```
ServiceInstanceResponse
KubernetesClusterResponse
ConditionResponse
VpnUsersResponse
StaticRouteResponse
VlanIpRangeResponse
ResourceLimitResponse
AutoScaleVmProfileResponse
RemoteAccessVpnResponse
GuestVlanRangeResponse
ApplicationLoadBalancerResponse
UserDataResponse
AutoScalePolicyResponse
UserVmResponse
GlobalLoadBalancerResponse
VirtualRouterProviderResponse
NetworkResponse
Site2SiteVpnGatewayResponse
LoadBalancerResponse
VpcResponse
UsageRecordResponse
Site2SiteCustomerGatewayResponse
PrivateGatewayResponse
IPAddressResponse
GuestVlanResponse
Site2SiteVpnConnectionResponse
ResourceCountResponse
AcquireIPAddressResponse
AutoScaleVmGroupResponse
VMSnapshotResponse
```

From ControlledViewEntityResponse

```
AffinityGroupResponse
TemplateResponse
BucketResponse
EventResponse
SecurityGroupResponse
DomainRouterResponse
VolumeResponse
ResourceTagResponse
InstanceGroupResponse
SnapshotResponse
ProjectInvitationResponse
ProjectAccountResponse
```

### CODE REVIEW

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Review by vishesh92 — APPROVED** [review]
clgtm

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Review by kiranchavala — APPROVED** [review]
LGTM, The domainpath is present in the apiresponses

```
(cmk) > list networks filter=name,doaminid,domainpath listall=true
{
  "count": 3,
  "network": [
    {
      "domainpath": "/domain2/",
      "name": "test2domain2"
    },
    {
      "domainpath": "/domain1/",
      "name": "account1net"
    },
    {
      "domainpath": "/",
      "name": "test"
    }
  ]
}
```
```
(cmk)  > list virtualmachines filter=name,domainid,domainpath listall=true
{
  "count": 3,
  "virtualmachine": [
    {
      "domainid": "12a1d40e-612c-11ef-ba9c-1e0027000437",
      "domainpath": "/",
      "name": "VM-eae4ab5f-c603-4009-a6a5-23130fbf43d7"
    },
    {
      "domainid": "a3dd29d3-243f-44f6-a16b-6248b04cd3eb",
      "domainpath": "/domain1/",
      "name": "vm2"
    },
    {
      "domainid": "a995ca47-c759-4ac2-9447-3d86446a4158",
      "domainpath": "/domain2/",
      "name": "vm3"
    }
  ]
}
```

**Comment by kiranchavala** [comment]
@blueorangutan test

**Pull request merged**
