### PR TITLE
Fix config drive iso path on Vmware

### PR DESCRIPTION
**Pull request by krissterckx**
## Description
Fixing capitalized 'ConfigDrive' iso path to lowercase 'configdrive'

## Types of changes
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## GitHub Issue/PRs

Fixes: #2759

## Checklist:
- [x] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
Testing
- [ ] I have added tests to cover my changes.
- [ ] All relevant new and existing integration tests have passed.
- [ ] A full integration testsuite with all test that can run on my environment has passed.

### CODE REVIEW

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-65

**Comment by wido** [comment]
In which part of the code is the lowercase 'configdrive' set?

**Comment by fmaximus** [comment]
@sateesh-chodapuneedi I agree, especially since there already is a constant defined: `ConfigDrive.CONFIGDRIVEDIR`

**Pull request merged**
