### PR TITLE
CLOUDSTACK-9583: VR: In CsDhcp.py preseed both hostaname and localhost to resolve to 127.0.0.1

### PR DESCRIPTION
**Pull request by murali-reddy**
ensuring for both vpc and non vpc vr, both localhost and hostname is resolved to 127.0.0.1

### CODE REVIEW

**Comment by murali-reddy** [comment]
@blueorangutan package

**Comment by murali-reddy** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
LGTM

**Comment by syed** [comment]
LGTM as well. Thanks for the fix @murali-reddy

**Comment by murali-reddy** [comment]
@blueorangutan test

**Comment by jburwell** [comment]
@murali-reddy could you please update the commit message/pull request description to describe the motivation for this change and the benefits it provides?  Also, this fix would be useful for 4.8 user as well.  Therefore, could you please change the base branch to 4.8?

**Comment by murali-reddy** [comment]
opened #1757 targeting 4.8 so closed this PR

**Pull request closed without merging**
