### PR TITLE
storpool: fix pom.xml which caused docker image build failures

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes the issue which can be reproduced by steps below:

- git clone https://github.com/apache/cloudstack.git
- cd cloudstack
- rm -rf .git/
- run `mvn -P developer,systemvm clean install`

Without this PR, it fails with error

```
 > [ 8/10] RUN mvn -Pdeveloper -Dsimulator -DskipTests clean install:
668.1 [ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:4.9.10:revision (get-the-git-infos) on project cloud-plugin-storage-volume-storpool: .git directory is not found! Please specify a valid [dotGitDirectory] in your pom.xml -> [Help 1]
```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [x] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
change looks sane, but does the docker build need to delete the .git directory @weizhouapache ?

**Comment by weizhouapache** [comment]
> change looks sane, but does the docker build need to delete the .git directory @weizhouapache ?

@DaanHoogland 
I have no idea how github action pulls the code, it seems .git directory is missing in the build container.
https://github.com/apache/cloudstack/blob/main/.github/workflows/docker-cloudstack-simulator.yml

**Comment by DaanHoogland** [comment]
> > change looks sane, but does the docker build need to delete the .git directory @weizhouapache ?
> 
> @DaanHoogland I have no idea how github action pulls the code, it seems .git directory is missing in the build container. https://github.com/apache/cloudstack/blob/main/.github/workflows/docker-cloudstack-simulator.yml

ok, if it is otherwise out of our control let's merge

**Review by slavkap — APPROVED** [review]
LGTM but didn't tested it with docker

**Comment by weizhouapache** [comment]
> > > change looks sane, but does the docker build need to delete the .git directory @weizhouapache ?
> > 
> > 
> > @DaanHoogland I have no idea how github action pulls the code, it seems .git directory is missing in the build container. https://github.com/apache/cloudstack/blob/main/.github/workflows/docker-cloudstack-simulator.yml
> 
> ok, if it is otherwise out of our control let's merge

yes. 
we could also consider that some users download the source code tarball from cloudstack website, which does not have .git directory as well.

**Comment by weizhouapache** [comment]
thanks @DaanHoogland @slavkap 
merging

**Comment by weizhouapache** [comment]
the latest build succeeded.
https://github.com/apache/cloudstack/actions/runs/5829634800/job/15809484444

**Pull request merged**
