### PR TITLE
Replicate `rootDiskController` behavior to `dataDiskController`.

### PR DESCRIPTION
**Pull request by GutoVeronezi**
### Description
The bus type to `data disk` volumes is hardcoded to `virtio` or `scsi`, when using virtio-scsi (or, based on the template type). Therefore, there is no way to specify the bus type to data disk volumes (as we have for root disks). 

This PR intends to replicate the `rootDiskController` behavior to `dataDiskController`, allowing the definition of the controller.

### Types of changes
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale
- [x] Major
- [ ] Minor
### How Has This Been Tested?
It has been tested locally.

### CODE REVIEW

**Review by RodrigoDLopez — APPROVED** [review]
Nice Enhancement @GutoVeronezi 
can you please explain to me how the local tests were carried out?

My tests consist of entering the details of the data disk (during the deployment process of an instance or via a graphical interface with a previously created instance) and then checking if the details informed are present in the dump XML of the target instance.

I performed manual tests with this branch. It is correct and working as it should.
LGTM

**Comment by RodrigoDLopez** [comment]
@blueorangutan package

**Comment by RodrigoDLopez** [comment]
@blueorangutan test

**Comment by GutoVeronezi** [comment]
@RodrigoDLopez thanks for asking.

Actually the process is quite similar as which you described.

I made the whole process via GUI.

1. I created an instance.

2. With it stopped, I created a volume and attached to it.

3. I setted the `dataDiskController` setting as `ide` and started the instance. 

4. After that, I checked if the detail informed was in the dump XML of the instance.
    What I got was `<target dev = 'hda' bus = 'ide' />`, which was what I expected.

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by DaanHoogland — COMMENTED** [review]
one concern; the default used to be `virtio` and now it is `null`? otherwise the code looks good

**Comment by GutoVeronezi** [comment]
> one concern; the default used to be `virtio` and now it is `null`? otherwise the code looks good

@DaanHoogland 
The method `getDataDiskModelFromVMDetail` returns null if the `dataDiskController` setting is not configured.
If the method returns null, then it will keep the same behavior as before, so the default still is `virtio`.

**Comment by DaanHoogland** [comment]
@GutoVeronezi you are right, i read with crooked eyes.

**Review by DaanHoogland — APPROVED** [review]

**Review by rhtyd — APPROVED** [review]

**Pull request merged**
