### PR TITLE
UI: add filter user/all to list user/all volumes

### LINKED ISSUE #6993: Root volume of system vms is being listed
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API/UI
~~~

##### CLOUDSTACK VERSION

~~~
4.18 [main]
~~~

##### EXPECTED RESULTS

~~~
Volumes of system VMs/routers should not be listed to admin/user in Volumes tab
~~~

##### ACTUAL RESULTS

~~~
they are
~~~
Screenshot 2022-12-15 at 10 34 21

### PR DESCRIPTION
**Pull request by weizhouapache**
This fixes #6993

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):

- list volumes in a project with filter=User , by root admin
image

- list volumes in a project with filter=All , by root admin
image

- list volumes in a project, by domain admin (no filter)
image

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan ui

**Review by rohityadavcloud — APPROVED** [review]
Didn’t test it

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
tested as admin and as domain admin

**Pull request merged**
