### PR TITLE
Fix ssl check in object store browser

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR fixes the ssl in image store browser.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by DaanHoogland** [comment]
@wido , can you test this?

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by wido** [comment]
> @wido , can you test this?

Yes. Will do so tomorrow (04-04-2024)

**Review by wido — APPROVED** [review]
Tested on my test environment and works as expected.

CORS gave me some troubles, but that is not related to this issue, local config problems.

LGTM

**Pull request merged**
