### PR TITLE
ui: fix admin dashboard vue warnings

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes warnings on admin dashboard in console.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):
Without change
Screenshot from 2024-05-29 14-23-55

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by shwstppr** [comment]
@blueorangutan ui

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Comment by rohityadavcloud** [comment]
LGTM, but without toFixed(2) how can we ensure upto two max. decimal places?

**Comment by shwstppr** [comment]
> LGTM, but without toFixed(2) how can we ensure upto two max. decimal places?

It must be handled by `:format`

**Review by rohityadavcloud — APPROVED** [review]

**Pull request merged**
