### PR TITLE
ui: fix create account/user with saml

### LINKED ISSUE #5477: Problem adding SAML user as Domain Admin
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME

~~~
UI, SAML SSO
~~~

##### CLOUDSTACK VERSION

~~~
4.15.1
4.15.2
~~~

##### CONFIGURATION
SAML is enabled.

##### OS / ENVIRONMENT
Using online environment http://primate-qa.cloudstack.cloud:8080/client/master/

##### SUMMARY
When logged as a Domain Admin, it is not possible to add a SAML user, since the identity provider list is not loaded in the new UI. 

##### STEPS TO REPRODUCE
1. Login to the UI using a Domain-Admin user, for example teste-sb/password/teste-sb at http://primate-qa.cloudstack.cloud:8080/client/master.
2. Go to “Accounts” 
3. “Add Account +” OR “<Existing account>”-> “View Users” -> “Add User +”
4.  Try to enable “Authorize SAML SSO”, the identity provider list is not loaded. Note: Using root admin at the same account the list is loaded successfully.

##### EXPECTED RESULTS

~~~
Identity Provider list is loaded 
~~~

##### ACTUAL RESULTS

~~~
A icon “No Data” is displayed
~~~

### LINKED ISSUE #5478: Problem adding SAML user into a existing Account
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME

~~~
UI, SAML SSO
~~~

##### CLOUDSTACK VERSION

~~~
4.15.1
4.15.2
~~~

##### CONFIGURATION
SAML is enabled.

##### OS / ENVIRONMENT
Using online environment http://primate-qa.cloudstack.cloud:8080/client/master/

##### SUMMARY
Logged as ROOT Admin, adding an adicional SAML user to an existing Account does not work properly when the new UI is used. 

##### STEPS TO REPRODUCE
1. Login to the UI as ROOT Admin, with saml configured and enabled, for example http://primate-qa.cloudstack.cloud:8080/client/master.
2. Go to “Accounts”
3. “<Existing account>”->“View Users” -> “Add User +”
4.  Add a user with “Authorize SAML SSO”.
5. Click at the new user.

##### EXPECTED RESULTS

~~~
User Type: saml2
~~~

##### ACTUAL RESULTS

~~~
User Type: native
~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #5477
Fixes #5478

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):
Before change:

Screenshot from 2021-09-21 12-19-12

Screenshot from 2021-09-21 12-19-36

After change:
Screenshot from 2021-09-21 12-22-38

Screenshot from 2021-09-21 12-22-59

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan ui

**Comment by rhtyd** [comment]
@blueorangutan ui

**Comment by rhtyd** [comment]
@shwstppr couple of issues, not sure if they are due to the qa.cloudstack.cloud backend of 4.15.1: (the qa.cloudstack.cloud is SAMl enabled and can be used for testing)

1. Check if the normal user/role type should be shown this form, it fails:
Screenshot from 2021-09-21 12-25-37

2. On creating user as normal user type, that fails too (in its own account):
Screenshot from 2021-09-21 12-26-14

3. As domain admin, the IDP list was somehow not shown in the create user form:
Screenshot from 2021-09-21 12-27-16

4. As root admin, I created a new user 'rick' and while creating the user ticked authorise saml sso and selected the IDP however the newly-created user is not SAML2 type:
Screenshot from 2021-09-21 12-30-45

5. For an already authorised saml user, when clicking edit saml authorisation button the IDP is pre-selected as 0 (something wrong in option/value key?)
Screenshot from 2021-09-21 12-36-20

Note: this form also seems to pass invalid entityid in the API, so the user isn't really SAML enabled.

**Comment by shwstppr** [comment]
@rhtyd Verified mentioned issues with PR build:
1. Normal User role cannot create new users in their own account. Old UI doesn't provide the option and option wasn't there in this PR build as well.
2. Same as `1`
3. Fixed this case
4. Fixed with this PR
5. Didn't see this behaviour with this PR build.

Addressed #5477 and #5478
@blueorangutan ui

**Comment by shwstppr** [comment]
@blueorangutan ui

**Review by utchoang — APPROVED** [review]
LGTM!

**Comment by rhtyd** [comment]
@blueorangutan ui

**Review by rhtyd — APPROVED** [review]
LGTM - I'll test and confirm shortly

**Comment by rhtyd** [comment]
@blueorangutan ui

**Comment by rhtyd** [comment]
@shwstppr outstanding/new issues:
1. Minor - does not refresh user detail page on edit/saving the authorise saml sso form
2. As domain admin, the entity ID is not updating - still 0? And on saving the form still passes 0 as entityid
3. Create user form doesn't work for domain user the #/user path (as domainid is not passed)

**Comment by rhtyd** [comment]
@shwstppr is this ready for final test/merge, or you addressing minor issues too?
@blueorangutan ui

**Comment by shwstppr** [comment]
@rhtyd let's move ahead with one for #2

> As domain admin, the entity ID is not updating - still 0? And on saving the form still passes 0 as entityid

I'll fix #1 and #3 in another PR #5487

**Pull request merged**
