### PR TITLE
test: Fix travis failure - test_outofbandmanagement.py

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

This PR fixes the travis test failure noticed on the main branch - 
```
ERROR: test suite for <class 'integration.smoke.test_outofbandmanagement.TestOutOfBandManagement'>
----------------------------------------------------------------------
Traceback (most recent call last):

  File "/home/travis/.local/lib/python3.6/site-packages/nose/suite.py", line 210, in run
    self.setUp()
  File "/home/travis/.local/lib/python3.6/site-packages/nose/suite.py", line 293, in setUp
    self.setupContext(ancestor)
  File "/home/travis/.local/lib/python3.6/site-packages/nose/suite.py", line 316, in setupContext
    try_run(context, names)
  File "/home/travis/.local/lib/python3.6/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/home/travis/build/apache/cloudstack/test/integration/smoke/test_outofbandmanagement.py", line 50, in setUpClass
    cls.skipIfMSIsUnsupported(cls)
  File "/home/travis/build/apache/cloudstack/test/integration/smoke/test_outofbandmanagement.py", line 99, in skipIfMSIsUnsupported
    os_details = SshClient(self.mgtSvrDetails["mgtSvrIp"], 22, self.mgtSvrDetails["user"], self.mgtSvrDetails["passwd"]).execute \
  File "/home/travis/.local/lib/python3.6/site-packages/marvin/sshClient.py", line 81, in __init__
    raise internalError("SSH Connection Failed")
marvin.cloudstackException.internalError: SSH Connection Failed
```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### How Has This Been Tested?
Ran the smoke test - test_outofbandmanagement.py on simulator env - passes

```
nosetests --with-xunit --xunit-file=results.xml --with-marvin --marvin-config=setup/dev/advanced.cfg -s -a tags=advanced --hypervisor=simulator test/integration/smoke/test_outofbandmanagement.py

==== Marvin Init Started ====

=== Marvin Parse Config Successful ===

=== Marvin Setting TestData Successful===

==== Log Folder Path: /tmp/MarvinLogs/Aug_20_2021_11_24_00_P3BZHV. All logs will be available here ====

=== Marvin Init Logging Successful===

==== Marvin Init Successful ====
=== TestName: test_oobm_background_powerstate_sync | Status : SUCCESS ===

=== TestName: test_oobm_configure_default_driver | Status : SUCCESS ===

=== TestName: test_oobm_configure_invalid_driver | Status : SUCCESS ===

=== TestName: test_oobm_disable_feature_invalid | Status : SUCCESS ===

=== TestName: test_oobm_disable_feature_valid | Status : SUCCESS ===

=== TestName: test_oobm_enable_feature_invalid | Status : SUCCESS ===

=== TestName: test_oobm_enable_feature_valid | Status : SUCCESS ===

=== TestName: test_oobm_enabledisable_across_clusterzones | Status : SUCCESS ===

=== TestName: test_oobm_issue_power_cycle | Status : SUCCESS ===

=== TestName: test_oobm_issue_power_off | Status : SUCCESS ===

=== TestName: test_oobm_issue_power_on | Status : SUCCESS ===

=== TestName: test_oobm_issue_power_reset | Status : SUCCESS ===

=== TestName: test_oobm_issue_power_soft | Status : SUCCESS ===

=== TestName: test_oobm_issue_power_status | Status : SUCCESS ===

=== TestName: test_oobm_multiple_mgmt_server_ownership | Status : SUCCESS ===

=== TestName: test_oobm_zchange_password | Status : SUCCESS ===

```

### CODE REVIEW

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by Pearl1594** [comment]
@blueorangutan package

**Review by rhtyd — APPROVED** [review]
LGTM since this runs only on Travis - we can merge as travis build has passed

**Comment by rhtyd** [comment]
@Pearl1594 should this be ported to 4.15?

**Comment by Pearl1594** [comment]
This was an issue only on main

**Pull request merged**
