### PR TITLE
server: allow normal users to create isolated network without source nat

### LINKED ISSUE #5897: Add Network :  Network Offering Drop down is not showing "Offering for Isolated networks with no Source Nat service "
##### ISSUE TYPE
 * Other

##### COMPONENT NAME
UI

##### CLOUDSTACK VERSION
4.16

##### CONFIGURATION
advanced networking

##### OS / ENVIRONMENT
Centos7.9

##### SUMMARY
Not able to get list of Network Offerings (only Source-Nat service offering is displayed ) when I try to create Isolated Guest Network.
I am looking to create Guest isolated Network from "Isolated networks with no Source Nat service" offering.  (NOTE:  able to create the same using API)

##### STEPS TO REPRODUCE
Go-to:  Network > Guest Networks .  Add Network (Click)

image

##### EXPECTED RESULTS

Add Network:  Network Offering Drop down shows "Offering for Isolated networks with no Source Nat service "

##### ACTUAL RESULTS

Add Network:  Network Offering Drop down is not showing "Offering for Isolated networks with no Source Nat service "

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR allows normal users to create isolated networks without source nat.

fixes #5897

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
your code looks good @weizhouapache can you think of the testing we need to do for this?
The obvious is just creating a network as normal user with a network offering without source-nat. But other than that?
Or do we just let it go with the generic regression testing on the RC?

**Comment by weizhouapache** [comment]
> your code looks good @weizhouapache can you think of the testing we need to do for this? The obvious is just creating a network as normal user with a network offering without source-nat. But other than that? Or do we just let it go with the generic regression testing on the RC?

@DaanHoogland 
I think we need to test the network creation with different network type, by different account type.
in my opinion, the expected results are
(1) root admin, can create shared, L2 and isolated with/without source nat
(2) domain admin, can create L2 and isolated with/without source nat
(2) normal user, can create L2 and isolated with/without source nat

Other features like firewall, lb, pf, static nat and vpc should work.

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@blueorangutan test

**Review by sureshanaparti — APPROVED** [review]
code LGTM

**Comment by DaanHoogland** [comment]
> (1) root admin, can create shared, L2 and isolated with/without source nat
> (2) domain admin, can create L2 and isolated with/without source nat
> (2) normal user, can create L2 and isolated with/without source nat

above tested and functional, the with sourcenet offerings used were with full services enabled so 

> Other features like firewall, lb, pf, static nat and vpc should work.

should all work

**Review by shwstppr — APPROVED** [review]
Code LGTM

**Pull request merged**
