### PR TITLE
python 3.9 comptibility fixes

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR...
- [x] replace encodestring for encodebytes
- [ ] ...

Fixes: #6962

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan help

**Review by rohityadavcloud — APPROVED** [review]
LGTM, tested test_accounts with the diff/change in cloudstackConnection.py on EL9.

**Comment by DaanHoogland** [comment]
@vladimirpetrov @borisstoyanov can you review this one?

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by kiranchavala** [comment]
@DaanHoogland , I did a test run with python 3.9 and was observing this exception 

```
kiran@kiran-ThinkPad-X1-Carbon-7th:~/Desktop/github-repos/shapeblue/cloudstack$ python --version
Python 3.9.16

kiran@kiran-ThinkPad-X1-Carbon-7th:~/Desktop/github-repos/shapeblue/cloudstack$ python3 --version
Python 3.9.16

kiran@kiran-ThinkPad-X1-Carbon-7th:~/Desktop/github-repos/shapeblue/cloudstack$ python tools/marvin/marvin/deployDataCenter.py -i setup/dev/advanced.cfg

==== Log Folder Path: /tmp/MarvinLogs/DeployDataCenter__Apr_20_2023_11_27_57_3O0NYX All logs will be available here ====

=== TestClient Creation Failed===


               
kiran@kiran-ThinkPad-X1-Carbon-7th:~/Desktop/github-repos/shapeblue/cloudstack$ cat /tmp/MarvinLogs/DeployDataCenter__Apr_20_2023_11_27_57_3O0NYX/runinfo.txt 
2023-04-20 11:27:57,572 - DEBUG - Parsing Test data successful
2023-04-20 11:27:57,572 - DEBUG - Payload: {'account': 'admin', 'command': 'listUsers', 'response': 'json'}
2023-04-20 11:27:57,572 - DEBUG - ========Sending GET Cmd : listUsers=======
2023-04-20 11:27:57,598 - ERROR - Exception:['Traceback (most recent call last):\n', '  File "/home/kiran/.pyenv/versions/3.9.16/lib/python3.9/site-packages/requests/models.py", line 971, in json\n    return complexjson.loads(self.text, **kwargs)\n', '  File "/home/kiran/.pyenv/versions/3.9.16/lib/python3.9/json/__init__.py", line 346, in loads\n    return _default_decoder.decode(s)\n', '  File "/home/kiran/.pyenv/versions/3.9.16/lib/python3.9/json/decoder.py", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n', '  File "/home/kiran/.pyenv/versions/3.9.16/lib/python3.9/json/decoder.py", line 355, in raw_decode\n    raise JSONDecodeError("Expecting value", s, err.value) from None\n', 'json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/home/kiran/.pyenv/versions/3.9.16/lib/python3.9/site-packages/marvin/cloudstackConnection.py", line 309, in __parseAndGetResponse\n    cmd_response.json(),\n', '  File "/home/kiran/.pyenv/versions/3.9.16/lib/python3.9/site-packages/requests/models.py", line 975, in json\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\n', 'requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n']
Traceback (most recent call last):
  File "/home/kiran/.pyenv/versions/3.9.16/lib/python3.9/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/kiran/.pyenv/versions/3.9.16/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/kiran/.pyenv/versions/3.9.16/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/kiran/.pyenv/versions/3.9.16/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kiran/.pyenv/versions/3.9.16/lib/python3.9/site-packages/marvin/cloudstackConnection.py", line 309, in __parseAndGetResponse
    cmd_response.json(),
  File "/home/kiran/.pyenv/versions/3.9.16/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by DaanHoogland** [comment]
@blueorangutan test keepEnv

**Comment by DaanHoogland** [comment]
@kiranchavala , i think you have an environmental issue:
```
$ python --version
Python 3.9.13
$ python3 --version
Python 3.9.13
$ python tools/marvin/marvin/deployDataCenter.py -i setup/dev/advanced.cfg 

==== Log Folder Path: /tmp/MarvinLogs/DeployDataCenter__Apr_28_2023_11_42_16_GILDD2 All logs will be available here ====

==== Deploy DC Started ====

=== Data Center Settings are dumped to /tmp/MarvinLogs/DeployDataCenter__Apr_28_2023_11_42_16_GILDD2/dc_entries.obj===

====Deploy DC Successful=====

```

**Comment by rohityadavcloud** [comment]
I think this should be merged @kiranchavala @DaanHoogland - would unblock a lot of people on newer distros and verions using py3 > python 3.8

**Review by rohityadavcloud — APPROVED** [review]

**Pull request merged**
