### PR TITLE
kvm: fix ovs network creation issue

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes the issue below when create a ovs network
```
2024-10-29 16:02:45,089 WARN  [resource.wrapper.LibvirtOvsFetchInterfaceCommandWrapper] (agentRequest-Handler-2:null) (logid:e716722e) Network interface: ''cloudbr1'' not found
```

This is a regression of a previous security release
see "framework/cluster: improve cluster service, integration API server"

since we now use NetworkInterface.getByName to get network interface, we should NOT add single quotes before/after the label.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [x] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
the OVS functionality is broken in the following releases
- 4.18.2.1
- 4.18.2.2
- 4.18.2.3
- 4.18.2.4
- 4.19.1.0
- 4.19.1.1
- 4.19.1.2

marked it as a BLOCKER

cc @rohityadavcloud @DaanHoogland @borisstoyanov @GutoVeronezi

**Comment by weizhouapache** [comment]
cc @rajujith

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Comment by weizhouapache** [comment]
@blueorangutan LLpackage

**Review by rohityadavcloud — APPROVED** [review]

**Review by DaanHoogland — APPROVED** [review]

**Comment by weizhouapache** [comment]
@blueorangutan LLtest

**Comment by weizhouapache** [comment]
@blueorangutan LLtest ubuntu22 kvm-ubuntu22

**Comment by weizhouapache** [comment]
@blueorangutan LLtest alma8 kvm-alma8

**Review by JoaoJandre — APPROVED** [review]

**Comment by weizhouapache** [comment]
tested on centos7 and ubuntu 24 with OVS, looks good

cc @rohityadavcloud @DaanHoogland @GutoVeronezi

**Review by shwstppr — APPROVED** [review]
LGTM

**Pull request merged**
