### PR TITLE
CLOUDSTACK-9120 READ.ME files describing the purpose of test directories

### PR DESCRIPTION
**Pull request by DaanHoogland**

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@remibergsma do I need to promote this? it is purely to describe what is in the test dirs and holds no execution value.

**Comment by remibergsma** [comment]
@DaanHoogland I'm OK with putting them there, but please make them consistent. Add header on top, then the message on the bottom.

**Comment by DaanHoogland** [comment]
@remibergsma good point, will do

**Comment by GabrielBrascher** [comment]
LGTM. Based on the lack of code.

**Comment by rhtyd** [comment]
@DaanHoogland can you move them to a wiki?

**Pull request closed without merging**
