### PR TITLE
api: Allow updating VM settings when custom constrained offering is used

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

This PR fixes: https://github.com/apache/cloudstack/issues/6131

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [X] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?
1. Create a VM using custom constrained compute offering
2. Stop VM 
3. Update VM settings - successfully gets updated
4. Start VM - vm starts successfully

### CODE REVIEW

**Review by shwstppr — APPROVED** [review]

**Comment by DaanHoogland** [comment]
code looks good @Pearl1594 but can you base on 4.16, please?

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Review by DaanHoogland — APPROVED** [review]

**Comment by DaanHoogland** [comment]
code here looks good and the `test_nic` error has been popping up in a lot of PRs lately. (cc @nvazquez @weizhouapache )

**Comment by weizhouapache** [comment]
> code here looks good and the `test_nic` error has been popping up in a lot of PRs lately. (cc @nvazquez @weizhouapache )

@DaanHoogland 
the issue should have been fixed by #5645 

```
test_01_nic (tests.smoke.test_nic.TestNic): DEBUG: Exception during NIC test SETUP!: Execute cmd: createnetwork failed, due to: errorCode: 431, errorText:The VLAN tag to use for new guest network, 1201 is already being used for dynamic vlan allocation for the guest network in zone pr6136-t3657-kvm-centos7
```

looks like a trillian config issue

**Pull request merged**
