### PR TITLE
ui: Fix breadcrumb discrepancy

### PR DESCRIPTION
**Pull request by davidjumani**
### Description

This PR aligns the breadcrumb with the info card display name

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

#### Before :

Screenshot from 2021-03-10 15-00-19

#### After :

Screenshot from 2021-03-10 15-00-46

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan ui

**Comment by utchoang** [comment]
@davidjumani can you change the base branch of the PR and rebase your PR branch to 4.15?

**Comment by davidjumani** [comment]
@utchoang Done!
@blueorangutan ui

**Review by utchoang — APPROVED** [review]
LGTM!

**Comment by rhtyd** [comment]
LGTM

**Pull request merged**
