### PR TITLE
ui: Move resource icon to first column for VM list view

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

This PR moves the resource icon to the first column - VM Name - in the Instance List View. With the following change https://github.com/apache/cloudstack/commit/413d10dd8106af9b3c369c1a393fbcca5e7217ce#diff-93b52572e13887859e26011826bd9744351c29e7a0de514ea308d503113a13e3L41-R41 the icon now appears on the second column, which looks odd.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [X] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X ] Minor
- [ ] Trivial

### How Has This Been Tested?
Prior Fix:
image

Post Fix:
image

### CODE REVIEW

**Comment by Pearl1594** [comment]
@blueorangutan ui

**Review by DaanHoogland — APPROVED** [review]

**Review by shwstppr — APPROVED** [review]

**Comment by DaanHoogland** [comment]
hm, default dark mode??? i think i should have -1ed something somewhere :(

**Comment by Pearl1594** [comment]
Sorry @DaanHoogland , are you referring to the Icons appearing in black as dark-mode?

**Review by GabrielBrascher — APPROVED** [review]
@Pearl1594 I think that @DaanHoogland comment regards the UI [in https://github.com/apache/cloudstack/pull/5465#issuecomment-921739097] being on Dark mode by default. I also was not expecting when logged in to check this PR.

However, the dark mode is not in the context of this PR.
I am LGTM with this PR.

**Review by utchoang — APPROVED** [review]

**Review by nvazquez — APPROVED** [review]
LGTM

**Pull request merged**
