### PR TITLE
javascript:TrailingComma sonacube issue considered blocker removed

### PR DESCRIPTION
**Pull request by DaanHoogland**
simple change in several locations

### CODE REVIEW

**Comment by koushik-das** [comment]
LGTM based on the changes

**Comment by wido** [comment]
The fix seems good to me. I would like to LGTM, but I can't test JavaScript that easily.

Isn't there a lint-check for JS?

**Comment by bhaisaab** [comment]
LGTM

**Comment by remibergsma** [comment]
LGTM, built a cloud on this PR and clicked through the UI which worked fine.

screen shot 2015-11-23 at 13 05 07

screen shot 2015-11-23 at 13 05 42

**Pull request merged**
