### PR TITLE
CLOUDSTACK-8913: Search box in Templates tab out of alignment

### PR DESCRIPTION
**Pull request by nitin-maharana**
Increased the margin and padding to accomodate all the boxes inside toolbar.

### CODE REVIEW

**Comment by nitin-maharana** [comment]
Sorry Its Decreased not increased.

**Comment by runseb** [comment]
@nitin-maharana LGTM +1 based on code review.
Maybe adding two snapshots to compare would help review (just a thought)

**Comment by nitin-maharana** [comment]
Hi @runseb, Added two snapshots of before change and after change.

Before Change:
pr_891_before_change

After Change:
pr_891_after_change

**Comment by runseb** [comment]
@nitin-maharana thanks for this. 
LGTM +1 based on code review and look at snapshot.
Somehow might want to compile and test fresh.

**Comment by bhaisaab** [comment]
LGTM. Thanks (have seen this on both 4.5/master).
Once this is merged on master, we'll need to backport this too 4.5 as well.

**Comment by remibergsma** [comment]
Ping @bhaisaab to backport to 4.5 as it is now merged to master.

**Comment by bhaisaab** [comment]
Thanks @remibergsma will do

**Pull request merged**
