### PR TITLE
CLOUDSTACK-9893 / CLOUDSTACK-8239 fix test_deploy_virtio_scsi_vm.py

### PR DESCRIPTION
**Pull request by nathanejohnson**
Fix issue where unsupported hypervisors were not skipping tests

Fix issue where the template referenced no longer existed on openvm.eu

@karuturi @DaanHoogland @serg38 @kiwiflyer

### CODE REVIEW

**Comment by nathanejohnson** [comment]
test results on kvm:

Test that libvirt properly created domain with scsi controller ... === TestName: test_01_verify_libvirt | Status : SUCCESS ===
ok
Verify that libvirt settings are as expected after a VM stop / start ... === TestName: test_02_verify_libvirt_after_restart | Status : SUCCESS ===
ok
Verify that libvirt settings are expected after a disk add ... === TestName: test_03_verify_libvirt_attach_disk | Status : SUCCESS ===
ok
Verify that guest sees scsi controller and disks ... === TestName: test_04_verify_guest_lspci | Status : SUCCESS ===
ok
Update os type to Ubuntu, change vm details rootdiskController ... === TestName: test_05_change_vm_ostype_restart | Status : SUCCESS ===
ok
Verify that guest sees scsi controller and disks after switching ostype and rdc ... === TestName: test_06_verify_guest_lspci_again | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 6 tests in 1110.727s

OK

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
code LGTM, i'll be kicking tests on vmware to make sure ;)

**Comment by DaanHoogland** [comment]
@blueorangutan test centos7 vmware-55u3

**Comment by karuturi** [comment]
code LGTM. will merge once the tests are ok.

**Comment by rhtyd** [comment]
LGTM. @nathanejohnson does this also affect 4.9, if so please change the base branch to 4.9 thanks.

**Comment by kiwiflyer** [comment]
@rhtyd The original PR was only pulled into master (4.10) as far as I'm aware.

**Comment by rhtyd** [comment]
Thanks @kiwiflyer

**Comment by nathanejohnson** [comment]
@DaanHoogland could you kick this off one more time?  I should have the issue with the class teardown resolved with the latest rebase

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-55u3

**Comment by nathanejohnson** [comment]
thanks @rhtyd and @DaanHoogland 

@karuturi looks like kvm tests succeed and other hypervisors should now properly skip the test. 
 Would you like to run any more tests or do you think this is sufficient for merging?

**Comment by rhtyd** [comment]
LGTM.
@blueorangutan package

**Comment by DaanHoogland** [comment]
@karuturi can you merge this?

**Pull request merged**
