### PR TITLE
a conditional to prevent creation of a field

### PR DESCRIPTION
**Pull request by DaanHoogland**
the files is based on volumes and will npe (if that's a thing in javascript)
  when applied in the snapshot dialog

## Description

Fixes: #3716
## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## Screenshots (if appropriate):
Screenshot 2019-11-28 at 11 09 16

## How Has This Been Tested?

manually (see screenshot)

### CODE REVIEW

**Comment by andrijapanicsb** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
Not sure why i thought this would work, maybe a copy error in my dev env.

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@GabrielBrascher @andrijapanicsb should we backport this to 4.13? It seems like a genuine regression to me.

**Comment by andrijapanicsb** [comment]
+1

**Comment by DaanHoogland** [comment]
ok, as this is already merged, i'll create a new PR

**Pull request merged**
