### PR TITLE
[FUTURE]CLOUDSTACK-8872: Replaced all occurences of Charset.forName(UTF-8) with StringUtils.getPreferredCharset().

### PR DESCRIPTION
**Pull request by borisroman**
This PR replaces all occurrences of Charset.forName("UTF-8") with StringUtils.getPreferredCharset(). 

This to ensure consistent encoding across all ACS components, even when UTF-8 is not available.

### CODE REVIEW

**Comment by wilderrodrigues** [comment]
Hi @borisroman 

Few months ago we had a thread on the list to discuss which PR flow we should have in place in order to increase ACS quality. The idea was:

* Each PR should contain:
  * Jira ticket
  * Proper description of the change: what it fixes / what is the improvement
  * Tests - either Unit or Integration

Except for the unit test part, which is already being covered by the StringUtilsTest class, the other 2 points are missing in your PR.

Could you please create a ticket and edit the PR description?

Cheers,
Wilder

**Comment by borisroman** [comment]
Hi @wilderrodrigues 

Thank you for your extensive comment. I've read through the thread you mentioned and added the required Jira ticket and PR description.

Thanks!

**Comment by wilderrodrigues** [comment]
Thanks, @borisroman ! :)

I will have a look at your PR again later today.

Cheers,
Wilder

**Comment by remibergsma** [comment]
@borisroman Can you force push this PR please and rebase it with current master? Then we can run some tests! Pinging @dahn to look at the code.

**Comment by borisroman** [comment]
@remibergsma @wilderrodrigues @DaanHoogland Done.

**Comment by borisroman** [comment]
Most of them have already been resolved.

**Pull request closed without merging**
