### PR TITLE
CLOUDSTACK-9123 - As a Developer I want the test_internal_lb.py to work with multiple hypervisors

### PR DESCRIPTION
**Pull request by wilderrodrigues**
This PR make the test_internal_lb.py work with other Hypervisors types.

   - Get hypervisor information from testClient.getHypervisorInfo()
   - Adds XenServer, HyperV and VMware hypervisors
   - Makes sure the OS type is "Other PV (64-bit)"

### CODE REVIEW

**Comment by wilderrodrigues** [comment]
Ping @remibergsma @borisroman @michaelandersen @miguelaferreira @DaanHoogland @karuturi 

* Environment
  * 1 KVM on CentOS 7.1
  * Management Server on CentOS 7.1
  * Agent + Common built from source

* Tests

```
nosetests --with-marvin --marvin-config=/data/shared/marvin/mct-zone2-kvm2-ISOLATED.cfg -s -a tags=advanced,required_hardware=true smoke/test_internal_lb.py
```

* Results

```
Test to verify access to loadbalancer haproxy admin stats page ... === TestName: test02_internallb_haproxy_stats_on_all_interfaces | Status : SUCCESS ===
ok
Test create, assign, remove of an Internal LB with roundrobin http traffic to 3 vm's ... === TestName: test_01_internallb_roundrobin_1VPC_3VM_HTTP_port80 | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 2 tests in 2867.658s

OK
/tmp//MarvinLogs/test_internal_lb_YAYUF4/results.txt (END)
```

* Environment
  * 1 XenServer 6.2
  * Management Server on CentOS 7.1

* Tests

```
nosetests --with-marvin --marvin-config=/data/shared/marvin/mct-zone1-xen1-ISOLATED.cfg -s -a tags=advanced,required_hardware=true smoke/test_internal_lb.py
```

* Results

```
Test to verify access to loadbalancer haproxy admin stats page ... === TestName: test02_internallb_haproxy_stats_on_all_interfaces | Status : SUCCESS ===
ok
Test create, assign, remove of an Internal LB with roundrobin http traffic to 3 vm's ... === TestName: test_01_internallb_roundrobin_1VPC_3VM_HTTP_port80 | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 2 tests in 1146.677s

OK
/tmp//MarvinLogs/test_internal_lb_NPZKJ3/results.txt (END)
```

**Comment by borisroman** [comment]
@wilderrodrigues @remibergsma I could only verify for KVM. 

Ran tests on Ubuntu 14.04 management/hypervisor.

```
Test to verify access to loadbalancer haproxy admin stats page ... === TestName: test02_internallb_haproxy_stats_on_all_interfaces | Status : SUCCESS ===
ok
Test create, assign, remove of an Internal LB with roundrobin http traffic to 3 vm's ... === TestName: test_01_internallb_roundrobin_1VPC_3VM_HTTP_port80 | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 2 tests in 2532.875s
```

LGTM :+1:

**Comment by wilderrodrigues** [comment]
Thanks, @borisroman!

@michaelandersen, have you already tested this against Xen?

By the way, I did both already.

Cheers,
Wilder

**Comment by michaelandersen** [comment]
Ran tests on Xenserver 6.2:

Results:
```
Test to verify access to loadbalancer haproxy admin stats page ... === TestName: test02_internallb_haproxy_stats_on_all_interfaces | Status : SUCCESS ===
ok
Test create, assign, remove of an Internal LB with roundrobin http traffic to 3 vm's ... === TestName: test_01_internallb_roundrobin_1VPC_3VM_HTTP_port80 | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 2 tests in 1064.773s

OK

```
Environment:

```
1 XenServer 6.2
Management Server on CentOS 7.1
```

Test command:
```
nosetests --with-marvin --marvin-config=/data/shared/marvin/mct-zone1-xen1.cfg -a tags=advanced,required_hardware=true test_internal_lb.py
```

LGTM!
good work @wilderrodrigues

**Comment by wilderrodrigues** [comment]
Thanks, @michaelandersen!

Ping @remibergsma @DaanHoogland - this one is ready to be merged.

Cheers,
Wilder

**Comment by remibergsma** [comment]
FYI: my tests also succeeded.

```
[root@cs1 integration]# cat  /tmp//MarvinLogs/test_internal_lb_88R1S8/results.txt 
Test to verify access to loadbalancer haproxy admin stats page ... === TestName: test02_internallb_haproxy_stats_on_all_interfaces | Status : SUCCESS ===
ok
Test create, assign, remove of an Internal LB with roundrobin http traffic to 3 vm's ... === TestName: test_01_internallb_roundrobin_1VPC_3VM_HTTP_port80 | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 2 tests in 1733.573s

OK
```

**Pull request merged**
