### PR TITLE
Fix lint errors

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR fixes pre-commit hook's lint errors to fix `pre-commit` github action.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Review by DaanHoogland — APPROVED** [review]
slipped through the maze. should have been cought before. thanks @vishesh92

**Comment by DaanHoogland** [comment]
I think only the gh actions should be enough on this one.

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@blueorangutan test keepEnv

**Comment by DaanHoogland** [comment]
@vishesh92 do you want to wait with merging this till after #7732 has been merged (forward)?
cc @weizhouapache

**Comment by vishesh92** [comment]
@DaanHoogland yes. Let's wait.

**Comment by DaanHoogland** [comment]
About https://github.com/apache/cloudstack/actions/runs/5475638802/jobs/9972019731?pr=7727 manual running the source_nat tests passes:
```
...
=== TestName: test_03_create_vpc_with_specified_source_nat_ip_address | Status : SUCCESS ===

=== TestName: test_04_change_source_nat_ip_address_for_vpc | Status : SUCCESS ===
....
```
and for kubernetes_clusters:
```
=== TestName: test_11_test_unmanaged_cluster_lifecycle | Status : SUCCESS ===
```
with no exception on tear down.

**Review by rohityadavcloud — APPROVED** [review]

**Pull request merged**
