### PR TITLE
[HEALTH][master/4.14] Health Check Run

### PR DESCRIPTION
**Pull request by yadvr**
This is just to check/run health checks - smoketests

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
closing in favour for a draft PR to guard extra

**Comment by DaanHoogland** [comment]
@blueorangutan sweep

**Pull request closed without merging**
