### PR TITLE
Limit API from trying to start a VM that is already running

### PR DESCRIPTION
**Pull request by kioie**
## Description

Enhancement for issue #2736

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## Screenshots (if appropriate):
Screenshot 2020-03-18 at 16 06 54

## How Has This Been Tested?

1. Start a VM
2. With cloudmonkey, start the same VM
3. Observe the result
Response should fail the job and say VM is already in running state.

### CODE REVIEW

**Comment by DaanHoogland** [comment]
I don't mind this code but it seems to me that there is no state transition from started to started and hence this should already fail. If it doesn't there is a bug in the statemachine implementation or - design.

**Comment by GabrielBrascher** [comment]
I just tested on the master and it indeed prompts no exception when starting a VM that is already Running; therefore it makes sense to have this PR merged.

@DaanHoogland are you OK with this one?

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Pull request merged**
