### PR TITLE
created VPC message a little less misleading

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR...

Fixes: #9395

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan ui

**Review by JoaoJandre — APPROVED** [review]
CLGTM

**Review by hsato03 — APPROVED** [review]
lgtm

**Comment by hsato03** [comment]
> > lgtm
> 
> @hsato03 did you test?

@DaanHoogland Yes. Tested by creating a VPC and some tiers for it.

**Pull request merged**
