### PR TITLE
UI: Fixes UI bug

### PR DESCRIPTION
**Pull request by utchoang**
### Description

This PR for fixes some UI Bugs

- [x] The project selected color is not displayed after switching project
- [x] Project view, the cards are not separated but stick together
- [x] Dashboard: The color of the selected zone is not displayed
- [x] Dark mode: Hover through row tables that are discolored

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):
image
image
image
image

### CODE REVIEW

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by utchoang** [comment]
AFTER Fixed:
image
image
image
image

**Review by Pearl1594 — APPROVED** [review]
LGTM

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Pull request merged**
