### PR TITLE
pre-commit: enable markdownlint rule `MD012`

### PR DESCRIPTION
**Pull request by jbampton**
MD012 no-multiple-blanks - Multiple consecutive blank lines

https://github.com/DavidAnson/markdownlint/blob/main/doc/md012.md

### Description

This PR cleans up and standardizes the Markdown files.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [X] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

Ran locally:

`pre-commit run --all-files`

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]

**Comment by jbampton** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Review by vishesh92 — APPROVED** [review]
clgtm

**Comment by jbampton** [comment]
@blueorangutan package

**Comment by jbampton** [comment]
@blueorangutan package

**Pull request merged**
