### PR TITLE
server: fix additional zones cannot be removed

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR reverts a change in #9212 

Got an exception when delete a zone

```
com.cloud.utils.exception.CloudRuntimeException: The zone cannot be deleted because there are Secondary storages in this zone
```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
I can see how this might fix a regression @weizhouapache , but isn't ZONE the proper Scope for this query logically? It seems like the solution should be in a data repair???

**Comment by weizhouapache** [comment]
> I can see how this might fix a regression @weizhouapache , but isn't ZONE the proper Scope for this query logically? It seems like the solution should be in a data repair???

@DaanHoogland 
if the scope if REGION, it means the image store can be accessed by all zones
the method lists
- image stores with scope=REGION
- and image store with scope=ZONE and data_center_id= <passed zoneid>

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@blueorangutan test

**Review by rohityadavcloud — APPROVED** [review]

**Pull request merged**
