### PR TITLE
Corrected sentence

### PR DESCRIPTION
**Pull request by thinktwo**
Corrected the sentence as the previous one didn't make sense

### CODE REVIEW

**Comment by pdube** [comment]
LGTM

**Comment by ke4qqq** [comment]
Thanks for the patch! 

LGTM

**Comment by remibergsma** [comment]
@thinktwo Thanks for the patch! Could you please force push your commits again so Jenkins can do another build? It failed although I believe the problem is not introduced in your PR. When the build succeeds, I will merge it.

**Comment by thinktwo** [comment]
@remibergsma Done.

**Pull request merged**
