### PR TITLE
delete F5 and SRX plugins

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR removes the plugins dependend on the stale iControl jar.

Fixes: #6976 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
LGTM, @DaanHoogland could you start a discussion thread on dev + users ML

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
keeping as draft until consensus is reached on this

**Comment by rohityadavcloud** [comment]
Let's merge this if there are no objections on your proposal thread by the freeze date @DaanHoogland !

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
@blueorangutan test rocky8 xcpng82

**Pull request merged**
