### PR TITLE
ui: Refresh after async job completed only on current / parent page

### PR DESCRIPTION
**Pull request by davidjumani**
### Description

Fixes https://github.com/apache/cloudstack/issues/5172

Ensures that the page is refreshed after an async job only if it is the same / parent page being viewed

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan build ui

**Comment by davidjumani** [comment]
@blueorangutan ui

**Comment by davidjumani** [comment]
@blueorangutan ui

**Review by utchoang — APPROVED** [review]
LGTM

**Review by DaanHoogland — APPROVED** [review]
clgtm, but not sure what `eventBus.$emit('async-job-complete')` does except for redrawing  a page. quick monkey test succeeded but like to play more than just the simplest scenario.

**Comment by DaanHoogland** [comment]
tested with stop/start/delete/recover VM all good merging

**Pull request merged**
