### PR TITLE
an inject annotation short

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR fixes a small regression as can be seen in https://github.com/apache/cloudstack/pull/5201#issuecomment-933030293
It has been showing in lots of PRs lately

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by weizhouapache — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Review by sureshanaparti — APPROVED** [review]
LGTM

**Review by nvazquez — APPROVED** [review]
LGTM, let's wait for the matrix test results

**Review by rhtyd — APPROVED** [review]

**Pull request merged**
