### PR TITLE
CLOUDSTACK-8990: start a stopped machine on a specific determinable host on UI

### PR DESCRIPTION
**Pull request by ustcweizhou**

### CODE REVIEW

**Comment by borisroman** [comment]
@ustcweizhou Thanks for implementing this feature. I've got 1 comment, could you select the first host available instead of none? See image.

screenshot from 2015-10-26 13 11 21

**Comment by borisroman** [comment]
@remibergsma @karuturi I've run the following tests:

```

**Comment by ustcweizhou** [comment]
@borisroman None means cloudstack will allocate the host to start the vm. I think it is also needed for users. Not everyone wants to specify a host, right?

**Comment by borisroman** [comment]
@ustcweizhou Oke! Though can you make that visible to the user? Now it seems like you "have to" select a host, like you're forced to do so.

**Comment by ustcweizhou** [comment]
@borisroman sorry my comment made you confused. The users I meant is one who use cloudstack for deployment. 
This window is only visible for root admins. For non-root users (defined in cloudstack), they still use the old window.

**Comment by borisroman** [comment]
@ustcweizhou By "user" I meant the root admin. So my question is: Could you adjust the dialog you created to show something like "Default" instead of an empty label.

**Comment by ustcweizhou** [comment]
@borisroman yes, sure

**Comment by ustcweizhou** [comment]
change default host from empty to 'Default'. done.

**Comment by wido** [comment]
LGTM

Nice feature indeed :)

**Comment by remibergsma** [comment]
@borisroman Can you review this again please?

**Comment by borisroman** [comment]
@remibergsma LGMT :+1: 
screenshot from 2015-10-27 21 36 41

**Pull request merged**
