### PR TITLE
[UI] Use CPU frequency of constrained offerings when importing VMs

### PR DESCRIPTION
**Pull request by SadiJr**
### Description

Using the VMware hypervisor, when importing a VM from vCenter via UI, if a custom constrained offering is used, the CPU frequency is not passed to the backend, causing an error. This PR aims to fix this behavior.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### How Has This Been Tested?
It was tested in a local lab:

1. I created one new VM and one custom constrained offering;
2. I tried importing this VM as root admin with the newly created custom constrained offering;
3. Before, the VM was not imported with an error of CPU frequency;
4. Now, the VM is correctly imported.

### CODE REVIEW

**Review by stephankruggg — APPROVED** [review]
LGTM

**Comment by DaanHoogland** [comment]
@stephankruggg did you test or just review?

**Comment by DaanHoogland** [comment]
> > @stephankruggg did you test or just review?
> 
> CLGTM* Not manually tested, sorry for the typo.

That's ok, I just want to make sure.

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Pull request merged**
