### PR TITLE
VMware: add support for 8.0b (8.0.0.2), 8.0c (8.0.0.3)

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR adds 

- The support (hypervisor capabilities) for VMware 8.0b (8.0.0.2) and 8.0c (8.0.0.3)

Refer to 
https://docs.vmware.com/en/VMware-vSphere/8.0/rn/vsphere-esxi-80b-release-notes/index.html
https://docs.vmware.com/en/VMware-vSphere/8.0/rn/vsphere-esxi-80c-release-notes/index.html

- The new guest os mappings introduced in VMware 8.0 (also supported by 8.0a and 8.0b/8.0c)

Refer to https://vdc-repo.vmware.com/vmwb-repository/dcr-public/c476b64b-c93c-4b21-9d76-be14da0148f9/04ca12ad-59b9-4e1c-8232-fd3d4276e52c/SDK/vsphere-ws/docs/ReferenceGuide/vim.vm.GuestOsDescriptor.GuestOsIdentifier.html

- An extra step to determine the guest os mappings for a hypervisor version

Since VMware 8, each minor update has a newer patch version. For example ESXi host of VMware 8.0b has hypervisor version 8.0.0.2. It is different from previous versions, for example, ESXi host of VMware 7.0 update 3a/3b/3c have the same hypervisor version 7.0.3.0 (not 7.0.3.1/7.0.3.2/7.0.3.3).

This PR adds an extra step to determine the guest os mappings for a hypervisor version: If guest os mapping does not exist, then search for the guest os mapping of parent version. For example
  X if guest os mapping of 8.0.0.2 does not exist, then search for guest os mapping for 8.0
  X if guest os mapping of 8.0.3.2 does not exist, then search for guest os mapping for 8.0.3

Based on this, we do not need to add guest os mappings for 8.0b (8.0.0.2) and 8.0c (8.0.0.3), the guest os mappings for VMware 8.0 will be used.

Pleae note:
The hypervisor capabilitiy for VMware 8.0U1 (8.0.1.0) has been added in this PR, but there are some critical failures in the testing on VMware 8.0U1, thus it is not supported. (see more information at #7572 )

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by rohityadavcloud — APPROVED** [review]

**Comment by weizhouapache** [comment]
@blueorangutan alma8 vmware-80

**Comment by weizhouapache** [comment]
@blueorangutan alma8 vmware-80

**Comment by weizhouapache** [comment]
@blueorangutan test alma8 vmware-80

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 vmware-80

**Comment by weizhouapache** [comment]
@blueorangutan test alma8 vmware-80

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan SFpackage

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan LLtest rocky8 vmware-80

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 vmware-80

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by weizhouapache** [comment]
@blueorangutan test ubuntu22 vmware-80

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 vmware-80

**Comment by borisstoyanov** [comment]
@blueorangutan test matrix

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test vmware

**Comment by borisstoyanov** [comment]
@blueorangutan test vmware keepEnv

**Comment by borisstoyanov** [comment]
@blueorangutan help

**Comment by weizhouapache** [comment]
> Thanks @weizhouapache could you merge latest main

thanks @rohityadavcloud 
done merged latest 4.18

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 vmware-80

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test u22 vmware-80

**Comment by weizhouapache** [comment]
@blueorangutan test ubuntu22 vmware-80

**Review by NuxRo — APPROVED** [review]
LGTM based on hands-on testing

**Comment by rohityadavcloud** [comment]
cc @weizhouapache @borisstoyanov @DaanHoogland @NuxRo I've started a discussion thread on VMware forum - https://communities.vmware.com/t5/ESXi-Discussions/VMware-disk-errors-when-booting-on-ESXi-8-0u1a/m-p/2980935#M289426

I tried to setup a mbx template and I can consistently reproduce issues with VMware 8.0u1a esxi (I think vcenter isn't an issue), I tried both NFS and local/datastore on ESXi 8.0u1 (using latest build/iso VMware-VMvisor-Installer-8.0U1a-21813344.x86_64.iso).

**Comment by rohityadavcloud** [comment]
is this ready for review/merging @weizhouapache @DaanHoogland @NuxRo ?

**Comment by weizhouapache** [comment]
> is this ready for review/merging @weizhouapache @DaanHoogland @NuxRo ?

@rohityadavcloud 
Andrija is doing final review/testing

**Comment by weizhouapache** [comment]
> cc @weizhouapache @borisstoyanov @DaanHoogland @NuxRo I've started a discussion thread on VMware forum - https://communities.vmware.com/t5/ESXi-Discussions/VMware-disk-errors-when-booting-on-ESXi-8-0u1a/m-p/2980935#M289426
> 
> I tried to setup a mbx template and I can consistently reproduce issues with VMware 8.0u1a esxi (I think vcenter isn't an issue), I tried both NFS and local/datastore on ESXi 8.0u1 (using latest build/iso VMware-VMvisor-Installer-8.0U1a-21813344.x86_64.iso).

thanks @rohityadavcloud 
I have created a github issue #7572 for follow-up

**Comment by andrijapanicsb** [comment]
@blueorangutan package

**Review by andrijapanicsb — APPROVED** [review]
LGTM after extensive testing and Int. Review.

Waiting for smoke tests to pass, then can merge.

**Comment by andrijapanicsb** [comment]
@blueorangutan LLpackage

**Comment by andrijapanicsb** [comment]
@blueorangutan test rocky8 vmware-80

**Comment by andrijapanicsb** [comment]
@blueorangutan LLtest rocky8 vmware-80

**Comment by andrijapanicsb** [comment]
@blueorangutan LLtest ubuntu22 vmware-80

**Comment by andrijapanicsb** [comment]
@blueorangutan test ubuntu22 vmware-80

**Comment by andrijapanicsb** [comment]
@blueorangutan test rocky8 vmware-80

**Comment by andrijapanicsb** [comment]
@blueorangutan test ubuntu22 vmware-80

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 vmware-80

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 vmware-67u3

**Comment by weizhouapache** [comment]
@blueorangutan test ubuntu22 vmware-80

**Comment by weizhouapache** [comment]
@blueorangutan test ubuntu22 vmware-80

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 vmware-67u3

**Comment by weizhouapache** [comment]
@blueorangutan test ubuntu22 vmware-80

**Pull request merged**
