### PR TITLE
ui: show nicAdapter selection for VMware non-readfromova template

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

NIC Adapter type option is missing in Register/Upload template form.
This PR fixes the behaviour

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):
Before:
Screenshot from 2021-09-10 14-52-41

After:
Screenshot from 2021-09-10 17-14-06

### How Has This Been Tested?
Screenshot from 2021-09-10 14-39-06

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan ui

**Review by nvazquez — APPROVED** [review]
Thanks @shwstppr - LGTM

**Review by rhtyd — APPROVED** [review]

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by shwstppr** [comment]
@blueorangutan ui

**Review by utchoang — APPROVED** [review]

**Pull request merged**
