### PR TITLE
vpc: dnsmasq is not started if use.external.dns is true

### PR DESCRIPTION
**Pull request by ustcweizhou**
### Description

This PR fixes the issue that dnsmasq cannot be started in VPC VR is use.external.dns is true

Steps to reproduce the issue
(1) change global setting use.external.dns to true
(2) create vpc
(3) create vpc tier and a vm
(4) restart VPC VR, or restart VPC with cleanup
(5) check VPC VR, dnasmasq is not started with error
```
Mar 12 14:15:07 r-999-VM dnsmasq[11176]: dnsmasq: bad IP address at line 5 of /etc/dnsmasq.d/cloud.conf
Mar 12 14:15:07 r-999-VM dnsmasq[11176]: bad IP address at line 5 of /etc/dnsmasq.d/cloud.conf
Mar 12 14:15:07 r-999-VM dnsmasq[11176]: FAILED to start up
```
dnsmasq config
```
root@r-999-VM:~# cat /etc/dnsmasq.d/cloud.conf
dhcp-hostsfile=/etc/dhcphosts.txt
listen-address=127.0.0.1,192.168.20.1
dhcp-range=set:interface-eth2-0,192.168.20.1,static
dhcp-option=tag:interface-eth2-0,15,cs2cloud.internal
dhcp-option=tag:interface-eth2-0,6,
dhcp-option=tag:interface-eth2-0,3,192.168.20.1
dhcp-option=tag:interface-eth2-0,1,255.255.255.240
```

with this PR, dnsmasq config is good and dnsmasq is running
```
root@r-999-VM:~# cat /etc/dnsmasq.d/cloud.conf
dhcp-hostsfile=/etc/dhcphosts.txt
listen-address=127.0.0.1,192.168.20.1
dhcp-range=set:interface-eth2-0,192.168.20.1,static
dhcp-option=tag:interface-eth2-0,15,cs2cloud.internal
dhcp-option=tag:interface-eth2-0,6,8.8.8.8
dhcp-option=tag:interface-eth2-0,3,192.168.20.1
dhcp-option=tag:interface-eth2-0,1,255.255.255.240

```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@weizhouapache I'm unable to reproduce the issue
dnsmasq comes up fine

use.external.dns = false
Screenshot from 2021-03-15 12-44-59

use.external.dns = true
Screenshot from 2021-03-15 12-42-31

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
> @weizhouapache I'm unable to reproduce the issue
> dnsmasq comes up fine
> Is there anything that was missed?
> 
> * Set use.external.dns = true
> * Created a VPC
> * Created a tier
> * Brought up a VM
> * Checked dnsmasq status and config
> 
> #### use.external.dns = false
> Screenshot from 2021-03-15 12-44-59
> 
> #### use.external.dns = true
> Screenshot from 2021-03-15 12-42-31

@davidjumani can you share the content of /etc/cloudstack/guestnetwork.json in VR ?

**Comment by davidjumani** [comment]
@weizhouapache This is when use.external.dns = false

Screenshot from 2021-03-15 13-40-28

use.external.dns = true

Screenshot from 2021-03-15 13-43-26

**Comment by weizhouapache** [comment]
> @weizhouapache This is when use.external.dns = false
> 
> Screenshot from 2021-03-15 13-40-28
> 
> use.external.dns = true
> 
> Screenshot from 2021-03-15 13-43-26

@davidjumani thanks.
'dns' is missing in my testing, strange. It might be caused by different vpc network offerings. I will check .

**Comment by weizhouapache** [comment]
> > @weizhouapache This is when use.external.dns = false
> > Screenshot from 2021-03-15 13-40-28
> > use.external.dns = true
> > Screenshot from 2021-03-15 13-43-26
> 
> @davidjumani thanks.
> 'dns' is missing in my testing, strange. It might be caused by different vpc network offerings. I will check .

@davidjumani could you please restart the vpc vr  and check again ?

**Review by DaanHoogland — APPROVED** [review]

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@weizhouapache Faced the error when rebooting the router, fixed with this change!

**Review by davidjumani — APPROVED** [review]

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by davidjumani** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@davidjumani can you check why we've so many failures? Is it because of the PR or env?
@blueorangutan test

**Comment by davidjumani** [comment]
@rhtyd Was an env issue. The new env is running fine ^^

**Pull request merged**
