### PR TITLE
CLOUDSTACK-9069: Newly added project is not showing in the drop down until the browser is refreshed.

### PR DESCRIPTION
**Pull request by nitin-maharana**
The created or deleted project was added to/deleted from the list but it was not being updated.
Now it updates the list at the same time.

### CODE REVIEW

**Comment by bhaisaab** [comment]
LGTM

**Comment by rafaelweingartner** [comment]
Isn't this PR the same as #1082?

**Comment by nitin-maharana** [comment]
@rafaelweingartner This PR will merge with current master. and #1082 Will merge in branch 4.6. Thanks.

**Comment by nitin-maharana** [comment]
Closing this PR. As #1082 is there to merge in 4.6. Thanks.

**Pull request closed without merging**
