### PR TITLE
test/vmware: add live migratevmwithvolume test and fix

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Current tests (for VMware) in test_vm_life_cyle.py for migrating VM with volume only do offline migration.
Fix for format exception in `relocateVirtualMachine` method.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

Ran updated `test/integration/smoke/test_vm_life_cycle.py` for a VMware env.
```
[root@pr5181-t1519-vmware-70u1-marvin marvin]# nosetests --with-xunit --xunit-file=results.xml --with-marvin --marvin-config=./pr5181-t1519-vmware-70u1-advanced-cfg -s -a tags=advanced --hypervisor=VMware tests/smoke/test_vm_life_cycle.py

==== Marvin Init Started ====

=== Marvin Parse Config Successful ===

=== Marvin Setting TestData Successful===

==== Log Folder Path: /marvin/MarvinLogs/Aug_06_2021_20_17_52_5YIVVL. All logs will be available here ====

=== Marvin Init Logging Successful===

==== Marvin Init Successful ====
=== TestName: test_advZoneVirtualRouter | Status : SUCCESS ===

=== TestName: test_deploy_vm | Status : SUCCESS ===

=== TestName: test_deploy_vm_multiple | Status : SUCCESS ===

=== TestName: test_01_offline_migrate_VM_and_root_volume | Status : SUCCESS ===

=== TestName: test_02_offline_migrate_VM_with_two_data_disks | Status : SUCCESS ===

=== TestName: test_03_live_migrate_VM_with_two_data_disks | Status : SUCCESS ===

=== TestName: test_04_migrate_detached_volume | Status : SUCCESS ===

=== TestName: test_01_unmanage_vm_cycle | Status : SUCCESS ===

=== TestName: test_01_vapps_vm_cycle | Status : SUCCESS ===
...
```
[test-logs.tar.gz](https://github.com/apache/cloudstack/files/6947916/test-logs.tar.gz)

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
68f6ac3 changes will be tested in #5288 
@blueorangutan test centos7 vmware-65u2

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-65u2

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-65u2

**Comment by rhtyd** [comment]
@blueorangutan package

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Review by GabrielBrascher — APPROVED** [review]

**Review by nvazquez — APPROVED** [review]
Thanks @shwstppr. Code LGTM

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test centos7 vmware67-u3

**Comment by nvazquez** [comment]
@blueorangutan test centos7 vmware-67u3

**Review by DaanHoogland — APPROVED** [review]

**Pull request merged**
