### PR TITLE
Generate cloud-init multipart user data for template append policy

### PR DESCRIPTION
**Pull request by nvazquez**
### Description

This PR introduces the concept of a user data provider to handle the user data concatenation in case a template has an APPEND policy and a VM also has user data.

The cloud-init user data provider is added as the default provider. It concatenates the template and VM user data as a multipart MIME message

Supported data formats: https://cloudinit.readthedocs.io/en/latest/explanation/format.html#user-data-formats

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### How Has This Been Tested?
- Add user data for different types (cloud-config, bash scripts)
- Register a template and link userdata with APPEND policy
- Deploy VM from the template and link another existing userdata
- Verify the generated user data is a multipart MIME message

### CODE REVIEW

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by kiranchavala** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@nvazquez @kiranchavala there seems to be some merge conflicts, I think that's why we see the build failures

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Review by kiranchavala — APPROVED** [review]
LGTM, Manually tested the issue, the multipart userdata is working correctly

1. Register a user-data 

#cloud-config
runcmd:
  - mkdir /home/ubuntu/kiran
  - echo kiran says hi >> /home/ubuntu/kiran/sample.txt 

2. Add the following user-data content to a cloud-init based template  with userdata append policy


3. When launching a vm pass the following user-data

#cloud-config
write_files:
  - path: /home/ubuntu/kiran/sample.txt
    content: |
      Here is a line.
      Another line is here.



4. Login to the vm and aceess the user-data

wget "http://10.1.1.1/latest/user-data"

The resulting user-data is




MIME-Version: 1.0
Content-Type: multipart/mixed;
	boundary="----=_Part_22_215298824.1688133183169"

------=_Part_22_215298824.1688133183169
Content-Type: text/cloud-config; charset=UTF-8
Content-Transfer-Encoding: base64

I2Nsb3VkLWNvbmZpZwpydW5jbWQ6CiAgLSBta2RpciAvaG9tZS91YnVudHUva2lyYW4KICAtIGVj
aG8ga2lyYW4gc2F5cyBoaSA+PiAvaG9tZS91YnVudHUva2lyYW4vc2FtcGxlLnR4dCA=
------=_Part_22_215298824.1688133183169
Content-Type: text/cloud-config; charset=UTF-8
Content-Transfer-Encoding: base64

I2Nsb3VkLWNvbmZpZwp3cml0ZV9maWxlczoKICAtIHBhdGg6IC9ob21lL3VidW50dS9raXJhbi9z
YW1wbGUudHh0CiAgICBjb250ZW50OiB8CiAgICAgIEhlcmUgaXMgYSBsaW5lLgogICAgICBBbm90
aGVyIGxpbmUgaXMgaGVyZS43
------=_Part_22_215298824.1688133183169--

**Comment by rohityadavcloud** [comment]
@nvazquez can you review the intermittent failures?

**Review by shwstppr — COMMENTED** [review]
Code LGTM

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Review by harikrishna-patnala — APPROVED** [review]
Code LGTM. let's wait for the test results. Thanks @nvazquez

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Comment by kiranchavala** [comment]
@blueorangutan package

**Pull request merged**
