### PR TITLE
api,engine/schema,server: vm readonly details rename

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Rename global configuration - `user.vm.readonly.ui.details` to `user.vm.readonly.details`

Documentation PR: https://github.com/apache/cloudstack-documentation/pull/206

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@weizhouapache setting name changed here

https://github.com/apache/cloudstack/pull/4629#issuecomment-770742309

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Review by rhtyd — APPROVED** [review]
LGTM but you need to check and update the docs as well @shwstppr

**Comment by rhtyd** [comment]
Is this ready for review/merging @shwstppr ?

**Comment by shwstppr** [comment]
@rhtyd I need to create doc PR. I'll update once done.

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
coed looks good

**Pull request merged**
