### PR TITLE
debian: add cpu-checker to debian/control

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR adds cpu-checker as a dependency for Debian/ubuntu distributions

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test ubuntu22 kvm-ubuntu22

**Comment by weizhouapache** [comment]
@blueorangutan test ubuntu24 kvm-ubuntu24

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
@blueorangutan test ubuntu24 kvm-ubuntu24

**Comment by rohityadavcloud** [comment]
Smoketests failures unrelated to this PR changes. Also verified cpu-checker pkg is available on old old/new stable Debian release (v11, v12)

**Pull request merged**
