### PR TITLE
console proxy: use AeadBase64Encryptor instead of AES/CBC/PKCS5Padding

### LINKED ISSUE #4694: Usage of "AES/CBC/PKCS5Padding" is insecure
In file https://github.com/apache/cloudstack/blob/0f3f2a09370a18301db28ec3d28efe746b6437c9/services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxyPasswordBasedEncryptor.java (at Line 61), insecure "AES/CBC/PKCS5Padding" was used for encryption.

Security Impact:

Cipher Block Chaining (CBC) with PKCS#5 padding (or PKCS#7) is susceptible to padding oracle attacks

Useful Resources:

https://rules.sonarsource.com/java/type/Vulnerability/RSPEC-4432

Solution we suggest:

Use GCM mode instead of ECB mode.

Please share with us your opinions/comments if there is any:

Is the bug report helpful?

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #4694

key will be used as password of AeadBase64Encryptor
iv will be used as aad of AeadBase64Encryptor

This need testing, at least:
- patch systemvm (cpvm)
- recreate systenvm (destroy and then recreate automatically)

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Review by rohityadavcloud — APPROVED** [review]
LGTM, is this critical for 4.18.0.0 @weizhouapache cc @DaanHoogland ?

**Comment by weizhouapache** [comment]
> LGTM, is this critical for 4.18.0.0 @weizhouapache cc @DaanHoogland ?

I think we can wait until 4.18.1.0.
currently this has not been reviewed and tested

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test keepEnv

**Comment by rohityadavcloud** [comment]
@weizhouapache cc @nvazquez @DaanHoogland @shwstppr - is it still relevant, do we need any testing to merge this or can this be merged now?

**Comment by DaanHoogland** [comment]
> @weizhouapache cc @nvazquez @DaanHoogland @shwstppr - is it still relevant, do we need any testing to merge this or can this be merged now?

code looks good but I have not tested this. I think this was a user request but don't recall exactly, @weizhouapache can you enlighten us?

**Comment by weizhouapache** [comment]
> > @weizhouapache cc @nvazquez @DaanHoogland @shwstppr - is it still relevant, do we need any testing to merge this or can this be merged now?
> 
> code looks good but I have not tested this. I think this was a user request but don't recall exactly, @weizhouapache can you enlighten us?

Sure @DaanHoogland 
See #4694 (also mentioned in the description of this PR)

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
we need to test cpvm patch/recreation manually

**Comment by DaanHoogland** [comment]
> we need to test cpvm patch/recreation manually

Can you add what you expect to the description of this PR, @weizhouapache ?

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
CLGTM and did
-     patch systemvm (cpvm)
-     recreate systenvm (destroy and then recreate automatically)
no errors returned, but I am not sure my tests where extensive enough.

**Comment by rohityadavcloud** [comment]
Testing LGTM @DaanHoogland
@weizhouapache - thnx could you review if that's enough to merge this or we need additional review, testing.

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix keepEnv

**Comment by DaanHoogland** [comment]
> Testing LGTM @DaanHoogland - did you manually test console against most supported hypervisors (KVM EL/Ubuntu, XCP-ng, VMware 6.7, 7.0) 

I tried kvm el, vmware and xen and these work.

**Pull request merged**
