### PR TITLE
[do not merge] server: Do NOT cleanup dhcp and dns when stop a vm

### PR DESCRIPTION
**Pull request by ustcweizhou**
## Description

According comment in PR #3608, dhcp and dns entries are cleaned up only when a VM is expunged.
Revert part of commit 8fb388e9312b917a8f36c7d7e3f45985a95ce773.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by ustcweizhou** [comment]
@rhtyd

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by andrijapanicsb** [comment]
This absolutely requires manual testing (that also means #3608).

No merging until tested thoroughly, please!
(I'll test myself as well)

**Comment by andrijapanicsb** [comment]
In short - NOTHING IS CLEANED at all, whatsoever...

Test:
ENV built based from packages built from this PR (VMware 6.5u, CenOS7 mgmt) - clean install.

Created Isolated network (R21 in examples below)
Created Shared network (R22 in examples below)

Created a "vm1" (and some more VMs, but irrelevant) and joined vm1 to:
- Isolated network (default one) , IP 10.1.1.101
- Shared network (additional network), IP 1.1.1.4

While VM running, inside R21 (Isolated)

```
root@r-21-VM:~# grep -ir "10\.1\.1\.101" /var/; grep -ir "10\.1\.1\.101" /etc/
/var/www/html/userdata/10.1.1.101/.htaccess:Allow from 10.1.1.101
/var/www/html/metadata/10.1.1.101/local-ipv4:10.1.1.101
/var/www/html/metadata/10.1.1.101/.htaccess:Allow from 10.1.1.101
/var/cache/cloud/passwords-10.1.1.1:10.1.1.101=saved_password
1","default_gateway":"10.1.1.1","default_entry":true,"remove":false,"type":"dhcpentry"}
/var/cache/cloud/processed/VR-df1e8224-8c07-4e8d-9006-191c1f48224a.cfg:{"vm_ip_address":"10.1.1.101","vm_metadata":[["userdata","user-data",null],["metadata","service-offering","Small Instance"],["metadata","availability-zone","pr3627-t408-vmware-65u2"],["metadata","local-ipv4","10.1.1.101"],["metadata","local-hostname","vm1"],["metadata","public-ipv4","10.1.35.64"],["metadata","public-hostname","10.1.35.64"],["metadata","instance-id","75c43c29-a101-458f-81c6-8fe6e7546890"],["metadata","vm-id","75c43c29-a101-458f-81c6-8fe6e7546890"],["metadata","public-keys",null],["metadata","cloud-identifier","CloudStack-{f36badac-df80-40f2-a1f2-ab3a9ea41259}"]],"type":"vmdata"}
/var/lib/misc/dnsmasq.leases:1573462858 02:00:2d:24:00:0e 10.1.1.101 vm1 *
/var/log/cloud.log:2019-10-10 20:52:55,009 INFO     Processing metadata for 10.1.1.101
/var/log/cloud.log:2019-10-10 20:53:08,194 INFO     Processing metadata for 10.1.1.101
/var/log/cloud.log:2019-10-10 20:59:14,675  configure.py process:330 Processing metadata for 10.1.1.101
/var/log/dnsmasq.log:Oct 10 21:00:58 dnsmasq-dhcp[2826]: DHCPDISCOVER(eth0) 10.1.1.101 02:00:2d:24:00:0e
/var/log/dnsmasq.log:Oct 10 21:00:58 dnsmasq-dhcp[2826]: DHCPOFFER(eth0) 10.1.1.101 02:00:2d:24:00:0e
/var/log/dnsmasq.log:Oct 10 21:00:58 dnsmasq-dhcp[2826]: DHCPREQUEST(eth0) 10.1.1.101 02:00:2d:24:00:0e
/var/log/dnsmasq.log:Oct 10 21:00:58 dnsmasq-dhcp[2826]: DHCPACK(eth0) 10.1.1.101 02:00:2d:24:00:0e vm1
/var/log/messages:Oct 10 20:59:13 systemvm passwd_server_ip.py: serve_password: password saved for VM IP 10.1.1.101
/etc/dhcphosts.txt:02:00:2d:24:00:0e,10.1.1.101,vm1,756h
/etc/cloudstack/vmdata.json:  "10.1.1.101": [
/etc/cloudstack/vmdata.json:      "10.1.1.101"
/etc/cloudstack/vmpassword.json:  "10.1.1.101": "saved_password",
/etc/cloudstack/dhcpentry.json:  "10.1.1.101": {
/etc/cloudstack/dhcpentry.json:    "ipv4_address": "10.1.1.101",
/etc/hosts:10.1.1.101   vm1
```

vm1 expunged, inside R21 (Isolated)

```
root@r-21-VM:~# grep -ir "10\.1\.1\.101" /var/; grep -ir "10\.1\.1\.101" /etc/
/var/www/html/userdata/10.1.1.101/.htaccess:Allow from 10.1.1.101
/var/www/html/metadata/10.1.1.101/local-ipv4:10.1.1.101
/var/www/html/metadata/10.1.1.101/.htaccess:Allow from 10.1.1.101
/var/cache/cloud/passwords-10.1.1.1:10.1.1.101=saved_password
/var/cache/cloud/processed/VR-df1e8224-8c07-4e8d-9006-191c1f48224a.cfg:{"host_name":"vm1","mac_address":"02:00:2d:24:00:0e","ipv4_address":"10.1.1.101","ipv6_duid":"00:03:00:01:02:00:2d:24:00:0e","dns_addresses":"10.1.1.1","default_gateway":"10.1.1.1","default_entry":true,"remove":false,"type":"dhcpentry"}
/var/cache/cloud/processed/VR-df1e8224-8c07-4e8d-9006-191c1f48224a.cfg:{"vm_ip_address":"10.1.1.101","vm_metadata":[["userdata","user-data",null],["metadata","service-offering","Small Instance"],["metadata","availability-zone","pr3627-t408-vmware-65u2"],["metadata","local-ipv4","10.1.1.101"],["metadata","local-hostname","vm1"],["metadata","public-ipv4","10.1.35.64"],["metadata","public-hostname","10.1.35.64"],["metadata","instance-id","75c43c29-a101-458f-81c6-8fe6e7546890"],["metadata","vm-id","75c43c29-a101-458f-81c6-8fe6e7546890"],["metadata","public-keys",null],["metadata","cloud-identifier","CloudStack-{f36badac-df80-40f2-a1f2-ab3a9ea41259}"]],"type":"vmdata"}
/var/lib/misc/dnsmasq.leases:1573462858 02:00:2d:24:00:0e 10.1.1.101 vm1 *
/var/log/cloud.log:2019-10-10 20:52:55,009 INFO     Processing metadata for 10.1.1.101
/var/log/cloud.log:2019-10-10 20:53:08,194 INFO     Processing metadata for 10.1.1.101
/var/log/cloud.log:2019-10-10 20:59:14,675  configure.py process:330 Processing metadata for 10.1.1.101
/var/log/dnsmasq.log:Oct 10 21:00:58 dnsmasq-dhcp[2826]: DHCPDISCOVER(eth0) 10.1.1.101 02:00:2d:24:00:0e
/var/log/dnsmasq.log:Oct 10 21:00:58 dnsmasq-dhcp[2826]: DHCPOFFER(eth0) 10.1.1.101 02:00:2d:24:00:0e
/var/log/dnsmasq.log:Oct 10 21:00:58 dnsmasq-dhcp[2826]: DHCPREQUEST(eth0) 10.1.1.101 02:00:2d:24:00:0e
/var/log/dnsmasq.log:Oct 10 21:00:58 dnsmasq-dhcp[2826]: DHCPACK(eth0) 10.1.1.101 02:00:2d:24:00:0e vm1
/var/log/messages:Oct 10 20:59:13 systemvm passwd_server_ip.py: serve_password: password saved for VM IP 10.1.1.101
/etc/dhcphosts.txt:02:00:2d:24:00:0e,10.1.1.101,vm1,756h
/etc/cloudstack/vmdata.json:  "10.1.1.101": [
/etc/cloudstack/vmdata.json:      "10.1.1.101"
/etc/cloudstack/vmpassword.json:  "10.1.1.101": "saved_password",
/etc/cloudstack/dhcpentry.json:  "10.1.1.101": {
/etc/cloudstack/dhcpentry.json:    "ipv4_address": "10.1.1.101",
/etc/hosts:10.1.1.101   vm1
```

Identical results are for R22 (Shared network) - zero difference in grep results (not sharing, for brevity)

**Comment by andrijapanicsb** [comment]
Additional thing I saw - when you restart network with cleanup - dhcp.leases file is completely empty (probably some more issues in other dns and dhcp related files)

**Comment by andrijapanicsb** [comment]
Tested with a VM attached just to Isolated network - same results.

**Comment by ustcweizhou** [comment]
@andrijapanicsb thanks a lot for testing.
the issue is not caused by this PR, but PR 3608 which has been merged.
in finalizeExpunge part, nics has already been removed so no rules will be applied in virtual routers.
we should move it to _networkMgr.cleanupNics

I will test it and update this PR if it is tested ok.

**Comment by ustcweizhou** [comment]
@andrijapanicsb I have updated this PR and tested ok. could you please test it ?

1. Before expunging vm
```
root@r-39-VM:~# cat /var/lib/misc/dnsmasq.leases
1573859468 1e:00:33:00:00:09 10.11.120.232 vm1 *
root@r-39-VM:~# cat /etc/dhcphosts.txt
1e:00:33:00:00:09,10.11.120.232,vm1,758h
```

2. nothing changes after stopping vm

3. after expunging vm
```
root@r-39-VM:~# cat /var/lib/misc/dnsmasq.leases
root@r-39-VM:~# cat /etc/dhcphosts.txt
```

**Comment by rhtyd** [comment]
@andrijapanicsb I did not review your test, the test should be to check the dnsmasq related config file and even maybe the leases file.

**Comment by andrijapanicsb** [comment]
Thx @ustcweizhou @rhtyd  - will test is as soon as possible.

**Comment by ustcweizhou** [comment]
@andrijapanicsb that's good, thanks for testing.
@rhtyd can you set up a trillian test ?

**Comment by andrijapanicsb** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@ustcweizhou @andrijapanicsb - have you tested the case that when a VM is stopped, its rules are not removed from the VR? I'll kick the test
@blueorangutan test

**Comment by andrijapanicsb** [comment]
yes @rhtyd , tested pretty thoroughly. Also tested when VR is stopped (and VM expunge automatically kicks in, etc). Looks good to me. Was even restarting networks with and without cleanup - all good.

**Comment by andrijapanicsb** [comment]
@weizhouapache @rhtyd I think I see a bit of a problem with this one (somewhat edge case).

VM1 has default network NET1
VM1 is attached to NET2 as an additional network - DNS and DHCP configs are created for this in the VR of NET2 (/etc/hosts and /etc/dhcphosts.txt
We later detach VM1 from NET2 (and potentially never again attach it) - garbage is left forever in VR of NET2 (this consumes IP if nothing else).

Can you think of any other consequence here?
I see that when attaching AGAIN VM1 to NET2, a NEW config (new IP) is used in DNS and DHCP config, while the OLD IP is still present (in /etc/hosts and /etc/dhcphosts.txt) - so this will make issues for sure.

**Comment by andrijapanicsb** [comment]
So... when an additional network is detached from the VM, and we later stop/delete/expunge that VM - nothing happens, since we only clean DHCP/DNS from the VRs/networks to which the VM is still attached.

Possibly a correct fix would be to ALSO do the same cleanup (that we otherwise do only when VM is expunging) when DETACHING from an ADDITIONAL network. Well, when detaching from ANY network - since after VM is detached, its reference(s) to its previous network(s) is lost and will never be later cleaned up (dhcp/dns config) when VM is destroyed

Makes sense @ustcweizhou @rhtyd  /CC @PaulAngus  ?

**Comment by rhtyd** [comment]
This PR is closed, we might lose the discussion @andrijapanicsb - can you create a ticket with your concerns? (i.e. to cleanup on vm nic remove/detach?)

**Comment by andrijapanicsb** [comment]
To be continued via: https://github.com/apache/cloudstack/issues/3706 

thx both!

**Pull request merged**
