### PR TITLE
Fix link to removed volumes being shown in info card and list view

### PR DESCRIPTION
**Pull request by winterhazel**
### Description

The volume snapshots and the snapshot details page show a link to the snapshotted volume. However, if the volume has been removed, it is not possible to access its page, resulting in a 404 when a user clicks the link.

This PR adds a validation in the UI in order to avoid showing this link when the volume has been removed.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### Screenshots (if appropriate):

<details>
<summary>
When the volume exists, a link is shown.
</summary>

Screenshot from 2024-03-26 09-18-39

</details>

<details>
<summary>
If the volume has been removed, the link does not get shown.
</summary>

Screenshot from 2024-03-26 09-18-54

</details>

### How Has This Been Tested?

1. I created a volume snapshot and verified that the volume snapshots and the snapshot details page showed a link to the volume;
2. I removed the volume and verified that the link was not shown anymore.

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan ui

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
qa does not seem to be responsive, not tested!

**Review by lucas-a-martins — APPROVED** [review]
LGTM

I manually tested by creating a volume snapshot and then deleting the volume.

<details>
    <summary>Before the proposed changes</summary>

- The snapshot details page shows a link to the volume even after the volume has been removed.

Before-changes


- Clicking the link redirected me to a 404 page.

404-Before

</details>

<details>
    <summary>After the proposed changes</summary>

- The snapshot details page does not show a link to the removed volume.

After-changes


</details>

I'm not sure if this is within the scope of this PR, but on the Volume Snapshots page, where it displays the list of volume snapshots, a link to the removed volume is still being shown and redirects to a 404 page.

volume-snapshot-list

**Comment by DaanHoogland** [comment]
@winterhazel , I marked this for 4.20 now as it is targeted for main. Do you want this in 4.19?

**Comment by winterhazel** [comment]
Thanks for testing @lucas-a-martins. At first, I think the issue regarding invalid links in the list view should be tackled in another PR, but I'll investigate how it could be implemented to see if it makes sense to unify how the validation is performed with this one.

> @winterhazel , I marked this for 4.20 now as it is targeted for main. Do you want this in 4.19?

@DaanHoogland sure, I'll target 4.19.

**Comment by winterhazel** [comment]
Hey @lucas-a-martins @DaanHoogland, sorry for the delay.

Looking back at this PR, I think it would be better to implement the link validation in both pages by including the volume's state in the response and verifying it in the UI, as the approach here (calling an API to obtain a single volume's data) would become unfeasible when we need to validate links for a lot of resources (such as in the volume snapshots page). I suppose this would also be the ideal approach for validating most links to resources.

I will make some changes in this PR to adjust this, and to include the validation in the volume snapshots page as well.

**Comment by winterhazel** [comment]
@lucas-a-martins @DaanHoogland, I changed how the link validation is performed, and included it in the list view as well. Could you guys take another look at this PR?

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Review by lucas-a-martins — APPROVED** [review]
LGTM

I tested the current iteration of this PR and everything is working as intended, including the changes to the volume snapshot list view.

<details>
<summary>Volume snapshot view</summary>

- Before deleting the volume: 

list-view-before-delete


- After deleting the volume:

list-view-after-delete


</details>

<details>
<summary>Snapshot details view</summary>

- Before deleting the volume:

snapshot-details-before-delete


- After deleting the volume:

snapshot-details-after-delete


</details>

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by JoaoJandre** [comment]
Merging based on approvals, CI result and manual tests by @lucas-a-martins

**Pull request merged**
