### PR TITLE
UI: create VPC network offering with conserve mode

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

The default offering for vpc networks has been changed to conserved mode in PR #8309 . It looks good.
This PR enables the option on UI

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by JoaoJandre** [comment]
@blueorangutan ui

**Comment by DaanHoogland** [comment]
@weizhouapache , any reason this should be on 4.20 and not 4.19?

**Comment by weizhouapache** [comment]
> @weizhouapache , any reason this should be on 4.20 and not 4.19?

as the line of code is different in 4.19/4.20

```
@@ -377,7 +452,7 @@
         <a-form-item
           name="conservemode"
           ref="conservemode"
-          v-if="(guestType === 'shared' || guestType === 'isolated') && !isVpcVirtualRouterForAtLeastOneService">
+          v-if="(guestType === 'shared' || guestType === 'isolated') && !isVpcVirtualRouterForAtLeastOneService && !forNsx && networkmode !== 'ROUTED'">
           <template #label>
             <tooltip-label :title="$t('label.conservemode')" :tooltip="apiParams.conservemode.description"/>
           </template>
```

I can rebase to 4.19 if you think it is needed. (then you will face merge conflict when merge forward :smile: )

**Comment by DaanHoogland** [comment]
> > @weizhouapache , any reason this should be on 4.20 and not 4.19?
> 
> as the line of code is different in 4.19/4.20
> 
> ```
> @@ -377,7 +452,7 @@
>          <a-form-item
>            name="conservemode"
>            ref="conservemode"
> -          v-if="(guestType === 'shared' || guestType === 'isolated') && !isVpcVirtualRouterForAtLeastOneService">
> +          v-if="(guestType === 'shared' || guestType === 'isolated') && !isVpcVirtualRouterForAtLeastOneService && !forNsx && networkmode !== 'ROUTED'">
>            <template #label>
>              <tooltip-label :title="$t('label.conservemode')" :tooltip="apiParams.conservemode.description"/>
>            </template>
> ```
> 
> I can rebase to 4.19 if you think it is needed. (then you will face merge conflict when merge forward 😄 )

thanks, I think I wil live with it ;) but it should not be a big deal.

**Review by JoaoJandre — APPROVED** [review]
LGTM, tested creating both VPC network offerings with and without conserve mode, both were correctly created

**Review by DaanHoogland — APPROVED** [review]

**Pull request merged**
