### PR TITLE
CLOUDSTACK-8733: Host stuck in rebalancing state during agent LB

### PR DESCRIPTION
**Pull request by koushik-das**
This is happening as ClusterServiceServletAdapter is started after ClusteredAgentManagerImpl.
Fix is to start ClusterServiceServletAdapter before ClusteredAgentManagerImpl.

Also added a log message in SyncQueueManagerImpl.

### CODE REVIEW

**Comment by remibergsma** [comment]
LGTM

**Comment by koushik-das** [comment]
@kishankavala @DaanHoogland Can any of you review this?

**Comment by kishankavala** [comment]
LGTM

**Comment by remibergsma** [comment]
Can't currently check the output of Apache Build Jenkins as it returns 404. Wanted to double check the UNSTABLE state. Holding on for now..

**Comment by koushik-das** [comment]
@remibergsma https://builds.apache.org is available, maybe https://builds.apache.org/job/cloudstack-pull-requests/1001/ got removed from the server as it was 7days old. In that case it will always return 404.

**Comment by koushik-das** [comment]
Merging as 2 LGTMs

**Comment by remibergsma** [comment]
@koushik-das Thanks for merging, sorry I forgot to do it for you ;-) Could you have a look at this script, to help you merge it? https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61311655 If you have feedback or need help: let me know!

**Comment by koushik-das** [comment]
@remibergsma I used the script to do the merge. This is how I used it tools/git/git-pr 698

**Comment by bhaisaab** [comment]
@koushik-das this issue seems to affect 4.5.0, have you already or can you port/merge this on 4.5 branch?

**Comment by koushik-das** [comment]
@bhaisaab I haven't merged it to 4.5

**Comment by bhaisaab** [comment]
@koushik-das if this applies for 4.5.x, it would be great to have it in 4.5 branch as well

**Comment by remibergsma** [comment]
@koushik-das Thanks for letting me know, there might be an issue because part of the merge message is missing. Will fix it.

**Comment by koushik-das** [comment]
@bhaisaab Should I simply cherry-pick to 4.5 branch?

**Comment by bhaisaab** [comment]
@koushik-das yes that will work, you may also send a PR with the cherry-picked commit so we can be sure it does not break smoke tests/travis

**Comment by koushik-das** [comment]
@bhaisaab Cherry-picked to 4.5 with commit 3d9cbf0bcb011f4012c94f0df040d9b8ddd325bc

**Comment by bhaisaab** [comment]
@koushik-das thanks :)

**Pull request merged**
