### PR TITLE
UI: Show IPv6 address of Instance

### PR DESCRIPTION
**Pull request by utchoang**
### Description

Fixes https://github.com/apache/cloudstack/issues/4844

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### Screenshots (if appropriate):
image

### CODE REVIEW

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by davidjumani** [comment]
@utchoang @rhtyd Would it be a good idea to include the ip6 address in the listview as well ?

**Comment by utchoang** [comment]
> @utchoang @rhtyd Would it be a good idea to include the ip6 address in the listview as well ?
@davidjumani @rhtyd  I think it's fine, I'll add it to the listview

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by utchoang** [comment]
@blueorangutan ui

**Review by rhtyd — APPROVED** [review]
LGTM - didn't test, don't have env with ipv6

**Review by wido — APPROVED** [review]
LGTM based on code and screenshots

**Comment by kricud** [comment]
If possible please show ipv6 link-local address as well. The one that is in range/block fe80::/10
If you have two instances on same network/subnet/broadcast domain and they both have fe80:xxx they will use it to communicate each other.

https://en.wikipedia.org/wiki/Link-local_address

**Review by davidjumani — APPROVED** [review]
LGTM based on code and screenshots

**Comment by rhtyd** [comment]
@kricud are you asking the ipv6 link-local address to be shown for systemvms or user VMs? Is that nic information something that gets added internal to the VM or plugged by CloudStack? (I would image all nics/ipv4/ipv6 addresses to be returned by the API to be shown in the UI; any custom nics/setup inside the VM may not be discovered by CloudStack)

**Comment by kricud** [comment]
@rhtyd In case of ipv6 you will always have link-local address even if routable ipv6 is not configured. In screenshot I do not see it and its misleading. As you wrote all ip addresses must be presented.

**Comment by rhtyd** [comment]
@kricud as long as those are internal to the VM, it will be difficult for CloudStack to report those IPs (for example a custom network over L2 network, there's no IP known to CloudStack). We only see all the IPs for all the nics configured for a VM by CloudStack. As you've said, showing link-local/lo IPs won't be useful for end-users. Thanks.

**Comment by wido** [comment]
> @rhtyd In case of ipv6 you will always have link-local address even if routable ipv6 is not configured. In screenshot I do not see it and its misleading. As you wrote all ip addresses must be presented.
> 
> Ignore- I mis understood its not doable and user must understand that ipv6 will have link-local.
> Configuring it manually for presentation in ui is nonsense.

I know it has been merged now, but let me add this:

The link-local address is a non-routable address which can't be used from the outside world. Nor does CloudStack know what it is allthough it could calculate the address based on the MAC.

CloudStack is aimed at routable addresses as that's what we use. Technically servers can communicate with each other over Link-Local as long as they are in the same L2 domain, but it's not the use-case which is used very much.

Most services use unicast addresses for the communication.

LL with IPv6 is mainly used for Router Advertisements, Neighbor Discovery, etc, etc.

I would not say it's very useful to display the LL addresses in the UI. In addition: The API does not return those.

**Comment by rhtyd** [comment]
@wido can you create a new issue tracking the new feature asked, you're right I checked the algorithm the LL address is generated using Mac address and it's certainly possible to display it in UI as mac address is already returned in API response.

**Pull request merged**
