### PR TITLE
ui: show read from ova only for ova format

### LINKED ISSUE #5107: UI: "Read settings from OVA" is shown before Format=OVA is selected.
* Enhancement Request / Bug

Minor enhancement with VMware/OVA format - to actually make sense...

When hypervisor is chosen - the filed "format" is still NOT populated (OK, fine), but there is by default the "Read settings from OVA" slider available - this should also be hidden until the Format=OVA is selected (seems like the correct solution - because in future we might support other formats as well)
OR
If we keep the default to show "Read setting from OVA" after the hypervisor=VMware is selected, then let's also populated automatically the format=OVA when "Read settings from OVA" is checked - short video:

http://somup.com/cr12FxqgmO

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #5107

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan ui

**Review by rhtyd — APPROVED** [review]
LGTM, @andrijapanicsb can you review/test

**Comment by rhtyd** [comment]
@blueorangutan package

**Review by Pearl1594 — APPROVED** [review]

**Review by utchoang — APPROVED** [review]
LGTM!

**Comment by andrijapanicsb** [comment]
LGTM (thanks)

(have not tested REALLY uploading the template - I assume we just hide/show things, and the correct parameters are still sent as before)

**Review by rhtyd — APPROVED** [review]

**Pull request merged**
