### PR TITLE
build/packaging: build tungsten plugin only if noredist is passed

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR moves tungsten plugin from normal packaging to noredist packaging

it also removes the maven repository for juniper-tungsten-api
whoever want to build tungsten, please install the jar manually. please refer to https://github.com/shapeblue/cloudstack-nonoss/
./install-non-oss.sh

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Comment by DaanHoogland** [comment]
code looks good so far @weizhouapache , but you are adding four agent commands without answers or calling them. What can we expect on this?

**Comment by weizhouapache** [comment]
> code looks good so far @weizhouapache , but you are adding four agent commands without answers or calling them. What can we expect on this?

@DaanHoogland 
The kvm plugin has dependency on tungsten currently. Since tungsten will be moved to noredist packaging, to not break the regular packaging (without noredist), I remove tungsten from kvm plugin.
4 tungsten classes (as you have noticed) are still used by the kvm plugin, I have to add the copies to kvm plugin, otherwise the compilation of kvm plugin will fail.

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test matrix

**Comment by sureshanaparti** [comment]
@weizhouapache need to update this file _deps/install-non-oss.sh_ here?

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Comment by weizhouapache** [comment]
> > @weizhouapache need to update this file _deps/install-non-oss.sh_ here?
> 
> yep, the jar has already been added last year I think

sorry @sureshanaparti 
I thought you mentioned the script in cloudstack-nonoss repo. It has been updated.

The script in _deps_ folder is not well maintained, the last change was 4 years ago. I will create a separated pr for it.

**Comment by weizhouapache** [comment]
This is ready for review and testing

**Comment by DaanHoogland** [comment]
@weizhouapache does it need further testing? (and what kind)

**Comment by weizhouapache** [comment]
> @weizhouapache does it need further testing? (and what kind)

no idea what needs to be tested
probably tungsten :-D

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@JoaoJandre I think this is hight beneficial for most users, as they don't use TF.

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Pull request merged**
