### PR TITLE
Enhancement scss refactoring

### PR DESCRIPTION
**Pull request by webermaximilian92**
## Description
This PR is an SCSS-refactoring addition to PR: https://github.com/apache/cloudstack/pull/3307#issuecomment-491314203

This enhances code-quality of scss code by
- including tool-tasks like sass-lint-fix (autodetects scss lint warnings and fix them if possible)
- adding jsbeautifyrc, that can be used by IDE extensions to unify scss code automatically 
- deleting old css files for IE7, that will no longer be in use today (almost 13 years old browser)
- rethinking of old "custom.css"-style-file. (it's not beneficial to generate own custom css file anymore. The less css, the less server requests. Rather now any CSS code can be included inside custom.scss file and will be compiled at bottom of cloudstack3.css by compiler.
- adding z-index variables to better organize treacherous interdependently z-index values.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?
By running compilers and check build css code and by visiting the page with new css file.
(This changes modify and unify the structure of css code only and deleting old unused code)
All we have to check yet, is if cloudstack3.css includes any effective changes.

It's very useful to reduce the diff to non whitespace changes here again:
Screenshot 2019-04-26 at 16 23 44

### CODE REVIEW

**Comment by webermaximilian92** [comment]
I know this PR may seem confusing to most of you first... 
The only interesting file of those 86 is "_cloudstack3.css_"!
**All other files** are just the source to build this final massive 13000 lines css file now and may be ignored in this PR. 
Later we can use those new smaller scss-files to adjust styles more safty and faster.

**Comment by DaanHoogland** [comment]
I'm all for this but fear a similar situation like the latest jquery update. Not that we should back down but I'm wondering if there is a reliable way to check _all_ changes here. a visual review of cloudstack3.ccs seems fine. /me not trusting my eyes.

**Comment by webermaximilian92** [comment]
Hey Daan, 
thanks for feedback.
This is not compareable to jquery update, because it's not an upgrade of any Framework Version. Final CSS keeps CSS. It's an refactoring of old technology. I didn't changed the code at all here but I generated a way to better work with it. 

The CSS script is full of redundant and outdated rules. We need to fix that anytime in future and we should begin right now.

Their will be no garantee that no issues and mistakes where done by me here, but it wont be that complicated to fix small issues and I am very experienced by what I'm doing.

Max

**Comment by webermaximilian92** [comment]
I am in Norway for around 3 weeks now. Let's merge this when I am back, so we can react faster to unlikely issues, then.

**Pull request merged**
