### PR TITLE
UI - Zone wizard - Fixes wrong add resource step with localstorageenabled

### PR DESCRIPTION
**Pull request by utchoang**
### Description
Fixes https://github.com/apache/cloudstack/issues/5302

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by utchoang** [comment]
@blueorangutan ui

**Review by davidjumani — COMMENTED** [review]
@utchoang Some of the steps are the same such as adding hosts / secondary storage. Perhaps there can just be a check on adding primary storage if localstorageenabled and changing the step numbers accordingly
On another note, should the primary storage step be removed or just skippable ? @rhtyd @shwstppr

**Comment by utchoang** [comment]
@davidjumani You can refer to https://github.com/apache/cloudstack/blob/4.14/ui/scripts/zoneWizard.js#L4454, In case both `localstorageenabled` && `localstorageenabledforsystemvm` are enabled, the step of adding primary storage will be skipped.

**Comment by davidjumani** [comment]
@utchoang That's right, my point is to skip just that step in an if condition rather than adding the redundant code of adding hosts and secondary storage in the if as well as else clause

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by utchoang** [comment]
@davidjumani can you please check again?

**Review by davidjumani — APPROVED** [review]
Verified working! Thanks @utchoang

**Review by rhtyd — APPROVED** [review]

**Pull request merged**
