### PR TITLE
Clean up Python code; Python `2` to `3`

### PR DESCRIPTION
**Pull request by jbampton**
### Description

This PR cleans up some Python code. Mainly `print` statements.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [X] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by jbampton** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
looks good and not sure if anybody is using the ovm3 plugin so low risk addition. No testing possible as far as I know. This probably the reason it wasa left behind as well.

**Comment by jbampton** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
clgtm, but this plugin should be deprecated. cc @JoaoJandre ?

**Review by JoaoJandre — APPROVED** [review]
LGTM. 
I'm not sure on the current status of ovm. But we could start a thread on the mailing lists to see if anyone still uses it. If not, we can deprecate it and eventually remove it in the next major version (we really need to agree on a way to release the next major).

**Comment by jbampton** [comment]
@blueorangutan package

**Pull request merged**
