### PR TITLE
CLOUDSTACK-10007 Isolation method claim

### PR DESCRIPTION
**Pull request by DaanHoogland**
This will prevent DirectNetworkGuru from designing and implementing a network it is not supposed to but, as discussed with @fmaximus, the  commit "remove hardcoded exemptions on directnetworkguru" will still allow it to implement a network if it supports one of the services from the offering so several gurus can still end up implementing a single network.
Solutions could include:
- only canHandle() if all required services are supported
- link a guru to a physical network and not ask for any guru if they canHandle()
- retrospecively check what guru implements the best set of services.

### CODE REVIEW

**Comment by rhtyd** [comment]
LGTM.

**Comment by DaanHoogland** [comment]
for now revert the last commit (see description).

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan matrix

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Pull request merged**
