### PR TITLE
Fixed Veeam listing restore points

### PR DESCRIPTION
**Pull request by harikrishna-patnala**
### Description

This PR fixes the issue https://github.com/apache/cloudstack/issues/6465 where listing backup restore points are failing with Veeam version v11.0.1.1261. 

Though this version is not fully supported for backup and recovery, existing backups, restore points for the VMs can continue to work with the Veeam version v11.0.1.1261. I've created a separate ticket here to fully support the version https://github.com/apache/cloudstack/issues/6554

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [x] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):
image

### How Has This Been Tested?

1. Setup Veeam v11.0.1.1261 with CloudStack
2. Added a back offering to the volume
3. Created a backup to the VM
4. Wait for the back sync to trigger in CloudStack
5. Restore points listed and saved in the database in the table "backups"

### CODE REVIEW

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Review by rohityadavcloud — APPROVED** [review]
LGTM but really needs testing against the said version of support veeam B&R

**Comment by shwstppr** [comment]
@harikrishna-patnala should this be fixed in 4.17 branch?

**Comment by harikrishna-patnala** [comment]
No need I think @shwstppr because this is more related to the latest version of Veeam which we don't fully support. We have created a separate ticket for that too https://github.com/apache/cloudstack/issues/6554

**Comment by harikrishna-patnala** [comment]
@SadiJr Can you please help me test this PR with the Veeam version v11.0.1.1261 ?

Though this version is not fully supported from a fresh install, it will still work with older version and even after upgrading to the  v11.0.1.1261. You can also try any test environment if you have by upgrading it to this version v11.0.1.1261. Thanks in advance.

**Review by shwstppr — APPROVED** [review]

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Comment by shwstppr** [comment]
Test failures are unrelated, merging based on approvals and testing

**Comment by SadiJr** [comment]
@harikrishna-patnala sorry for the delay in answer. I tested in my lab with the Veeam build 11.0.1.1261 P20211211, comparing with the main commit bca60761c502f1fa04c1d462128ef537c0e7ce73, and the error reported in issue #6465 is fixed. About issue #6554, I cannot reproduce the second example; can you please inform your version of Windows and PowerShell?

**Pull request merged**
