### PR TITLE
CLOUDSTACK-9220 Sort list of domains on Domain tab in UI

### PR DESCRIPTION
**Pull request by remibergsma**
The list of domains was unsorted and that annoyed me so I sorted it :-)

### CODE REVIEW

**Comment by remibergsma** [comment]
Before this PR it was unsorted:
cloudstack_pr1327_2

Now it is sorted:
cloudstack_pr1327_1

**Comment by remibergsma** [comment]
@nitin-maharana Could you please review this? Thanks!

**Comment by DaanHoogland** [comment]
code reviewed, simple fix for convenience in large installations: LGTM

**Comment by nitin-maharana** [comment]
@remibergsma: Checked for all alphabet names, its sorting perfectly. But how it is sorting for special character names starting with @, #, etc. Is it sorting according to ASCII value or anything else? 

screen shot 2016-01-11 at 1 05 32 pm

**Comment by bhaisaab** [comment]
LGTM

**Comment by borisroman** [comment]
It's sorted! LGTM

screen shot 2016-01-11 at 11 45 06

**Pull request merged**
