### PR TITLE
[Ignore][Defunct][Experimental] WIP Debian8 systemvmtemplate

### PR DESCRIPTION
**Pull request by rhtyd**
Experimental PR.

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by wido** [comment]
Are you still working on this update Rohit? Or is there a new PR for updating the SSVM to Debian 8?

**Comment by rhtyd** [comment]
@wido no, I'm not working on this presently. Though, I've kept it open as a reminder that we need to indeed work on updating the ssvm code to Debian8. Part of the issue is between Debian7 and Debian8, systemd's introducing causes issues with expecting our VR/ssvm codebase to work out of the box, cloud-early-config does not work as it's a init-d script.

**Comment by wido** [comment]
Ok, understood. I'll see if I can find some time to work on this. Thanks

**Comment by rhtyd** [comment]
Time to skip debian8, move to debian9!

**Pull request closed without merging**
