### PR TITLE
CLOUDSTACK-9049: fix Centos7 with Tomcat7 packaging and python libs

### PR DESCRIPTION
**Pull request by davidamorimfaria**
CLOUDSTACK-9049: Fix Centos7 with Tomcat7 packaging and python libs

### CODE REVIEW

**Comment by davidamorimfaria** [comment]
I haven't tested these changes yet, hopefully will have time tomorrow to do it.

**Comment by remibergsma** [comment]
Thanks @davidamorimfaria will give it a go.

**Comment by wilderrodrigues** [comment]
Ping @davidamorimfaria @remibergsma 

How can I help testing it? Steps...???

Cheers,
Wilder

**Comment by wilderrodrigues** [comment]
I will build RPMs and try to install the management server form the RPM in a machine with tomcat7 installed. is that how it is supposed to work?

**Comment by DaanHoogland** [comment]
@wilderrodrigues that would be a way, a problem that was identified is that tomcat as dependency will not be installed. I don't think that is arddessed in this.

**Comment by wilderrodrigues** [comment]
This PR needs fixes, I cannot even build the RPMs.

I did:

* git fetch origin pull/1052/head:pr/1052
* git checkout pr/1052
* cd packaging
* ./packaging -d centos7

Result below:

```
7-nonssl.conf /data/git/cs1/cloudstack/dist/rpmbuild/BUILDROOT/cloudstack-4.6.0-SNAPSHOT.el7.centos.x86_64/etc/cloudstack/management/tomcat7-nonssl.conf
mv: cannot stat '/data/git/cs1/cloudstack/dist/rpmbuild/BUILDROOT/cloudstack-4.6.0-SNAPSHOT.el7.centos.x86_64/usr/share/cloudstack-management/webapps/client/WEB-INF/classes/tomcat7-nonssl.conf': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.YrDgHw (%install)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.YrDgHw (%install)
RPM Build Failed 
[root@cs1 packaging]#
```

Cheers,
Wilder

**Comment by remibergsma** [comment]
@wilderrodrigues @davidamorimfaria RPM build now works properly:

```
+ exit 0
RPM Build Done
```

**Comment by remibergsma** [comment]
@davidamorimfaria Here's another glitch you may want to look at:

```
[root@cs2 x86_64]# cloudstack-setup-management
  File "/usr/bin/cloudstack-setup-management", line 36
    if options.tomcat7
                     ^
SyntaxError: invalid syntax
```

You mis a `:` after `if options.tomcat7`.

I edit it locally, then run: `cloudstack-setup-management --tomcat7` (suppose I need that option when I look at the code?)

Now I get:
```
Starting to configure CloudStack Management Server:
Configure Firewall ...        [OK]
Configure CloudStack Management Server ...Configure CloudStack Management Server failed, Please check the /var/log/cloudstack/setupManagement.log for detail, due to:globalEnv instance has no attribute 'srvConf'
Try to restore your system:
Restore Firewall ...          [OK]
```

**Comment by remibergsma** [comment]
@davidamorimfaria Ooops... something went wrong! You got like 10 commits of other people pushed and created conflicts. I'd suggest squashing your own commits and making sure it's the only commit in the pr.

**Comment by davidamorimfaria** [comment]
The mess has been sorted and the code is ready for testing.

**Comment by davidamorimfaria** [comment]
Just tested and managed to deploy the management server without issues.

**Comment by remibergsma** [comment]
@davidamorimfaria Thanks, will retest soon.

**Comment by DaanHoogland** [comment]
validated the build and install with centos7. validation on centos6 started

**Comment by davidamorimfaria** [comment]
added pr for docs-install https://github.com/apache/cloudstack-docs-install/pull/24

**Comment by remibergsma** [comment]
LGTM, Tested on CentOS7 with Tomcat 7. 

The package builds fine:

```
+ exit 0
RPM Build Done
```

Install also works:

```
Installed:
  cloudstack-common.x86_64 0:4.6.0-SNAPSHOT.el7.centos                                  
  cloudstack-management.x86_64 0:4.6.0-SNAPSHOT.el7.centos                                  

Complete!
```

Setup, now requires `--tomcat7` as parameter:

```
[root@cs2 x86_64]# cloudstack-setup-management --tomcat7
Starting to configure CloudStack Management Server:
Configure Firewall ...        [OK]
Configure CloudStack Management Server ...[OK]
CloudStack Management Server setup is Done!
```

Files in `/etc/`:

```
[root@cs2 management]# pwd
/etc/cloudstack/management
[root@cs2 management]# ls -la
total 136
drwxr-xr-x. 3 root root   4096 Nov 10 09:10 .
drwxr-xr-x. 3 root root   4096 Nov  9 17:06 ..
drwxrwx---. 3 root cloud  4096 Nov 10 09:06 Catalina
-rw-r--r--. 1 root root   8945 Nov 10 08:56 catalina.policy
-rw-r--r--. 1 root root   3794 Nov 10 08:56 catalina.properties
-rw-r--r--. 1 root root   1653 Nov 10 08:56 classpath.conf
-rw-r--r--. 1 root root   1357 Nov 10 08:56 commons-logging.properties
-rw-r-----. 1 root cloud  3125 Nov 10 09:08 db.properties
-rw-r-----. 1 root cloud  3125 Nov  9 21:27 db.properties.rpmsave
-rw-r--r--. 1 root root    972 Nov 10 08:56 environment.properties
-rw-r--r--. 1 root root    927 Nov 10 08:56 java.security.ciphers
-rw-r--r--. 1 root root      8 Nov 10 09:08 key
-rw-r--r--. 1 root root   7020 Nov 10 08:56 log4j-cloud.xml
-rw-r--r--. 1 root root   6722 Nov 10 08:56 server7-nonssl.xml
-rw-r--r--. 1 root root   7251 Nov 10 08:56 server7-ssl.xml
lrwxrwxrwx. 1 root root     45 Nov 10 09:10 server.xml -> /etc/cloudstack/management/server7-nonssl.xml
-rw-r--r--. 1 root root   1383 Nov 10 08:56 tomcat-users.xml
-rw-r--r--. 1 root root  50475 Nov 10 08:56 web.xml
```

Enabling and starting:

```
[root@cs2 management]# systemctl enable cloudstack-management
[root@cs2 management]# systemctl start cloudstack-management
[root@cs2 management]# systemctl status cloudstack-management
cloudstack-management.service - CloudStack Management Server
   Loaded: loaded (/usr/lib/systemd/system/cloudstack-management.service; enabled)
   Active: active (running) since Tue 2015-11-10 09:11:41 GMT; 5s ago
 Main PID: 12381 (java)
   CGroup: /system.slice/cloudstack-management.service
           └─12381 java -Djava.awt.headless=true -Dcom.sun.management.jmxremote=false -Xmx2g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/log/cloudstack/management/ -XX:PermSize=512M -XX:MaxPermSize=800m -cla...
```

Deployed data center:

screen shot 2015-11-10 at 11 12 42

screen shot 2015-11-10 at 11 07 15

Currently running some Marvin tests and that looks good. Will post results later.

**Comment by remibergsma** [comment]
Ping @PaulAngus to have a look.

**Comment by remibergsma** [comment]
@davidamorimfaria Please squash the commits, thanks.

**Comment by davidamorimfaria** [comment]
squashed

**Comment by DaanHoogland** [comment]
LGTM on centos 6:
```
[root@cs3 x86_64]# cloudstack-setup-databases cloud:password@localhost --deploy-as=root
Mysql user name:cloud                                                           [ OK ]
Mysql user password:******                                                      [ OK ]
Mysql server ip:localhost                                                       [ OK ]
Mysql server port:3306                                                          [ OK ]
Mysql root user name:root                                                       [ OK ]
Mysql root user password:******                                                 [ OK ]
Checking Cloud database files ...                                               [ OK ]
Checking local machine hostname ...                                             [ OK ]
Checking SELinux setup ...                                                      checkSelinux failed with error continuing...                                    SELinux is set to enforcing. There are two options:
1> Set it permissive in /etc/selinux/config, then reboot the machine.
2> Type 'setenforce Permissive' in commandline, after which you can run this program again.

We strongly suggest you doing the option 1 that makes sure SELinux goes into permissive after system reboot.
[ OK ]
Detected local IP address as 192.168.22.63, will use as cluster management server node IP[ OK ]
Preparing /etc/cloudstack/management/db.properties                              [ OK ]
Applying /usr/share/cloudstack-management/setup/create-database.sql             [ OK ]
Applying /usr/share/cloudstack-management/setup/create-schema.sql               [ OK ]
Applying /usr/share/cloudstack-management/setup/create-database-premium.sql     [ OK ]
Applying /usr/share/cloudstack-management/setup/create-schema-premium.sql       [ OK ]
Applying /usr/share/cloudstack-management/setup/server-setup.sql                [ OK ]
Applying /usr/share/cloudstack-management/setup/templates.sql                   [ OK ]
Processing encryption ...                                                       [ OK ]
Finalizing setup ...                                                            [ OK ]

CloudStack has successfully initialized database, you can check your database configuration in /etc/cloudstack/management/db.properties

[root@cs3 x86_64]# cloudstack-setup-management
Starting to configure CloudStack Management Server:
Configure Firewall ...        [OK]
Configure CloudStack Management Server ...[OK]
CloudStack Management Server setup is Done!
[root@cs3 x86_64]#
```

**Comment by remibergsma** [comment]
Verified RPM build after squash to be sure:

```
+ exit 0
RPM Build Done
```

**Comment by remibergsma** [comment]
Executed a few tests just to see if it actually does something:

```
Test advanced zone virtual router ... === TestName: test_advZoneVirtualRouter | Status : SUCCESS ===
ok
Test Deploy Virtual Machine ... === TestName: test_deploy_vm | Status : SUCCESS ===
ok
```

It is still running the tests against the RPM deployed CentOS 7 box.

**Comment by remibergsma** [comment]
Verified with @dahn that `cloudstack-management` started on CentOS 6 as well and that he was able to use the UI.

**Pull request merged**
