### PR TITLE
Fixed incorrect label in VRs and  SVMs

### PR DESCRIPTION
**Pull request by FelipeM525**
### Description

This PR Fixes [!9615](https://github.com/apache/cloudstack/issues/9615)

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### Screenshots (if appropriate):
<details>
<summary>
Before
</summary>

image
image
</details>
<details>
<summary>
After
</summary>

image
image
</details>

### CODE REVIEW

**Review by lucas-a-martins — APPROVED** [review]
CLGTM

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@blueorangutan ui

**Comment by DaanHoogland** [comment]
looks good in qa

**Pull request merged**
