### PR TITLE
agent: remove powermock from tests

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR removes usage of powermock from agent's tests.

After this change, this is the remaining usage of powermock left.
```bash
$ git grep "PowerMockito" | tr "/" " "| awk '{print $1, $2, $3, $4}' | sort | uniq -c 
     76 api src test java
     51 core src test java
     37 engine schema src test
     68 engine storage configdrive src
      9 engine storage snapshot src
     11 plugins acl project-role-based src
      3 plugins database quota src
    150 plugins hypervisors kvm src
      3 plugins hypervisors vmware src
     40 plugins hypervisors xenserver src
      5 plugins integrations kubernetes-service src
      2 plugins network-elements nicira-nvp src
     96 plugins network-elements tungsten src
      1 plugins storage volume storpool
     17 plugins user-authenticators ldap src
    196 server src test java
      4 services console-proxy server src
      2 services secondary-storage server src
      2 vmware-base src test java
```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Review by DaanHoogland — APPROVED** [review]
tlgtm

**Comment by weizhouapache** [comment]
code lgtm

@vishesh92 
are you still working on other tests ? will you update this PR or create new PR ?

**Review by weizhouapache — APPROVED** [review]

**Comment by vishesh92** [comment]
@weizhouapache I was planning to create separate PRs. Not sure how much time it will take to replace all the tests. And I don't want to have one huge PR with a lot of changes.

**Comment by weizhouapache** [comment]
> @weizhouapache I was planning to create separate PRs. Not sure how much time it will take to replace all the tests. And I don't want to have one huge PR with a lot of changes.

@vishesh92 
fine, I will merge this

**Pull request merged**
