### PR TITLE
Add all tests in /test/integration/smoke to Travis run and nove nicir…

### PR DESCRIPTION
**Pull request by sebgoa**
Adds all tests in smoke folder to Travis.
Moves nicira test to /test/integration/plugins

### CODE REVIEW

**Comment by miguelaferreira** [comment]
@runseb Travis is green but no tests are running.

I checked all the builds and the first few say this:
```
$ ./tools/travis/script.sh $TESTS
./tools/travis/script.sh: line 42: nosetests: command not found
+------+--------+
| Test | Result |
+======+========+
+------+--------+
```

And the rest say this:
```
/home/travis/build.sh: line 108:  2390 Terminated              travis_jigger $! $timeout $cmd
The command "travis_wait 30 sleep 30" exited with 0.
$ ./tools/travis/script.sh $TESTS
Skipping tests ... SUCCESS !
```

**Comment by bhaisaab** [comment]
Updates on this?

**Comment by runseb** [comment]
nope, I'd like to figure out why tests are not running. Just have not found the time to do so.

**Comment by rhtyd** [comment]
This can be closed, I've moved max. tests to travis and fix test runs etc.
@runseb 

tag:closeme

**Pull request closed without merging**
