### PR TITLE
travis: Fix simulator tests and optimize default global configs

### PR DESCRIPTION
**Pull request by bhaisaab**
- Migrate to trusty based Travis VMs
- Increase tests across five build matrices
- Fix xunit-reader output, include time
- Fix pip/python usage, pkg installation
- Build CloudStack in parallel with -T4
- Deploy database with optimized global settings

cc @runseb @swill @wido @DaanHoogland

### CODE REVIEW

**Comment by runseb** [comment]
+1 LGTM based on code review

**Comment by swill** [comment]
### CI RESULTS




**85/85 TESTS PASS**

Everything is looking pretty good from this side.


**Associated Uploads**

**`test_network_SC8F3J`:**

* [results.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1461/test_network_SC8F3J/results.txt)

**`test_vpc_routers_8H0Y84`:**

* [results.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1461/test_vpc_routers_8H0Y84/results.txt)


Uploads will be available until `2016-06-05 02:00:00 +0200 CEST`

*Comment created by [`upr comment`](https://github.com/swill/upr).*

**Comment by bhaisaab** [comment]
@swill thanks, can you help merge this so all current and PRs can be correctly evaluated by travis.

**Comment by swill** [comment]
@bhaisaab would you mind doing a `push -f` on this PR to kick off the Jenkins job again so we can verify it is not failing before I merge.  Thx.

**Pull request merged**
