### PR TITLE
Revert "Add missing HA config keys"

### PR DESCRIPTION
**Pull request by svenvogel**
Reverts apache/cloudstack#3737

issues has been noticed and a fix has been proposed in PR 3773 from 3737
we need to revert this PR.

### CODE REVIEW

**Comment by andrijapanicsb** [comment]
+1, please merge and I've asked the original author of PR #3737 to fix the PR

**Comment by andrijapanicsb** [comment]
LGTM to merge @svenvogel

**Comment by mdominka** [comment]
+1 the revert is ok.

**Comment by svenvogel** [comment]
+1 LGTM

**Pull request merged**
