### PR TITLE
CLOUDSTACK-8611. CS waits indefinitely for CheckS2SVpnConnectionsComm…

### PR DESCRIPTION
**Pull request by likitha**
…and to return.

While remote executing commands through ssh, handle channel condition of EOF because we wait for the the condition.

CheckS2SVpnConnectionsCommand execution involves executing a script (checkbatchs2svpn.sh) in the virtual router. Once CS has opened a session to a virtual router and executed a script in the router, it waits indefinitely till the session either times-out or the exit status of the remote process is available. But it is possible that an EOF is reached by the process in the router and the router never set the exit status.

References -
1. Some servers never send the exist status, or occasionally "forget" to do so (http://grepcode.com/file/repo1.maven.org/maven2/org.jvnet.hudson/trilead-ssh2/build212-hudson-1/com/trilead/ssh2/ChannelCondition.java).
2. Get the exit code/status from the remote command - if available. Be careful - not all server implementations return this value - (http://grepcode.com/file/repo1.maven.org/maven2/org.jvnet.hudson/trilead-ssh2/build212-hudson-1/com/trilead/ssh2/Session.java#Session.waitForCondition%28int%2Clong%29).

Hence if exit status is not set then the command will never return.

### CODE REVIEW

**Comment by remibergsma** [comment]
Who wants to step in and finish this work? It seems the original author is not able to finish it. If no one steps in, we'll have to close the PR without merging it so please help :-).

**Comment by GabrielBrascher** [comment]
Shouldn't the class throw a less generic Exception? A good choice might be the **com.cloud.utils.ssh.SshException.SshException(String)**.
Although this change is out of this PR scope, this got my attention.

**Comment by DaanHoogland** [comment]
@GabrielBrascher If you want to work on this I suggest you pull in the pr branch and push it to your own clone to make a new PR. @likitha has left the community

**Comment by GabrielBrascher** [comment]
That's fair enough @DaanHoogland, I will see what I can do for this PR.

**Pull request closed without merging**
