### PR TITLE
CLOUDSTACK-9069: Newly added project is not showing in the drop down until the browser is refreshed.

### PR DESCRIPTION
**Pull request by nitin-maharana**
The created or deleted project was added to/deleted from the list but it was not being updated.
Now it updates the list at the same time.

### CODE REVIEW

**Comment by bhaisaab** [comment]
LGTM

**Comment by rafaelweingartner** [comment]
In which version is this problem happening?
I tested on CS 4.3.2 and it is working.
I used both Chrome and Firefox.

**Comment by nitin-maharana** [comment]
@rafaelweingartner This is happening in 4.5. I checked with this master.

**Comment by rafaelweingartner** [comment]
@nitin-maharana , I do not have CS 4.6 or 4.5.1 here to test. However, I have compared those files from CS 4.3.2 with files from 4.5.1 and 4.6.0. I could not see a change that would make that stop working (since it is working in 4.3.2). I might have overlooked them, but can someone else also test it?

Additionally, in what browser did you test?

**Comment by nitin-maharana** [comment]
I tested in chrome and firefox.

**Comment by nitin-maharana** [comment]
I checked in Internet Explorer and Chromium browser also. It is working fine.

**Comment by bhaisaab** [comment]
@remibergsma @DaanHoogland anyone wants to review this one?

**Comment by remibergsma** [comment]
@nitin-maharana How do I test this? I tried adding a project but the page keeps loading forever. Which dropdown should I look at?

screen shot 2015-12-07 at 11 50 52

**Comment by nitin-maharana** [comment]
Hi @remibergsma, here I attached the snapshots. See the cursor arrows.
step-1_nitin
step-2_nitin
step-3_nitin

**Comment by remibergsma** [comment]
Hi @nitin-maharana thanks for the info! I built a new cloud and still have the issue that after creating a project it keeps loading forever (see image above). I tried the same on master and there it works.

Also, after creating a project on master, I do see it in the list without refreshing?

screen shot 2015-12-12 at 10 01 54

I might not understand what you fixed, but in any way you seem to introduce a new problem for me. Please have a look.

**Comment by nitin-maharana** [comment]
Hi @remibergsma : Yes, you are correct. This issue is no more in master. I think this issue was resolved with a different PR. So closing the PR. Thanks.

**Pull request closed without merging**
