### PR TITLE
CLOUDSTACK-8862: Introduced new state attaching for volume. This will…

### PR DESCRIPTION
**Pull request by anshul1886**
… make sure that other attach operation on same volume will fail gracefully without calling access calls for managed storage like SolidFire

### CODE REVIEW

**Comment by mike-tutkowski** [comment]
I don't have the resources in my lab available to perform tests on this at this time, but the code itself LGTM.

Thanks for working on this JIRA ticket!

**Comment by karuturi** [comment]
@ProjectMoon @anshul1886  #1898 and #1900 are for the same bug. Can you please collaborate and put a single PR?

**Comment by ProjectMoon** [comment]
@anshul1886 I am fine with putting both commits on either PR. If you are unopposed we can just stick it on mine?

**Comment by anshul1886** [comment]
@ProjectMoon We don't need both the commits.  One of the commit is enough. Correct me if I am missing something.  And I think using state method is better than using lock method.

**Comment by ProjectMoon** [comment]
@anshul1886 I have not delved too deeply into the state machine transition code, though I understand the basics of how it works. I think `synchronized` + state transition should be enough in a single management server scenario, but will it work in a clustered scenario? Of course, `synchronized` cannot lock across processes, which is why CS has the database locks everywhere. If the state transitions will work in a clustered scenario, then I'm fine with just using that one.

**Comment by anshul1886** [comment]
@ProjectMoon Yes it will work fine in clustered scenario as ultimate source of truth is DB.

**Comment by cloudmonger** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 324
 Hypervisor xenserver
 NetworkType Advanced
 Passed=103
 Failed=1
 Skipped=7

_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/yj3wnzbceo9uef2/AAB6u-Iap-xztdm6jHX9SjPja?dl=0


**Failed tests:**
* test_routers_network_ops.py

 * test_03_RVR_Network_check_router_state Failed


**Skipped tests:**
test_01_test_vm_volume_snapshot
test_vm_nic_adapter_vmxnet3
test_static_role_account_acls
test_11_ss_nfs_version_on_ssvm
test_nested_virtualization_vmware
test_3d_gpu_support
test_deploy_vgpu_enabled_vm

**Passed test suits:**
test_deploy_vm_with_userdata.py
test_affinity_groups_projects.py
test_portable_publicip.py
test_over_provisioning.py
test_global_settings.py
test_scale_vm.py
test_service_offerings.py
test_routers_iptables_default_policy.py
test_loadbalance.py
test_routers.py
test_reset_vm_on_reboot.py
test_deploy_vms_with_varied_deploymentplanners.py
test_network.py
test_router_dns.py
test_non_contigiousvlan.py
test_login.py
test_deploy_vm_iso.py
test_list_ids_parameter.py
test_public_ip_range.py
test_multipleips_per_nic.py
test_regions.py
test_affinity_groups.py
test_network_acl.py
test_pvlan.py
test_volumes.py
test_nic.py
test_deploy_vm_root_resize.py
test_resource_detail.py
test_secondary_storage.py
test_vm_life_cycle.py
test_disk_offerings.py

**Comment by anshul1886** [comment]
Rebased with current master.

**Comment by cloudmonger** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 358
 Hypervisor xenserver
 NetworkType Advanced
 Passed=105
 Failed=0
 Skipped=7

_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/yj3wnzbceo9uef2/AAB6u-Iap-xztdm6jHX9SjPja?dl=0


**Failed tests:**

**Skipped tests:**
test_01_test_vm_volume_snapshot
test_vm_nic_adapter_vmxnet3
test_static_role_account_acls
test_11_ss_nfs_version_on_ssvm
test_nested_virtualization_vmware
test_3d_gpu_support
test_deploy_vgpu_enabled_vm

**Passed test suits:**
test_deploy_vm_with_userdata.py
test_affinity_groups_projects.py
test_portable_publicip.py
test_over_provisioning.py
test_global_settings.py
test_scale_vm.py
test_service_offerings.py
test_routers_iptables_default_policy.py
test_loadbalance.py
test_routers.py
test_reset_vm_on_reboot.py
test_deploy_vms_with_varied_deploymentplanners.py
test_network.py
test_router_dns.py
test_non_contigiousvlan.py
test_login.py
test_deploy_vm_iso.py
test_list_ids_parameter.py
test_public_ip_range.py
test_multipleips_per_nic.py
test_regions.py
test_affinity_groups.py
test_network_acl.py
test_pvlan.py
test_volumes.py
test_nic.py
test_deploy_vm_root_resize.py
test_resource_detail.py
test_secondary_storage.py
test_vm_life_cycle.py
test_routers_network_ops.py
test_disk_offerings.py

**Comment by karuturi** [comment]
@anshul1886  can you take a look at the travis and jenkins failures?
volume related tests failed on travis

> 
> +------------------+------------------+------------------+------------------+
> | test_04_deploy_s | Failure          | 15.836           | test_stopped_vm  |
> | tartvm_false_att |                  |                  |                  |
> | ach_volume       |                  |                  |                  |
> +------------------+------------------+------------------+------------------+
> +------------------+------------------+------------------+------------------+
> | test_06_deploy_s | Failure          | 10.782           | test_stopped_vm  |
> | tartvm_attach_de |                  |                  |                  |
> | tach             |                  |                  |                  |
> +------------------+------------------+------------------+------------------+
> | test_08_deploy_a | Failure          | 21.020           | test_stopped_vm  |
> | ttached_volume   |                  |                  |                  |
> +------------------+------------------+------------------+------------------+

**Comment by anshul1886** [comment]
@karuturi @koushik-das @sateesh-chodapuneedi , I had analysed those failures and working on how to go about those. Issue here is that there are marvin tests which are for something which was never working. But nobody has reported any bugs for that. 
When we create VM without starting it(startvm=false), then there are issues. So in this scenario if we try to attach the uploaded volume then its failing in this PR. But in existing code it is passing successfully i.e. DB entries are created. Now when we start the VM then we are doing nothing for uploaded Volume and they always remains in uploaded state and not attached to VM on hypervisor.

This marvin test is there for ages but nobody has reported any issue regarding this. So I am currently analysing how to go about this. Is this even used by Users? Because if they were using this then somebody should have reported this as this was introduced some five years back. I am thinking of  simple solution  which would be to inform user that they have to start vm first (root volume created) before trying to attach volume.

**Comment by cloudmonger** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 391
 Hypervisor xenserver
 NetworkType Advanced
 Passed=105
 Failed=0
 Skipped=7

_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/yj3wnzbceo9uef2/AAB6u-Iap-xztdm6jHX9SjPja?dl=0


**Failed tests:**

**Skipped tests:**
test_01_test_vm_volume_snapshot
test_vm_nic_adapter_vmxnet3
test_static_role_account_acls
test_11_ss_nfs_version_on_ssvm
test_nested_virtualization_vmware
test_3d_gpu_support
test_deploy_vgpu_enabled_vm

**Passed test suits:**
test_deploy_vm_with_userdata.py
test_affinity_groups_projects.py
test_portable_publicip.py
test_over_provisioning.py
test_global_settings.py
test_scale_vm.py
test_service_offerings.py
test_routers_iptables_default_policy.py
test_loadbalance.py
test_routers.py
test_reset_vm_on_reboot.py
test_deploy_vms_with_varied_deploymentplanners.py
test_network.py
test_router_dns.py
test_non_contigiousvlan.py
test_login.py
test_deploy_vm_iso.py
test_list_ids_parameter.py
test_public_ip_range.py
test_multipleips_per_nic.py
test_regions.py
test_affinity_groups.py
test_network_acl.py
test_pvlan.py
test_volumes.py
test_nic.py
test_deploy_vm_root_resize.py
test_resource_detail.py
test_secondary_storage.py
test_vm_life_cycle.py
test_routers_network_ops.py
test_disk_offerings.py

**Comment by sateesh-chodapuneedi** [comment]
LGTM for code changes.
Thanks @anshul1886 for the path.

@karuturi Seems this PR is ready for merge, as it has 2 LGTMs and latest test results from @cloudmonger has 0 failures.

**Comment by cloudmonger** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 416
 Hypervisor xenserver
 NetworkType Advanced
 Passed=105
 Failed=0
 Skipped=7

_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/yj3wnzbceo9uef2/AAB6u-Iap-xztdm6jHX9SjPja?dl=0


**Failed tests:**

**Skipped tests:**
test_01_test_vm_volume_snapshot
test_vm_nic_adapter_vmxnet3
test_static_role_account_acls
test_11_ss_nfs_version_on_ssvm
test_nested_virtualization_vmware
test_3d_gpu_support
test_deploy_vgpu_enabled_vm

**Passed test suits:**
test_deploy_vm_with_userdata.py
test_affinity_groups_projects.py
test_portable_publicip.py
test_over_provisioning.py
test_global_settings.py
test_scale_vm.py
test_service_offerings.py
test_routers_iptables_default_policy.py
test_loadbalance.py
test_routers.py
test_reset_vm_on_reboot.py
test_deploy_vms_with_varied_deploymentplanners.py
test_network.py
test_router_dns.py
test_non_contigiousvlan.py
test_login.py
test_deploy_vm_iso.py
test_list_ids_parameter.py
test_public_ip_range.py
test_multipleips_per_nic.py
test_regions.py
test_affinity_groups.py
test_network_acl.py
test_pvlan.py
test_volumes.py
test_nic.py
test_deploy_vm_root_resize.py
test_resource_detail.py
test_secondary_storage.py
test_vm_life_cycle.py
test_routers_network_ops.py
test_disk_offerings.py

**Comment by ramkatru** [comment]
tag:mergeready

**Comment by anshul1886** [comment]
Fixed minor conflicts.

**Pull request merged**
