### PR TITLE
cks: use public links for templates and binaries iso for smoke tests

### PR DESCRIPTION
**Pull request by shwstppr**
## Description
Use public links for templates and binaries iso for CKS smoke tests

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@andrijapanicsb if we get this to work before release, i'd like it in so we have a clean run from trillian.

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by shwstppr** [comment]
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
@shwstppr can you check those results? two platforms fail but the third passes the same test.

**Comment by DaanHoogland** [comment]
looking at the code i see a `1.16.0` mentioned but on the site it is missing. might that be the issue?

  | Name | Last modified | Size | Description
-- | -- | -- | -- | --
  | Parent Directory |   | - |  
  | setup-1.11.4.iso | 2020-01-14 11:52 | 1.0G |  
  | setup-1.12.5.iso | 2020-01-14 11:54 | 1.0G |  
  | setup-1.13.2.iso | 2020-01-14 11:55 | 927M |  
  | setup-1.14.9.iso | 2020-01-14 11:57 | 1.0G |  
  | setup-1.15.0.iso | 2020-01-14 12:00 | 1.0G |  
  | setup-1.16.3.iso | 2020-01-14 12:01 | 1.0G |

**Comment by DaanHoogland** [comment]
I guess not, the error is in the other test file. Can you please look at this error as well and advice if this can independendly merged, @shwstppr ?

**Comment by shwstppr** [comment]
@DaanHoogland will look at the logs and will try to fix the issue in next hours or tomorrow morning

**Comment by shwstppr** [comment]
> looking at the code i see a `1.16.0` mentioned but on the site it is missing. might that be the issue?
>   	Name 	Last modified 	Size 	Description
>   	Parent Directory 	  	- 	 
>   	setup-1.11.4.iso 	2020-01-14 11:52 	1.0G 	 
>   	setup-1.12.5.iso 	2020-01-14 11:54 	1.0G 	 
>   	setup-1.13.2.iso 	2020-01-14 11:55 	927M 	 
>   	setup-1.14.9.iso 	2020-01-14 11:57 	1.0G 	 
>   	setup-1.15.0.iso 	2020-01-14 12:00 	1.0G 	 
>   	setup-1.16.3.iso 	2020-01-14 12:01 	1.0G

@DaanHoogland yes 1.16.0 is missing and it is needed for testing upgrade on HA k8s cluster. I've internally asked for adding it at a public repo.

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by shwstppr** [comment]
@DaanHoogland 1.16.0 ISO is yet not available on public repo. Plus tests might fail due to Trillian issues right now

**Comment by shwstppr** [comment]
@blueorangutan test matrix

**Comment by shwstppr** [comment]
@blueorangutan test matrix

**Comment by shwstppr** [comment]
@blueorangutan test matrix

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test matrix

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by shwstppr** [comment]
@PaulAngus @rhtyd @borisstoyanov @andrijapanicsb 
Need your opinion on this. Since CKS tests need multiple k8s binaries ISOs (~1GB in size each) which makes tests to run for longer time for download (from the Internet) and install of these ISOs does it make sense to move CKS tests into component tests from smoke-tests?
Or any other way you can suggest to make this part of the tests more reliable, faster?
cc @DaanHoogland

**Comment by rhtyd** [comment]
@shwstppr does it take more than 0.5-1 hour to run the test, I would keep it in smoketest/ 
You can host the isos locally on staging server which is closer to the trillian env; make the url configure URL specific to the Trillian env via its test_data: https://github.com/shapeblue/Trillian/blob/master/Ansible/roles/marvin/templates/test_data.py.j2
The test_data (default) is here: https://github.com/apache/cloudstack/blob/master/tools/marvin/marvin/config/test_data.py

**Comment by DaanHoogland** [comment]
@rhtyd I don't agree either a run of more than 0.5 hour or a download of multiple 1GB files would justify not running it on every test run.
adding the URLs to test_data does certainly make sense though.

**Comment by DaanHoogland** [comment]
@shwstppr could we spoof the ISOs with smaller files and put those in a local webserver somewhere?

**Comment by rhtyd** [comment]
LGTM, merge this @DaanHoogland @andrijapanicsb ?

**Comment by andrijapanicsb** [comment]
@shwstppr can you please advise on the duration of these tests and can we also override the URLs the same way we do with i.e. systemVM templates or default centos templates, to be downloaded actually from our local web server - downloading from download.cloudstack is slow as hell

**Comment by andrijapanicsb** [comment]
[root@ref-trl-902-k-M7-andrija-panic-mgmt1 ~]# wget http://download.cloudstack.org/cks/setup-1.14.9.iso
--2020-05-06 11:32:06--  http://download.cloudstack.org/cks/setup-1.14.9.iso
Resolving download.cloudstack.org (download.cloudstack.org)... 185.27.174.49, 2a00:f10:121:400:403:9cff:fe00:37f
Connecting to download.cloudstack.org (download.cloudstack.org)|185.27.174.49|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1077303296 (1.0G) [application/x-iso9660-image]
Saving to: ‘setup-1.14.9.iso’

100%[=========================================================================>] 1,077,303,296 8.07MB/s   in **2m 8s** 

So for 5 x ISOs, that's 10min at least - could be worse I guess...

**Comment by shwstppr** [comment]
@andrijapanicsb I'll work for overriding URLs with local server URLs as Rohit suggested in next few days or over the weekend. Can be fixed in next release/after 4.14

**Comment by andrijapanicsb** [comment]
sure @shwstppr - keep in mind we override inside Trillian code, not in the public git code here!
thx

**Pull request merged**
