### PR TITLE
[WIP] travis reorganisation

### PR DESCRIPTION
**Pull request by DaanHoogland**
## Description

Due to tests randomly failing with timeout....

### CODE REVIEW

**Comment by DaanHoogland** [comment]
done @borisstoyanov , though there are only three smaller tests in there. doubt if size is really the problem, in this case!???

**Comment by rhtyd** [comment]
Looks good @DaanHoogland I've rekicked Travis; perhaps some of the tests may be clubbed? Ideally if a job passes within 50mins travis does not consider it failed.

**Comment by rhtyd** [comment]
@DaanHoogland can you test latest master, I've tried to re-arrange and fix the failing travis tests due to timeout on 4.11 and forward merged them on 4.12 and master.

**Comment by DaanHoogland** [comment]
ok @rhtyd , i will rebase and force push to looksee

**Comment by rhtyd** [comment]
This is old, there is a new PR related to this effort: https://github.com/apache/cloudstack/pull/3476

**Pull request closed without merging**
