### PR TITLE
Usage event fixes for deleted accounts

### PR DESCRIPTION
**Pull request by nnesic**
Fixes regarding usage event emission. 

UsageEventUtils was previously not checking deleted accounts, which meant that if an account was deleted that had some resources running on it, those resources would get destroyed without emitting any events. 

Furthermore, the VOLUME_DELETE event of ROOT volumes is the responsibility of the UserVmManager, which gets circumvented when expunging resources following the account deletion. Added a check to the AccountManager which catches the ROOT volumes that need to be deleted and emits events for them. 

To test this: Create a new user. As that user, create and destroy an instance. This should cause the VM_CREATE, VM_START, VM_STOP, VM_DESTROY, VOLUME_CREATE, and VOLUME_DELETE events to be emitted. 
Create a new instance as the same user. Log in as admin, and delete the user. The same set of events should be emitted, and there should be no duplicate DELETE events for the ROOT volume of the previous instance.

### CODE REVIEW

**Comment by nnesic** [comment]
Hi, could you please re-trigger the build, since it seems to have crashed?

**Comment by remibergsma** [comment]
Hi @nnesic, you can do that by force pushing your commits again to the PR branch. The tests will then run again.

**Comment by kishankavala** [comment]
@remibergsma We not have any tests that will check for correct events on account delete. 
@nnesic Would you be able to add one?

**Comment by nnesic** [comment]
I added two unit tests to check that the account manager adheres to its new responsibility of emitting the usage events for root volumes of instances which were not in destroyed state prior to the account deletion.

**Comment by remibergsma** [comment]
Pinging @borisroman @michaelandersen to review this PR.

**Comment by nnesic** [comment]
Hello, how is the review on this going?

**Comment by DaanHoogland** [comment]
code reviewed LGTM, @remibergsma kan you start a bubble with this?

**Comment by remibergsma** [comment]
I tried rebasing against current master but I run into build issues. Tried again but same thing.

@nnesic Could you try rebasing the PR against master and run a build?

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:35.871s
[INFO] Finished at: Fri Nov 20 09:51:10 GMT 2015
[INFO] Final Memory: 50M/329M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:testCompile (default-testCompile) on project cloud-server: Compilation failure
[ERROR] /data/git/cs1/cloudstack/dist/rpmbuild/BUILD/cloudstack-4.7.0-SNAPSHOT/server/test/com/cloud/user/MockUsageEventDao.java:[19,7] error: MockUsageEventDao is not abstract and does not override abst
ract method searchAndDistinctCount(SearchCriteria<UsageEventVO>,Filter) in GenericDao
```

**Comment by ProjectMoon** [comment]
The PR has been fixed by the application of two more commits. Maybe squashing is in order before a merge.

The abuse of reflection required to make the unit test play nice is an indicator that maybe that class should be made non-static though.

**Comment by ProjectMoon** [comment]
What's the status of this pull request? Do we need to redo this PR on 4.6 instead? Also what are the thoughts about squashing some of these commits down?

**Comment by bhaisaab** [comment]
@ProjectMoon can you rebase against latest master, and squash changes to a single commit

**Comment by ProjectMoon** [comment]
Squashing and rebasing is definitely needed. But isn't this a bug fix though? And thus should go on to 4.6 and then be forward merged?

**Comment by bhaisaab** [comment]
@ProjectMoon yes please squash them and maybe open a new PR against 4.7 (or 4.6) closing this one as github won't allow you to edit/change the source/dest branches.

**Comment by ProjectMoon** [comment]
New request is located at https://github.com/apache/cloudstack/pull/1372.

**Comment by ProjectMoon** [comment]
I don't have the close button, so this one needs to be closed again.

**Comment by bhaisaab** [comment]
@nnesic since you're the author you can close this PR  @ProjectMoon thanks for the new PR

**Pull request closed without merging**
