### PR TITLE
CLOUDSTACK-9542 make listNics and ListUserVms return uniform NIC data

### PR DESCRIPTION
**Pull request by DaanHoogland**
@PaulAngus @borisroman please see if this is what is expected

### CODE REVIEW

**Comment by borisstoyanov** [comment]
Hey @DaanHoogland I think you pinged the wrong Boris, but don't worry 
@blueorangutan package

**Comment by DaanHoogland** [comment]
sorry @borisroman , just missing you ;)

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
LGTM, no deletions in returned keys just additive changes. @DaanHoogland however a minor note, the comments may be indented, or just removed. I understand that it notes the sequence of keys, however that's not how the params/keys are serialized/returned in the api response. It just makes the code look bit weird IMO :)

**Comment by DaanHoogland** [comment]
@rhtyd I agree with your comment on comments (in this case) however those are there just to keep track for the viewer which has been added in which output. I will add cross references to both bits to each other so future generations will be able to make sense of it.

**Comment by DaanHoogland** [comment]
@borisstoyanov I don't see how a host unreachable can be caused by an API result changing. I will rebase, repackage and retest.

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by cloudmonger** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 1146
 Hypervisor xenserver
 NetworkType Advanced
 Passed=106
 Failed=5
 Skipped=12

_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/r2si930m8xxzavs/AAAzNrnoF1fC3auFrvsKo_8-a?dl=0

**Failed tests:**
* test_volumes.py

 * test_06_download_detached_volume Failing since 2 runs

* test_routers_network_ops.py

 * test_01_isolate_network_FW_PF_default_routes_egress_true Failing since 11 runs

 * test_02_isolate_network_FW_PF_default_routes_egress_false Failing since 138 runs

 * test_01_RVR_Network_FW_PF_SSH_default_routes_egress_true Failing since 133 runs

 * test_02_RVR_Network_FW_PF_SSH_default_routes_egress_false Failing since 133 runs


**Skipped tests:**
test_vm_nic_adapter_vmxnet3
test_01_verify_libvirt
test_02_verify_libvirt_after_restart
test_03_verify_libvirt_attach_disk
test_04_verify_guest_lspci
test_05_change_vm_ostype_restart
test_06_verify_guest_lspci_again
test_static_role_account_acls
test_11_ss_nfs_version_on_ssvm
test_nested_virtualization_vmware
test_3d_gpu_support
test_deploy_vgpu_enabled_vm

**Passed test suits:**
test_deploy_vm_with_userdata.py
test_affinity_groups_projects.py
test_portable_publicip.py
test_vm_snapshots.py
test_over_provisioning.py
test_global_settings.py
test_router_dnsservice.py
test_scale_vm.py
test_service_offerings.py
test_routers_iptables_default_policy.py
test_loadbalance.py
test_routers.py
test_reset_vm_on_reboot.py
test_deploy_vms_with_varied_deploymentplanners.py
test_network.py
test_router_dns.py
test_non_contigiousvlan.py
test_login.py
test_deploy_vm_iso.py
test_list_ids_parameter.py
test_public_ip_range.py
test_multipleips_per_nic.py
test_metrics_api.py
test_regions.py
test_affinity_groups.py
test_network_acl.py
test_pvlan.py
test_nic.py
test_deploy_vm_root_resize.py
test_resource_detail.py
test_secondary_storage.py
test_disk_offerings.py

**Comment by DaanHoogland** [comment]
@blueorangutan  test

**Comment by DaanHoogland** [comment]
question about @cloudmonger, everyone: How to find the error output for the failed tests in the dropbox link. There are only numbered directories in there. Must they be grep'd, i.e. all downloaded to search? or can i find a logical link from a failed test name to a location of it's results? @karuturi @kishankavala @sanjaytripathi , @all, @anyoneelse, ...

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
two runs with the same version led to different fails as I suspected. I don't see direct relation to the code but don't dare to merge. I will rebase and go from there.

**Comment by rhtyd** [comment]
@DaanHoogland please rebase and fix conflicts

**Comment by rhtyd** [comment]
@DaanHoogland can you fix conflicts on your PR?

**Comment by DaanHoogland** [comment]
Yes @rhtyd I will rebase one last time.

**Comment by rhtyd** [comment]
@DaanHoogland thanks, you know you can kick tests yourself!
@blueorangutan package

**Comment by rhtyd** [comment]
@DaanHoogland and also run them ;)
@blueorangutan test

**Comment by rhtyd** [comment]
Tests lgtm, additional review required for merging this.

**Comment by borisstoyanov** [comment]
LGTM, based on the latests test results

**Comment by rhtyd** [comment]
Merged this based on test results and two lgtms/code reviews.

**Pull request merged**
