### PR TITLE
server: use ecdsa instead of ed25519 when generate public/private keys

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR replaces ed25519 with ecdsa.

PR #8549 replaced RSA with ed25519. Unfornately, ed25519 keys is unsupported in FIPS mode

```
$  ssh-keygen -t ed25519 -m PEM -N '' -f key1
ED25519 keys are not allowed in FIPS mode

$  ssh-keygen -t ecdsa -m PEM -N '' -f key1
Generating public/private ecdsa key pair.
Your identification has been saved in key1
Your public key has been saved in key1.pub
The key fingerprint is:
.........

```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test alma9 kvm-alma9

**Review by vishesh92 — COMMENTED** [review]
clgtm

**Review by JoaoJandre — APPROVED** [review]
CLGTM, didn't test it

**Review by rohityadavcloud — APPROVED** [review]

**Comment by weizhouapache** [comment]
@blueorangutan test matrix

**Pull request merged**
