### PR TITLE
[WIP] coverage: fix scaleio plugin code coverage

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes code coverage of scaleio.

The other plugins have the same setting.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
\o/

**Comment by harikrishna-patnala** [comment]
> the unit tests failures have been fixed by @harikrishna-patnala in PR #7408

Not all @weizhouapache there are a couple of other failures in ScaleIOGatewayClientImplTest which I could not figure out.
I was discussing with @vishesh92 on these failures. 

@vishesh92 can you help us fix the tests in ScaleIOGatewayClientImplTest. Also as discussed, in case we cannot fix, lets skip them as they seem to be more of integration tests covering multiple methods.

**Comment by vishesh92** [comment]
@harikrishna-patnala @DaanHoogland @weizhouapache I have fixed the tests and created a new PR here: https://github.com/apache/cloudstack/pull/7622

**Comment by DaanHoogland** [comment]
then let's abandon this for that, @weizhouapache ?

**Comment by weizhouapache** [comment]
> then let's abandon this for that, @weizhouapache ?

yes @DaanHoogland

**Pull request closed without merging**
