### PR TITLE
Change 2FA plugin related global setting names

### PR DESCRIPTION
**Pull request by harikrishna-patnala**
### Description

This is related to the new improvement for 2FA in CloudStack #6924

In this PR we are changing the plugin related global setting names to be more relevant.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by DaanHoogland** [comment]
@harikrishna-patnala this looks like a fix on a new feature . is this critical in any way (to go into 4.18)?

**Comment by weizhouapache** [comment]
> @harikrishna-patnala this looks like a fix on a new feature . is this critical in any way (to go into 4.18)?

this looks like a polish.
However, if config name is changed after 4.18.0 release, a sql in upgrade script is required to rename config name in existing db. I suggest to merge it into 4.18.0

**Comment by harikrishna-patnala** [comment]
if we are about to cut RC2 then can you include this as well in 4.18. This is more of a polish change, since this feature is included in 4.18 it is better to merge this 4.18 instead of 4.18.1

**Comment by harikrishna-patnala** [comment]
yes what @weizhouapache said

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Review by vladimirpetrov — APPROVED** [review]
LGTM based on manual testing.

**Pull request merged**
