### PR TITLE
Changes database upgrade script names to be consistent for the 4.9.1.0 release

### PR DESCRIPTION
**Pull request by jburwell**
* Changes the names of the schema-490to491* scripts to
  schema-490to4910*
  * Changes the name of the Upgrade490to491 class to Upgrade490to4910
  * Modifies the Marvin setup.py script to use version 4.9.1.0-SNAPSHOT

/cc @rhtyd @karuturi

### CODE REVIEW

**Comment by rhtyd** [comment]
@jburwell -1
The db upgrade version only considers the major/minor fields such as a.b.c, the last `.d` is ignored (for that matter any other suffix in the version). Due to the current mechanism of how db versions are implemented, used and run, the change cannot be accepted as it will cause db upgrade failures when the upgrade path is run (as you can see Travis has failed all jobs at the deploydb step). The db upgrade paths therefore won't run for any security release (for example, b/w 4.9.1.0 and 4.9.1.1), unless we want to have db changes between security releases for the same major.minor release?

**Comment by rhtyd** [comment]
With new db schema/versioning and upgrade changes in #1654 we can merge this with some additional changes once #1654 is merged and fwd-merged.

**Comment by rhtyd** [comment]
@jburwell this needs to be reworked now that #1654 is merged. Good to have the changes but not a blocker for 4.8, 4.9 RCs.

**Comment by jburwell** [comment]
@rhtyd I have fixed the ``DatabaseUpgradeCheckerTest`` to reflect 4.9.1.0 being a ``NoopUpgrade``.  I also removed the unnecessary 4.9.0->4.9.1.0 upgrade scripts and class.

**Comment by rhtyd** [comment]
@jburwell we'll need that upgrade path class, we have some alter table changes we want for the 4.9.0->4.9.1.0 upgrade path, see the diff for changes you've removed.

**Comment by jburwell** [comment]
@rhtyd good catch -- sorry for that oversight.  I have redone the PR to only rename the files and class.

**Comment by rhtyd** [comment]
LGTM

**Comment by rhtyd** [comment]
Tests performed:

    - Upgraded from 4.9.0, upgrade path ran (whose sql file names were changed)
    - Clean db deployment

**Comment by rhtyd** [comment]
Tests performed after fwd-merge, all pass:

    - Upgraded from 4.9.1.0
    - Clean db deployment

**Comment by milamberspace** [comment]
LGTM.

Tested on CS 4.9.0 to 4.9.1.0-snapshot installation.
(perhaps just change the comment below inside the SQL file to indicate 4.9.1.0 (missing .0?)
"-- Schema upgrade from 4.9.0 to 4.9.1;"

Logs:
2016-09-02 15:13:45,721 INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) DB version = 4.9.0 Code Version = 4.9.1.0
2016-09-02 15:13:45,722 INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Database upgrade must be performed from 4.9.0 to 4.9.1.0
2016-09-02 15:13:45,723 DEBUG [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Running upgrade Upgrade490to4910 to upgrade from 4.9.0-4.9.1.0 to 4.9.1.0
[...]
2016-09-02 15:13:45,984 DEBUG [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Cleanup script /usr/share/cloudstack-management/setup/db/schema-490to4910-cleanup.sql is executed successfully
2016-09-02 15:13:46,019 DEBUG [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Upgrade completed for version 4.9.1.0

**Comment by rhtyd** [comment]
Thanks @milamberspace 
Based on the tests and LGTMs, I'll proceed with merging this on 4.9. On fwd-merging, I've fixed conflicts and renamed a subsequent class to match the change. Fwd-merged master branch has also passed my tests.

**Pull request merged**
