### PR TITLE
Remove extraenous log dir and add catalina.out log rotation.

### PR DESCRIPTION
**Pull request by PaulAngus**
remove unused /var/log/cloudstack-management directory
add cloudstack-catalina to logrotate.d directory so that /var/log/cloudstack/management/catalina.out is rotated.

### CODE REVIEW

**Comment by wilderrodrigues** [comment]
@PaulAngus, every PR needs an issue on Apache Jira.

In addition, how did you test your changes? Some input will help us to test it as well.

Cheers,
Wilder

**Comment by PaulAngus** [comment]
Apologies.
https://issues.apache.org/jira/browse/CLOUDSTACK-9073  created

removal of /var/log/cloudstack-management
and addition of catalina log rotation in /etc/logrotate.d/
has been running against 4.5.1 for 2 months with no issues.

updated packaging was built against current master and (centos6 and 7) deployed with files/directories as expected.
Left running overnight /var/log/cloudstack/management/catalina.log seen to rotate and compress previous file.

**Comment by jburwell** [comment]
@PaulAngus the change looks reasonable.  Have you checked upgrading the RPM to ensure that the any modified logrotate configuration files are left alone?

**Comment by bhaisaab** [comment]
LGTM, here's a rpm repo built out of this patch: http://sb.bhaisaab.org/cloudstack/paul-rpmpr-1087/centos/paul-rpmpr-1087/

**Comment by remibergsma** [comment]
LGTM, tested on CentOS7:

Logrotate is there:

```
[root@cs1 x86_64]# cat /etc/logrotate.d/cloudstack-catalina 
/var/log/cloudstack/management/catalina.out {
    copytruncate
    daily
    rotate 14
    compress
    missingok
    create 0644 cloud cloud
}
```

And this folder is missing (expected):
```
ls -la /var/log/cloudstack-management/
ls: cannot access /var/log/cloudstack-management/: No such file or directory
```

**Comment by remibergsma** [comment]
@PaulAngus please respond to the comment by @jburwell. After that we can merge.

**Comment by PaulAngus** [comment]
So looking at the rpm spec options using +%config(noreplace) will cause a new version of cloudstack-catalina (cloudstack-catalina.rpmnew) to be created if cloudstack-catalina has been edited.
However as the contents of /etc/logrotate.d/ are enumerated and run this would result in both the new and old behaviour both being applied - which seems the worst of all worlds.
Therefore I suggest the orginal PR (without commit ec698f5377ad98ac2a34488a0102c45c2408d089) which will overwrite if the new rpm has an updated value in it [1]; is the lesser of two evils.

[1] http://www-uxsup.csx.cam.ac.uk/~jw35/docs/rpm_config.html

**Comment by jburwell** [comment]
@PaulAngus sounds like a reasonable solution to preserve custom logrotate configurations on update.  Can you push update the PR to remove commit ec698f5?

**Comment by bhaisaab** [comment]
@PaulAngus please rebase against latest master and force push

**Comment by rhtyd** [comment]
@PaulAngus can you rebase against latest master and share state of your PR, thanks

**Pull request closed without merging**
