### PR TITLE
Enable CPU cap for SSVMs and CPVMs

### PR DESCRIPTION
**Pull request by JoaoJandre**
### Description

Currently it is not possible to create CPU-capped SSVMs or CPVMs, even if the system offering used by these system VMs has this enabled. This is due to the fact that, when creating and persisting SSVMs and CPVMs in the database, the CPU cap configuration of the system offering is not being respected and the value false is always used for the CPU usage limitation option. This behavior has been corrected, so that it is now possible to deploy a CPU-limited SSVM or CPVM, according to the settings of the system offering.

In addition, the standard system offerings for System VMs has been updated so that the CPU cap is enabled, as keeping system VMs without CPU usage limits opens up space for different types of infrastructure attacks/misuses.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?
To test this patch, I ran the SQL script, then checked the DB to see if everything is as expected; then, I recreated the SSVM and CPVM and checked if they were configured with CPU limits.

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by GutoVeronezi** [comment]
@blueorangutan package

**Comment by GutoVeronezi** [comment]
Merging based in the approvals and packaging and CI results. Code smells reported by sonarcloud are not related to the changes.

**Pull request merged**
