### PR TITLE
messages: fix string in pt_BR translation file

### PR DESCRIPTION
**Pull request by bhaisaab**
The string error caused JS error that failed translation on the UI

Signed-off-by: Rohit Yadav <rohit.yadav@shapeblue.com>

### CODE REVIEW

**Comment by terbolous** [comment]
LGTM

**Comment by snuf** [comment]
LGTM

**Comment by milamberspace** [comment]
No LTGM. This isn't the good way to fix this.

**Comment by milamberspace** [comment]
The root cause of this issue is the missing comma after the backslash in the pt_BR translation.

See this key/value on source messages.properties:

message.admin.guide.read=For VMware-based VMs, please read the dynamic scaling section in the admin guide before scaling. Would you like to continue?\,


Generally, the translators on Transifex don't changes the 'special' characters on source language, thus the BR translation (and others languages) must included the backslash in the localization sentence.

But in the case of Portuguese (Brazil) localization, the translator has missed the comma at the end of the sentence (unlike the source language). (the language like French (my native) is good, on master or 4.5, because the comma at the end exists)

The correct fix is:

1/ Fix on Transifex (else, next time when I will update the L10N properties files, your changes will be erased)
2/ Download the new l10n properties from Transifex (all languages or only the language with issue)
3/ Make the PR
4/ Wait the 2 LGTM (if possibly with me, because I follow the L10N process on CloudStack (important for me))
5/ Commit/Merge the PR

You can have some information on the L10N here:
https://cwiki.apache.org/confluence/display/CLOUDSTACK/Update+L10N+files+from+Transifex+to+git+repo

@bhaisaab  I can fix this issue on Transifex (and check for all languages if the comma is missing) and purpose a new PR to (re)fix this issue, Or if you want fix them, free you as felling.

**Comment by bhaisaab** [comment]
@milamberspace :+1: sorry I don't know how to use transifex or how to do translation the right way; I just found this issue in one of the production environment and shared the fix. We should do what you've suggested.

**Comment by milamberspace** [comment]
@bhaisaab I've send 2 PR (one for master/4.6 and one for 4.5 branch) to fix this issue (and update the L10N files) from Transifex.
See #769 and #770

**Pull request merged**
