### PR TITLE
api,server: list autoscalevmgroups with keyword

### LINKED ISSUE #9042: Search Bar at Autoscale Instance Group Page is not working
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Autoscale Group
~~~

##### CLOUDSTACK VERSION

~~~
4.19.0
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

1. Open Autoscale Instance Group Page (View list of ASG Groups)
2. Use search bar on the top right corner

Result is that the page refreshes, but the ASG groups are not filtered accordingly based on the search criteria.

##### STEPS TO REPRODUCE

~~~
N/A
~~~

##### EXPECTED RESULTS

~~~
Result is that the page refreshes, but the ASG groups are not filtered accordingly based on the search criteria.
~~~

##### ACTUAL RESULTS

~~~
Search bar should work accordingly
~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

fixes #9042 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

https://github.com/apache/cloudstack/assets/153340/71d5ea98-f156-4951-a2f9-a305df2e3790

### CODE REVIEW

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by DaanHoogland** [comment]
@shwstppr , did you test this? it seems strange that this would work as the DB does not have a field 'keyword'.  I would expect a bit of code like 
```
        if (keyword != null) {
            SearchCriteria<AccountJoinVO> ssc = _accountJoinDao.createSearchCriteria();
            ssc.addOr("accountName", SearchCriteria.Op.LIKE, "%" + keyword + "%");
            ssc.addOr("state", SearchCriteria.Op.LIKE, "%" + keyword + "%");
            sc.addAnd("accountName", SearchCriteria.Op.SC, ssc);
        }
```
(stolen from ListAccounts)

**Comment by shwstppr** [comment]
> @shwstppr , did you test this? it seems strange that this would work as the DB does not have a field 'keyword'. I would expect a bit of code like
> 
> ```
>         if (keyword != null) {
>             SearchCriteria<AccountJoinVO> ssc = _accountJoinDao.createSearchCriteria();
>             ssc.addOr("accountName", SearchCriteria.Op.LIKE, "%" + keyword + "%");
>             ssc.addOr("state", SearchCriteria.Op.LIKE, "%" + keyword + "%");
>             sc.addAnd("accountName", SearchCriteria.Op.SC, ssc);
>         }
> ```
> 
> (stolen from ListAccounts)

@DaanHoogland at line 1188, name field is used

**Comment by shwstppr** [comment]
And I already added a screen recording of my testing in the description

**Comment by DaanHoogland** [comment]
> @DaanHoogland at line 1188, name field is used

yes, so only the name is possible in a keyword search!? not state, min/max, etc; that is what I question.

**Comment by DaanHoogland** [comment]
> yes, so only the name is possible in a keyword search!? not state, min/max, etc; that is what I question.

I have been reading the code again and I think we may choose to leave it at this , sorry to question @shwstppr . We may allow search for extra but this is at least sensible functionality.

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by vishesh92 — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Comment by DaanHoogland** [comment]
@blueorangutan test alma9 kvm-alma9

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Comment by shwstppr** [comment]
Merging based on approvals and test results

**Pull request merged**
