### PR TITLE
CLOUDSTACK-9503: Increased the VR script timeout. Most of the changes…

### PR DESCRIPTION
**Pull request by abhinandanprateek**
… are about converting int/long time values to joda Duration.

### CODE REVIEW

**Comment by abhinandanprateek** [comment]
Moved PR from 4.9 (https://github.com/apache/cloudstack/pull/1678) to 4.8 here.

**Comment by abhinandanprateek** [comment]
@karuturi I guess jenkins' failure is due to env ? 
"ERROR: Step ‘Archive the artifacts’ failed: no workspace for cloudstack-pr-analysis #2184"

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by jburwell** [comment]
@abhinandanprateek the Jenkins build failed.  Could you please investigate?

**Comment by abhinandanprateek** [comment]
@jburwell The reason is ""ERROR: Step ‘Archive the artifacts’ failed: no workspace for cloudstack-pr-analysis #2184""
I will force push again.

**Comment by rhtyd** [comment]
The following will run an additional component tests:
@blueorangutan test centos7 kvm-centos7 component/test_routers.py component/test_acl_isolatednetwork.py component/test_add_remove_network.py component/test_network_offering.py component/test_persistent_networks.py

**Comment by rhtyd** [comment]
There was an issue with the additionaltests [script](https://github.com/shapeblue/Trillian/blob/master/Ansible/roles/marvin/templates/additionaltests.sh.j2) that caused no outputs in the last comment. I've re-kicked the tests now.

**Comment by karuturi** [comment]
@blueorangutan test matrix component/test_routers.py component/test_acl_isolatednetwork.py component/test_add_remove_network.py component/test_network_offering.py component/test_persistent_networks.py

**Comment by karuturi** [comment]
@blueorangutan help

**Comment by karuturi** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
LGTM. Reviews -- @karuturi @jburwell @murali-reddy and others ?

**Comment by jburwell** [comment]
@rhtyd we have the following failures in the blueoraguntan vmware run that were fixed as part of #1692:

* `test_CreateTemplateWithDuplicateName`
* `test_01_create_template`
* `ContextSuite context=TestTemplates>:setup`

Do we have an explanation for these failures?

**Comment by rhtyd** [comment]
@jburwell I'm running tests on 4.8+ branches to see what tests may have regressed on these branches.
PR #1752  - 4.8
PR #1753  - 4.9
PR #1754  - 4.10

@blueorangutan package

**Comment by jburwell** [comment]
@rhtyd where do we stand determining the root cause of the test failures?

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@jburwell I'll need to rebuild packages, and re-run tests to see where we currently are.

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
LGTM, merging this based on last test run and code reviews.

**Pull request merged**
