### PR TITLE
CLOUDSTACK-9594: Fix regression in test_templates

### PR DESCRIPTION
**Pull request by rhtyd**
Fixes regression in component test `test_templates.py`

### CODE REVIEW

**Comment by rhtyd** [comment]
Tested this manually, the issue was with the test itself.

Test list templates with templatefilter=all is not permitted for normal user ... === TestName: test_01_list_templates_with_templatefilter_all_normal_user | Status : SUCCESS ===          
ok                                                                                  
Test list templates with templatefilter=all is not permitted for domain admin ... === TestName: test_02_list_templates_with_templatefilter_all_domain_admin | Status : SUCCESS === 
ok                                                                                  
                                                                                    
----------------------------------------------------------------------              
Ran 2 tests in 33.051s                                                              
                                                                                    
OK

**Comment by abhinandanprateek** [comment]
LGTM on code review

**Comment by murali-reddy** [comment]
LGTM

**Comment by rhtyd** [comment]
The Travis failure was due to an env issue, I'll merge this on discretion that affected component test has been fixed. The components are added to Travis in 4.9+ branches.

**Pull request merged**
