### PR TITLE
VR: fix data-server if shared network has multiple ip ranges

### LINKED ISSUE #5518: data-server IP provided to the cloud-init if not from the same subnet
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

* VR

##### CLOUDSTACK VERSION

* Tested in 4.14.x, 4.15.0, 4,15.1, 4,15.2

##### CONFIGURATION

  CloudStack with VMware 6.5 with Basic or Advanced Networks.

##### OS / ENVIRONMENT

* CentOS 7, ESXI 6.5

##### SUMMARY
A wrong data-server IP is provided to the cloud-init.

This issue persist for shared networks (Guest traffic) with multiple subnets in Basic network or with Advanced Networks.

##### STEPS TO REPRODUCE

It is simple to reproduce, add multiple CIDR to the same guest router, deploy multiple instances, when a new VM is going to be deployed under different subnet, for some reasons the returned data-server IP is not from VM subnet, it is the IP which is defined in /etc/hosts into the router, example;
149.xx.xx.99 r-xxx-VM data-server

And because it is from different subnet, there is no password saved in the file for different subnet (in router ). in this case, no password is going to be set for this VM.

If I execute this: "cat /var/lib/dhclient/dhclient--eth0.lease | grep dhcp-server-identifier" into the VM the returned IP is the right one. Even if I try to add this to VM host file( IP data-server) ,it is not working, the cloud-init it is using the IP for metadata, and not the host `"http://data-server"`.

##### EXPECTED RESULTS

~~~
 Expected not to have this issue, cloud-init should receive the data-server IP from same subnet as we have on the VM. 
~~~

##### ACTUAL RESULTS

~~~
    data-server IP from a different subnet is returned.
~~~

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #5518

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
@weizhouapache can you re-target to 'main' please.

**Comment by weizhouapache** [comment]
> @weizhouapache can you re-target to 'main' please.

@sureshanaparti done.

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@nvazquez @sureshanaparti 
this is ready for review and test

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Review by sureshanaparti — APPROVED** [review]

**Comment by weizhouapache** [comment]
@blueorangutan test

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
This may needs some checking/testing, not merging this myself cc @nvazquez

**Review by DaanHoogland — APPROVED** [review]
tested
two small ranges in a shared net 10.11.12.10-12 and 10.11.13.10-12. After creating a fourth VM, including VR/dataserver, passwords are still handed out:
image

**Pull request merged**
