### PR TITLE
Updated log message and throw error when unable to update the secret in key file

### PR DESCRIPTION
**Pull request by harikrishna-patnala**
### Description

This PR fixes issue #6232 to update the error message and throw the error when updating key file is failed. This helps to find out the proper reason for failure, mainly with umask.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by harikrishna-patnala** [comment]
@blueoranguton package

**Comment by shwstppr** [comment]
@harikrishna-patnala will it be good to have in 4.17 branch?

**Comment by harikrishna-patnala** [comment]
> @harikrishna-patnala will it be good to have in 4.17 branch?

Yeah, it will be good. Let me change this to 4.17. Thanks @shwstppr

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Review by rohityadavcloud — APPROVED** [review]

**Pull request merged**
