### PR TITLE
Details on add guest os optional

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR fixes a issue reported in the user mail list: https://lists.apache.org/thread/clsoyz3kgp47ppbhtqp8m0o2fkczqrmk

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
I don't think this will be touched by any smoke tests

**Review by BryanMLima — APPROVED** [review]
LGTM, already manually tested this change with PR #6979.

**Review by harikrishna-patnala — APPROVED** [review]
code LGTM

**Pull request merged**
