### PR TITLE
Hide settings button if not on development mode

### PR DESCRIPTION
**Pull request by nvazquez**
### Description

This PR displays the Settings widget only in development mode 
Screenshot from 2021-09-10 09-51-19

After the fix in production:
Screenshot from 2021-09-10 09-49-53

After the fix in development:
Screenshot from 2021-09-10 09-51-19

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by nvazquez** [comment]
@blueorangutan ui

**Review by shwstppr — APPROVED** [review]
Tested on QA server, looks good to me!

**Comment by nvazquez** [comment]
@blueorangutan ui

**Comment by nvazquez** [comment]
@blueorangutan ui

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
Tested lgtm

**Review by shwstppr — APPROVED** [review]
Makes sense to not show settings button in current form. @utchoang maybe we can relook this in 4.16? Currently, it doesn't save settings in any way, not even for a single session.
LGTM

**Pull request merged**
