### PR TITLE
[4.9] Smoketest health checkrun baseline

### PR DESCRIPTION
**Pull request by rhtyd**
@blueorangutan package

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by borisstoyanov** [comment]
@blueorangutan test matrix

**Comment by borisstoyanov** [comment]
I've rebased and pushed in order to get latest master, will rebuild and trigger new tests. 
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@borisstoyanov don't rebase 4.9 against master, this PR/smoketests are intended for 4.9 branch only. For master branch, see #2289

**Comment by borisstoyanov** [comment]
yes, sorry got the wrong PR, will undo shortly

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-55u3

**Pull request closed without merging**
