### PR TITLE
UI: Fix deploy VM wizard vApp properties

### PR DESCRIPTION
**Pull request by nvazquez**
### Description

This PR fixes the vApp properties values sent as part of the deployVirtualMachine API through the UI

Fixes: #7998 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

Tested with vApps containing properties registered as 'Read settings from OVA' templates on Vmware env

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
tested ok with a vstream template. in the ui:
image

call being made:
```
http://localhost:5050/client/api/?zoneid=b97af5af-6dc9-408e-8e5a-d3918591ab95&dynamicscalingenabled=true&iothreadsenabled=false&templateid=d38fd9a5-f30e-42d1-b0a8-740d14aa1f4f&startvm=true&serviceofferingid=5e380a1c-708b-4f48-8aad-c93b8943f387&affinitygroupids=&nicnetworklist[0].nic=12&nicnetworklist[0].network=4430bd0a-978a-43ad-8184-73a680ef6ffc&nicnetworklist[1].nic=13&nicnetworklist[1].network=4430bd0a-978a-43ad-8184-73a680ef6ffc&keypairs=&name=v1&displayname=v1&properties[0].key=A_IPADDR&properties[0].value=10.10.10.1&properties[1].key=B_NETMASK&properties[1].value=255.255.255.0&properties[2].key=C_DEFGATEWAY&properties[2].value=10.10.10.11&properties[3].key=H_HOSTNAME&properties[3].value=vstream&properties[4].key=I_DOMAINNAME&properties[4].value=bla&properties[5].key=E_DNS1&properties[5].value=10.10.10.11&properties[6].key=F_DNS2&properties[6].value=10.10.10.22&properties[7].key=F_NTP1&properties[7].value=10.10.10.11&properties[8].key=G_NTP2&properties[8].value=10.10.10.22&properties[9].key=A_NGENIUS_SERVER_IPV4&properties[9].value=10.10.10.11&properties[10].key=dataDisk&properties[10].value=20&command=deployVirtualMachine&response=json
```

**Review by shwstppr — APPROVED** [review]
Code LGTM

**Comment by DaanHoogland** [comment]
@nvazquez , do you need to add to this or can we merge?

**Comment by nvazquez** [comment]
@DaanHoogland I think this is ready but we could double check other vApps sections as well for verification

**Review by borisstoyanov — APPROVED** [review]
LGTM, just ui changes no need for Marvin tests

**Review by harikrishna-patnala — APPROVED** [review]
LGTM, tested these changes.

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by kiranchavala** [comment]
@blueorangutan package

**Review by kiranchavala — COMMENTED** [review]
@nvazquez If there are no networks available,  the VM deployment form does allow to create a new network 

An existing isolated network should be present  before launching a vm from a vapp


vapp

vapp2

vapp3

**Comment by shwstppr** [comment]
Option to add a new network can be a separate improvement as it has been the same behaviour even before this PR @kiranchavala  cc @nvazquez

**Review by kiranchavala — APPROVED** [review]
LGTM, tested the changes manually

**Pull request merged**
