### PR TITLE
Remove psudo jobs from listAsyncJobs API

### PR DESCRIPTION
**Pull request by davidjumani**
### Description

Removes psudo job results from the response of the listAsyncJobs API

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

#### Before :
```
(localhost) 🐱 > list asyncjobs listall=true filter=jobid,jobinstancetype,
{
  "asyncjobs": [
    {
      "jobid": "27ed55c7-419d-4c69-acfc-496e6f85266a"      <- Psudo job
    },
    {
      "jobid": "3d616d8f-f8ca-413d-a622-25f579137f14"      <- Psudo job
    },
    {
      "jobid": "202fed87-fde7-476e-a829-8d3b39167019"      <- Psudo job
    },
    {
      "jobid": "202fed87-5f85-4767-a622-ee39be729451"      <- Psudo job
    }
    {
      "jobid": "ae46b9e7-d315-4795-bc24-a1fb4bd4ec73",
      "jobinstancetype": "VirtualMachine"
    }
  ],
  "count": 5
}


```

#### After :
```
(localhost) 🐱 > list asyncjobs listall=true filter=jobid,jobinstancetype,
{
  "asyncjobs": [
    {
      "jobid": "eba01225-7029-4730-96e1-b9d38c916657",
      "jobinstancetype": "VirtualMachine"
    }
  ],
  "count": 1
}

```

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan test

**Comment by shwstppr** [comment]
@davidjumani as this is a bugfix should this go in 4.17?

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
Updated the base @shwstppr

**Comment by shwstppr** [comment]
@blueorangutan test

**Review by sureshanaparti — APPROVED** [review]
code LGTM

**Review by harikrishna-patnala — APPROVED** [review]
LGTM

**Review by shwstppr — APPROVED** [review]
Tested with and without this change

Without change (A volume migration is in progress):
```
(localcloud) 🐱 > list asyncjobs listall=true
{
  "asyncjobs": [
    {
      "accountid": "49ab4525-f71a-11ec-87b5-1e0057000461",
      "created": "2022-06-29T11:18:06+0000",
      "jobid": "bde2a196-8e6e-490c-8453-1e5d4dc36971",
      "jobprocstatus": 0,
      "jobresultcode": 0,
      "jobstatus": 0,
      "userid": "49ab5232-f71a-11ec-87b5-1e0057000461"
    },
    {
      "accountid": "49ab4525-f71a-11ec-87b5-1e0057000461",
      "created": "2022-06-29T11:18:06+0000",
      "jobid": "bec2ae08-696b-4bc7-a509-944659f1adb0",
      "jobprocstatus": 0,
      "jobresultcode": 0,
      "jobstatus": 0,
      "userid": "49ab5232-f71a-11ec-87b5-1e0057000461"
    },
    {
      "accountid": "49ac12a3-f71a-11ec-87b5-1e0057000461",
      "cmd": "org.apache.cloudstack.api.command.admin.volume.MigrateVolumeCmdByAdmin",
      "created": "2022-07-27T06:25:55+0000",
      "jobid": "4711fb07-f038-4021-9dbb-5f2eadc3f030",
      "jobinstanceid": "05dd1e62-d2f3-46d8-bd39-401f70941b6f",
      "jobinstancetype": "Volume",
      "jobprocstatus": 0,
      "jobresultcode": 0,
      "jobstatus": 0,
      "userid": "49ad4079-f71a-11ec-87b5-1e0057000461"
    },
    {
      "accountid": "49ac12a3-f71a-11ec-87b5-1e0057000461",
      "cmd": "com.cloud.vm.VmWorkMigrateVolume",
      "created": "2022-07-27T06:25:55+0000",
      "jobid": "286823ce-df79-49e6-886e-91da9eab16fd",
      "jobprocstatus": 0,
      "jobresultcode": 0,
      "jobstatus": 0,
      "userid": "49ad4079-f71a-11ec-87b5-1e0057000461"
    }
  ],
  "count": 4
}
```

With change (Again a volume migration is in progress):
```
(localcloud) 🐱 > list asyncjobs listall=true
{
  "asyncjobs": [
    {
      "accountid": "49ac12a3-f71a-11ec-87b5-1e0057000461",
      "cmd": "org.apache.cloudstack.api.command.admin.volume.MigrateVolumeCmdByAdmin",
      "created": "2022-07-27T07:07:58+0000",
      "jobid": "8f52f1ed-920e-429a-a45b-bb0e9eab7072",
      "jobinstanceid": "05dd1e62-d2f3-46d8-bd39-401f70941b6f",
      "jobinstancetype": "Volume",
      "jobprocstatus": 0,
      "jobresultcode": 0,
      "jobstatus": 0,
      "userid": "49ad4079-f71a-11ec-87b5-1e0057000461"
    }
  ],
  "count": 1
}
```

**Pull request merged**
