### PR TITLE
Allow CGN (RFC6598) to be used within a VPC

### PR DESCRIPTION
**Pull request by leprechau**
Add the CGN network to the list of allowed netblocks for guest networks.  Additionally convert the previous strings to a list to allow easier modification/expansion in the future if needed.

### CODE REVIEW

**Comment by kiwiflyer** [comment]
cgn_example

**Comment by kiwiflyer** [comment]
successful_cgn

**Comment by kiwiflyer** [comment]
rfc1918_example

**Comment by kiwiflyer** [comment]
show_successful_rfc1918

**Comment by kiwiflyer** [comment]
public_example

**Comment by kiwiflyer** [comment]
error_screen

**Comment by kiwiflyer** [comment]
vr_interface

**Comment by kiwiflyer** [comment]
vr_routes

**Comment by kiwiflyer** [comment]
Tested in a 4.8 lab. Verified as per screen shots that all RFC 1918 and RFC 6598 ranges work. Attempting to use a public cidr produces an error as expected. Interface is correctly configured on the VR and the routing table is correct and matches the interface the private gateway was configured on (eth3).

LGTM

**Comment by rhtyd** [comment]
LGTM (did not test it, kicked a packaging build)

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by jburwell** [comment]
@kiwiflyer are there Marvin tests that verify this behavior?

**Comment by kiwiflyer** [comment]
John, I'll defer to Aaron on this, as he submitted the PR.

**Comment by jburwell** [comment]
@leprechau following up regarding Marvin tests.  Unless they are ready, we are likely going to have to push this PR to 4.9.2.0 since I am trying to get a 4.8.2.0 RC cut ASAP (we are week late already).

**Comment by leprechau** [comment]
@jburwell Not really sure what you would want as far as tests.  There shouldn't be any change that would alter existing functionality as demonstrated by the above screenshots.  If there is something I'm missing please let me know.

**Comment by jburwell** [comment]
@leprechau you have expanded the type of networks blocks supported by the system.  Therefore, there should be a Marvin test case that attempts to specify a CGN network block for a guest network and verifies that the system behaves as expected.  In particular, the test should verify that the API calls are successful, and that the networks are implemented as expected when a CGN network block is specified.

**Comment by leprechau** [comment]
@jburwell Is there already an existing test for the previous behavior that could be modified?  I haven't had a chance to do much with Marvin other than briefly browse the tests folder.

**Comment by koushik-das** [comment]
@leprechau You may add an unit test as well for NetUtils.validateGuestCidr(). Check NetUtilsTest.java, there is already an existing test for 192.168.

**Comment by jburwell** [comment]
@leprechau I would like to get this fix into 4.8.2.0, 4.9.1.0, and 4.10.0.0.  Have you had a chance to add the unit tests requested?  Also, is there a JIRA ticket for this bug?

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
LGTM on tests and code review.
@leprechau @kiwiflyer can we have a JIRA id for this and use that in the commit summary.

**Comment by rhtyd** [comment]
Ping @leprechau @kiwiflyer

**Comment by kiwiflyer** [comment]
I've added issue Jira CLOUDSTACK-9661 to track this.
https://issues.apache.org/jira/browse/CLOUDSTACK-9661

@leprechau @rhtyd

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by leprechau** [comment]
What's the current status of this PR?  Is this acceptable as is?

**Comment by rossor** [comment]
Is it appropriate to add a comparatively complex integration test to cover a functional predicate whose cognitive load is so small?

I will expand the associated unit test to include boundary conditions testing of the CGN address range, and that would seem to me to be sufficient. Please advise.

@karuturi

**Comment by karuturi** [comment]
@rossor unittest would be nice to have. Can you also rebase this PR to 4.9?

**Comment by karuturi** [comment]
@rhtyd Can you run tests on this please?

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by karuturi** [comment]
@borisstoyanov @rhtyd @DaanHoogland Can you run tests on this PR? it only has package build

**Comment by DaanHoogland** [comment]
@leprechau @karuturi I can run tests but there are no added unit or integration tests. This has no value for this fix, only for detecting regression in other code or in the tests due to this change.
@blueorangutan test

**Comment by karuturi** [comment]
@rossor Can you check on the travis and jenkins failures? 
looks like there are checkstyle issues in the new code.

**Comment by leprechau** [comment]
@rossor @nathanejohnson Can we get the code formatted correctly so the tests pass?

**Comment by leprechau** [comment]
@kiwiflyer @karuturi Tests passed!

**Pull request merged**
