### PR TITLE
Display hypervisor type for VM snapshot

### PR DESCRIPTION
**Pull request by ravening**
## Description

The "hypervisor" field in listvmsnapshot response will
be used in primate to enable/disable creating a snapshot
from VM snapshot functionality.

Creating snapshot from VM snapshot will be enabled only if
the hypervisor is KVM

## Types of changes

- [X] Enhancement (improves an existing feature and functionality)

## How Has This Been Tested?

Cloudmonkey output

```
(local) 🐵 > list vmsnapshot
{
  "count": 2,
  "vmSnapshot": [
    {
      "account": "admin",
      "created": "2020-08-18T11:12:11+0000",
      "current": true,
      "displayname": "i-2-5-VM_VS_20200818111211",
      "domain": "ROOT",
      "domainid": "f47-c10d-11ea-8715-063381",
      "hypervisor": "KVM",
      "id": "d34f9-df5a-4510-985a-e7f508ad",
      "name": "i-2-5-VM_VS_20200818111211",
      "state": "Ready",
      "tags": [],
      "type": "DiskAndMemory",
      "virtualmachineid": "52cfd-e8d6-4c85-a7e0-f603f151",
      "zoneid": "d0802-be7b-4345-8b55-1612c0b"
    },
    {
      "account": "admin",
      "created": "2020-08-17T15:48:08+0000",
      "current": true,
      "description": "second",
      "displayname": "second",
      "domain": "ROOT",
      "domainid": "f4702-c10d-11ea-8715-0623381",
      "hypervisor": "KVM",
      "id": "c953-0836-4d75-83a7-f805f8ad",
      "name": "i-2-8-VM_VS_20200817154808",
      "state": "Ready",
      "tags": [],
      "type": "DiskAndMemory",
      "virtualmachineid": "3c34-99d2-491c-b1a1-228ec87cb",
      "zoneid": "d0802-be7b-4345-8b55-1612fe0b"
    }
  ]
}
```

### CODE REVIEW

**Comment by ravening** [comment]
@rhtyd @davidjumani Please review

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
@blueorangutan package

**Review by davidjumani — APPROVED** [review]
LGTM

**Comment by rhtyd** [comment]
(centos8 failure is ignorable as 4.14 does not support centos8 pkg support)

**Comment by rhtyd** [comment]
Explicit smoketest is not needed as fix is presentation on API layer and we can merge as soon as Travis passes.

**Pull request merged**
