### PR TITLE
Removed unused agent command AttachVolumeCommand and corresponding an…

### PR DESCRIPTION
**Pull request by koushik-das**
…swer AttachVolumeAnswer

These types are not used anywhere in the orchestration layer.

### CODE REVIEW

**Comment by bhaisaab** [comment]
@koushik-das what are the volume attach/detach agent commands, if these are not being used?

**Comment by koushik-das** [comment]
@bhaisaab I am not sure what was the exact purpose of these agent commands. I believe these existed even before the code was donated to Apache. But if you look at the code these are not used anywhere (other than the HV resource layer).

**Comment by bhaisaab** [comment]
@koushik-das thanks for replying.

LGTM.

**Comment by snuf** [comment]
LGTM

**Comment by koushik-das** [comment]
Merging as 2 LGTMs

**Comment by koushik-das** [comment]
@remibergsma I merged this using the tool but still the merge commit didn't automatically get the messages. I manually added some of the messages for now. For another PR also I saw the same. Is the issue not yet fixed?

tools/git/git-pr 743

**Comment by koushik-das** [comment]
Output of the tmp file

$cat .git-tmp-message.txt
Merge pull request #743 from koushik-das/code_cleanup

Removed unused agent command AttachVolumeCommand and corresponding answer AttachVolumeAnswer

These types are not used anywhere in the orchestration layer.

**Comment by remibergsma** [comment]
@koushik-das I tried it and it works for me. Can you tell me about your environment (OS, shell, ?) Maybe I might be able to figure it out (line 220 maybe). You can also try to run it using 'bash -x tools/git/git-pr 743` and send me the output. I'll then debug it. Thx!

**Pull request merged**
