### PR TITLE
UI: Add authmethod field allowing to choose password or ssh key when adding host

### PR DESCRIPTION
**Pull request by utchoang**
### Description

This PR for fixes https://github.com/apache/cloudstack/issues/6499

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):
image
image

### CODE REVIEW

**Comment by harikrishna-patnala** [comment]
Thanks for the PR @utchoang.
I've quickly tested this and works well for KVM in zone wizard.
image
image


The thing I saw with other hypervisors is the password tab appears under "Authentication Method". Is there a way we can skip both the "Authentication Method" heading and Password tab completely? 

Following is the screenshot I saw when I go back and try to add Xenserver cluster and host
image

**Comment by harikrishna-patnala** [comment]
Wow, that's quick.

image

I saw the tooltip has gone but I still see this password tab @utchoang.

Also, I just realised "Add host" form also shows the password tab for non-kvm hypervisor types. I don't think it is kept intentionally. What do you say @utchoang

**Comment by utchoang** [comment]
@harikrishna-patnala Same with "Add Host" it remains for non-KVM hypervisors. I think it's okay to keep it, but if you want I can delete it.
image

**Review by harikrishna-patnala — APPROVED** [review]
Yeah, let's keep it the same way here, may be it helps in future when we add it to other hypervisors. Thanks for all the changes @utchoang 

LGTM

**Review by rohityadavcloud — APPROVED** [review]

**Comment by sureshanaparti** [comment]
@blueorangutan ui

**Pull request merged**
