### PR TITLE
[4.9] Smoketest Health

### PR DESCRIPTION
**Pull request by rhtyd**
@blueorangutan package

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
I'll be fixing some env issues and possible regressions causing this today.

**Comment by rhtyd** [comment]
@blueorangutan test centos7 kvm-centos6

**Comment by murali-reddy** [comment]
@blueorangutan test centos7 vmware-55u3

**Comment by murali-reddy** [comment]
@blueorangutan test centos7 xenserver-65sp1

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
:happy: smoke tests looking a lot greener for the first time!

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
All tests on 4.9 LGTM. The failing rvr/vpc tests are known intermittent issues and one failing volumes related test on kvm is known due to volume re-attachement issues (previously detached volumes don't actually get detached and occupy the device/slot until a VM stop/start operation, known issue on certain kvm/libvirt/qemu based os configuration).

**Comment by rhtyd** [comment]
Component tests results:
https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr1837-t732-kvm-centos7.zip
https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr1837-t733-vmware-55u3.zip
https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr1837-t734-xenserver-65sp1.zip

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
/cc @karuturi running a test on 4.9 as well, given several failures in recent/last set of tests
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Kicking one more time
@blueorangutan package

**Comment by rhtyd** [comment]
(tests did not run :( )
@blueorangutan package

**Comment by rhtyd** [comment]
Will create  a new PR, this has too many comments now.

**Comment by rhtyd** [comment]
New: https://github.com/apache/cloudstack/pull/2115

**Pull request closed without merging**
