### PR TITLE
CLOUDSTACK-9334: Support jenv and pyenv to manage Java and Python versions

### PR DESCRIPTION
**Pull request by jburwell**
* Adds .java-version to specify Java 1.7 as the JDK version to use
    for CloudStack development.  jenv does not support comments in
    this file.  Therefore, no license header is present.
  * Adds .python-vresion to specify Python 2.7.11 as the Python to
    use for CloudStack development.  pyenv does not support comments
    in this file.  Therefore, no license header is present.
  * Adds requirements.txt to specify the default dependencies used
    for CloudStack development.  It does not include Marvin's
    dependencies because it's bundle already defines the dependencies
    which are installed with Marvin.
  * Updates INSTALL.md to explain how to utilize jenv and pyenv for
    CloudStack development

### CODE REVIEW

**Comment by jburwell** [comment]
Jenkins has failed on RAT, but the report doesn't indicate the nature of the problem.  As an attempt to debug, I was unable to replicate the failure locally executing the following command:
```
mvn --projects='org.apache.cloudstack:cloudstack' org.apache.rat:apache-rat-plugin:0.10:check
```
Anyone have any thoughts on the cause of the error?

**Comment by DaanHoogland** [comment]
@jburwell the failure is not in rat but in the unit tests for the secondary storage controller project

**Comment by jburwell** [comment]
@DaanHoogland I don't know how these changes could cause secondary storage controller unit tests to break.  Unfortunately, the Jenkins report link returns a 404.  Locally, all unit tests pass on the branch.  Could you push up a log with the errors?

**Comment by DaanHoogland** [comment]
@jburwell please restart the jenkins run (force push/close re-open) The logs have been deleted from jenkins.

**Comment by jburwell** [comment]
@DaanHoogland I forced pushed which triggered both Travis and Jenkins to rebuild PR.  However, the Jenkins details link still yields a 404.  Any thoughts on how I can get information about the Jenkins failure?

**Comment by DaanHoogland** [comment]
so it was a timeout:
```
[INFO] Apache CloudStack Plugin - Quota Service ........... SUCCESS [ 44.634 s]
[INFO] Apache CloudStack Framework - Spring Module ........ SUCCESS [ 38.721 s]
[INFO] Apache CloudStack Secondary Storage Controller ..... FAILURE [10:04 min]
[INFO] Apache CloudStack Client UI ........................ SKIPPED
[INFO] Apache CloudStack Console Proxy - RDP Client ....... SKIPPED
[INFO] Apache CloudStack Console Proxy .................... SKIPPED
[INFO] Apache CloudStack Console Proxy - Server ........... SKIPPED
[INFO] Apache CloudStack Framework - QuickCloud ........... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:25 h
[INFO] Finished at: 2016-04-13T22:08:13+00:00
[INFO] Final Memory: 249M/4518M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:findbugs-maven-plugin:3.0.1:findbugs (findbugs) on project cloud-controller-secondary-storage: Execution findbugs of goal org.codehaus.mojo:findbugs-maven-plugin:3.0.1:findbugs failed: Timeout: killed the sub-process -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :cloud-controller-secondary-storage
Build step 'Invoke top-level Maven targets' marked build as failure
[CHECKSTYLE] Skipping publisher since build result is FAILURE
[FINDBUGS] Skipping publisher since build result is FAILURE
[PMD] Skipping publisher since build result is FAILURE
[DRY] Skipping publisher since build result is FAILURE
Archiving artifacts
Skipping Cobertura coverage report as build was not UNSTABLE or better ...
Publishing Clover coverage report...
No Clover report will be published due to a Build Failure
Putting comment on the pull request
Finished: FAILURE
```

**Comment by jburwell** [comment]
@DaanHoogland I rebased against master, and Travis and Jenkins have gone green.  Looks like my branch was out of date.

**Comment by rhtyd** [comment]
tag:needlove

**Comment by jburwell** [comment]
@rhtyd @DaanHoogland @swill I don't think any tests are necessary for this PR.  Would y'all mind reviewing for LGTM?

**Comment by swill** [comment]
Since both Jenkins and Travis are green, I agree that we don't need to do any further testing on this one.

I will give this a LGTM, can I get one more?

**Comment by rhtyd** [comment]
I'll play with pyenv, jenv tomorrow and keep you posted

**Comment by rhtyd** [comment]
Tested locally on Ubuntu Linux 16.04, had to install some build dependencies as README suggests to get pyenv installed. LGTM

@swill ready for merge

**Comment by swill** [comment]
### CI RESULTS

```
Tests Run: 85
  Skipped: 0
   Failed: 2
   Errors: 0
 Duration: 9h 17m 35s
```

**Summary of the problem(s):**
```
FAIL: Create a redundant VPC with two networks with two VMs in each network and check default routes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/git/cs1/cloudstack/test/integration/smoke/test_vpc_redundant.py", line 559, in test_02_redundant_VPC_default_routes
    self.do_default_routes_test()
  File "/data/git/cs1/cloudstack/test/integration/smoke/test_vpc_redundant.py", line 701, in do_default_routes_test
    (vmObj.get_ip(), e)
AssertionError: SSH Access failed for <marvin.lib.base.PublicIPAddress instance at 0x2e91c68>: SSH connection has Failed. Waited 600s. Error is SSH Connection Failed
----------------------------------------------------------------------
Additional details in: /tmp/MarvinLogs/test_network_1AG6V1/results.txt
```

```
FAIL: test_04_rvpc_privategw_static_routes (integration.smoke.test_privategw_acl.TestPrivateGwACL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/git/cs1/cloudstack/test/integration/smoke/test_privategw_acl.py", line 277, in test_04_rvpc_privategw_static_routes
    self.performVPCTests(vpc_off)
  File "/data/git/cs1/cloudstack/test/integration/smoke/test_privategw_acl.py", line 282, in performVPCTests
    vpc_2 = self.createVPC(vpc_off, cidr = '10.0.2.0/24')
  File "/data/git/cs1/cloudstack/test/integration/smoke/test_privategw_acl.py", line 349, in createVPC
    self.fail('Unable to create VPC due to %s ' % e)
AssertionError: Unable to create VPC due to Job failed: {jobprocstatus : 0, created : u'2016-05-12T12:52:04+0200', jobresult : {errorcode : 530, errortext : u'Failed to create VPC'}, cmd : u'org.apache.cloudstack.api.command.admin.vpc.CreateVPCCmdByAdmin', userid : u'02e9d9ca-17f7-11e6-931b-5254001daa61', jobstatus : 2, jobid : u'287143c9-e2e7-4492-8604-85de53ce169a', jobresultcode : 530, jobresulttype : u'object', jobinstancetype : u'None', accountid : u'02e9beb7-17f7-11e6-931b-5254001daa61'} 
----------------------------------------------------------------------
Additional details in: /tmp/MarvinLogs/test_network_1AG6V1/results.txt
```



**Associated Uploads**

**`/tmp/MarvinLogs/DeployDataCenter__May_12_2016_06_10_12_GP20SX:`**
* [dc_entries.obj](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1460/tmp/MarvinLogs/DeployDataCenter__May_12_2016_06_10_12_GP20SX/dc_entries.obj)
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1460/tmp/MarvinLogs/DeployDataCenter__May_12_2016_06_10_12_GP20SX/failed_plus_exceptions.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1460/tmp/MarvinLogs/DeployDataCenter__May_12_2016_06_10_12_GP20SX/runinfo.txt)

**`/tmp/MarvinLogs/test_network_1AG6V1:`**
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1460/tmp/MarvinLogs/test_network_1AG6V1/failed_plus_exceptions.txt)
* [results.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1460/tmp/MarvinLogs/test_network_1AG6V1/results.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1460/tmp/MarvinLogs/test_network_1AG6V1/runinfo.txt)

**`/tmp/MarvinLogs/test_vpc_routers_LIT1HH:`**
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1460/tmp/MarvinLogs/test_vpc_routers_LIT1HH/failed_plus_exceptions.txt)
* [results.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1460/tmp/MarvinLogs/test_vpc_routers_LIT1HH/results.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1460/tmp/MarvinLogs/test_vpc_routers_LIT1HH/runinfo.txt)


Uploads will be available until `2016-07-12 02:00:00 +0200 CEST`

*Comment created by [`upr comment`](https://github.com/cloudops/upr).*

**Comment by swill** [comment]
I think this one is ready...

**Pull request merged**
