### PR TITLE
Follow consistent vo table name convention

### PR DESCRIPTION
**Pull request by davidjumani**
### Description

Follows a consistent way of specifying the table name for a VO in the annotation

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan test

**Review by DaanHoogland — APPROVED** [review]
looks good, is there some automation requirement behind this, or is it 'just' a cleanup?

**Comment by davidjumani** [comment]
> looks good, is there some automation requirement behind this, or is it 'just' a cleanup?

Just some good old regex

**Comment by davidjumani** [comment]
@blueorangutan test

**Review by GabrielBrascher — APPROVED** [review]
Code LGTM :+1:

**Review by sureshanaparti — APPROVED** [review]
@davidjumani thanks for these changes, easy to figure out used tables (with the consistent format) :-).

code LGTM.

**Review by GutoVeronezi — APPROVED** [review]

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan test

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
@davidjumani can you check and confirm if the above test failure is related to this PR changes or not.

**Comment by davidjumani** [comment]
@sureshanaparti the failures are unrelated to the PR, if it should have failed, it would be caught during compile time since the changes were only cosmetic

**Comment by nvazquez** [comment]
Thanks @davidjumani, merging based on approvals and test results

**Pull request merged**
