### PR TITLE
Modified Zone and VPC DB table schema to add IPv6 attributes to support IPv6. 

### PR DESCRIPTION
**Pull request by sureshr-hasvik**
This is one of the initial code changes required for CLOUDSTACK-8529

### CODE REVIEW

**Comment by karuturi** [comment]
@sureshr-hasvik This PR has a lot more other changes. Can you please rebase and update it?

**Comment by wilderrodrigues** [comment]
@sureshr-hasvik  I cannot merge, or even review, your PR. It was not rebased before being created and now contains 190 commits, that already reached master several days ago.

You have to update your fork master branch with latest from master. Once that's done, you have to rebase you branch based on your master. Only after that you push and create the PR.

Please, close this PR.

**Comment by sureshr-hasvik** [comment]
Reviewers, thanks for looking into the PR quickly. 
feature/vpc-ipv6 branch in ACS repo is not up to date. So, when I did a PR bunch of commits also came along with it. I will close the PR and I will fix this later.

**Comment by sureshr-hasvik** [comment]
Closing the PR as this has lot of commits to be merged.

**Pull request closed without merging**
