### PR TITLE
Fix Div overlay problem when PopUp modal with error message is closed

### PR DESCRIPTION
**Pull request by rafaelweingartner**
## Description

The error fixed by this PR happens when we have a Pop-up modal with an error message in the latest master. When we close the modal, the overlay div is not being hidden. Therefore, the screen gets locked. 

image

image

The solution is quite simple, we should hide the overlay div when closing the modal pop-up.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?
Manually

## Checklist:

- [ ] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
Testing
- [ ] I have added tests to cover my changes.
- [ ] All relevant new and existing integration tests have passed.
- [ ] A full integration testsuite with all test that can run on my environment has passed.

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@rafaelweingartner how and when was this introduced? i.e. is it for 4.11 as well?

**Comment by rafaelweingartner** [comment]
During jQuery-UI upgrade. Our jQuery UI was quite old and some of its function changed behavior during this time. That PR was only merged into master not 4.11. Therefore, we only need to address master here.

**Comment by DaanHoogland** [comment]
ok, lgtm

**Comment by rafaelweingartner** [comment]
@DaanHoogland thanks!
It was my fault, during the upgrade I tested only the happy day. I forgot to test the alternative execution flown when we have exceptions, and then these popups are used.

**Pull request merged**
