### PR TITLE
ui: show guest networks for guest vlans list

### LINKED ISSUE #7247: Assign a network name column in the Guest Vlan page
##### ISSUE TYPE

 * Enhancement Request

##### COMPONENT NAME

~~~
Componet:UI
Componet:api
~~~

##### CLOUDSTACK VERSION

~~~
4.18 nightly
4.17.2

~~~

##### SUMMARY

Assign a network name column in the Guest Vlan page

Have the network name as a  column in this page ( Network > Guest Vlan) 

Currently to identify the mapping between guestvlan and networks

User has to click on the Vlan id > Guestnetworks > 

It will be easy for the admin user to identify the relation with the networks if its on the main page of guest vlan 

https://cloudstack.apache.org/api/apidocs-4.17/apis/listGuestVlans.html
guestvlan1

guestvlan2

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #7247

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):
Screenshot from 2024-08-20 17-14-40

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by weizhouapache** [comment]
@shwstppr 
code lgtm
have you tested user-shared networks ?

**Comment by shwstppr** [comment]
@weizhouapache I'm not sure but is there some backend issue with VLANs for shared networks?
While VLAN is assigned to the network, it still shows as Free in the VLANs list

image

image

Also, we maybe returning DB IDs in the listguestvlans API

**Comment by weizhouapache** [comment]
> @weizhouapache I'm not sure but is there some backend issue with VLANs for shared networks? While VLAN is assigned to the network, it still shows as Free in the VLANs list
> 
> image
> 
> image
> 
> Also, we maybe returning DB IDs in the listguestvlans API

if create a shared network with specified vlan and skip vlan overlap check, the vlan will not be updated in table `op_dc_vnet_alloc`

to test user-shared network, you can
- create a network offering for shared network with specifyvlan=false
- create a shared network with the new network offering
- you need to specify an isolated (or L2) network with associated network (the two networks will use the same vlan).

when done, the guest networks tab will list both networks, for example

image


the table `op_dc_vnet_alloc` does not have column `uuid` so only `id` is returned and displayed on UI.
considering the api is only available for root admin, it might be a minor issue

**Comment by shwstppr** [comment]
@weizhouapache works fine
image

**Comment by weizhouapache** [comment]
> @weizhouapache works fine image

cool, thanks @shwstppr

**Review by weizhouapache — APPROVED** [review]
lgtm

**Review by kiranchavala — APPROVED** [review]
LGTM, the guest networks information is displayed on the vlan view


Screenshot 2024-08-29 at 6 09 08 PM

**Pull request merged**
