### PR TITLE
Prevent vm's from stopping while enabling maintenance mode

### PR DESCRIPTION
**Pull request by ravening**
### Description
Sometimes when host isput into maintenance, the connection get
disconnected and as result vm's are stopped. So check for extra state
before considering host as down and stopping the vm's

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [X] Trivial

### CODE REVIEW

**Comment by rhtyd** [comment]
@ravening shouldn't we want to be able to control some vm lifecycle (at least things like stop) if host is in maintenance mode, could that cause a regression (in expected behaviour). what's the use-case for this?

**Comment by nvazquez** [comment]
@ravening the only use case I can think of (tested before) is having a single active host, then attempting to put the host into maintenance. Can you elaborate on the use cases?

**Comment by ravening** [comment]
@rhtyd @nvazquez we have seen some corner cases when maintenance mode was enabled on host, the connection gets disconnected with mgt server and as a result it thinks that host is down and it stops the vm rather than migrating the vm's away which is supposed to be the default behavior

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by DaanHoogland — APPROVED** [review]

**Comment by nvazquez** [comment]
Been trying to reproduce the issue but couldn't, pinging @rhtyd @weizhouapache @sureshanaparti the changes makes sense however I could not reproduce the failure to test the fix, please advise if you figure out a way to reproduce it

**Comment by rhtyd** [comment]
I've no idea Nicolas
@blueorangutan package

**Comment by weizhouapache** [comment]
@ravening @nvazquez @rhtyd 
can we move to 4.16.1 ?

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
> Been trying to reproduce the issue but couldn't, pinging @rhtyd @weizhouapache @sureshanaparti the changes makes sense however I could not reproduce the failure to test the fix, please advise if you figure out a way to reproduce it

@nvazquez What steps you tried to reproduce it? May be, keep as many VMs possible in a host, and try rebooting host / disconnecting host agent as soon as maintenance is enabled. @ravening can you confirm on how to reproduce / verify this?

**Comment by ravening** [comment]
> > Been trying to reproduce the issue but couldn't, pinging @rhtyd @weizhouapache @sureshanaparti the changes makes sense however I could not reproduce the failure to test the fix, please advise if you figure out a way to reproduce it
> 
> @nvazquez What steps you tried to reproduce it? May be, keep as many VMs possible in a host, and try rebooting host / disconnecting host agent as soon as maintenance is enabled. @ravening can you confirm on how to reproduce / verify this?

@sureshanaparti @nvazquez this issue mostly happens when you try to enable maintenance mode on the host but it fails to enter the maintenance mode and rathen it goes into disconnected state. In that case vm's will be stopped as they cant be reached through agent.

Im ok to close this pr, if it cant be reproduced

**Comment by kricud** [comment]
@ravening @sureshanaparti @nvazquez Encountered this two days ago. Doing regular maintenance on KVM hosts Ubuntu 18.04/16.04 ACS 4.15.1. Put KVM host in maintenance and some VM are migrate with shutdown. Happened in advanced and basic networking around 10~ VM where affected.

2021-09-21 15:04:01,620 DEBUG [c.c.c.CapacityManagerImpl] (Work-Job-Executor-114:ctx-92ff343d job-537958/job-538524 ctx-23550d3b) (logid:ff628fbe) VM state transitted from :Running to Stopping with event: StopRequestedvm's original host id: 183 new host id: 184 host id before state transition: 184
2021-09-21 15:04:01,793 DEBUG [c.c.a.m.ClusteredAgentAttache] (Work-Job-Executor-114:ctx-92ff343d job-537958/job-538524 ctx-23550d3b) (logid:ff628fbe) Seq 184-8823114619972222986: Forwarding Seq 184-8823114619972222986: { Cmd , MgmtId: 345051779916, via: 184(zzz1.zzz.ccc), Ver: v1, Flags: 100011, [{"com.cloud.agent.api.StopCommand":{"isProxy":"false","checkBeforeCleanup":"false","forceStop":"true","volumesToDisconnect":[],"vmName":"i-hhh-kkkkk-VM","executeInSequence":"false","wait":"0","bypassHostMaintenance":"false"}}] } to 345051789152

2021-09-21 15:04:01,593 WARN [o.a.c.n.t.BasicNetworkTopology] (Work-Job-Executor-114:ctx-92ff343d job-537958/job-538524 ctx-23550d3b) (logid:ff628fbe) Unable to apply save userdata entry on disconnected router r-nnnn-VM

But router is ok/live.

I can privately send all log if you are interested.

**Comment by weizhouapache** [comment]
> @ravening @sureshanaparti @nvazquez Encountered this two days ago. Doing regular maintenance on KVM hosts Ubuntu 18.04/16.04 ACS 4.15.1. Put KVM host in maintenance and some VM are migrate with shutdown. Happened in advanced and basic networking around 10~ VM where affected.
> 
> 2021-09-21 15:04:01,620 DEBUG [c.c.c.CapacityManagerImpl] (Work-Job-Executor-114:ctx-92ff343d job-537958/job-538524 ctx-23550d3b) (logid:ff628fbe) VM state transitted from :Running to Stopping with event: StopRequestedvm's original host id: 183 new host id: 184 host id before state transition: 184
> 2021-09-21 15:04:01,793 DEBUG [c.c.a.m.ClusteredAgentAttache] (Work-Job-Executor-114:ctx-92ff343d job-537958/job-538524 ctx-23550d3b) (logid:ff628fbe) Seq 184-8823114619972222986: Forwarding Seq 184-8823114619972222986: { Cmd , MgmtId: 345051779916, via: 184(zzz1.zzz.ccc), Ver: v1, Flags: 100011, [{"com.cloud.agent.api.StopCommand":{"isProxy":"false","checkBeforeCleanup":"false","forceStop":"true","volumesToDisconnect":[],"vmName":"i-hhh-kkkkk-VM","executeInSequence":"false","wait":"0","bypassHostMaintenance":"false"}}] } to 345051789152
> 
> 2021-09-21 15:04:01,593 WARN [o.a.c.n.t.BasicNetworkTopology] (Work-Job-Executor-114:ctx-92ff343d job-537958/job-538524 ctx-23550d3b) (logid:ff628fbe) Unable to apply save userdata entry on disconnected router r-nnnn-VM
> 
> But router is ok/live.
> 
> I can privately send all log if you are interested.

@kricud 
I am not sure if it has been fixed in 4.15.2.0 (there are many bug fixes in 4.15.2.0). it would be better to upgrade to 4.15.2.0.

**Comment by kricud** [comment]
@weizhouapache We are in process of moving to 4.15.2 and 99% that it’s not fixed in it.
From discussion above I understand that it can’t be repeated. With my comment intention was to confirm that it is a problem. When you put host in maintenance you get ErrorInPrepareForMainatance~ and VM's are going down.

**Comment by kricud** [comment]
@weizhouapache 4.15.2 has same problems.

**Comment by weizhouapache** [comment]
> @weizhouapache 4.15.2 has same problems.

@kricud 
do you have idea how to reproduce the issue ?

**Comment by kricud** [comment]
@weizhouapache Both occasions we encountered it again there was no pattern.
Now we are doing it by hand for instances and after pressing maintenance hoping that routers will not shutdown.

**Comment by nvazquez** [comment]
Hi @kricud any update on this issue and how to reproduce it? Thanks

**Comment by kricud** [comment]
@nvazquez no

**Comment by nvazquez** [comment]
@DaanHoogland @weizhouapache @rohityadavcloud this fix is simply adding an extra check before disconnecting a host while waiting to enable maintenance mode to prevent VM's to stop - however it is not clear on how to reproduce the issue, could occur sometimes, what do you advise?

**Comment by nvazquez** [comment]
@blueorangutan package

**Pull request merged**
