### PR TITLE
fix yum install require java => 1.7.0 when build management agent and us...

### PR DESCRIPTION
**Pull request by ghxandsky**
...age rpm package

### CODE REVIEW

**Comment by K0zka** [comment]
looks ok

**Comment by karuturi** [comment]
looks good. merging

**Comment by karuturi** [comment]
just an unrelated note. It would help for easy reading if the commit message text width is set to 72. especially headline.
http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

**Comment by bhaisaab** [comment]
+1 the merged patch on master does not include the closes #issues string before the signature, can you close it @ghxandsky ?

**Comment by karuturi** [comment]
Hi @ghxandsky 
After this change, if I install the rpm, its installing java 1.6. I am trying on centos6.3 machine.  if I give the version as java-1.7.0-openjdk it succeeds. Any idea why?

**Comment by ghxandsky** [comment]
@karuturi I'm sorry for this commit, it should be "Requires: java-1.7.0-openjdk" . I make a mistake. :(

**Comment by ghxandsky** [comment]
@karuturi Can you craete a new commit and fix it ?

**Comment by bhaisaab** [comment]
@ghxandsky can you send a new PR, both both master and 4.5 (separately)? Thanks.

**Comment by karuturi** [comment]
@ghxandsky 
I fixed it on master yesterday. Please verify.

@bhaisaab
This is not pushed to 4.5

-----Original Message-----

**Comment by karuturi** [comment]
@ghxandsky, do you know why java => 1.7.0 is working with centos7 and not with centos63? The surprising thing was, on 6.3 without failing due to missing dependency, it installs java 1.6 even on a system which doesnt have java.

**Pull request closed without merging**
