### PR TITLE
BUG-ID:CLOUDSTACK-9678

### PR DESCRIPTION
**Pull request by pdumbre**
listNetworkOfferings API is listing all the offerings which has same prefix in their name

### CODE REVIEW

**Comment by serg38** [comment]
Why this is a bug? Most of ACS searches using name field work exactly this way to bring list of VMs, templates etc when partial name is specified. If exact name match is expected it needs to be processed on a client side.

**Comment by pdumbre** [comment]
For listing of other offerings  Disk, Compute and VPC, we have to provide exact name and not partial one.So this fix is done for consistent behaviour of all list APIs

**Comment by serg38** [comment]
@pdumbre I confirm your observation. LGTM on code review.

**Comment by pdumbre** [comment]
Test Results Passed:
https://travis-ci.org/apache/cloudstack/builds/201069131

**Comment by cloudmonger** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 344
 Hypervisor xenserver
 NetworkType Advanced
 Passed=103
 Failed=1
 Skipped=7

_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/yj3wnzbceo9uef2/AAB6u-Iap-xztdm6jHX9SjPja?dl=0


**Failed tests:**
* test_routers_network_ops.py

 * test_03_RVR_Network_check_router_state Failed


**Skipped tests:**
test_01_test_vm_volume_snapshot
test_vm_nic_adapter_vmxnet3
test_static_role_account_acls
test_11_ss_nfs_version_on_ssvm
test_nested_virtualization_vmware
test_3d_gpu_support
test_deploy_vgpu_enabled_vm

**Passed test suits:**
test_deploy_vm_with_userdata.py
test_affinity_groups_projects.py
test_portable_publicip.py
test_over_provisioning.py
test_global_settings.py
test_scale_vm.py
test_service_offerings.py
test_routers_iptables_default_policy.py
test_loadbalance.py
test_routers.py
test_reset_vm_on_reboot.py
test_deploy_vms_with_varied_deploymentplanners.py
test_network.py
test_router_dns.py
test_non_contigiousvlan.py
test_login.py
test_deploy_vm_iso.py
test_list_ids_parameter.py
test_public_ip_range.py
test_multipleips_per_nic.py
test_regions.py
test_affinity_groups.py
test_network_acl.py
test_pvlan.py
test_volumes.py
test_nic.py
test_deploy_vm_root_resize.py
test_resource_detail.py
test_secondary_storage.py
test_vm_life_cycle.py
test_disk_offerings.py

**Pull request merged**
