### PR TITLE
Fix schema-421to430.sql issue after MariaDB upgrade

### PR DESCRIPTION
**Pull request by ustcweizhou**
@remibergsma @wido Can you test it?

### CODE REVIEW

**Comment by ustcweizhou** [comment]
description of the issue:
http://markmail.org/message/7isvqsur2preppvl
http://markmail.org/message/t47bdpkhg6j4hhlb

**Comment by remibergsma** [comment]
Assuming the tests will pass: LGTM
What I tested:
- the new query has the same result as the old ones
- the build now works again on CentOS 7 using MariaDB 5.5.44 (that failed since I upgraded from 5.5.41)
In general, the query is much better anyway I'd say. Thanks @ustcweizhou !

**Comment by bhaisaab** [comment]
I guess we simply need to test this for mysql 5.1.x, 5.5.x, 5.6.x; once it runs we can merge this.

**Comment by remibergsma** [comment]
Tested CentOS 6 which has MySQL 5.1 and it works fine. The other versions I don't have at hand now.

**Comment by DaanHoogland** [comment]
LGTM

**Comment by ustcweizhou** [comment]
Tested on Ubuntu 12.04 with mysql 5.5.41-0ubuntu0.12.04.1-log, it works .

**Pull request merged**
