### PR TITLE
ui: assignVM: Set isrecursive to false when fetching accounts

### PR DESCRIPTION
**Pull request by davidjumani**
### Description

Fixes the issue of displaying users in subdomains as well
Broken in the old UI as well

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan ui

**Review by utchoang — APPROVED** [review]
LGTM!

**Comment by rhtyd** [comment]
@davidjumani what is the issue - how do we reproduce and test the fix?

**Comment by davidjumani** [comment]
@rhtyd The issue is that calling list accounts with listall=true returns accounts in sub domains as well, even when isrecursive is set to false, related https://github.com/apache/cloudstack/issues/4868
This PR replaces listall with isrecursive=false so that accounts belonging to the specific domain are returned

As admin -> assign VM -> Root domain. Users from the subdomains are also listed. Selecting a user from the sub domain leads to an error
Screenshot from 2021-03-30 10-04-56

**Comment by davidjumani** [comment]
@blueorangutan ui

**Review by rhtyd — APPROVED** [review]

**Pull request merged**
