### PR TITLE
agent: import letsencrypt X3 cross signed certificate to ssvm agent keystore

### LINKED ISSUE #2541: Add "Lets Encrypt CA" Certpath to SSVM Keystore (for cdimage.debian.org)
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
SSVM
~~~

##### CLOUDSTACK VERSION

~~~
4.11
~~~

##### SUMMARY

The Download of ISO Images from https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-9.4.0-amd64-netinst.iso fails.

    sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

The site "cdimage.debian.org" uses Certificates from "Lets Encrypt".

Could it be the certification path for "Lets Encrypt" is not included in the Java Keystore on the SSVM? If so, could "Lets Encrypt" be added to the Keystore?

##### STEPS TO REPRODUCE

~~~
Log in to Web-UI
Register ISO
Enter Download URL "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-9.4.0-amd64-netinst.iso"

~~~

##### EXPECTED RESULTS

~~~
The Debian ISO image should be installed correctly.
~~~

##### ACTUAL RESULTS

~~~
Download fails with:

    sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
~~~

### PR DESCRIPTION
**Pull request by rhtyd**
This imports letsencypt X3 cross signed certificate to the default
keystore file for ssvm agent.

This fixes #2541.

Example listing:
````
$ keytool -list -keystore realhostip.keystore
Keystore type: JKS
Keystore provider: SUN

Your keystore contains 5 entries

root, Feb 3, 2012, trustedCertEntry,
Certificate fingerprint (SHA1): 27:96:BA:E6:3F:18:01:E2:77:26:1B:A0:D7:77:70:02:8F:20:EE:E4
realhostip, Feb 3, 2012, PrivateKeyEntry,
Certificate fingerprint (SHA1): DD:DB:44:55:E8:CF:33:4D:CB:54:B1:5A:95:A3:60:38:C3:1B:EF:7D
letsencryptauthorityx3cross, Apr 7, 2018, trustedCertEntry,
Certificate fingerprint (SHA1): E6:A3:B4:5B:06:2D:50:9B:33:82:28:2D:19:6E:FE:97:D5:95:6C:CB
cross, Feb 3, 2012, trustedCertEntry,
Certificate fingerprint (SHA1): DE:70:F4:E2:11:6F:7F:DC:E7:5F:9D:13:01:2B:7E:68:7A:3B:2C:62
intermed, Feb 3, 2012, trustedCertEntry,
Certificate fingerprint (SHA1): 7C:46:56:C3:06:1F:7F:4C:0D:67:B3:19:A8:55:F6:0E:BC:11:FC:44
````

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## Checklist:

- [ ] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
Testing
- [ ] I have added tests to cover my changes.
- [ ] All relevant new and existing integration tests have passed.
- [ ] A full integration testsuite with all test that can run on my environment has passed.

@blueorangutan package

### CODE REVIEW

**Comment by rafaelweingartner** [comment]
@rhtyd thanks for updating the CA certificates into CloudStack's one. Out of curiosity, do you have an idea if it would be too complicated to change the name of this CA keystore? Something like cloudstack.keystore looks better, than realhost.keystore.

**Comment by rhtyd** [comment]
Yes, you're right @rafaelweingartner it's not difficult to rename the keystore at all. In fact, I'm even considering, to get rid of this keystore file or symlink to the default system one (at /etc/ssl/certs/java/cacert, with password: `changeit`). The issue I found was that even when I updated the system `cacert` the agent failed to load that, since the old keystore file is used by default. Doing so may require some testing around using custom SSL certs for both SSVM and CPVM. Keeping a separate ca-cert file for cloudstack will cause a pain, when another provider's cert/chain are missing.

**Comment by rafaelweingartner** [comment]
I think it is ok to customize the default cacerts with users certificates. However, I am not sure if we already have an execution flow that could achieve this. The good point on using the default cacerts is that on every update of the OS (of the system VM template) we get the updates in cacerts "automatically".

**Comment by rhtyd** [comment]
Let me re-visit the approach this or next week, we have an interim solution that works if anyone wants to use.

**Comment by rhtyd** [comment]
I've moved fix to https://github.com/apache/cloudstack/pull/2616

**Pull request closed without merging**
