### PR TITLE
Update VM name, when the new name provided in updateVirtualMachine API is in different case.

### PR DESCRIPTION
**Pull request by sureshanaparti**
### Description

This PR update VM name, when the new name provided in updateVirtualMachine API is in different case.

```
(test-env) 🐱 > list virtualmachines id=0dd16832-5f07-402d-9238-10c69b6daeb5 filter=id,name,displayname,instancename
{
  "count": 1,
  "virtualmachine": [
    {
      "displayname": "TestVM02",
      "id": "0dd16832-5f07-402d-9238-10c69b6daeb5",
      "instancename": "i-2-7-VM",
      "name": "testvm02"
    }
  ]
}
(test-env) 🐱 > update virtualmachine id=0dd16832-5f07-402d-9238-10c69b6daeb5 name=TestVM02
{
  "virtualmachine": {
    "account": "admin",
    "affinitygroup": [],
    "cpunumber": 1,
    "cpuspeed": 500,
    "cpuused": "14.3%",
    "created": "2022-05-11T07:18:25+0000",
    "details": {
      "cpuOvercommitRatio": "2.0",
      "memoryOvercommitRatio": "1.0"
    },
    "diskioread": 0,
    "diskiowrite": 4,
    "diskkbsread": 0,
    "diskkbswrite": 24,
    "displayname": "TestVM02",
    "displayvm": true,
    "domain": "ROOT",
    "domainid": "64482588-cf5d-11ec-b370-1e00ba000212",
    "guestosid": "6473e9a7-cf5d-11ec-b370-1e00ba000212",
    "haenable": false,
    "hasannotations": false,
    "hostid": "56039acc-b250-4a0f-9b67-94ebaeb2c50e",
    "hostname": "trl-288-k-M7-suresh-anaparti-kvm1",
    "hypervisor": "KVM",
    "id": "0dd16832-5f07-402d-9238-10c69b6daeb5",
    "instancename": "i-2-7-VM",
    "isdynamicallyscalable": false,
    "lastupdated": "2022-05-11T07:18:29+0000",
    "memory": 512,
    "memoryintfreekbs": -1,
    "memorykbs": 524288,
    "memorytargetkbs": 524288,
    "name": "testvm02",
...
    "serviceofferingid": "529b7537-85ef-4bfd-a992-817a7186a7b2",
    "serviceofferingname": "Small Instance",
    "state": "Running",
    "tags": [],
    "templatedisplaytext": "CentOS 5.5(64-bit) no GUI (KVM)",
    "templateid": "644b8abf-cf5d-11ec-b370-1e00ba000212",
    "templatename": "CentOS 5.5(64-bit) no GUI (KVM)",
    "userid": "7dbb3d96-cf5d-11ec-b370-1e00ba000212",
    "username": "admin",
    "zoneid": "67ecf93f-6958-4b19-bad4-4742c67dc093",
    "zonename": "trl-288-k-M7-suresh-anaparti"
  }
}


(test-env) 🐱 > list virtualmachines id=0dd16832-5f07-402d-9238-10c69b6daeb5 filter=id,name,displayname,instancename
{
  "count": 1,
  "virtualmachine": [
    {
      "displayname": "TestVM02",
      "id": "0dd16832-5f07-402d-9238-10c69b6daeb5",
      "instancename": "i-2-7-VM",
      "name": "testvm02"
    }
  ]
}
```

Log:

_2022-05-11 07:23:43,858 DEBUG [c.c.v.UserVmManagerImpl] (qtp793138072-20:ctx-939ba5d9 ctx-8de3ee5e) (logid:33e17e0c) Vm VM instance {id: "7", name: "i-2-7-VM", uuid: "0dd16832-5f07-402d-9238-10c69b6daeb5", type="User"} is already set with the hostName specified: TestVM02_

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

### How Has This Been Tested?

Manually tested update virtualmachine API.

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Review by nvazquez — APPROVED** [review]
Code LGTM - not aware if there is any restriction on the hypervisor side @rohityadavcloud @DaanHoogland @andrijapanicsb @weizhouapache @Pearl1594 ?

**Comment by nvazquez** [comment]
Ping for review @rohityadavcloud @DaanHoogland @andrijapanicsb @weizhouapache @Pearl1594

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Pull request merged**
