### PR TITLE
UI: enable project menu on mobile devices

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR shows project menu on mobile devices

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@weizhouapache have you tested this/ is it draft? I wonder why this was put in place. Is the reason for that gone?

**Comment by weizhouapache** [comment]
> @weizhouapache have you tested this/ is it draft? I wonder why this was put in place. Is the reason for that gone?

@DaanHoogland 
to be frank, I have no idea.
it was introduced in a very early commit 63e6173a2685166fa9b33dedfa82c401336cb15a by @rohityadavcloud 


I used Chrome for testing

- an env without this PR

image


- an env with this change 

image

**Comment by weizhouapache** [comment]
@blueorangutan ui

**Comment by DaanHoogland** [comment]
ok, will test on ff

**Comment by DaanHoogland** [comment]
> ok, will test on ff

Screenshot_20240918-104930

works :+1:

**Review by DaanHoogland — APPROVED** [review]

**Review by FelipeM525 — APPROVED** [review]
LGTM! Tested in the simulator build!

**Review by rohityadavcloud — APPROVED** [review]

**Pull request merged**
