### PR TITLE
Cleanup domain details when domain is deleted

### PR DESCRIPTION
**Pull request by ravening**
## Description

Cleanup domain details when domain is deleted

    When domain is deleted, all the settings configured under
    the domain scope still exists in domain_details table.
    All the entries for the domain should be deleted as well

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

Before the fix
```
mysql> select name,state from domain where id=254;
+--------+--------+
| name   | state  |
+--------+--------+
| domain | Active |
+--------+--------+
1 row in set (0.00 sec)

mysql> select * from domain_details where domain_id=254;
+----+-----------+---------------------------------+--------------------------+
| id | domain_id | name                            | value                    |
+----+-----------+---------------------------------+--------------------------+
| 11 |       254 | allow.duplicate.networkname     | WRXXfK4XO7HPzDmQ0MGAGw== |
| 12 |       254 | allow.empty.start.end.ipaddress | Ia4BIOohYf4W5C5FwOJe+A== |
| 13 |       254 | allow.user.expunge.recover.vm   | nRTlX/+K9wqesxm9x1zwmQ== |
+----+-----------+---------------------------------+--------------------------+
3 rows in set (0.00 sec)

mysql> select name,state from domain where id=254;
+--------+----------+
| name   | state    |
+--------+----------+
| domain | Inactive |
+--------+----------+
1 row in set (0.00 sec)

mysql> select * from domain_details where domain_id=254;
+----+-----------+---------------------------------+--------------------------+
| id | domain_id | name                            | value                    |
+----+-----------+---------------------------------+--------------------------+
| 11 |       254 | allow.duplicate.networkname     | WRXXfK4XO7HPzDmQ0MGAGw== |
| 12 |       254 | allow.empty.start.end.ipaddress | Ia4BIOohYf4W5C5FwOJe+A== |
| 13 |       254 | allow.user.expunge.recover.vm   | nRTlX/+K9wqesxm9x1zwmQ== |
+----+-----------+---------------------------------+--------------------------+
3 rows in set (0.00 sec)
```

After the fix

```
mysql> select name,state from domain where id=255;
+--------+--------+
| name   | state  |
+--------+--------+
| domain | Active |
+--------+--------+
1 row in set (0.00 sec)

mysql> select * from domain_details where domain_id=255;
+----+-----------+---------------------------------+--------------------------+
| id | domain_id | name                            | value                    |
+----+-----------+---------------------------------+--------------------------+
| 14 |       255 | allow.duplicate.networkname     | dXYs8M+ZfwHYzPwSPgjk7g== |
| 15 |       255 | allow.empty.start.end.ipaddress | kjjnH9Y+qmGfwdF11eSobg== |
| 16 |       255 | allow.user.expunge.recover.vm   | 6oE1TAZHn+o64seAhLHDng== |
+----+-----------+---------------------------------+--------------------------+
3 rows in set (0.00 sec)

mysql> select name,state from domain where id=255;
+--------+----------+
| name   | state    |
+--------+----------+
| domain | Inactive |
+--------+----------+
1 row in set (0.00 sec)

mysql> select * from domain_details where domain_id=255;
Empty set (0.00 sec)

mysql>
```

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@ravening , this sounds like something that should be done in a cascading delete in sql. I see only java changes, any thoughts?

**Comment by ravening** [comment]
> @ravening , this sounds like something that should be done in a cascading delete in sql. I see only java changes, any thoughts?

Anything is fine with me as long as entries are cleaned up

**Comment by DaanHoogland** [comment]
I think doing this in java is error prone. if the domain is marked removed it doesn't hurt to keep the details around and if the domain records is actually removed it should be removed with a cascading delete. the only possible reason to do it this way is if we have other 'child' records to domain that we do want to keep when domains are deleted.
if you look at DomainDaoImpl.remove(..), you'll find that any checks needed are done there. I think this cleanup should happen there as well.

**Comment by weizhouapache** [comment]
@DaanHoogland I do not see any harmless to remove the records from db. however if you want to keep it in db, it is ok for me. @ravening

**Review by weizhouapache — APPROVED** [review]

**Comment by shwstppr** [comment]
@ravening Moving to 4.16.0.0 milestone based on base branch please update if needed

**Comment by DaanHoogland** [comment]
@ravening @shwstppr as this is a bug fix and based on a version before branching of I've set the version to 4.15.1

**Comment by weizhouapache** [comment]
> @ravening @shwstppr as this is a bug fix and based on a version before branching of I've set the version to 4.15.1

@ravening @shwstppr @DaanHoogland maybe better to merge this into 4.14 ?

**Review by shwstppr — APPROVED** [review]
LGTM

@weizhouapache 👍

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
> > @ravening @shwstppr as this is a bug fix and based on a version before branching of I've set the version to 4.15.1
> 
> @ravening @shwstppr @DaanHoogland maybe better to merge this into 4.14 ?

@weizhouapache it will need rebasing for that. cc @ravening

**Comment by rhtyd** [comment]
LGTM, business layer only changes; merging based on Travis tests. LGTM.

**Pull request merged**
