### PR TITLE
maven quality tool plugins

### PR DESCRIPTION
**Pull request by DaanHoogland**
## Description

owasp dependency checker and other tools during the site build phase to be able to add them to apache jenkins. inluding updates and cleanups.

Some version discrepencies arose so version upgrades are included and `mvn dependency:tree | grep <this or that> | sort -u` gave some that need handling:

```
com.fasterxml.jackson.core:jackson-core:jar:2.1.3:compile
com.fasterxml.jackson.core:jackson-core:jar:2.9.10:compile

com.google.code.findbugs:jsr305:jar:1.3.9:compile
com.google.code.findbugs:jsr305:jar:3.0.2:compile

com.google.http-client:google-http-client:jar:1.17.0-rc:compile
com.google.http-client:google-http-client:jar:1.20.0:compile

com.unboundid:unboundid-ldapsdk:jar:3.2.0:compile
com.unboundid:unboundid-ldapsdk:jar:4.0.14:test

commons-collections:commons-collections:jar:3.2.1:compile
commons-collections:commons-collections:jar:3.2.2:compile

commons-logging:commons-logging:jar:1.1.1:compile
commons-logging:commons-logging:jar:1.2:compile

javax.annotation:javax.annotation-api:jar:1.3.2:compile
# javax.annotation:javax.annotation-api:jar:1.3:compile

joda-time:joda-time:jar:2.10.5:compile
# joda-time:joda-time:jar:2.2:compile
# joda-time:joda-time:jar:2.8.1:compile
# joda-time:joda-time:jar:2.9.3:compile

org.slf4j:slf4j-api:jar:1.7.29:compile
org.slf4j:slf4j-log4j12:jar:1.7.29:compile

xerces:xercesImpl:jar:2.12.0:test
# xerces:xercesImpl:jar:2.8.0:compile
xml-apis:xml-apis-ext:jar:1.3.04:compile

# xml-apis:xml-apis:jar:1.0.b2:compile,test
# xml-apis:xml-apis:jar:1.4.01:test
xml-apis:xml-apis:jar:2.0.2:test,compile ???
```

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@rhtyd @weizhouapache @GabrielBrascher finally apache builds gave a positive again on this maven update. can you approve?
cc @svenvogel @PaulAngus @anybody

**Comment by DaanHoogland** [comment]
ping @weizhouapache @kiwiflyer @GabrielBrascher @rhtyd @nathanejohnson @andrijapanic-dont-use-this-one @svenvogel @wido this is ready for review.

**Comment by nvazquez** [comment]
@DaanHoogland  I'm hitting this error when building:

````
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:28 min (Wall Clock)
[INFO] Finished at: 2020-03-13T13:47:08-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project cloud-vmware-base: Could not resolve dependencies for project org.apache.cloudstack:cloud-vmware-base:jar:4.14.0.0-SNAPSHOT: Failure to find com.sun.xml.ws:jaxws-ri:pom:2.6 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :cloud-vmware-base
````

**Comment by nvazquez** [comment]
@DaanHoogland I got this error when building (with update dependecies flag)

````
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15:24 min
[INFO] Finished at: 2020-03-13T14:11:21-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project cloud-plugin-network-f5: Could not resolve dependencies for project org.apache.cloudstack:cloud-plugin-network-f5:jar:4.14.0.0-SNAPSHOT: Could not find artifact commons-discovery:commons-discovery:jar:1.0-dev in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :cloud-plugin-network-f5
````

**Comment by DaanHoogland** [comment]
@nvazquez I had been using -Dnonoss which has not been in use for ever and a day. You are right the dependency on f5 doesn't work.
testing further with `mvn clean install -Dnoredist -P developer,systemvm`, but it needs to work with `mvn site -Dnoredist` as well, will push if i get both to work.

**Comment by nvazquez** [comment]
@DaanHoogland I checked that the version 1.0-dev for the dependency commons-discovery is not present in the artifactory, so I changed the version to 0.5 (he last available in the repo: https://mvnrepository.com/artifact/commons-discovery/commons-discovery/0.5).

After changing that, I'm hitting a different error:

````
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16:42 min
[INFO] Finished at: 2020-03-14T20:48:46-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project cloud-plugin-outofbandmanagement-driver-nested-cloudstack: Could not resolve dependencies for project org.apache.cloudstack:cloud-plugin-outofbandmanagement-driver-nested-cloudstack:jar:4.14.0.0-SNAPSHOT: Failed to collect dependencies at org.apache.cloudstack:cloud-server:jar:clover:4.14.0.0-SNAPSHOT -> org.apache.cloudstack:cloud-framework-jobs:jar:4.14.0.0-SNAPSHOT -> org.apache.cloudstack:cloud-framework-events:jar:4.14.0.0-SNAPSHOT -> com.google.guava:guava:jar:28.2-jre -> org.checkerframework:checker-qual:jar:2.10.0: class java.util.HashMap$Node cannot be cast to class java.util.HashMap$TreeNode (java.util.HashMap$Node and java.util.HashMap$TreeNode are in module java.base of loader 'bootstrap') -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :cloud-plugin-outofbandmanagement-driver-nested-cloudstack

````

BTW: I'm compiling with:
````
mvn clean install -Dnoredist -P developer,systemvm -DskipTests -U
````

**Comment by DaanHoogland** [comment]
very frustrating, I'm hitting a different one:
```
[ERROR] Failed to execute goal on project cloud-vmware-base: Could not resolve dependencies for project org.apache.cloudstack:cloud-vmware-base:jar:4.14.0.0-SNAPSHOT: Failure to find com.sun.xml.ws:jaxws-ri:pom:2.6 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
```

**Comment by nvazquez** [comment]
@DaanHoogland can you try adding `-U` to force updating the dependencies?

**Comment by DaanHoogland** [comment]
`mvn clean install -Dnoredist -P developer,systemvm -U` tried, it doesn't complete with above error. Unfortunately having a compiled system is more important than having good analysis output so no go for this, for now.

**Comment by DaanHoogland** [comment]
@svenvogel why would you put a label security on this PR?

**Comment by DaanHoogland** [comment]
ok, builds now on

-  fedora 31 and
-  @nvazquez' ubuntu (what's the version) and
-  macos 10.15.3 (19D76) provided the sed hack is added (see #3312 )
-  jenkins job

@rhtyd @weizhouapache @GabrielBrascher can you approve?

**Comment by rhtyd** [comment]
@blueorangutan package

**Pull request merged**
