### PR TITLE
[4.5.3]Cherry-pick PR #795 into 4.5 branch.

### PR DESCRIPTION
**Pull request by borisroman**

### CODE REVIEW

**Comment by bhaisaab** [comment]
4.5 was missing upgrade path, implemented that; please push again to force a travis build

**Comment by borisroman** [comment]
@bhaisaab Done.

**Comment by bhaisaab** [comment]
@borisroman not sure about the apache repo error, I'm having build failures when building locally due to getPreferredCharset method not avialable in StringUtils class (utils package). Please test locally and update the PR thanks.

**Comment by bhaisaab** [comment]
Also there seems to be a license header issue (missing new line between header and package definition in the utils class).

**Comment by borisroman** [comment]
@bhaisaab Updated the PR. Tests run fine now. Thanks for your time!

**Comment by bhaisaab** [comment]
LGTM, merging this this is already merged on master and builds are passing on 4.5 branch now

**Pull request merged**
