### PR TITLE
CLOUDSTACK-9782: New Background Polling Task Manager

### PR DESCRIPTION
**Pull request by rhtyd**
CloudStack has several background polling tasks that are spread across
the codebase, the aim of this work is to provide a single manager to
handle submission, execution and handling of background tasks. With
the framework implemented, existing oobm background task has been
refactored to use this manager.

The work has been split from a bigger host-ha pr: https://github.com/apache/cloudstack/pull/1960

@blueorangutan package

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@borisstoyanov @DaanHoogland and others - please review.

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
Test LGTM, some of the failing tests are intemittent and ignore-able. Two test are failing on both 4.9 and master branches and can be dealt with separately, not related to this PR:

test_01_nic | Error | 193.93 | test_nic.py
test_reboot_router | Error | 238.47 | test_network.py

**Comment by rhtyd** [comment]
Thanks @borisstoyanov @DaanHoogland -- yes for now, I'm not moved other runnable threads to be handled by this manager, which will be a next step.

**Pull request merged**
