### PR TITLE
UI: Add s3 provider option to create secondary storage

### PR DESCRIPTION
**Pull request by utchoang**
### Description

This PR fixes https://github.com/apache/cloudstack/issues/5718

Add s3 provider option to create secondary storage and adjust the form add secondary storage in creating zone

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### Screenshots (if appropriate):
image

### CODE REVIEW

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by rhtyd** [comment]
Hi @utchoang have you tested this against s3/swift?

**Comment by utchoang** [comment]
@rhtyd Yes, I have checked and added the storagepolicy attribute for a swift provider which was missing in create the zone.

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by rohityadavcloud** [comment]
@blueorangutan ui

**Review by sureshanaparti — APPROVED** [review]
Verified the S3 provider option, and API call from UI.

**Review by shwstppr — APPROVED** [review]

**Pull request merged**
