### PR TITLE
Allow users to update volume name

### PR DESCRIPTION
**Pull request by ravening**
Provide an api support to update volume name by all users
UI changes ported from https://github.com/apache/cloudstack-primate/pull/920
### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [X] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@ravening I recall this being discussed before. is it a reopening with old code?

**Comment by DaanHoogland** [comment]
yes, to answer my own question: #4584

**Review by weizhouapache — APPROVED** [review]

**Review by DaanHoogland — APPROVED** [review]

**Review by RodrigoDLopez — APPROVED** [review]

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
ping @ravening can you fix the conflicts

**Comment by sureshanaparti** [comment]
Hi @ravening, Can you resolve the code conflicts.

**Comment by nvazquez** [comment]
Hi @ravening can you please resolve the conflicts?

**Comment by ravening** [comment]
> Hi @ravening can you please resolve the conflicts?

@rhtyd @sureshanaparti @nvazquez will work on it today.
I didnt get any notification from github on tagging my username and so was unaware of this

**Comment by rhtyd** [comment]
@ravening ping - can you fix the conflict? You can enable email settings in your github https://github.com/settings/notifications

**Comment by ravening** [comment]
> @ravening ping - can you fix the conflict? You can enable email settings in your github https://github.com/settings/notifications

@rhtyd yes thats all enabled.. no idea why its not sending notifications!

**Comment by nvazquez** [comment]
@blueorangutan package

**Review by nvazquez — APPROVED** [review]
Code LGTM

**Comment by nvazquez** [comment]
@blueorangutan test

**Pull request merged**
