### PR TITLE
Changed UsageEventUtils to UsageEventEmitter and made it injectable

### PR DESCRIPTION
**Pull request by ProjectMoon**
An updated version of #1191, against the master branch. This also updates the HypervisorTemplateAdapter test slightly, making it less unwieldy.

### CODE REVIEW

**Comment by ProjectMoon** [comment]
Looks like there is some autowiring problem, probably a missing XML definition for the emitter. Will address tomorrow. The simulator has issues with a missing event bus, though Travis reports missing UsageEventEmitterImpl... the Impl is in the core-managers-context. Will change the code for the event bus, but not sure what to do about the Travis CI error yet.

**Comment by ProjectMoon** [comment]
Travis is failing due to some connection error, it seems. Any ideas?

```
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
nc: connect to localhost port 8096 (tcp) failed: Connection refused
nc: connect to localhost port 8096 (tcp) failed: Connection refused
nc: connect to localhost port 8096 (tcp) failed: Network is unreachable
````

**Comment by ProjectMoon** [comment]
Latest CI run does not happen to me locally. I can compile and start the simulator fine. Anyone have any insights?

**Comment by ProjectMoon** [comment]
Rebased to latest master, though I suspect the same error will still occur in the CI run.

**Comment by rhtyd** [comment]
@blueorangutan package
@ProjectMoon can you push -f to rekick Travis?

**Comment by rhtyd** [comment]
@ProjectMoon can you fix the conflicts thanks.

**Comment by ProjectMoon** [comment]
We are in the process of fixing the conflicts. The rebase worked fine, but we have to rewrite one of the new unit tests to not use the `UsageEventEmitter`.

**Pull request closed without merging**
