### PR TITLE
server: password is not displayed when reinstall a vm or reset ssh key

### PR DESCRIPTION
**Pull request by ustcweizhou**
## Description

After reinstall a stopped vm or reset ssh key, the password is reset, and new password is saved in virtual router (if it is running). However we do not get any password in the api response as well as cloudstack UI.

This fixes the issue above.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by ustcweizhou** [comment]
@rhtyd this seems to be caused by acc5fdc
could you please review it ?

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by Spaceman1984** [comment]
Tested LGTM.

**Comment by Spaceman1984** [comment]
@blueorangutan test

**Pull request merged**
