### PR TITLE
Fix simulator docker db deploy issue (apache#3397)

### PR DESCRIPTION
**Pull request by khnazaretyan**
## Description

As the latest docker image in dockerhub is built from master branch, I thought it would be correct to open PR into a master branch (and not to release, if inacceptable, please suggest the correct one).

Fixes: #3397

The latest cloudstack/simulator image is not working causing issue #3397. 
The build was incomplete as mysql 5.7 is failing to start during docker build, thus DB is not deployed.
The command `find /var/lib/mysql -type f -exec touch {} \;` is a workaround for the issue which causes mysqld 5.7 to crash after start.
Putting VOLUME instruction before starting mysql also solves this problem but does not allow any other changes to the folder during build.

There are other also options that might be discussed:
1. Setting `VOLUME /var/lib/mysql` instruction in Dockerfile and importing the db during each container run (the start of the container will take longer).
2. Try to download and install mysql v5.5 from archives during docker build (not included in ubuntu repository, limited to 5.5)

Other ideas/input will be much appreciated.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

Successfully built/run docker image/container according to the documentation.
```
docker build -f Dockerfile -t cloudstack/simulator ../..
docker run --name simulator -p 8080:8080 -d cloudstack/simulator
```

### CODE REVIEW

**Comment by 85matthew** [comment]
I ran into this issue with the docker container today & this does fix it. Are you able to get this merged for others? @rhtyd 

Thanks for the PR @khnazaretyan 

Looking forward to checking the system out.

**Comment by weizhouapache** [comment]
@DaanHoogland @rhtyd could you test and get this merged into 4.13/4.14 ?

**Comment by DaanHoogland** [comment]
tested and checked if mysql was running:
```
baloujak:docker dahn$ docker exec -it 74738358a18c bash
root@74738358a18c:~# ps  -a
  PID TTY          TIME CMD
  686 pts/0    00:00:00 ps
root@74738358a18c:~# ps -eaf
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  1 09:52 ?        00:00:03 /usr/bin/python /usr/bin/supervisord
root         9     1 99 09:52 ?        00:04:58 /usr/lib/jvm/java-8-openjdk-amd64/bin/java -classpath /usr/share/maven/boot/plexus-classworlds-2.x.jar -Dclassworlds.conf=/usr/share/ma
root        10     1  0 09:52 ?        00:00:00 /bin/sh /usr/bin/mysqld_safe
mysql      404    10  0 09:52 ?        00:00:01 /usr/sbin/mysqld --basedir=/usr --datadir=/var/lib/mysql --plugin-dir=/usr/lib/mysql/plugin --user=mysql --log-error=/var/log/mysql/err
root       666     0  1 09:55 pts/0    00:00:00 bash
root       687   666  0 09:55 pts/0    00:00:00 ps -eaf
root@74738358a18c:~# mysql
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 6
Server version: 5.7.29-0ubuntu0.16.04.1 (Ubuntu)

Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> use cloud
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql>
```

@weizhouapache do you agree this is good enough?
@khnazaretyan can you reapply your change on branch 4.13 and force push it here?

**Comment by khnazaretyan** [comment]
@DaanHoogland Thanks for the review and test. I've reapplied the changes to 4.13 branch and pushed it here.

**Comment by DaanHoogland** [comment]
ping @rhtyd @weizhouapache

**Pull request merged**
