### PR TITLE
CLOUDSTACK-9646: No usage is generated for uploaded templates/volumes from local

### PR DESCRIPTION
**Pull request by karuturi**
published usage events on successful upload of template or volume.

### CODE REVIEW

**Comment by rhtyd** [comment]
@karuturi this looks useful, can you change the PR's base branch to 4.9, rebase your branch against 4.9?

**Comment by karuturi** [comment]
@rhtyd in progress

**Comment by rhtyd** [comment]
@karuturi please push -f on the PR to re-kick travis, or close/open the PR

**Comment by cloudmonger** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 156
 Hypervisor xenserver
 NetworkType Advanced
 Passed=102
 Failed=3
 Skipped=7

_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/yj3wnzbceo9uef2/AAB6u-Iap-xztdm6jHX9SjPja?dl=0


**Failed tests:**
* test_snapshots.py

 * test_01_snapshot_root_disk Failing since 3 runs

* test_deploy_vm_iso.py

 * test_deploy_vm_from_iso Failing since 27 runs

* test_vm_life_cycle.py

 * test_10_attachAndDetach_iso Failing since 28 runs


**Skipped tests:**
test_01_test_vm_volume_snapshot
test_vm_nic_adapter_vmxnet3
test_static_role_account_acls
test_11_ss_nfs_version_on_ssvm
test_nested_virtualization_vmware
test_3d_gpu_support
test_deploy_vgpu_enabled_vm

**Passed test suits:**
test_deploy_vm_with_userdata.py
test_affinity_groups_projects.py
test_portable_publicip.py
test_over_provisioning.py
test_global_settings.py
test_scale_vm.py
test_service_offerings.py
test_routers_iptables_default_policy.py
test_loadbalance.py
test_routers.py
test_reset_vm_on_reboot.py
test_deploy_vms_with_varied_deploymentplanners.py
test_network.py
test_router_dns.py
test_non_contigiousvlan.py
test_login.py
test_list_ids_parameter.py
test_public_ip_range.py
test_multipleips_per_nic.py
test_regions.py
test_affinity_groups.py
test_network_acl.py
test_pvlan.py
test_volumes.py
test_nic.py
test_deploy_vm_root_resize.py
test_resource_detail.py
test_secondary_storage.py
test_routers_network_ops.py
test_disk_offerings.py

**Comment by rhtyd** [comment]
Thanks @karuturi 
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by borisstoyanov** [comment]
LGTM based on test results and code review.

**Comment by rhtyd** [comment]
LGTM, merging this.

**Pull request merged**
