### PR TITLE
CLOUDSTACK-8502 Improvement/annotations kvm citrix

### PR DESCRIPTION
**Pull request by wilderrodrigues**
@mlsorensen, I implemented the Annotations as you suggested. Thanks for the hints. ;)

@bhaisaab, I'm now testing Xen 6.2 and KVM with the changes in this PR.

All unit tests (262 for both plugins) are green! Once the integration tests are done, I will send the report.

Cheers,
Wilder

### CODE REVIEW

**Comment by wilderrodrigues** [comment]
@bhaisaab @mlsorensen

If you are okay with the result, I will merge the PR this afternoon.

Environments:

Centos7 + KVM + Qemu
MySQL/MariaDB 5.5.41
Management Server running CentOS 7
Component/Smoke tests: https://github.com/apache/cloudstack (test/integration/component and smoke)
Storage type: NFS shared
Isolation method: VLAN
Agent: 4.6.0

XenServer 6.2
MySQL/MariaDB 5.5.41
Management Server running CentOS 7
Component/Smoke tests: https://github.com/apache/cloudstack (test/integration/component and smoke)
Storage type: NFS shared
Isolation method: VLAN


================== KVM tests ==================

Test advanced zone virtual router ... === TestName: test_advZoneVirtualRouter | Status : SUCCESS ===
ok
Test Deploy Virtual Machine ... === TestName: test_deploy_vm | Status : SUCCESS ===
ok
Test Multiple Deploy Virtual Machine ... === TestName: test_deploy_vm_multiple | Status : SUCCESS ===
ok
Test Stop Virtual Machine ... === TestName: test_01_stop_vm | Status : SUCCESS ===
ok
Test Start Virtual Machine ... === TestName: test_02_start_vm | Status : SUCCESS ===
ok
Test Reboot Virtual Machine ... === TestName: test_03_reboot_vm | Status : SUCCESS ===
ok
Test destroy Virtual Machine ... === TestName: test_06_destroy_vm | Status : SUCCESS ===
ok
Test recover Virtual Machine ... === TestName: test_07_restore_vm | Status : SUCCESS ===
ok
Test migrate VM ... SKIP: At least two hosts should be present in the zone for migration
Test destroy(expunge) Virtual Machine ... === TestName: test_09_expunge_vm | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 10 tests in 2698.252s

OK (SKIP=1)
/tmp//MarvinLogs/test_vm_life_cycle_DZNVX5/results.txt (END)


Test Create Account and user for that account ... === TestName: test_01_create_account | Status : SUCCESS ===
ok
Test Sub domain allowed to launch VM  when a Domain ... === TestName: test_01_add_vm_to_subdomain | Status : SUCCESS ===
ok
Test delete domain without force option ... === TestName: test_DeleteDomain | Status : SUCCESS ===
ok
Test delete domain with force option ... === TestName: test_forceDeleteDomain | Status : SUCCESS ===
ok
Test to verify Non Root admin previleges ... === TestName: test_01_non_root_admin_Privileges | Status : SUCCESS ===
ok
Test Remove one user from the account ... === TestName: test_01_user_remove_VM_running | Status : SUCCESS ===
ok
Test to verify service offerings at same level in hierarchy ... === TestName: test_01_service_offering_hierarchy | Status : SUCCESS ===
ok
Test to verify service offerings at same level in hierarchy ... === TestName: test_01_service_offering_siblings | Status : SUCCESS ===
ok
Test to verify template at same level in hierarchy ... === TestName: test_01_template_hierarchy | Status : SUCCESS ===
ok
Test update admin details ... === TestName: test_updateAdminDetails | Status : SUCCESS ===
ok
Test update domain admin details ... === TestName: test_updateDomainAdminDetails | Status : SUCCESS ===
ok
Test user update API ... === TestName: test_updateUserDetails | Status : SUCCESS ===
ok
Test login API with domain ... === TestName: test_LoginApiDomain | Status : SUCCESS ===
ok
Test if Login API does not return UUID's ... === TestName: test_LoginApiUuidResponse | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 14 tests in 6499.442s

OK
/tmp//MarvinLogs/test_accounts_8RTDXH/results.txt (END)


================== XenServer 6.2 tests ==================

Test advanced zone virtual router ... === TestName: test_advZoneVirtualRouter | Status : SUCCESS ===
ok
Test Deploy Virtual Machine ... === TestName: test_deploy_vm | Status : SUCCESS ===
ok
Test Multiple Deploy Virtual Machine ... === TestName: test_deploy_vm_multiple | Status : SUCCESS ===
ok
Test Stop Virtual Machine ... === TestName: test_01_stop_vm | Status : SUCCESS ===
ok
Test Start Virtual Machine ... === TestName: test_02_start_vm | Status : SUCCESS ===
ok
Test Reboot Virtual Machine ... === TestName: test_03_reboot_vm | Status : SUCCESS ===
ok
Test destroy Virtual Machine ... === TestName: test_06_destroy_vm | Status : SUCCESS ===
ok
Test recover Virtual Machine ... === TestName: test_07_restore_vm | Status : SUCCESS ===
ok
Test migrate VM ... SKIP: At least two hosts should be present in the zone for migration
Test destroy(expunge) Virtual Machine ... === TestName: test_09_expunge_vm | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 10 tests in 872.307s

OK (SKIP=1)
/tmp//MarvinLogs/test_vm_life_cycle_D6HQHB/results.txt (END)


Test Create Account and user for that account ... === TestName: test_01_create_account | Status : SUCCESS ===
ok
Test Sub domain allowed to launch VM  when a Domain ... === TestName: test_01_add_vm_to_subdomain | Status : SUCCESS ===
ok
Test delete domain without force option ... === TestName: test_DeleteDomain | Status : SUCCESS ===
ok
Test delete domain with force option ... === TestName: test_forceDeleteDomain | Status : SUCCESS ===
ok
Test to verify Non Root admin previleges ... === TestName: test_01_non_root_admin_Privileges | Status : SUCCESS ===
ok
Test Remove one user from the account ... === TestName: test_01_user_remove_VM_running | Status : SUCCESS ===
ok
Test to verify service offerings at same level in hierarchy ... === TestName: test_01_service_offering_hierarchy | Status : SUCCESS ===
ok
Test to verify service offerings at same level in hierarchy ... === TestName: test_01_service_offering_siblings | Status : SUCCESS ===
ok
Test to verify template at same level in hierarchy ... === TestName: test_01_template_hierarchy | Status : SUCCESS ===
ok
Test update admin details ... === TestName: test_updateAdminDetails | Status : SUCCESS ===
ok
Test update domain admin details ... === TestName: test_updateDomainAdminDetails | Status : SUCCESS ===
ok
Test user update API ... === TestName: test_updateUserDetails | Status : SUCCESS ===
ok
Test login API with domain ... === TestName: test_LoginApiDomain | Status : SUCCESS ===
ok
Test if Login API does not return UUID's ... === TestName: test_LoginApiUuidResponse | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 14 tests in 1320.486s

OK
/tmp//MarvinLogs/test_accounts_1TSTJ1/results.txt (END)

**Comment by bhaisaab** [comment]
@wilderrodrigues kickass, thanks for merging man!

**Comment by rsafonseca** [comment]
@wilderrodrigues the Xenserver tests are failing in master with a ClassCast Exception :(

*/plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/wrapper/citrix/CitrixRequestWrapper.java*
`    Reflections baseWrappers = new Reflections("com.cloud.hypervisor.xenserver.resource.wrapper");
    @SuppressWarnings("rawtypes")
    Set<Class<? extends CommandWrapper>> baseSet = baseWrappers.getSubTypesOf(CommandWrapper.class);` 

The baseSet ends up becoming the sum of all tests, because the scanner is recursive, so wrapper.xen56, wrapper.xcp, etc will all get included in the set.

I've tested fixing it by changing the package for the Citrix* classes to a package that in not parent to the other wrapper's classes and it's working fine.
Do you want to fix this your way, or should I send a PR? :)

**Comment by rsafonseca** [comment]
Hoi @wilderrodrigues  :)
I've created a pull request for it, have a look

https://github.com/apache/cloudstack/pull/293

glad to help :)

**Comment by wilderrodrigues** [comment]
Awesome.

Will look/merge it once behind the computer.

Thanks again.

Cheers,
Wilder

Sent from my iPhone

On 23 May 2015, at 16:21, Rafael da Fonseca <notifications@github.com<mailto:notifications@github.com>> wrote:


Hoi @wilderrodrigues<https://github.com/wilderrodrigues> :)
I've created a pull request for it, have a look

#293<https://github.com/apache/cloudstack/pull/293>

glad to help :)

**Pull request merged**
