### PR TITLE
kvm: fix wrong VM CPU usage

### PR DESCRIPTION
**Pull request by ustcweizhou**
## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by sureshanaparti — APPROVED** [review]
Changes LGTM, _info.nrVirtCpu_ is the actual VM's CPU count, which is already set in the stats, and the same is used for usage calc.

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
@blueorangutan test

**Review by shwstppr — APPROVED** [review]
lgtm

**Pull request merged**
