### PR TITLE
pom.xml: upgrade trilead-ssh2 verison

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR...

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@soreana @kriegsmanj can you test this ?
this probably fixes #8055

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test matrix

**Review by rohityadavcloud — APPROVED** [review]
LGTM but we need to check/test that this doesn’t bring any regressions

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Review by DaanHoogland — APPROVED** [review]
CLGTM, but needs extensive testing (component test suites?)

**Comment by soreana** [comment]
@weizhouapache I tested the PR, it didn't fix #8055 . Without these changes, it took roughly 10 minutes to restart a VPC with cleanup in an empty test environment. After applying the changes, the same VPC still required around 10 minutes for the restart.

Also tested VM deployments and ACL assignments they worked fine.

**Review by soreana — APPROVED** [review]

**Comment by weizhouapache** [comment]
> @weizhouapache I tested the PR, it didn't fix #8055 . Without these changes, it took roughly 10 minutes to restart a VPC with cleanup in an empty test environment. After applying the changes, the same VPC still required around 10 minutes for the restart.
> 
> Also tested VM deployments and ACL assignments they worked fine.

thanks @soreana 
that's not good to know  ;-D let's discuss in the issue #8055

**Comment by weizhouapache** [comment]
closing as it did not help https://github.com/apache/cloudstack/issues/8055

**Pull request closed without merging**
