### PR TITLE
vpc/network: set mtu of networks/vpcs/nics during 4.18 upgrade

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes a blocker issue in 4.18/main branch.

Steps to reproduce the issue

- deploy 4.17.2.0 environment
- create VPC and deploy vm
- upgrade to 4.18.0.0 nightly
- restart VPC with cleanup or restart VPC router

error logs

```
{"com.cloud.agent.api.PlugNicAnswer":{"result":"true","details":"success","wait":"0","bypassHostMaintenance":"false"}},{"com.cloud.agent.api.routing.GroupAnswer":{"results":["null - success: ","null - failed: Traceback (most recent call last):
  File "/opt/cloud/bin/update_config.py", line 144, in <module>
    process_file()
  File "/opt/cloud/bin/update_config.py", line 53, in process_file
    qf.load(None)
  File "/opt/cloud/bin/merge.py", line 309, in load
    updateDataBag(self)
  File "/opt/cloud/bin/merge.py", line 92, in __init__
    self.process()
  File "/opt/cloud/bin/merge.py", line 106, in process
    dbag = self.processGuestNetwork(self.db.getDataBag())
  File "/opt/cloud/bin/merge.py", line 158, in processGuestNetwork
    dp['mtu'] = str(d['mtu'])
KeyError: 'mtu'
"],"result":"false","wait":"0","bypassHostMaintenance":"false"}}] }

```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [x] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
this issue is caused by #6426 

The first mysql statement fixes the issue.
However, I do not know if there is other issue caused by the PR, so this PR updates the mtu of vpcs/nics as well.

cc @shwstppr @DaanHoogland

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Review by DaanHoogland — APPROVED** [review]
statements look good. I don´t think we can test this othere than using it a lot in environments.

**Review by rohityadavcloud — APPROVED** [review]

**Review by stephankruggg — APPROVED** [review]
CLGTM

**Pull request merged**
