### PR TITLE
CLOUDSTACK-8850: revertSnapshot command does not work

### PR DESCRIPTION
**Pull request by yvsubhash**
Updating the documentation before the api is actually supported

### CODE REVIEW

**Comment by ustcweizhou** [comment]
Please note revertSnapshot for KVM has been merged into master.

**Comment by bhaisaab** [comment]
LGTM cc @wilderrodrigues @wido @ustcweizhou

**Comment by wido** [comment]
LGTM

**Comment by bhaisaab** [comment]
Only text change and 2LGTMs, merging now

**Pull request merged**
