### PR TITLE
CKS : More log changes from uuid to name

### PR DESCRIPTION
**Pull request by davidjumani**
## Description
Changing log details from cluster / node UUID to name 
Add-on to https://github.com/apache/cloudstack/pull/4411

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
no comments

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan test

**Review by shwstppr — APPROVED** [review]
LGTM

**Comment by DaanHoogland** [comment]
trivial changes, test is by merit of the smoke tests.

**Pull request merged**
