### PR TITLE
display translation labels as html instead of plain text

### LINKED ISSUE #2575: HTML shown to end-user in UI
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.11.0.0
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

Any OS

##### SUMMARY

HTML code (`<br/><br/>`) in the UI

captura

##### STEPS TO REPRODUCE

~~~
Create a zone
~~~

##### EXPECTED RESULTS

~~~
non-HTML text
~~~

##### ACTUAL RESULTS

~~~

~~~

### PR DESCRIPTION
**Pull request by ernjvr**
## Description

fixes #2575 

In the dictionary internationalization javascript files there are certain label translation descriptions that contain HTML markup to help format the text when it is rendered in the UI. 

Expected Behaviour:
These HTML markup tags must be rendered as HTML instead of plain text.

Actual Behaviour:
These HTML markup tags are currently rendering as plain text instead of HTML.
For example, the HTML line break tag renders as plain text: '\<br/\>' instead of rendering an actual HTML line break.

To Reproduce:
Create a Zone. In the UI, in the left-hand pane, click on the Infrastructure link and click on Zones.
On the Zones screen, click on the 'Create Zone' button to create a Zone. Follow the Zone creation wizard steps up until the 'HOST' step. Notice that the description contains the '\<br/\>' text instead of rendering it as HTML.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## GitHub Issue/PRs

Fixes: #2575 

## Screenshots (if appropriate):
image

## How Has This Been Tested?
Manually: (See screenshot above)

Create a Zone. In the UI, in the left-hand pane, click on the Infrastructure link and click on Zones.
On the Zones screen, click on the 'Create Zone' button to create a Zone. Follow the Zone creation wizard steps up until the 'HOST' step. It now renders the \<br/\> HTML markup as HTML instead of plain text.

CloudStack version 4.11, KVM hypervisor.

## Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
Testing
- [ ] I have added tests to cover my changes.
- [ ] All relevant new and existing integration tests have passed.
- [ ] A full integration testsuite with all test that can run on my environment has passed.

### CODE REVIEW

**Comment by PaulAngus** [comment]
@blueorangutan package

**Comment by PaulAngus** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
Wait, @ernjvr you sent the PR for master branch and not 4.11 branch. I've updated the milestone to 4.12.0.0, was this intended or you wanted to fix this for 4.11? /cc @DaanHoogland

**Comment by rhtyd** [comment]
checked the change, @ernjvr can you resend a PR targeting 4.11 branch, thanks.

**Comment by ernjvr** [comment]
It was meant for 4.11 but can also go to master. I have resent a PR for 4.11.

**Pull request merged**
