### PR TITLE
Changed all references from VM to Instance to maintain a naming pattern.

### PR DESCRIPTION
**Pull request by msinhore**
### Description

This PR changes the term "VM" in the UI to Instance in order to establish naming consistency.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### How Has This Been Tested?

The term "VM" was used in different sections of the UI to refer to the Instance. In order to establish consistency, I modified the references to exclusively use "Instance". This resulted in a more polished UI with a uniform naming convention for Instances.

### CODE REVIEW

**Review by DaanHoogland — COMMENTED** [review]
@msinhore I think we should make this VM Instances and not just Instances. It will be confusing.

**Comment by msinhore** [comment]
@DaanHoogland, I appreciate your input, and I understand your concern about potential confusion. However, I believe that using 'Instances' rather than 'VM Instances' aligns with industry-standard terminology and provides a cleaner and more straightforward experience for users. Many cloud platforms, such as AWS, Google Cloud, and OpenStack, use the term 'Instances' to refer to their virtual machines, so adopting this term in CloudStack would promote consistency across the industry. Additionally, simplifying the terminology to 'Instances' can help reduce clutter in the UI and improve overall usability. While there might be a slight learning curve for existing users, I think the long-term benefits of adopting 'Instances' outweigh any initial confusion. Let me know if you have any other concerns or suggestions, and I'm happy to discuss further. 
Thank you!

**Comment by DaanHoogland** [comment]
> @DaanHoogland, I appreciate your input, and I understand your concern about potential confusion. However, I believe that using 'Instances' rather than 'VM Instances' aligns with industry-standard terminology and provides a cleaner and more straightforward experience for users. Many cloud platforms, such as AWS, Google Cloud, and OpenStack, use the term 'Instances' to refer to their virtual machines, so adopting this term in CloudStack would promote consistency across the industry. Additionally, simplifying the terminology to 'Instances' can help reduce clutter in the UI and improve overall usability. While there might be a slight learning curve for existing users, I think the long-term benefits of adopting 'Instances' outweigh any initial confusion. Let me know if you have any other concerns or suggestions, and I'm happy to discuss further. Thank you!

I think this is a very bad argument for two reasons:
1. if instance is accepted in the industry, VM instance will certainly be accepted as well
2. if the industry collectively jumps of a cliff I will not follow suit.
that said, start a discussion at dev@/users@ and find support. I will certainly not give it for this change. Instance is a multi-homonym and not a useful term as such.

**Comment by msinhore** [comment]
I also recognise the importance of considering alternative viewpoints and discussing this matter further within the community. Feel free to initiate a conversation in the community to gather more feedback and opinions.

**Pull request closed without merging**
