### PR TITLE
Adds tar as dependency used for VMware to seed systemvmtemplate on mgmt server 

### PR DESCRIPTION
**Pull request by rohityadavcloud**
Adds tar as dependency used for VMware to seed systemvmtemplate on mgmt server

### CODE REVIEW

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by weizhouapache** [comment]
@rohityadavcloud 
systemvm templates are not bundled if `@blueorangutan package` is not the last line of your comment (e.g. blank/empty line after that).

@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Comment by rohityadavcloud** [comment]
@blueorangutan help

**Comment by rohityadavcloud** [comment]
@blueorangutan rocky8 kvm-rocky8

**Comment by rohityadavcloud** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Review by DaanHoogland — APPROVED** [review]
looks good,
Have you seen any errors that make this necessary, and only necessary on centos8?
if not needed on rehel7 or rhel9 varieties, it seems good enough like this.

**Comment by rohityadavcloud** [comment]
Mentioned briefly in the description; I was trying to deploy Vmware 7 and 8 on an EL8 mgmt server when the routing-8.ova won't extract as "tar" pkg was missing on the mgmt server host. This fixes for only vmware env with EL8. @DaanHoogland

**Comment by DaanHoogland** [comment]
@blueorangutan test centos7 vmware-70u3

**Comment by rohityadavcloud** [comment]
@blueorangutan test centos7 vmware-70u3

**Comment by rohityadavcloud** [comment]
@blueorangutan test centos7 vmware-70u3

**Comment by rohityadavcloud** [comment]
@DaanHoogland - this is ready but let's wait until the smoketests pass. (earlier env failed due to env issues)

**Pull request merged**
