### PR TITLE
Feature/persisten systemvm redundant vpc rebase

### PR DESCRIPTION
**Pull request by wilderrodrigues**
Hi @bhaisaab [Rohit],

That's the PR for the Persistent SystemVM config + Redundant VPC work we have been doing for a while.

Today I rebased from master, in order to get Funs OV3 work, and tested the whole branch with the set of marvin tests I have.

Could you please have a look at this branch and check if that's fine to be merged towards Master?

The tests results follow below.

Thanks in advance.

Cheers,
Wilder

=========================================================================================================================================================

Test Create Account and user for that account ... === TestName: test_01_create_account | Status : SUCCESS ===
ok
Test Sub domain allowed to launch VM  when a Domain level zone is created ... === TestName: test_01_add_vm_to_subdomain | Status : SUCCESS ===
ok
Test delete domain without force option ... === TestName: test_DeleteDomain | Status : SUCCESS ===
ok
Test delete domain with force option ... === TestName: test_forceDeleteDomain | Status : SUCCESS ===
ok
Test update admin details ... === TestName: test_updateAdminDetails | Status : SUCCESS ===
ok
Test update domain admin details ... === TestName: test_updateDomainAdminDetails | Status : SUCCESS ===
ok
Test user update API ... === TestName: test_updateUserDetails | Status : SUCCESS ===
ok
Test login API with domain ... === TestName: test_LoginApiDomain | Status : SUCCESS ===
ok
Test if Login API does not return UUID's ... === TestName: test_LoginApiUuidResponse | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 9 tests in 1311.256s

OK
/tmp//MarvinLogs/test_accounts_UJFDB3/results.txt

=========================================================================================================================================================

Test advanced zone virtual router ... === TestName: test_advZoneVirtualRouter | Status : SUCCESS ===
ok
Test Deploy Virtual Machine ... === TestName: test_deploy_vm | Status : SUCCESS ===
ok
Test Multiple Deploy Virtual Machine ... === TestName: test_deploy_vm_multiple | Status : SUCCESS ===
ok
Test Stop Virtual Machine ... === TestName: test_01_stop_vm | Status : SUCCESS ===
ok
Test Start Virtual Machine ... === TestName: test_02_start_vm | Status : SUCCESS ===
ok
Test Reboot Virtual Machine ... === TestName: test_03_reboot_vm | Status : SUCCESS ===
ok
Test destroy Virtual Machine ... === TestName: test_06_destroy_vm | Status : SUCCESS ===
ok
Test recover Virtual Machine ... === TestName: test_07_restore_vm | Status : SUCCESS ===
ok
Test migrate VM ... SKIP: At least two hosts should be present in the zone for migration
Test destroy(expunge) Virtual Machine ... === TestName: test_09_expunge_vm | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 10 tests in 873.671s

OK (SKIP=1)
/tmp//MarvinLogs/test_vm_life_cycle_FT0VUY/results.txt

=========================================================================================================================================================

test_privategw_acl (integration.acs.tests.test_privategw_acl.TestPrivateGwACL) ... === TestName: test_privategw_acl | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 1 test in 86.001s

OK
/tmp//MarvinLogs/test_privategw_acl_OAEQIW/results.txt

=========================================================================================================================================================

Test reset virtual machine on reboot ... === TestName: test_01_reset_vm_on_reboot | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 1 test in 217.738s

OK
/tmp//MarvinLogs/test_reset_vm_on_reboot_IR5ZLY/results.txt

=========================================================================================================================================================

Test router internal advanced zone ... SKIP: Marvin configuration has no host credentials to check router services
Test restart network ... === TestName: test_03_restart_network_cleanup | Status : SUCCESS ===
ok
Test router basic setup ... === TestName: test_05_router_basic | Status : SUCCESS ===
ok
Test router advanced setup ... === TestName: test_06_router_advanced | Status : SUCCESS ===
ok
Test stop router ... === TestName: test_07_stop_router | Status : SUCCESS ===
ok
Test start router ... === TestName: test_08_start_router | Status : SUCCESS ===
ok
Test reboot router ... === TestName: test_09_reboot_router | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 7 tests in 455.654s

OK (SKIP=1)
/tmp//MarvinLogs/test_routers_LTXVCY/results.txt

=========================================================================================================================================================

Test create VPC offering ... === TestName: test_01_create_vpc_offering | Status : SUCCESS ===
ok
Test VPC offering without load balancing service ... === TestName: test_03_vpc_off_without_lb | Status : SUCCESS ===
ok
Test VPC offering without static NAT service ... === TestName: test_04_vpc_off_without_static_nat | Status : SUCCESS ===
ok
Test VPC offering without port forwarding service ... === TestName: test_05_vpc_off_without_pf | Status : SUCCESS ===
ok
Test VPC offering with invalid services ... === TestName: test_06_vpc_off_invalid_services | Status : SUCCESS ===
ok
Test update VPC offering ... === TestName: test_07_update_vpc_off | Status : SUCCESS ===
ok
Test list VPC offering ... === TestName: test_08_list_vpc_off | Status : SUCCESS ===
ok
test_09_create_redundant_vpc_offering (integration.acs.tests.test_vpc_offerings.TestVPCOffering) ... === TestName: test_09_create_redundant_vpc_offering | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 8 tests in 684.518s

OK
/tmp//MarvinLogs/test_vpc_offerings_7AQKRG/results.txt

=========================================================================================================================================================

Test start/stop of router after addition of one guest network ... === TestName: test_01_start_stop_router_after_addition_of_one_guest_network | Status : SUCCESS ===
ok
Test reboot of router after addition of one guest network ... === TestName: test_02_reboot_router_after_addition_of_one_guest_network | Status : SUCCESS ===
ok
Test to change service offering of router after addition of one guest network ... === TestName: test_04_chg_srv_off_router_after_addition_of_one_guest_network | Status : SUCCESS ===
ok
Test destroy of router after addition of one guest network ... === TestName: test_05_destroy_router_after_addition_of_one_guest_network | Status : SUCCESS ===
ok
Test to stop and start router after creation of VPC ... === TestName: test_01_stop_start_router_after_creating_vpc | Status : SUCCESS ===
ok
Test to reboot the router after creating a VPC ... === TestName: test_02_reboot_router_after_creating_vpc | Status : SUCCESS ===
ok
Tests to change service offering of the Router after ... === TestName: test_04_change_service_offerring_vpc | Status : SUCCESS ===
ok
Test to destroy the router after creating a VPC ... === TestName: test_05_destroy_router_after_creating_vpc | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 8 tests in 838.694s

OK
/tmp//MarvinLogs/test_vpc_routers_ESJZ88/results.txt

=========================================================================================================================================================

Test VPN in VPC ... === TestName: test_vpc_remote_access_vpn | Status : SUCCESS ===
ok
Test VPN in VPC ... === TestName: test_vpc_site2site_vpn | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 2 tests in 412.303s

OK
/tmp//MarvinLogs/test_vpc_vpn_AZ8F3C/results.txt

=========================================================================================================================================================

Test to change service offering of router after addition of one guest network ... === TestName: test_04_chg_srv_off_router_after_addition_of_one_guest_network | Status : SUCCESS ===
ok
Test destroy of router after addition of one guest network ... === TestName: test_05_destroy_router_after_addition_of_one_guest_network | Status : SUCCESS ===
ok
Test to stop and start router after creation of VPC ... === TestName: test_01_stop_start_router_after_creating_vpc | Status : SUCCESS ===
ok
Test to reboot the router after creating a VPC ... === TestName: test_02_reboot_router_after_creating_vpc | Status : SUCCESS ===
ok
Tests to change service offering of the Router after ... === TestName: test_04_change_service_offerring_vpc | Status : SUCCESS ===
ok
Test to destroy the router after creating a VPC ... === TestName: test_05_destroy_router_after_creating_vpc | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 6 tests in 657.504s

OK
/tmp//MarvinLogs/test_redundant_vpc_FLIL4M/results.txt

=========================================================================================================================================================

### CODE REVIEW

**Comment by bhaisaab** [comment]
Thanks for sending the PR @wilderrodrigues I'll try to test and merge today or tomorrow. Right now focusing on 4.5 branch, since 4.5.1 needs to go soon.

**Comment by wilderrodrigues** [comment]
Thanks for the reply

Sent from my iPhone

On 17 Mar 2015, at 09:34, Rohit Yadav <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for sending the PR @wilderrodrigues<https://github.com/wilderrodrigues> I'll try to test and merge today or tomorrow. Right now focusing on 4.5 branch, since 4.5.1 needs to go soon.

**Comment by bhaisaab** [comment]
Loved the Persistent SystemVM config work, especially the use of json transport/encoding way to send configs. Did basic vm lifecycle, networking tests. LGTM, merging.

**Comment by wilderrodrigues** [comment]
Awesome!

Thanks a lot, Rohit!

Now let's get everybody to test it even more and get it 100% for ACS 4.6

Cheers,
Wilder

**Pull request merged**
