### PR TITLE
params: allow signatureversion and expires without logging

### PR DESCRIPTION
**Pull request by pyr**
## Description

This patch considers the new expires and signatureversion parameters
valid. Without this, all calls log when using the V3 signature scheme.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by rafaelweingartner** [comment]
Has your other PR been merged already?

**Comment by pyr** [comment]
@rafaelweingartner which other PR are you referring to?

**Comment by pyr** [comment]
I'm not sure I understand the Jenkins failure but it seems unrelated to this PR

**Comment by rafaelweingartner** [comment]
You are saying that these parameters are always logged as not valid ones. Therefore, I was assuming that they are somehow new parameters that were introduced by you. 

It is Monday morning,  my brain might not be working yet.

P.S. I restarted Jenkins manually.

**Comment by pyr** [comment]
@rafaelweingartner I did not introduce the new parameters, they were introduced as part of the Signature version 3 scheme in the `ApiServer` class.

**Comment by pyr** [comment]
@rafaelweingartner provided I find where to push again, how many approvals should I wait for before merging? (it's been a while since I pushed to the project)

**Comment by rafaelweingartner** [comment]
2

**Comment by rhtyd** [comment]
is this the PR https://github.com/apache/cloudstack/pull/2893 in question @pyr ? If so, let's review and merge https://github.com/apache/cloudstack/pull/2893 before this PR.

**Comment by pyr** [comment]
@rhtyd nope, this is unrelated to #2893, signature version 3 parameters are already logged

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by pyr** [comment]
Thanks for the review!

**Comment by rhtyd** [comment]
@pyr we've not tested/merged your PR, we need 2 lgtms just for qualifying, we also need testing. Do you still want the PR -- in which case please re-open the PR.

**Comment by pyr** [comment]
@rhtyd Hi rohit, this wasn't clear to me, I went ahead and committed assuming what @rafaelweingartner mentioned was sufficient, I'm happy to revert if you think that is warranted.

**Comment by rafaelweingartner** [comment]
@pyr somebody has to merge it. Your PR was not merged, and your commit is not in our code base yet.

What do you mean with "went ahead and committed"?

**Comment by rhtyd** [comment]
@pyr this is not acceptable, you merged a commit on master directly without the PR id and without any testing results on them. Your change may therefore potentially break master for others. Instead of closing or pushing the change, you should have reopened this PR or create a new PR and wait for test results, even though we requested you to re-open your PR. If things were not clear you could discuss and/or ask questions but you committed the change on master.
You may see how other PRs get reviewed, tested and (squash) merged.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by pyr** [comment]
@rhtyd I'm happy to revert the change, and sorry I misinterpreted @rafaelweingartner's instructions. Let me know how you wish to proceed

**Comment by rhtyd** [comment]
@pyr no need to revert now as it would make git history ugly, I've kicked testing now so let's wait and act accordingly. I'm sure your changes don't break anything, we still need testing as a matter of process to ensure stability. Once testing is OK, you may close this PR as the change is already on master.

**Comment by rafaelweingartner** [comment]
@pyr, @rhtyd is right. If you are a committer, you should have done the merge via Github. Moreover, we need the functional tests. When you pushed your changes, there was no functional testes results.

**Comment by pyr** [comment]
@rafaelweingartner I don't have the merge option on Github, hence I assumed the pre-github workflow prevailed. Again, apologies and all.

**Comment by rafaelweingartner** [comment]
@pyr then you need to follow the "signup" process for the Gitbox experiment.

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
Deployment/setup failed on testing, retrying again
@blueorangutan test

**Comment by rhtyd** [comment]
Checked master, there are some intermittent failures but no new/major failure. I'll close the PR as the commit already is on master 58b4e71b0e62a0e96e6eb20e96234a1599d0ffd0.

**Pull request closed without merging**
