### PR TITLE
findbugs: new found old instance of DM_DEFAULT_ENCODING fixed

### PR DESCRIPTION
**Pull request by DaanHoogland**
this quick fix to silence the findbugs
   which seems to think this is a new issue

### CODE REVIEW

**Comment by swill** [comment]
It looks like your IDE had a field day with this class.  So other than the reordering of imports, adding `final` to a ton of variables and removing some unneeded brackets, this is really the only change?  Right?

`
-        String dir = UUID.nameUUIDFromBytes(nfsPath.getBytes()).toString();
+        final String dir = UUID.nameUUIDFromBytes(nfsPath.getBytes(getPreferredCharset())).toString();
`

**Comment by DaanHoogland** [comment]
:) @swill it is the only part I typed

**Comment by swill** [comment]
Haha.  Fair enough.  I will let Raja test, but otherwise it LGTM.

**Comment by pvr9711** [comment]
LGTM
Ran BVT  with XS 6.5  - all the test passed with the exception of the following tests due to env issues:
test_01_create_volume - ssh issue.  
test_07_list_default_iso - iso didn't exist.  
test_01_test_vm_volume_snapshot - test case issue - operation is not allowed?

**Comment by DaanHoogland** [comment]
#1438 covers this

**Pull request closed without merging**
