### PR TITLE
pom.xml: bump only required dependencies

### PR DESCRIPTION
**Pull request by rohityadavcloud**
Upgrades to some dependencies that address CVEs and improvements

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
looks good, I think we should also open a PR with all possible upgrades, just to keep ourselves up to date. Of course that one would have less priority than this one.

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan help

**Comment by rohityadavcloud** [comment]
Thanks @DaanHoogland yes - we can do that for main branch; for 4.18 I went through them and picked only that weren't breaking the build and must have ones (springframework and reload4j in particular, but their CVEs still aren't directly affecting cloudstack)

**Comment by rohityadavcloud** [comment]
@blueorangutan help

**Comment by DaanHoogland** [comment]
@rohityadavcloud any further testing required?
cc @weizhouapache @shwstppr @vladimirpetrov

**Review by shwstppr — APPROVED** [review]
LGTM based on smoke test run

**Pull request merged**
