### PR TITLE
ui: Add user initials as avatar if no icon present

### PR DESCRIPTION
**Pull request by davidjumani**
### Description

Fixes the missing user avatar in the header when no icon is present

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### Screenshots (if appropriate):

Screenshot from 2022-03-08 17-24-40

### CODE REVIEW

**Review by rohityadavcloud — APPROVED** [review]

**Comment by davidjumani** [comment]
@blueorangutan ui

**Comment by davidjumani** [comment]
@blueorangutan ui

**Review by nvazquez — APPROVED** [review]
LGTM - manually tested

**Comment by davidjumani** [comment]
@blueorangutan ui

**Pull request merged**
