### PR TITLE
[VMware] Cancel the pending tasks for a worker VM before destroying it

### PR DESCRIPTION
**Pull request by sureshanaparti**
### Description

This PR cancels the pending tasks for a worker VM (in VMware hypervisor) before destroying it.

Fixes: #3408

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

Set following global settings:

job.expire.minutes : 1
job.cancel.threshold.minutes : 1
vmware.clean.old.worker.vms : true

- Create a big size DATA disk, and add some dummy files (after creating file system) to it.
- Take volume snapshot

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test centos7 vmware-67u3

**Review by nvazquez — APPROVED** [review]

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by nvazquez** [comment]
@blueorangutan help

**Comment by nvazquez** [comment]
@blueorangutan test ubuntu18 vmware-67u3

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by rhtyd** [comment]
Merged this based on test results and review.
Wondering if any further manual testing is needed @sureshanaparti @nvazquez?

**Comment by nvazquez** [comment]
Thanks @rhtyd, it's fine IMO as @davidjumani has tested manually https://github.com/apache/cloudstack/pull/5374#pullrequestreview-740176275

**Pull request merged**
