### PR TITLE
Migrating VM from ISO failures

### PR DESCRIPTION
**Pull request by nvazquez**
## Description
Prevents errors while migrating VM from ISO:

- Test 1: Deploy VM from ISO -> Live migrate VM to another host -> ERROR
- Test 2: Register ISO using Direct Download on KVM -> Deploy VM from ISO -> Live migrate VM to another host -> ERROR

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?
Local environment: 2 KVM CentOS 7 hosts.
Repeated tests described above and pass successfully

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
Test LGTM, can you review - @rafaelweingartner @wido @GabrielBrascher @nvazquez thanks.

**Comment by wido** [comment]
If I read the code correctly and what I'm missing in the description is that this only happens with VMs which were deployed using Direct Downloaded templates, correct?

**Comment by rhtyd** [comment]
Yes the second case is indeed around direct download feature, @nvazquez can you comment?

**Comment by nvazquez** [comment]
Sorry @wido somehow I didn't see your comment before. It happened on 2 cases: direct downloaded and not-direct downloaded ISOs.

**Pull request merged**
