### PR TITLE
CLOUDSTACK-9449: Fix typo in user role description

### PR DESCRIPTION
**Pull request by rhtyd**
Fixes description in default user role entry.

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan kick

**Comment by rhtyd** [comment]
@blueorangutan help

**Comment by pdion891** [comment]
Hum, This is a change to a file for an upgrade SQL to a release that is already GA. 
I think it would be preferable to get it into the 490_to_4100 file to avoid divergence between the voted release and the repo.

**Comment by rhtyd** [comment]
@pdion891 thanks I'll fix that.

**Pull request closed without merging**
