### PR TITLE
Let network guru decide if ipv6 cidr size can't be equal to 64

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR makes changes to allow shared networks to have ipv6 cidr size other than 64. For now, it let's network guru decide whether this is possible or not. Network Orchestrator relies on the return value of `isSlaacV6Only` method of the network guru.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by borisstoyanov** [comment]
@blueorangutan test matrix

**Review by shwstppr — APPROVED** [review]
Code LGTM

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Review by borisstoyanov — APPROVED** [review]
LGTM, I've manually checked it.

**Pull request merged**
