### PR TITLE
CLOUDSTACK-8720: Handle corner case in remove nic from vm

### PR DESCRIPTION
**Pull request by sanju1010**
Please see the bug for more details

### CODE REVIEW

**Comment by sanju1010** [comment]
Test to verify remove nic from vm if the nic ip is same as another vm ip in another network ... === TestName: test_29_remove_nic_CS22503 | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 1 test in 359.186s

OK

**Comment by pavanb018** [comment]
Looks Good to me. 

Probably remove_nic might return an error if the NIC is not removed , but just wondering if a check is needed in the below step , to validate that only 1 NIC exists for the VM by listing nics after the remove nic operation? If you feel the check is redundant then leave it.: 

#Try to remove nic 2 from vm1
+        try:
+            vm1.remove_nic(self.apiclient, self.nics[0].id)
+        except Exception as e:
+            self.fail("Failed to delete the nic from vm")
+        return

**Comment by nitt10prashant** [comment]
Looks Good

**Comment by pavanb018** [comment]
LGTM

**Pull request closed without merging**
