### PR TITLE
CLOUDSTACK-8933 SSVm and CPVM do not survive a reboot from API

### PR DESCRIPTION
**Pull request by wilderrodrigues**
This closes PR #930 as well.

I Rebased @bvbharat's PR with latest Master and tested the SSVM/CPVM and the routers: rVPC; VPC; VR; and RVR.

### CODE REVIEW

**Comment by wilderrodrigues** [comment]
Ping @karuturi @bvbharat @borisroman @wido @remibergsma @miguelaferreira @DaanHoogland 

Test Environment:

* Management Server + MySQL on CentOS 7.1
* KVM host on CentOS 7.1
* ACS Agent and Common built from source

Tests Results:

```
Test SSVM Internals ... === TestName: test_03_ssvm_internals | Status : SUCCESS ===
ok
Test CPVM Internals ... === TestName: test_04_cpvm_internals | Status : SUCCESS ===
ok
Test stop SSVM ... === TestName: test_05_stop_ssvm | Status : SUCCESS ===
ok
Test stop CPVM ... === TestName: test_06_stop_cpvm | Status : SUCCESS ===
ok
Test reboot SSVM ... === TestName: test_07_reboot_ssvm | Status : SUCCESS ===
ok
Test reboot CPVM ... === TestName: test_08_reboot_cpvm | Status : SUCCESS ===
ok
Test destroy SSVM ... === TestName: test_09_destroy_ssvm | Status : SUCCESS ===
ok
Test destroy CPVM ... === TestName: test_10_destroy_cpvm | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 8 tests in 2099.701s

OK
/tmp//MarvinLogs/test_ssvm_VGNRI1/results.txt (END)



Create a redundant VPC with two networks with two VMs in each network ... === TestName: test_01_create_redundant_VPC_2tiers_4VMs_4IPs_4PF_ACL | Status : SUCCESS ===
ok
Create a redundant VPC with two networks with two VMs in each network and check default routes ... === TestName: test_02_redundant_VPC_default_routes | Status : SUCCESS ===
ok
Create a VPC with two networks with one VM in each network and test nics after destroy ... === TestName: test_01_VPC_nics_after_destroy | Status : SUCCESS ===
ok
Create a VPC with two networks with one VM in each network and test default routes ... === TestName: test_02_VPC_default_routes | Status : SUCCESS ===
ok
Test iptables default INPUT/FORWARD policy on RouterVM ... === TestName: test_02_routervm_iptables_policies | Status : SUCCESS ===
ok
Test iptables default INPUT/FORWARD policies on VPC router ... === TestName: test_01_single_VPC_iptables_policies | Status : SUCCESS ===
ok
Stop existing router, add a PF rule and check we can access the VM ... === TestName: test_isolate_network_FW_PF_default_routes | Status : SUCCESS ===
ok
Test redundant router internals ... === TestName: test_RVR_Network_FW_PF_SSH_default_routes | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 8 tests in 7418.431s

OK
/tmp//MarvinLogs/test_routers_network_ops_VMU09R/results.txt (END)



Test to create Load balancing rule with source NAT ... === TestName: test_01_create_lb_rule_src_nat | Status : SUCCESS ===
ok
Test to create Load balancing rule with non source NAT ... === TestName: test_02_create_lb_rule_non_nat | Status : SUCCESS ===
ok
Test for assign & removing load balancing rule ... === TestName: test_assign_and_removal_lb | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 3 tests in 871.657s

OK
/tmp//MarvinLogs/test_loadbalance_AHQVYG/results.txt (END)
```

Cheers,
Wilder

**Comment by karuturi** [comment]
The code concerns(incase of stop-start on a slow network and the changes of outer while waiting infinitely) with it were not addressed.
I am ok with merging this and taking up those later. But, if they are simple, better to address them now.

**Comment by wilderrodrigues** [comment]
Hi @karuturi ,

I did not change the code as I thought the work needed was more tests related. I had a better look at PR #930 and will address your concerns in the code.

Thanks for the hints. :)

Cheers,
Wilder

**Comment by wilderrodrigues** [comment]
@karuturi @remibergsma 

In the previous PR it was mentioned that looping 30 times would probably be enough to get the configuration done and also get rid of the infinite loop. I looked at the code and did not find any sleep or any sort of wait, so looping 30 times will go quite fast:

The block inside the for loop would be this one:

```
           while read line; do
             if [[ $line == cmdline:* ]]; then
               cmd=${line//cmdline:/}
               echo $cmd > /var/cache/cloud/cmdline
             elif [[ $line == pubkey:* ]]; then
               pubkey=${line//pubkey:/}
               echo $pubkey > /var/cache/cloud/authorized_keys
               echo $pubkey > /root/.ssh/authorized_keys
             fi
           done < /dev/vport0p1
           # In case of reboot we do not send the boot args again.
           # So, no need to wait for them, as the boot args are already set at startup
           if [ -s /var/cache/cloud/cmdline  ]
           then
               log_it "Found a non empty cmdline file. Will now exit the loop and proceed with configuration."
               break;
           fi
```

If my assumption is right, about the 30 times loop, I would suggest to do it in a different way. For example:

```
local factor=2
local progress=1
for i in {1..5}
do
    #block mentioned above
    sleep ${progress}
    progress=$[ progress * factor]
done
```

In a worst case scenario we would wait 16 seconds before then leave the for loop.

What do you think?

Cheers,
Wilder

**Comment by wilderrodrigues** [comment]
@karuturi @remibergsma 

I checked manually if the cached cmdline has the same link local IP as defined in the interface after stop/start/reboot a SSVM/CPVM router. And it does. So, that's fine.

But to make it better I will improve the current test_ssvm.py and add that check. It will make the PR wait a bit longer, but not more than a few hours.

Please, I'm also waiting on your comments concerning the solution proposed in my comment 2 hours ago. Thanks in advance. 

Cheers,
Wilder

**Comment by karuturi** [comment]
Agree.

-----Original Message-----

**Comment by borisroman** [comment]
@wilderrodrigues @remibergsma @karuturi I tested the PR AS-IS, without the changes proposed Wilder.

Test results:
```
=== TestName: test_03_ssvm_internals | Status : SUCCESS ===
ok
=== TestName: test_04_cpvm_internals | Status : SUCCESS ===
ok
=== TestName: test_05_stop_ssvm | Status : SUCCESS ===
ok
=== TestName: test_06_stop_cpvm | Status : SUCCESS ===
ok
=== TestName: test_07_reboot_ssvm | Status : SUCCESS ===
ok
=== TestName: test_08_reboot_cpvm | Status : SUCCESS ===
ok
=== TestName: test_09_destroy_ssvm | Status : SUCCESS ===
ok
=== TestName: test_10_destroy_cpvm | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 8 tests in 1805.321s

OK
```
```
=== TestName: test_01_create_redundant_VPC_2tiers_4VMs_4IPs_4PF_ACL | Status : SUCCESS ===
ok
=== TestName: test_02_redundant_VPC_default_routes | Status : SUCCESS ===
ok
=== TestName: test_01_VPC_nics_after_destroy | Status : SUCCESS ===
ok
=== TestName: test_02_VPC_default_routes | Status : SUCCESS ===
ok
=== TestName: test_02_routervm_iptables_policies | Status : SUCCESS ===
ok
=== TestName: test_01_single_VPC_iptables_policies | Status : SUCCESS ===
ok
=== TestName: test_isolate_network_FW_PF_default_routes | Status : SUCCESS ===
ok
=== TestName: test_RVR_Network_FW_PF_SSH_default_routes | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 8 tests in 5981.632s

OK
```
```
=== TestName: test_01_create_lb_rule_src_nat | Status : SUCCESS ===
ok
=== TestName: test_02_create_lb_rule_non_nat | Status : SUCCESS ===
ok
=== TestName: test_assign_and_removal_lb | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 3 tests in 659.437s

OK
```

Based on the tests: LGTM :+1:

**Comment by wilderrodrigues** [comment]
Thanks for the confirmation, @karuturi . Much appreciated! :)

Thanks for testing, @borisroman ! I will force push the new tests in about 30min. If you can test it again, that would be cool!

Cheers,
Wilder

**Comment by borisroman** [comment]
@wilderrodrigues Pushing will be alright. No force needed ;)

**Comment by wilderrodrigues** [comment]
Ping @borisroman @remibergsma @karuturi @miguelaferreira 

New code available for review. Please let me know if that's fine.

Test Results:

```
Test SSVM Internals ... === TestName: test_03_ssvm_internals | Status : SUCCESS ===
ok
Test CPVM Internals ... === TestName: test_04_cpvm_internals | Status : SUCCESS ===
ok
Test stop SSVM ... === TestName: test_05_stop_ssvm | Status : SUCCESS ===
ok
Test stop CPVM ... === TestName: test_06_stop_cpvm | Status : SUCCESS ===
ok
Test reboot SSVM ... === TestName: test_07_reboot_ssvm | Status : SUCCESS ===
ok
Test reboot CPVM ... === TestName: test_08_reboot_cpvm | Status : SUCCESS ===
ok
Test destroy SSVM ... === TestName: test_09_destroy_ssvm | Status : SUCCESS ===
ok
Test destroy CPVM ... === TestName: test_10_destroy_cpvm | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 8 tests in 1589.042s

OK
/tmp//MarvinLogs/test_ssvm_NPMX05/results.txt (END)
```

I will also run some other tests, but you can start reviewing/testing as soon as you have time.

Cheers,
Wilder

**Comment by borisroman** [comment]
@wilderrodrigues Done.

Test results:
```
=== TestName: test_03_ssvm_internals | Status : SUCCESS ===
ok
=== TestName: test_04_cpvm_internals | Status : SUCCESS ===
ok
=== TestName: test_05_stop_ssvm | Status : SUCCESS ===
ok
=== TestName: test_06_stop_cpvm | Status : SUCCESS ===
ok
=== TestName: test_07_reboot_ssvm | Status : SUCCESS ===
ok
=== TestName: test_08_reboot_cpvm | Status : SUCCESS ===
ok
=== TestName: test_09_destroy_ssvm | Status : SUCCESS ===
ok
=== TestName: test_10_destroy_cpvm | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 8 tests in 1320.153s

OK
```

Still LGTM :+1:

**Comment by wilderrodrigues** [comment]
That was quick! Thanks, @borisroman ! :)

@karuturi @remibergsma 1 LGTM to go. :)

Cheers,
Wilder

**Comment by wilderrodrigues** [comment]
Ping @remibergsma @karuturi @DaanHoogland @miguelaferreira @bhaisaab 

I ran the router tests as well.

Test Environment:

* Management Server + MySQL on CentOS 7.1
* KVM host on CentOS 7.1
* ACS Agent and Common built from source

Tests Results:

```
Create a redundant VPC with two networks with two VMs in each network ... === TestName: test_01_create_redundant_VPC_2tiers_4VMs_4IPs_4PF_ACL | Status : SUCCESS ===
ok
Create a redundant VPC with two networks with two VMs in each network and check default routes ... === TestName: test_02_redundant_VPC_default_routes | Status : SUCCESS ===
ok
Test iptables default INPUT/FORWARD policy on RouterVM ... === TestName: test_02_routervm_iptables_policies | Status : SUCCESS ===
ok
Test iptables default INPUT/FORWARD policies on VPC router ... === TestName: test_01_single_VPC_iptables_policies | Status : SUCCESS ===
ok
Create a VPC with two networks with one VM in each network and test nics after destroy ... === TestName: test_01_VPC_nics_after_destroy | Status : SUCCESS ===
ok
Create a VPC with two networks with one VM in each network and test default routes ... === TestName: test_02_VPC_default_routes | Status : SUCCESS ===
ok
Test to create Load balancing rule with source NAT ... === TestName: test_01_create_lb_rule_src_nat | Status : SUCCESS ===
ok
Test to create Load balancing rule with non source NAT ... === TestName: test_02_create_lb_rule_non_nat | Status : SUCCESS ===
ok
Test for assign & removing load balancing rule ... === TestName: test_assign_and_removal_lb | Status : SUCCESS ===
ok
Stop existing router, add a PF rule and check we can access the VM ... === TestName: test_isolate_network_FW_PF_default_routes | Status : SUCCESS ===
ok
Test redundant router internals ... === TestName: test_RVR_Network_FW_PF_SSH_default_routes | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 11 tests in 7829.409s

OK
/tmp//MarvinLogs/test_routers_network_ops_6BZDHE/results.txt (END)
```

Looking forward a 2nd LGTM. :)

Cheers,
Wilder

**Comment by remibergsma** [comment]
@wilderrodrigues @borisroman My tests also succeeded:

```
Test router internal advanced zone ... === TestName: test_02_router_internal_adv | Status : SUCCESS ===
ok
Test restart network ... === TestName: test_03_restart_network_cleanup | Status : SUCCESS ===
ok
Test router basic setup ... === TestName: test_05_router_basic | Status : SUCCESS ===
ok
Test router advanced setup ... === TestName: test_06_router_advanced | Status : SUCCESS ===
ok
Test stop router ... === TestName: test_07_stop_router | Status : SUCCESS ===
ok
Test start router ... === TestName: test_08_start_router | Status : SUCCESS ===
ok
Test reboot router ... === TestName: test_09_reboot_router | Status : SUCCESS ===
ok
test_privategw_acl (integration.smoke.test_privategw_acl.TestPrivateGwACL) ... === TestName: test_privategw_acl | Status : SUCCESS ===
ok
Test reset virtual machine on reboot ... === TestName: test_01_reset_vm_on_reboot | Status : SUCCESS ===
ok
Test advanced zone virtual router ... === TestName: test_advZoneVirtualRouter | Status : SUCCESS ===
ok
Test Deploy Virtual Machine ... === TestName: test_deploy_vm | Status : SUCCESS ===
ok
Test Multiple Deploy Virtual Machine ... === TestName: test_deploy_vm_multiple | Status : SUCCESS ===
ok
Test Stop Virtual Machine ... === TestName: test_01_stop_vm | Status : SUCCESS ===
ok
Test Start Virtual Machine ... === TestName: test_02_start_vm | Status : SUCCESS ===
ok
Test Reboot Virtual Machine ... === TestName: test_03_reboot_vm | Status : SUCCESS ===
ok
Test destroy Virtual Machine ... === TestName: test_06_destroy_vm | Status : SUCCESS ===
ok
Test recover Virtual Machine ... === TestName: test_07_restore_vm | Status : SUCCESS ===
ok
Test migrate VM ... === TestName: test_08_migrate_vm | Status : SUCCESS ===
ok
Test destroy(expunge) Virtual Machine ... === TestName: test_09_expunge_vm | Status : SUCCESS ===
ok
Test VPN in VPC ... === TestName: test_vpc_remote_access_vpn | Status : SUCCESS ===
ok
Test VPN in VPC ... === TestName: test_vpc_site2site_vpn | Status : SUCCESS ===
ok
Test to create service offering ... === TestName: test_01_create_service_offering | Status : SUCCESS ===
ok
Test to update existing service offering ... === TestName: test_02_edit_service_offering | Status : SUCCESS ===
ok
Test to delete service offering ... === TestName: test_03_delete_service_offering | Status : SUCCESS ===
ok
Test create VPC offering ... === TestName: test_01_create_vpc_offering | Status : SUCCESS ===
ok
Test VPC offering without load balancing service ... === TestName: test_03_vpc_off_without_lb | Status : EXCEPTION ===
ERROR
Test VPC offering without static NAT service ... === TestName: test_04_vpc_off_without_static_nat | Status : EXCEPTION ===
ERROR
Test VPC offering without port forwarding service ... === TestName: test_05_vpc_off_without_pf | Status : EXCEPTION ===
ERROR
Test VPC offering with invalid services ... === TestName: test_06_vpc_off_invalid_services | Status : SUCCESS ===
ok
Test update VPC offering ... === TestName: test_07_update_vpc_off | Status : SUCCESS ===
ok
Test list VPC offering ... === TestName: test_08_list_vpc_off | Status : SUCCESS ===
ok
test_09_create_redundant_vpc_offering (integration.component.test_vpc_offerings.TestVPCOffering) ... === TestName: test_09_create_redundant_vpc_offering | Status : SUCCESS ===
ok
Test start/stop of router after addition of one guest network ... === TestName: test_01_start_stop_router_after_addition_of_one_guest_network | Status : SUCCESS ===
ok
Test reboot of router after addition of one guest network ... === TestName: test_02_reboot_router_after_addition_of_one_guest_network | Status : SUCCESS ===
ok
Test to change service offering of router after addition of one guest network ... === TestName: test_04_chg_srv_off_router_after_addition_of_one_guest_network | Status : SUCCESS ===
ok
Test destroy of router after addition of one guest network ... === TestName: test_05_destroy_router_after_addition_of_one_guest_network | Status : SUCCESS ===
ok
Test to stop and start router after creation of VPC ... === TestName: test_01_stop_start_router_after_creating_vpc | Status : SUCCESS ===
ok
Test to reboot the router after creating a VPC ... === TestName: test_02_reboot_router_after_creating_vpc | Status : SUCCESS ===
ok
Tests to change service offering of the Router after ... === TestName: test_04_change_service_offerring_vpc | Status : SUCCESS ===
ok
Test to destroy the router after creating a VPC ... === TestName: test_05_destroy_router_after_creating_vpc | Status : SUCCESS ===
ok
----------------------------------------------------------------------
Ran 40 tests in 7371.091s

FAILED (errors=3)
```

The 3 errors are cleanup related. Baswed on above: LGTM.

**Pull request merged**
