### PR TITLE
Add e2e tests for listing resources

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR adds e2e tests for listing resources and makes changes for simulator to use dualzone config in github actions workflow.

Recreating PR #8281 including fix from PR #8392.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan test matrix

**Comment by vishesh92** [comment]
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
the vmware version:

Smoke tests completed. 127 look OK, 1 have errors, 0 did not run
Only failed and skipped tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_02_balanced_drs_algorithm | `Failure` | 125.08 | test_cluster_drs.py

**Review by harikrishna-patnala — APPROVED** [review]
code and smoke test results LGTM

**Review by rohityadavcloud — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by vishesh92** [comment]
<b>[SF] Trillian test result (tid-9099)</b>
Environment: vmware-67u3 (x2), Advanced Networking with Mgmt server r8
Total time taken: 51455 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr8410-t9099-vmware-67u3.zip
Smoke tests completed. 129 look OK, 0 have errors, 0 did not run
Only failed and skipped tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Pull request merged**
