### PR TITLE
vpc/server: Fix network statistics for vpc

### PR DESCRIPTION
**Pull request by ustcweizhou**
# Description

This contains 3 main changes
(1) add NETWORK_STATS_ethX for all nics with public ips in VPC VRs (current: NETWORK_STATS_eth1)
(2) DO NOT create records in user_statistics for each VPC tier (only one record per public nic per VPC VR)
(3) send NetworkUsageCommand before unplugging a NIC with public IPs from VPC VR

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by rhtyd** [comment]
Is this in progress or ready for review @ustcweizhou ?

**Comment by weizhouapache** [comment]
> Is this in progress or ready for review @ustcweizhou ?

@rhtyd it is ready for review

travis failed, I will check it.

**Comment by DaanHoogland** [comment]
> > Is this in progress or ready for review @ustcweizhou ?
> 
> @rhtyd it is ready for review
> 
> travis failed, I will check it.

don't bother @weizhouapache those seem to be the usual log too long errors. Travis stops at 4GB or so.

**Comment by weizhouapache** [comment]
> > > Is this in progress or ready for review @ustcweizhou ?
> > 
> > 
> > @rhtyd it is ready for review
> > travis failed, I will check it.
> 
> don't bother @weizhouapache those seem to be the usual log too long errors. Travis stops at 4GB or so.

thanks @DaanHoogland for your info.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@weizhouapache @ustcweizhou can you start a discussion thread on dev ML? This needs some discussion before we can consider merging this.

**Comment by DaanHoogland** [comment]
@weizhouapache converted to draft so it is clear 4.15 is not waiting for it. please change back if you disagree

**Comment by rhtyd** [comment]
@ustcweizhou @weizhouapache can you comment/explore the cases where this could add regression for usage/billing?

**Comment by weizhouapache** [comment]
@DaanHoogland @rhtyd 
this fixes bugs in network statistics for vpc.
cloudstack should collect network statistics from the public interfaces, not from eth1 which is default public nic for vpc but there might be more public nics, not from vpc tiers.
in a word, there is not per tier billing. there are only statistics for all public interfaces in VR for isolated network and vpc, and for all nics on shared network.

**Comment by DaanHoogland** [comment]
@weizhouapache the changes seem logical to me and given your description above seem to do what you intended, but we have no testdescription and no integration tests to guarantee against regressions. I'm a bit reluctant to include this just before release. can we with just the current set of smoke tests? cc @rhtyd @sureshanaparti are there any others we could ask for testing this functionality?

**Comment by weizhouapache** [comment]
> @weizhouapache the changes seem logical to me and given your description above seem to do what you intended, but we have no testdescription and no integration tests to guarantee against regressions. I'm a bit reluctant to include this just before release. can we with just the current set of smoke tests? cc @rhtyd @sureshanaparti are there any others we could ask for testing this functionality?

@DaanHoogland let's move this to 4.15.1.0 (and 4.14.1.0)

**Comment by shwstppr** [comment]
@weizhouapache conflicts here

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@rhtyd @weizhouapache no discussion has happened, do we dare merge this?

**Comment by weizhouapache** [comment]
> @rhtyd @weizhouapache no discussion has happened, do we dare merge this?

@DaanHoogland @rhtyd 
it is ok for me to merge it :-D

we have this patch on our productions. looks good until now.

**Review by DaanHoogland — APPROVED** [review]

**Review by rhtyd — APPROVED** [review]
Proxying my lgtm based on Daan's and Wei's comments/review.

**Pull request merged**
