### PR TITLE
ui: don't skip if dataview has multiple items in response

### PR DESCRIPTION
**Pull request by rohityadavcloud**
This would fix the case of multiple items return in API response for a resource such as a template or ISO in case of multi-zone env.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by rohityadavcloud** [comment]
@blueorangutan ui

**Review by weizhouapache — APPROVED** [review]
Verified OK on an environment with 2 zones

**Comment by nvazquez** [comment]
@rohityadavcloud could this fix cause regressions on PR https://github.com/apache/cloudstack/pull/7846 which introduced the check?

**Comment by rohityadavcloud** [comment]
@nvazquez yes we need to regression test, but I think this code wasn't that useful in the first place; was put in as an additional check. We should check for #7846

**Review by shwstppr — APPROVED** [review]
code lgtm

**Comment by rohityadavcloud** [comment]
I've tested for https://github.com/apache/cloudstack/pull/7846 and can't reproduce the issue with this fix, I think this PR should address @rajujith 's issue and not cause further regression. Thank @rajujith @weizhouapache for reporting.
/cc @weizhouapache @nvazquez

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Review by nvazquez — APPROVED** [review]
Thanks @rohityadavcloud - LGTM

**Comment by weizhouapache** [comment]
Reproduced the issue and verified it is fixed by this PR.

Without this PR
image


With this PR
image

**Review by rajujith — COMMENTED** [review]
The issue is no longer observed in environments with 2 zones.

**Pull request merged**
