### PR TITLE
UI: Removed redundant IP Address Column

### PR DESCRIPTION
**Pull request by OlegChuev**
### Description

This PR removes redundant IP Address column

Link to the issue: https://github.com/apache/cloudstack/issues/8273 

### Types of changes

- [X] Enhancement (improves an existing feature and functionality)

#### Feature/Enhancement Scale

- [X] Minor

#### Bug Severity

- [X] Trivial

### Screenshots (if appropriate):

Before fix:
Screenshot 2023-11-27 at 19 01 34

After fix:
Screenshot 2023-11-28 at 11 34 52

### CODE REVIEW

**Comment by DaanHoogland** [comment]
code looks good, but I am not sure if an operator wouldn´t want to see the ip during configuration of the pf rules. If it is not available though , ... It seems strange and may be a bug.

**Comment by weizhouapache** [comment]
> code looks good, but I am not sure if an operator wouldn´t want to see the ip during configuration of the pf rules. If it is not available though , ... It seems strange and may be a bug.

the IP is displayed when a VM is choosed.
now the view is almost same as the view when adding load balancing rules (IPs are not displayed in the list)

**Comment by DaanHoogland** [comment]
@blueorangutan ui

**Comment by DaanHoogland** [comment]
@weizhouapache @OlegChuev should this go on the 4.18 branch?

**Comment by OlegChuev** [comment]
> should this go on the 4.18 branch?

yep, sorry, I missed it. I'll change the target branch

**Comment by DaanHoogland** [comment]
@blueorangutan ui

**Pull request merged**
