### PR TITLE
Display proper names in error message

### PR DESCRIPTION
**Pull request by ravening**
### Description

Display the proper account and other names rather than the
uuid representation of the object

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [X] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [X] Trivial

### Screenshots (if appropriate):

```
Error: (HTTP 531, error code 4365) Account testuser does not have permission to launch instances from template testubuntu
```

### CODE REVIEW

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Review by GabrielBrascher — APPROVED** [review]
Code LGTM. My only suggestion would be to adopt [String.format](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Formatter.html) to help with future maintenance of the Strings.

**Review by GutoVeronezi — APPROVED** [review]
CLGTM, +1 on @GabrielBrascher's comment.

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
Merging based on travis pass.

**Pull request merged**
