### PR TITLE
Default value of force should be false for template delete operation

### PR DESCRIPTION
**Pull request by harikrishna-patnala**
### Description

Default value of force should be false for the template delete operation

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@harikrishna-patnala can you have a look if it does make sense for the test_templates tests to now fail?

**Comment by harikrishna-patnala** [comment]
yes @DaanHoogland it seems to be related. 
\'Unable to delete template with id: 267 because VM instances: [VM instance {"id":205,"instanceName":"i-119-205-VM","type":"User","uuid":"810e3e54-aeb1-444d-bb9b-9b224df2bd08"}] are using it.\'

I'll fix the tests too

**Comment by weizhouapache** [comment]
this parameter was introduced in PR #1773

changing the default value to `false` makes sense. However, it will break backwards compatibility.
once this is merged, we need to add a note to to release note (e.g. in `Breaking changes` section)

**Review by shwstppr — APPROVED** [review]
Code LGTM

**Comment by weizhouapache** [comment]
a similar issue:
due to a new flag introduced by https://github.com/apache/cloudstack/pull/4617, 
ansible needs to be updated: https://github.com/ngine-io/ansible-collection-cloudstack/pull/122

**Review by kiranchavala — APPROVED** [review]
LGTM , tested manually with the api call 

Also tested with project 

Before the fix 


`
2023-08-02 10:25:41,346 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (qtp1239807799-18:ctx-6c52ee9f ctx-71da430f ctx-dbb08cbb) (logid:2828153a) submit async job-113, details: AsyncJobVO: {id:113, userId: 2, accountId: 2, instanceType: Template, instanceId: 215, cmd: org.apache.cloudstack.api.command.user.template.DeleteTemplateCmd, cmdInfo: {"apiKey":"LIN6rqXuaJwMPfGYFh13qDwYz5VNNz1J2J6qIOWcd3oLQOq0WtD4CwRundBL6rzXToa3lQOC_vKjI3nkHtiD8Q","signature":"YiZXnlLsEqPiSiiMrEBLTiSJAlo\u003d","response":"json","ctxUserId":"2","httpmethod":"GET","ctxStartEventId":"267","id":"44bb4d22-c43c-4ce5-a9c0-fcf61aeb1775","ctxDetails":"{\"interface com.cloud.template.VirtualMachineTemplate\":\"44bb4d22-c43c-4ce5-a9c0-fcf61aeb1775\"}","ctxAccountId":"2","uuid":"44bb4d22-c43c-4ce5-a9c0-fcf61aeb1775","cmdEventType":"TEMPLATE.DELETE"}, cmdVersion: 0, status: IN_PROGRESS, processStatus: 0, resultCode: 0, result: null, initMsid: 32986556793923, completeMsid: null, lastUpdated: null, lastPolled: null, created: null, removed: null}
`



After the fix 

```

2023-08-02 10:21:24,306 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-41:ctx-f860df56 job-73) (logid:1cb54178) Executing AsyncJobVO: {id:73, userId: 2, accountId: 2, instanceType: Template, instanceId: 205, cmd: org.apache.cloudstack.api.command.user.template.DeleteTemplateCmd, cmdInfo: {"apiKey":"LIN6rqXuaJwMPfGYFh13qDwYz5VNNz1J2J6qIOWcd3oLQOq0WtD4CwRundBL6rzXToa3lQOC_vKjI3nkHtiD8Q","signature":"bdb7Zdkui9CZUoFAr7RMvEoIpm8\u003d","response":"json","ctxUserId":"2","httpmethod":"GET","ctxStartEventId":"161","id":"2bc0c528-55f8-4860-9b00-8f1b0f2acff8","ctxDetails":"{\"interface com.cloud.template.VirtualMachineTemplate\":\"2bc0c528-55f8-4860-9b00-8f1b0f2acff8\"}","ctxAccountId":"2","uuid":"2bc0c528-55f8-4860-9b00-8f1b0f2acff8","cmdEventType":"TEMPLATE.DELETE"}, cmdVersion: 0, status: IN_PROGRESS, processStatus: 0, resultCode: 0, result: null, initMsid: 32988351955670, completeMsid: null, lastUpdated: null, lastPolled: null, created: null, removed: null}

2023-08-02 10:21:24,306 DEBUG [c.c.a.ApiServlet] (qtp1239807799-13:ctx-a0ba720f ctx-e324f833 ctx-89287e07) (logid:9ba795bc) ===END===  10.0.3.251 -- GET  apiKey=LIN6rqXuaJwMPfGYFh13qDwYz5VNNz1J2J6qIOWcd3oLQOq0WtD4CwRundBL6rzXToa3lQOC_vKjI3nkHtiD8Q&command=deleteTemplate&id=2bc0c528-55f8-4860-9b00-8f1b0f2acff8&response=json&signature=bdb7Zdkui9CZUoFAr7RMvEoIpm8%3D

2023-08-02 10:21:24,315 WARN  [c.c.t.TemplateManagerImpl] (API-Job-Executor-41:ctx-f860df56 job-73 ctx-89c8cbb6) (logid:1cb54178) Unable to delete template with id: 205 because VM instances: [VM instance {"id":8,"instanceName":"i-2-8-VM","type":"User","uuid":"3dbd61ea-6608-4bf7-9144-ac510eec8358"}] are using it.

2023-08-02 10:21:24,320 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-41:ctx-f860df56 job-73) (logid:1cb54178) Complete async job-73, jobStatus: FAILED, resultCode: 431, result: org.apache.cloudstack.api.response.ExceptionResponse/null/{"uuidList":[],"errorcode":"431","errortext":"Unable to delete template with id: 205 because VM instances: [VM instance {"id":8,"instanceName":"i-2-8-VM","type":"User","uuid":"3dbd61ea-6608-4bf7-9144-ac510eec8358"}] are using it."
```

**Comment by weizhouapache** [comment]
@rohityadavcloud @harikrishna-patnala @DaanHoogland @shwstppr @kiranchavala 
what should we proceed with this PR ?
it looks I am the only one disagree to merge this.

**Comment by weizhouapache** [comment]
moved to 4.18.2.0 milestone

**Review by rohityadavcloud — APPROVED** [review]
LGTM didn't test it

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Comment by harikrishna-patnala** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@harikrishna-patnala any resolution on this? cc @shwstppr

**Comment by DaanHoogland** [comment]
> this parameter was introduced in PR #1773
> 
> changing the default value to `false` makes sense. However, it will break backwards compatibility. once this is merged, we need to add a note to to release note (e.g. in `Breaking changes` section)

@shwstppr , I think we can merge this if we take @weizhouapache 's remark into account. What do you think?

**Comment by shwstppr** [comment]
@DaanHoogland I'm okay to merge this.
@harikrishna-patnala if you're okay please take this out of draft

**Comment by harikrishna-patnala** [comment]
> @DaanHoogland I'm okay to merge this. @harikrishna-patnala if you're okay please take this out of draft

yes @DaanHoogland This can be merged cc @shwstppr

**Comment by DaanHoogland** [comment]
@harikrishna-patnala 
can you add a doc PR for this please?

**Comment by harikrishna-patnala** [comment]
@DaanHoogland I get that I'm breaking backward compatibility, in my opinion documenting this is not needed as we are not breaking anything that is correct or expected behaviour by someone. On the other hand I also dont know where exactly to document this if you can suggest that helps please.

**Comment by DaanHoogland** [comment]
as @weizhouapache sugested, it should be in the release notes in the breaking changes section. humans may expect this , but tools like ansible and terraform will not.

**Comment by harikrishna-patnala** [comment]
ah we have a breaking changes section, nice. Thanks @DaanHoogland I'll create one.

**Pull request merged**
