### PR TITLE
packaging: fix centos8/el8 upgrade

### LINKED ISSUE #7258: KVM: Cannot recreate system VMs after upgrade from 4.17.1.0 to 4.18.0
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
System VMs
~~~

##### CLOUDSTACK VERSION

~~~
4.18.0
~~~

##### OS / ENVIRONMENT

on management and agents: Rocky Linux VERSION="8.4 (Green Obsidian)"

##### SUMMARY

After the upgrade from 4.17.1.0 to 4.18 RC1 cannot recreate the SSVM/CPVM

> 2023-02-17 19:35:41,461 WARN  [resource.wrapper.LibvirtStartCommandWrapper] (agentRequest-Handler-5:null) (logid:d27dcb39) LibvirtException 
> org.libvirt.LibvirtException: Hook script execution failed: internal error: Child process (LC_ALL=C PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin /etc/libvirt/hooks/qemu v-17171-VM prepare begin -) unexpected exit status 1: Traceback (most recent call last):
>   File "/etc/libvirt/hooks/qemu", line 24, in <module>
>     from cloudutils.configFileOps import configFileOps
> ModuleNotFoundError: No module named 'cloudutils'
> 
>         at org.libvirt.ErrorHandler.processError(Unknown Source)
>         at org.libvirt.ErrorHandler.processError(Unknown Source)
>         at org.libvirt.Connect.domainCreateXML(Unknown Source

##### STEPS TO REPRODUCE

~~~
Following the procedure for the Upgrade of CloudStack
~~~

##### EXPECTED RESULTS

~~~
Successful system VMs deployment
~~~

##### ACTUAL RESULTS

~~~
ModuleNotFoundError: No module named 'cloudutils'
~~~

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #7258 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [X] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by shwstppr — COMMENTED** [review]
Tested upgrade from 4.17 to this PR's packages. System VMs are recreated fine but while trying to console it displays window with `failed` message. Not sure if related or a different issue

**Comment by DaanHoogland** [comment]
> Tested upgrade from 4.17 to this PR's packages. System VMs are recreated fine but while trying to console it displays window with `failed` message. Not sure if related or a different issue

@shwstppr what system di you do your upgrade on? (MS and host)

**Comment by shwstppr** [comment]
@weizhouapache yes recreated them. And I can see they are deployed with the new systemvm template. Investigating further

**Comment by shwstppr** [comment]
@weizhouapache ignore that console error.
It seemed to be a browser cache issue with UI. Works after a hard refresh on browser.

Upgrade working fine now

**Review by shwstppr — APPROVED** [review]
tested 4.17 to this PR's packages, systemvms working fine.

```
[root@ref-trl-4516-k-Mr8-abhishek-kumar-mgmt1 ~]# hostnamectl
   Static hostname: n/a
Transient hostname: ref-trl-4516-k-Mr8-abhishek-kumar-mgmt1
         Icon name: computer-vm
           Chassis: vm
        Machine ID: ec2f5af8e2a348e686bd75385747ee42
           Boot ID: 0ca98fd36958448385c2ee09c3c0d9aa
    Virtualization: vmware
  Operating System: Rocky Linux 8.4 (Green Obsidian)
       CPE OS Name: cpe:/o:rocky:rocky:8.4:GA
            Kernel: Linux 4.18.0-305.3.1.el8_4.x86_64
      Architecture: x86-64
[root@ref-trl-4516-k-Mr8-abhishek-kumar-mgmt1 ~]# yum info cloudstack-management
Last metadata expiration check: 0:32:49 ago on Tue 21 Feb 2023 09:41:48 AM UTC.
Installed Packages
Name         : cloudstack-management
Version      : 4.18.0.0
Release      : shapeblue6633
Architecture : x86_64
Size         : 1.4 G
Source       : cloudstack-4.18.0.0-shapeblue6633.src.rpm
Repository   : @System
From repo    : cloudstack
Summary      : CloudStack management server UI
License      : ASL 2.0
Description  : The CloudStack management server is the central point of coordination,
             : management, and intelligence in CloudStack.

[root@ref-trl-4516-k-Mr8-abhishek-kumar-mgmt1 ~]# cmk
Apache CloudStack 🐵 CloudMonkey 6.2.0
Report issues: https://github.com/apache/cloudstack-cloudmonkey/issues

(localcloud) 🐱 > list systemvms 
{
  "count": 2,
  "systemvm": [
    {
      "agentstate": "Up",
      "created": "2023-02-21T09:47:01+0000",
      "dns1": "10.0.32.1",
      "dns2": "8.8.8.8",
      "gateway": "10.0.48.1",
      "hasannotations": false,
      "hostcontrolstate": "Enabled",
      "hostid": "71a1bc6f-d827-45a5-a181-bb851e46d5d4",
      "hostname": "ref-trl-4516-k-Mr8-abhishek-kumar-kvm1",
      "hypervisor": "KVM",
      "id": "fa6c688e-a132-47bc-8c39-6c43087df719",
      "isdynamicallyscalable": false,
      "linklocalip": "169.254.248.38",
      "linklocalmacaddress": "0e:00:a9:fe:f8:26",
      "linklocalnetmask": "255.255.0.0",
      "name": "s-3-VM",
      "podid": "fcde252f-59fb-4c9d-8a52-dffce40192ee",
      "podname": "Pod1",
      "privateip": "10.0.43.132",
      "privatemacaddress": "1e:00:cb:00:00:20",
      "privatenetmask": "255.255.240.0",
      "publicip": "10.0.59.81",
      "publicmacaddress": "1e:00:84:00:00:01",
      "publicnetmask": "255.255.240.0",
      "state": "Running",
      "systemvmtype": "secondarystoragevm",
      "templateid": "43e29fb1-73ad-423f-b4b0-c71544b892c3",
      "templatename": "systemvm-kvm-4.18.0",
      "version": "4.18.0.0-SNAPSHOT",
      "zoneid": "6d26c7d1-aeeb-4a52-9e80-d53a4526cc54",
      "zonename": "ref-trl-4516-k-Mr8-abhishek-kumar"
    },
    {
      "activeviewersessions": 0,
      "agentstate": "Up",
      "created": "2023-02-21T09:47:01+0000",
      "dns1": "10.0.32.1",
      "dns2": "8.8.8.8",
      "gateway": "10.0.48.1",
      "hasannotations": false,
      "hostcontrolstate": "Enabled",
      "hostid": "71a1bc6f-d827-45a5-a181-bb851e46d5d4",
      "hostname": "ref-trl-4516-k-Mr8-abhishek-kumar-kvm1",
      "hypervisor": "KVM",
      "id": "c201fada-aeba-4724-b2af-7d0c13d86be8",
      "isdynamicallyscalable": false,
      "linklocalip": "169.254.45.117",
      "linklocalmacaddress": "0e:00:a9:fe:2d:75",
      "linklocalnetmask": "255.255.0.0",
      "name": "v-4-VM",
      "podid": "fcde252f-59fb-4c9d-8a52-dffce40192ee",
      "podname": "Pod1",
      "privateip": "10.0.43.123",
      "privatemacaddress": "1e:00:7a:00:00:17",
      "privatenetmask": "255.255.240.0",
      "publicip": "10.0.59.82",
      "publicmacaddress": "1e:00:20:00:00:02",
      "publicnetmask": "255.255.240.0",
      "state": "Running",
      "systemvmtype": "consoleproxy",
      "templateid": "43e29fb1-73ad-423f-b4b0-c71544b892c3",
      "templatename": "systemvm-kvm-4.18.0",
      "version": "4.18.0.0-SNAPSHOT",
      "zoneid": "6d26c7d1-aeeb-4a52-9e80-d53a4526cc54",
      "zonename": "ref-trl-4516-k-Mr8-abhishek-kumar"
    }
  ]
}
```

**Review by DaanHoogland — APPROVED** [review]
clgtm tested on rocky (as well)

**Pull request merged**
