### PR TITLE
Allow port 80/8080 accessible only from guest network

### PR DESCRIPTION
**Pull request by ravening**
# Description

The port 80/8080 in the vr of the guest network is accessible from
outisde the world. Restrict it so that only the vm's in the guest
network can access them

Before fix

$ nc -vz 10.11.118.172 8080
Connection to 10.11.118.172 port 8080 [tcp/http] succeeded!

After fix
$ nc -vz 10.11.118.172 8080
^C

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by rhtyd** [comment]
In case of SSVM we may want port 80 connectivity to be able to download templates/isos/volumes.
@ravening can you check if you change adds regression for SSVM?

@blueorangutan package

**Comment by weizhouapache** [comment]
@rhtyd this PR adds a rule only in method fw_vpcrouter and fw_router. ssvm should not be impacted.

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
Thanks @weizhouapache - have you tested this in your env?

**Comment by weizhouapache** [comment]
> Thanks @weizhouapache - have you tested this in your env?

@rhtyd yes, we have used this change in production for 3 years.

**Pull request merged**
