### PR TITLE
Bug/unmanaged ingest exceptions #4539

### PR DESCRIPTION
**Pull request by DK101010**
### Description

This PR...

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

manually testet

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Review by shwstppr — APPROVED** [review]
LGTM on code changes.

**Comment by DaanHoogland** [comment]
@DK101010 can you explain why #1 is on the commits listr for this PR?

**Comment by DK101010** [comment]
@DaanHoogland I had updated my fork with the apache/cloudstack master over the GitHub Web interface. For this I had to created a pull request in my fork.... mmmh is that wrong ?

**Comment by DaanHoogland** [comment]
> @DaanHoogland I had updated my fork with the apache/cloudstack master over the GitHub Web interface. For this I had to created a pull request in my fork.... mmmh is that wrong ?

It is a red flag to me, but i think we'll squash and merge this anyway, so it won't polute our master branch in the end. don't worry.

**Comment by DK101010** [comment]
> > @DaanHoogland I had updated my fork with the apache/cloudstack master over the GitHub Web interface. For this I had to created a pull request in my fork.... mmmh is that wrong ?
> 
> It is a red flag to me, but i think we'll squash and merge this anyway, so it won't polute our master branch in the end. don't worry.

@DaanHoogland Hmmm ... but how would be looks like right? Not quite sure what should I change in the future.

**Comment by DaanHoogland** [comment]
> > > @DaanHoogland I had updated my fork with the apache/cloudstack master over the GitHub Web interface. For this I had to created a pull request in my fork.... mmmh is that wrong ?
> > 
> > 
> > It is a red flag to me, but i think we'll squash and merge this anyway, so it won't polute our master branch in the end. don't worry.
> 
> @DaanHoogland Hmmm ... but how would be looks like right? Not quite sure what should I change in the future.

_*I think*_, you would need to branch of master and then base your code on that, or cherry-pick it on it.
$ git checkout master
$ git pull
$ git checkout -b <new-branch>
$ git cherry-pick <relevant-commit>

or

$ git checkout master
$ git pull
$ git checkout <old-branch>
$ git rebase -i master

not sure what happened with you but it looks like you merged an ancient commit. I doubt if that would have done anything for you.

**Comment by DK101010** [comment]
> > > > @DaanHoogland I had updated my fork with the apache/cloudstack master over the GitHub Web interface. For this I had to created a pull request in my fork.... mmmh is that wrong ?
> > > 
> > > 
> > > It is a red flag to me, but i think we'll squash and merge this anyway, so it won't polute our master branch in the end. don't worry.
> > 
> > 
> > @DaanHoogland Hmmm ... but how would be looks like right? Not quite sure what should I change in the future.
> 
> __I think__, you would need to branch of master and then base your code on that, or cherry-pick it on it.
> $ git checkout master
> $ git pull
> $ git checkout -b
> $ git cherry-pick
> 
> or
> 
> $ git checkout master
> $ git pull
> $ git checkout
> $ git rebase -i master
> 
> not sure what happened with you but it looks like you merged an ancient commit. I doubt if that would have done anything for you.

Could it be that you work with the apache/cloudstack master without forking?

**Comment by DK101010** [comment]
> > > not sure what happened with you but it looks like you merged an ancient commit. I doubt if that would have done anything for you.
> > 
> > 
> > Could it be that you work with the apache/cloudstack master without forking?
> 
> I work with several forks. I have my private that I rarely use and only in free time. my company one, some clients and some conculeagues/friends. 12 in total. mine was forked originaly, but on whatever i work, I start with pulling master from the origin and than proceed with `git checkout -b <branchname>`. it always does the trick.

I think I understood. your git remote address pointed to apache/cloudstack and your upstream to your fork correct?

**Comment by DaanHoogland** [comment]
> > > > not sure what happened with you but it looks like you merged an ancient commit. I doubt if that would have done anything for you.
> > > 
> > > 
> > > Could it be that you work with the apache/cloudstack master without forking?
> > 
> > 
> > I work with several forks. I have my private that I rarely use and only in free time. my company one, some clients and some conculeagues/friends. 12 in total. mine was forked originaly, but on whatever i work, I start with pulling master from the origin and than proceed with `git checkout -b <branchname>`. it always does the trick.
> 
> I think I understood. your git remote address pointed to apache/cloudstack and your upstream to your fork correct?

Well, i think you do but in my words:
for master the upstream alias is origin and points to apache/cloudstack and
for the branch i work in i let the remote be for instance my personal fork.

**Review by davidjumani — APPROVED** [review]
Code LGTM

**Comment by rhtyd** [comment]
@blueorangutan test

**Pull request merged**
