### PR TITLE
server,test: fix resourceid for VOLUME.DESTROY in restore VM

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Destroys old ROOT volume for the VM to be restored in its own context to allow event to be published with resourceid. Fixes exception in test_event_resources.py
Fixes failures seen in:
https://github.com/apache/cloudstack/pull/8601#issuecomment-2078654228
https://github.com/apache/cloudstack/pull/8601#issuecomment-2079018980
https://github.com/apache/cloudstack/pull/8601#issuecomment-2079141241

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Comment by shwstppr** [comment]
Failed tests are unrelated, https://github.com/apache/cloudstack/pull/8601#issuecomment-2091938578

**Review by vishesh92 — APPROVED** [review]
clgtm

**Review by DaanHoogland — APPROVED** [review]

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan test

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan test

**Pull request merged**
