### PR TITLE
Make text clear regarding removing data disks.

### PR DESCRIPTION
**Pull request by PaulAngus**
## Description

Alter English text to make it clear that the volumes listed (or not) are data volumes

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

Previous:

New:
image

image

### CODE REVIEW

**Comment by PaulAngus** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
packaging works, textual and UI only, merging...

**Comment by weizhouapache** [comment]
how about 4.13 ?

**Comment by DaanHoogland** [comment]
I think this is a fix for a feature not in 4.13, @weizhouapache .
cc @PaulAngus ?

**Pull request merged**
