### PR TITLE
make sure no time skew can interfere with comparison

### PR DESCRIPTION
**Pull request by DaanHoogland**
## Description

see titel

## Types of changes

Test fix

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@bwsw @nvazquez have a look

**Comment by bwsw** [comment]
@DaanHoogland LGTM, but I'm not a skilled java developer. Don't rely on my review.

**Comment by DaanHoogland** [comment]
I'll take that as 👍 😉

**Comment by rafaelweingartner** [comment]
@DaanHoogland just one remark. What about removing that `main` method there?

**Comment by DaanHoogland** [comment]
makes sense, if the cantants is covoured. I didn't give that any attention @rafaelweingartner

**Comment by DaanHoogland** [comment]
Do we need full regression tests?
@blueorangutan package

**Comment by rafaelweingartner** [comment]
@DaanHoogland I do not think so.

**Pull request merged**
