### PR TITLE
server: clear resource reservation and increment resource count in a transaction

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

This PR addresses rare cases of potential overlap of resource reservation and resource count. For different resource types there could be some delay between incrementing of the resource count and clearing of the earlier done reservation. This may result in failures when there are parallel deployments happening.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
code looks good but can you put the transaction in a separate method and not in with the precondition checks, please.

**Comment by shwstppr** [comment]
@DaanHoogland refactored

@blueorangutan package

**Review by harikrishna-patnala — APPROVED** [review]
I hit this issue too. Thanks @shwstppr 
Code LGTM

**Comment by shwstppr** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Pull request merged**
