### PR TITLE
Refactor userVmDetailsDao field and remove unusued fields

### PR DESCRIPTION
**Pull request by dhlaluku**
## Description

This PR refactors a duplicated field vmDetailsDao and _uservmDetailsDao into userVmDetailsDao.
vmDetailsDao, uservmDetailsDao --> userVmDetailsDao

It also removes several unused injected vars as well i.e.;
_domainDao, rulesMgr, _vguTypesDao, _configDepot

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?
I have recompiled CloudStack in my local environment and ran the virtual machine related Marvin smoke tests.

## Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
Testing
- [ ] I have added tests to cover my changes.
- [ ] All relevant new and existing integration tests have passed.
- [ ] A full integration testsuite with all test that can run on my environment has passed.

### CODE REVIEW

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by dhlaluku** [comment]
@DaanHoogland @rafaelweingartner @resmo @marcaurele I am new to this community and I would like to ask for your assistance with reviewing of this PR.

**Comment by dhlaluku** [comment]
@blueorangutan package

**Comment by dhlaluku** [comment]
@rafaelweingartner checked the attributes, it seems like they can be set to private. I will modify them and do some tests before pushing again

**Comment by dhlaluku** [comment]
@blueorangutan package

**Comment by dhlaluku** [comment]
@blueorangutan test

**Pull request merged**
