### PR TITLE
pre-commit: enable `markdownlint` rule `MD018`

### PR DESCRIPTION
**Pull request by jbampton**
https://github.com/DavidAnson/markdownlint/blob/main/doc/md018.md

### Description

This PR adds another check for our Markdown linter. 

MD018/no-missing-space-atx No space after hash on atx style heading.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [X] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

Ran locally:

`pre-commit run --all-files`

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]

**Comment by jbampton** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]

**Comment by jbampton** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Review by vishesh92 — APPROVED** [review]
lgtm

**Comment by DaanHoogland** [comment]
@JoaoJandre , can we merge these linting changes (mostly by @jbampton ) during freeze? I don't think any of them have code changes. At least this one hasn't .

**Comment by JoaoJandre** [comment]
> @JoaoJandre , can we merge these linting changes (mostly by @jbampton ) during freeze? I don't think any of them have code changes. At least this one hasn't .

@DaanHoogland I don't see why we would merge them during a freeze. Although they generally do not pose any risks (at least this one doesn't), they are also not really high priority, are they? I see no problem in waiting until we release to merge these.

**Comment by jbampton** [comment]
@blueorangutan package

**Comment by jbampton** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Pull request merged**
