### PR TITLE
remove constant unexplained failures that don´t seem to fail

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR disables the SuperLinter which always claims there are failures even if there is nothing to report.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### CODE REVIEW

**Review by GabrielBrascher — APPROVED** [review]
LGTM

**Comment by rohityadavcloud** [comment]
With https://github.com/apache/cloudstack/pull/6531 this may not be needed if the lint is fixed, if we think it's not necessary (as travis does some lint checks too?) let's remove this indeed.

**Comment by DaanHoogland** [comment]
@jbampton can you comment please? i lost track of our pre-commit track record.

**Comment by rohityadavcloud** [comment]
Travis lint checks are somehow quicker and only done via job #1 which only does build related checks (doesn't run more than one simple smoketests). Job #1 is usually fastest among rest of the jobs.

**Pull request closed without merging**
