### PR TITLE
UI - Fix Locked "Override Root Disk Size" switch

### PR DESCRIPTION
**Pull request by utchoang**
### Description

This PR fixes https://github.com/apache/cloudstack/issues/5842

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### Screenshots (if appropriate):
Fixes error found when entering the "Add Instances" page
image

Fixes root disk size switch being locked when changing offerings
image
image

### CODE REVIEW

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by sureshanaparti** [comment]
@blueorangutan ui

**Comment by DaanHoogland** [comment]
@blueorangutan ui

**Review by GabrielBrascher — APPROVED** [review]
Thanks for the PR @utchoang!
LGTM, based on manual tests and code review.

**Review by sureshanaparti — APPROVED** [review]
Verified 'Override Root Disk Size' toggle in New instance wizard, with different compute offerings.

**Pull request merged**
