### PR TITLE
CLOUDSTACK-8977: remove session creation from index.jsp

### PR DESCRIPTION
**Pull request by K0zka**
Signed-off-by: Laszlo Hornyak <laszlo.hornyak@gmail.com>

### CODE REVIEW

**Comment by DaanHoogland** [comment]
makes sense. lgtm . testing in batch with other ui fixes? It is rather small but not trivial and should be verified.

**Comment by K0zka** [comment]
Hi Daan,

I have verified the result with curl -v, therefore manual verification. It would be nice to have automatic test to verify that unauthenticated users can not create session in CS whatever they do. One should get a session with login only.

**Comment by borisroman** [comment]
Verified with curl -v => LGTM :+1: 

Before:

```
[root@cs1 cloudstack]# curl -v 192.168.22.61:8080/client/
* About to connect() to 192.168.22.61 port 8080 (#0)
*   Trying 192.168.22.61...
* Connected to 192.168.22.61 (192.168.22.61) port 8080 (#0)
> GET /client/ HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 192.168.22.61:8080
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: text/html; charset=utf-8
< Expires: Thu, 01-Jan-1970 00:00:00 GMT
< Set-Cookie: JSESSIONID=s17fnbszvqyz1t9vgieqevtog;Path=/client
< Transfer-Encoding: chunked
< Server: Jetty(6.1.26)
< 
```

After:
```
[root@cs1 cloudstack]# curl -v 192.168.22.61:8080/client/
* About to connect() to 192.168.22.61 port 8080 (#0)
*   Trying 192.168.22.61...
* Connected to 192.168.22.61 (192.168.22.61) port 8080 (#0)
> GET /client/ HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 192.168.22.61:8080
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: text/html; charset=utf-8
< Expires: Thu, 01-Jan-1970 00:00:00 GMT
< Transfer-Encoding: chunked
< Server: Jetty(6.1.26)
< 
```

Ping @remibergsma

**Comment by remibergsma** [comment]
LGTM, I also see the sessionid no longer there:


```
[root@cs2 cloudstack]# curl -v 192.168.22.62:8080/client/ >/dev/null
* About to connect() to 192.168.22.62 port 8080 (#0)
*   Trying 192.168.22.62...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 192.168.22.62 (192.168.22.62) port 8080 (#0)
> GET /client/ HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 192.168.22.62:8080
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: text/html; charset=utf-8
< Transfer-Encoding: chunked
< Server: Jetty(6.1.26)
< 
{ [data not shown]
100  225k    0  225k    0     0  7769k      0 --:--:-- --:--:-- --:--:-- 8047k
* Connection #0 to host 192.168.22.62 left intact
```

Also important, I can still login properly and it all works as expected:
screen shot 2015-10-24 at 19 02 21

**Comment by remibergsma** [comment]
Thanks for the fix @K0zka !

**Comment by ustcweizhou** [comment]
guys, CS UI is broken by this commit on my env.
I am using Chrome (Version 46.0.2490.80 m)
It works after reverting this commit.

**Comment by K0zka** [comment]
@ustcweizhou could you share some details about the problem? Are you not able to login?

**Comment by ustcweizhou** [comment]
@K0zka the page is blank. I tried sometimes with the same result (blank page with this commit, works without this commit).

**Comment by K0zka** [comment]
@ustcweizhou thats exciting... can you share any log, errormessage, configuration, etc? What http status do you get?

**Comment by ustcweizhou** [comment]
@K0zka there is no related log, no error message... I tried on CentOS/Ubuntu/Win7 Firefox/Chome, all did not work until revert the commit... weird...
anyone has same issue ?

**Comment by K0zka** [comment]
@ustcweizhou 
* could you try to clear the tomcat work directory?
* could you check the service with ```curl -v <serviceurl> -o /dev/null```

**Comment by borisroman** [comment]
@ustcweizhou I'm not experiencing any problems...

**Comment by karuturi** [comment]
@K0zka I have the same issue as @ustcweizhou no log, no error message. Just a blank page
environment: management server running on centos 6.6 and tomcat tomcat6-el-2.1-api-6.0.24-49.el6.noarch

**Comment by ustcweizhou** [comment]
@K0zka 

(1) not working:
```
[root@weizhou master]# curl -v 10.11.115.10:8080/client/ -o /dev/null
* About to connect() to 10.11.115.10 port 8080 (#0)
*   Trying 10.11.115.10... connected
* Connected to 10.11.115.10 (10.11.115.10) port 8080 (#0)
> GET /client/ HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.14.0.0 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: 10.11.115.10:8080
> Accept: */*
>
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0< HTTP/1.1 200 OK
< Server: Apache-Coyote/1.1
< Content-Type: text/html;charset=UTF-8
< Transfer-Encoding: chunked
< Date: Wed, 28 Oct 2015 08:00:06 GMT
<
{ [data not shown]
100  105k    0  105k    0     0  2353k      0 --:--:-- --:--:-- --:--:-- 6193k* Connection #0 to host 10.11.115.10 left intact

* Closing connection #0

```
(2) working:
```
[root@weizhou master]# curl -v 10.11.115.10:8080/client/ -o /dev/null
* About to connect() to 10.11.115.10 port 8080 (#0)
*   Trying 10.11.115.10... connected
* Connected to 10.11.115.10 (10.11.115.10) port 8080 (#0)
> GET /client/ HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.14.0.0 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: 10.11.115.10:8080
> Accept: */*
>
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0< HTTP/1.1 200 OK
< Server: Apache-Coyote/1.1
< Set-Cookie: JSESSIONID=E5F293179AD0BEDAF4A2746A8C41F546; Path=/client; HttpOnly
< Content-Type: text/html;charset=UTF-8
< Transfer-Encoding: chunked
< Date: Wed, 28 Oct 2015 08:00:21 GMT
<
{ [data not shown]
100  226k    0  226k    0     0   922k      0 --:--:-- --:--:-- --:--:--  933k* Connection #0 to host 10.11.115.10 left intact

* Closing connection #0
```

**Comment by ustcweizhou** [comment]
@K0zka I also cleaned the folder /var/cache/cloudstack/management/work/, it does not fix the issue.

**Comment by K0zka** [comment]
thank you for the response, then that prehistoric tomcat may not be able to compile the jsp.

Could you try if it works well with 4eb707a567663cb4da0e548281f001b27196ba3d ?

**Comment by karuturi** [comment]
Hi @k0zka are you saying it might be specific to tomcat6? Reverting the the change works fine.
 Do you think we should revert this until we find a solution which also works on tomcat6?

**Comment by ustcweizhou** [comment]
@K0zka @karuturi I am using tomcat 6 as well. agree with Rajani

**Comment by remibergsma** [comment]
@K0zka If you know of a fix for Tomcat6 we can merge that. Otherwise I think we should consider reverting. We can wait a bit but if there is no solution at the time we're about to cut a RC we better revert.

Do you guys install RPMs?

@miguelaferreira Can you please test this against Tomcat7?

**Comment by DaanHoogland** [comment]
@remibergsma  this doesn't work in tomcat7 either. We ran tests on centos7 and only half a page is loaded.

**Comment by remibergsma** [comment]
@karuturi @K0zka @ustcweizhou @DaanHoogland @miguelaferreira I just reverted the commit.

**Comment by miguelaferreira** [comment]
In tomcat I see the following errors:
```
Oct 30, 2015 9:39:13 AM org.apache.catalina.core.ApplicationDispatcher invoke
SEVERE: Servlet.service() for servlet jsp threw exception
java.lang.IllegalStateException: Cannot create a session after the response has been committed
        at org.apache.catalina.connector.Request.doGetSession(Request.java:2934)
        at org.apache.catalina.connector.Request.getSession(Request.java:2310)
        at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:897)
        at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:229)
        at org.apache.catalina.core.ApplicationHttpRequest.getSession(ApplicationHttpRequest.java:569)
        at org.apache.catalina.core.ApplicationHttpRequest.getSession(ApplicationHttpRequest.java:514)
        at org.apache.jasper.runtime.PageContextImpl._initialize(PageContextImpl.java:147)
        at org.apache.jasper.runtime.PageContextImpl.initialize(PageContextImpl.java:126)
        at org.apache.jasper.runtime.JspFactoryImpl.internalGetPageContext(JspFactoryImpl.java:112)
        at org.apache.jasper.runtime.JspFactoryImpl.getPageContext(JspFactoryImpl.java:65)
        at org.apache.jsp.dictionary_jsp._jspService(dictionary_jsp.java:66)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
        at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:604)
        at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:543)
        at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:954)
        at org.apache.jsp.index_jsp._jspService(index_jsp.java:2735)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
```

Then is cascades for several other requests:
```
Oct 30, 2015 9:39:13 AM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [jsp] in context with path [/client] threw exception [org.apache.jasper.JasperException: javax.servlet.ServletException: java.lang.IllegalStateException: Cannot create a session after the response has been committed] with root cause
java.lang.IllegalStateException: Cannot create a session after the response has been committed
        at org.apache.catalina.connector.Request.doGetSession(Request.java:2934)
        at org.apache.catalina.connector.Request.getSession(Request.java:2310)
        at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:897)
        at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:229)
        at org.apache.catalina.core.ApplicationHttpRequest.getSession(ApplicationHttpRequest.java:569)
        at org.apache.catalina.core.ApplicationHttpRequest.getSession(ApplicationHttpRequest.java:514)
        at org.apache.jasper.runtime.PageContextImpl._initialize(PageContextImpl.java:147)
        at org.apache.jasper.runtime.PageContextImpl.initialize(PageContextImpl.java:126)
        at org.apache.jasper.runtime.JspFactoryImpl.internalGetPageContext(JspFactoryImpl.java:112)
        at org.apache.jasper.runtime.JspFactoryImpl.getPageContext(JspFactoryImpl.java:65)
        at org.apache.jsp.dictionary_jsp._jspService(dictionary_jsp.java:66)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
...
```

Even the error page does not show because of it
```
Oct 30, 2015 9:39:13 AM org.apache.catalina.core.StandardHostValve custom
SEVERE: Exception Processing ErrorPage[exceptionType=java.lang.Exception, location=*/error.jsp*]
org.apache.jasper.JasperException: javax.servlet.ServletException: java.lang.IllegalStateException: Cannot create a session after the response has been committed
        at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:549)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:455)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
...
```

I'm not a web application expert, but I've looked at the code of the UI and it seems that all "pages" are defined in a single page but hidden. If that is the case, how can we disable session for one page but not for the others?

**Comment by miguelaferreira** [comment]
After digging in a bit more, I've debugged the browser session when hitting the home page with `session="false"` what I see is that the page is not even completely downloaded. My best guess is that the server stops responding when the exceptions I've posted in the previous comment happen. And because the page was not completely downloaded it is also not well rendered. In addition the script tags are at the end of the page, so none of the dynamics will work either.

Researching for similar problems took me to a stackoverflow question
http://stackoverflow.com/questions/2055502/java-lang-illegalstateexception-pwc3999-cannot-create-a-session-after-the-resp?answertab=active#tab-top

In the accepted answer, the poster explains that the exception (which is the same as I see, "Cannot create a session after the response has been committed") has to do with trying to write to a response that has be already committed (i.e. already sent to the client). The poster also mentions that the response is automatically flushed (i.e. sent to the client) when it reached a size of 2K (I assume 2K bytes). Then looking at the size of the html generated for the ACS home page one can easily see that it is way larger than the 2K (actually it is 226K large).

While not being an expert on these matters, it seems to me that the culprit is the sheer size and complexity of this webpage. How it actually works with our the `session="false"` declaration is a mystery to me.

**Comment by terbolous** [comment]
just proves that we really need a new web ui :-)

**Comment by K0zka** [comment]
I do not know if a new web UI is needed, but tomcat 6 is a walking dead.

@miguelaferreira yes correct, the session can not be created once the headers are out on the pipe. I have only tested with jetty, that's the problem...

I try to find some time to experiment with tomcat 6.

**Comment by remibergsma** [comment]
@K0zka FYI: it also didn't work in tomcat 7

**Pull request merged**
