### PR TITLE
CLOUDSTACK-9687: if the allocated amount is 0 the capacity updates are not done, resulting in wrong values being shown as allocated value instead of zero

### PR DESCRIPTION
**Pull request by abhinandanprateek**
WIP

### CODE REVIEW

**Comment by abhinandanprateek** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
LGTM.
@blueorangutan package

**Comment by rhtyd** [comment]
@abhinandanprateek is this ready for review/merge? The description says WIP?

**Comment by rhtyd** [comment]
@abhinandanprateek @borisstoyanov is this ready for reviewing/merging?
@blueorangutan package

**Comment by rhtyd** [comment]
With https://github.com/apache/cloudstack/pull/1844/files merged, @abhinandanprateek @borisstoyanov where do we stand on merging/testing this?

**Comment by rhtyd** [comment]
I checked the changes are effective same as done in #1844, closing this.

**Pull request closed without merging**
