### PR TITLE
CLOUDSTACK-9637: Template create from snapshot does not populate vm_t…

### PR DESCRIPTION
**Pull request by sudhansu7**
**ISSUE**
============
Template create from snapshot does not populate vm_template_details

**REPRO STEPS**
==================
1. Register a template A and specify property:
Root disk controller: scsi
NIC adapter type: E1000
Keyboard type: us

2. Create a vm instance from template A

3. Take volume snapshot for vm instance

4. Delete VM instance

5. Switch to "Storage->Snapshots", convert snapshot to a template B

6. Observe template B does not inherit property from template A, the table vm_template_details is empty

**SOLUTION**: Retrieve and add source template details to VMTemplateVO.

Before Fix:

```

mysql> select id,name,source_template_id from vm_template where id=202; 
+-----+--------+--------------------+
| id  | name   | source_template_id |
+-----+--------+--------------------+
| 202 | Debian |               NULL |
+-----+--------+--------------------+
1 row in set (0.00 sec)

mysql> select * from vm_template_details where template_id=202; 
+----+-------------+--------------------+-------+---------+
| id | template_id | name               | value | display |
+----+-------------+--------------------+-------+---------+
|  1 |         202 | keyboard           | us    |       1 |
|  2 |         202 | nicAdapter         | E1000 |       1 |
|  3 |         202 | rootDiskController | scsi  |       1 |
+----+-------------+--------------------+-------+---------+
3 rows in set (0.00 sec)

mysql> select id,name,source_template_id from vm_template where source_template_id=202;
+-----+----------------+--------------------+
| id  | name           | source_template_id |
+-----+----------------+--------------------+
| 203 | derived-debian |                202 |
+-----+----------------+--------------------+
1 row in set (0.00 sec)

mysql> select * from vm_template_details where template_id=203;
Empty set (0.00 sec)


After Fix:

mysql> select id,name,source_template_id from vm_template where source_template_id=202;
+-----+--------------------------+--------------------+
| id  | name                     | source_template_id |
+-----+--------------------------+--------------------+
| 203 | derived-debian           |                202 |
| 204 | debian-derived-after-fix |                202 |
+-----+--------------------------+--------------------+
2 rows in set (0.00 sec)

mysql> select * from vm_template_details where template_id=204;
+----+-------------+--------------------+-------+---------+
| id | template_id | name               | value | display |
+----+-------------+--------------------+-------+---------+
|  4 |         204 | keyboard           | us    |       1 |
|  5 |         204 | nicAdapter         | E1000 |       1 |
|  6 |         204 | rootDiskController | scsi  |       1 |
+----+-------------+--------------------+-------+---------+
3 rows in set (0.00 sec)

```

**Marvin Test :** test_template_from_snapshot_with_template_details.py

**Result:**
```
test_01_create_template_snampshot (integration.component.test_template_from_snapshot_with_template_details.TestCreateTemplate) ... === TestName: test_01_create_template_snampshot | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 1 test in 864.523s

OK
```

### CODE REVIEW

**Comment by rhtyd** [comment]
Nice fix, @sudhansu7 this looks useful, can you change the base branch for the PR to 4.9, rebase your PR branch against 4.9?

**Comment by rhtyd** [comment]
@sudhansu7  please push -f on the PR to re-kick travis, or close/open the PR

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@sudhansu7 can you have a look at failures in `test_templates.py` and others.

**Comment by borisstoyanov** [comment]
I've manually verified the bug fix, looks OK
```
(local) SBCM5> list templates name=newTemp templatefilter=all
{
  "count": 1,
  "template": [
    {
      "account": "admin",
      "created": "2016-12-06T10:23:11+0000",
      "crossZones": false,
      "details": {
        "Message.ReservedCapacityFreed.Flag": "false",
        "cpuOvercommitRatio": "2.0",
        "dataDiskController": "osdefault",
        "keyboard": "us",
        "memoryOvercommitRatio": "1.0",
        "nicAdapter": "E1000",
        "rootDiskController": "scsi"
      },
      "displaytext": "newTemp",
      "domain": "ROOT",
      "domainid": "817d7ade-baf7-11e6-a594-06dc6e01070b",
      "format": "OVA",
      "hypervisor": "VMware",
      "id": "d39e190e-76a0-4bc3-9802-d7257153516e",
      "isdynamicallyscalable": false,
      "isextractable": false,
      "isfeatured": false,
      "ispublic": true,
      "isready": true,
      "name": "newTemp",
      "ostypeid": "819d53f9-baf7-11e6-a594-06dc6e01070b",
      "ostypename": "Other Linux (64-bit)",
      "passwordenabled": false,
      "size": 52428800,
      "sourcetemplateid": "20e9fd78-b256-4bf8-bb78-645b5950843b",
      "sshkeyenabled": false,
      "status": "Download Complete",
      "tags": [],
      "templatetype": "USER",
      "zoneid": "298acd1a-89e0-4a8e-9dc1-0498cd117fbc",
      "zonename": "pr1805-t590-vmware-55u3"
    }
  ]
}
```

Other than the test failures looks OK.

**Comment by cloudmonger** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 157
 Hypervisor xenserver
 NetworkType Advanced
 Passed=97
 Failed=6
 Skipped=7

_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/yj3wnzbceo9uef2/AAB6u-Iap-xztdm6jHX9SjPja?dl=0


**Failed tests:**
* test_snapshots.py

 * test_01_snapshot_root_disk Failing since 4 runs

* test_network.py

 * test_delete_account Failed

* test_non_contigiousvlan.py

 * test_extendPhysicalNetworkVlan Failed

* test_deploy_vm_iso.py

 * test_deploy_vm_from_iso Failing since 28 runs

* test_list_ids_parameter.py

 * ContextSuite context=TestListIdsParams>:setup Failing since 7 runs

* test_vm_life_cycle.py

 * test_10_attachAndDetach_iso Failing since 29 runs


**Skipped tests:**
test_01_test_vm_volume_snapshot
test_vm_nic_adapter_vmxnet3
test_static_role_account_acls
test_11_ss_nfs_version_on_ssvm
test_nested_virtualization_vmware
test_3d_gpu_support
test_deploy_vgpu_enabled_vm

**Passed test suits:**
test_deploy_vm_with_userdata.py
test_affinity_groups_projects.py
test_portable_publicip.py
test_over_provisioning.py
test_global_settings.py
test_scale_vm.py
test_service_offerings.py
test_routers_iptables_default_policy.py
test_loadbalance.py
test_routers.py
test_reset_vm_on_reboot.py
test_deploy_vms_with_varied_deploymentplanners.py
test_router_dns.py
test_login.py
test_public_ip_range.py
test_multipleips_per_nic.py
test_regions.py
test_affinity_groups.py
test_network_acl.py
test_pvlan.py
test_volumes.py
test_nic.py
test_deploy_vm_root_resize.py
test_resource_detail.py
test_secondary_storage.py
test_routers_network_ops.py
test_disk_offerings.py

**Comment by rhtyd** [comment]
LGTM, merging this based on review and tests.

**Pull request merged**
