### PR TITLE
CLOUDSTACK-8749: Add checks to prevent malformed/unexpected input

### PR DESCRIPTION
**Pull request by bhaisaab**
Based on @jburwell's comment on PR #718

### CODE REVIEW

**Comment by remibergsma** [comment]
@bhaisaab Can you send this PR against master please? For now, I'd rather merge to master, then cherry-pick back to 4.5 as I want to prevent all the cherry-picks in master (as we need to put them in a PR anyway in order for the tests to run first).

Once 4.6 is out and we'll be working on 4.7, we'll be able to send PRs against 4.6, then merge forward to 4.7/master.

Pinging @karuturi

**Comment by bhaisaab** [comment]
@remibergsma merges cleanly on master, if you LGTM; I can merge this on master and 4.5

**Comment by bhaisaab** [comment]
@remibergsma sending another PR just for master

**Comment by bhaisaab** [comment]
@remibergsma here: https://github.com/apache/cloudstack/pull/735

**Comment by remibergsma** [comment]
@bhaisaab Thanks, now the tests can run on master as well :-)

**Comment by remibergsma** [comment]
LGTM on this one, will do the other once the tests are done.

**Comment by remibergsma** [comment]
@jburwell can you review this please? Thanks!

**Comment by jburwell** [comment]
See comments on PR #735 regarding extracting the parsing logic and unit testing.

**Pull request merged**
