### PR TITLE
refactor: cloud-sysvmadm script

### LINKED ISSUE #9000: cloudstack-sysvmadm - /etc/rc.d/init.d/functions: No such file or directory
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME
~~~
cloudstack-sysvmadm
~~~

##### CLOUDSTACK VERSION
~~~
CloudStack 4.19.0.1
~~~

##### OS / ENVIRONMENT
```
Ubuntu 22.04
```

##### STEPS TO REPRODUCE
Start the command: `/usr/bin/cloudstack-sysvmadm`
~~~
root@nuc1:~# cloudstack-sysvmadm
/usr/bin/cloudstack-sysvmadm: line 21: /etc/rc.d/init.d/functions: No such file or directory

  The tool for stopping/starting running system vms and domain routers

  Usage: cloudstack-sysvmadm: [-d] [-u] [-p] [-m] [-s] [-r] [-a] [-n] [-t] [-l] [-z] [-v] [-i] [-j]

   -d - cloud DB server ip address, defaulted to localhost if not specified
   -u - user name to access cloud DB, defaulted to "root" if not specified
   -p - cloud DB user password, defaulted to no password if not specified

~~~

##### EXPECTED RESULTS
~~~
No error
~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes: #9000

- Fixes script, mainly the queryAsyncJobResult response parsing
- Indentations
- Use `uuid` instead of database `id`

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

#### How did you try to break this feature and the system with this change?

```
root@pr8601-t6928-kvm-ubuntu22-mgmt1:~# /usr/bin/cloudstack-sysvmadm -p pssword -s
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.

Stopping and starting 1 secondary storage vm(s)...
Done stopping and starting secondary storage vm(s)

Stopping and starting 1 console proxy vm(s)...
Done stopping and starting console proxy vm(s) .

```

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
clgtm, mostly cleanup

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by rohityadavcloud — APPROVED** [review]
LGTM - didn't test it though, not even sure who uses this. I know we may have this logged in release/upgrade notes.

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by shwstppr** [comment]
I don't see this script being called in the code anywhere so not sure if smoke tests would find anything

**Comment by DaanHoogland** [comment]
> I don't see this script being called in the code anywhere so not sure if smoke tests would find anything

sorry, blind execution

**Review by rohityadavcloud — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Pull request merged**
