### PR TITLE
CLOUDSTACK-7539: coverity regression dead local store

### PR DESCRIPTION
**Pull request by DaanHoogland**

### CODE REVIEW

**Comment by karuturi** [comment]
:+1:

**Comment by koushik-das** [comment]
Changes look good. Not sure what "dead local store" mean.

**Comment by DaanHoogland** [comment]
@koushik-das 'dead local storage' is a source analysis term for 'unused variable'. Not severe unless it happens a lot, because of memory consumption.

**Comment by koushik-das** [comment]
@DaanHoogland Thanks for the information.

**Comment by wilderrodrigues** [comment]
LGTM :+1:  Merging...

**Pull request closed without merging**
