### PR TITLE
schema: add empty DB upgrade path from 4.12.0.0 to 4.13.0.0

### PR DESCRIPTION
**Pull request by rhtyd**
This adds empty empty upgrade path from 4.12.0.0 to 4.13.0.0.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by rhtyd** [comment]
We need this otherwise, db install/setup seems to be failing and also to have existing/new PRs use the db upgrade path for db related changes.
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
4.13 systemvm links were missed in trillian config file. Re-kicked test job again.

**Comment by ustcweizhou** [comment]
code LGTM

**Pull request merged**
