### PR TITLE
CLOUDSTACK-9010: adjust packaging for centos7

### PR DESCRIPTION
**Pull request by davidamorimfaria**
Here are a few adjustments for the packaging in centos7. With these changes I was able to start the service. Please review. Thank you.

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@davidamorimfaria due to a known bug in jenkins/maven integration the build in jenkins failed. Could you repush with git push --force to your branch? I'm reviewing in the meanwhile.

**Comment by DaanHoogland** [comment]
@davidamorimfaria I saw you didn't go for the tomcat instance creation, right?
changes look good and as we discussed off-line.
Can you add a jira ticket name to the PR?

**Comment by wilderrodrigues** [comment]
Thanks for the fix and the PR, @davidamorimfaria 

I will try to test/review this one today.

Cheers,
Wilder

**Comment by remibergsma** [comment]
Seems to start fine now, thanks @davidamorimfaria 

Haven't setup a cloud with this or tested it further. Just built RPM packages and started management server.

```
[root@cs2 ~]# systemctl start cloudstack-management
[root@cs2 ~]# systemctl status cloudstack-management
cloudstack-management.service - CloudStack Management Server
   Loaded: loaded (/usr/lib/systemd/system/cloudstack-management.service; disabled)
   Active: active (running) since Fri 2015-10-30 09:56:41 GMT; 7s ago
 Main PID: 11075 (java)
   CGroup: /system.slice/cloudstack-management.service
           └─11075 java -Djava.awt.headless=true -Dcom.sun.management.jmxremote=false -Xmx2g -XX:+HeapDumpOnOutOfMemo...

Oct 30 09:56:43 cs2 server[11075]: Oct 30, 2015 9:56:43 AM org.apache.catalina.core.StandardEngine startInternal
Oct 30 09:56:43 cs2 server[11075]: INFO: Starting Servlet Engine: Apache Tomcat/7.0.54
Oct 30 09:56:43 cs2 server[11075]: Oct 30, 2015 9:56:43 AM org.apache.catalina.startup.HostConfig deployDirectory
Oct 30 09:56:43 cs2 server[11075]: INFO: Deploying web application directory /usr/share/cloudstack-management/w...client
Oct 30 09:56:43 cs2 server[11075]: Oct 30, 2015 9:56:43 AM org.apache.catalina.loader.WebappClassLoader validateJarFile
Oct 30 09:56:43 cs2 server[11075]: INFO: validateJarFile(/usr/share/cloudstack-management/webapps/client/WEB-IN....class
Oct 30 09:56:43 cs2 server[11075]: Oct 30, 2015 9:56:43 AM org.apache.catalina.loader.WebappClassLoader validateJarFile
Oct 30 09:56:43 cs2 server[11075]: INFO: validateJarFile(/usr/share/cloudstack-management/webapps/client/WEB-IN....class
Oct 30 09:56:43 cs2 server[11075]: Oct 30, 2015 9:56:43 AM org.apache.catalina.loader.WebappClassLoader validateJarFile
Oct 30 09:56:43 cs2 server[11075]: INFO: validateJarFile(/usr/share/cloudstack-management/webapps/client/WEB-IN....class
Hint: Some lines were ellipsized, use -l to show in full.
```

**Comment by davidamorimfaria** [comment]
I haven't installed a cloud with the packages made with this change, but so far the management servers start and talk to each other:

Oct 30 13:54:04 mgmt01 server: WARN  [c.c.c.ClusterManagerImpl] (Cluster-Notification-1:ctx-cb4bc2b4) Notifying management server join event took 0 ms

 These were the steps I did, using a mariadb 10 as db backend:
- yum localinstall cloudstack-common-4.6.0-SNAPSHOT.el7.centos.x86_64.rpm cloudstack-management-4.6.0-SNAPSHOT.el7.centos.x86_64.rpm cloudstack-usage-4.6.0-SNAPSHOT.el7.centos.x86_64.rpm cloudstack-cli-4.6.0-SNAPSHOT.el7.centos.x86_64.rpm
- [in mgmt01] cloudstack-setup-databases cloud:<fancy_password>@localhost
- [in mgmt02] cloudstack-setup-databases cloud:<fancy_password>@<remote_db_ip>
- cloudstack-setup-management
- systemctl enable cloudstack-management
- systemctl start cloudstack-management

**Comment by DaanHoogland** [comment]
based on the review of the changes and looking at the deployment of the management servers i think this LGTM

**Comment by remibergsma** [comment]
This PR fixes CentOS 7 packaging and obsoletes #888 and CLOUDSTACK-8812. I will merge this and close the other.

**Comment by remibergsma** [comment]
@davidamorimfaria Final request, please squash your commits. We need them to be atomic. Please ping me when done, thanks!

**Comment by davidamorimfaria** [comment]
done

**Comment by bhaisaab** [comment]
@davidamorimfaria @remibergsma should we port this to 4.5?

**Comment by DaanHoogland** [comment]
@bhaisaab I think it is fine to do so, but centos7 support was still experimental. Not sure if we spring hopes there that are unjust.

**Comment by bhaisaab** [comment]
@DaanHoogland I see, leaving it then. CentOS7 users should use 4.6/4.7 then.

**Comment by davidamorimfaria** [comment]
@bhaisaab I see no harm in trying to package 4.5 with this spec. It should just work (read, services start) if all the files expected by the spec file are also included in 4.5.

**Comment by bhaisaab** [comment]
@davidamorimfaria thanks, I personally won't be able to fix/test this soonish so dropping this unless of course you or someone wants this in 4.5 and sends a PR.

**Pull request merged**
