### PR TITLE
UI: bulk action support for various resources

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

This PR supports ui bulk action for various resources. Following are addressed as part of this PR:
- Bulk action support for various resources
- Suppression of notification pop up (that appears on the top right corner of the screen) for async jobs in case the operation progress modal is open
- Router links added to notification list for failed jobs/operations
- Progress View - would have a filter column to filter the jobs by state
- Cancel will be the default button for bulk operations
- Different hue used for alert message for _destructive_ bulk operations - like delete, stop, i,e, those that could lead to a possible down-time - to indicate to the users that such actions need to be performed with caution

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [X] Major
- [ ] Minor

### CODE REVIEW

**Comment by Pearl1594** [comment]
@blueorangutan ui

**Comment by Pearl1594** [comment]
@blueorangutan ui

**Comment by Pearl1594** [comment]
@blueorangutan ui

**Comment by Pearl1594** [comment]
@blueorangutan ui

**Comment by Pearl1594** [comment]
@blueorangutan ui

**Comment by Pearl1594** [comment]
@blueorangutan ui

**Comment by vladimirpetrov** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan ui

**Comment by vladimirpetrov** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan ui

**Review by vladimirpetrov — APPROVED** [review]
The following actions has been tested:
· VM: start, stop, restart, destroy (start, stop, destroy – already supported, but check implementation) - OK
· Kubernetes: start, stop, destroy - OK
· Instance groups: delete - OK
· SSH keypair: delete - OK
· Affinity groups: delete - OK
· Volumes: destroy - OK
· Snapshots: delete - OK
· VM snapshots: delete - OK
· Networks: restart, delete - OK
· VPC: restart, delete - OK
· Public IP Addresses: delete - OK
· VPN customer gateway and VPN users: delete - OK
· Firewall, port forwarding, LB rules: delete - OK
· Template and ISOs: delete (if feasible, as they are zone specific) - OK
· Events and Alerts: archive, delete (already supported, but check implementation) - OK
· Projects: active, suspend, delete - OK
· Accounts: enable, disable, lock, delete - OK
· Systemvms and Virtual Routers: stop, start, reboot and destroy - OK
· Internal LB: stop, start - OK
· Compute, system, disk and backup offerings: delete - OK
· Network and VPC offerings: enable, disable, delete - OK

The following functional changes were tested:
Suppress notifications (top right) when the progress view is open - OK
Router links added in the notification list view - OK
Display selected items in the confirmation & progress view - OK
Show only relevant columns in the confirmation / progress view - OK
Bulk action support for all user types - OK
Filter(in Progress view) on the operation status column - to filter jobs based on whether they are in progress, have succeeded or failed - OK
Different Alert message for destructive bulk actions like - delete*, stop*, expunge*, disassociate*, release* operations - OK
Cancel will be the default button for bulk operations - OK

In summary - LGTM

**Review by DaanHoogland — APPROVED** [review]
monkey tested and superficial code review
lgtm

**Comment by DaanHoogland** [comment]
@Pearl1594 can you look at the conflicts?

**Comment by Pearl1594** [comment]
@blueorangutan ui

**Comment by Pearl1594** [comment]
Done @DaanHoogland

**Pull request merged**
