### PR TITLE
packaging: Create cloud user and group if not present

### PR DESCRIPTION
**Pull request by davidjumani**
### Description

This PR creates the cloud group as well as the user if not present. Prevents errors / permission issues during setting up the MS

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
I think this may cause some issue with VMware (with secondary storage mounting). @davidjumani how/where did you hit a problem due to this?
@blueorangutan test centos7 vmware-67u3

**Comment by rhtyd** [comment]
I tested manually it does not affect CentOS7 (fresh install which does not have cloud user or group).
This is what I see after mgmt server is installed:
```
[root@qa4-low-mem-cs415-243bdd57-kvm-mgmt1 ~]# cat /etc/group | grep cloud
cloud:x:992:
[root@qa4-low-mem-cs415-243bdd57-kvm-mgmt1 ~]# cat /etc/passwd | grep cloud
cloud:x:995:992:CloudStack unprivileged user:/var/cloudstack/management:/bin/sh
[root@qa4-low-mem-cs415-243bdd57-kvm-mgmt1 ~]# id cloud
uid=995(cloud) gid=992(cloud) groups=992(cloud)
[root@qa4-low-mem-cs415-243bdd57-kvm-mgmt1 ~]# ls -lahi /var/lib/cloudstack/
total 4.0K
34121744 drwxr-xr-x.  2 cloud cloud    6 Feb 18 13:08 .
33582984 drwxr-xr-x. 35 root  root  4.0K Feb 18 13:08 ..
```

**Comment by rhtyd** [comment]
With about findings, this is not critical/blocker for 4.15.1.0, moving it to 4.15.2.0.

**Review by rhtyd — APPROVED** [review]

**Pull request merged**
