### PR TITLE
Fix spelling

### PR DESCRIPTION
**Pull request by jbampton**
### Description

This PR fixes spelling

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [X] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [X] Trivial

### CODE REVIEW

**Review by JoaoJandre — APPROVED** [review]
LGTM

**Review by GutoVeronezi — APPROVED** [review]

**Review by stephankruggg — APPROVED** [review]

**Review by DaanHoogland — APPROVED** [review]
spelling lgtm but let's at least intergration test this (method name changes!)

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
@blueorangutan test centos7 xenserver-71

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
except for the `test_08_upgrade_kubernetes_ha_cluster` non of the test failures are consistent and probably environmental. merging this.

**Pull request merged**
