### PR TITLE
[HEALTH][4.13] Health Check Run

### PR DESCRIPTION
**Pull request by DaanHoogland**

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
and again
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
@blueorangutan test centos7 vmware67

**Comment by DaanHoogland** [comment]
@blueorangutan test centos7 vmware67-u3

**Comment by DaanHoogland** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by andrijapanicsb** [comment]
@blueorangutan package

**Comment by andrijapanicsb** [comment]
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
just being double sure

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by andrijapanicsb** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by andrijapanicsb** [comment]
@blueorangutan test centos7 xenserver-71

**Comment by andrijapanicsb** [comment]
Besides the known privategtw failures, the rest of the (volumes) issues in XS71 and VMware-67 are complete nonsense (internal test issues, not cleaning up or similar) - and have nothing to do with the actual functionality being testing.

Proceeding with cutting the RC2 release as the health looks good.

**Comment by andrijapanicsb** [comment]
@blueorangutan package

**Comment by andrijapanicsb** [comment]
@blueorangutan test matrix

**Comment by andrijapanicsb** [comment]
@blueorangutan test centos7 xenserver71

**Comment by andrijapanicsb** [comment]
@blueorangutan test centos7 xenserver-71

**Comment by andrijapanicsb** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by andrijapanicsb** [comment]
@blueorangutan test

**Comment by andrijapanicsb** [comment]
Tests ok for 4.13.1 RC3.

**Comment by rhtyd** [comment]
Let's open a new one if/when we do 4.13.2.0

**Comment by DaanHoogland** [comment]
@blueorangutan sweep

**Pull request closed without merging**
