### PR TITLE
Fix for the NicVO.java regression.

### PR DESCRIPTION
**Pull request by borisroman**
Renamed set*() methods to correct naming.

### CODE REVIEW

**Comment by borisroman** [comment]
The updateBuilder will check if the DAO has changed based on the set*() methods. When it can't resolve one, it won't update. After learning this I changed the set*() method names to reflect the names of the variable fields.

**Comment by wido** [comment]
LGTM

**Comment by borisroman** [comment]
Tested it in a new environment. The nics are correctly put in the db again.

**Comment by borisroman** [comment]
@remibergsma @karuturi Please review!

**Comment by karuturi** [comment]
LGTM. lets wait for travis and other jenkins verifications.

In future, can you club all refactoring work in a branch and merge them together? That way, we can test it once(giving bigger time window for everyone to verofy) and merge
Also, I think this refactoring is a candidate for 4.7. We are already close to RC on 4.6(once 4.5.2 is done) and cannot afford regressions at this stage.

**Comment by borisroman** [comment]
@karuturi I came to that conclusion in the previous pr. I will stack all refactoring work in a branch. And send a PR when done.

**Comment by remibergsma** [comment]
@borisroman Thanks! I'll run some tests later tonight. Travis is green, didn't see an Apache build reporting results (yet?).

**Comment by remibergsma** [comment]
LGTM Verified that a new cloud deployment had working system VMs again.

**Comment by remibergsma** [comment]
cloudstack-pull-analysis 296 failed due to: `Expected exactly 2 but it took more than 3 microseconds between 2 consecutive calls to System.nanoTime().` Seems not related.

**Comment by DaanHoogland** [comment]
I think we have to disable this test, enlarging the period even more beats every intention of its use. not related indeed

**Comment by remibergsma** [comment]
Check, as far as I can tell everything is OK. And since master is broken now anyway, I think it's time to merge this to fix it.

**Comment by DaanHoogland** [comment]
hm, you shouldt merge anything to a broken master that isn't hellbound on fixing it.

**Comment by remibergsma** [comment]
@DaanHoogland It does fix the problem, I just feel a bit blind sometimes by the builds that seem less reliable lately so then it's hard to be sure. 
But anyway, when looking back we should have quickly reverted the initial PR that introduced the problem. Next time we should do that. Benefit is master is stable again, plus there is time to work on a fix that can then be send as a PR along with the original commits.

**Pull request merged**
