### PR TITLE
SystemVM cleanups

### PR DESCRIPTION
**Pull request by resmo**
from the logrotate docs

> size - With this, the log file is rotated when the specified size is reached. Size may be specified in bytes (default), kilobytes (sizek), or megabytes (sizem).

> Note: If size and time interval options are specified at same time, only size option take effect. it causes log files to be rotated without regard for the last rotation time. If both log size and timestamp of a log file need to be considered by logrotate, the minsize option should be used. logrotate will rotate log file when they grow bigger than minsize, but not before the additionally specified time interval.

### CODE REVIEW

**Comment by rafaelweingartner** [comment]
Do we want to rotate logs only based on size?
What about using that “minsize” and the timestamp (daily) configuration? I do not know the system vms log growth rate, but that seems a better approach.

**Comment by resmo** [comment]
Actually the logrotating is running every hour (by size), which can not be done with logrotate time interval. We have had problems in the past filling up /var (and / when it wasn't a separate partition).

This PR does not change functionality, it just make it explicitely.

**Comment by rafaelweingartner** [comment]
thanks for the explanation.
Your PR LGTM

**Comment by glennwagner** [comment]
Had a look ta your changes, PR LGTM

**Comment by kiwiflyer** [comment]
Makes sense. LGTM.

**Comment by bvbharatk** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 83
 Hypervisor xenserver
 NetworkType Advanced
Passed=75
 Failed=23
 Skipped=3

**The follwing tests have known issues**
integration.smoke.test_iso.TestISO.test_07_list_default_iso
integration.smoke.test_privategw_acl.py
integration.smoke.test_vm_snapshots.TestSnapshots.test_01_test_vm_volume_snapshot
integration.smoke.test_vpc_vpn.TestVpcSite2SiteVpn.test_vpc_site2site_vpn
integration.smoke.test_iso.TestISO.test_04_extract_Iso


_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/yj3wnzbceo9uef2/AAB6u-Iap-xztdm6jHX9SjPja?dl=0


**Failed tests:**
* integration.smoke.test_vpc_vpn.TestVpcRemoteAccessVpn

 * test_vpc_remote_access_vpn

 * test_vpc_site2site_vpn

* integration.smoke.test_vm_snapshots.TestSnapshots

 * test_01_test_vm_volume_snapshot

 * test_02_revert_vm_snapshots

 * test_03_delete_vm_snapshots

* integration.smoke.test_privategw_acl.TestPrivateGwACL

 * test_01_vpc_privategw_acl

 * test_02_vpc_privategw_static_routes

 * test_03_rvpc_privategw_static_routes

* integration.smoke.test_guest_vlan_range.TestDedicateGuestVlanRange

 * test_dedicateGuestVlanRange

* <nose.suite

 * ContextSuite context=TestRouterServices>:setup

* <nose.suite

 * ContextSuite context=TestNiciraContoller>:setup

* integration.smoke.test_primary_storage.TestPrimaryStorageServices

 * test_01_primary_storage_iscsi

* <nose.suite

 * ContextSuite context=TestSnapshotRootDisk>:setup

* integration.smoke.test_volumes.TestCreateVolume

 * ContextSuite context=TestVolumes>:setup

* integration.smoke.test_ssvm.TestSSVMs

 * test_05_stop_ssvm

 * test_06_stop_cpvm

 * test_09_destroy_ssvm

 * test_10_destroy_cpvm

* integration.smoke.test_internal_lb.TestInternalLb

 * test02_internallb_haproxy_stats_on_all_interfaces

 * test_01_internallb_roundrobin_1VPC_3VM_HTTP_port80

* integration.smoke.test_templates.TestCreateTemplate

 * ContextSuite context=TestTemplates>:setup

* integration.smoke.test_iso.TestCreateIso

 * test_04_extract_Iso

 * test_07_list_default_iso


**Skipped tests:**
test_vm_nic_adapter_vmxnet3
test_deploy_vgpu_enabled_vm
test_06_copy_iso

**Passed test suits:**
integration.smoke.test_deploy_vm_with_userdata.TestDeployVmWithUserData
integration.smoke.test_affinity_groups_projects.TestDeployVmWithAffinityGroup
integration.smoke.test_portable_publicip.TestPortablePublicIPAcquire
integration.smoke.test_over_provisioning.TestUpdateOverProvision
integration.smoke.test_global_settings.TestUpdateConfigWithScope
integration.smoke.test_scale_vm.TestScaleVm
integration.smoke.test_service_offerings.TestCreateServiceOffering
integration.smoke.test_loadbalance.TestLoadBalance
integration.smoke.test_reset_vm_on_reboot.TestResetVmOnReboot
integration.smoke.test_deploy_vms_with_varied_deploymentplanners.TestDeployVmWithVariedPlanners
integration.smoke.test_network.TestDeleteAccount
integration.smoke.test_non_contigiousvlan.TestUpdatePhysicalNetwork
integration.smoke.test_deploy_vm_iso.TestDeployVMFromISO
integration.smoke.test_public_ip_range.TestDedicatePublicIPRange
integration.smoke.test_multipleips_per_nic.TestDeployVM
integration.smoke.test_regions.TestRegions
integration.smoke.test_affinity_groups.TestDeployVmWithAffinityGroup
integration.smoke.test_network_acl.TestNetworkACL
integration.smoke.test_pvlan.TestPVLAN
integration.smoke.test_nic.TestNic
integration.smoke.test_deploy_vm_root_resize.TestDeployVM
integration.smoke.test_resource_detail.TestResourceDetail
integration.smoke.test_secondary_storage.TestSecStorageServices
integration.smoke.test_vm_life_cycle.TestDeployVM
integration.smoke.test_disk_offerings.TestCreateDiskOffering

**Comment by swill** [comment]
@bvbharatk I am guessing you are still having some environment issues in your CI or are these results correct?  Thanks...

**Comment by rhtyd** [comment]
@resmo LGTM, please rebase against master and squash changes into a single commit

tag:mergeready

**Comment by resmo** [comment]
@rhtyd rebased and squashed

**Comment by swill** [comment]
### CI RESULTS

```
Tests Run: 83
  Skipped: 0
   Failed: 0
   Errors: 2
 Duration: 8h 32m 12s
```

**Summary of the problem(s):**
```
ERROR: test suite for <class 'integration.smoke.test_vpc_vpn.TestVpcRemoteAccessVpn'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/suite.py", line 209, in run
    self.setUp()
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/util.py", line 471, in try_run
    return func()
  File "/data/git/cs1/cloudstack/test/integration/smoke/test_vpc_vpn.py", line 293, in setUpClass
    cls.template.download(cls.apiclient)
  File "/usr/lib/python2.7/site-packages/marvin/lib/base.py", line 1350, in download
    elif 'Downloaded' in template.status:
TypeError: argument of type 'NoneType' is not iterable
----------------------------------------------------------------------
Additional details in: /tmp/MarvinLogs/test_network_L8KB3U/results.txt
```

```
ERROR: test suite for <class 'integration.smoke.test_vpc_vpn.TestVpcSite2SiteVpn'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/suite.py", line 209, in run
    self.setUp()
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/util.py", line 471, in try_run
    return func()
  File "/data/git/cs1/cloudstack/test/integration/smoke/test_vpc_vpn.py", line 472, in setUpClass
    cls.template.download(cls.apiclient)
  File "/usr/lib/python2.7/site-packages/marvin/lib/base.py", line 1350, in download
    elif 'Downloaded' in template.status:
TypeError: argument of type 'NoneType' is not iterable
----------------------------------------------------------------------
Additional details in: /tmp/MarvinLogs/test_network_L8KB3U/results.txt
```



**Associated Uploads**

**`/tmp/MarvinLogs/DeployDataCenter__May_17_2016_23_33_20_PPVIA5:`**
* [dc_entries.obj](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1414/tmp/MarvinLogs/DeployDataCenter__May_17_2016_23_33_20_PPVIA5/dc_entries.obj)
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1414/tmp/MarvinLogs/DeployDataCenter__May_17_2016_23_33_20_PPVIA5/failed_plus_exceptions.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1414/tmp/MarvinLogs/DeployDataCenter__May_17_2016_23_33_20_PPVIA5/runinfo.txt)

**`/tmp/MarvinLogs/test_network_L8KB3U:`**
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1414/tmp/MarvinLogs/test_network_L8KB3U/failed_plus_exceptions.txt)
* [results.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1414/tmp/MarvinLogs/test_network_L8KB3U/results.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1414/tmp/MarvinLogs/test_network_L8KB3U/runinfo.txt)

**`/tmp/MarvinLogs/test_vpc_routers_P26BC1:`**
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1414/tmp/MarvinLogs/test_vpc_routers_P26BC1/failed_plus_exceptions.txt)
* [results.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1414/tmp/MarvinLogs/test_vpc_routers_P26BC1/results.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1414/tmp/MarvinLogs/test_vpc_routers_P26BC1/runinfo.txt)


Uploads will be available until `2016-07-18 02:00:00 +0200 CEST`

*Comment created by [`upr comment`](https://github.com/cloudops/upr).*

**Comment by swill** [comment]
I think this one is ready...

**Pull request merged**
