### PR TITLE
Fixed double slash in secret breaking db insert

### PR DESCRIPTION
**Pull request by Spaceman1984**
## Description

Fixes: #4147 
## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

From the front end, add RBD primary storage pool with a secrect with 2 slashes next to each other - no error.

### CODE REVIEW

**Comment by Spaceman1984** [comment]
@blueorangutan package

**Comment by Spaceman1984** [comment]
Needs end to end testing

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
Does this happen on Primate too @Spaceman1984  or just a UI issue, than backend issue? (related to secret input for adding ceph/rbd pool)
@blueorangutan test

**Comment by Spaceman1984** [comment]
I'll check primate.

**Comment by Spaceman1984** [comment]
@rhtyd I don't see the RBD as an option on Primate for primary storage.

**Comment by rhtyd** [comment]
Note - Needs testing

**Comment by rhtyd** [comment]
Looks like this only affects the old UI, if we're not getting it in 4.15 we may want to check Primate and then close this. cc @sureshanaparti @DaanHoogland et al

**Comment by DaanHoogland** [comment]
We can keep this open or merge it. old UI so no real consequences. Do we have heavy rdb users?

**Review by GabrielBrascher — APPROVED** [review]
Code LGTM

**Comment by GabrielBrascher** [comment]
I have seen this issue to register RBD pool via UI inded in case "/" appear in Rados secret. Quite a corner case to have "/" on the secret, thus not really noticed I guess.

**Comment by DaanHoogland** [comment]
@GabrielBrascher can you test whether you have this issue in primate?

**Comment by GabrielBrascher** [comment]
@DaanHoogland @Spaceman1984 I just tested it. The same exception as the one presented at #4147 happens when adding RBD pool via the Primate UI.

A password containing multiple multiple '/' (e.g. _1234//1234_) resulted on the following exception; the same password with just one '/' does not preset this exception.

Output with dummy values for adding a RBD pool with double slashes:
`Failed to add data store: DB Exception on: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO storage_pool (storage_pool.id, storage_pool.name, storage_pool.uuid, storage_pool.pool_type, storage_pool.created, storage_pool.update_time, storage_pool.data_center_id, storage_pool.pod_id, storage_pool.used_bytes, storage_pool.capacity_bytes, storage_pool.status, storage_pool.storage_provider_name, storage_pool.host_address, storage_pool.path, storage_pool.port, storage_pool.user_info, storage_pool.cluster_id, storage_pool.scope, storage_pool.managed, storage_pool.capacity_iops, storage_pool.hypervisor, storage_pool.parent) VALUES (0, _binary'test2', _binary'e28b680f-cb21-3089-84e3-584bf549f062', 'RBD', '2020-11-10 12:53:57', null, 1, 1, 0, 0, 'Initialized', _binary'DefaultPrimary', null, _binary'12334@10.2.3.4/pool', 0, null, 1, null, 0, null, null, 0)`

**Comment by GabrielBrascher** [comment]
Maybe this should be addressed on the backend.

**Comment by DaanHoogland** [comment]
@GabrielBrascher I don't see a double slash in that output, what is the problematic field, and what was the input value?

**Comment by DaanHoogland** [comment]
@Spaceman1984 the issue is reported on 4.13. can you rebase?

**Comment by GabrielBrascher** [comment]
@DaanHoogland sorry, I did not provide all the details on the test.

What happens is that the double slashes _break_ the input. For instance, I configured a RBD pool with a password of `1234//12334`, the user as _user_, rados monitor address of `10.2.3.4`, and pool named as `pool`; however, instead of having the expectedf `user@10.2.3.4/pool` the log presents a broken user with the second part of the password after "//": `12334@10.2.3.4/pool`. Via the UI the error presented is the one that I pasted here. The INSERT (as far as I checked) due to null value that should not be null.

From the management server side it is possible to check the API request as:

```
zoneid=d3bcf0c7-4886-44d8-a6a1-5952c430e235
scope=cluster
name=test2
provider=DefaultPrimary
podid=9d3126c1-4309-4e32-b989-df7b11b7e020
clusterid=27754861-5aeb-488a-b679-0133e1689186
url=rbd:%2F%2Fuser:1234_%2F12334@10.2.3.4%2Fpool
command=createStoragePool
response=json
```

Note that the url had scaped one "/" (_%2F_) between _1234_ and _12334_ . URL: `rbd:%2F%2Fuser:1234_%2F12334@10.2.3.4%2Fpool`.

Full log:
```
2020-11-10 13:53:57,682 DEBUG [c.c.a.ApiServlet] (qtp477376212-967:ctx-4a0a2d92) (logid:44629add) ===START===  127.0.0.1 -- GET  scope=cluster&zoneid=d3bcf0c7-4886-44d8-a6a1-5952c430e235&name=test2&provider=DefaultPrimary&podid=9d3126c1-4309-4e32-b989-df7b11b7e020&clusterid=27754861-5aeb-488a-b679-0133e1689186&url=rbd:%2F%2Fuser:1234_%2F12334@10.2.3.4%2Fpool&command=createStoragePool&response=json
2020-11-10 13:53:57,702 DEBUG [o.a.c.s.d.l.CloudStackPrimaryDataStoreLifeCycleImpl] (qtp477376212-967:ctx-4a0a2d92 ctx-287b0e56) (logid:44629add) createPool Params @ scheme - rbd storageHost - null hostPath - /12334@10.2.3.4/pool port - -1
2020-11-10 13:53:57,707 DEBUG [c.c.u.d.T.Transaction] (qtp477376212-967:ctx-4a0a2d92 ctx-287b0e56) (logid:44629add) Rolling back the transaction: Time = 2 Name =  qtp477376212-967; called by -TransactionLegacy.rollback:888-TransactionLegacy.removeUpTo:831-TransactionLegacy.close:655-TransactionContextInterceptor.invoke:36-ReflectiveMethodInvocation.proceed:175-ExposeInvocationInterceptor.invoke:95-ReflectiveMethodInvocation.proceed:186-JdkDynamicAopProxy.invoke:212-$Proxy61.persist:-1-PrimaryDataStoreHelper.createPrimaryDataStore:135-CloudStackPrimaryDataStoreLifeCycleImpl.initialize:364-StorageManagerImpl.createPool:738
2020-11-10 13:53:57,709 DEBUG [c.c.s.StorageManagerImpl] (qtp477376212-967:ctx-4a0a2d92 ctx-287b0e56) (logid:44629add) Failed to add data store: DB Exception on: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO storage_pool (storage_pool.id, storage_pool.name, storage_pool.uuid, storage_pool.pool_type, storage_pool.created, storage_pool.update_time, storage_pool.data_center_id, storage_pool.pod_id, storage_pool.used_bytes, storage_pool.capacity_bytes, storage_pool.status, storage_pool.storage_provider_name, storage_pool.host_address, storage_pool.path, storage_pool.port, storage_pool.user_info, storage_pool.cluster_id, storage_pool.scope, storage_pool.managed, storage_pool.capacity_iops, storage_pool.hypervisor, storage_pool.parent) VALUES (0, _binary'test2', _binary'e28b680f-cb21-3089-84e3-584bf549f062', 'RBD', '2020-11-10 12:53:57', null, 1, 1, 0, 0, 'Initialized', _binary'DefaultPrimary', null, _binary'12334@10.2.3.4/pool', 0, null, 1, null, 0, null, null, 0)
com.cloud.utils.exception.CloudRuntimeException: DB Exception on: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO storage_pool (storage_pool.id, storage_pool.name, storage_pool.uuid, storage_pool.pool_type, storage_pool.created, storage_pool.update_time, storage_pool.data_center_id, storage_pool.pod_id, storage_pool.used_bytes, storage_pool.capacity_bytes, storage_pool.status, storage_pool.storage_provider_name, storage_pool.host_address, storage_pool.path, storage_pool.port, storage_pool.user_info, storage_pool.cluster_id, storage_pool.scope, storage_pool.managed, storage_pool.capacity_iops, storage_pool.hypervisor, storage_pool.parent) VALUES (0, _binary'test2', _binary'e28b680f-cb21-3089-84e3-584bf549f062', 'RBD', '2020-11-10 12:53:57', null, 1, 1, 0, 0, 'Initialized', _binary'DefaultPrimary', null, _binary'12334@10.2.3.4/pool', 0, null, 1, null, 0, null, null, 0)
        at com.cloud.utils.db.GenericDaoBase.persist(GenericDaoBase.java:1450)
        at org.apache.cloudstack.storage.datastore.db.PrimaryDataStoreDaoImpl.persist(PrimaryDataStoreDaoImpl.java:273)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
```

**Review by rhtyd — APPROVED** [review]
LGTM, let's merge since old UI will be removed in next milestone

**Pull request merged**
