### PR TITLE
CLOUDSTACK-6697: bigswitch networking plugin update

### PR DESCRIPTION
**Pull request by kwanggithub**
1. provide compatibility with the Big Cloud Fabric (BCF) controller
   L2 Connectivity Service in both VPC and non-VPC modes
2. virtual network terminology updates: VNS --> BCF_SEGMENT
3. uses HTTPS with trust-always certificate handling
4. topology sync support with BCF controller
5. support multiple (two) BCF controllers with HA
6. support VM migration
7. support Firewall, Static NAT, and Source NAT with NAT enabled option
8. add VifDriver for Indigo Virtual Switch (IVS)

### CODE REVIEW

**Comment by bhaisaab** [comment]
Since I don't have any real hardware to test against and since TravisCI build is green I'm merging it. Thanks @kwanggithub for the PR.

**Comment by bhaisaab** [comment]
@kwanggithub sorry there are issues with the patch so I cannot merge it on master;
1. the fix removes old apis and replaces them with new ones. This breaks backward compatibility for old plugin users. Do you want to do it?
2. The SQL drop table and create table for the new plugin needs to go into schema-451to460.sql. We ought not change schema-442to450.sql now.

**Comment by runseb** [comment]
@bhaisaab thanks for looking into this one. KC had several reviews in RB and has been working on this for a while now. It's about time we try to merge it.

**Comment by bhaisaab** [comment]
@runseb I can help merge it now, though I'll need to move the sql statements to the other file. I guess since it's a small task I'll go ahead and do it.

**Comment by runseb** [comment]
With features like this, I am not sure what's best. Ideally we would pull them in a separate feature branch and call a [MERGE] on the list. Then keep track of it for the release (if we were to release based on master).

**Comment by bhaisaab** [comment]
@runseb I skimmed through the diff, since TravisCI is green and most major changes are in the plugin itself I'm going ahead with the merge now.

**Comment by karuturi** [comment]
@kwanggithub 
This commit introduced many new findbugs issues. Can you please fix them?

**Comment by kwanggithub** [comment]
Thanks to all who helped shepherd this effort! Happy to see this merged!
@karuturi , absolutely - I will fix the find bug issues, together with many PMD issues identified. Will push the fixes soon.

**Pull request closed without merging**
