### PR TITLE
CLOUDSTACK-9064: The users should be able to create multiple Guest Sh…

### PR DESCRIPTION
**Pull request by abhinandanprateek**
…ared Networks in same Vlan ID, same Physical Network and same network, just with a different IP ranges.

### CODE REVIEW

**Comment by bhaisaab** [comment]
LGTM

**Comment by remibergsma** [comment]
If we want this in 4.6, please don't merge this. When #1116 is merged in 4.6, it will be fwd merged to master as well.

**Comment by bhaisaab** [comment]
@remibergsma cool, @abhinandanprateek can you close this; as the other PR has been merged on 4.6 and will be fwd-merged on master to get the fix on master.

**Comment by bhaisaab** [comment]
@agneya2001 @abhinandanprateek please review and close this PR

**Comment by rhtyd** [comment]
@abhinandanprateek @agneya2001 please check that your changes has been merged on master and close this PR, thanks

tag:closeme

**Comment by abhinandanprateek** [comment]
fixed in master

**Comment by rhtyd** [comment]
@abhinandanprateek was this merged in 4.9 as well?

**Comment by abhinandanprateek** [comment]
@rhtyd yes it is merged in 4.9 as well.

**Comment by rhtyd** [comment]
@abhinandanprateek great thanks

**Pull request closed without merging**
