### PR TITLE
CLOUDSTACK-8835: Added alerts incase of template download failure

### PR DESCRIPTION
**Pull request by karuturi**
Authored-By: @sanjaytripathi 
Reviewed-By: @devdeep

### CODE REVIEW

**Comment by bhaisaab** [comment]
LGTM

**Comment by DaanHoogland** [comment]
Makes sense and LGTM. I see some code duplication in ImageStoreUploadMonitorImpl, though. A good moment to get rid of this?

**Comment by wido** [comment]
LGTM

**Comment by karuturi** [comment]
@DaanHoogland the repeated code is two lines calling sendalert and logger. may be we could move the logging to send alert itself. Will check that later.

**Pull request merged**
