### PR TITLE
Hyper-V communication broken by change in variable names

### PR DESCRIPTION
**Pull request by mike-tutkowski**
Change variable names back to fix communication with Hyper-V Agent:

https://issues.apache.org/jira/browse/CLOUDSTACK-9383

### CODE REVIEW

**Comment by rafaelweingartner** [comment]
Given our discussion on mailing list and code review, LGTM.

**Comment by swill** [comment]
### CI RESULTS

```
Tests Run: 85
  Skipped: 0
   Failed: 1
   Errors: 1
 Duration: 11h 00m 25s
```

**Summary of the problem(s):**
```
ERROR: Test to verify access to loadbalancer haproxy admin stats page
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/git/cs1/cloudstack/test/integration/smoke/test_internal_lb.py", line 854, in tearDown
    raise Exception("Cleanup failed with %s" % e)
Exception: Cleanup failed with Job failed: {jobprocstatus : 0, created : u'2016-05-21T11:09:36+0200', jobresult : {errorcode : 530, errortext : u'Failed to delete network'}, cmd : u'org.apache.cloudstack.api.command.user.network.DeleteNetworkCmd', userid : u'eabb1fa0-1f04-11e6-9252-5254001daa61', jobstatus : 2, jobid : u'3f774cb0-c0b7-433e-9442-e27c4134c1e7', jobresultcode : 530, jobresulttype : u'object', jobinstancetype : u'Network', accountid : u'eabb0890-1f04-11e6-9252-5254001daa61'}
----------------------------------------------------------------------
Additional details in: /tmp/MarvinLogs/test_network_CCYW7Z/results.txt
```

```
FAIL: Test destroy(expunge) Virtual Machine
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/git/cs1/cloudstack/test/integration/smoke/test_vm_life_cycle.py", line 646, in test_09_expunge_vm
    self.assertEqual(list_vm_response,None,"Check Expunged virtual machine is in listVirtualMachines response")
AssertionError: Check Expunged virtual machine is in listVirtualMachines response
----------------------------------------------------------------------
Additional details in: /tmp/MarvinLogs/test_vpc_routers_90CD36/results.txt
```



**Associated Uploads**

**`/tmp/MarvinLogs/DeployDataCenter__May_21_2016_05_37_14_WSLJYQ:`**
* [dc_entries.obj](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1556/tmp/MarvinLogs/DeployDataCenter__May_21_2016_05_37_14_WSLJYQ/dc_entries.obj)
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1556/tmp/MarvinLogs/DeployDataCenter__May_21_2016_05_37_14_WSLJYQ/failed_plus_exceptions.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1556/tmp/MarvinLogs/DeployDataCenter__May_21_2016_05_37_14_WSLJYQ/runinfo.txt)

**`/tmp/MarvinLogs/test_network_CCYW7Z:`**
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1556/tmp/MarvinLogs/test_network_CCYW7Z/failed_plus_exceptions.txt)
* [results.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1556/tmp/MarvinLogs/test_network_CCYW7Z/results.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1556/tmp/MarvinLogs/test_network_CCYW7Z/runinfo.txt)

**`/tmp/MarvinLogs/test_vpc_routers_90CD36:`**
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1556/tmp/MarvinLogs/test_vpc_routers_90CD36/failed_plus_exceptions.txt)
* [results.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1556/tmp/MarvinLogs/test_vpc_routers_90CD36/results.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1556/tmp/MarvinLogs/test_vpc_routers_90CD36/runinfo.txt)


Uploads will be available until `2016-07-22 02:00:00 +0200 CEST`

*Comment created by [`upr comment`](https://github.com/cloudops/upr).*

**Comment by swill** [comment]
### CI RESULTS

```
Tests Run: 85
  Skipped: 0
   Failed: 1
   Errors: 1
 Duration: 10h 51m 43s
```

**Summary of the problem(s):**
```
FAIL: Test destroy(expunge) Virtual Machine
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/git/cs1/cloudstack/test/integration/smoke/test_vm_life_cycle.py", line 646, in test_09_expunge_vm
    self.assertEqual(list_vm_response,None,"Check Expunged virtual machine is in listVirtualMachines response")
AssertionError: Check Expunged virtual machine is in listVirtualMachines response
----------------------------------------------------------------------
Additional details in: /tmp/MarvinLogs/test_vpc_routers_FSAZNE/results.txt
```

```
ERROR: Test to verify access to loadbalancer haproxy admin stats page
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/git/cs1/cloudstack/test/integration/smoke/test_internal_lb.py", line 854, in tearDown
    raise Exception("Cleanup failed with %s" % e)
Exception: Cleanup failed with Job failed: {jobprocstatus : 0, created : u'2016-05-22T12:00:18+0200', jobresult : {errorcode : 530, errortext : u'Failed to delete network'}, cmd : u'org.apache.cloudstack.api.command.user.network.DeleteNetworkCmd', userid : u'2fac0d9d-1fd2-11e6-93b7-5254001daa61', jobstatus : 2, jobid : u'6cc5cc63-3184-4087-8888-4c51a659c9f1', jobresultcode : 530, jobresulttype : u'object', jobinstancetype : u'Network', accountid : u'2fabf773-1fd2-11e6-93b7-5254001daa61'}
----------------------------------------------------------------------
Additional details in: /tmp/MarvinLogs/test_network_XMCT4W/results.txt
```



**Associated Uploads**

**`/tmp/MarvinLogs/DeployDataCenter__May_22_2016_06_06_04_MNRZVU:`**
* [dc_entries.obj](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1556/tmp/MarvinLogs/DeployDataCenter__May_22_2016_06_06_04_MNRZVU/dc_entries.obj)
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1556/tmp/MarvinLogs/DeployDataCenter__May_22_2016_06_06_04_MNRZVU/failed_plus_exceptions.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1556/tmp/MarvinLogs/DeployDataCenter__May_22_2016_06_06_04_MNRZVU/runinfo.txt)

**`/tmp/MarvinLogs/test_network_XMCT4W:`**
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1556/tmp/MarvinLogs/test_network_XMCT4W/failed_plus_exceptions.txt)
* [results.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1556/tmp/MarvinLogs/test_network_XMCT4W/results.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1556/tmp/MarvinLogs/test_network_XMCT4W/runinfo.txt)

**`/tmp/MarvinLogs/test_vpc_routers_FSAZNE:`**
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1556/tmp/MarvinLogs/test_vpc_routers_FSAZNE/failed_plus_exceptions.txt)
* [results.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1556/tmp/MarvinLogs/test_vpc_routers_FSAZNE/results.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1556/tmp/MarvinLogs/test_vpc_routers_FSAZNE/runinfo.txt)


Uploads will be available until `2016-07-24 02:00:00 +0200 CEST`

*Comment created by [`upr comment`](https://github.com/cloudops/upr).*

**Comment by swill** [comment]
I ran CI again hoping to clear up those errors and I got the same ones again.  I don't think they are related to this PR, but twice in a row concerns me a bit.  I will run another set...

**Comment by koushik-das** [comment]
Simple changes. LGTM.

**Comment by swill** [comment]
### CI RESULTS

```
Tests Run: 82
  Skipped: 0
   Failed: 0
   Errors: 3
 Duration: 8h 11m 34s
```

**Summary of the problem(s):**
```
ERROR: test suite for <class 'integration.smoke.test_vpc_vpn.TestRVPCSite2SiteVpn'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/suite.py", line 209, in run
    self.setUp()
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/util.py", line 471, in try_run
    return func()
  File "/data/git/cs1/cloudstack/test/integration/smoke/test_vpc_vpn.py", line 835, in setUpClass
    cls.template.download(cls.apiclient)
  File "/usr/lib/python2.7/site-packages/marvin/lib/base.py", line 1350, in download
    elif 'Downloaded' in template.status:
TypeError: argument of type 'NoneType' is not iterable
----------------------------------------------------------------------
Additional details in: /tmp/MarvinLogs/test_network_71Q19A/results.txt
```

```
ERROR: test suite for <class 'integration.smoke.test_vpc_vpn.TestVpcRemoteAccessVpn'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/suite.py", line 209, in run
    self.setUp()
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/util.py", line 471, in try_run
    return func()
  File "/data/git/cs1/cloudstack/test/integration/smoke/test_vpc_vpn.py", line 293, in setUpClass
    cls.template.download(cls.apiclient)
  File "/usr/lib/python2.7/site-packages/marvin/lib/base.py", line 1350, in download
    elif 'Downloaded' in template.status:
TypeError: argument of type 'NoneType' is not iterable
----------------------------------------------------------------------
Additional details in: /tmp/MarvinLogs/test_network_71Q19A/results.txt
```

```
ERROR: test suite for <class 'integration.smoke.test_vpc_vpn.TestVpcSite2SiteVpn'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/suite.py", line 209, in run
    self.setUp()
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/util.py", line 471, in try_run
    return func()
  File "/data/git/cs1/cloudstack/test/integration/smoke/test_vpc_vpn.py", line 472, in setUpClass
    cls.template.download(cls.apiclient)
  File "/usr/lib/python2.7/site-packages/marvin/lib/base.py", line 1350, in download
    elif 'Downloaded' in template.status:
TypeError: argument of type 'NoneType' is not iterable
----------------------------------------------------------------------
Additional details in: /tmp/MarvinLogs/test_network_71Q19A/results.txt
```



**Associated Uploads**

**`/tmp/MarvinLogs/DeployDataCenter__May_24_2016_06_32_26_Y962ID:`**
* [dc_entries.obj](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1556/tmp/MarvinLogs/DeployDataCenter__May_24_2016_06_32_26_Y962ID/dc_entries.obj)
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1556/tmp/MarvinLogs/DeployDataCenter__May_24_2016_06_32_26_Y962ID/failed_plus_exceptions.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1556/tmp/MarvinLogs/DeployDataCenter__May_24_2016_06_32_26_Y962ID/runinfo.txt)

**`/tmp/MarvinLogs/test_network_71Q19A:`**
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1556/tmp/MarvinLogs/test_network_71Q19A/failed_plus_exceptions.txt)
* [results.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1556/tmp/MarvinLogs/test_network_71Q19A/results.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1556/tmp/MarvinLogs/test_network_71Q19A/runinfo.txt)

**`/tmp/MarvinLogs/test_vpc_routers_X3MOBD:`**
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1556/tmp/MarvinLogs/test_vpc_routers_X3MOBD/failed_plus_exceptions.txt)
* [results.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1556/tmp/MarvinLogs/test_vpc_routers_X3MOBD/results.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1556/tmp/MarvinLogs/test_vpc_routers_X3MOBD/runinfo.txt)


Uploads will be available until `2016-07-24 02:00:00 +0200 CEST`

*Comment created by [`upr comment`](https://github.com/cloudops/upr).*

**Comment by swill** [comment]
This is a clean run.  The errors here are not related to this PR.  I will merge this.  Thanks...

**Pull request merged**
