### PR TITLE
security_group.py: fix NameError: name 'd' is not defined

### PR DESCRIPTION
**Pull request by ustcweizhou**
## Description

in agent.log on a host running with cloudstack 4.14.0.0-SNAPSHOT, it gives error
```
Traceback (most recent call last):
  File "/usr/share/cloudstack-common/scripts/vm/network/security_group.py", line 1272, in <module>
    get_rule_logs_for_vms()
  File "/usr/share/cloudstack-common/scripts/vm/network/security_group.py", line 758, in get_rule_logs_for_vms
    vms = virshlist(state)
  File "/usr/share/cloudstack-common/scripts/vm/network/security_group.py", line 104, in virshlist
    alldomains = [d for domain in map(conn.lookupByID, conn.listDomainsID())]
  File "/usr/share/cloudstack-common/scripts/vm/network/security_group.py", line 104, in <listcomp>
    alldomains = [d for domain in map(conn.lookupByID, conn.listDomainsID())]
NameError: name 'd' is not defined
```

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by ustcweizhou** [comment]
@wido 
could you please review it ?

**Comment by rhtyd** [comment]
The changes are in SG related file that trillian doesn't test by default, can you share any confirmation of testing @ustcweizhou @wido @GabrielBrascher ?

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Tested locally, the issue is pythonic iteration. LGTM.

**Pull request merged**
