### PR TITLE
mvn: bump version ahead of next major release

### PR DESCRIPTION
**Pull request by rohityadavcloud**
Bumps version of specific dependency to latest ahead of the next major release 4.18.

### CODE REVIEW

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan test matrix

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Review by shwstppr — APPROVED** [review]

**Pull request merged**
