### PR TITLE
CLOUDSTACK-9160: Remove unused folder(s)/file(s); engine/api/src/org/…

### PR DESCRIPTION
**Pull request by borisroman**
…apache/engine/subsystem/api/storage/disktype

Empty files. Moved DiskFormat.java to engine/api/src/org/apache/engine/subsystem/api/storage/type

As a developer I want
 - a clean project to work on
 - a project with maintained code
 - a project without dead code or files

Builds ok:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6:04.428s (Wall Clock)
[INFO] Finished at: Sun Dec 13 20:25:49 CET 2015
[INFO] Final Memory: 95M/787M
[INFO] ------------------------------------------------------------------------
```

Ping @wido @DaanHoogland @remibergsma @miguelaferreira @wilderrodrigues 

Running integration tests now.

### CODE REVIEW

**Comment by rodrigo93** [comment]
Nice @borisroman, can you send it to test it again?
It seems that Jenkins is not working...

**Comment by DaanHoogland** [comment]
LGTM , I'll look at jenkins again.

**Comment by DaanHoogland** [comment]
@borisroman can you post any results if you have them? If you care you can force push to have jenkins validate the PR but as far as I can see no added value to a local build.

**Comment by rodrigo93** [comment]
LGTM based on the files, no tests were made.
What is happening with Jenkins? I noticed that many PRs are flagged with error because Jenkins did not work.
I saw in an email before that communication seems poor.

**Comment by borisroman** [comment]
Closing!

**Pull request closed without merging**
