### PR TITLE
WIP: CLOUDSTACK-9815 intergration of ApplicationClusterService

### PR DESCRIPTION
**Pull request by DaanHoogland**
this external plugin will be integrated as core plugin. It was originally created as plugin on 4.5. bouncycaste needs updating and several integration problems are still blocking a merge.

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by ustcweizhou** [comment]
awesome

@DaanHoogland  could you upload /etc/cloudstack/management/k8s-master.yml and /etc/cloudstack/management/k8s-node.yml as well ?

For the license on top of some files, will you change it ?

**Comment by DaanHoogland** [comment]
@ustcweizhou of course. It is still work in progress but all changes needed will be added in time.

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@blueorangutan help

**Comment by DaanHoogland** [comment]
@blueorangutan package centos7

**Comment by DaanHoogland** [comment]
@blueorangutan package centos7

**Comment by DaanHoogland** [comment]
@blueorangutan test centos7 kvm-centos7 component/application_clusters/test_application_cluster_life_cycle.py,component/application_clusters/test_application_cluster_provisioning.py,component/application_clusters/test_provisioning_and_deployment.py

**Comment by DaanHoogland** [comment]
@ustcweizhou @sebgoa @rhtyd can you review this as a first version of an integrated plugin for application clusters. It is still very k8s specific and I want to defer making it more generic until we found real use cases for that.

**Comment by DaanHoogland** [comment]
this branch is screwed up, it is missing essential commits that must have somehow become orphaned.

**Pull request closed without merging**
