### PR TITLE
Resource reservation framework

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR  addresses parallel resource allocation as a generalization of the problem and solution described in #6644. Instead of the Global lock on the resources a reservation record is created which is added in the resource check count in the `ResourceLimitService`/`ResourceLimitManagerImpl`.  As a convenience a `CheckedReservation` is created. This is an implementation of `AutoClosable` and can be used as a guard in a try-with-resource fashion. The close method of the `CheckedReservation` wil delete the reservation record.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

in a cloud with three Management Servers
- create a domain `limited`
- set domain limits in `limited` (for instance `user_vm == 2`)
- create an account `luser`
- create a network for `luser`
- create a first vm for this account in this network
- execute a similar script as:
```
for i in 1 2 3 4 5
do
  for  profile in first second third
  do
    cmk -p $profile deploy virtualmachine templateid=82fb9e32-291b-11ed-89fb-1e001b000173 serviceofferingid=1009e2e0-1bd1-4142-a539-1a95a2835467 zoneid=8fb4602d-87cb-4942-ad64-140a2e53d686 domainid=9676aa4b-a218-4adb-99cd-3179b9cff867 account=luser &
  done
done
```

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan test keepEnv

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
@blueorangutan test centos7  vmware65u2

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Review by borisstoyanov — APPROVED** [review]
LGTM, manually tested

**Review by weizhouapache — APPROVED** [review]

**Review by rohityadavcloud — APPROVED** [review]

**Pull request merged**
