### PR TITLE
packaging: Improve post-upgrade processing

### PR DESCRIPTION
**Pull request by rhtyd**
$1 is "2" during package upgrade in %post section, this fixes the
handling of $1 as per https://fedoraproject.org/wiki/Packaging:Scriptlets

This improves handling of $1 during %post upgrade step. Some of the
command/code are idempotent such as enabling and starting a service
and can be run without any $1 checks.

Pinging for review - @wido @DaanHoogland @abhinandanprateek @DagSonstebo and others
@blueorangutan package

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@karuturi can you consider reviewing/merging this?

**Comment by wido** [comment]
Hard for me to review this one. My main experience is DEB and RPM I am not so very familiar with. Sorry @rhtyd

**Comment by rhtyd** [comment]
Thanks @wido np

**Comment by rhtyd** [comment]
Pinging for review - @DaanHoogland @karuturi @ustcweizhou @nvazquez @K0zka and others

**Comment by rhtyd** [comment]
Merging based on test results and 1 LGTM

**Pull request merged**
