### PR TITLE
utils: fix RBD URI if credentials contains slash

### LINKED ISSUE #7673: Ceph Primary Storage: Unsupported slash character by parser
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Utils
~~~

##### CLOUDSTACK VERSION

~~~
4.18
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Current parser doesn't properly interpret a rbd:// URI with a secret containing a slash "/" character.

##### STEPS TO REPRODUCE

I've added a testcase that fails here to reproduce: https://github.com/apache/cloudstack/pull/7671

##### EXPECTED RESULTS

Unit test passes

##### ACTUAL RESULTS

Unit test fails (also silently fails on a real setup because the URL is incorrect)

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes the credentials of RBD pool which contains slashes.

see the test failures in PR #7671 
This fixes #7673

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by rohityadavcloud — APPROVED** [review]
LGTM didn't test it, but trust the unit tests

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@weizhouapache do we need more testing than the  gha and packaging?

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Pull request merged**
