### PR TITLE
[4.6.1] CLOUDSTACK-9022: keep Destroyed volumes for sometime

### PR DESCRIPTION
**Pull request by ustcweizhou**
for now, the Destroyed volumes will be expunged in Storage cleanup thread, no matter when they are destroyed.
In Expunging vm thread, we expunge the Destroyed vms which have been destroyed at least 'expunge.delay' seconds. We add the similar configuration for volumes.

same to #1029 , for 4.6

### CODE REVIEW

**Comment by wido** [comment]
I would swear I saw this code before. Dejavu moment?

**Comment by NuxRo** [comment]
@wido yes https://github.com/apache/cloudstack/pull/1144 , just PR against correct branch now

**Comment by bhaisaab** [comment]
+1 LGTM (had reviewed before)
@ustcweizhou If we merge it on 4.6 and fwd-merge on master, we won't need the PR #1029. Lastly, do you think we should put this in 4.5 branch?

**Comment by wido** [comment]
LGTM based on the code. Seems sane to me.

@bhaisaab This seems like a feature, so I don't think it's supposed to go into 4.5?

**Comment by bhaisaab** [comment]
@wido cool, it's one of the those that seemed like bugs

**Comment by remibergsma** [comment]
The integration tests show this test failing (part of test_vm_life_cycle.py):
```
Test destroy(expunge) Virtual Machine ... === TestName: test_09_expunge_vm | Status : FAILED ===
FAIL
```
Haven't seen this failing before, will run `smoke/test_vm_life_cycle.py` again to be sure.

**Comment by ustcweizhou** [comment]
@remibergsma any update ?
@wido yes, #1029 for master, and #1044 is a mistake

**Comment by wilderrodrigues** [comment]
@ustcweizhou @bhaisaab @wido 

Did you actually test this PR?

Cheers,
Wilder

**Comment by bhaisaab** [comment]
@wilderrodrigues no, just code review

**Comment by ustcweizhou** [comment]
@wilderrodrigues I just tested. 

I set the storage.cleanup.interval to 60s, the storage.cleanup.delay to 120s. 

I restored a VM, then the old volume of the vm will be in 'Destroy' state

```
mysql> select id,name,uuid,created,updated,removed,state from volumes where id=7574\G
*************************** 1. row ***************************
     id: 7574
   name: ROOT-7558
   uuid: 82c5991d-5211-4fd8-bd8b-f1285cc50574
created: 2015-11-30 08:27:36
updated: 2015-12-02 09:50:34
removed: NULL
  state: Destroy
1 row in set (0.00 sec)
```

The volume is expunged after 2-3 minutes.

```
mysql> select id,name,uuid,created,updated,removed,state from volumes where id=7574\G
*************************** 1. row ***************************
     id: 7574
   name: ROOT-7558
   uuid: 82c5991d-5211-4fd8-bd8b-f1285cc50574
created: 2015-11-30 08:27:36
updated: 2015-12-02 09:53:31
removed: 2015-12-02 09:53:31
  state: Expunged
1 row in set (0.00 sec)
```

**Comment by ustcweizhou** [comment]
@remibergsma @wilderrodrigues checked the code (java and test_vm_life_cycle.py), I think this PR is not related to the failure in integration test. Can you please run testing again?

**Comment by ustcweizhou** [comment]
test/integration/component/test_browse_volumes.py
this test might be impacted.

**Comment by wilderrodrigues** [comment]
@remibergsma  @DaanHoogland @wido @bhaisaab @ustcweizhou @karuturi @runseb @borisroman @jburwell 

If test_vm_life_cycle.py is failing because the current 4.6 and/or master is broken/unstable, we have to get it working again before any other PR gets merged. 

We cannot, for any imaginable reason, get into the situation we were at few months ago.

I will run tests against current 4.6 branch and Master to see if that's actually broken. Who can help me on testing as well?

Cheers,
Wilder

**Comment by bhaisaab** [comment]
@wilderrodrigues I'm approaching EOD today, but can help test master tomorrow.
I tested vm lifecycle manually with 4.6.1 RC1 and KVM, so I suppose 4.6 should be stable.

**Comment by wilderrodrigues** [comment]
Thanks, @bhaisaab!

I will test it and and also see if I have time tomorrow to run the same tests agains this PR. We need to be 100% sure that it works on both branches and with this PR.

Cheers,
Wilder

**Comment by wilderrodrigues** [comment]
Ping @remibergsma @DaanHoogland @ustcweizhou @bhaisaab 

The test fails on latest 4.6 branch!

```
=== TestName: test_01_stop_vm | Status : SUCCESS ===

=== TestName: test_02_start_vm | Status : SUCCESS ===

=== TestName: test_03_reboot_vm | Status : SUCCESS ===

=== TestName: test_06_destroy_vm | Status : SUCCESS ===

=== TestName: test_07_restore_vm | Status : SUCCESS ===

=== TestName: test_09_expunge_vm | Status : FAILED ===
```

And here is the failure:

```
2015-12-02 14:12:47,260 - CRITICAL - FAILED: test_09_expunge_vm: ['Traceback (most recent call last):\n', '  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run\n    testMethod()\n', '  File "/data/git/cs2/cloudstack/test/integration/smoke/test_vm_life_cycle.py", line 646, in test_09_expunge_vm\n    self.assertEqual(list_vm_response,None,"Check Expunged virtual machine is in listVirtualMachines response")\n', '  File "/usr/lib64/python2.7/unittest/case.py", line 553, in assertEqual\n    assertion_func(first, second, msg=msg)\n', '  File "/usr/lib64/python2.7/unittest/case.py", line 546, in _baseAssertEqual\n    raise self.failureException(msg)\n', 'AssertionError: Check Expunged virtual machine is in listVirtualMachines response\n']

/tmp//MarvinLogs//Dec_02_2015_13_33_23_C9WHUF/failed_plus_exceptions.txt (END)
```


Cheers,
Wilder

**Comment by wilderrodrigues** [comment]
Okay... no panic! I might have been some expunge global settings that is deployed on all of our test  environments. It has been reverted and I will run the tests again.

Cheers,
Wilder

**Comment by remibergsma** [comment]
@ustcweizhou Took me a while, but the issue is not in this PR. Will post test results soon.

**Comment by remibergsma** [comment]
LGTM based on these tests:

```
nosetests --with-marvin --marvin-config=${marvinCfg} -s -a tags=advanced,required_hardware=true \
component/test_vpc_redundant.py \
component/test_routers_iptables_default_policy.py \
component/test_routers_network_ops.py \
component/test_vpc_router_nics.py \
smoke/test_loadbalance.py \
smoke/test_internal_lb.py \
smoke/test_ssvm.py \
smoke/test_network.py

```

Result:

```
Test iptables default INPUT/FORWARD policies on VPC router ... === TestName: test_01_single_VPC_iptables_policies | Status : SUCCESS ===
ok
Test redundant router internals ... === TestName: test_01_isolate_network_FW_PF_default_routes_egress_true | Status : SUCCESS ===
ok
Test redundant router internals ... === TestName: test_02_isolate_network_FW_PF_default_routes_egress_false | Status : SUCCESS ===
ok
Test redundant router internals ... === TestName: test_01_RVR_Network_FW_PF_SSH_default_routes_egress_true | Status : SUCCESS ===
ok
Test redundant router internals ... === TestName: test_02_RVR_Network_FW_PF_SSH_default_routes_egress_false | Status : SUCCESS ===
ok
Create a VPC with two networks with one VM in each network and test nics after destroy ... === TestName: test_01_VPC_nics_after_destroy | Status : SUCCESS ===
ok
Create a VPC with two networks with one VM in each network and test default routes ... === TestName: test_02_VPC_default_routes | Status : SUCCESS ===
ok
Check the password file in the Router VM ... === TestName: test_isolate_network_password_server | Status : SUCCESS ===
ok
Check that the /etc/dhcphosts.txt doesn't contain duplicate IPs ... === TestName: test_router_dhcphosts | Status : SUCCESS ===
ok
Test to create Load balancing rule with source NAT ... === TestName: test_01_create_lb_rule_src_nat | Status : SUCCESS ===
ok
Test to create Load balancing rule with non source NAT ... === TestName: test_02_create_lb_rule_non_nat | Status : SUCCESS ===
ok
Test for assign & removing load balancing rule ... === TestName: test_assign_and_removal_lb | Status : SUCCESS ===
ok
Test to verify access to loadbalancer haproxy admin stats page ... === TestName: test02_internallb_haproxy_stats_on_all_interfaces | Status : SUCCESS ===
ok
Test create, assign, remove of an Internal LB with roundrobin http traffic to 3 vm's ... === TestName: test_01_internallb_roundrobin_1VPC_3VM_HTTP_port80 | Status : SUCCESS ===
ok
Test SSVM Internals ... === TestName: test_03_ssvm_internals | Status : SUCCESS ===
ok
Test CPVM Internals ... === TestName: test_04_cpvm_internals | Status : SUCCESS ===
ok
Test stop SSVM ... === TestName: test_05_stop_ssvm | Status : SUCCESS ===
ok
Test stop CPVM ... === TestName: test_06_stop_cpvm | Status : SUCCESS ===
ok
Test reboot SSVM ... === TestName: test_07_reboot_ssvm | Status : SUCCESS ===
ok
Test reboot CPVM ... === TestName: test_08_reboot_cpvm | Status : SUCCESS ===
ok
Test destroy SSVM ... === TestName: test_09_destroy_ssvm | Status : SUCCESS ===
ok
Test destroy CPVM ... === TestName: test_10_destroy_cpvm | Status : SUCCESS ===
ok
Test Remote Access VPN in VPC ... === TestName: test_vpc_remote_access_vpn | Status : SUCCESS ===
ok
Test VPN in VPC ... === TestName: test_vpc_site2site_vpn | Status : SUCCESS ===
ok
Test for port forwarding on source NAT ... === TestName: test_01_port_fwd_on_src_nat | Status : SUCCESS ===
ok
Test for port forwarding on non source NAT ... === TestName: test_02_port_fwd_on_non_src_nat | Status : SUCCESS ===
ok
Test for reboot router ... === TestName: test_reboot_router | Status : SUCCESS ===
ok
Test for Router rules for network rules on acquired public IP ... === TestName: test_network_rules_acquired_public_ip_1_static_nat_rule | Status : SUCCESS ===
ok
Test for Router rules for network rules on acquired public IP ... === TestName: test_network_rules_acquired_public_ip_2_nat_rule | Status : SUCCESS ===
ok
Test for Router rules for network rules on acquired public IP ... === TestName: test_network_rules_acquired_public_ip_3_Load_Balancer_Rule | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 33 tests in 16226.348s

OK
```


And:

```
nosetests --with-marvin --marvin-config=${marvinCfg} -s -a tags=advanced,required_hardware=false \
smoke/test_routers.py \
smoke/test_network_acl.py \
smoke/test_privategw_acl.py \
smoke/test_reset_vm_on_reboot.py \
smoke/test_vm_life_cycle.py \
smoke/test_vpc_vpn.py \
smoke/test_service_offerings.py \
component/test_vpc_offerings.py \
component/test_vpc_routers.py
```

Result:

```
Test router internal advanced zone ... === TestName: test_02_router_internal_adv | Status : SUCCESS ===
ok
Test restart network ... === TestName: test_03_restart_network_cleanup | Status : SUCCESS ===
ok
Test router basic setup ... === TestName: test_05_router_basic | Status : SUCCESS ===
ok
Test router advanced setup ... === TestName: test_06_router_advanced | Status : SUCCESS ===
ok
Test stop router ... === TestName: test_07_stop_router | Status : SUCCESS ===
ok
Test start router ... === TestName: test_08_start_router | Status : SUCCESS ===
ok
Test reboot router ... === TestName: test_09_reboot_router | Status : SUCCESS ===
ok
test_privategw_acl (integration.smoke.test_privategw_acl.TestPrivateGwACL) ... === TestName: test_privategw_acl | Status : SUCCESS ===
ok
Test reset virtual machine on reboot ... === TestName: test_01_reset_vm_on_reboot | Status : SUCCESS ===
ok
Test advanced zone virtual router ... === TestName: test_advZoneVirtualRouter | Status : SUCCESS ===
ok
Test Deploy Virtual Machine ... === TestName: test_deploy_vm | Status : SUCCESS ===
ok
Test Multiple Deploy Virtual Machine ... === TestName: test_deploy_vm_multiple | Status : SUCCESS ===
ok
Test Stop Virtual Machine ... === TestName: test_01_stop_vm | Status : SUCCESS ===
ok
Test Start Virtual Machine ... === TestName: test_02_start_vm | Status : SUCCESS ===
ok
Test Reboot Virtual Machine ... === TestName: test_03_reboot_vm | Status : SUCCESS ===
ok
Test destroy Virtual Machine ... === TestName: test_06_destroy_vm | Status : SUCCESS ===
ok
Test recover Virtual Machine ... === TestName: test_07_restore_vm | Status : SUCCESS ===
ok
Test migrate VM ... === TestName: test_08_migrate_vm | Status : SUCCESS ===
ok
Test destroy(expunge) Virtual Machine ... === TestName: test_09_expunge_vm | Status : SUCCESS ===
ok
Test to create service offering ... === TestName: test_01_create_service_offering | Status : SUCCESS ===
ok
Test to update existing service offering ... === TestName: test_02_edit_service_offering | Status : SUCCESS ===
ok
Test to delete service offering ... === TestName: test_03_delete_service_offering | Status : SUCCESS ===
ok
Test for delete account ... === TestName: test_delete_account | Status : SUCCESS ===
ok
Test for Associate/Disassociate public IP address for admin account ... === TestName: test_public_ip_admin_account | Status : SUCCESS ===
ok
Test for Associate/Disassociate public IP address for user account ... === TestName: test_public_ip_user_account | Status : SUCCESS ===
ok
Test for release public IP address ... === TestName: test_releaseIP | Status : SUCCESS ===
ok
Test create VPC offering ... === TestName: test_01_create_vpc_offering | Status : SUCCESS ===
ok
Test VPC offering without load balancing service ... === TestName: test_03_vpc_off_without_lb | Status : SUCCESS ===
ok
Test VPC offering without static NAT service ... === TestName: test_04_vpc_off_without_static_nat | Status : SUCCESS ===
ok
Test VPC offering without port forwarding service ... === TestName: test_05_vpc_off_without_pf | Status : SUCCESS ===
ok
Test VPC offering with invalid services ... === TestName: test_06_vpc_off_invalid_services | Status : SUCCESS ===
ok
Test update VPC offering ... === TestName: test_07_update_vpc_off | Status : SUCCESS ===
ok
Test list VPC offering ... === TestName: test_08_list_vpc_off | Status : SUCCESS ===
test_09_create_redundant_vpc_offering (integration.component.test_vpc_offerings.TestVPCOffering) ... === TestName: test_09_create_redundant_vpc_offering | Status : SUCCESS ===
ok
Test start/stop of router after addition of one guest network ... === TestName: test_01_start_stop_router_after_addition_of_one_guest_network | Status : SUCCESS ===
ok
Test reboot of router after addition of one guest network ... === TestName: test_02_reboot_router_after_addition_of_one_guest_network | Status : SUCCESS ===
ok
Test to change service offering of router after addition of one guest network ... === TestName: test_04_chg_srv_off_router_after_addition_of_one_guest_network | Status : SUCCESS ===
ok
Test destroy of router after addition of one guest network ... === TestName: test_05_destroy_router_after_addition_of_one_guest_network | Status : SUCCESS ===
ok
Test to stop and start router after creation of VPC ... === TestName: test_01_stop_start_router_after_creating_vpc | Status : SUCCESS ===
ok
Test to reboot the router after creating a VPC ... === TestName: test_02_reboot_router_after_creating_vpc | Status : SUCCESS ===
ok
Tests to change service offering of the Router after ... === TestName: test_04_change_service_offerring_vpc | Status : SUCCESS ===
ok
Test to destroy the router after creating a VPC ... === TestName: test_05_destroy_router_after_creating_vpc | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 42 tests in 8427.761s

OK
```

Haven't tested the actual functionality, this just shows you didn't break anything else.

**Pull request merged**
