### PR TITLE
FIX issue in VR if remote access vpn is enabled

### PR DESCRIPTION
**Pull request by ravening**
## Description

Use both tcp protocol and module so that
vpn is enabled properly

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@ravening can you give this a priority? as we are in code freeze, do we need this before 4.15?

**Comment by ravening** [comment]
> @ravening can you give this a priority? as we are in code freeze, do we need this before 4.15?

@DaanHoogland yes its good to have this before 4.15 as its a bug fix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
looks good but i am not sure why protocol would improve on the vpn instead of just restrict it. no regressions so i'm fine with it.

**Review by rhtyd — APPROVED** [review]
LGTM - though I'm not sure adding the protocol tcp (instead of matcher tcp) makes any difference, I'm not sure what/how it fixes the issue; LGTM as no regression seen in tests

**Review by weizhouapache — APPROVED** [review]
this should be good.

**Pull request merged**
