### PR TITLE
UI: Fixes switching between domains with SAML user

### PR DESCRIPTION
**Pull request by utchoang**
### Description

Fixes: #5618 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by DaanHoogland** [comment]
@utchoang both scenarios from issue #5618  remain unchanged.  I see how this logic would be needed, but it looks like it is not enough, the menu is not reloaded.

**Comment by utchoang** [comment]
@sureshanaparti @DaanHoogland cc @shwstppr This PR is not ready for review.

**Review by shwstppr — APPROVED** [review]
Code LGTM. Have not tested

**Comment by sureshanaparti** [comment]
> @sureshanaparti @DaanHoogland cc @shwstppr This PR is not ready for review. Related [#5618 (comment)](https://github.com/apache/cloudstack/issues/5618#issuecomment-1011944596)

ok @utchoang let us know once the PR is ready.

**Comment by DaanHoogland** [comment]
if you think it is ready @utchoang , we can merge (2lgtm+tests)

**Comment by utchoang** [comment]
@DaanHoogland Yes, if you tested it and it works fine then it's ready for merge.

**Review by shwstppr — APPROVED** [review]

**Comment by sureshanaparti** [comment]
> @DaanHoogland Yes, if you tested it and it works fine then it's ready for merge.

@adrianopaterlini tested this, and updated details in the issue #5618

**Pull request merged**
