### PR TITLE
db: make *_details.value non-nullable

### LINKED ISSUE #4897: Eliminate *_details table inconsistency
Different details tables in cloud database have different structure. While some (specifically) allow inserting details with NULL value others do not. This creates issues when data needs to be copied from one to another, similar to #4628 

```
mysql> describe user_vm_details;
+---------+-----------------+------+-----+---------+----------------+
| Field   | Type            | Null | Key | Default | Extra          |
+---------+-----------------+------+-----+---------+----------------+
| id      | bigint unsigned | NO   | PRI | NULL    | auto_increment |
| vm_id   | bigint unsigned | NO   | MUL | NULL    |                |
| name    | varchar(255)    | NO   |     | NULL    |                |
| value   | varchar(5120)   | YES  |     | NULL    |                |
| display | tinyint(1)      | NO   |     | 1       |                |
+---------+-----------------+------+-----+---------+----------------+
5 rows in set (0.00 sec)

mysql> describe vm_template_details;
+-------------+-----------------+------+-----+---------+----------------+
| Field       | Type            | Null | Key | Default | Extra          |
+-------------+-----------------+------+-----+---------+----------------+
| id          | bigint unsigned | NO   | PRI | NULL    | auto_increment |
| template_id | bigint unsigned | NO   | MUL | NULL    |                |
| name        | varchar(255)    | NO   |     | NULL    |                |
| value       | varchar(1024)   | NO   |     | NULL    |                |
| display     | tinyint(1)      | NO   |     | 1       |                |
+-------------+-----------------+------+-----+---------+----------------+
5 rows in set (0.00 sec)
```
To prevent such issues structure of these details table should be consistent and shouldn't accept details with NULL values.
Discussed in #4794

##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
DB
~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### CONFIGURATION

NA

##### OS / ENVIRONMENT

NA

##### SUMMARY

As above

##### STEPS TO REPRODUCE

~~~
1. Deploy a VM
2. Add a VM detail with a null value
3. Create a template from ROOT disk of the VM
~~~

##### EXPECTED RESULTS

~~~
Template created successfully
~~~

##### ACTUAL RESULTS

~~~
Template creation fails
~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #4897
Some details tables were allowing null values for detail value which can cause NPE in some cases.
```
mysql> SELECT TABLE_NAME, COLUMN_NAME, COLUMN_TYPE FROM information_schema.columns WHERE table_schema='cloud' AND table_name LIKE'%_details' AND column_name='value' AND IS_NULLABLE='YES';
+-------------------------------+-------------+---------------+
| TABLE_NAME                    | COLUMN_NAME | COLUMN_TYPE   |
+-------------------------------+-------------+---------------+
| account_details               | value       | varchar(255)  |
| cluster_details               | value       | varchar(255)  |
| data_center_details           | value       | varchar(1024) |
| domain_details                | value       | varchar(255)  |
| image_store_details           | value       | varchar(255)  |
| storage_pool_details          | value       | varchar(255)  |
| template_deploy_as_is_details | value       | text          |
| user_vm_deploy_as_is_details  | value       | text          |
| user_vm_details               | value       | varchar(5120) |
+-------------------------------+-------------+---------------+
9 rows in set (0.00 sec)
```

Brings consistency for value column of *_details tables with preventing null values.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Review by nvazquez — APPROVED** [review]
Code LGTM. I'm not aware of any case that will attempt to add a detail key with a null value on these tables

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by shwstppr** [comment]
@blueorangutan test

**Review by DaanHoogland — APPROVED** [review]

**Review by rhtyd — APPROVED** [review]
LGTM - needs testing

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by nvazquez** [comment]
@shwstppr can you please solve the conflict?

**Review by GabrielBrascher — APPROVED** [review]
Code LGTM. I am +1 in having non-null values and I don't see any way of this PR causing regression issues.

However, I could not find why/how these values have been set to NULL.
Some of them seem to be created as `NOT NULL` values (see [reate-schema.sql](https://github.com/apache/cloudstack/blob/28e70c0a2a709c10edeba01e04d9eb606cf4c1f8/setup/db/create-schema.sql#L1141)).
On the other hand, I could indeed find a case where the field was created without `NOT NULL`, such as `template_deploy_as_is_details` created in [schema-41400to41500.sql](https://github.com/apache/cloudstack/blob/bf6266188c89a5487383f216333ae10e878d2c10/engine/schema/src/main/resources/META-INF/db/schema-41400to41500.sql#L550).

Probably something that I am missing. Maybe a DB table change via Java or an upgrade `schema-4XYto4XY+1.sql ` that would change values to NULL.

Has anyone mapped the cause of these NULL values? This question is just to avoid it happening again in the future.

**Comment by shwstppr** [comment]
@GabrielBrascher Some tables may have been altered using upgrade SQL (very old change, not much there in commit message - https://github.com/apache/cloudstack/commit/c11dbad9c9b), https://github.com/apache/cloudstack/blob/main/engine/schema/src/main/resources/META-INF/db/schema-410to420.sql#L1873-L1876

Others were created without NOT NULL constraint. Not sure if was for some use-case or an oversight
https://github.com/apache/cloudstack/blob/main/engine/schema/src/main/resources/META-INF/db/schema-41000to41100.sql#L576-L583
https://github.com/apache/cloudstack/blob/main/engine/schema/src/main/resources/META-INF/db/schema-41400to41500.sql#L555-L562

@blueorangutan package

**Comment by GabrielBrascher** [comment]
@shwstppr looks like a couple of legacy SQL upgrades then, thanks for checking it.
This PR LGTM :+1:

**Comment by nvazquez** [comment]
@blueorangutan test

**Pull request merged**
