### PR TITLE
Reset unusable db connections

### PR DESCRIPTION
**Pull request by mrog**
### Description

This PR...

When the management service detects a broken database connection, it didn't do anything about it.  It already has code to reset the connection, but that doesn't get used.  This change causes the connection to be reset after it's found to be unusable.

See https://github.com/apache/cloudstack/issues/6724 for repro steps

Fixes: 6724

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [X] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

The instructions in INSTALL.md are incomplete or outdated.  I was able to get the project to build, but I haven't been able to test my change.  See https://github.com/apache/cloudstack/issues/6726.

### CODE REVIEW

**Comment by rohityadavcloud** [comment]
Thanks @mrog for the PR, sounds like good find, let us kick some regression tests.
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan test matrix

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Review by shwstppr — APPROVED** [review]

**Comment by shwstppr** [comment]
Previous Travis failures seem unrelated. Will check with 4.17.1 health check. Merging this.

**Pull request merged**
