### PR TITLE
Backports for 4.11 branch

### PR DESCRIPTION
**Pull request by rhtyd**
## Description

This PR has backported changes/PRs merged on master that we can consider for 4.11, limiting to fixes and no features.

I've few more PRs, please advise if we should backport:
https://github.com/apache/cloudstack/pull/2499
https://github.com/apache/cloudstack/pull/2401
https://github.com/apache/cloudstack/pull/2574
https://github.com/apache/cloudstack/pull/2387
https://github.com/apache/cloudstack/pull/2414 (tagged bugfix)
https://github.com/apache/cloudstack/pull/2404 (tagged bugfix)
https://github.com/apache/cloudstack/pull/2443 (tagged bugfix)

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
Testing
- [ ] I have added tests to cover my changes.
- [x] All relevant new and existing integration tests have passed.
- [ ] A full integration testsuite with all test that can run on my environment has passed.

### CODE REVIEW

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by rafaelweingartner** [comment]
@rhtyd I backported most of the bug PRs I created to master here. There were only two that I did not consider because of the volume of changes that I have there.

**Comment by rhtyd** [comment]
Thanks @rafaelweingartner that's great. Can you check travis, looks like some build errors have occurred. I'll kick tests once travis is green.

**Comment by rafaelweingartner** [comment]
@rhtyd Travis was not passing because of some problems that were created after the `cherry-pick`. I have fixed them, and now everything seems to be fine.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rafaelweingartner** [comment]
@rhtyd I think we should proceed and merge as soon as test results are fine here. There are already a big amount of changes. It is easy to get lost and let things slip through in this volume of changes.

**Comment by rhtyd** [comment]
@rafaelweingartner sure, given these changes are already reviewed and tested on master. If tests are fine, I'll merge them on 4.11 and then forward merge on master using `-X ours` to perform an empty forward merge and ignore changes from this backport PR.

**Comment by rafaelweingartner** [comment]
Awesome. thanks.
Just watch-out that the branch 4.11 might have merged PRs that were not forwarded to master yet. Therefore, it might be good to check it before "merging" this one forward.

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan test centos7 xenserver-71

**Comment by rhtyd** [comment]
I looked at the reported errors, none of them are PR related, but either issue with the PR itself or network/env issue. I'll fix some tests in a separate PR.
I'll do a squash merge, after check 4.11 branch and doing any fwd-merge. Then merge this PR from 4.11 onto master with `-X ours` since the backported changes are already on master.

**Pull request merged**
