### PR TITLE
cleanup: kvm-storage - fix misleading error log

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Discussed here, https://github.com/apache/cloudstack/issues/5309#issuecomment-898330887
Log is not actually an ERROR level log.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by rhtyd — APPROVED** [review]

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by nvazquez — APPROVED** [review]
LGTM

**Comment by nvazquez** [comment]
@blueorangutan test

**Review by sureshanaparti — APPROVED** [review]
@shwstppr thanks for updating the log level here. clgtm.

**Review by rhtyd — APPROVED** [review]

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by nvazquez** [comment]
@blueorangutan test

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
Merging based on lgtms and Travis job 1, trivial log only change

**Pull request merged**
