### PR TITLE
Fix "agent-lb" project

### PR DESCRIPTION
**Pull request by rafaelweingartner**
@DaanHoogland, @rhtyd, and @nvazquez can you take a look here?

When PR #2469 got merged forward, the parent pom version was not updated.

### CODE REVIEW

**Comment by DaanHoogland** [comment]
sounds like a bug in the git-merge-fwd script, @rafaelweingartner . will have a look

**Comment by rafaelweingartner** [comment]
As soon as travis and Jenkins are green, do we need the integration tests?

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rafaelweingartner** [comment]
Are these errors something that we need to take a look into? No code has been changed here.

**Pull request merged**
