### PR TITLE
UI: Fix delete ISO navigation after job is finished

### PR DESCRIPTION
**Pull request by nvazquez**
### Description

This PR fixes the navigation for ISOs after deletion. The following issues are addressed:
- After removal of an ISO without bulk operation -> The view keeps displaying the data of the removed ISO
- After removal of an ISO selecting bulk operation -> The view redirects to the 404 exception view

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### How Has This Been Tested?
The following scenarios were tested on a single zone:
- Delete ISO without selecting any zone -> After removal, the ISO view is displayed
- Delete ISO selecting the zone and clicking on 'Bulk operation' -> After removal, the ISO view is displayed

### CODE REVIEW

**Review by utchoang — APPROVED** [review]

**Review by utchoang — APPROVED** [review]
LGTM!

**Review by DaanHoogland — APPROVED** [review]
tested in qa, lgtm

**Review by shwstppr — COMMENTED** [review]
@nvazquez I see an issue with this. After iso is deleted view is correctly moved iso list view but if I press back there then 404 is seen as this is adding item to the stack

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
so we should remove from the history @shwstppr ?

**Comment by shwstppr** [comment]
@rohityadavcloud yes, instead of pushing new route maybe we can replace or rather use something like `$router.go(-2)` when `$router.go(-1)` isn't resolvable

**Comment by slavkap** [comment]
We discussed offline with @nvazquez for a few scenarios in which the 404 page shows again.

**Comment by nvazquez** [comment]
@shwstppr @utchoang do you know how to deal with 404 error when closing the bulk operation dialog? This 404 error is shown while the delete operation is in progress, after the delete finishes then it redirects correctly to the ISOs view

**Comment by shwstppr** [comment]
I think the 404 error can be prevented by checking the result of navigation while moving back from a view. With following changes I was able to see the difference 
```
diff --git a/ui/src/views/image/IsoZones.vue b/ui/src/views/image/IsoZones.vue
index 7ca07ebb4b..74f4e39add 100644
--- a/ui/src/views/image/IsoZones.vue
+++ b/ui/src/views/image/IsoZones.vue
@@ -340,6 +340,13 @@ export default {
       this.selectedRowKeys = []
       this.fetchData()
       if (this.dataSource.length === 0) {
+        this.moveToPreviousView()
+      }
+    },
+    async moveToPreviousView () {
+      const lastPath = this.$router.currentRoute.value.fullPath
+      const navigationResult = await this.$router.go(-1)
+      if (navigationResult !== undefined || this.$router.currentRoute.value.fullPath === lastPath) {
         this.$router.go(-1)
       }
     },
@@ -379,7 +386,7 @@ export default {
           successMethod: result => {
             if (singleZone) {
               if (this.selectedItems.length === 0) {
-                this.$router.go(-1)
+                this.moveToPreviousView()
               }
             } else {
               if (this.selectedItems.length === 0) {
@@ -388,6 +395,9 @@ export default {
             }
             if (this.selectedItems.length > 0) {
               eventBus.emit('update-resource-state', { selectedItems: this.selectedItems, resource: record.zoneid, state: 'success' })
+              if (this.selectedItems.length === this.zones.length) {
+                this.moveToPreviousView()
+              }
             }
           },
           errorMethod: () => {
```

**Comment by nvazquez** [comment]
Thanks @shwstppr @slavkap, I think the issue is solved after applying @shwstppr's fix and a minor tweak to it, can you re-review?

**Comment by rohityadavcloud** [comment]
@shwstppr is this ready for merging?

**Review by shwstppr — APPROVED** [review]

**Pull request merged**
