### PR TITLE
CLOUDSTACK-8889: delete volume doesnt decrement primary store resource count

### PR DESCRIPTION
**Pull request by karuturi**
Primary Storage count for an account does not decrease when a Data Disk
is deleted belonging to the account unless the VM to which volume
belonged is destroyed

The resource counts are updated even before the disk is actually deleted
resulting in the same value.
Moved the resource counts updation to after the expunge operation as
thats when the disk is actually deleted.

Testing:
 Earlier, test_create_multiple_volumes in test/integration/component/test_ps_limits.py failed  with error AssertionError: Resource count 37 should match with the expected resource count 32

Before

Test create multiple volumes ... === TestName: test_create_multiple_volumes_1_root_domain_admin | Status : FAILED ===
FAIL
Test create multiple volumes ... === TestName: test_create_multiple_volumes_2_child_domain_admin | Status : FAILED ===
FAIL

After the Fix

Test create multiple volumes ... === TestName: test_create_multiple_volumes_1_root_domain_admin | Status : SUCCESS ===
ok
Test create multiple volumes ... === TestName: test_create_multiple_volumes_2_child_domain_admin | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 2 tests in 334.823s

OK

### CODE REVIEW

**Comment by koushik-das** [comment]
LGTM

**Comment by borisroman** [comment]
@karuturi @remibergsma Is this still actual? If so, could you please rebase? I'll then test it and it can be a bugfix for 4.6 :)

**Comment by karuturi** [comment]
@borisroman yes this is real :) . I think this might exist in 4.5 as well. Haven't tested it there.
I rebased with the current master

**Comment by borisroman** [comment]
@remibergsma @karuturi I tested this PR with the changes in #979. Results:

```
nosetests --with-marvin --marvin-config=/data/shared/marvin/mct-zone1-kvm1-basic.cfg -s -a tags=basic,required_hardware=false smoke/test_vm_life_cycle.py
```
```
==== Marvin Init Started ====

=== Marvin Parse Config Successful ===

=== Marvin Setting TestData Successful===

==== Log Folder Path: /tmp//MarvinLogs//Oct_26_2015_09_55_20_4UDZRZ. All logs will be available here ====

=== Marvin Init Logging Successful===

==== Marvin Init Successful ====
=== TestName: test_deploy_vm | Status : SUCCESS ===

=== TestName: test_deploy_vm_multiple | Status : SUCCESS ===

=== TestName: test_01_stop_vm | Status : SUCCESS ===

=== TestName: test_02_start_vm | Status : SUCCESS ===

=== TestName: test_03_reboot_vm | Status : SUCCESS ===

=== TestName: test_06_destroy_vm | Status : SUCCESS ===

=== TestName: test_07_restore_vm | Status : SUCCESS ===

=== TestName: test_09_expunge_vm | Status : SUCCESS ===

===final results are now copied to: /tmp//MarvinLogs/test_vm_life_cycle_2GU6K4===
```
```
nosetests --with-marvin --marvin-config=/data/shared/marvin/mct-zone1-kvm1-basic.cfg -s -a tags=basic,required_hardware=false component/test_ps_limits.py 
```
```
==== Marvin Init Started ====

=== Marvin Parse Config Successful ===

=== Marvin Setting TestData Successful===

==== Log Folder Path: /tmp//MarvinLogs//Oct_26_2015_10_19_51_ZY3KD5. All logs will be available here ====

=== Marvin Init Logging Successful===

==== Marvin Init Successful ====
=== TestName: test_assign_vm_different_account_1_root_domain_admin | Status : SUCCESS ===

=== TestName: test_assign_vm_different_account_2_child_domain_admin | Status : SUCCESS ===

=== TestName: test_attach_detach_volume_1_root_domain_admin | Status : SUCCESS ===

=== TestName: test_attach_detach_volume_2_child_domain_admin | Status : SUCCESS ===

=== TestName: test_create_multiple_volumes_1_root_domain_admin | Status : SUCCESS ===

=== TestName: test_create_multiple_volumes_2_child_domain_admin | Status : SUCCESS ===

=== TestName: test_deploy_multiple_vm_1_root_domain_admin | Status : SUCCESS ===

=== TestName: test_deploy_multiple_vm_2_child_domain_admin | Status : SUCCESS ===

=== TestName: test_stop_start_vm_1_root_domain_admin | Status : SUCCESS ===

=== TestName: test_stop_start_vm_2_child_domain_admin | Status : SUCCESS ===

===final results are now copied to: /tmp//MarvinLogs/test_ps_limits_0E1HFP===
```

Based on the test: LGTM :+1:

**Comment by borisroman** [comment]
@karuturi Jenkins failed;

[ERROR] Error in Cobertura Report generation: Unable to execute Cobertura.

Could maybe force push again?

**Comment by karuturi** [comment]
3rd attempt. I hope it succeeds this time.

**Comment by wilderrodrigues** [comment]
Ping @karuturi @remibergsma ... time to get this on in? :)

Cheers,
Wilder

**Pull request merged**
