### PR TITLE
[4.11] Smoketest Health Check

### PR DESCRIPTION
**Pull request by yadvr**
This is a dummy PR to run smoke/component tests on master branch towards the 4.11 release.
@blueorangutan package

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@mike-tutkowski the `test_change_service_offering_for_vm_with_snapshots` fails repeatedly now /cc @rafaelweingartner @DaanHoogland @borisstoyanov and others
See marvin failures logs rom the test job above. I'm investigating a fix as well.
See the management server logs attached:
[ms-err.log](https://github.com/apache/cloudstack/files/1631145/ms-err.log)

**Comment by rafaelweingartner** [comment]
What is this test trying to achieve?
I am seeing this "error":
```
2018-01-15 09:39:58,710 ERROR [c.c.s.VolumeApiServiceImpl] (Work-Job-Executor-59:ctx-d58caf82 job-2505/job-2506 ctx-89d8d0fa) (logid:7c2d2191)  For ROOT volume resize VM should be in Power Off state.
2018-01-15 09:39:58,713 DEBUG [c.c.u.d.T.Transaction] (Work-Job-Executor-59:ctx-d58caf82 job-2505/job-2506 ctx-89d8d0fa) (logid:7c2d2191) Rolling back the transaction: Time = 14 Name =  Work-Job-Executor-59; called by -TransactionLegacy.rollback:889-TransactionLegacy.removeUpTo:832-TransactionLegacy.close:656-Transaction.execute:43-VMSnapshotManagerImpl.orchestrateRevertToVMSnapshot:847-VMSnapshotManagerImpl.orchestrateRevertToVMSnapshot:1211-NativeMethodAccessorImpl.invoke0:-2-NativeMethodAccessorImpl.invoke:62-DelegatingMethodAccessorImpl.invoke:43-Method.invoke:498-VmWorkJobHandlerProxy.handleVmWorkJob:107-VMSnapshotManagerImpl.handleVmWorkJob:1224
2018-01-15 09:39:58,713 DEBUG [c.c.v.s.VMSnapshotManagerImpl] (Work-Job-Executor-59:ctx-d58caf82 job-2505/job-2506 ctx-89d8d0fa) (logid:7c2d2191) Failed to revert vmsnapshot: 5
com.cloud.exception.InvalidParameterValueException: VM current state is : PowerOn. But VM should be in PowerOff state.

Are these log entries the result of that test? The "error" in log entries are right.... ACS is not allowing resize of volumes when VMs are running.
```

**Comment by rafaelweingartner** [comment]
Looking a little deeper, the test case, tries to revert the VM to a snapshot. It seems that the stop command has not finished when the rever to snapshot command was executed.

**Comment by rhtyd** [comment]
@rafaelweingartner you can read `test_vm_snapshots.py` for details, the test case tries to see how vm snapshot work when service offering is changed.

It deploys a VM, takes a VM snapshot (without memory), eventually (performs cpu/memory check to verify the offering used) changes the service offering and then shuts the VM, and then reverts to the previously taken VM snapshot. It fails at that point, as the revertSnapshot facade tries to resize root disk volume per the disk offering (if any).

I found the fix, rather embarassing -- for some reason the user VM dao have a caching problem, so if someones tries to immediately revert snapshot after shutting the VM down, it may appear to be `PowerOn` to CloudStack which is where the exception is thrown that fails the test, the following fixes the test:

```
--- a/test/integration/smoke/test_vm_snapshots.py
+++ b/test/integration/smoke/test_vm_snapshots.py
@@ -513,7 +513,8 @@ class TestChangeServiceOfferingForVmWithSnapshots(cloudstackTestCase):
             virtual_machine.stop(self.apiclient)
         except Exception as e:
             self.fail("Failed to stop VM: %s" % e)
-        
+
+        time.sleep(30)
         # 8) Revert to VM Snapshot

```

With this change, the test passes:

```
=== TestName: test_change_service_offering_for_vm_with_snapshots | Status : SUCCESS ===
ok

Ran 1 test in 501.359s
OK
```

**Comment by mike-tutkowski** [comment]
@rhtyd @rafaelweingartner I tried that use case manually and it worked. Of course, I don't click buttons as far as the test issues API commands, so the caching issue didn't show up when I did it.

**Comment by mike-tutkowski** [comment]
@rhtyd With regards to the following:

Are these log entries the result of that test? The "error" in log entries are right.... ACS is not allowing resize of volumes when VMs are running.

It looks like this test is being hit, which seems correct:

        if (userVm != null) {
            if (volume.getVolumeType().equals(Volume.Type.ROOT) && userVm.getPowerState()!= VirtualMachine.PowerState.PowerOff && hypervisorType == HypervisorType.VMware){
                s_logger.error(" For ROOT volume resize VM should be in Power Off state.");
                throw new InvalidParameterValueException("VM current state is : "+userVm.getPowerState()+ ". But VM should be in "+VirtualMachine.PowerState.PowerOff+" state.");
            }

**Comment by rhtyd** [comment]
Thanks @mike-tutkowski.
I've created a PR to address this, which may be accepted only with code reviews - @rafaelweingartner @mike-tutkowski since the change has been already manually QA-ed. Thanks.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan test centos7 xenserver-65sp1

**Comment by borisstoyanov** [comment]
@blueorangutan test centos7 xenserver-7

**Comment by borisstoyanov** [comment]
@blueorangutan test centos7 xenserver-71

**Comment by borisstoyanov** [comment]
@blueorangutan test centos7 xenserver-71

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan test centos7 xenserver-65sp1

**Comment by rhtyd** [comment]
@rafaelweingartner with xs 6.5sp1, latest 4.11 has no errors. LGTM, what errors if any are you seeing wrt the TLS fix (with latest 4.11)?

**Comment by rafaelweingartner** [comment]
I see, you are using the SP1. The error was that we were trying to use API (ACS connecting to the XenServer host), but it uses HTTPS via TLS1, and we wanted 1.2. The server was configured to work only with version 1, which will be no longer supported by ACS.

**Comment by rhtyd** [comment]
@rafaelweingartner how different is your XenServer host from a usually installed default setup (do you have to seed/setup https certificates?). I'll ask @PaulAngus or @DagSonstebo either of whom may advise us if the Trillian based tests uses HTTPS enabled XenServer hosts (default or custom cert setup).

**Comment by rafaelweingartner** [comment]
It is pretty standard. I did not installed any SP. It is the 6.5 version you get when you install XenServer using the ISO provided by Citrix. No, I did not setup certificates. I tried to look for a way to change the protocol used for securing the XS API, but I only found a way to do that on XS 7.

I asked you because I was a little worried that this could break things in production. Therefore, it might be interesting to release a warning or some extra instructions for the upgrade.

**Comment by rhtyd** [comment]
In that case, the XenServer 6.5sp1 setup we've for trillian based testing is default installed xenserver from iso. @PaulAngus can you comment on this, do you think it could break TLS or is there any workaorund for @rafaelweingartner? If it indeed break things in production, we can introduce a global settings or config/file based approach to fixing this (enable/disable a set of tls versions).

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Manually kicked tests via BO backend.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Review by borisstoyanov — COMMENTED** [review]
regarding xen server failures, test_scale_vm failure is related to unsupported feature by the license we got. I've tried reproducing the reset_vm_on_reboot failure a couple of times but the test was passing.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan test centos7 xenserver-65

**Comment by rhtyd** [comment]
@blueorangutan test centos7 xenserver-65sp1

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-65

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test centos7 xenserver-71

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-65

**Comment by rhtyd** [comment]
@blueorangutan test centos6 kvm-centos6

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
@blueorangutan sweep

**Pull request closed without merging**
