### PR TITLE
Restore iptables at once using iptables-restore instead of calling iptables numerous times

### PR DESCRIPTION
**Pull request by remibergsma**
This makes handling the firewall rules about 50-60 times faster because it is generated in memory and then loaded once. It's work by @borisroman see PR #1400. Reopened it here because I think this is a great improvement.

### CODE REVIEW

**Comment by DaanHoogland** [comment]
### CI bubble run


**Commit Reference: 30741a3309da346f324a8f365cb6ef8e1aab39d8**


Looks good to me

**Comment by swill** [comment]
@remibergsma please rebase as we currently have merge conflicts with master.  Thanks...

**Comment by remibergsma** [comment]
@swill conflict resolved

**Comment by rhtyd** [comment]
@remibergsma please rebase against master and squash changes to a single commit

tag:needlove

**Comment by swill** [comment]
Squash yes, but this can remain open against 4.7 as we are still fixing bugs and such against 4.7 and it is still supported (until 4.9 is released).  Anything merged into 4.7 will be forward merged...

**Comment by swill** [comment]
@remibergsma can you squash this and re-push.  I need one more code review on this one and we should be ready to merge it.  Thanks...

**Comment by swill** [comment]
@remibergsma just a reminder to squash and re-push so we can get jenkins green.  Thx...

**Comment by swill** [comment]
@remibergsma can you re-push this one.  Jenkins and Travis should be fixed now, so we should be able to get this green with a new push. 

I am missing one code review on this one.  @kiwiflyer and @dmabry did you guys happen to check this one already?  I know you guys have been reviewing stuff in this space.  Thx...

**Comment by kiwiflyer** [comment]
@swill We'll pull this in.

**Comment by swill** [comment]
Thanks guys.  👍

**Comment by kiwiflyer** [comment]
@remibergsma I'm porting this patch set into our 4.8 QA branch currently. I noticed 709be45 is in here as well (force encap). Can you pull that out of this set, as we've already merged it in https://github.com/apache/cloudstack/pull/1402 from your other PR.

Thanks!

**Comment by kiwiflyer** [comment]
ok, I'm just blind and didn't see the additional commit to remove the forceencaps. :-)

**Comment by remibergsma** [comment]
@kiwiflyer I'll see if I can get it out completely ;-)

**Comment by swill** [comment]
@remibergsma would you mind rebasing and re-pushing?  We don't have the reason why Jenkins failed, but Travis passed, so I am considering making a judgment call on this one, but would rather not.  Thx...

**Comment by kiwiflyer** [comment]
I've done some basic testing of this patch adding and deleting ACLs and rules within ACLs within VPCs.
LGTM

**Comment by kiwiflyer** [comment]
LGTM above from @DaanHoogland as well.

**Comment by swill** [comment]
Thank you.  I think that bumps this into my judgement call category.  👍

**Comment by swill** [comment]
@remibergsma can you give me a status on this PR.  I know you reverted it because of missing licenses.  Should I be trying to wait for this one to get back in for 4.9?  Thx...

**Comment by remibergsma** [comment]
@swill Some parts need to be rewritten so that won't be on time I'm afraid.

**Comment by swill** [comment]
@remibergsma ok, no problem.  Thanks for the heads up.  :)

**Pull request merged**
