### PR TITLE
Fix NPE if global setting implicit.host.tags is set to null

### PR DESCRIPTION
**Pull request by harikrishna-patnala**
### Description

This PR fixes the issue #8056 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### How Has This Been Tested?

Followed the steps mentioned in the issue and did not face NPE after the fix

### CODE REVIEW

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Review by weizhouapache — APPROVED** [review]
code lgtm
tested ok

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by rohityadavcloud — APPROVED** [review]

**Pull request merged**
