### PR TITLE
server: reapply checkVmProfileAndHost to check guest os preference

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR reapply #4338, which is reverted by #3600

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@GabrielBrascher @sureshanaparti please have a look

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by nvazquez** [comment]
@sureshanaparti please advise if this can be included on 4.16.1 or should be on 4.17

**Comment by sureshanaparti** [comment]
> @sureshanaparti please advise if this can be included on 4.16.1 or should be on 4.17

I think, we should include if it is a regression or breaking any previous functionality.

**Review by GabrielBrascher — APPROVED** [review]
Thanks for the PR @weizhouapache, LGTM.
Removing these lines should not bring regressions in the context of #3600.

I believe this was caused by either a backporting between different branches or a conflict with the main branch that was not properly addressed by me. These lines slipped by mistake into #3600.

**Review by sureshanaparti — APPROVED** [review]

**Pull request merged**
