### PR TITLE
Provision to sort ISOs from UI, and Updated Templates/ISOs API response to return in the order of sortkey.

### PR DESCRIPTION
**Pull request by sureshanaparti**
### Description

This PR allows ISOs sorting from UI, and updates the Templates/ISOs API response to return in the order of sortkey.

Fixes: #5731

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):

Sort_ISOs

### How Has This Been Tested?

Manually tested the Templates/ISOs sorting from the UI.

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Review by utchoang — APPROVED** [review]
UI LGTM!

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Pull request merged**
