### PR TITLE
api: fix new password is applied on host when update host password with update_passwd_on_host=false

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes that issue new password is applied on host when update host password with update_passwd_on_host=false

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### How Has This Been Tested?

prior to this change, this cmd command updated the host password
with this change, this cmd command did not update the host password.

(localcloud) 🐱 > update hostpassword hostid=cc83a7ed-8387-4d99-b1bf-4ded51e91aa7 password=password username=root update_passwd_on_host=false
{
  "success": true
}

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Review by vladimirpetrov — APPROVED** [review]
LGTM based on manual testing.

**Pull request merged**
