### PR TITLE
server: fix cannot get systemvm ips in dedicated ranges

### LINKED ISSUE #6698: Dedication of public IP ranges broken after upgrade to 4.17.0.1
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API, UI, SSVM, CPVM
~~~

##### CLOUDSTACK VERSION

~~~
4.17.0.1
~~~

##### CONFIGURATION

1 Zone, Advanced networking, 3 domains

##### OS / ENVIRONMENT

All running Ubuntu 20.04.5
Database mysql 8

##### SUMMARY

Existing configuration (working running CS 4.16.1)
System_Root

details

Setting `system.vm.public.reservation.mode.strictness` = true

After upgrade:
While deploying SSVM / CPVM, dedicated IP Ranges for use of system VMs aren't concidert for deployment. With `system.vm.public.reservation.mode.strictness` enabled, a deployment of SSVM / CPVM fails "due to Insufficent address capacity".
With `system.vm.public.reservation.mode.strictness` set to 'false' deployment is successfull while using IP ranges not marked as dedicated for system VMs.
Newly created IP ranges with dedication for systemVMs aren't stored or found in db table `domain_vlan_map`. Also prior used ip ranges dedicated for systemVMs aren't referenced in `domain_vlan_map`.

Currently tested with public IP addresses. Not tested with "strictness" for management IP addresses.

##### STEPS TO REPRODUCE

- Create IP range for public IPs with dedication for system VMs enabled
- Change setting `system.vm.public.reservation.mode.strictness` to true
- Destroy existing CPVM / SSVM

##### EXPECTED RESULTS

~~~
- Table `domain_vlan_map` shows entry for newly created IP range (stored as new vlan) assigned to domain
- System VMs are successfully deployed using IPs from the dedicated IP range
~~~

##### ACTUAL RESULTS

~~~
- Table `domain_vlan_map` shows no entry
- Deployment of systemVMs  fails due to insufficent address capacity
- Changeing setting `system.vm.public.reservation.mode.strictness` to "false"
   --> deployment successfull using IP range of domain not dedicated for systemVMs
~~~

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #6698 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Review by rohityadavcloud — APPROVED** [review]
Code LGTM, didn't test it. This may need manual testing. I'm not sure if the changes in marvin tests are enough?

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
clgtm, small remarks

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by rohityadavcloud** [comment]
@weizhouapache @DaanHoogland can this be merged, or need furthet testing/review?

**Comment by weizhouapache** [comment]
> @weizhouapache @DaanHoogland can this be merged, or need furthet testing/review?

@rohityadavcloud 
yes, this needs reproducing and testing (ongoing...)

**Comment by DaanHoogland** [comment]
verified: after setting `system.vm.public.reservation.mode.strictness` to `true` and `use.system.public.ips` to `false` on 4.18.0 SVMs won't come up. After upgrading to this PR they do. :+1:

**Comment by weizhouapache** [comment]
Thanks @DaanHoogland for verification
merging

**Pull request merged**
