### PR TITLE
Fix OS category for some OS-es added in 4.13

### PR DESCRIPTION
**Pull request by andrijapanicsb**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
SQL was tested to fix the issue - otherwise, nothing to test really.

### CODE REVIEW

**Comment by andrijapanicsb** [comment]
ping @rhtyd @PaulAngus @svenvogel for LGTMs

**Comment by svenvogel** [comment]
@andrijapanicsb looks good. Should we add RHEL 7.7. too?

**Comment by andrijapanicsb** [comment]
@svenvogel that's beyond the intention of this specific PR - but any additional/valid guest OS mappings are most welcome (in another PR).

**Comment by svenvogel** [comment]
@andrijapanicsb really a second PR? :)

**Comment by andrijapanicsb** [comment]
I don't understand what exactly you are suggesting? If you want to add CentOS 7.7 as the OS and the related hypervisor mappings (guest_os_hypervisor table entries) then it makes sense (to me) to do that in another PR (I like to avoid mixing apples and oranges, although both are fruits...)

**Comment by svenvogel** [comment]
@andrijapanicsb sure no problem i file a new one.

**Comment by andrijapanicsb** [comment]
Merging based on 2 x approvals and manual test results.

**Comment by andrijapanicsb** [comment]
@DaanHoogland can we merge this one to 4.13 as well - check the SQLs please, they are safe to be "done" in 4.13.0.0 to 4.13.1.0, and then executed again in the 4.13.x.x to 4.14.0.0 (if that makes sense?)

**Comment by DaanHoogland** [comment]
@andrijapanicsb we can, we'll just make sure to test that right? ;)

**Comment by andrijapanicsb** [comment]
Yes, you can repeat the queries, 2nd run will do no changes  - and the rows to be changed are uniquely identified by ID and name - if it doesn't match, it will not be executed:

UPDATE `cloud`.`guest_os` SET `category_id`='10' WHERE `id`=277 AND display_name="Ubuntu 17.04";UPDATE `cloud`.`guest_os` SET `category_id`='10' WHERE `id`=278 AND display_name="Ubuntu 17.10";UPDATE `cloud`.`guest_os` SET `category_id`='10' WHERE `id`=279 AND display_name="Ubuntu 18.04 LTS";UPDATE `cloud`.`guest_os` SET `category_id`='10' WHERE `id`=280 AND display_name="Ubuntu 18.10";UPDATE `cloud`.`guest_os` SET `category_id`='10' WHERE `id`=281 AND display_name="Ubuntu 19.04";UPDATE `cloud`.`guest_os` SET `category_id`='4' WHERE `id`=282 AND display_name="Red Hat Enterprise Linux 7.3";UPDATE `cloud`.`guest_os` SET `category_id`='4' WHERE `id`=283 AND display_name="Red Hat Enterprise Linux 7.4";UPDATE `cloud`.`guest_os` SET `category_id`='4' WHERE `id`=284 AND display_name="Red Hat Enterprise Linux 7.5";UPDATE `cloud`.`guest_os` SET `category_id`='4' WHERE `id`=285 AND display_name="Red Hat Enterprise Linux 7.6";UPDATE `cloud`.`guest_os` SET `category_id`='4' WHERE `id`=286 AND display_name="Red Hat Enterprise Linux 8.0";;
**/* Affected rows: 10  Found rows: 0  Warnings: 0  Duration for 10 queries: 0.062 sec. */**
UPDATE `cloud`.`guest_os` SET `category_id`='10' WHERE `id`=277 AND display_name="Ubuntu 17.04";UPDATE `cloud`.`guest_os` SET `category_id`='10' WHERE `id`=278 AND display_name="Ubuntu 17.10";UPDATE `cloud`.`guest_os` SET `category_id`='10' WHERE `id`=279 AND display_name="Ubuntu 18.04 LTS";UPDATE `cloud`.`guest_os` SET `category_id`='10' WHERE `id`=280 AND display_name="Ubuntu 18.10";UPDATE `cloud`.`guest_os` SET `category_id`='10' WHERE `id`=281 AND display_name="Ubuntu 19.04";UPDATE `cloud`.`guest_os` SET `category_id`='4' WHERE `id`=282 AND display_name="Red Hat Enterprise Linux 7.3";UPDATE `cloud`.`guest_os` SET `category_id`='4' WHERE `id`=283 AND display_name="Red Hat Enterprise Linux 7.4";UPDATE `cloud`.`guest_os` SET `category_id`='4' WHERE `id`=284 AND display_name="Red Hat Enterprise Linux 7.5";UPDATE `cloud`.`guest_os` SET `category_id`='4' WHERE `id`=285 AND display_name="Red Hat Enterprise Linux 7.6";UPDATE `cloud`.`guest_os` SET `category_id`='4' WHERE `id`=286 AND display_name="Red Hat Enterprise Linux 8.0";;
**/* Affected rows: 0  Found rows: 0  Warnings: 0  Duration for 10 queries: 0.078 sec. */**

**Comment by DaanHoogland** [comment]
I'm afraid we'll need a new PR though as this one has been merged, @andrijapanicsb

**Pull request merged**
