### PR TITLE
router: Fixes #2544 run passwd server on dhcpserver IP on rVR

### LINKED ISSUE #2544: Password Reset does not work with Isolated Networks with redundant routers
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VR
~~~

##### CLOUDSTACK VERSION

~~~
4.11.0.0
~~~

##### CONFIGURATION

Advanced Network, Isolated Network with Redundant Router and DNS, DHCP, Passwort, etc. Feateres all on

##### SUMMARY

When using the cloudstack-set-guest-password skript, the query is done against http://IP-OF-THE-DHCP-SERVER-THAT-SERVED-THE-LEASE:8080

A quick peek inside the MASTER of a redundant router setup shows, that the service (python) is only listening to the service-IP (the default gateway)

Firewall instead shows that port 8080 is open for both host- and service-IP.

##### STEPS TO REPRODUCE

Deploy a VM connected to an Isolated Network with redundant routers and use /etc/init.d/cloudstack-set-guest-password inside the VM 

wget just silently quits, telnet shows a "connection refused"

SSH keys are not affected since the pubkeys are deliverd by another service.

~~~

~~~

##### EXPECTED RESULTS

~~~
Getting the password via DHCP-SERVER-HOST-IP:8080
~~~

##### ACTUAL RESULTS

~~~

~~~

### PR DESCRIPTION
**Pull request by rhtyd**
This fixes #2544, ensure that password reset script works in redudant networks.

This ensures that password server runs on the dhcpserver identifier
IP which is the not the VRRP virtual (10.1.1.1) IP by default but
the actual ip of the interface. When dhcp client discovery is made,
the `dhcp-server-identifier` contains the non VIP address that is
used by password reset script to query guest VM password.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

Deployed a guest VM in redundant VR network, with a password enable template (macchinina). Verified on master VRs (and also on switching) that password server runs on the guest nic IP than the VIP and the password script is able to consume the nonVIP address from `dhcp-server-identifier`.

## Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
Testing
- [ ] I have added tests to cover my changes.
- [x] All relevant new and existing integration tests have passed.
- [x] A full integration testsuite with all test that can run on my environment has passed.

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by ustcweizhou** [comment]
@rhtyd FYI, here is our commit for similar issue
```
        if self.config.is_vpc():
            ads = [o for o in self.address.get_ips() if o.needs_vrrp()]
            for o in ads:
                CsPasswdSvc(o.get_gateway()).restart()
                CsPasswdSvc(o.get_ip()).restart()
        else:
            interfaces = [interface for interface in self.address.get_ips() if interface.is_guest()]
            for interface in interfaces:
                CsPasswdSvc(interface.get_ip()).restart()
            CsPasswdSvc(self.cl.get_guest_gw()).restart()
```

the "stop" part has similar change.

**Comment by rhtyd** [comment]
Thanks @ustcweizhou I'll handle the stop case as well.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@ustcweizhou @rhtyd both your changes look functionally the same but spark a question; Isn't the passwordserver going to be started on the public ip as well by this code (it requires vrrp as well, no)?
otherwise it looks good

**Comment by rhtyd** [comment]
@DaanHoogland thanks, no we don't want to start password server on public IP but only on guest gateway/nic IPs of the router. (we don't usually want to run on public IPs for the general internet) VRRP in case of rVR is enabled for guest nic/network IPs which is why we start password server on them.

**Comment by rhtyd** [comment]
Tests LGTM, failure were caused by one of the failing test that injected an invalid public IP range.
@DaanHoogland are you lgtm on this?

**Comment by DaanHoogland** [comment]
yes, @rhtyd . The question was due to my misunderstanding. please go ahead

**Pull request merged**
