### PR TITLE
On snapshot backup, this converts the rbd raw format on disk to qcow2 for compression.

### PR DESCRIPTION
**Pull request by nathanejohnson**

### CODE REVIEW

**Comment by nathanejohnson** [comment]
On KVM where primary storage is ceph / rbd, and a snapshot is backed up to secondary, the comments seem to indicate that in this scenario the image will be converted to qcow2 to save space.  In implementation, however, it actually "converts" the source format (RAW in this case) into  RAW, which is effectly a straight copy.  This means that for a 20GB volume that is mostly empty, it will copy a full 20GB file onto secondary storage as a backup.  I have changed this to it always sets the source type to that of the disk (which should always be RAW for RBD), and sets the dest disk type to QCOW2.

**Comment by nathanejohnson** [comment]
```
before:

[njohnson@csm01.nsvltn secondary]$ ls -lh snapshots/102/5022/a6baaf14-190a-4a06-b95a-5b502fbd7d06
-rw-r--r-- 1 root root 40G Aug 17 16:41 snapshots/102/5022/a6baaf14-190a-4a06-b95a-5b502fbd7d06
[njohnson@csm01.nsvltn secondary]$ file snapshots/102/5022/a6baaf14-190a-4a06-b95a-5b502fbd7d06
snapshots/102/5022/a6baaf14-190a-4a06-b95a-5b502fbd7d06: x86 boot sector; partition 1: ID=0x7, active, starthead 32, startsector 2048, 716800 sectors; partition 2: ID=0x7, starthead 190, startsector 718848, 83165184 sectors, code offset 0xc0, OEM-ID "      м", Bytes/sector 190, sectors/cluster 124, reserved sectors 191, FATs 6, root entries 185, sectors 64514 (volumes <=32 MB) , Media descriptor 0xf3, sectors/FAT 20644, heads 6, hidden sectors 309755, sectors 2147991229 (volumes > 32 MB) , physical drive 0x7e, dos < 4.0 BootSector (0x0)
[njohnson@csm01.nsvltn secondary]$

after:

[njohnson@dkrlab01.dev secondary]$ file snapshots/10/215/6c191b18-32fe-4ff3-b6e0-b1a216c3bdfd
snapshots/10/215/6c191b18-32fe-4ff3-b6e0-b1a216c3bdfd: QEMU QCOW Image (v3), 21474836480 bytes
[njohnson@dkrlab01.dev secondary]$ ls -lh snapshots/10/215/6c191b18-32fe-4ff3-b6e0-b1a216c3bdfd
-rw-r--r-- 1 root root 193K Aug 17 16:10 snapshots/10/215/6c191b18-32fe-4ff3-b6e0-b1a216c3bdfd
[njohnson@dkrlab01.dev secondary]$ 
```

**Comment by kiwiflyer** [comment]
LGTM, tested in our lab.

**Comment by kiwiflyer** [comment]
@wido  This is also nice for users of Ceph.

**Comment by kiwiflyer** [comment]
CLOUDSTACK-9461

**Comment by wido** [comment]
Are we sure this will work? Since the DB format will probably stay RAW, correct?

**Comment by nathanejohnson** [comment]
The snapshot in primary stays raw anyway, it's only the backup to secondary that gets converted.

**Comment by wido** [comment]
Ok, this code is a bit rusty for me. But I think that the qemu-img converter is started at the back to do the conversion, right?

**Comment by nathanejohnson** [comment]
@wido that seems to be the case, yes.

https://github.com/myENA/cloudstack/blob/44220a41c119020404c55e7a82a808ddee828116/plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java#L727

The section starts there, and down on line 747 it calls convert.  Keep in mind the above link is the code as if this PR was applied.  From my testing, this seems to work well, but please let me know if after revisiting the code you have any concerns.  Thank you!

**Comment by wido** [comment]
It seems good, but I'm worried if the management server is also aware if this. The Answer going back to the mgmt server needs to tell it that the format became QCOW2.

I don't have a test env for this right now, but I think this PR will work just fine.

**Comment by kiwiflyer** [comment]
For reference, here are the DB entries:

snapshot_ref

snapshot_store_ref

**Comment by wido** [comment]
What I see to remember somehow is that the management server/code always thinks a snapshot is in the same format as the base image was.

So when you try to do something with this snapshot it still thinks it is RAW since that's what the original volume is.

For a snapshot there is no additional field saying that's QCOW2 and not RAW.

**Comment by kiwiflyer** [comment]
Yeah, there seems to be some black magic going on here. We'll dig into this a bit more.

**Comment by jburwell** [comment]
@kiwiflyer @nathanejohnson as part of your continued evaluation, can you evaluate the following test cases to ensure this new behavior is verified and regression tested:

* ``smoke/test_snaptshots.py``
* ``component/test_snapshot_gc.py``
* ``component/test_snapshot_limits.py``
* ``component/test_snapshots.py``
* ``component/test_snapshots_improvements.py``

**Comment by jburwell** [comment]
@nathanejohnson could you please create JIRA ticket for this issue and prepend the commit message with the ID?

**Comment by nathanejohnson** [comment]
@jburwell 

I'm hoping that I can spend a good part of today on the requests you've made on my three open pull requests.

**Comment by jburwell** [comment]
@nathanejohnson excellent.  I will keep any eye out for your updates.

**Comment by nathanejohnson** [comment]
@jburwell as an update, the smoke test has completed successfully, and I'll let the component tests run overnight.  Hopefully they will have finished by the morning.

**Comment by wido** [comment]
@kiwiflyer So does the mgmt server know the snapshot is now in QCOW2? Or does it still think it's RAW?

**Comment by nathanejohnson** [comment]
@wido I don't know that the management server knows explicitly, it doesn't actually seem to store the disk image format in the snapshot related tables at all, only in volumes as far as I can tell.  However, I don't believe the management server ever does anything with the snapshot backup on secondary other than deleting it whenever the corresponding snapshot is deleted, and for that it doesn't actually care what format it's in.

**Comment by nathanejohnson** [comment]
@jburwell the smoke test completed successfully
Test Snapshot Root Disk ... === TestName: test_01_snapshot_root_disk | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 1 test in 1961.555s

OK

I'm going to have to rerun the component tests because it looks like it picked a Windows based template, and all of the operations where it required being able to ssh in failed.

**Comment by kiwiflyer** [comment]
I took a look at the code last night and it seems that we're no longer specifying the source format when calling qemu-img convert. We're relying on qemu-img's auto detection of source format and just specifying the output format.

See here:
https://github.com/apache/cloudstack/blob/de173bd8921ef926ace405796b4037902ce1979e/plugins/hypervisors/kvm/src/org/apache/cloudstack/utils/qemu/QemuImg.java#L226

**Comment by nathanejohnson** [comment]
@jburwell @si @wido 

Here are the results of the nosetests.  One test did throw an exception during teardown, but I am not sure that this is anything to be concerned about.  I'll post the logs and see what you guys thing:

Test snapshot cleanup after account deletion ... === TestName: test_02_accountSnapshotClean | Status : SUCCESS ===
ok
Test snapshot limit in snapshot policies ... === TestName: test_04_snapshot_limit | Status : SUCCESS ===
ok
Test create VM, Snapshot and Template ... === TestName: test_01_createVM_snapshotTemplate | Status : SUCCESS ===
ok
Test snapshot events ... === TestName: test_05_snapshot_events | Status : SUCCESS ===
ok
Test Creating snapshot from volume having spaces in name(KVM) ... === TestName: test_01_volume_from_snapshot | Status : SUCCESS ===
ok
Test Snapshot Data Disk ... === TestName: test_02_snapshot_data_disk | Status : SUCCESS ===
ok
Test snapshot from detached disk ... === TestName: test_03_snapshot_detachedDisk | Status : SUCCESS ===
ok
Test Delete Snapshot ... === TestName: test_04_delete_snapshot | Status : SUCCESS ===
ok
Create Template from snapshot ... === TestName: test_07_template_from_snapshot | Status : SUCCESS ===
ok
Test perform concurrent snapshots and migrate the vm from one host ... === TestName: test_01_concurrent_snapshots_live_migrate | Status : SUCCESS ===
ok
Test stop running VM while performing concurrent snapshot on volume ... === TestName: test_02_stop_vm_concurrent_snapshots | Status : SUCCESS ===
ok
Test while parent concurrent snapshot job in progress,create ... === TestName: test_03_concurrent_snapshots_create_template | Status : SUCCESS ===
ok
Test while parent concurrent snapshot job in progress,create volume ... === TestName: test_04_concurrent_snapshots_create_volume | Status : SUCCESS ===
ok
Test create VM with default cent os template and create snapshot ... === TestName: test_01_snapshot_on_rootVolume | Status : EXCEPTION ===
ERROR

... <snipped long segment of logs>

Ran 14 tests in 11936.921s

FAILED (errors=1)
(END)

And in the failed plus exceptions:

[njohnson@dkrlab01.dev test_snapshots_improvement_FE4IW5]$ cat failed_plus_exceptions.txt 
2016-08-26 03:26:10,082 - CRITICAL - EXCEPTION: test_01_snapshot_on_rootVolume: ['Traceback (most recent call last):\n', '  File "/usr/lib64/python2.7/unittest/case.py", line 398, in run\n    self.tearDown()\n', '  File "/home/njohnson/cloudstack-ena/test/integration/component/test_snapshots_improvement.py", line 195, in tearDown\n    raise Exception("Warning: Exception during cleanup : %s" % e)\n', "Exception: Warning: Exception during cleanup : Job failed: {jobprocstatus : 0, created : u'2016-08-26T03:20:58-0500', jobresult : {errorcode : 530, errortext : u'Failed to delete snapshot'}, cmd : u'org.apache.cloudstack.api.command.user.snapshot.DeleteSnapshotCmd', userid : u'f1d1ed88-4fb7-11e6-986a-000c29b79f06', jobstatus : 2, jobid : u'26b7de07-d293-445f-8e60-fb2089aad844', jobresultcode : 530, jobinstanceid : u'a23db950-4035-4906-b6a6-2d1d50437450', jobresulttype : u'object', jobinstancetype : u'Snapshot', accountid : u'f1d12b61-4fb7-11e6-986a-000c29b79f06'}\n"]
[njohnson@dkrlab01.dev test_snapshots_improvement_FE4IW5]$ 


I can paste full logs in a gist if anyone is interested.

**Comment by wido** [comment]
@kiwiflyer That seems good indeed. If we are not setting a source format this looks good indeed.

LGTM

**Comment by karuturi** [comment]
I will start our internal CI run on this(it runs the smoke tests and will post the results here). Once that is successful, I will merge this.

**Comment by cloudmonger** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 98
 Hypervisor xenserver
 NetworkType Advanced
 Passed=102
 Failed=1
 Skipped=4

_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/yj3wnzbceo9uef2/AAB6u-Iap-xztdm6jHX9SjPja?dl=0


**Failed tests:**
* test_network.py

 * test_delete_account Failed


**Skipped tests:**
test_vm_nic_adapter_vmxnet3
test_static_role_account_acls
test_3d_gpu_support
test_deploy_vgpu_enabled_vm

**Passed test suits:**
test_deploy_vm_with_userdata.py
test_affinity_groups_projects.py
test_portable_publicip.py
test_over_provisioning.py
test_global_settings.py
test_scale_vm.py
test_service_offerings.py
test_routers_iptables_default_policy.py
test_loadbalance.py
test_routers.py
test_reset_vm_on_reboot.py
test_snapshots.py
test_deploy_vms_with_varied_deploymentplanners.py
test_router_dns.py
test_non_contigiousvlan.py
test_login.py
test_deploy_vm_iso.py
test_list_ids_parameter.py
test_public_ip_range.py
test_multipleips_per_nic.py
test_regions.py
test_affinity_groups.py
test_network_acl.py
test_pvlan.py
test_volumes.py
test_ssvm.py
test_nic.py
test_deploy_vm_root_resize.py
test_resource_detail.py
test_secondary_storage.py
test_vm_life_cycle.py
test_disk_offerings.py

**Comment by kiwiflyer** [comment]
@karuturi  - So, note that this feature addition only affects KVM when using RBD as the back-end storage.

**Comment by karuturi** [comment]
@kiwiflyer Noted. Looking at the code diff, I dont think it will cause any regressions. But, just wanted to run the tests once.

**Comment by cloudmonger** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 99
 Hypervisor xenserver
 NetworkType Advanced
 Passed=99
 Failed=1
 Skipped=4

_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/yj3wnzbceo9uef2/AAB6u-Iap-xztdm6jHX9SjPja?dl=0


**Failed tests:**
* test_network.py

 * test_delete_account Failing since 2 runs


**Skipped tests:**
test_vm_nic_adapter_vmxnet3
test_static_role_account_acls
test_3d_gpu_support
test_deploy_vgpu_enabled_vm

**Passed test suits:**
test_deploy_vm_with_userdata.py
test_affinity_groups_projects.py
test_portable_publicip.py
test_over_provisioning.py
test_global_settings.py
test_scale_vm.py
test_service_offerings.py
test_routers_iptables_default_policy.py
test_routers.py
test_reset_vm_on_reboot.py
test_snapshots.py
test_deploy_vms_with_varied_deploymentplanners.py
test_router_dns.py
test_non_contigiousvlan.py
test_login.py
test_deploy_vm_iso.py
test_list_ids_parameter.py
test_public_ip_range.py
test_multipleips_per_nic.py
test_regions.py
test_affinity_groups.py
test_network_acl.py
test_pvlan.py
test_volumes.py
test_ssvm.py
test_nic.py
test_deploy_vm_root_resize.py
test_resource_detail.py
test_secondary_storage.py
test_vm_life_cycle.py
test_disk_offerings.py

**Comment by karuturi** [comment]
Failure is not related. Looks like an environment issue(I am checking it). Merging this PR.

**Comment by jburwell** [comment]
@karuturi was this PR tested on KVM?

**Comment by karuturi** [comment]
@jburwell No I didnt. As I said in the other PR, I only have a xenserver environment(my test run was only to see it didnt cause any regressions). If you can get a KVM environment running, which can run the test suite, that would be great.

**Comment by jburwell** [comment]
@nathanejohnson @kiwiflyer do you have test results to share for KVM + Ceph?  If not, we need to rollback this PR until we get test confirmation of the functionality.

**Comment by nathanejohnson** [comment]
@jburwell , test results were posted earlier in the thread.

**Comment by jburwell** [comment]
@nathanejohnson to confirm, the test results in your [26 Aug comment](https://github.com/apache/cloudstack/pull/1645#issuecomment-242715452) comment were from a run on KVM + Ceph?

**Comment by nathanejohnson** [comment]
@jburwell that is correct, the lab I tested on is running KVM + ceph.

**Comment by jburwell** [comment]
@nathanejohnson thank you for your confirmation

**Pull request merged**
