### PR TITLE
CPU socket count reporting correction

### PR DESCRIPTION
**Pull request by NuxRo**
CPU socket count reporting correction
From https://github.com/MissionCriticalCloud/cosmic-plugin-hypervisor-kvm/pull/16

### CODE REVIEW

**Comment by swill** [comment]
@NuxRo can you do a force push to kick off jenkins and travis again.  Also, can you show this change fixes the behavior with a screenshot or something.  I don't think the code change warrants a full CI run since nothing new was introduced, only the value of a variable has changed and it uses proper defensive programming...  It would be nice to see the problem it solves though...

**Comment by remibergsma** [comment]
@swill more details here: https://github.com/MissionCriticalCloud/cosmic-plugin-hypervisor-kvm/pull/16

**Comment by swill** [comment]
Great, thanks @remibergsma.  :)

**Comment by rhtyd** [comment]
@NuxRo thanks, please rebase and squash to a single commit

LGTM

tag:mergeready

**Comment by NuxRo** [comment]
I'd appreciate it if someone else could do it, I do not have the setup to perform more advanced github operations right now, other than the UI.

**Comment by swill** [comment]
Can we get another code review on this?  Also, Jenkins seems to be hung, can we either close and reopen the PR or do a force push to kick it off?  Thx...

**Comment by dmabry** [comment]
We have rolled this patch in our lab and verified that it does indeed report the number of sockets correctly.  Based on testing this LGTM.

Please do a force push to kick off jenkins and travis again.

**Comment by rhtyd** [comment]
LGTM (code review)

tag:mergeready

**Comment by swill** [comment]
I am comfortable not running CI on this one given the scope of the change and the manual tests that have been run.  This one is ready now.  We need this force pushed again though so we can get Jenkins green.  Thx...

**Comment by swill** [comment]
@NuxRo can you close and reopen this PR to force Jenkins to kick off a run.  It has been hung in this state for days.  I know you can't easily `amend` and force push, so closing and reopening the PR will let you kick it off again through the UI.

**Comment by swill** [comment]
@NuxRo I have pushed fixes to both Jenkins and Travis this morning.  Can you close and reopen the PR to kick off the Jenkins and Travis runs again.  Thanks...

**Comment by remibergsma** [comment]
LGTM, running this in prod for about a month now. See link above for screenshots.

**Comment by kiwiflyer** [comment]
@swill  This one is green now.

**Comment by swill** [comment]
Awesome, thanks guys.  I will merge this...

**Pull request merged**
