### PR TITLE
linstor: fix template copy on non hyperconverged setups

### PR DESCRIPTION
**Pull request by rp-**
### Description

Making a diskful resource was meant as an optimization, but cannot work on non hyperconverged setups,
as the storage nodes (diskful) are not part of the cloudstack cluster.

This was introduced with 4a86a0d2339bbd809d87e7179f510e018030cbbc, so it isn't in any released version yet.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [x] BLOCKER for non hyperconverged setups
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

Tested on a new non hyperconverged cluster setup

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
should this go in 4.18.2/4.19 @rp- ?

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by rp-** [comment]
> should this go in 4.18.2/4.19 @rp- ?

yes, in both if my mentioned commit was also merged in 4.19.

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by shwstppr — APPROVED** [review]
Code LGTM

**Comment by shwstppr** [comment]
@rp- is this good to merge?

**Comment by rp-** [comment]
> @rp- is this good to merge?

yes

**Pull request merged**
