### PR TITLE
vxlan: arp does not work between hosts as multicast group is communicated over physical nic instead of linux bridge

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

when linux bridge is setup (refer to http://docs.cloudstack.apache.org/projects/archived-cloudstack-getting-started/en/latest/networking/vxlan.html#configure-product-to-use-vxlan-plugin) and used as the kvm traffic label of physical networks, the vms on different hosts cannot reach each other.

(1) does not work:
```
/usr/share/cloudstack-common/scripts/vm/network/vnet/modifyvxlan.sh -v 1001 -p eth1 -b brvx-1001 -o add
```
"bridge fdb" shows
```
00:00:00:00:00:00 dev vxlan1001 dst 239.0.3.233 via eth1 self permanent
```

(2) this works:
```
/usr/share/cloudstack-common/scripts/vm/network/vnet/modifyvxlan.sh -v 1001 -p cloudbr1 -b brvx-1001 -o add
```
"bridge fdb" shows
```
00:00:00:00:00:00 dev vxlan1001 dst 239.0.3.233 via cloudbr1 self permanent
```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [X] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@GabrielBrascher @wido 
have you faced this issue before ?

**Comment by rhtyd** [comment]
Tentatively putting on 4.15.1.0

**Comment by wido** [comment]
> @GabrielBrascher @wido
> have you faced this issue before ?

No. We use a modified version of the vxlan shell script as we are not using VXLAN with Multicast, but we use it with BGP+EVPN with Frr on the host.

I would always recommend to use VXLAN in combination with BGP as it's much more flexible and future-proof than multicast.

**Comment by weizhouapache** [comment]
> > @GabrielBrascher @wido
> > have you faced this issue before ?
> 
> No. We use a modified version of the vxlan shell script as we are not using VXLAN with Multicast, but we use it with BGP+EVPN with Frr on the host.
> 
> I would always recommend to use VXLAN in combination with BGP as it's much more flexible and future-proof than multicast.

@wido thanks for your information. it's a good idea.
any chance to add to cloudstack code and documentations ?

**Comment by wido** [comment]
> > > @GabrielBrascher @wido
> > > have you faced this issue before ?
> > 
> > 
> > No. We use a modified version of the vxlan shell script as we are not using VXLAN with Multicast, but we use it with BGP+EVPN with Frr on the host.
> > I would always recommend to use VXLAN in combination with BGP as it's much more flexible and future-proof than multicast.
> 
> @wido thanks for your information. it's a good idea.
> any chance to add to cloudstack code and documentations ?

Here is the modified Shell script which we use: https://gist.github.com/wido/51cb9880d86f08f73766634d7f6df3f4

BGP and EVPN is a totally different thing to document. I wouldn't put that in the CloudStack documentation, but leave that up to projects like FRR

**Comment by weizhouapache** [comment]
> > > > @GabrielBrascher @wido
> > > > have you faced this issue before ?
> > > 
> > > 
> > > No. We use a modified version of the vxlan shell script as we are not using VXLAN with Multicast, but we use it with BGP+EVPN with Frr on the host.
> > > I would always recommend to use VXLAN in combination with BGP as it's much more flexible and future-proof than multicast.
> > 
> > 
> > @wido thanks for your information. it's a good idea.
> > any chance to add to cloudstack code and documentations ?
> 
> Here is the modified Shell script which we use: https://gist.github.com/wido/51cb9880d86f08f73766634d7f6df3f4
> 
> BGP and EVPN is a totally different thing to document. I wouldn't put that in the CloudStack documentation, but leave that up to projects like FRR

@wido great, thanks for sharing !

ps: it looks this pr will not affect you, as $PIF is not used at all in your script.

**Comment by wido** [comment]
> > > > > @GabrielBrascher @wido
> > > > > have you faced this issue before ?
> > > > 
> > > > 
> > > > No. We use a modified version of the vxlan shell script as we are not using VXLAN with Multicast, but we use it with BGP+EVPN with Frr on the host.
> > > > I would always recommend to use VXLAN in combination with BGP as it's much more flexible and future-proof than multicast.
> > > 
> > > 
> > > @wido thanks for your information. it's a good idea.
> > > any chance to add to cloudstack code and documentations ?
> > 
> > 
> > Here is the modified Shell script which we use: https://gist.github.com/wido/51cb9880d86f08f73766634d7f6df3f4
> > BGP and EVPN is a totally different thing to document. I wouldn't put that in the CloudStack documentation, but leave that up to projects like FRR
> 
> @wido great, thanks for sharing !
> 
> ps: it looks this pr will not affect you, as $PIF is not used at all in your script.

Indeed. Everything goes through BGP and the IPv4 address on the loopback interface which is then announced through BGP.

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@weizhouapache is this ready for merging? (asking as PR is in draft)

**Comment by weizhouapache** [comment]
> @weizhouapache is this ready for merging? (asking as PR is in draft)

@rhtyd this is ready for review.

this issue seems to be caused by #3070 (merged on Jan 9, 2019), but nobody complains about it in past two years.
I am not sure if it is really a critical issue.

in old implememtation, it uses bridge (brif) not physical nic (pif), see
https://github.com/apache/cloudstack/pull/3070/files#diff-1446a11b068fed39393b671473102fccf780de39421edf0847548a712467f97bL75

**Comment by wido** [comment]
> > @weizhouapache is this ready for merging? (asking as PR is in draft)
> 
> @rhtyd this is ready for review.
> 
> this issue seems to be caused by #3070 (merged on Jan 9, 2019), but nobody complains about it in past two years.
> I am not sure if it is really a critical issue.
> 
> in old implememtation, it uses bridge (brif) not physical nic (pif), see
> https://github.com/apache/cloudstack/pull/3070/files#diff-1446a11b068fed39393b671473102fccf780de39421edf0847548a712467f97bL75

It is weird though. We have one CloudStack (dev) environment where we use VXLAN with Multicast and not with BGP.

This script is in use there and is working just fine.

**Comment by weizhouapache** [comment]
> It is weird though. We have one CloudStack (dev) environment where we use VXLAN with Multicast and not with BGP.
> 
> This script is in use there and is working just fine.

@wido do you use linux bridge in the environment ?
if not, it does not have this issue.

**Comment by wido** [comment]
> > It is weird though. We have one CloudStack (dev) environment where we use VXLAN with Multicast and not with BGP.
> > This script is in use there and is working just fine.
> 
> @wido do you use linux bridge in the environment ?
> if not, it does not have this issue.

Yes. That environment uses Linux bridging:

<pre>
root@n01:~# brctl show
bridge name	bridge id		STP enabled	interfaces
brvx-2001		8000.be3a51f8ca5e	no		vnet2
							vxlan2001
brvx-2002		8000.1265359ad1da	no		vnet0
							vxlan2002
brvx-2004		8000.3e7767b8c917	no		vnet1
							vxlan2004
cloud0		8000.fe00a9fe017d	no		vnet3
							vnet4
							vnet5
cloudbr1		8000.86fab6316ec1	no		vxlan100
root@n01:~# cat /etc/cloudstack/agent/agent.properties|grep cloudbr
private.network.device=cloudbr1
guest.network.device=cloudbr0
public.network.device=cloudbr0
root@n01:~# 
</pre>

Does this help?

**Comment by weizhouapache** [comment]
> > > It is weird though. We have one CloudStack (dev) environment where we use VXLAN with Multicast and not with BGP.
> > > This script is in use there and is working just fine.
> > 
> > 
> > @wido do you use linux bridge in the environment ?
> > if not, it does not have this issue.
> 
> Yes. That environment uses Linux bridging:
> 
> root@n01:~# brctl show
> bridge name	bridge id		STP enabled	interfaces
> brvx-2001		8000.be3a51f8ca5e	no		vnet2
> 							vxlan2001
> brvx-2002		8000.1265359ad1da	no		vnet0
> 							vxlan2002
> brvx-2004		8000.3e7767b8c917	no		vnet1
> 							vxlan2004
> cloud0		8000.fe00a9fe017d	no		vnet3
> 							vnet4
> 							vnet5
> cloudbr1		8000.86fab6316ec1	no		vxlan100
> root@n01:~# cat /etc/cloudstack/agent/agent.properties|grep cloudbr
> private.network.device=cloudbr1
> guest.network.device=cloudbr0
> public.network.device=cloudbr0
> root@n01:~# 
> Does this help?

@wido yes, I think the main difference is, you use vxlan100 while I use eth1.
(I followed the link http://docs.cloudstack.apache.org/en/latest/plugins/vxlan.html?highlight=vxlan#configure-in-ubuntu)

can you also share the result of command `bridge fdb |egrep "vxlan100 |via"` on kvm host ?
thanks.

**Comment by wido** [comment]
> bridge fdb |egrep "vxlan100 |via"

<pre>
root@n01:~# bridge fdb |egrep "vxlan100 |via"
5e:43:12:74:c9:47 dev vxlan100 master cloudbr1 
56:df:29:8d:db:83 dev vxlan100 vlan 1 master cloudbr1 permanent
36:6f:6d:c7:d6:02 dev vxlan100 master cloudbr1 
56:df:29:8d:db:83 dev vxlan100 master cloudbr1 permanent
00:00:00:00:00:00 dev vxlan100 dst 239.0.0.100 via cloudbr0 self permanent
5e:43:12:74:c9:47 dev vxlan100 dst 192.168.0.10 self 
36:6f:6d:c7:d6:02 dev vxlan100 dst 192.168.0.1 self 
00:00:00:00:00:00 dev vxlan2002 dst 239.0.7.210 via cloudbr0 self permanent
00:00:00:00:00:00 dev vxlan2004 dst 239.0.7.212 via cloudbr0 self permanent
00:00:00:00:00:00 dev vxlan2001 dst 239.0.7.209 via cloudbr0 self permanent
root@n01:~# 
</pre>

**Comment by weizhouapache** [comment]
> > bridge fdb |egrep "vxlan100 |via"
> 
> root@n01:~# bridge fdb |egrep "vxlan100 |via"
> 5e:43:12:74:c9:47 dev vxlan100 master cloudbr1 
> 56:df:29:8d:db:83 dev vxlan100 vlan 1 master cloudbr1 permanent
> 36:6f:6d:c7:d6:02 dev vxlan100 master cloudbr1 
> 56:df:29:8d:db:83 dev vxlan100 master cloudbr1 permanent
> 00:00:00:00:00:00 dev vxlan100 dst 239.0.0.100 via cloudbr0 self permanent
> 5e:43:12:74:c9:47 dev vxlan100 dst 192.168.0.10 self 
> 36:6f:6d:c7:d6:02 dev vxlan100 dst 192.168.0.1 self 
> 00:00:00:00:00:00 dev vxlan2002 dst 239.0.7.210 via cloudbr0 self permanent
> 00:00:00:00:00:00 dev vxlan2004 dst 239.0.7.212 via cloudbr0 self permanent
> 00:00:00:00:00:00 dev vxlan2001 dst 239.0.7.209 via cloudbr0 self permanent
> root@n01:~#

@wido the configs look good.
In my testing env, it has "via eth1" instead of "via cloudbr*", which causes the connection issue between vms.
I need to look into the java code.

**Comment by wido** [comment]
@weizhouapache Do you think the Java fix is working now? Or is this PR still WIP?

**Comment by weizhouapache** [comment]
> @weizhouapache Do you think the Java fix is working now? Or is this PR still WIP?

@wido the java fix works for me (need to specify the kvm network label to cloudbrX, otherwise it still does not work).

another option is, fix it in modifyvxlan.sh, for example, get "brif" using code below should also work.
https://github.com/apache/cloudstack/commit/d3e95b98fc4833933cc73455a22bf5b87f7b6053#diff-1446a11b068fed39393b671473102fccf780de39421edf0847548a712467f97bL37-L58

since there is no issue in your environment, we'd better try to reproduce the issue and test the fix.

**Comment by rhtyd** [comment]
@Pearl1594 @shwstppr has this been tested? (note while testing make sure the mtu of host is 40bytes + default mtu, consult with Wei or me if that helps). Thanks.

**Comment by rhtyd** [comment]
@weizhouapache @GabrielBrascher @wido is this ready for merging? Or are we looking at additional work?

**Comment by weizhouapache** [comment]
@rhtyd I talked to @Pearl1594 , she can also reproduce the issue that vms in other hosts cannot get dhcp IP from VR.

This PR requires the kvm network label to be 'cloudbrX', but in some environments the kvm network label is not set (it just "Use default gateway").
so I think it would be better to fix it in modifyvxlan.sh (in the function 'addVxlan')
https://github.com/apache/cloudstack/blob/main/scripts/vm/network/vnet/modifyvxlan.sh#L47-L63

**Comment by weizhouapache** [comment]
@wido do you think if we should use brif instead pif in modifyvxlan.sh, like we did in previous versions ?

https://github.com/apache/cloudstack/commit/d3e95b98fc4833933cc73455a22bf5b87f7b6053#diff-1446a11b068fed39393b671473102fccf780de39421edf0847548a712467f97bL75

**Comment by weizhouapache** [comment]
> @rhtyd I talked to @Pearl1594 , she can also reproduce the issue that vms in other hosts cannot get dhcp IP from VR.
> 
> This PR requires the kvm network label to be 'cloudbrX', but in some environments the kvm network label is not set (it just "Use default gateway").
> so I think it would be better to fix it in modifyvxlan.sh (in the function 'addVxlan')
> https://github.com/apache/cloudstack/blob/main/scripts/vm/network/vnet/modifyvxlan.sh#L47-L63

updated the pr to fix the issue when network label is not set.

thanks @Pearl1594 for advice and testing.

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan test

**Review by Pearl1594 — APPROVED** [review]
Verified fix on Zone with vxlan isolation method.
Prior Fix:
VM (on host not containing the VR) fails to get an IP
image

Post fix:
VMs deployed on 2 different hosts get DHCP IP from VR.

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@Pearl1594 @weizhouapache is this ready for merging? The last test failures may not be related to this PR.

**Comment by weizhouapache** [comment]
> @Pearl1594 @weizhouapache is this ready for merging? The last test failures may not be related to this PR.

@rhtyd it is ok in our testing (with or without kvm network label).
we need to make sure it does not break vlan functionalities which are more important than vxlan.

I will look into the issues in Trillian test result (tid-938) above.

**Review by wido — APPROVED** [review]
LGTM based on code. I have not been able to test it.

**Comment by weizhouapache** [comment]
@blueorangutan test

**Review by GabrielBrascher — APPROVED** [review]
Code LGTM

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@rhtyd 
strange, I have run the smoketests manually, all looks good.

**Pull request merged**
