### PR TITLE
packaging: add libvirt-daemon-driver-storage-rbd as cloudstack-agent dependency

### LINKED ISSUE #9797: Ubuntu missing dependency libvirt-daemon-driver-storage-rbd
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME

~~~
Storage
~~~

##### CLOUDSTACK VERSION

~~~
4.19.1
~~~

##### OS / ENVIRONMENT
~~~
Ubuntu 22.04
~~~

##### SUMMARY

~~~
The cloudstack-agent deb file doesn't pull  libvirt-daemon-driver-storage-rbd as a dependency 
(although it does pull librados etc).
In envs with CEPH this leads to failing to connect to the storage pool
despite manual rbd commands working on the hypervisor.
~~~
##### STEPS TO REPRODUCE

~~~
apt install cloudstack-agent
~~~

##### EXPECTED RESULTS

~~~
apt pulls in libvirt-daemon-driver-storage-rbd as a dependency
~~~

##### ACTUAL RESULTS

~~~
Cloudstack couldn't start a VM on CEPH
~~~

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #9797 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by andrijapanicsb** [comment]
@weizhouapache this was spoted only for Ubuntu 22.04+, not sure if EL8 are affected

**Comment by weizhouapache** [comment]
> @weizhouapache this was spoted only for Ubuntu 22.04+, not sure if EL8 are affected

@andrijapanicsb 
the package name is the same on ubuntu 22/24 and el8/9

it is a known issue (for me yes)

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
@weizhouapache is this considered critical for 4.20 release? cc @JoaoJandre 

@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test ol9 kvm-ol9

**Comment by weizhouapache** [comment]
@blueorangutan test ol8 kvm-ol8

**Review by vishesh92 — APPROVED** [review]
clgtm. packaging is successful.

**Comment by weizhouapache** [comment]
kicked off tests on
- ol8
- ol9
- ubuntu24
- debian12

let's wait

**Review by JoaoJandre — APPROVED** [review]

**Comment by weizhouapache** [comment]
this is ready for review

the smoke test results look fine

**Comment by rohityadavcloud** [comment]
LGTM, tests & review LGTM. Only affects deb packaging that too installation of a required dependency on Ubuntu.

**Pull request merged**
