### PR TITLE
L10n update 4.8 20160422

### PR DESCRIPTION
**Pull request by milamberspace**
@swill the good PR for 4.8 branch.

### CODE REVIEW

**Comment by swill** [comment]
Can you squash the commits for me?  I will get this merged and then forward merged to master and then we can rebase the other ones to to make sure we don't have merge conflicts.  Thanks...

**Comment by milamberspace** [comment]
@swill It's done.

**Comment by swill** [comment]
@milamberspace sorry to do this to you again.  :(  Can you force push again so we can try to get travis green.  Thanks...

**Comment by milamberspace** [comment]
@swill re-push force done.

**Comment by swill** [comment]
@milamberspace and again.  :P sorry...

**Comment by milamberspace** [comment]
@swill re-done.

**Comment by swill** [comment]
Well Jenkins just does not like us today.  Can you review the error and see if it is a valid error and try again?

**Comment by swill** [comment]
I see another PR with the same error, so I doubt it is your PR.

**Comment by milamberspace** [comment]
@swill Now the Jenkins build works, but the Travis failed with:
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
...

**Comment by milamberspace** [comment]
@swill after a new push to start a new Travis build, Travis and Jenkins are now green! You can merge the PR! :-)

**Comment by swill** [comment]
awesome, thank you sir.  i will get this merged today...

**Comment by rhtyd** [comment]
LGTM

tag:mergeready

**Comment by swill** [comment]
Please rebase this PR to fix the merge conflicts.  Thanks...  #1527 has been merged into 4.7 and then forward merged to 4.8 and then master.  Once the merge conflicts are fixed in this PR, I will merge this one next and then I will check if #1376 has conflicts (which it currently does).

**Comment by milamberspace** [comment]
@swill conflicts fixed. Push with force done, ready to merge.

**Pull request merged**
