### PR TITLE
[UI] Allow detach ISO from instance toolbar when ISO is attached

### LINKED ISSUE #8711: Attach ISO tooltip for instances with ISO attached
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.19
~~~

##### SUMMARY

On UI navigation the tooltip says 'Attach ISO' instead of 'Detach ISO' for instance with ISO attached.

Screenshot 2024-02-27 at 3 59 38 PM

Screenshot 2024-02-27 at 3 59 48 PM

### PR DESCRIPTION
**Pull request by sureshanaparti**
### Description

This PR allows detach ISO from instance toolbar when ISO is attached.

Fixes #8711

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### How Has This Been Tested?

Manually tested attach & detach ISO from instance toolbar.

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan ui

**Comment by sureshanaparti** [comment]
@blueorangutan ui

**Review by DaanHoogland — APPROVED** [review]
clgtm, tested in qa

**Review by JoaoJandre — APPROVED** [review]
CLGTM, also tested in QA

**Pull request merged**
