### PR TITLE
cks: add boot option params for cluster vms

### LINKED ISSUE #4120: CKS: Consider the UEFI for the VMs used as nodes
##### ISSUE TYPE

 * Improvement Request

Purely as an enhancement, consider having the option to choose whether the master/worker nodes should use UEFI or BIOS on hypervisor side - if (and only if) it makes sense for the next-to-be-chosen OS for CKS (instead of CoreOS).

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #4120

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by rohityadavcloud** [comment]
Is this valid or already fixed cc @Pearl1594 ?

**Comment by shwstppr** [comment]
@rohityadavcloud @Pearl1594 maybe revisit this in next release. This may need adding new parameters to createKubernetesCluster API

**Comment by nvazquez** [comment]
Thanks @shwstppr, including it in 4.17. Can you please fix the conflicts?

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
Closing this PR since the issue #4120 is no longer valid

**Pull request closed without merging**
