### PR TITLE
User allowed to tag project created by him

### PR DESCRIPTION
**Pull request by Spaceman1984**
## Description

Fixed issue where a user cannot tag a project.

To reproduce:

in the UI:

log in as a user type
create a project
tag the new created project

Fixes: #2823
## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

Tested from UI.

Created a new project, and tagged the project, no errors.

Tested with cloudmonkey

Tested under Ubuntu server 18.04.2 LTS using the simulator

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@anuragaw you say "username is fed into ...", a username is not the same as an account name!
sounds like it's a hazardous assumption

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
It seems this causes #3377 . we may have to revert :(

**Pull request merged**
