### PR TITLE
UI: Fix sorter across different components

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR fixes sorting in tables by columns in the UI.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
code looks good

**Comment by DaanHoogland** [comment]
@blueorangutan ui

**Comment by vishesh92** [comment]
@blueorangutan ui

**Review by rohityadavcloud — APPROVED** [review]
Code LGTM, need to test

**Comment by rohityadavcloud** [comment]
Tested a few views - VM, volumes, ip address and templates.

**Pull request merged**
