### PR TITLE
add metadata to KVM domain (Issue 6695 fix)

### PR DESCRIPTION
**Pull request by Jehan-h20220012**
### Description

This PR...
Fixes: #6695 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by slavkap** [comment]
Hi @Jehan-h20220012, could you please add a more descriptive title and message?

You need to pass this setting when starting a VM. You can try adding it to the VM's details or do some research on how it would be better. The main part of the Domain's XML is generated from [here](https://github.com/apache/cloudstack/blob/main/plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java#L171). when the setting is enabled you need to append the required metadata to the XML.

https://libvirt.org/formatdomain.html#general-metadata

**Comment by Jehan-h20220012** [comment]
@slavkap Thank you, I will look into it and will let know if any help needed.

**Comment by DaanHoogland** [comment]
@Jehan-h20220012 what @slavkap said and can you add test description as well, please? good luck.

**Comment by DaanHoogland** [comment]
@Jehan-h20220012 is this still relevant? are you still looking at this? (cc @slavkap )

**Comment by Jehan-h20220012** [comment]
> @Jehan-h20220012 is this still relevant? are you still looking at this? (cc @slavkap )

I have no updates on it and this issue might have been resolved by some other PRs.

**Comment by DaanHoogland** [comment]
@slavkap @shwstppr should we postpone or try to get this in 4.19?

**Comment by shwstppr** [comment]
@DaanHoogland I don't think this is ready yet. PR just adds the global config but I don't see its value being queried. Or maybe I'm missing something

**Comment by DaanHoogland** [comment]
No @shwstppr , let's abandon this and reboot when there is call for it.

**Pull request closed without merging**
