### PR TITLE
CLOUDSTACK-9180: Optimize concurrent VM deployment operation on same …

### PR DESCRIPTION
**Pull request by koushik-das**
…network

Check if VR needs to be allocated for a given network and only acquire lock if required

Refer to the bug for details.

### CODE REVIEW

**Comment by koushik-das** [comment]
Simulator test results for basic zone. Failure is for NiciraNvp which can be ignored.
-------------------------------------------------------------------------------------------------------------------------

test DeployVM in anti-affinity groups ... === TestName: test_DeployVmAntiAffinityGroup | Status : SUCCESS ===
ok
Test to deploy vm with a first fit offering ... === TestName: test_deployvm_firstfit | Status : SUCCESS ===
ok
Test deploy VMs using user concentrated planner ... === TestName: test_deployvm_userconcentrated | Status : SUCCESS ===
ok
Test deploy VMs using user dispersion planner ... === TestName: test_deployvm_userdispersing | Status : SUCCESS ===
ok
Test to create disk offering ... === TestName: test_01_create_disk_offering | Status : SUCCESS ===
ok
Test to create  a sparse type disk offering ... === TestName: test_02_create_sparse_type_disk_offering | Status : SUCCESS ===
ok
Test to create  a sparse type disk offering ... === TestName: test_04_create_fat_type_disk_offering | Status : SUCCESS ===
ok
Test to update existing disk offering ... === TestName: test_02_edit_disk_offering | Status : SUCCESS ===
ok
Test to delete disk offering ... === TestName: test_03_delete_disk_offering | Status : SUCCESS ===
ok
test update configuration setting at zone level scope ... === TestName: test_UpdateConfigParamWithScope | Status : SUCCESS ===
ok
test_nic_secondaryip_add_remove (integration.smoke.test_multipleips_per_nic.TestDeployVM) ... === TestName: test_nic_secondaryip_add_remove | Status : SUCCESS ===
ok
Failure: ImportError (cannot import name NiciraNvp) ... === TestName: Failure: | Status : EXCEPTION ===
ERROR
Test to create a portable public ip range ... === TestName: test_createPortablePublicIPRange | Status : SUCCESS ===
ok
Test primary storage pools - XEN, KVM, VMWare. Not Supported for hyperv ... === TestName: test_01_primary_storage_nfs | Status : SUCCESS ===
ok
Test reset virtual machine on reboot ... === TestName: test_01_reset_vm_on_reboot | Status : SUCCESS ===
ok
Test system VM start ... === TestName: test_01_sys_vm_start | Status : SUCCESS ===
ok
Test system templates are ready ... === TestName: test_02_sys_template_ready | Status : SUCCESS ===
ok
Test to create service offering ... === TestName: test_01_create_service_offering | Status : SUCCESS ===
ok
Test to update existing service offering ... === TestName: test_02_edit_service_offering | Status : SUCCESS ===
ok
Test to delete service offering ... === TestName: test_03_delete_service_offering | Status : SUCCESS ===
ok
Test Edit template ... === TestName: test_02_edit_template | Status : SUCCESS ===
ok
Test delete template ... === TestName: test_03_delete_template | Status : SUCCESS ===
ok
Update & Test for template permissions ... === TestName: test_05_template_permissions | Status : SUCCESS ===
ok
Test only public templates are visible to normal user ... === TestName: test_07_list_public_templates | Status : SUCCESS ===
ok
Test System templates are not visible to normal user ... === TestName: test_08_list_system_templates | Status : SUCCESS ===
ok
Download a Volume attached to a VM ... === TestName: test_03_download_attached_volume | Status : SUCCESS ===
ok
Delete a Volume attached to a VM ... === TestName: test_04_delete_attached_volume | Status : SUCCESS ===
ok
Detach a Volume attached to a VM ... === TestName: test_05_detach_volume | Status : SUCCESS ===
ok
Delete a Volume unattached to an VM ... === TestName: test_09_delete_detached_volume | Status : SUCCESS ===
ok

Ran 29 tests in 462.825s

FAILED (errors=1)
-----------------------------------------------------------------------------------------------


Selective advanced zone tests on simulator
-------------------------------------------------------

test_vm_life_cycle.py

Test advanced zone virtual router ... === TestName: test_advZoneVirtualRouter | Status : SUCCESS ===
ok
Test Deploy Virtual Machine ... === TestName: test_deploy_vm | Status : SUCCESS ===
ok
Test Multiple Deploy Virtual Machine ... === TestName: test_deploy_vm_multiple | Status : SUCCESS ===
ok
Test Stop Virtual Machine ... === TestName: test_01_stop_vm | Status : SUCCESS ===
ok
Test Start Virtual Machine ... === TestName: test_02_start_vm | Status : SUCCESS ===
ok
Test Reboot Virtual Machine ... === TestName: test_03_reboot_vm | Status : SUCCESS ===
ok
Test destroy Virtual Machine ... === TestName: test_06_destroy_vm | Status : SUCCESS ===
ok
Test recover Virtual Machine ... === TestName: test_07_restore_vm | Status : SUCCESS ===
ok
Test migrate VM ... === TestName: test_08_migrate_vm | Status : SUCCESS ===
ok
Test destroy(expunge) Virtual Machine ... === TestName: test_09_expunge_vm | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 10 tests in 306.163s

OK

test_network.py

Test for delete account ... === TestName: test_delete_account | Status : SUCCESS ===
ok
Test for Associate/Disassociate public IP address for admin account ... === TestName: test_public_ip_admin_account | Status : SUCCESS ===
ok
Test for Associate/Disassociate public IP address for user account ... === TestName: test_public_ip_user_account | Status : SUCCESS ===
ok
Test for release public IP address ... === TestName: test_releaseIP | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 4 tests in 779.509s

OK

test_routers.py

Test router internal advanced zone ... SKIP: Marvin configuration has no host credentials                            to check router services
Test restart network ... === TestName: test_03_restart_network_cleanup | Status : SUCCESS ===
ok
Test router basic setup ... === TestName: test_05_router_basic | Status : SUCCESS ===
ok
Test router advanced setup ... === TestName: test_06_router_advanced | Status : SUCCESS ===
ok
Test stop router ... === TestName: test_07_stop_router | Status : SUCCESS ===
ok
Test start router ... === TestName: test_08_start_router | Status : SUCCESS ===
ok
Test reboot router ... === TestName: test_09_reboot_router | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 7 tests in 41.786s

OK (SKIP=1)

test_multipleips_per_nic.py

test_nic_secondaryip_add_remove (integration.smoke.test_multipleips_per_nic.TestDeployVM) ... === TestName: test_nic_secondaryip_add_remove | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 1 test in 25.983s

OK

test_portable_publicip.py

Test to acquire a provisioned public ip range ... === TestName: test_createPortablePublicIPAcquire | Status : SUCCESS ===
ok
Test to create a portable public ip range ... === TestName: test_createPortablePublicIPRange | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 2 tests in 61.391s

OK

test_privategw_acl.py

test_privategw_acl (integration.smoke.test_privategw_acl.TestPrivateGwACL) ... === TestName: test_privategw_acl | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 1 test in 46.513s

OK

test_public_ip_range.py

Test public IP range dedication ... === TestName: test_dedicatePublicIpRange | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 1 test in 5.557s

OK

**Comment by pedro-martins** [comment]
nice =)
Can you create a java doc to explain your 'isRouterDeployed()'  (even the name explaining itself)? 
If you can create a test case for only this method it will be more easy to verify if it stop working in future modifications =) 
Thx.

**Comment by koushik-das** [comment]
@pedro-martins By java doc are you referring to adding some comments for isRouterDeployed()? Note that this is a private method.
If you look at the unit tests I have added, isRouterDeployed() is getting invoked in them. The function invocation count verification ensures that the method is called.

**Comment by pedro-martins** [comment]
A javadoc is a notation above the method declaration that describes what the method do.
javadoc with examples :)  http://www.oracle.com/technetwork/articles/java/index-137868.html

I saw that you create a test for the deployVirtualRouter that uses the isRouterDeployed(), but if this test don't pass, will be difficult to analyse if the test don't pass because the isRouterDeployed method or another problem.  :) 

Ty.

**Comment by wilderrodrigues** [comment]
Ping @remibergsma 

This one ca have the integrations tests executed against.

@pedro-martins: no need to add javadocs. The code should be self-documented. A private method called ```isRouterDeployed``` is already clear enough.

Cheers,
Wilder

**Comment by DaanHoogland** [comment]
@wilderrodrigues Agreed @pedro-martins comments, persé should add to the clarity of the code, even javadoc. If the name is explanatory and there are no unexpected side effects we should not create them, especially for private methods. It doubles the maintenance needed. When changes are done both the code and the comments needs to change.

**Comment by koushik-das** [comment]
@bvbharat Can you run the tests on this one?

**Comment by bvbharatk** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 175
 Hypervisor xenserver
 NetworkType Advanced
 Passed=34
 Failed=21
 Skipped=2

_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/yj3wnzbceo9uef2/AAB6u-Iap-xztdm6jHX9SjPja?dl=0


**Failed tests:**
* test_affinity_groups_projects.py

 * ContextSuite context=TestDeployVmWithAffinityGroup>:teardown Failed

* test_vpc_vpn.py

 * ContextSuite context=TestVpcRemoteAccessVpn>:setup Failing since 5 runs

 * ContextSuite context=TestVpcSite2SiteVpn>:setup Failing since 3 runs

* test_scale_vm.py

 * ContextSuite context=TestScaleVm>:teardown Failed

* test_routers_iptables_default_policy.py

 * test_01_single_VPC_iptables_policies Failed

 * ContextSuite context=TestVPCIpTablesPolicies>:teardown Failed

* test_quota.py

 * test_01_quota Failing since 3 runs

 * test_02_quota Failing since 3 runs

 * test_03_quota Failing since 3 runs

 * test_04_quota Failing since 3 runs

 * test_05_quota Failing since 3 runs

 * test_06_quota Failing since 3 runs

 * test_07_quota Failing since 3 runs

* test_loadbalance.py

 * ContextSuite context=TestLoadBalance>:setup Failing since 2 runs

* test_network.py

 * test_delete_account Failing since 2 runs

 * ContextSuite context=TestPortForwarding>:setup Failing since 2 runs

 * ContextSuite context=TestPublicIP>:setup Failed

 * test_reboot_router Failing since 2 runs

 * test_releaseIP Failing since 2 runs

 * ContextSuite context=TestRouterRules>:setup Failing since 2 runs

* test_password_server.py

 * test_isolate_network_password_server Failing since 2 runs


**Skipped tests:**
test_vm_nic_adapter_vmxnet3
test_deploy_vgpu_enabled_vm

**Passed test suits:**
test_deploy_vm_with_userdata.py
test_over_provisioning.py
test_guest_vlan_range.py
test_service_offerings.py
test_reset_vm_on_reboot.py
test_deploy_vms_with_varied_deploymentplanners.py
test_deploy_vm_iso.py
test_public_ip_range.py
test_multipleips_per_nic.py
test_regions.py
test_resource_detail.py
test_secondary_storage.py
test_vm_life_cycle.py

**Comment by rhtyd** [comment]
@koushik-das can you rebase against latest master and share state of your PR, thanks

**Comment by swill** [comment]
### CI RESULTS

```
Tests Run: 82
  Skipped: 0
   Failed: 1
   Errors: 4
 Duration: 9h 31m 01s
```

**Summary of the problem(s):**
```
ERROR: Test to verify access to loadbalancer haproxy admin stats page
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/git/cs1/cloudstack/test/integration/smoke/test_internal_lb.py", line 854, in tearDown
    raise Exception("Cleanup failed with %s" % e)
Exception: Cleanup failed with Job failed: {jobprocstatus : 0, created : u'2016-05-20T01:01:48+0200', jobresult : {errorcode : 530, errortext : u'Failed to delete network'}, cmd : u'org.apache.cloudstack.api.command.user.network.DeleteNetworkCmd', userid : u'7419d6d0-1de7-11e6-9293-5254001daa61', jobstatus : 2, jobid : u'63713d1c-6f2b-480f-a7a3-8f5bac6328bc', jobresultcode : 530, jobresulttype : u'object', jobinstancetype : u'Network', accountid : u'7419c212-1de7-11e6-9293-5254001daa61'}
----------------------------------------------------------------------
Additional details in: /tmp/MarvinLogs/test_network_TL42E7/results.txt
```

```
ERROR: test suite for <class 'integration.smoke.test_vpc_vpn.TestRVPCSite2SiteVpn'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/suite.py", line 209, in run
    self.setUp()
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/util.py", line 471, in try_run
    return func()
  File "/data/git/cs1/cloudstack/test/integration/smoke/test_vpc_vpn.py", line 835, in setUpClass
    cls.template.download(cls.apiclient)
  File "/usr/lib/python2.7/site-packages/marvin/lib/base.py", line 1350, in download
    elif 'Downloaded' in template.status:
TypeError: argument of type 'NoneType' is not iterable
----------------------------------------------------------------------
Additional details in: /tmp/MarvinLogs/test_network_TL42E7/results.txt
```

```
ERROR: test suite for <class 'integration.smoke.test_vpc_vpn.TestVpcRemoteAccessVpn'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/suite.py", line 209, in run
    self.setUp()
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/util.py", line 471, in try_run
    return func()
  File "/data/git/cs1/cloudstack/test/integration/smoke/test_vpc_vpn.py", line 293, in setUpClass
    cls.template.download(cls.apiclient)
  File "/usr/lib/python2.7/site-packages/marvin/lib/base.py", line 1350, in download
    elif 'Downloaded' in template.status:
TypeError: argument of type 'NoneType' is not iterable
----------------------------------------------------------------------
Additional details in: /tmp/MarvinLogs/test_network_TL42E7/results.txt
```

```
ERROR: test suite for <class 'integration.smoke.test_vpc_vpn.TestVpcSite2SiteVpn'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/suite.py", line 209, in run
    self.setUp()
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/util.py", line 471, in try_run
    return func()
  File "/data/git/cs1/cloudstack/test/integration/smoke/test_vpc_vpn.py", line 472, in setUpClass
    cls.template.download(cls.apiclient)
  File "/usr/lib/python2.7/site-packages/marvin/lib/base.py", line 1350, in download
    elif 'Downloaded' in template.status:
TypeError: argument of type 'NoneType' is not iterable
----------------------------------------------------------------------
Additional details in: /tmp/MarvinLogs/test_network_TL42E7/results.txt
```

```
FAIL: Test destroy(expunge) Virtual Machine
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/git/cs1/cloudstack/test/integration/smoke/test_vm_life_cycle.py", line 646, in test_09_expunge_vm
    self.assertEqual(list_vm_response,None,"Check Expunged virtual machine is in listVirtualMachines response")
AssertionError: Check Expunged virtual machine is in listVirtualMachines response
----------------------------------------------------------------------
Additional details in: /tmp/MarvinLogs/test_vpc_routers_6NRPKU/results.txt
```



**Associated Uploads**

**`/tmp/MarvinLogs/DeployDataCenter__May_19_2016_19_33_43_9O7LI4:`**
* [dc_entries.obj](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1251/tmp/MarvinLogs/DeployDataCenter__May_19_2016_19_33_43_9O7LI4/dc_entries.obj)
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1251/tmp/MarvinLogs/DeployDataCenter__May_19_2016_19_33_43_9O7LI4/failed_plus_exceptions.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1251/tmp/MarvinLogs/DeployDataCenter__May_19_2016_19_33_43_9O7LI4/runinfo.txt)

**`/tmp/MarvinLogs/test_network_TL42E7:`**
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1251/tmp/MarvinLogs/test_network_TL42E7/failed_plus_exceptions.txt)
* [results.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1251/tmp/MarvinLogs/test_network_TL42E7/results.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1251/tmp/MarvinLogs/test_network_TL42E7/runinfo.txt)

**`/tmp/MarvinLogs/test_vpc_routers_6NRPKU:`**
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1251/tmp/MarvinLogs/test_vpc_routers_6NRPKU/failed_plus_exceptions.txt)
* [results.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1251/tmp/MarvinLogs/test_vpc_routers_6NRPKU/results.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1251/tmp/MarvinLogs/test_vpc_routers_6NRPKU/runinfo.txt)


Uploads will be available until `2016-07-20 02:00:00 +0200 CEST`

*Comment created by [`upr comment`](https://github.com/cloudops/upr).*

**Comment by swill** [comment]
I don't think these issues are related to this PR, but if you have any insight as to why they might be happening I would be interested.  I will run this CI again to see if we can get a bit of a cleaner report.

**Comment by koushik-das** [comment]
@swill The failures are not related to this PR.
The failure in test_internal_lb.py is due to some cleanup issue. The network deletion failed most probably due to some leftover VMs.
The remaining failures seems to be some environment issue due to which templates are not downloaded and also some test code issue in base.py. In the below snippet, the execution is going to elif and that is resulting in failure due to 'in' check on template.status which doesn't seem to be iterable. 
                if template.status == 'Download Complete':
                    break
                elif 'Downloaded' in template.status:
                    time.sleep(interval)
                elif 'Installing' not in template.status:
                    raise Exception(
                        "Error in downloading template: status - %s" %
                        template.status)

**Comment by swill** [comment]
Thanks @koushik-das, I need to track down what changed to cause that intermittent problem of the `template.status`.  I need some code review on this one.  Thanks...

**Comment by swill** [comment]
### CI RESULTS

```
Tests Run: 82
  Skipped: 0
   Failed: 0
   Errors: 4
 Duration: 8h 31m 38s
```

**Summary of the problem(s):**
```
ERROR: test suite for <class 'integration.smoke.test_internal_lb.TestInternalLb'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/suite.py", line 228, in run
    self.tearDown()
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/suite.py", line 351, in tearDown
    self.teardownContext(ancestor)
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/suite.py", line 367, in teardownContext
    try_run(context, names)
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/util.py", line 471, in try_run
    return func()
  File "/data/git/cs1/cloudstack/test/integration/smoke/test_internal_lb.py", line 847, in tearDownClass
    raise Exception("Cleanup failed with %s" % e)
Exception: Cleanup failed with Job failed: {jobprocstatus : 0, created : u'2016-05-20T11:25:42+0200', jobresult : {errorcode : 530, errortext : u'Failed to delete template'}, cmd : u'org.apache.cloudstack.api.command.user.template.DeleteTemplateCmd', userid : u'e34c6f59-1e44-11e6-9276-5254001daa61', jobstatus : 2, jobid : u'88b5638b-7732-4e6d-9ccf-9a3be346b281', jobresultcode : 530, jobinstanceid : u'3cd24df8-bd13-4250-8706-a43e9e42c754', jobresulttype : u'object', jobinstancetype : u'Template', accountid : u'e34c5a5a-1e44-11e6-9276-5254001daa61'}
----------------------------------------------------------------------
Additional details in: /tmp/MarvinLogs/test_network_GHIWU7/results.txt
```

```
ERROR: test suite for <class 'integration.smoke.test_vpc_vpn.TestRVPCSite2SiteVpn'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/suite.py", line 209, in run
    self.setUp()
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/util.py", line 471, in try_run
    return func()
  File "/data/git/cs1/cloudstack/test/integration/smoke/test_vpc_vpn.py", line 835, in setUpClass
    cls.template.download(cls.apiclient)
  File "/usr/lib/python2.7/site-packages/marvin/lib/base.py", line 1350, in download
    elif 'Downloaded' in template.status:
TypeError: argument of type 'NoneType' is not iterable
----------------------------------------------------------------------
Additional details in: /tmp/MarvinLogs/test_network_GHIWU7/results.txt
```

```
ERROR: test suite for <class 'integration.smoke.test_vpc_vpn.TestVpcRemoteAccessVpn'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/suite.py", line 209, in run
    self.setUp()
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/util.py", line 471, in try_run
    return func()
  File "/data/git/cs1/cloudstack/test/integration/smoke/test_vpc_vpn.py", line 293, in setUpClass
    cls.template.download(cls.apiclient)
  File "/usr/lib/python2.7/site-packages/marvin/lib/base.py", line 1350, in download
    elif 'Downloaded' in template.status:
TypeError: argument of type 'NoneType' is not iterable
----------------------------------------------------------------------
Additional details in: /tmp/MarvinLogs/test_network_GHIWU7/results.txt
```

```
ERROR: test suite for <class 'integration.smoke.test_vpc_vpn.TestVpcSite2SiteVpn'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/suite.py", line 209, in run
    self.setUp()
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/usr/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/util.py", line 471, in try_run
    return func()
  File "/data/git/cs1/cloudstack/test/integration/smoke/test_vpc_vpn.py", line 472, in setUpClass
    cls.template.download(cls.apiclient)
  File "/usr/lib/python2.7/site-packages/marvin/lib/base.py", line 1350, in download
    elif 'Downloaded' in template.status:
TypeError: argument of type 'NoneType' is not iterable
----------------------------------------------------------------------
Additional details in: /tmp/MarvinLogs/test_network_GHIWU7/results.txt
```



**Associated Uploads**

**`/tmp/MarvinLogs/DeployDataCenter__May_20_2016_06_42_48_FTFEG1:`**
* [dc_entries.obj](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1251/tmp/MarvinLogs/DeployDataCenter__May_20_2016_06_42_48_FTFEG1/dc_entries.obj)
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1251/tmp/MarvinLogs/DeployDataCenter__May_20_2016_06_42_48_FTFEG1/failed_plus_exceptions.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1251/tmp/MarvinLogs/DeployDataCenter__May_20_2016_06_42_48_FTFEG1/runinfo.txt)

**`/tmp/MarvinLogs/test_network_GHIWU7:`**
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1251/tmp/MarvinLogs/test_network_GHIWU7/failed_plus_exceptions.txt)
* [results.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1251/tmp/MarvinLogs/test_network_GHIWU7/results.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1251/tmp/MarvinLogs/test_network_GHIWU7/runinfo.txt)

**`/tmp/MarvinLogs/test_vpc_routers_SEIXAD:`**
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1251/tmp/MarvinLogs/test_vpc_routers_SEIXAD/failed_plus_exceptions.txt)
* [results.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1251/tmp/MarvinLogs/test_vpc_routers_SEIXAD/results.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1251/tmp/MarvinLogs/test_vpc_routers_SEIXAD/runinfo.txt)


Uploads will be available until `2016-07-20 02:00:00 +0200 CEST`

*Comment created by [`upr comment`](https://github.com/cloudops/upr).*

**Comment by swill** [comment]
Similar issues on this run.  They are not related to this PR.  Still need some review on this one...

**Comment by swill** [comment]
Need code review on this one.  Thx...

**Comment by kansal** [comment]
LGTM.

**Pull request merged**
