### PR TITLE
Replace Hashtable with LinkedHashMap in createIsoResponse

### PR DESCRIPTION
**Pull request by CharlesQueiroz**
### Description

This change replaces Hashtable with LinkedHashMap in the `createIsoResponse` method of `ViewResponseHelper`.
This modification is to maintain the insertion order of entries, which isn't the case with Hashtable.

This solves the problem described here: 

https://github.com/apache/cloudstack/issues/7278

Related to the ordering of the ISOs table in CloudStack.
Currently, the order is not maintained because, when using a Hashtable, the insertion order gets lost when it tries to create the list on the API side.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
thanks @CharlesQueiroz for the fix

Hashtable is used many times in same PR. can you fix the others as well ?

@kiranchavala can you please verify it ?

**Comment by kiranchavala** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by weizhouapache** [comment]
thanks @CharlesQueiroz for the update
it looks there is still one in the class
```
Hashtable<Long, UserVmResponse> vmDataList = new Hashtable<Long, UserVmResponse>();
```

**Comment by CharlesQueiroz** [comment]
> thanks @CharlesQueiroz for the update it looks there is still one in the class
> 
> ```
> Hashtable<Long, UserVmResponse> vmDataList = new Hashtable<Long, UserVmResponse>();
> ```


Oh.. you're right. I've already fixed it. I patched the commit with this change.

Sorry about that. :P

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by kiranchavala — APPROVED** [review]
LGTM , Tested manually, the order of the ISO is maintained, able to move to the top/bottom and move one row up/down

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Review by rohityadavcloud — APPROVED** [review]
LGTM, didn't test it myself but changes and description makes sense.
I'm not sure if manual testing is needed, but any integration/marvin test would be great. Also I'm not sure of any consequences/side effects of this.

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by weizhouapache** [comment]
@blueorangutan test matrix

**Comment by soreana** [comment]
@blueorangutan package

**Pull request merged**
