### PR TITLE
Fix the problem at #1740 when it loads all snapshots in the primary storage

### PR DESCRIPTION
**Pull request by rafaelweingartner**
## Description

While checking a problem with @mike-tutkowski at PR #1740, we noticed that the method `org.apache.cloudstack.storage.snapshot.SnapshotDataFactoryImpl.getSnapshots(long, DataStoreRole)` was not loading the snapshots in `snapshot_store_ref` table according to their storage role. Instead, it would return a list of all snapshots (even if they are not in the storage role sent as a parameter) saying that they are in the storage that was sent as parameter.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?
Manually and unit tests

## Checklist:

- [X] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
Testing
- [ ] I have added tests to cover my changes.
- [ ] All relevant new and existing integration tests have passed.
- [ ] A full integration testsuite with all test that can run on my environment has passed.

### CODE REVIEW

**Comment by rafaelweingartner** [comment]
@mike-tutkowski can you take a look at this PR? This is the follow-up of that #1740

**Comment by mike-tutkowski** [comment]
The code LGTM. Also, I have run the particular managed-storage test suite (this one only contains two tests) that initially led me to #1740 and both tests in it passed:

test_online_migrate_volume_from_nfs_storage_to_managed_storage (TestOnlineStorageMigration.TestOnlineStorageMigration) ... === TestName: test_online_migrate_volume_from_nfs_storage_to_managed_storage | Status : SUCCESS ===
ok
test_online_migrate_volume_with_snapshot_from_nfs_storage_to_managed_storage (TestOnlineStorageMigration.TestOnlineStorageMigration) ... === TestName: test_online_migrate_volume_with_snapshot_from_nfs_storage_to_managed_storage | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 2 tests in 472.520s

OK

**Comment by DaanHoogland** [comment]
looks good
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Pull request merged**
