### PR TITLE
server: fix wrong error message when create isolated network without SourceNat

### PR DESCRIPTION
**Pull request by ustcweizhou**
### Description

This PR fixes wrong message when create isolated network without SourceNat

When I created network without sourcenat, I got message below
```
(localcloud) 🐱 > create network name=fully-isolated-noservices displaytext=fully-isolated-noservices networkofferingid=83f13c21-38fd-439f-a0fc-54d6d5233fec zoneid=70e90072-db05-42c0-a639-71d16d905406
🙈 Error: (HTTP 431, error code 4350) StartIp/endIp/gateway/netmask are required when create network of type Shared and network of type Isolated with service SourceNat disabled
```
However, when I passed StartIp/endIp/gateway/netmask, it also failed.
```
(localcloud) 🐱 > create network name=fully-isolated-noservices displaytext=fully-isolated-noservices networkofferingid=83f13c21-38fd-439f-a0fc-54d6d5233fec zoneid=70e90072-db05-42c0-a639-71d16d905406 startip=192.168.101.2 endip=192.168.101.20 gateway=192.168.101.1 netmask=255.255.255.0
🙈 Error: (HTTP 431, error code 4350) Network offering with specified id doesn't support adding multiple ip ranges
```

without startip/endip, the following worked.
```
create network name=fully-isolated-noservices displaytext=fully-isolated-noservices networkofferingid=83f13c21-38fd-439f-a0fc-54d6d5233fec zoneid=70e90072-db05-42c0-a639-71d16d905406 gateway=192.168.102.1 netmask=255.255.255.0
```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### CODE REVIEW

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
@blueorangutan package

**Review by shwstppr — APPROVED** [review]
LGTM

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Pull request merged**
