### PR TITLE
CLOUDSTACK-9183: bash: /opt/cloud/bin/getRouterAlerts.sh: No such fil…

### PR DESCRIPTION
**Pull request by olafurgreen**
…e or directory

### CODE REVIEW

**Comment by olafurgreen** [comment]
Seams like Wilder Rodrigues accidentally deleted this file so I just want to bring back.

**Comment by rhtyd** [comment]
I think this is an issue only in 4.7 branch, the file has been removed in recent branches. @PaulAngus can share his insights on this as well.

**Comment by ProjectMoon** [comment]
In the JIRA ticket, it's at least reported that this is happening on 4.8 as well.

**Comment by rhtyd** [comment]
LGTM, this seems like a regression introduced by https://github.com/apache/cloudstack/commit/6477bd8ff7f982e10d0d20a97857262897dc05ed

I think we can merge this, regression tests won't catch the error caused by this script's removal. Pinging for review @murali-reddy @abhinandanprateek @karuturi

**Comment by rhtyd** [comment]
I tested this, the script is useful for getting alerts when any expected service running on VR fails. A `monitorServices.py` script monitors such services and tries to recover failing services, while logging this at `/var/log/routerServiceMonitor.log`. Without this script, mgmt server/admins won't know when an error such as failing service has happened. LGTM on manual testing.

**Comment by olafurgreen** [comment]
This file is also missing in 4.9

**Comment by rhtyd** [comment]
@olafurgreen thanks, we'll fwd-merge this on all 4.7+ branches.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan centos7 vmware-55u3

**Comment by rhtyd** [comment]
@blueorangutan centos7 vmware-55u3

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
The failures from last test run are related to env, also they ran on 4.7 branch where several of the integration test fixes were not made.

**Comment by rhtyd** [comment]
Merging this based on git history changes found in 6477bd8
Several test failures are not related to the changes, but because marvin test fixes were not merged on 4.7 branch. Going ahead with the merge, since this only adds a delete file.

**Pull request merged**
