### PR TITLE
CLOUDSTACK-9719: [VMware] VR loses DHCP settings and VMs cannot obtain IP after HA recovery - Set high restart priority for the VR.

### PR DESCRIPTION
**Pull request by sureshanaparti**
[VMware] VR loses DHCP settings and VMs cannot obtain IP after HA recovery.
Fix: Set high restart priority for the VR.

Test scenarios:
- Enable cluster HA after VR is created. Now stop and start VR and check its restart priority, should be High.
- Enable cluster HA before VR is created. Now create some VM and verify that VR created must have High restart priority.

Issue validation steps:
- Create a VMware setup with a cluster having 2 ESXi hosts and Enable HA at cluster level in vCenter.
- Creat a Network offering with DHCP and source NAT
- Create few VMs using network created above and Ensure that router VM is created with restart priority set to High.
- Make the ESXi host (where router VM is running) unreachable.
- Verified that router VM is first migrated to other host and VMs acquire IP via DHCP.

### CODE REVIEW

**Comment by karuturi** [comment]
@blueorangutan help

**Comment by karuturi** [comment]
@blueorangutan test centos7 vmware-55u3

**Comment by rhtyd** [comment]
@sureshanaparti can you push -f on the PR, Travis failed.
@blueorangutan package

**Comment by sureshanaparti** [comment]
@rhtyd Can you kick off VMware CI on this PR.

**Comment by rhtyd** [comment]
Sure. 
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-55u3

**Comment by sureshanaparti** [comment]
@rhtyd Thanks for running these test. The failures/errors are not related to this PR changes.

**Comment by sureshanaparti** [comment]
@sateesh-chodapuneedi @rhtyd  Please review the code changes.

**Comment by sureshanaparti** [comment]
@nvazquez @serg38 Please review the code changes.

**Comment by serg38** [comment]
LGTM @nvazquez Can we test it with shared networking?

**Comment by nvazquez** [comment]
Sure @serg38, after enabling HA on cluster, stopping VR and the starting VR we got this exception on ESXi 6:
````
2017-03-06 12:18:14,654 ERROR [cloud.vm.VmWorkJobDispatcher] (Work-Job-Executor-4:ctx-d275214a job-8521/job-8522) Unable to complete AsyncJobVO {id:8522, userId: 2, accountId: 2, instanceType: null, instanceId: null, cmd: com.cloud.vm.VmWorkStart, cmdInfo: rO0ABXNyABhjb20uY2xvdWQudm0uVm1Xb3JrU3RhcnR9cMGsvxz73gIAC0oABGRjSWRMAAZhdm9pZHN0ADBMY29tL2Nsb3VkL2RlcGxveS9EZXBsb3ltZW50UGxhbm5lciRFeGNsdWRlTGlzdDtMAAljbHVzdGVySWR0ABBMamF2YS9sYW5nL0xvbmc7TAAGaG9zdElkcQB-AAJMAAtqb3VybmFsTmFtZXQAEkxqYXZhL2xhbmcvU3RyaW5nO0wAEXBoeXNpY2FsTmV0d29ya0lkcQB-AAJMAAdwbGFubmVycQB-AANMAAVwb2RJZHEAfgACTAAGcG9vbElkcQB-AAJMAAlyYXdQYXJhbXN0AA9MamF2YS91dGlsL01hcDtMAA1yZXNlcnZhdGlvbklkcQB-AAN4cgATY29tLmNsb3VkLnZtLlZtV29ya5-ZtlbwJWdrAgAESgAJYWNjb3VudElkSgAGdXNlcklkSgAEdm1JZEwAC2hhbmRsZXJOYW1lcQB-AAN4cAAAAAAAAAACAAAAAAAAAAIAAAAAAAAhUHQAGVZpcnR1YWxNYWNoaW5lTWFuYWdlckltcGwAAAAAAAAAAHBwcHBwcHBwc3IAEWphdmEudXRpbC5IYXNoTWFwBQfawcMWYNEDAAJGAApsb2FkRmFjdG9ySQAJdGhyZXNob2xkeHA_QAAAAAAADHcIAAAAEAAAAAF0AA5SZXN0YXJ0TmV0d29ya3QAP3JPMEFCWE55QUJGcVlYWmhMbXhoYm1jdVFtOXZiR1ZoYnMwZ2NvRFZuUHJ1QWdBQldnQUZkbUZzZFdWNGNBRXhw, cmdVersion: 0, status: IN_PROGRESS, processStatus: 0, resultCode: 0, result: null, initMsid: 345051565299, completeMsid: null, lastUpdated: null, lastPolled: null, created: Mon Mar 06 12:18:05 PST 2017}, job origin:8521
com.cloud.exception.InsufficientServerCapacityException: Unable to create a deployment for VM[DomainRouter|r-8528-VM]Scope=interface com.cloud.dc.DataCenter; id=1
        at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStart(VirtualMachineManagerImpl.java:961)
        at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStart(VirtualMachineManagerImpl.java:4643)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.cloud.vm.VmWorkJobHandlerProxy.handleVmWorkJob(VmWorkJobHandlerProxy.java:107)
        at com.cloud.vm.VirtualMachineManagerImpl.handleVmWorkJob(VirtualMachineManagerImpl.java:4804)
        at com.cloud.vm.VmWorkJobDispatcher.runJob(VmWorkJobDispatcher.java:102)
        at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.runInContext(AsyncJobManagerImpl.java:554)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
        at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.run(AsyncJobManagerImpl.java:502)
````
Also, on vSphere we got this error: `Configuration vmConfig is not valid for cluster CLD100`.

@sureshanaparti maybe this link could be useful to solve the issue: https://communities.vmware.com/thread/467685?start=0&tstart=0

**Comment by sureshanaparti** [comment]
@nvazquez @serg38  I tested this fix on VMware vSphere 5.5 and 6.0. I'll re-verify this on 6.0. Can you please share the build# of ESXi 6.

**Comment by nvazquez** [comment]
@sureshanaparti sure, we use version 6.0.0, build 3634794

**Comment by rhtyd** [comment]
I can fire something on vmware6.0 
@sureshanaparti can you retarget this PR to 4.9 if this is a useful bugfix as 4.9 also support vmware 6.
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-60u2

**Comment by sureshanaparti** [comment]
@rhtyd thanks for running tests. The intermittent failures reported above are not related to this PR. These tests are also failing most of the time in other PRs as well.

**Comment by sureshanaparti** [comment]
@nvazquez Thanks for testing the changes. Tested these changes in ESXi 6.0.0, Build 3620759 on vCenter 60U2. I had already looked at the link you provided while fixing this. I observed the same error on vSphere while testing the changes and fixed this. This is because the VR instance already exists in the vCenter. Below code fixes that issue:

`clusterDasVmConfigSpec.setOperation(vmAlreadyExists ? ArrayUpdateOperation.EDIT : ArrayUpdateOperation.ADD); `

**Comment by sureshanaparti** [comment]
@nvazquez can you please re-verify?

**Comment by sureshanaparti** [comment]
@rhtyd Retargeted this PR to 4.9. Please re-run the tests.

**Comment by nvazquez** [comment]
@sureshanaparti I pulled the latest code and repeated the first test scenario, got the same failure: `Message: The setting of vmConfig is invalid for cluster CLD100.`. I attach the full [management server logs](https://github.com/apache/cloudstack/files/842198/startVR-HA-on.zip)

**Comment by sureshanaparti** [comment]
@nvazquez Thanks for testing. I'll check and update accordingly.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@nvazquez Updated the code for the issue reported. Can you please re-test?

**Comment by sureshanaparti** [comment]
@rhtyd Please kick off VMware tests on this PR.

**Comment by rhtyd** [comment]
@sureshanaparti sure
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-55u3

**Comment by nvazquez** [comment]
Thanks @sureshanaparti! I tested scenarios and work as expected! 
I attach some screenshots:

- Test scenario 1: Enable HA after VR created, stop VR, start VR.
vr1

- Test scenario 2: HA enabled before VR created. deployed VM
vr2

**Comment by sateesh-chodapuneedi** [comment]
tag:mergeready

**Comment by sureshanaparti** [comment]
@rhtyd This PR has 2 LGTMs, is targeted to 4.9. Can you merge this PR to 4.9 or Shall I change the base branch to master?

**Comment by rhtyd** [comment]
Thanks @sureshanaparti, since @karuturi is the RM I've avoided merging any PRs. @karuturi if you're busy and need a co-pilot I can help review and merge some outstanding PRs that have enough LGTMs and regression test results.

**Comment by sureshanaparti** [comment]
@karuturi Can you merge this PR. Current base branch is 4.9. Is that OK or Shall I change to master?

**Comment by karuturi** [comment]
@rhtyd at this stage, I am not looking at more PRs/features for 4.10. I need help on fixing the blockers for releasing 4.10

**Comment by rhtyd** [comment]
@karuturi thanks I'll see how I can help. This PR though looks like a bug to me, though not a blocker.

**Pull request merged**
