### PR TITLE
Update en.json

### PR DESCRIPTION
**Pull request by NuxRo**
Replace "Control Plane" with "Compute Resource"

### Description

A simple replacement so it makes sense to people, sorry but "**Control Plane Status**" is not very meaningful and took a while to figure out what it meant.

We should just say agent or vcenter.. I used "**Compute Resource**" instead, hopefully that's general enough and meaningful.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]

**Review by rohityadavcloud — APPROVED** [review]
Should it be host state/status?

**Review by rohityadavcloud — APPROVED** [review]
Should it be host state/status?

**Comment by DaanHoogland** [comment]
> Should it be host state/status?

@NuxRo ?

**Review by sureshanaparti — APPROVED** [review]
lgtm

**Comment by sureshanaparti** [comment]
@blueorangutan ui

**Comment by NuxRo** [comment]
> > Should it be host state/status?
> 
> @NuxRo ?

Well, we could go a step further and call it "hypervisor", but it could also be a vcenter if it's vmware, so.. don't know. I'm all for making things as clear as possible. Happy to accept alternatives.

**Pull request merged**
