### PR TITLE
Enhance gulp autoprefixer task

### PR DESCRIPTION
**Pull request by webermaximilian92**
## Description

- these changes remove css-prefixes that have no relevance for todays browsers anymore
- last css changes from other PR-merges were moved into scss-files to prevent them from being deleted accidently 
- newest version of autoprefixer for gulp got a new recommendation for browserlist-usage, thus I moved the browserlist into package.json file and sync the new package-lock.json file

Glossary:
"css-prefixes": Fallback or beta css-rules for browsers, when new css rules are introduced
"autoprefixer": Tool that adds css-prefixes automatically
"gulp": Task script manager
"package.json": File that includes information about node packages that are required for e.g. gulp.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

## Screenshots (if appropriate):
not optical changes at all

## How Has This Been Tested?
By checking the view correct changes inside cloudstack.css

### CODE REVIEW

**Comment by rhtyd** [comment]
@webermaximilian92 cc @svenvogel - there have been several css/UI related PRs proposed recently, can you start a discussion thread on dev@ to explain what are the goals and refactorings you're trying to do. I'm personally not sure where the UI changes are heading and would like to learn more.

Typically any framework/component related changes and refactorings may have a design document to capture this that is shared with the dev community for review and discussion. Any proposals and discussions are welcome on dev@. Thanks.

**Comment by webermaximilian92** [comment]
@rhtyd 
I prepared a thread which may help developers to understand what our goals for refactoring and UI are. You can find it here: 
https://lists.apache.org/list.html?dev@cloudstack.apache.org
Thank you too

**Comment by rhtyd** [comment]
Thanks @webermaximilian92 I'll try to follow

**Comment by rhtyd** [comment]
@webermaximilian92 @svenvogel  - do you think we can close this now that we have Primate?

**Comment by rhtyd** [comment]
@webermaximilian92  @svenvogel - with primate in, kindly close this. Let's move all major UI development work in Primate. Thanks.

**Comment by svenvogel** [comment]
@rhtyd closed in favor of cloudstack primate development https://github.com/apache/cloudstack-primate/

**Pull request closed without merging**
