### PR TITLE
CLOUDSTACK-10340: Add setter to hypervisorType in VMInstanceVO

### PR DESCRIPTION
**Pull request by rhtyd**
## Description

This adds a missing setter to set hypervisorType in VMInstanceVO. The consumer is a 3rd party network plugin that may require the method for integration.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.

@blueorangutan package

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by ustcweizhou** [comment]
LGTM

**Comment by nitin-maharana** [comment]
LGTM

**Comment by rhtyd** [comment]
Thanks all, merging this based on code reviews and test results (the failures were not caused by this PR, but were intermitted/env caused).

**Pull request merged**
