### PR TITLE
Reducing expunge delay and interval on default dev cfgs

### PR DESCRIPTION
**Pull request by pdube**
Significantly reduces the time it takes to execute the integration tests

### CODE REVIEW

**Comment by remibergsma** [comment]
@pdube Nice one, will give it a try!

**Comment by remibergsma** [comment]
@pdube Had a look and you may also want to tweak these settings:

# Network garbage collection
network.gc.wait
network.gc.interval

# Storage/Account cleanups
storage.cleanup.interval
account.cleanup.interval

Furthermore I'd set default.page.size as the new infra tab in the UI doesn't like 10000 (which is quite large anyway).

Going to test these and will let you know. Thanks!

**Comment by pdube** [comment]
I will check it out!

**Comment by remibergsma** [comment]
FYI: @pdube I set all timers to 5 sec but that didn't result in a faster integration test run for me.

**Comment by DaanHoogland** [comment]
@pdube @remibergsma and i have been noticing extra failures in the integration tests with such short expunge timeouts. maybe it should work and can with some extra work but like this I don't like :(

**Comment by pdube** [comment]
@DaanHoogland np, I will close the PR

**Pull request closed without merging**
