### PR TITLE
Refactored Nic.java for readability.

### PR DESCRIPTION
**Pull request by borisroman**
Only changed names and reorganized them! No functional implementation change.

See issue CLOUDSTACK-8736 for ongoing effort to clean up network code.

### CODE REVIEW

**Comment by DaanHoogland** [comment]
80bcfb1 and  af199e7 are not atomic then?

**Comment by borisroman** [comment]
@DaanHoogland You are right. I squashed to commits together so there will not be a non-working commit left.

**Comment by wido** [comment]
LGTM to me

**Comment by karuturi** [comment]
I seeing below errors after applying this patch. Please do a noredist build as mentioned at https://cwiki.apache.org/confluence/display/CLOUDSTACK/How+to+build+CloudStack#HowtobuildCloudStack-BuildingCloudStack

```
[ERROR] /root/source/cloudstack/plugins/hypervisors/vmware/src/com/cloud/hypervisor/guru/VMwareGuru.java:[270,50] error: cannot find symbol
[ERROR]   symbol:   method getDns1()
  location: variable publicNicProfile of type NicProfile
/root/source/cloudstack/plugins/hypervisors/vmware/src/com/cloud/hypervisor/guru/VMwareGuru.java:[271,50] error: cannot find symbol
[ERROR]   symbol:   method getDns2()
  location: variable publicNicProfile of type NicProfile
/root/source/cloudstack/plugins/hypervisors/vmware/src/com/cloud/hypervisor/guru/VMwareGuru.java:[272,40] error: cannot find symbol
[ERROR]   symbol:   method getGateway()
  location: variable publicNicProfile of type NicProfile
/root/source/cloudstack/plugins/hypervisors/vmware/src/com/cloud/hypervisor/guru/VMwareGuru.java:[273,57] error: cannot find symbol
```

**Comment by borisroman** [comment]
@karuturi I see, fixed them in a new commit.

**Comment by karuturi** [comment]
build is successful now. :+1:

**Pull request merged**
