### PR TITLE
[VMware][Deploy-as-is] OVF properties not importing when template is uploaded from local

### PR DESCRIPTION
**Pull request by nvazquez**
### Description

This PR adds the missing template details when combining: OVA template upload from local + Read VM settings from OVA

Fixes: #5808 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?
- Upload a OVA template from local
- Verify the template_deploy_as_is_details table and the VM deployment wizard
- Deploy VM and ensure properties/configurations/etc are set

### CODE REVIEW

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan package

**Review by sureshanaparti — APPROVED** [review]
code LGTM

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test centos7 vmware-67u3 keepEnv

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@blueorangutan test centos-7 vmware-65u3 keepEnv

**Comment by DaanHoogland** [comment]
@blueorangutan test centos7 vmware-67u3 keepEnv

**Review by borisstoyanov — APPROVED** [review]
LGTM, manually uploaded a template and the properties were imported

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by sureshanaparti** [comment]
@blueorangutan test centos7 vmware-67u3

**Pull request merged**
