### PR TITLE
Removing an old, unused NetApp plug-in

### PR DESCRIPTION
**Pull request by mike-tutkowski**
## Description
NetApp doesn't support this old plug-in anymore nor do we believe anyone is actually still using it. Removing this plug-in will also remove a CloudStack non-OSS dependency on the manageontap.jar file.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

## Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
Testing
- [ ] I have added tests to cover my changes.
- [ ] All relevant new and existing integration tests have passed.
- [ ] A full integration testsuite with all test that can run on my environment has passed.

### CODE REVIEW

**Comment by mike-tutkowski** [comment]
A couple questions for reviewers:

* Is it OK that I removed the cloudvoladm file? I see this file was removed in the past and then put back. It seems specific to this plug-in, so I removed it.

* Is it OK that I updated the .sql files and the Upgrade2213to2214.java file?

Thanks!

**Comment by mike-tutkowski** [comment]
Hi Rohit,

I sent a message to dev@, but not to users@.

I’ll go ahead and forward it to users@ now.

Thanks,
Mike

On May 24, 2018, at 1:28 AM, Rohit Yadav <notifications@github.com<mailto:notifications@github.com>> wrote:


@rhtyd approved this pull request.

LGTM.
Mike, I'm okay to remove any tables from other sql files including removal of tables in recent upgrade paths if those are not used at all like the following:

DROP TABLE IF EXISTS `cloud`.`netapp_volume`;
DROP TABLE IF EXISTS `cloud`.`netapp_pool`;
DROP TABLE IF EXISTS `cloud`.`netapp_lun`;


Can you start a conversation on both dev and user MLs, to see if any users are using this that can potentially block removal of this feature/plugin.

**Comment by DaanHoogland** [comment]
@mike-tutkowski I hope these failures do not signify the state of master at this moment. You can ignore hostha, privategateway and CA, but the rest I'm not sure

**Comment by mike-tutkowski** [comment]
I reviewed the test failures and none appears to be applicable to this PR.

Since this PR seems pretty low risk with respect to its likelihood to generate tests failures, I'm going to go ahead and merge it.

**Pull request merged**
