### PR TITLE
ui: fix infocard template, iso fields

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes info card by showing both ISO and template where needed.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

Before:
Screenshot from 2023-05-12 17-49-06

After:
Screenshot from 2023-05-12 17-48-20
Screenshot from 2023-05-12 17-48-06

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan ui

**Review by weizhouapache — APPROVED** [review]
code lgtm
I will verify it

**Review by weizhouapache — APPROVED** [review]
code lgtm
I will verify it

**Review by rohityadavcloud — APPROVED** [review]

**Comment by weizhouapache** [comment]
Verified OK

**Pull request merged**
