### PR TITLE
ui: show zones and offerings to users

### PR DESCRIPTION
**Pull request by rohityadavcloud**
Show common information such as zone and offerings to users for their use with Terraform, CAPC etc. without having to use cmk for getting the IDs.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by rohityadavcloud** [comment]
@blueorangutan ui

**Comment by rohityadavcloud** [comment]
Tested with users on QA/UI server: admin, user and domainadmin (under Test domain) all with password `password`

**Review by weizhouapache — APPROVED** [review]
verified oK.

**Review by DaanHoogland — APPROVED** [review]
clgtm and qa env looks good as well

**Comment by rohityadavcloud** [comment]
@blueorangutan ui

**Comment by DaanHoogland** [comment]
tested in qa again:
as regular user I see
image
image

**Pull request merged**
