### PR TITLE
Update proper destroy status when SSVM is destroyed.

### LINKED ISSUE #5895: Destroying SSVM reported to have failed, while it actually succeeded
while destroying a system VM (ssvm in this case) it is reported to have failed, while it actually succeeded,

image

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

### PR DESCRIPTION
**Pull request by sureshanaparti**
### Description

This PR fixes reporting of the destroy status when SSVM is destroyed.

Issue due to changes here:

https://github.com/apache/cloudstack/commit/1aef5cba666510a23f50bd24c4233fc5dd1d35d2#diff-d8fdd320d08cc4eff5dfe391d01c910c660e08ced5afcb2915c78da35f23c453R988-R996

Fixes #5895 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Review by weizhouapache — APPROVED** [review]
lgtm 
make sense

**Review by DaanHoogland — APPROVED** [review]
clgtm. So we basically failed to delete what was no longer there in the first place? strange.

**Review by shwstppr — APPROVED** [review]

**Comment by DaanHoogland** [comment]
> > clgtm. So we basically failed to delete what was no longer there in the first place? strange.
> 
> that is addressed as the fix there, but it should also return true when host entry doesn't exists.

yes, of course. fix is good afaics

**Comment by DaanHoogland** [comment]
@blueorangutan test keepEnv

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Review by GutoVeronezi — APPROVED** [review]

**Comment by DaanHoogland** [comment]
works as expected : 
image

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Pull request merged**
