### PR TITLE
CLOUDSTACK-10105: Maven standard

### PR DESCRIPTION
**Pull request by marcaurele**
Remove maven standard module (which only a few were using) and get ride of maven customization for the projects structure.

- [x] moved all directories to `src/main/java`, `src/main/resources`, `src/main/scripts`, `src/test/java`, `src/test/resources`
- [x] grep scan to search for `src/com` and `src/org` left over
- [x] grep for `<project>/scripts` to fix `pom.xml` configuration
- [x] remove custom `<build>` configuration in `pom.xml`

### CODE REVIEW

**Comment by rafaelweingartner** [comment]
@marcaurele it is not that I am against moving towards standards (I am actually in favor of it), but won't this break the history of the affected files (the files you are moving around)?

I am commenting this so we can discuss the impact that a change like this once can cause, and then check if we are in favor of such thing.

**Comment by marcaurele** [comment]
@rafaelweingartner True 😞 I forgot about this point... I have to find a solution to that

**Comment by marcaurele** [comment]
@rafaelweingartner Better news, it's actually only github that is not able to track the file history correctly. If I use the git history in Intellij I don't loose any commits. If I run in the new file directory a `git log --follow <my_file>` I can see the full history of that file too. The blame function on a file on Github does show each referring commit per line.
The only lost history is the "History" button on github website, which isn't nice I agree since I'm using it quite often. I'm surprised they don't use `--follow` to display the full history. Maybe there's a magic query parameter to get that.
You can try out by checking this PR branch.

**Comment by rafaelweingartner** [comment]
@marcaurele Ah, if that is the case, we do not have many problems (besides  the conflicts will are probably getting constantly)

Have you tried to contact someone from Github to ask about this behavior?

**Comment by marcaurele** [comment]
I did (to bump the number of requests on that feature) see https://stackoverflow.com/a/21508105

**Comment by marcaurele** [comment]
For the conflicts, the only thing I need to do is a final `git rebase --onto master` before merging. The only conflicts/errors left for the future PRs are the one creating new files in the old directory structure.

**Comment by rafaelweingartner** [comment]
@marcaurele I think it is  good idea to squash into a single commit before merging (if we move this PR forward)

**Comment by marcaurele** [comment]
@rafaelweingartner sure, I was going to squash them all. It's just for me to knew where I was in the "moving process". When the PR is ready, I'll squash them, and maintain the rebase until the merge.

**Comment by rafaelweingartner** [comment]
Awesome!
Thanks for the hard work

**Comment by marcaurele** [comment]
@rhtyd @rafaelweingartner @wido this PR to move all projects structure to maven standard is passing all the tests. I'm ready to fix the conflict with the new merges (very easy). I simply want to ensure that you're also ready to merge the PR when conflicts are resolved.

As said in the previous comment, we *don't loose* the commit history, only github does not display them correctly because they don't use the `--follow` option. See https://github.com/apache/cloudstack/pull/2283#issuecomment-334358004 and https://github.com/apache/cloudstack/pull/2283#issuecomment-334445336

**Comment by rafaelweingartner** [comment]
@marcaurele from me you have an LGTM

**Comment by rhtyd** [comment]
It will be difficult to accept this at this point with more than 150 PRs pending review/merge, as this will potentially cause merge conflicts on all of them. Accepting this will also fail cherry-picking and doing branch maintenance. @marcaurele pardon my ignorance, except for cosmetics changes in file-systems/directories/paths what are the pros of such refactoring? My understanding is our file structure does not follow the `maven-standard`, (given our `ant` build-system history) however it's has not created a problem for developers or users.

**Comment by marcaurele** [comment]
@rhtyd My goal was to align all projects, all poms to follow one standard, a cleanup process thing. Currently there are 3 types of project: the ones using the old structure, the ones using the new, and some redefining their `<build>` section (most of the time with unnecessary changes). Of course the build works, otherwise we would be in trouble. But I feel the project deserves more cleanup and standardization on how things are done. Then the usual copy/paste of code & configuration will be aligned too when creating new modules. Also the `pom` files will be simpler with less customization at different places within the sub-module tree.

I agree that the cherry-picking could be cumbersome, if lot of them should happen. It makes me think that it should be merge (if agreed) as the first commit for the next LTS version. This will lower the cherry-pick frictions on backporting fixes. I'm up for handling the effort to backport commits colliding with this one.

On the 150+ PR waiting to be merged, I don't see that number really getting to a low value any time soon since the build and check process is pretty long. The rebasing of any of them is trivial, the only exception to newly created file, which would show up as an error pretty quickly since they should be used directly by the PR's code.

**Comment by khos2ow** [comment]
@marcaurele @rhtyd Hi. Is there any update/ETA on this PR? The reason is I created another PR (#2343) which is somehow has the same nature and it's still WIP.

**Comment by rafaelweingartner** [comment]
@rhtyd, @marcaurele, and @khos2ow I have been thinking about this PR and #2343, which focus on changing ACS code base to use current standard technologies and development patterns.  I do believe they are needed; by adopting standards we lower the bar to newcomers. It has been a great effort of @marcaurele so far, and we need this kind of work and ideas in the community.

**Comment by marcaurele** [comment]
Rebased to fix all conflicts, and ready for 4.12.0

**Comment by rafaelweingartner** [comment]
@marcaurele I believe it might be a good idea to ask others to look into this one before we start merging again...

**Comment by marcaurele** [comment]
@wido @PaulAngus @rhtyd @swill @rafaelweingartner @DaanHoogland can we have your voice over this change to move all project to follow maven standards.

**Comment by wido** [comment]
I would be OK with this as it's indeed a better structure. It might however kill a lot of PRs, but if we want to do this, NOW is the time imho.

**Comment by rafaelweingartner** [comment]
me too...

**Comment by khos2ow** [comment]
Strong +1 from me.

**Comment by DaanHoogland** [comment]
gogogo

**Comment by rafaelweingartner** [comment]
@marcaurele please do the honors and merge this one....

P.S. you are going to generate conflicts in my PRs :(

**Comment by rhtyd** [comment]
Hold on, we need to run tests across xenserver, vmware and kvm before this may be accepted.

**Comment by marcaurele** [comment]
@rafaelweingartner thanks, i will as soon as @rhtyd give me a go

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@marcaurele do we need `marven-standard` now, can we remove that as well?

**Comment by marcaurele** [comment]
@rhtyd it's removed in this PR

**Comment by rhtyd** [comment]
@marcaurele can you fix packaging for CentOS6 and 7.
CentOS6 packaging fails due to:
+ cp -r 'plugins/network-elements/cisco-vnmc/scripts/network/cisco/*' /jenkins/workspace/acs-pr-centos6-pkg-builder/dist/rpmbuild/BUILDROOT/cloudstack-4.12.0.0-shapeblue1671.el6.x86_64/usr/share/cloudstack-common/scripts/network/cisco
cp: cannot stat `plugins/network-elements/cisco-vnmc/scripts/network/cisco/*': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.lS7NDO (%install)


CentOS7 fails due to:
+ cp -r 'plugins/network-elements/cisco-vnmc/scripts/network/cisco/*' /jenkins/workspace/acs-pr-centos7-pkg-builder/dist/rpmbuild/BUILDROOT/cloudstack-4.12.0.0-shapeblue1674.el7.centos.x86_64/usr/share/cloudstack-common/scripts/network/cisco
cp: cannot stat 'plugins/network-elements/cisco-vnmc/scripts/network/cisco/*': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.mUH4PE (%install)

For your local testing, you can use following docker images:
https://hub.docker.com/r/bhaisaab/centos7-cloudstack-slave/
https://hub.docker.com/r/bhaisaab/centos6-cloudstack-slave/

**Comment by marcaurele** [comment]
@rhtyd ack, I will - thanks for the link to the docker images

**Comment by wido** [comment]
If tests pass LGTM from me. Should be done as early as possible now we are heading for 4.12 in master

**Comment by marcaurele** [comment]
@rhtyd the centos packages have been fixed. Is there a guide on how to use a cs docker image to validate a development, which goes down to building the package and installing it inside the container?

**Comment by rhtyd** [comment]
@marcaurele you can kick packages with bo:
@blueorangutan package

**Comment by marcaurele** [comment]
@rhtyd I thought it was restricted to some users only. Good to know

**Comment by rhtyd** [comment]
@marcaurele running a trillian test is restricted, packing is available to everyone.

**Comment by rhtyd** [comment]
@marcaurele I'll update packaging docs with the docker images soon, the idea is you run the container, git clone your repo, switch to your branch and run the package build script in packaging directory.

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by marcaurele** [comment]
Tests are ok, merging

**Comment by rhtyd** [comment]
Vmware test lgtm, @marcaurele please wait for kvm and xenserver tests, which should succeed too, then you can squash merge your changes.

**Comment by marcaurele** [comment]
A reminder, the history on Github of some files will look like gone. You have to use your local git to "follow" the files move, see https://github.com/apache/cloudstack/pull/2283#issuecomment-334358004

**Comment by rafaelweingartner** [comment]
@marcaurele any plan to execute this merge?

**Comment by rhtyd** [comment]
@rafaelweingartner I think you missed my comment, for changes like this we shouldn't be merging them without test results. We only have test result for vmware, awaiting results for xenserver and kvm.
@marcaurele can you fix the conflict?

**Comment by rafaelweingartner** [comment]
I saw it. My question was actually "considering that the tests finished successfully", will this be merged today? Or maybe we have something else to do or check before proceeding to merge.

**Comment by rhtyd** [comment]
@rafaelweingartner I pretty sure it's different than what was actually asked :)
I'll leave the squash merging to @marcaurele after xenserver test (kvm tests LGTM) are back later today (hopefully few hours) and he can fix a merge conflict in `plugins/hypervisors/kvm/src/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
Squash and merge `

**Comment by marcaurele** [comment]
@rhtyd rebase done, conflict gone

**Comment by rhtyd** [comment]
Tests LGTM, the scale related error is caused due to license issue for xenserver tests. Merging this based on code reviews and test results.

**Comment by rhtyd** [comment]
@marcaurele with accepting of your PR, can you notify dev@ about your work, request people to rebase their branches and what/how PR authors should fix conflicts, and your suggestion about using `--folow` etc?

**Comment by rafaelweingartner** [comment]
@rhtyd what are these "merge 4.11" that are appearing in our commit history?

**Comment by rhtyd** [comment]
@rafaelweingartner those are forward merges from 4.11 branch -- we've had three merges on 4.11 since rc1, we want to get them to master branch. Refer for details - https://cwiki.apache.org/confluence/display/CLOUDSTACK/Release+principles+for+Apache+CloudStack+4.6+and+up

**Comment by rafaelweingartner** [comment]
hmm... Are you doing via Github the merge forward?
I was under the impression that our merge forward script would provide a bit of details in the commit regarding the "commit"/"PR" it is merging forward.

**Comment by rhtyd** [comment]
No, forward merges are done manually.

**Comment by rafaelweingartner** [comment]
Normally, whenever merging forward I use `https://github.com/apache/cloudstack/blob/master/tools/git/git-fwd-merge`. This script creates commits like this one: https://github.com/apache/cloudstack/commit/359d20e8d6d11a992755926a0cf1b1f2a5454487

It inserts in the commit body the message of the commits being merged forward. Otherwise, we get commit message that does not say much.

**Pull request merged**
