### PR TITLE
remove duplicate index region

### PR DESCRIPTION
**Pull request by andrijapanicsb**
remove duplicate index region

### CODE REVIEW

**Comment by svenvogel** [comment]
@andrijapanicsb can you explain

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
Checked backend, we've some issues. Based on previous test run and Travis LGTM. Essentially this is a simple DB related fix, validated through Travis.

**Pull request merged**
