### PR TITLE
packaging: move juniper-contrail network plugin to noredist build

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR moves juniper-contrail to noredist and removes the repository for it.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by sureshanaparti — APPROVED** [review]
lgtm

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Review by DaanHoogland — APPROVED** [review]

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Comment by weizhouapache** [comment]
are we ok to merge this ? I can rebase with 4.19 or 4.20

@DaanHoogland @rohityadavcloud @sureshanaparti

**Pull request merged**
