### PR TITLE
Add NULL checks for various objects in SolidFire integration test API

### PR DESCRIPTION
**Pull request by syed**
Guard from cases where we pass an invalid `accountID` or `storagePoolID` in the API.

CC: @mike-tutkowski

### CODE REVIEW

**Comment by GabrielBrascher** [comment]
Code LGTM. Thanks @syed !

**Comment by syed** [comment]
Thanks for the quick review @GabrielBrascher

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
LGTM, the changes are strictly in solidfire codebase. GIven Travis passed, additional Trillian run are not needed.

**Pull request merged**
