### PR TITLE
Packaging: new timestamp format and add output dir option

### PR DESCRIPTION
**Pull request by ustcweizhou**
### Description

This PR add an option "-o" to specify the output directory of packages.

Usage:
    cd packaging && ./build-deb.sh -T -o ~/packages/$BRANCH_NAME

This PR also changes the format of timestamp when create packages using "./build-deb.sh -T"

old output
```
# ls -l *16052*
-rw-r--r-- 1 jenkins jenkins     12509 Nov 12 22:31 cloudstack_4.14.1.0-1605219288~bionic_amd64.buildinfo
-rw-r--r-- 1 jenkins jenkins      3714 Nov 12 22:31 cloudstack_4.14.1.0-1605219288~bionic_amd64.changes
-rw-r--r-- 1 jenkins jenkins  62306764 Nov 12 22:30 cloudstack-agent_4.14.1.0-1605219288~bionic_all.deb
-rw-r--r-- 1 jenkins jenkins  61913896 Nov 12 22:30 cloudstack-common_4.14.1.0-1605219288~bionic_all.deb
-rw-r--r-- 1 jenkins jenkins     52964 Nov 12 22:30 cloudstack-docs_4.14.1.0-1605219288~bionic_all.deb
-rw-r--r-- 1 jenkins jenkins    651156 Nov 12 22:30 cloudstack-integration-tests_4.14.1.0-1605219288~bionic_all.deb
-rw-r--r-- 1 jenkins jenkins 107535424 Nov 12 22:31 cloudstack-management_4.14.1.0-1605219288~bionic_all.deb
-rw-r--r-- 1 jenkins jenkins    508912 Nov 12 22:30 cloudstack-marvin_4.14.1.0-1605219288~bionic_all.deb
-rw-r--r-- 1 jenkins jenkins  48869360 Nov 12 22:31 cloudstack-usage_4.14.1.0-1605219288~bionic_all.deb
```

new output
```
# ls -l 
total 277092
-rw-rw-r-- 1 jenkins jenkins     12619 Nov 12 09:25 cloudstack_4.14.1.0-20201112T085715~bionic_amd64.buildinfo
-rw-rw-r-- 1 jenkins jenkins      3849 Nov 12 09:25 cloudstack_4.14.1.0-20201112T085715~bionic_amd64.changes
-rw-r--r-- 1 jenkins jenkins  62132640 Nov 12 09:24 cloudstack-agent_4.14.1.0-20201112T085715~bionic_all.deb
-rw-r--r-- 1 jenkins jenkins  62454532 Nov 12 09:24 cloudstack-common_4.14.1.0-20201112T085715~bionic_all.deb
-rw-r--r-- 1 jenkins jenkins     52964 Nov 12 09:24 cloudstack-docs_4.14.1.0-20201112T085715~bionic_all.deb
-rw-r--r-- 1 jenkins jenkins    662468 Nov 12 09:24 cloudstack-integration-tests_4.14.1.0-20201112T085715~bionic_all.deb
-rw-r--r-- 1 jenkins jenkins 107355880 Nov 12 09:25 cloudstack-management_4.14.1.0-20201112T085715~bionic_all.deb
-rw-r--r-- 1 jenkins jenkins    512556 Nov 12 09:24 cloudstack-marvin_4.14.1.0-20201112T085715~bionic_all.deb
-rw-r--r-- 1 jenkins jenkins  50534436 Nov 12 09:25 cloudstack-usage_4.14.1.0-20201112T085715~bionic_all.deb
```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
looks good. pudding needed

**Review by davidjumani — APPROVED** [review]
LGTM. Packages created with the new timestamp and moved to the output directory
However it would be nice to echo that the packages can be found in $OUTPUT_DIR since in the logs it mentions that the packages are being built in the current directory
```
dpkg-deb: building package 'cloudstack-common' in '../cloudstack-common_4.15.0.0-SNAPSHOT~eoan~eoan~eoan_all.deb'.
dpkg-deb: building package 'cloudstack-docs' in '../cloudstack-docs_4.15.0.0-SNAPSHOT~eoan~eoan~eoan_all.deb'.
dpkg-deb: building package 'cloudstack-integration-tests' in '../cloudstack-integration-tests_4.15.0.0-SNAPSHOT~eoan~eoan~eoan_all.deb'.
dpkg-deb: building package 'cloudstack-marvin' in '../cloudstack-marvin_4.15.0.0-SNAPSHOT~eoan~eoan~eoan_all.deb'.
dpkg-deb: building package 'cloudstack-usage' in '../cloudstack-usage_4.15.0.0-SNAPSHOT~eoan~eoan~eoan_all.deb'.
dpkg-deb: building package 'cloudstack-agent' in '../cloudstack-agent_4.15.0.0-SNAPSHOT~eoan~eoan~eoan_all.deb'.
dpkg-deb: building package 'cloudstack-management' in '../cloudstack-management_4.15.0.0-SNAPSHOT~eoan~eoan~eoan_all.deb'.

```

**Comment by weizhouapache** [comment]
> LGTM. Packages created with the new timestamp and moved to the output directory
> However it would be nice to echo that the packages can be found in $OUTPUT_DIR since in the logs it mentions that the packages are being built in the current directory
> 
> ```
> dpkg-deb: building package 'cloudstack-common' in '../cloudstack-common_4.15.0.0-SNAPSHOT~eoan~eoan~eoan_all.deb'.
> dpkg-deb: building package 'cloudstack-docs' in '../cloudstack-docs_4.15.0.0-SNAPSHOT~eoan~eoan~eoan_all.deb'.
> dpkg-deb: building package 'cloudstack-integration-tests' in '../cloudstack-integration-tests_4.15.0.0-SNAPSHOT~eoan~eoan~eoan_all.deb'.
> dpkg-deb: building package 'cloudstack-marvin' in '../cloudstack-marvin_4.15.0.0-SNAPSHOT~eoan~eoan~eoan_all.deb'.
> dpkg-deb: building package 'cloudstack-usage' in '../cloudstack-usage_4.15.0.0-SNAPSHOT~eoan~eoan~eoan_all.deb'.
> dpkg-deb: building package 'cloudstack-agent' in '../cloudstack-agent_4.15.0.0-SNAPSHOT~eoan~eoan~eoan_all.deb'.
> dpkg-deb: building package 'cloudstack-management' in '../cloudstack-management_4.15.0.0-SNAPSHOT~eoan~eoan~eoan_all.deb'.
> ```

@davidjumani good. I will add the message

**Review by davidjumani — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@PaulAngus @rhtyd in spite of not being a bug fix, i think we can take this in before release, do you?

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
Last packaging failed on centos7 due to backend issue re-running
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Pull request merged**
