### PR TITLE
Upgrade to mockito 4 and handle Mockito deprecations

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR upgrades mockito from v3 to v4 and remove deprecated methods.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
hard work @vishesh92 , looks good

**Review by rohityadavcloud — APPROVED** [review]
LGTM but needs testing/further review

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@vishesh92 , i think we have a package dependency error

**Comment by DaanHoogland** [comment]
> @vishesh92 , i think we have a package dependency error

in utils

**Comment by vishesh92** [comment]
@DaanHoogland It's because of some new tests which used the deprecated runners module. Let me fix this.

**Comment by vishesh92** [comment]
@DaanHoogland Tests passed after fixing the import.

**Pull request merged**
