### PR TITLE
Go back to previous timestamp on logging

### PR DESCRIPTION
**Pull request by JoaoJandre**
### Description

Before #7131, the logs' timestamp was in the `2024-04-02 22:04:28,617`, with the upgrade to log4j2, the logs' timestamp was changed to the `2024-04-02T21:55:12,724` format. This PR changes the timestamp back to the previous format.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by JoaoJandre** [comment]
The PR is ready for review, I just need to test it manually on all components.

**Comment by JoaoJandre** [comment]
> Is this really needed @JoaoJandre ? seems to me this is a user choice and taking a standard as the default is not that bad a choice. (did you get complaints?)

This will revert the default timestamp to what it used to be before the Log4j2 update, I mistakenly changed the default timestamp when upgrading the default log4j configurations on #7131. This PR will change the timestamp to the one that was being used before #7131.

The change on the timestamp pattern could break users' log parsers, that's why I created this PR. If they wish, they can change the value to ISO8601 or whatever they prefer.

**Review by DaanHoogland — APPROVED** [review]

**Review by FelipeM525 — APPROVED** [review]
CLGTM!

**Comment by JoaoJandre** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan LLtest

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Pull request merged**
