### PR TITLE
utils: build both SHADED and original jars

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR builds two jars for utils project
- `cloud-utils-4.19.0.0-SNAPSHOT.jar` : will be built into `cloudstack-4.19.0.0-SNAPSHOT.jar` (installed on management server) and `systemvm/target/agent.zip` (copied into system vms).
- `cloud-utils-4.19.0.0-SNAPSHOT-SHADED.jar` , will be installed as `/usr/share/cloudstack-common/lib/cloudstack-utils.jar`

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@blueorangutan test ubuntu22 kvm-ubuntu22

**Comment by rohityadavcloud** [comment]
Hi @weizhouapache thanks for the PR - can you explain, the advantage of this, for systemvms aren't we copying all dependency jars?

**Comment by DaanHoogland** [comment]
can you explain why @weizhouapache ? It seems the jars are the same and only one needs to be built.

**Comment by weizhouapache** [comment]
@rohityadavcloud @DaanHoogland 

- Without this PR (main)

During build, it creates `cloud-utils-4.19.0.0-SNAPSHOT.jar` which contains some dependencies, see below

https://github.com/apache/cloudstack/blob/3b05797344c15a9fbd6bee4ecd38281b677f24a2/utils/pom.xml#L267-L273

The jar will be installed as `/usr/share/cloudstack-common/lib/cloudstack-utils.jar` so we can use it to encrypt/decrypt values, for example,
```
# java -classpath /usr/share/cloudstack-common/lib/cloudstack-utils.jar com.cloud.utils.crypt.EncryptionCLI -p password -i testinput -v
Input: testinput
Encrypted: 0SrcIiIutYYQ43s4pc9e93MUCXELM0T7uHj4UFB5sfD+IhW9rQ==

# java -classpath /usr/share/cloudstack-common/lib/cloudstack-utils.jar com.cloud.utils.crypt.EncryptionCLI -p password -i 0SrcIiIutYYQ43s4pc9e93MUCXELM0T7uHj4UFB5sfD+IhW9rQ== -d -v
Input: 0SrcIiIutYYQ43s4pc9e93MUCXELM0T7uHj4UFB5sfD+IhW9rQ==
Encrypted: testinput
```

This jar file will be copied to system vms  (as /usr/local/cloud/systemvm/cloud-utils-4.19.0.0-SNAPSHOT.jar). 

There are two issues
- The dependencies are also included in cloud-client-ui-4.19.0.0-SNAPSHOT.jar and deployed to management server (as part of /usr/share/cloudstack-management/lib/cloudstack-4.19.0.0-SNAPSHOT.jar). so it is not needed to built into cloudstack-4.19.0.0-SNAPSHOT.jar twice.
- In the testing of PR #7131, it causes that system vms do not have any logs (see discussions after https://github.com/apache/cloudstack/pull/7131#issuecomment-1692211705) , which because log4j jars exists in the directory /usr/local/cloud/systemvm/ and is also built into cloud-utils-4.19.0.0-SNAPSHOT.jar

- With this PR

During build, there are two jars
(1) cloud-utils-4.19.0.0-SNAPSHOT.jar : will be built into cloudstack-4.19.0.0-SNAPSHOT.jar (installed on management server) and systemvm/target/agent.zip (copied into system vms). This does not have any dependencies. The system vm log issue with #7131 can be solved.
(2) cloud-utils-4.19.0.0-SNAPSHOT-SHADED.jar , will be installed as /usr/share/cloudstack-common/lib/cloudstack-utils.jar. This package has some dependencies and can be used separately (no need to include log4j jars in the path)

**Comment by DaanHoogland** [comment]
ok so this depends on #7131  to make any sense, but it removes the need of a new command line for the encryption tools :+1:

**Review by DaanHoogland — APPROVED** [review]

**Comment by weizhouapache** [comment]
> ok so this depends on #7131 to make any sense, but it removes the need of a new command line for the encryption tools 👍

yes, 
moreover, no need to install `log4j-core` and `log4j-api` in `/usr/share/cloudstack-common/lib/`  cc @JoaoJandre

**Comment by weizhouapache** [comment]
> Hi @weizhouapache thanks for the PR - can you explain, the advantage of this, for systemvms aren't we copying all dependency jars?

@rohityadavcloud 
the jars in system vms are not changed, except cloud-utils.
this avoids some jar dependencies to be loaded twice (1 jar in directory, 1 jar in cloud-utils.jar) during the start of java process in system vms and management servers, which might cause some problems.

**Comment by weizhouapache** [comment]
@blueorangutan test matrix

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan LLpackage

**Comment by weizhouapache** [comment]
@blueorangutan test matrix

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan LLtest matrix

**Comment by DaanHoogland** [comment]
@weizhouapache @JoaoJandre should this be merged with the log4j2 PR? it seems to only be relevant in that context, is it?

**Comment by weizhouapache** [comment]
> @weizhouapache @JoaoJandre should this be merged with the log4j2 PR? it seems to only be relevant in that context, is it?

@DaanHoogland 
this is an independant PR, which can fix the issue with system vms in the log4j PR.

**Comment by DaanHoogland** [comment]
> > @weizhouapache @JoaoJandre should this be merged with the log4j2 PR? it seems to only be relevant in that context, is it?
> 
> @DaanHoogland this is an independant PR, which can fix the issue with system vms in the log4j PR.

yes, and it is only needed if the log4j PR is merged, right?

**Comment by weizhouapache** [comment]
> > > @weizhouapache @JoaoJandre should this be merged with the log4j2 PR? it seems to only be relevant in that context, is it?
> > 
> > 
> > @DaanHoogland this is an independant PR, which can fix the issue with system vms in the log4j PR.
> 
> yes, and it is only needed if the log4j PR is merged, right?

it can reduce the package size of cloudstack packages (~4M for cloudstack-agent/common/usage/management)

image


image

again, this PR is separated. it does not matter if the log4j PR is merged or not.
The trillian tests for log4j PR do not work without this PR, unless trillian is modified.

**Comment by weizhouapache** [comment]
@rohityadavcloud 
does this looks good to you ?

**Review by JoaoJandre — APPROVED** [review]
@weizhouapache I did some basic tests and it LGTM. 
I also tested this with #7131 and it does solve the issue. I added the log4j2 dependencies to the shaded jar and the system VM logs did not break.

**Comment by weizhouapache** [comment]
> @weizhouapache I did some basic tests and it LGTM. I also tested this with #7131 and it does solve the issue. I added the log4j2 dependencies to the shaded jar and the system VM logs did not break.

good, thanks for testing @JoaoJandre

**Pull request merged**
