### PR TITLE
While starting VM with 'considerlasthost' enabled, don't load host tags/details for the last host when it doesn't exist [main]

### PR DESCRIPTION
**Pull request by sureshanaparti**
### Description

This PR doesn't load host tags/details for the last host when it doesn't exist, while starting VM with 'considerlasthost' enabled. It addresses https://github.com/apache/cloudstack/issues/9033, in main

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [x] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by vladimirpetrov** [comment]
I'm having an error when trying to start a VM on an already deleted host with 'Consider last host' enabled, here are the exceptions in the log:
```
2024-06-12T09:06:20,389 ERROR [c.c.v.VmWorkJobDispatcher] (Work-Job-Executor-7:[ctx-d8af49a8, job-42/job-44]) (logid:fd3c0220) Unable to complete AsyncJobVO: {id:44, userId: 2, accountId: 2, instanceType: null, instanceId: null, cmd: com.cloud.vm.VmWorkStart, cmdInfo: rO0ABXNyABhjb20uY2xvdWQudm0uVm1Xb3JrU3RhcnR9cMGsvxz73gIAC0oABGRjSWRMAAZhdm9pZHN0ADBMY29tL2Nsb3VkL2RlcGxveS9EZXBsb3ltZW50UGxhbm5lciRFeGNsdWRlTGlzdDtMAAljbHVzdGVySWR0ABBMamF2YS9sYW5nL0xvbmc7TAAGaG9zdElkcQB-AAJMAAtqb3VybmFsTmFtZXQAEkxqYXZhL2xhbmcvU3RyaW5nO0wAEXBoeXNpY2FsTmV0d29ya0lkcQB-AAJMAAdwbGFubmVycQB-AANMAAVwb2RJZHEAfgACTAAGcG9vbElkcQB-AAJMAAlyYXdQYXJhbXN0AA9MamF2YS91dGlsL01hcDtMAA1yZXNlcnZhdGlvbklkcQB-AAN4cgATY29tLmNsb3VkLnZtLlZtV29ya5-ZtlbwJWdrAgAESgAJYWNjb3VudElkSgAGdXNlcklkSgAEdm1JZEwAC2hhbmRsZXJOYW1lcQB-AAN4cAAAAAAAAAACAAAAAAAAAAIAAAAAAAAAA3QAGVZpcnR1YWxNYWNoaW5lTWFuYWdlckltcGwAAAAAAAAAAHBwcHBwcHBwc3IAEWphdmEudXRpbC5IYXNoTWFwBQfawcMWYNEDAAJGAApsb2FkRmFjdG9ySQAJdGhyZXNob2xkeHA_QAAAAAAADHcIAAAAEAAAAAJ0ABBDb25zaWRlckxhc3RIb3N0dAAPck8wQUJYUUFCSFJ5ZFdVdAAKVm1QYXNzd29yZHQAHHJPMEFCWFFBRG5OaGRtVmtYM0JoYzNOM2IzSmt4cA, cmdVersion: 0, status: IN_PROGRESS, processStatus: 0, resultCode: 0, result: null, initMsid: 32986942669477, completeMsid: null, lastUpdated: null, lastPolled: null, created: Wed Jun 12 09:06:18 UTC 2024, removed: null}, job origin: 42 java.lang.NullPointerException: Cannot invoke "com.cloud.host.Host.getClusterId()" because "lastHost" is null
        at com.cloud.vm.VirtualMachineManagerImpl.checkAndAttemptMigrateVmAcrossCluster(VirtualMachineManagerImpl.java:1080)
        at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStart(VirtualMachineManagerImpl.java:1254)
        at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStart(VirtualMachineManagerImpl.java:5419)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
```
2024-06-12T09:06:20,423 ERROR [c.c.a.ApiAsyncJobDispatcher] (API-Job-Executor-32:[ctx-4f25b3d9, job-42]) (logid:fd3c0220) Unexpected exception while executing org.apache.cloudstack.api.command.admin.vm.St
artVMCmdByAdmin java.lang.NullPointerException
        at com.cloud.vm.VirtualMachineManagerImpl.checkAndAttemptMigrateVmAcrossCluster(VirtualMachineManagerImpl.java:1080)
        at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStart(VirtualMachineManagerImpl.java:1254)
        at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStart(VirtualMachineManagerImpl.java:5419)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Review by vladimirpetrov — APPROVED** [review]
LGTM based on manual testing. Steps to reproduce:
1. Deploy a VM
2. Stop the VM
3. Delete the host the VM used to be running
4. Start the VM again using the 'Consider last host' option enabled.

**Pull request merged**
