### PR TITLE
account check made explicit - cleanup

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR cleans up and restructures the code that checks and applies invites on update.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### How Has This Been Tested?

should be tested by the project smoke tests.

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by nvazquez — APPROVED** [review]
Code LGTM

**Review by rohityadavcloud — APPROVED** [review]
LGTM, can you add unit test (optionally also a marvin test case if it doesn't already exist) for this change?

**Comment by DaanHoogland** [comment]
> LGTM, can you add unit test (optionally also a marvin test case if it doesn't already exist) for this change?

As stated in the description @rohityadavcloud "should be tested by the project smoke tests."

**Review by Pearl1594 — APPROVED** [review]
code LGTM

**Pull request merged**
