### PR TITLE
[TEST] - Test unit - Fix failing UI unit test main branch

### PR DESCRIPTION
**Pull request by utchoang**
### Description

Related #5212

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by weizhouapache** [comment]
@utchoang can you please fix the conflicts ?

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by rhtyd** [comment]
@utchoang please merge latest 'main' branch and address any new failures/conflicts, thanks.

**Comment by utchoang** [comment]
Alternative PR https://github.com/apache/cloudstack/pull/5262

**Pull request closed without merging**
