### PR TITLE
Storage and volumes statistics tasks for StorPool primary storage

### PR DESCRIPTION
**Pull request by slavkap**
### Description

Added tasks for statistics of the StorPool's volumes and primary storage

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

### CODE REVIEW

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@slavkap 
can you fix the conflicts ?

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@slavkap `test_vm_life_cycle.py` are a known issue. Can you check the others?

**Comment by slavkap** [comment]
Hi @DaanHoogland, is it possible to rerun the test? The tests failed because of a timeout.
```

./management-server.log:393287:2023-07-04 14:59:50,949 WARN  [c.c.s.d.DownloadListener] (Timer-36:ctx-e500f9be) (logid:f5842f54) Entering download error state: timeout waiting for response from storage host, TEMPLATE: 277 at host 5
./management-server.log:393655:2023-07-04 15:00:56,420 WARN  [c.c.s.d.DownloadListener] (Timer-37:ctx-2b9ef11f) (logid:5ca2b8eb) Entering download error state: timeout waiting for response from storage host, TEMPLATE: 278 at host 5
./management-server.log:394023:2023-07-04 15:02:01,864 WARN  [c.c.s.d.DownloadListener] (Timer-38:ctx-08f57732) (logid:61d5dc57) Entering download error state: timeout waiting for response from storage host, TEMPLATE: 279 at host 5
./management-server.log:403095:2023-07-04 15:13:19,754 WARN  [c.c.s.d.DownloadListener] (Timer-39:ctx-ad47793a) (logid:71c88bcd) Entering download error state: timeout waiting for response from storage host, TEMPLATE: 284 at host 5
```

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Pull request merged**
