### PR TITLE
default teardown methods with reversed() handling

### PR DESCRIPTION
**Pull request by DaanHoogland**
## Description

In this a small change to improve the marvin framework for resource cleanup and adding examples in the test-implementations.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by DaanHoogland** [comment]
any thoughts @GabrielBrascher @borisstoyanov @rhtyd

**Comment by DaanHoogland** [comment]
also @vladimirpetrov

**Comment by DaanHoogland** [comment]
@blueorangutan test centos7 kvm-centos7 keepEnv

**Comment by DaanHoogland** [comment]
@blueorangutan test centos7 kvm-centos7 keepEnv

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test centos7 kvm-centos7 keepEnv

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@PaulAngus not sure if it was you or a script of yours, but you removed the label bug here. It should be marked that way.

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by GabrielBrascher — APPROVED** [review]
LGTM based on code review.

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@borisstoyanov @vladimirpetrov can you review please?

**Review by borisstoyanov — COMMENTED** [review]
LMGT, based on code and test results

**Pull request merged**
