### PR TITLE
Replaced all occurences of Charset.forName(UTF-8) with StringUtils.getPreferredCharset().

### PR DESCRIPTION
**Pull request by borisroman**

### CODE REVIEW

**Comment by wido** [comment]
Pending travis LGTM

**Comment by borisroman** [comment]
Travis failed due to a time-out.

**Comment by DaanHoogland** [comment]
LGTM, thanks @borisroman

**Comment by wilderrodrigues** [comment]
@borisroman @wido 

Was this PR compiled locally? Master is now broken. When I try to build I get:

BrocadeVcsApi.java:[378,26] error: cannot find symbol

I checked the file and found out the following:

* Previous to @borisroman changes:

import com.cloud.dc.Vlan;
import com.cloud.utils.StringUtils;
import com.cloud.utils.cisco.n1kv.vsm.PortProfile;

* After @borisroman changes:

import com.cloud.network.schema.interfacevlan.InterfaceVlan;
import com.cloud.network.schema.interfacevlan.Interface;
import com.cloud.network.schema.interfacevlan.Vlan;
import com.cloud.network.schema.portprofile.PortProfile;
import com.cloud.network.schema.portprofile.PortProfile.Activate;
import com.cloud.network.schema.portprofile.PortProfile.Static;
import com.cloud.network.schema.portprofile.PortProfileGlobal;
import com.cloud.network.schema.portprofile.VlanProfile;
import com.cloud.network.schema.portprofile.VlanProfile.Switchport;
import com.cloud.network.schema.portprofile.VlanProfile.Switchport.Mode;
import com.cloud.network.schema.portprofile.VlanProfile.Switchport.Trunk;
import com.cloud.network.schema.portprofile.VlanProfile.Switchport.Trunk.Allowed;
import com.cloud.network.schema.portprofile.VlanProfile.SwitchportBasic;
import com.cloud.network.schema.portprofile.VlanProfile.SwitchportBasic.Basic;
import com.cloud.network.schema.showvcs.Output;

Which gives also this error:

PortProfile() is not public in PortProfile; cannot be accessed from outside package.

The imports are all wrong. Could you please fix it?

ping @remibergsma @miguelaferreira @DaanHoogland @karuturi @bhaisaab 

Cheers,
Wilder

**Comment by remibergsma** [comment]
@wilderrodrigues If something breaks master, any committer can revert it in order to restore stability. I didn't verify yet, but feel free to revert and ping the dev-list about it.

**Comment by wilderrodrigues** [comment]
Reverted by commit 6e426fa46d8cda50ec76f33429320d4590701678

**Comment by wilderrodrigues** [comment]
Building is passing again:

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7:52.562s
[INFO] Finished at: Tue Sep 15 15:14:58 GMT 2015
[INFO] Final Memory: 91M/414M
[INFO] ------------------------------------------------------------------------
[root@cs1 cloudstack]#

**Pull request merged**
