### PR TITLE
README: happy holidays!

### PR DESCRIPTION
**Pull request by bhaisaab**
Happy holidays, let's merge this asap
cc @remibergsma @DaanHoogland @wido @wilderrodrigues @abhinandanprateek @jburwell @borisroman @miguelaferreira @runseb @milamberspace @ke4qqq @karuturi @mlsorensen @mike-tutkowski @NuxRo @pdion891 @resmo @pyr and others

### CODE REVIEW

**Comment by pyr** [comment]
:+1:

**Comment by milamberspace** [comment]
:+1:  Happy holidays!

**Comment by agneya2001** [comment]
sure !

**Comment by wido** [comment]
:+1:

**Comment by NuxRo** [comment]
+1

**Comment by bhaisaab** [comment]
screen shot 2015-12-23 at 4 55 10 pm

File name changed to reflect the content

**Comment by pdion891** [comment]
Nice !    +1

**Comment by pdube** [comment]
lol @DaanHoogland . +1

**Comment by jburwell** [comment]
+1 LGTM

**Comment by mike-tutkowski** [comment]
Works for me. :)

**Comment by resmo** [comment]
:+1:

**Comment by remibergsma** [comment]
@bhaisaab Can you please send the PR to revert this, now that the holidays are over?

**Comment by bhaisaab** [comment]
@remibergsma okay

**Pull request merged**
