### PR TITLE
CLOUDSTACK-9359: IPv6 for Basic Networking

### PR DESCRIPTION
**Pull request by wido**
This PR is a proposal for adding very basic IPv6 to Basic Networking. The main goal of this PR is that the API returns a valid IPv6 address over which the Instance is reachable.

The GUI will show the IPv6 address after deployment of the Instance.

screenshot from 2016-10-03 16 34 56

If the table VLAN has a proper IPv6 CIDR configured the DirectPodBasedNetworkGuru will calculate the IPv6 Address the Instance will obtain using EUI-64 and SLAAC: https://tools.ietf.org/search/rfc4862

In this case the _vlan_ table contained:

<pre>mysql> select * from vlan \G
*************************** 1. row ***************************
                 id: 1
               uuid: 90e0716c-5261-4992-bb9d-0afd3006f476
            vlan_id: vlan://untagged
       vlan_gateway: 172.16.0.1
       vlan_netmask: 255.255.255.0
        description: 172.16.0.10-172.16.0.250
          vlan_type: DirectAttached
     data_center_id: 1
         network_id: 204
physical_network_id: 200
        ip6_gateway: 2001:980:7936:112::1
           ip6_cidr: 2001:980:7936:112::/64
          ip6_range: NULL
            removed: NULL
            created: 2016-07-19 20:39:41
1 row in set (0.00 sec)

mysql></pre>

It will then log:

<pre>2016-10-04 11:42:44,998 DEBUG [c.c.n.g.DirectPodBasedNetworkGuru] (Work-Job-Executor-1:ctx-1975ec54 job-186/job-187 ctx-0d967d88) (logid:275c4961) Found IPv6 CIDR 2001:980:7936:112::/64 for VLAN 1
2016-10-04 11:42:45,009 INFO  [c.c.n.g.DirectPodBasedNetworkGuru] (Work-Job-Executor-1:ctx-1975ec54 job-186/job-187 ctx-0d967d88) (logid:275c4961) Calculated IPv6 address 2001:980:7936:112:4ba:80ff:fe00:e9 using EUI-64 for NIC 6a05deab-b5d9-4116-80da-c94b48333e5e</pre>

The template has to be configured accordingly:
- No IPv6 Privacy Extensions
- Use SLAAC
- Follow RFC4862

This is also described in: https://cwiki.apache.org/confluence/display/CLOUDSTACK/IPv6+in+Basic+Networking

The next steps after this will be:
- Security Grouping to prevent IPv6 Address Spoofing
- Security Grouping to filter ICMP, UDP and TCP traffic

### CODE REVIEW

**Comment by wido** [comment]
@NuxRo and @rhtyd Would you mind taking a look at this one?

**Comment by rhtyd** [comment]
Thanks for the PR @wido
I can review/test next week, this in general looks great. Can you squash your commits with the commit message reflecting the JIRA id in the format `CLOUDSTACK-xxxx: one liner`.
 /cc @murali-reddy

**Comment by wido** [comment]
@rhtyd Thanks! I've updated and squashed the commits. Commit message now also shows more information.

Feedback is welcome! Currently working on the Security Grouping for IPv6. Will send each bit in as different, small, Pull Requests.

**Comment by NuxRo** [comment]
@wido As an IPv6 rookie I am trying to wrap my head around this. 
Why can't we just DHCP out to instances a /128, in a similar manner we do with IPv4?
Is this all to avoid too much code and db changes?

**Comment by wido** [comment]
@NuxRo There are two things to it.

First, yes, it saves a lot, a lot of code by using SLAAC/EUI-64. No need to configure dnsmasq or anything else. No failure possible where the VR is not responding or properly configuring the lease in it's database.

Secondly, with IPv6 Router Advertisements are mandatory anyway. DHCPv6 can't tell a Instance which gateway to use, that is always done by a RA.

With IPv6 using RA/SLAAC is most widely used and supported on all operating systems.

So using SLAAC makes life much, much easier. DHCPv6 is just not required at all.

**Comment by NuxRo** [comment]
Thanks
I'd be happy to give this a run when all the bits are in then, @wido 
@rhtyd if the orangutan could build some packages when the time comes, that's be great. ;-)

**Comment by rhtyd** [comment]
@blueorangutan package
@NuxRo sure

**Comment by wido** [comment]
@NuxRo The first test would be to run this code and actually see that the API returns a IPv6 address which you can then use to reach your Instance.

**Comment by NuxRo** [comment]
Wido,

Will do, but need to wait until next week to get some help re getting IPv6 on my test rig. As soon as I have feedback, I'll post here.

Lucian

--
Sent from the Delta quadrant using Borg technology!

Nux!
www.nux.ro

----- Original Message -----

**Comment by karuturi** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by karuturi** [comment]
@blueorangutan test matrix

**Comment by wido** [comment]
Seems good looking at the tests, right? These VPC tests have been failing for some time and do not seem to be related to this PR.

**Comment by rhtyd** [comment]
@wido due to the scope of the changes, I'll hold this PR until releases graduate. We'll get back to reviewing, testing this after the branches are cut. /cc @murali-reddy @abhinandanprateek pinging for review

**Comment by wido** [comment]
@rhtyd Understood! I have one more PR pending after this which should make IPv6 usable in Basic Networking.

4.11 would be great to get this in.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test centos7 kvm-centos6

**Comment by wido** [comment]
I rebased the code against master and it is compiling with Java 8 and passing all tests.

```[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8:59.691s (Wall Clock)
[INFO] Finished at: Thu Jan 26 15:45:36 CET 2017
[INFO] Final Memory: 105M/1555M
[INFO] ------------------------------------------------------------------------```

**Comment by karuturi** [comment]
LGTM. Test results are good. I am merging this now.

**Pull request merged**
