### PR TITLE
Fix delete network with no services

### PR DESCRIPTION
**Pull request by nvazquez**
## Description
Fix dele shared network with no services on network offering
Fixes: #4096 

## Types of changes
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?
Create network offering with no services
Create network from offering
Deploy VM
Delete network

### CODE REVIEW

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by nvazquez** [comment]
@borisstoyanov @andrijapanicsb @rhtyd I've checked the test environment and it ended up with a disabled zone and no system VMs, had to manually enable the zone back. Do you remember which test caused this failure?

**Comment by rhtyd** [comment]
@nvazquez you can check yourself:
```
$ cd test/integration/smoke
$ grep updateZone -R .
```

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
Ping @borisstoyanov @andrijapanicsb @DaanHoogland

**Pull request merged**
