### PR TITLE
ui: fix missing component in SearchView

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

TooltipButton was not added as Vue component. It was leading to error in page load.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### Screenshots (if appropriate):
Before (logs in console):
Screenshot from 2021-06-17 19-09-04

After (SearchView shows button with tooltip):
Screenshot from 2021-06-17 19-08-03

### How Has This Been Tested?
UI

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by rhtyd** [comment]
Does this affect 4.15.1 RC2 @shwstppr UI wide or limited to certain views?

**Comment by shwstppr** [comment]
> Does this affect 4.15.1 RC2 @shwstppr UI wide or limited to certain views?

@rhtyd this affects RC2 but a very minor issue in my opinion.
Clear button in the search form doesn't show up and the user will have to manually clear input fields.

**Review by utchoang — APPROVED** [review]
LGTM!

**Comment by rhtyd** [comment]
Lgtm

**Pull request merged**
