### PR TITLE
ui: fix getDiagnosticsData files field

### LINKED ISSUE #5707: Can't paste any value in Get Diagnostics Data
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION
~~~
4.16.0
~~~

##### CONFIGURATION
XCP-NG 8.2
Advanced Zone

##### OS / ENVIRONMENT
Oracle Linux 8.4 - Management server, MYSQL 8.0.26
XCP-NG 8.2 - hypervisor

##### SUMMARY
Can't paste any value in Get Diagnostics Data:
image

##### STEPS TO REPRODUCE
~~~
Try to get Diagnostics Data from VM or System VM
~~~
##### EXPECTED RESULTS
~~~
Administrator can paster any available value, for example, iptable or all Diagnostics Data after click OK button
~~~

##### ACTUAL RESULTS
~~~
Administrator can't paster any available value. Only all Diagnostics Data after click OK button are presented.
~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #5707

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):
getdiagnosticsdata

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan ui

**Review by utchoang — APPROVED** [review]
LGTM!

**Review by sureshanaparti — APPROVED** [review]
code LGTM

**Comment by sureshanaparti** [comment]
Verified the fix. Minor UI change, smoke tests not needed.

**Pull request merged**
