### PR TITLE
Fix 404 when moving a VM to out of a project

### PR DESCRIPTION
**Pull request by winterhazel**
### Description

In a project's view, after assigning an instance belonging to the project to a user account through the instance's page, the UI tries to refresh the information about the instance. However, as the project does not have permission to view instances from other accounts, the user is redirected to a 404.

This PR adds a check in the UI to avoid showing this 404.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### How Has This Been Tested?

In the root admin account, I made the following tests:

| Number | Test | Previous result | New result | Expected result? (Y/N) |
| - | - | - | - | - |
| 1 | In a project's view, I assigned an instance belonging to the project to a user account | UI gets redirected to a 404 | UI gets redirected to the instance listing | Y |
| 2 | In a project's view, I tried to assign an instance belonging to the project to the project itself | An error is shown, as the previous and the new owner are the same. The UI stays in the same page | An error is shown, as the previous and the new owner are the same. The UI stays in the same page | Y |
| 3 | In a project's view, I assigned an instance belonging to the project to another project in the same domain | UI gets redirected to a 404 | UI gets redirected to the instance listing | Y |
| 4 | In a project's view, I assigned an instance belonging to the project to another project in a subdomain | UI gets redirected to a 404 | UI gets redirected to the instance listing | Y |
| 5 | In the default view, I assigned an instance belonging to account A to account B | The UI refreshes the information about the instance | The UI refreshes the information about the instance | Y |

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@blueorangutan ui

**Review by GutoVeronezi — APPROVED** [review]
CLGTM

**Comment by GutoVeronezi** [comment]
@winterhazel, as this PR fixes the 404 error, it's `Types of changes` should be defined as `Bug fix`.

**Comment by rohityadavcloud** [comment]
@winterhazel can you change base branch to 4.19 as it's a fix.

**Review by lucas-a-martins — APPROVED** [review]
I manually tested this, lgtm

Before changes:

old#8650

After changes:

new#8650

**Comment by DaanHoogland** [comment]
@winterhazel , does this not occur on 4.18? or should it go into the 4.18 branch?

**Comment by winterhazel** [comment]
@DaanHoogland this problem also occurs on 4.18.

I'm not sure if this PR can still go to 4.18 though, as @JoaoJandre recently froze the branch and will move pending items to the next milestone. Will there be another milestone in 4.18 this PR can go to?

**Comment by DaanHoogland** [comment]
> @DaanHoogland this problem also occurs on 4.18.
> 
> I'm not sure if this PR can still go to 4.18 though, as @JoaoJandre recently froze the branch and will move most pending items to the next milestone. Will there be another milestone in 4.18 this PR can go to?

It does not matter, we can put it on the branch so people building their own have it, and we will still merge it forward to 4.19 whether there will be a 4.18.3 or not.

**Comment by DaanHoogland** [comment]
that said, just say no and we can merge it now

**Pull request merged**
