### PR TITLE
CLOUDSTACK-10251: HTTPS downloader for Direct Download templates failure

### PR DESCRIPTION
**Pull request by nvazquez**
JIRA Ticket: https://issues.apache.org/jira/browse/CLOUDSTACK-10251

Failure on HTTPS downloader for Direct Download templates on KVM.
Reason: Incorrect request caused NullPointerException getting the response InputStream

### CODE REVIEW

**Comment by nvazquez** [comment]
Ping for review @borisstoyanov @DaanHoogland @rhtyd

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
LGTM, merging based on test results and reviews.

**Pull request merged**
