### PR TITLE
UI: fixes login button not work and Single Sign-On tab disabled after logout

### PR DESCRIPTION
**Pull request by utchoang**
### Description

This PR for fixes:

- [x] The login button in Single Sign-On tab not working
- [x] Single Sign-On tab is disabled when logout from the application

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by rohityadavcloud** [comment]
@blueorangutan ui

**Review by nvazquez — APPROVED** [review]

**Comment by nvazquez** [comment]
Ping for review @rohityadavcloud @Pearl1594

**Review by rohityadavcloud — APPROVED** [review]
LGTM - but this needs testing - many changes

**Pull request merged**
