### PR TITLE
Change Global setting type for allow.user.create.projects

### PR DESCRIPTION
**Pull request by Pearl1594**
## Description
Fixes: https://github.com/apache/cloudstack/issues/4318

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?
Tested by changing the Global setting value on the UI

### CODE REVIEW

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan test

**Comment by Pearl1594** [comment]
@blueorangutan test

**Review by shwstppr — APPROVED** [review]
LGTM

**Comment by rhtyd** [comment]
LGTM

**Pull request merged**
