### PR TITLE
ui: Fix failing UI

### PR DESCRIPTION
**Pull request by davidjumani**
### Description

Fixes the error when building the UI

```

⇒  npm run serve                                        
> cloudstack-ui@1.0.0 serve /home/shwstppr/lab/shapeblue/cloudstack/ui
> vue-cli-service lint --no-fix && vue-cli-service serve
error: 'originalPage' is assigned a value but never used (no-unused-vars) at src/utils/plugins.js:59:9:
  57 |         action = null,
  58 |         bulkAction = false,
> 59 |         originalPage = null
     |         ^
  60 |       } = options
  61 | 
  62 |       store.dispatch('AddHeaderNotice', {
error: Parsing error: Unexpected token
  810 | 
  811 |         return resolve(false)
> 812 |       })
      |        ^
  813 |     },
  814 |     execSubmit (e) {
  815 |       e.preventDefault() at src/views/AutogenView.vue:1191:7:
  1189 | 
  1190 |         return resolve(false)
> 1191 |       })
       |       ^
  1192 |     },
  1193 |     execSubmit (e) {
  1194 |       e.preventDefault()
error: 'actions' is not defined (no-undef) at tests/unit/views/compute/MigrateWizard.spec.js:616:18:
  614 | 
  615 |         setTimeout(() => {
> 616 |           expect(actions.AddAsyncJob).toHaveBeenCalled()
      |                  ^
  617 |           expect(mocks.$pollJob).toHaveBeenCalled()
  618 |           expect(wrapper.emitted()['close-action'][0]).toEqual([])
  619 | 
3 errors found.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cloudstack-ui@1.0.0 serve: `vue-cli-service lint --no-fix && vue-cli-service serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cloudstack-ui@1.0.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan ui

**Review by shwstppr — APPROVED** [review]
LGTM. UI build working again

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by Pearl1594** [comment]
@blueorangutan ui

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
Looks like my forward merge created the boo-boo

**Pull request merged**
