### PR TITLE
utils: fix check for metalink url

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes condition

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by nvazquez — APPROVED** [review]
LGTM

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
code looks good @shwstppr, but what does this fix?

**Comment by shwstppr** [comment]
> code looks good @shwstppr, but what does this fix?

Code

**Comment by DaanHoogland** [comment]
> > code looks good @shwstppr, but what does this fix?
> 
> Code

haha, no issue no description. why is this?

**Comment by shwstppr** [comment]
> > > code looks good @shwstppr, but what does this fix?
> > 
> > 
> > Code
> 
> haha, no issue no description. why is this?

To fix code. I guess most developers should get the fact that the condition that has been changed was originally incorrect.

**Comment by shwstppr** [comment]
Merging based on tests and 2xLGTM

**Comment by DaanHoogland** [comment]
> > > > code looks good @shwstppr, but what does this fix?
> > > 
> > > 
> > > Code
> > 
> > 
> > haha, no issue no description. why is this?
> 
> To fix code. I guess most developers should get the fact that the condition that has been changed was originally incorrect.

Yes, they should but we are not all developers here and some might want to test this and want to know what behaviourt to look for.

**Pull request merged**
