### PR TITLE
UI - Fixes UI bugs

### PR DESCRIPTION
**Pull request by utchoang**
### Description

This PR fixes https://github.com/apache/cloudstack/issues/6107

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by nvazquez** [comment]
Thanks for the PR @utchoang - 2 new issues have been added since you have open the PR, if its not too much to ask can you please consider them as well on this PR?

**Comment by nvazquez** [comment]
@blueorangutan ui

**Comment by nvazquez** [comment]
Thanks @utchoang I have validated the following:

- As user: Does not refresh dashboard values when switching from a project to the default view -> FIXED
- Launch VM and stay on page does not work -> FIXED
- Destroy instance expanded menu throws errors in the console -> FIXED
- Clear notification button remains when a notification is dismissed via the 'x' icon -> FIXED

Have found some additional issues while testing the PR:
- As a user, accepting a project invitation worked but after accepting it the page continued loading and the popup didn't close - had to refresh the page to continue
Screen Shot 2022-03-25 at 11 12 13

- As a user, the events view below the dashboard is not aligned (it works when switching to a project)
Screen Shot 2022-03-25 at 11 15 12

- On a project view, the Kubernetes and Kubernetes ISO icons are not visible:
Screen Shot 2022-03-25 at 11 28 05

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by utchoang** [comment]
@nvazquez `Clicking on a SSH key gives 404 error` does it have to click SSH key pair from the menu? I tried to do it, no problem at all?

**Comment by davidjumani** [comment]
@utchoang When in a project view, and the user clicks on a specific ssh key, it should go into the detail view of that key. However it results in a 404. Caused by using `name=<key-id>` instead of `name=<key-name>` in the request

**Comment by nvazquez** [comment]
Yes @utchoang as @davidjumani describes, the issue comes when clicking on any created SSH key on the list

**Comment by davidjumani** [comment]
@blueorangutan ui

**Comment by utchoang** [comment]
@nvazquez I fixed it, Please check again. thanks

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by utchoang** [comment]
lòng gà xào hành

**Comment by utchoang** [comment]
@blueorangutan ui

**Review by nvazquez — APPROVED** [review]
Thanks @utchoang - LGTM, manually tested OK

**Review by weizhouapache — APPROVED** [review]
manually tested ok

**Pull request merged**
