### PR TITLE
UI: Network offering selection - Show display text instead of the name

### PR DESCRIPTION
**Pull request by utchoang**
### Description
Related https://github.com/apache/cloudstack-primate/pull/844
This PR to fix show display text instead of the name

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### Screenshots (if appropriate):
image

### CODE REVIEW

**Comment by utchoang** [comment]
@blueorangutan ui

**Review by shwstppr — APPROVED** [review]

**Review by rhtyd — APPROVED** [review]
LGTM we need someone to manually check the create network cases (from deploy VM form and network -> add network)

**Comment by rhtyd** [comment]
@shwstppr was a manual test done?

**Comment by shwstppr** [comment]
@rhtyd yes, tested network forms from Networks section and zone's traffic type tab

**Pull request merged**
