### PR TITLE
Disable logs to stdout and capture remaining stdout logs to a file

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

As of now, logs which get logged to journalctl also get logged to file. In one of the environments, we saw some logs which were present in journalctl but not in management-server.log file. This PR disables the logging to stdout and logs which are not getting captured will be logged to a file.

After this change,
1. stdout of cloudstack services is logged to files
2. Disable log4j logs from stdout to prevent duplication of logs
3. Add log rotation for stdout logs

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan test alma8 kvm-alma8

**Comment by vishesh92** [comment]
@blueorangutan test alma8 kvm-alma8 keepEnv

**Review by JoaoJandre — APPROVED** [review]
CLGTM

**Comment by vishesh92** [comment]
@blueorangutan test alma8 kvm-alma8 keepEnv

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Review by sureshanaparti — APPROVED** [review]
code lgtm

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by borisstoyanov — APPROVED** [review]
LGTM, manually checked it.

**Pull request merged**
