### PR TITLE
Console: upgrade noVNC from v1.2.0 to v1.4.0

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR upgrades the noVNC in ConsoleProxy VM from v1.2.0 to v1.4.0

Steps

1.  Create the patch by commands

    git clone -b v1.2.0 https://github.com/novnc/noVNC.git .
    git checkout v1.4.0
    git diff v1.2.0 >noVNC-v1.2.0-v1.4.0.patch

2. Apply the patch by

    cd systemvm/agent/noVNC
    patch -p1 <noVNC-v1.2.0-v1.4.0.patch

3. Fix conflicts

4. Use png instead of svg in html/css

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [x] Major
- [ ] Minor

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan help

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Review by vladimirpetrov — APPROVED** [review]
LGTM based on manual testing. Tested upgrade from 4.18, virtual keys, hiding full screen button when not connected, API driver console access, secure KVM VNC connection. Virtual shift key is not working properly on KVM but it's not a regression - the same behavior is in 4.18.0.

**Review by rohityadavcloud — APPROVED** [review]
Overall LGTM - @weizhouapache could you remove some folders/files that aren't necessary for novnc (such as the .github folder).

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Review by andrijapanicsb — APPROVED** [review]
LGTM

(tested)

**Pull request merged**
