### PR TITLE
CLOUDSTACK-9683: system.vm.default.hypervisor will pin the hypervisor…

### PR DESCRIPTION
**Pull request by abhinandanprateek**
… for VR too with this fix

### CODE REVIEW

**Comment by abhinandanprateek** [comment]
@blueorangutan help

**Comment by abhinandanprateek** [comment]
@blueorangutan test centos6 kvm-centos6

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by abhinandanprateek** [comment]
@blueorangutan test centos6 kvm-centos6

**Comment by borisstoyanov** [comment]
LGTM based on code review and test results, there seems to be no new test failures present.

**Comment by rhtyd** [comment]
@abhinandanprateek do we have a unit test or integration/smoke test to validate the global setting, or can you write one?

**Comment by abhinandanprateek** [comment]
@rhtyd  most of the automation environments are single hypervisor one, so will end up creating a mixed hypervisor zone for this test only. If that can be done i can put one together, probably not worth the effort. @borisstoyanov

**Comment by rhtyd** [comment]
LGTM. Merging this now.

**Pull request merged**
