### PR TITLE
CLOUDSTACK-8970 Centos 6.{1,2,3,4,5} guest OS mapping for vmware is n…

### PR DESCRIPTION
**Pull request by SudharmaJain**
…ot available

### CODE REVIEW

**Comment by snuf** [comment]
Values are inline with the guest_os table and inserts the inserts all work so LGTM!

**Comment by bhaisaab** [comment]
LGTM, @abhinandanprateek do you have any comments?

**Comment by bhaisaab** [comment]
@SudharmaJain please rebase against latest

**Comment by SudharmaJain** [comment]
@bhaisaab Rebased against master.

**Comment by bhaisaab** [comment]
@SudharmaJain The provided version have already released so these change need to go into 481to490 related sql /cc @swill 

any vmware/guest-os-mapping guru want to comment on the changes -- @anshulgangwar @devdeep @agneya2001 @koushik-das @sureshanaparti

**Comment by SudharmaJain** [comment]
@bhaisaab Thanks for the comment. I  have updated with the latest now.

**Comment by koushik-das** [comment]
Changes LGTM.
@swill This can be merged.

**Comment by swill** [comment]
Do we have any verification that this does what it is supposed to?  It would be good if we could get some form of verification posted that this behaves as expected.

**Comment by rhtyd** [comment]
@SudharmaJain please rebase against master and push -f, and update on status of your PR, thanks
LGTM

tag:easypr

**Comment by swill** [comment]
Can you do a force push again.  Jenkins has been in this state for 3 days now.  Thx...

**Comment by SudharmaJain** [comment]
@swill I force pushed again and still it is failing. In logs I see following error.

fatal: write error: No space left on device

**Comment by swill** [comment]
Thanks @SudharmaJain.  I will get someone to look into this.  @DaanHoogland do you or @pdion891 have access to this box to clean up the disk space so it is functional again?  I am not sure who had access to these boxes...

**Comment by SudharmaJain** [comment]
Rebased and pushed it again.

**Comment by swill** [comment]
Can someone with a VMware environment validate this PR is functional?  I don't think running CI is going to give us anything on this one since I only have KVM  and this is only a DB change.  Thoughts???

**Comment by swill** [comment]
@SudharmaJain please rebase as we now have merge conflicts.  Ideally we would have some verification that this works as expected.  I don't have the ability to test this.

**Comment by SudharmaJain** [comment]
@swill Rebased against master.

**Comment by swill** [comment]
Thank you @SudharmaJain.  Is there anything you can provide to show this works as expected?  Screenshots or something?  I don't have the ability to CI this, so it would be awesome if we could get some sort of verification that this is working.  Are you running this in production somewhere?

**Comment by SudharmaJain** [comment]
Getting following error with Jenkins

Running org.apache.cloudstack.utils.hypervisor.HypervisorUtilsTest
Testing don't block on newly created clones - pass
Testing block on modified files - pass
Testing timeout of blocking on modified files - pass
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.272 sec - in org.apache.cloudstack.utils.hypervisor.HypervisorUtilsTest
Running org.apache.cloudstack.utils.imagestore.ImageStoreUtilTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.057 sec - in org.apache.cloudstack.utils.imagestore.ImageStoreUtilTest
Running org.apache.cloudstack.utils.process.ProcessTest
Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 301.061 sec <<< FAILURE! - in org.apache.cloudstack.utils.process.ProcessTest
testProcessRunner(org.apache.cloudstack.utils.process.ProcessTest)  Time elapsed: 300.038 sec  <<< FAILURE!
java.lang.AssertionError: expected:<-1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.apache.cloudstack.utils.process.ProcessTest.testProcessRunner(ProcessTest.java:43)

**Comment by abhinandanprateek** [comment]
@SudharmaJain it is a unit test failure triggered by an assert. cc @rhtyd It is being generated by ProcessRunner.

**Comment by rhtyd** [comment]
My bad, it is fixed here: https://github.com/apache/cloudstack/pull/1543

**Comment by swill** [comment]
@SudharmaJain can you re-push or close and reopen this PR to kick off Jenkins again?

@rhtyd and @nvazquez I know you both use VMware.  I don't have a way to validate this PR, so can you give me your opinion on if this should be merged without validation or can either of you validate this PR in your environment and give me a verbal OK?  Since I don't have a way to test this, I want some verification from someone who is affected by this PR.  Thx...

**Comment by swill** [comment]
@SudharmaJain can you rebase and push to see if we can get this green for the 4.9 freeze...

**Comment by SudharmaJain** [comment]
Rebased and pushed the branch.

**Comment by swill** [comment]
I have no way to test this and no one has verification of this from what I can tell.  Otherwise it is ready to go...  I may have to make a judgement call on this one for 4.9.  Thoughts?

**Comment by pdion891** [comment]
LGTM, unfortunately there is not way on our side to tests this :-S because it require VMware host.
but inserts are similar to previous from previous releases.

**Comment by DaanHoogland** [comment]
Why would we need this?
https://cloudstack.apache.org/api/apidocs-4.8/root_admin/addGuestOsMapping.html
Ypu can add an guest os to hypervisormapping on runtime

**Comment by pdion891** [comment]
@DaanHoogland to automatically have support for those OSes ? unless we should have a script that auto populate Oses mapping thru the API instead of preinserting data into the database.

**Pull request merged**
