### PR TITLE
UI: add component was missing

### PR DESCRIPTION
**Pull request by utchoang**
### Description

Fixes https://github.com/apache/cloudstack/issues/4724

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### Screenshots (if appropriate):
After fix:

- Autocomplex:
image

- Slider:
image

### CODE REVIEW

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by rhtyd** [comment]
@blueorangutan ui

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
@blueorangutan ui

**Comment by DaanHoogland** [comment]
@utchoang the combobox looks fine but I am missing the slider from the vm create dialog in that ^^ buils. Am I looking in the wrong place?

**Comment by davidjumani** [comment]
@blueorangutan ui

**Comment by utchoang** [comment]
@DaanHoogland During my testing I found the slider component was missing so I added it.

**Comment by DaanHoogland** [comment]
> @DaanHoogland During my testing I found the slider component was missing so I added it.

@utchoang , I didn't find the new slider yet, I expected it at the cpus in the instance creation wizard. Where should I look?

**Comment by utchoang** [comment]
@DaanHoogland You can go to Instance -> Add instance
image

**Comment by DaanHoogland** [comment]
ah, does it only work with the 'constrained' offering? (i tried 'unconstrained')

**Pull request merged**
