### PR TITLE
CLOUDSTACK-8757:FTP modules are not loaded in VR

### PR DESCRIPTION
**Pull request by shwetaag**
check bug 8757 for more details .

### CODE REVIEW

**Comment by remibergsma** [comment]
@shwetaag Can you please add more details? The Jira issue only has a title. Are you submitting a test so in case the modules are not loaded, alarms go off? Or do you think it is actually broken right now in master?

When I test it, it seems to work:
```
root@r-3-VM:~# lsmod | grep ftp
nf_nat_ftp             12460  0 
nf_nat                 18242  2 nf_nat_ftp,iptable_nat
nf_conntrack_ftp       12605  1 nf_nat_ftp
nf_conntrack           52720  7 nf_conntrack_ipv4,nf_conntrack_ftp,nf_nat,nf_nat_ftp,iptable_nat,xt_state,xt_connmark
```

If you want to submit a test (which is great btw!), then please update the title of the PR and the Jira issue accordingly. Thanks!

**Comment by shwetaag** [comment]
@remibergsma : i have added details to the bug . Copy pasting for your reference 
To have Active FTP working in isolated networks VRs need the have the following modules loaded (In order to map the FTP Data and FTP CMD to the same frontend IP):

    modprobe nf_conntrack_ftp
    modprobe nf_nat_ftp

in some versions of Cloudstack we noted that these modules are not loaded on CS Routers by default  . So this test case is for verifying that these modules are loaded by default in VR and if not report an error

**Comment by remibergsma** [comment]
@shwetaag Could you change the title to: "CLOUDSTACK-8757: Test to verify if FTP modules are loaded in VR" as right now it looks like there is a defect, which there is not.

Also, could you post the test results please. I'll have a look tomorrow and see if I can run the test as well.

Thanks!

**Comment by shwetaag** [comment]
Result information: 
test_01_FTPModulesInVR (integration.component.maint.test_escalations_routers.TestVR) ... === TestName: test_01_FTPModulesInVR | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 1 test in 233.348s

OK

**Comment by remibergsma** [comment]
@shwetaag Thanks. I was also able to run your test. Please change the title, see previous comment.

```
[root@cs2 cloudstack]# cat /tmp//MarvinLogs/test_escalations_routers_G3E8EO/results.txt
@desc: Verify FTP modules are loaded in VR of advance zone ... === TestName: test_01_FTPModulesInVR | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 1 test in 415.669s

OK
```

**Comment by bhaisaab** [comment]
Code LGTM (not tested on a real infra though), merging.

**Pull request merged**
