### PR TITLE
api: fix ipv6 firewall apis default role permissions

### LINKED ISSUE #6575: Missing IPV6 Firewall in UI User view
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.17
~~~

##### CONFIGURATION

IPV6 Isolated Networkers (DUAL STACK)

##### SUMMARY
Under Network -> Guest Networks -> any IPV4+IPV6 (Dualstack) networker the tab IPv6 Firewall is missing for anyone but the Administrator. 

##### STEPS TO REPRODUCE

~~~
Create a new Isolated IPv4 + IPv6 network.
Check network with Administrator and you will see Ipv6 Firewall is present
Check with user that the network belongs to. The Ipv6 Firewall tab is missing.
~~~

##### EXPECTED RESULTS

~~~
Both User and Administrator should be able to view and configure IPV6 Firewall
~~~

##### ACTUAL RESULTS
~~~
Only Administrator can see and configure IPV6 Firewall
~~~

~~~
Admin view:
![image](https://user-images.githubusercontent.com/78906279/181244312-95350d96-1cf0-42ed-9e9b-c514cca35b4f.png)

User: view
![image](https://user-images.githubusercontent.com/78906279/181244464-6865079b-4bd2-42f3-86d1-a582f60ed6b5.png)
~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description
Fixes default roles permissions for IPv6 firewall related APIs
Refactors related marvin tests to call deploy, update, restart network and VM APIs as user instead of the admin
Fixes #6575

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Review by weizhouapache — APPROVED** [review]
code lgtm

@shwstppr are the two `test_network_ipv6.py` same ?

**Review by rohityadavcloud — APPROVED** [review]

**Comment by shwstppr** [comment]
@weizhouapache no. The file under component tests has more number of tests

**Comment by shwstppr** [comment]
@blueorangutan test

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-67u3

**Pull request merged**
