### PR TITLE
utils: Add support for TLSv1.3 and deprecate TLSv1.0 and TLSv1.1

### PR DESCRIPTION
**Pull request by rohityadavcloud**
This adds support for TLSv1.3 as one of the recommended protocols as per
RFC8446 and deprecates TLSv1.0 and TLSv1.1 from recommended protocols
list as per RFC8996 which deprecates both TLSv1.0 and TLSv1.1 as of March 2021.

Refs:
https://datatracker.ietf.org/doc/html/rfc8446
https://datatracker.ietf.org/doc/html/rfc8996

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [x] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [x] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by rohityadavcloud** [comment]
This might be acceptable only if it passes smoketests as this can potentially break support for older distros and hypervisors. However, around Q3 2022, several old distros and hypervisors are reaching EOL (https://cwiki.apache.org/confluence/display/CLOUDSTACK/Hypervisor+and+Management+Server+OS+EOL+Dates). 

Deprecating both TLSv1 and TLSv1.1 becomes important for organisations who want to pass HIPPA, PCI, NIST etc certifications. Let's discuss - cc @andrijapanicsb @alexandremattioli @NuxRo @ @gsirett @DaanHoogland @wido @GabrielBrascher @kiwiflyer @mlsorensen @svenvogel and others.

@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test matrix

**Comment by rohityadavcloud** [comment]
Looks like we can't deprecate TLSv1, TLSv1.1 if env are failing
@blueorangutan test

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
Actually leave it for now @sureshanaparti, TLSv1.3 may not work with many older hypervisors. Many of those are reaching EOL by mid of '22, so we can revisit this PR for 4.17 or 4.18/future.

**Comment by nvazquez** [comment]
Hi @rohityadavcloud, is this PR ready for review or still needs work? Should we consider it for 4.17?

**Comment by rohityadavcloud** [comment]
Thanks @svenvogel given that we still support legacy hypervisors (XS7.1, vmware 6.0/6.5) we can't get this PR in yet. Hopefully by end of this year or sometime next year we can do something about it. I'll close the PR for now and open an issue to track this for 4.18/4.19.

**Pull request closed without merging**
