### PR TITLE
Check the network access when deploying VM in Advanced Security Group.

### LINKED ISSUE #6049: CloudStack allows deploying VMs on Networks that should not be accessed by VM's owner
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
(probably affects also versions before 4.15, but not tested before)
4.15
4.16
main (4.17)
~~~

##### CONFIGURATION

Advanced network with security groups

##### OS / ENVIRONMENT

N/A

##### SUMMARY

VMs can be deployed with Networks that have a domain ID where the VM’s owner / domain should not be able to.

Even with the user not being able to list the UUID, it is still possible to use the API command to deploy when passing the UUID.
This also can be easily reproduced when the root admin (which can list all networks) uses a "private" network when deploying a VM to a user that does not have access to the respective "private" / "restricted" network.

This can become a very serious issue in case this grows into multiple VMs on the wrong networks.
Also, this is a security issue.

##### STEPS TO REPRODUCE

~~~
Deploy VM for an account that has no access to the network ID
~~~

##### EXPECTED RESULTS

~~~
VM is not deployed (propper error message should be thrown)
~~~

##### ACTUAL RESULTS

~~~
VM is deployed on network that the user / domain should not be able to
~~~

### PR DESCRIPTION
**Pull request by sureshanaparti**
### Description

This PR checks the network access when deploying VM in Advanced Security Group.

Fixes #6049 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [x] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

- Before fix, able to deploy VM with ROOT account, in Domain02 using network on Domain01 (in  Advanced Security Group)
- After fix, deploy VM failed with '_Unable to use network with id= 031a45f3-8522-4265-a145-6a647df20d27, permission denied_'

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@GabrielBrascher can you please review/test this fix?

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Review by weizhouapache — APPROVED** [review]
code lgtm !!

**Comment by sureshanaparti** [comment]
> @sureshanaparti
> can you also add my suggestion in comment [#6049 (comment)](https://github.com/apache/cloudstack/issues/6049#issuecomment-1054422439) to this PR ?

@weizhouapache the access check for VM owner already exists here.
https://github.com/apache/cloudstack/blob/85c59979f76cef39559c75000de536a9103318bc/server/src/main/java/com/cloud/vm/UserVmManagerImpl.java#L1312-L1313

so, the check against caller is still required here?
https://github.com/apache/cloudstack/blob/85c59979f76cef39559c75000de536a9103318bc/server/src/main/java/com/cloud/vm/UserVmManagerImpl.java#L1339-L1340

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by GabrielBrascher** [comment]
Thanks for the PR @sureshanaparti!
Is this ready to review or still in Draft?

I did a few tests applying your changes and seems to be working fine.
I will be running a few more tests but wanted to double-check if there is anything left for the PR.

**Comment by sureshanaparti** [comment]
> Thanks for the PR @sureshanaparti! Is this ready to review or still in Draft?
> 
> I did a few tests applying your changes and seems to be working fine. I will be running a few more tests but wanted to double-check if there is anything left for the PR.

it is ready for review @GabrielBrascher

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@sureshanaparti 
should this target to 4.16 ?

**Review by GabrielBrascher — APPROVED** [review]
@Thanks @sureshanaparti, code LGTM.
Tested With Advanced Network + SG and now it is working as expected.

**Comment by sureshanaparti** [comment]
> @thanks @sureshanaparti, code LGTM.
> Tested With Advanced Network + SG and now it is working as expected.

great, thanks for testing @GabrielBrascher

**Comment by sureshanaparti** [comment]
> @sureshanaparti
> should this target to 4.16 ?

@weizhouapache this is targeted to 4.17

**Comment by weizhouapache** [comment]
> 

if there is 4.16.2.0 release, we need to backport this, right ?
why not target to 4.16 ?

**Comment by sureshanaparti** [comment]
> if there is 4.16.2.0 release, we need to backport this, right ?
> why not target to 4.16 ?

yes, may be when another minor release is needed on 4.16.

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by nvazquez** [comment]
Agree with @weizhouapache - let's target the fix for branch 4.16 and merge forward to main

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Review by nvazquez — APPROVED** [review]
LGTM

**Pull request merged**
