### PR TITLE
hypervisor: Add Citrix Hypervisor 8x product name support

### PR DESCRIPTION
**Pull request by shwstppr**
## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test centos7 xenserver-71

**Comment by rhtyd** [comment]
rekicked test manually

**Comment by rhtyd** [comment]
@shwstppr was any testing done against Citrix Hypervisor 8.x, cc @DaanHoogland @andrijapanicsb

**Comment by andrijapanicsb** [comment]
none (afaik) @rhtyd - as the product name is changed, so is writen like that in DB, and code doesn't recognise that HV (this PR - I never tested)

**Comment by harikrishna-patnala** [comment]
As far as I remember we also have to address the name change of XenServer Tools to Citrix Hypervisor Tools. This must be during attach and dettach ISO operations.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
https://github.com/apache/cloudstack/blob/master/plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/discoverer/XcpServerDiscoverer.java#L121-L122
@harikrishna-patnala this is the only remaining place where I see Xenserver Tools name used in java code. Does this needs updating?

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@andrijapanicsb @borisstoyanov - are you LGTM on it, have we tested it (assuming XS/Citrix Hypervisor 8.0 iso was available)? Or we can merge based on regression testing?

**Comment by andrijapanicsb** [comment]
I haven't tested this, we don't have the Trillian template for this, so it would requre manually building a small CS 8.1 pool and verifying there...takes time.

**Comment by rhtyd** [comment]
@blueorangutan package

**Review by DaanHoogland — COMMENTED** [review]
code looks good but I have no idea of completeness. extensive xen 8 testing is needed for this.

**Comment by shwstppr** [comment]
@blueorangutan help

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test centos7 xcpng81

**Comment by shwstppr** [comment]
Screenshots from local testing for reference cc @rhtyd @harikrishna-patnala @davidjumani @DaanHoogland @Pearl1594 @weizhouapache @ravening 
Will be great if others can test/review

Citrix Hypervisor 8.1 host added
Screenshot from 2020-10-08 12-18-41
Screenshot from 2020-10-08 12-23-31

System VMs running
Screenshot from 2020-10-08 12-25-04

VM deployment working
Screenshot from 2020-10-08 12-34-14
Screenshot from 2020-10-08 12-33-46

VR seems okay as well
Screenshot from 2020-10-08 12-37-20
Screenshot from 2020-10-08 12-37-44

**Comment by rhtyd** [comment]
Thanks for test results @shwstppr, merging this based on regression tests and code LGTM from Daan and I.

**Pull request merged**
