### PR TITLE
UI: Prevent listing network offering with external LB for VPC tiers if a n/w already exists

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

Fixes https://github.com/apache/cloudstack/issues/4985

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by Pearl1594** [comment]
@blueorangutan ui

**Review by shwstppr — APPROVED** [review]
Code LGTM. Haven't tested

**Review by utchoang — APPROVED** [review]
LGTM!

**Comment by rhtyd** [comment]
@blueorangutan help

**Pull request merged**
