### PR TITLE
novnc: Fix vm console is not working on firefox if language is not English

### PR DESCRIPTION
**Pull request by ustcweizhou**
### Description

This PR fixes the blank screen issue of novnc console if language is not English in some browsers.

Steps to reproduce the issue
(1) install firefox, and switch to another language other than English, for example Germany, Russian.
refer to https://support.mozilla.org/en-US/kb/use-firefox-another-language
(2) open vm console

Expected result: console works
Actual result: the first time it works, then blank screen in retries (also with other vms).

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [X] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by ustcweizhou** [comment]
@davidjumani please review and test it

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by davidjumani — APPROVED** [review]
LGTM! Tested and Working

**Review by rhtyd — APPROVED** [review]
Didn't test it, LGTM otherwise

**Comment by rhtyd** [comment]
Merging based on Travis job1 as manually it was tested by David (novnc console is not covered otherwise by marvin tests).

**Comment by luhaijiao** [comment]
We have hit the same issue.  Shall we have it in 4.15.1 as well since it's not released yet.

**Comment by weizhouapache** [comment]
> We have hit the same issue. Shall we have it in 4.15.1 as well since it's not released yet.

@luhaijiao it has been merged into 4.15 branch, it will be released in 4.15.1.0

**Pull request merged**
