### PR TITLE
UI: Display drop down list for VPN customer gateway selection

### PR DESCRIPTION
**Pull request by ravening**
## Description

Display drop-down list for VPN customer gateway selection in UI so that it can be searched according to domains

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## Screenshots (if appropriate):
Before the change, there was no drop down list for domains

Screenshot 2020-01-13 at 14 49 24

After the change there is a drop down and the domains are displayed in the sorted order

Screenshot 2020-01-13 at 14 50 09

### CODE REVIEW

**Comment by weizhouapache** [comment]
pure UI change.
LGTM

**Comment by DaanHoogland** [comment]
@ravening I see your use case and do approve. Could you please keep in mind that this UI is phased out and create a primate ticket?

**Comment by ravening** [comment]
> @ravening I see your use case and do approve. Could you please keep in mind that this UI is phased out and create a primate ticket?

@DaanHoogland Just to confirm, are you saying all the future Ui pr's should be raised again primate and not here?

**Comment by DaanHoogland** [comment]
> > @ravening I see your use case and do approve. Could you please keep in mind that this UI is phased out and create a primate ticket?
> 
> @DaanHoogland Just to confirm, are you saying all the future Ui pr's should be raised again primate and not here?

No, not at the moment. I am saying that primate is planned to replace the UI as the standard UI in 4.15. It is still in alpha mode so it may take a while. but when voted on primate will probably be the only UI maintained and whether it will be part of this project is to be decided but very likely, so in that case PRs for UI will still be here!

**Comment by rhtyd** [comment]
Can anyone confirm manual testing?

**Comment by weizhouapache** [comment]
> Can anyone confirm manual testing?

I have manually tested it

**Comment by rhtyd** [comment]
Merging this based on @weizhouapache 's manual tests, code lgtm.

**Pull request merged**
