### PR TITLE
Improvements and cleanup on the javadocs of QemuImg

### PR DESCRIPTION
**Pull request by GaOrtiga**
### Description

This PR improves the javadocs of the class `QemuImg` by fixing grammatical errors, cleaning up methods that were not implemented, enhancing existing documentation and adding new. 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [X] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?
I built the code in a local lab and checked that there were no errors.

### CODE REVIEW

**Review by stephankruggg — APPROVED** [review]

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by BryanMLima — APPROVED** [review]

**Comment by GutoVeronezi** [comment]
@blueorangutan package

**Review by GutoVeronezi — APPROVED** [review]
LGTM

**Comment by GutoVeronezi** [comment]
Merging this one based on test and packaging results and approvals. Errors in https://github.com/apache/cloudstack/pull/6917#issuecomment-1335767747 does not seem related to the PR.

**Pull request merged**
