### PR TITLE
ui: update npm dependencies to latest

### PR DESCRIPTION
**Pull request by rohityadavcloud**
Run commands to update dependencies:

    npm outdated
    npm update

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by rohityadavcloud** [comment]
@blueorangutan ui

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan ui
@blueorangutan package

**Review by utchoang — APPROVED** [review]
LGTM!

**Review by davidjumani — APPROVED** [review]
CLGTM. Will run tests of this along with Vue3

**Comment by rohityadavcloud** [comment]
@davidjumani great, agree. Let's merge this only after running some manual tests.

**Review by sureshanaparti — APPROVED** [review]

**Review by davidjumani — APPROVED** [review]
Ran basic tests, Good to merge. Can continue testing once merged

**Pull request merged**
