### PR TITLE
schema,upgrade: fix wrong comment for new columns of cloud.event

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes wrong comment for column added for `cloud.event`

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by nvazquez — APPROVED** [review]

**Comment by nvazquez** [comment]
@blueorangutan package

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Pull request merged**
