### PR TITLE
Git PR merge script improvements

### PR DESCRIPTION
**Pull request by remibergsma**
Processed feedback from @bhaisaab and (a colleague of) @karuturi 

- make the help message better (I also updated Confluence)
- make sure we can use it on other repo's as well (Documentation and such)

Tested it and works fine for me.

### CODE REVIEW

**Comment by karuturi** [comment]
tested with a cloudstack-docs-admin PR and a cloudstack PR. worked great. Thanks for the update. 
:+1:

**Comment by terbolous** [comment]
Might not be related as this is the first time I try the script, but I'm getting this:
eriweb@eriweb:~/git/cloudstack/tools/git master$ git pr 735 --force
WARNING: You used --force to merge a PR with non-clean merge state 'unstable'.
ERROR: We couldn't find a git remote pointing to 'apache/cloudstack.git' to merge the PR from.
INFO: Current remotes:
origin	git@github.com:apache/cloudstack (fetch)
origin	git@github.com:apache/cloudstack (push)

Seems to be because i used the git@github.com (which lacks the .git suffix), rather than the https form. Should be an easy fix (probably just drop the .git while greping)?

**Comment by terbolous** [comment]
On the other side, if you just drop the '.git' suffix, you risk matching things like 'cloudstack-docs-rn' while you really mean 'cloudstack'

**Comment by remibergsma** [comment]
@terbolous You need to point to the Apache mirror on GitHub, not your fork. The PRs are at the mirror repository. Also, the version from this PR gives more descriptive error messages. Another thing I note is that you do not have the Apache upstream repo in your remotes. Please see: https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61311655 Let me know if you need more help!

**Comment by bhaisaab** [comment]
LGTM

**Comment by terbolous** [comment]
@remibergsma it does point to the apache repo, but with a somewhat different url

I used 'git clone gh:apache/cloudstack' to initialize the repo, and that doesn't seem to include .git in the path.

My url: git@github.com:apache/cloudstack 
Script expected url: git@github.com:apache/cloudstack.git (or using https mode)
Both works, so I just wanted to give a heads up as more people might experience the same.

It is true that I didn't have the apache official repo added yet, but that isn't relevant to the error.

I can fix it on my end by changing the path to include .git, but this can easily confuse others (as the repo is present)

**Comment by remibergsma** [comment]
@terbolous Ah, I see your point now ;-) Thanks, I will make it work.

**Comment by remibergsma** [comment]
@terbolous Hmm, the default always includes .git in the end (both for https and ssh). Although, as you said, omitting the .git part works (in both cases). Just submitted a patch to make it work, please test.

**Comment by remibergsma** [comment]
@terbolous Squashed the latest fix into an earlier commit, as that makes more sense. If you want to see the diff that should fix your issue, look here: https://github.com/remibergsma/cloudstack/commit/221e0e3d8340e10d8231677347a42d5f14eec9b0

**Comment by terbolous** [comment]
Verified that it now works on my weird URL as well.

LGTM

**Pull request merged**
