### PR TITLE
server: dedicate vxlan range to account

### LINKED ISSUE #6871: Guest Network - Dedicated VXLAN Range
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
API, UI
~~~

##### CLOUDSTACK VERSION
~~~
4.17.0, 4.17.1
~~~

##### CONFIGURATION
Advanced Networking

##### OS / ENVIRONMENT
N/A

##### SUMMARY
I can't add a dedicated VXLAN range

##### STEPS TO REPRODUCE
 * Edit the guest physical network from the UI interface
 * Add a dedicated VLAN/VNI range

image

##### EXPECTED RESULTS
A new dedicated VXLAN range

##### ACTUAL RESULTS
image

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #6871

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by kiranchavala** [comment]
@blueorangutan  ui

**Comment by kiranchavala** [comment]
@blueorangutan help

**Comment by kiranchavala** [comment]
@blueorangutan ui

**Comment by kiranchavala** [comment]
@weizhouapache 

Tested the issue LGTM 

was able to dedicate vxlan range to an account

on 4.17.2 - exception 

vxaln


On PR build 

vxaln2

**Comment by weizhouapache** [comment]
thanks @kiranchavala for the testing

added to 4.18.1.0 milestone . cc @DaanHoogland

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by shwstppr — APPROVED** [review]
Code LGTM

**Comment by shwstppr** [comment]
@blueorangutan test

**Review by rohityadavcloud — APPROVED** [review]
I did n't test it, but logical changes LGTM

**Comment by rohityadavcloud** [comment]
Test failures not related to this PR. Merging this.

**Pull request merged**
