### PR TITLE
Add and improve logs in ACS bootstrap process

### PR DESCRIPTION
**Pull request by stephankruggg**
### Description

ACS bootstrap process contains code that might cause exceptions, which are not logged; thus, it can make it hard for developers and operators to understand what is happening to the system and breaking the boot of the application. This PR intends to improve and add new logs to this process in order to facilitate troubleshooting.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

### How Has This Been Tested?
I applied the changes in a local lab and checked if the messages were being correctly logged.

### CODE REVIEW

**Review by GaOrtiga — APPROVED** [review]

**Review by DaanHoogland — COMMENTED** [review]
i´d approve if any debug log statements that do parameter evaluation were guarded.

**Review by GutoVeronezi — APPROVED** [review]
LGTM, I just pointed out a minor improvement.

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by GutoVeronezi** [comment]
@DaanHoogland @rohityadavcloud can we run the tests for this one?

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
double check:
@blueorangutan test

**Review by shwstppr — APPROVED** [review]
Code LGTM

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Review by DaanHoogland — COMMENTED** [review]
in my opinion debug logging should still be guarded if parameter expansion is done, but as I am alone in this opnion I am no longer going to ask for changes in that perspect, hte rest looks good.

**Comment by DaanHoogland** [comment]
@GutoVeronezi still want to review?

**Pull request merged**
