### PR TITLE
add kvm vcpu socket and threads config

### PR DESCRIPTION
**Pull request by div8cn**
## Description

Supplement the vcpu cores Per Socket configuration of KVM VM
Increase the vcpu hyperthreading configuration of KVM VM

Use vm.details for configuration

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by luhaijiao** [comment]
This feature aims to allow user to specify how many CPU sockets the target VM would have by using the 'cores per socket' parameter.  

Assume user assign 16 vCPUs to a new VM,  without manually specify the 'cores per socket',  CloudStack would try to divide the 16 vCPUs by 6, 4 and 1 in order.  In this case,  CloudStack would assign 4 sockets (16vCPUs /4) to this VM and every scoket has 4 vCPUs.

In most cases,  it shall casue no issue, however if there's sort of CPU limits due to Guest OS or application, e.g. SQL Sever version,   it could turn into a big performance issue. 

In our real case,  user deployed an Windows 10 guest OS with 16 vCPUs,  and CloudStack assgins 4 virtual CPU sockets by default.    Due to Windows 10 only supports 2 CPU sockets (https://answers.microsoft.com/en-us/windows/forum/windows_10-win_upgrade/windows-10-versions-cpu-limits/905c24ad-ad54-4122-b730-b9e7519c823f?auth=1) ,  it turns out this guest OS is only able to utilize two sockets (8 vCPUs) even though we have assigned 16 vCPUs in toal.   If user has CPU intensive application running on this VM,  this could introduce bottelneck.

**Comment by DaanHoogland** [comment]
@GabrielBrascher @div8cn @luhaijiao what is the status of this PR?

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
#4497

**Pull request closed without merging**
