### PR TITLE
 CLOUDSTACK-9598: wrong defaut gateway for the nic in non-default network

### PR DESCRIPTION
**Pull request by murali-reddy**
when guest VM has nic's in more than one guest network set the tag for each host in /etc/dhcphosts.txt, and use the tag to add exception in /etc/dhcpopts.txt to prevent sending default route, dns server in case if the nic is in non-default network

this was the behaviour with edithosts.sh prior to 4.6

### CODE REVIEW

**Comment by murali-reddy** [comment]
@blueorangutan package

**Comment by murali-reddy** [comment]
@blueorangutan test

**Comment by ustcweizhou** [comment]
I suggest to use default_entry in the script.
see https://issues.apache.org/jira/browse/CLOUDSTACK-9017?focusedCommentId=15653794&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15653794

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by murali-reddy** [comment]
Added test case TestRouterDHCPOpts, that will test the VR behaviour of not sending gateway and DNS server information while server DHCP response on non-default network NIC's

@ustcweizhou i have used default_entry as per your comment, as it make more sense

**Comment by murali-reddy** [comment]
@blueorangutan package

**Comment by murali-reddy** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@murali-reddy can you check why `test_router_dhcp_opts` failed?
@blueorangutan package

**Comment by murali-reddy** [comment]
@blueorangutan test

**Comment by murali-reddy** [comment]
@rhtyd @abhinandanprateek @ustcweizhou  can you please review, we have clean test pass and new test test_router_dhcp_opts passing too.

**Comment by rhtyd** [comment]
@murali-reddy lgtm, can you see why the same test passed again given no change to the PR was made? Do you think this new test could become a source of intermittent failure?

**Comment by murali-reddy** [comment]
@rhtyd it was packaging issue, in failed run my change was not picked

**Comment by rhtyd** [comment]
LGTM. @abhinandanprateek can you review as well?

**Comment by abhinandanprateek** [comment]
@rhtyd reviewing...

**Comment by abhinandanprateek** [comment]
@murali-reddy @rhtyd looks good to me on code review. Marvin test is neat.

**Comment by rhtyd** [comment]
Thanks all for reviewing and testing. I'll merge this now.

**Pull request merged**
