### PR TITLE
4.20.merge

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR...

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@vishesh92 @JoaoJandre @weizhouapache @rohityadavcloud @GutoVeronezi @rp-  @nvazquez @Pearl1594 @bernardodemarco @sureshanaparti @FelipeM525 @RodrigoDLopez @winterhazel 

this is a days worth of merging and fixing test failures. I think it is ok, and usually I just push but in this case I think a bunch of review is in order.

**Review by rp- — APPROVED** [review]
I did only go trough kvm and linstor changes

**Comment by weizhouapache** [comment]
@DaanHoogland 
I think we can merge  (not "Squash and merge") ?

**Comment by DaanHoogland** [comment]
> @DaanHoogland I think we can merge (not "Squash and merge") ?

I am not sure but I think we have to redo once we found all the issues. (already newer merges on 4.20

**Review by bernardodemarco — COMMENTED** [review]
Changes related to #9966, #9759, and #9927 look good. @DaanHoogland, I couldn’t spot the changes for #9949, though.

**Comment by DaanHoogland** [comment]
I will redo this to see if I can do better, if need be there will be some cherry-picking involved...

**Pull request closed without merging**
