### PR TITLE
server: improve storage GC to skip expunging possible duplicate volumes

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Storage GC deletes volumes that are in Destroy state. This PR adds a check in this action that is if two volume records (one in Destroy state and one in Ready state) point to exactly the same disk file then skip doing GC on such Destroy state volume record.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [x] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by rohityadavcloud — APPROVED** [review]
Didn't test this, LGTM - this would need testing (one concern that can be tested if, this doesn't introduce any regression in the GC logic such that valid volumes that must be GC'd and deleted are no longer deleted)

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@blueorangutan LLtest

**Comment by DaanHoogland** [comment]
@blueorangutan LLtest

**Review by DaanHoogland — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
This seems ready to merge, I am just missing some validation and given the description it seems hard to reproduce/test.

**Comment by shwstppr** [comment]
This is just a defensive check and I don't think it would be simple to reproduce. At most, we can test that there is no regression in the GC logic. I've also tried to add multiple unit tests to prevent any unnecessary change in the behaviour

**Pull request merged**
