### PR TITLE
Fix deprecation of CIDR_LIST parameter

### PR DESCRIPTION
**Pull request by onitake**
### Description

This is a follow-up to #4037 .

The CIDR_LIST parameter was only deprecated for CreateIpForwardingRule, CreateLoadBalancerRule and CreatePortForwardingRule. It is still supported for CreateFirewallRule.

This PR documents the deprecation in all these API calls, and reverts the deprecation for CreateFirewallRule.

@weizhouapache 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### How Has This Been Tested?

N/A

### CODE REVIEW

**Comment by weizhouapache** [comment]
@onitake good, thanks for the fix.

@nvazquez code lgtm

**Review by weizhouapache — APPROVED** [review]

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Review by nvazquez — APPROVED** [review]
LGTM

**Pull request merged**
