### PR TITLE
increase width of field in UI

### PR DESCRIPTION
**Pull request by PaulAngus**
## Description

this fixes: https://github.com/apache/cloudstack/issues/3697

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ * ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## Screenshots (if appropriate):
This fixes times when long names are truncated, despite there being much more space available

image

image

### CODE REVIEW

**Comment by PaulAngus** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Did a quick test on Primate, very-very long names are handled like this:
Screenshot from 2019-11-22 01-07-30
Screenshot from 2019-11-22 01-07-38

**Comment by PaulAngus** [comment]
@blueorangutan test

**Comment by PaulAngus** [comment]
after PR fields now look as follows:

image

**Comment by DaanHoogland** [comment]
lgtm,
@rhtyd did you test that in all kinds of browsers in primate? just as a heads up, we saw differences between browsers and even between the same browser on different platforms.

**Comment by DaanHoogland** [comment]
@PaulAngus I don't think oran utang will tell us anything on this one. Do you think we need to do a full walk through of the UI? Only details tables are affected so I think we are fine with your proof above.

**Comment by rhtyd** [comment]
LGTM, we can merge based on the screenshot proofs

**Pull request merged**
