### PR TITLE
veeam: fix issues with PreSetup and DVS and Solidfire

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes some issues when restore veeam backup (including #8939)
- The storage pool uses PreSetup or VMFS
- The backend use DVS, not standard virtual switch
- The storage pool use Solidfire storage

It has been tested

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 vmware-80

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 vmware-80

**Review by rohityadavcloud — APPROVED** [review]
LGTM - I haven't tested it, but I think Wei has tested against a customer solid fire env.

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Comment by sureshanaparti** [comment]
@blueorangutan test rocky8 vmware-80

**Pull request merged**
