### PR TITLE
ui: call logout before login to clear old sessionkey cookies

### LINKED ISSUE #4324: Cannot login after upgrading from 4.14.0.0 to master/4.15-snapshot
Using old/legacy UI I was unable to login due to duplicate sessionkey issue:

The request for initial login:
Screenshot from 2020-09-14 15-23-07

The request made after login is OK but fails due to multiple sessionkey cookies passed (with likely different paths):
Screenshot from 2020-09-14 15-23-22

##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME

~~~
API, UI
~~~

### PR DESCRIPTION
**Pull request by rhtyd**
This handle edge cases of upgrades and when legacy UI is used along with
Primate or any UI sharing cookies. The specific case it fixes involves
removal of duplicate sessionkey cookies.

Fixes #4324 

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

1. Logout and create a fake sessionkey cookie using `$.cookie('sessionkey', '123')`
2. Try to login, login will fail and in the request two sessionkey cookies will be seen passed: 
Screenshot from 2020-09-14 15-23-22

With the fix, when logout is called the API will clear sessionkey cookie (which is httponly so only the backend/server can remove it); and login works. This will cover issues after upgrades and when using legacy UI with Primate:

Screenshot from 2020-09-14 16-25-26

### CODE REVIEW

**Comment by rhtyd** [comment]
Please review - @Pearl1594 @davidjumani @utchoang @andrijapanicsb  @svenvogel and rest. Thnx

**Comment by utchoang** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Sorry @utchoang the blueorangutan package for old UI wont' setup a live demo to test that

**Comment by utchoang** [comment]
@rhtyd OK. I'll run and test on my local. Thnks

**Comment by davidjumani** [comment]
Unable to log in from an upgrade / restart of the management server without clearing cookies
Screenshot from 2020-09-15 14-32-20

**Review by shwstppr — APPROVED** [review]
LGTM

**Review by davidjumani — APPROVED** [review]
LGTM

**Review by utchoang — APPROVED** [review]
LGTM!

**Pull request merged**
