### PR TITLE
UI: Logout before login

### PR DESCRIPTION
**Pull request by nvazquez**
### Description

This PR calls the logout API before login, to cleanup any duplicate sessionkey, as it was done on the legacy UI: https://github.com/apache/cloudstack/pull/4326
Fixes: #6127 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### How Has This Been Tested?

### CODE REVIEW

**Comment by nvazquez** [comment]
@blueorangutan ui

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
The only case worth checking is the SAML based SSO mechanism, not sure if the login method is hit; otherwise LGTM

**Review by utchoang — APPROVED** [review]
LGTM!

**Review by weizhouapache — APPROVED** [review]
code lgtm
I do not know if this fixes #6127

**Pull request merged**
