### PR TITLE
Handle with VM snapshot events

### PR DESCRIPTION
**Pull request by RodrigoDLopez**
## Description

On these days, when a VM snapshot is deleted, the `cloudstack-usage` still seeing that snapshot as active and continues billing this deleted snapshot. This PR proposes new methods to handle with `vm_snapshot_create` and `vm_snapshot_delete` events.   
Also, add some unit tests to cover those new methods.  

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

I don't know why the `cloudstack-usage` duplicate entries for vm_snapshot. I think this is a bug and I'll fix it in a future PR.  
To run tests,  I create a VM snapshot and used the `cloudmonkey` to list usageRecords type=25.  

**Created at 14:12**
```
() 🐱 > list usagerecords startdate=2020-08-08 enddate=2020-08-08 type=25
{
  "count": 2,
  "usagerecord": [
    {
      "account": "admin",
      "description": "VMSnapshot usage Id: 1 (7b63f2f0-61fc-4034-8438-26e8989e3503)  for VM VM-ccb8b3d9-18aa-40c3-8e13-adde2de9b34b (ccb8b3d9-18aa-40c3-8e13-adde2de9b34b)",
      "enddate": "2020-08-08'T'14:13:31+00:00",
      "name": "i-2-5-VM_VS_20200808141157",
      "rawusage": "0.025106",
      "size": 214749184,
      "startdate": "2020-08-08'T'14:12:01+00:00",
      "usage": "0.025106 Hrs",
      "usagetype": 25,
      "virtualmachineid": "ccb8b3d9-18aa-40c3-8e13-adde2de9b34b",
    },
    {
      "account": "admin",
      "description": "VMSnapshot usage Id: 1 (7b63f2f0-61fc-4034-8438-26e8989e3503)  for VM VM-ccb8b3d9-18aa-40c3-8e13-adde2de9b34b (ccb8b3d9-18aa-40c3-8e13-adde2de9b34b)",
      "enddate": "2020-08-08'T'14:13:31+00:00",
      "name": "i-2-5-VM_VS_20200808141157",
      "rawusage": "0.025106",
      "size": 214749184,
      "startdate": "2020-08-08'T'14:12:01+00:00",
      "usage": "0.025106 Hrs",
      "usagetype": 25,
      "virtualmachineid": "ccb8b3d9-18aa-40c3-8e13-adde2de9b34b",
    }
  ]
}
```

**Deleted at 14:18**
```
() 🐱 > list usagerecords startdate=2020-08-08 enddate=2020-08-08 type=25
{
  "count": 4,
  "usagerecord": [
    {
      "account": "admin",
      "description": "VMSnapshot usage Id: 1 (7b63f2f0-61fc-4034-8438-26e8989e3503)  for VM VM-ccb8b3d9-18aa-40c3-8e13-adde2de9b34b (ccb8b3d9-18aa-40c3-8e13-adde2de9b34b)",
      "enddate": "2020-08-08'T'14:13:31+00:00",
      "name": "i-2-5-VM_VS_20200808141157",
      "rawusage": "0.025106",
      "size": 214749184,
      "startdate": "2020-08-08'T'14:12:01+00:00",
      "usage": "0.025106 Hrs",
      "usagetype": 25,
      "virtualmachineid": "ccb8b3d9-18aa-40c3-8e13-adde2de9b34b",
    },
    {
      "account": "admin",
      "description": "VMSnapshot usage Id: 1 (7b63f2f0-61fc-4034-8438-26e8989e3503)  for VM VM-ccb8b3d9-18aa-40c3-8e13-adde2de9b34b (ccb8b3d9-18aa-40c3-8e13-adde2de9b34b)",
      "enddate": "2020-08-08'T'14:13:31+00:00",
      "name": "i-2-5-VM_VS_20200808141157",
      "rawusage": "0.025106",
      "size": 214749184,
      "startdate": "2020-08-08'T'14:12:01+00:00",
      "usage": "0.025106 Hrs",
      "usagetype": 25,
      "virtualmachineid": "ccb8b3d9-18aa-40c3-8e13-adde2de9b34b",
    },
    {
      "account": "admin",
      "description": "VMSnapshot usage Id: 1 (7b63f2f0-61fc-4034-8438-26e8989e3503)  for VM VM-ccb8b3d9-18aa-40c3-8e13-adde2de9b34b (ccb8b3d9-18aa-40c3-8e13-adde2de9b34b)",
      "enddate": "2020-08-08'T'14:18:31+00:00",
      "name": "i-2-5-VM_VS_20200808141157",
      "rawusage": "0.083337",
      "size": 214749184,
      "startdate": "2020-08-08'T'14:13:31+00:00",
      "usage": "0.083337 Hrs",
      "usagetype": 25,
      "virtualmachineid": "ccb8b3d9-18aa-40c3-8e13-adde2de9b34b",
    },
    {
      "account": "admin",
      "description": "VMSnapshot usage Id: 1 (7b63f2f0-61fc-4034-8438-26e8989e3503)  for VM VM-ccb8b3d9-18aa-40c3-8e13-adde2de9b34b (ccb8b3d9-18aa-40c3-8e13-adde2de9b34b)",
      "enddate": "2020-08-08'T'14:18:31+00:00",
      "name": "i-2-5-VM_VS_20200808141157",
      "rawusage": "0.083337",
      "size": 214749184,
      "startdate": "2020-08-08'T'14:13:31+00:00",
      "usage": "0.083337 Hrs",
      "usagetype": 25,
      "virtualmachineid": "ccb8b3d9-18aa-40c3-8e13-adde2de9b34b",
    }
  ]
}
```

### CODE REVIEW

**Comment by RodrigoDLopez** [comment]
@blueorangutan package

**Comment by RodrigoDLopez** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Review by rhtyd — APPROVED** [review]
LGTM, did not test it; travis tests LGTM

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan test

**Review by DaanHoogland — APPROVED** [review]
code looks good but the double records are kind of a problem, does this happen in the old/current implementation as well?

**Comment by DaanHoogland** [comment]
> I don't know why the cloudstack-usage duplicate entries for vm_snapshot. I think this is a bug and I'll fix it in a future PR.
Did you create an issue yet? please do so before merging. maybe these double records should be mentioned in release notes as well (cc @PaulAngus )

**Comment by RodrigoDLopez** [comment]
Hi @DaanHoogland 
I saw this bug when I was fixing other issues in the 4.13.1.0 version. On this version, we can see duplicates records for `vm_snapshot`, I did not test this on `master`, but I saw the code. The duplicate records will occur on `master` as well.

As you requested, I will open an issue to report these duplicate records for `vm_snapshot` on `cloud-usage`

**Review by GabrielBrascher — APPROVED** [review]
Code LGTM

**Comment by rhtyd** [comment]
@nvazquez can you review this? thanks.

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Pull request merged**
