### PR TITLE
[CS45] Add missing localization for some labels in Web UI

### PR DESCRIPTION
**Pull request by milamberspace**
- on the zone configuration wizard for the "Next" button
- on templates, Shared, extratable and Dynamically Scalable
- Improve some French translations ("Téléverser" for "Upload")
- update French messages properties from transifex (4.5 branch)

### CODE REVIEW

**Comment by DaanHoogland** [comment]
travis timeout
LGTM

**Comment by bhaisaab** [comment]
LGTM.

**Comment by bhaisaab** [comment]
@milamberspace thanks, merged on 4.5; since this is a non-master branch you'll have to close the PR manually. Also, do we want to port this to master?

**Comment by DaanHoogland** [comment]
@bhaisaab if you merge, preserving the commit-ids github will close this PR regardless of the branch it was merged to.

**Comment by bhaisaab** [comment]
@DaanHoogland cool, will try that in future

**Comment by milamberspace** [comment]
@bhaisaab Thanks for LGTM (Daan too)

The PR for fix the master is here: (#686)
https://github.com/apache/cloudstack/pull/686
Need a second LGTM too

**Comment by remibergsma** [comment]
@bhaisaab Wrote a script to handle the merge and made it compatible with your 'git pr' workflow. 

See https://github.com/schubergphilis/cloudstack-git-tree-manipulation/blob/master/git-pr
Put 'git-pr' script in $PATH (and disable/rename your 'pr' alias). I'm finalising the script based on feedback I got and will send a PR soon to add it to ACS repo. 
Docs are being written here: https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61311655

Let me know if it makes sense.

**Comment by remibergsma** [comment]
@milamberspace Could you please close this PR as @bhaisaab applied the patch to 4.5. Thanks!

**Pull request closed without merging**
