### PR TITLE
Handle public IP race conditions

### PR DESCRIPTION
**Pull request by hsato03**
### Description

When executing many operations simultaneously with a public IP, some inconsistencies are being implemented in the environment, such as the duplicate public IP (Fixes: #8967).

For this reason, this PR adds a lock to most APIs that manipulate a public IP, preventing inconsistencies that may occur due to race conditions.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [X] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

All tests were done following the same steps but using different APIs that create rules for the IP (`createLoadBalancerRule`, `createFirewallRule`, `createPortForwardingRule`, `createIpForwardingRule`):

1. Associate a public IP with a network;
2. Create a rule with one of the APIs;
3. Disassociate the IP (before) and create a rule again (after) at the same time.

To test the `createRemoteAccessVpn` API, I created a firewall rule in step 2 and called the `createRemoteAccessVpn` API in step 3.

**Before**: The `disassociateIpAddress` API threw an exception and still disassociated the IP from the VR. The APIs that kept the IP in the VR even after disassociation were `createLoadBalancerRule` and `createRemoteAccessVpn`.

**Now**: All APIs that create rules for the IP wait for the `disassociateIpAddress` API to finish executing and only then begin execution, meaning that the exception is now thrown when creating the rule and no longer when disassociating the IP. No API held the IP in the VR.

The tests were made in high and low performance environments. The low performance environments were more susceptible to race conditions due to the time it takes to process a request.

### CODE REVIEW

**Comment by GutoVeronezi** [comment]
@weizhouapache, could you take a look at this one?

**Comment by weizhouapache** [comment]
> @weizhouapache, could you take a look at this one?

Will do

@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
codewise looks good.
need some manual testing (for instance, run the scripts for 12 hours).

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Review by weizhouapache — APPROVED** [review]
codewise lgtm

not tested

**Comment by rohityadavcloud** [comment]
@blueorangutan test ol8 kvm-ol8

**Comment by sureshanaparti** [comment]
@blueorangutan test alma9 kvm-alma8

**Comment by sureshanaparti** [comment]
Hi @hsato03 Can you check & fix the NPEs mentioned here: https://github.com/apache/cloudstack/issues/8967#issuecomment-2195025830

**Comment by hsato03** [comment]
@blueorangutan package

**Pull request merged**
