### PR TITLE
Fixup listing of serivce offering & storagepools with tags

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR fixes listing of service offering & stroagepools with tags.

1. Add 2 tags to a storage pool. The list operation fails.
2. List services offerings for a VM with service offering tags.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan package

**Review by sureshanaparti — APPROVED** [review]
code lgtm

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test keepEnv

**Review by borisstoyanov — APPROVED** [review]
LGTM, manually tested the api, it considers tags when listing the suitable offerings

**Pull request merged**
