### PR TITLE
server: apply network ACL even if there is no network ACLs rules in the ACL list

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes an issue with network ACL

- create a new ACL list (without any rule) in a VPC
- check current iptables rules in VPC VR
- replace VPC tier with the new ACL list

expected:
- the iptables rules are replaced (to same rules as `default_deny`)

actual:
- the iptables rules are not changed.
- in management-server.log, it shows
```
DEBUG [c.c.n.v.NetworkACLManagerImpl]  Applying NetworkACL for network: 517 with Network ACL service provider
DEBUG [o.a.c.n.t.BasicNetworkTopology] No network ACLs to be applied for network 517

```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Comment by DaanHoogland** [comment]
@weizhouapache there are unit test failures: https://github.com/apache/cloudstack/actions/runs/9893593560/job/27359418049?pr=9374#step:7:9300 can you have a look?

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Review by rohityadavcloud — APPROVED** [review]

**Review by kiranchavala — APPROVED** [review]
LGTM

1. Create a vpc network
2. Create a tier with default_deny acl rule
3. create a new acl rule with no rules
4. Replace the acl rule for the tier with the acl rule created in step 3 

Before fix 
```

2024-09-24T05:59:27,953 DEBUG [c.c.n.v.NetworkACLManagerImpl] (API-Job-Executor-36:[ctx-89b40bfe, job-46, ctx-65267911]) (logid:948cbd28) New network ACL is empty. Revoke existing rules before applying ACL
2024-09-24T05:59:27,957 DEBUG [c.c.n.v.NetworkACLManagerImpl] (API-Job-Executor-36:[ctx-89b40bfe, job-46, ctx-65267911]) (logid:948cbd28) Updated network: 205 with Network ACL Id: 4, Applying ACL items
2024-09-24T05:59:27,963 DEBUG [c.c.n.v.NetworkACLManagerImpl] (API-Job-Executor-36:[ctx-89b40bfe, job-46, ctx-65267911]) (logid:948cbd28) Applying NetworkACL for network: 205 with Network ACL service provider
2024-09-24T05:59:27,974 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-36:[ctx-89b40bfe, job-46, ctx-65267911]) (logid:948cbd28) Complete async job-46, jobStatus: SUCCEEDED, resultCode: 0, result: org.apache.cloudstack.api.response.SuccessResponse/null/{"success":"true"}
```




After fix 

```
2024-09-24 05:53:06,552 DEBUG [c.c.n.v.NetworkACLManagerImpl] (API-Job-Executor-29:ctx-77843697 job-36 ctx-87af95cc) (logid:c829616e) New network ACL is empty. Revoke existing rules before applying ACL
2024-09-24 05:53:06,562 DEBUG [c.c.n.v.NetworkACLManagerImpl] (API-Job-Executor-29:ctx-77843697 job-36 ctx-87af95cc) (logid:c829616e) Releasing 2 Network ACL Items for network id=204
2024-09-24 05:53:06,564 DEBUG [c.c.n.v.NetworkACLManagerImpl] (API-Job-Executor-29:ctx-77843697 job-36 ctx-87af95cc) (logid:c829616e) Applying NetworkACL for network: 204 with Network ACL service provider
2024-09-24 05:53:06,586 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-29:ctx-77843697 job-36 ctx-87af95cc) (logid:c829616e) Complete async job-36, jobStatus: SUCCEEDED, resultCode: 0, result: org.apache.cloudstack.api.response.SuccessResponse/null/{"success":"true"}
```

**Pull request merged**
