### PR TITLE
CLOUDSTACK-9584: run component tests in Travis run

### PR DESCRIPTION
**Pull request by rhtyd**
This would run additional component tests in Travis run.

### CODE REVIEW

**Comment by rhtyd** [comment]
@abhinandanprateek @murali-reddy @jburwell @serg38 @nvazquez @syed @koushik-das @karuturi @milamberspace @wido @JayapalUradi @K0zka @rafaelweingartner @yvsubhash -- ping, please help review this.
This will add some existing (800+ test cases) component tests to Travis run, with aim to (1) finish each Travis sub-job within 45 mins, (2) run RAT related checks and build with `-Dnoredist` in the first job.

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by abhinandanprateek** [comment]
LGTM on code review @rhtyd

**Comment by rhtyd** [comment]
@borisstoyanov thanks, but a Trillian test is not necessary as all changes are related to Travis. Since Travis is green, I'll need a couple of some lgtms to proceed with merging this.

**Comment by borisstoyanov** [comment]
yes, you have a point @rhtyd, but I've kicked it since I noticed there were some changes in the ../integration/smoke/ as well.. I thought it's worth confirming that smoketest is running ok with Trillian as well.

**Comment by rhtyd** [comment]
@borisstoyanov okay, though changes in smoketests have been confirmed by Travis test results as well.

**Comment by borisstoyanov** [comment]
yes @rhtyd , I'll cancel the run to free resources in the Lab.
LGTM on code review and Travis results

**Comment by rhtyd** [comment]
Thanks @borisstoyanov I'll proceed with merging this as Travis is all green now.

**Pull request merged**
