### PR TITLE
Debian10 support

### LINKED ISSUE #3654: Remote VPN not working if site-to-site VPN exists
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VPN
~~~

##### CLOUDSTACK VERSION

~~~
4.11.x
4.13.x
~~~

##### CONFIGURATION

Site-to-site VPN enabled.
Remote VPN configured

##### OS / ENVIRONMENT

N/A

##### SUMMARY

When both site-to-site VPN and the Remote VPN are configured/enabled - Remote VPN will not work. When site-to-site VPN is removed, Remote VPN will start functioning again fine.

##### WORK AROUND

~~~
Create a SVM in VirtualBox and login as root.
Comment all repositories in /etc/apt/sources.list and add buster repository. The buster is the debian stable release.

> vim.tiny /etc/apt/sources.list
`deb http://http.debian.net/debian buster main`

Run apt update and install the newest strongswan:
`apt update`
`apt install libcharon-extra-plugins libstrongswan libstrongswan-extra-plugins strongswan strongswan-charon strongswan-libcharon strongswan-starter`

Shutdown the VM in VirtualBox and upload a new SVM template into ACS.
~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

### PR DESCRIPTION
**Pull request by rhtyd**
This upgrades the systemvmtemplate base to Debian 10 with openjdk-11.
Fixes #3654

Prev. https://github.com/apache/cloudstack/pull/3797

Public location: (testing purposes, until GA)
http://download.cloudstack.org/systemvm/4.15/

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@rhtyd can you incorporate teh change in #3921 in this one?

**Comment by rhtyd** [comment]
@Spaceman1984 can you merge/push your PR commits (or patch https://patch-diff.githubusercontent.com/raw/apache/cloudstack/pull/3921.patch) to this branch?

**Comment by rhtyd** [comment]
Looks like testing with kvm passed, we'll need to kick tests against other hypervisors manually from Trillian.
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Kicked matrix smoketests on jenkins by overriding the built systemvmtemplates

**Comment by rhtyd** [comment]
The systemvmtemplate build log: http://download.cloudstack.org/systemvm/4.15/build.log
Public URL for dev-testing until GA: http://download.cloudstack.org/systemvm/4.15/

**Comment by weizhouapache** [comment]
@rhtyd I have two concerns
(1) does Trillian use new debian10 template in tests ?
(2) is python2 or python3 installed in debian10 ?

**Comment by rhtyd** [comment]
Hi @weizhouapache 
- Trillian by default uses branch/version specific systevmtemplates, but allows option to override. For testing this PR, I'm not using BO but passing systemvmtemplate overide on our internal Jenkins. This gives us ability to test a PR with a new systemvmtemplate.
- Currently, no python3 is not installed in this PR. Are you/anyone-else working to migrate VR scripts from py2 to py3, then I can make changes in this PR to install python3 (make the template future ready).

**Comment by weizhouapache** [comment]
> Hi @weizhouapache
> 
> * Trillian by default uses branch/version specific systevmtemplates, but allows option to override. For testing this PR, I'm not using BO but passing systemvmtemplate overide on our internal Jenkins. This gives us ability to test a PR with a new systemvmtemplate.
> * Currently, no python3 is not installed in this PR. Are you/anyone-else working to migrate VR scripts from py2 to py3, then I can make changes in this PR to install python3 (make the template future ready).

@rhtyd nice, thanks.
let's merge it, and upgrade to python3 in systemvm template along with python2->python3 support (it seems to be part of centos8 support).

**Comment by rhtyd** [comment]
@weizhouapache 
- I checked python3 was already installed on the built systemvmtemplate, but I've added explicit pkg to be installed
- python2->3 migration is not done in the centos8 support PR; the systemvm continue to be on Debian where python2 ships by default (with the python package)

**Comment by weizhouapache** [comment]
code lgtm
did not test it

**Comment by rhtyd** [comment]
Checked test failures not related to this PR on XenServer, overall all tests have passed.

**Pull request merged**
