### PR TITLE
Fix upload volume format

### PR DESCRIPTION
**Pull request by nvazquez**
### Description

This PR fixes an issue if format is not properly passed in uppercase.

Note: this issue is applicable only to API when format value is lowercase, UI passes the format in uppercase to the uploadVolume API

````
2022-04-21 19:48:57,569 ERROR [c.c.a.ApiAsyncJobDispatcher] (API-Job-Executor-23:ctx-319bdf84 job-425147) (logid:864904bb) Unexpected exception while executing org.apache.cloudstack.api.command.admin.volume.UploadVolumeCmdByAdmin
java.lang.IllegalArgumentException: No enum constant com.cloud.storage.Storage.ImageFormat.ova
	at java.base/java.lang.Enum.valueOf(Enum.java:240)
	at com.cloud.storage.Storage$ImageFormat.valueOf(Storage.java:25)
	at com.cloud.storage.VolumeApiServiceImpl$2.doInTransaction(VolumeApiServiceImpl.java:559)
	at com.cloud.storage.VolumeApiServiceImpl$2.doInTransaction(VolumeApiServiceImpl.java:523)
	at com.cloud.utils.db.Transaction.execute(Transaction.java:40)
	at com.cloud.storage.VolumeApiServiceImpl.persistVolume(VolumeApiServiceImpl.java:523)
	at com.cloud.storage.VolumeApiServiceImpl.uploadVolume(VolumeApiServiceImpl.java:345)
	at com.cloud.storage.VolumeApiServiceImpl.uploadVolume(VolumeApiServiceImpl.java:203)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
````

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by nvazquez** [comment]
@blueorangutan package

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by nvazquez** [comment]
@blueorangutan test

**Review by Pearl1594 — APPROVED** [review]
LGTM

**Comment by weizhouapache** [comment]
@blueorangutan test

**Pull request merged**
