### PR TITLE
UI: support serviceofferingid when create vpc offering

### LINKED ISSUE #7042: Creating VPC offering: unable to choose compute or network offering
##### ISSUE TYPE

 * Bug Report

##### CLOUDSTACK VERSION

~~~
4.17.1 4.17.2
~~~

##### OS / ENVIRONMENT

OracleLinux 8

##### SUMMARY

I want to create VPC Oferring linked with new network and system offering. The reason is that I need VPC network with specific storage and host tags.
But on VPC creation page I don't see any offering suggestions despite I created system offering and linked network offering with VPC toggle.

##### STEPS TO REPRODUCE

~~~
1. Open Network offering
2. Create new network offering with VPC toggle
3. Open VPC offering
4. Try to add offering with  earlier created  network offering
~~~

##### EXPECTED RESULTS

~~~
Possibility choose compute (network) offering
~~~

##### ACTUAL RESULTS

~~~
There is no any compute (network) offering suggestion.
~~~
image

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #7042 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):

no supported services

image

"SourceNat" is checked

image### How Has This Been Tested?

### CODE REVIEW

**Review by stephankruggg — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
@weizhouapache is this root-admin only, or for anybody?

**Comment by weizhouapache** [comment]
> @weizhouapache is this root-admin only, or for anybody?

@rohityadavcloud 
this is root-admin only.

non-root users can only create service and disk offerings. 
they cannot create system offering, network offering and vpc offering

**Review by DaanHoogland — APPROVED** [review]
clgtm and tested in QA env

**Comment by DensonNgumo** [comment]
Experienced a similar UI bug where I am unable to select a Network Offering. This is on the latest 4.19.0.1
cloudstack_network

**Comment by DaanHoogland** [comment]
@DensonNgumo can you create a new issue with reproduction scensario?

**Pull request merged**
