### PR TITLE
JRE17 Migration Investigation

### PR DESCRIPTION
**Pull request by rohityadavcloud**
This PR is to investigate if CloudStack can be used against JRE17 (LTS) as JRE11 reached EOL.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [x] build/CI

#### Feature/Enhancement Scale

- [x] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan test ol8 kvm-ol8

**Comment by vishesh92** [comment]
@blueorangutan test ol8 kvm-alma9

**Comment by vishesh92** [comment]
@blueorangutan test alma9 kvm-alma9

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan test alma9 kvm-alma9

**Comment by vishesh92** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan test alma8 kvm-alma8

**Comment by vishesh92** [comment]
@blueorangutan test alma8 kvm-alma8

**Comment by vishesh92** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Comment by vishesh92** [comment]
@blueorangutan test alma8 kvm-alma8 keepEnv

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
> [SF] Trillian test result (tid-8775) Environment: kvm-alma8 (x2), Advanced Networking with Mgmt server a8 Total time taken: 48733 seconds Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr8438-t8775-kvm-alma8.zip Smoke tests completed. 119 look OK, 2 have errors, 0 did not run Only failed and skipped tests results shown below:
> Test 	Result 	Time (s) 	Test File
> test_02_upload_direct_download_certificates 	`Failure` 	0.03 	test_direct_download.py
> test_01_migrate_VM_and_root_volume 	`Error` 	85.08 	test_vm_life_cycle.py
> test_02_migrate_VM_with_two_data_disks 	`Error` 	51.63 	test_vm_life_cycle.py
> test_08_migrate_vm 	`Error` 	46.00 	test_vm_life_cycle.py

Failing tests in `test_vm_life_cycle` passed when I ran them manually against the same environment. 
Tested `test_02_upload_direct_download_certificates` after the last commit manually and tests passed.

**Comment by vishesh92** [comment]
@blueorangutan test rocky8 kvm-rocky8 keepEnv

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 vmware-70u3

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan test alma9 kvm-alma9

**Comment by vishesh92** [comment]
@blueorangutan test rocky8 vmware-70u3

**Comment by vishesh92** [comment]
@blueorangutan test ubuntu22 xenserver-71

**Review by weizhouapache — APPROVED** [review]
code lgtm

Great job @vishesh92

**Review by DaanHoogland — APPROVED** [review]

**Comment by weizhouapache** [comment]
with this PR, the java version will be forcely upgraded to 17 on mgmt servers and kvm hosts.
is there any side effect caused by it ?
cc @rohityadavcloud @vishesh92 @DaanHoogland 

(centos7 will not be supported any more, it is good)

**Comment by DaanHoogland** [comment]
> with this PR, the java version will be forcely upgraded to 17 on mgmt servers and kvm hosts. is there any side effect caused by it ? cc @rohityadavcloud @vishesh92 @DaanHoogland

haven't seen any yet, but I am sure we will encounter some.

> (centos7 will not be supported any more, it is good)

yes, that is one for the v20 release notes (cc @JoaoJandre )

**Review by rohityadavcloud — COMMENTED** [review]
LGTM thanks @vishesh92 for taking this forward - having CloudStack work with JRE17 is a great first step before we move the codebase to work with JDK17.

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
Closing this PR as changes/commits of this PR are included in https://github.com/apache/cloudstack/pull/8497/commits
cc @vishesh92 @weizhouapache @borisstoyanov - would make review and QA easier if #8497 is tested that includes the JRE17 support.

**Pull request closed without merging**
