### PR TITLE
CLOUDSTACK-8577: fixing script  testpath_disable_enable_zone

### PR DESCRIPTION
**Pull request by nitt10prashant**
disable enable cluster ... === TestName: test_01_disable_enable_cluster | Status : SUCCESS ===
ok
disable enable host ... === TestName: test_01_disable_enable_host | Status : SUCCESS ===
ok
disable enable Pod ... === TestName: test_01_disable_enable_pod | Status : SUCCESS ===
ok
disable enable zone ... === TestName: test_01_disable_enable_zone | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 4 tests in 2818.119s

OK

### CODE REVIEW

**Comment by wilderrodrigues** [comment]
@DaanHoogland @runseb @bhaisaab @remibergsma 

Does the LGTM idea also apply to integration tests?

Cheers,
Wilder

**Comment by DaanHoogland** [comment]
I have let Gaurav take care of things before because he was the only one actually looking. I don't think we can afford to demand 2 LTGM on integration tests. I would like to.

**Comment by wilderrodrigues** [comment]
Fair enough. I'm just asking because it should be made clear on the list.

It's already difficult to get 2 LGTM on the Java stuff, not many people looking into things. There are also a lot of PRs standing due to lack of information from the committer. 

How should we address that?

**Comment by DaanHoogland** [comment]
first let us not limmit the LTGM to commiters in the case of integration tests. As for information, we will have to ask for it. Finally I want for us to have a mech to refuse/close PRs as community. We can't at the moment. I don't even know who can.

**Pull request closed without merging**
