### PR TITLE
ui: show only advanced zones for vmautoscale form

### LINKED ISSUE #7409: Display Only the Advanced Zones when creating a "AutoScale Vm groups".
##### ISSUE TYPE

Bug Report

##### COMPONENT NAME

component:UI

##### SUMMARY

Display Only the Advanced Zones when creating a "AutoScale Vm groups".

Currently, the autoscaling feature is only supported in Advanced zone as it requires LB support and only isolated network and vpc support LB.

The admin user should not be able to create an Autoscale vm Group in a basic zone.

We can add a filter to show any Advance/Core zones

-------------
Steps to reproduce the issue

1. Create a basic zone  

2. Create a autoscale vm group 

Compute > Autoscale vm group > New Autoscale Vm group

[Screencast from 06-04-23 02:34:29 PM IST.webm](https://user-images.githubusercontent.com/1401014/230331272-40e55544-3371-4cca-9802-2815fd720a76.webm)

##### EXPECTED RESULTS

The admin user should not be able to create a Autoscale vm Group in a basic zone.

##### ACTUAL RESULTS

The admin user is having the option to  create a Autoscale vm Group in a basic zone.

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #7409

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by weizhouapache** [comment]
@shwstppr 
My suggestions are
- display this section only if there is at least one advanced zone
 
image

- In the AS vmgroup creation wizard, list only the Advanced zones
(securitygroupenabled = false)

**Comment by shwstppr** [comment]
@weizhouapache conditional displaying of the section would be tricky. Even if implemented it may delay UI loading while it lists zones.
Will add change in the wizard

**Review by kiranchavala — APPROVED** [review]
LGTM

**Review by rohityadavcloud — APPROVED** [review]

**Pull request merged**
