### PR TITLE
 volume: fix volume metrics view from returning sensitive info to end user

### PR DESCRIPTION
**Pull request by dhlaluku**
## Description

Problem: The listVolumeMetrics API response does not honor the volume detail visibility restrictions set for normal users and returns sensitive information which should only be visible to the root admin.

Root Cause: The listVolumeMetrics API response extends the ListVolumesByAdmin API internally and this results in a full display view response that is only meant for the root admin.

Solution: This has been fixed by rectifying the API response to not show ‘physical size’, 'storage type', and ‘storage pool’ information. The UI has also been fixed to hide these columns for normal users.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## Screenshots (if appropriate):
User metrics view from the UI with  physical size, storage type, and storage pool details hideen
image

Admin Response contains the full display view/results
image

### CODE REVIEW

**Comment by dhlaluku** [comment]
@rhtyd please add appropriate labels for this PR

@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
just in case someone needs to play with this:
@blueorangutan package

**Comment by DaanHoogland** [comment]
@rhtyd I saw more PRs on this subject. Is this still relevant? LGTM

**Comment by rhtyd** [comment]
Yes this is relevant @DaanHoogland thanks.
@blueorangutan test centos7 vmware-65u2

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-65u2

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-65u2

**Comment by anuragaw** [comment]
@blueorangutan package

**Comment by anuragaw** [comment]
Rebased to remove merge conflicts @rhtyd , @shwstppr , @borisstoyanov

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Pull request merged**
