### PR TITLE
VR: fix site-2-site VPN if split connections is enabled

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes the issue that s2s vpn cannot be applied if split-connections is enabled

the issue is because `count` is a build-in method in python3 , `len` should be used instead.
```
>>> aa=[]
>>> aa.count
<built-in method count of list object at 0x76e292158b40>
>>> len(aa)
0
```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by andrijapanicsb** [comment]
@blueorangutan package

**Comment by andrijapanicsb** [comment]
@blueorangutan test

**Review by vishesh92 — APPROVED** [review]
clgtm. didn't test.

**Comment by DaanHoogland** [comment]
tested in lab env, both active and passive versions get created

**Comment by weizhouapache** [comment]
@blueorangutan test

**Pull request merged**
