### PR TITLE
User friendly name of Downloaded Templates Volumes and ISOs

### PR DESCRIPTION
**Pull request by harikrishna-patnala**
### Description

This PR addresses the improvement #6949 

Previously when a template or volume or ISO is downloaded then the file name generated for the downloaded file is a random URL, with this PR we have improved to use the name of the object to set as the file name.

During the preparation of URL, MS uses only alphanumeric characters and replaces others with Hyphen (-).

For example 

image

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

### How Has This Been Tested?

Downloaded multiple templates, volumes with various names.

### CODE REVIEW

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Review by sureshanaparti — APPROVED** [review]
code lgtm

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Review by rohityadavcloud — APPROVED** [review]
LGTM - wondering if it can have any side effects? For example, we used randomised object names, so they can't be guessed by anyone.

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Comment by harikrishna-patnala** [comment]
@DaanHoogland I've updated the PR which adds the UUID in the path

image

Please review

**Review by DaanHoogland — APPROVED** [review]
reviewed and tested in a lab env

**Pull request merged**
