### PR TITLE
Add api arg validator for create project api (#3097)

### PR DESCRIPTION
**Pull request by anuragaw**
## Description

Create project command should have an Apiarg validator.

Fixes: #3097 

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

When create project is called with empty name or displaytext or both the call fails as it should.

### CODE REVIEW

**Comment by anuragaw** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by anuragaw** [comment]
@rhtyd - does this also need to go into 4.11? The current PR is against master.

**Comment by rhtyd** [comment]
You call @anuragaw, I did not stress as it is not a major bug. Generally it's good to send bugfix PRs towards the on-going LTS branch.

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by anuragaw** [comment]
Sounds good. I think it's not as critical and reasonable to push only to master

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Pull request merged**
