### PR TITLE
packaging: bundle cmk in cloudstack-management package

### PR DESCRIPTION
**Pull request by rohityadavcloud**
This bundles latest cmk release in cloudstack-management package, so admins won't need to install it for typical first-install use.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

### CODE REVIEW

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@rohityadavcloud how can we install a management server without cmk? or is it the intention that this is no longer possible?

**Comment by rohityadavcloud** [comment]
@DaanHoogland sorry, I don't understand your question. The PR intends to bundle cmk with the cloudstack-management pkg.

**Comment by weizhouapache** [comment]
> @rohityadavcloud how can we install a management server without cmk? or is it the intention that this is no longer possible?

with this change, cmk will always be installed on mgmt server.
is there any user dislike installing cmk on mgmt server ? I do not see any issue of it.

**Review by weizhouapache — APPROVED** [review]
code lgtm

`/usr/bin/cmk` will be overwritted if it already exists, right ?

**Comment by rohityadavcloud** [comment]
@weizhouapache unfortunately if /usr/bin/cmk exists then yes, it will be overwritten by cloudstack-management pkg provided CLI. If you'd prefer, I can create a new rpm/deb pkg called cloudstack-cli  that bundles/installs cmk ?

**Comment by weizhouapache** [comment]
> @weizhouapache unfortunately if /usr/bin/cmk exists then yes, it will be overwritten by cloudstack-management pkg provided CLI. If you'd prefer, I can create a new rpm/deb pkg called cloudstack-cli that bundles/installs cmk ?

@rohityadavcloud 
I just wanted to confirm it.
I think it is not needed. no problem to overwrite the existing cmk.

**Comment by DaanHoogland** [comment]
well, not a :-1: but I think it should be installed separately.

**Comment by weizhouapache** [comment]
> well, not a 👎 but I think it should be installed separately.

currently it is.
```
wget https:///xxxxx -O /usr/bin/cmk
chmod +x /usr/bin/cmk
```

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Review by kiranchavala — APPROVED** [review]
Tested with OL8 and Ubuntu22

The cmk package is installed under /usr/bin/cmk and the tool is working fine

```
Loaded in-built API cache. Failed to read API cache, please run 'sync'.
Apache CloudStack 🐵 CloudMonkey 6.3.0
Report issues: https://github.com/apache/cloudstack-cloudmonkey/issues

(localcloud) 🐱 > list zones
{
  "count": 1,
  "zone": [
    {
      "allocationstate": "Enabled",
      "allowuserspecifyvrmtu": false,
      "dhcpprovider": "VirtualRouter",
      "dns1": "10.0.32.1",
      "dns2": "8.8.8.8",
      "guestcidraddress": "10.1.1.0/24",
      "hasannotations": false,
      "id": "7f08660c-443c-4351-88c4-611d44961bc6",
      "internaldns1": "10.0.32.1",
      "internaldns2": "8.8.4.4",
      "localstorageenabled": false,
      "name": "ref-trl-6320-k-Mu22-kiran-chavala",
      "networktype": "Advanced",
      "routerprivateinterfacemaxmtu": 1500,
      "routerpublicinterfacemaxmtu": 1500,
      "securitygroupsenabled": false,
      "tags": [],
      "type": "Core",
      "zonetoken": "037b5229-490e-3dd9-9343-58e1c1088699"
    }
  ]
}
(l
```

**Comment by weizhouapache** [comment]
merging based on approvals and manua testing

**Pull request merged**
