### PR TITLE
server: do not check zone imagestores for directdownload template delete

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

This PR fixes the error while deleting a direct-download template when there is no secondary storage added (probably only in Edge zones).

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@weizhouapache cc @DaanHoogland this can be included in 4.18.1 milestone. I wrongly targetted it to `main` branch previously

**Comment by weizhouapache** [comment]
> @weizhouapache cc @DaanHoogland this can be included in 4.18.1 milestone. I wrongly targetted it to `main` branch previously

thanks @shwstppr 
moved to 4.18.1.0 milestone

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@blueorangutan test keepEnv

**Comment by DaanHoogland** [comment]
tested this:

- registered two templates, one direct download and one downloaded
- disabled the zone
- removed the secondary storage
- enabled the zone
- tried to delete the downloaded template, this failed (PASS)
- tried to the delete the direct download template, this succeeded (PASS)

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by rohityadavcloud — APPROVED** [review]
Changes LGTM didn't test it

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Pull request merged**
