### PR TITLE
CLOUDSTACK-8658: make initializer static instead of default

### PR DESCRIPTION
**Pull request by DaanHoogland**
bad bug: ommision of the static keyword on initializer leaves data uninitialized :{

### CODE REVIEW

**Comment by wilderrodrigues** [comment]
Hey @DaanHoogland 

Could you write a test for that, please? :)

Cheers,
Wilder

**Comment by DaanHoogland** [comment]
@wilderrodrigues of course, sure you want to wait for that?
And to what extend? we want tests for this initializer but also for the agent and it's functioning

**Comment by wilderrodrigues** [comment]
Hey @DaanHoogland 

Just the initialiser stuff and the return of the getPreferredCharset() method.

Cheers,
Wilder

**Comment by bhaisaab** [comment]
LGTM

**Comment by wilderrodrigues** [comment]
Will test it against KVM + Agent.

**Comment by wilderrodrigues** [comment]
Keys are being created:

[root@kvm1 ~]# ls -lart ~/.ssh/
total 16
dr-xr-x---. 3 root root 4096 Jul 22 02:37 ..
drwx------. 2 root root 4096 Jul 22 02:42 .
-rw-r--r--. 1 root root  389 Jul 22 02:42 id_rsa.pub.cloud
-rw-------. 1 root root 1678 Jul 22 02:42 id_rsa.cloud
[root@kvm1 ~]# 

I will now run some basic tests: vm_life_cycle

**Comment by wilderrodrigues** [comment]
LGTM :+1:  merging...

Thanks, @DaanHoogland !!!

Tested with:

KVM + Qemu on Centos7
Management Server on Centos7
Agent 4.6.0 (I built myself)
SystemVM 4.6.0 (latest from jenkins.bac.o

Test advanced zone virtual router ... === TestName: test_advZoneVirtualRouter | Status : SUCCESS ===
ok
Test Deploy Virtual Machine ... === TestName: test_deploy_vm | Status : SUCCESS ===
ok
Test Multiple Deploy Virtual Machine ... === TestName: test_deploy_vm_multiple | Status : SUCCESS ===
ok
Test Stop Virtual Machine ... === TestName: test_01_stop_vm | Status : SUCCESS ===
ok
Test Start Virtual Machine ... === TestName: test_02_start_vm | Status : SUCCESS ===
ok
Test Reboot Virtual Machine ... === TestName: test_03_reboot_vm | Status : SUCCESS ===
ok
Test destroy Virtual Machine ... === TestName: test_06_destroy_vm | Status : SUCCESS ===
ok
Test recover Virtual Machine ... === TestName: test_07_restore_vm | Status : SUCCESS ===
ok
Test migrate VM ... SKIP: At least two hosts should be present in the zone for migration
Test destroy(expunge) Virtual Machine ... === TestName: test_09_expunge_vm | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 10 tests in 2732.895s

OK (SKIP=1)
/tmp//MarvinLogs/test_vm_life_cycle_EW6E00/results.txt (END)

**Comment by borisroman** [comment]
The https://builds.apache.org/job/cloudstack-pull-requests fail after adding the Default Charset test. I think the localization of the Jenkins server needs to be adjusted. Or the test should be removed.

**Pull request closed without merging**
