### PR TITLE
test_network_ipv6.py : remove wrong icmp type

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes trillian test failures caused by wrong icmp type.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by shwstppr — APPROVED** [review]

**Review by shwstppr — COMMENTED** [review]
@weizhouapache ~I may have approved change too soon. I think nft uses `mld-listener-reduction` for type 132~
LGTM

**Comment by weizhouapache** [comment]
@blueorangutan test

**Review by sureshanaparti — APPROVED** [review]

**Comment by weizhouapache** [comment]
merging based on 2 lgtm and trillian test results, 4 successful checks

**Pull request merged**
