### PR TITLE
test: update test_kubernetes_clusters.py to support advanced zone with security groups

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR updates test_kubernetes_clusters.py to support advanced zone with security groups

test passes with #6132 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### CODE REVIEW

**Review by rohityadavcloud — APPROVED** [review]
LGTM subject to testing/CI/CD passing

**Comment by weizhouapache** [comment]
test results
```
Test to check for failure while tying to upgrade a Kubernetes cluster to a lower version ... === TestName: test_01_invalid_upgrade_kubernetes_cluster | Status : SUCCESS ===
ok
Test to deploy a new Kubernetes cluster and upgrade it to newer version ... === TestName: test_02_upgrade_kubernetes_cluster | Status : SUCCESS ===
ok
Test to deploy a new Kubernetes cluster and check for failure while tying to scale it ... === TestName: test_03_deploy_and_scale_kubernetes_cluster | Status : SUCCESS ===
ok
Test to enable autoscaling a Kubernetes cluster ... === TestName: test_04_autoscale_kubernetes_cluster | Status : SUCCESS ===
ok
Test to deploy a new Kubernetes cluster ... === TestName: test_05_basic_lifecycle_kubernetes_cluster | Status : SUCCESS ===
ok
Test to delete an existing Kubernetes cluster ... === TestName: test_06_delete_kubernetes_cluster | Status : SUCCESS ===
ok
Test to deploy a new Kubernetes cluster ... SKIP: HA cluster on shared network requires external ip address, skipping it
Test to upgrade a Kubernetes cluster to newer version ... SKIP: HA cluster on shared network requires external ip address, skipping it
Test to delete a HA Kubernetes cluster ... SKIP: HA cluster on shared network requires external ip address, skipping it

----------------------------------------------------------------------
Ran 9 tests in 1221.165s

OK (SKIP=3)
```

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan test

**Review by Pearl1594 — APPROVED** [review]

**Review by rohityadavcloud — APPROVED** [review]

**Pull request merged**
