### PR TITLE
debian12: update debian/control

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes the cloudstack-management package installation issue on debian12

on Debian12, the package name is `mysql-connector-python-py3`
while the package name is `python3-mysql.connector` on ubuntu 24.04
```
# wget https://dev.mysql.com/get/mysql-apt-config_0.8.32-1_all.deb
# apt install -y ./mysql-apt-config_0.8.32-1_all.deb
# apt update

# apt search python3-mysql.connector
Sorting... Done
Full Text Search... Done

# apt search mysql-connector-python
Sorting... Done
Full Text Search... Done
mysql-connector-python-py3/unknown,now 8.4.0-1debian12 amd64 [installed]
  MySQL database driver written in pure Python 3

mysql-connector-python-py3-dbgsym/unknown 8.4.0-1debian12 amd64
  debug symbols for mysql-connector-python-py3
```

as a workaround, please install the package for ubuntu 24.04
```
wget http://launchpadlibrarian.net/717081070/python3-mysql.connector_8.0.15-4_all.deb
DEBIAN_FRONTEND=noninteractive apt install -y /tmp/python3-mysql.connector_8.0.15-4_all.deb
```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by sureshanaparti — APPROVED** [review]
lgtm

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
As this is a pkg install issue, should this be considered critical for release cc @JoaoJandre  ?

**Comment by DaanHoogland** [comment]
@JoaoJandre , this is experimental support for debian as MS and hypervisor. It is not really a feature. Do you think we can include it?

**Comment by weizhouapache** [comment]
some test failures are caused by timezone issue in debian
https://unix.stackexchange.com/questions/451709/timedatectl-set-timezone-doesnt-update-etc-timezone
it has been fixed by command `dpkg-reconfigure tzdata` in jenkins

retesting now

(some ubuntu 24.04 test failures might be caused by it as well)

**Pull request merged**
