### PR TITLE
vpc: fix acl rule with protocol number is not applied correctly in vpc vr

### PR DESCRIPTION
**Pull request by ustcweizhou**
## Description

When add a acl rule with protocol number, the iptables rules in vpc vr is not applied correctly.
for example, when add an ingress acl rule (protocol number:50, cidr: 2.2.2.2/32), we expect to have a iptables rule: "-A ACL_INBOUND_eth2 -s 2.2.2.2/32 -p esp -j ACCEPT"
the actual rule is "-A ACL_INBOUND_eth2 -j DROP"

It is because the rules in json are not correct.
network_acl.json.a8c52dca-0278-4e1c-b72b-987ca7121f4f.gz:{"device":"eth2","mac_address":"02:00:7d:27:00:02","private_gateway_acl":false,"nic_ip":"192.168.11.12","nic_netmask":"28","ingress_rules":[{"type":"protocol","protocol":50,"cidr":"ACCEPT","allowed":false},{"type":"all","cidr":"0.0.0.0/0","allowed":true},],"egress_rules":[],"type":"networkacl"}

Fixes: #3602 

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

Add acl rule in VPC, then check the iptables rules in VPC VR. all are good with this change.

### CODE REVIEW

**Comment by andrijapanicsb** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by andrijapanicsb** [comment]
@blueorangutan test

**Comment by andrijapanicsb** [comment]
@weizhouapache seems that blueorangutan doesn't honour your request, will need to kick his bash :) 
thx for the fix, I'm testing manually as we speak.

**Comment by andrijapanicsb** [comment]
LGTM

tested manually, results below.

Setup:
image

Results as expected:
image

**Comment by andrijapanicsb** [comment]
Actually, by checking some strongswan documentation, that is how rules should be added (no PORT definition in the rule) - so that is all OK.

**Comment by weizhouapache** [comment]
@andrijapanicsb thanks for testing !

dport is not supported by some protocols , for example ah/esp/gre (50/51/47)
According to iptables document (https://linux.die.net/man/8/iptables) , dport is supported by some other protocols  besides tcp/udp , for example dccp, sctp. The protocols are rarely used.

**Comment by weizhouapache** [comment]
@andrijapanicsb 
I have tested in a virtual router, it gives the same result, only tcp/udp/dccp/sctp support dport.

```
root@r-597-VM:~# for i in `seq 0 142`;do iptables -I ACL_INBOUND_eth2 -p $i --dport 1000 -j ACCEPT >/dev/null 2>&1;if [ "$?" == "0" ];then echo $i;fi;done
6
17
33
132
```
https://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml

**Comment by andrijapanicsb** [comment]
yes @weizhouapache that's what I mean, that's fine.

**Comment by weizhouapache** [comment]
@andrijapanicsb nice. 
maybe we can take dccp/sctp into consideration afterwards.
They are not in use on our platforms.

**Comment by andrijapanicsb** [comment]
your call @weizhouapache  (for now, I'm fine with just this fix here). Thx

**Comment by weizhouapache** [comment]
@rhtyd @DaanHoogland can you please review it ?

**Pull request merged**
