### PR TITLE
Remove unused images

### PR DESCRIPTION
**Pull request by remibergsma**
We really don't need this, do we?

Check your own cloud, it's there...

screen shot 2016-03-22 at 17 38 45

### CODE REVIEW

**Comment by remibergsma** [comment]
Travis error is unrelated obviously:
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

**Comment by DaanHoogland** [comment]
:) still cleaning, good job.
LGTM

**Comment by GabrielBrascher** [comment]
Remove unused files is always good. LGTM.

**Comment by swill** [comment]
Can you either close and reopen or do a `push -f` to try to kick off travis.  I am confident in this PR, but I want everything green before we merge...  Thank you for the code reviews...

**Comment by remibergsma** [comment]
@swill force pushed

**Comment by wido** [comment]
Yes, seems rather stupid to keep those :)

LGTM

**Comment by swill** [comment]
Isn't there references to these files?  Forget the ones in `target`, but the references in `cloudstack/scripts/installer/windows/client.wxs` should probably be addressed...

Thoughts?

```
Searching 15246 files for "sample-project-view.png"

cloudstack/client/target/cloud-client-ui-4.9.0-SNAPSHOT.war:
    File too large, skipping

cloudstack/client/target/cloud-client-ui-4.9.0-SNAPSHOT/WEB-INF/classes/scripts/installer/windows/client.wxs:
  170                      </Component>
  171                      <Component Id="cmp6E186870ED4CF468177D7449592B651D" Guid="{1735AF1A-2962-4A6C-9103-A1B891920977}">
  172:                         <File Id="filFC755B88B988B6799CCF3B813EFE8E8F" KeyPath="yes" Source="!(wix.SourceClient)\images\sample-project-view.png" />
  173                      </Component>
  174                      <Component Id="cmp1C89ADB77497A7903954C1555FE7D35D" Guid="{9795E109-A613-4891-A396-F6FCDA1121FA}">

cloudstack/client/target/generated-webapp/WEB-INF/classes/scripts/installer/windows/client.wxs:
  170                      </Component>
  171                      <Component Id="cmp6E186870ED4CF468177D7449592B651D" Guid="{1735AF1A-2962-4A6C-9103-A1B891920977}">
  172:                         <File Id="filFC755B88B988B6799CCF3B813EFE8E8F" KeyPath="yes" Source="!(wix.SourceClient)\images\sample-project-view.png" />
  173                      </Component>
  174                      <Component Id="cmp1C89ADB77497A7903954C1555FE7D35D" Guid="{9795E109-A613-4891-A396-F6FCDA1121FA}">

cloudstack/scripts/installer/windows/client.wxs:
  170                      </Component>
  171                      <Component Id="cmp6E186870ED4CF468177D7449592B651D" Guid="{1735AF1A-2962-4A6C-9103-A1B891920977}">
  172:                         <File Id="filFC755B88B988B6799CCF3B813EFE8E8F" KeyPath="yes" Source="!(wix.SourceClient)\images\sample-project-view.png" />
  173                      </Component>
  174                      <Component Id="cmp1C89ADB77497A7903954C1555FE7D35D" Guid="{9795E109-A613-4891-A396-F6FCDA1121FA}">

3 matches across 3 files


Searching 15246 files for "vm-instance-screen-sample.png"

cloudstack/client/target/cloud-client-ui-4.9.0-SNAPSHOT.war:
    File too large, skipping

cloudstack/client/target/cloud-client-ui-4.9.0-SNAPSHOT/WEB-INF/classes/scripts/installer/windows/client.wxs:
  176                      </Component>
  177                      <Component Id="cmp033EEE431FC34259BCA1CE1B246E50F4" Guid="{FEF35205-58DB-42E6-9C9A-2C9CE2C46527}">
  178:                         <File Id="filABF125D326B2B2880F897A3B8356A17C" KeyPath="yes" Source="!(wix.SourceClient)\images\vm-instance-screen-sample.png" />
  179                      </Component>
  180                  </Directory>

cloudstack/client/target/generated-webapp/WEB-INF/classes/scripts/installer/windows/client.wxs:
  176                      </Component>
  177                      <Component Id="cmp033EEE431FC34259BCA1CE1B246E50F4" Guid="{FEF35205-58DB-42E6-9C9A-2C9CE2C46527}">
  178:                         <File Id="filABF125D326B2B2880F897A3B8356A17C" KeyPath="yes" Source="!(wix.SourceClient)\images\vm-instance-screen-sample.png" />
  179                      </Component>
  180                  </Directory>

cloudstack/scripts/installer/windows/client.wxs:
  176                      </Component>
  177                      <Component Id="cmp033EEE431FC34259BCA1CE1B246E50F4" Guid="{FEF35205-58DB-42E6-9C9A-2C9CE2C46527}">
  178:                         <File Id="filABF125D326B2B2880F897A3B8356A17C" KeyPath="yes" Source="!(wix.SourceClient)\images\vm-instance-screen-sample.png" />
  179                      </Component>
  180                  </Directory>

3 matches across 3 files
```

**Comment by rafaelweingartner** [comment]
Is that "wix-acs" maven task executed?
What does it build?

I noticed it has as an output a file called "acs.msi", what is it?

**Comment by DaanHoogland** [comment]
the windows install of acs

**Comment by rafaelweingartner** [comment]
you mean the ACS itself?

The whole ACS? For what I have seen of the code base, it does not seem to work in Windows environments.

**Comment by DaanHoogland** [comment]
might be just for the agent, I have never run it. I read about people running it on windows but back in the days when i did it is was on cygwin.

**Comment by rafaelweingartner** [comment]
I also thought it was the HyperV agent; but, that agent is built in a different way. I was going over the files, and it seems that is used to build an installer to install ACS on Windows. 

Has anyone ever used that? I doubt that it works today.
The image is being referenced there, but it does not seem to be used anywhere else. I would instead create a Jira ticket and then with time prepare a PR to remove everything that has to do with that whole “MSI” build.

**Comment by remibergsma** [comment]
@rafaelweingartner +1 to remove all that stuff

**Comment by rafaelweingartner** [comment]
I have created a jira ticket for this.
https://issues.apache.org/jira/browse/CLOUDSTACK-9345

Maybe we could close this PR, and then next release we could work on this cleanup.

**Comment by swill** [comment]
@remibergsma how should we handle this PR now that we have found references to these files?

**Comment by swill** [comment]
@remibergsma bump.  :)  just a friendly reminder.  what should we do with this PR?

**Pull request closed without merging**
