### PR TITLE
Add three more `pre-commit` checks

### PR DESCRIPTION
**Pull request by jbampton**
Ran `pre-commit autoupdate` to update the hooks.

Hooks that are added:

https://github.com/pre-commit/pre-commit-hooks#check-case-conflict

https://github.com/pre-commit/pre-commit-hooks#check-vcs-permalinks

https://github.com/pre-commit/pre-commit-hooks#end-of-file-fixer

### Description

This PR adds to our pre-commit framework with three more hooks.

Also has auto cleaned the end of files.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [X] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [X] Trivial

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
i am sick, I know (triple pun intended), but I went through all 632 files. LGTM

**Comment by DaanHoogland** [comment]
@davidjumani @rohityadavcloud can you review this one please?

**Comment by DaanHoogland** [comment]
> @davidjumani @rohityadavcloud can you review this one please?

@davidjumani @rohityadavcloud ping

**Comment by DaanHoogland** [comment]
@jbampton can you look at the conflicts

**Comment by DaanHoogland** [comment]
ping @rohityadavcloud @davidjumani , can you review?

**Review by JoaoJandre — APPROVED** [review]
Looked through all the files as well, LGTM.

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by jbampton** [comment]
Hey @DaanHoogland updated now.  The "end of file" is fixed

**Pull request merged**
