### PR TITLE
fix: remove double <form> element from 2FA form

### PR DESCRIPTION
**Pull request by phsm**
### Description

This PR fixes the password managers autofill functionality in the 2FA OTP code form.
It is caused by double `<form>` element. 

Fixes: #9510

The PR simply removes the outer empty `<form>` element, leaving the inner one intact.

**Steps to reproduce:**
1. Install 1password password manager and the browser extension.
2. Enable 2FA authentication for your Cloudstack user.
3. Save the OTP token for your user in 1password so it now provides OTP passwords.
4. Try to login to Cloudstack UI with 1password autofill. 

Expected behavior:
1password fills all 6 numbers of the OTP token into the input form.

Actual behavior:
1password only fills 3 numbers out of 6 into the input form.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### Screenshots (if appropriate):
Before:

https://github.com/user-attachments/assets/d5d81734-16a1-434a-b4ef-f71f225ef761

After:

https://github.com/user-attachments/assets/18d55901-f9f4-4701-b58b-7764aa232798

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan ui

**Comment by sureshanaparti** [comment]
@blueorangutan ui

**Comment by phsm** [comment]
> clgtm, I cannot see a functional difference in your video snippets (before/after) @phsm?

Thanks for pointing that out. I indeed made it unclear. 

Replaced the first video.

**Review by DaanHoogland — APPROVED** [review]

**Comment by phsm** [comment]
Hello,
is there any progress with this PR?

**Comment by DaanHoogland** [comment]
@blueorangutan ui

**Comment by phsm** [comment]
@rohityadavcloud I see you have made changes to this file in the past. Perhaps you can take a look?

**Review by Pearl1594 — APPROVED** [review]

**Pull request merged**
