### PR TITLE
db, server: refactor host_view to prevent duplicate entries

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Re-creates `cloud.host_view` to prevent duplication when a host has multiple tags associated.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

With a KVM env, using API.

- Multiple tags have been added to a KVM host.
```
(localcloud) SBCM5> > list hosts type=ROUTING filter=id,name,hosttags
{
  "count": 2,
  "host": [
    {
      "id": "9745b62e-45a8-4a96-a782-57204c3fdb98",
      "name": "ref-trl-755-k-M7-abhishek-kumar-kvm2"
    },
    {
      "id": "109fc401-e7d4-4cef-ba40-1cdfe0896914",
      "name": "ref-trl-755-k-M7-abhishek-kumar-kvm1"
    }
  ]
}
(localcloud) SBCM5> > update host id=109fc401-e7d4-4cef-ba40-1cdfe0896914 hosttags=tag1,tag2
{
  "host": {
    "capabilities": "hvm,snapshot",
    "clusterid": "7ba1f501-f006-461e-9849-8fd605921a59",
    "clustername": "p1-c1",
    "clustertype": "CloudManaged",
    "cpuallocated": "15.87%",
    "cpuallocatedpercentage": "15.87%",
    "cpuallocatedvalue": 1000,
    "cpuallocatedwithoverprovisioning": "7.94%",
    "cpuloadaverage": 0.15,
    "cpunumber": 3,
    "cpusockets": 3,
    "cpuspeed": 2100,
    "cpuused": "5.2%",
    "cpuwithoverprovisioning": "12600",
    "created": "2021-04-11T19:14:43+0000",
    "details": {
      "Host.OS": "CentOS",
      "Host.OS.Kernel.Version": "3.10.0-957.12.2.el7.x86_64",
      "Host.OS.Version": "7.6.1810",
      "com.cloud.network.Networks.RouterPrivateIpStrategy": "HostLocal",
      "secured": "true"
    },
    "events": "HostDown; Remove; Ping; StartAgentRebalance; ManagementServerDown; ShutdownRequested; AgentConnected; PingTimeout; AgentDisconnected",
    "hahost": false,
    "hostha": {
      "haenable": false,
      "hastate": "Disabled"
    },
    "hosttags": "tag1,tag2",
    "hypervisor": "KVM",
    "id": "109fc401-e7d4-4cef-ba40-1cdfe0896914",
    "ipaddress": "10.0.34.120",
    "islocalstorageactive": false,
    "lastpinged": "1970-01-19T06:57:22+0000",
    "managementserverid": "66100c64-c81f-4756-b050-c5369a19848d",
    "memoryallocated": 1610612736,
    "memoryallocatedbytes": 1610612736,
    "memoryallocatedpercentage": "22.13%",
    "memorytotal": 7277125632,
    "memoryused": 388489216,
    "memorywithoverprovisioning": "7277125632",
    "name": "ref-trl-755-k-M7-abhishek-kumar-kvm1",
    "networkkbsread": 3503,
    "networkkbswrite": 1,
    "outofbandmanagement": {
      "enabled": false,
      "powerstate": "Disabled"
    },
    "podid": "06798308-d801-41a5-b465-4d72083d5f37",
    "podname": "Pod1",
    "resourcestate": "Enabled",
    "state": "Up",
    "type": "Routing",
    "ueficapability": false,
    "version": "4.16.0.0-SNAPSHOT",
    "zoneid": "e44f5eca-9625-4bfa-953f-2e6a2f9b5438",
    "zonename": "ref-trl-755-k-M7-abhishek-kumar"
  }
}

```
- DB entries and API output has been verified.

Original behaviour:
Each host tag has a different entry in `cloud.host_view`.
```
MariaDB [cloud]> select id,name,tag from host_view where type='ROUTING'\G
*************************** 1. row ***************************
  id: 1
name: ref-trl-755-k-M7-abhishek-kumar-kvm1
 tag: tag1
*************************** 2. row ***************************
  id: 1
name: ref-trl-755-k-M7-abhishek-kumar-kvm1
 tag: tag2
*************************** 3. row ***************************
  id: 2
name: ref-trl-755-k-M7-abhishek-kumar-kvm2
 tag: NULL
3 rows in set (0.01 sec)
```
API creates host host response for first found entry for an ID using `newHostResponse`/`newHostForMigrationResponse` and for remaining entries calls `setHostResponse`/`setHostForMigrationResponse` so that remaining tags can be added to the response.
```
(localcloud) SBCM5> > list hosts type=ROUTING filter=id,name,hosttags
{
  "count": 2,
  "host": [
    {
      "id": "9745b62e-45a8-4a96-a782-57204c3fdb98",
      "name": "ref-trl-755-k-M7-abhishek-kumar-kvm2"
    },
    {
      "hosttags": "tag1,tag2",
      "id": "109fc401-e7d4-4cef-ba40-1cdfe0896914",
      "name": "ref-trl-755-k-M7-abhishek-kumar-kvm1"
    }
  ]
}
```

This change re-creates `cloud.host_view` so the `tag` field can contain comma-separated multiple tags.
DB entries after the change:
```
MariaDB [cloud]> select id,name,tag from host_view where type='ROUTING'\G
*************************** 1. row ***************************
  id: 1
name: ref-trl-755-k-M7-abhishek-kumar-kvm1
 tag: tag1,tag2
*************************** 2. row ***************************
  id: 2
name: ref-trl-755-k-M7-abhishek-kumar-kvm2
 tag: NULL
2 rows in set (0.00 sec)
```
API returns the same response as the code has been refactored to use the new `cloud.host_view`:
```
(localcloud) SBCM5> > list hosts type=ROUTING filter=id,name,hosttags
{
  "count": 2,
  "host": [
    {
      "id": "9745b62e-45a8-4a96-a782-57204c3fdb98",
      "name": "ref-trl-755-k-M7-abhishek-kumar-kvm2"
    },
    {
      "hosttags": "tag1,tag2",
      "id": "109fc401-e7d4-4cef-ba40-1cdfe0896914",
      "name": "ref-trl-755-k-M7-abhishek-kumar-kvm1"
    }
  ]
}
```

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@shwstppr pr #4789 has been merged

**Comment by shwstppr** [comment]
@weizhouapache updated changes here

@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
The code and your test output look like a great cleanup @shwstppr! Can you describe testing a bit further? It looks scary in terms of API output and UI consequences ;)

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test keep

@DaanHoogland Updated PR description for test

**Comment by shwstppr** [comment]
@blueorangutan test

**Review by DaanHoogland — APPROVED** [review]

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by sureshanaparti — APPROVED** [review]
code LGTM

**Comment by rhtyd** [comment]
@shwstppr can you resolve conflicts and kick tests

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
Hi @shwstppr can you please fix the conflicts

**Comment by shwstppr** [comment]
@sureshanaparti done

@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by nvazquez** [comment]
@shwstppr is this PR ready to merge?

**Comment by shwstppr** [comment]
@nvazquez yes

**Pull request merged**
