### PR TITLE
vxlan: do not create duplicated network for private gateway

### LINKED ISSUE #7891: The corresponding Network Tier like vpc-XXX-privateNetwork cannot be automatically removed
##### ISSUE TYPE
* Bug Report

##### COMPONENT NAME
- VR, Private gateway

##### CLOUDSTACK VERSION
- CloudStack 4.18.0.0

##### CONFIGURATION
- Cloudstack zone with VXLAN
- VPC --> tier 

##### OS / ENVIRONMENT
- oracle linux 8

##### SUMMARY
The VPC tier will auto add a name like  vpc-XXX-privateNetwork when add a Private Gateway to a VPC. But when deleting a Private Gateway, the corresponding Network Tier like vpc-XXX-privateNetwork cannot be automatically removed.

##### STEPS TO REPRODUCE
- Create a VPC
- Create a tier test and dev
- Add  Private gateway
- Delete the Private gateway
- Check the Networks tier and the VR status, In my env, the Private gateway only has one. but the Networks tier is still having the deleted the privateNetwork.
image

image

image

##### EXPECTED RESULTS
when deleting a Private Gateway, the corresponding Network Tier like vpc-XXX-privateNetwork cannot be automatically removed.

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #7891 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by rohityadavcloud — APPROVED** [review]

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Review by borisstoyanov — APPROVED** [review]
LGTM, checked it manually

**Pull request merged**
