### PR TITLE
Fixes: #2881 Improve Exception message

### PR DESCRIPTION
**Pull request by fmaximus**
## Description

Network.Service and Network.Provider were missing a toString() method.
Added toString() methods so appending instances, or a collection of instances 
to a String, will result in an understandable String.

### Before
com.cloud.network.Network$Provider@11763e57 requires services: [com.cloud.network.Network$Service@4f9871a2]
### After
Provider Network.Provider[name=NuageVsp] requires services: [Network.Service[name=Connectivity]]

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## GitHub Issue/PRs

Fixes: #2881

## How Has This Been Tested?
Manually, added Unit Test to validate exception message.

## Checklist:

- [ ] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
Testing
- [x] I have added tests to cover my changes.
- [ ] All relevant new and existing integration tests have passed.
- [ ] A full integration testsuite with all test that can run on my environment has passed.

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@fmaximus while this looks to improve logging, I'm not sure if it will fix the root cause of #2881 /cc @borisstoyanov can you test?

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by borisstoyanov** [comment]
yes @rhtyd, let me build env and verify this.

**Pull request merged**
