### PR TITLE
CLOUDSTACK-10341: Reduce systemvmtemplate size, install nftables

### PR DESCRIPTION
**Pull request by rhtyd**
## Description

This reduces systemvmtemplate size by 600MB and installs nftables,
updates iptables.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

## Screenshots (if appropriate):

screenshot from 2018-03-23 13-32-44
screenshot from 2018-03-23 13-33-03

## How Has This Been Tested?

Manually built using packer and tested locally by running smoketests.

## Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by resmo** [comment]
while improving, I wonder do we already have --no-recommends? This would also skip installing docs and optimize disk space usage. I would even suggest to add it to apt.conf

~~~
cat > /etc/apt/apt.conf.d/01norecommend << EOF
APT::Install-Recommends "0";
APT::Install-Suggests "0";
EOF
~~~

Any thoughts?

**Comment by rhtyd** [comment]
Thanks @resmo, we indeed install packages with the --no-install-recommends flag https://github.com/apache/cloudstack/blob/master/tools/appliance/systemvmtemplate/scripts/install_systemvm_packages.sh#L46

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Manual tests have passed, let me kick a final run.
@blueorangutan test matrix

**Comment by rhtyd** [comment]
Test LGTM, failures are due to environment issues or not related to this PR. Merging this based on results and two review LGTMs.

**Pull request merged**
