### PR TITLE
server: check hostId when attach disk to a Stopped vm with local storage

### LINKED ISSUE #7834: Stopped VM with local storage and data disk created/attached fails if created on a different host
This is where all disks are local storage. Create a VM with root disk on host A, stop the VM and create a disk and attach it to the VM and chances are sometimes it gets created on host B (local storage); however on attach it fails with error as data disk is on local storage of host B.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Local storage, VM/volume
~~~

##### CLOUDSTACK VERSION

~~~
4.18
~~~

##### CONFIGURATION

Adv zone

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This fixes #7834

Steps to reproduce the issue
- create service offering and disk offering with local storage
- create a vm with local storage, and stop it
- create volume with local storage
- attach volume to vm

sometimes the volume is allocated to other host than root disk in the attach process, and an exception is thrown
```
com.cloud.utils.exception.CloudRuntimeException: Failed to attach local data volume data-001 to VM local-001 as migration of local data volume is not allowed
    at com.cloud.storage.VolumeApiServiceImpl.orchestrateAttachVolumeToVM(VolumeApiServiceImpl.java:2234)
    at com.cloud.storage.VolumeApiServiceImpl.orchestrateAttachVolumeToVM(VolumeApiServiceImpl.java:4697)
```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Review by DaanHoogland — APPROVED** [review]
code looks good.

**Review by vishesh92 — APPROVED** [review]
clgtm

**Review by rohityadavcloud — APPROVED** [review]
LGTM haven't tested it but I can see where/how Wei has fixed it and has tested it.

**Pull request merged**
