### PR TITLE
README: that time of the year!

### PR DESCRIPTION
**Pull request by rhtyd**
That time of the year :christmas_tree: - let's merge this without tests?

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## Screenshots (if appropriate):

Screenshot from 2019-12-16 21-14-27

### CODE REVIEW

**Comment by rhtyd** [comment]
To all of CloudStack contributors - Happy Christmas and holidays!
/cc alphabetically-ish @andrijapanic @anuragaw @borisstoyanov @bwsw @chiradeep @DaanHoogland @GabrielBrascher @gsirett @harikrishna-patnala @K0zka @kiwiflyer @PaulAngus @mlsorensen @mike-tutkowski @milamberspace @msinhore @NuxRo @nvazquez @pdion891 @steveroles @svenvogel @webermaximilian92 @DennisKonrad @swill @syed @ustcweizhou @wido and so many others! (sorry guys don't remember all the handles, I may have missed more than a few)

**Comment by syed** [comment]
Happy holidays all :)

**Comment by msinhore** [comment]
Happy holidays folks!

**Comment by svenvogel** [comment]
@rohit and all other ... happy holiday ... :star::evergreen_tree::snowflake::snowman::gift::santa::bell:

**Comment by mike-tutkowski** [comment]
LGTM :)

**Comment by nvazquez** [comment]
Happy holidays and new year all!

**Comment by andrijapanicsb** [comment]
Merging based on so may LGTMs and +1 (Rohit you'll have the pleasure or reverting the stuff later)

**Comment by anuragaw** [comment]
Happy new year and best wishes for the season all! :)

**Comment by borisstoyanov** [comment]
+1! happy holidays guys, wish you all the best in the new year!

**Comment by rhtyd** [comment]
That went in a little fast, hope it doesn't stop everyone to still continue exchanging greetings. Cheers all.

**Pull request merged**
