### PR TITLE
Debian/Ubuntu packaging issues

### PR DESCRIPTION
**Pull request by borisroman**
See individual issues. I've installed the management server with and without the fix. See difference bellow.

Before:
```
root@acs46:~# ls -la /var/lib/cloudstack
total 16
drwxr-xr-x  4 root root  4096 Nov 23 00:20 .
drwxr-xr-x 46 root root  4096 Nov 23 00:21 ..
drwxrwx---  2 root cloud 4096 Nov 17 01:15 management
drwxr-xr-x  2 root root  4096 Nov 17 01:15 mnt
```
```
root@acs46:~# ls -la /usr/share/cloudstack-management/webapps/client/WEB-INF/classes/scripts/storage/secondary/
total 152
drwxr-xr-x 2 root root  4096 Nov 23 00:20 .
drwxr-xr-x 4 root root  4096 Nov 23 00:20 ..
-rw-r--r-- 1 root root 10092 Nov 17 01:15 cloud-install-sys-tmplt
-rw-r--r-- 1 root root 10591 Nov 17 01:15 cloud-install-sys-tmplt.py
-rw-r--r-- 1 root root 11254 Nov 23 00:20 cloud-install-sys-tmplt.pyc
-rw-r--r-- 1 root root  2362 Nov 17 01:15 create_privatetemplate_from_snapshot_xen.sh
-rw-r--r-- 1 root root  5446 Nov 17 01:15 createtmplt.sh
-rw-r--r-- 1 root root  5388 Nov 17 01:15 createvolume.sh
-rw-r--r-- 1 root root  2532 Nov 17 01:15 installIso.sh
-rw-r--r-- 1 root root  1622 Nov 17 01:15 listvmtmplt.sh
-rw-r--r-- 1 root root  1621 Nov 17 01:15 listvolume.sh
-rw-r--r-- 1 root root 75712 Nov 17 01:15 swift
```

After:
```
root@acs46:~# ls -la /var/lib/cloudstack
total 16
drwxr-xr-x  4 cloud cloud 4096 Nov 23 00:51 .
drwxr-xr-x 46 root  root  4096 Nov 23 00:53 ..
drwxrwx---  2 cloud cloud 4096 Nov 23 00:33 management
drwxr-xr-x  2 cloud cloud 4096 Nov 23 00:33 mnt
```
```
root@acs46:~# ls -la /usr/share/cloudstack-management/webapps/client/WEB-INF/classes/scripts/storage/secondary/
total 152
drwxr-xr-x 2 root root  4096 Nov 23 00:53 .
drwxr-xr-x 4 root root  4096 Nov 23 00:53 ..
-rwxr-xr-x 1 root root 10092 Nov 23 00:33 cloud-install-sys-tmplt
-rwxr-xr-x 1 root root 10591 Nov 23 00:33 cloud-install-sys-tmplt.py
-rwxr-xr-x 1 root root 11254 Nov 23 00:53 cloud-install-sys-tmplt.pyc
-rwxr-xr-x 1 root root  2362 Nov 23 00:33 create_privatetemplate_from_snapshot_xen.sh
-rwxr-xr-x 1 root root  5446 Nov 23 00:33 createtmplt.sh
-rwxr-xr-x 1 root root  5388 Nov 23 00:33 createvolume.sh
-rwxr-xr-x 1 root root  2532 Nov 23 00:33 installIso.sh
-rwxr-xr-x 1 root root  1622 Nov 23 00:33 listvmtmplt.sh
-rwxr-xr-x 1 root root  1621 Nov 23 00:33 listvolume.sh
-rwxr-xr-x 1 root root 75712 Nov 23 00:33 swift
```

### CODE REVIEW

**Comment by bhaisaab** [comment]
LGTM, should we fix the scripts in src paths?

**Comment by borisroman** [comment]
Hi @bhaisaab, what do you mean with "fix the scripts in src paths" ? Regards

**Comment by bhaisaab** [comment]
@borisroman I mean, if it helps to do chmod +x to the scripts in scripts/storage in the git repo itself?

**Comment by borisroman** [comment]
@bhaisaab Ah, i've already looked them up, and in fact, in the git repo, they have the +x flag. So during the install, they have that flagged stripped...

**Comment by remibergsma** [comment]
LGTM, haven't verified Debian packages though.

**Pull request merged**
