### PR TITLE
simplify code using optional chaining in compute views

### PR DESCRIPTION
**Pull request by Damans227**
### Description

This PR is related to issue: `ui: Simplify code` #4956

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by utchoang** [comment]
@blueorangutan ui

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
@blueorangutan ui

**Review by utchoang — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@blueorangutan ui

**Comment by DaanHoogland** [comment]
I failed to test this (the migration wizard) in the qa environment but think it is the environment and not the PR. Can anybody confirm?

**Comment by utchoang** [comment]
@DaanHoogland I don't have the same problem as you, can you check again?

**Comment by DaanHoogland** [comment]
@utchoang my problem is with the migration wizard, the ssh keypair works (and kubernetes is not configured), never mind is this is succesfully tested by others.

**Pull request merged**
