### PR TITLE
Fix set initial reservation on public IP ranges

### PR DESCRIPTION
**Pull request by nvazquez**
## Description
Fix initial reservation on public IP range addition. Also, if the range is dedicated for system VMs do not allow dedicating it to any account

Fixes: #2929 

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?
- Set reservation to a domain, add range. Verify domain is set to the domain.

### CODE REVIEW

**Comment by nvazquez** [comment]
Hi @svenvogel can you please test it?

**Comment by svenvogel** [comment]
Hi @nvazquez wow great.. i will test fastly and done back greets Sven

**Comment by DaanHoogland** [comment]
#2980 fixes this for 4.11. we should not merge this as it will be merged forward from there.

**Comment by rhtyd** [comment]
If there is already a 4.11 based PR, this can be closed @nvazquez

**Comment by nvazquez** [comment]
@rhtyd @DaanHoogland yes, just created this PR for testing it on master. Closing it

**Pull request closed without merging**
