### PR TITLE
CLOUDSTACK-10117 Domain level ldap configuration

### PR DESCRIPTION
**Pull request by DaanHoogland**
This contains fixes and implementation of CLOUDSTACK-10117 and CLOUDSTACK-10118, enabling the operator to configure an ldap server per domain. Work will follow that enables mapping of accounts to ldap-domains but as is this change is functional if no further mapping is needed.

### CODE REVIEW

**Comment by rhtyd** [comment]
@DaanHoogland can you fix conflicts?

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
Travis error is a job timeout. @rhtyd do you agree this is unrelated to the code or any ACS issue?

**Comment by rhtyd** [comment]
@DaanHoogland let me rekick travis job (any committer with access to commit to apache repos, can login via github and rekick travis jobs :) )

**Comment by DaanHoogland** [comment]
tnx @rhtyd 
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@DaanHoogland can you fix the conflicts, thanks.

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
this is overridden by #2381 which implements account level binding on ldap groups

**Pull request closed without merging**
