### PR TITLE
Use parallel builds for github actions

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR allows usage of multiple threads for running different github actions depending on the number of cores present in the system.

As per the documentation [here](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources), github runners have 2 cores. This should decrease the time it takes for github actions to run.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by weizhouapache — APPROVED** [review]
code lgtm

comparing with #7583, this saves 2 minutes for each build.

**Comment by vishesh92** [comment]
For code coverage, running tests with coverage took 54 minutes.

**Review by rohityadavcloud — APPROVED** [review]
LGTM, I've attempted that in the past (but with travis which I think was using Google compute, not Azure/VMs based Github Actions) and sometimes the VM hits cpu contention and could cause intermittent job failures

**Comment by weizhouapache** [comment]
> LGTM, I've attempted that in the past (but with travis which I think was using Google compute, not Azure/VMs based Github Actions) and sometimes the VM hits cpu contention and could cause intermittent job failures

@rohityadavcloud 
yes, I discussed with @vishesh92 and shared the same concern. anyway, the simulator CIs and all other tests look good.

**Comment by vishesh92** [comment]
@rohityadavcloud @weizhouapache I understand your concerns. I used `nproc` to only use the number of cores available. It depends on the GitHub Actions infrastructure how they provision cores to github action runners. Can we merge this and revert if we see any issues?

**Comment by weizhouapache** [comment]
the codecov and sonar test failures are caused by tokens, not this PR

**Comment by weizhouapache** [comment]
> @rohityadavcloud @weizhouapache I understand your concerns. I used `nproc` to only use the number of cores available. It depends on the GitHub Actions infrastructure how they provision cores to github action runners. Can we merge this and revert if we see any issues?

@vishesh92 yes, merged

**Pull request merged**
