### PR TITLE
Don't log VNC password in VirtualMachineTO

### PR DESCRIPTION
**Pull request by mlsorensen**
### Description

This PR turns logging off for the VNC password on VirtualMachineTO

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### CODE REVIEW

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Review by rohityadavcloud — APPROVED** [review]
Code lgtm

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by weizhouapache** [comment]
I checked the management-server.log in the trillian test results . there is no vncPassword in the log .
I think we are good to merge this. cc @DaanHoogland 



1. In my testing without this change, found vncPassword in the logs of StartCommand and StartAnswer
```
root@ref-trl-3836-k-Mu22-wei-zhou-mgmt1:~# zgrep vncPassword /var/log/cloudstack/management/management-server.log.2023-03-01.gz |wc -l
10
```
2. in the trillian test results, no vncPassword is found
```
$ grep vncPassword management-server.log |wc -l
0
```

**Comment by kiranchavala** [comment]
@borisstoyanov  @DaanHoogland 

Tested this  LGTM 

on 4.17.2 build

There is vncPassword parameter getting passed to the vm when it starts up 

~~~

2023-03-02 11:28:58,873 DEBUG [c.c.a.t.Request] (AgentManager-Handler-20:null) (logid:) Seq 2-7958142016540377725: Processing:  { Ans: , MgmtId: 32986993000843, via: 2, Ver: v1, Flags: 10, [{"com.cloud.agent.api.StartAnswer":{"vm":{"id":"3","name":"i-2-3-VM","state":"Starting","type":"User","cpus":"1","minSpeed":"250","maxSpeed":"500","minRam":"(512.00 MB) 536870912","maxRam":"(512.00 MB) 536870912","arch":"x86_64","os":"CentOS 5.5 (64-bit)","platformEmulator":"CentOS 5.5","bootArgs":"","enableHA":"false","limitCpuUse":"false","enableDynamicallyScaleVm":"false","**vncPassword":"3a54p4tPNbDxy**5JN9FtmMQ","vncAddr":"10.0.32.176","params":{"deployvm":"true","cpuOvercommitRatio":"2.0","m

~~~

or Pr-7291 build , 

There is no " vncPassword " parameter getting passed to the vm when it starts up 

~~~
2023-03-02 12:10:42,413 DEBUG [c.c.a.t.Request] (AgentManager-Handler-15:null) (logid:) Seq 1-1401463909042356305: Processing:  { Ans: , MgmtId: 32989408919868, via: 1, Ver: v1, Flags: 10, [{"com.cloud.agent.api.StartAnswer":{"vm":{"id":"3","name":"i-2-3-VM","state":"Starting","type":"User","cpus":"1","minSpeed":"250","maxSpeed":"500","minRam":"(512.00 MB) 536870912","maxRam":"(512.00 MB) 536870912","arch":"x86_64","os":"CentOS 5.5 (64-bit)","platformEmulator":"CentOS 5.5","bootArgs":"","enableHA":"false","limitCpuUse":"false","enableDynamicallyScaleVm":"false","vncAddr":"10.0.32.168","params":{"cpuOvercommitRatio":"2.0","memoryOvercommitRatio":"1.0","Message.ReservedCapacityFreed.Flag":"false"},"uuid":"c977c7bc-21c0-4795-bfe2-4f9fd0d2b989","enterHardwareSetup":"false","disks":[{"data":{"org.apache.cloudstack.storage.to.VolumeObjectTO":{"uuid":"75e12f98-2e34-43dd-903d-2574fc008549","volumeType":"ROOT","dataStore":{"org.apache.cloudstack.storage.to.PrimaryDataStoreTO":{"uuid":"33be8404-a958-303b-b44c-c867bd508902","name":"pr7291-t6256-kvm-centos7-kvm-pri2","id":"2","poolType":"NetworkFilesystem","host":"10.0.32.4","path":"/acs/primary/pr7291-t6256-kvm-centos7/pr7291-t6256-kvm-centos7-kvm-pri2","port":"2049","url":"NetworkFilesystem://10.0.32.4/acs/primary/pr7291-t6256-kvm-centos7/pr7291-t6256-kvm-centos7-kvm-pri2/?ROLE=Primary&STOREUUID=33be8404-a958-303b-b44c-c867bd508902","isManaged":"false"}},"name":"ROOT-3","size":"(8.00 GB) 8589934592","path":"75e12f98-2e34-43dd-903d-2574fc008549","volumeId":"3","vmName":"i-2-3-VM","accountId":"2","format":"QCOW2","provisioningType":"THIN","poolId":"2","id":"3","deviceId":"0","bytesReadRate":"(0 bytes) 0","bytesWriteRate":"(0 bytes) 0","iopsReadRate":"(0 bytes) 0","iopsWriteRate":"(0 bytes) 0","hypervisorType":"KVM","directDownload":"false","deployAsIs":"false"}},"diskSeq":"0","path":"75e12f98-2e34-43dd-903d-2574fc008549","type":"ROOT","_details":{"storageHost":"10.0.32.4","managed":"false","storagePort":"2049","storage.pool.disk.wait":"60","volumeSize":"(8.00 GB) 8589934592"}},{"data":{"org.apache.cloudstack.storage.to.TemplateObjectTO":{"id":"0","format":"ISO","accountId":"0","hvm":"false","bootable":"false","directDownload":"false","deployAsIs":"false"}},"diskSeq":"3","type":"ISO"}],"nics":[{"deviceId":"0","networkRateMbps":"200","defaultNic":"true","pxeDisable":"false","nicUuid":"26018f07-d3a7-489e-82b8-cbda940aa3a9","details":{"PromiscuousMode":"false","ForgedTransmits":"true","MacLearning":"false","MacAddressChanges":"true"},"dpdkEnabled":"false","uuid":"55fb1879-72cd-46e3-ad17-6ca5620c3677","ip":"10.1.1.74","netmask":"255.255.255.0","gateway":"10.1.1.1","mac":"02:00:3b:ee:00:01","dns1":"10.0.32.1","dns2":"8.8.8.8","broadcastType":"Vlan","type":"Guest","broadcastUri":"vlan://1221","isolationUri":"vlan://1221","isSecurityGroupEnabled":"false","name":"cloudbr1"}],"vcpuMaxLimit":"1","configDriveLocation":"SECONDARY","guestOsDetails":{},"extraConfig":{}},"result":"true","wait":"0","bypassHostMaintenance":"false"}}] }

~~~

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Pull request merged**
