### PR TITLE
Include 'removed' async jobs to check recurring snapshots

### PR DESCRIPTION
**Pull request by gmueller-ewerk**
## Description

While checking the state of all currently executing snapshots we also include those async jobs for the snapshots which have a 'removed' flag. Due to the fact that the snapshot scheduler need to find its related job to check its state and update the snapshot_schedule table accordingly.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by svenvogel** [comment]
@borisroman @rhtyd can you take a look?

**Comment by borisstoyanov** [comment]
Thanks for this PR @gmueller-ewerk let me run some tests
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by svenvogel** [comment]
@rhtyd @borisstoyanov can we merge it... there are no new changes.

**Comment by rhtyd** [comment]
@svenvogel we need another review to merge this, are you lgtm on it?

**Comment by svenvogel** [comment]
@rhtyd yes sure no problem. now we are two! :)

**Comment by DennisKonrad** [comment]
@rhtyd Hi, we tested this PR thoroughly. I think it's ready to merge LGTM

**Pull request merged**
