### PR TITLE
UI: Enable shared network with scope option in advanced zone with SG

### LINKED ISSUE #6293: Advanced Zone with SG: Add L2 networks and shared networks with Account/Project Scope
##### ISSUE TYPE

 * Improvement Request
 * Enhancement Request

##### COMPONENT NAME

~~~
API, UI, VR
~~~

##### CLOUDSTACK VERSION

~~~
4.16.1
~~~

##### CONFIGURATION

Cloudstack 4.16.1 Environment Advanced Zone with Security Groups. There is a shared default Network with a pool of IP addresses available for instances.

##### OS / ENVIRONMENT

RHEL 8.4 is used for cloudstack management servers and hosts.

##### SUMMARY

For some accounts, we need additional shared networks (with a specific VLAN ID) available only for the account (Scope: Account). Afaik defining the scope for an additional shared network was available on previous ACS versions. However, in ACS 4.16.1, I see only Scope: All. Another option would be defining an L2 network but this is not available for SG enabled Advanced Networks.

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #6293 

Some other changes:
- disable 'Create network' button for non-admin users in advanced zone with SG
- disable 'L2 network' tab for advanced zone with SG
- disable 'Create new network" button in instance wizard for non-admin users in advanced zone with SG
- disable 'Create network' button for all users in basic zone

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):

advanced zone with SG (root admin)

image

advanced zone with SG (domain admin)

image

Basic zone
image

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
tested in qa.c.c

**Comment by rohityadavcloud** [comment]
@weizhouapache have you checked against old/legacy UI and also:
- What if the env has several zones (both SG enabled and not)
- On the other hand, to show/hide security groups (tab or the create button) when any of the zones don't have SG enable?

Otherwise LGTM.

**Comment by weizhouapache** [comment]
> @weizhouapache have you checked against old/legacy UI and also:
> 
> * What if the env has several zones (both SG enabled and not)
> * On the other hand, to show/hide security groups (tab or the create button) when any of the zones don't have SG enable?
> 
> Otherwise LGTM.

@rohityadavcloud 
I have not tested with multiple zones.  zone with advanced and zone with advanced SG work well in my testing.

If there are multiple zone , for example 1 advanced zone and 1 advanced zone with SG, it is possible that domain admin and regular user can open the dialog, but cannot create shared networks in the advanced zone with SG.

I will test it. @DaanHoogland do not merge now.

(security groups tab is displayed only if there are zones with SG enabled, it works since primate UI was introduced in 4.15.0)

**Comment by weizhouapache** [comment]
@rohityadavcloud @DaanHoogland 
I made some changes for envs wth multiple zones with different types.

**Comment by DaanHoogland** [comment]
@blueorangutan ui

**Comment by DaanHoogland** [comment]
retested in qa

**Review by rohityadavcloud — APPROVED** [review]

**Pull request merged**
