### PR TITLE
Adding acl name to listNetworkAcl, listNetwork, listPrivateGateway, listVpcs responses

### PR DESCRIPTION
**Pull request by davidjumani**
## Description
Adding acl name to listNetworkAcl, listNetwork, listPrivateGateway, listVpcs responses

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?
```
(localhost) 🐱 > list vpcs
{
  "count": 1,
  "vpc": [
    {
      "network": [
        {
          "aclid": "4a8a6365-f329-11ea-9aba-50eb71576f75",
          "aclname": "default_allow",
           ..........
    }
  ]
}


(localhost) 🐱 > list networks
{
  "count": 1,
  "network": [
    {
      "aclid": "4a8a6365-f329-11ea-9aba-50eb71576f75",
      "aclname": "default_allow",
       ..........
    }
  ]
}


(localhost) 🐱 > list networkacls 
{
  "count": 4,
  "networkacl": [
    {
      "aclid": "4a8a6365-f329-11ea-9aba-50eb71576f75",
      "aclname": "default_allow",
       ..........
    }
  ]
}

(localhost) 🐱 > list privategateways 
{
  "count": 1,
  "privategateway": [
    {

      "aclid": "4a8a4c78-f329-11ea-9aba-50eb71576f75",
      "aclname": "default_deny",
       ..........
    }
  ]
}

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Review by rhtyd — APPROVED** [review]

**Review by shwstppr — APPROVED** [review]
LGTM on changes but new API response params don't have since tag @davidjumani

**Pull request merged**
