### PR TITLE
UI missing changes

### PR DESCRIPTION
**Pull request by harikrishna-patnala**
### Description

This PR fixes one missing label and one edit icon

Edit Template
image

Edit Backup offering icon
image

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by harikrishna-patnala** [comment]
@blueorangutan ui

**Comment by DaanHoogland** [comment]
@harikrishna-patnala @nvazquez can we put any missing labels in a single PR, please? (context: #7230 )

**Comment by harikrishna-patnala** [comment]
Yes @DaanHoogland tried to look for others, but for now I found only these.

**Comment by harikrishna-patnala** [comment]
shall I push this commit into #7230 PR ?

**Comment by DaanHoogland** [comment]
> shall I push this commit into #7230 PR ?

well @harikrishna-patnala , this has a better title, but I am inpartial to which we use in the end.

**Review by rohityadavcloud — APPROVED** [review]

**Review by DaanHoogland — APPROVED** [review]
clgtm,
tested in qa

**Pull request merged**
