### PR TITLE
Removed unnecessary @Local annotations and their respective imports

### PR DESCRIPTION
**Pull request by cristofolini**
Following @rafaelweingartner 's findings in PR #714 that many spring beans contained an @Local annotation, we've decided to remove said annotations and their imports from the ComponentLifecycleBase class and its subclasses seeking a reduction of a few hundred lines of useless code.

I had already opened a pull request for this (#853) but at some point my commit disappeared from the PR entirely, showing no new changes in code, which caused it to be merged automatically (with no changes).

### CODE REVIEW

**Comment by remibergsma** [comment]
LGTM, based on a set of tests that I run on this branch. Screenshot is from an experimental Jenkins job (that runs the same tests I did manually until now).

These test may not cover your change, all they do is show you didn't break them. Someone else needs to review the code.

screen shot 2015-11-23 at 11 13 16

**Comment by DaanHoogland** [comment]
LGTM, checked the code. It felt like skimming at times as 607 lines were removed ;) I don't think there is any problem though.

**Comment by DaanHoogland** [comment]
@cristofolini  github doesn't show JuniperSRXExternalFirewallElement. It has a syntax error. Did you compile this? and did you use -Dnoredist? that part would have probably revealed the error.

**Comment by rafaelweingartner** [comment]
@DaanHoogland, 
@cristofolini did not run a mvn build witth "-Dnoredist". Sadly, we did not realize that there were some projects that were not built without that parameter.

Sorry for the trouble.
From now on, we will make sure to run a "mvn clean install -Dnoredist -P developer,systemvm" to make sure that everything is ok, before we create a PR.

**Pull request merged**
