### PR TITLE
4.9 multiplex testing

### PR DESCRIPTION
**Pull request by rhtyd**
This merges several PRs in this PR, this is for speeding up test efforts.

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
Fixes most of the failures from test_volumes, which turns out to be env related.

Test Volume creation for all Disk Offerings (incl. custom) ... === TestName: test_01_create_volume | Status : FAILED ===
FAIL
Attach a created Volume to a Running VM ... === TestName: test_02_attach_volume | Status : SUCCESS ===
ok
Download a Volume attached to a VM ... === TestName: test_03_download_attached_volume | Status : SUCCESS ===
ok
Delete a Volume attached to a VM ... === TestName: test_04_delete_attached_volume | Status : SUCCESS ===
ok
Detach a Volume attached to a VM ... === TestName: test_05_detach_volume | Status : SUCCESS ===
ok
Download a Volume unattached to an VM ... === TestName: test_06_download_detached_volume | Status : SUCCESS ===
ok
Test resize (negative) non-existent volume ... === TestName: test_07_resize_fail | Status : SUCCESS ===
ok
Test resize a volume ... === TestName: test_08_resize_volume | Status : SUCCESS ===
ok
Delete a Volume unattached to an VM ... === TestName: test_09_delete_detached_volume | Status : SUCCESS ===
ok

**Comment by rhtyd** [comment]
CentOS6 pkg re-kicked.

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by borisstoyanov** [comment]
@rhtyd I'm on the Xen failures and just re-run the snapshots one and it passed. So I guess there was something wrong with the environment at that point 

```
Test Snapshot Root Disk ... === TestName: test_01_snapshot_root_disk | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 1 test in 241.647s

OK
```

**Comment by rhtyd** [comment]
Thanks @borisstoyanov I re ran that test too. I'm re-running failed tests and with Murali's fix. Most tests are green on KVM now, currently investigation vmware and xenserver environments.

**Comment by borisstoyanov** [comment]
Hi @mike-tutkowski @syed,  
I've been investigating the test failure from test_primary_storage.py: test_01_primary_storage_iscsi, and we came to a conclusion that iscsi attaches but it's not writeable. 

By any chance do you recall any change that might cause this? 


Here's the management log failing to create a hearbeat volume: 

```
2016-12-23 11:30:58,826 DEBUG [c.c.h.x.r.CitrixResourceBase] (DirectAgent-404:ctx-c95759e3) (logid:f96038aa) Setting up the heartbeat sr for host 10.2.2.33 and sr ca748d82-3668-9559-07ba-19ff94844ed0
2016-12-23 11:30:59,104 WARN  [c.c.h.x.r.w.x.CitrixModifyStoragePoolCommandWrapper] (DirectAgent-404:ctx-c95759e3) (logid:f96038aa) ModifyStoragePoolCommand add XenAPIException:Unable to setup heartbeat
 sr on SR ca748d82-3668-9559-07ba-19ff94844ed0 due to #6# Unable to create heartbeat volume hb-db2a4468-ef57-4936-9ccd-7b8f4c06d822 host:db2a4468-ef57-4936-9ccd-7b8f4c06d822 pool: 10.5.0.4/iqn.2016-10.l
ocal.marvin:tgt1/0
com.cloud.utils.exception.CloudRuntimeException: Unable to setup heartbeat sr on SR ca748d82-3668-9559-07ba-19ff94844ed0 due to #6# Unable to create heartbeat volume hb-db2a4468-ef57-4936-9ccd-7b8f4c06d
822
        at com.cloud.hypervisor.xenserver.resource.CitrixResourceBase.setupHeartbeatSr(CitrixResourceBase.java:4596)
        at com.cloud.hypervisor.xenserver.resource.wrapper.xenbase.CitrixModifyStoragePoolCommandWrapper.execute(CitrixModifyStoragePoolCommandWrapper.java:54)
        at com.cloud.hypervisor.xenserver.resource.wrapper.xenbase.CitrixModifyStoragePoolCommandWrapper.execute(CitrixModifyStoragePoolCommandWrapper.java:40)
        at com.cloud.hypervisor.xenserver.resource.wrapper.xenbase.CitrixRequestWrapper.execute(CitrixRequestWrapper.java:122)
        at com.cloud.hypervisor.xenserver.resource.CitrixResourceBase.executeRequest(CitrixResourceBase.java:1687)
        at com.cloud.agent.manager.DirectAgentAttache$Task.runInContext(DirectAgentAttache.java:315)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2016-12-23 11:30:59,111 DEBUG [c.c.a.m.DirectAgentAttache] (DirectAgent-404:ctx-c95759e3) (logid:f96038aa) Seq 1-4225502350380368681: Response Received:
2016-12-23 11:30:59,111 DEBUG [c.c.a.t.Request] (DirectAgent-404:ctx-c95759e3) (logid:f96038aa) Seq 1-4225502350380368681: Processing:  { Ans: , MgmtId: 7003044906821, via: 1(pr1854-t722-xenserver-65sp1
-xs1), Ver: v1, Flags: 10, [{"com.cloud.agent.api.Answer":{"result":false,"details":"ModifyStoragePoolCommand add XenAPIException:Unable to setup heartbeat sr on SR ca748d82-3668-9559-07ba-19ff94844ed0
due to #6# Unable to create heartbeat volume hb-db2a4468-ef57-4936-9ccd-7b8f4c06d822 host:db2a4468-ef57-4936-9ccd-7b8f4c06d822 pool: 10.5.0.4/iqn.2016-10.local.marvin:tgt1/0","wait":0}}] }
2016-12-23 11:30:59,111 DEBUG [c.c.a.t.Request] (catalina-exec-18:ctx-ecf415b7 ctx-29dead47 ctx-1fd26575) (logid:f96038aa) Seq 1-4225502350380368681: Received:  { Ans: , MgmtId: 7003044906821, via: 1(pr
1854-t722-xenserver-65sp1-xs1), Ver: v1, Flags: 10, { Answer } }
2016-12-23 11:30:59,111 DEBUG [c.c.a.m.AgentManagerImpl] (catalina-exec-18:ctx-ecf415b7 ctx-29dead47 ctx-1fd26575) (logid:f96038aa) Details from executing class com.cloud.agent.api.ModifyStoragePoolComm
and: ModifyStoragePoolCommand add XenAPIException:Unable to setup heartbeat sr on SR ca748d82-3668-9559-07ba-19ff94844ed0 due to #6# Unable to create heartbeat volume hb-db2a4468-ef57-4936-9ccd-7b8f4c06
d822 host:db2a4468-ef57-4936-9ccd-7b8f4c06d822 pool: 10.5.0.4/iqn.2016-10.local.marvin:tgt1/0
2016-12-23 11:30:59,112 WARN  [o.a.c.alerts] (catalina-exec-18:ctx-ecf415b7 ctx-29dead47 ctx-1fd26575) (logid:f96038aa)  alertType:: 7 // dataCenterId:: 1 // podId:: 1 // clusterId:: null // message:: U
nable to attach storage pool11 to the host1
2016-12-23 11:30:59,120 WARN  [o.a.c.s.d.l.CloudStackPrimaryDataStoreLifeCycleImpl] (catalina-exec-18:ctx-ecf415b7 ctx-29dead47 ctx-1fd26575) (logid:f96038aa) Unable to establish a connection between Ho
st[-1-Routing] and org.apache.cloudstack.storage.datastore.PrimaryDataStoreImpl@70894d68
com.cloud.utils.exception.CloudRuntimeException: Unable establish connection from storage head to storage pool 11 due to ModifyStoragePoolCommand add XenAPIException:Unable to setup heartbeat sr on SR c
a748d82-3668-9559-07ba-19ff94844ed0 due to #6# Unable to create heartbeat volume hb-db2a4468-ef57-4936-9ccd-7b8f4c06d822 host:db2a4468-ef57-4936-9ccd-7b8f4c06d822 pool: 10.5.0.4/iqn.2016-10.local.marvin
:tgt1/011
        at org.apache.cloudstack.storage.datastore.provider.DefaultHostListener.hostConnect(DefaultHostListener.java:75)
        at com.cloud.storage.StorageManagerImpl.connectHostToSharedPool(StorageManagerImpl.java:955)
        at org.apache.cloudstack.storage.datastore.lifecycle.CloudStackPrimaryDataStoreLifeCycleImpl.attachCluster(CloudStackPrimaryDataStoreLifeCycleImpl.java:414)
        at com.cloud.storage.StorageManagerImpl.createPool(StorageManagerImpl.java:709)
        at com.cloud.storage.StorageManagerImpl.createPool(StorageManagerImpl.java:199)
        at org.apache.cloudstack.api.command.admin.storage.CreateStoragePoolCmd.execute(CreateStoragePoolCmd.java:163)
        at com.cloud.api.ApiDispatcher.dispatch(ApiDispatcher.java:150)
        at com.cloud.api.ApiServer.queueCommand(ApiServer.java:709)
        at com.cloud.api.ApiServer.handleRequest(ApiServer.java:533)
        at com.cloud.api.ApiServlet.processRequestInContext(ApiServlet.java:299)
        at com.cloud.api.ApiServlet$1.run(ApiServlet.java:129)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
        at com.cloud.api.ApiServlet.processRequest(ApiServlet.java:126)
        at com.cloud.api.ApiServlet.doGet(ApiServlet.java:88)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:555)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:299)
        at org.apache.coyote.http11.Http11NioProcessor.process(Http11NioProcessor.java:889)
        at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:732)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:2274)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2016-12-23 11:30:59,121 WARN  [o.a.c.s.d.l.CloudStackPrimaryDataStoreLifeCycleImpl] (catalina-exec-18:ctx-ecf415b7 ctx-29dead47 ctx-1fd26575) (logid:f96038aa) No host can access storage pool org.apache.
cloudstack.storage.datastore.PrimaryDataStoreImpl@70894d68 on cluster 1
2016-12-23 11:30:59,127 DEBUG [c.c.s.StorageManagerImpl] (catalina-exec-18:ctx-ecf415b7 ctx-29dead47 ctx-1fd26575) (logid:f96038aa) Failed to add data store: Failed to access storage pool
com.cloud.utils.exception.CloudRuntimeException: Failed to access storage pool
        at org.apache.cloudstack.storage.datastore.lifecycle.CloudStackPrimaryDataStoreLifeCycleImpl.attachCluster(CloudStackPrimaryDataStoreLifeCycleImpl.java:427)
        at com.cloud.storage.StorageManagerImpl.createPool(StorageManagerImpl.java:709)
        at com.cloud.storage.StorageManagerImpl.createPool(StorageManagerImpl.java:199)
        at org.apache.cloudstack.api.command.admin.storage.CreateStoragePoolCmd.execute(CreateStoragePoolCmd.java:163)
        at com.cloud.api.ApiDispatcher.dispatch(ApiDispatcher.java:150)
        at com.cloud.api.ApiServer.queueCommand(ApiServer.java:709)
        at com.cloud.api.ApiServer.handleRequest(ApiServer.java:533)
        at com.cloud.api.ApiServlet.processRequestInContext(ApiServlet.java:299)
        at com.cloud.api.ApiServlet$1.run(ApiServlet.java:129)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
        at com.cloud.api.ApiServlet.processRequest(ApiServlet.java:126)
        at com.cloud.api.ApiServlet.doGet(ApiServlet.java:88)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:555)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:299)
        at org.apache.coyote.http11.Http11NioProcessor.process(Http11NioProcessor.java:889)
        at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:732)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:2274)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2016-12-23 11:30:59,129 DEBUG [c.c.s.StorageManagerImpl] (catalina-exec-18:ctx-ecf415b7 ctx-29dead47 ctx-1fd26575) (logid:f96038aa) Failed to clean up storage pool: null
2016-12-23 11:30:59,130 INFO  [c.c.a.ApiServer] (catalina-exec-18:ctx-ecf415b7 ctx-29dead47 ctx-1fd26575) (logid:f96038aa) Failed to add data store: Failed to access storage pool
2016-12-23 11:30:59,130 DEBUG [c.c.a.ApiServlet] (catalina-exec-18:ctx-ecf415b7 ctx-29dead47 ctx-1fd26575) (logid:f96038aa) ===END===  10.5.0.4 -- GET  apiKey=LIN6rqXuaJwMPfGYFh13qDwYz5VNNz1J2J6qIOWcd3oLQOq0WtD4CwRundBL6rzXToa3lQOC_vKjI3nkHtiD8Q&name=Test+iSCSI&url=iscsi%3A%2F%2F10.5.0.4%2Fiqn.2016-10.local.marvin%3Atgt1%2F0&podid=8b409e63-f298-4113-a23b-0700a8dfc76d&clusterid=4b2458e0-9da9-4a99-987e-3d2cd6f2f0a9&zoneid=8d414040-93d1-47d9-8706-7a15f3c1dfb6&command=createStoragePool&signature=eLjbko60Wfjj4iny2w0ktjvKcK4%3D&response=json
2016-12-23 11:30:59,143 DEBUG [c.c.a.ApiServlet] (catalina-exec-16:ctx-9fd311e8) (logid:2d0d3d40) ===START===  10.5.0.4 -- GET  apiKey=LIN6rqXuaJwMPfGYFh13qDwYz5 
```

Marvin test failure: 

`2016-12-23 11:30:58,520 - CRITICAL - EXCEPTION: test_01_primary_storage_iscsi: ['Traceback (most recent call last):\n', '  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run\n    testMethod()\n', '  File "/marvin/tests/smoke/test_primary_storage.py", line 199, in test_01_primary_storage_iscsi\n    podid=self.pod.id\n', '  File "/usr/lib/python2.7/site-packages/marvin/lib/base.py", line 2732, in create\n    return StoragePool(apiclient.createStoragePool(cmd).__dict__)\n', '  File "/usr/lib/python2.7/site-packages/marvin/cloudstackAPI/cloudstackAPIClient.py", line 2537, in createStoragePool\n    response = self.connection.marvinRequest(command, response_type=response, method=method)\n', '  File "/usr/lib/python2.7/site-packages/marvin/cloudstackConnection.py", line 379, in marvinRequest\n    raise e\n', 'CloudstackAPIException: Execute cmd: createstoragepool failed, due to: errorCode: 530, errorText:Failed to add data store: Failed to access storage pool\n']`

CC: @rhtyd @PaulAngus

**Comment by borisstoyanov** [comment]
I've just re-run the test_templates failures and it has passed.
```
Test create public & private template ... === TestName: test_01_create_template | Status : SUCCESS ===
ok
Test when createTemplate is used to create templates having the same name all of them get ... === TestName: test_CreateTemplateWithDuplicateName | Status : SUCCESS ===
ok
Test Edit template ... === TestName: test_02_edit_template | Status : SUCCESS ===
ok
Test delete template ... === TestName: test_03_delete_template | Status : SUCCESS ===
ok
Test for extract template ... === TestName: test_04_extract_template | Status : SUCCESS ===
ok
Update & Test for template permissions ... === TestName: test_05_template_permissions | Status : SUCCESS ===
ok
Test for copy template from one zone to another ... SKIP: Not enough zones available to perform copy template
Test only public templates are visible to normal user ... === TestName: test_07_list_public_templates | Status : SUCCESS ===
ok
Test System templates are not visible to normal user ... === TestName: test_08_list_system_templates | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 9 tests in 847.599s

OK (SKIP=1)
```

I guess XenServer test results are looking good, except from the iscsi issue listed up.

**Comment by rhtyd** [comment]
I re-ran all tests, most of them are passing except for rvr/vpc related and the one iscsi/xenserver related:

Xenserver:
Test create public & private template ... === TestName: test_01_create_template | Status : SUCCESS ===
ok
Test when createTemplate is used to create templates having the same name all of them get ... === TestName: test_CreateTemplateWithDuplicateName | Status : SUCCESS ===
ok
Test Edit template ... === TestName: test_02_edit_template | Status : SUCCESS ===
ok
Test delete template ... === TestName: test_03_delete_template | Status : SUCCESS ===
ok
Test for extract template ... === TestName: test_04_extract_template | Status : SUCCESS ===
ok
Update & Test for template permissions ... === TestName: test_05_template_permissions | Status : SUCCESS ===
ok
Test for copy template from one zone to another ... SKIP: Not enough zones available to perform copy template
Test only public templates are visible to normal user ... === TestName: test_07_list_public_templates | Status : SUCCESS ===
ok
Test System templates are not visible to normal user ... === TestName: test_08_list_system_templates | Status : SUCCESS ===
ok
Test Snapshot Root Disk ... === TestName: test_01_snapshot_root_disk | Status : SUCCESS ===
ok
Test primary storage pools - XEN. Not Supported for kvm,hyperv,vmware ... === TestName: test_01_primary_storage_iscsi | Status : EXCEPTION ===
ERROR
Test primary storage pools - XEN, KVM, VMWare. Not Supported for hyperv ... === TestName: test_01_primary_storage_nfs | Status : SUCCESS ===
ok


Vmware:
Test List secondary storage VMs ... === TestName: test_01_list_sec_storage_vm | Status : SUCCESS ===
ok
Test List console proxy VMs ... === TestName: test_02_list_cpvm_vm | Status : SUCCESS ===
ok
Test SSVM Internals ... === TestName: test_03_ssvm_internals | Status : SUCCESS ===
ok
Test CPVM Internals ... === TestName: test_04_cpvm_internals | Status : SUCCESS ===
ok
Test stop SSVM ... === TestName: test_05_stop_ssvm | Status : SUCCESS ===
ok
Test stop CPVM ... === TestName: test_06_stop_cpvm | Status : SUCCESS ===
ok
Test reboot SSVM ... === TestName: test_07_reboot_ssvm | Status : SUCCESS ===
ok
Test reboot CPVM ... === TestName: test_08_reboot_cpvm | Status : SUCCESS ===
ok
Test destroy SSVM ... === TestName: test_09_destroy_ssvm | Status : SUCCESS ===
ok
Test destroy CPVM ... === TestName: test_10_destroy_cpvm | Status : SUCCESS ===
ok
Test create public & private template ... === TestName: test_01_create_template | Status : SUCCESS ===
ok
Test when createTemplate is used to create templates having the same name all of them get ... === TestName: test_CreateTemplateWithDuplicateName | Status : SUCCESS ===
ok
Test Edit template ... === TestName: test_02_edit_template | Status : SUCCESS ===
ok
Test delete template ... === TestName: test_03_delete_template | Status : SUCCESS ===
ok
Test for extract template ... === TestName: test_04_extract_template | Status : SUCCESS ===
ok
Update & Test for template permissions ... === TestName: test_05_template_permissions | Status : SUCCESS ===
ok
Test for copy template from one zone to another ... SKIP: Not enough zones available to perform copy template
Test only public templates are visible to normal user ... === TestName: test_07_list_public_templates | Status : SUCCESS ===
ok
Test System templates are not visible to normal user ... === TestName: test_08_list_system_templates | Status : SUCCESS ===
ok
Check the password file in the Router VM ... === TestName: test_isolate_network_password_server | Status : SUCCESS ===
ok
Test Volume creation for all Disk Offerings (incl. custom) ... === TestName: test_01_create_volume | Status : SUCCESS ===
ok
Attach a created Volume to a Running VM ... === TestName: test_02_attach_volume | Status : SUCCESS ===
ok
Download a Volume attached to a VM ... === TestName: test_03_download_attached_volume | Status : SUCCESS ===
ok
Delete a Volume attached to a VM ... === TestName: test_04_delete_attached_volume | Status : SUCCESS ===
ok
Detach a Volume attached to a VM ... === TestName: test_05_detach_volume | Status : SUCCESS ===
ok
Download a Volume unattached to an VM ... === TestName: test_06_download_detached_volume | Status : SUCCESS ===
ok
Test resize (negative) non-existent volume ... SKIP: Resize Volume is unsupported on VmWare and Hyper-V
Test resize a volume ... SKIP: Resize Volume is unsupported on VmWare and Hyper-V
Delete a Volume unattached to an VM ... === TestName: test_09_delete_detached_volume | Status : SUCCESS ===
ok
Test Site 2 Site VPN Across redundant VPCs ... === TestName: test_01_redundant_vpc_site2site_vpn | Status : SUCCESS ===
ok
Test Remote Access VPN in VPC ... 
=== TestName: test_01_vpc_remote_access_vpn | Status : SUCCESS ===
ok
Test Site 2 Site VPN Across VPCs ... === TestName: test_01_vpc_site2site_vpn | Status : SUCCESS ===
ok
Test create, assign, remove of an Internal LB with roundrobin http traffic to 3 vm's in a Single VPC ... === TestName: test_01_internallb_roundrobin_1VPC_3VM_HTTP_port80 | Status : SUCCESS ===
ok
Test create, assign, remove of an Internal LB with roundrobin http traffic to 3 vm's in a Redundant VPC ... === TestName: test_02_internallb_roundrobin_1RVPC_3VM_HTTP_port80 | Status : SUCCESS ===
ok
Test to verify access to loadbalancer haproxy admin stats page ... === TestName: test_03_vpc_internallb_haproxy_stats_on_all_interfaces | Status : SUCCESS ===
ok
Test to verify access to loadbalancer haproxy admin stats page ... === TestName: test_04_rvpc_internallb_haproxy_stats_on_all_interfaces | Status : SUCCESS ===
ok
test_01_vpc_privategw_acl (tests.smoke.test_privategw_acl.TestPrivateGwACL) ... === TestName: test_01_vpc_privategw_acl | Status : SUCCESS ===
ok
test_02_vpc_privategw_static_routes (tests.smoke.test_privategw_acl.TestPrivateGwACL) ... === TestName: test_02_vpc_privategw_static_routes | Status : SUCCESS ===
ok
test_03_vpc_privategw_restart_vpc_cleanup (tests.smoke.test_privategw_acl.TestPrivateGwACL) ... === TestName: test_03_vpc_privategw_restart_vpc_cleanup | Status : SUCCESS ===
ok
test_04_rvpc_privategw_static_routes (tests.smoke.test_privategw_acl.TestPrivateGwACL) ... === TestName: test_04_rvpc_privategw_static_routes | Status : FAILED ===
FAIL



KVM:
Test Volume creation for all Disk Offerings (incl. custom) ... === TestName: test_01_create_volume | Status : EXCEPTION ===
ERROR
Attach a created Volume to a Running VM ... === TestName: test_02_attach_volume | Status : SUCCESS ===
ok
Download a Volume attached to a VM ... === TestName: test_03_download_attached_volume | Status : SUCCESS ===
ok
Delete a Volume attached to a VM ... === TestName: test_04_delete_attached_volume | Status : SUCCESS ===
ok
Detach a Volume attached to a VM ... === TestName: test_05_detach_volume | Status : SUCCESS ===
ok
Download a Volume unattached to an VM ... === TestName: test_06_download_detached_volume | Status : SUCCESS ===
ok
Test resize (negative) non-existent volume ... === TestName: test_07_resize_fail | Status : SUCCESS ===
ok
Test resize a volume ... === TestName: test_08_resize_volume | Status : SUCCESS ===
ok
Delete a Volume unattached to an VM ... === TestName: test_09_delete_detached_volume | Status : SUCCESS ===
ok

**Comment by rhtyd** [comment]
Based on test results, I'll proceed with merging this.

I don't see any regressions, let's work on the iscsi issue in a separate PR? /cc @syed @murali-reddy @abhinandanprateek @borisstoyanov @mike-tutkowski @PaulAngus

**Comment by mike-tutkowski** [comment]
@rhtyd I think we can deal with this in another PR, as you suggest.

@syed Does any of that code look like something that might have been changed for archiving managed snapshots? I don't think I changed code there. Does any of that look familiar to you?

**Comment by rhtyd** [comment]
@mike-tutkowski @syed I was aiming at 4.9.1.0-rc1, and put this workaround for now: https://github.com/apache/cloudstack/pull/1863/files

**Pull request merged**
