### PR TITLE
Refer pod_ip_range_map table instead of host_pod_ref.description.

### PR DESCRIPTION
**Pull request by cl-k-takahashi**
## Description

Make `host_pod_ref` table satisfy 1NF by creating new table `pod_ip_range_map`
Fixes: #3762 

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

Now under test & fix

### CODE REVIEW

**Comment by cl-k-takahashi** [comment]
[TESTS]
Migration from current host_pod_ref.description seems to work correctly. Test cases are:
233.233.233.233-233.233.233.234-0-untagged
233.233.233.233-233.233.233.234-1-untagged
233.233.233.233-233.233.233.234-0-99999,233.233.233.235-233.233.233.236-1-untagged

Operations below seems to work correctly:
1. Adding a new pod
2. Add new ip range for a pod.
3. Remove an existing ip range in a pod.

CPVM and SSVM are working with correct private IP address.
Virtual Routers are not tested yet.

**Comment by cl-k-takahashi** [comment]
VR is working with correct private IP address.

**Comment by cl-k-takahashi** [comment]
This PR is now ready for reviewing.

**Comment by cl-k-takahashi** [comment]
I added signature for my commit.

**Comment by DaanHoogland** [comment]
@cl-k-takahashi , I like your code and your thinking. I am worried that we are taking a risk here that is not going to profit us. Do you envision any future enhancements that justify this change? Otherwise this is a hard sell; not broke, no fix.
That is not a 👎 by any means, btw. I'm all for it, given performance doesn't suffer.

**Comment by cl-k-takahashi** [comment]
I think you are right, because current code is working well. 
First, I wanted to make cloudstack support ipv6 addresses for pod and thought that keeping ipv6 addresses in host_pod_ref like "2001::1-2001::99-0-99999,233.233.233.235-233.233.233.236-1-untagged" is not a good idea.
So, I intended to split ipv4 range from `host_pod_ref` to `pod_ip_range_map` in this PR and create `pod_ip6_range_map` in future PR.
However, of course, this is my own opinion.
Keeping ipv6 addresses in `host_pod_ref` is an option, keeping ipv6 addresses in separate table is also an option and not supporting ipv6 pod ip range now is OK.

**Comment by DaanHoogland** [comment]
Hah, IPv6. ok, so there is a good future selling point for this improvement 🥇 
@wido can you comment?

**Comment by cl-k-takahashi** [comment]
@wido Gentle ping...

**Comment by wido** [comment]
@GabrielBrascher Can you take a look at this PR?

**Comment by rhtyd** [comment]
@cl-k-takahashi can you fix the conflicts? Thanks.

**Comment by DaanHoogland** [comment]
@cl-k-takahashi can you rebase and force push, please?

**Comment by cl-k-takahashi** [comment]
@DaanHoogland I'm sorry for noticing your reply late.
I'll try to fix it.

**Comment by GabrielBrascher** [comment]
Sorry for the late check on this one, it got out of my radar.

Well, the main idea is interesting, IPv6 enhancements is always a big motivation :+1:. It adds the risky of DB architecture changes but we definitelly need to enhance the DB for supporting IPv6. I will take a deeper look at this one. Would need to run a few tests (advanced, advanced with SG supporting ipv6, basic?).

@DaanHoogland @andrijapanicsb 4.14 is almost good to go, should we postpone this to 4.15 to avoid any risks?

**Comment by andrijapanicsb** [comment]
We are already frozen (for some time now...) for any new features for 4.14, so yes, please plan it for 4.15. Thx

**Comment by DaanHoogland** [comment]
@GabrielBrascher as you are now active on the IPv6 support again, can you gicve this another look?
@cl-k-takahashi can you rebase on latest master, please?

**Comment by DaanHoogland** [comment]
ping @cl-k-takahashi (and @GabrielBrascher )

**Comment by rhtyd** [comment]
ping @cl-k-takahashi can you help fix the conflicts? Thanks.

**Comment by sureshanaparti** [comment]
Hi @cl-k-takahashi can you resolve the conflicts. thanks.

**Comment by rohityadavcloud** [comment]
ping @andrijapanicsb @cl-k-takahashi cc @nvazquez - is this PR still applicable or can be closed?

**Comment by rohityadavcloud** [comment]
@cl-k-takahashi  thank you for your PR contribution. Due to inactivity on the PR for more than two years and unresolved conflicts, I'm closing this PR. If you've time and interest please do raise a new PR, thanks again.

**Pull request closed without merging**
