### PR TITLE
Check all mgt server connectivity

### PR DESCRIPTION
**Pull request by ravening**
## Description

Check all mgt server connectivity

    Currently ssvm checks connectivity only for one mgt server.
    Since we can have multiple mgt servers using comma separated
    list, make the change in script so that it checks for connectivity
    for all mgt servers

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

Before the fix

```
root@s-172-VM:~# /usr/local/cloud/systemvm/ssvm-check.sh
================================================
Management server is 10.135.122.10,10.135.122.15,10.135.122.16. Checking connectivity.
ERROR: Cannot connect to 10.135.122.10,10.135.122.15,10.135.122.16 port 8250
2020/11/03 12:58:34 socat[4508] E parseopts(): unknown option "10.135.122.15" <<<<<<<<<<<<<<
```

After the fix

```
root@s-175-VM:~# /usr/local/cloud/systemvm/ssvm-check.sh
================================================
Management server is 10.135.122.10,10.135.122.15,10.135.122.16. Checking connectivity.
Good: Can connect to management server 10.135.122.10 port 8250
Good: Can connect to management server 10.135.122.15 port 8250
Good: Can connect to management server 10.135.122.16 port 8250
================================================
Tests Complete. Look for ERROR or WARNING above.
```

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@ravening I'd call this a cleanup and not a bug would you? the check-ssvm script is not a runtime requirement but more like tooling, agree?

**Comment by DaanHoogland** [comment]
@PaulAngus @rhtyd this should/could go in even older versions than 4.15. not a runtime fix but a fix of the ssvm check script that will usually only run if the ssvm isn't working anyway.

**Comment by ravening** [comment]
> @ravening I'd call this a cleanup and not a bug would you? the check-ssvm script is not a runtime requirement but more like tooling, agree?

@DaanHoogland fine with me 🙂 feel free to add proper label

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@borisstoyanov @vladimirpetrov can you review/test?

**Review by weizhouapache — APPROVED** [review]

**Comment by DaanHoogland** [comment]
not in production code, 2 lgtm, test results provided -> merging

**Pull request merged**
