### PR TITLE
CLOUDSTACK-8928: While adding VMs to LB rule, default NIC IP is always displayed rather than the IP corresponding to the NIC where LB is being created

### PR DESCRIPTION
**Pull request by nitin-maharana**
While calling the listNics API, instead of sending the default nic id as parameter, it should send the network id as a parameter.

So, replaced that nicid parameter as networkid parameter.

### CODE REVIEW

**Comment by runseb** [comment]
@nitin-maharana Any automated tests for this ? if not, can you spend the time to write some. thanks

**Comment by nitin-maharana** [comment]
@runseb I think there is no automated tests for this. I will try to write one. Thanks.

**Comment by remibergsma** [comment]
@nitin-maharana Any update on this?

**Comment by nitin-maharana** [comment]
@remibergsma I was busy in some other works. Within 3-4 days I will work on this and will give an update. Thank you.

**Comment by nitin-maharana** [comment]
Hi @runseb @remibergsma I don't understand how to write a test for this. If you have any idea of how to write one, please help me out. Thanks.

**Comment by karuturi** [comment]
great find @nitin-maharana 
manually tested the fix
In my setup, I had a vm with two nics 
isolated1 - 	10.1.1.14 - default
isolated 2 - 	10.1.1.187 - non default

When I add a LB rule in network isolated2 for the VM, this is API call before the change and it failed.
screen shot 2015-11-02 at 4 38 35 pm

After the fix, it took the right IP and succeeded. 
screen shot 2015-11-02 at 4 49 11 pm

:+1: LGTM

**Comment by remibergsma** [comment]
Nice small fix, LGTM.

**Comment by nitin-maharana** [comment]
Thanks @karuturi @remibergsma.

**Pull request merged**
