### PR TITLE
UI - Fixes search error in selectbox

### PR DESCRIPTION
**Pull request by utchoang**
### Description

In select boxes containing resource-icon, when entering input a search, an error occurs.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### Screenshots (if appropriate):
BEFORE:
image
image

AFTER:
image

### CODE REVIEW

**Comment by Pearl1594** [comment]
@blueorangutan ui

**Review by rhtyd — APPROVED** [review]
Needs testing, LGTM

**Comment by Pearl1594** [comment]
Thanks @utchoang for identifying this issue.  There are some places where this fix may be needed to be extended to:
1. CreateVolume -> Zones Dropdown 
2. UploadVolume -> Zones Dropdown
3. RegisterVolume -> Zones Dropdown
4. ReinstallVM -> Templates Dropdown (may be required to be changed in AutogenView)
5. CreateL2NetworkForm -> zones dropdown
6. CreateVpc -> Zone dropdown
7. RegisterOrUploadTemplate - zones dropdown (for both registration and upload)
8. RegisterOrUploadIso - zones dropdown (for both)
9. PodAdd - zones dropdown 
10. ClusterAdd - zones dropdown
11. HostAdd - zones dropdown
12. AddPrimaryStorage - zones
13. AddSecondaryStorage - zones

**Comment by utchoang** [comment]
@blueorangutan ui

**Review by DaanHoogland — APPROVED** [review]
tests good

**Review by nvazquez — APPROVED** [review]
LGTM thanks @utchoang

**Pull request merged**
