### PR TITLE
ui-primary-storage: hide provider if Linstor protocol

### PR DESCRIPTION
**Pull request by rp-**
### Description
If Linstor protocol is selected it makes no sense to show other
providers as Linstor only works with the Linstor provider.

This was removed with the fix for #5613, that probably resulted from a
bad merge resolving from my part.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### How Has This Been Tested?
Clicked through local served vui ui -> add primary storage

### CODE REVIEW

**Comment by rp-** [comment]
I added another fix for the setup-wizard, which didn't set the correct provider for Linstor and would have failed.

**Comment by GabrielBrascher** [comment]
@blueorangutan ui

**Review by utchoang — APPROVED** [review]
LGTM!

**Review by GabrielBrascher — APPROVED** [review]
LGTM

**Pull request merged**
