### PR TITLE
Fix wrong logger class in *Cmd.java

### PR DESCRIPTION
**Pull request by davidjumani**
### Description

This PR changes the incorrect class name used in the logger in ListHypervisorsCmd

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan package

**Review by sureshanaparti — APPROVED** [review]
good catch, LGTM

**Review by weizhouapache — APPROVED** [review]

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan test

**Comment by davidjumani** [comment]
@blueorangutan test

**Review by harikrishna-patnala — APPROVED** [review]

**Review by rhtyd — APPROVED** [review]
LGTM - however, the standard practice (that is inconsistent in our codebase) is to pass the class itself and not class's name. For example:
```
Logger.getLogger(ListTrafficMonitorsCmd.class);
```

**Comment by rhtyd** [comment]
Smoketests are not required as changes are in logger only; pkging and travis passed.

**Pull request merged**
