### PR TITLE
Removed unused vars from pom file

### PR DESCRIPTION
**Pull request by Spaceman1984**
## Description

Just some cleanup, these vars in the pom file are not being referenced from anywhere.

cs.axis2.version
cs.jstl-api.version
cs.rampart.version
cs.xml-apis.version

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [X] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

I ran a build after removing these vars and there were no issues.

### CODE REVIEW

**Comment by Spaceman1984** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
no runtime code changed, packaging works, two lgtm, merging

**Pull request merged**
