### PR TITLE
novnc: Accept new novnc client and disconnect old session

### LINKED ISSUE #4550: Potential security issue with novnc console
The url in iframe of novnc console can be used without user login.

When open a vm console, and open the source of page, we get the real link of novnc console.
we are able to access the novnc console on other browsers/servers/ via the link, without user login.

This is a potential security issue.

We have two options
(1) add source IP of client to encrypted token, and check the client IP after token decryption when access the vm console.

we need to make sure
- IP to management server and CPVM (console proxy vm) are same.
- If the new browser/session has same outgoing IP as old session, it will still be able to access the vm console.

to be clear, these two files need to be changed
https://github.com/apache/cloudstack/blob/master/server/src/main/java/com/cloud/servlet/ConsoleProxyClientParam.java
and
https://github.com/apache/cloudstack/blob/master/services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxyClientParam.java

(2) save the access ticket to database
when vm console, access ticket will be generated and saved into database.

When access the console, management server will check the params to see if vm is valid and access ticket is not expired.,etc.
It will also check if token is valid and has been not used.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
NoVNC console
~~~

##### CLOUDSTACK VERSION

~~~
4.15/master
~~~

##### STEPS TO REPRODUCE

1. open a vm console
example:  
image

2. view the source of the page
example
```
<html><title>v-1-VM</title><frameset><frame src="https://10-135-126-207.cloud.leaseweb.net/resource/noVNC/vnc.html?port=8080&token=I-QW-IpdDhf3i82rJP_WctztYaq15O6ZP1Mya9F1VspNwDHDhXhQjRqO-ubZMM6YwJkfDNNEShT1K1XZmrnZvmv9ro504qoPqEuC9go5UlrQqBdJga-DAWaFKg0pv_QGo3xhGy4VSNCuj_N86ILC8wAQjmaqbSxyqFFfAlEc8UHxuyGiZG4YpHNnM6je3V82IV555AfnA1-3oyXh5tp9X-Bd7zeXRGIprt7_lwTnGxLgvdk06AoGseD4YabpB_aJLpvx3RfxuHD7hR1IrOrl9g"></frame></frameset></html>

```
3. open the link on other server. 
It will not work at the first time, but works after refresh (related to #4531 )

image

##### EXPECTED RESULTS

~~~
The link in page source should NOT work in other servers, without login
~~~

##### ACTUAL RESULTS

~~~
We are able to access the vm console via the URL in page source, without login.
~~~

### PR DESCRIPTION
**Pull request by ustcweizhou**
### Description

Fixes #4550 
This PR fixes an issue with novnc.

1. open a vm console
2. open the console in another session (other server, or different browser, or incognito window)
console will be stuck at Connecting
3. reload the page, vm console works. The console in step (1) is kicked out.

image

with this PR, the console in new session will work, the old session will be disconnected.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [X] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

with this pr, in new windows

image

### CODE REVIEW

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
Shouldn't new console kick the old one out?

**Comment by weizhouapache** [comment]
> Shouldn't new console kick the old one out?

@rhtyd in old ajax viewer, no

**Comment by rhtyd** [comment]
@ustcweizhou I think for the new novnc console, opening new window/session should close the previous on. 
@davidjumani can you review ?

**Comment by weizhouapache** [comment]
> @ustcweizhou I think for the new novnc console, opening new window/session should close the previous on.
> @davidjumani can you review ?

@rhtyd 
there are 3 options
(1) reject new session, and keep old session.
(2) accept new session, and kick out old session
(3) keep both sessions

The current behavior (reject the first new session and accept the second new session) seems to be bug.

we have (3) in our production but the implementation is different from master.
we think (1) is better than (2).

@davidjumani @DaanHoogland @PaulAngus @andrijapanicsb your opinion ?

**Comment by davidjumani** [comment]
@rhtyd Keeping both sessions should not be possible since an exclusive flag is sent when viewing the console
I'm for (1) - Reject the new and keep the old (just shorten the idle timeout)

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Last time I tried to do a remote vnd - if you try to connect, it usually bounces off older/other consoles and grants the new one to be opened. What's the behaviour in old console proxy? I think if we're rejecting the new console then a suitable msg but be shown.

**Comment by DaanHoogland** [comment]
without any extra €0.02, option 1 has my vote but rohit's remark is valid, something like "concole session active" should do. we don't have to be verbose.

**Comment by andrijapanic-dont-use-this-one** [comment]
Old VNC console is to kick out the previous session.

If we do the opposite, at very least a proper message should be shown to user, while making sure that an old session is terminated after some inactivity period, otherwise a colleague helping another colleague would not be able to take over the console session, which impacts usability. 

I'm personally for the old behaviour - kick off the old session (with a message explaining that another session has been established elsewhere) and allow the new session - it simply makes more sense and is more user-friendly.

**Comment by andrijapanicsb** [comment]
um, that was me above ^^^

**Comment by weizhouapache** [comment]
it looks difficult to get an decision.
would it be better to add global setting and let users choose ?

**Comment by andrijapanicsb** [comment]
+1, with perhaps defaulting to the old VNC console behaviour (which should have been implemented in the first place)

**Comment by rhtyd** [comment]
Agree, I would prefer the original behaviour; new console should kick the old one out.

**Comment by davidjumani** [comment]
New console should not be created if an existing one is open. Kicking out the old session will cause issues especially when there are multiple users trying to access the console

**Comment by andrijapanicsb** [comment]
That is how it worked so far @davidjumani and it allows colleagues who are jointly (remotely distanced people) troubleshooting a thing.

We all need to observe things from the user and usability perspective.

**Comment by shwstppr** [comment]
Do we have a consensus on this? Can we have new global setting to switch between new session kicking our ol session and new session being rejected?

**Comment by DaanHoogland** [comment]
> @rhtyd
> there are 3 options
> (1) reject new session, and keep old session.
> (2) accept new session, and kick out old session
> (3) keep both sessions
> 
> The current behavior (reject the first new session and accept the second new session) seems to be bug.

I think given discussions here we should go for a tristate configuration option, letting the operator decide. Given that (2) is the old behaviour it should then be the default. agree?

**Comment by rhtyd** [comment]
+1 makes sense, go with backward compatibility

**Comment by rhtyd** [comment]
ping @ustcweizhou can you make the changes? Or introduce a global setting to toggle behaviour?

**Comment by weizhouapache** [comment]
> ping @ustcweizhou can you make the changes? Or introduce a global setting to toggle behaviour?

@rhtyd I will work on it.

**Comment by weizhouapache** [comment]
@rhtyd @DaanHoogland @davidjumani 
as discussed, updated this pr to accept new vm console session and disconnect old session.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Review by davidjumani — APPROVED** [review]
Works like the old console. The old session is terminated when a new one is opened

**Review by rhtyd — APPROVED** [review]

**Pull request merged**
