### PR TITLE
Feature: Add support for DRS in a Cluster

### PR DESCRIPTION
**Pull request by vishesh92**
Documentation PR - https://github.com/apache/cloudstack-documentation/pull/334

### Description

This pull request (PR) implements a Distributed Resource Scheduler (DRS) for a CloudStack cluster. The primary objective of this feature is to enable automatic resource optimization and workload balancing within the cluster by live migrating the VMs as per configuration.
Administrators can also execute DRS manually for a cluster, using the UI or the API.
Adds support for two algorithms - `condensed` & `balanced`. Algorithms are pluggable allowing ACS Administrators to have customized control over scheduling.

**Implementation**
There are three top level components:

1. **Scheduler**
A timer task which:
* Generate DRS plan for clusters
* Process DRS plan
* Remove old DRS plan records

2. **DRS Execution**
We go through each VM in the cluster and use the specified algorithm to check if DRS is required and to calculate `cost`, `benefit` & `improvement` of migrating that VM to another host in the cluster. On the basis of `cost`, `benefit` & `improvement`, the best migration is selected for the current iteration and the VM is migrated. The maximum number of iterations (live migrations) possible on the cluster is defined by `drs.iterations` which is defined as a percentage (as a value between 0 and 1) of total number of workloads.

3. **Algorithm** 
Every algorithms implements two methods: 
    1.  `needsDrs` - to check if drs is required for cluster
    2.  `getMetrics` - to calculate `cost`, `benefit` & `improvement` of a migrating a VM to another host.

**Algorithms**
1. `Condensed` - Packs all the VMs on minimum number of hosts in the cluster.
2. `Balanced` - Distributes the VMs evenly across hosts in the cluster. 
Algorithms use `drs.level` to decide the amount of imbalance to allow in the cluster.

#### APIs Added
_listClusterDrsPlan_
> `id` - ID of the DRS plan to list
> `clusterid` - to list plans for a cluster id

_generateClusterDrsPlan_
>`id` - cluster id
>`iterations` - The maximum number of iterations in a DRS job defined as a percentage (as a value between 0 and 1) of total number of workloads. Defaults to value of cluster's `drs.iterations` setting.

_executeClusterDrsPlan_
> `id` - ID of the cluster for which DRS plan is to be executed.
> `migrateto` - This parameter specifies the mapping between a vm and a host to migrate that VM. Format of this parameter: `migrateto[vm-index].vm=<uuid>&migrateto[vm-index].host=<uuid>`.

#### Config Keys Added
 - ClusterDrsPlanExpireInterval
**Key** `drs.plan.expire.interval`
**Scope** `Global`
**Default Value** `30` days
**Description** The interval in days after which old DRS records will be cleaned up.

 - ClusterDrsEnabled
**Key** `drs.automatic.enable`
**Scope** `Cluster`
**Default Value** `false`
**Description** Enable/disable automatic DRS on a cluster.

 - ClusterDrsInterval
**Key** `drs.automatic.interval`
**Scope** `Cluster`
**Default Value** `60` minutes
**Description** The interval in minutes after which a periodic background thread will schedule DRS for a cluster.

 - ClusterDrsIterations
**Key** `drs.max.migrations`
**Scope** `Cluster`
**Default Value** `50`
**Description** Maximum number of live migrations in a DRS execution.

 - ClusterDrsAlgorithm
**Key** `drs.algorithm`
**Scope** `Cluster`
**Default Value** `condensed`
**Description** DRS algorithm to execute on the cluster. This PR implements two algorithms - `balanced` & `condensed`.

 - ClusterDrsLevel
**Key** `drs.imbalance`
**Scope** `Cluster`
**Default Value** `0.5`
**Description** Percentage (as a value between 0.0 and 1.0) of imbalance allowed in the cluster. 1.0 means no imbalance 
is allowed and 0.0 means imbalance is allowed.

 - ClusterDrsMetric
**Key** `drs.imbalance.metric`
**Scope** `Cluster`
**Default Value** `memory`
**Description** The cluster imbalance metric to use when checking the `drs.imbalance.threshold`. Possible values are `memory` and `cpu`.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [x] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
> @vishesh92 This is an awesome feature and I'm looking forward for it to be merged.
> 
> One improvement that would be useful, is to reserved resource for specific service offering. Let me clear it a bit up with an example, assume that a cluster have two hosts each with 64GB memory [`H1`, `H2`]. If we create two `32` GB vm [`V1`, `V2`] and place both of them on `H1` there would be a room to create a vm with `64` GB. So far so good.
> 
> But the thing is, the DRS might balance the cluster and moves one of the VMs to the `H2`. In that case, it is not possible to create a new VM with `64` GB memory although there is enough capacity to deploy one in the cluster.
> 
> It would be really nice if we can set a service offering uuid, and DRS reserves that capacity for new VMs. Let me know what do you think about this suggestion.

@soreana There will be two Algorithms that I am implementing as part of this feature.
1. Balanced
2. Condensed

Having a Condensed algorithm will solve your use case. Right?

I need to update the PR description, but I am introducing a configuration parameter `drs.level` which configures the threshold percentage after which DRS should run. Configuring this variable with balanced might also help with your use case.

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by soreana** [comment]
> > @vishesh92 This is an awesome feature and I'm looking forward for it to be merged.
> > One improvement that would be useful, is to reserved resource for specific service offering. Let me clear it a bit up with an example, assume that a cluster have two hosts each with 64GB memory [`H1`, `H2`]. If we create two `32` GB vm [`V1`, `V2`] and place both of them on `H1` there would be a room to create a vm with `64` GB. So far so good.
> > But the thing is, the DRS might balance the cluster and moves one of the VMs to the `H2`. In that case, it is not possible to create a new VM with `64` GB memory although there is enough capacity to deploy one in the cluster.
> > It would be really nice if we can set a service offering uuid, and DRS reserves that capacity for new VMs. Let me know what do you think about this suggestion.
> 
> @soreana There will be two Algorithms that I am implementing as part of this feature.
> 
> 1. Balanced
> 2. Condensed
> 
> Having a Condensed algorithm will solve your use case. Right?
> 
> I need to update the PR description, but I am introducing a configuration parameter `drs.level` which configures the threshold percentage after which DRS should run. Configuring this variable with balanced might also help with your use case.

@vishesh92 Thanks for explanation, that would work for us.

Another questions, when the DRS calculates the CPU and Memory, does it use the used value or the allocated value?

**Comment by vishesh92** [comment]
@soreana It's using the allocated value.

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan test

**Comment by vishesh92** [comment]
@blueorangutan test

**Comment by vishesh92** [comment]
@blueorangutan test keepEnv

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan test

**Comment by kishankavala** [comment]
can executeClusterDrsPlan API take planId as input?

**Comment by vishesh92** [comment]
> can executeClusterDrsPlan API take planId as input?

@kishankavala I thought about that as well. But executing a plan id might not be that useful in a busy cluster since the plans will become stale quite frequently.

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan test

**Comment by vishesh92** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Comment by vishesh92** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Comment by vishesh92** [comment]
@blueorangutan test rocky8 kvm-rocky8 keepEnv

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan test

**Comment by vishesh92** [comment]
@blueorangutan test rocky8 kvm-rocky8 keepEnv

**Comment by vishesh92** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan test

**Comment by kiranchavala** [comment]
@blueorangutan package

**Review by kiranchavala — APPROVED** [review]
LGTM, Tested the feature manually and its working fine

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by kiranchavala** [comment]
@blueorangutan test

**Comment by kiranchavala** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by alexandremattioli** [comment]
LGTM

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by shwstppr — APPROVED** [review]
Code LGTM

**Comment by vishesh92** [comment]
@blueorangutan test matrix

**Comment by shwstppr** [comment]
@vishesh92 apart from other failures on VMware, `test_cluster_drs.py` also failed. Can you please have a look?

```
2023-10-19 15:12:53,844 - CRITICAL - FAILED: test_02_balanced_drs_algorithm: ['Traceback (most recent call last):\n', '  File "/usr/lib64/python3.6/unittest/case.py", line 60, in testPartExecutor\n    yield\n', '  File "/usr/lib64/python3.6/unittest/case.py", line 622, in run\n    testMethod()\n', '  File "/marvin/tests/smoke/test_cluster_drs.py", line 259, in test_02_balanced_drs_algorithm\n    self.assertEqual(len(vm_to_dest_host_map), 1, msg="DRS plan should have 1 migrations")\n', '  File "/usr/local/lib/python3.6/site-packages/marvin/cloudstackTestCase.py", line 94, in assertEqual\n    super(cloudstackTestCase,self).assertEqual(first,second,msg)\n', '  File "/usr/lib64/python3.6/unittest/case.py", line 846, in assertEqual\n    assertion_func(first, second, msg=msg)\n', '  File "/usr/lib64/python3.6/unittest/case.py", line 839, in _baseAssertEqual\n    raise self.failureException(msg)\n', "AssertionError: 2 != 1 : b'DRS plan should have 1 migrations'\n"]
```

**Comment by vishesh92** [comment]
> @vishesh92 apart from other failures on VMware, `test_cluster_drs.py` also failed. Can you please have a look?
> 
> ```
> 2023-10-19 15:12:53,844 - CRITICAL - FAILED: test_02_balanced_drs_algorithm: ['Traceback (most recent call last):\n', '  File "/usr/lib64/python3.6/unittest/case.py", line 60, in testPartExecutor\n    yield\n', '  File "/usr/lib64/python3.6/unittest/case.py", line 622, in run\n    testMethod()\n', '  File "/marvin/tests/smoke/test_cluster_drs.py", line 259, in test_02_balanced_drs_algorithm\n    self.assertEqual(len(vm_to_dest_host_map), 1, msg="DRS plan should have 1 migrations")\n', '  File "/usr/local/lib/python3.6/site-packages/marvin/cloudstackTestCase.py", line 94, in assertEqual\n    super(cloudstackTestCase,self).assertEqual(first,second,msg)\n', '  File "/usr/lib64/python3.6/unittest/case.py", line 846, in assertEqual\n    assertion_func(first, second, msg=msg)\n', '  File "/usr/lib64/python3.6/unittest/case.py", line 839, in _baseAssertEqual\n    raise self.failureException(msg)\n', "AssertionError: 2 != 1 : b'DRS plan should have 1 migrations'\n"]

@shwstppr Not sure. But most likely happened due to some left over VM from a previous failed test. Let me run the tests again.

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan test vmware

**Comment by vishesh92** [comment]
@blueorangutan test vmware

**Comment by vishesh92** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by shwstppr** [comment]
Test results look good. Merging this. Will keep an eye on Health check PR

**Pull request merged**
