### PR TITLE
delete configuration `task.cleanup.retry.interval`

### PR DESCRIPTION
**Pull request by GaOrtiga**
### Description

The configuration `task.cleanup.retry.interval` is not used in any part of the code, so it was removed.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [X] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] Critical
- [ ] BLOCKER
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

I applied the changes in a local lab and verified that the build was successful.

### CODE REVIEW

**Review by stephankruggg — APPROVED** [review]

**Review by BryanMLima — APPROVED** [review]

**Comment by GaOrtiga** [comment]
@DaanHoogland I was checking the code in order to implement your suggestion and noticed that this configuration is actually not used in any part of the code. So I deleted it entirely.

**Review by stephankruggg — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by rohityadavcloud — APPROVED** [review]
LGTM, checked this is not referenced or used anywhere using basic git grep

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@GaOrtiga can you look at resolving the conflicts here, please?

**Comment by DaanHoogland** [comment]
lloks good btw

**Comment by GaOrtiga** [comment]
> @GaOrtiga can you look at resolving the conflicts here, please?

Done.

**Review by DaanHoogland — APPROVED** [review]

**Comment by GutoVeronezi** [comment]
Merging this one based on the approvals and test results.

**Pull request merged**
