### PR TITLE
CKS: fix upgrade of HA cluster

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes the smoke test failure test_08_upgrade_kubernetes_ha_cluster

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test keepEnv

**Comment by weizhouapache** [comment]
@blueorangutan test matrix

**Comment by weizhouapache** [comment]
@DaanHoogland @davidjumani @shwstppr 
the testing results look fine (all pass without smoke test failures). This is ready for review/testing

This PR has been tested with upgrade
- v1.23.3 -> v1.24.0
- v1.24.0 -> v1.25.0
- v1.25.0 -> v1.26.0

main ideas
(1) the current command to get k8s versions does not work well, see https://github.com/kubernetes/kubernetes/issues/115130, 
(2) therefore use 'kubectl get nodes' on the primary control master to get the k8s version of all nodes. However the version is not updated immediately after upgrade. so wait 10times*15seconds=150seconds (a bit too long) for the k8s version to be updated. For example during upgrade from v1.23.3 to v1.24.0, the output of k8s version is in the order:

- Ready,SchedulingDisabled with v1.23.3
- Ready with v1.23.3
- NotReady with v1.23.3
- Ready with v1.24.0

see below log
```
===== loop 228 at Fri 20 Jan 2023 04:33:45 PM UTC ======
cloud-1-23-3-control-185cf3d5af9   Ready,SchedulingDisabled   control-plane   3h37m   v1.23.3
===== loop 229 at Fri 20 Jan 2023 04:33:47 PM UTC ======
cloud-1-23-3-control-185cf3d5af9   Ready,SchedulingDisabled   control-plane   3h37m   v1.23.3
===== loop 230 at Fri 20 Jan 2023 04:33:48 PM UTC ======
cloud-1-23-3-control-185cf3d5af9   Ready,SchedulingDisabled   control-plane   3h37m   v1.23.3
===== loop 231 at Fri 20 Jan 2023 04:33:49 PM UTC ======
cloud-1-23-3-control-185cf3d5af9   Ready,SchedulingDisabled   control-plane   3h37m   v1.23.3

===== loop 232 at Fri 20 Jan 2023 04:33:50 PM UTC ======
cloud-1-23-3-control-185cf3d5af9   Ready    control-plane   3h37m   v1.23.3
===== loop 233 at Fri 20 Jan 2023 04:33:52 PM UTC ======
cloud-1-23-3-control-185cf3d5af9   Ready    control-plane   3h37m   v1.23.3
===== loop 234 at Fri 20 Jan 2023 04:33:53 PM UTC ======
cloud-1-23-3-control-185cf3d5af9   Ready    control-plane   3h37m   v1.23.3
===== loop 235 at Fri 20 Jan 2023 04:33:54 PM UTC ======
cloud-1-23-3-control-185cf3d5af9   Ready    control-plane   3h37m   v1.23.3
===== loop 236 at Fri 20 Jan 2023 04:33:56 PM UTC ======
cloud-1-23-3-control-185cf3d5af9   Ready    control-plane   3h37m   v1.23.3
===== loop 237 at Fri 20 Jan 2023 04:33:57 PM UTC ======
cloud-1-23-3-control-185cf3d5af9   Ready    control-plane   3h37m   v1.23.3
===== loop 238 at Fri 20 Jan 2023 04:33:58 PM UTC ======
cloud-1-23-3-control-185cf3d5af9   Ready    control-plane   3h37m   v1.23.3
===== loop 239 at Fri 20 Jan 2023 04:33:59 PM UTC ======
cloud-1-23-3-control-185cf3d5af9   Ready    control-plane   3h37m   v1.23.3
===== loop 240 at Fri 20 Jan 2023 04:34:01 PM UTC ======
cloud-1-23-3-control-185cf3d5af9   Ready    control-plane   3h37m   v1.23.3

===== loop 241 at Fri 20 Jan 2023 04:34:02 PM UTC ======
cloud-1-23-3-control-185cf3d5af9   NotReady   control-plane   3h37m   v1.24.0
===== loop 242 at Fri 20 Jan 2023 04:34:03 PM UTC ======
cloud-1-23-3-control-185cf3d5af9   NotReady   control-plane   3h37m   v1.24.0
===== loop 243 at Fri 20 Jan 2023 04:34:04 PM UTC ======
cloud-1-23-3-control-185cf3d5af9   NotReady   control-plane   3h37m   v1.24.0
===== loop 244 at Fri 20 Jan 2023 04:34:06 PM UTC ======
cloud-1-23-3-control-185cf3d5af9   NotReady   control-plane   3h37m   v1.24.0

===== loop 245 at Fri 20 Jan 2023 04:34:07 PM UTC ======
cloud-1-23-3-control-185cf3d5af9   Ready                      control-plane   3h37m   v1.24.0
===== loop 246 at Fri 20 Jan 2023 04:34:13 PM UTC ======
cloud-1-23-3-control-185cf3d5af9   Ready                      control-plane   3h37m   v1.24.0
===== loop 247 at Fri 20 Jan 2023 04:34:14 PM UTC ======
cloud-1-23-3-control-185cf3d5af9   Ready                      control-plane   3h37m   v1.24.0
===== loop 248 at Fri 20 Jan 2023 04:34:16 PM UTC ======
cloud-1-23-3-control-185cf3d5af9   Ready                      control-plane   3h37m   v1.24.0
===== loop 249 at Fri 20 Jan 2023 04:34:17 PM UTC ======
cloud-1-23-3-control-185cf3d5af9   Ready                      control-plane   3h38m   v1.24.0
===== loop 250 at Fri 20 Jan 2023 04:34:18 PM UTC ======
cloud-1-23-3-control-185cf3d5af9   Ready                      control-plane   3h38m   v1.24.0
```

**Review by shwstppr — APPROVED** [review]
LGTM

**Review by DaanHoogland — APPROVED** [review]
CLGTM

**Comment by DaanHoogland** [comment]
@shwstppr @davidjumani @weizhouapache Do you feel we need more testing that this? (as RM I am satisfied, as k8s nitwir, I don´t know)

**Pull request merged**
