### PR TITLE
packaging: Fix mkdir path for centos rpms

### PR DESCRIPTION
**Pull request by rhtyd**
## Description

This fixes the mkdir path `/usr/bin` for el6/7 rpms.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

## Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.

@blueorangutan package

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rafaelweingartner** [comment]
As @resmo said, I also did not notice any problem while using the packaging scripts.

This is the issue reported in the security list, right @rhtyd ?

**Comment by rhtyd** [comment]
Yes @rafaelweingartner. @resmo you're right, I think none of us have never faced any problems due to this issue.

**Comment by rhtyd** [comment]
Since this is a packaging only fix, merging based on a successful packaging build and 2+ lgtms.

**Pull request merged**
