### PR TITLE
CLOUDSTACK-8924: Removed duplicate test from test_scale_vm.py

### PR DESCRIPTION
**Pull request by sanju1010**
Please go through CS-8924 for more details.

### CODE REVIEW

**Comment by sanju1010** [comment]
root@localhost:~/cloudstack# nosetests --with-marvin --marvin-config=/root/cloudstack/setup/dev/local1.cfg --zone=Sandbox-simulator --hypervisor=simulator -a tags=basic,required_hardware=false /root/cloudstack/test/integration/smoke/test_scale_vm.py

==== Marvin Init Started ====

=== Marvin Parse Config Successful ===

=== Marvin Setting TestData Successful===

==== Log Folder Path: /tmp//MarvinLogs//Sep_30_2015_08_06_32_AWNF1O. All logs will be available here ====

=== Marvin Init Logging Successful===

==== Marvin Init Successful ====
===final results are now copied to: /tmp//MarvinLogs/test_scale_vm_OPS7AD===
root@localhost:~/cloudstack# cd /tmp//MarvinLogs/test_scale_vm_OPS7AD
root@localhost:/tmp/MarvinLogs/test_scale_vm_OPS7AD# ls
failed_plus_exceptions.txt  results.txt  runinfo.txt
root@localhost:/tmp/MarvinLogs/test_scale_vm_OPS7AD# vi  results.txt
root@localhost:/tmp/MarvinLogs/test_scale_vm_OPS7AD# ls -al
total 48
drwxr-xr-x 2 root root  4096 Sep 30 08:07 .
drwxr-xr-x 8 root root  4096 Sep 30 08:06 ..
-rw-r--r-- 1 root root     0 Sep 30 08:06 failed_plus_exceptions.txt
-rw-r--r-- 1 root root   186 Sep 30 08:06 results.txt
-rw-r--r-- 1 root root 36164 Sep 30 08:06 runinfo.txt
root@localhost:/tmp/MarvinLogs/test_scale_vm_OPS7AD#
root@localhost:/tmp/MarvinLogs/test_scale_vm_OPS7AD# cat results.txt
Test scale virtual machine ... === TestName: test_01_scale_vm | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 1 test in 23.455s

OK

**Comment by pvr9711** [comment]
LGTM!  Thanks Sanjeev!

**Comment by koushik-das** [comment]
LGTM. Since now test_01_scale_vm can be run on simulator, no need for the other one.

**Comment by borisroman** [comment]
[root@cs1 smoke]# nosetests --with-marvin --marvin-config=/data/shared/marvin/mct-zone1-xen1-basic.cfg -s -a tags=basic,required_hardware=false test_scale_vm

==== Marvin Init Started ====

=== Marvin Parse Config Successful ===

=== Marvin Setting TestData Successful===

==== Log Folder Path: /tmp//MarvinLogs//Oct_01_2015_11_34_15_WWBMZ3. All logs will be available here ====

=== Marvin Init Logging Successful===

==== Marvin Init Successful ====
=== TestName: test_01_scale_vm | Status : SUCCESS ===

===final results are now copied to: /tmp//MarvinLogs//NIMUQD===

:+1: LGTM

**Comment by wilderrodrigues** [comment]
@remibergsma 

@borisroman also had a look at this one, which is marked as blocker - although is just about a test that wasn't properly executed.

Could you please get this one merged?

Cheers,
Wilder

**Comment by borisroman** [comment]
@wilderrodrigues I can't merge...

**Comment by remibergsma** [comment]
Just merged this.

**Pull request merged**
