### PR TITLE
UI: fix scale vm if first disk offering is dymamic

### LINKED ISSUE #8212: UI: Scale vm failed if the first disk offering is customized
Steps to reproduce the issue
- remove built-int disk offerings (Small, Medium, Large)
- create a custom disk offering if the 'Custom' offering does not exist
- create a vm
- stop the vm, and resize the root disk size
- scale the vm to another service offering, the disk size is displayed incorrectly
image

- click OK, got an error "You cannot pass in a custom disk size to a non-custom disk offering."
image

In 4.18 and onwards, update global setting allow.diskoffering.change.during.scale.vm to true (this does not exist in 4.17) before testing.

logs show that the `details[0].rootdisksize=0` is passed which should not be passed.

```
2023-11-10 07:54:46,650 DEBUG [c.c.a.ApiServlet] (qtp989447607-16:ctx-b67707d1) (logid:13ab8e58) ===START===  127.0.0.1 -- GET  id=ab516f09-de84-407d-8a15-a4685c5d17f1&serviceofferingid=60f2bf60-30b6-4117-a265-b1b1b7f00a94&automigrate=true&details[0].rootdisksize=0&command=scaleVirtualMachine&response=json
```

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~
4.17/4.18/main
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #8212 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
screenshot

prior to this PR
image


with this PR
image

**Comment by weizhouapache** [comment]
@blueorangutan ui

**Review by Pearl1594 — APPROVED** [review]
Tested - LGTM

**Review by DaanHoogland — APPROVED** [review]
CLGTM

**Pull request merged**
