### PR TITLE
CLOUDSTACK-9050 Virtual router should only match IP address when choosing which interface to NAT

### PR DESCRIPTION
**Pull request by dsclose**
Changed grep to match IP address only. Solves issue where virtual router was NATing IP addresses to the wrong interface if the IP address was a substring of the broadcast address on another interface.

### CODE REVIEW

**Comment by remibergsma** [comment]
@dsclose Thanks for the fix. Can you please make the title of the PR a bit more descriptive?

How did you test this? Were any Marvin integration tests run?

**Comment by dsclose** [comment]
I've only used situational tests for this fix. I'll looking into the docs regarding getting the integration tests up and running and will get back to you in the next few days.

**Comment by ustcweizhou** [comment]
LGTM
the similar issue happened several times in our scripts.
We should use more precise expression when we use sed/grep, etc

**Comment by remibergsma** [comment]
@wilderrodrigues Are these scripts still used in master/4.6?

**Comment by wilderrodrigues** [comment]
@ustcweizhou @dsclose 

Dude, this script is not used anymore! Please test it with maven, or manually, and you will see that it doesn't apply.

The only place the file is reference is here ==>

image

It should have been removed with the Routers Persistent Configuration / Redundant VPCs.

I'm glad to help to get the fix in the right place, but please test against 4.6.0/master using a 4.6.0 SystemVM.

Cheers,
Wilder

**Comment by wilderrodrigues** [comment]
@dsclose, please have a look at:

```
./cloud-systemvm/patches/debian/config/opt/cloud/bin/configure.py
```

Cheers,
Wilder

**Comment by wilderrodrigues** [comment]
@dsclose 

Scripts not in use since 4.6.0:

```
    public static final String FIREWALL_EGRESS = "firewall_egress.sh";
    public static final String IPASSOC = "ipassoc.sh";
    public static final String VMDATA = "vmdata.py";
    public static final String VPC_ACL = "vpc_acl.sh";
    public static final String VPC_GUEST_NETWORK = "vpc_guestnw.sh";
    public static final String VPC_PRIVATEGW_ACL = "vpc_privategw_acl.sh";
    public static final String VPC_STATIC_NAT = "vpc_staticnat.sh";
    public static final String VPC_STATIC_ROUTE = "vpc_staticroute.sh";
    public static final String S2SVPN_IPSEC = "ipsectunnel.sh";
    public static final String DHCP = "edithosts.sh";
    public static final String DNSMASQ_CONFIG = "dnsmasq.sh";
    public static final String FIREWALL_INGRESS = "firewall_ingress.sh";
    public static final String FIREWALL_NAT = "firewall_nat.sh";
    public static final String IPALIAS_CREATE = "createipAlias.sh";
    public static final String IPALIAS_DELETE = "deleteipAlias.sh";
    public static final String LB = "loadbalancer.sh";
    public static final String MONITOR_SERVICE = "monitor_service.sh";
    public static final String PASSWORD = "savepassword.sh";
    public static final String VPC_IPASSOC = "vpc_ipassoc.sh";
    public static final String VPC_LB = "vpc_loadbalancer.sh";
    public static final String VPC_PRIVATEGW = "vpc_privateGateway.sh";
    public static final String VPC_PORTFORWARDING = "vpc_portforwarding.sh";
    public static final String VPC_SOURCE_NAT = "vpc_snat.sh";
    public static final String VPN_L2TP = "vpn_l2tp.sh";
```

I will remove all of them from the project to avoid misunderstands.

Cheers,
Wilder

**Comment by borisroman** [comment]
@dsclose Thanks for your PR, it shows support! As the script is not in use anymore, would you close the PR?

**Comment by DaanHoogland** [comment]
@borisroman @dsclose how about changing it to a pr that removes the script ;)

**Comment by borisroman** [comment]
@DaanHoogland That's already being done by @wilderrodrigues. Therefore this one is obsolete.

**Comment by dsclose** [comment]
CLosing this pull request as the patched script is already deprecated.

**Pull request closed without merging**
