### PR TITLE
Fix unmanage VM marvin tests and small UI fixes for import

### PR DESCRIPTION
**Pull request by nvazquez**
### Description

This PR fixes the failing smoke test for `test_vm_lifecycle_unmanage_import.py` for Vmware and adds a small UI fix on the import wizard

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test matrix

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-67u3

**Review by shwstppr — APPROVED** [review]
LGTM

**Comment by DaanHoogland** [comment]
@blueorangutan test alma8 vmware-70u3

**Comment by shwstppr** [comment]
@DaanHoogland @harikrishna-patnala @rohityadavcloud cc @nvazquez oops I merged it a bit early. Do you approve or else I can revert?

**Review by kishankavala — COMMENTED** [review]
LGTM

**Review by harikrishna-patnala — COMMENTED** [review]
code LGTM.  
cc @shwstppr

**Review by DaanHoogland — COMMENTED** [review]
code lgtm

**Pull request merged**
