### PR TITLE
Filter templates in vue

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR...

Fixes: #7560 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

Tested manually in the UI on and environment with two zones with different hypervisors.

An alternative way of testing could be testing in a single zone with two different hypervisor types or in two zones with the same hypervisor type. In both cases the list of available templates to choose from should be restricted to the current zone and hypervisor type. I.E. and template that is of a different hypervisortype or not available in the zone the VM is in should not be offered as a choice in the drop-down.

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan ui

**Comment by DaanHoogland** [comment]
> @DaanHoogland Shouldn't we also fix the api call as well? In my view, those templates shouldn't be visible in the front end at all.

No, i don´t see why @soreana. The user has rights to see those templates, it is just that these are not applicable for restoring the VM.

**Comment by soreana** [comment]
So 

> > @DaanHoogland Shouldn't we also fix the api call as well? In my view, those templates shouldn't be visible in the front end at all.
> 
> No, i don´t see why @soreana. The user has rights to see those templates, it is just that these are not applicable for restoring the VM.

Yeah I agree that this is a default behaviour and user can see those. My question is what would be the point of showing those templates to user while they can't use them :D

**Comment by DaanHoogland** [comment]
> So
> 
> > > @DaanHoogland Shouldn't we also fix the api call as well? In my view, those templates shouldn't be visible in the front end at all.
> > 
> > 
> > No, i don´t see why @soreana. The user has rights to see those templates, it is just that these are not applicable for restoring the VM.
> 
> Yeah I agree that this is a default behaviour and user can see those. My question is what would be the point of showing those templates to user while they can't use them :D

none, that is why this PR (and why #7560 was reported) . Not sure I get your comment @soreana .

**Comment by kiranchavala** [comment]
@blueorangutan package

**Review by kiranchavala — APPROVED** [review]
LGTM

Tested manually and only the zone specific templates are visible when you try to reinstall a vm

**Comment by DaanHoogland** [comment]
second test verification reported at https://github.com/apache/cloudstack/issues/7560#issuecomment-1656584114

**Comment by weizhouapache** [comment]
code lgtm

**Comment by weizhouapache** [comment]
@DaanHoogland 
it looks UI test failed after merging this
https://github.com/apache/cloudstack/actions/runs/5710998969/job/15472424976

**Comment by DaanHoogland** [comment]
see #7792 

> @DaanHoogland it looks UI test failed after merging this https://github.com/apache/cloudstack/actions/runs/5710998969/job/15472424976

**Pull request merged**
