### PR TITLE
README: it's that time of the year!

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

image

To all of the CloudStack contributors - Merry Christmas and Happy Holidays!

/cc alphabetically-ish @abh1sar @alexandremattioli @andrijapanicsb @borisstoyanov @BryanMLima @bernardodemarco @chiradeep @DaanHoogland @GabrielBrascher @GaOrtiga @gsirett @GutoVeronezi @harikrishna-patnala @hsato03 @rajujith @jbampton @JoaoJandre @kiwiflyer @kiranchavala @kishankavala @mlsorensen @msinhore @NuxRo @nvazquez @PeterBackroll @pdion891 @rafaelweingartner  @resmo  @RodrigoDLopez @rohityadavcloud @rp- @SadiJr @shwstppr @slavkap @soreana @steveroles @SadiJr @sureshanaparti @svenvogel @swill @syed @utchoang @vishesh92 @vladimirpetrov @winterhazel @weizhouapache @wido and so many others! (I may have missed quite a few - you're all in my thoughts)

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]

**Comment by resmo** [comment]
To be honest, I don't really like this PR. Not that it matters to me whether it's Christmas or any other festival in any religion. It shouldn't have anything to do with this project... and a simple

Merry Christmas to the ones who celebrate 

on the ML should be enough.

Just my 2 cents.

**Comment by DaanHoogland** [comment]
> To be honest, I don't really like this PR. Not that it matters to me whether it's Christmas or any other festival in any religion. It shouldn't have anything to do with this project... and a simple
> 
> Merry Christmas to the ones who celebrate
> 
> on the ML should be enough.
> 
> Just my 2 cents.

I like your killjoy attitude @resmo (no sarcasm, really)

**Review by shwstppr — APPROVED** [review]

**Comment by gsirett** [comment]
I'm normally accused of being the Christmas grinch, I think @resmo is bidding for my title :-)

Happy Christmas (to those that celebrate) and a peaceful new year to everybody in this community

**Review by nvazquez — APPROVED** [review]
Merry Christmas and happy new year all! 💪🏼

**Comment by andrijapanicsb** [comment]
@resmo pls improve on the code so that we can eventually merge it. I see sooooooo many people are asked to review - this is hardly ever going to be merged, damn it.... (not that I care about holidays that much :D )

**Review by andrijapanicsb — CHANGES_REQUESTED** [review]
What Christmas, 25th December 2024 or 7th January 2025?
Code is unclear. There are no proper logging messages. Have the smoke tests passed for major hypervisors?

**Review by rohityadavcloud — APPROVED** [review]
Happy Christmas and holidays.

**Review by resmo — APPROVED** [review]
🤷

**Review by weizhouapache — APPROVED** [review]

**Review by abh1sar — APPROVED** [review]

**Comment by abh1sar** [comment]
Merry Christmas and Happy Holidays 🎉 !

**Review by JoaoJandre — APPROVED** [review]
Happy holidays to everyone :santa:

**Comment by msinhore** [comment]
Merry Christmas and Happy New Year everybody!

**Review by BryanMLima — APPROVED** [review]
Happy holidays everyone!!

**Review by hsato03 — APPROVED** [review]
Happy holidays! 🎊

**Comment by DaanHoogland** [comment]
> What Christmas, 25th December 2024 or 7th January 2025? Code is unclear. There are no proper logging messages. Have the smoke tests passed for major hypervisors?

@andrijapanicsb , since you are blocking this High-prio and time-sensitive PR, please add suggestions to make its progress possible. i.e. add log messages to add/specify the missing smoke tests. 

Please make it as easy on the contributor as possible to have their changes adopted!

**Review by sureshanaparti — APPROVED** [review]
Happy Christmas and New Year!

**Review by vladimirpetrov — APPROVED** [review]
Happy holidays to all of you!

**Review by kiranchavala — APPROVED** [review]
Happy Christmas and New Year!

**Review by soreana — APPROVED** [review]
Wishing everyone a Merry Christmas and a Happy New Year! Excited for another fantastic year of working together!

**Pull request merged**
