### PR TITLE
UI - Add a setting to config.json that allows users to set theme

### PR DESCRIPTION
**Pull request by utchoang**
### Description

Add a setting to config.json that allows users to set theme

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by sureshanaparti** [comment]
Hi @shwstppr can you test this please.

**Review by Pearl1594 — APPROVED** [review]
LGTM. Shows the Page styling drawer on setting the config to true.

**Review by shwstppr — APPROVED** [review]

**Review by sureshanaparti — APPROVED** [review]
LGTM

**Pull request merged**
