### PR TITLE
Switched to the official SolidFire SDK for Java

### PR DESCRIPTION
**Pull request by mike-tutkowski**
SolidFire has recently released an official SDK for Java.

I have converted the SolidFire storage plug-ins to make use of this new SDK.

http://search.maven.org/#artifactdetails%7Ccom.solidfire%7Csolidfire-sdk-java%7C1.2.0.29%7Cjar

### CODE REVIEW

**Comment by mike-tutkowski** [comment]
TestAddRemoveHosts.py

test_add_remove_host_with_solidfire_plugin_1 (TestAddRemoveHosts.TestAddRemoveHosts) ... === TestName: test_add_remove_host_with_solidfire_plugin_1 | Status : SUCCESS ===
ok
test_add_remove_host_with_solidfire_plugin_2 (TestAddRemoveHosts.TestAddRemoveHosts) ... === TestName: test_add_remove_host_with_solidfire_plugin_2 | Status : SUCCESS ===
ok
test_add_remove_host_with_solidfire_plugin_3 (TestAddRemoveHosts.TestAddRemoveHosts) ... === TestName: test_add_remove_host_with_solidfire_plugin_3 | Status : SUCCESS ===
ok
test_add_remove_host_with_solidfire_plugin_4 (TestAddRemoveHosts.TestAddRemoveHosts) ... === TestName: test_add_remove_host_with_solidfire_plugin_4 | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 4 tests in 3435.128s

OK

**Comment by mike-tutkowski** [comment]
TestSnapshots.py: The failure in test 04 makes sense as that test case is actually dependent upon #1600, which has not yet been merged in.

test_01_create_volume_snapshot_using_sf_snapshot (TestSnapshots.TestSnapshots) ... === TestName: test_01_create_volume_snapshot_using_sf_snapshot | Status : SUCCESS ===
ok
test_02_create_volume_snapshot_using_sf_volume (TestSnapshots.TestSnapshots) ... === TestName: test_02_create_volume_snapshot_using_sf_volume | Status : SUCCESS ===
ok
test_03_create_volume_snapshot_using_sf_volume_and_sf_snapshot (TestSnapshots.TestSnapshots) ... === TestName: test_03_create_volume_snapshot_using_sf_volume_and_sf_snapshot | Status : SUCCESS ===
ok
test_04_create_volume_snapshot_using_sf_snapshot_and_archiving (TestSnapshots.TestSnapshots) ... === TestName: test_04_create_volume_snapshot_using_sf_snapshot_and_archiving | Status : FAILED ===
FAIL
test_05_create_volume_snapshot_using_sf_snapshot_and_revert_volume_to_snapshot (TestSnapshots.TestSnapshots) ... === TestName: test_05_create_volume_snapshot_using_sf_snapshot_and_revert_volume_to_snapshot | Status : SUCCESS ===
ok

**Comment by mike-tutkowski** [comment]
TestVMMigrationWithStorage

test_01_storage_migrate_root_and_data_disks (TestVMMigrationWithStorage.TestVMMigrationWithStorage) ... === TestName: test_01_storage_migrate_root_and_data_disks | Status : SUCCESS ===
ok
test_02_storage_migrate_root_and_data_disks (TestVMMigrationWithStorage.TestVMMigrationWithStorage) ... === TestName: test_02_storage_migrate_root_and_data_disks | Status : SUCCESS ===
ok
test_03_storage_migrate_root_and_data_disks_fail (TestVMMigrationWithStorage.TestVMMigrationWithStorage) ... === TestName: test_03_storage_migrate_root_and_data_disks_fail | Status : SUCCESS ===
ok
test_04_storage_migrate_root_disk_fails (TestVMMigrationWithStorage.TestVMMigrationWithStorage) ... === TestName: test_04_storage_migrate_root_disk_fails | Status : SUCCESS ===
ok
test_05_storage_migrate_data_disk_fails (TestVMMigrationWithStorage.TestVMMigrationWithStorage) ... === TestName: test_05_storage_migrate_data_disk_fails | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 5 tests in 2941.392s

OK

**Comment by mike-tutkowski** [comment]
TestVMSnapshots.py

test_01_take_VM_snapshot (TestVMSnapshots.TestVMSnapshots) ... === TestName: test_01_take_VM_snapshot | Status : SUCCESS ===
ok
test_02_take_VM_snapshot_with_data_disk (TestVMSnapshots.TestVMSnapshots) ... === TestName: test_02_take_VM_snapshot_with_data_disk | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 2 tests in 608.358s

OK

**Comment by mike-tutkowski** [comment]
TestVolumes (resigning)

test_00_check_template_cache (TestVolumes.TestVolumes) ... === TestName: test_00_check_template_cache | Status : SUCCESS ===
ok
Attach a volume to a stopped virtual machine, then start VM ... === TestName: test_01_attach_new_volume_to_stopped_VM | Status : SUCCESS ===
ok
Attach, detach, and attach volume to a running VM ... === TestName: test_02_attach_detach_attach_volume | Status : SUCCESS ===
ok
Attach volume to running VM, then reboot. ... === TestName: test_03_attached_volume_reboot_VM | Status : SUCCESS ===
ok
Detach volume from a running VM, then reboot. ... === TestName: test_04_detach_volume_reboot | Status : SUCCESS ===
ok
Detach volume from a stopped VM, then start. ... === TestName: test_05_detach_vol_stopped_VM_start | Status : SUCCESS ===
ok
Attach a volume to a stopped virtual machine, then start VM ... === TestName: test_06_attach_volume_to_stopped_VM | Status : SUCCESS ===
ok
Destroy and expunge VM with attached volume ... === TestName: test_07_destroy_expunge_VM_with_volume | Status : SUCCESS ===
ok
Delete volume that was attached to a VM and is detached now ... === TestName: test_08_delete_volume_was_attached | Status : SUCCESS ===
ok
Attach a data disk to a VM in one account and attach another data disk to a VM in another account ... === TestName: test_09_attach_volumes_multiple_accounts | Status : SUCCESS ===
ok
Attach more than one disk to a VM ... === TestName: test_10_attach_more_than_one_disk_to_VM | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 11 tests in 1673.081s

OK

**Comment by mike-tutkowski** [comment]
TestVolumes.py (no resigning)

test_00_check_template_cache (TestVolumes.TestVolumes) ... === TestName: test_00_check_template_cache | Status : SUCCESS ===
ok
Attach a volume to a stopped virtual machine, then start VM ... === TestName: test_01_attach_new_volume_to_stopped_VM | Status : SUCCESS ===
ok
Attach, detach, and attach volume to a running VM ... === TestName: test_02_attach_detach_attach_volume | Status : SUCCESS ===
ok
Attach volume to running VM, then reboot. ... === TestName: test_03_attached_volume_reboot_VM | Status : SUCCESS ===
ok
Detach volume from a running VM, then reboot. ... === TestName: test_04_detach_volume_reboot | Status : SUCCESS ===
ok
Detach volume from a stopped VM, then start. ... === TestName: test_05_detach_vol_stopped_VM_start | Status : SUCCESS ===
ok
Attach a volume to a stopped virtual machine, then start VM ... === TestName: test_06_attach_volume_to_stopped_VM | Status : SUCCESS ===
ok
Destroy and expunge VM with attached volume ... === TestName: test_07_destroy_expunge_VM_with_volume | Status : SUCCESS ===
ok
Delete volume that was attached to a VM and is detached now ... === TestName: test_08_delete_volume_was_attached | Status : SUCCESS ===
ok
Attach a data disk to a VM in one account and attach another data disk to a VM in another account ... === TestName: test_09_attach_volumes_multiple_accounts | Status : SUCCESS ===
ok
Attach more than one disk to a VM ... === TestName: test_10_attach_more_than_one_disk_to_VM | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 11 tests in 1370.642s

OK

**Comment by rhtyd** [comment]
All changes are restricted to the solidfire plugin and currently we don't have infra/tests to run them in a general env so considering Mike's tests, LGTM.
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test
(this is to run a regression testing round)

**Comment by syed** [comment]
LGTM as well

**Comment by mike-tutkowski** [comment]
@rhtyd Do you know what the results were of those regression tests you kicked off for this PR a few days ago? Thanks!

**Comment by mike-tutkowski** [comment]
@rhtyd Do you know what the results were of those regression tests you kicked off for this PR a few days ago? Just checking in to see if we are able to merge this. Thanks!

**Comment by rhtyd** [comment]
@mike-tutkowski yesterday was a bank holiday so did not see the message. Something went wrong with blueorangutan as it did not pick the mgmt server OS and hypervisor type. I'll re-kick it.
@blueorangutan test

**Comment by rhtyd** [comment]
The single failure is env related, we can ignore that. Given regression tests have all passed, LGTM on tests. Single all of the changes are related to vendor (solidfire) specific codebase/lib, LGTM on changes as well. Based on this, I'll move forward and merge this. Thanks Mike.

**Comment by mike-tutkowski** [comment]
Thanks, @rhtyd!

**Pull request merged**
