### PR TITLE
server: fix failed to remove template/iso if upload from local fails

### PR DESCRIPTION
**Pull request by ustcweizhou**
### Description

This PR fixes the issue that failed to remove template/iso if upload from local fails

When upload template/iso/volume from local fails, the install_path will not be a full path of file so removing it will fail.

```
mysql> select install_path from template_store_ref;
+--------------------------------------------------------------------+
| install_path                                                       |
+--------------------------------------------------------------------+
| template/tmpl/1/3/805f4763-248e-40ec-b79a-b868cc480d0a.qcow2       |
| template/tmpl/1/4/c7e32c9e-5e72-3726-85cf-aa5ccd84118d.qcow2       |
| template/tmpl/2/201/bc4f4f08-138a-31b8-af1a-d4450eff7982.qcow2     |
| template/tmpl/2/202                                                |
| template/tmpl/2/203/203-2-d47f8cde-a2a8-31e7-a826-2628ad98a6c8.iso |
| template/tmpl/2/204                                                |
| template/tmpl/5/205                                                |
| template/tmpl/2/206                                                |
| template/tmpl/2/207                                                |
| template/tmpl/2/208                                                |
| template/tmpl/2/209                                                |
| template/tmpl/2/210                                                |
+--------------------------------------------------------------------+
12 rows in set (0.00 sec)

mysql> select install_path from volume_store_ref;
+---------------------------------------------------------+
| install_path                                            |
+---------------------------------------------------------+
| volumes/2/22                                            |
| volumes/2/19/f93face9-6521-4184-b89a-cb07f86bbae8.qcow2 |
| volumes/2/23                                            |
| volumes/2/24                                            |
+---------------------------------------------------------+
4 rows in set (0.00 sec)
```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by rhtyd** [comment]
@blueorangutan test

**Review by shwstppr — COMMENTED** [review]
@ustcweizhou Local upload failed with a message,
`Failed to upload file due to system misconfiguration. Please contact admin.`
Now with changes, I cannot delete the template with message,
`The template is either getting uploaded or it may be initiated shortly, please wait for it to be completed`
Is this desired? I think we can allow deleting when it is in NotUploaded state

**Comment by weizhouapache** [comment]
> NotUploaded

@shwstppr NotUploaded is the initialed state of volumes/template/iso when it is uploaded from local.
when upload starts, it will be transited to UploadInProgress
when upload failed, it will be transited to UploadError

I think deleting template/iso in NotUploaded state should not be allowed (same as volumes).
when upload fails (by default template/isos/volumes will be in UploadError state after 1 hour), we can remove them.

**Review by Pearl1594 — APPROVED** [review]
Verified behavior. LGTM

**Review by shwstppr — APPROVED** [review]

**Comment by rhtyd** [comment]
ping @shwstppr @Pearl1594 - should we merge this on 4.14 now, or change base/milestone to 4.15.1.0?

**Pull request merged**
