### PR TITLE
[CLOUDSTACK-10254] checkstyle: add package name declaration validation

### PR DESCRIPTION
**Pull request by marcaurele**
- add a new checkstyle directive (http://checkstyle.sourceforge.net/config_coding.html#PackageDeclaration)
- force the use of latest checkstyle library version (the default one is pretty old)
- fix all findings

Most of the findings were due to incorrect moves done in PR #2283

### CODE REVIEW

**Comment by marcaurele** [comment]
Relating to #2417 too

**Comment by marcaurele** [comment]
Having a hard time try to make checkstyle to skip `generated-sources` directories (first encounter is in `plugins/network-elements/brocade-vcs` project). If anyone has a clue on what is the correct syntax, I'll appreciate.

**Comment by rafaelweingartner** [comment]
@marcaurele would you mind separating the removal of those empty classes from the commit that introduces these new checkstyle configurations?

**Comment by marcaurele** [comment]
@rafaelweingartner I'd rather push all together since it does not disturb the build. I had a hard time finding the solution for the generated classes. I'm down to the apidoc project, which requires a fix and it should all be good.

**Comment by rafaelweingartner** [comment]
Ok, no problem. Can you look into travis errors?

**Comment by marcaurele** [comment]
@rafaelweingartner CI is green, so it should be all good to merge now since there is no code change in term of functionality.

**Comment by rafaelweingartner** [comment]
@marcaurele we still need one more review.

**Comment by DaanHoogland** [comment]
LGTM but paranoia
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Pull request merged**
