### PR TITLE
CLOUDSTACK-9833: Move configuration parameters from Config.java to use configdepot

### PR DESCRIPTION
**Pull request by harikrishna-patnala**
Following parameters are moved from config.java to configdepot.
This will make the management of configuration parameter easy during upgrade and avoid inconsistency of values of parameters for fresh setup and upgraded setup.

snapshot.max.hourly
snapshot.max.daily
snapshot.max.weekly
snapshot.max.monthly
enable.secure.session.cookie
json.content.type

### CODE REVIEW

**Comment by jayapalu** [comment]
Code LGTM

**Comment by harikrishna-patnala** [comment]
Thanks @jayapalu I have also added some content security policy in HTTP servlet response to detect and mitigate certain type of attacks.
Restricted image source, style sheets, java scripts, URLs to be loaded only from self.

**Comment by Divyanimmagadda** [comment]
Verified the dynamic configuration of the below parameters. LGTM. 

snapshot.max.hourly
snapshot.max.daily
snapshot.max.weekly
snapshot.max.monthly
enable.secure.session.cookie
json.content.type

result1
result2
result3

**Comment by harikrishna-patnala** [comment]
tag:mergeready

**Comment by karuturi** [comment]
@harikrishna-patnala Can you make two separate commits? one for configdepo related changes and the other for security policy in HTTP servlet response

**Comment by harikrishna-patnala** [comment]
Hi @karuturi , I have updated the PR with two commits. Please review.

**Comment by rhtyd** [comment]
@karuturi why was this merged without any regression testing?

**Comment by karuturi** [comment]
I saw the manual testing results, mergeready label and merged. Didn't see missing BVTs. will take care next time

**Comment by rhtyd** [comment]
@karuturi okay, I'll kick a round of tests on master branch with #1836 by eod today.

**Pull request merged**
