### PR TITLE
[WIP DO NOT MERGE] VM ingestion

### PR DESCRIPTION
**Pull request by shwstppr**
## Description
VM ingestion feature allows CloudStack to discover, on-board, import existing VMs in an infra. The feature currently works only for VMware, with a hypervisor agnostic framework which may be extended for KVM and XenServer in future.
Two new APIs have been added, `listUnmanagedInstances` and `importUnmanagedInstance`.
### listUnmanagedInstances
API will list all unmanaged virtual machine for a give cluster. Optionally, name for an existing unmanaged virtual machine can be given to retrieve VM details.
**API request params -** 
`clusterid`(UUID of cluster)
`name`(instance name)
**Response -**
`clusterid`
`hostid`
`name`
`osdisplayname`
`memory`
`powerstate`
`cpuCoresPerSocket`
`cpunumber`
`cpuspeed`
`disk`
    - `id`
    - `capacity`
    - `controller`
    - `controllerunit`
    - `imagepath`
    - `position`
`nic`
    - `id`
    - `macaddress`
    - `networkname`
    - `vlanid`
    - `pcislot`

### importUnmanagedInstance
API will import an exisitng unmanaged virtual machine into CloudStack for a given cluster and virtual machine name. Service offering for the VM, disk offerings for volumes and networks for NICs of the VM can be mapped. Some optional parameters like projectid, domainid, hostname, details, etc can also be given. Appropritate networks, service offering and disk offerings need to be present before import and cannot be created on the fly during the API call.
**API request params -** 
`clusterid`(UUID of cluster)
`name`(instance name)
`displayname`
`hostname`
`domainid`
`projectid`
`templateid`
`serviceofferingid`
`diskofferingid`(UUID of disk offering for root disk)
`nicnetworklist`(Map for NIC ID and corresponding Network UUID)
`datadiskofferinglist`(Map for disk ID and corresponding disk offering UUID)
`details`(Map for VM details)
**Response -** 
Same response as that of `deployVirtualMachine` API

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## API sample calls:
**List**
```
> list unmanagedinstances clusterid=079a19c2-2710-4ed6-9110-027dd5e0f262 
{
  "count": 2,
  "unmanagedinstance": [
    {
      "clusterid": "079a19c2-2710-4ed6-9110-027dd5e0f262",
      "cpucorespersocket": 1,
      "cpunumber": 1,
      "cpuspeed": 0,
      "disk": [
        {
          "capacity": 2097152,
          "controller": "ide",
          "controllerunit": 0,
          "id": "51-3001",
          "imagepath": "[8aca30d6f7803420973f01cc91c1c011] test-unmanaged/test-unmanaged_64.vmdk",
          "label": "Hard disk 1",
          "position": 1
        },
        {
          "capacity": 5242880,
          "controller": "scsi",
          "controllerunit": 0,
          "id": "51-2000",
          "imagepath": "[8aca30d6f7803420973f01cc91c1c011] test-unmanaged/test-unmanaged_63.vmdk",
          "label": "Hard disk 2",
          "position": 0
        }
      ],
      "hostid": "4ab4147a-7e40-4abe-a0e2-2fac1aa6f0bf",
      "memory": 512,
      "name": "test-unmanaged",
      "nic": [
        {
          "id": "Network adapter 1",
          "macaddress": "02:00:39:7c:00:24",
          "networkname": "cloud.guest.1212.200.1-vSwitch1",
          "vlanid": 1212
        }
      ],
      "osdisplayname": "CentOS 4/5 or later (64-bit)",
      "powerstate": "POWERED_ON"
    }
  ]
}
```
**Import**
```
> import unmanagedinstance name=test-unmanaged templateid=200f3fe9-c845-11e9-b69f-1e003c0107c4 clusterid=079a19c2-2710-4ed6-9110-027dd5e0f262 diskofferingid=e9eb069f-2946-4e26-8d81-07aebba868d1 serviceofferingid=c4c5b9e8-8a4a-422d-bccc-2f1bcc166c59 datadiskofferinglist[0].disk=51-2000 datadiskofferinglist[0].diskOffering=e9eb069f-2946-4e26-8d81-07aebba868d1 displayname=NewVm nicNetworkList[0].nic="Network adapter 1" nicNetworkList[0].network=4c44312b-f009-4d33-b942-989169f3d2fc
{
  "virtualmachine": {
    "account": "admin",
    "affinitygroup": [],
    "cpunumber": 1,
    "cpuspeed": 500,
    "created": "2019-09-05T11:32:04+0000",
    "details": {},
    "diskofferingid": "e9eb069f-2946-4e26-8d81-07aebba868d1",
    "diskofferingname": "Custom",
    "displayname": "NewVm",
    "displayvm": true,
    "domain": "ROOT",
    "domainid": "20088b4d-c845-11e9-b69f-1e003c0107c4",
    "guestosid": "2015cd08-c845-11e9-b69f-1e003c0107c4",
    "haenable": false,
    "hostid": "4ab4147a-7e40-4abe-a0e2-2fac1aa6f0bf",
    "hostname": "10.2.2.144",
    "hypervisor": "VMware",
    "id": "4fda861e-e693-4227-a8aa-1b4ce90d5041",
    "instancename": "test-unmanaged",
    "isdynamicallyscalable": false,
    "memory": 512,
    "name": "test-unmanaged",
    "nic": [
      {
        "broadcasturi": "vlan://1212",
        "extradhcpoption": [],
        "id": "61952f25-7efa-4bc2-aa92-ecd38c122e65",
        "isdefault": true,
        "isolationuri": "vlan://1212",
        "macaddress": "02:00:39:7c:00:24",
        "networkid": "4c44312b-f009-4d33-b942-989169f3d2fc",
        "networkname": "lol",
        "secondaryip": [],
        "traffictype": "Guest",
        "type": "L2"
      }
    ],
    "ostypeid": "2015cd08-c845-11e9-b69f-1e003c0107c4",
    "passwordenabled": false,
    "rootdeviceid": 0,
    "rootdevicetype": "ROOT",
    "securitygroup": [],
    "serviceofferingid": "c4c5b9e8-8a4a-422d-bccc-2f1bcc166c59",
    "serviceofferingname": "Small Instance",
    "state": "Stopped",
    "tags": [],
    "templatedisplaytext": "CentOS 5.3(64-bit) no GUI (vSphere)",
    "templateid": "200f3fe9-c845-11e9-b69f-1e003c0107c4",
    "templatename": "CentOS 5.3(64-bit) no GUI (vSphere)",
    "userid": "4dfc315c-c845-11e9-b69f-1e003c0107c4",
    "username": "admin",
    "zoneid": "db18d224-279d-4c08-aeef-0cb7030d0edb",
    "zonename": "pr3540-t341-vmware-65u2"
  }
}importUnmanagedInstance
```

## How Has This Been Tested?

- A VMware added to running CloudStack with multiple hosts.
- A new vitrual machine deployed from VMware vCenter with multiple disks, networks in the cluster.
- At this point CloudStack does not show or control newly deployed virtual machine.
- `listUnmanagedInstances` API is executed for the cluster. It shows newly deployed VM (deployed from vCenter)
- Import API, `importUnmanagedInstance`, is executed, with appropriate service offering, network- VM NIC details and custom disk offerings for this unmanaged VM
- On successful completion of import API, UI is verified showing imported VM. `listVirtualMachines` API is called to verify showing new VM and `cloud` database is checked for containing new records in `vm_instance`, `volumes`, `nics` tables.
- Lifecycle tasks were performed on the imported VM - stop, start, reboot, migrate, attach new disk.

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test matrix

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
> @shwstppr can you add unit tests please

added tests

**Comment by shwstppr** [comment]
Moved here, https://github.com/apache/cloudstack/pull/3606

**Pull request closed without merging**
