### PR TITLE
Improve marvin test site2site VPN

### PR DESCRIPTION
**Pull request by michaelandersen**
Add optional fields: iprange and fordisplay to Marvin base.py class method Vpn.create
Add optional field: passive to Marvin base.py class method Vpn.createVpnConnection

### CODE REVIEW

**Comment by michaelandersen** [comment]
run with:
nosetests --with-marvin --log-folder-path=/tmp/marvin/ --marvin-config=/data/shared/marvin/mct-zone1-kvm1.cfg -a tags=advanced  test/integration/smoke/test_vpc_vpn.py

**Comment by wilderrodrigues** [comment]
Thanks, @michaelandersen 

I will have a look at this one today!

Cheers,
Wilder

**Comment by remibergsma** [comment]
@michaelandersen Thank you! Can you please rebase with current master? Will test it afterwards :-)

**Comment by wilderrodrigues** [comment]
Testing this one now!

**Comment by wilderrodrigues** [comment]
Run the tests and it LGTM :+1: 

```
Test Remote Access VPN in VPC ... === TestName: test_vpc_remote_access_vpn | Status : SUCCESS ===
ok
Test VPN in VPC ... === TestName: test_vpc_site2site_vpn | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 2 tests in 1008.486s

OK
/tmp//MarvinLogs/test_vpc_vpn_NGALOC/results.txt (END)
```

Thanks for this PR, @michaelandersen 

Cheers,
Wilder

**Comment by remibergsma** [comment]
Please have a look at Jenkins and/or force push to trigger another run.

**Comment by michaelandersen** [comment]
@remibergsma: why another run?  Jenkins (and travis) is green

**Comment by wilderrodrigues** [comment]
Ping @remibergsma @karuturi @DaanHoogland @borisroman @wido @bhaisaab @miguelaferreira @michaelandersen @bvbharat @runseb @terbolous 

This is a test: no java/python/shell code changes. Could someone please try to run it so we can get a 2nd LGTM and merge it?

Since we need more tests, this will fit like a glove. :)

Thanks in advance.

Cheers,
Wilder

**Comment by miguelaferreira** [comment]
@wilderrodrigues running it now (together with a bunch of other tests). I'll report the results tomorrow.

**Comment by miguelaferreira** [comment]
I ran the test against master with additional PRs (**#952**, #958, #951, #957,  #940) and the result was `SUCCESSFUL`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="nosetests" tests="2" errors="0" failures="0" skip="0">
  <testcase classname="integration.smoke.test_vpc_vpn.TestVpcRemoteAccessVpn" name="test_vpc_remote_access_vpn" time="1696.270"></testcase>
  <testcase classname="integration.smoke.test_vpc_vpn.TestVpcSite2SiteVpn" name="test_vpc_site2site_vpn" time="1268.090">
    <system-err>
      <![CDATA[====Trying SSH Connection: Host:192.168.23.6 User:root                                   Port:22 RetryCnt:10===
===SSH to Host 192.168.23.6 port : 22 SUCCESSFUL===
{Cmd: /bin/ping -c 3 -t 10 10.1.1.165 |grep packet|cut -d ' ' -f 7| cut -f1 -d'%' via Host: 192.168.23.6} {returns: [u'0']}
]]>
    </system-err>
  </testcase>
</testsuite>
```
I don't have the full Marvin log because my build failed to archive those.

:+1:

**Comment by michaelandersen** [comment]
thanks for testing @miguelaferreira and @wilderrodrigues for chasing this pr
haven't seen this type of report before but looking at the combination of:
<testsuite name="nosetests" tests="2" errors="0" failures="0" skip="0">
which says no errors, failures, nor skipped
AND
the {returns: [u'0']}  as output of the ping, which is the packet loss percentage i would say this test succeeded.

**Comment by DaanHoogland** [comment]
did the check-pr test on this one but faied rerunning to further investigate

**Comment by wilderrodrigues** [comment]
Hi @miguelaferreira 

The system-err is because the Marvin code prints all the ssh commands to the terminal. It doesn't mean it failed. All the SSH related tests will print a huge amount of data on the terminal. :(

@DaanHoogland: but what kind of error did you get? Is it environment related?

Cheers,
Wilder

**Comment by miguelaferreira** [comment]
That's what I thought. The JUnit report plugin in Jenkins sais the test passed. (See last line of table in picture)

screen shot 2015-10-22 at 11 13 31

I'm running a new build at the moment, and hopefully that will archive the full marvin logs.

**Comment by DaanHoogland** [comment]
@wilderrodrigues I think it was, in the end I ran only the smoke test suite and even that got errors so please ignore for this PR

**Comment by miguelaferreira** [comment]
New test run, same result:
```
[mct-run-marvin-tests@3] Running shell script
+ nosetests --with-xunit --xunit-file=integration-test-results/smoke/test_vpc_vpn.xml --with-marvin --marvin-config=mct-zone1-kvm1-kvm2.cfg test/integration/smoke/test_vpc_vpn.py -s -a tags=advanced,required_hardware=false
Retrieving default VPC offering
VPC 80389751-14b9-4029-964f-b09bfa2e783d created
Network 05828668-278b-4b0e-92af-52af36d37a08 created in VPC 80389751-14b9-4029-964f-b09bfa2e783d
Deployed virtual machine: OK
Acquired public ip address: OK
Created Remote Access VPN: OK
Created VPN User: OK
Deleted the Remote Access VPN: OK
1878.306
Cleaning up resources
VPC1 761ab6d1-27c2-484a-884a-0b941bf603ac created
VPC2 9cc05183-e13e-492e-bfa8-b3c7d914b858 created
Network 5f1d2caf-b1e6-4eac-a700-430cd6c397db created in VPC 761ab6d1-27c2-484a-884a-0b941bf603ac
Network 38648175-c606-4087-a139-eff95c6ef435 created in VPC 9cc05183-e13e-492e-bfa8-b3c7d914b858
VM 3f365f69-809e-4007-8694-5cdeb989df94 deployed in VPC 761ab6d1-27c2-484a-884a-0b941bf603ac
VPN gateway for VPC 761ab6d1-27c2-484a-884a-0b941bf603ac enabled
VPN gateway for VPC 9cc05183-e13e-492e-bfa8-b3c7d914b858 enabled
{'account': u'test-TestVpcSite2SiteVpn-test_vpc_remote_access_vpn-5WT3SN', 'domainid': u'27347822-7895-11e5-91be-5254001daa61', 'name': u'Peer VPC1', 'cidrlist': u'10.1.0.0/16', 'ikepolicy': u'3des-md5;modp1536', 'esplifetime': 3600, 'id': u'8b500d33-9a97-4a32-9899-b0130fa6953e', 'dpd': False, 'domain': u'ROOT', 'ikelifetime': 86400, 'ipsecpsk': u'ipsecpsk', 'esppolicy': u'3des-md5;modp1536', 'gateway': u'192.168.23.20'}
{'account': u'test-TestVpcSite2SiteVpn-test_vpc_remote_access_vpn-5WT3SN', 'domainid': u'27347822-7895-11e5-91be-5254001daa61', 'name': u'Peer VPC2', 'cidrlist': u'10.2.0.0/16', 'ikepolicy': u'3des-md5;modp1536', 'esplifetime': 3600, 'id': u'4b6bf105-cadf-4c45-843a-74f365909b77', 'dpd': False, 'domain': u'ROOT', 'ikelifetime': 86400, 'ipsecpsk': u'ipsecpsk', 'esppolicy': u'3des-md5;modp1536', 'gateway': u'192.168.23.7'}
Creating NAT rule in network for vm with public IP
Adding NetworkACL rules to make NAT rule accessible
====Trying SSH Connection: Host:192.168.23.12 User:root                                   Port:22 RetryCnt:10===
SshClient: Exception under createConnection: ['Traceback (most recent call last):\n', '  File "/home/jenkins/workspace/mccloud/mct-run-marvin-tests@3/venv/lib/python2.7/site-packages/marvin/sshClient.py", line 121, in createConnection\n    timeout=self.timeout)\n', '  File "/home/jenkins/workspace/mccloud/mct-run-marvin-tests@3/venv/lib/python2.7/site-packages/paramiko/client.py", line 251, in connect\n    retry_on_signal(lambda: sock.connect(addr))\n', '  File "/home/jenkins/workspace/mccloud/mct-run-marvin-tests@3/venv/lib/python2.7/site-packages/paramiko/util.py", line 270, in retry_on_signal\n    return function()\n', '  File "/home/jenkins/workspace/mccloud/mct-run-marvin-tests@3/venv/lib/python2.7/site-packages/paramiko/client.py", line 251, in <lambda>\n    retry_on_signal(lambda: sock.connect(addr))\n', '  File "/usr/lib64/python2.7/socket.py", line 224, in meth\n    return getattr(self._sock,name)(*args)\n', 'error: [Errno 113] No route to host\n']
Traceback (most recent call last):
  File "/home/jenkins/workspace/mccloud/mct-run-marvin-tests@3/venv/lib/python2.7/site-packages/marvin/sshClient.py", line 121, in createConnection
    timeout=self.timeout)
  File "/home/jenkins/workspace/mccloud/mct-run-marvin-tests@3/venv/lib/python2.7/site-packages/paramiko/client.py", line 251, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/home/jenkins/workspace/mccloud/mct-run-marvin-tests@3/venv/lib/python2.7/site-packages/paramiko/util.py", line 270, in retry_on_signal
    return function()
  File "/home/jenkins/workspace/mccloud/mct-run-marvin-tests@3/venv/lib/python2.7/site-packages/paramiko/client.py", line 251, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 113] No route to host
====Trying SSH Connection: Host:192.168.23.12 User:root                                   Port:22 RetryCnt:9===
SshClient: Exception under createConnection: ['Traceback (most recent call last):\n', '  File "/home/jenkins/workspace/mccloud/mct-run-marvin-tests@3/venv/lib/python2.7/site-packages/marvin/sshClient.py", line 121, in createConnection\n    timeout=self.timeout)\n', '  File "/home/jenkins/workspace/mccloud/mct-run-marvin-tests@3/venv/lib/python2.7/site-packages/paramiko/client.py", line 251, in connect\n    retry_on_signal(lambda: sock.connect(addr))\n', '  File "/home/jenkins/workspace/mccloud/mct-run-marvin-tests@3/venv/lib/python2.7/site-packages/paramiko/util.py", line 270, in retry_on_signal\n    return function()\n', '  File "/home/jenkins/workspace/mccloud/mct-run-marvin-tests@3/venv/lib/python2.7/site-packages/paramiko/client.py", line 251, in <lambda>\n    retry_on_signal(lambda: sock.connect(addr))\n', '  File "/usr/lib64/python2.7/socket.py", line 224, in meth\n    return getattr(self._sock,name)(*args)\n', 'error: [Errno 113] No route to host\n']
Traceback (most recent call last):
  File "/home/jenkins/workspace/mccloud/mct-run-marvin-tests@3/venv/lib/python2.7/site-packages/marvin/sshClient.py", line 121, in createConnection
    timeout=self.timeout)
  File "/home/jenkins/workspace/mccloud/mct-run-marvin-tests@3/venv/lib/python2.7/site-packages/paramiko/client.py", line 251, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/home/jenkins/workspace/mccloud/mct-run-marvin-tests@3/venv/lib/python2.7/site-packages/paramiko/util.py", line 270, in retry_on_signal
    return function()
  File "/home/jenkins/workspace/mccloud/mct-run-marvin-tests@3/venv/lib/python2.7/site-packages/paramiko/client.py", line 251, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 113] No route to host
====Trying SSH Connection: Host:192.168.23.12 User:root                                   Port:22 RetryCnt:8===
SshClient: Exception under createConnection: ['Traceback (most recent call last):\n', '  File "/home/jenkins/workspace/mccloud/mct-run-marvin-tests@3/venv/lib/python2.7/site-packages/marvin/sshClient.py", line 121, in createConnection\n    timeout=self.timeout)\n', '  File "/home/jenkins/workspace/mccloud/mct-run-marvin-tests@3/venv/lib/python2.7/site-packages/paramiko/client.py", line 251, in connect\n    retry_on_signal(lambda: sock.connect(addr))\n', '  File "/home/jenkins/workspace/mccloud/mct-run-marvin-tests@3/venv/lib/python2.7/site-packages/paramiko/util.py", line 270, in retry_on_signal\n    return function()\n', '  File "/home/jenkins/workspace/mccloud/mct-run-marvin-tests@3/venv/lib/python2.7/site-packages/paramiko/client.py", line 251, in <lambda>\n    retry_on_signal(lambda: sock.connect(addr))\n', '  File "/usr/lib64/python2.7/socket.py", line 224, in meth\n    return getattr(self._sock,name)(*args)\n', 'error: [Errno 113] No route to host\n']
Traceback (most recent call last):
  File "/home/jenkins/workspace/mccloud/mct-run-marvin-tests@3/venv/lib/python2.7/site-packages/marvin/sshClient.py", line 121, in createConnection
    timeout=self.timeout)
  File "/home/jenkins/workspace/mccloud/mct-run-marvin-tests@3/venv/lib/python2.7/site-packages/paramiko/client.py", line 251, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/home/jenkins/workspace/mccloud/mct-run-marvin-tests@3/venv/lib/python2.7/site-packages/paramiko/util.py", line 270, in retry_on_signal
    return function()
  File "/home/jenkins/workspace/mccloud/mct-run-marvin-tests@3/venv/lib/python2.7/site-packages/paramiko/client.py", line 251, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 113] No route to host
====Trying SSH Connection: Host:192.168.23.12 User:root                                   Port:22 RetryCnt:7===
SshClient: Exception under createConnection: ['Traceback (most recent call last):\n', '  File "/home/jenkins/workspace/mccloud/mct-run-marvin-tests@3/venv/lib/python2.7/site-packages/marvin/sshClient.py", line 121, in createConnection\n    timeout=self.timeout)\n', '  File "/home/jenkins/workspace/mccloud/mct-run-marvin-tests@3/venv/lib/python2.7/site-packages/paramiko/client.py", line 251, in connect\n    retry_on_signal(lambda: sock.connect(addr))\n', '  File "/home/jenkins/workspace/mccloud/mct-run-marvin-tests@3/venv/lib/python2.7/site-packages/paramiko/util.py", line 270, in retry_on_signal\n    return function()\n', '  File "/home/jenkins/workspace/mccloud/mct-run-marvin-tests@3/venv/lib/python2.7/site-packages/paramiko/client.py", line 251, in <lambda>\n    retry_on_signal(lambda: sock.connect(addr))\n', '  File "/usr/lib64/python2.7/socket.py", line 224, in meth\n    return getattr(self._sock,name)(*args)\n', 'error: [Errno 111] Connection refused\n']
Traceback (most recent call last):
  File "/home/jenkins/workspace/mccloud/mct-run-marvin-tests@3/venv/lib/python2.7/site-packages/marvin/sshClient.py", line 121, in createConnection
    timeout=self.timeout)
  File "/home/jenkins/workspace/mccloud/mct-run-marvin-tests@3/venv/lib/python2.7/site-packages/paramiko/client.py", line 251, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/home/jenkins/workspace/mccloud/mct-run-marvin-tests@3/venv/lib/python2.7/site-packages/paramiko/util.py", line 270, in retry_on_signal
    return function()
  File "/home/jenkins/workspace/mccloud/mct-run-marvin-tests@3/venv/lib/python2.7/site-packages/paramiko/client.py", line 251, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
====Trying SSH Connection: Host:192.168.23.12 User:root                                   Port:22 RetryCnt:6===
===SSH to Host 192.168.23.12 port : 22 SUCCESSFUL===
{Cmd: /bin/ping -c 3 -t 10 10.1.1.202 |grep packet|cut -d ' ' -f 7| cut -f1 -d'%' via Host: 192.168.23.12} {returns: [u'0']}

==== Marvin Init Started ====

=== Marvin Parse Config Successful ===

=== Marvin Setting TestData Successful===

==== Log Folder Path: /tmp//MarvinLogs//Oct_22_2015_10_35_49_GL655U. All logs will be available here ====

=== Marvin Init Logging Successful===

==== Marvin Init Successful ====
=== TestName: test_vpc_remote_access_vpn | Status : SUCCESS ===

=== TestName: test_vpc_site2site_vpn | Status : SUCCESS ===

===final results are now copied to: /tmp//MarvinLogs/test_vpc_vpn_F16GJ7===
```

:+1:  LGTM

**Comment by michaelandersen** [comment]
The exceptions:
error: [Errno 113] No route to host
error: [Errno 111] Connection refused
until 
===SSH to Host 192.168.23.12 port : 22 SUCCESSFUL===
basically show the state change of the VM to which the test is trying to connect to.
the exceptions can be ignored as the test is able to login and perform the assertion

**Pull request merged**
