### PR TITLE
debian build: add python3-setuptools to dependencies

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes the marvin build error for ubuntu

it looks there is a regression in the marvin build , related to #6889 

```
[INFO] --- exec-maven-plugin:1.2.1:exec (package) @ cloud-marvin ---
Traceback (most recent call last):
  File "setup.py", line 20, in <module>
    from setuptools import setup, find_packages
ImportError: No module named 'setuptools'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 23, in <module>
    from distribute_setup import use_setuptools
ImportError: No module named 'distribute_setup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 27, in <module>
    raise RuntimeError("python setuptools is required to build Marvin")
RuntimeError: python setuptools is required to build Marvin
```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@blueorangutan test ubuntu22 kvm-ubuntu22

**Review by rohityadavcloud — APPROVED** [review]

**Review by harikrishna-patnala — APPROVED** [review]
LGTM

**Comment by DaanHoogland** [comment]
@weizhouapache is this ready for review/merge?

**Comment by weizhouapache** [comment]
> @weizhouapache is this ready for review/merge?

Yes @DaanHoogland , moved to ready for review.

**Review by stephankruggg — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@blueorangutan test ubuntu22 kvm-ubuntu22

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
The changes are only in build dependency, as packages are Debian build are passing that's enough to accept this PR. Merging based on packaging, and LGTMs.

**Pull request merged**
