### PR TITLE
Add the Transifex config for next version of CS (4.10)

### PR DESCRIPTION
**Pull request by milamberspace**

### CODE REVIEW

**Comment by rhtyd** [comment]
LGTM

**Comment by rhtyd** [comment]
Nevermind @blueorangutan centos7 packaging worked, debian builder had an issue so it failed. I've fixed them.

**Comment by rhtyd** [comment]
@blueorangutan kick

**Comment by rhtyd** [comment]
@blueorangutan kick

**Comment by pdion891** [comment]
Does those files actually exist? otherwise how do we generate those files?

**Comment by milamberspace** [comment]
Yes these files exists when your use the tools/transifex/sync-transifex-ui.sh script to download/upload the L10N resources files with Transifex.
These file are generated by the tx client program.
See: tools/transifex/README-transifex.txt

**Comment by pdion891** [comment]
LGTM, 

Does this command most be run every build or one time per branch only ? Shouldn't we document this process in the building doc or the wiki ?

Thanks!

**Comment by milamberspace** [comment]
Add the transifex config for new L10N resources files must be done after each new major release on master branch (for the N+1 release, and after the creation of the release branch)

After, we must update the translation on each branch (releases and master branch) regularly or just before make a minor release.

For the documentation, I've just update the wiki:
https://cwiki.apache.org/confluence/display/CLOUDSTACK/Update+L10N+files+from+Transifex+to+git+repo

**Comment by jburwell** [comment]
@milamberspace we are targeting the 4.10.0.0 RC for 25 Sept 2016.  Will you be able to investigate/resolve the Jenkins build failure by that time?

**Comment by milamberspace** [comment]
@jburwell I've just rebase and force push. All is green now.

**Comment by rhtyd** [comment]
LGTM. Since basic checks are all green and we've enough votes, I'll merge this.

**Pull request merged**
