### PR TITLE
db upgrade: use "create or replace view" instead of "alter view"

### PR DESCRIPTION
**Pull request by ustcweizhou**
### Description

I faced an old issue when I upgrade cloudstack which database is restored from backup, and got the error in upgrade

```
2020-12-10 06:36:22,252 ERROR [c.c.u.d.ScriptRunner] (main:null) (logid:) java.sql.SQLSyntaxErrorException: Access denied; you need (at least one of) the SUPER privilege(s) for this operation
2020-12-10 06:36:22,255 ERROR [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Unable to execute upgrade script
java.sql.SQLSyntaxErrorException: Access denied; you need (at least one of) the SUPER privilege(s) for this operation
        at com.cloud.utils.db.ScriptRunner.runScript(ScriptRunner.java:185)
        at com.cloud.utils.db.ScriptRunner.runScript(ScriptRunner.java:87)
        at com.cloud.upgrade.DatabaseUpgradeChecker.runScript(DatabaseUpgradeChecker.java:201)
        at com.cloud.upgrade.DatabaseUpgradeChecker.upgrade(DatabaseUpgradeChecker.java:256)
        at com.cloud.upgrade.DatabaseUpgradeChecker.check(DatabaseUpgradeChecker.java:340)
```

see more info at http://mail-archives.apache.org/mod_mbox/cloudstack-dev/201310.mbox/%3CCAM9eXO7nJOYmcZE=gte-1AiB+o8ZDtz7KuMEcy6mL-oovCUFBQ@mail.gmail.com%3E

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by rhtyd** [comment]
@weizhouapache do you think this is a blocker for 4.15?

**Comment by weizhouapache** [comment]
> @weizhouapache do you think this is a blocker for 4.15?

@rhtyd no ,it is not a blocker

**Review by DaanHoogland — APPROVED** [review]
old files but yes, valid changes

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Pull request merged**
