### PR TITLE
ui: remove CA certificate button from UI

### PR DESCRIPTION
**Pull request by rhtyd**
This removes CA certificate button from UI as this is not used and
confuses both admin and users how to use it. This may be re-introduced
in future when a use-case can be justified.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by svenvogel** [comment]
@rhtyd what was the use case before?

**Comment by rhtyd** [comment]
@svenvogel in 4.11+ if you notice there is a button on right/top side that downloads the CA certificate. This is not used at all and confuses users/admins. This removes it. The original use-case was something to do with cert setup, but that never got implemented. We may put it back if we do that in future.

**Comment by PaulAngus** [comment]
@blueorangutan package

**Comment by PaulAngus** [comment]
@blueorangutan test

**Comment by svenvogel** [comment]
@rhtyd okay i see. no problem. sounds good.

**Pull request merged**
