### PR TITLE
README: Ho ho ho!

### PR DESCRIPTION
**Pull request by rhtyd**
Merry Christmas and happy holidays! :monkey: :cloud: :santa: :christmas_tree:

/cc alphabetically-ish @andrijapanic @anuragaw @borisstoyanov @bwsw @chiradeep @csquire @DaanHoogland @DagSonsteboSB @dhlaluku @fmaximus @GabrielBrascher @gsirett @glennwagner @harikrishna-patnala @jayapalu @K0zka @karuturi @kiwiflyer @khos2ow @PaulAngus @marcaurele @mike-tutkowski @milamberspace @msinhore @nitin-maharana @NuxRo @nvazquez @pdion891 @pyr @rafaelweingartner @RPDiep @resmo @steveroles @sureshanaparti @svenvogel @swill @syed @ustcweizhou @wido and so many others!

### CODE REVIEW

**Comment by ustcweizhou** [comment]
merry xmas and happy new year!

**Comment by bwsw** [comment]
@rhtyd Thank you! Merry Christmas as well)

**Comment by rhtyd** [comment]
Can we have some LGTMs, I checked the Travis test failures were not caused by this PR ;)

**Comment by syed** [comment]
LGTM! Merry Christmas and Happy new year everyone!

**Comment by nvazquez** [comment]
LGTM. Merry Christmas and Happy New Year guys! :tada:

**Comment by khos2ow** [comment]
LGTM and merry Christmas everyone!
I do have a small comment though, why the name of branch is `xmas-2019`? :wink:

**Comment by glennwagner** [comment]
LGTM , Merry Christmas everyone, Happy new year

**Comment by andrijapanic** [comment]
+1
Merry Christmas and Happy New year to all :)

**Comment by NuxRo** [comment]
Fill your bellies and be merry! Ho ho ho :)

**Comment by PaulAngus** [comment]
+1  Merry Christmas everyone!
image

**Comment by RPDiep** [comment]
LGTM, Happy holidays and have a wonderful 2019!

**Comment by andrijapanicsb** [comment]
> > I do have a small comment though, why the name of branch is `xmas-2019`?
> > @khos2ow well it's about Christmas time and 2019 new year!

For me xmas is on 7th January 2019 - so "works on my machine" 🕺

**Comment by andrijapanicsb** [comment]
> > I do have a small comment though, why the name of branch is `xmas-2019`?
> > @khos2ow well it's about Christmas time and 2019 new year!

For me xmas is on 7th January 2019 - so "works on my machine" 🕺

**Comment by pdion891** [comment]
Best PR ever,  +1

Enjoy holidays ! :-)

**Comment by milamberspace** [comment]
LGTM
Thanks and Happy new year!

**Comment by rhtyd** [comment]
We're in violent agreement, let's merge!

**Pull request merged**
