### PR TITLE
Fix NPE on scale VM operation after the corresponding template is del…

### PR DESCRIPTION
**Pull request by harikrishna-patnala**
### Description

This is same as PR https://github.com/apache/cloudstack/pull/5721 for 4.16 branch to fix NPE on scale with deleted template

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

1. Created a VM with a template
2. Force deleted the template
3. Dynamically scaled VM created from that template -> successful

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Review by sureshanaparti — APPROVED** [review]
LGTM

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Review by weizhouapache — APPROVED** [review]

**Pull request merged**
