### PR TITLE
Display creation date for domain and account

### PR DESCRIPTION
**Pull request by ravening**
### Description
Display creation date for account and domain

**NOTE: backend change is in https://github.com/apache/cloudstack/pull/4649**
Screenshot 2021-02-11 at 16 31 36

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [X] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [X] Trivial

### CODE REVIEW

**Review by GabrielBrascher — APPROVED** [review]
Code LGTM (_"back-end" PR needs to be merged first_)

**Review by weizhouapache — APPROVED** [review]

**Review by rhtyd — APPROVED** [review]

**Comment by weizhouapache** [comment]
#4649

**Comment by shwstppr** [comment]
@blueorangutan ui

**Review by shwstppr — APPROVED** [review]
LGTM, tested with simulator env

**Pull request merged**
