### PR TITLE
CLOUDSTACK-8578: fix listVirtualMachines does not return deleted mach…

### PR DESCRIPTION
**Pull request by resmo**
…ines when zone is specified

### CODE REVIEW

**Comment by DaanHoogland** [comment]
why should we return machines that no longer exist?

**Comment by resmo** [comment]
@DaanHoogland We already do :). User permissions API is **not affected** of this change however.

The API does already return VMs `listVirtualMacines` in `destroyed` state if you have *admin* permissions. 

But if you provide `zoneid` in `listVirtualMacines` with *admin* permissions, it does not return VMs in `destroyed` state. This makes no sense to me. The bug was already fixed in CLOUDSTACK-284 but then the bug was reimplemented by accident.

**Comment by DaanHoogland** [comment]
good point so backwards compatibility is a glass eye anyway;) will merge

**Comment by bhaisaab** [comment]
this can potentially break clients depending on the behaviour when zoneid is passed

**Comment by bhaisaab** [comment]
@resmo can you send a doc PR so at least we can document this in release notes?

**Comment by resmo** [comment]
@bhaisaab Ok. I'll make a doc PR. We could probably think about extending the list API to a state e.g. `present` which returns all VMs in states `starting, running, stopped, stopping'. So the *old* behaviour could be used as well in a proper way. Any thoughts?

**Pull request closed without merging**
