### PR TITLE
Add empty config value for scope based config setting

### PR DESCRIPTION
**Pull request by sureshanaparti**
### Description

This PR add empty config value for scope based config setting.

Fixes: #5545

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [x] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

Manually tested empty config values in 'Domain' scope.

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Review by nvazquez — APPROVED** [review]
Code LGTM

**Review by vladimirpetrov — APPROVED** [review]
LGTM based on manual testing using both UI and cloudmonkey.

**Pull request merged**
