### PR TITLE
Create user 'cloud' in cloudstack-usage postinstall

### PR DESCRIPTION
**Pull request by benj-n**
### Description

This PR creates user 'cloud' in cloudstack-usage postinstall script. This ensures the chown 'cloud:cloud' command (later in the same file) is always performed with no error.

Fixes: #7507

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [X] Trivial

### CODE REVIEW

**Comment by benj-n** [comment]
This PR supersedes https://github.com/apache/cloudstack/pull/7535

**Review by DaanHoogland — APPROVED** [review]
clgtm, great work @benj-n , will test it next ...

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by weizhouapache — APPROVED** [review]
the code is same debian/cloudstack-management.postinst, which is good.

not tested yet

**Review by rohityadavcloud — APPROVED** [review]
LGTM - should we do this for EL7/EL8 etc rpms as well @benj-n for consistency?

**Comment by benj-n** [comment]
> LGTM - should we do this for EL7/EL8 etc rpms as well @benj-n for consistency?

According to https://github.com/apache/cloudstack/issues/7507#issuecomment-1562443286, the centos7/8 management and usage packages already have the 'cloud' user managed in their %pre phases.

**Comment by DaanHoogland** [comment]
@blueorangutan LLtest

**Comment by DaanHoogland** [comment]
tested on ubuntu20 (and for comparison on rocky8) works as expected

**Pull request merged**
