### PR TITLE
scripts/network/exdhcp: cleaned up code in dhcpd_edithosts.py

### PR DESCRIPTION
**Pull request by falcon78921**
## Description

Minor cleanups in ``dhcpd_edithosts.py``. Updated string formatting
to ``str.format()``. Aligning code to Python3.

Signed-off-by: James McClune <jmcclune@mcclunetechnologies.net>

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by falcon78921** [comment]
@DaanHoogland Yeah, I used ``str.format()``, which is becoming a more widespread and recommended way to format strings in Python3 (replacing the ``%`` operator). I saw that ``os.path`` is also used. ``pathlib`` is becoming a better alternative for file manipulations as well (replacing ``os.path``). If there's anything I'm missing, please let me know and I'll fix. :)

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by falcon78921** [comment]
@borisstoyanov @DaanHoogland I'm just following up on this PR. If there's anything else I need to do, please let me know :)

**Comment by DaanHoogland** [comment]
@falcon78921 master is frozen till 4.12 is released. Also there are a lot of errors in travis. I see a lot of false positives so my first instinct is restarting. Please have a look if these continue to appear.

**Comment by falcon78921** [comment]
@DaanHoogland Cool :) Thanks for the update.

**Comment by rhtyd** [comment]
We'll need to check but current systemvmtemplate only has python 2.7.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Confirmed, current systemvmtemplate based on Debian 9 does not have python 3 by default:
Screenshot from 2019-05-27 18-04-42

-1 The change may be breaking, the bigger change would be to replace all of the VR programming codebase (about 2-3k loc) with new rpc mechanism.

**Comment by falcon78921** [comment]
@rhtyd Do you want me to close?

**Comment by falcon78921** [comment]
Made some corrections regarding `pathlib` usage

**Pull request closed without merging**
