### PR TITLE
CLOUDSTACK-9335: fix typo in dashboard's fetchlatest usage

### PR DESCRIPTION
**Pull request by bhaisaab**
cc @swill @terbolous @runseb @wido @abhinandanprateek

### CODE REVIEW

**Comment by terbolous** [comment]
Tested this manually by patching dashboard.js and re-gzipping it.

The parameter is now passed as 'fetchLatest' as it should.
![Request parameters]
(https://www.dropbox.com/s/57bfp4jncgv7uge/Screenshot%202016-04-04%2009.48.05.png?dl=1)
LGTM

**Comment by remibergsma** [comment]
Works as expected, LGTM.
screen shot 2016-04-04 at 21 05 09 pm

**Comment by swill** [comment]
I don't think there are any CI tests that will actually test this.  Can we assume the verifications that you guys have done is good enough?  Also, I see that Jenkins has failed, but that seems to be a problems with Jenkins and not necessarily with this PR.  Is this ready to merge???

**Comment by rafaelweingartner** [comment]
I believe we have to be reasonable when asking/requiring functional tests.
After looking at the code, I am ok with the changes and the tests executed.

**Comment by swill** [comment]
I agree.  I just want to make sure others agree with us...

**Comment by eriweb** [comment]
Would be great with a jira ticket to track it though :)

**Comment by swill** [comment]
I agree.  @bhaisaab do you mind adding a Jira ticket for this just so we have a record of it.

**Comment by kiwiflyer** [comment]
Pulled this in manually and tested it.

image

LGTM

**Comment by bhaisaab** [comment]
@swill feel free to create a JIRA ticket for this

**Comment by terbolous** [comment]
@bhaisaab here you go: https://issues.apache.org/jira/browse/CLOUDSTACK-9335

please update the PR and add the issue to the title

**Comment by bhaisaab** [comment]
Thanks @terbolous, fixed

**Comment by bhaisaab** [comment]
@swill for the UI fix maybe in future we'll have selenium or jasmine/karma tests but for now we don't have anything other than manual testing for UI changes. Since several people on this PR have confirmed that it works, please merge. Thanks.

**Comment by swill** [comment]
Is there a way to manually kick off travis on a specific PR, or is the only way to have the author do a `push -f`?

**Comment by bhaisaab** [comment]
@swill I guess we have to do push -f; will do just now

**Comment by bhaisaab** [comment]
@swill done *though for purely JS change we may ignore CI errors if manual testing confirm a fix)

**Comment by swill** [comment]
Thanks @bhaisaab, sorry to keep having you do that.  I know it is just semantics, but I want to avoid doing `--force` merges.  I got your travis fixes merged in today, so hopefully that will reduce the failures.  :)

**Comment by bhaisaab** [comment]
Thanks @swill I totally understand

**Comment by bhaisaab** [comment]
@swill all green now

**Pull request merged**
