### PR TITLE
server: prevent update vm read-only details

### LINKED ISSUE #4514: User vm details is readonly on UI but still can be changed via api or cloudmonkey/cmk
#3244 introduced a global setting to make some details read-only on UI.
however, these details can still be changed by cloudmonkey.

it would be better to improve it.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VM
~~~

##### CLOUDSTACK VERSION

~~~
4.14/4.15
~~~

##### STEPS TO REPRODUCE

login as domain admin or regular user
create a dynamic offering
deploy a vm  with the offering, and stop it
cpuNumber, cpuSpeed and memory are visible and editable in vm Settings page
change global setting user.vm.readonly.ui.details to "dataDiskController, rootDiskController,cpuSpeed,memory,cpuNumber"
cpuNumber, cpuSpeed and memory are visible but not editable in vm Settings page

use cmk to update vm with details[0].cpuNumber=X

~~~

~~~

##### EXPECTED RESULTS

~~~
Fail with error similar as
```
You're not allowed to add or edit the restricted setting: cpuNumber
```
~~~

##### ACTUAL RESULTS

~~~
cmk command is successful. vm cpunumber is changed
~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description
Fixes behaviour in updateVirtualMachine API by disallowing updating read-only details (details mentioned in global setting `user.vm.readonly.ui.details`) of the VM for accounts other than root-admin using API. Such read-only details will be copied from original values.

Fixes #4514 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### How Has This Been Tested?
```
(localcloud) 🐱 >  list virtualmachine id=527a92ab-f59f-45fc-abc3-abf34ca5cbad
{
  "virtualmachine": {
    "account": "user",
    "affinitygroup": [],
    "cpunumber": 1,
    "cpuspeed": 500,
    "cpuused": "10%",
    "created": "2021-01-28T14:39:08+0530",
    "details": {
      "newdetail": "somethingnew"
    },
    "diskioread": 0,
    "diskiowrite": 0,
    "diskkbsread": 0,
    "diskkbswrite": 0,
    "displayname": "t1",
    "domain": "ROOT",
    "domainid": "b4924318-6146-11eb-9c0f-a0afbd4a2d60",
    "guestosid": "b48662d8-6146-11eb-9c0f-a0afbd4a2d60",
    "haenable": false,
    "hypervisor": "Simulator",
    "id": "527a92ab-f59f-45fc-abc3-abf34ca5cbad",
    "isdynamicallyscalable": false,
    "memory": 512,
    "memoryintfreekbs": 0,
    "memorykbs": 0,
    "memorytargetkbs": 0,
    "name": "t1",
    "networkkbsread": 32768,
    "networkkbswrite": 16384,
    "nic": [
      {
        "extradhcpoption": [],
        "gateway": "10.1.1.1",
        "id": "530b68fb-d15e-43cc-bb52-20b4686251ea",
        "ipaddress": "10.1.1.61",
        "isdefault": true,
        "macaddress": "02:00:67:12:00:01",
        "netmask": "255.255.255.0",
        "networkid": "39d80951-0087-4ab2-9af7-3dc886d04eb2",
        "networkname": "test",
        "secondaryip": [],
        "traffictype": "Guest",
        "type": "Isolated"
      }
    ],
    "osdisplayname": "CentOS 5.6 (64-bit)",
    "ostypeid": "b48662d8-6146-11eb-9c0f-a0afbd4a2d60",
    "passwordenabled": false,
    "readonlyuidetails": "dataDiskController, rootDiskController, newdetail",
    "rootdeviceid": 0,
    "rootdevicetype": "ROOT",
    "securitygroup": [],
    "serviceofferingid": "6338335e-5ee7-4fcc-a0cb-4746ff0d35e3",
    "serviceofferingname": "Small Instance",
    "state": "Stopped",
    "tags": [],
    "templatedisplaytext": "CentOS 5.6 (64-bit) no GUI (Simulator)",
    "templateid": "4a0360b8-6147-11eb-9c0f-a0afbd4a2d60",
    "templatename": "CentOS 5.6 (64-bit) no GUI (Simulator)",
    "userid": "07af36d0-391a-4c56-a85a-ccde0611174b",
    "username": "user",
    "zoneid": "25849759-355c-49be-b004-664f34d77a65",
    "zonename": "Sandbox-simulator"
  }
}

(localcloud) 🐱 >  set username admin
(localcloud) 🐱 > sync
Discovered 587 APIs
(localcloud) 🐱 > list configurations name=user.vm.readonly.ui.details
{
  "configuration": [
    {
      "category": "Advanced",
      "description": "List of UI read-only VM settings/details as comma separated string",
      "isdynamic": true,
      "name": "user.vm.readonly.ui.details",
      "value": "dataDiskController, rootDiskController, newdetail"
    }
  ],
  "count": 1
}
(localcloud) 🐱 > set username user
(localcloud) 🐱 > sync
Discovered 266 APIs
(localcloud) 🐱 > update virtualmachine id=527a92ab-f59f-45fc-abc3-abf34ca5cbad details[0].newdetail=somethingevennew
🙈 Error: (HTTP 431, error code 4350) You're not allowed to add or edit the read-only setting: newdetail
(localcloud) 🐱 > update virtualmachine id=527a92ab-f59f-45fc-abc3-abf34ca5cbad details[0].evennewdetail=somethingevenmorenew
{
  "virtualmachine": {
    "account": "user",
    "affinitygroup": [],
    "cpunumber": 1,
    "cpuspeed": 500,
    "created": "2021-01-28T14:39:08+0530",
    "details": {
      "evennewdetail": "somethingevenmorenew",
      "newdetail": "somethingnew"
    },
    "displayname": "t1",
    "domain": "ROOT",
    "domainid": "b4924318-6146-11eb-9c0f-a0afbd4a2d60",
    "guestosid": "b48662d8-6146-11eb-9c0f-a0afbd4a2d60",
    "haenable": false,
    "hypervisor": "Simulator",
    "id": "527a92ab-f59f-45fc-abc3-abf34ca5cbad",
    "isdynamicallyscalable": false,
    "memory": 512,
    "name": "t1",
    "nic": [
      {
        "extradhcpoption": [],
        "gateway": "10.1.1.1",
        "id": "530b68fb-d15e-43cc-bb52-20b4686251ea",
        "ipaddress": "10.1.1.61",
        "isdefault": true,
        "macaddress": "02:00:67:12:00:01",
        "netmask": "255.255.255.0",
        "networkid": "39d80951-0087-4ab2-9af7-3dc886d04eb2",
        "networkname": "test",
        "secondaryip": [],
        "traffictype": "Guest",
        "type": "Isolated"
      }
    ],
    "osdisplayname": "CentOS 5.6 (64-bit)",
    "ostypeid": "b48662d8-6146-11eb-9c0f-a0afbd4a2d60",
    "passwordenabled": false,
    "readonlyuidetails": "dataDiskController, rootDiskController, newdetail",
    "rootdeviceid": 0,
    "rootdevicetype": "ROOT",
    "securitygroup": [],
    "serviceofferingid": "6338335e-5ee7-4fcc-a0cb-4746ff0d35e3",
    "serviceofferingname": "Small Instance",
    "state": "Stopped",
    "tags": [],
    "templatedisplaytext": "CentOS 5.6 (64-bit) no GUI (Simulator)",
    "templateid": "4a0360b8-6147-11eb-9c0f-a0afbd4a2d60",
    "templatename": "CentOS 5.6 (64-bit) no GUI (Simulator)",
    "userid": "07af36d0-391a-4c56-a85a-ccde0611174b",
    "username": "user",
    "zoneid": "25849759-355c-49be-b004-664f34d77a65",
    "zonename": "Sandbox-simulator"
  }
}


```

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@shwstppr good, thanks.
should the detail name be changed from 'user.vm.readonly.ui.details' to 'user.vm.readonly.details' ?

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
@weizhouapache I think changing global setting name would require DB change and doc changes, the feature/user of the change is only UI so I guess that's why the setting name has `ui` in it.

**Comment by shwstppr** [comment]
@weizhouapache maybe we can change setting name in master alongwith similar setting changes #4135? cc @rhtyd @DaanHoogland

**Comment by DaanHoogland** [comment]
@shwstppr that PR also needs more attention to updates. I agree with the principle as this is not only UI but also API (which would be a security issue if it wasn't) as is this change lgtm

**Comment by weizhouapache** [comment]
> @weizhouapache I think changing global setting name would require DB change and doc changes, the feature/user of the change is only UI so I guess that's why the setting name has `ui` in it.



> @shwstppr that PR also needs more attention to updates. I agree with the principle as this is not only UI but also API (which would be a security issue if it wasn't) as is this change lgtm

@rhtyd @DaanHoogland 
 let's merge this, and change setting name afterwards as it requires sql change ?

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by Pearl1594 — APPROVED** [review]
Verified Behaviour. LGTM

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Pull request merged**
