### PR TITLE
Usage: usage generated for destroyed VMs with assigned backup offering

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

Fixes: https://github.com/apache/cloudstack/issues/4990
When a VM associated with a backup offering is destroyed/expunged, the backup offering isn't unassigned, hence leading to backup usage generation. This PR fixes/addresses the following:
- When a VM is destroyed, backup offering associated with the VM is removed
- A cleanup job to disassociate the backup offering from expunged VMs

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [X] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?
Created a VM and assigned a backup offering to it, destroyed the VM and verified no further usage events are generated and events corresponding to "BACKUP.OFFERING.REMOVE" is generated / added in the event table

### CODE REVIEW

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
cc @olivierlemasle can you help review and test this PR? Thanks

**Review by shwstppr — APPROVED** [review]
Code looks good

**Comment by shwstppr** [comment]
Re-kicking tests

@blueorangutan test

**Comment by olivierlemasle** [comment]
Sure, I'll be able to look at this (and #4982) tonight (Paris time). Thank you!

**Review by rhtyd — APPROVED** [review]
LGTM - let's wait for @olivierlemasle 's confirmation and smoketests before merging

**Review by olivierlemasle — COMMENTED** [review]
It should indeed fix the usage bug.

However, this also deletes all backups from deleted VMs, which seems to be breaking change.

Currently, it seems to be possible to restore an expunged VM from a backup (is it really possible @rhtyd? It's not possible with the dummy B&R provider, but it seems to be possible with Veeam, however when I tested it, I got errors). If backups on deleted VMs can indeed be restored, they are still useful and deleting them would be impactful.

**Comment by Pearl1594** [comment]
Closing this. Raised https://github.com/apache/cloudstack/pull/5017 to address the the issue of backup usage records being generated for VMs that are expunged and have no backups present.

**Pull request closed without merging**
