### PR TITLE
server: Fix update capacity for hosts take long time if there are many service offerings

### PR DESCRIPTION
**Pull request by ustcweizhou**
### Description

This PR fixes the issue that update capacity for hosts take long time if there are many service offerings.

Steps to reproduce the issue:

(1)Create 10000 service offerings (by db changes or cloudmonkey).

(2) Check the total time of periodical capacity check in cloudstack.

Without this patch, it spend 2.5 seconds (2 hosts)
```
2021-01-15 16:10:12,793 DEBUG [c.c.a.AlertManagerImpl] (CapacityChecker:ctx-5d5f3b3b) (logid:f5eb68ba) Running Capacity Checker ...
2021-01-15 16:10:15,287 DEBUG [c.c.a.AlertManagerImpl] (CapacityChecker:ctx-5d5f3b3b) (logid:f5eb68ba) Done running Capacity Checker ...
```

With this patch ,it spend 1.3 seconds (2 hosts)
```
2021-01-15 16:12:43,604 DEBUG [c.c.a.AlertManagerImpl] (CapacityChecker:ctx-a2a7f3f1) (logid:f7e0a4c5) Running Capacity Checker ...
2021-01-15 16:12:44,927 DEBUG [c.c.a.AlertManagerImpl] (CapacityChecker:ctx-a2a7f3f1) (logid:f7e0a4c5) Done running Capacity Checker ...
```

If there are 100 hosts, the total time will be reduced from 100+ seconds to around 10 seconds.
This helps a lot to reduce the execution time of prometheus exporter.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@ustcweizhou can you review the `test_01_nic` failure?

**Comment by weizhouapache** [comment]
> @ustcweizhou can you review the `test_01_nic` failure?

@rhtyd I ran the test on 4.14 and 4.15, both succeed.
can you re-kick the test ?

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
Running failed test manually @weizhouapache @rhtyd

**Review by DaanHoogland — APPROVED** [review]
looks like a sensible optimisation; fetch the offerings before looping over hosts instead of re-fetch for each host. I think only regression tests are needed for this one.

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by shwstppr — APPROVED** [review]

**Comment by shwstppr** [comment]
> @ustcweizhou can you review the `test_01_nic` failure?

Failing test verified manually,
```
==== Marvin Init Started ====

=== Marvin Parse Config Successful ===

=== Marvin Setting TestData Successful===

==== Log Folder Path: /marvin/MarvinLogs/Feb_02_2021_14_27_56_UX96H4. All logs will be available here ====

=== Marvin Init Logging Successful===

==== Marvin Init Successful ====
=== TestName: test_01_nic | Status : SUCCESS ===

```

**Pull request merged**
