### PR TITLE
Make CloudStack JSP-free

### PR DESCRIPTION
**Pull request by rhtyd**
CLOUDSTACK-9842: Make UI JSP Free
  
    We use some JSP files mainly for translation of strings in the UI. This is
    achievable purely in JavaScript. This removes those JSPs, simplifies
    translation usage and workflow (purely JS based). The l10n js (dictionary)
    files are generated from existing messages.properties files during client-ui
    code generation phase.
    
/cc @jburwell @karuturi @abhinandanprateek @murali-reddy @wido @NuxRo @milamberspace @koushik-das and others

@milamberspace can our translation workflow/infra be changed to translate the JS files instead of the messages.properties file?

### CODE REVIEW

**Comment by rhtyd** [comment]
During build step, the l10n JS files are built:

> [INFO] --- exec-maven-plugin:1.2.1:exec (generate-sources) @ cloud-client-ui ---
> Exporting compiled dictionary: /home/bhaisaab/Lab/apache/cloudstack/client/../ui/l10n//nb_NO.js
> Exporting compiled dictionary: /home/bhaisaab/Lab/apache/cloudstack/client/../ui/l10n//ca.js
> Exporting compiled dictionary: /home/bhaisaab/Lab/apache/cloudstack/client/../ui/l10n//ko_KR.js
> Exporting compiled dictionary: /home/bhaisaab/Lab/apache/cloudstack/client/../ui/l10n//de_DE.js
> Exporting compiled dictionary: /home/bhaisaab/Lab/apache/cloudstack/client/../ui/l10n//es.js
> [Warning] Found a duplicate translation for key label.provider
> [Warning] Found a duplicate translation for key label.quota.value
> [Warning] Found a duplicate translation for key label.release.dedicated.vlan.range
> [Warning] Found a duplicate translation for key label.add.isolated.guest.network
> [Warning] Found a duplicate translation for key label.na
> [Warning] Found a duplicate translation for key label.instances
> [Warning] Found a duplicate translation for key message.desc.created.ssh.key.pair
> [Warning] Found a duplicate translation for key label.advanced.search
> Exporting compiled dictionary: /home/bhaisaab/Lab/apache/cloudstack/client/../ui/l10n//en.js
> Exporting compiled dictionary: /home/bhaisaab/Lab/apache/cloudstack/client/../ui/l10n//fr_FR.js
> Exporting compiled dictionary: /home/bhaisaab/Lab/apache/cloudstack/client/../ui/l10n//ar.js
> Exporting compiled dictionary: /home/bhaisaab/Lab/apache/cloudstack/client/../ui/l10n//zh_CN.js
> Exporting compiled dictionary: /home/bhaisaab/Lab/apache/cloudstack/client/../ui/l10n//nl_NL.js
> Exporting compiled dictionary: /home/bhaisaab/Lab/apache/cloudstack/client/../ui/l10n//ru_RU.js
> Exporting compiled dictionary: /home/bhaisaab/Lab/apache/cloudstack/client/../ui/l10n//it_IT.js
> Exporting compiled dictionary: /home/bhaisaab/Lab/apache/cloudstack/client/../ui/l10n//pt_BR.js
> Exporting compiled dictionary: /home/bhaisaab/Lab/apache/cloudstack/client/../ui/l10n//hu.js
> Exporting compiled dictionary: /home/bhaisaab/Lab/apache/cloudstack/client/../ui/l10n//pl.js
> Exporting compiled dictionary: /home/bhaisaab/Lab/apache/cloudstack/client/../ui/l10n//ja_JP.js
> 

Some screenshots with existing translation/language options:

screenshot from 2016-08-30 23-29-33
screenshot from 2016-08-30 23-29-46
screenshot from 2016-08-30 23-30-11

**Comment by milamberspace** [comment]
@rhtyd Probably the best way will be to change the Transifex L10N resources files type from Unicode Properties to JSON Key/value

A sample are here:
https://www.transifex.com/ke4qqq/CloudStack_UI/47xmessagesjson/

We can create the 4.10 json l10n files and change the translation update process to get the json files instead of the properties.

**Comment by rhtyd** [comment]
Thanks @milamberspace I've modified the build process to generate l10n translation JS (dictionary) files when client/UI is built. I think if we use json file, then also we will need some sort of transformation build step so we can consume from messages.properties without changing any of our workflow if we don't have a way to directly translate into the `.js` files.

**Comment by abhinandanprateek** [comment]
LGTM on code review. Another disadvantage of jsp is the compilation. No jsp will mean smoother transitions to newer java versions.

**Comment by rhtyd** [comment]
CloudStack UI used dictionary, dictionary2 and index jsp files.

The dictionary jsp files simply added a dictionary (java script object or map) by reading through messages properties for various translations. Replacing them was easy, we added a python script (`tools/transifex/gen-l10n.py`) that would generate js files (at build time) by reading through the `messages` files such that the generated dictionary (object or map) would be exactly same as what the jsp files did.

The `index.jsp` file primarily did two things: (1) include dictionary, dictionary2 jsp files, (2) used them for translating strings. By replacing the dictionary jsp files with auto-generated translation js file based on a `lang` cookie exactly the same dictionary object was still accessible to the index.jsp file. All the translated strings in index.jsp were replaced with a new/custom `DOM` element `<translate key="some.key">`, and some code was added that would process and add text to this new dom element based on the translation key set. Replacement of `<fmt:` code with `<translate>` was done with a search/replace operation. By adding a new custom `DOM` element, no CSS changes were required. The translation was done by this method: https://github.com/shapeblue/cloudstack/blob/26b591f225abbee8690c20af914f8e37103043ef/ui/index.html#L1746

The only exception were `select` dropdowns, where translation was done explicitly by getting the DOM element and injecting `options` as seen here:
https://github.com/shapeblue/cloudstack/blob/26b591f225abbee8690c20af914f8e37103043ef/ui/index.html#L1766

**Comment by borisstoyanov** [comment]
LGTM, I've checkout the PR, builded it and deployed a simulator zone, then ran through a few localizations and did exploratory testing in the UI, all seem to work fine.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
(I checked debian pkg failed due to dns/name resolution issue).

**Comment by rhtyd** [comment]
@milamberspace since this changes the way translations are consumed, would you help review/test this? Thanks. FYI - this does not change how translation workflow works.

**Comment by jburwell** [comment]
@milamberspace to pile onto @rhtyd's comment, I would like to get this change into 4.10.0.0 which freezes Sunday (25 Sept 2016).

**Comment by jburwell** [comment]
LGTM based on code review

**Comment by jburwell** [comment]
@blueorangutan package

**Comment by jburwell** [comment]
@milamberspace are you +1/LGTM on this PR?

**Comment by milamberspace** [comment]
Not look good to me, I've found these issues:

The quote ' in French UI (and other language using quote) is precede by a backslash:
selection_342

selection_341

In Korean (and other language not fully translated), the default language (EN) is not use to display the missing translations:
selection_343

selection_344

Also, the generated files under the directory client/ui/l10n/ (*.js) must have the Apache license header.
(and probably add the l10n directory into the project's gitignore )

I don't like the idea that we have two L10N files for each language (the message_xx.properties and the (generated) xx.js. I thinks we should study to change the current process from/in transifex (move to JSON key/value file instead of the current message.properties)

**Comment by rhtyd** [comment]
Thanks @milamberspace I'll fix them, the issues come up due to differences in how java/jsp urlencoded the translation strings and how the python based messages.properties->l10n js file converter escapes the unicode strings.

The approach to move from messages.properties to json can be done in the next step, as that will require change in the transifex workflow -- while this PR aims at removing jsps without changing the transifex workflow.

**Comment by rhtyd** [comment]
@milamberspace I've fixed the issues that were raised and few other unescaped characters I found from the generated l10n js files. The `label.affinity.groups` translation does not exist in korean message.properties file so the label is not found and hence not translated and we see the label/key.

Please re-review. Thanks.

**Comment by jburwell** [comment]
@rhtyd @milamberspace I have started a conversation on dev@ to discuss transitioning to the JSON format.  Is acceptable to hold this PR until we come to consensus on that thread?

**Comment by milamberspace** [comment]
@rhtyd in the normal case, if the key label.affinity.groups doesn't exists, the default language is display ("Affinity Groups" in this case). The PR is a regression for this case (vs the current 4.9 version).
@rhtyd the quote issue is now fixed on my test platform.
@jburwell the json key/vleu format seems a good way. I will try to test the changes of current transifex process to move to json file next weekend (1st oct).

**Comment by jburwell** [comment]
@milamberspace I agree because it appears to remove the need to maintain the Python compilation script which reduces complexity and doesn't add any more build time.

**Comment by rhtyd** [comment]
@jburwell even with change in transifex format [1], some transformation and conversion of json to a js dictionary would still be needed.

@milamberspace I've fixed the issues now. Please re-review thanks.

[1] http://docs.transifex.com/formats/json

**Comment by rhtyd** [comment]
@jburwell @milamberspace with the current changes, no explicit change in workflow is needed but may be change in future. Since the aim of the PR was to get rid of jsps, I would like to avoid too many changes. Please re-review and comment if we can accept the PR without changing the transifex format/workflow.

@abhinandanprateek @murali-reddy can you help with an additional review, thanks?

**Comment by milamberspace** [comment]
@rhtyd I've just tests successfully the last version of the PR. Now if the value isn't translate, the default language is display.

**Comment by rhtyd** [comment]
Thanks @milamberspace is that a LGTM?

**Comment by milamberspace** [comment]
@rhtyd Yes LGTM.
Now (and in another PR), I would like work to try to use directly the json key/value files from Transifex.

**Comment by rhtyd** [comment]
@milamberspace thanks, yes please proceed with changing transifex format following merge of this PR. I lack experience with Transifex usage, but I can help with transforming the current messages.properties file to json etc. Let me know what I would need to do.

**Comment by rhtyd** [comment]
With the tests and lgtms, I'll go with merging this.

**Comment by rhtyd** [comment]
@milamberspace I've started a new ticket to track progress on migration of transifex to json format: https://issues.apache.org/jira/browse/CLOUDSTACK-9513

**Pull request merged**
