### PR TITLE
CLOUDSTACK-9044: Add RBD Primary Storage to the Zone Wizard.

### PR DESCRIPTION
**Pull request by borisroman**
Added to option to use RBD as primary storage in the Zone Wizard.

Pure UI change.

### CODE REVIEW

**Comment by DaanHoogland** [comment]
though this is a needed change, would we want to solve it more generally so there will be only point of maintenance?

**Comment by borisroman** [comment]
@DaanHoogland I share the same opinion. I would actually like to see the UI be a separate project. But in my opinion that supersedes this PR.

**Comment by wido** [comment]
@DaanHoogland @borisroman Fully agree, the UI is currently not the best, but this change can go in.

I want to LGTM, but it's hard to test. The code seems fine to me. I'll give my LGTM after @borisroman shows me it works.

**Comment by DaanHoogland** [comment]
@davidamorimfaria If we need to reinstoll a devcloud this week, can we verify as well?

**Comment by davidamorimfaria** [comment]
I will have a chance to test it this week

**Comment by kevindierkx** [comment]
The code looks fine to me.

@DaanHoogland @borisroman I agree decoupling the UI from the main Cloudstack project would be the better choice. Development on the main Cloudstack project wouldn't be halted by the frontend and the end user would have more choice in what frontend they would use. It would also be a great moment to look at all the frontend code and make a list of all the things that should be changed or improved. (Like testing...)

**Comment by kevindierkx** [comment]
@davidamorimfaria @borisroman Took the commit for a spin, looks like it does what it suppose to do. (Adding form elements when certain conditions are met.)

boris1
boris2

**Comment by wido** [comment]
I saw this in action today. LGTM

**Comment by borisroman** [comment]
I added a RBD pool using the ZoneWizard:

screenshot from 2015-11-09 23 24 29
screenshot from 2015-11-09 23 24 45
screenshot from 2015-11-09 23 24 55

**Comment by wilderrodrigues** [comment]
Ping @remibergsma @borisroman 

This PR LGTM :+1: 

I reviewed the code and read the comments in the PR, also looking at the tests @borisroman did and the screenshots he shared.

@remibergsma, you can proceed with the merge.

Cheers,
Wilder

**Pull request merged**
