### PR TITLE
UI: Edit instance - offer existing Groups

### PR DESCRIPTION
**Pull request by utchoang**
### Description
Edit instance - offer existing Groups
This PR for fix https://github.com/apache/cloudstack-primate/issues/743

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### Screenshots (if appropriate):
image

### CODE REVIEW

**Comment by utchoang** [comment]
@blueorangutan ui

**Review by shwstppr — APPROVED** [review]
Lgtm

**Review by davidjumani — APPROVED** [review]

**Comment by rhtyd** [comment]
@davidjumani @shwstppr was this manually tested?

**Comment by davidjumani** [comment]
@rhtyd Yes, tested and working

**Pull request merged**
