### PR TITLE
UI: Fixes notification error can't close when exit config limit tab

### PR DESCRIPTION
**Pull request by utchoang**
### Description

This PR fixes https://github.com/apache/cloudstack/issues/6602

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by slavkap — APPROVED** [review]
Thanks, @utchoang! LGTM manually tested

**Review by shwstppr — APPROVED** [review]

**Review by shwstppr — CHANGES_REQUESTED** [review]
@utchoang this introduces another issue. Now when you navigate between different domains resource count is not being updated

**Comment by shwstppr** [comment]
@utchoang removing `deep: true` fixes things for me

**Review by shwstppr — APPROVED** [review]

**Comment by shwstppr** [comment]
@slavkap can you please check once again now

**Review by slavkap — APPROVED** [review]
LGTM

**Pull request merged**
