### PR TITLE
gha(python): fix `W391` blank line at end of file

### PR DESCRIPTION
**Pull request by jbampton**
flake8 --select=W291,W292,W293,W391 .

./test/integration/smoke/test_register_userdata.py:766:1: W391 blank line at end of file

./test/integration/component/test_network_vpc_custom_dns.py:732:1: W391 blank line at end of file

### Description

This PR fixes the `flake8` test

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [X] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [X] Trivial

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@jbampton are you running these tests locally? they are not run in any of the travis jobs.

**Comment by jbampton** [comment]
Yes I run `flake8` locally.  But it runs with the GitHub Actions `SuperLinter Check` on modified files only on pull requests:

https://github.com/apache/cloudstack/actions/runs/3454836056/jobs/5766433087

**Comment by jbampton** [comment]
In future we could add `flake8` to `pre-commit` to allow everyone to run the tests locally on `git commit`.

There is another pull request where I was adding the first check with `pre-commit`. 

refs #6273

**Comment by DaanHoogland** [comment]
daring to go against principle on this one, only empty lines on end of files

**Pull request merged**
