### PR TITLE
fix typo c&p bug in externalId feature UI

### PR DESCRIPTION
**Pull request by DaanHoogland**
closes issue #2533

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
Testing
- [ ] I have added tests to cover my changes.
- [ ] All relevant new and existing integration tests have passed.
- [ ] A full integration testsuite with all test that can run on my environment has passed.

@blueorangutan package

### CODE REVIEW

**Comment by nitin-maharana** [comment]
@DaanHoogland, Thanks for the fix. @rafaelweingartner, I just had a look at the code. Everywhere the check for netmask is performed with the gateway only (gateway != null && netmask != null), but I couldn't able to figure out, how ACS picks the default value if it is null.

**Comment by rhtyd** [comment]
@DaanHoogland can you add a screenshot to show that some testing was done, then we can merge this.

**Comment by rafaelweingartner** [comment]
@rhtyd Do we really need a screenshot here? Looking at the code it is clear the problem and how it was fixed.

What do you think @DaanHoogland?

**Comment by rhtyd** [comment]
Sure, @rafaelweingartner we can accept this without explicit screenshot. In which case I'll merge this.

**Comment by DaanHoogland** [comment]
sorry @rhtyd and @rafaelweingartner I didn't look at adding the screen shot. I'm not sure twhat i would have been adding. probably the lack of an error but it was tested by a colleague.

**Pull request merged**
