### PR TITLE
ui: fix account list on domain change in filterview

### LINKED ISSUE #9274: Search filter does not work for domain/account
see screenshot

Issue 1: the list of account is not updated when domain is changed. All accounts are listed
image

Issue 2: got an exception when search by account
image

the account name should be passed instead of account uuid

looks like related to #9068

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.19/main
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #9274

Fixes the following issues with filter widget in the UI
- Account element loading
- Account filtering usage based on name and not with UUID
- Listing accounts for only the selected domain
- Labels for primary storage element

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):
Primary storage list labels,
Before
Screenshot from 2024-07-08 14-35-39
After
Screenshot from 2024-07-08 14-36-00

Account filtering after fix,

https://github.com/apache/cloudstack/assets/153340/c45a8403-f416-4562-9595-a052e515806b

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan ui

**Review by rohityadavcloud — APPROVED** [review]

**Review by DaanHoogland — APPROVED** [review]
code looks good , but some more test info would be useful. I suppose this is in the deploy instance dialog. This would not be clear to the outsider.

**Comment by shwstppr** [comment]
Thanks @weizhouapache. I'll check

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by weizhouapache** [comment]
thanks @shwstppr 

tested some actions
- switch from ROOT domain to a sub-domain, the account list is updated. looks good
- switch from sub-domain to ROOT domain, the account list is updated, which contains all accounts (in ROOT domain and sub-domain)
- search by ROOT domain and an account in ROOT domain, it works
- search by sub-domain and an account in the sub-domain, it works
- search by ROOT domain and an account in the sub-domain, it throws an exception

maybe we do not need to list the accounts in the sub-domains of selected domain.
cc @sureshanaparti @shwstppr

**Review by vishesh92 — APPROVED** [review]

**Comment by vishesh92** [comment]
code looks good to me.

**Comment by vishesh92** [comment]
> thanks @shwstppr
> 
> tested some actions
> 
>     * switch from ROOT domain to a sub-domain, the account list is updated. looks good
> 
>     * switch from sub-domain to ROOT domain, the account list is updated, which contains all accounts (in ROOT domain and sub-domain)
> 
>     * search by ROOT domain and an account in ROOT domain, it works
> 
>     * search by sub-domain and an account in the sub-domain, it works
> 
>     * search by ROOT domain and an account in the sub-domain, it throws an exception
> 
> 
> maybe we do not need to list the accounts in the sub-domains of selected domain. cc @sureshanaparti @shwstppr

Agree with @weizhouapache . AFAIK, for all the list queries for a resource, when we specify domainid, it lists resources for that specific domainid and not the subdomains.

**Comment by shwstppr** [comment]
@weizhouapache cc @vishesh92 I guess that needs an API change,

```
(qaserver) 🐱 > list accounts domainid=b32b3316-6c14-11ed-86c2-1e0093003d07 filter=id,name,domainid
{
  "account": [
    {
      "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
      "id": "fda39ec5-6c14-11ed-86c2-1e0093003d07",
      "name": "admin"
    },
    {
      "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
      "id": "ef45928c-b2cb-4f9d-93cd-a484e761d4f9",
      "name": "baremetal-system-account"
    },
    {
      "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
      "id": "cd9ebe99-e02c-4385-b6ae-bac1ea677489",
      "name": "rohit"
    },
    {
      "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
      "id": "4e9e632c-ee02-49c1-9868-b53700246c73",
      "name": "euler"
    },
    {
      "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
      "id": "36b4c0a4-b339-40f0-9991-b17282a686a9",
      "name": "rick"
    },
    {
      "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
      "id": "04efc774-1777-4056-9cd7-21e27aa52a72",
      "name": "testy"
    },
    {
      "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
      "id": "705e654b-d85d-456d-8e51-cbe6a14865ad",
      "name": "user"
    },
    {
      "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
      "id": "f79af173-32c1-4f0b-bb0a-6acb433aabb3",
      "name": "capc"
    },
    {
      "domainid": "ae613512-769e-48cd-bd93-a685b9ac9c0a",
      "id": "3dd88047-73dd-4795-833d-da87e13c0698",
      "name": "test"
    }
  ],
  "count": 9
}
(qaserver) 🐱 > list accounts domainid=b32b3316-6c14-11ed-86c2-1e0093003d07 filter=id,name,domainid isrecursive=false 
{
  "account": [
    {
      "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
      "id": "fda39ec5-6c14-11ed-86c2-1e0093003d07",
      "name": "admin"
    },
    {
      "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
      "id": "ef45928c-b2cb-4f9d-93cd-a484e761d4f9",
      "name": "baremetal-system-account"
    },
    {
      "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
      "id": "cd9ebe99-e02c-4385-b6ae-bac1ea677489",
      "name": "rohit"
    },
    {
      "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
      "id": "4e9e632c-ee02-49c1-9868-b53700246c73",
      "name": "euler"
    },
    {
      "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
      "id": "36b4c0a4-b339-40f0-9991-b17282a686a9",
      "name": "rick"
    },
    {
      "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
      "id": "04efc774-1777-4056-9cd7-21e27aa52a72",
      "name": "testy"
    },
    {
      "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
      "id": "705e654b-d85d-456d-8e51-cbe6a14865ad",
      "name": "user"
    },
    {
      "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
      "id": "f79af173-32c1-4f0b-bb0a-6acb433aabb3",
      "name": "capc"
    },
    {
      "domainid": "ae613512-769e-48cd-bd93-a685b9ac9c0a",
      "id": "3dd88047-73dd-4795-833d-da87e13c0698",
      "name": "test"
    }
  ],
  "count": 9
}
(qaserver) 🐱 > list accounts domainid=b32b3316-6c14-11ed-86c2-1e0093003d07 filter=id,name,domainid isrecursive=false listall=false 
{
  "account": [
    {
      "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
      "id": "fda39ec5-6c14-11ed-86c2-1e0093003d07",
      "name": "admin"
    },
    {
      "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
      "id": "ef45928c-b2cb-4f9d-93cd-a484e761d4f9",
      "name": "baremetal-system-account"
    },
    {
      "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
      "id": "cd9ebe99-e02c-4385-b6ae-bac1ea677489",
      "name": "rohit"
    },
    {
      "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
      "id": "4e9e632c-ee02-49c1-9868-b53700246c73",
      "name": "euler"
    },
    {
      "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
      "id": "36b4c0a4-b339-40f0-9991-b17282a686a9",
      "name": "rick"
    },
    {
      "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
      "id": "04efc774-1777-4056-9cd7-21e27aa52a72",
      "name": "testy"
    },
    {
      "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
      "id": "705e654b-d85d-456d-8e51-cbe6a14865ad",
      "name": "user"
    },
    {
      "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
      "id": "f79af173-32c1-4f0b-bb0a-6acb433aabb3",
      "name": "capc"
    },
    {
      "domainid": "ae613512-769e-48cd-bd93-a685b9ac9c0a",
      "id": "3dd88047-73dd-4795-833d-da87e13c0698",
      "name": "test"
    }
  ],
  "count": 9
}
```

**Comment by weizhouapache** [comment]
> @weizhouapache cc @vishesh92 I guess that needs an API change,
> 
> ```
> (qaserver) 🐱 > list accounts domainid=b32b3316-6c14-11ed-86c2-1e0093003d07 filter=id,name,domainid
> {
>   "account": [
>     {
>       "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
>       "id": "fda39ec5-6c14-11ed-86c2-1e0093003d07",
>       "name": "admin"
>     },
>     {
>       "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
>       "id": "ef45928c-b2cb-4f9d-93cd-a484e761d4f9",
>       "name": "baremetal-system-account"
>     },
>     {
>       "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
>       "id": "cd9ebe99-e02c-4385-b6ae-bac1ea677489",
>       "name": "rohit"
>     },
>     {
>       "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
>       "id": "4e9e632c-ee02-49c1-9868-b53700246c73",
>       "name": "euler"
>     },
>     {
>       "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
>       "id": "36b4c0a4-b339-40f0-9991-b17282a686a9",
>       "name": "rick"
>     },
>     {
>       "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
>       "id": "04efc774-1777-4056-9cd7-21e27aa52a72",
>       "name": "testy"
>     },
>     {
>       "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
>       "id": "705e654b-d85d-456d-8e51-cbe6a14865ad",
>       "name": "user"
>     },
>     {
>       "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
>       "id": "f79af173-32c1-4f0b-bb0a-6acb433aabb3",
>       "name": "capc"
>     },
>     {
>       "domainid": "ae613512-769e-48cd-bd93-a685b9ac9c0a",
>       "id": "3dd88047-73dd-4795-833d-da87e13c0698",
>       "name": "test"
>     }
>   ],
>   "count": 9
> }
> (qaserver) 🐱 > list accounts domainid=b32b3316-6c14-11ed-86c2-1e0093003d07 filter=id,name,domainid isrecursive=false 
> {
>   "account": [
>     {
>       "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
>       "id": "fda39ec5-6c14-11ed-86c2-1e0093003d07",
>       "name": "admin"
>     },
>     {
>       "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
>       "id": "ef45928c-b2cb-4f9d-93cd-a484e761d4f9",
>       "name": "baremetal-system-account"
>     },
>     {
>       "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
>       "id": "cd9ebe99-e02c-4385-b6ae-bac1ea677489",
>       "name": "rohit"
>     },
>     {
>       "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
>       "id": "4e9e632c-ee02-49c1-9868-b53700246c73",
>       "name": "euler"
>     },
>     {
>       "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
>       "id": "36b4c0a4-b339-40f0-9991-b17282a686a9",
>       "name": "rick"
>     },
>     {
>       "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
>       "id": "04efc774-1777-4056-9cd7-21e27aa52a72",
>       "name": "testy"
>     },
>     {
>       "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
>       "id": "705e654b-d85d-456d-8e51-cbe6a14865ad",
>       "name": "user"
>     },
>     {
>       "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
>       "id": "f79af173-32c1-4f0b-bb0a-6acb433aabb3",
>       "name": "capc"
>     },
>     {
>       "domainid": "ae613512-769e-48cd-bd93-a685b9ac9c0a",
>       "id": "3dd88047-73dd-4795-833d-da87e13c0698",
>       "name": "test"
>     }
>   ],
>   "count": 9
> }
> (qaserver) 🐱 > list accounts domainid=b32b3316-6c14-11ed-86c2-1e0093003d07 filter=id,name,domainid isrecursive=false listall=false 
> {
>   "account": [
>     {
>       "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
>       "id": "fda39ec5-6c14-11ed-86c2-1e0093003d07",
>       "name": "admin"
>     },
>     {
>       "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
>       "id": "ef45928c-b2cb-4f9d-93cd-a484e761d4f9",
>       "name": "baremetal-system-account"
>     },
>     {
>       "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
>       "id": "cd9ebe99-e02c-4385-b6ae-bac1ea677489",
>       "name": "rohit"
>     },
>     {
>       "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
>       "id": "4e9e632c-ee02-49c1-9868-b53700246c73",
>       "name": "euler"
>     },
>     {
>       "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
>       "id": "36b4c0a4-b339-40f0-9991-b17282a686a9",
>       "name": "rick"
>     },
>     {
>       "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
>       "id": "04efc774-1777-4056-9cd7-21e27aa52a72",
>       "name": "testy"
>     },
>     {
>       "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
>       "id": "705e654b-d85d-456d-8e51-cbe6a14865ad",
>       "name": "user"
>     },
>     {
>       "domainid": "b32b3316-6c14-11ed-86c2-1e0093003d07",
>       "id": "f79af173-32c1-4f0b-bb0a-6acb433aabb3",
>       "name": "capc"
>     },
>     {
>       "domainid": "ae613512-769e-48cd-bd93-a685b9ac9c0a",
>       "id": "3dd88047-73dd-4795-833d-da87e13c0698",
>       "name": "test"
>     }
>   ],
>   "count": 9
> }
> ```


@shwstppr 
as a workaround, can we filter the accounts by domainid or domain path on UI ?

**Comment by shwstppr** [comment]
@weizhouapache done

**Review by weizhouapache — APPROVED** [review]
verified ok

thanks @shwstppr for the fix

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by sureshanaparti** [comment]
@blueorangutan ui

**Pull request merged**
