### PR TITLE
Enable CPU cap in VRs if the offering has a CPU cap limitation

### PR DESCRIPTION
**Pull request by SadiJr**
### Description

When deploying a new VR, using a network offering with CPU cap, this limitation is not respected in the VR, because in the definition and persistence of VR in database, the configuration of CPU cap of the network offering is not considered, and always uses the value `false`. This PR aims to fix this behavior, to respect the CPU cap of the network offering.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### How Has This Been Tested?
It was tested in a local lab:

1. I created new isolated networks, and also created new VMs that use they;
2. I executed an `dumpxml` in the VR definition;
3. Before, the XML of the VR does not have the cpushared tag;
4. Now, the definition of the VR have the cpushares tag, when using a network offering with CPU cap.

### CODE REVIEW

**Review by ezntt — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@ezntt please comment on why you approve. Did you test/review and if test, how?

**Comment by ezntt** [comment]
Sure, @DaanHoogland, I approve the feature based on my testing, which was carried out using a similar approach to the PR owner.

I tested the change by creating a VR and verifying its dumpxml to confirm that cpushares tag was set correctly. Specifically, I confirmed that the tag:
```
<cputune>
    <shares>500</shares> 
</cputune>
```
were properly defined, which confirmed that the change was successful.

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by DaanHoogland** [comment]
> Sure, @DaanHoogland, I approve the feature based on my testing, which was carried out using a similar approach to the PR owner.
> 
> I tested the change by creating a VR and verifying its dumpxml to confirm that cpushares tag was set correctly. Specifically, I confirmed that the tag:
> ```
> <cputune>
>     <shares>500</shares> 
> </cputune>
> ```
> were properly defined, which confirmed that the change was successful.

Great work @ezntt , we have a rule to have at least  one lgtm based on code review and one lgtm based on 3rd party testing. Hence my question.

**Review by stephankruggg — APPROVED** [review]
CLGTM, not manually tested

**Comment by kiranchavala** [comment]
@SadiJr @DaanHoogland 

I have performed a manual test on 4.17.2 release and I observe that cpu cap is honoured 

Let me know if any step is missing in  reproducing the issue ?


Steps that I have followed

1. Create router with the default system offering 


Default-systemoffering

Login to the kvm host where the router is running and execute

virsh dumpxml <>

 <cputune>
    <shares>250</shares>
  </cputune>

2. Create a system offering with cpu-cap enabled

systemoffering-test-cpu-cap

3. Change the global setting value of   "router.service.offering" to the uuid of system offering with cpu-cap enabled

4. Create a router with the new system offering for router with cpu-cap

Observer the cpushare tag is present 

virsh dumpxml <>

  <cputune>
    <shares>256</shares>
  </cputune>

**Review by rohityadavcloud — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Pull request merged**
