### PR TITLE
systemvm: add template_zone_ref record when add a new zone with same hypervisor type

### LINKED ISSUE #8388: Template reported as Ready/Installed only based on the template_stor_ref, ignoring template_zone_ref
ACS 4.18.1

As the title says:

image

- The template_zone_ref record for the given template is missing/not present
- The template_store_ref record for the given template is present/populated.
- Template is present on the Secondary Storage
- ACS shows the template as Ready/Installed, while in reality, ACS consider it absent in that Zone (when you try to use it) - due to missing zone ref records.

**Reproduce** the issue (with systemVM template specifically, can be tested with User templates): 

- Disable the zone, delete SSVM/CPVM
- in the DB, remove the record for the systemVM template from the template_zone_ref
- Enable the Zone, observer SSVM/CPVM created in DB but not started
- Observer the mgmt logs having error: com.cloud.utils.exception.CloudRuntimeException: Unable to orchestrate start VM instance {"id":4,"instanceName":"v-4-VM","type":"ConsoleProxy","uuid":"c4bc6e96-d0ff-49ef-84c0-2e3f9d209092"} due to [T**emplate for the VM instance can not be found in the zone ID: %s,** VM instance configuration needs to be updated]. 

This can be fixed by simply adding a record back to the zone ref table, for the correct template_id and that's all.

**Problem:** The UI (and/or API) should not show template as Ready and available only based on the template_store_ref

**Proposal:** improve it to explain that either 1) Template is not ready in the given Zone or 2) Say that the template is installed, but not "registered" in that specific Zone

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR should fix #8388 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

The fix ensures that when you have at least one Zone with a specific hypervisor type (e.g. KVM), then when adding a new Zone with the same hypervisor type, even if the systemVM template for that hypervisor (when registered in the original Zone) is not marked as cross_zone=1 (in vm_template table) - i.e. when it's not marked for "ALL ZONES" - CloudStack will created the record in the template_zone_ref table, and the rest of the work will be done by the automatic systemVM template installation script (that runs when a first Secondary Storage is added inside a new Zone)

### CODE REVIEW

**Comment by weizhouapache** [comment]
cc @andrijapanicsb

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by sureshanaparti — APPROVED** [review]
changes lgtm

**Comment by weizhouapache** [comment]
@blueorangutan LLtest matrix

**Comment by rohityadavcloud** [comment]
@blueorangutan LLtest matrix

**Review by andrijapanicsb — APPROVED** [review]
LGTM

(updated the desc, so it becomes readable for regular mortals :)

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan LLtest

**Comment by weizhouapache** [comment]
tests result
```
10:14:53 Smoke tests completed. 106 look OK, 3 have errors, 0 did not run
10:14:53 Only failed and skipped tests results shown below:
10:14:53 
10:14:53 
10:14:53 Test | Result | Time (s) | Test File
10:14:53 --- | --- | --- | ---
10:14:53 test_04_rvpc_privategw_static_routes | `Failure` | 954.59 | test_privategw_acl.py
10:14:53 test_01_invalid_upgrade_kubernetes_cluster | `Failure` | 0.01 | test_kubernetes_clusters.py
10:14:53 test_02_upgrade_kubernetes_cluster | `Failure` | 0.00 | test_kubernetes_clusters.py
10:14:53 test_03_deploy_and_scale_kubernetes_cluster | `Failure` | 0.00 | test_kubernetes_clusters.py
10:14:53 test_04_autoscale_kubernetes_cluster | `Failure` | 0.00 | test_kubernetes_clusters.py
10:14:53 test_05_basic_lifecycle_kubernetes_cluster | `Failure` | 0.00 | test_kubernetes_clusters.py
10:14:53 test_06_delete_kubernetes_cluster | `Failure` | 0.00 | test_kubernetes_clusters.py
10:14:53 test_07_deploy_kubernetes_ha_cluster | `Failure` | 0.00 | test_kubernetes_clusters.py
10:14:53 test_08_upgrade_kubernetes_ha_cluster | `Failure` | 0.00 | test_kubernetes_clusters.py
10:14:53 test_09_delete_kubernetes_ha_cluster | `Failure` | 0.00 | test_kubernetes_clusters.py
10:14:53 test_10_vpc_tier_kubernetes_cluster | `Failure` | 0.00 | test_kubernetes_clusters.py
10:14:53 test_08_migrate_vm | `Error` | 40.57 | test_vm_life_cycle.py
```

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
tested ok, this is ready for review now

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
merging based on approvals and CI tests

**Pull request merged**
