### PR TITLE
CLOUDSTACK-10127: KVM + Ovs: Incorrect devId on static nat

### PR DESCRIPTION
**Pull request by fmaximus**

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
Several failures seen, I'll rerun tests.
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@fmaximus can you check new/additional failures than the baseline failures seen in #2289

**Comment by fmaximus** [comment]
@rhtyd This branch is against 4.9, is there a baseline of failures on 4.9?

**Comment by rhtyd** [comment]
@fmaximus I think I closed that old PR, can kick one over the weekend.

**Comment by svenvogel** [comment]
@rhtyd Close the old PR? Which one is the old one?

**Comment by rhtyd** [comment]
@svenvogel Frank asked if we've a 4.9 baseline to compare against, I closed the last 4.9 smoketests PR #2217

**Comment by svenvogel** [comment]
Hi @fmaximus,  Hi @rhtyd 

we tried to add this fix to 4.10 and build new rpms but it seems that the fix dont work. i think there are not so much changes to 4.10. we added you commit in our repo. 

`[root@csmgmt02 resource]# find . -iname libvirtco* -ls
17608816    4 -rw-r--r--   1 root     root         3710 Nov 12 19:31 ./wrapper/LibvirtConsoleProxyLoadCommandWrapper.class
18182547    8 -rw-r--r--   1 root     root         5786 Nov 12 19:31 ./wrapper/LibvirtCopyVolumeCommandWrapper.class
1006374    4 -rw-r--r--   1 root     root         2260 Nov 12 19:31 ./LibvirtComputingResource$KeyValueInterpreter.class
1006375    4 -rw-r--r--   1 root     root         1357 Nov 12 19:31 ./LibvirtComputingResource$BridgeType.class
1006376    4 -rw-r--r--   1 root     root         1439 Nov 12 19:31 ./LibvirtComputingResource$1.class
1006377    4 -rw-r--r--   1 root     root         1192 Nov 12 19:31 ./LibvirtComputingResource$VmStats.class
1006378    4 -rw-r--r--   1 root     root          963 Nov 12 19:31 ./LibvirtComputingResource$2.class
1006379  120 -rw-r--r--   1 root     root       120820 Nov 12 19:31 ./LibvirtComputingResource.class
1006404    4 -rw-r--r--   1 root     root         3679 Nov 12 19:31 ./LibvirtConnection.class`

there are new class files.  we added
`import java.util.EnumMap;`

`        try {
            conn = getLibvirtUtilitiesHelper().getConnectionByVmName(routerName);
            final IpAddressTO[] ips = cmd.getIpAddresses();
            Integer devNum = 0;
            final Map<TrafficType, Integer> trafficTypeToNicNum = new EnumMap<>(TrafficType.class);
            final List<InterfaceDef> pluggedNics = getInterfaces(conn, routerName);

            for (final InterfaceDef pluggedNic : pluggedNics) {
                final String pluggedVlan = pluggedNic.getBrName();
                if (pluggedVlan.equalsIgnoreCase(_linkLocalBridgeName)) {
                    trafficTypeToNicNum.put(TrafficType.Control, devNum);
                } else if (pluggedVlan.equalsIgnoreCase(_publicBridgeName)) {
                    trafficTypeToNicNum.put(TrafficType.Public, devNum);
                } else if (pluggedVlan.equalsIgnoreCase(_privBridgeName)) {
                    trafficTypeToNicNum.put(TrafficType.Management, devNum);
                } else if (pluggedVlan.equalsIgnoreCase(_guestBridgeName)) {
                    trafficTypeToNicNum.put(TrafficType.Guest, devNum);
                }
                devNum++;
            }

            for (final IpAddressTO ip : ips) {
                ip.setNicDevId(trafficTypeToNicNum.get(ip.getTrafficType()));
            }`

after new deployment of a vpc we added a static nat

root@r-40-VM:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 0e:00:a9:fe:01:23 brd ff:ff:ff:ff:ff:ff
    inet 169.254.1.35/16 brd 169.254.255.255 scope global eth0
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 1e:00:7b:00:00:70 brd ff:ff:ff:ff:ff:ff
    inet 146.0.122.142/26 brd 146.0.122.191 scope global eth1
4: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 02:00:3c:6c:00:02 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.254/24 brd 192.168.1.255 scope global eth2
    **inet 146.0.122.143/26 brd 146.0.122.191 scope global eth2**

result, public ip is on the internal network.

is there something we miss or wrong?

**Comment by svenvogel** [comment]
@fmaximus 

No we tried it with redundant VPC offering. It seems the same problem like this Bug. Normal offer is fixed with this but not redundant Offering. Thats not fixed with this pull request.

@fmaximus can this fix also applied to redundant offering?

thanks

Sven

**Comment by rhtyd** [comment]
@fmaximus I see several failures compared to baseline 4.9 tests results: https://github.com/apache/cloudstack/pull/2318

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Ignoring centos6 failure that was intermittent pkging failure
@blueorangutan test

**Comment by rhtyd** [comment]
@fmaximus we've done a couple of rounds of regression tests, can you check the failures? Alternatively, re-open this for master?

**Comment by svenvogel** [comment]
@fmaximus @rhtyd some news about this commit.

**Comment by rhtyd** [comment]
@svenvogel we need to hear from @fmaximus on the failures seen in the test results -- if they are caused by this change or intermittent/env introduced

**Comment by rhtyd** [comment]
Since the author of the PR is not replying, I'll port this PR/changes to #2211 and see if it passes the smoketests in which case I may consider merging this PR or via #2211.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@fmaximus I did testing in my branch/pr #2211 and found that the dev id is not assigned in case of private gate and this fails with an issue similar to https://issues.apache.org/jira/browse/CLOUDSTACK-9759 where when nic_dev_id is not provided, it leads to ethNone is ips.json and fails VPC deployment and related test as seen in test failures on this PR. Please fix this and test against a normal non-ovs (bridge) env, thanks.

**Comment by fmaximus** [comment]
Rewrite using Mac Address, should work now.
Checked the implementation for PrivateGateway on LinuxBridge.

**Comment by rhtyd** [comment]
Thanks @fmaximus I'll kick another round of tests
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
Test LGTM, I'll check if rest of the failures are related to PR or environment introduced. Additional review requested - @marcaurele @wido @ustcweizhou @rafaelweingartner and others.

**Comment by rhtyd** [comment]
For testing purposes, I've changed the branch's base to master to kick tests. Once they are okay, we can merge this.
@blueorangutan package

**Comment by borisstoyanov** [comment]
let me test this blocker as well

**Comment by rhtyd** [comment]
I'll close and re-open this PR to re-kick travis, it's not pick up changes and failing due to base branch changes not propagated.

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
Merged based on two lgtms and test results.

**Pull request merged**
