### PR TITLE
npm audit fix

### PR DESCRIPTION
**Pull request by rohityadavcloud**
Runs `npm audit fix` and commits changes.

### CODE REVIEW

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan ui

**Comment by davidjumani** [comment]
Could cause potential conflicts with https://github.com/apache/cloudstack/pull/6091
Can they both be integrated into a single PR @rohityadavcloud

**Comment by rohityadavcloud** [comment]
Let me drop this, since we've major change in main/4.17 we can keep the other PR.

**Pull request closed without merging**
