### PR TITLE
Remove unneeded duplicate words

### PR DESCRIPTION
**Pull request by jbampton**
### Description

This PR removes some unneeded duplicate words.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [X] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [X] Trivial

### CODE REVIEW

**Comment by jbampton** [comment]
@blueorangutan package

**Review by harikrishna-patnala — APPROVED** [review]
LGTM

**Review by DaanHoogland — APPROVED** [review]
lgtm

**Comment by DaanHoogland** [comment]
@shwstppr this is only log messages, parameter descriptors and comments. I think we can include this.

**Review by shwstppr — APPROVED** [review]

**Pull request merged**
