### PR TITLE
ui: load project list with minimum details

### LINKED ISSUE #9679: Project Dropdown in Dashboard takes minutes to load
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.19.1.1
~~~

##### SUMMARY

When logging in as Admin, Domain Admin or User, when clicking on the Project Drop down, it doesnt display info at first. 

Screenshot 2024-09-13 at 9 15 21 PM

It shows 0 for a long time (around 30s-1min) in order for the project list to be fully loaded. 

But after loading, if you click on the dropdown again, it shows 0 again.

##### STEPS TO REPRODUCE

~~~
1. Login to Cloudstack Dashboard
2. Select 'Project' dropdown
3. Notice it display 0 and No Data
4. Wait for 30s-1min and the project list will be loaded
~~~

##### EXPECTED RESULTS

~~~
Project Dropdown to load faster (eg. 1-3 seconds)
~~~

##### ACTUAL RESULTS

~~~
Project Dropdown takes 30s-1min to load
~~~

### PR DESCRIPTION
**Pull request by rohityadavcloud**
This calls listProjects with details=min in the global header menu.

Stole idea/diff from @weizhouapache 's https://github.com/apache/cloudstack/issues/9679#issuecomment-2358596154 :)

Fixes #9679

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functional
- [ ] ty)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan ui

**Comment by rohityadavcloud** [comment]
@blueorangutan ui

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Review by JoaoJandre — APPROVED** [review]
CLGTM

**Review by DaanHoogland — APPROVED** [review]

**Comment by DaanHoogland** [comment]
tested in qa. @JoaoJandre are we still merging 4.19 bugfixes?

**Pull request merged**
