### PR TITLE
New feature: Resource count (CPU/RAM) take only running vms into calculation

### PR DESCRIPTION
**Pull request by ustcweizhou**
## Description

Stopped VMs do not use CPU/RAM actually.
A new global configuration resource.count.running.vms.only is added to determine whether resource (cpu/memory) of only running vms (including Starting/Stopping) will be taken into calculation of resource consumption.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

all testing in test/integration/component/test_resource_count_running_vms.py passed, including
deploy/start/stop/reboot a vm
update a vm with displayvm
destroy/expunge vm

tested with resource.count.running.vms.only is true and false both.

Two issues found in the testing:  #3758 #3759

### CODE REVIEW

**Comment by luhaijiao** [comment]
This is introducing a flexible way to calculate the resource only for running VMs.  It's particulalry useful for some customer senario, e.g. quota calculation.

Thanks weizhou !

**Comment by svenvogel** [comment]
@weizhouapache nice feature. its good to get the calculation in a better state.

**Comment by andrijapanicsb** [comment]
@blueorangutan package

**Comment by andrijapanicsb** [comment]
@blueorangutan test

**Comment by andrijapanicsb** [comment]
wow, it only took 2 days for the monkey to kick the tests... nice

**Comment by rhtyd** [comment]
@ustcweizhou can you fix the merge conflict?

**Comment by weizhouapache** [comment]
@rhtyd rebased with latest master

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@ustcweizhou can you check the one failing Travis test?

**Comment by weizhouapache** [comment]
@rhtyd 
rebased with latest master
let's see if travis test fails again.

**Comment by DaanHoogland** [comment]
all travis failures are long logs. merging

**Comment by rhtyd** [comment]
@ustcweizhou a new marvin test was added to component, if it's a fast tests (doesn't take time to run) - please move to smoke and also add it to `.travis.yml` cc @DaanHoogland

**Comment by DaanHoogland** [comment]
@rhtyd we already suffer from failures due to long logs. I think we must skim the load we lay on travis. (someday soon)

**Comment by rhtyd** [comment]
@DaanHoogland tests added to component are not run by default, so it's like not adding the test in the first place. A new job runner/block can be easily added to Travis. We've like 20 odd jobs/runs per PR.

**Comment by DaanHoogland** [comment]
we are using 18. is 20 the maximum that you know, @rhtyd ? I would like to see each test run for each change, but that may be too costly.

**Pull request merged**
