### PR TITLE
cleanup: remove unused class org.apache.cloudstack.network.NetworkOrchestrator

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR removes org.apache.cloudstack.network.NetworkOrchestrator which is useless

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]

**Comment by weizhouapache** [comment]
@blueorangutan test

**Review by rohityadavcloud — APPROVED** [review]

**Review by harikrishna-patnala — COMMENTED** [review]
@weizhouapache I see the whole module "network" has only one interface. Can we remove the module itself, something like this

	deleted:    engine/network/pom.xml
	deleted:    engine/network/src/main/java/org/apache/cloudstack/network/NetworkOrchestrator.java
	modified:   engine/pom.xml

**Comment by weizhouapache** [comment]
> @weizhouapache I see the whole module "network" has only one interface. Can we remove the module itself, something like this
> 
> ```
> deleted:    engine/network/pom.xml
> deleted:    engine/network/src/main/java/org/apache/cloudstack/network/NetworkOrchestrator.java
> modified:   engine/pom.xml
> ```

@harikrishna-patnala 
good point, I will update this PR

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Review by harikrishna-patnala — APPROVED** [review]
Thanks for addressing the comments @weizhouapache 

LGTM

**Comment by DaanHoogland** [comment]
@blueorangutan test centos7 vmware-67u3

**Pull request merged**
