### PR TITLE
debian/control: add uuid-runtime to cloudstack-common, ufw/apparmor to cloudstack-agent

### PR DESCRIPTION
**Pull request by ustcweizhou**
## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
makes sense

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by shwstppr — COMMENTED** [review]
LGTM on changes. Have kicked Trillian test on Ubuntu18 through Jenkins

**Review by rhtyd — APPROVED** [review]

**Pull request merged**
