### PR TITLE
Tagging tests appropriately to pick them for running on basic zone

### PR DESCRIPTION
**Pull request by sanju1010**
Adding additional tag to the list of tags.

### CODE REVIEW

**Comment by bvbharatk** [comment]
LGTM

**Comment by harikrishna-patnala** [comment]
LGTM

**Comment by karuturi** [comment]
No direct commits to master. all the commits to master should be merges. 
I earlier reverted and merged a PR. Please check the comments on PR #728 and merge the PR

**Comment by karuturi** [comment]
I am reverting this direct commit. Please reopen the PR and use the git pr script to merge

**Comment by remibergsma** [comment]
@karuturi Thank you

**Pull request closed without merging**
