### PR TITLE
cks: fix k8s cluster network deletion

### LINKED ISSUE #4056: The listKubernetesSupportedVersions API does not honour searching
The kubernetes ISOs or the listKubernetesSupportedVersions API does not support searching as the keyword parameter is not honoured. Fixing this would enable searching both in UI and API.

Originally opened as Primate bug - https://github.com/apache/cloudstack-primate/issues/280

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API, UI
~~~

##### CLOUDSTACK VERSION

~~~
4.14
~~~

### LINKED ISSUE #4133: CKS: Cluster remains in destroying state when non-cluster VMs are using cluster network
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
CKS
~~~

##### CLOUDSTACK VERSION

~~~
4.14.0
~~~

##### OS / ENVIRONMENT

N/A

##### SUMMARY

When additional VMs are added to the k8s cluster network, cluster deletion fails with a message, Unable to delete cluster network. k8s cluster remains in destroying state. It gets removed once non-cluster VMs are migrated from the cluster network. Instead of failing during deletion itself, service can intimate user before deletion that the network is being used by other VMs and they must be migrated before deleting.

##### STEPS TO REPRODUCE

~~~
1. Create a k8s cluster without passing an existing network.
2. Create and add a new VM to this network outside of CKS
3. Delete k8s cluster
~~~

##### EXPECTED RESULTS

~~~
Service should throw an error before deleting k8s cluster that cluster network is in use by VMs outside k8s cluster. So these VMs can be migrated.
~~~

##### ACTUAL RESULTS

~~~
Service tries to delete the k8s cluster. Node VMs are deleted. But cannot delete the network. Error is thrown at this time. Cluster shows up in destroying state until VMs are migrated from the network.
~~~

### PR DESCRIPTION
**Pull request by shwstppr**
## Description
Fixes #4133 
Fixes #4056

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@shwstppr is this ready for review/testing?

**Comment by shwstppr** [comment]
@rhtyd will test and update. Tests failed. I've to check the reason. And maybe refactor tests alongwith this change to make them more reliable

**Comment by rhtyd** [comment]
@shwstppr can you club your cks PRs, and at least change base branch to 4.14?

**Comment by shwstppr** [comment]
Moved #4116

**Pull request closed without merging**
