### PR TITLE
Enable Flake8 rule W391

### PR DESCRIPTION
**Pull request by jbampton**
Best practice is to have one blank line at the end of Python files.

Remove unneeded blank lines from the end of files

### Description

This PR standardizes the Python code.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [X] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [X] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
CLGTM and job one in travis succeeds. this should be the only test we need is it @jbampton ?

**Comment by jbampton** [comment]
Hey @DaanHoogland seems Flake8 is being run by the Super-Linter and that check passed.

Can you please show me where Travis runs flake8 ?

**Review by DaanHoogland — APPROVED** [review]

**Review by JoaoJandre — APPROVED** [review]
CLGTM

**Review by GutoVeronezi — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Pull request merged**
