### PR TITLE
Trillian testrun on PR-1692 fwd-merged on 4.9 branch

### PR DESCRIPTION
**Pull request by rhtyd**
@blueorangutan package
The aim of the PR is to see how marvin tests perform on 4.9 branch with recent list of fixes from PR #1692 
/cc @jburwell

### CODE REVIEW

**Comment by rhtyd** [comment]
Rebased against 4.9 branch, re-kicking packaging and tests.
@blueorangutan package

**Comment by rhtyd** [comment]
Kicked 4 trillian test envs with xenserver65, kvm centos7, vmware 5.5 and 6.0. We'll see some results in next 6-8 hours.

**Comment by rhtyd** [comment]
Similar to #1703 the test `test_oobm_zchange_password` failed due to env related config where oobm sync interval was set to 1 second. I've increased the timeout to 5s, and added some code to cleanup old alerts (the failure was around alert count, while the core test itself passed). The failure as seen above can be ignored, as manually ran test succeeded along with the test that ran in the Travis job.

Tests out-of-band management ownership expiry across multi-mgmt server ... === TestName: test_oobm_multiple_mgmt_server_ownership | Status : SUCCESS ===
ok
Tests out-of-band management change password feature ... === TestName: test_oobm_zchange_password | Status : SUCCESS ===
ok

Ran 16 tests in 206.122s

OK

**Comment by jburwell** [comment]
@karuturi @swill @wido @NuxRo @nvazquez we believe this PR is ready to merge.  However, we need to cross check the test results.  Would one (or more of you) be able to test this PR in order to move it forward?

**Comment by rhtyd** [comment]
@karuturi can you help run BVT tests on this PR?

**Comment by nvazquez** [comment]
@jburwell @rhtyd we're running tests with @serg38 and we got some errors, but we notice that `failed_plus_exceptions` and `runinfo` files are empty after tests finish. When we run individual tests this doesn't happen. It would be helpful for us to have those files so we can fix some things in our config and re-run tests. Did you have the same issue before?

We are running tests using this command:
```
nosetests --with-marvin --marvin-config=setup/dev/advanced.cfg -vv -s -a tags=advanced,required_hardware=true --hypervisor=vmware test/integration/smoke/*.py
```

**Comment by rhtyd** [comment]
@nvazquez thanks for the update, yes it's known issue that when running tests all at once it might cause issues. If you have a look at our Travis runner, we're running each test one at a time:
https://github.com/apache/cloudstack/blob/master/tools/travis/script.sh#L43

Trillian runs them one at a time as well, you may take some hints from Trillian's smoketest runner:
https://github.com/shapeblue/Trillian/blob/master/Ansible/roles/marvin/templates/smoketests.sh.j2#L70

**Comment by nvazquez** [comment]
Thanks! I'll post results when we can fix issues

**Comment by jburwell** [comment]
@nvazquez @serg38 thank you for your help verifying the is PR.

**Comment by serg38** [comment]
The same results as 1692.  Overall much better state. We have still failure in execution of the following tests:
test_privategw_acl
test_routers_network_ops
test_vpc_redundant
test_vpc_router_nics

All of the failure seem to be either environmental or due to incorrect ACL order .
Also out-of-band management test give a lot of exceptions but this is as expected.

We had to make one change that I propose to include. In test_service_offereing.py line 389 switch from

range=20 to range=40 . In our tests variation in available RAM in CentOs was larger than 20 Mb so test_service_offereing fails.

Let's merge this !!!

Successful tests. RHEL 6 management server, advanced networking, Vmware 5.5/6 hypervisors
```
test DeployVM in anti-affinity groups for project ... === TestName: test_DeployVmAntiAffinityGroup_in_project | Status : SUCCESS ===
test DeployVM in anti-affinity groups ... === TestName: test_DeployVmAntiAffinityGroup | Status : SUCCESS ===
Test Deploy Virtual Machine from ISO ... === TestName: test_deploy_vm_from_iso | Status : SUCCESS ===
Test deploy virtual machine with root resize ... === TestName: test_00_deploy_vm_root_resize | Status : SUCCESS ===
Test proper failure to deploy virtual machine with rootdisksize of 0 ... === TestName: test_01_deploy_vm_root_resize | Status : SUCCESS ===
Test proper failure to deploy virtual machine with rootdisksize less than template size ... === TestName: test_02_deploy_vm_root_resize | Status : SUCCESS ===
Test to deploy vm with a first fit offering ... === TestName: test_deployvm_firstfit | Status : SUCCESS ===
Test deploy VMs using user concentrated planner ... === TestName: test_deployvm_userconcentrated | Status : SUCCESS ===
Test deploy VMs using user dispersion planner ... === TestName: test_deployvm_userdispersing | Status : SUCCESS ===
Test userdata as GET, size > 2k ... === TestName: test_deployvm_userdata | Status : SUCCESS ===
Test userdata as POST, size > 2k ... === TestName: test_deployvm_userdata_post | Status : SUCCESS ===
Test to create disk offering ... === TestName: test_01_create_disk_offering | Status : SUCCESS ===
Test to create  a sparse type disk offering ... === TestName: test_02_create_sparse_type_disk_offering | Status : SUCCESS ===
Test to create  a sparse type disk offering ... === TestName: test_04_create_fat_type_disk_offering | Status : SUCCESS ===
Test to update existing disk offering ... === TestName: test_02_edit_disk_offering | Status : SUCCESS ===
Test to delete disk offering ... === TestName: test_03_delete_disk_offering | Status : SUCCESS ===
test update configuration setting at zone level scope ... === TestName: test_UpdateConfigParamWithScope | Status : SUCCESS ===
Test guest vlan range dedication ... === TestName: test_dedicateGuestVlanRange | Status : SUCCESS ===
Test create, assign, remove of an Internal LB with roundrobin http traffic to 3 vm's in a Single VPC ... === TestName: test_01_internallb_roundrobin_1VPC_3VM_HTTP_port80 | Status : SUCCESS ===
Test create, assign, remove of an Internal LB with roundrobin http traffic to 3 vm's in a Redundant VPC ... === TestName: test_02_internallb_roundrobin_1RVPC_3VM_HTTP_port80 | Status : SUCCESS ===
Test to verify access to loadbalancer haproxy admin stats page ... === TestName: test_03_vpc_internallb_haproxy_stats_on_all_interfaces | Status : SUCCESS ===
Test to verify access to loadbalancer haproxy admin stats page ... === TestName: test_04_rvpc_internallb_haproxy_stats_on_all_interfaces | Status : SUCCESS ===
Test create public & private ISO ... === TestName: test_01_create_iso | Status : SUCCESS ===
Test Edit ISO ... === TestName: test_02_edit_iso | Status : SUCCESS ===
Test delete ISO ... === TestName: test_03_delete_iso | Status : SUCCESS ===
Test for extract ISO ... === TestName: test_04_extract_Iso | Status : SUCCESS ===
Update & Test for ISO permissions ... === TestName: test_05_iso_permissions | Status : SUCCESS ===
Test delete ISO ... === TestName: test_07_list_default_iso | Status : SUCCESS ===
Test listing Volumes using 'ids' parameter ... === TestName: test_01_list_volumes | Status : SUCCESS ===
Test listing Templates using 'ids' parameter ... === TestName: test_02_list_templates | Status : SUCCESS ===
Test listing Snapshots using 'ids' parameter ... === TestName: test_03_list_snapshots | Status : SUCCESS ===
Test to create Load balancing rule with source NAT ... === TestName: test_01_create_lb_rule_src_nat | Status : SUCCESS ===
Test to create Load balancing rule with non source NAT ... === TestName: test_02_create_lb_rule_non_nat | Status : SUCCESS ===
Test for assign & removing load balancing rule ... === TestName: test_assign_and_removal_lb | Status : SUCCESS ===
Tests that SAML users are not allowed CloudStack local log in ... === TestName: login_test_saml_user | Status : SUCCESS ===
test_nic_secondaryip_add_remove (integration.smoke.test_multipleips_per_nic.TestDeployVM) ... === TestName: test_nic_secondaryip_add_remove | Status : SUCCESS ===
Test network ACL lists and items in VPC ... === TestName: test_network_acl | Status : SUCCESS ===
Test for delete account ... === TestName: test_delete_account | Status : SUCCESS ===
Test for port forwarding on source NAT ... === TestName: test_01_port_fwd_on_src_nat | Status : SUCCESS ===
Test for port forwarding on non source NAT ... === TestName: test_02_port_fwd_on_non_src_nat | Status : SUCCESS ===
Test for Associate/Disassociate public IP address for admin account ... === TestName: test_public_ip_admin_account | Status : SUCCESS ===
Test for Associate/Disassociate public IP address for user account ... === TestName: test_public_ip_user_account | Status : SUCCESS ===
Test for reboot router ... === TestName: test_reboot_router | Status : SUCCESS ===
Test for release public IP address ... === TestName: test_releaseIP | Status : SUCCESS ===
Test for Router rules for network rules on acquired public IP ... === TestName: test_network_rules_acquired_public_ip_1_static_nat_rule | Status : SUCCESS ===
Test for Router rules for network rules on acquired public IP ... === TestName: test_network_rules_acquired_public_ip_2_nat_rule | Status : SUCCESS ===
Test for Router rules for network rules on acquired public IP ... === TestName: test_network_rules_acquired_public_ip_3_Load_Balancer_Rule | Status : SUCCESS ===
Test to change service offering for instances with vm snapshots ... === TestName: test_04_change_service_offering_for_vm_with_snapshots | Status : SUCCESS ===
Test to add and update added nic to a virtual machine ... === TestName: test_01_nic | Status : SUCCESS ===
Test to update a physical network and extend its vlan ... === TestName: test_extendPhysicalNetworkVlan | Status : SUCCESS ===
test update configuration setting at storage scope ... === TestName: test_UpdateStorageOverProvisioningFactor | Status : SUCCESS ===
Check the password file in the Router VM ... === TestName: test_isolate_network_password_server | Status : SUCCESS ===
Test to acquire a provisioned public ip range ... === TestName: test_createPortablePublicIPAcquire | Status : SUCCESS ===
Test to create a portable public ip range ... === TestName: test_createPortablePublicIPRange | Status : SUCCESS ===
Test primary storage pools - XEN, KVM, VMWare. Not Supported for hyperv ... === TestName: test_01_primary_storage_nfs | Status : SUCCESS ===
test_01_vpc_privategw_acl (integration.smoke.test_privategw_acl.TestPrivateGwACL) ... === TestName: test_01_vpc_privategw_acl | Status : SUCCESS ===
Test public IP range dedication ... === TestName: test_dedicatePublicIpRange | Status : SUCCESS ===
test_create_pvlan_network (integration.smoke.test_pvlan.TestPVLAN) ... === TestName: test_create_pvlan_network | Status : SUCCESS ===
Test for create region ... === TestName: test_createRegion | Status : SUCCESS ===
Test reset virtual machine on reboot ... === TestName: test_01_reset_vm_on_reboot | Status : SUCCESS ===
Test volume detail ... === TestName: test_01_updatevolumedetail | Status : SUCCESS ===
Check that the /etc/dhcphosts.txt doesn't contain duplicate IPs ... === TestName: test_router_dhcphosts | Status : SUCCESS ===
Checks that non-guest network IPs cannot access VR DNS ... === TestName: test_router_dns_externalipquery | Status : SUCCESS ===
Checks that guest VM can query VR DNS ... === TestName: test_router_dns_guestipquery | Status : SUCCESS ===
Test iptables default INPUT/FORWARD policy on RouterVM ... === TestName: test_02_routervm_iptables_policies | Status : SUCCESS ===
Test iptables default INPUT/FORWARD policies on VPC router ... === TestName: test_01_single_VPC_iptables_policies | Status : SUCCESS ===
Test redundant router internals ... === TestName: test_01_isolate_network_FW_PF_default_routes_egress_true | Status : SUCCESS ===
Test redundant router internals ... === TestName: test_01_RVR_Network_FW_PF_SSH_default_routes_egress_true | Status : SUCCESS ===
Test router internal basic zone ... === TestName: test_01_router_internal_basic | Status : SUCCESS ===
Test router internal advanced zone ... === TestName: test_02_router_internal_adv | Status : SUCCESS ===
Test restart network ... === TestName: test_03_restart_network_cleanup | Status : SUCCESS ===
Test restart network without cleanup ... === TestName: test_04_restart_network_wo_cleanup | Status : SUCCESS ===
Test router basic setup ... === TestName: test_05_router_basic | Status : SUCCESS ===
Test router advanced setup ... === TestName: test_06_router_advanced | Status : SUCCESS ===
Test stop router ... === TestName: test_07_stop_router | Status : SUCCESS ===
Test start router ... === TestName: test_08_start_router | Status : SUCCESS ===
Test reboot router ... === TestName: test_09_reboot_router | Status : SUCCESS ===
Test system VM start ... === TestName: test_01_sys_vm_start | Status : SUCCESS ===
Test system templates are ready ... === TestName: test_02_sys_template_ready | Status : SUCCESS ===
Test to create service offering ... === TestName: test_01_create_service_offering | Status : SUCCESS ===
Test to update existing service offering ... === TestName: test_02_edit_service_offering | Status : SUCCESS ===
Test to delete service offering ... === TestName: test_03_delete_service_offering | Status : SUCCESS ===
Test to change service to a small capacity ... === TestName: test_04_change_offering_small | Status : SUCCESS ===
Test to create service offering ... === TestName: test_01_create_service_offering | Status : SUCCESS ===
Test to update existing service offering ... === TestName: test_02_edit_service_offering | Status : SUCCESS ===
Test to delete service offering ... === TestName: test_03_delete_service_offering | Status : SUCCESS ===
Test to change service to a small capacity ... === TestName: test_04_change_offering_small | Status : SUCCESS ===
Test Snapshot Root Disk ... === TestName: test_01_snapshot_root_disk | Status : SUCCESS ===
Test List secondary storage VMs ... === TestName: test_01_list_sec_storage_vm | Status : SUCCESS ===
Test List console proxy VMs ... === TestName: test_02_list_cpvm_vm | Status : SUCCESS ===
Test SSVM Internals ... === TestName: test_03_ssvm_internals | Status : SUCCESS ===
Test CPVM Internals ... === TestName: test_04_cpvm_internals | Status : SUCCESS ===
Test stop SSVM ... === TestName: test_05_stop_ssvm | Status : SUCCESS ===
Test stop CPVM ... === TestName: test_06_stop_cpvm | Status : SUCCESS ===
Test reboot SSVM ... === TestName: test_07_reboot_ssvm | Status : SUCCESS ===
Test reboot CPVM ... === TestName: test_08_reboot_cpvm | Status : SUCCESS ===
Test destroy SSVM ... === TestName: test_09_destroy_ssvm | Status : SUCCESS ===
Test destroy CPVM ... === TestName: test_10_destroy_cpvm | Status : SUCCESS ===
Tests allowed APIs for common account types ... === TestName: test_static_role_account_acls | Status : SUCCESS ===
Test create public & private template ... === TestName: test_01_create_template | Status : SUCCESS ===
Test when createTemplate is used to create templates having the same name all of them get ... === TestName: test_CreateTemplateWithDuplicateName | Status : SUCCESS ===
Test Edit template ... === TestName: test_02_edit_template | Status : SUCCESS ===
Test delete template ... === TestName: test_03_delete_template | Status : SUCCESS ===
Test for extract template ... === TestName: test_04_extract_template | Status : SUCCESS ===
Update & Test for template permissions ... === TestName: test_05_template_permissions | Status : SUCCESS ===
Test only public templates are visible to normal user ... === TestName: test_07_list_public_templates | Status : SUCCESS ===
Test System templates are not visible to normal user ... === TestName: test_08_list_system_templates | Status : SUCCESS ===
Test advanced zone virtual router ... === TestName: test_advZoneVirtualRouter | Status : SUCCESS ===
Test Deploy Virtual Machine ... === TestName: test_deploy_vm | Status : SUCCESS ===
Test Multiple Deploy Virtual Machine ... === TestName: test_deploy_vm_multiple | Status : SUCCESS ===
Test Stop Virtual Machine ... === TestName: test_01_stop_vm | Status : SUCCESS ===
Test Start Virtual Machine ... === TestName: test_02_start_vm | Status : SUCCESS ===
Test Reboot Virtual Machine ... === TestName: test_03_reboot_vm | Status : SUCCESS ===
Test destroy Virtual Machine ... === TestName: test_06_destroy_vm | Status : SUCCESS ===
Test recover Virtual Machine ... === TestName: test_07_restore_vm | Status : SUCCESS ===
Test migrate VM ... === TestName: test_08_migrate_vm | Status : SUCCESS ===
Test destroy(expunge) Virtual Machine ... === TestName: test_09_expunge_vm | Status : SUCCESS ===
Test for attach and detach ISO to virtual machine ... === TestName: test_10_attachAndDetach_iso | Status : SUCCESS ===
@Desc: Test that Volume snapshot for root volume is not allowed ... === TestName: test_01_test_vm_volume_snapshot | Status : SUCCESS ===
Test to create VM snapshots ... === TestName: test_01_create_vm_snapshots | Status : SUCCESS ===
Test to revert VM snapshots ... === TestName: test_02_revert_vm_snapshots | Status : SUCCESS ===
Test to delete vm snapshots ... === TestName: test_03_delete_vm_snapshots | Status : SUCCESS ===
Test Volume creation for all Disk Offerings (incl. custom) ... === TestName: test_01_create_volume | Status : SUCCESS ===
Attach a created Volume to a Running VM ... === TestName: test_02_attach_volume | Status : SUCCESS ===
Download a Volume attached to a VM ... === TestName: test_03_download_attached_volume | Status : SUCCESS ===
Delete a Volume attached to a VM ... === TestName: test_04_delete_attached_volume | Status : SUCCESS ===
Detach a Volume attached to a VM ... === TestName: test_05_detach_volume | Status : SUCCESS ===
Download a Volume unattached to an VM ... === TestName: test_06_download_detached_volume | Status : SUCCESS ===
Delete a Volume unattached to an VM ... === TestName: test_09_delete_detached_volume | Status : SUCCESS ===
Create a redundant VPC with two networks with two VMs in each network and check default routes ... === TestName: test_02_redundant_VPC_default_routes | Status : SUCCESS ===
Create a redundant VPC with two networks with two VMs in each network ... === TestName: test_03_create_redundant_VPC_1tier_2VMs_2IPs_2PF_ACL_reboot_routers | Status : SUCCESS ===
Create a VPC with two networks with one VM in each network and test default routes ... === TestName: test_02_VPC_default_routes | Status : SUCCESS ===
Test Site 2 Site VPN Across redundant VPCs ... === TestName: test_01_redundant_vpc_site2site_vpn | Status : SUCCESS ===
Test Remote Access VPN in VPC ... === TestName: test_01_vpc_remote_access_vpn | Status : SUCCESS ===
Test Site 2 Site VPN Across VPCs ... === TestName: test_01_vpc_site2site_vpn | Status : SUCCESS ===
```

Failed tests
```
test_02_vpc_privategw_static_routes (integration.smoke.test_privategw_acl.TestPrivateGwACL) ... === TestName: test_02_vpc_privategw_static_routes | Status : FAILED ===
test_03_vpc_privategw_restart_vpc_cleanup (integration.smoke.test_privategw_acl.TestPrivateGwACL) ... === TestName: test_03_vpc_privategw_restart_vpc_cleanup | Status : FAILED ===
test_04_rvpc_privategw_static_routes (integration.smoke.test_privategw_acl.TestPrivateGwACL) ... === TestName: test_04_rvpc_privategw_static_routes | Status : FAILED ===
Test redundant router internals ... === TestName: test_02_isolate_network_FW_PF_default_routes_egress_false | Status : FAILED ===
Create a redundant VPC with two networks with two VMs in each network ... === TestName: test_01_create_redundant_VPC_2tiers_4VMs_4IPs_4PF_ACL | Status : FAILED ===
Create a VPC with two networks with one VM in each network and test nics after destroy ... === TestName: test_01_VPC_nics_after_destroy | Status : FAILED ===
```
Exceptions:
```
Tests out-of-band management background powerstate sync ... === TestName: test_oobm_background_powerstate_sync | Status : EXCEPTION ===
Tests out-of-band management configuration with valid data ... === TestName: test_oobm_configure_default_driver | Status : EXCEPTION ===
Tests out-of-band management configuration with invalid driver ... === TestName: test_oobm_configure_invalid_driver | Status : EXCEPTION ===
Tests out-of-band management host disable feature with ... === TestName: test_oobm_disable_feature_invalid | Status : EXCEPTION ===
Tests out-of-band management host disable feature with ... === TestName: test_oobm_disable_feature_valid | Status : EXCEPTION ===
Tests out-of-band management host enable feature with ... === TestName: test_oobm_enable_feature_invalid | Status : EXCEPTION ===
Tests out-of-band management host enable feature with ... === TestName: test_oobm_enable_feature_valid | Status : EXCEPTION ===
Tests out-of-band management enable/disable feature at cluster ... === TestName: test_oobm_enabledisable_across_clusterzones | Status : EXCEPTION ===
Tests out-of-band management issue power cycle action ... === TestName: test_oobm_issue_power_cycle | Status : EXCEPTION ===
Tests out-of-band management issue power off action ... === TestName: test_oobm_issue_power_off | Status : EXCEPTION ===
Tests out-of-band management issue power on action ... === TestName: test_oobm_issue_power_on | Status : EXCEPTION ===
Tests out-of-band management issue power reset action ... === TestName: test_oobm_issue_power_reset | Status : EXCEPTION ===
Tests out-of-band management issue power soft action ... === TestName: test_oobm_issue_power_soft | Status : EXCEPTION ===
Tests out-of-band management issue power action ... === TestName: test_oobm_issue_power_status | Status : EXCEPTION ===
Tests out-of-band management ownership expiry across multi-mgmt server ... === TestName: test_oobm_multiple_mgmt_server_ownership | Status : EXCEPTION ===
Tests out-of-band management change password feature ... === TestName: test_oobm_zchange_password 
```

**Comment by rhtyd** [comment]
Thanks all for your review, tests. Fwd merge did not automatically close this PR, so closing this manually.

**Pull request closed without merging**
