### PR TITLE
tools/docker: Upgrade to ubuntu 20.04 , MySQL 8 and python3

### LINKED ISSUE #4891: Issue while running the simulator docker image
##### ISSUE TYPE

 * Other

##### COMPONENT NAME

~~~
Docker image - simulator
~~~

##### CLOUDSTACK VERSION

~~~
Master branch
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

After cloning the repo, building the docker image from scratch and running it, the UI doesn't show up and throws the following error:
"You're in developer mode, please build and run UI using npm." 

##### STEPS TO REPRODUCE

~~~
cd tools/docker 
docker build -f Dockerfile -t cloudstack/simulator ../..
docker run --name simulator -p 8080:8080 -d cloudstack/simulator
docker exec -ti simulator python \
/root/tools/marvin/marvin/deployDataCenter.py -i /root/setup/dev/basic.cfg
~~~

##### EXPECTED RESULTS

~~~
Cloudstack UI
~~~

##### ACTUAL RESULTS

~~~
On the web browser:

"You're in developer mode, please build and run UI using npm." 
~~~

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR upgrades cloudstack simulator to Ubuntu 20.04, MySQL 8 and python3, launches cloudstack UI at port 5050.

README.md is updated accordingly.

fixes #4891

How to test it
```
cd tools/docker 
docker build -f Dockerfile -t cloudstack/simulator ../..
docker run --name simulator -p 8080:5050 -d cloudstack/simulator
docker exec -it simulator python /root/tools/marvin/marvin/deployDataCenter.py -i /root/setup/dev/advanced.cfg

# Open your browser at http://localhost:8080/
```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
Didn't test it manually, I think we can merge if Wei can confirm how/if he has tested this.

**Review by Pearl1594 — APPROVED** [review]
Tested it locally - works fine - http://localhost:8080  opens the onboarding UI page (haven't setup the zone)
image

**Comment by rhtyd** [comment]
cc As Wei advised @tampler maybe try these changes (git cherry-pick) in your private branch and see if it fixes your issue.

**Comment by synergiator** [comment]
as of today, I was able to build and run a container with the 4.17 and logon to UI. Would be great to see fresh images on Docker Hub!

**Comment by synergiator** [comment]
build from tag 4.16.1 advanced configuration does not work
```
docker exec -it simulator python /root/tools/marvin/marvin/deployDataCenter.py -i /root/setup/dev/advanced.cfg
=== TestClient Creation Failed===

``

**Comment by weizhouapache** [comment]
@synergiator 
I will check it

**Comment by weizhouapache** [comment]
@synergiator 
I have built a docker image from cloudstack 4.16.1.0 and uploaded to my owner docker hub:
https://hub.docker.com/repository/docker/ustcweizhou/cloudstack-simulator

it works well in my testing
```
root@689d4fe9dabc:~# python /root/tools/marvin/marvin/deployDataCenter.py -i /root/setup/dev/advanced.cfg

==== Log Folder Path: /tmp/MarvinLogs/DeployDataCenter__May_17_2022_11_49_11_KB6AX4 All logs will be available here ====

==== Deploy DC Started ====

=== Data Center Settings are dumped to /tmp/MarvinLogs/DeployDataCenter__May_17_2022_11_49_11_KB6AX4/dc_entries.obj===

====Deploy DC Successful=====
root@689d4fe9dabc:~# 
```

Please notice you should create the zone only when management server is running.

**Comment by synergiator** [comment]
thanks @weizhouapache - it works indeed with 4.16.1.0, obviously I did not verified final server start logs. Now it's time for the Docker Hub release :-)

**Pull request merged**
