### PR TITLE
Tungsten integration

### PR DESCRIPTION
**Pull request by davidjumani**
### Description

Continuation of https://github.com/apache/cloudstack/pull/4205

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan test

**Comment by davidjumani** [comment]
@blueorangutan test matrix

**Comment by davidjumani** [comment]
@blueorangutan test matrix

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@davidjumani new conflicts

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
the definition of insanity , ...
@blueorangutan test

**Comment by kiwiflyer** [comment]
Here's the TF API JAR forked repo - https://github.com/kiwiflyer/tf-java-api/
JAR is here -  https://github.com/kiwiflyer/tf-java-api/blob/master/target/juniper-tungsten-api-2.0.jar

I took the work that Huy and Radu completed, reforked the original TF repo with the original license (APL2) and applied the patches.

Original Repo is reference in plugins/network-elements/tungsten/pom.xml- 

    <repositories>
        <repository>
            <id>juniper-tungsten-api</id>
            <url>https://github.com/radu-todirica/tungsten-api/raw/master</url>
        </repository>
    </repositories>

**Comment by rohityadavcloud** [comment]
@kiwiflyer could you help publish the jar to the general public maven repo, or if you plan to use Github explore and publish the jar as (a) Github mvn pkg (see https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry) or (b) create a tag so CloudStack refers to a specific tag and not the main branch.

**Comment by kiwiflyer** [comment]
> @kiwiflyer could you help publish the jar to the general public maven repo, or if you plan to use Github explore and publish the jar as (a) Github mvn pkg (see https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry) or (b) create a tag so CloudStack refers to a specific tag and not the main branch.
> 
> For reference, we've some mvn jar published here - https://github.com/orgs/apache/packages?repo_name=cloudstack (that's outdated though).

@rohityadavcloud I've created a tag. Let me know if this works - https://github.com/kiwiflyer/tf-java-api/releases/tag/v.1.0.0

**Comment by rohityadavcloud** [comment]
@davidjumani @DaanHoogland could we use the tag to get the jar dependency in the mvn pom.xml instead of referring to the repo link to main branch?

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by davidjumani** [comment]
@blueorangutan package

**Review by NuxRo — APPROVED** [review]
LGTM, in its default state (off) Tungsten does not seem to break anything, tested in regular Advanced zones as well as Advanced + Security Groups.

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
This PR is a followup of several older ones, it has had a lot of reviews and has been finally implemented as aan experimental feature. It has been manually tested. I deem this safe and desireable, so merging.

**Review by DaanHoogland — APPROVED** [review]

**Comment by anhtt96VN** [comment]
@huyle-uni Hi anh huyle em là Tuấn Anh kỹ sư IT Việt Nam, em cũng rất quan tâm về Tungsten nhưng còn nhiều thắc mắc không biết em có thể liện hệ với anh để xin chia sẻ về Tungsten từ anh được không ạ?

**Pull request merged**
