### PR TITLE
Description field option is needed for networking NAT, ACL and Security Group rules.

### PR DESCRIPTION
**Pull request by raiciks**
## Description
Hello!
Many of our customers asking for description field option in networking NAT, ACL rules. Some of our customers have huge list of rules, and they need strictly to know who create a rule, for what service rule is created and so on. This option is required not only for system administrators, but it is requested by security managers and GDPR. This issue is affected by: Guest Networks, VPC networks - ACL list of rules and Security Groups. I prepared screen shots where this option is necessary.  

## Types of changes
- [ ] New feature (non-breaking change which adds functionality)

## Screenshots (if appropriate):
I prepared screen shots where this option is necessary.  
guest_networks

### CODE REVIEW

**Comment by rafaelweingartner** [comment]
Something like this https://github.com/apache/cloudstack/pull/2475?

**Comment by raiciks** [comment]
Yes! But this feature we need in Guest Networks, ACL and Security Groups.

**Comment by rafaelweingartner** [comment]
I guess they all use the same ACL endpoint. Therefore, it is a matter of extending the Javascript that is used by these functions.

**Comment by rafaelweingartner** [comment]
I will close this one in favor of #3131

**Pull request closed without merging**
