### PR TITLE
CLOUDSTACK-9014 Rename xapi plugins for s3 and swift to make them work after renaming the calls

### PR DESCRIPTION
**Pull request by remibergsma**
Make renaming introduced in a8212d9ef458dd7ac64b021e6fa33fcf64b3cce0 work for S3 and Swift xapi plugins.

This PR is to address comments in PR #970

### CODE REVIEW

**Comment by xenserverarmy** [comment]
@remibergsma How did the tests work out?

**Comment by remibergsma** [comment]
@xenserverarmy Sure, it works. It's very easy, the files end up in `/etc/xapi.d/plugins`. Are you able to verify yourself?

**Comment by remibergsma** [comment]
@DaanHoogland @wilderrodrigues You can do this to test this PR:

```
./kvm_local_deploy.py -r xenserver65
/data/shared/helper_scripts/cloudstack/check-pr.sh -m /data/shared/marvin/mct-zone1-xen1.cfg -p 982
```

Once the deploy is done:

``
ssh xen1
ls -la /etc/xapi.d/plugins/ | grep xenserver
``

Before this PR, the result was:
```
-rwxr-xr-x 1 root root 12714 Oct 29 20:20 s3xen
-rwxr-xr-x 1 root root  3241 Oct 29 20:19 swiftxen
```

Now it is:

```
-rwxr-xr-x 1 root root 12714 Oct 29 20:20 s3xenserver
-rwxr-xr-x 1 root root  3241 Oct 29 20:19 swiftxenserver
```

Can you also verify this please?

**Comment by wilderrodrigues** [comment]
@remibergsma ... Will start testing now!

Cheers,
Wilder

**Comment by wilderrodrigues** [comment]
Just tested it! LGTM :+1: 

```
[root@xen1 ~]# ls -la /etc/xapi.d/plugins/ | grep xenserver 
-rwxr-xr-x 1 root root 12714 Oct 30 07:52 s3xenserver
-rwxr-xr-x 1 root root  3241 Oct 30 07:52 swiftxenserver
[root@xen1 ~]# uname -a
Linux xen1 3.10.0+2 #1 SMP Tue Dec 9 12:45:36 EST 2014 x86_64 x86_64 x86_64 GNU/Linux
[root@xen1 ~]# 
```

I will also run some basic tests to make sure all is fine!

Cheers,
Wilder

**Comment by karuturi** [comment]
manually tested by upgrading an existing xenserver setup and force reconnecting the host

Before
```
[root@rjn-xen65-host plugins]# ls -la /etc/xapi.d/plugins/ | grep xen
-rwxr-xr-x 1 root root 12708 Sep 29 10:44 s3xen
-rwxr-xr-x 1 root root  3235 Sep 29 10:44 swiftxen
```

After
```
[root@rjn-xen65-host plugins]# ls -la /etc/xapi.d/plugins/ | grep xen
-rwxr-xr-x 1 root root 12708 Sep 29 10:44 s3xen
-rwxr-xr-x 1 root root 12714 Oct 30 10:42 s3xenserver
-rwxr-xr-x 1 root root  3235 Sep 29 10:44 swiftxen
-rwxr-xr-x 1 root root  3241 Oct 30 10:42 swiftxenserver
```

I am guessing having the both the scripts after upgrade wont be an issue. I didnt see any issues after the change(manually tested launch new vm etc.) 
:+1:

**Comment by remibergsma** [comment]
@karuturi Added Jira issue CLOUDSTACK-9014

**Pull request merged**
