### PR TITLE
[Vmware] Fix bad ovf null error when registering template

### PR DESCRIPTION
**Pull request by nvazquez**
## Description
Fix error on template registration:

image

Caused by:

````
2019-07-23 12:23:09,674 DEBUG [c.c.a.t.Request] (AgentManager-Handler-6:null) (logid:) Seq 4-4903012619322916910: Processing:  { Ans: , MgmtId: 32987630602057, via: 4, Ver: v1, Flags: 10, [{"com.cloud.agent.api.storage.DownloadAnswer":{"jobId":"ef37e03c-ef79-42da-9a34-47d3f41ba88b","downloadPct":100,"errorString":"Failed post download script: com.cloud.exception.InternalErrorException: OVA package has bad ovf file null","downloadStatus":"DOWNLOAD_ERROR","downloadPath":"/mnt/SecStorage/a9751ac5-94ed-35c4-bff1-42f61b3c8b18/template/tmpl/2/202/dnld5595547545501326400tmp_","installPath":"template/tmpl/2/202/95d1f7c7-d6b6-3387-bdc6-9c8ab170e702.ova","templateSize":0,"templatePhySicalSize":0,"checkSum":"5cc9bedfb202cd88f4b9abed33f38f0d","result":true,"details":"Failed post download script: com.cloud.exception.InternalErrorException: OVA package has bad ovf file null","wait":0}}] }
2019-07-23 12:23:09,684 WARN  [c.c.a.AlertManagerImpl] (RemoteHostEndPoint-1:ctx-546dd73b) (logid:4644378a) AlertType:: 28 | dataCenterId:: 1 | podId:: null | clusterId:: null | message:: Failed to register template: b6c595de-2ebe-4b0c-bcab-bd6f5a887af9 with error: Failed post download script: com.cloud.exception.InternalErrorException: OVA package has bad ovf file null
2019-07-23 12:23:09,687 ERROR [o.a.c.s.i.BaseImageStoreDriverImpl] (RemoteHostEndPoint-1:ctx-546dd73b) (logid:4644378a) Failed to register template: b6c595de-2ebe-4b0c-bcab-bd6f5a887af9 with error: Failed post download script: com.cloud.exception.InternalErrorException: OVA package has bad ovf file null
````

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)

## How Has This Been Tested?
Register template from URL

### CODE REVIEW

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test matrix

**Comment by anuragaw** [comment]
Description could use some more details perhaps @nvazquez . What was the root cause of the error for instance.

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-65u2

**Comment by rhtyd** [comment]
@anuragaw I think it could be null if the ova has multiple disks where at least one of them is an ISO or additional data disk without an explicitly stated controller.

**Comment by rhtyd** [comment]
Just checked, the multi-disk case may not be tested by the trillian env. The KVM tests LGTM and Travis as well. I'll merge this PR now.

**Pull request merged**
