### PR TITLE
test: reduce PowerMock usage for code coverage

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

JaCoCo used for code coverage calculation in the project doesn't support PowerMockito classes. This PR attemps to reduce usage of PowerMockito.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by weizhouapache — COMMENTED** [review]
code lgtm

**Comment by DaanHoogland** [comment]
@shwstppr , is this ongoing work or do you want to merge and add similar PRs later?

**Comment by shwstppr** [comment]
@DaanHoogland ongoing work

**Comment by weizhouapache** [comment]
great, there are some improvements in the codecov report.
go ahead @shwstppr 
:+1:

**Comment by shwstppr** [comment]
@weizhouapache @DaanHoogland I'm marking this ready for review.
I'll open new PR(s) as and when I make changes to the new test files.

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by weizhouapache — APPROVED** [review]

**Pull request merged**
