### PR TITLE
Tungsten: fix functional issues

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes the issues we encounter in testing
- Unable to add bridge vhost0 port vnet1: Operation not supported, as kvm agent cannot read DB
- VM nic is created as a tap device in advanced zone with security groups on KVM

The following issues are not fixed
- only 1 physical network is supported if isolated method is TF
- Host must have an assigned ip address on public interface. (Not a bug maybe)
- ports are not removed fro Tungsten when (FAILED) system vms are destroyed

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [x] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
This is not necessarily an issue, but just an observation. Any list tungsten API returns the zone ID (long) and not the zone UUID
@DaanHoogland @weizhouapache Do you think this needs to be updated or can be left as is ?

**Comment by DaanHoogland** [comment]
> This is not necessarily an issue, but just an observation. Any list tungsten API returns the zone ID (long) and not the zone UUID @DaanHoogland @weizhouapache Do you think this needs to be updated or can be left as is ?

@davidjumani , I think we can address this in 4.18.1, IDs can be used in the API but it is not very neat/polished.

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

> This is not necessarily an issue, but just an observation. Any list tungsten API returns the zone ID (long) and not the zone UUID @DaanHoogland @weizhouapache Do you think this needs to be updated or can be left as is ?

@davidjumani , did you create a separate issue for this?

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Comment by weizhouapache** [comment]
@blueorangutan test ubuntu22 kvm-ubuntu22

**Comment by DaanHoogland** [comment]
@weizhouapache what is the purpose of the empty shell scripts?

**Comment by weizhouapache** [comment]
> @weizhouapache what is the purpose of the empty shell scripts?

@DaanHoogland 
it changed the mode of files from rw to rwx
Not required actually as the file will be changed to be executable during packaging.
just keep consistent with other scripts which are executable.

**Review by DaanHoogland — APPROVED** [review]
CLGTM

**Review by rohityadavcloud — APPROVED** [review]
Didn’t test it but on a high level changes LGTM

**Comment by DaanHoogland** [comment]
This has been tested by several people in a lab environment; merging

**Pull request merged**
