### PR TITLE
kvm: use ACPI and signal based reboot on KVM

### PR DESCRIPTION
**Pull request by rhtyd**
This replace the legacy stop/start logic with libvirt's native reboot
operation that will use ACPI and signal based rebooting of VM on KVM
hosts.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@rhtyd 
is acpi is turned off inside vm, will it work ?

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/high_availability_add-on_reference/s1-acpi-CA#s2-bios-setting-CA

**Comment by wido** [comment]
I'm ok with this.

Any modern distro has ACPI enabled and should respond to it. Nowadays it's usually systemd handling this but in older versions it's acpid.

**Comment by mlsorensen** [comment]
If ACPI is off in the guest, that would apparently fail for any hypervisor that is using ACPI triggers to reboot.  I haven't checked myself but I've been told that the Xen and VMware use ACPI triggers for the reboot API as well, and I think it would be expected behavior. 

If it becomes an issue for KVM users who are accustomed to the current behavior, perhaps there can be a 'forced' option like stopVirtualMachine has, and that can be a shortcut to a full stop and start, so the various plugin workflows are properly called.

**Comment by weizhouapache** [comment]
> If ACPI is off in the guest, that would apparently fail for any hypervisor that is using ACPI triggers to reboot. I haven't checked myself but I've been told that the Xen and VMware use ACPI triggers for the reboot API as well, and I think it would be expected behavior.
> 
> If it becomes an issue for KVM users who are accustomed to the current behavior, perhaps there can be a 'forced' option like stopVirtualMachine has, and that can be a shortcut to a full stop and start, so the various plugin workflows are properly called.

@rhtyd  it would be nice to have 'forced' option as @mlsorensen said.

**Comment by rhtyd** [comment]
That sounds sensible, thanks @mlsorensen @weizhouapache I'll update the logic to perform ACPI reboot (default), and if a forced API arg is provided do a stop + start (at the orchestration level, not in hypervisor plugin).

**Comment by DaanHoogland** [comment]
code here looks good, are you still implementing the stop / start in this PR @rhtyd , or is that somewhere else?

**Comment by sureshanaparti** [comment]
> code here looks good, are you still implementing the stop / start in this PR @rhtyd , or is that somewhere else?

@DaanHoogland @rhtyd Addressed the suggested changes on the PR: https://github.com/apache/cloudstack/pull/4681 , which provides the forced reboot option (to stop and start VM), along with ACPI reboot for KVM VM.

**Comment by rhtyd** [comment]
Closing this old PR, in favour of the new

**Pull request closed without merging**
