### PR TITLE
linstor: disconnect-disk also search for resource name in Linstor

### PR DESCRIPTION
**Pull request by rp-**
### Description

disconnectPhysicalDisk(String, KVMStoragePool) seems to calls the plugin with the resource name instead of the device path, so we also have to search for resource names, while cleaning up.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### How Has This Been Tested?

6 Node CloudStack cluster, non hyperconverged.

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@rp- , isn't this obfuscating a bug where the path should have been stored instead of the name?

**Comment by rp-** [comment]
> @rp- , isn't this obfuscating a bug where the path should have been stored instead of the name?

Good point, but I store the disk uuid as path and reference for Linstor and it only gets translated to the real device path in the `getPhysicalDisk()` and `createPhysicalDisk()` calls in the adaptor.

So yes, the name volumePath might be misleading here, because in Linstor case it is actually part of the resource name.

**Review by sureshanaparti — APPROVED** [review]
CLGTM

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Pull request merged**
