### PR TITLE
VPC VR: fix Conflicting device id on private gw nic when restart vpc with cleanup

### PR DESCRIPTION
**Pull request by ustcweizhou**
### Description

Some issues with vpc vr have been fixed in #4484
This PR fixes the last two issues we found in our testing.

We run the the integration tests in test/integration/component/test_multiple_subnets*.py many times (>20) , all are SUCCESSFUL.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [x] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by rhtyd** [comment]
@weizhouapache is this critical fix wrt 4.15 or can we do in the next release? cc @DaanHoogland @PaulAngus 
@blueorangutan package

**Comment by weizhouapache** [comment]
> @weizhouapache is this critical fix wrt 4.15 or can we do in the next release? cc @DaanHoogland @PaulAngus
> @blueorangutan package

@rhtyd it is better to merge it into 4.15.0.0

**Comment by rhtyd** [comment]
@weizhouapache okay I've bumped to critical but let's also hear from @PaulAngus and @DaanHoogland 
@blueorangutan test

**Review by DaanHoogland — APPROVED** [review]
seems like a proper refactor though I'd liked to have seen the code taken out in a separate method. The component tests are fixed as well, let's have these run.

**Comment by DaanHoogland** [comment]
@blueorangutan test centos7 kvm-centos7 keepEnv

**Comment by DaanHoogland** [comment]
@rhtyd @PaulAngus I would put this in and merge forward. testing in an independent env (not @weizhouapache's) advised

**Comment by weizhouapache** [comment]
> @rhtyd @PaulAngus I would put this in and merge forward. testing in an independent env (not @weizhouapache's) advised

@DaanHoogland this pr does not have any change with iptables rules in VRs.
if all integration tests pass, it should be good.

**Comment by DaanHoogland** [comment]
i ran the test_multiple_subnets_in_isolated_network.py component tests and they passed. I just wanted to conform to the external test party rule for merging , @weizhouapache ; good to go as far as i am concerned.

**Review by rhtyd — APPROVED** [review]

**Pull request merged**
