### PR TITLE
use `Files.createTempDirectory()` instead of `new File()`

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR addresses a static analysis concern with temp file creation. It is not a security issue but an improvement nonetheless.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### How Has This Been Tested?

unit test added

### CODE REVIEW

**Review by oscerd — APPROVED** [review]
LGTM. Thanks.

**Review by rohityadavcloud — APPROVED** [review]
LGTM - need smoketests (I havent' tested it)

**Comment by rohityadavcloud** [comment]
@DaanHoogland should this be targeted to 4.18 branch as well?

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by harikrishna-patnala — APPROVED** [review]
code LGTM

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by rohityadavcloud — APPROVED** [review]
LGTM - thanks Daan for changing base to 4.18

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Pull request merged**
