### PR TITLE
Remove 'todb' in favor of 'encodeURIComponent'.

### PR DESCRIPTION
**Pull request by rafaelweingartner**
## Description

While executing the find/replace, I found some blocks of duplicated code. Therefore, I extracted the duplicated part to an utils file, and then removed the duplicated blocks.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [X] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?
Locally

## Checklist:

- [X] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
Testing
- [ ] I have added tests to cover my changes.
- [X] All relevant new and existing integration tests have passed.
- [ ] A full integration testsuite with all test that can run on my environment has passed.

@blueorangutan package

### CODE REVIEW

**Comment by DaanHoogland** [comment]
Why remove todb for the longer encodeURIComponent, when the first is only a wrapper for the latter?

**Comment by rafaelweingartner** [comment]
Good question.  Why not use directly a function that everybody knows (everybody that works with javascript)? 

When I first encountered it, I spent some time trying to find its documentation in the Javascript specs. Just then, I discovered that it was a wrapper created in CloudStack's javascript. This wrapper does not help us with anything. Moreover, it was not used consistently in the code base. There are quite a lot of places using the 'encodeURIComponent'.

If we want to write less, we should first stop copying and pasting code ;)

**Comment by DaanHoogland** [comment]
right, but having a wrapper around an external piece of code is always good. Per our older discussions; let's reduce the surface layer of 3rd party software to ours.

**Comment by DaanHoogland** [comment]
btw: look good in general it is just that I would have opted for giving a better name to todb and use the wrapper

**Comment by rafaelweingartner** [comment]
The method `encodeURIComponent` is not a third party library. It is a native function in Javascript.

**Comment by DaanHoogland** [comment]
ah, in that case I stand corrected, @rafaelweingartner. once again looks good

**Pull request merged**
