### PR TITLE
Fix Bug that prevents adding multiple public IP ranges on the same subnet

### PR DESCRIPTION
**Pull request by kioie**
## Description

Referencing this issue: https://github.com/apache/cloudstack/issues/3114
Edited the code to check for an ipOverlap in the IP ranges and not subnet overlap.

Signed-off-by: @kioie <kioieddy@google.com>

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

**STEPS TO TEST**

`create vlaniprange zoneId="06e5e428-1170-4ab3-bfc3-c018660bdca1" vlan=untagged gateway=192.168.2.1 netmask=255.255.255.0 startip=192.168.2.2 endip=192.168.2.200 forsystemvms=false forVirtualNetwork=true`

`create vlaniprange zoneId="06e5e428-1170-4ab3-bfc3-c018660bdca1" vlan=untagged gateway=192.168.2.1 netmask=255.255.255.0 startip=192.168.2.201 endip=192.168.2.220 forsystemvms=false forVirtualNetwork=true`

**EXPECTED RESULTS**
`2nd range added without issue`

**ACTUAL RESULTS**
`2nd range added without issue`

### CODE REVIEW

**Comment by dhlaluku** [comment]
@kioie may you please resolve the merge conflicts

**Comment by dhlaluku** [comment]
@blueorangutan package

**Comment by dhlaluku** [comment]
@blueorangutan test

**Comment by shwstppr** [comment]
@kioie If you are still working on this, please resolve conflicts

**Comment by kioie** [comment]
Issue seems to be corrected on #3430

**Pull request closed without merging**
