### PR TITLE
kvm: fix exception in volume stats after storage migration

### PR DESCRIPTION
**Pull request by ustcweizhou**
## Description

on kvm, the 'path' of volume is the file name on primary storage. we should use 'path' instead of 'uuid' in volume statistics.

Fixes: #3878 
## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

1. storage migration
2. volume statistics every 10 minutes (default)

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Packaging overlap failure, rekicking
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by andrijapanicsb** [comment]
LGTM 

haven't tested. @weizhouapache if you tested, I'm fine with it - thx for the fix.

**Comment by weizhouapache** [comment]
@DaanHoogland @andrijapanicsb @rhtyd 

I have tested with qcow2 on NFS. Did not test local storage and Ceph RBD.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@skattoju3 can you review this?
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Pull request merged**
