### PR TITLE
Add extra checks for test_vm_schedule to avoid intermittent failures

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR adds additional checks in test_vm_schedule to avoid intermittent failures

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [] Minor
- [x] Trivial

### CODE REVIEW

**Comment by vishesh92** [comment]
@blueorangutan package

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Review by rohityadavcloud — APPROVED** [review]
Didn't test it but LGTM

**Review by DaanHoogland — APPROVED** [review]

**Comment by DaanHoogland** [comment]
this should avoid some of the intermitted failures, at least.

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan test

**Review by shwstppr — APPROVED** [review]

**Pull request merged**
