### PR TITLE
CLOUDSTACK-10012: Load SQL schema scripts from JAR

### PR DESCRIPTION
**Pull request by marcaurele**
Load the SQL schema files from the fatjar directly to simply file path discovery.

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@marcaurele it might be an issue as cloudstack-setup-databases reads from that folder, and also it will become an issue to verify the changes in various older upgrade paths. Let me review and get back to you on this next week.

**Comment by marcaurele** [comment]
From our experience on this change that is running in production for us, we can deploy a new SQL schema/lab with the usual mvn developer script, as well as upgrading the DB on schema changes. If a customization is needed, we should invert the way the upgrades are executed and do a package scan on classes rather than declaring them "statically" in `DatabaseUpgradeChecker`. It should help anyone to extend an upgrade class to add extra changes. The upgrade classes should declare themselves the version from which they should be run, and the DB version after the upgrade. With the help of a Comparable, we could sort them in the correct order, and even skip over unneeded ones if a class declares a bigger upgrade path.

**Comment by rhtyd** [comment]
Thanks @marcaurele there are several conflicts and large changes, I'll work with you on this after the original fat-jar PR is tested and merged.

**Comment by rhtyd** [comment]
@marcaurele with the fatjar PR merged, please rebase and switch the base branch of this PR to `master`. Let's get this reviewed, tested and merged as next step. Thanks.

**Comment by marcaurele** [comment]
@rhtyd rebase done + target branch changed

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@marcaurele this will require two additional changes:
- Fix `cloud(stack)-setup-databases` script to use com.cloud.upgrade.DatabaseUpgradeChecker and remove assumptions that a setup folder will be available to read/run the sql scripts from. We'll need to do this while making sure cloudstack-setup-databases is backward compatible.
- Fix various packaging scripts to not copy/bundle `setup` as a separate directory

**Comment by marcaurele** [comment]
@rhtyd  `cloud-setup-databases` is good to go as it is since I left the SQL files in `setup/db` directory to create the schema. Only the migration files are moved into the JAR. I found one trace of this sub directory in the centos packaging and remove the lines.

**Comment by marcaurele** [comment]
@rhtyd all checks are green, can you have a look or push further testing on this branch.

**Comment by rhtyd** [comment]
Thanks @marcaurele - I'm wondering if it's still a good idea to keep the subdirectory with initial seed schema files while having the upgrade paths shaded/included in jar? I'll kick some tests.
@blueorangutan package

**Comment by rhtyd** [comment]
@marcaurele can you fix the conflicts? I'll help run tests then.

**Comment by marcaurele** [comment]
@rhtyd rebase done

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Pull request merged**
