### PR TITLE
server: fix vm migration failed if iso is attached

### PR DESCRIPTION
**Pull request by ustcweizhou**
## Description

If vm has attached ISO, the migration fails with error message "org.libvirt.LibvirtException: Cannot access storage file /mnt/b33e5a1d-e4ea-3465-b6ac-c98dc8ff8af0/207-2-cc5fd717-2d57-3bb3-bcf6-2c930268db6c.iso"

This issue happens after #2983 is merged.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

create vm
register ISO
attach ISO to vm
migrate vm

all work fine.

### CODE REVIEW

**Comment by ustcweizhou** [comment]
@nvazquez could you please review/test it ?

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
Hi @ustcweizhou, I've also provided a fix within this PR: #3828, specifically this commit: https://github.com/apache/cloudstack/pull/3828/commits/2102864e8a57ae39a71d4839928923e43554bdff

prepareIso will select the ISO from primary or secondary storage depending if the template is direct download or not

**Comment by weizhouapache** [comment]
> Hi @ustcweizhou, I've also provided a fix within this PR: #3828, specifically this commit: [2102864](https://github.com/apache/cloudstack/commit/2102864e8a57ae39a71d4839928923e43554bdff)
> 
> prepareIso() will select the ISO from primary or secondary storage depending if the template is direct download or not

@nvazquez it looks better. can you create a separated pull request for it ? we need to fix the issue asap.

**Comment by nvazquez** [comment]
Sure @ustcweizhou please see #3935

**Comment by rhtyd** [comment]
@ustcweizhou @nvazquez can you advice which one of the PRs to keep, this or Nicolas's #3935 ?

**Comment by weizhouapache** [comment]
@rhtyd @nvazquez I will close this PR ,and test #3935

**Pull request closed without merging**
