### PR TITLE
server: find suitable disk offering for volume upload

### LINKED ISSUE #5696: Uploaded volumes use the first custom disk offering
In a multi-zone setup where the zones are configured to use different storage types (shared vs local) the uploaded volume will not have assigned the first Custom disk offering available without considering zone.

Even if the zones in the setup use the same kind of storage only the disk offerings available for the selected zone in the upload form should be considered.

In my case my first zone is using local storage and if I want to upload a volume in the second zone which uses Shared storage I must first change the disk offering to the shared storage one otherwise I get an error that the zone does not support local storage (because I don't have any local storage pools configured).

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #5696

- Find suitable custom disk offering for volume upload based on the zone.
- In UI, added diskoffering option in Upload volume from local.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):
Screenshot from 2022-01-28 13-47-08

### How Has This Been Tested?

- Deployed an env with 2 zones
- _Tested volume upload local/url without passing diskoffering_ 
- Deleted default custom disk offering, created two separate custom disk offerings for the two zones and then:

1. Tested local/url volume upload to both zones, one by one without passing offering
2. Tested local/url  volume upload to both zones, one by one while passing offering
3. Tested local/url  volume upload to first zone while passing offering offering from second zone

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
code looks good so far, @shwstppr How far is this from done?

**Comment by shwstppr** [comment]
@DaanHoogland I was not able to test a multi-zone setup yet. Also, I was not sure if it will correct to use a different custom offering as default other than one with unique_name=Cloud.com-Custom. So would like other's opinion.

**Comment by DaanHoogland** [comment]
The offering name should not matter.
I would like to see the user have the opportunity to choose an offering and maybe even create one during the upload process. For now this seems a bit out of scope. Just something to think about.

Let me know when this is ready for review.

**Comment by shwstppr** [comment]
> The offering name should not matter. I would like to see the user have the opportunity to choose an offering and maybe even create one during the upload process. For now this seems a bit out of scope. Just something to think about.
> 
> Let me know when this is ready for review.

@DaanHoogland uploadVolume API does have a param to specify diskoffering. Creating a new offering during volume upload itself in the UI won't make a lot of sense as disk offering creation by default is not allowed to default User role.
Sorry forgot to ping you after marking the PR ready for review but I guess you already noticed.

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
tested LGTM

**Comment by DaanHoogland** [comment]
@shwstppr I have considered only upload from local in my testing but @sureshanaparti pointed me to the upload from url dialog. I think we'll need to look at this as well. It displays a complete set of offerings while it should probably automatically select a constom offering for the current zone as well.

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
code looks good
test performed:
- in a dual zone env;
- delete the default custom offering
- create custom offerings per zone
- upload a data disk from local and url to both zones
- check if the correct offerings are chosen
all results good.

**Comment by sureshanaparti** [comment]
@blueorangutan package help

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
@shwstppr Upload volume from URL lists disk offerings with name, whereas Upload volume from Local lists disk offerings with display name, please make them consistent. and When selecting other zone's disk offering in Upload volume from URL, it is not throwing access permission error (which it shown earlier).

**Comment by shwstppr** [comment]
@sureshanaparti 

Made UI change for your first issue
Not able reproduce second issue. Error shown when offering from a different zone is selected while upload from URL,

Screenshot from 2022-02-01 17-41-42

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@sureshanaparti @DaanHoogland I've refactored code changes to use `checkAccess` so a valid offering can be found using both zone and owner's domain.

@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
> @sureshanaparti
> 
> Made UI change for your first issue ~Not able reproduce second issue. Error shown when offering from a different zone is selected while upload from URL,~
> 
> Reverted access check

Verified the UI changes, looks good.

**Comment by sureshanaparti** [comment]
Tested upload from local and url with user and admin accounts with latest changes. Also, verified the access restriction on other zone's disk offering while uploading volume from url. LGTM.

**Review by sureshanaparti — APPROVED** [review]

**Pull request merged**
