### PR TITLE
ui: recommend adv zone to new users and show basic zone as bottom option

### PR DESCRIPTION
**Pull request by rhtyd**
This shows the adv zone option in the create zone wizard before the basic
zone option and recommends it for new users. This is because adv zone
can offer more flexible and network topology options including what
basic zone offers in form of shared network (with/without security
groups).

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan ui

**Comment by weizhouapache** [comment]
@rhtyd can we set 'Advanced' as default ?

**Comment by rhtyd** [comment]
Yes, I couldn't figure out how to do that; @utchoang @Pearl1594 @davidjumani any pointers?

**Comment by rhtyd** [comment]
@blueorangutan ui

**Comment by davidjumani** [comment]
@blueorangutan ui

**Comment by rhtyd** [comment]
@blueorangutan ui

**Comment by rhtyd** [comment]
Seems to be working now with Adv zone option preselected as default, pl review and test @davidjumani @utchoang @weizhouapache ;
Screenshot from 2021-09-22 14-44-59

**Review by davidjumani — APPROVED** [review]

**Review by shwstppr — APPROVED** [review]
LGTM. Tested QA server

**Pull request merged**
