### PR TITLE
SQL: Remove snapshot references if primary storage pool has been removed

### LINKED ISSUE #7093: Record still left in snapshot_store_ref after primary storage has been removed causing 530 when listSanpshots is called
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME
Storage

##### CLOUDSTACK VERSION
4.17.2 (maybe before as well)

##### OS / ENVIRONMENT
VMware 6.7.3

##### SUMMARY
When a primary storage is deleted, the corresponding record in the snapshot_store_ref table is not deleted
Noted specifically in VMware

##### STEPS TO REPRODUCE

- Take ROOT volume snapshot(This primary storage is Storage1.)
- Migrate ROOT volume to other storage(as Storage2) with the API - migrateVirtualMachine -
- Confirm the snapshot has two entries in cloud.snapshot_store_ref - one for primary and one for image.
- Then remove Storage1.
- Confirm that two entries remain in cloud.snapshot_store_ref.
- Do a listSnapshots API call against the snapshot and observe Error:(HTTP 530, error code 9999) - Due to an NPE in the DB record refering to the deleted storage pool

##### EXPECTED RESULTS

The record in the table pointing to the now deleted primary storage is still present

##### ACTUAL RESULTS

The DB record is deleted

Similar to https://github.com/apache/cloudstack/issues/3264

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #7093 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@weizhouapache is this an upgrade only action? It seems by the description, it should be done in a clean-up task that runs regularly.

**Review by DaanHoogland — APPROVED** [review]

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by vladimirpetrov — APPROVED** [review]
LGTM based on manual testing, reproduced on 4.15.2, upgraded to 4.17.2, then to this PR and the problem disappeared. Tested with VMWare 6.7u3.

**Pull request merged**
