### PR TITLE
CLOUDSTACK-8838: Allow ensX enoX enpX enxX format for nics in CentOS 7

### PR DESCRIPTION
**Pull request by giraffeforestg**

### CODE REVIEW

**Comment by remibergsma** [comment]
@giraffeforestg Thanks for picking this up! Will test it tomorrow.

FYI: You can always make changes after the PR is opened. If you'd want to change something now, you'd push a new commit to `giraffeforestg:CLOUDSTACK-8838`. You can also alter an existing commit, or overwrite it using `-f` when pushing. In other words, whatever you do to your branch `giraffeforestg:CLOUDSTACK-8838` that this PR is linked to, will end up here. 
Don't get me wrong, opening a new PR is just fine too ;-)

**Comment by wido** [comment]
Looking at the if-statement I give it a LGTM

**Comment by rafaelweingartner** [comment]
Why don’t you extract the content of line 1164 (the condition) to a method, this way it is possible to create a test case and enables some java doc. Moreover, the code becomes easier to read.

**Comment by bhaisaab** [comment]
LGTM, given the if conditions

**Comment by DaanHoogland** [comment]
I agree with @rafaelweingartner that this can have (and deserves) a unit test maybe it can even be generalized to dynamically find nic prefixes or at least have a list of them ourside the condition. It will make the code clearer and thus better maintainable

**Pull request merged**
