### PR TITLE
added favicon

### PR DESCRIPTION
**Pull request by K0zka**
Signed-off-by: Laszlo Hornyak <laszlo.hornyak@gmail.com>

### CODE REVIEW

**Comment by bhaisaab** [comment]
Nice idea, @K0zka  but I don't see any file called cloud.ico in the repo?

**Comment by K0zka** [comment]
Hi @bhaisaab ,

It is in the same commit. This is what it looks like.
icon

Here you can see an image of how it looks like in the browser:
https://issues.apache.org/jira/secure/attachment/12729991/hint-1.png

**Comment by bhaisaab** [comment]
LGTM, though using this icon: 
apache_cloudstack

**Comment by K0zka** [comment]
I was affraid that the monkey will not look good in 16x16, but it works :+1:  Thank you @bhaisaab !

**Comment by bhaisaab** [comment]
screen shot 2015-05-04 at 2 55 09 pm
this is what it looks like on my chrome; can we resize it or do anything else?

**Comment by K0zka** [comment]
I only looked at it in firefox, it was OK. If you have an IE, could you make a screenshot? Just curious...

**Pull request closed without merging**
