### PR TITLE
engine-schema: make adding/dropping indexes idempotent

### LINKED ISSUE #9170: Make schema migrations are idempotent
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
Schema migrations

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### SUMMARY

Ensure that migrations are idempotent. Sometimes, there are some schema changes which are already applied in the database. This causes issues during upgrade. Especially if someone is maintaining a private fork.

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #9170

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by rohityadavcloud — APPROVED** [review]

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@b;lueorangutan test

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@shwstppr 
There are some simulator CI errors

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test alma9 kvm-alma9

**Review by DaanHoogland — APPROVED** [review]

**Review by vishesh92 — APPROVED** [review]
clgtm

**Pull request merged**
