### PR TITLE
travis: run junit tests only in one job

### PR DESCRIPTION
**Pull request by karuturi**
added DONOTRUNUNITTESTS variable for each of the jobs. The value is
false only in the first job

### CODE REVIEW

**Comment by karuturi** [comment]
@abhinandanprateek 

job 1: timedout. since its running unittests, should we decrease the tests there? may be run only unit tests
job 9: timedout
job 10: there are some skipped and failed test cases

**Comment by karuturi** [comment]
job 1: timed out in the deploy datacenter phase. debugging
job10: timed out. removed one more test file

**Comment by karuturi** [comment]
There are two unittests failing with the below error
```java
Running org.apache.cloudstack.storage.resource.NfsSecondaryStorageResourceTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.078 sec <<< FAILURE! - in org.apache.cloudstack.storage.resource.NfsSecondaryStorageResourceTest
testMount(org.apache.cloudstack.storage.resource.NfsSecondaryStorageResourceTest)  Time elapsed: 0.07 sec  <<< ERROR!
javax.naming.ConfigurationException: Unable to find agent.properties.
	at org.apache.cloudstack.storage.resource.NfsSecondaryStorageResourceTest.loadProperties(NfsSecondaryStorageResourceTest.java:95)
	at org.apache.cloudstack.storage.resource.NfsSecondaryStorageResourceTest.setUp(NfsSecondaryStorageResourceTest.java:55)
Running org.apache.cloudstack.storage.resource.LocalNfsSecondaryStorageResourceTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 sec <<< FAILURE! - in org.apache.cloudstack.storage.resource.LocalNfsSecondaryStorageResourceTest
testExecuteRequest(org.apache.cloudstack.storage.resource.LocalNfsSecondaryStorageResourceTest)  Time elapsed: 0.001 sec  <<< ERROR!
javax.naming.ConfigurationException: Unable to find agent.properties.
	at org.apache.cloudstack.storage.resource.LocalNfsSecondaryStorageResourceTest.loadProperties(LocalNfsSecondaryStorageResourceTest.java:129)
	at org.apache.cloudstack.storage.resource.LocalNfsSecondaryStorageResourceTest.setUp(LocalNfsSecondaryStorageResourceTest.java:68)
Results :
Tests in error: 
  LocalNfsSecondaryStorageResourceTest.setUp:68->loadProperties:129 Configuration
  NfsSecondaryStorageResourceTest.setUp:55->loadProperties:95 Configuration Unab...
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0
```

**Comment by karuturi** [comment]
these tests are explicitly disabled in the pom.xml using skipTests=true
refactored a but and not using skipTests now.

**Comment by bhaisaab** [comment]
LGTM, @abhinandanprateek - do you want to review and merge this one?

**Comment by karuturi** [comment]
@bhaisaab Thanks for the review. please dont merge this yet. Travis is still failing and would like to fix it. It would be good to have abhi's opinion..

**Pull request closed without merging**
