### PR TITLE
[4.5] vmware: improve support for disk controllers

### PR DESCRIPTION
**Pull request by bhaisaab**
- Improve disk chain usage while attaching, migrating disks
- Gets root disk controller based diskDeviceBusName from volume's chain info
- Enforce a boot order based on the disk information CloudStack has

### CODE REVIEW

**Comment by bhaisaab** [comment]
VM tests performed manually on 4.5+patch:

1. Started Windows 2012 Template on the newly patched 4.5.2
Windows 2012 Root drive was set too IDE (0:1)
Data Drive SCSI (0:0)
Default controller global setting = osdefault
2. Started a Windows 2012 VM from ISO on newly patched 4.5.2
Window 2012 Root drive SCSI (0:1)
Data drive SCSI (0:0)
Default controller global setting = osdefault 

Based on above we can merge on 4.5

**Comment by cristofolini** [comment]
@bhaisaab Did you get to see the output of the jenkins build? Was it just another false positive? I don't see anything in the code that could cause it to fail...

But, if I may make a small suggestion, I'd ask you to extract the contents from that if statement beginning at line 1799 to its own method, just to help out with readability, as the sheer amount of conditionals involved in the original method can make it a bit overwhelming to read. :)

**Comment by bhaisaab** [comment]
@cristofolini I think you're right, both Travis and Jenkins are having inconsistent builds. While I could refactor the method in its own method, I don't see if it could be reused elsewhere. I'll try to fix the PR soon. Thanks.

**Comment by bvbharatk** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 112
 Hypervisor xenserver
 NetworkType Advanced
 Passed=105
 Failed=13
 Skipped=4

**The follwing tests have known issues**
test_vpc_remote_access_vpn
test_vpc_site2site_vpn
test_01_test_vm_volume_snapshot
test_02_vpc_privategw_static_routes
test_03_rvpc_privategw_static_routes
test_04_change_offering_small
ContextSuite context=TestNiciraContoller>:setup
test_01_primary_storage_iscsi
test02_internallb_haproxy_stats_on_all_interfaces
test_01_internallb_roundrobin_1VPC_3VM_HTTP_port80
ContextSuite context=TestDeployVM>:setup
test_04_extract_template
test_04_extract_Iso
test_07_list_default_iso


_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/yj3wnzbceo9uef2/AAB6u-Iap-xztdm6jHX9SjPja?dl=0


**Failed tests:**
* integration.smoke.test_guest_vlan_range.TestDedicateGuestVlanRange

 * test_dedicateGuestVlanRange Failing since 3 runs


**Skipped tests:**
test_vm_nic_adapter_vmxnet3
test_deploy_vgpu_enabled_vm
test_06_copy_template
test_06_copy_iso

**Passed test suits:**
integration.smoke.test_deploy_vm_with_userdata.TestDeployVmWithUserData
integration.smoke.test_affinity_groups_projects.TestDeployVmWithAffinityGroup
integration.smoke.test_portable_publicip.TestPortablePublicIPAcquire
integration.smoke.test_over_provisioning.TestUpdateOverProvision
integration.smoke.test_global_settings.TestUpdateConfigWithScope
integration.smoke.test_scale_vm.TestScaleVm
integration.smoke.test_service_offerings.TestCreateServiceOffering
integration.smoke.test_loadbalance.TestLoadBalance
integration.smoke.test_routers.TestRouterServices
integration.smoke.test_reset_vm_on_reboot.TestResetVmOnReboot
integration.smoke.test_snapshots.TestSnapshotRootDisk
integration.smoke.test_deploy_vms_with_varied_deploymentplanners.TestDeployVmWithVariedPlanners
integration.smoke.test_network.TestDeleteAccount
integration.smoke.test_non_contigiousvlan.TestUpdatePhysicalNetwork
integration.smoke.test_deploy_vm_iso.TestDeployVMFromISO
integration.smoke.test_public_ip_range.TestDedicatePublicIPRange
integration.smoke.test_multipleips_per_nic.TestDeployVM
integration.smoke.test_regions.TestRegions
integration.smoke.test_affinity_groups.TestDeployVmWithAffinityGroup
integration.smoke.test_network_acl.TestNetworkACL
integration.smoke.test_pvlan.TestPVLAN
integration.smoke.test_volumes.TestCreateVolume
integration.smoke.test_ssvm.TestSSVMs
integration.smoke.test_nic.TestNic
integration.smoke.test_deploy_vm_root_resize.TestDeployVM
integration.smoke.test_resource_detail.TestResourceDetail
integration.smoke.test_secondary_storage.TestSecStorageServices
integration.smoke.test_vm_life_cycle.TestDeployVM
integration.smoke.test_disk_offerings.TestCreateDiskOffering

**Comment by rafaelweingartner** [comment]
@bhaisaab, @swill, 
Was this PR merge or closed?!?
I noticed a merge to the code base, but this PR did not have the 2LGTMs that it would need to be merged. Additionally, it seems that it was a direct commit; I was not able to find the commit “23e1fcdaa0e39298e249c9046f31a3d0f0504ef0” into 4.5 branch.

If it was “merged”, should not it be forwarded to 4.6, 4.7, 4.8 and master? Giving that it was “merged” to 4.5. Unless there is another PR that introduces the same changes into those other branches.

**Comment by bhaisaab** [comment]
@rafaelweingartner more of a guidelines, this was never voted on and this does not apply for 4.5; there is an outstanding PR for recent branches

**Comment by rafaelweingartner** [comment]
Do you mean that the need for 2LGTMs was voted after this PR was open? It seems that it was a direct commit. Why did you not use the merge tool? 

Is it just a guideline? I have seen much less complicated PRs being reverted because they did not have those 2LGTMS. 

Could you refer the outstanding PR here too, for tracking purpose?

**Comment by bhaisaab** [comment]
@rafaelweingartner mea culpa, I used the older git pr tool and pushed it. AFAIK our current process and details of reviewing, testing and merging PRs is not voted on, it's more of a guideline. For 4.5 and older branches, they are so old that most contributors won't invest time on them. As a 4.5 maintainer, I try to backport/cherry-pick patches (for example, you can follow last 4-5 commits on 4.5).

The outstanding PR for 4.7+ i.e. newer branches is referenced above in this PR as well -- https://github.com/apache/cloudstack/issues/1365

**Comment by rafaelweingartner** [comment]
Ok, thanks @bhaisaab

**Pull request closed without merging**
