### PR TITLE
ui: allow copying password from notification

### LINKED ISSUE #7960: Provide a copy option from the UI to copy the password of a vm
ISSUE TYPE

    Improvement request

COMPONENT NAME

Component: UI

CLOUDSTACK VERSION

Cloudstack 4.18

SUMMARY

Provide a copy option from the UI to copy the password of a vm 

Steps to reproduce the issue

1. Register a password-enabled template 

2. Deploy a vm 

Password field

Currently, Cloudstack Ui supports copy options on many fields in the ui  (like instance uuid, template uuid)

copy id

It will be useful to the end-user to copy the password of a vm

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #7960 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

Screenshot from 2023-09-20 17-25-58

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@blueorangutan ui

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by kiranchavala** [comment]
@blueorangutan package

**Review by rohityadavcloud — APPROVED** [review]

**Review by kiranchavala — COMMENTED** [review]
@shwstppr the copy password is only working vm's password is reset.

It's not working when the password enabled vm is deployed for the first time

Screenshot 2023-09-26 at 5 54 23 PM

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by shwstppr** [comment]
@kiranchavala you may try now,
Screenshot from 2023-09-28 17-36-58

**Review by kiranchavala — APPROVED** [review]
LGTM, it's working for both new vm deploy and  for reset vm password

Screenshot 2023-09-28 at 5 48 22 PM



Screenshot 2023-09-28 at 5 50 54 PM

**Pull request merged**
