### PR TITLE
Update en.json

### PR DESCRIPTION
**Pull request by alexandremattioli**
### Description

This PR rephrases some confusing messages in the UI

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### How Has This Been Tested?

N/A

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@blueorangutan ui

**Review by DaanHoogland — APPROVED** [review]

**Review by stephankruggg — APPROVED** [review]

**Review by GaOrtiga — APPROVED** [review]

**Comment by nvazquez** [comment]
@alexandremattioli I notice there is also #6884, should we close one of them and keep only one with all the changes? cc @DaanHoogland

**Comment by alexandremattioli** [comment]
@nvazquez I think this one has all the changes so far. Should I keep it draft until it's all done?

**Comment by DaanHoogland** [comment]
@blueorangutan ui

**Comment by DaanHoogland** [comment]
@alexandremattioli is this ready?

**Comment by alexandremattioli** [comment]
It is @DaanHoogland

**Pull request merged**
