### PR TITLE
maven: update dependencies

### PR DESCRIPTION
**Pull request by rohityadavcloud**
This upgrades mvn dependencies for the project.

### CODE REVIEW

**Comment by rohityadavcloud** [comment]
This would require testing the SAML integration and console manually.
@blueorangutan package

**Comment by rohityadavcloud** [comment]
This would require testing the SAML integration and console manually. Limitation: can't upgrade the mysql and jetty-maven dependencies.

**Review by DaanHoogland — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
kicked too soon, need to re-package
@blueorangutan package

**Comment by rohityadavcloud** [comment]
sorry @DaanHoogland could you kill/cancel those jobs (I pushed a change for mysql dependency that requires re-packaging)

**Comment by rohityadavcloud** [comment]
nevermind 😃

**Comment by rohityadavcloud** [comment]
@blueorangutan test matrix

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Comment by rohityadavcloud** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by DaanHoogland** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Comment by rohityadavcloud** [comment]
@blueorangutan test centos7 vmware-67u3

**Review by harikrishna-patnala — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
This needs manual testing of:
- saml integration
- vm consoles

**Comment by rohityadavcloud** [comment]
Manually tested VM console with and without SSL/TLS certificate with VMware as hypervisor. Also tested SAML login against https://samltest.id (in the SP metadata I had to remove the md:Organization elements).

**Pull request merged**
