### PR TITLE
add procedures procedure

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR...

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by GutoVeronezi** [comment]
Nice work @DaanHoogland!

I believe we could do the same for the `cloud_usage` stored procedures.

**Comment by DaanHoogland** [comment]
> Nice work @DaanHoogland!
> 
> ~I believe we could do the same for the `cloud_usage` stored procedures.~
> 
> Should we separate the `cloud_usage` in different files?

I thought of that but wanted to check versions against each other. I will make that change.

A change I won't make but what we need to do in another PR is cleaning the views from the schema update files. I encoutered a couple.

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by GutoVeronezi** [comment]
> > Nice work @DaanHoogland!
> > ~I believe we could do the same for the `cloud_usage` stored procedures.~
> > Should we separate the `cloud_usage` in different files?
> 
> I thought of that but wanted to check versions against each other. I will make that change.

@DaanHoogland 
I was thinking a little bit more about this, and, except for `ADD_GUEST_OS_AND_HYPERVISOR_MAPPING`, the other procedures are valid for both `cloud` and `cloud_usage`. Perhaps we could execute the script once for each schema instead of duplicating the code. What do you think?

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by KlausDornsbach** [comment]
Hey @DaanHoogland, I created the PR #9401 to address the view cleanup that you mentioned.

**Comment by DaanHoogland** [comment]
@blueorangutan test alma9 kvm-alma9

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@GutoVeronezi i got this working and did some investigating on iterating over databases but all solutions so far seem overcomplicated. Let's revisist later, ok?

**Review by weizhouapache — APPROVED** [review]
code lgtm

just a tip for those who want to create the procedures manually
the SQLs do not work in mysql CLI as the default delimiter is ";", need to change to other value like "||"
```
DROP PROCEDURE IF EXISTS ...

DELIMITER ||

CREATE PROCEDURE ...
||

DELIMITER ;
```

**Review by rohityadavcloud — APPROVED** [review]

**Review by vladimirpetrov — APPROVED** [review]
LGTM based on manual testing, I did some upgrade and smoke testing and found no issues.

**Pull request merged**
