### PR TITLE
4.5 Branch: update pom version and add upgrade path from 4.5.0 to 4.5.1

### PR DESCRIPTION
**Pull request by bhaisaab**
- Updates pom version to 4.5.1-SNAPSHOT
- Adds upgrade path from 4.5.0 to 4.5.1

### CODE REVIEW

**Comment by bhaisaab** [comment]
Build fine with all unit tests passing, upgrade runs successfully from 4.5.0.

cc @ke4qqq @runseb @daanhoogland - would be great if you can review it

**Comment by runseb** [comment]
@bhaisaab just a thought, but from the commit messages I can't tell the critical bug fix was applied. I think you should merge. We need the pom version switch anyway. And we need to test the release on the actual source.

**Comment by bhaisaab** [comment]
@runseb the bugs were fixed on 4.5 branch so they are already in 4.5 branch. I think to create 4.5.1 RC one could simply branch off from 4.5 once these commits are merged, or do you only want to create a different branch with only the identified critical bugfixes?

These are the list of important commits IMO that went into 4.5 branch but did n't made into 4.5.0:

https://github.com/apache/cloudstack/commit/02cadc3fb3fae7f5e8c87b7fafb977fb5eeae6eb
https://github.com/apache/cloudstack/commit/f3f47f25bab8661f31e5d470995f6f24cc08310e
https://github.com/apache/cloudstack/commit/f9090eacd6432856ca7504ebdfce38d65f8d019d
https://github.com/apache/cloudstack/commit/b2b9de7fa39825e8ff111353619df4e5aece12e6
https://github.com/apache/cloudstack/commit/b879916f5c64ddbca8713852b2c0ac187e9be1ff
https://github.com/apache/cloudstack/commit/ab8f367850c7ef75e1ff851397ff7dee4b5e40ab
https://github.com/apache/cloudstack/commit/729e239a471dc9910f550e7ce0c01e29fa920381

**Comment by runseb** [comment]
On Mar 11, 2015, at 5:09 PM, Rohit Yadav <notifications@github.com> wrote:

> @runseb the bugs were fixed on 4.5 branch so they are already in 4.5 branch. I think to create 4.5.1 RC one could simply branch off from 4.5 once these commits are merged, or do you only want to create a different branch with only the identified critical bugfixes?
> 
> These are the list of important commits IMO that went into 4.5 branch but did n't made into 4.5.0:
> 

So let me show my ignorance here.

4.5.0 is a tag in the 4.5 branch ? correct ?

Commits were made on top of that to fix some issues including a critical bug fix in 4.5.0 that is forcing us to release 4.5.1 quickly.

Why don't we do a linear release on the 4.5 branch ? Why do you want to branch from 4.5 ?

In the end we vote on a git hash.

**Comment by bhaisaab** [comment]
@runseb So we've two options:

I merge this into 4.5 and then a 4.5.1 RC1 candidate is cut off 4.5 branch. On 4.5 branch there aren't many commits that have went into after 4.5.0 was cut/released.

Or,

I merge this into 4.5 and share only commits that need to be picked on top of 4.5.0 (tag). That is - I'll create a branch from the 4.5.0 tag and cherry-pick commits that need to go into the emergency 4.5.1 and use that for voting?

Which one do you prefer?

**Comment by bhaisaab** [comment]
@runseb yes, I want a linear release too; just use latest 4.5 (after we merge this).

I'm testing it now and then merging if it passes.

**Comment by bhaisaab** [comment]
Ran basic tests against KVM, they passed for merging.

**Pull request closed without merging**
