### PR TITLE
CLOUDSTACK-10294: PEP-8 fixes and enhancements to security_group.py

### PR DESCRIPTION
**Pull request by wido**
The code in security_group.py is very old.

I looked into using Libvirt network filters for this, but it's lacking functionality we require.

This is my first attempt in cleaning up this file. There is a lot more work to do.

I tested this on a local system with Basic Networking and that worked just fine in my case.

The quality of the code is still horrible though:

<pre>Your code has been rated at 3.60/10 (previous run: 3.56/10, +0.04)</pre>

A lot more work is needed, but I'm taking baby-steps so that it makes the review a bit easier and not one big bang with changes.

### CODE REVIEW

**Comment by DaanHoogland** [comment]
#BabySteps save the world LGTM

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by wido** [comment]
We can merge this one, right?

**Comment by rhtyd** [comment]
@wido let me kick a test round.
@blueorangutan test

**Comment by rhtyd** [comment]
@wido can you add a JIRA id for this?

**Comment by wido** [comment]
Done @rhtyd , updated the title with the issue: https://issues.apache.org/jira/browse/CLOUDSTACK-10294

**Pull request merged**
