### PR TITLE
Enable restart of redundant VPCs implementing Rolling Restart

### PR DESCRIPTION
**Pull request by DaanHoogland**
stolen from cosmic

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@DaanHoogland 4.11 can benefit from the change to reduce VR downtime for rVRs on upgrade, can you change base branch to 4.11?

**Comment by DaanHoogland** [comment]
can do, @rhtyd

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@borisstoyanov if this gets no more traction I will abandon and close it. No, I will not make a jira issue for the sake of an jira issue.

**Comment by rhtyd** [comment]
I'll move the changes to https://github.com/apache/cloudstack/pull/2508. Closing this.

**Pull request closed without merging**
