### PR TITLE
Fix migration path of PR #5909

### PR DESCRIPTION
**Pull request by GutoVeronezi**
### Description

PR #5909 was created before the announce of release 4.17.1.0 and the changes in the databases were addressed in the `4.17.0.0 -> 4.18.0.0` migration path. However, #5909 was merged after 4.17.1.0 releasing, with the original migration path.

This PR intends to fix the migration path of PR #5909.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by GutoVeronezi** [comment]
Thank you for the ping, @DaanHoogland.

**Review by DaanHoogland — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Review by harikrishna-patnala — APPROVED** [review]
LGTM

**Comment by rohityadavcloud** [comment]
LGTM
@blueorangutan test

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by BryanMLima — APPROVED** [review]

**Review by RodrigoDLopez — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Pull request merged**
