### PR TITLE
This is a quick fix to attempt to resolve most of the travis failures

### PR DESCRIPTION
**Pull request by rsafonseca**
Most of the failures have been due to transient network failures, that are causing dependency artifact downloads to fail
Maven does not have a way to retry this without restarting the whole build, so the mvn dependency plugin is the best bet
Unfortunately, running a dependency:resolve on the project returns yet to be compiled dependencies, and causes it to fail...
There is an option to excludeGroupIds and excludeArtifactIds in the docs for this goal, but unfortunately they don't seem to work
This drafts a dummy pom in a quick and dirty way, just to download all the deps in one go, while retrying for RETRY_COUNT times if it fails

UPDATE: this is no longer a quick fix, as it fixes several issues with travis ;)

### CODE REVIEW

**Comment by rsafonseca** [comment]
Travis failure on 2c0d07e was due to second phase not running after i moved the script to tools/travis
xerxesImpl is downloaded on that phase
Issue is already fixed is in d2faa90

**Comment by rsafonseca** [comment]
Travis is still not looking very well :( will resume soon

**Comment by rsafonseca** [comment]
7 successes in a row is looking better :)
Will do a couple more minor changes to force some more runs.. will rebase at the end when it feels like travis is running stable

**Comment by DaanHoogland** [comment]
Are you done with this @rsafonseca ? As in; should I merge?

**Comment by rsafonseca** [comment]
@DaanHoogland LGTM, altough travis has been very stable today :)
Lastest commit is also useful, since the after_failure.sh script was doing nothing at all.. this will allow some insight into failures such as these:

https://travis-ci.org/apache/cloudstack/jobs/67514846

==== Marvin Init Successful ====
=== TestName: test_01_sys_vm_start | Status : FAILED ===
=== TestName: test_02_sys_template_ready | Status : EXCEPTION ===
===final results are now copied to: /tmp//MarvinLogs/test_secondary_storage_KYYYZV===
+----------------------------+---------+
|            Test            | Result  |
+============================+=========+
| test_01_sys_vm_start       | Failure |
+----------------------------+---------+
| test_02_sys_template_ready | Success |
+----------------------------+---------+

**Comment by rsafonseca** [comment]
Perfect, last travis failure was just what i was referring to in the last comment, after_failure.sh printed full marvin logs, we can properly troubleshoot that issue now :)
Will look into that later or during the weekend if no one else beats me to it hehe :)

**Comment by rsafonseca** [comment]
It seems like this test sometimes fails because the SSVM takes a while to startup.. the test/integration/smoke/test_secondary_storage.py:159 asserts that "Starting" != "Running" and just exits there.
This needs to allow some time for the SSVM to start if state="Starting" instead of immediately throwing an AssertionError.
File hasn't been touched for over a year, so i guess this is a pretty old issue on travis, also explains why it's intermittent.

**Comment by rsafonseca** [comment]
Mentioned issue fixed in https://github.com/apache/cloudstack/pull/493/
:D

**Comment by rsafonseca** [comment]
Ever since i first saw this failure I wondered... why is this considered a success?!?

=== TestName: test_02_sys_template_ready | Status : EXCEPTION ===
+----------------------------+---------+
| test_02_sys_template_ready | Success |
+----------------------------+---------+

Fixed in the latest commit.

**Comment by rsafonseca** [comment]
It seems latest fix uncovered tests that were failing but actually reporting success!

**Comment by rsafonseca** [comment]
I'd say this now downloads around 99% of project dependencies before build starts
Mostly just maven-remote-resources-plugin stuff is still downloaded, plus very few others that somehow are not picked-up by the script runs... hopefully 99% will be enough to have travis never fail with download error/timeouts.. will launch some load on travis to see :)

**Comment by DaanHoogland** [comment]
LGTM waiting for travis to agree

**Pull request closed without merging**
