### PR TITLE
test cleanup

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR intends to make sure (in the end each of) the tests clean up their own test data.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

make inventory of your cloud.
run any of the tests.
make invetory again
check the difference (should be nul

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
ping @borisstoyanov @rhtyd @GabrielBrascher

**Comment by rhtyd** [comment]
Is this ready for merging @DaanHoogland LGTM
@blueorangutan package

**Comment by DaanHoogland** [comment]
@rhtyd yes, a lot of similar things will follow but we can merge it in parts

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@borisstoyanov @rhtyd can you approve?

**Review by rhtyd — APPROVED** [review]
LGTM based on last test run

**Comment by DaanHoogland** [comment]
ping @borisstoyanov ?

**Review by borisstoyanov — APPROVED** [review]
LGTM based on runs and code review

**Pull request merged**
