### PR TITLE
Adding support for RHEL8 binary-compatible variants

### PR DESCRIPTION
**Pull request by davidjumani**
### Description

Adds support for hopefully all RHEL binary-compatible variants

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

### Screenshots (if appropriate):

Screenshot from 2021-06-25 13-49-30

Screenshot from 2021-06-25 23-44-36

### How has this been tested ?

https://github.com/apache/cloudstack/pull/5158#issuecomment-871435409
https://github.com/apache/cloudstack/pull/5158#issuecomment-871456934

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan test

**Comment by davidjumani** [comment]
@blueorangutan help

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Comment by davidjumani** [comment]
@blueorangutan test matrix

**Comment by davidjumani** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Comment by davidjumani** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Comment by davidjumani** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Review by rhtyd — APPROVED** [review]
LGTM - needs thorough testing

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Comment by davidjumani** [comment]
@blueorangutan test alma8 kvm-alma8

**Comment by davidjumani** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Review by vladimirpetrov — APPROVED** [review]
Feature LGTM

Smoke test results (Rocky mgmt + Rocky KVM):
http://sl-jenkins-master.sofia.shapeblue.com:8080/job/Reference_Trillian/1529/

Smoke tests completed. 87 look OK, 2 have error(s)
Only failed tests results shown below:

Test | Result | Time (s) | Test File

test_03_ssvm_internals | Failure | 3.13 | test_ssvm.py
test_01_migrate_VM_and_root_volume | Error | 79.58 | test_vm_life_cycle.py
test_02_migrate_VM_with_two_data_disks | Error | 66.88 | test_vm_life_cycle.py

The failed tests were executed manually and passed successfully.

Manual tests performed:

console proxy on system and regular VMs - OK

deploy a VM from a default template, uploaded template and ISO image - OK

VM operations: reboot, stop/start on another host, reinstall, create/revert snapshot, move to another host, attach/detach ISO, recover, expunge - OK

volume operations: resize, migrate, destroy/recover, attach/detach disk, create/revert snapshot, create template from snapshot - OK

storages: add/remove primary and secondary storage, mark secondary storage read-only and back - OK

system VMs operations: start/stop, reboot, migrate, get diag. data, run diagnostics, destroy - OK

outbound traffic: add/remove egress rules to VM network to allow outbound traffic - OK

inbound traffic: add/remove firewall and port-forwarding rules to allow inbound connections - OK

usage server: make sure the usage service is gathering usage data - OK

roles: deploy a VM, create/remove a network as regular user - OK

VM network operations: add/remove network to VM, add/remove secondary IP address, change IP address, set default NIC root - OK

hosts: add/remove, enable/disable a host, enable/disable maintenance mode - OK

Basic zone with shared storage - Zone deployment + basic VM / template / network / storage lifecycle - OK
Basic zone with local storage - Zone deployment + basic VM / template / network / storage lifecycle - OK
Advanced zone with SG and with shared storage - Smoke Tests - OK
Advanced zone with SG and with local storage - Smoke Tests - OK

Other combinations: VLAN, config drive - OK

Test Matrix :  (Trillian combinations)
- C7 MS + Rocky KVM Agent - OK
- Rocky MS + Rocky KVM Agent - OK
- Rocky MS + C7 KVM Agent - OK
- Rocky MS + VMware 6.7u3 / 7.0 - OK
- Rocky MS + XCPNG 8.2 / LTS - OK

Support for packaging and testing with BO (should be quick if jenkins jobs exist) - OK

Upstream docs with updates to installation and QIG sections - OK

**Comment by andrijapanicsb** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Comment by vladimirpetrov** [comment]
@blueorangutan test keepEnv

**Comment by davidjumani** [comment]
@blueorangutan package

**Review by andrijapanicsb — APPROVED** [review]
LGTM

**Comment by andrijapanicsb** [comment]
Merging based on manual tests, automatic tests, and approvals

**Pull request merged**
