### PR TITLE
remove Project Template Permissions inhibition

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR removes the inhibition for projects to update template permissions.

Fixes: #7350 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by vishesh92 — APPROVED** [review]
clgtm

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@DaanHoogland I tested the below scenario in an env with a Simulator zone:
1. Create a normal user
2. Create a project
3. Create a template with admin account in a project
4. Share the template with the normal user

Now the normal user doesn't have access to the project.
image

Toggling the Projects button, I can see the template.
image

I couldn't deploy a VM via UI because I couldn't see the template while launching the VM.
image

I am not sure if this is intended or if this is another bug or an enhancement?

**Comment by DaanHoogland** [comment]
> @DaanHoogland I tested the below scenario in an env with a Simulator zone:
> 
>     1. Create a normal user
> 
>     2. Create a project
> 
>     3. Create a template with admin account in a project
> 
>     4. Share the template with the normal user

...

> I am not sure if this is intended or if this is another bug or an enhancement?

as discussed I think the deplpoy wizard can not handle the truth. I'll have a look. thanks @vishesh92

**Comment by DaanHoogland** [comment]
@vishesh92 , seemed trivial. I have now added the `projectid=-1` parameter to the api call in the deploy wizard. Can you re-test/-check/-view?

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Comment by vishesh92** [comment]
@DaanHoogland Tested now. Able to launch a VM using the shared template.

**Comment by slavkap** [comment]
Hi all, on my dev. environments I don't work with projects (and I'm not very familiar with this option). I don't see any available templates when using the deploy VM wizard because of the `projectid=-1` in the API call. Should this be handled in the backend?

**Comment by DaanHoogland** [comment]
> Hi all, on my dev. environments I don't work with projects (and I'm not very familiar with this option). I don't see any available templates when using the deploy VM wizard because of the `projectid=-1` in the API call. Should this be handled in the backend?

No @slavkap I think another parameter needs to be set as well, or the the parameter needs to be optional (as in list templates)

**Comment by vishesh92** [comment]
@slavkap @DaanHoogland I have created a PR to fix this issue here: https://github.com/apache/cloudstack/pull/9196

**Pull request merged**
