### PR TITLE
ui: remove mandatory rule on root disk controller field while registering / updating a template

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

This PR removes the requirement to pass a root disk controller while either registering a template or while updating a template

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### Screenshots (if appropriate):
Legacy UI did not enforce root disk controller to be passed:
image

### How Has This Been Tested?
Registered / Attempted editing a template without passing root disk controller & deployed VM with the template

### CODE REVIEW

**Review by rohityadavcloud — APPROVED** [review]
LGTM - do we test with vmware @Pearl1594 ?

**Review by utchoang — APPROVED** [review]

**Comment by Pearl1594** [comment]
yes @rohityadavcloud

**Comment by Pearl1594** [comment]
@blueorangutan ui

**Comment by rohityadavcloud** [comment]
(testing new github actions integration that will automate some actions)

**Review by nvazquez — APPROVED** [review]

**Pull request merged**
