### PR TITLE
api: Remove redundant API parameters

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

This PR removes the redundant api parameters listed under listVirtualMachines API. The parameters are already defined in `ListVMsCmdByAdmin` class
```
(localcloud) 🐱 > list virtualmachines -h
listVirtualMachines: List the virtual machines owned by the account.
API Params               Type     Description
==========               ====     ===========
account                  string   list resources by account. Must be used w
                                  ith the domainId parameter.
...
hostid                   uuid     the host ID
hostid                   uuid     the host ID
...
podid                    uuid     the pod ID
podid                    uuid     the pod ID
...
storageid                uuid     the storage ID where vm's volumes belong 
                                  to
storageid                uuid     the storage ID where vm's volumes belong 
                                  to
...
```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [X] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan package

**Review by GabrielBrascher — COMMENTED** [review]
Thanks for the PR, @Pearl1594.

I would like to double-check if those parameters should be aimed only at Admins.
I ask this because it is not clear if that's the goal of this PR as well, or if it is aiming just at removing the redundant/duplicated parameters.

If the goal is to remove duplicated parameters but keep the current API behavior (Users & Admins), then I believe it should instead be removed at the `ListVMsCmdAdmin` which extends `ListVMsCmd`.

**Comment by Pearl1594** [comment]
Thanks for reviewing @GabrielBrascher , the following params: pod_id, storage_id, host_id, seem to be used only applicable only for root admins - https://github.com/apache/cloudstack/blob/main/server/src/main/java/com/cloud/api/query/QueryManagerImpl.java#L1004-L1011 , hence I took the following approach. It removes the redundant params and also ensures to behave the same way as before.

**Comment by DaanHoogland** [comment]
@Pearl1594 shouldn't a domain- or resource admin be allowed to list by host, pod, zone ?

**Comment by GabrielBrascher** [comment]
Sorry @Pearl1594, I raised the question regarding  "Admins & Users".
However, my concerns are regarding what @DaanHoogland mentioned, Admins & Domain Admins.

**Comment by Pearl1594** [comment]
It seems that only listing zones is allowed by domainAdmins - listing storage pools, hosts, clusters and pods, are restricted to root admins only. So, this change shouldn't effect any behavior.

**Comment by Pearl1594** [comment]
@blueorangutan package

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by Pearl1594** [comment]
@blueorangutan test

**Review by GabrielBrascher — APPROVED** [review]
LGTM

**Review by nvazquez — APPROVED** [review]
Code LGTM, checked the UI codebase and could not find any of the params being passed to the listVirtualMachines API

**Comment by nvazquez** [comment]
Have tested different roles and as advised by @Pearl1594 the removed parameters only apply for ROOT admin

**Pull request merged**
