### PR TITLE
Remove annotation and "depends-on" declaration not needed at cloud-engine-storage-image

### PR DESCRIPTION
**Pull request by rafaelweingartner**
Following the discussion on [1], I am proposing the removal of some unnecessary annotation and Spring configurations at cloud-engine-storage-image.

[1] http://mail-archives.apache.org/mod_mbox/cloudstack-dev/201711.mbox/%3CCAGQtxvZ1kc1EmzsMPRqUjOtcDSjr9aEAQGigBNUdVVg4ee%2BHGw%40mail.gmail.com%3E

### CODE REVIEW

**Comment by rafaelweingartner** [comment]
@DaanHoogland and @rhtyd can we check this PR?
Travis seems to be broken now for the problem we were discussing in the mailing list, and this PR solves it.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
LGTM, thanks for fixing @rafaelweingartner 
@blueorangutan test

**Comment by marcaurele** [comment]
LGTM - the `@Component` cannot work due to the system of spring sub modules created for CS. We would need to create a custom annotation to append the context name in which the bean should be created.

**Comment by rafaelweingartner** [comment]
@marcaurele yes, it is not working because these modules do not inherit the application context that enables annotations (I know there is one somewhere).

**Comment by rhtyd** [comment]
Tests LGTM

**Comment by rhtyd** [comment]
Ignoring intermittent failures not caused by this PR, I'll proceed with merging this. Thanks @rafaelweingartner

**Pull request merged**
