### PR TITLE
CLOUDSTACK-9788: Fix exception listNetworks with pagesize=0

### PR DESCRIPTION
**Pull request by ustcweizhou**

### CODE REVIEW

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
This might affect other/all APIs therefore would require regression testing, but LGTM (did not test this).

**Comment by borisstoyanov** [comment]
Trillian build failed:
16:43:38 FAILED - RETRYING: TASK: Wait for default template to be ready before returning (1 retries left).
will try again.. 
@blueorangutan test

**Comment by rhtyd** [comment]
LGTM.
@karuturi this is ready for merge.

**Comment by kiwiflyer** [comment]
tag:mergeready

**Comment by rhtyd** [comment]
LGTM. @karuturi let's merge this?

**Pull request merged**
