### PR TITLE
ui: fix haenable in edit vm form

### LINKED ISSUE #8510: UI instance edit does not show ha setting correctly
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.18.1.0
~~~

##### SUMMARY

When editing the instance settings via UI the value of haenable will always shown as disabled, even if the state is true.
Api call listVirtualMachinesMetrics is providing the correct value, it looks like UI is just not using this value to disable or enalbe the button in the edit popup.

##### STEPS TO REPRODUCE

1) create an instance using a compute offering with ha enable true
2) in UI go to Compute ->Instances and click on the instance.
3) take a look at the Details and HA enabled. It shows true
cs41810_instance_details

4) click on edit icon to open the popup to edit the instance
cs41810_instance_edit

HA enabled will always shown as disabled.

~~~

~~~

##### EXPECTED RESULTS

~~~
UI edit instance popup will show correct value of haenable.
~~~

##### ACTUAL RESULTS

~~~
UI edit instancen popup will always show haenable as disabled.
~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #8510

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by DaanHoogland** [comment]
@shwstppr you mention 8150, is this a typo? It seems to be about something else.

**Comment by shwstppr** [comment]
> @shwstppr you mention 8150, is this a typo? It seems to be about something else.

Yes, @DaanHoogland. I've fixed now

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@shwstppr , i tried in QA but don't see the check for ha in the edit vm dialog there. Is this available in main only?

**Comment by shwstppr** [comment]
VM offering should offer HA.
Here is one such VM, https://qa.cloudstack.cloud/simulator/pr/9049/#/vm/ca609571-ab79-4d65-b572-49b2f701d109

**Comment by shwstppr** [comment]
@DaanHoogland ^^

**Comment by DaanHoogland** [comment]
thanks, @shwstppr clear (and of course :facepalm: )
LGTM

**Review by weizhouapache — APPROVED** [review]
qa looks good

**Comment by weizhouapache** [comment]
verified OK on QA: https://qa.cloudstack.cloud/simulator/pr/9049/#/vm/28927242-410b-4e4e-a5bf-e33740b8e240

please note, the service offering must offer HA. otherwise, user will see the following error when update vm to ha-enabled
```
(localcloud) 🐱 > update virtualmachine id=2446f9d9-83ad-4b4c-bf3e-df041a390fcf haenable=true
🙈 Error: (HTTP 530, error code 4250) Failed to update VM, due to: Can't enable ha for the vm as it's created from the Service offering having HA disabled
```

**Pull request merged**
