### PR TITLE
UI: Add search filters

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR fixes https://github.com/apache/cloudstack/issues/7218

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by vishesh92** [comment]
@blueorangutan ui

**Comment by DaanHoogland** [comment]
@blueorangutan ui

**Review by DaanHoogland — APPROVED** [review]
code looks good and filters show in qa (and work wherever I tried)

**Review by shwstppr — APPROVED** [review]
Code LGTM

**Pull request merged**
