### PR TITLE
vr: fix python exception when configure VRs

### LINKED ISSUE #4474: Cloudstack Agent SetMonitorServiceCommand
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Cloudstack-Agent
~~~

##### CLOUDSTACK VERSION

~~~
4.14 , running on Ubuntu 18.04
~~~

##### CONFIGURATION

Advance Network, with SG

##### OS / ENVIRONMENT

Ubuntu 18.04

##### STEPS TO REPRODUCE

~~~
Create VM , and In Cloudstack log show:

2020-11-17 03:50:54,123 WARN  [resource.virtualnetwork.VirtualRoutingResource] (agentRequest-Handler-1:null) (logid:d557e0de) Expected 1 answers while executing SetMonitorServiceCommand but received 3



Cloudstack Usage for Network Byte send and Received is not calculated ,  Suspect is this SetMonitorServiceCommand warning and not populate the data correctly

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~




~~~

### PR DESCRIPTION
**Pull request by ustcweizhou**
### Description

This PR fixes #4474

before
```
root@r-27-VM:/var/cache/cloud# /opt/cloud/bin/configure.py monitor_service.json
ERROR:root:Command 'ip link show eth0 | grep 'state DOWN'' returned non-zero exit status 1
```

with this change
```
root@r-27-VM:/var/cache/cloud# /opt/cloud/bin/configure.py monitor_service.json
root@r-27-VM:/var/cache/cloud#
```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by ravening** [comment]
LGTM

**Review by DaanHoogland — APPROVED** [review]
change makes sense, but not tested.

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Pull request merged**
