### PR TITLE
UI: fix create Isolated/L2 network form

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes a UI bug caused by #5745 
Fixes: #5780

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan ui

**Review by DaanHoogland — APPROVED** [review]
tnx @weizhouapache seems good to me

**Review by shwstppr — APPROVED** [review]

**Review by utchoang — APPROVED** [review]
LGTM!

**Review by sureshanaparti — APPROVED** [review]

**Comment by sureshanaparti** [comment]
Verified the dialog for creating a new network. LGTM.

**Pull request merged**
