### PR TITLE
cleanup: remove test/src-not-used/

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR removes unused project:  test/src-not-used/

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
LGTM - smoketests aren't required if this was dead/unused code to begin with.

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
> LGTM - smoketests aren't required if this was dead/unused code to begin with.

right, didn't check that (or the PR number) I stopped the jobs and we should be fine to merge.

**Review by DaanHoogland — APPROVED** [review]

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@blueorangutan test matrix

**Comment by weizhouapache** [comment]
the test failures are not related to this pr


```
marvin.cloudstackException.CloudstackAPIException: Execute cmd: createnetwork failed, due to: errorCode: 431, errorText:The VLAN tag to use for new guest network, 2468 is already being used for dynamic vlan allocation for the guest network in zone pr9007-t10185-xenserver-71
```

and
```
Exception: Job failed: {accountid : '00dc36b4-0cb2-11ef-b0f4-1e00f60001d2', userid : '00dd8de2-0cb2-11ef-b0f4-1e00f60001d2', cmd : 'org.apache.cloudstack.api.command.admin.vm.MigrateVMCmd', jobstatus : 2, jobprocstatus : 0, jobresultcode : 431, jobresulttype : 'object', jobresult : {errorcode : 431, errortext : 'Cannot migrate VM, destination host is not in correct state, has status: Connecting, state: Enabled'}, jobinstancetype : 'VirtualMachine', jobinstanceid : 'aa2151a3-6879-4951-81ee-af6892ecbd5f', created : '2024-05-08T06:27:17+0000', completed : '2024-05-08T06:27:17+0000', jobid : '56824238-11a0-4adb-a089-76d8886476d9'}
```

**Pull request merged**
