### PR TITLE
fix noredist build because of missing maven dependency of vmware 6.0 lib

### PR DESCRIPTION
**Pull request by pdion891**
fix noredist build for new vmware lib

### CODE REVIEW

**Comment by swill** [comment]
This is to fix novelist on master. Correct?

**Comment by swill** [comment]
noredist* phone loves to change things.

**Comment by swill** [comment]
@rhtyd can you review why travis is failing?  It seems to be failing to find something at shapeblue.  We should probably review what is being hosted at shapeblue which is in our critical path and get them moved.  Thx...

**Comment by rhtyd** [comment]
@swill there is a ipmitool pkg that needs to be installed before each run. I'll send a PR for a workaround.
The packages.shapeblue.com repository is down, which we'll chase with BT who is hosting the server on Monday.

**Comment by rhtyd** [comment]
@pdion891 usually, I clone this repo: https://github.com/rhtyd/cloudstack-nonoss and execute the install-non-oss.sh script in that repo: https://github.com/rhtyd/cloudstack-nonoss/blob/master/install-non-oss.sh

**Comment by rhtyd** [comment]
LGTM

**Comment by pdion891** [comment]
@rhtyd  why not update the main "deps/install-non-oss.sh" instead of duplicating it in another repo? Also, I think we are due to update the documentation on build ACS with noredist. It's an oudated documentation :-S

**Comment by swill** [comment]
Fixed...  You can resume testing `master` @pdion891.  Cheers...

**Pull request merged**
