### PR TITLE
Fix listStoragePoolsMetricsCmd

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR fixes `listStoragePoolsMetricsCmd` when there are no search results.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

To reproduce the error
```
cmk list storagepoolsmetrics keyword=zxcvbn
__ Error: (HTTP 530, error code 4250) DB Exception on: com.mysql.cj.jdbc.ClientPreparedStatement: SELECT cluster.id, cluster.name, cluster.guid, cluster.data_center_id, cluster.pod_id, cluster.hypervisor_type, cluster.cluster_type, cluster.allocation_state, cluster.managed_state, cluster.removed, cluster.uuid FROM cluster WHERE cluster.uuid IN )  AND cluster.removed IS NULL 
```
After applying the patch, error disappears.

### CODE REVIEW

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan test

**Review by sureshanaparti — APPROVED** [review]
code lgtm

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Review by borisstoyanov — APPROVED** [review]
LGTM, manually tested

**Pull request merged**
