### PR TITLE
engine/orchestration: enable unit tests and fix errors

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

The unit tests in engine/orchestration module are skipped for now.

This PR enables the unit tests and fixes the errors with the unit tests.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
code looks good

**Comment by DaanHoogland** [comment]
@weizhouapache do you feel this has been tested enough with packaging and the github actions?

**Comment by weizhouapache** [comment]
> @weizhouapache do you feel this has been tested enough with packaging and the github actions?

@DaanHoogland 
yeah, I think so.
unit tests might be skipped in some packaging jobs or CI checks, but most of them should build cloudstack with unit tests.

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
Packaging has passed and the maven build Github Action, so unit tests are passing. Changes are only in unit tests so integration tests are n't required.

**Pull request merged**
