### PR TITLE
systemvm: remove config in /etc/pam.d/systemd-user to fix user@0.service

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

the service `user@0.service` fails in system vms and virtual routers

This PR removes a change to fix memory leak of SSH connections in the systemvm templates with old linux kernel.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
image

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
looks good, the original bug for which this was introduced is fixed. I see no reference to any problems, so it should be good. Not sure if we can test anything other than the SVMs running fine.

**Comment by shwstppr** [comment]
@weizhouapache this will require new systemvm template?

**Comment by weizhouapache** [comment]
> @weizhouapache this will require new systemvm template?

@shwstppr 
I think so
the changes with `init.sh` and `cloud-early-config` require new systemvm template

**Review by rohityadavcloud — APPROVED** [review]
LGTM - didn't test it but changes make sense, esp that the upstream systemd is fixed

**Comment by rohityadavcloud** [comment]
@weizhouapache @DaanHoogland @harikrishna-patnala  I'm assuming this doesn't require a systemvmtemplate build (since changes are not in the cloud-early-config ?)

**Comment by shwstppr** [comment]
@rohityadavcloud This may require new systemvm template build. https://github.com/apache/cloudstack/pull/8048#issuecomment-1754819284

**Comment by rohityadavcloud** [comment]
Thanks @shwstppr @weizhouapache - that seems to be correct, but the other question is - is this fixing any issue? Is the failure of the service causing issues with systemvms and vrouters?

**Comment by weizhouapache** [comment]
@rohityadavcloud 
this fixes the service user@0.service in VRs and system vms. 
but It seems other services in the vms are not impacted by the failure with `user@0.service`. this is a minor/trivial issue

**Comment by rohityadavcloud** [comment]
Thanks for checking @weizhouapache cc @shwstppr - if necessary let's build systemvmtemplate for 4.19.0 ?

**Pull request merged**
