### PR TITLE
CLOUDSTACK-8690:Added remote access vpn and vpn users configuration

### PR DESCRIPTION
**Pull request by jayapalu**
@remibergsma  @wilderrodrigues 
Added the VR configuration changes for 
1. Remote access vpn
2. Remote access vpn users.

### CODE REVIEW

**Comment by miguelaferreira** [comment]
@jayapalu I can make time to test this, but I would need you help for that. I mean, I need to know what's the minimal setup and a test to run. Would it be possible to arrange that?

**Comment by jayapalu** [comment]
@miguelaferreira 
1. configure advanced zone isolated network. (Note: Bring up the VR with the PR changes)
2. Enable remote access vpn on source NAT network.
3. Configure the vpn users.
4. From the public side vpn client connect to this VR public ip.
You can use windows to connect the vpn.

**Comment by miguelaferreira** [comment]
I have step 1 automated, but unfortunately that's the only one. I will keep this PR on my list to test, but other for which the testing is fully automated will take precedence.
I'll keep you posted.

**Comment by wilderrodrigues** [comment]
Hi @jayapalu 

Could you have a look at the smoke/test_vpc_vpn.py  test and let me know if that covers your changes?

There is also a test for vpn users: component/test_vpn_users.py

Thanks in advance.

Cheers,
Wilder

**Comment by jayapalu** [comment]
@miguelaferreira Configuration on the vpc router also applied. So the tests should get passed.

**Comment by wilderrodrigues** [comment]
Hi @jayapalu 

I will run the test_vpn_users and test_vpc_vpn tests. Will be back to you later.

Cheers,
Wilder

**Comment by wilderrodrigues** [comment]
Hi @jayapalu @remibergsma @miguelaferreira @DaanHoogland 

I executed the tests mentioned about. Results below:

VPN remote access user limit tests ... === TestName: test_01_VPN_user_limit | Status : SUCCESS ===
ok
Test create VPN when L2TP port in use ... === TestName: test_02_use_vpn_port | Status : SUCCESS ===
ok
Test create NAT rule when VPN when L2TP enabled ... === TestName: test_03_enable_vpn_use_port | Status : SUCCESS ===
ok
Test add new users to existing VPN ... === TestName: test_04_add_new_users | Status : SUCCESS ===
ok
Test add duplicate user to existing VPN ... === TestName: test_05_add_duplicate_user | Status : SUCCESS ===
ok
Test as global admin, add a new VPN user to an existing VPN entry ... === TestName: test_06_add_VPN_user_global_admin | Status : SUCCESS ===
ok
Test as domain admin, add a new VPN user to an existing VPN entry ... === TestName: test_07_add_VPN_user_domain_admin | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 7 tests in 2483.901s

OK
/tmp//MarvinLogs/test_vpn_users_Z7SW61/results.txt (END)

Test VPN in VPC ... === TestName: test_vpc_remote_access_vpn | Status : SUCCESS ===
ok
Test VPN in VPC ... === TestName: test_vpc_site2site_vpn | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 2 tests in 1560.555s

OK
/tmp//MarvinLogs/test_vpc_vpn_LXRLZL/results.txt (END)


I also had a look at the tests code in order to see if they are covering real cases. For the test user, it doesn't really check connection availability. It's more about the users, as the name suggested.

Concerning the VPC VPN, it tests quite a lot. It creates a VPC and adds 1 VM to it, then it creates a VPN on the source nat IP and adds 1 VPN user to it. It doesn't test connection though. That would have to be done manually or we have to write a Python VPN client connection inside the test code.

In respect to the test_vpc_site2site_vpn test, it creates 2 VPCs, 2 networks, 2 VMs and 2 VPNs - on each source nat ip address. The cool thing is that the test connects the VPCs to each other, so testing the VPN connection in this case.

Would that cover your changes, @jayapalu ?

What do you think, @remibergsma @miguelaferreira @DaanHoogland ?

Cheers,
Wilder

**Comment by jayapalu** [comment]
@wilderrodrigues Configuring  remote access vpn and vpn users is success in test cases that covers the code changes. Regarding the remote access vpn connection test,. it is not automated. So try manually connecting if it is success please give LGTM.

**Comment by jayapalu** [comment]
@wilderrodrigues  You can try remote access vpn connection in isolated network VR.

**Comment by wilderrodrigues** [comment]
Hi @jayapalu 

The change LGTM regarding the tests I have executed, which covers almost the whole thing. If you tested it manually, that's fine by me.

I can help writing a test to cover it, but won't have time to do so in the coming weeks. I would say go on with the merge as soon as you get a 2nd LGTM.

Cheers,
Wilder

**Comment by wilderrodrigues** [comment]
@karuturi @wido @borisroman 

Could one of you have a look at this PR, please? :)

Cheers,
Wilder

**Comment by bvbharatk** [comment]
LGTM

**Pull request merged**
