### PR TITLE
docker: upgrade to ubuntu 18.04 and fix some issues

### PR DESCRIPTION
**Pull request by ustcweizhou**
## Description

upgrade dockerfile to use ubuntu 18.04 instead of ubuntu 16.04 because we use java 11 in 4.14.
meanwhile, fix an issue due to mysql change in ubuntu 18.04, and fix NPE by installing iproute2.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@weizhouapache do we need this on 4.13 as well?

**Comment by ravening** [comment]
Tested it and works fine.

**Comment by weizhouapache** [comment]
> @weizhouapache do we need this on 4.13 as well?

@DaanHoogland no... in 4.13 we use openjdk 8 which is supported by ubuntu 16.04

**Comment by DaanHoogland** [comment]
👍

**Comment by DaanHoogland** [comment]
not sure what happened but travis is not at all happy as the DB is unreachable for root@localhost

**Comment by weizhouapache** [comment]
travis test still failed. I will have a look when I have time.

**Comment by rhtyd** [comment]
This cannot be checked without docker building the dockerfile, we've enough +1/lgtm/thumbsup so I'll merge this.

**Pull request merged**
