### PR TITLE
CLOUDSTACK-8537 add check for unique public key on registration

### PR DESCRIPTION
**Pull request by DaanHoogland**
tests are following but need a manager refactor:(

### CODE REVIEW

**Comment by bhaisaab** [comment]
LGTM, any test results?

**Comment by DaanHoogland** [comment]
H @bhaisaab not done writing a unit test yet. It is on my list so but it seems fairly trivial so feel free to merge if you like it like this.

**Comment by DaanHoogland** [comment]
accidentally added another commit by rebasing on it. trying to fix now

**Comment by DaanHoogland** [comment]
@bhaisaab unit test added, won't test this other then integrally with the suits at hand

**Pull request closed without merging**
