### PR TITLE
Cleanup stale files in /tmp which is filling up during some runs

### PR DESCRIPTION
**Pull request by rsafonseca**
Output status of disk and memory on build host for some extra info on build environment before start

This should fix the travis problem made visible in this run:
https://travis-ci.org/apache/cloudstack/jobs/68291716

### CODE REVIEW

**Comment by wilderrodrigues** [comment]
LGTM

I executed the command on one of my machines and it's fine - although my eyes could already see it was.

Result:

[wrodrigues@mct-wrodrigues ~]$ sudo find /tmp -type f -mtime +2 | grep -v "`sudo lsof | grep /tmp |awk '{print $9}'|sed -e '1 d' |sort |uniq | tr \\n \|`"
/tmp/libvirt/pool_images.xml
/tmp/libvirt/pool_iso.xml

Remark: I removed the "| xargs sudo rm -vf" part because I did not want to remove my files

Cheers,
Wilder

**Comment by wilderrodrigues** [comment]
@runseb @DaanHoogland @remibergsma 

Does this one needs 2 LGTM as well?

I'm willing to close a few PRs.

Cheers,
Wilder

**Comment by karuturi** [comment]
changes looks good to me.

**Comment by DaanHoogland** [comment]
@wilderrodrigues let's stick to that for now (I kind of did the last few findbugs thing to see what happened with them:)

LGTM

**Comment by wilderrodrigues** [comment]
@DaanHoogland 

I already merged :)

Got a LGTM from @karuturi 

Thanks, guys!

**Pull request merged**
