### PR TITLE
server: Honor vm.destroy.forcestop when expunge a vm

### PR DESCRIPTION
**Pull request by ustcweizhou**
## Description

When expunge a Running vm, vm will be stopped with forcestop=false which does not make sense. we should honor vm.destroy.forcestop in global setting, or always set forcestop=true.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by rhtyd** [comment]
Usually we would expunged a destroyed VM which must be already stopped?
LGTM nonetheless.

**Comment by weizhouapache** [comment]
> Usually we would expunged a destroyed VM which must be already stopped?
> LGTM nonetheless.

actually there are two apis doing the same thing.

```
expunge virtualmachine id=<vm id>
destroy virtualmachine id=<vm id> expunge=True
```

vm can be Running, Stopped, Destroyed.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Pull request merged**
