### PR TITLE
systemvm: fix pep8 errors

### PR DESCRIPTION
**Pull request by resmo**
fixed pep8 errors. in `baremetal-vr.py` also replaced "windows carriage return" to "unix carriage return".

Before:
~~~
 $ pep8 --max-line-length=160 systemvm/patches/debian/config/opt/cloud/bin/**/*.py
systemvm/patches/debian/config/opt/cloud/bin/baremetal-vr.py:1:1: E265 block comment should start with '# '
systemvm/patches/debian/config/opt/cloud/bin/baremetal-vr.py:2:1: E265 block comment should start with '# '
systemvm/patches/debian/config/opt/cloud/bin/baremetal-vr.py:3:1: E265 block comment should start with '# '
systemvm/patches/debian/config/opt/cloud/bin/baremetal-vr.py:4:1: E265 block comment should start with '# '
systemvm/patches/debian/config/opt/cloud/bin/baremetal-vr.py:5:1: E265 block comment should start with '# '
systemvm/patches/debian/config/opt/cloud/bin/baremetal-vr.py:6:1: E265 block comment should start with '# '
systemvm/patches/debian/config/opt/cloud/bin/baremetal-vr.py:7:1: E265 block comment should start with '# '
systemvm/patches/debian/config/opt/cloud/bin/baremetal-vr.py:11:1: E265 block comment should start with '# '
systemvm/patches/debian/config/opt/cloud/bin/baremetal-vr.py:12:1: E265 block comment should start with '# '
systemvm/patches/debian/config/opt/cloud/bin/baremetal-vr.py:13:1: E265 block comment should start with '# '
systemvm/patches/debian/config/opt/cloud/bin/baremetal-vr.py:14:1: E265 block comment should start with '# '
systemvm/patches/debian/config/opt/cloud/bin/baremetal-vr.py:15:1: E265 block comment should start with '# '
systemvm/patches/debian/config/opt/cloud/bin/baremetal-vr.py:16:1: E265 block comment should start with '# '
systemvm/patches/debian/config/opt/cloud/bin/baremetal-vr.py:20:1: E402 module level import not at top of file
systemvm/patches/debian/config/opt/cloud/bin/baremetal-vr.py:21:1: E402 module level import not at top of file
systemvm/patches/debian/config/opt/cloud/bin/baremetal-vr.py:22:1: E402 module level import not at top of file
systemvm/patches/debian/config/opt/cloud/bin/baremetal-vr.py:23:1: E402 module level import not at top of file
systemvm/patches/debian/config/opt/cloud/bin/baremetal-vr.py:24:1: E402 module level import not at top of file
systemvm/patches/debian/config/opt/cloud/bin/baremetal-vr.py:25:1: E402 module level import not at top of file
systemvm/patches/debian/config/opt/cloud/bin/baremetal-vr.py:26:1: E402 module level import not at top of file
systemvm/patches/debian/config/opt/cloud/bin/baremetal-vr.py:28:1: E402 module level import not at top of file
systemvm/patches/debian/config/opt/cloud/bin/baremetal-vr.py:39:1: E302 expected 2 blank lines, found 1
systemvm/patches/debian/config/opt/cloud/bin/baremetal-vr.py:49:161: E501 line too long (166 > 160 characters)
systemvm/patches/debian/config/opt/cloud/bin/baremetal-vr.py:70:1: E302 expected 2 blank lines, found 1
systemvm/patches/debian/config/opt/cloud/bin/baremetal-vr.py:76:5: E301 expected 1 blank line, found 0
systemvm/patches/debian/config/opt/cloud/bin/baremetal-vr.py:143:161: E501 line too long (176 > 160 characters)
systemvm/patches/debian/config/opt/cloud/bin/baremetal-vr.py:147:1: E305 expected 2 blank lines after class or function definition, found 1
systemvm/patches/debian/config/opt/cloud/bin/baremetal-vr.py:149:1: E302 expected 2 blank lines, found 1
systemvm/patches/debian/config/opt/cloud/bin/baremetal-vr.py:160:161: E501 line too long (172 > 160 characters)
systemvm/patches/debian/config/opt/cloud/bin/configure.py:50:15: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:73:17: E122 continuation line missing indentation or outdented
systemvm/patches/debian/config/opt/cloud/bin/configure.py:125:44: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:323:25: E221 multiple spaces before operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:503:18: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:503:48: E231 missing whitespace after ','
systemvm/patches/debian/config/opt/cloud/bin/configure.py:504:18: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:504:48: E231 missing whitespace after ','
systemvm/patches/debian/config/opt/cloud/bin/configure.py:506:12: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:508:16: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:531:25: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:555:1: E302 expected 2 blank lines, found 1
systemvm/patches/debian/config/opt/cloud/bin/configure.py:556:13: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:563:23: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:573:40: E228 missing whitespace around modulo operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:573:46: E231 missing whitespace after ','
systemvm/patches/debian/config/opt/cloud/bin/configure.py:574:37: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:574:42: E231 missing whitespace after ','
systemvm/patches/debian/config/opt/cloud/bin/configure.py:575:45: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:586:5: E303 too many blank lines (2)
systemvm/patches/debian/config/opt/cloud/bin/configure.py:589:34: E228 missing whitespace around modulo operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:589:40: E231 missing whitespace after ','
systemvm/patches/debian/config/opt/cloud/bin/configure.py:608:47: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:613:65: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:618:1: E303 too many blank lines (3)
systemvm/patches/debian/config/opt/cloud/bin/configure.py:628:22: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:630:13: E265 block comment should start with '# '
systemvm/patches/debian/config/opt/cloud/bin/configure.py:632:65: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:645:17: E265 block comment should start with '# '
systemvm/patches/debian/config/opt/cloud/bin/configure.py:650:5: E303 too many blank lines (2)
systemvm/patches/debian/config/opt/cloud/bin/configure.py:651:21: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:652:23: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:653:23: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:654:25: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:657:16: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:658:18: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:659:20: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:660:16: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:661:12: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:663:9: E265 block comment should start with '# '
systemvm/patches/debian/config/opt/cloud/bin/configure.py:668:9: E303 too many blank lines (2)
systemvm/patches/debian/config/opt/cloud/bin/configure.py:670:38: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:674:43: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:675:43: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:678:21: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:679:53: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:683:18: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:684:18: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:685:17: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:688:9: E303 too many blank lines (2)
systemvm/patches/debian/config/opt/cloud/bin/configure.py:695:35: E231 missing whitespace after ','
systemvm/patches/debian/config/opt/cloud/bin/configure.py:696:35: E231 missing whitespace after ','
systemvm/patches/debian/config/opt/cloud/bin/configure.py:697:35: E231 missing whitespace after ','
systemvm/patches/debian/config/opt/cloud/bin/configure.py:698:35: E231 missing whitespace after ','
systemvm/patches/debian/config/opt/cloud/bin/configure.py:699:35: E231 missing whitespace after ','
systemvm/patches/debian/config/opt/cloud/bin/configure.py:699:71: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:700:35: E231 missing whitespace after ','
systemvm/patches/debian/config/opt/cloud/bin/configure.py:700:78: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:701:35: E231 missing whitespace after ','
systemvm/patches/debian/config/opt/cloud/bin/configure.py:703:35: E231 missing whitespace after ','
systemvm/patches/debian/config/opt/cloud/bin/configure.py:704:35: E231 missing whitespace after ','
systemvm/patches/debian/config/opt/cloud/bin/configure.py:705:35: E231 missing whitespace after ','
systemvm/patches/debian/config/opt/cloud/bin/configure.py:708:9: E303 too many blank lines (2)
systemvm/patches/debian/config/opt/cloud/bin/configure.py:708:31: E231 missing whitespace after ','
systemvm/patches/debian/config/opt/cloud/bin/configure.py:709:31: E231 missing whitespace after ','
systemvm/patches/debian/config/opt/cloud/bin/configure.py:710:34: E231 missing whitespace after ','
systemvm/patches/debian/config/opt/cloud/bin/configure.py:715:37: E231 missing whitespace after ','
systemvm/patches/debian/config/opt/cloud/bin/configure.py:715:53: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/configure.py:716:37: E231 missing whitespace after ','
systemvm/patches/debian/config/opt/cloud/bin/configure.py:717:37: E231 missing whitespace after ','
systemvm/patches/debian/config/opt/cloud/bin/configure.py:718:37: E231 missing whitespace after ','
systemvm/patches/debian/config/opt/cloud/bin/configure.py:719:37: E231 missing whitespace after ','
systemvm/patches/debian/config/opt/cloud/bin/configure.py:734:5: E265 block comment should start with '# '
systemvm/patches/debian/config/opt/cloud/bin/configure.py:780:9: E265 block comment should start with '# '
systemvm/patches/debian/config/opt/cloud/bin/configure.py:895:109: E502 the backslash is redundant between brackets
systemvm/patches/debian/config/opt/cloud/bin/configure.py:898:137: E502 the backslash is redundant between brackets
systemvm/patches/debian/config/opt/cloud/bin/configure.py:909:9: E265 block comment should start with '# '
systemvm/patches/debian/config/opt/cloud/bin/configure.py:913:144: E231 missing whitespace after ','
systemvm/patches/debian/config/opt/cloud/bin/configure.py:913:161: E501 line too long (185 > 160 characters)
systemvm/patches/debian/config/opt/cloud/bin/configure.py:1035:1: E305 expected 2 blank lines after class or function definition, found 1
systemvm/patches/debian/config/opt/cloud/bin/cs/CsAddress.py:30:1: E302 expected 2 blank lines, found 1
systemvm/patches/debian/config/opt/cloud/bin/cs/CsAddress.py:363:5: E303 too many blank lines (2)
systemvm/patches/debian/config/opt/cloud/bin/cs/CsAddress.py:444:75: E221 multiple spaces before operator
systemvm/patches/debian/config/opt/cloud/bin/cs/CsAddress.py:726:1: W391 blank line at end of file
systemvm/patches/debian/config/opt/cloud/bin/cs/CsDatabag.py:139:27: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/cs/CsDatabag.py:140:19: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/cs/CsDhcp.py:137:35: E712 comparison to True should be 'if cond is True:' or 'if cond:'
systemvm/patches/debian/config/opt/cloud/bin/cs/CsDhcp.py:143:51: E231 missing whitespace after ','
systemvm/patches/debian/config/opt/cloud/bin/cs/CsDhcp.py:162:5: E303 too many blank lines (2)
systemvm/patches/debian/config/opt/cloud/bin/cs/CsFile.py:71:5: E303 too many blank lines (2)
systemvm/patches/debian/config/opt/cloud/bin/cs/CsFile.py:138:5: E303 too many blank lines (2)
systemvm/patches/debian/config/opt/cloud/bin/cs/CsFile.py:143:31: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/cs/CsFile.py:153:5: E303 too many blank lines (2)
systemvm/patches/debian/config/opt/cloud/bin/cs/CsFile.py:166:5: E303 too many blank lines (2)
systemvm/patches/debian/config/opt/cloud/bin/cs/CsHelper.py:30:30: E203 whitespace before ':'
systemvm/patches/debian/config/opt/cloud/bin/cs/CsHelper.py:30:52: E203 whitespace before ':'
systemvm/patches/debian/config/opt/cloud/bin/cs/CsHelper.py:32:27: E203 whitespace before ':'
systemvm/patches/debian/config/opt/cloud/bin/cs/CsHelper.py:33:30: E203 whitespace before ':'
systemvm/patches/debian/config/opt/cloud/bin/cs/CsHelper.py:33:161: E501 line too long (173 > 160 characters)
systemvm/patches/debian/config/opt/cloud/bin/cs/CsHelper.py:35:1: E302 expected 2 blank lines, found 1
systemvm/patches/debian/config/opt/cloud/bin/cs/CsHelper.py:55:1: E302 expected 2 blank lines, found 1
systemvm/patches/debian/config/opt/cloud/bin/cs/CsHelper.py:242:1: E302 expected 2 blank lines, found 1
systemvm/patches/debian/config/opt/cloud/bin/cs/CsNetfilter.py:147:35: E203 whitespace before ':'
systemvm/patches/debian/config/opt/cloud/bin/cs/CsRedundant.py:45:1: E302 expected 2 blank lines, found 1
systemvm/patches/debian/config/opt/cloud/bin/cs/CsRedundant.py:106:1: W293 blank line contains whitespace
systemvm/patches/debian/config/opt/cloud/bin/cs/CsRedundant.py:153:1: W293 blank line contains whitespace
systemvm/patches/debian/config/opt/cloud/bin/cs/CsRedundant.py:374:24: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/cs/CsRedundant.py:377:38: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/cs/CsRoute.py:40:14: E111 indentation is not a multiple of four
systemvm/patches/debian/config/opt/cloud/bin/cs/CsRoute.py:44:14: E111 indentation is not a multiple of four
systemvm/patches/debian/config/opt/cloud/bin/cs/CsRoute.py:118:21: W292 no newline at end of file
systemvm/patches/debian/config/opt/cloud/bin/cs/CsRule.py:52:11: E271 multiple spaces after keyword
systemvm/patches/debian/config/opt/cloud/bin/cs/CsStaticRoutes.py:42:48: W292 no newline at end of file
systemvm/patches/debian/config/opt/cloud/bin/cs_ip.py:21:1: E302 expected 2 blank lines, found 1
systemvm/patches/debian/config/opt/cloud/bin/cs_ip.py:34:10: E111 indentation is not a multiple of four
systemvm/patches/debian/config/opt/cloud/bin/cs_ip.py:48:45: E261 at least two spaces before inline comment
systemvm/patches/debian/config/opt/cloud/bin/cs_vpnusers.py:41:17: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/cs_vpnusers.py:42:12: E225 missing whitespace around operator
systemvm/patches/debian/config/opt/cloud/bin/line_edit.py:196:1: E305 expected 2 blank lines after class or function definition, found 1
systemvm/patches/debian/config/opt/cloud/bin/master.py:45:1: E265 block comment should start with '# '
systemvm/patches/debian/config/opt/cloud/bin/merge.py:273:1: E302 expected 2 blank lines, found 1
systemvm/patches/debian/config/opt/cloud/bin/merge.py:323:5: E303 too many blank lines (2)
systemvm/patches/debian/config/opt/cloud/bin/merge.py:335:161: E501 line too long (165 > 160 characters)
systemvm/patches/debian/config/opt/cloud/bin/merge.py:339:5: E303 too many blank lines (2)
systemvm/patches/debian/config/opt/cloud/bin/merge.py:344:5: E303 too many blank lines (2)
systemvm/patches/debian/config/opt/cloud/bin/merge.py:352:5: E303 too many blank lines (2)
systemvm/patches/debian/config/opt/cloud/bin/passwd_server_ip.py:36:20: E272 multiple spaces before keyword
systemvm/patches/debian/config/opt/cloud/bin/passwd_server_ip.py:37:18: E272 multiple spaces before keyword
systemvm/patches/debian/config/opt/cloud/bin/passwd_server_ip.py:37:44: E261 at least two spaces before inline comment
systemvm/patches/debian/config/opt/cloud/bin/passwd_server_ip.py:37:45: E262 inline comment should start with '# '
systemvm/patches/debian/config/opt/cloud/bin/passwd_server_ip.py:45:1: E302 expected 2 blank lines, found 1
systemvm/patches/debian/config/opt/cloud/bin/passwd_server_ip.py:48:1: E302 expected 2 blank lines, found 1
systemvm/patches/debian/config/opt/cloud/bin/passwd_server_ip.py:51:1: E302 expected 2 blank lines, found 1
systemvm/patches/debian/config/opt/cloud/bin/passwd_server_ip.py:61:1: E302 expected 2 blank lines, found 1
systemvm/patches/debian/config/opt/cloud/bin/passwd_server_ip.py:64:1: E302 expected 2 blank lines, found 1
systemvm/patches/debian/config/opt/cloud/bin/passwd_server_ip.py:68:35: E701 multiple statements on one line (colon)
systemvm/patches/debian/config/opt/cloud/bin/passwd_server_ip.py:74:1: E302 expected 2 blank lines, found 1
systemvm/patches/debian/config/opt/cloud/bin/passwd_server_ip.py:84:1: E302 expected 2 blank lines, found 1
systemvm/patches/debian/config/opt/cloud/bin/passwd_server_ip.py:87:1: E302 expected 2 blank lines, found 1
systemvm/patches/debian/config/opt/cloud/bin/passwd_server_ip.py:93:1: E302 expected 2 blank lines, found 1
systemvm/patches/debian/config/opt/cloud/bin/passwd_server_ip.py:106:5: E301 expected 1 blank line, found 0
systemvm/patches/debian/config/opt/cloud/bin/passwd_server_ip.py:136:46: E231 missing whitespace after ':'
systemvm/patches/debian/config/opt/cloud/bin/passwd_server_ip.py:137:44: E231 missing whitespace after ':'
systemvm/patches/debian/config/opt/cloud/bin/passwd_server_ip.py:138:21: E124 closing bracket does not match visual indentation
systemvm/patches/debian/config/opt/cloud/bin/passwd_server_ip.py:169:23: E251 unexpected spaces around keyword / parameter equals
systemvm/patches/debian/config/opt/cloud/bin/passwd_server_ip.py:169:25: E251 unexpected spaces around keyword / parameter equals
systemvm/patches/debian/config/opt/cloud/bin/passwd_server_ip.py:170:22: E251 unexpected spaces around keyword / parameter equals
systemvm/patches/debian/config/opt/cloud/bin/passwd_server_ip.py:170:24: E251 unexpected spaces around keyword / parameter equals
systemvm/patches/debian/config/opt/cloud/bin/update_config.py:112:1: E305 expected 2 blank lines after class or function definition, found 1
systemvm/patches/debian/config/opt/cloud/bin/vmdata.py:167:1: E305 expected 2 blank lines after class or function definition, found 1
~~~

### CODE REVIEW

**Comment by DaanHoogland** [comment]
thanks @resmo , good to see someone cares. provided the import changes are correct I see no issues so based on the code
LGTM

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by resmo** [comment]
there are a few important open PR conflicting with this cleanup. rebasing asap these are merged.

**Comment by wido** [comment]
Merge conflicts :(

Otherwise a LGTM from me, but can you fix these?

**Comment by rhtyd** [comment]
@resmo LGTM, is this ready for testing/merging, can you fix conflicts?

**Pull request closed without merging**
