### PR TITLE
Ovmsupport 3.2.1/3.3.x

### PR DESCRIPTION
**Pull request by snuf**
This is a plugin that puts in ovm3 support ranging from 3.3.1 to 3.3.2. Basic functionality is in here, advanced networking etc..

Snapshots only work when a VM is stopped now due to the semantics of OVM's raw image implementation (so snapshots should work on a storage level underneath the hypervisor *shrug*)

### CODE REVIEW

**Comment by snuf** [comment]
grrrrr

**Comment by snuf** [comment]
woops, was right initially.

**Comment by ghxandsky** [comment]
So good.

**Comment by bhaisaab** [comment]
@snuf too many merge conflicts if I merge from your branch to master branch. This PR is for merging your branch to the ovmsupport branch. Please go ahead and merge it yourself, rebase it against latest master and send a PR against master. Thanks!

**Comment by snuf** [comment]
@bhaisaab move this into https://github.com/apache/cloudstack/pull/113 which is a new request, and a bit more condensed.....

**Pull request closed without merging**
