### PR TITLE
Increase the length for parameters that expect a list of domain IDs.

### PR DESCRIPTION
**Pull request by GabrielBrascher**
### Description

This PR proposes setting a length for domain id parameters that allow passing a list of UUIDs separated by a comma. Allowing to run the API command in use-cases where there are many domain admins.

Currently when calling API command with multiple domain ids (for example `updateServiceOffering`) it leads to the following API error:
```
Error: (HTTP 431, error code 9999) Unable to execute API command updateserviceoffering due to invalid value.
Value greater than max allowed length 255 for param: domainIds"
```
I am targeting this implementation at 4.16.1.0 and considering it a bug due to the fact that we could not relly on the API to execute a few critical updates. 

Admins end up either calling multiple times the API or (:warning: don't go this way) doing DB changes.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [X] Trivial

### CODE REVIEW

**Comment by wido** [comment]
Aren't these calls also affected?

- https://cloudstack.apache.org/api/apidocs-4.16/apis/updateDiskOffering.html
- https://cloudstack.apache.org/api/apidocs-4.16/apis/updateNetworkOffering.html
- https://cloudstack.apache.org/api/apidocs-4.16/apis/updateBackupOffering.html
- https://cloudstack.apache.org/api/apidocs-4.16/apis/updateVPCOffering.html

They all have the 'domainid' parameter which probably needs to be updated as well.

These can all be assigned to multiple domains.

**Comment by GabrielBrascher** [comment]
@wido you are right.
This PR already added the proposed change to the following API commands:
-    https://cloudstack.apache.org/api/apidocs-4.16/apis/updateServiceOffering.html
-    https://cloudstack.apache.org/api/apidocs-4.16/apis/updateDiskOffering.html
-    https://cloudstack.apache.org/api/apidocs-4.16/apis/updateNetworkOffering.html
-    https://cloudstack.apache.org/api/apidocs-4.16/apis/updateBackupOffering.html
-    https://cloudstack.apache.org/api/apidocs-4.16/apis/updateVPCOffering.html

However, I did not add the parameter changes in:
-    https://cloudstack.apache.org/api/apidocs-4.16/apis/updateBackupOffering.html

I will update the PR adding for this call as well.
Thanks for double-checking!

**Comment by GabrielBrascher** [comment]
@wido just updating that [updateBackupOffering](https://cloudstack.apache.org/api/apidocs-4.16/apis/updateBackupOffering.html) does not have domain IDs; therefore, so it does not need changes there.

**Review by sureshanaparti — APPROVED** [review]
code LGTM

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
code LGTM

**Review by weizhouapache — APPROVED** [review]

**Comment by sureshanaparti** [comment]
> Trillian test result (tid-2656) Environment: kvm-centos7 (x2), Advanced Networking with Mgmt server 7 Total time taken: 32392 seconds Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr5763-t2656-kvm-centos7.zip Smoke tests completed. 90 look OK, 1 have errors Only failed tests results shown below:
> 
> Test	Result	Time (s)	Test File
> test_08_arping_in_ssvm	`Failure`	5.18	test_diagnostics.py

Test failure ^^^ is not related to the changes in this PR.

**Pull request merged**
