### PR TITLE
github-actions: fix ui build workflow

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

package-lock.json is not removed.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
UI build passed https://github.com/apache/cloudstack/actions/runs/4956024920/jobs/8866001691?pr=7522 cc @rohityadavcloud

**Review by weizhouapache — APPROVED** [review]
code lgtm

I wonder if we need to remove this file from code base if it is updated or generated during the building process (not only in github action, but also in packaging jobs, etc)

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
@weizhouapache we don't remove the lock file in our packaging jobs that's why packaging jobs pass.

**Comment by rohityadavcloud** [comment]
I've noticed between v14 and newer, the lock file format (version number) changes.

**Comment by weizhouapache** [comment]
> @weizhouapache we don't remove the lock file in our packaging jobs that's why packaging jobs pass.

@rohityadavcloud 
sorry I am confused. 

indeed we do not remove the lock file in debian/rules and packaging/centos8/cloud.spec
```
    cd ui && npm install && npm run build && cd ..
```
and it works.

why the file should be removed ?

**Pull request merged**
