### PR TITLE
[HEALTH] 4.17.2.0 RC3 Health Check, please don't merge this!

### PR DESCRIPTION
**Pull request by rohityadavcloud**

### CODE REVIEW

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@rohityadavcloud , did you merge this by accident?

**Comment by rohityadavcloud** [comment]
Nope @DaanHoogland this is the RC3 branch; I merged it to 4.17 following release process https://cwiki.apache.org/confluence/display/CLOUDSTACK/Release+Procedure after vote for RC3 passed.

**Pull request merged**
