### PR TITLE
CLOUDSTACK-10007 no isolationmethod check for basic zone

### PR DESCRIPTION
**Pull request by DaanHoogland**
in case of DirectPodBasedNetworkGuru

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan help

**Comment by DaanHoogland** [comment]
@blueorangutan test centos7 xenserver-65sp1

**Comment by mike-tutkowski** [comment]
I have tested this code in a Basic Zone with XenServer and it worked. Also, the code LGTM. Thanks, @DaanHoogland!

**Comment by mike-tutkowski** [comment]
test_01_create_system_vms_on_managed_storage (TestManagedSystemVMs.TestManagedSystemVMs) ... === TestName: test_01_create_system_vms_on_managed_storage | Status : SUCCESS ===
ok
test_02_failure_to_create_service_offering_with_customized_iops (TestManagedSystemVMs.TestManagedSystemVMs) ... === TestName: test_02_failure_to_create_service_offering_with_customized_iops | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 2 tests in 2041.553s

OK

**Comment by mike-tutkowski** [comment]
test_01_storage_migrate_root_and_data_disks (TestVMMigrationWithStorage.TestVMMigrationWithStorage) ... === TestName: test_01_storage_migrate_root_and_data_disks | Status : SUCCESS ===
ok
test_02_storage_migrate_root_and_data_disks (TestVMMigrationWithStorage.TestVMMigrationWithStorage) ... === TestName: test_02_storage_migrate_root_and_data_disks | Status : SUCCESS ===
ok
test_03_storage_migrate_root_and_data_disks_fail (TestVMMigrationWithStorage.TestVMMigrationWithStorage) ... === TestName: test_03_storage_migrate_root_and_data_disks_fail | Status : SUCCESS ===
ok
test_04_storage_migrate_root_disk_fails (TestVMMigrationWithStorage.TestVMMigrationWithStorage) ... === TestName: test_04_storage_migrate_root_disk_fails | Status : SUCCESS ===
ok
test_05_storage_migrate_data_disk_fails (TestVMMigrationWithStorage.TestVMMigrationWithStorage) ... === TestName: test_05_storage_migrate_data_disk_fails | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 5 tests in 2589.177s

OK

**Comment by mike-tutkowski** [comment]
test_01_take_VM_snapshot (TestVMSnapshots.TestVMSnapshots) ... === TestName: test_01_take_VM_snapshot | Status : SUCCESS ===
ok
test_02_take_VM_snapshot_with_data_disk (TestVMSnapshots.TestVMSnapshots) ... === TestName: test_02_take_VM_snapshot_with_data_disk | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 2 tests in 547.525s

OK

**Comment by mike-tutkowski** [comment]
test_00_check_template_cache (TestVolumes.TestVolumes) ... === TestName: test_00_check_template_cache | Status : SUCCESS ===
ok
Attach a volume to a stopped virtual machine, then start VM ... === TestName: test_01_attach_new_volume_to_stopped_VM | Status : SUCCESS ===
ok
Attach, detach, and attach volume to a running VM ... === TestName: test_02_attach_detach_attach_volume | Status : SUCCESS ===
ok
Attach volume to running VM, then reboot. ... === TestName: test_03_attached_volume_reboot_VM | Status : SUCCESS ===
ok
Detach volume from a running VM, then reboot. ... === TestName: test_04_detach_volume_reboot | Status : SUCCESS ===
ok
Detach volume from a stopped VM, then start. ... === TestName: test_05_detach_vol_stopped_VM_start | Status : SUCCESS ===
ok
Attach a volume to a stopped virtual machine, then start VM ... === TestName: test_06_attach_volume_to_stopped_VM | Status : SUCCESS ===
ok
Destroy and expunge VM with attached volume ... === TestName: test_07_destroy_expunge_VM_with_volume | Status : SUCCESS ===
ok
Delete volume that was attached to a VM and is detached now ... === TestName: test_08_delete_volume_was_attached | Status : SUCCESS ===
ok
Attach a data disk to a VM in one account and attach another data disk to a VM in another account ... === TestName: test_09_attach_volumes_multiple_accounts | Status : SUCCESS ===
ok
Attach more than one disk to a VM ... === TestName: test_10_attach_more_than_one_disk_to_VM | Status : SUCCESS ===
ok
test_11_template_from_volume (TestVolumes.TestVolumes) ... === TestName: test_11_template_from_volume | Status : SUCCESS ===
ok
test_12_resize_volume_on_running_vm (TestVolumes.TestVolumes) ... === TestName: test_12_resize_volume_on_running_vm | Status : SUCCESS ===
ok
test_13_resize_volume_on_stopped_vm (TestVolumes.TestVolumes) ... === TestName: test_13_resize_volume_on_stopped_vm | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 14 tests in 1365.057s

OK

**Comment by mike-tutkowski** [comment]
This run of TestVolumes.py is with XenServer resigning enabled:

test_00_check_template_cache (TestVolumes.TestVolumes) ... === TestName: test_00_check_template_cache | Status : SUCCESS ===
ok
Attach a volume to a stopped virtual machine, then start VM ... === TestName: test_01_attach_new_volume_to_stopped_VM | Status : SUCCESS ===
ok
Attach, detach, and attach volume to a running VM ... === TestName: test_02_attach_detach_attach_volume | Status : SUCCESS ===
ok
Attach volume to running VM, then reboot. ... === TestName: test_03_attached_volume_reboot_VM | Status : SUCCESS ===
ok
Detach volume from a running VM, then reboot. ... === TestName: test_04_detach_volume_reboot | Status : SUCCESS ===
ok
Detach volume from a stopped VM, then start. ... === TestName: test_05_detach_vol_stopped_VM_start | Status : SUCCESS ===
ok
Attach a volume to a stopped virtual machine, then start VM ... === TestName: test_06_attach_volume_to_stopped_VM | Status : SUCCESS ===
ok
Destroy and expunge VM with attached volume ... === TestName: test_07_destroy_expunge_VM_with_volume | Status : SUCCESS ===
ok
Delete volume that was attached to a VM and is detached now ... === TestName: test_08_delete_volume_was_attached | Status : SUCCESS ===
ok
Attach a data disk to a VM in one account and attach another data disk to a VM in another account ... === TestName: test_09_attach_volumes_multiple_accounts | Status : SUCCESS ===
ok
Attach more than one disk to a VM ... === TestName: test_10_attach_more_than_one_disk_to_VM | Status : SUCCESS ===
ok
test_11_template_from_volume (TestVolumes.TestVolumes) ... === TestName: test_11_template_from_volume | Status : SUCCESS ===
ok
test_12_resize_volume_on_running_vm (TestVolumes.TestVolumes) ... === TestName: test_12_resize_volume_on_running_vm | Status : SUCCESS ===
ok
test_13_resize_volume_on_stopped_vm (TestVolumes.TestVolumes) ... === TestName: test_13_resize_volume_on_stopped_vm | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 14 tests in 1444.825s

OK

**Comment by mike-tutkowski** [comment]
All three errors here were environmental. I later re-ran those tests successfully (also included below).

test_01_create_volume_snapshot_using_sf_snapshot (TestSnapshots.TestSnapshots) ... === TestName: test_01_create_volume_snapshot_using_sf_snapshot | Status : SUCCESS ===
ok
test_02_create_volume_snapshot_using_sf_volume (TestSnapshots.TestSnapshots) ... === TestName: test_02_create_volume_snapshot_using_sf_volume | Status : EXCEPTION ===
ERROR
test_03_create_volume_snapshot_using_sf_volume_and_sf_snapshot (TestSnapshots.TestSnapshots) ... === TestName: test_03_create_volume_snapshot_using_sf_volume_and_sf_snapshot | Status : EXCEPTION ===
ERROR
test_04_create_volume_snapshot_using_sf_snapshot_and_archiving (TestSnapshots.TestSnapshots) ... === TestName: test_04_create_volume_snapshot_using_sf_snapshot_and_archiving | Status : EXCEPTION ===
ERROR
test_05_create_volume_snapshot_using_sf_snapshot_and_revert_volume_to_snapshot (TestSnapshots.TestSnapshots) ... === TestName: test_05_create_volume_snapshot_using_sf_snapshot_and_revert_volume_to_snapshot | Status : SUCCESS ===
ok

test_02_create_volume_snapshot_using_sf_volume (TestSnapshots.TestSnapshots) ... === TestName: test_02_create_volume_snapshot_using_sf_volume | Status : SUCCESS ===
ok
test_03_create_volume_snapshot_using_sf_volume_and_sf_snapshot (TestSnapshots.TestSnapshots) ... === TestName: test_03_create_volume_snapshot_using_sf_volume_and_sf_snapshot | Status : SUCCESS ===
ok
test_04_create_volume_snapshot_using_sf_snapshot_and_archiving (TestSnapshots.TestSnapshots) ... === TestName: test_04_create_volume_snapshot_using_sf_snapshot_and_archiving | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 3 tests in 5391.933s

OK

**Comment by mike-tutkowski** [comment]
test_add_remove_host_with_solidfire_plugin_1 (TestAddRemoveHosts.TestAddRemoveHosts) ... === TestName: test_add_remove_host_with_solidfire_plugin_1 | Status : SUCCESS ===
ok
test_add_remove_host_with_solidfire_plugin_2 (TestAddRemoveHosts.TestAddRemoveHosts) ... === TestName: test_add_remove_host_with_solidfire_plugin_2 | Status : SUCCESS ===
ok
test_add_remove_host_with_solidfire_plugin_3 (TestAddRemoveHosts.TestAddRemoveHosts) ... === TestName: test_add_remove_host_with_solidfire_plugin_3 | Status : SUCCESS ===
ok
test_add_remove_host_with_solidfire_plugin_4 (TestAddRemoveHosts.TestAddRemoveHosts) ... === TestName: test_add_remove_host_with_solidfire_plugin_4 | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 4 tests in 2847.135s

OK

**Comment by mike-tutkowski** [comment]
I needed to run all managed-storage regression tests for the following PR: https://github.com/apache/cloudstack/pull/2081

In order to get an environment up and running to run those tests, I included this PR when testing that PR. As a result, the managed-storage regression tests whose results I included above were gathered when I ran those tests against code from https://github.com/apache/cloudstack/pull/2081 and this PR.

**Pull request merged**
