### PR TITLE
make sure vmware adapter detail for nic is passed during registering template

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR Fixes: #7864 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

#### How did you try to break this feature and the system with this change?

debugged in local UI against lab environment.
Note that this is a pure UI change but is dependend on the template being for vmware and thus can not be tested in the qa env (which is simulator only).

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan ui

**Comment by DaanHoogland** [comment]
@blueorangutan ui

**Comment by DaanHoogland** [comment]
@andrijapanicsb , low prio but you want this! ;)

**Review by shwstppr — APPROVED** [review]
Change at line 231 looks good. Rest seems refactoring

**Comment by DaanHoogland** [comment]
> Change at line 231 looks good. Rest seems refactoring

that's right @shwstppr , but the renaming of values to formvalues is because of a name clash that i encountered debugging. The fetchNicAdapterTypes() changes are pure refactoring.

**Review by rohityadavcloud — APPROVED** [review]
LGTM - didn't test it though

**Comment by rajujith** [comment]
@blueorangutan package

**Review by rajujith — APPROVED** [review]
LGTM. Verified that the NIC Adapter setting 'vmxnet3' input in the template registration form is retained in the template settings.

**Pull request merged**
