### PR TITLE
Load balancer configurations using HAProxy

### PR DESCRIPTION
**Pull request by ravening**
### Description

Ported from https://github.com/apache/cloudstack-primate/pull/778

This is the UI change needed for confgiuring load balancer
rules using haproxy and also adding ssl certificated to
load balancer rules

Load balancer configs are avaiable at two scopes.
one at the network level under "LB Configs" tab and
another under each load balancer rule and can be configured
by clicking on "Configuration" button.

The SSL certificates can be added only for load balancer
rules with ssl protocols

To apply global load balancing configurations, navigate to "Networks" -> LB Configs

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [X] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@ravening this is for 4.16?

**Comment by onitake** [comment]
This needs to merged together (or after) #4141 , so it should depend on that.

**Comment by ravening** [comment]
> @ravening this is for 4.16?

@DaanHoogland Wei might use this change along with his backend pr only. so i will close this once he updates the pr

**Comment by weizhouapache** [comment]
> > @ravening this is for 4.16?
> 
> @DaanHoogland Wei might use this change along with his backend pr only. so i will close this once he updates the pr

@ravening 
I have updated pr #4141 to include your changes.

**Comment by ravening** [comment]
> > > @ravening this is for 4.16?
> > 
> > 
> > @DaanHoogland Wei might use this change along with his backend pr only. so i will close this once he updates the pr
> 
> @ravening
> I have updated pr #4141 to include your changes.

Closing this pr

**Pull request closed without merging**
