### PR TITLE
UI: fix ui test errors

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes the UI test errors.

```
$ npm run test:unit

=============================== Coverage summary ===============================
Statements   : 5.54% ( 1322/23850 )
Branches     : 5.42% ( 636/11724 )
Functions    : 2.59% ( 189/7311 )
Lines        : 5.63% ( 1304/23143 )
================================================================================

Test Suites: 4 passed, 4 total
Tests:       175 passed, 175 total
Snapshots:   0 total
Time:        16.175s
Ran all test suites.

```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by rohityadavcloud** [comment]
@blueorangutan ui

**Comment by rohityadavcloud** [comment]
Other failures fixed, just one remaining @weizhouapache 
```
FAIL tests/unit/components/view/ActionButton.spec.js
  ● Components > View > ActionButton.vue › Watcher › handleShowBadge() › The handleShowBadge() is not called with an empty resource

    TypeError: object.hasOwnProperty is not a function

      273 |           }
      274 |         })
    > 275 |         const handleShowBadge = jest.spyOn(wrapper.vm, 'handleShowBadge')
          |                                      ^
      276 |         await wrapper.setProps({ resource: null })
      277 |
      278 |         expect(handleShowBadge).not.toBeCalled()

      at ModuleMockerClass.spyOn (node_modules/jest-mock/build/index.js:850:36)
      at Object.<anonymous> (tests/unit/components/view/ActionButton.spec.js:275:38)

  ● Components > View > ActionButton.vue › Watcher › handleShowBadge() › The handleShowBadge() is not called with a resource have containing id null

    TypeError: object.hasOwnProperty is not a function

      287 |           }
      288 |         })
    > 289 |         const handleShowBadge = jest.spyOn(wrapper.vm, 'handleShowBadge')
          |                                      ^
      290 |         await wrapper.setProps({ resource: { id: null } })
      291 |
      292 |         expect(handleShowBadge).not.toBeCalled()

      at ModuleMockerClass.spyOn (node_modules/jest-mock/build/index.js:850:36)
      at Object.<anonymous> (tests/unit/components/view/ActionButton.spec.js:289:38)

  ● Components > View > ActionButton.vue › Watcher › handleShowBadge() › The handleShowBadge() should be called with changed resource data

    TypeError: object.hasOwnProperty is not a function

      301 |           }
      302 |         })
    > 303 |         const handleShowBadge = jest.spyOn(wrapper.vm, 'handleShowBadge')
          |                                      ^
      304 |         await wrapper.setProps({
      305 |           resource: {
      306 |             id: 'test-resource-id-2'

      at ModuleMockerClass.spyOn (node_modules/jest-mock/build/index.js:850:36)
      at Object.<anonymous> (tests/unit/components/view/ActionButton.spec.js:303:38)


=============================== Coverage summary ===============================
Statements   : 5.7% ( 1373/24101 )
Branches     : 4.83% ( 646/13375 )
Functions    : 2.59% ( 189/7304 )
Lines        : 5.79% ( 1354/23392 )
================================================================================
Test Suites: 1 failed, 3 passed, 4 total
Tests:       3 failed, 172 passed, 175 total
Snapshots:   0 total
Time:        104.483s
```

**Comment by weizhouapache** [comment]
ubuntu 20.04 is tool old. The following succeeds on ubuntu 22.04.

```
FAIL tests/unit/components/view/ActionButton.spec.js
  ● Components > View > ActionButton.vue › Watcher › handleShowBadge() › The handleShowBadge() is not called with an empty resource
    TypeError: object.hasOwnProperty is not a function
      273 |           }
      274 |         })
    > 275 |         const handleShowBadge = jest.spyOn(wrapper.vm, 'handleShowBadge')
          |                                      ^
      276 |         await wrapper.setProps({ resource: null })
      277 |
      278 |         expect(handleShowBadge).not.toBeCalled()
      at ModuleMockerClass.spyOn (node_modules/jest-mock/build/index.js:850:36)
      at Object.<anonymous> (tests/unit/components/view/ActionButton.spec.js:275:38)
```

**Review by DaanHoogland — APPROVED** [review]

**Comment by DaanHoogland** [comment]
only github action and ui test changes, merging

**Pull request merged**
