### PR TITLE
Two fixes for RC3 by @mike-tutkowski

### PR DESCRIPTION
**Pull request by karuturi**
This PR is a rebase of PR #2147 by @mike-tutkowski 
The target branch is changed to master from the release branch.

### CODE REVIEW

**Comment by karuturi** [comment]
@borisstoyanov can you run tests on this PR?

**Comment by borisstoyanov** [comment]
Sure @karuturi 
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by karuturi** [comment]
Thanks @borisstoyanov. merging this now. Time for RC5 :)

**Pull request merged**
