### PR TITLE
server: fix host anti-affinity when start batch vms

### LINKED ISSUE #5527: Anti affinity Groups not work  sometimes ,  Start VM in batches
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
affinity Groups
~~~

##### CLOUDSTACK VERSION

~~~
CloudStack 4.15.0.0
~~~

##### OS / ENVIRONMENT

CloudStack 4.15.0.0
host  OS version: Ubuntu 20.04

##### SUMMARY

Start virtual machines in batches, anti affinity Groups not work sometimes

##### STEPS TO REPRODUCE

It doesn't happen every time

1.Two host in one cluster
2.add three VM to a anti-affinity group
3.VM in stopped state
4.start vm with WEB UI, Check three VM to start
5.Three VMs will start successful 

logs ：
          vm id : 158 159 160 
          host id:  3 9
job-5595: 
2021-09-29 09:35:14,379 DEBUG [o.a.c.a.HostAntiAffinityProcessor] (API-Job-Executor-31:ctx-ff549a9e job-5595 ctx-e1872415) (logid:ec8a48c2) Processing affinity group gumd-test for VM Id: 158
2021-09-29 09:35:14,382 DEBUG [o.a.c.a.HostAntiAffinityProcessor] (API-Job-Executor-31:ctx-ff549a9e job-5595 ctx-e1872415) (logid:ec8a48c2) Added host 3 to avoid set, since VM 159 is present on the host, in Stopped state but has reserved capacity
2021-09-29 09:35:14,383 DEBUG [o.a.c.a.HostAntiAffinityProcessor] (API-Job-Executor-31:ctx-ff549a9e job-5595 ctx-e1872415) (logid:ec8a48c2) Added host 9 to avoid set, since VM 160 is present on the host, in Stopped state but has reserved capacity

job-5598
2021-09-29 09:35:14,594 DEBUG [o.a.c.a.HostAntiAffinityProcessor] (API-Job-Executor-32:ctx-acdc74f8 job-5598 ctx-3ce8dd3b) (logid:1d2445d0) Processing affinity group gumd-test for VM Id: 159
2021-09-29 09:35:14,597 DEBUG [o.a.c.a.HostAntiAffinityProcessor] (API-Job-Executor-32:ctx-acdc74f8 job-5598 ctx-3ce8dd3b) (logid:1d2445d0) Added host 9 to avoid set, since VM 158 is present on the host, in Stopped state but has reserved capacity
2021-09-29 09:35:14,600 DEBUG [o.a.c.a.HostAntiAffinityProcessor] (API-Job-Executor-32:ctx-acdc74f8 job-5598 ctx-3ce8dd3b) (logid:1d2445d0) Added host 9 to avoid set, since VM 160 is present on the host, in Stopped state but has reserved capacity

job-5592
2021-09-29 09:35:14,498 DEBUG [o.a.c.a.HostAntiAffinityProcessor] (API-Job-Executor-30:ctx-307add2b job-5592 ctx-0802d14f) (logid:c430fdd5) Processing affinity group gumd-test for VM Id: 160
2021-09-29 09:35:14,500 DEBUG [o.a.c.a.HostAntiAffinityProcessor] (API-Job-Executor-30:ctx-307add2b job-5592 ctx-0802d14f) (logid:c430fdd5) Added host 9 to avoid set, since VM 158 is present on the host, in Stopped state but has reserved capacity
2021-09-29 09:35:14,502 DEBUG [o.a.c.a.HostAntiAffinityProcessor] (API-Job-Executor-30:ctx-307add2b job-5592 ctx-0802d14f) (logid:c430fdd5) Added host 3 to avoid set, since VM 159 is present on the host, in Stopped state but has reserved capacity

~~~

~~~

##### EXPECTED RESULTS

~~~
Two VMs start success , one VM start failed
~~~

##### ACTUAL RESULTS

~~~
Three VMs start success 
~~~

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #5527 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Review by nvazquez — CHANGES_REQUESTED** [review]
Manually tested on KVM with 2 hosts:

Success cases:
- Create anti-affinity group
- Attempt deploying 3 VMs assigning them to anti-affinity group -> RESULT: first 2 VMs running one on each host, 3rd deployment fails
- Stop the 2 running VMs
- Deploy VM without start, assigning it to the anti-affinity group
- Start 3 VMs in batch -> RESULT: 2 VMs running on different hosts (screenshot)
Screen Shot 2022-02-17 at 22 06 56

Failing case:
- 2 VMs running one on each host
- Attemp to start the third VM on a specific host (different form the last_host_id) -> RESULT 3 VMs running (screenshot)
Screen Shot 2022-02-17 at 22 12 07

**Comment by weizhouapache** [comment]
> Manually tested on KVM with 2 hosts:
> 
> Success cases:
> 
> * Create anti-affinity group
> * Attempt deploying 3 VMs assigning them to anti-affinity group -> RESULT: first 2 VMs running one on each host, 3rd deployment fails
> * Stop the 2 running VMs
> * Deploy VM without start, assigning it to the anti-affinity group
> * Start 3 VMs in batch -> RESULT: 2 VMs running on different hosts (screenshot)
> 
> Screen Shot 2022-02-17 at 22 06 56
> 
> Failing case:
> 
> * 2 VMs running one on each host
> * Attemp to start the third VM on a specific host (different form the last_host_id) -> RESULT 3 VMs running (screenshot)
> 
> Screen Shot 2022-02-17 at 22 12 07

@nvazquez 
thanks for testing.

the case seems to be expected behaviour. see below

https://github.com/apache/cloudstack/blob/9eefc76fc5ef9abf3d74a5cc6c528ca404c707fd/server/src/main/java/com/cloud/deploy/DeploymentPlanningManagerImpl.java#L297-L301

**Comment by DaanHoogland** [comment]
> 
> @nvazquez thanks for testing.
> 
> the case seems to be expected behaviour. see below
> 
> https://github.com/apache/cloudstack/blob/9eefc76fc5ef9abf3d74a5cc6c528ca404c707fd/server/src/main/java/com/cloud/deploy/DeploymentPlanningManagerImpl.java#L297-L301

@weizhouapache @nvazquez , this does not seem like desired behaviour, unless we decide to allow it (for root admin only). I think a user should remove a VM from the anti-affinity group if they want it to run anyway.

code changes looks good, btw.

**Comment by nvazquez** [comment]
Thanks @weizhouapache @DaanHoogland - looks good then

**Comment by nvazquez** [comment]
@blueorangutan test

**Review by nvazquez — APPROVED** [review]

**Review by DaanHoogland — APPROVED** [review]

**Pull request merged**
