### PR TITLE
cks: fix logging exception on create cluster

### PR DESCRIPTION
**Pull request by shwstppr**
## Description
Fix for exception in logging while creating k8s cluster

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
@blueorangutan test

**Review by Pearl1594 — APPROVED** [review]

**Review by davidjumani — APPROVED** [review]
Tested! LGTM!

**Comment by rhtyd** [comment]
Only logging fix, merging based on Travis

**Pull request merged**
