### PR TITLE
Allow enable the Java remote Debug for CloudStack Agent

### PR DESCRIPTION
**Pull request by GabrielBrascher**
The idea is to create a property in /etc/defaults/cloudstack-agent that can be enabled/disabled (uncommented/commented) to control the enabling of Java remote debug in CloudStack's JVM.

This PR is analogous with #2535, which created an easy way to enable Java remote Debug on the CloudStack management; however, this PR creates a variable (JAVA_DEBUG) that helps on enabling remote debug in the CloudStack agent service.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
Testing
- [ ] I have added tests to cover my changes.
- [ ] All relevant new and existing integration tests have passed.
- [ ] A full integration testsuite with all test that can run on my environment has passed.

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rafaelweingartner** [comment]
@rhtyd do you know why the debian package is failing with @blueorangutan ?

**Comment by rhtyd** [comment]
@rafaelweingartner yes there is an issue with the ubuntu docker container, and a case in one of the unit tests that causes NPE. I've fixed that now, future packaging jobs will work.

**Comment by rafaelweingartner** [comment]
The errors do not seem do be related to changes introduced here.

**Pull request merged**
