### PR TITLE
Allow volume migrations in ScaleIO within and across ScaleIO storage clusters

### PR DESCRIPTION
**Pull request by harikrishna-patnala**
### Description
This feature allows the storage migration for ScaleIO volumes between the ScaleIO storage pools of the same and different ScaleIO storage clusters. Previously this operation was blocked and now we are allowing it from API/UI.

The volume migration within the same storage cluster is performed using ScaleIO’s native V-Tree migration operation where the volume will be live migrated to another storage pool. The volume migration across the different storage cluster is performed using libvirt’s live blockcopy operation which will first copy the volume to the destination storage pool and after a successful copy, the source volume will be deleted. Upon any failures during the block copy, source volume will remain to continue and other blockcopy operations will be reverted.

A document PR is added here https://github.com/apache/cloudstack-documentation/pull/321

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [x] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test keepEnv

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test matrix

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by rohityadavcloud** [comment]
@harikrishna-patnala @borisstoyanov should this bugfix/improvement be targeted for 4.18 since there are no DB changes and essentially you're addressing a limitation of the scaleio storage plugin?

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test matrix

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by borisstoyanov** [comment]
@blueorangutan test centos8

> [SF] Trillian test result (tid-6761) Environment: vmware-67u3 (x2), Advanced Networking with Mgmt server r8 Total time taken: 56589 seconds Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr7408-t6761-vmware-67u3.zip Smoke tests completed. 107 look OK, 1 have errors, 0 did not run Only failed and skipped tests results shown below:
> 
> Test	Result	Time (s)	Test File
> test_01_deploy_vm_on_specific_host	`Error`	18.73	test_vm_deployment_planner.py
> test_02_deploy_vm_on_specific_cluster	`Error`	3605.89	test_vm_deployment_planner.py
> test_03_deploy_vm_on_specific_pod	`Error`	40.36	test_vm_deployment_planner.py
> test_04_deploy_vm_on_host_override_pod_and_cluster	`Error`	3604.32	test_vm_deployment_planner.py
> test_05_deploy_vm_on_cluster_override_pod	`Error`	11.55	test_vm_deployment_planner.py

Manually passed

=== TestName: test_01_deploy_vm_on_specific_host | Status : SUCCESS ===

=== TestName: test_02_deploy_vm_on_specific_cluster | Status : SUCCESS ===

=== TestName: test_03_deploy_vm_on_specific_pod | Status : SUCCESS ===

=== TestName: test_04_deploy_vm_on_host_override_pod_and_cluster | Status : SUCCESS ===

=== TestName: test_05_deploy_vm_on_cluster_override_pod | Status : SUCCESS ===

**Comment by borisstoyanov** [comment]
> [SF] Trillian test result (tid-6765) Environment: kvm-centos7 (x2), Advanced Networking with Mgmt server 7 Total time taken: 46162 seconds Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr7408-t6765-kvm-centos7.zip Smoke tests completed. 107 look OK, 1 have errors, 0 did not run Only failed and skipped tests results shown below:
> 
> Test	Result	Time (s)	Test File
> test_01_migrate_VM_and_root_volume	`Error`	83.95	test_vm_life_cycle.py
> test_02_migrate_VM_with_two_data_disks	`Error`	52.30	test_vm_life_cycle.py

This has been seen in other 4.18 PRs as well, it's not related to the changes of this PR

**Review by borisstoyanov — APPROVED** [review]
LGTM, manually tested.

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Pull request merged**
