### PR TITLE
utils: fix invalid JSESSIONID cookie in https setup

### LINKED ISSUE #9848: 4.19.1.2. -> Unable to login with non 2FA users. Error: "JSESSIONID is invalid."
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
LOGIN, MANAGEMENT
~~~

##### CLOUDSTACK VERSION
~~~
4.19.1.2
~~~

##### SUMMARY
After the update to version `4.19.1.2`. Users that don't have 2FA enabled are unable to login and get a `401 UNAUTHORIZED` answer from the system. In the logs I can see that an error `JSESSIONID is invalid.` gets logged multiple times.

__We have no special login methods (like OAuth, SAML) enabled and 2FA is also not mandatory but enabled.__

This was tested with different clients with and without cache. All clients produced the same error.

##### STEPS TO REPRODUCE
~~~
1. Update to version 4.19.1.2
2. Try to login with a non 2FA user
3. Get 401 UNAUTHORIZED error

4. Downgrade to 4.19.1.1
5. Try to login with a non 2FA user
6. Login works fine
~~~

##### EXPECTED RESULTS

~~~
Login with non 2FA users does work.
~~~

##### ACTUAL RESULTS
~~~
Login with non 2FA users doesn't work. (401 UNAUTHORIZED)
~~~
---
We've downgraded to version 4.19.1.1 for now.

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #9848 

When enable.secure.session.cookie is set to true, use cannot login with error
```
    2024-10-25T09:03:33,898 DEBUG [c.c.u.HttpUtils] (qtp384617262-21:[ctx-a3ee3670]) (logid:7c5bfd8d) jsessionidFromCookie = node017ygldpe44nub1frmqafsj0qmc18
    2024-10-25T09:03:33,898 DEBUG [c.c.u.HttpUtils] (qtp384617262-21:[ctx-a3ee3670]) (logid:7c5bfd8d) session.getId() = node017ygldpe44nub1frmqafsj0qmc18
    2024-10-25T09:03:33,898 ERROR [c.c.u.HttpUtils] (qtp384617262-21:[ctx-a3ee3670]) (logid:7c5bfd8d) JSESSIONID from cookie is invalid.
```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [x] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
another option could be removing the check completely

```
        final String jsessionidFromCookie = HttpUtils.findCookie(cookies, "JSESSIONID");
        if (jsessionidFromCookie == null
                || !(jsessionidFromCookie.startsWith(session.getId() + '.'))) {
            s_logger.error("JSESSIONID from cookie is invalid.");
            return false;
        }
```

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
this does not fix a blocker issue, but fixes a regression issue (#9848) of previous security release.
maybe we should add it to the next minor releases.
cc @rohityadavcloud @DaanHoogland @borisstoyanov @GutoVeronezi

**Comment by JoaoJandre** [comment]
> @weizhouapache , a regression should be a BLOCKER for a release, right? especially when it is a new one. cc @rohityadavcloud @GutoVeronezi @JoaoJandre @borisstoyanov

I agree with @DaanHoogland , we should look to getting this merged into 4.20

**Review by sureshanaparti — APPROVED** [review]

**Comment by dataCobra** [comment]
Hello,

is there a reason this PR didn't get added to the new minor release?

I think this is an issue is a blocker and not critical.
We are unable to update to any newer version as long as this PR is not added to a release.

Also the issue got marked as blocker but the PR is not.

**Pull request merged**
