### PR TITLE
api: Fix reset configuration

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

This PR fixes issue with resetConfiguration for settings defined in Config.java

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### How Has This Been Tested?
Before Fix:
image

Post Fix:
Successfully able to reset config

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
quite frankly, I think this is due to technical debt and we should not fix this but phase those configs defined in Config.java out.

**Comment by weizhouapache** [comment]
> quite frankly, I think this is due to technical debt and we should not fix this but phase those configs defined in Config.java out.

@DaanHoogland 
reset configuration is already supported in 4.16.1 (see #4230). this is a bug fix .

**Review by weizhouapache — APPROVED** [review]
tested ok.

**Comment by DaanHoogland** [comment]
> > quite frankly, I think this is due to technical debt and we should not fix this but phase those configs defined in Config.java out.
> 
> @DaanHoogland reset configuration is already supported in 4.16.1 (see #4230). this is a bug fix .

It is supported for modern ConfigKey entries, this is extra. I think any Config that needs resetting should be modernised.

**Review by nvazquez — APPROVED** [review]
Code LGTM

**Comment by weizhouapache** [comment]
the test failure is not related to this PR. 
merging

**Pull request merged**
