### PR TITLE
SystemVM template changes - updated debian version & other changes

### PR DESCRIPTION
**Pull request by sureshanaparti**
### Description

This PR updates SystemVM template debian version to 12.7.0 and other changes below.

- Update the module dependencies explicitly (`depmod -a`) for VMware - resolves the iptables and nfs mount issues observed in SSVM & CCPVM.

```
root@v-1-VM:~# iptables-save
iptables-save/1.8.9 (nf_tables) Failed to initialize nft: Protocol not supported
root@v-1-VM:~#
```

```
root@s-2-VM:~# tail -f /var/log/cloud.log
...
2024-09-02T14:19:44,456 WARN  [storage.resource.NfsSecondaryStorageResource] (agentRequest-Handler-4:[]) Execution of process [4162] for command [mount -t nfs -o soft,timeo=133,retrans=2147483647,tcp,acdirmax=0,acdirmin=0 10.0.x.x:/acs/secondary/ref-trl-7233-v-Mol8-suresh-anaparti/ref-trl-7233-v-Mol8-suresh-anaparti-sec1 /mnt/SecStorage/b9cbaeeb-495b-388b-b49d-4c122d9310d8 ] failed.
2024-09-02T14:19:44,457 WARN  [storage.resource.NfsSecondaryStorageResource] (agentRequest-Handler-4:[]) Process [4162] for command [mount -t nfs -o soft,timeo=133,retrans=2147483647,tcp,acdirmax=0,acdirmin=0 10.0.x.x:/acs/secondary/ref-trl-7233-v-Mol8-suresh-anaparti/ref-trl-7233-v-Mol8-suresh-anaparti-sec1 /mnt/SecStorage/b9cbaeeb-495b-388b-b49d-4c122d9310d8 ] encountered the error: [mount.nfs: No such device].
2024-09-02T14:19:44,457 ERROR [storage.resource.NfsSecondaryStorageResource] (agentRequest-Handler-4:[]) Unable to mount 10.0.x.x:/acs/secondary/ref-trl-7233-v-Mol8-suresh-anaparti/ref-trl-7233-v-Mol8-suresh-anaparti-sec1 at /mnt/SecStorage/b9cbaeeb-495b-388b-b49d-4c122d9310d8 due to mount.nfs: No such device
2024-09-02T14:19:44,459 WARN  [cloud.agent.Agent] (agentRequest-Handler-4:[]) Caught: com.cloud.utils.exception.CloudRuntimeException: Failed to get root directory from secondary storage URL [nfs://10.0.x.x/acs/secondary/ref-trl-7233-v-Mol8-suresh-anaparti/ref-trl-7233-v-Mol8-suresh-anaparti-sec1], using NFS version [null], due to [Unable to mount 10.0.x.x:/acs/secondary/ref-trl-7233-v-Mol8-suresh-anaparti/ref-trl-7233-v-Mol8-suresh-anaparti-sec1 at /mnt/SecStorage/b9cbaeeb-495b-388b-b49d-4c122d9310d8 due to mount.nfs: No such device].
	at org.apache.cloudstack.storage.resource.NfsSecondaryStorageResource.getRootDir(NfsSecondaryStorageResource.java:2674)
	at org.apache.cloudstack.storage.resource.NfsSecondaryStorageResource.execute(NfsSecondaryStorageResource.java:2406)
	at org.apache.cloudstack.storage.resource.NfsSecondaryStorageResource.executeRequest(NfsSecondaryStorageResource.java:297)
	at com.cloud.storage.resource.PremiumSecondaryStorageResource.defaultAction(PremiumSecondaryStorageResource.java:62)
	at com.cloud.storage.resource.PremiumSecondaryStorageResource.executeRequest(PremiumSecondaryStorageResource.java:58)
	at com.cloud.agent.Agent.processRequest(Agent.java:679)
	at com.cloud.agent.Agent$AgentRequestHandler.doTask(Agent.java:1092)
	at com.cloud.utils.nio.Task.call(Task.java:83)
	at com.cloud.utils.nio.Task.call(Task.java:29)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.cloud.utils.exception.CloudRuntimeException: Unable to mount 10.0.x.x:/acs/secondary/ref-trl-7233-v-Mol8-suresh-anaparti/ref-trl-7233-v-Mol8-suresh-anaparti-sec1 at /mnt/SecStorage/b9cbaeeb-495b-388b-b49d-4c122d9310d8 due to mount.nfs: No such device
	at org.apache.cloudstack.storage.resource.NfsSecondaryStorageResource.attemptMount(NfsSecondaryStorageResource.java:3080)
	at org.apache.cloudstack.storage.resource.NfsSecondaryStorageResource.mount(NfsSecondaryStorageResource.java:3031)
	at org.apache.cloudstack.storage.resource.NfsSecondaryStorageResource.mountUri(NfsSecondaryStorageResource.java:3019)
	at org.apache.cloudstack.storage.resource.NfsSecondaryStorageResource.getRootDir(NfsSecondaryStorageResource.java:2670)
	... 12 more
```

- VMware hardware version updated to 13 - compatible with latest VMware version supported (https://docs.vmware.com/en/VMware-vSphere/8.0/vsphere-vm-administration/GUID-64D4B1C9-CD5D-4C68-8B50-585F6A87EBA0.html)

- Updated grub config with `fsck.mode=force fsck.repair=yes` - resolves the file system read-only issue observed in VRs.

systemvm-filesystem-readonly-issue

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [x] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
Packaging isn't required as changes are only in systemvmtemplate codebase. I've kicked Jenkins builds, which should be available shortly at https://build.yadav.cloud/systemvm/

**Comment by rohityadavcloud** [comment]
build OK

**Review by weizhouapache — APPROVED** [review]
tested the new systemvm template on ubuntu24 and vmware80u3 manually

 [#9470 ](https://github.com/apache/cloudstack/pull/9470#issuecomment-2326353288) shows that smoke tests worked with the new systemvm template

**Comment by rohityadavcloud** [comment]
Merged based on 2lgtms and manual build/tests.

**Pull request merged**
