### PR TITLE
server: honor listall param for listiso api

### LINKED ISSUE #8315: List ISO doesn't respect listall=true
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API, ISO
~~~

##### CLOUDSTACK VERSION

~~~
4.18, 4.19 (main)
~~~

##### SUMMARY

Cloudstack Doesn't list the iso when the `listall=true` is passes.

##### STEPS TO REPRODUCE

1. list ISOs using the following command, nothing is returned (or some ISOs are returned)
```
(localcloud)  > list isos
(localcloud)  >
```
2. pass `listall=true` to the previous list ISOs command, the same result is returned.
```
(localcloud)  > list isos listall=true
(localcloud)  >
```
3. remove `listall=true` and add `domainid`, you would get the ISOs:
```
(localcloud)  > list isos domainid=bb55b9e8-8e05-11ee-89aa-1e002100337e filter=name,id
{
  "count": 1,
  "iso": [
    {
      "id": "98efda2e-c4a1-4bd4-afe3-ab4290b81a92",
      "name": "xs-tools.iso"
    }
  ]
}
(localcloud)  >
```

##### EXPECTED RESULTS

~~~
CloudStack lists all the ISOs.
~~~

##### ACTUAL RESULTS

~~~
CloudStack lists nothing.
~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #8315

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Review by vishesh92 — APPROVED** [review]
lgtm

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by shwstppr** [comment]
@blueorangutan test

**Comment by shwstppr** [comment]
`listIsos` now return all ISOs when `listall` is passed,

```
(local) 🐱 > list isos filter=id,name,ispublic,domainid
{
  "count": 3,
  "iso": [
    {
      "domainid": "8da34656-08a3-11ef-9779-1e00a7000c5f",
      "id": "79681074-a7bd-4434-befd-e7c5ad728ee7",
      "ispublic": false,
      "name": "test1"
    },
    {
      "domainid": "8da34656-08a3-11ef-9779-1e00a7000c5f",
      "id": "fdeb66bc-57ac-491d-b4d8-c6a2545e064c",
      "ispublic": false,
      "name": "test1-dd"
    },
    {
      "domainid": "8da34656-08a3-11ef-9779-1e00a7000c5f",
      "id": "77c5f629-4e8c-4b04-8fa2-5b08e4a4d8d7",
      "ispublic": false,
      "name": "ds"
    }
  ]
}
(local) 🐱 > list isos filter=id,name,ispublic,domainid listall=true
{
  "count": 9,
  "iso": [
    {
      "domainid": "8da34656-08a3-11ef-9779-1e00a7000c5f",
      "id": "6c519636-3b2f-419c-b5bb-baac2c42ee5d",
      "ispublic": true,
      "name": "vmware-tools.iso"
    },
    {
      "domainid": "8da34656-08a3-11ef-9779-1e00a7000c5f",
      "id": "afa5ca21-6bd1-4682-88bc-c0956606250e",
      "ispublic": true,
      "name": "xs-tools.iso"
    },
    {
      "domainid": "8da34656-08a3-11ef-9779-1e00a7000c5f",
      "id": "aa621e5c-0689-412f-8b43-5976acdb404e",
      "ispublic": true,
      "name": "v1.26.0-Kubernetes-Binaries-ISO"
    },
    {
      "domainid": "8da34656-08a3-11ef-9779-1e00a7000c5f",
      "id": "79681074-a7bd-4434-befd-e7c5ad728ee7",
      "ispublic": false,
      "name": "test1"
    },
    {
      "domainid": "8da34656-08a3-11ef-9779-1e00a7000c5f",
      "id": "fdeb66bc-57ac-491d-b4d8-c6a2545e064c",
      "ispublic": false,
      "name": "test1-dd"
    },
    {
      "domainid": "8da34656-08a3-11ef-9779-1e00a7000c5f",
      "id": "77c5f629-4e8c-4b04-8fa2-5b08e4a4d8d7",
      "ispublic": false,
      "name": "ds"
    },
    {
      "domainid": "8da34656-08a3-11ef-9779-1e00a7000c5f",
      "id": "0bb30117-d53a-45e8-b2f5-65c17e635ff1",
      "ispublic": true,
      "name": "v1.24.0-Kubernetes-Binaries-ISO"
    },
    {
      "domainid": "8da34656-08a3-11ef-9779-1e00a7000c5f",
      "id": "969111e5-c6f9-4d46-822f-31c7700ff4d3",
      "ispublic": true,
      "name": "v1.24.0-Kubernetes-Binaries-ISO"
    },
    {
      "domainid": "db8c37e6-1e90-409b-addb-f1d8a9f77ce2",
      "id": "ff67dfbe-1b2b-4dd2-9c7a-309d14a5fc37",
      "ispublic": true,
      "name": "test-domain-iso"
    }
  ]
}
```

**Pull request merged**
