### PR TITLE
tool to aid db comaprision for upgrade testing

### PR DESCRIPTION
**Pull request by shwetaag**
What this tool is capable to do is

1.	Compare all the tables schema between upgraded setup and fresh install setup  and find if there is any schema difference between any tables
2.	Compare global configuration between upgraded and fresh install setup and find out if there is any difference between the two on following fields
	a.	Value
	b.	Scope
	c.	Description
	d.	Component
	e.	Category

### CODE REVIEW

**Comment by sanju1010** [comment]
I am taking this patch. LGTM

**Comment by agneya2001** [comment]
It appears that some functionality still needs to be completed.

**Comment by terbolous** [comment]
Shouldn't the files have licensing information in them?

**Comment by karuturi** [comment]
@agneya2001 some functionality like?

**Comment by shwetaag** [comment]
@agneya2001  this is version 1. 
I know enhancement are possible .
Like db comparison based on versions but that will come in next version

**Comment by agneya2001** [comment]
Was thinking of more of a script with a wizard interface, instead of bunch of scripts, that guides the user during upgrade.
Some suggestions:
A way to fix mismatched configuration like prompt user with missing config and accept values ?
On another side, if this kind of functionality is integrated with upgrade itself, that warns user about changed configs after upgrades etc.

**Comment by bhaisaab** [comment]
Was this merge on master?

**Comment by agneya2001** [comment]
Yes this was committed.

**Pull request closed without merging**
