### PR TITLE
UI - Add storage name to delete primary/secondary storage dialog

### PR DESCRIPTION
**Pull request by utchoang**
### Description

Fixes https://github.com/apache/cloudstack/issues/5344

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### Screenshots (if appropriate):
image
image

### CODE REVIEW

**Comment by utchoang** [comment]
@blueorangutan ui

**Review by nvazquez — COMMENTED** [review]
LGTM. Tested the changes and works fine, thanks @utchoang 

As an improvement, at least personally, I would prefer to see the pool name in the title and not as a field in the form. Something like:
image

**Comment by utchoang** [comment]
@nvazquez The problem is that the case where the storage name is too long will be a break into a new line. Do you feel it's okay?
image

**Comment by davidjumani** [comment]
@utchoang If thats the case, can it be added in the warning message, with just the name in bold ?

**Comment by utchoang** [comment]
@davidjumani Changed!
image
image

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by rhtyd** [comment]
I think just displaying the name is enough, without the key "Name: "
@blueorangutan ui

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
Tested OK - merging based on Nicolas and my LGTM.

**Pull request merged**
