### PR TITLE
server: fix resource count during assign volume

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

ResourceType.volume stores the count of the volume and not the size so increment decrement should be just 1 when assigning a volume to a different account.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
> ResourceType.volume stores the count of the volume and not the size so increment decrement should be just 1 when assigning a volume to a different account.

sounds like a bug. shouldn't the size be taken into account?

**Comment by shwstppr** [comment]
> > ResourceType.volume stores the count of the volume and not the size so increment decrement should be just 1 when assigning a volume to a different account.
> 
> sounds like a bug. shouldn't the size be taken into account?
@DaanHoogland 
As per my understanding we use ResourceType.volume for count of the volumes and ResourceType.primary_storage for size of the volume (incremented/decremented in the subsequent lines).

**Comment by DaanHoogland** [comment]
> > > ResourceType.volume stores the count of the volume and not the size so increment decrement should be just 1 when assigning a volume to a different account.
> > 
> > sounds like a bug. shouldn't the size be taken into account?
> 
> @DaanHoogland As per my understanding we use ResourceType.volume for count of the volumes and ResourceType.primary_storage for size of the volume (incremented/decremented in the subsequent lines).

Yes, I think you are right, my bad.

**Review by JoaoJandre — APPROVED** [review]
CLGTM, I did a quick check on the rest of the code and the resourcetype.volume seems to be the volume count indeed.
Did not test it.

**Comment by shwstppr** [comment]
@blueorangutan test

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by shwstppr** [comment]
Test results from backend,
```
23:22:55 Smoke tests completed. 108 look OK, 1 have errors, 0 did not run
23:22:55 Only failed and skipped tests results shown below:
23:22:55 
23:22:55 
23:22:55 Test | Result | Time (s) | Test File
23:22:55 --- | --- | --- | ---
23:22:55 test_08_migrate_vm | `Error` | 45.95 | test_vm_life_cycle.py
```

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Comment by shwstppr** [comment]
Forgot to mention, verified that failures were unrelated

**Pull request merged**
