### PR TITLE
[4.20] VR: fix issue if userdata is binary data

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes the issue that VM cannot start with binary userdata. This is a regression of #8497 

Steps to reproduce the issue and verify the fix

1. create a userdata with content below
cloud-init supports gzip compress userdata. for example
```
$ echo "Apache CloudStack" |gzip |base64 -w0
H4sIAAAAAAAAA3MsSEzOSFVwzskvTQkuSUzO5gIAxXcOkxIAAAA=
```

3. deploy a vm with the userdata, it failed
```
2024-03-04T11:13:27,400 DEBUG [c.c.a.t.Request] (AgentManager-Handler-7:[]) (logid:) Seq 1-8288593639198687341: 
Processing:  { Ans: , MgmtId: 167781234, via: 1, Ver: v1, Flags: 10, [{"com.cloud.agent.api.routing.GroupAnswer":{"results":
["null - success: Creating file in VR, with ip: 169.254.52.151, file: vm_password.json.5f0a36da-6fa7-48e4-8aae-
dcc8923fc42d","null - success: "],"result":"true","wait":"0","bypassHostMaintenance":"false"}},
{"com.cloud.agent.api.routing.GroupAnswer":{"results":["null - success: Creating file in VR, with ip: 169.254.52.151, file: 
vm_metadata.json.53c05bda-dc05-49df-b548-f517ae0fa546","null - failed: Traceback (most recent call last):  File 
"/opt/cloud/bin/update_config.py", line 147, in <module>    process_file()  File "/opt/cloud/bin/update_config.py", line 57, in 
process_file    finish_config()  File "/opt/cloud/bin/update_config.py", line 42, in finish_config    returncode = 
configure.main(sys.argv)                 ^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/cloud/bin/configure.py", line 1413, in main    
execDatabag(json_type, databag_map)  File "/opt/cloud/bin/configure.py", line 1400, in execDatabag    executor.process()  File 
"/opt/cloud/bin/configure.py", line 625, in process    self.__createfile(ip, folder, file, data)  File "/opt/cloud/bin/configure.py", line 
652, in __createfile    fh.write(data.decode())             ^^^^^^^^^^^^^UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in 
position 1: invalid start byte"],"result":"false","wait":"0","bypassHostMaintenance":"false"}}] }
```

4. apply this PR, vm is started successfully
5. check the userdata in vm
image

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [x] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by weizhouapache** [comment]
@blueorangutan test matrix

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan alma9 kvm-alma9

**Comment by weizhouapache** [comment]
@blueorangutan test alma9 kvm-alma9

**Comment by weizhouapache** [comment]
This fixes the issue that CAPC cannot create kubernetes cluster on 4.20/main

cc @rohityadavcloud

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@DaanHoogland 
will you test this pr ? the PR description might help

**Comment by DaanHoogland** [comment]
> @DaanHoogland will you test this pr ? the PR description might help

will find time... (as if that would be a promise ;)

**Comment by weizhouapache** [comment]
> > @DaanHoogland will you test this pr ? the PR description might help
> 
> will find time... (as if that would be a promise ;)

ah ha, I consider it as a promise. thanks buddy @DaanHoogland

**Comment by DaanHoogland** [comment]
@blueorangutan test alma9 kvm-alma9

**Comment by DaanHoogland** [comment]
just noticed I didn't report back here; tests ok:
image
used blApache to make sure nothing fishy was going on there ;)

**Comment by weizhouapache** [comment]
> just noticed I didn't report back here; tests ok:
> image
> used blApache to make sure nothing fishy was going on there ;)
> 

Great, thanks @DaanHoogland  !

**Review by vishesh92 — APPROVED** [review]
clgtm. didn't test.

**Pull request merged**
