### PR TITLE
Migrate VR codebase from Python2 to Python3

### PR DESCRIPTION
**Pull request by GabrielBrascher**
### Description

Considering the Python2 end of life we must migrate the VR's codebase to Python3.

This PR covers partially issue #3195. Additionally, this PR is a joint of the work done in #3730 and #4727.

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
ATM this is a mix of python2 and python3 during the travis run and though I tried to implement it according to their spec, I had to put a question to them concerning a python not being found.
I'll add details and/or resolution later

**Comment by GabrielBrascher** [comment]
@rhtyd I am doing some tests but it still need to cover more networks. I would appreciate any help testing it on environment with advanced networks + VPCs. I am testing at first with advacned networks + SG.

**Comment by DaanHoogland** [comment]
@GabrielBrascher , I'm on vacation since tomorrow ;) I will help you with testing this when I come back.

**Comment by nvazquez** [comment]
Hi @DaanHoogland @GabrielBrascher can you please resolve conflicts?

**Comment by rhtyd** [comment]
Ping @GabrielBrascher any update on this should we target this for 4.17 instead?

**Comment by rhtyd** [comment]
On second thought and after reviewing the changes, the risks to VR maybe huge so lets target this for 4.17.

**Comment by GabrielBrascher** [comment]
@rhtyd sorry for the delay here. We might need to postpone it to 4.17 indeed.

One of the biggest issues I am having is the testing, it can work great with my test environment (Advanced + SG, or basic network) but someone using a specific advanced network + VPC/VPN, etc could see issues.

I would appreciate it if anyone could check it on advanced without SG, I am mostly able to reproduce on a (decent) test environment with advanced + security groups.

**Comment by GabrielBrascher** [comment]
This is also one of the reasons I made this PR in an `apache/clodustack` branch. We can have any committer testing and contributing to it.

The main concerns are related to the fact that such implementation is quite complex (too many cases for testing and evaluating) and critical (a small python porting issue could mess with the VRs scripts).

**Comment by nvazquez** [comment]
Hi @GabrielBrascher should this be included on 4.17? Can you please fix the conflicts?

**Pull request closed without merging**
