### PR TITLE
cks: fix list apis response count

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes count value in listKubernetesClusters and listSupportedKubernetesVersions APIs response.
Currently, it returns items count of the response

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Review by vishesh92 — APPROVED** [review]
clgtm

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Review by kiranchavala — COMMENTED** [review]
@shwstppr Just tested on the latest 4.19, I found that count for both apis is working fine

Any step I am missing?

```
shapeblue) 🐱 > list kubernetessupportedversions filter=name
{
  "count": 3,
  
  
  (shapeblue) 🐱 > list kubernetesclusters filter=name
{
  "count": 2,
  
```

**Comment by shwstppr** [comment]
@kiranchavala can you please try giving a pagesize lesser than the number of resources present in the env?

**Comment by shwstppr** [comment]
@kiranchavala here is an example in an env without fix,

```
(local) 🐱 > list kubernetessupportedversions pagesize=2 page=1 filter=id,name
{
  "count": 2,
  "kubernetessupportedversion": [
    {
      "id": "6570218c-7d3f-478c-bb72-1c3c778aaf45",
      "name": "v1.26.0"
    },
    {
      "id": "b3e308be-e39b-4d9c-82d5-de41da9ed843",
      "name": "v1.24.0"
    }
  ]
}
(local) 🐱 > list kubernetessupportedversions filter=id,name
{
  "count": 3,
  "kubernetessupportedversion": [
    {
      "id": "6570218c-7d3f-478c-bb72-1c3c778aaf45",
      "name": "v1.26.0"
    },
    {
      "id": "b3e308be-e39b-4d9c-82d5-de41da9ed843",
      "name": "v1.24.0"
    },
    {
      "id": "04c74e5c-7802-460e-92b7-cce2b8efc546",
      "name": "v1.24.0"
    }
  ]
}
```

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Review by kiranchavala — APPROVED** [review]
LGTM. Tested the fix

The count is same 


```
(cmk) 🐱 > list kubernetessupportedversions filter=id,name
{
  "count": 3,
  "kubernetessupportedversion": [
    {
      "id": "ed372000-c2cb-45e0-aa72-e0eda51f618d",
      "name": "v1.28.4"
    },
    {
      "id": "7f4a657a-96d3-4ed6-afc7-379361299462",
      "name": "v1.27.8"
    },
    {
      "id": "5b2594ec-f41f-4bd4-9ff1-57c1c9a18c20",
      "name": "v1.26.0"
    }
  ]
}


(cmk) 🐱 > list kubernetessupportedversions pagesize=2 page=1 filter=id,name
{
  "count": 3,
  "kubernetessupportedversion": [
    {
      "id": "ed372000-c2cb-45e0-aa72-e0eda51f618d",
      "name": "v1.28.4"
    },
    {
      "id": "7f4a657a-96d3-4ed6-afc7-379361299462",
      "name": "v1.27.8"
    }
  ]
}

```


```

(cmk) 🐱 > list kubernetesclusters filter=id,name
{
  "count": 2,
  "kubernetescluster": [
    {
      "id": "21975df3-2f19-4865-890c-e9eb58b671fb",
      "name": "cks1"
    },
    {
      "id": "9607e862-a082-4c5b-a92c-245cf78ca3f0",
      "name": "cks2"
    }
  ]
}

(cmk) 🐱 > list kubernetesclusters pagesize=1 page=1 filter=id,name
{
  "count": 2,
  "kubernetescluster": [
    {
      "id": "21975df3-2f19-4865-890c-e9eb58b671fb",
      "name": "cks1"
    }
  ]
}

```

**Pull request merged**
