### PR TITLE
CLOUDSTACK-9789: Fix releasing secondary guest IP fails with associated static nat which is actually not used

### PR DESCRIPTION
**Pull request by ustcweizhou**

### CODE REVIEW

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
LGTM.

**Comment by rhtyd** [comment]
@karuturi this is ready for merge.

**Pull request merged**
