### PR TITLE
Fix camel case in some methods' names

### PR DESCRIPTION
**Pull request by GutoVeronezi**
### Description

Fix camel case in some methods' names.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

### CODE REVIEW

**Comment by GutoVeronezi** [comment]
@blueorangutan package

**Review by sureshanaparti — APPROVED** [review]
code LGTM

**Comment by sureshanaparti** [comment]
Hi @GutoVeronezi Is this good to go in 4.16.1? If so, please rebase with 4.16.

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
Looks good and should be done. One caveat is that some bean handling third party libraries may have required these to be in a different case and the names where on purpose. I do not know of these cases to be so.

**Review by GabrielBrascher — APPROVED** [review]
LGTM

**Comment by GutoVeronezi** [comment]
> Looks good and should be done. One caveat is that some bean handling third party libraries may have required these to be in a different case and the names where on purpose. I do not know of these cases to be so.

Hey @DaanHoogland, thanks. These beans don't seem to be the case you mentioned, as they only handle our own packages. 

Note: In case the beans that address these cases don't have javadoc, I think we should put some javadoc in them, explaining why they are written in different ways.

**Comment by GutoVeronezi** [comment]
> Hi @GutoVeronezi Is this good to go in 4.16.1? If so, please rebase with 4.16.

Hey @sureshanaparti, I'm good with it in main only, thanks.

**Review by nvazquez — APPROVED** [review]

**Review by SadiJr — APPROVED** [review]
Code LGTM

**Comment by GutoVeronezi** [comment]
Merging it based in the tests results and 5 approvals.

**Comment by rohityadavcloud** [comment]
Lgtm but one caveat, the getters and setters Methods are dynamically used during runtime to get the Field, were the affected APIs manually tested @GutoVeronezi? (such changes are not caught by smoketests that don't check api response for all keys)

**Comment by GutoVeronezi** [comment]
@rohityadavcloud, yes, they were tested. The behavior is kept.

**Pull request merged**
