### PR TITLE
Add 'break' at RedifshClient request re-try loop

### PR DESCRIPTION
**Pull request by GabrielBrascher**
### Description

This PR adds a missing break at the HTTP request re-try loop.

It is a minor bug, but it can result in double re-try requests where one should be enough. Also, talking about corner cases, there is a small possibility of the first re-try request be successful, and the second fails, which could result in _false error_.

This PR added the break and also Test cases that cover such scenarios to ensure that now we have it all covered.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by GabrielBrascher** [comment]
@blueorangutan package

**Review by rhtyd — APPROVED** [review]
LGTM - no way to verify the changes; smoketests won't cover changes in the plugin.

**Comment by rhtyd** [comment]
@GabrielBrascher have you performed any integration tests (manual/automated)?

**Comment by GabrielBrascher** [comment]
Thanks for the review @rhtyd! I have tested it, and it looks good.

Here follows details of the test process comparing **4.15.0.0** with this implementation (**4.15.1.0-SNAPSHOT** based on this branch).

**A - Test steps with 4.15.0.0:**
1. connect at the JVM via remote debug
2. place breakpoints and _tail_ logs
2. verify that it keeps attempting new HTTP requests even with the previous not failing until it reaches 3 attempts

**B - Test this implementation (4.15.1.0-SNAPSHOT):**
1. build packages
2. update mgmt server
3. connect on JVM to remote debug
4. place breakpoints and _tail_ logs
5. verify that the break indeed works if the HTTP request has not failed

**Review by Pearl1594 — APPROVED** [review]
code LGTM

**Comment by rhtyd** [comment]
@GabrielBrascher unfortunately I didn't check Travis and based on your confirmation/testing merged the PR only to find that unit tests were failing. I've reverted the PR https://github.com/apache/cloudstack/pull/4861
Please raise a new one with the unit tests issues fixed.

**Comment by GabrielBrascher** [comment]
Sorry, @rhtyd my bad; the `string.format` parameters order changed at the last commit has not been updated correctly.
I will soon raise another PR.

**Pull request merged**
