### PR TITLE
kvm/cloudstack-guest-tool: Tool to query Qemu Guest Agent

### PR DESCRIPTION
**Pull request by wido**
Using this tool on a hypervisor admins can query KVM Instances running
on that hypervisor if they have the Qemu Guest Agent installed.

All System VMs have this and they can be queried.

For example:

$ cloudstack-guest-tool i-2-25-VM

This will print some information about network and filesystem status.

root@hv-138-a05-23:~# ./cloudstack-guest-tool s-11-VM --command info|jq
{
  "network": [
    {
      "ip-addresses": [
        {
          "prefix": 8,
          "ip-address": "127.0.0.1",
          "ip-address-type": "ipv4"
        }
      ],
      "name": "lo",
      "hardware-address": "00:00:00:00:00:00"
    },
    {
      "ip-addresses": [
        {
          "prefix": 16,
          "ip-address": "169.254.242.169",
          "ip-address-type": "ipv4"
        }
      ],
      "name": "eth0",
      "hardware-address": "0e:00:a9:fe:f2:a9"
    },
 ...
 ...
  "filesystem": [
    {
      "mountpoint": "/var",
      "disk": [
        {
          "bus": 0,
          "bus-type": "virtio",
          "target": 0,
          "unit": 0,
          "pci-controller": {
            "slot": 7,
            "bus": 0,
            "domain": 0,
            "function": 0
          }
        }
      ],
      "type": "ext4",
      "name": "vda6"
    },

Signed-off-by: Wido den Hollander <wido@widodh.nl>

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by wido** [comment]
Example of running this tool on my KVM hypervisor:

<pre>
root@hv-138-a05-23:~# ./cloudstack-guest-tool s-11-VM --command info|jq
{
  "network": [
    {
      "ip-addresses": [
        {
          "prefix": 8,
          "ip-address": "127.0.0.1",
          "ip-address-type": "ipv4"
        }
      ],
      "name": "lo",
      "hardware-address": "00:00:00:00:00:00"
    },
    {
      "ip-addresses": [
        {
          "prefix": 16,
          "ip-address": "169.254.242.169",
          "ip-address-type": "ipv4"
        }
      ],
      "name": "eth0",
      "hardware-address": "0e:00:a9:fe:f2:a9"
    },
    {
      "ip-addresses": [
        {
          "prefix": 20,
          "ip-address": "10.100.3.239",
          "ip-address-type": "ipv4"
        }
      ],
      "name": "eth1",
      "hardware-address": "1e:00:05:00:01:e5"
    },
    {
      "ip-addresses": [
        {
          "prefix": 24,
          "ip-address": "185.109.XX.XX",
          "ip-address-type": "ipv4"
        }
      ],
      "name": "eth2",
      "hardware-address": "1e:00:0b:00:00:f5"
    }
  ],
  "filesystem": [
    {
      "mountpoint": "/var",
      "disk": [
        {
          "bus": 0,
          "bus-type": "virtio",
          "target": 0,
          "unit": 0,
          "pci-controller": {
            "slot": 7,
            "bus": 0,
            "domain": 0,
            "function": 0
          }
        }
      ],
      "type": "ext4",
      "name": "vda6"
    },
    {
      "mountpoint": "/boot",
      "disk": [
        {
          "bus": 0,
          "bus-type": "virtio",
          "target": 0,
          "unit": 0,
          "pci-controller": {
            "slot": 7,
            "bus": 0,
            "domain": 0,
            "function": 0
          }
        }
      ],
      "type": "ext2",
      "name": "vda1"
    },
    {
      "mountpoint": "/tmp",
      "disk": [
        {
          "bus": 0,
          "bus-type": "virtio",
          "target": 0,
          "unit": 0,
          "pci-controller": {
            "slot": 7,
            "bus": 0,
            "domain": 0,
            "function": 0
          }
        }
      ],
      "type": "ext4",
      "name": "vda7"
    },
    {
      "mountpoint": "/",
      "disk": [
        {
          "bus": 0,
          "bus-type": "virtio",
          "target": 0,
          "unit": 0,
          "pci-controller": {
            "slot": 7,
            "bus": 0,
            "domain": 0,
            "function": 0
          }
        }
      ],
      "type": "ext4",
      "name": "vda5"
    }
  ]
}
root@hv-138-a05-23:~#
</pre>

**Comment by rhtyd** [comment]
Doesn't virsh already output this? For example the patch.sh uses virsh for ping etc guest agent communication.

**Comment by wido** [comment]
@rhtyd Yes, virsh allows you to fetch this information as well, but you would need to execute this:

<pre>virsh qemu-agent-command i-1-1VM '{"execute": "guest-network-get-interfaces"}'|jq</pre>

The idea of this tool is to add commands which you (as an admin) can use to quickly talk to a VM.

Usually you want to see if the VM is set up properly. We could expand it with even more commands so that you could:

- Reset a password (in case this is broken inside the VM)
- Execute a command

**Comment by rhtyd** [comment]
Okay so less things to type.
@blueorangutan package

**Comment by wido** [comment]
@rhtyd Yes, less things to type nor to remember. A tool to make their life easier.

Debug issues like:
- Hmm, the VM is running, but I can't ping it. Did it get it's DHCP lease?
- The VM is online, but has it booted?

And as I said, we can add more features to it later to support a few more things which can help admins in their daily work.

**Comment by rhtyd** [comment]
@wido do we need to test against python 2 vs 3?

**Comment by wido** [comment]
@rhtyd I wrote this tool in Python 2, but should work on Python 3 as well.

We can't be sure if the libvirt Python 3 bindings are installed on the systems.

**Comment by rhtyd** [comment]
Okay let me test soon and get back to you, otherwise I'm sure this tool be purely bash based and use virsh instead of python libvirt library.

**Comment by wido** [comment]
security_group.py already uses the python-libvirt bindings, so they are present on a system. But they will be Python 2, not Python 3.

So no problem to have Python to this work instead of Bash.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@wido rpm packaging is failing, can you check? The new file needs declaration in the spec file.
```
error: Installed (but unpackaged) file(s) found:
   /usr/bin/cloudstack-guest-tool


RPM build errors:
    Binaries arch (1) not matching the package arch (2).
    Installed (but unpackaged) file(s) found:
   /usr/bin/cloudstack-guest-tool
```

**Comment by wido** [comment]
Can you retry the packaging?

**Comment by rhtyd** [comment]
@blueorangutan package

**Pull request merged**
