### PR TITLE
Improve logs on KVMHostActivityChecker

### PR DESCRIPTION
**Pull request by GutoVeronezi**
### Description
This PR intends to improve logging in the class `KVMHostActivityChecker` to facilitate troubleshooting.

### Types of changes
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functioanlity)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale
- [ ] Major
- [x] Minor

### How Has This Been Tested?
It has been tested locally on a test lab.

### CODE REVIEW

**Review by GabrielBrascher — COMMENTED** [review]
Overall code looks good; most of the changes regard adding logs while keeping the core behavior of the execution flow.

I would like just to bring another option to enhance the logs: what do you think of adding the host's name combined (or not) with the host ID?

In my opinion, this would make it easier to find the problematic host in a blink of an eye, otherwise, there is the need of checking via  DB/API to find which host has the respective ID.

**Review by DaanHoogland — APPROVED** [review]

**Comment by DaanHoogland** [comment]
pressed enter by accident ^^
code LGTM not tested

**Comment by GutoVeronezi** [comment]
> Overall code looks good; most of the changes regard adding logs while keeping the core behavior of the execution flow.
> 
> I would like just to bring another option to enhance the logs: what do you think of adding the host's name combined (or not) with the host ID?
> 
> In my opinion, this would make it easier to find the problematic host in a blink of an eye, otherwise, there is the need of checking via DB/API to find which host has the respective ID.

@GabrielBrascher as you suggested, I added more host information to the log.

**Review by GabrielBrascher — APPROVED** [review]
Code LGTM, I did not test it though.

- **+1** on log improvements;
- the proposal for changing the HostVO `toString()` format LGTM as well.

**Comment by GutoVeronezi** [comment]
@GabrielBrascher @DaanHoogland is there anything else to do?

**Comment by GabrielBrascher** [comment]
This one looks ready for merge. Travis and Jenkins's tests have passed and the code has 2 LGTMs. Maybe we can spawn @blueorangutan for testing.

**Pull request merged**
