### PR TITLE
CLOUDSTACK-9511: fix test_privategw_acl.py to handle multiple physical network

### PR DESCRIPTION
**Pull request by murali-reddy**
fix to ensure only physical network with guest traffic is picked up for
creating a private network for vpc private gateway

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by murali-reddy** [comment]
all tests in test_privategw_acl.py passed on KVM & XEN except for test_02_vpc_privategw_static_routes test fail in XenServer, which was due to  private gateway not getting created "createprivategateway failed, due to: errorCode: 431, errorText:Network with vlan vlan://842 already exists in zone 1". A network which may not have cleaned up.

Successfully ran 'test_02_vpc_privategw_static_routes' test manually, there no issue with the test.

**Comment by rhtyd** [comment]
@murali-reddy thanks, I've added a cleanup step b/w tests to ensure old resources can be cleared. Is there a way to modify/run the test to avoid any such intermittent error?

https://github.com/shapeblue/Trillian/blob/master/Ansible/roles/marvin/templates/smoketests.sh.j2#L27

**Comment by rhtyd** [comment]
LGTM on code.

**Comment by abhinandanprateek** [comment]
@murali-reddy LGTM on code review.

**Comment by rhtyd** [comment]
I saw there seems to be an issue with the fwd-merge, I'll fix that @murali-reddy for now.

**Pull request closed without merging**
