### PR TITLE
Add lsb-release dependency to mgmt server and agent on Debian/Ubuntu.

### PR DESCRIPTION
**Pull request by ProjectMoon**
New version of #1412, based on the 4.7 branch.

### CODE REVIEW

**Comment by swill** [comment]
@ProjectMoon please close and reopen to kick off travis again.  Thanks...

**Comment by wido** [comment]
Merge this back to 4.7? Will we release a new 4.7 version?

Anyway, LGTM

**Comment by swill** [comment]
### CI RESULTS

```
Tests Run: 85
  Skipped: 0
   Failed: 1
   Errors: 0
 Duration: 8h 37m 08s
```

**Summary of the problem(s):**
```
FAIL: test_03_vpc_privategw_restart_vpc_cleanup (integration.smoke.test_privategw_acl.TestPrivateGwACL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/git/cs1/cloudstack/test/integration/smoke/test_privategw_acl.py", line 274, in test_03_vpc_privategw_restart_vpc_cleanup
    self.performVPCTests(vpc_off, restart_with_cleanup = True)
  File "/data/git/cs1/cloudstack/test/integration/smoke/test_privategw_acl.py", line 303, in performVPCTests
    vpc_2 = self.createVPC(vpc_off, cidr = '10.0.2.0/24')
  File "/data/git/cs1/cloudstack/test/integration/smoke/test_privategw_acl.py", line 472, in createVPC
    self.fail('Unable to create VPC due to %s ' % e)
AssertionError: Unable to create VPC due to Job failed: {jobprocstatus : 0, created : u'2016-05-26T23:28:40+0200', jobresult : {errorcode : 530, errortext : u'Failed to create VPC'}, cmd : u'org.apache.cloudstack.api.command.admin.vpc.CreateVPCCmdByAdmin', userid : u'd11a1719-2357-11e6-92ce-5254001daa61', jobstatus : 2, jobid : u'7ae0f8ed-b922-46fc-b651-5fe657510310', jobresultcode : 530, jobresulttype : u'object', jobinstancetype : u'None', accountid : u'd119fe06-2357-11e6-92ce-5254001daa61'} 
----------------------------------------------------------------------
Additional details in: /tmp/MarvinLogs/test_network_6QAMPX/results.txt
```



**Associated Uploads**

**`/tmp/MarvinLogs/DeployDataCenter__May_26_2016_17_40_22_9UMTAF:`**
* [dc_entries.obj](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1565/tmp/MarvinLogs/DeployDataCenter__May_26_2016_17_40_22_9UMTAF/dc_entries.obj)
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1565/tmp/MarvinLogs/DeployDataCenter__May_26_2016_17_40_22_9UMTAF/failed_plus_exceptions.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1565/tmp/MarvinLogs/DeployDataCenter__May_26_2016_17_40_22_9UMTAF/runinfo.txt)

**`/tmp/MarvinLogs/test_network_6QAMPX:`**
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1565/tmp/MarvinLogs/test_network_6QAMPX/failed_plus_exceptions.txt)
* [results.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1565/tmp/MarvinLogs/test_network_6QAMPX/results.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1565/tmp/MarvinLogs/test_network_6QAMPX/runinfo.txt)

**`/tmp/MarvinLogs/test_vpc_routers_ITAGDW:`**
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1565/tmp/MarvinLogs/test_vpc_routers_ITAGDW/failed_plus_exceptions.txt)
* [results.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1565/tmp/MarvinLogs/test_vpc_routers_ITAGDW/results.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1565/tmp/MarvinLogs/test_vpc_routers_ITAGDW/runinfo.txt)


Uploads will be available until `2016-07-27 02:00:00 +0200 CEST`

*Comment created by [`upr comment`](https://github.com/cloudops/upr).*

**Comment by swill** [comment]
Yes @wido, this will be merged into 4.7 and then forward merged.  This test has been flaky recently, so I think this is PR is ready since we have LGTMs from the previous PR as well.

**Pull request merged**
