### PR TITLE
server: fix public IP association/disassociation to new network

### LINKED ISSUE #3321: Cannot associate a public IP to a new isolated network (4.12.0.0)
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
Networking
~~~

##### CLOUDSTACK VERSION
~~~
4.12.0.0
~~~

##### CONFIGURATION
I'm running my tests against the simulator container which I configured with an advanced datacenter setup: 
`python /root/tools/marvin/marvin/deployDataCenter.py -i /root/setup/dev/advanced.cfg`

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When creating an isolated network and then try to assign a public IP to the network, I get the following error:
```
{"errorcode":431,"errortext":"Network with UUID:a45c36c1-c9c4-458e-838d-1c7c7eea80a6 is in allocated and needs to be implemented first before acquiring an IP address"}
```
This worked fine with the 4.11.2.0 simulator container, but now fails with 4.12.0.0.

##### STEPS TO REPRODUCE
Create a new isolated (`DefaultIsolatedNetworkOfferingWithSourceNatService`) network using the `createNetwork` API call. Then try to assign a public IP using the `associateIpAddress` API call.

##### EXPECTED RESULTS
Don't get any errors and get a network with a public IP that will be it's source NAT IP.
 
##### ACTUAL RESULTS
A network without a public IP and this error:
~~~
{"errorcode":431,"errortext":"Network with UUID:a45c36c1-c9c4-458e-838d-1c7c7eea80a6 is in allocated and needs to be implemented first before acquiring an IP address"}
~~~

### PR DESCRIPTION
**Pull request by shwstppr**
## Description
Fixes #3321 

This changes removes exception throwing while associating an IP address to a new isolated network which is in `Allocated` state. And it allows disassociating an IP address when it is used for source NAT purpose but network is in allocated state.
Refer, https://github.com/apache/cloudstack/issues/3321#issuecomment-510389806

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?
Using cmk,
```
(localcloud) 🐱 > list networks filter=id,name,state
{
  "count": 1,
  "network": [
    {
      "id": "6838a64f-2f55-4097-af9f-c0cdff805737",
      "name": "Test",
      "state": "Allocated"
    }
  ]
}
(localcloud) 🐱 > associate ipaddress networkid=6838a64f-2f55-4097-af9f-c0cdff805737 
{
  "ipaddress": {
    "account": "admin",
    "allocated": "2019-07-12T15:29:07+0530",
    "associatednetworkid": "6838a64f-2f55-4097-af9f-c0cdff805737",
    "associatednetworkname": "Test",
    "domain": "ROOT",
    "domainid": "5b4d6fd0-a486-11e9-a980-645d8651f45a",
    "fordisplay": true,
    "forvirtualnetwork": true,
    "id": "8e8593dd-b38c-4272-8748-bdd87de5997f",
    "ipaddress": "192.168.2.4",
    "isportable": false,
    "issourcenat": true,
    "isstaticnat": false,
    "issystem": false,
    "networkid": "09e7940c-a642-41c1-9bad-47d9d97fb1d5",
    "physicalnetworkid": "e964a192-5883-4e07-afdb-a30ef5ea69fe",
    "state": "Allocating",
    "tags": [],
    "vlanid": "3421057d-5a58-45cd-b451-e26de05f7417",
    "vlanname": "vlan://50",
    "zoneid": "c9db52ce-6425-4460-aed4-cb00b67b02e8",
    "zonename": "Sandbox-simulator"
  }
}
(localcloud) 🐱 > disassociate ipaddress id=8e8593dd-b38c-4272-8748-bdd87de5997f
{
  "success": true
}

```

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
ping for review @rhtyd @anuragaw @borisroman @nvazquez @DaanHoogland

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
Tests lgtm

**Comment by rhtyd** [comment]
cc @svanharmelen @DaanHoogland

**Comment by svanharmelen** [comment]
Looks like this should fix the issues we had earlier, so LGTM!

**Pull request merged**
