### PR TITLE
Fix ServiceOfferingDao duplication

### PR DESCRIPTION
**Pull request by stephankruggg**
### Description

This PR fixes a double declaration of ServiceOfferingDao in UserVmManagerImpl.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [X] Trivial

### How Has This Been Tested?

I applied the changes in a local lab, and checked if commands associated to UserVmManagerImpl were correctly executed.

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by JoaoJandre — APPROVED** [review]
LGTM

**Review by rohityadavcloud — APPROVED** [review]

**Pull request merged**
