### PR TITLE
Fixup test_image_store_object_migration.py

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR fixes failure seem in https://github.com/apache/cloudstack/pull/7344#issuecomment-1862107631

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by vishesh92** [comment]
@blueorangutan package

**Review by shwstppr — APPROVED** [review]
LGTM. VMware may contain more template related files in the directory

**Comment by shwstppr** [comment]
@blueorangutan test matrix

**Review by harikrishna-patnala — APPROVED** [review]
Code and results LGTM

**Pull request merged**
