### PR TITLE
[REMOVED] IRC references on Readme.

### LINKED ISSUE #4880: Remove IRC references
##### SUMMARY

In 2019 there was a discussion on ML [[1]](https://lists.apache.org/thread.html/296def97c549e0b75bc14d0382ae412245cef6088e576acbcb007cc8%40%3Cdev.cloudstack.apache.org%3E) about dropping IRC as there is no movement there; the discussion reached a consensus regarding removing the IRC references.

Nowadays we mainly communicate via mailing list and Github issues/PRs. Additionally, the referenced IRC has no movement at all, and the fact that we are still marketing it as a point for discussions can give the wrong impression to newcomers, such as: _"either the project is dead or documentation is outdated"_.

With that said, this issue tracks the process of removing all IRC references, which reflects on working at the [README.md](https://github.com/apache/cloudstack/blob/master/README.md) (work in progress at #4879), as well as the website ([cloudstack-www](https://github.com/apache/cloudstack-www)) and documentation ([cloudstack-documentation](https://github.com/apache/cloudstack-documentation)).

[[1]](https://lists.apache.org/thread.html/296def97c549e0b75bc14d0382ae412245cef6088e576acbcb007cc8%40%3Cdev.cloudstack.apache.org%3E) https://lists.apache.org/thread.html/296def97c549e0b75bc14d0382ae412245cef6088e576acbcb007cc8%40%3Cdev.cloudstack.apache.org%3E

### PR DESCRIPTION
**Pull request by apurv-1**
### Issues

fixes #4880 

### Description

The readme file had older `irc.freenode.net`, without any link.

Screenshot (141)

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### Screenshots (if appropriate):
Capture1

### How Has This Been Tested?
By opening `https://webchat.freenode.net/` on the browser.

### CODE REVIEW

**Review by GabrielBrascher — COMMENTED** [review]
Good catch, thanks for the PR @apurv-1. However, I am not sure if we should keep IRC, as far as I know, there is no one hanging out there.

In 2019 there was a discussion on ML about dropping IRC and therefore removing all IRC information on the website and documentations. I will double-check this.

@DaanHoogland @PaulAngus @svenvogel and others: was there a vote regarding dropping IRC or did we get into a discussion but never raised a vote?

**Comment by PaulAngus** [comment]
The discussion was here @GabrielBrascher - https://lists.apache.org/thread.html/296def97c549e0b75bc14d0382ae412245cef6088e576acbcb007cc8%40%3Cdev.cloudstack.apache.org%3E
I think my view remains the same - only promote the mailing lists and if people want to have a synchronous call/chat, they can use whatever platform they like at the time.  That may be the Slack channel, whereas the UI SIG used an adhoc Google Meet.

If a subject such as this can be resolved through community discussion, there is no need for a formal vote.


(For the record, irc.freenode.net is the URI for an IRC client, webchat.freenode.net is *a* client, which may or may not stay around)

**Comment by andrijapanicsb** [comment]
+1 on what Paul said.

Remove all IRC info. as it's (at best) misleading, and mention Slack channel together with a way on how to requests joining it (@kiwiflyer had some fancy Google Form sheet or something), but still emphasise " it's ML or nothing"

**Comment by GabrielBrascher** [comment]
@PaulAngus @andrijapanicsb thanks for answering. In order to track such a process, I created issue #4880.

@apurv-1 as you brought this up, could you please change the PR scope from _updating the IRC reference_ to _removing IRC references_ at the README?

**Comment by apurv-1** [comment]
Done @GabrielBrascher

**Review by GabrielBrascher — APPROVED** [review]

**Comment by GabrielBrascher** [comment]
Ping for review: @PaulAngus @andrijapanicsb @DaanHoogland @rhtyd @svenvogel @wido @kiwiflyer @ustcweizhou @weizhouapache  and others.

**Review by DaanHoogland — APPROVED** [review]

**Comment by DaanHoogland** [comment]
come to think about it, this should go on as old a branch as possible, should it?
cc @GabrielBrascher @rhtyd @andrijapanicsb @PaulAngus

**Comment by GabrielBrascher** [comment]
Good question, @DaanHoogland.

IMHO I don't see much problem with keeping it on master; I think that users tend to check the README at the master.

**Review by rhtyd — APPROVED** [review]

**Pull request merged**
