### PR TITLE
ui: fix import instance form for recent changes

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

7123269 and 535761b introduced changes that are affecting Import Instance form.
Custom compute selection was not showing properly.
On import error was seen in UI.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### How Has This Been Tested?

import-instance

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by shwstppr** [comment]
@blueorangutan ui

**Review by rhtyd — APPROVED** [review]
LGTM - need some review/manual testing

**Comment by nvazquez** [comment]
@blueorangutan package

**Review by nvazquez — APPROVED** [review]
LGTM.

Manually tested on a VMware 6.7 env, was able to:
- Deploy multiple VMs
- Unmanage instances
- Import the unmanaged instances
- Verify imported instances are functional

**Comment by nvazquez** [comment]
Merging based on approvals, no smoke tests required as are purely UI changes

**Pull request merged**
