### PR TITLE
Catch error in Debian packaging script and fail the build

### PR DESCRIPTION
**Pull request by khos2ow**
## Description

This PR is going to:

- fail the build early if `--use-timestamp` is provided and working directory is not clean.
- catch any potential error and fail the build (fix the regression added in 1708838 (#2433))

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
Testing
- [ ] I have added tests to cover my changes.
- [ ] All relevant new and existing integration tests have passed.
- [ ] A full integration testsuite with all test that can run on my environment has passed.

### CODE REVIEW

**Comment by khos2ow** [comment]
@rafaelweingartner @rhtyd this is essentially a follow up of #2627, for Debian builds.

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by khos2ow** [comment]
@rhtyd the fact that debian build is failing on BO might actually be a good result, that the proposed enhancement in this PR works! Can you check/share the log of it?

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan help

**Comment by borisstoyanov** [comment]
@blueorangutan test ubuntu kvm-ubuntu

**Pull request merged**
