### PR TITLE
[CLOUDSTACK-10195] CloudStack MySQL HA problem -- No database selected

### PR DESCRIPTION
**Pull request by rafaelweingartner**
When using CloudStack with database HA configuration user receives warnings constantly saying “No database selected”.

This problem happens at com.cloud.cluster.ClusterManagerImpl.getHeartbeatTask().new ManagedContextRunnable(){...}.runInContext(), line 550. The scheme of the database is not properly set in the transaction when database HA options are enabled.

The problem was found and discussed in the following thread: http://mail-archives.apache.org/mod_mbox/cloudstack-dev/201712.mbox/%3CCAOVNhEJUPYxE7Y04c1LKkGGJ1igXg3PAb8RL5vobjhAtX-%2BgTQ%40mail.gmail.com%3E

### CODE REVIEW

**Comment by rhtyd** [comment]
@rafaelweingartner why was the unit test removed?

**Comment by rafaelweingartner** [comment]
Because it was testing the method   `txn.transitToUserManagedConnection(getHeartbeatConnection())`.
I replaced the use of this method by `txn.transitToAutoManagedConnection(TransactionLegacy.CLOUD_DB);`

If you see in that code at line 600, after "trying" to reuse a connection if something goes wrong, it will try to transit to a transaction using schema "Cloud_DB", and then it will close the transaction. The only place where the transaction was "reused" is there. So, when I changed `txn.transitToUserManagedConnection(getHeartbeatConnection())` to `txn.transitToAutoManagedConnection(TransactionLegacy.CLOUD_DB);`, the first method could be deleted. After that, I inspected and this method is not used anywhere else. Therefore, I also removed the method and its test cases.

**Comment by rhtyd** [comment]
Alright, let me kick some tests.
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rafaelweingartner** [comment]
@rhtyd Thanks!

**Comment by rhtyd** [comment]
Tests LGTM. We'll need an additional review on this.

**Comment by rafaelweingartner** [comment]
@khos2ow, @nvazquez, @DaanHoogland, @GabrielBrascher can some of you review this PR as well?

**Comment by rhtyd** [comment]
Merging based on reviews and test results.

**Pull request merged**
