### PR TITLE
Update L10N resource files with 4.7 strings from Transifex (20160127)

### PR DESCRIPTION
**Pull request by milamberspace**
cc @remibergsma @bhaisaab @DaanHoogland

### CODE REVIEW

**Comment by bvbharatk** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 109
 Hypervisor xenserver
 NetworkType Advanced
 Passed=106
 Failed=12
 Skipped=4

**The follwing tests have known issues**
test_vpc_remote_access_vpn
test_vpc_site2site_vpn
test_01_test_vm_volume_snapshot
test_02_vpc_privategw_static_routes
test_03_rvpc_privategw_static_routes
test_04_change_offering_small
ContextSuite context=TestNiciraContoller>:setup
test_01_primary_storage_iscsi
test02_internallb_haproxy_stats_on_all_interfaces
test_01_internallb_roundrobin_1VPC_3VM_HTTP_port80
ContextSuite context=TestDeployVM>:setup
test_04_extract_template
test_04_extract_Iso
test_07_list_default_iso


_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/yj3wnzbceo9uef2/AAB6u-Iap-xztdm6jHX9SjPja?dl=0


**Failed tests:**

**Skipped tests:**
test_vm_nic_adapter_vmxnet3
test_deploy_vgpu_enabled_vm
test_06_copy_template
test_06_copy_iso

**Passed test suits:**
integration.smoke.test_deploy_vm_with_userdata.TestDeployVmWithUserData
integration.smoke.test_affinity_groups_projects.TestDeployVmWithAffinityGroup
integration.smoke.test_portable_publicip.TestPortablePublicIPAcquire
integration.smoke.test_over_provisioning.TestUpdateOverProvision
integration.smoke.test_global_settings.TestUpdateConfigWithScope
integration.smoke.test_guest_vlan_range.TestDedicateGuestVlanRange
integration.smoke.test_scale_vm.TestScaleVm
integration.smoke.test_service_offerings.TestCreateServiceOffering
integration.smoke.test_loadbalance.TestLoadBalance
integration.smoke.test_routers.TestRouterServices
integration.smoke.test_reset_vm_on_reboot.TestResetVmOnReboot
integration.smoke.test_snapshots.TestSnapshotRootDisk
integration.smoke.test_deploy_vms_with_varied_deploymentplanners.TestDeployVmWithVariedPlanners
integration.smoke.test_network.TestDeleteAccount
integration.smoke.test_non_contigiousvlan.TestUpdatePhysicalNetwork
integration.smoke.test_deploy_vm_iso.TestDeployVMFromISO
integration.smoke.test_public_ip_range.TestDedicatePublicIPRange
integration.smoke.test_multipleips_per_nic.TestDeployVM
integration.smoke.test_regions.TestRegions
integration.smoke.test_affinity_groups.TestDeployVmWithAffinityGroup
integration.smoke.test_network_acl.TestNetworkACL
integration.smoke.test_pvlan.TestPVLAN
integration.smoke.test_volumes.TestCreateVolume
integration.smoke.test_ssvm.TestSSVMs
integration.smoke.test_nic.TestNic
integration.smoke.test_deploy_vm_root_resize.TestDeployVM
integration.smoke.test_resource_detail.TestResourceDetail
integration.smoke.test_secondary_storage.TestSecStorageServices
integration.smoke.test_vm_life_cycle.TestDeployVM
integration.smoke.test_disk_offerings.TestCreateDiskOffering

**Comment by koushik-das** [comment]
@swill Again UI changes related to l10n. I think these can be merged.

**Comment by milamberspace** [comment]
@swill I've just rebase from 4.7 update the L10N files and push --force this PR.
cc @koushik-das

**Comment by rhtyd** [comment]
LGTM, @milamberspace please rebase and squash changes into to a single commit

tag:easypr

**Comment by milamberspace** [comment]
@rhtyd rebase and squash done

**Comment by rhtyd** [comment]
Thanks @milamberspace cc @swill @DaanHoogland we need one more LGTM

**Comment by swill** [comment]
#1515 is going in today and then we will validate that this one and #1376 don't have merge conflicts once #1515 is in and they will follow right after...

**Comment by DaanHoogland** [comment]
@swill I think you want to forward merge before this one and then merge -s ours or such to prevent this from being merged forward.
4.8 has its own transifex stuff.

**Comment by swill** [comment]
@DaanHoogland this is opened against `master` though while #1515 is opened against `4.8`, so the forward merge of #1515 will affect this one...

**Comment by DaanHoogland** [comment]
ok, the other way around, but you get what I am warning for.

**Comment by swill** [comment]
@DaanHoogland I think this PR should probably be opened against the `4.7` branch though in order for your point to be valid.  Right?

**Comment by milamberspace** [comment]
@swill @DaanHoogland Yes, on my local machine, the branch are open against thr 4.7 branch. The PR in github is against the master, but will be against 4.7.
I can close and open a new PR (4.7) if you want.

**Comment by swill** [comment]
@milamberspace I think that is probably the best option.  Then I will merge the new one (with these changes) first and forward merge and then merge #1515 and then if no conflicts #1376.

**Comment by milamberspace** [comment]
@swill ok I will do this. But you must understand that the L10N resources files for each CS version are different and cannot merge together. On the Transifex website (used for the translation) each CS version has its own resources files.
The others RM merged directly my PRs (about the L10N) without forward merge after. It is not necessary (and probably counter-productive)

**Pull request closed without merging**
