### PR TITLE
4.8.0.1 rc20160525 t1247

### PR DESCRIPTION
**Pull request by toshen**

### CODE REVIEW

**Comment by rhtyd** [comment]
@toshen was this created by mistake, I see my old commits which are already in master and 4.9/4.10 branches.

**Comment by rhtyd** [comment]
I checked both the commits, they are in master and recent branches. For both the changes, subsequent fixes were fixed in #2009 and #1763. This PR does not describe the intention and why it's resubmitted @toshen ?

**Comment by rafaelweingartner** [comment]
@rhtyd if there is no answer here, I vote for closing this PR.
That is one of the biggest benefits of using the Gitbox experiment.

**Comment by rhtyd** [comment]
Thanks @rafaelweingartner I'll give another day to @toshen to reply, if there is no answer we can close this PR as potential spam/mistake.

**Comment by DaanHoogland** [comment]
not a vaild pr

**Pull request closed without merging**
