### PR TITLE
Fix VM snapshot size during storage capacity check

### PR DESCRIPTION
**Pull request by harikrishna-patnala**
### Description

This PR fixes the issue #8054 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

1. created a VM with one root (2GB) and data (5GB) disks
2. create VM snapshot and the primary storage usage looks like below 
image

3. After this is fixed, usage considered 5GB data disk size as well
image

### CODE REVIEW

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by DaanHoogland — APPROVED** [review]
less == more, needs testing though

**Review by shwstppr — APPROVED** [review]
Code LGTM

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
tested manually according to description, works as expected

**Pull request merged**
