### PR TITLE
Added compress option to dnsmasq log files

### PR DESCRIPTION
**Pull request by Spaceman1984**
## Description

This PR adds compression to dnsmasq log files

Fixes: #3756 
## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

Log into virtual router
Check /var/log/ directory, observe dnsmasq.log
Change system time 1 day ahead  and reboot VR
Check /var/log/ directory, observe dnsmasq.log, dnsmasq.log1
Change system time 1 day ahead  and reboot VR
There should be 3 log files now and 1 should be compressed
Check /var/log/ directory, observe dnsmasq.log, dnsmasq.log1, dnsmasq.log.2.gz

### CODE REVIEW

**Comment by Spaceman1984** [comment]
@blueorangutan package

**Comment by Spaceman1984** [comment]
@blueorangutan package

**Comment by Spaceman1984** [comment]
@blueorangutan test

**Review by DaanHoogland — APPROVED** [review]

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
Simple enough change, let's merge for master @DaanHoogland ?

**Comment by DaanHoogland** [comment]
@PaulAngus merging this as it is small and not intrusive. cc @GabrielBrascher @weizhouapache.

**Pull request merged**
