### PR TITLE
Add quick test attribute

### PR DESCRIPTION
**Pull request by DaanHoogland**
## Description

Adding 'quick-test' attribute to list of smoketests and adding 'vpc', 'templates', 'deploy-vm', 'roles', 'service-offerings', 'storage', 'routers', 'networks', 'usage', 'accounts' tags

quick-test label aims to provide quick feedback of recent changes to the developer, instead of waiting for the whole smoketest to execute(24h+). This execution lasts about 1.5h at Trillian environments.

The categories aim to offer more efficient way to slice through tests in both smoke and component tests. Let's say as a developer you've made a change in the accounts. You can simply trigger marvin tests with tag=accounts pointing all the tests for example:

```
nosetests --with-marvin --marvin-config=[config] --hypervisor=xenserver -a tags=accounts /tests/integration/*/*.*
```

http://cwiki.apache.org/confluence/display/CLOUDSTACK/Test+Categories+and+Quick-test+in+Marvin

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@PaulAngus @borisstoyanov do you want this in? cc @rhtyd

**Review by borisstoyanov — APPROVED** [review]
yup, LGTM

**Comment by rhtyd** [comment]
@DaanHoogland many conflicts, but LGTM - pl do the honours if you think it's useful
(personally I don't who will run only a sub-set of tests)

**Comment by DaanHoogland** [comment]
@rhtyd this will need rework, changing to draft. we might want to run this for low risk changes, but a am also thinking about a more flexible test set system.

**Comment by nvazquez** [comment]
Hi @DaanHoogland are you considering this PR for 4.17? In that case, can you please solve the conflicts?

**Comment by DaanHoogland** [comment]
one in 5 lines in here is a conflict. maybe revisit the idea later.

**Pull request closed without merging**
