### PR TITLE
vm-import: fix stopped managed vms listing in unmanaged instances

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

When listing unmanaged instances for a cluster with multiple hosts, stopped manager VMs are getting listed as well. This PR fixes this behaviour and adds some code refactoring

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@DaanHoogland maybe the title and description wasn't that clear. This PR is trying to fix an issue where stopped **managed** VMs are getting listed as unmanaged instances

**Comment by DaanHoogland** [comment]
> @DaanHoogland maybe the title and description wasn't that clear. This PR is trying to fix an issue where stopped **managed** VMs are getting listed as unmanaged instances

ok, tnx

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test rocky8 vmware-67u3

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by rohityadavcloud** [comment]
@shwstppr - is this ready for review?
@blueorangutan package

**Comment by shwstppr** [comment]
@rohityadavcloud yes, marked it as ready for review

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by DaanHoogland** [comment]
tested manually @shwstppr , there was one circumstance in which a VM was visible both as managed as well as unmanaged:
- New VM created in cloudstack
- unmanaged
- stopped in vcenter
- imported
now  it is visible on both lists of the dialog:
image
after starting it in cloudstack it is no longer visible as unmanaged:
image
All other combinations of stop/start seem to display correctly

**Comment by shwstppr** [comment]
@DaanHoogland thanks for the testing. Will have to check. Weird that an unmanaged VM is showing in the managed list

**Comment by DaanHoogland** [comment]
> @DaanHoogland thanks for the testing. Will have to check. Weird that an unmanaged VM is showing in the managed list

np. it isn´t, it is still showing after re-importing

**Comment by DaanHoogland** [comment]
@shwstppr can you look at this conflict. I'll retest after.

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test rocky8 vmware-70u3 keepEnv

**Comment by DaanHoogland** [comment]
@shwstppr still a little snag (I don't know if you already gave that attention)
image
note i-2-431-VM is visible on both sides, This is the case where I stopped on ACS unmanaged and imported again. At first it is not visible on the left side, but on pressing refresh it appears.

**Comment by shwstppr** [comment]
@DaanHoogland will investigate this week and update

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@DaanHoogland I tested this again and it seems to be working fine in my test.

- I build 2 cluster VMware env.
- Deployed 4 VMs.
- Stopped 2 VMs of them
- Unmanaged one running and one stopped VM
- Checked import tool in the UI
Am I missing anything?

Below is a screen grab of the same
Before change
[pre-7606.webm](https://github.com/apache/cloudstack/assets/153340/8283a278-5241-4a74-9772-74129cc3eb90)
After change
[post-7606.webm](https://github.com/apache/cloudstack/assets/153340/9947d95b-bc28-45ba-8922-342b2a9d2511)

**Comment by shwstppr** [comment]
@DaanHoogland issue should be fixed now

https://github.com/apache/cloudstack/assets/153340/142c39af-5b78-4992-85ff-063bcd77c5b6



@blueorangutan package

**Comment by DaanHoogland** [comment]
great @shwstppr , the issue is gone indeed.

**Comment by DaanHoogland** [comment]
@blueorangutan test rocky8 vmware-67u3

**Comment by DaanHoogland** [comment]
@blueorangutan test alma8 vmware-70u3

**Pull request merged**
