### PR TITLE
Remove powermock from xenserver hypervisor plugin

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR removes powermock from xenserver hypervisor plugin

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by vishesh92** [comment]
@blueorangutan package

**Review by harikrishna-patnala — COMMENTED** [review]
@vishesh92 This PR should increase the coverage right! any idea why it is decreasing? 
image

**Comment by vishesh92** [comment]
@harikrishna-patnala Even I am not sure. The files it is listing are in a completely different module. In intellij, running xenserver tests on main are not generating coverage for the below files either.

image

**Comment by vishesh92** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
> @vishesh92 This PR should increase the coverage right! any idea why it is decreasing? image

It was an issue with code coverage. I could see similar output for other PRs as well. Rebasing with latest _main_ fixed the issue.

**Review by harikrishna-patnala — APPROVED** [review]
Code LGTM.

**Pull request merged**
