### PR TITLE
BUG-ID: CLOUDSTACK-8484 - Hosts without tag are not listed while list…

### PR DESCRIPTION
**Pull request by sudhansu7**
…ing the hosts for migration for instance with tag

While preparing the suitable hosts we are accidentally removing the incompatible (host does not have host tag) hosts from other host list(incorrect use of List.retainAll).

### CODE REVIEW

**Comment by karuturi** [comment]
Can you add some unit/marvin tests? 
Also, fix the commit msg header to 72 :) http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

**Comment by bhaisaab** [comment]
LGTM, I guess unit tests would be cool.

**Comment by remibergsma** [comment]
Code looks good, although I didn't test it yet. Before I do, I'd like to understand why do you want to push this to 4.5 and not to master?

**Comment by runseb** [comment]
@sudhansu7 there is a question here from @remibergsma , can you answer it so it can get merged.

**Comment by sudhansu7** [comment]
@remibergsma  @runseb 
This issue exists in 4.5 , hence fixed it in 4.5. this can me merged to master as well.

**Comment by remibergsma** [comment]
@sudhansu7 Let's first merge this to master, then it can go to 4.5. I just tried to merge your PR on master and that seems to work just fine so that is nice.

There were two other questions: about unit tests and one about the commit message. If you could respond to that please? In the mean time, I'll go ahead and give it a test run.

**Comment by sudhansu7** [comment]
@remibergsma @karuturi 
I have added marvin test for this issue.
Test result from local setup:

Sudhansus-MAC:cloudstack sudhansu$ nosetests --with-marvin --marvin-config=setup/dev/advanced.cfg ./test/integration/smoke/find_hosts_for_migration.py 

==== Marvin Init Started ====

=== Marvin Parse Config Successful ===

=== Marvin Setting TestData Successful===

==== Log Folder Path: /tmp//MarvinLogs//Jul_03_2015_17_38_01_JVMT7H. All logs will be available here ====

=== Marvin Init Logging Successful===

==== Marvin Init Successful ====
===final results are now copied to: /tmp//MarvinLogs/find_hosts_for_migration_FKMWAR===
Sudhansus-MAC:cloudstack sudhansu$ cat /tmp//MarvinLogs/find_hosts_for_migration_FKMWAR/results.txt 
Test find suitable and not-suitable list of hosts for migration ... === TestName: test_01_find_hosts_for_migration | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 1 test in 27.003s

OK
Sudhansus-MAC:cloudstack sudhansu$ cat /tmp//MarvinLogs/find_hosts_for_migration_FKMWAR/failed_plus_exceptions.txt 

Sudhansus-MAC:cloudstack sudhansu$ cat /tmp//MarvinLogs/find_hosts_for_migration_FKMWAR/runinfo.txt | grep -i 'Suitable Hosts'
2015-07-03 17:38:18,171 - DEBUG - Suitable Hosts: set([])
2015-07-03 17:38:18,171 - DEBUG - Not suitable Hosts: set([{cpuwithoverprovisioning : u'32000.0', version : u'4.5.2-SNAPSHOT', memorytotal : 8589934592, jobstatus : 0, zoneid : u'7a83176c-4ae7-49cc-88ff-a794716e74f9', cpunumber : 4, managementserverid : 4278190080, cpuallocated : u'0%', memoryused : 0, id : u'b1b25f17-18f7-4b4d-a8e1-a353ebf33660', cpuused : u'0%', suitableformigration : False, clusterid : u'c138587b-c149-4819-9d30-d4fa9d6d5da4', capabilities : u'hvm', state : u'Up', memoryallocated : 1879048192, networkkbswrite : 16384, cpuspeed : 8000, type : u'Routing', events : u'Ping; StartAgentRebalance; ShutdownRequested; ManagementServerDown; HostDown; AgentDisconnected; PingTimeout; Remove; AgentConnected', zonename : u'Sandbox-simulator', podid : u'b0b72cfb-db0a-4e9c-a9da-84854d8c4a1f', clustertype : u'CloudManaged', hahost : False, lastpinged : u'1970-01-17T11:01:01+0530', ipaddress : u'172.16.15.21', disconnected : u'2015-07-03T14:32:16+0530', name : u'SimulatedAgent.3481871b-7626-450a-b2c1-ab4e6a2e5965', networkkbsread : 32768, created : u'2015-07-03T13:39:27+0530', clustername : u'C0', hypervisor : u'Simulator', islocalstorageactive : False, resourcestate : u'Enabled', requiresStorageMotion : False, podname : u'POD0'}])

**Comment by karuturi** [comment]
Awesome @sudhansu7. Congratulations on the first marvin test :+1: :)
I will push this to master in sometime.

**Pull request closed without merging**
