### PR TITLE
systemvm: new qemu-guest-agent based patching for KVM

### PR DESCRIPTION
**Pull request by rhtyd**
It was reported that systemvm patching broke with qemu-ev 2.12, this fixes for that reported issue:

This introduces a new patching script for patching systemvms on KVM
using qemu-guest-agent that runs inside the systemvm on startup. This
also removes the vport device which was previously used by the legacy
patching script and instead uses the modern and new uniform guest
agent vport for host-guest communication.

Also updates the sytemvmtemplate build config to use the latest Debian
9.8.0 iso.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test centos7 kvm-centos6

**Comment by rhtyd** [comment]
@borisstoyanov env setup issue?
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test matrix

**Comment by borisstoyanov** [comment]
@blueorangutan test centos7 kvm-centos6

**Comment by rhtyd** [comment]
@borisstoyanov don't test matrix - this needs to be manually kicked with the new systemvmtemplate at least for KVM :)

**Comment by DennisKonrad** [comment]
@rhtyd Can you provide a version of this patch thats working with current master?
Sadly we're not able to test this with 4.11 -.-

**Comment by borisstoyanov** [comment]
@DennisKonrad you can checkout the repo and rebase this branch against master, then build it locally and test it out.

**Comment by DennisKonrad** [comment]
@borisstoyanov Already tried that. But I wasn't able to handle the merge conflicts

**Comment by rhtyd** [comment]
@DennisKonrad you may forward merge or cherry-pick the changes, once this PR is approved we'll forward merge this on master/4.13.

**Comment by rhtyd** [comment]
@PaulAngus - please review.
After merging this, we may explore merging any further changes to the systemvmtemplate @PaulAngus  - and then add a suitable upgrade path.

**Comment by rhtyd** [comment]
Merge note: 4.11.3.0/master will require a new systemvmtemplate for KVM only. The older template may work due to the way patch.sh is written, but a new template is recommended. For testing purposes, we'll need to host this new template.

**Comment by svenvogel** [comment]
@rhtyd @wido @kiwiflyer we encounter the same problem. i wrote in the dev mailing list.

We use CentOS 1805 or 1810 and OVS and QEMU 2.12. It seems the first agent contact will not work so that the agent know the virtual machine is running. With 2.10 and the old agent, SystemVM it works.

is there something what we forgot? 

````
2019-07-19 00:17:30,571 DEBUG [kvm.resource.LibvirtComputingResource] (agentRequest-Handler-5:null) (logid:8ad14091) Executing: /usr/share/cloudstack-common/scripts/vm/hypervisor/kvm/patch.sh -n v-1728-VM -c  template=domP type=consoleproxy host=10.24.48.46 port=8250 name=v-1728-VM premium=true zone=4 pod=4 guid=Proxy.1728 proxy_vm=1728 disable_rp_filter=true eth2ip=185.232.219.237 eth2mask=255.255.255.248 gateway=185.232.219.233 eth0ip=169.254.0.193 eth0mask=255.255.0.0 eth1ip=10.24.48.124 eth1mask=255.255.255.0 mgmtcidr=10.24.48.0/24 localgw=10.24.48.1 internaldns1=10.24.48.33 internaldns2=10.24.48.34 dns1=217.69.224.73 dns2=85.232.28.146
2019-07-19 00:17:30,573 DEBUG [kvm.resource.LibvirtComputingResource] (agentRequest-Handler-5:null) (logid:8ad14091) Executing while with timeout : 300000
2019-07-19 00:17:30,616 DEBUG [resource.virtualnetwork.VirtualRoutingResource] (agentRequest-Handler-2:null) (logid:7577151e) Unable to logon to 169.254.2.189
```

maybe we need to reopen this issue.

**Comment by wido** [comment]
We had a similar issue with Ubuntu 18.04 and 4.12. The SSVM 4.11.3 template wouldn't work properly and we reverted to the 4.11.2 template.

@GabrielBrascher is going to look into this to make sure we have this fixed in time.

**Comment by svenvogel** [comment]
@wido @GabrielBrascher that would be great! we can help by looking in the error and support but at the moment we dont see where the error comes from. what we see is that it has something to do with the qemu agent and the first connectivity check from the host to the VM. i will post here if i finde something.

```xml
<channel type='unix'>
<source mode='bind' path='/var/lib/libvirt/qemu/r-1710-VM.agent'/>
<target type='virtio' name='r-1710-VM.vport'/>
<alias name='channel0'/>
<address type='virtio-serial' controller='0' bus='0' port='1'/>
</channel>
<channel type='unix'>
<source mode='bind' path='/var/lib/libvirt/qemu/r-1710-VM.org.qemu.guest_agent.0'/>
<target type='virtio' name='org.qemu.guest_agent.0'/>
<alias name='channel1'/>
<address type='virtio-serial' controller='0' bus='0' port='2'/>
</channel>
```
we found on any cases (not all) that got two channels. another thing is we use since we know ".org.qemu.guest_agent.0" and not ".vport". maybe there is a problem.

you wrote about a similar issue. was it an issue with QEMU 2.12?

**Comment by GabrielBrascher** [comment]
@svenvogel @wido I am taking a look into this. Deploying a 4.13 staging environment, I hope to have feedback soon.

**Pull request merged**
