### PR TITLE
ui: Fix Scale VM failure - missing args when custom compute offering is selected

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

This PR fixes the failure noticed during scale VM operation when a custom offering is selected. It observed that when cpuNumber / cpu speed is provided for the selected custom compute offering, it fails to pass the args properly

image

image

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### How Has This Been Tested?
Successfully scaled VM - args properly passed:
image

### CODE REVIEW

**Comment by Pearl1594** [comment]
@blueorangutan ui

**Review by utchoang — APPROVED** [review]
LGTM!

**Comment by rhtyd** [comment]
LGTM but @shwstppr to confirm

**Review by shwstppr — COMMENTED** [review]
@Pearl1594 this will affect 4.15 too?

**Comment by Pearl1594** [comment]
Yes @shwstppr, but since it isn't a critical issue, I've targeted the fix for 4.16

**Comment by rhtyd** [comment]
@Pearl1594 is this a critical/blocker issue for 4.15; for example is there a workaround possible with using API or legacy UI?

**Comment by Pearl1594** [comment]
@rhtyd  It's not a blocker - one can use the legacy UI / cmk to achieve the same

**Review by nvazquez — APPROVED** [review]
LGTM

**Pull request merged**
