### PR TITLE
Two fixes for RC3

### PR DESCRIPTION
**Pull request by mike-tutkowski**
This PR is based on master. Old PR was the following: https://github.com/apache/cloudstack/pull/2141

### CODE REVIEW

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by karuturi** [comment]
@mike-tutkowski I cherry-picked the commits from this PR and created a new one for master. #2150

**Comment by karuturi** [comment]
closing this in favor of #2150

**Pull request closed without merging**
