### PR TITLE
CLOUDSTACK-9857: With this change if agent dies the systemd will catc…

### PR DESCRIPTION
**Pull request by abhinandanprateek**
…h it properly and show process as exited

### CODE REVIEW

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
ping @DaanHoogland @PaulAngus @rhtyd for review

**Comment by DaanHoogland** [comment]
trivial enough: LGTM

**Comment by borisstoyanov** [comment]
@karuturi we have 2 LGTMs on this trivial PR, I guess we can proceed and merge it.

**Comment by rhtyd** [comment]
LGTM. @abhinandanprateek should we retarget this PR to 4.9? Thanks. 
@karuturi let's merge this before next 4.10 RC

**Comment by wido** [comment]
LGTM

**Comment by abhinandanprateek** [comment]
@rhtyd @karuturi here is the cherry picked PR on 4.9 https://github.com/apache/cloudstack/pull/2029

**Comment by rhtyd** [comment]
LGTM, @karuturi this is ready for merging.

**Pull request merged**
