### PR TITLE
[CLOUDSTACK-9732] Update L10N resource files with 4.9 strings from Transifex (20170106)

### PR DESCRIPTION
**Pull request by milamberspace**
(PR with 4.9 branch)

Related to: http://markmail.org/message/lywieba2nxlrbyzf?q=list:org.apache.incubator.cloudstack-*+[VOTE]+Apache+Cloudstack+4.9.2.0+%28RC2%29

And update the others language too

cc @rhtyd @rafaelweingartner

### CODE REVIEW

**Comment by rhtyd** [comment]
LGTM, only text/translation changes. Thanks @milamberspace 
Travis test LGTM, trillian smoke tests are not necessary.

**Comment by rhtyd** [comment]
@karuturi pure translation changes, we need one more LGTM, otherwise this is ready for merge.

**Comment by karuturi** [comment]
@rhtyd missed this one. Thanks for reminding. merging now.
@milamberspace  Thanks for keeping the translations updated for every release :)

**Comment by karuturi** [comment]
@milamberspace  Should the merge to master be an empty merge? Meaning is this only for 4.9??

**Comment by milamberspace** [comment]
@karuturi Since master (4.10) use now JSON files for the localization files (and too because on Transifex the localization's resources for each version of CS are different), so this PR will be merge only on 4.9.

**Comment by rafaelweingartner** [comment]
@milamberspace @rhtyd do you know why the entry "label.host.alerts" was removed from some languages?

**Comment by milamberspace** [comment]
@rafaelweingartner It was because the source string (en) has been chenged by this PR 1803, so the translations have been deleted by Transifex to invite the translator to make the new translation.

https://github.com/apache/cloudstack/pull/1803/files

**Comment by rafaelweingartner** [comment]
Got it, thanks for the explanation. I saw that, and I was wondering if it could have been a bug or something else.

LGTM then.

**Comment by rhtyd** [comment]
LGTM. @karuturi let's merge this?

**Pull request merged**
