### PR TITLE
CLOUDSTACK-8615 :skip all tests in test_ps_limits.py for lxc

### PR DESCRIPTION
**Pull request by nitt10prashant**
issue
-------
All test cases are failing due to unsupported storage type

solution
-----------
skip test if supported storage type(for lxc hyp) is not present

### CODE REVIEW

**Comment by nitt10prashant** [comment]
Test assign Vm to different account ... SKIP: unsupported storage type
Test assign Vm to different account ... SKIP: unsupported storage type
Stop attach and detach volume from VM ... SKIP: unsupported storage type
Stop attach and detach volume from VM ... SKIP: unsupported storage type
Test create multiple volumes ... SKIP: unsupported storage type
Test create multiple volumes ... SKIP: unsupported storage type
Test create snapshot and templates from volume ... SKIP: unsupported storage type
Test create snapshot and templates from volume ... SKIP: unsupported storage type
Test Deploy multiple VMs with & verify the usage ... SKIP: unsupported storage type
Test Deploy multiple VMs with & verify the usage ... SKIP: unsupported storage type
Test delete and recover instance ... SKIP: skip
Test delete and recover instance ... SKIP: skip
Test Deploy VM with 5 GB volume & verify the usage ... SKIP: unsupported storage type
Test Deploy VM with 5 GB volume & verify the usage ... SKIP: unsupported storage type

----------------------------------------------------------------------
Ran 14 tests in 2.833s

OK (SKIP=14)

**Comment by sanju1010** [comment]
LGTM

**Comment by karuturi** [comment]
please wait for 2 manual reviews before pushing to master.

**Comment by pavanb018** [comment]
The changes Look Good to me

**Pull request closed without merging**
