### PR TITLE
VMware: match hardware version for worker VM when taking a snapshot

### PR DESCRIPTION
**Pull request by Spaceman1984**
## Description

When a worker VM is created in the process of creating a volume snapshot on Vmware, the hardware version of the worker VM will be set to the highest supported hardware version of the hypervisor. If you have hypervisors of different versions in a cluster and have set the "Default VM compatibility" to a lower version, the worker VM should use the same version as the original VM instance,

This PR sets the worker VM hardware version to the same version as the original VM instance.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

This has been tested by doing the following: 
* create an instance 
* take a snapshot 
* check the hardware version of the worker vm created in Vsphere.

### CODE REVIEW

**Comment by Spaceman1984** [comment]
@blueorangutan package

**Comment by Spaceman1984** [comment]
@blueorangutan package

**Comment by Spaceman1984** [comment]
@blueorangutan ?

**Comment by Spaceman1984** [comment]
@blueorangutan test ?

**Comment by Spaceman1984** [comment]
@blueorangutan test

**Comment by Spaceman1984** [comment]
@blueorangutan test ?

**Comment by Spaceman1984** [comment]
@blueorangutan test centos7 vmware-65-u2

**Comment by Spaceman1984** [comment]
@blueorangutan test centos7 vmware-65u2

**Comment by Spaceman1984** [comment]
@blueorangutan package

**Comment by Spaceman1984** [comment]
@blueorangutan package

**Comment by Spaceman1984** [comment]
@blueorangutan test centos7 vmware-65-u2

**Comment by Spaceman1984** [comment]
@blueorangutan test centos7 vmware-65u2

**Comment by Spaceman1984** [comment]
@blueorangutan test centos7 vmware-65u2

**Review by shwstppr — APPROVED** [review]
LGTM based on code

**Review by DaanHoogland — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@Spaceman1984 I changed the title to what I think better descibes what is intended. please have a look.

**Comment by rhtyd** [comment]
@blueorangutan package

**Review by rhtyd — APPROVED** [review]
LGTM, let's hold on merging until @borisstoyanov @andrijapanicsb can lgtm

**Comment by rhtyd** [comment]
@Spaceman1984 pl check, build failing due to possibly code or unit test failure

**Comment by andrijapanicsb** [comment]
The internal branch work is LGTM - if this PR is a duplicate of the same code - then let's assume LGTM.

**Comment by Spaceman1984** [comment]
The branch builds fine locally, must be some kind of merge issue. Looking into it.

**Comment by Spaceman1984** [comment]
@blueorangutan package

**Comment by andrijapanicsb** [comment]
I was advised that Alex will test cc @rhtyd

**Comment by Spaceman1984** [comment]
@blueorangutan package

**Comment by Spaceman1984** [comment]
@blueorangutan test centos7 vmware-65u2

**Comment by alexandremattioli** [comment]
LGTM

**Pull request merged**
