### PR TITLE
New feature: Reserve and release Public IPs

### LINKED ISSUE #4357: To be able to Reserve IP and not allocate to VM
##### ISSUE TYPE

 * Enhancement Request
 

##### COMPONENT NAME

~~~
IP assignment,  Able to reserve IP that not auto assign to VM
~~~

##### CLOUDSTACK VERSION

~~~
Cloudstack 4.15
~~~

##### SUMMARY

Some IP address that assigned to VM, but that IP that having issue of Spamming, Blacklist etc, and after the VM being changed to new IP, the issued-ip will return to the IP Pool and future re-assign to other VM.
The system not able to reserve the problem ip which temporary do not re-assign to as it the spamming issue took time to resolve, some time it may took few months for resolving.

##### EXPECTED RESULTS

~~~
Allow mark IP as Reserve, and reserved ip shall not be auto-reassign to VM
~~~

##### ACTUAL RESULTS

Not able to reserve IP that have issue

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR provides a new feature to reserve public IPs and release them.
(1) new Public IP state: Reserved
(2) new API: reserveipaddress and releaseipaddress
(3) Reserved IP cannot be allocated to network/vms. they are considered in resource count calculation.

This fixes #4357 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Review by nvazquez — APPROVED** [review]
LGTM - manually tested:

- Create isolated network
- Navigate to public IPs -> filter Free IPS -> reserve IP
- Ensure the IP is not assigned to other deployments
- Released IP

Can we add a different color for the Reserved state, like orange? 
Screen Shot 2022-03-04 at 14 50 55

**Comment by weizhouapache** [comment]
> LGTM - manually tested:
> 
> * Create isolated network
> * Navigate to public IPs -> filter Free IPS -> reserve IP for account
> * Ensure the IP is available for acquiring new public IPs
> * Released IP
> 
> Can we add a different color for the Reserved state, like orange? Screen Shot 2022-03-04 at 14 50 55

@nvazquez 
great, thanks for testing.

Updated the PR.

**Comment by nvazquez** [comment]
Thanks @weizhouapache, looks great! Can you please raise a PR for documentation for these changes?

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
PIng for review @davidjumani @Pearl1594 @rohityadavcloud

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by Pearl1594** [comment]
Code LGTM. Small points:
- When reserving an IP for an account, it would be nice, if the account for which the IP has been reserved has the ability to release the address
- For a reserved IP address - it would be better if we could hide the Firewall, LB and protforwarding tab - this isn't major, can be addressed later too.
Thanks @weizhouapache

**Comment by weizhouapache** [comment]
> Code LGTM. Small points:
> 
> * When reserving an IP for an account, it would be nice, if the account for which the IP has been reserved has the ability to release the address
> * For a reserved IP address - it would be better if we could hide the Firewall, LB and protforwarding tab - this isn't major, can be addressed later too.
>   Thanks @weizhouapache

thanks @Pearl1594  for review

I have addressed your comments
(1) both apis are available for domain admins and regular users, same as associate/disassociate public ip
(2) the tabs on UI and other UI issues (due to vue3 upgrade) has been fixed.

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by nvazquez** [comment]
@blueorangutan test

**Review by Pearl1594 — APPROVED** [review]

**Pull request merged**
