### PR TITLE
Fix API parameter description for boottype/bootmode

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

This PR fixes API parameter description for boottype and bootmode

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [X] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [X] Trivial

### CODE REVIEW

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Review by shwstppr — APPROVED** [review]

**Review by SadiJr — APPROVED** [review]
LGTM

**Comment by nvazquez** [comment]
@blueorangutan package

**Review by nvazquez — APPROVED** [review]

**Review by GabrielBrascher — APPROVED** [review]

**Review by sureshanaparti — APPROVED** [review]
LGTM

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Pull request merged**
