### PR TITLE
Remove unused guest OS mapping class from Vmware code

### PR DESCRIPTION
**Pull request by nvazquez**
## Description
Remove unused class for guest OS - Vmware mappings. Mappings are checked from DB (guest_os_hypervisor table)

## Types of changes
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?
Class is not referenced elsewhere

### CODE REVIEW

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by andrijapanicsb** [comment]
@blueorangutan help

**Comment by andrijapanicsb** [comment]
@blueorangutan test centos7 + vmware-67u3

**Comment by andrijapanicsb** [comment]
@blueorangutan test centos7 vmware-67u3

**Pull request merged**
