### PR TITLE
Fix snapshot scheduling with expired jobs

### PR DESCRIPTION
**Pull request by hsato03**
### Description

During the snapshot process of a scheduled snapshot, if the time to create the snapshot is greater than the value of the `job.expire.minutes` global setting, both `async_job` and `snapshot_schedule` records are removed from the database due to the `ON DELETE CASCADE` constraint present in the `async_job_id` foreign key of the `snapshot_schedule` table. This causes snapshot scheduling to stop working as the record of the last `snapshot_schedule` must exist to schedule the next one.

Therefore, the `async_job_id` constraint was removed so that an expired job does not trigger the removal of the scheduled snapshot.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### How Has This Been Tested?

I followed the same steps from `How did you try to break this feature and the system with this change?` and verified that the `async_job` was removed but the `snapshot_schedule` was not and the recurring snapshots were working.

#### How did you try to break this feature and the system with this change?

1. Change the `job.expire.minutes` global setting value to `1`;
2. Create a recurring snapshot for a volume;
3. Wait until the snapshot starts and `async_job` is removed;
4. The `snapshot_schedule` is also removed and the next snapshot is not scheduled.

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
CLGTM, nice cleanup as well as fix

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test alma9 kvm-alma9

**Comment by DaanHoogland** [comment]
@blueorangutan test alma9 kvm-alma9

**Comment by borisstoyanov** [comment]
@hsato03 could you look into the merge conflicts please.

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by JoaoJandre** [comment]
Hey @DaanHoogland , could we run the CI?

**Review by kiranchavala — APPROVED** [review]
LGTM 

Steps to follow

 
1. Change the job.expire.minutes global setting value to 1;
2. Create a recurring snapshot for a volume;
3. Wait until the snapshot starts and async_job is removed;
4. The snapshot_schedule is also removed and the next snapshot is not scheduled.
5. Cross check the database entries 


Before fix 

mysql> select * from snapshot_schedule \G;
Empty set (0.00 sec)


---
After fix 



```
mysql> select * from snapshot_schedule;
+----+--------------------------------------+-----------+-----------+---------------------+--------------+-------------+
| id | uuid                                 | volume_id | policy_id | scheduled_timestamp | async_job_id | snapshot_id |
+----+--------------------------------------+-----------+-----------+---------------------+--------------+-------------+
|  2 | 1ca75a38-6ccf-408d-97e7-14f4c9bd2d96 |         7 |         2 | 2024-08-21 04:31:00 |         NULL |        NULL |
+----+--------------------------------------+-----------+-----------+---------------------+--------------+-------------+
1 row in set (0.00 sec)
```

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by hsato03** [comment]
Thanks @kiranchavala

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Pull request merged**
