### PR TITLE
Improve error messaging / logs when listing VMs on the remote KVM host (for import)

### PR DESCRIPTION
**Pull request by sureshanaparti**
### Description

This PR improves error messaging / logs when listing VMs on the remote KVM host (for import).

Addresses appropriate messages aa per the comments on #8704.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

Manually tested list VMs on the remote KVM host.

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Review by DaanHoogland — COMMENTED** [review]
clgtm, though I am not so sure about adding stack traces to error messages.

**Review by borisstoyanov — CHANGES_REQUESTED** [review]
When trying to list hosts I got this error: 

```

2024-06-11 08:46:01,634 DEBUG [c.c.a.t.Request] (AgentManager-Handler-10:null) (logid:) Seq 1-5872693914091126914: Processing:  { Ans: , MgmtId: 32986691010854, via: 1, Ver: v1, Flags: 10, [{"com.cloud.agent.api.Answer":{"result":"false","details":"Unable to connect to remote host 10.0.32.168, please check the libvirtd tcp connectivity and retry","wait":"0","bypassHostMaintenance":"false"}}] }
2024-06-11 08:46:01,634 DEBUG [c.c.a.t.Request] (qtp931675031-19:ctx-90519523 ctx-a268b381) (logid:8483a0e7) Seq 1-5872693914091126914: Received:  { Ans: , MgmtId: 32986691010854, via: 1(ref-trl-6794-k-Mr8-boris-stoyanov-kvm1), Ver: v1, Flags: 10, { Answer } }
2024-06-11 08:46:01,634 DEBUG [c.c.a.m.AgentManagerImpl] (qtp931675031-19:ctx-90519523 ctx-a268b381) (logid:8483a0e7) Details from executing class com.cloud.agent.api.GetRemoteVmsCommand: Unable to connect to remote host 10.0.32.168, please check the libvirtd tcp connectivity and retry
2024-06-11 08:46:01,634 ERROR [c.c.a.ApiServer] (qtp931675031-19:ctx-90519523 ctx-a268b381) (logid:8483a0e7) unhandled exception executing api command: [Ljava.lang.String;@1c3e3d70
com.cloud.utils.exception.CloudRuntimeException: Failed to list VMs, due to: Unable to connect to remote host 10.0.32.168, please check the libvirtd tcp connectivity and retry
	at org.apache.cloudstack.vm.UnmanagedVMsManagerImpl.getRemoteVmsOnKVMHost(UnmanagedVMsManagerImpl.java:2488)
	at org.apache.cloudstack.vm.UnmanagedVMsManagerImpl.listVmsForImport(UnmanagedVMsManagerImpl.java:2463)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy464.listVmsForImport(Unknown Source)
	at org.apache.cloudstack.api.command.admin.vm.ListVmsForImportCmd.execute(ListVmsForImportCmd.java:121)
	at com.cloud.api.ApiDispatcher.dispatch(ApiDispatcher.java:172)
	at com.cloud.api.ApiServer.queueCommand(ApiServer.java:803)
	at com.cloud.api.ApiServer.handleRequest(ApiServer.java:624)
	at com.cloud.api.ApiServlet.processRequestInContext(ApiServlet.java:342)
	at com.cloud.api.ApiServlet$1.run(ApiServlet.java:149)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
	at com.cloud.api.ApiServlet.processRequest(ApiServlet.java:146)
	at com.cloud.api.ApiServlet.doGet(ApiServlet.java:100)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:645)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1450)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:554)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:772)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:829)
2024-06-11 08:46:01,637 DEBUG [c.c.a.ApiServlet] (qtp931675031-19:ctx-90519523 ctx-a268b381) (logid:8483a0e7) ===END===  10.0.3.251 -- GET  zoneid=1ed242ee-e3ec-441a-b43c-3ebb4245fa18&page=1&pagesize=10&host=10.0.32.168&username=root&hypervisor=kvm&command=listVmsForImport&response=json
2024-06-11 08:46:01,827 DEBUG [c.c.a.ApiServlet] (qtp931675031-15:ctx-006d5079) (logid:e3611c60) ===START===  10.0.3.251 -- GET  command=readyForShutdown&response=json
2024-06-11 08:46:01,827 DEBUG [c.c.a.ApiServlet] (qtp931675031-15:ctx-006d5079) (logid:e3611c60) Two factor authentication is
```

Not sure if something extra needs to be configured at the host side, but it's a standard host that we've been using all the time.

**Review by borisstoyanov — APPROVED** [review]
LGTM, configured it properly and checked it manually

**Pull request merged**
