### PR TITLE
Fix network GC error that's failing a smoketests on master

### LINKED ISSUE #2935: Network GC error on master/4.12
On latest master/4.12, network GC mysql errors are seen:

```
2018-10-27 15:17:05,819 WARN  [o.a.c.e.o.NetworkOrchestrator] (Network-Scavenger-1:ctx-db281a94) (logid:2d18453c) Caught exception while running network gc:
com.cloud.utils.exception.CloudRuntimeException: Caught: com.mysql.jdbc.JDBC4PreparedStatement@64b5357b: SELECT networks.id FROM networks  INNER JOIN network_offerings ON networks.network_offering_id=network_offerings.id  INNER JOIN op_networks ON networks.id=op_networks.id WHERE networks.removed IS NULL  AND  (op_networks.nics_count = ** NOT SPECIFIED **  AND op_networks.gc = ** NOT SPECIFIED **  AND op_networks.check_for_gc = ** NOT SPECIFIED ** )
        at com.cloud.utils.db.GenericDaoBase.customSearchIncludingRemoved(GenericDaoBase.java:507)
        at com.cloud.utils.db.GenericDaoBase.customSearch(GenericDaoBase.java:518)
        at com.cloud.network.dao.NetworkDaoImpl.findNetworksToGarbageCollect(NetworkDaoImpl.java:461)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:338)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:197)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at com.cloud.utils.db.TransactionContextInterceptor.invoke(TransactionContextInterceptor.java:34)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy64.findNetworksToGarbageCollect(Unknown Source)
        at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator$NetworkGarbageCollector.reallyRun(NetworkOrchestrator.java:2761)
        at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator$NetworkGarbageCollector.runInContext(NetworkOrchestrator.java:2745)

```

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Mgmt server, network/db
~~~

##### CLOUDSTACK VERSION

~~~
master/4.12
~~~

### PR DESCRIPTION
**Pull request by rhtyd**
This PR attempts to fix various test failures on master:

1. Fixes #2935: This fixes the variable name to adhere to the DB framework convention
as defined by the method interceptor that creates attributes:

https://github.com/apache/cloudstack/blob/master/framework/db/src/main/java/com/cloud/utils/db/SearchBase.java#L480

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by rhtyd** [comment]
@rafaelweingartner @GabrielBrascher guys this is still in progress, unfortunately, I'm unable to work on stabilizing failing master smoketests this week, I'll try next week. I think there are a few in Travis+{smoke, component}-tests and few on Trillian+smoketests. If you've time, please feel free to fix and push changes to the branch (acs committers can do that on any PRs).

**Comment by rafaelweingartner** [comment]
Ah, so you are not targeting a single problem. Thanks for the first fix.

**Comment by GabrielBrascher** [comment]
I also thought it was targeting a single problem; I saw that it fixed some tests and imagined it was all good to go. Thanks for the effort @rhtyd!

**Comment by rhtyd** [comment]
I'm not sure when I'll be able to fix other issues, I'll proceed with merging this based on Travis smoketests that at least fix the network gc error.

**Comment by rafaelweingartner** [comment]
Thanks @rhtyd. Gabriel and I are actually working on the other issues already. I decided to open a PR per issue, since it gets easier to review and to discuss them.

Thanks for this one ;)

**Pull request merged**
