### PR TITLE
CLOUDSTACK-9513 Migrate transifex workflow and format to json

### PR DESCRIPTION
**Pull request by milamberspace**
Move the localization resource files from Java Properties format to JSON Key-Value format
Change the Transifex sync script to handle JSON resource files instead of Properties files
Update the README
Remove old version from the Transifex configuration file
Remove unused gen-l10n.py script and update the ui/pom.xml to remove the execution of this script

cc @rhtyd @jburwell

### CODE REVIEW

**Comment by rhtyd** [comment]
Sweet! Thanks @milamberspace I was going to send this in few days, but you beat me to it :)
I'll review this tomorrow and get back to you.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by jburwell** [comment]
I will add this PR to the list to merge post resolution of #1692

**Comment by rhtyd** [comment]
+1 LGTM

Screenshots:

screenshot from 2016-10-04 11-36-28

screenshot from 2016-10-04 11-43-01

**Comment by borisstoyanov** [comment]
+ 1 LGTM 

Looks like all available labels are presented, if not defaults to english. 

Screenshots of Russian and Korean: 
screen shot 2016-10-04 at 12 40 54 pm
screen shot 2016-10-04 at 12 42 23 pm

**Comment by rhtyd** [comment]
Thanks @milamberspace for the PR.
Since, it's a pure UI change and with Travis and packaging passing and enough test runs and reviews I'll proceed with merging this one.

**Pull request merged**
