### PR TITLE
Merged 4.18 to 4.19

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR...

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@vishesh92 
This will lose the information of 4.18 commits
You can fix the merge conflicts if exists, and  push to github if build is successful.

**Comment by vishesh92** [comment]
> @vishesh92 This will lose the information of 4.18 commits You can fix the merge conflicts if exists, and push to github if build is successful.

@weizhouapache I don't have access to push directly to apache/cloudstack repo.

**Comment by weizhouapache** [comment]
> > @vishesh92 This will lose the information of 4.18 commits You can fix the merge conflicts if exists, and push to github if build is successful.
> 
> @weizhouapache I don't have access to push directly to apache/cloudstack repo.

oh, right, you are not a committer yet.

currently only "Squash and merge" is allowed when merge a PR. 
image
 @rohityadavcloud @DaanHoogland  and any committers can merge forward the branches.

**Comment by rohityadavcloud** [comment]
I'll do this manually thanks @vishesh92

**Pull request closed without merging**
