### PR TITLE
ui: Show memory allocated percentage when migrating vm

### PR DESCRIPTION
**Pull request by davidjumani**
### Description

This PR  adds the memory allocated percentage to the migrate wizard form, since just seeing the used memory may not be enough

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

### Screenshots (if appropriate):
Screenshot from 2021-03-10 12-46-48

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan ui

**Review by utchoang — APPROVED** [review]
LGTM!

**Review by shwstppr — APPROVED** [review]
LGTM. Tested with a VMware env
Screenshot from 2021-03-10 13-53-39

**Pull request merged**
