### PR TITLE
CLOUDSTACK-9950:listUsageRecords doesnt return required fields

### PR DESCRIPTION
**Pull request by mrunalinikankariya**
There is no cpuspeed, cpunumber or memory details in the listUsageRecords output as documented
In DB (cloud_usage table) we have cpu_speed, cpu_cores and ram fileds, but these are not populated for all the VM's. These fields are only populated for the VM's which are deployed with custom service offerings.

### CODE REVIEW

**Comment by SudharmaJain** [comment]
LGTM code changes.

**Comment by mrunalinikankariya** [comment]
This has already been fixed by Venkata Yedugundla, so closing this request

**Comment by rhtyd** [comment]
LGTM.

**Comment by rhtyd** [comment]
Merging based on Travis checks and code review, explicit Trillian tests are not necessary.

**Pull request merged**
