### PR TITLE
Set version 4.8.0-SNAPSHOT in master branch

### PR DESCRIPTION
**Pull request by remibergsma**
- setnextversion.sh
- upgrade path to `4.8.0` via `4.7.0` -> `4.7.1` as this is the one set in `4.7` branch. Then we also have the next minor release of `4.7` covered.

Build succeeds:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10:07 min
[INFO] Finished at: 2015-12-21T22:45:41+01:00
[INFO] Final Memory: 124M/1609M
[INFO] ------------------------------------------------------------------------
```

Will run upgrade test soon and post results.

### CODE REVIEW

**Comment by pdion891** [comment]
LGTM  already 4.8 ! :-)

**Comment by pdube** [comment]
Code reviewed. Nothing out of the ordinary. LGTM. There must be a better way to do it than to manually add it to each and every migration though.

**Comment by remibergsma** [comment]
@pdube Indeed, as we speed up releases this becomes a real bottleneck. We should handle db upgrades out of the repo. There was some discussion already. Let's see how others solve this problem ;-)

**Comment by remibergsma** [comment]
Tested upgrade, works fine:
```
INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Grabbing lock to check for database upgrade.
INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) DB version = 4.7.1 Code Version = 4.8.0-SNAPSHOT
INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Database upgrade must be performed from 4.7.1 to 4.8.0-SNAPSHOT
INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Cleaning upgrades because all management server are now at the same version
INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Cleanup upgrade Upgrade471to480 to upgrade from 4.7.1-4.8.0 to 4.8.0
INFO  [o.a.c.s.l.CloudStackExtendedLifeCycle] (main:null) (logid:) Configuring CloudStack Components
INFO  [o.a.c.s.l.CloudStackExtendedLifeCycle] (main:null) (logid:) Done Configuring CloudStack Components
```

**Pull request merged**
