### PR TITLE
Move user shared networks tests to component tests

### PR DESCRIPTION
**Pull request by nvazquez**
### Description

This PR moves the user shared networks tests for component tests

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

### CODE REVIEW

**Comment by nvazquez** [comment]
@blueorangutan package

**Review by weizhouapache — APPROVED** [review]

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
travis tests passed :+1:

**Review by Pearl1594 — APPROVED** [review]

**Comment by nvazquez** [comment]
@blueorangutan package

**Pull request merged**
