### PR TITLE
router: support multi-homed VMs in VPC

### LINKED ISSUE #3273: VR DHCP VPC multihomed VM broken
##### ISSUE TYPE
* Bug Report - BLOCKER

##### COMPONENT NAME
* VR dnsmasq DHCP

##### CLOUDSTACK VERSION
* ACS 4.11.2
* ACS 4.12 not tested but assumed issues are still present looking at code changes
* Regressions from / previously present in ACS 4.9 / 4.10 / 4.11

##### REFERENCES
1) PR2427 - CLOUDSTACK-10252: Delete dnsmasq leases file on restart /  https://github.com/apache/cloudstack/pull/2427
2) Old Jira issue: VR DNSmasq lease file not persistent across DHCP actions
 / https://issues.apache.org/jira/browse/CLOUDSTACK-10204
3) Old Jira issue: New VR after network restart with cleanup is missing DNS and DHCP entries
 / https://issues.apache.org/jira/browse/CLOUDSTACK-10167
4) Finite lease introduction in https://github.com/apache/cloudstack/pull/1547
5) Also check related issue https://github.com/apache/cloudstack/issues/3272

##### CONFIGURATION
* ACS4.11.2
* Isolated guest networks and VPC networks

##### OS / ENVIRONMENT
* Any

##### SUMMARY
VPC multihomed VMs DHCP partially broken:

What still works:
* VM with isolated network primary NIC and shared secondary NIC seems to work OK, VM gets both DHCP leases and Default GW appears on primary NIC only as expected. Checking /etc/dhcphosts.txt on secondary NIC shared network VR shows the DHCP address is tagged (set) and DHCP options set as per /etc/dhcpops.txt.
* VM with two isolated networks attached works the same way - both primary NIC and secondary NIC get DHCP leases, secondary NIC DHCP (on separate VR) sets the right tags and ensures no DG and no DHCP options 3/6/15.
* VM with primary VPC tier and secondary NIC on isolated network - works as above.
* VM with primary VPC tier and secondary NIC on shared network - works as above 
* VM with primary isolated network and secondary NIC on VPC tier - works as above.
* VM with primary shared network and secondary NIC on VPC tier - works
* VMs with primary and secondary NIC on two different VPCs (actual VPCs, not tiers) - also works OK, secondary NIC again not set up with DG etc.

What is very broken:
* VM with multiple NICs attached to different VPC tiers in the same VPC fail to get DHCP address on it's primary NIC.
* General file / setting management around this also not right - e.g. the cloud.conf file ends up with duplicate entries

##### STEPS TO REPRODUCE
VPC VR tier VMs not getting DHCP leases:
* VPC created: super CIDR is 10.21.0.0/16, tier1 is 10.21.1.0/24, tier2 is 10.21.2.0/24
* VM created and attached to one tier1 only.
* VM at this point gets DHCP address OK on eth0
* VR files
root@r-339-VM:~# cat /etc/dhcphosts.txt
02:00:2c:78:00:01,10.21.1.33,CROSSTIER1,723h
root@r-339-VM:~# cat /var/lib/misc/dnsmasq.leases
1557669293 02:00:2c:78:00:01 10.21.1.33 CROSSTIER1

* Second VPC tier2 added to VM, all lease files removed and VM restarted
* VM comes online with no DHCP lease for eth0 but dhcp lease for eth1.
* /etc/dhcphosts is found to be empty:
root@r-339-VM:~# cat /etc/dnsmasq.d/dhcphosts.txt
<blank>

* Leases file show only the eth1 lease - BUT note this is not marked ("set") as being a secondary NIC:
root@r-339-VM:~# cat /var/lib/misc/dnsmasq.leases
1557806022 02:00:5e:96:00:03 10.21.2.238 CROSSTIER1

* Note /etc/dhcpopts.txt is populated as it should be when a NIC is secondary - although there is no tag matching that will make this active:
root@r-339-VM:~# cat /etc/dhcpopts.txt
10_21_2_238,3
10_21_2_238,6
10_21_2_238,15

* Probably unrelated (unknown what this file is used for) but the /etc/dnsmasq.d/dhcphosts.txt file is also empty:
root@r-339-VM:~# cat /etc/dnsmasq.d/dhcphosts.txt
<blank>

* Checking the /etc/dnsmasq.d/cloud.conf file which contains the defaults for each tier it is however found this is now double populated for each of the two tiers:
root@r-339-VM:~# cat /etc/dnsmasq.d/cloud.conf
dhcp-hostsfile=/etc/dhcphosts.txt
dhcp-range=set:interface-eth2-0,10.21.2.1,static
dhcp-option=tag:interface-eth2-0,15,cs2cloud.internal
dhcp-option=tag:interface-eth2-0,6,10.21.2.1,8.8.8.8,8.8.4.4
dhcp-option=tag:interface-eth2-0,3,10.21.2.1
dhcp-option=tag:interface-eth2-0,1,255.255.255.0
dhcp-range=set:interface-eth3-1,10.21.1.1,static
dhcp-option=tag:interface-eth3-1,15,cs2cloud.internal
dhcp-option=tag:interface-eth3-1,6,10.21.1.1,8.8.8.8,8.8.4.4
dhcp-option=tag:interface-eth3-1,3,10.21.1.1
dhcp-option=tag:interface-eth3-1,1,255.255.255.0
dhcp-range=set:interface-eth3-0,10.21.1.1,static
dhcp-option=tag:interface-eth3-0,15,cs2cloud.internal
dhcp-option=tag:interface-eth3-0,6,10.21.1.1,8.8.8.8,8.8.4.4
dhcp-option=tag:interface-eth3-0,3,10.21.1.1
dhcp-option=tag:interface-eth3-0,1,255.255.255.0
dhcp-range=set:interface-eth2-1,10.21.2.1,static
dhcp-option=tag:interface-eth2-1,15,cs2cloud.internal
dhcp-option=tag:interface-eth2-1,6,10.21.2.1,8.8.8.8,8.8.4.4
dhcp-option=tag:interface-eth2-1,3,10.21.2.1
dhcp-option=tag:interface-eth2-1,1,255.255.255.0

* Logs show eth1 not being present in host file:
Apr 12 11:52:41 dnsmasq-dhcp[5302]: DHCPDISCOVER(eth3) 02:00:2c:78:00:01 no address available
Apr 12 11:52:44 dnsmasq-dhcp[5302]: DHCPDISCOVER(eth3) 02:00:2c:78:00:01 no address available
Apr 12 11:52:52 dnsmasq-dhcp[5302]: DHCPDISCOVER(eth3) 02:00:2c:78:00:01 no address available
Apr 12 11:53:07 dnsmasq-dhcp[5302]: DHCPDISCOVER(eth3) 02:00:2c:78:00:01 no address available
Apr 12 11:53:24 dnsmasq-dhcp[5302]: DHCPDISCOVER(eth3) 02:00:2c:78:00:01 no address available
Apr 12 11:53:42 dnsmasq-dhcp[5302]: DHCPDISCOVER(eth2) 02:00:5e:96:00:03
Apr 12 11:53:42 dnsmasq-dhcp[5302]: DHCPOFFER(eth2) 10.21.2.238 02:00:5e:96:00:03
Apr 12 11:53:42 dnsmasq-dhcp[5302]: DHCPREQUEST(eth2) 10.21.2.238 02:00:5e:96:00:03
Apr 12 11:53:42 dnsmasq-dhcp[5302]: DHCPACK(eth2) 10.21.2.238 02:00:5e:96:00:03 CROSSTIER1

##### EXPECTED RESULTS
* VM getting DHCP lease on all interfaces, with secondary NIC not getting DG etc.

##### ACTUAL RESULTS
* VM getting DHCP lease on eth1 only, not on eth0

### PR DESCRIPTION
**Pull request by rhtyd**
This does not remove VM entries in dbags when hostnames match. The
current codebase already removes entry when a VM is stopped/removed so
we don't need to handle lazy removal. This will allow a VM on
multiple-tiers in a VPC to get dns/dhcp rules as expected.

This also fixes the issue of dhcp_release based on a specific interface.

Fixes #3273

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by rhtyd** [comment]
To test it, I deployed a VM with a VPC with two tiers. By adding two nics on the VPC's tier1 and tier2, I could confirm that VM gets dhcp/dns rules:

Screenshot from 2019-06-04 17-09-06

Outputs from the VPC VR:
```
root@r-3-VM:/opt/cloud/bin# cat /etc/dhcphosts.txt
02:00:3e:91:00:04,set:10_21_2_53,10.21.2.53,VM-91dd442b-d87f-482c-889f-76e6da5bae17,750h
02:00:7d:b9:00:05,10.21.1.175,VM-91dd442b-d87f-482c-889f-76e6da5bae17,735h

root@r-3-VM:/opt/cloud/bin# cat /etc/hosts
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
10.21.1.175     VM-91dd442b-d87f-482c-889f-76e6da5bae17
::1     localhost ip6-localhost ip6-loopback
10.21.2.53      VM-91dd442b-d87f-482c-889f-76e6da5bae17
127.0.0.1       localhost r-3-VM

root@r-3-VM:/opt/cloud/bin# cat /var/lib/misc/dnsmasq.leases
1562348805 02:00:3e:91:00:04 10.21.2.53 VM-91dd442b-d87f-482c-889f-76e6da5bae17 *
1562294389 02:00:7d:b9:00:05 10.21.1.175 * 01:02:00:7d:b9:00:05
```

@blueorangutan package

**Comment by rhtyd** [comment]
Can you help review this - @ustcweizhou @shwstppr @anuragaw, thanks.

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
Thanks for testing and reviewing @nvazquez - it's likely that when nic is removed the rules are not removed from the VR. I'll test and try to fix the case you've found tomorrow. Cheers!

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by ustcweizhou** [comment]
code LGTM
did not test it.

**Comment by rhtyd** [comment]
Thanks @nvazquez and @ustcweizhou 
I'll merge this based on the latest test results and reviews.

**Pull request merged**
