### PR TITLE
server: save GUID for KVM cluster

### PR DESCRIPTION
**Pull request by rhtyd**
When a KVM host is added to a cluster, the cluster GUID is null. In case
the KVM host fails to be added, the GUID is null and if any
other hosts are added an exception is thrown by the resource manager
that does not allow addition of hosts to a cluster with existing hosts
whose GUID is null.

In case of KVM, other hosts may be added in parallel therefore this
restriction can be safely removed.

Issue references:
http://mail-archives.apache.org/mod_mbox/cloudstack-users/201604.mbox/%3Cloom.20160415T120602-157@post.gmane.org%3E
http://mail-archives.apache.org/mod_mbox/cloudstack-users/201306.mbox/%3C1F7751C3-DB29-4639-9E67-9760B07C9A5B@gmail.com%3E

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?
Tested in a local centos7.6+kvm env:

Deployed mgmt server
Made sys.exit(1) in the cloudstack-setup-agent script
Deployed zone, added the host
Host error-ed out, no entries saved in cloud.host table, re-added passed

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by ustcweizhou** [comment]
code LGTM

merge into 4.11 as well ?

**Comment by rhtyd** [comment]
@ustcweizhou we've missed the 4.11.3.0 milestone freeze window, RC1 is already out and this is not a blocker issue.

**Comment by rhtyd** [comment]
Merging based on tests and reviews.

**Comment by ustcweizhou** [comment]
> @ustcweizhou we've missed the 4.11.3.0 milestone freeze window, RC1 is already out and this is not a blocker issue.

ok. maybe we can add it to 4.11 branch after 4.11.3 release

**Comment by rhtyd** [comment]
@ustcweizhou this is not a critical/blocker issue, and only reproducible when there is no KVM host in a cluster that gets successfully added within the default/hardcoded wait time (of 2*5 mins). Sure, feel free to backport to 4.11.

**Pull request merged**
