### PR TITLE
[master/4.10+] CLOUDSTACK-9462: Support for Ubuntu 14.04/16.04 with tomcat6/tomcat7

### PR DESCRIPTION
**Pull request by rhtyd**
This extends work from @ustcweizhou from https://github.com/apache/cloudstack/pull/1950 by fixing some build issues to make this work with Ubuntu 14.04 and 16.04.

This closes #1950

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test ubuntu kvm-ubuntu

**Comment by rhtyd** [comment]
I've checked this on Trillian, LGTM. While I've ports this PR, the work is by @ustcweizhou 
Pinging for review -- @wido @ustcweizhou @abhinandanprateek @DaanHoogland @karuturi

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test ubuntu kvm-ubuntu

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@karuturi this is ready for merge
Pinging for review - @wido @ @ustcweizhou

**Comment by wido** [comment]
LGTM

Just tested on Ubuntu 16.04 and works

**Comment by karuturi** [comment]
@rhtyd Can you add "This closes #1950" to the description of this PR?
can you force push to make jenkins happy? 

@ustcweizhou can you review please?

**Comment by ustcweizhou** [comment]
@karuturi LGTM. I did not see big difference from #1950

**Comment by rhtyd** [comment]
@karuturi done, thanks.

**Comment by rhtyd** [comment]
@ustcweizhou thanks, yes there is a minor difference around the init-helper version that's all 
@karuturi jenkins/travis re-kicked.
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test ubuntu kvm-ubuntu

**Pull request merged**
