### PR TITLE
Fix LibvirtStorageAdaptor.java

### PR DESCRIPTION
**Pull request by cl-k-takahashi**
## Description

I fixed createNetfsStoragePool() function in LibvirtStorageAdaptor.java.
The current implementation of createNetfsStoragePool() does not unmount already mounted pool in non-English environment so I edited it to check the pool is already mounted using mountpoint command and unmount the pool if already mounted.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?
I got the following output in agent.log in a KVM hypervisor host:
```
2018-06-06 19:51:26,059 INFO  [kvm.storage.LibvirtStorageAdaptor] (agentRequest-Handler-5:null) (logid:293e0c5c) Attempting to unmount old mount at /mnt/00ec8deb-14b2-3264-bd61-4bf38f4bccc5
2018-06-06 19:51:26,090 INFO  [kvm.storage.LibvirtStorageAdaptor] (agentRequest-Handler-5:null) (logid:293e0c5c) Succeeded in unmounting /mnt/00ec8deb-14b2-3264-bd61-4bf38f4bccc5
```
This output indicates already-mounted mountpoint /mnt/00ec8deb-14b2-3264-bd61-4bf38f4bccc5 is successfully unmounted.

## Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
Testing
- [ ] I have added tests to cover my changes.
- [ ] All relevant new and existing integration tests have passed.
- [ ] A full integration testsuite with all test that can run on my environment has passed.

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by wido** [comment]
@DaanHoogland Yes, I understand, we check for "already mounted" in the code.

However, my main point is, why do we manually unmount. Destroying the pool in libvirt should make sure the mountpoint is gone.

**Comment by DaanHoogland** [comment]
so @wido your objection is to ```Script.runSimpleBashScript("umount -l " + targetPath);```? I would agree to that but it is not part of this change. Do you propose to change this change to deal with that in one go?

**Comment by wido** [comment]
Hmm, yes, I understand you. It would be better if libvirt would handle all this, but it's indeed not part of this PR.

**Comment by cl-k-takahashi** [comment]
@DaanHoogland The current implementation detects "already mounted" in e.toString() but e.toString() is language configuration dependent. In Japanese environment, it gives "すでにマウントされています" instead of "already mounted" and the KVM agent doesn't unmount the pool.

**Comment by DaanHoogland** [comment]
yes @cl-k-takahashi we understand that.
@wido do you accept the change as is?

**Comment by rhtyd** [comment]
Test LGTM, merging this based on code reviews and test results, as well as manual testing of mountpoint tool on centos6, centos7 and ubuntu 16.04/18.04.

**Pull request merged**
