### PR TITLE
Don't allow service offering change if encryption value would change

### PR DESCRIPTION
**Pull request by mlsorensen**
Signed-off-by: Marcus Sorensen <mls@apple.com>

### Description

This PR blocks change of service offering if the offering root volume encryption values don't match.  We don't support dynamically removing or adding encryption to a VM.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### How Has This Been Tested?

Tested prior to this change - could move from non-encrypted to encrypted offerings.

Tested after this change - clean error indicating the encryption type must not change if selected offering does not match current offering encryption setting. Tested both compute-only disk offering and service offering referencing existing disk offerings.

Tested:
* Service offering with compute-only disk offerings
* Service offering with compute referencing disk offerings
* Trying to go from encrypted to non-encrypted
* Trying to go from non-encrypted to encrypted
* VM referencing deleted disk offering still correctly blocks move to offering with different encryption setting

Screen Shot 2022-09-27 at 2 19 45 PM

### CODE REVIEW

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
@mlsorensen can you add a unit or marvin test for the same if feasible?
@blueorangutan package

**Comment by mlsorensen** [comment]
@rohityadavcloud I'm really not sure how to do that.  I'm aware of the smoke tests but as far as understanding what is actually going to be run on PR, and how to actually get a local environment to develop against (Marvin seems to be pretty heavy handed about setting up zones and networking in a specific way during setup for a test, for example I can't just pick a VM test and run it against any existing zone using existing networks and offerings... or can I?). Honestly we would add dozens of tests if we understood how the target environment works and it were easy to iterate on.

**Comment by mlsorensen** [comment]
I can probably add a unit test for this since the method is isolated... working.

**Comment by rohityadavcloud** [comment]
@mlsorensen you can for example write a simple marvin test to (1) create an offering with encryption enabled, (2) deploy VM using that, (3) stop the VM if necessary and try changing its offering to one of the available default offerings that don't have an encryption enabled. Since this test is checking only the business logic, it may even run as a simulator test (and therefore also on Travis). To run a local (kvm/vmware/xen) env, you can deploy them as VMs on your workstations (or remote server with your workstation joined over VPN), or use something like https://github.com/shapeblue/mbx to tests using built pkgs.

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Comment by mlsorensen** [comment]
> @mlsorensen you can for example write a simple marvin test to (1) create an offering with encryption enabled, (2) deploy VM using that, (3) stop the VM if necessary and try changing its offering to one of the available default offerings that don't have an encryption enabled. Since this test is checking only the business logic, it may even run as a simulator test (and therefore also on Travis), and very easy to run smoketests against simulator (https://github.com/shapeblue/hackerbook/blob/main/2-dev.md#simulator-based-development).
> 
> To run a local (kvm/vmware/xen) env, you can deploy them as VMs on your workstations (or remote server with your workstation joined over VPN), or use something like https://github.com/shapeblue/mbx to tests using built pkgs.

Cool, thanks @rohityadavcloud. I'm aware of these (we use simulator quite a bit w/containers) but the gaps are elsewhere, maybe we can meet and discuss. 

One is really around environment overload. I already have several environments I maintain for development that represent real configurations. It's a bit cumbersome to then set up yet another VM instance as a blank slate for each dev cycle of smoke testing (or automate it), I'm not aware of how to run Marvin tests against an existing dev environment since many of the tests make assumptions about the environment.  Likewise I don't really understand the environment that is under test by Trillian and how to reproduce it in a way that I can develop tests which will work there.

The other is understanding of which tests actually will be run in the community on every PR vs tests that aren't and which tests are run when. It looked like maybe there are some decorators that manage this.

I'd love to just be able to run `mvn test -Dfunctests` or similar and everything that would normally run during PR gets tested, even if that includes starting up a java instance and some containers.

**Review by rohityadavcloud — APPROVED** [review]
Unit test LGTM

**Review by shwstppr — APPROVED** [review]

**Pull request merged**
