### PR TITLE
Use lowercase HTTP header field names so we are compatible with HTTP/2

### PR DESCRIPTION
**Pull request by jbampton**
"Just as in HTTP/1.x, header field names are strings of ASCII characters that are compared in a case-insensitive fashion. However, header field names MUST be converted to lowercase prior to their encoding in HTTP/2. A request or response containing uppercase header field names MUST be treated as malformed (Section 8.1.2.6)."

https://www.rfc-editor.org/rfc/rfc7540#section-8.1.2

https://web.dev/performance-http2/

### Description

This PR changes some HTTP header field names to lowercase.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [X] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [X] Trivial

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@jbampton debian packaging fails with 
```
10:15:41 [INFO] Scanning for projects...
10:15:42 [ERROR] [ERROR] Some problems were encountered while processing the POMs:
10:15:43 [FATAL] Non-resolvable parent POM for org.apache.cloudstack:cloud-framework-ipc:4.18.0.0-SNAPSHOT: Could not find artifact org.apache.cloudstack:cloudstack-framework:pom:4.18.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 24, column 13
10:15:43 [FATAL] Non-resolvable parent POM for org.apache.cloudstack:cloud-framework-jobs:4.18.0.0-SNAPSHOT: Could not find artifact org.apache.cloudstack:cloudstack-framework:pom:4.18.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 24, column 13
10:15:43  @ 
10:15:43 [ERROR] The build could not read 2 projects -> [Help 1]
10:15:43 [ERROR]   
10:15:43 [ERROR]   The project org.apache.cloudstack:cloud-framework-ipc:4.18.0.0-SNAPSHOT (/jenkins/workspace/acs-deb-pkg-builder/framework/ipc/pom.xml) has 1 error
10:15:43 [ERROR]     Non-resolvable parent POM for org.apache.cloudstack:cloud-framework-ipc:4.18.0.0-SNAPSHOT: Could not find artifact org.apache.cloudstack:cloudstack-framework:pom:4.18.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 24, column 13 -> [Help 2]
10:15:43 [ERROR]   
10:15:43 [ERROR]   The project org.apache.cloudstack:cloud-framework-jobs:4.18.0.0-SNAPSHOT (/jenkins/workspace/acs-deb-pkg-builder/framework/jobs/pom.xml) has 1 error
10:15:43 [ERROR]     Non-resolvable parent POM for org.apache.cloudstack:cloud-framework-jobs:4.18.0.0-SNAPSHOT: Could not find artifact org.apache.cloudstack:cloudstack-framework:pom:4.18.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 24, column 13 -> [Help 2]
10:15:43 [ERROR] 
10:15:43 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
10:15:43 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
10:15:43 [ERROR] 
10:15:43 [ERROR] For more information about the errors and possible solutions, please read the following articles:
10:15:43 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
10:15:43 [ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
10:15:43 debian/rules:16: recipe for target 'override_dh_auto_build' failed
10:15:43 make[1]: *** [override_dh_auto_build] Error 1
10:15:43 make[1]: Leaving directory '/jenkins/workspace/acs-deb-pkg-builder'
10:15:43 debian/rules:9: recipe for target 'binary' failed
10:15:43 make: *** [binary] Error 2
10:15:43 dpkg-buildpackage: error: debian/rules binary gave error exit status 2
10:15:43 Build step 'Execute shell' marked build as failure
```
this happens consequently and is after the build succeeds.

**Review by BryanMLima — APPROVED** [review]

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@BryanMLima did you already test this? (I didn´t yet)

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by BryanMLima** [comment]
@DaanHoogland I only reviewed the code, as it was a simple change, I did not tested.

**Comment by DaanHoogland** [comment]
No problem @BryanMLima , it was tested a bit, and we will fully regression test the Release so it will be checked anyway.

**Pull request merged**
