### PR TITLE
UI: add a provider for primary storage when adding zone wizard

### PR DESCRIPTION
**Pull request by utchoang**
### Description

This PR fixes https://github.com/apache/cloudstack/issues/6088

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### Screenshots (if appropriate):
image

### CODE REVIEW

**Comment by slavkap** [comment]
Hi @utchoang, I think adding a `custom` protocol is needed for SolidFire and PowerFlex, and because the protocol parameter is set as mandatory

**Comment by sureshanaparti** [comment]
> Hi @utchoang, I think adding a `custom` protocol is needed for SolidFire and PowerFlex, and because the protocol parameter is set as mandatory

@utchoang Correct, protocol is the required input at UI, for adding primary storage. This is imp to pick the correct storage provider, url and related parameter inputs. If `custom` protocol for PowerFlex is confusing, this can be updated to something meaningful, eg. PreSetup or PowerFlex (now or can be re-visited later ?), but ensure that all the provider details are properly picked and passed to the API call. Also, it's better to keep adding primary storage options in sync, at zone wizard and add primary storage dialog. Check if any documentation update needed for these changes. Thanks.

**Comment by utchoang** [comment]
@slavkap @sureshanaparti Thank you for your comments. I fixed it, please review it again.

**Comment by slavkap** [comment]
Hi @utchoang, I think it will be more user-friendly if the `custom` protocol option is shown with the rest of the protocol options. Because we fill in the form sequentially, the provider, in this case, should be above the protocol, or the `custom` option should be in the list of protocols. Another option when you choose PowerFlex/SolidFire, the `custom` protocol could be automatically set.
Also, I think that it's not a good idea to limit the `custom` option only to SolidFire/PowerFlex (e.g. Datera plugin also is using this option, probably there are other storage plugins even such not in CS upstream but have integrations with CS)

**Comment by sureshanaparti** [comment]
@utchoang Sometimes 'Protocol' is cleared when 'Provider' is selected, please check.

**Review by slavkap — CHANGES_REQUESTED** [review]
Hi @utchoang, here https://github.com/apache/cloudstack/blob/d815b9cf490ab27c9e341114d82415bde0805291/ui/src/views/infra/zone/ZoneWizardLaunchZone.vue#L1327
if it's SharedMountPoint, the `server` should be set to `server = 'localhost'` because it's not provided by default

**Review by slavkap — APPROVED** [review]
Thanks, @utchoang, for the PR! 
code LGTM tested it with SharedMoutPoint and StorPool

**Review by shwstppr — APPROVED** [review]

**Pull request merged**
