### PR TITLE
systemvm: have flags to check x86_64 to install specifics for amd64 arch

### PR DESCRIPTION
**Pull request by rohityadavcloud**
This flips conditional checks to check specifically for x86_64/amd64 to install dependencies in systemvm.

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@rohityadavcloud , how do we test s390x? do we know a guy ;) ?

**Comment by rohityadavcloud** [comment]
@DaanHoogland kicked build using Jenkins, to see arm64 & x86_64 template building okay: https://build.yadav.cloud/systemvm/

Build logs:
[build-arm64.txt](https://github.com/user-attachments/files/16781435/build-arm64.txt)
[build-x86.txt](https://github.com/user-attachments/files/16781436/build-x86.txt)

**Comment by DaanHoogland** [comment]
> @DaanHoogland kicked build using Jenkins, to see arm64 & x86_64 template building okay which should be enough to validate this PR: https://build.yadav.cloud/systemvm/
> 
> Build logs: [build-arm64.txt](https://github.com/user-attachments/files/16781435/build-arm64.txt) [build-x86.txt](https://github.com/user-attachments/files/16781436/build-x86.txt)

agree on those two @rohityadavcloud . I was just wondering about the s390x arch; is it used anywhere and do we know anybody willing to test that one?

**Review by kiranchavala — APPROVED** [review]
LGTM
The jenkins job output with the parameters were successful 

```
bash -x build.sh systemvmtemplate 4.20.0 x86_64
bash -x build.sh systemvmtemplate 4.20.0 aarch64
```

**Pull request merged**
