### PR TITLE
propagate sort order through retrieval sequence

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR...

Fixes: #9595 

Note that is only fixes the regression reported in #9595, not enhancing it or fixing any ordering bugs that were already present before 4.19, except that the renumbering now only takes place within the page displayed.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [x] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

#### How did you try to break this feature and the system with this change?

both with API (cmk) and UI

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by rohityadavcloud — APPROVED** [review]
LGTM - didn't test it though

**Review by vishesh92 — APPROVED** [review]
clgtm. Tested basic workflow and it's working as expected.

**Pull request merged**
