### PR TITLE
Adjust misformatted logs

### PR DESCRIPTION
**Pull request by winterhazel**
### Description

Fixes some misformatted logs in the deployment & Quota balance calculation processes.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [X] Trivial

### How Has This Been Tested?

Before:

```
2024-11-05 12:40:32,643 INFO  [cloudstack.quota.QuotaManagerImpl_EnhancerByCloudStack_281d8029] (Usage-Job-1:[]) (logid:) Processing quota balance for account[{}] between [{}] and [{}].
```

After:

```
2024-11-05 12:40:38,903 INFO  [cloudstack.quota.QuotaManagerImpl_EnhancerByCloudStack_281d8029] (Usage-Job-1:[]) (logid:) Processing quota balance for account [{"accountName":"system","domainId":1,"id":1,"uuid":"60b8ca5a-28b2-11ef-a04e-6ac09c2b3d6b"}] between [2024-11-05T00:13:00.000+0000] and [2024-11-05T12:39:59.000+0000].
```

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
compiles, ship it ;)

But seriously, I am not sure if this is covered by any tests...

**Review by bernardodemarco — APPROVED** [review]
LGTM

**Comment by JoaoJandre** [comment]
> compiles, ship it ;)
> 
> But seriously, I am not sure if this is covered by any tests...

@DaanHoogland I think that for a change like this there isn't much to test. The CI should suffice, no?

**Comment by DaanHoogland** [comment]
> > compiles, ship it ;)
> > But seriously, I am not sure if this is covered by any tests...
> 
> @DaanHoogland I think that for a change like this there isn't much to test. The CI should suffice, no?

You are absolutely right @JoaoJandre, and looking back at the code I am not sure if we need even that.

**Pull request merged**
