### PR TITLE
Add Python flake8 linting for W291 trailing whitespace with Super-Linter

### PR DESCRIPTION
**Pull request by jbampton**
### Description

Need to have standardized Python code.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [X] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [X] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
thanks @jbampton , I will try to merge this asap, Have you just removed trailing spaces or also looked at tab (especially component tests have that problem)?

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by jbampton** [comment]
Hey @DaanHoogland  I only looked at `trailing whitespace` so far.

I was going to add a `GitHub Action` to run `flake8` to test for `W291` for trailing whitespace.

By adding this check it will mean it will stop regressions.

Yes I am interested in cleaning up `tab` problems in future and / or other Python linting problems.

https://flake8.pycqa.org/en/latest/
https://www.flake8rules.com/rules/W291.html

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
Ping @jbampton are you working on this, can you resolve conflicts? Thanks

**Comment by nvazquez** [comment]
Moving it to the next milestone

**Comment by jbampton** [comment]
@rohityadavcloud and @nvazquez I have removed the conflicts now

**Comment by jbampton** [comment]
@DaanHoogland  I have included both `spaces` and `tab` in this update.

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Review by nvazquez — APPROVED** [review]

**Comment by nvazquez** [comment]
Hi @DaanHoogland @weizhouapache @Pearl1594 could you please review? Smoke tests look good, no major changes besides removing spaces, I think it should be good to merge after approvals

**Review by weizhouapache — APPROVED** [review]
code lgtm

@jbampton can you tell how to configure the check on github ?

**Review by DaanHoogland — COMMENTED** [review]
looks generally good but licenses need to be attended

**Comment by jbampton** [comment]
Hey @weizhouapache GitHub Actions don't run the first time they are added to a repo with a pull request.

So this PR will need to be merged and then new PRs will run this GitHub Action.

**Comment by nvazquez** [comment]
@blueorangutan test matrix

**Comment by jbampton** [comment]
Thanks everyone 💯

**Pull request merged**
