### PR TITLE
UI: fix wrong vpcid when create network in VPC

### LINKED ISSUE #7601: Unable to create Network using VPC
#####Unable to use VPC setting

 * Bug Report
 * Improvement Request
 * Enhancement Request
 * Feature Idea
 * Documentation Report
 * Other

##### Management-server-component

~~~
VPC issue
~~~

##### 4.18..0.0

~~~
4.18.0.0
~~~

##### SUMMARY

I cannot create network by using VPC. It's show like below picture. I'm newbie and i have no clue to fix. Can anyone assist me

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~
image

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #7601 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Review by rohityadavcloud — DISMISSED** [review]

**Review by shwstppr — APPROVED** [review]
Code LGTM

**Review by harikrishna-patnala — APPROVED** [review]
LGTM, quickly verified the fix on the local environment and vpcid is passed during the network creation.

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@blueorangutan test keepEnv

**Comment by weizhouapache** [comment]
@DaanHoogland 
I will merge this PR, you can use the environments to investigate the test failures

**Pull request merged**
