### PR TITLE
Use parameter dcId as wrapper to prevent NPE

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR...

Fixes: #8956

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [x] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@rajujith, can you test your scenario with this?

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by JoaoJandre — APPROVED** [review]
CLGTM, I have no way to test the scenario on https://github.com/apache/cloudstack/issues/8956.

**Comment by KlausDornsbach** [comment]
CLGTM.

Also done some testing:
1. Remove NFS secondary storage.
2. Create AWS Bucket, generate access and secret keys.
3. Add the S3 secondary storage bucket to ACS with success and no errors on logs.

**Comment by DaanHoogland** [comment]
@blueorangutan test alma9 vmware-80u1

**Comment by DaanHoogland** [comment]
@blueorangutan test alma9 vmware-70u3

**Review by rajujith — APPROVED** [review]
LGTM.
I can add the S3 bucket as a secondary storage along with an NFS staging storage. I used a Minio S3 bucket.

**Comment by DaanHoogland** [comment]
/me investigating the `test_02_balanced_drs_algorithm` failure.

**Comment by DaanHoogland** [comment]
@blueorangutan test alma9 vmware-70u3 keepEnv

**Pull request merged**
