### PR TITLE
test: fix test failure on ubuntu 24.04: "top: unknown option 'n'"

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes the smoke test failure test_service_offering.py on Ubuntu 24.04

```
======================================================================
ERROR: Test CPU Cap on KVM
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/marvin/lib/decoratorGenerators.py", line 30, in test_wrapper
    return test(self, *args, **kwargs)
  File "/marvin/tests/smoke/test_service_offerings.py", line 1049, in test_01_service_offering_cpu_limit_use
    host_cpu_usage_before = round(float(host_cpu_usage_before_str))
ValueError: could not convert string to float: "top: unknown option 'n'"
-------------------- >> begin captured stdout << ---------------------
=== TestName: test_01_service_offering_cpu_limit_use | Status : EXCEPTION ===

```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
@blueorangutan help

**Comment by DaanHoogland** [comment]
@blueorangutan test ubuntu24 kvm-ubuntu24

**Comment by weizhouapache** [comment]
> [SF] Trillian test result (tid-10505) Environment: kvm-ubuntu24 (x2), Advanced Networking with Mgmt server u24 Total time taken: 46141 seconds Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr9262-t10505-kvm-ubuntu24.zip Smoke tests completed. 129 look OK, 2 have errors, 0 did not run Only failed and skipped tests results shown below:
> 
> Test	Result	Time (s)	Test File
> test_oobm_background_powerstate_sync	`Failure`	21.03	test_outofbandmanagement.py
> test_oobm_enabledisable_across_clusterzones	`Error`	37.51	test_outofbandmanagement.py
> test_oobm_issue_power_cycle	`Error`	20.11	test_outofbandmanagement.py
> test_oobm_issue_power_off	`Error`	20.13	test_outofbandmanagement.py
> test_oobm_issue_power_on	`Error`	20.14	test_outofbandmanagement.py
> test_oobm_issue_power_reset	`Error`	20.14	test_outofbandmanagement.py
> test_oobm_issue_power_soft	`Error`	20.10	test_outofbandmanagement.py
> test_oobm_issue_power_status	`Error`	20.13	test_outofbandmanagement.py
> test_oobm_multiple_mgmt_server_ownership	`Failure`	28.42	test_outofbandmanagement.py
> test_oobm_zchange_password	`Error`	7.54	test_outofbandmanagement.py
> test_hostha_kvm_host_degraded	`Error`	10.18	test_hostha_kvm.py
> test_hostha_kvm_host_fencing	`Error`	8.64	test_hostha_kvm.py
> test_hostha_kvm_host_recovering	`Error`	9.62	test_hostha_kvm.py

comparing with https://github.com/apache/cloudstack/pull/9263#issuecomment-2177265906, the test "test_service_offering.py" has no failures with this PR
cc @DaanHoogland @sureshanaparti

**Review by sureshanaparti — APPROVED** [review]
clgtm, hope no issues with previous versions @weizhouapache

**Comment by DaanHoogland** [comment]
looks good @weizhouapache , one more try out of insanity
@blueorangutan test ubuntu24 kvm-ubuntu24

**Comment by weizhouapache** [comment]
> looks good @weizhouapache , one more try out of insanity

Thanks @sureshanaparti @DaanHoogland 
Let's try another os

@blueorangutan test a9 kvm-alma9

**Comment by weizhouapache** [comment]
@blueorangutan test alma9 kvm-alma9

**Review by rohityadavcloud — APPROVED** [review]

**Review by vishesh92 — APPROVED** [review]
clgtm
manually tested the top command on ubuntu 24.04 and centos 7.

**Comment by sureshanaparti** [comment]
test_service_offering.py has no failures, manually verified cmds in Rocky Linux 8.4, Oracle Linux 8.6.

**Pull request merged**
