### PR TITLE
Remove powermock from ldap & project-role-based plugin

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR removes powermock from tests & fixes the path for tests of project-role-based plugin.

Pending powermock usage after this PR
```bash
 git grep -i "PowerMockito" | tr "/" " "| awk '{print $1, $2, $3, $4, $5}' | sort | uniq -c       
     76 api src test java org
     51 core src test java com
     37 engine schema src test java
     68 engine storage configdrive src test
      9 engine storage snapshot src test
      3 plugins database quota src test
    150 plugins hypervisors kvm src test
      3 plugins hypervisors vmware src test
     40 plugins hypervisors xenserver src test
      5 plugins integrations kubernetes-service src test
      2 plugins network-elements nicira-nvp src test
     96 plugins network-elements tungsten src test
      1 plugins storage volume storpool src
    194 server src test java com
      2 server src test java org
      4 services console-proxy server src test
      2 services secondary-storage server src test
      2 vmware-base src test java com

```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by vishesh92** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by vishesh92** [comment]
@blueorangutan test

**Review by shwstppr — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@shwstppr please add an explanation for your approval

**Review by rohityadavcloud — APPROVED** [review]
LGTM didn't test it, but I think we can rely on automated tests

**Comment by rohityadavcloud** [comment]
Merging this based on code review, build/pkging checks, simulator/Github actions and smoketests.

**Comment by rohityadavcloud** [comment]
Thanks @vishesh92 feel to submit for other areas of codebase in subsequent PRs, thanks for your PR.

**Pull request merged**
