### PR TITLE
simulator: Add support to scale a VM

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

This PR addresses https://github.com/apache/cloudstack/issues/5508 - where in vm scale operation is not allowed even when there is no resizing required to be performed.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### How Has This Been Tested?
1. Performed scale VM operation from one compute (fixed) offering type w/o root disk size to another - successful
2. Performed scale VM operation from a compute(fixed) offering  w/o root disk size to a custom constrained / unconstrained offering without any root disk size - successful
3. performed scale VM operation from a compute offering with root disk size to a one without any root disk size  - successful
4. performed scaleVM operation from a compute offering w/o root disk size to a one with root disk size specified - fails with:
image

### CODE REVIEW

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan package

**Review by weizhouapache — APPROVED** [review]
manually tested ok in simulator

**Comment by weizhouapache** [comment]
@blueorangutan test

**Review by shwstppr — APPROVED** [review]

**Pull request merged**
