### PR TITLE
speedup iptables by prefetching the variables

### PR DESCRIPTION
**Pull request by kollyma**
-- This PR is replacing speedup iptables setup #1449 
-- Squashing commits and cleanup

PR against 4.7 as discussed with Remi Bergsma. This will speed up the iptables creation on the virtual router.

Testing showed the following:
with current code:
root@kvm704:~# time /usr/share/cloudstack-common/scripts/network/domr/router_proxy.sh vr_cfg.sh 169.254.1.176 -c /var/cache/cloud/VR-12f28879-de7e-44d2-8dbe-b93a04bd3ba4.cfg
real 2m56.401s
user 0m0.012s
sys 0m0.012s

modified version:
root@kvm704:~# time /usr/share/cloudstack-common/scripts/network/domr/router_proxy.sh vr_cfg.sh 169.254.1.176 -c /var/cache/cloud/VR-12f28879-de7e-44d2-8dbe-b93a04bd3ba4.cfg
real 1m35.762s
user 0m0.020s
sys 0m0.004s

### CODE REVIEW

**Comment by wido** [comment]
Seems like a sane Python change. Looking at the code it's OK. I can't find an issue.

Testing it is a bit harder to do for me now.

Based on the code: LGTM

**Comment by DaanHoogland** [comment]
code LGTM running tests as we write

**Comment by swill** [comment]
@DaanHoogland I already ran tests against this one as #1449.  I am planning to merge this today...

**Comment by DaanHoogland** [comment]
fine I had a failure but the re-run worked. Not very reassuring but mainly about my test-env not the pr.

**Comment by swill** [comment]
Ok, perfect.  I will merge this now.  Thx for confirming..  :)

**Comment by DaanHoogland** [comment]
just to finalize my report, @swill ; I isolated the failing test:
```
SSH into VM: 192.168.23.7
====Trying SSH Connection: Host:192.168.23.7 User:root                                   Port:22 RetryCnt:20===
====Trying SSH Connection: Host:192.168.23.7 User:root                                   Port:22 RetryCnt:20===
====Trying SSH Connection: Host:192.168.23.7 User:root                                   Port:22 RetryCnt:20===
====Trying SSH Connection: Host:192.168.23.7 User:root                                   Port:22 RetryCnt:20===
====Trying SSH Connection: Host:192.168.23.7 User:root                                   Port:22 RetryCnt:20===
===SSH to Host 192.168.23.7 port : 22 SUCCESSFUL===
===SSH to Host 192.168.23.7 port : 22 SUCCESSFUL===
===SSH to Host 192.168.23.7 port : 22 SUCCESSFUL===
===SSH to Host 192.168.23.7 port : 22 SUCCESSFUL===
===SSH to Host 192.168.23.7 port : 22 SUCCESSFUL===
Ping to google.com from VM
{Cmd: ping -c 3 8.8.8.8 via Host: 192.168.23.7} {returns: [u'PING 8.8.8.8 (8.8.8.8): 56 data bytes', u'', u'--- 8.8.8.8 ping statistics ---', u'3 packets transmitted, 0 packets received, 100% packet loss']}
{Cmd: ping -c 3 8.8.8.8 via Host: 192.168.23.7} {returns: [u'PING 8.8.8.8 (8.8.8.8): 56 data bytes', u'', u'--- 8.8.8.8 ping statistics ---', u'3 packets transmitted, 0 packets received, 100% packet loss']}
{Cmd: ping -c 3 8.8.8.8 via Host: 192.168.23.7} {returns: [u'PING 8.8.8.8 (8.8.8.8): 56 data bytes', u'', u'--- 8.8.8.8 ping statistics ---', u'3 packets transmitted, 0 packets received, 100% packet loss']}
{Cmd: ping -c 3 8.8.8.8 via Host: 192.168.23.7} {returns: [u'PING 8.8.8.8 (8.8.8.8): 56 data bytes', u'', u'--- 8.8.8.8 ping statistics ---', u'3 packets transmitted, 0 packets received, 100% packet loss']}
{Cmd: ping -c 3 8.8.8.8 via Host: 192.168.23.7} {returns: [u'PING 8.8.8.8 (8.8.8.8): 56 data bytes', u'', u'--- 8.8.8.8 ping statistics ---', u'3 packets transmitted, 0 packets received, 100% packet loss']}
SSH result: [u'PING 8.8.8.8 (8.8.8.8): 56 data bytes', u'', u'--- 8.8.8.8 ping statistics ---', u'3 packets transmitted, 0 packets received, 100% packet loss']; COUNT is ==> 0
=== TestName: test_02_redundant_VPC_default_routes | Status : FAILED ===

===final results are now copied to: /tmp//MarvinLogs/test_vpc_route_FDIXGV===
[root@cs1 MarvinLogs]# ssh 192.168.23.7
The authenticity of host '192.168.23.7 (192.168.23.7)' can't be established.
ECDSA key fingerprint is b3:20:a9:be:83:82:d2:56:43:3a:a9:8c:81:1e:7a:d1.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '192.168.23.7' (ECDSA) to the list of known hosts.
root@192.168.23.7's password: 
```
but then, i removed the teardown part from the test:
```
# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=46 time=26.690 ms
64 bytes from 8.8.8.8: seq=1 ttl=46 time=26.481 ms
^C
--- 8.8.8.8 ping statistics ---
3 packets transmitted, 2 packets received, 33% packet loss
round-trip min/avg/max = 26.481/26.585/26.690 ms
```
conclusion, 'something in the test is in conflict with my environment'?

**Pull request merged**
