### PR TITLE
test: fix test_guest_os.py failure on xcpng82

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR is related to #8586 

on xenserver-71, supported Debian OSes are
```
          name-label ( RW): Debian Squeeze 6.0 (32-bit)
          name-label ( RW): Debian Jessie 8.0
          name-label ( RW): Debian Wheezy 7.0 (32-bit)
          name-label ( RW): Debian Squeeze 6.0 (64-bit)
          name-label ( RW): Debian Wheezy 7.0 (64-bit)
```

on xcpng82, supported Debian OSes are
```
          name-label ( RW): Debian Jessie 8.0
          name-label ( RW): Debian Buster 10
          name-label ( RW): Debian Stretch 9.0
```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Review by DaanHoogland — APPROVED** [review]

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 xenserver-71

**Comment by weizhouapache** [comment]
@blueorangutan rocky8 xcpng-82

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 xcpng82

**Review by rohityadavcloud — APPROVED** [review]

**Comment by DaanHoogland** [comment]
Therre are many failures on xcpng82 still. Are these related, @weizhouapache ? 
Should we create separate issues/PRs for those?

**Comment by weizhouapache** [comment]
> Therre are many failures on xcpng82 still. Are these related, @weizhouapache ? 
> Should we create separate issues/PRs for those?

Hi @DaanHoogland 
Please check #8586

**Pull request merged**
