### PR TITLE
[DO NOT MERGE] Health Check Master: Dummy commit

### PR DESCRIPTION
**Pull request by andrijapanicsb**
Dummy PR - just for sake of running smoke tests against the master - DO NOT MERGE!

### CODE REVIEW

**Comment by andrijapanicsb** [comment]
@blueorangutan package

**Comment by andrijapanicsb** [comment]
@blueorangutan help

**Comment by andrijapanicsb** [comment]
@blueorangutan test matrix

**Comment by borisstoyanov** [comment]
VMware doesn't seem right, let me rerun
@blueorangutan test centos7 vmware65

**Comment by borisstoyanov** [comment]
@blueorangutan test centos7 vmware-65u2

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@rhtyd @andrijapanicsb Let's close this and create a draft PR for this work. It will prevent merging by accident (untill someone says it's ready for review.

**Comment by andrijapanicsb** [comment]
@blueorangutan test

**Comment by andrijapanicsb** [comment]
@blueorangutan test

**Comment by andrijapanicsb** [comment]
> @rhtyd @andrijapanicsb Let's close this and create a draft PR for this work. It will prevent merging by accident (until someone says it's ready for review.

As agreed, will close it once the atm running tests are complete. Thx.

**Comment by rhtyd** [comment]
Will reopen a fresh one.

**Comment by DaanHoogland** [comment]
@blueorangutan sweep

**Pull request closed without merging**
