### PR TITLE
Ensure affinity groups are honored when VMs are deployed in parallel

### LINKED ISSUE #7202: host anti-affinity is not working
##### ISSUE TYPE

 * Bug report

##### COMPONENT NAME

~~~
Compute
~~~

##### CLOUDSTACK VERSION

~~~
4.18 nightly
4.17.2

~~~

##### OS / ENVIRONMENT

Centos 7 , 1 management , 1 pod , 1 cluster with 2 kvm hypervisor hosts

##### SUMMARY

host anti-affinity is not working 

##### STEPS TO REPRODUCE
~~~

1. Create a affinity group of type "host anti-affinity (Strict)".

2. Deploy 2 vm without any affinity group attached 

3. Check the vm's host ( they can be deployed on the same host)

Note: Make sure the vm's are deployed on 1 single host in the cluster

3. Stop the vm's

4. Change the affinity group  of the vms to  "host anti-affinity (Strict)"

Note: Make sure the affinity group is attached to the vm

5. Start the vm 

6. The Vm 's still remains on the same host in the cluster

Made sure to uncheck the option to start on Last host 
![start](https://user-images.githubusercontent.com/1401014/218453831-ed4070bf-707d-4d39-80fc-36477a7e74a2.png)



~~~

##### EXPECTED RESULTS

~~~
The vm's should go to different host in the cluster
~~~

##### ACTUAL RESULTS

~~~
The vm's  are not going  to different hosts  in the cluster
~~~

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

Fixes #7202 #9110

This PR doesn't completely solve the issue. To completely resolving the issue, we will have to sacrifice the speed at which VMs can be deployed in parallel.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan test keepEnv

**Comment by weizhouapache** [comment]
@vishesh92 
have you tested it ?

**Comment by vishesh92** [comment]
> @vishesh92 have you tested it ?

I tested with simulator. I was able to reproduce and fix the issue for strict anti affinity.

**Comment by weizhouapache** [comment]
> > @vishesh92 have you tested it ?
> 
> I tested with simulator. I was able to reproduce and fix the issue for strict anti affinity.

thanks @vishesh92 
I will create a testing env to test it

**Comment by weizhouapache** [comment]
@vishesh92 
I tested host-affinity, 
```
    command="cmk deploy virtualmachine zoneid=5a6557c9-b1e0-4fbf-bca4-7f376a96df65 templateid=344e6034-28ae-11ef-8462-1e00c200016f serviceofferingid=2eb32c51-d604-472b-895e-019f31a2f146 networkids=39323a57-1e12-4f3d-b030-36ef7e850e22"

    affinitygroup=$(cmk create affinitygroup type='host affinity' name=test-`uuidgen`)
    affinitygroupid=$(echo $affinitygroup |jq -r '.affinitygroup.id')

    # create 2 vms in parallel
    for i in `seq 1 2`;do $command affinitygroupids=$affinitygroupid & done
```

I tried twice. first time it works, second try it did not

image

**Comment by vishesh92** [comment]
> @vishesh92 I tested host-affinity,
> 
> ```
>     command="cmk deploy virtualmachine zoneid=5a6557c9-b1e0-4fbf-bca4-7f376a96df65 templateid=344e6034-28ae-11ef-8462-1e00c200016f serviceofferingid=2eb32c51-d604-472b-895e-019f31a2f146 networkids=39323a57-1e12-4f3d-b030-36ef7e850e22"
> 
>     affinitygroup=$(cmk create affinitygroup type='host affinity' name=test-`uuidgen`)
>     affinitygroupid=$(echo $affinitygroup |jq -r '.affinitygroup.id')
> 
>     # create 2 vms in parallel
>     for i in `seq 1 2`;do $command affinitygroupids=$affinitygroupid & done
> ```
> 
> I tried twice. first time it works, second try it did not

Yes. This will reduce the occurrence of failures but not completely resolve the issue.

**Review by rohityadavcloud — APPROVED** [review]
LGTM - but can't confirm on stability of the feature/testing, or if current smoketests cover these changes

**Comment by weizhouapache** [comment]
@vishesh92 
I had a look of the process of vm deployment, would it make sense to lock the method below ?

https://github.com/apache/cloudstack/blob/cb9b3134f7fff972b63d8565a4d021f8ea918903/server/src/main/java/com/cloud/deploy/DeploymentPlanningManagerImpl.java#L303-L304

rename it to `planDeploymentInternal` and create a new `planDeployment` using Transaction ?

**Comment by weizhouapache** [comment]
> @vishesh92 I had a look of the process of vm deployment, would it make sense to lock the method below ?
> 
> https://github.com/apache/cloudstack/blob/cb9b3134f7fff972b63d8565a4d021f8ea918903/server/src/main/java/com/cloud/deploy/DeploymentPlanningManagerImpl.java#L303-L304
> 
> rename it to `planDeploymentInternal` and create a new `planDeployment` using Transaction ?

I am also wondering what processes should be locked, maybe until the host is determined ?

maybe we could introduce some mechanism, for example
- when create a vm , lock the `network` table (for example, to fix #7907 , cc @abh1sar ) and `resource_limit` table (to fix the resource issue ?)
- when start a vm, lock the `affinity_group` table and some other tables if needed ?

the problem is, it could lead to high latency if the platform is large.

**Comment by rohityadavcloud** [comment]
@vishesh92 can you review and advise further (PR marked waiting-for-author)?

**Comment by vishesh92** [comment]
> @vishesh92 can you review and advise further (PR marked waiting-for-author)?

@rohityadavcloud I am running the capc e2e test for affinity group. Let me share the results once the job is complete.

**Comment by vishesh92** [comment]
@weizhouapache @sureshanaparti I ran e2e test 5 times on an env with this patch. Here are the results:
2 - Successfully passed
2- timed out
1 - failure

**Comment by DaanHoogland** [comment]
@sureshanaparti , will we try to merge this in 4.19.1?

**Comment by vishesh92** [comment]
@DaanHoogland This PR is targeted for 4.19.2

**Review by kiranchavala — APPROVED** [review]
LGTM, tested with the following steps

```

1. Create a affinity group of type "host anti-affinity (Strict)".

2. Deploy 2 vm's ok  without any affinity group attached 

3. Check the vm's host ( they can be deployed on the same host)

Note: Make sure the vm's are deployed on 1 single host in the cluster

3. Stop the vm's

4. Change the affinity group  of the vms to  "host anti-affinity (Strict)"

Note: Make sure the affinity group is attached to the vm

5. Start the vm (Made sure to uncheck the option to start on Last host )

6. The vm's got deployed  on different hosts 
```

**Pull request merged**
