### PR TITLE
fix debian package after addition of license header in pom.xml

### PR DESCRIPTION
**Pull request by pdion891**
PR#737 add lines  in pom.xml which break debian build.
This fix debian package build issue.

### CODE REVIEW

**Comment by terbolous** [comment]
Verified that the command works as expected.

LGTM

**Comment by ke4qqq** [comment]
LGTM - I am going to close and open to see if Travis will pass.

**Comment by remibergsma** [comment]
@pdion891 If you force push your commits, Travis will run again. It will then probably pass and we can merge it. Thanks!

**Comment by remibergsma** [comment]
@pdion891 All green, merging!

**Comment by pdion891** [comment]
Thanks!

**Pull request merged**
