### PR TITLE
UI: Save the tab and re-activate it after submitting the form.

### PR DESCRIPTION
**Pull request by utchoang**
### Description

Fixes https://github.com/apache/cloudstack/issues/4961

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by davidjumani** [comment]
@blueorangutan ui

**Review by davidjumani — APPROVED** [review]

**Comment by davidjumani** [comment]
@utchoang Can you raise this against 4.15 ?
Thanks

**Comment by shwstppr** [comment]
@blueorangutan ui

**Review by shwstppr — APPROVED** [review]
Tested. LGTM

**Comment by andrijapanicsb** [comment]
LGTM - thx guys.

**Pull request merged**
