### PR TITLE
display nics deviceid and order nics by deviceid on Nics tab of insta…

### PR DESCRIPTION
**Pull request by soreana**
### Description

As a cloudstack team, we want to show sorted NICs in the Nic tab of the instance and API calls. To achieve this goal, cloudstack should put the deviceid in userVmResponse. This is the minor PR to add this feature.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

### Screenshots (if appropriate):
Screenshot 2021-03-08 at 04 27 21

### How Has This Been Tested?

I deployed the following instance in my test environment with three networks, as you can see they are sorted in NIC tab.

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
none of these ^^ errors have to do with this PR afaics.

**Comment by rhtyd** [comment]
@soreana this looks like a good enhancement. @DaanHoogland @shwstppr should we consider/ask for 4.15.1?

**Comment by DaanHoogland** [comment]
@rhtyd (cc @soreana ) though it is a minor change it does include AI and DB changes, so I'd say leave it for 4.16 (that is not a definite :-1: at all, just a expression of our merge principles and principles are there to be broken with)

**Comment by rhtyd** [comment]
+1 I didn't look at code changes, if it involved db changes.

**Comment by rhtyd** [comment]
@DaanHoogland from what I read, apart from me nobody was interested in 4.15 including the author so I didn't push it any further. I just checked branch compatibility and it looks like without rebasing (+ moving any db changes to the right file) this causes conflicts on 4.15. I'm fine with what others have said.

**Comment by rhtyd** [comment]
@soreana can you fix the conflict? Thanks.

**Comment by nvazquez** [comment]
Hi @soreana can you please fix the conflict?

**Comment by weizhouapache** [comment]
Hi @soreana can you please fix the conflict?

**Comment by soreana** [comment]
I fixed the conflict.
@weizhouapache @nvazquez @rhtyd Sorry for the late response guys. As I was away for couple of weeks, I completely forgot about this.

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan test

**Review by davidjumani — APPROVED** [review]

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@blueorangutan test

**Review by nvazquez — APPROVED** [review]

**Pull request merged**
