### PR TITLE
server: fix volume detach operation when no vm host

### LINKED ISSUE #7525: Offline VM migration in VMware with disk detach causes VM snapshots issues
VM snapshot fails with the following steps:

1. Migration of offline virtual machines between clusters
2. Disk attach to that VM
3. Disk detach
4. Disk deletion
5. Obtaining VM snapshot

There is still an issue with the detach volume operation. CloudStack does not send DetachCommand to the vCenter during step 3 and in vCenter the VM continues to show the detached disk.

Ref:
https://github.com/apache/cloudstack/blob/main/server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java#L2781-L2790

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VMware
~~~

##### CLOUDSTACK VERSION

~~~
4.11, 4.18+
~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #7525 

CloudStack may not keep the VM associated to any host when there is offline migration across cluster or pod. In such cases, CloudStack should be able to send the AttachCommand or DetachCommand to any available host in the current VM cluster.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
cc @andrijapanicsb @rajujith @alexandremattioli @NuxRo have we enabled London lab?

**Comment by shwstppr** [comment]
@blueorangutan test matrix

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test matrix

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Review by rohityadavcloud — APPROVED** [review]

**Comment by DaanHoogland** [comment]
tested according to https://github.com/apache/cloudstack/issues/7525#issue-1707304990 and verified no extra disks attached to the VM.

**Review by kiranchavala — COMMENTED** [review]
@shwstppr @DaanHoogland 



The following scenario is failing 


1. Deploy an environment with 2 clusters (Cluster A , Cluster B) in a single pod

2. Deploy a vm with a data disk in cluster A  

3. Stop the vm from CS, the host id will be set to null

4. Migrate the vm to cluster B via Vcenter

Screenshot 2023-05-25 at 7 55 48 PM



5. Try to detach the data volume to Vm >> failure


It works fine if the migration of the vm is done by CS

1. Deploy a environment with 2 clusters (Cluster A , Cluster B) in a single pod

2. Deploy a vm with a data disk in cluster A  

3. Stop the vm in CS

4.  Migrate the vm to cluster B  via CS

5.  Try to detach  data volume to Vm  >> Success

**Comment by DaanHoogland** [comment]
@kiranchavala , if you feel this scenario should be supported as well, please open a new issue. I think it is out of scope for this fix and a stretch to ask in general; If people do things to cloud resources out of band we cannot guarantee recovery in all circumstances.

**Comment by kiranchavala** [comment]
Thanks @DaanHoogland I agree with @shwstppr  view that we cannot cover all cases of out-of-band operations

**Pull request merged**
