### PR TITLE
Removed double encoding of Public Key from JS.

### PR DESCRIPTION
**Pull request by borisroman**
See Cloudstack issue CLOUDSTACK-8742 & CLOUDSTACK-8649 for information.

### CODE REVIEW

**Comment by borisroman** [comment]
It was double encoded because encodeURIComponent() and jQuery.param() encoded it. The latter does this automatically because the request is of type post and the option processData was not explicitly set to false.

http://api.jquery.com/jquery.ajax/#sending-data-to-server

**Comment by bhaisaab** [comment]
@borisroman does backend do double decoding? there was a patch for cloudmonkey regarding this: https://github.com/apache/cloudstack-cloudmonkey/commit/6bd92395592c133a63b8087bf4acc9cb3a1aac0d so does this need to be fixed in cloudmonkey as well?

**Comment by karuturi** [comment]
so, the double encoding and double decoding lived happily together :) 
Now, jquery does the encoding from UI and decoding is done in ApiServlet.processRequestInContext() method
When we make an api call directly(though cloudmonkey etc.), we should pass the encoded value (which is same as earlier and no apidoc change is required)
is my understanding right?

**Comment by milamberspace** [comment]
LGTM +1

**Comment by ustcweizhou** [comment]
LGTM.

I made the commit two years ago. However, something changed in the following commit, so the encoding on UI is not needed any more.

    commit 6aafb9c50da3cf4db37c0323d8bdc859776a8fa0
    Author: Likitha Shetty <likitha.shetty@citrix.com>
    Date:   Thu Nov 21 13:33:57 2013 +0530

        CLOUDSTACK-5227. Cannot pass Japanese characters as parameter values to an API.
        During API check for control characters use pattern matching to avoid identifying all non-printable characters as control characters.

**Comment by borisroman** [comment]
@karuturi Cloudmonkey passes an single encoded public key, as it's supposed to!

**Comment by karuturi** [comment]
@borisroman excluding the cloudmonkey bit, if I make direct api call, should I send the encoded value or the original value. Did that change from previous version? 
I think it would be better to also update api documentation to reflect whether it accepts encoded/decoded value. right now it just says "Public key material of the keypair"
https://cloudstack.apache.org/api/apidocs-4.5/user/registerSSHKeyPair.html

**Comment by karuturi** [comment]
@milamberspace, I couldnt find registerSSHKeyPair from UI. I could only see reset ssh key on a stopped vm. Where is this option in UI?

**Comment by ustcweizhou** [comment]
@karuturi  go to the Accounts page, and select "SSH Key pairs" in the dropdown.

**Comment by borisroman** [comment]
@karuturi You should send a public key which has it's special characters ( SPACE / - % ) replaced with uri compatible escape characters. -> encoding http://www.w3schools.com/tags/ref_urlencode.asp

**Comment by wido** [comment]
LGTM

**Pull request merged**
