### PR TITLE
Set integration.api.port to 0 (zero) as default.

### PR DESCRIPTION
**Pull request by GabrielBrascher**
# Description

CloudStack provides CloudStack API Unauthenticated Access through port
8096. It should not be open to the Internet in any case.

Fixes: #3450

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

**Current behavior**
1. Deploy a fresh CloudStack environment
2. Assert that the port 8096 is enabled by default. 
3. Verify that `integration.api.port` is indeed configured as 8096

**WIth this PR**
1. Deploy a fresh CloudStack environment with packages from this PR
2. Assert that the port 8096 is not enabled by default.
3. Verify that `integration.api.port` is indeed configured as 0

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by anuragaw** [comment]
I ran a fresh environment off the PR based on KVM and still see integration.api.port to be 8096 in GUI. Are there any additional steps involved or is that supposed to be 0 @GabrielBrascher ?

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Trillian is full capacity, merging this based on Travis job https://travis-ci.org/apache/cloudstack/jobs/561936104 and lgtms

**Pull request merged**
