### PR TITLE
[cleanup] Deleted file FakeDhcpSnooper.java and DhcpSnooper.java

### LINKED ISSUE #7646: [Enhancement]change the return type from null to empty object in [FakeDhcpSnooper.java]
##### ISSUE TYPE

 * Enhancement Request

##### SUMMARY

location - agent/src/main/java/com/cloud/agent/dhcp/FakeDhcpSnooper.java
line - 146
Null is a reference that does not point to any object. Returning an empty object can help to improve the readability and maintainability of code.

##### EXPECTED RESULTS

add this line.
Screenshot - 

and this 

##### ACTUAL RESULTS

Screenshot - 
prev

### PR DESCRIPTION
**Pull request by nikam14**
### Description

This PR... fixes #7646 

 the class FakeDhcpSnooper.java and the class DhcpSnooper.java haven't been used anywhere in the code. They were added in 2011 for testing but they are no longer used. 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [x] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
@blueorangutan test rocky8 vmware-67u3

**Review by soreana — APPROVED** [review]
LGTM

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Pull request merged**
