### PR TITLE
CKS: fix creation on shared network if HA is enabled

### LINKED ISSUE #8585: CKS: Fail to create CKS cluster with HA enabled on Shared networks
when I input the `External load balancer IP address`, I got the exception
```
externalloadbalanceripaddress parameter must be specified along with Shared type of network
```
when I did not input the value, got a different exception
```
Multi-control nodes, HA Kubernetes cluster with Shared network ID: 82b60ec8-b2a2-4d5c-9dfd-c6528b31b03a needs an external load balancer IP address. externalloadbalanceripaddress parameter can be used
```

This issue could be fixed by
```
diff --git a/plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java b/plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java
index f45f78bf42c..a367a99304e 100644
--- a/plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java
+++ b/plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java
@@ -825,7 +825,7 @@ public class KubernetesClusterManagerImpl extends ManagerBase implements Kuberne
             if (network == null) {
                 throw new InvalidParameterValueException(String.format("%s parameter must be specified along with %s parameter", ApiConstants.EXTERNAL_LOAD_BALANCER_IP_ADDRESS, ApiConstants.NETWORK_ID));
             }
-            if (Network.GuestType.Shared.equals(network.getGuestType())) {
+            if (!Network.GuestType.Shared.equals(network.getGuestType())) {
                 throw new InvalidParameterValueException(String.format("%s parameter must be specified along with %s type of network", ApiConstants.EXTERNAL_LOAD_BALANCER_IP_ADDRESS, Network.GuestType.Shared.toString()));
             }
         }
```

It works in Advanced zone, but CKS still does not work in advanced zone with security groups.
- The first control nodes was setup successfully
- The 2nd/3rd control nodes do not work

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~
ACS 4.19.0-RC4
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #8585

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@weizhouapache is this still valid?

**Comment by weizhouapache** [comment]
> @weizhouapache is this still valid?

@DaanHoogland 
it is valid. But need more changes

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Comment by kiranchavala** [comment]
@blueorangutan package

**Review by kiranchavala — APPROVED** [review]
@weizhouapache , i am getting the following exception when I provide a external loadbalancer IP  during cks cluster creation in a shared network 

Screenshot 2024-09-24 at 12 54 51 PM

**Comment by weizhouapache** [comment]
> @weizhouapache , i am getting the following exception when I provide a external loadbalancer IP during cks cluster creation in a shared network
> 
> Screenshot 2024-09-24 at 12 54 51 PM

because 10.0.0.96.6 is not valid address
try 10.0.96.6 :smile:

**Comment by weizhouapache** [comment]
@kiranchavala 
are you testing it ?
please note, you need to setup the lb (nginx/haproxy) for the external IP

it does not work in advanced zone with security groups. 
some ports need to be opened.

**Review by kiranchavala — APPROVED** [review]
LGTM

Tested using nginx configuration as Loadbalancer 

Able to deploy a cks cluster on a shared network with HA option enabled 


sample nginx config 
```


[root@centos7 ~]# cat nginx.conf
error_log stderr notice;
worker_processes auto;
events {
    multi_accept on;
    use epoll;
    worker_connections 1024;
}
stream {
    upstream cloudstack {
        server 10.1.17.89:6443;
        server 10.1.17.90:6443 backup;
        server 10.1.17.86:6443 backup;
    }
    server {
        listen 0.0.0.0:6443;
        proxy_pass cloudstack;
        proxy_timeout 10m;
        proxy_connect_timeout 1s;
    }
    upstream control-1 {
        server 10.1.17.89:22;
    }
    server {
        listen 0.0.0.0:2222;
        proxy_pass control-1;
        proxy_timeout 10m;
        proxy_connect_timeout 1s;
    }
    upstream control-2 {
        server 10.1.17.90:22;
    }
    server {
        listen 0.0.0.0:2223;
        proxy_pass control-2;
        proxy_timeout 10m;
        proxy_connect_timeout 1s;
    }
    upstream control-3 {
        server 10.1.17.86:22;
    }
    server {
        listen 0.0.0.0:2224;
        proxy_pass control-3;
        proxy_timeout 10m;
        proxy_connect_timeout 1s;
    }
}
```


if there is no external IP is given exception is thrown

Screenshot 2024-09-25 at 12 33 29 PM

**Comment by weizhouapache** [comment]
great, thanks for the testing @kiranchavala

**Comment by JoaoJandre** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test securityGroups

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by JoaoJandre** [comment]
Merging based on reviews, manual testing (https://github.com/apache/cloudstack/pull/8588#pullrequestreview-2328115511) and CI results, the failures shown in CI are not related to this PR

**Pull request merged**
