### PR TITLE
README: again that time of the year! :christmas_tree:

### PR DESCRIPTION
**Pull request by rhtyd**
That time of the year christmas_tree - allow me to get away by merging this PR without tests?

## Screenshots (if appropriate):

Screenshot from 2019-12-16 21-14-27

To all of the CloudStack contributors - Happy Christmas and holidays!
/cc alphabetically-ish @alexandremattioli @andrijapanicsb @borisstoyanov @chiradeep @DaanHoogland @davidjumani @DK101010 @Damans227 @GabrielBrascher @gsirett @GutoVeronezi @harikrishna-patnala @kiwiflyer @mlsorensen @msinhore @nathanejohnson @NuxRo @nvazquez @Pearl1594 @pdion891 @ravening @radu-todirica @rp- @shwstppr @slavkap @soreana @steveroles @SadiJr @sureshanaparti @svenvogel @swill @syed @utchoang @vladimirpetrov @weizhouapache @wido @apurv-1 @atrocitytheme @shatoboar @bicrxm @ngrosc @alexandru-bagu @kricud @edikevich @xuanyuanaosheng @tampler @div8cn and so many others! (I may have missed quite a few other handles - you're all in my thoughts as well)

### CODE REVIEW

**Review by weizhouapache — APPROVED** [review]

**Review by NuxRo — APPROVED** [review]
LGTM! :)

**Comment by Damans227** [comment]
LGTM! :) Wish you all a Merry Christmas and a Happy New Year.

**Review by DaanHoogland — APPROVED** [review]
I wish you all very intuitive code and merry other things as well

**Comment by msinhore** [comment]
Merry Christmas and a Happy New Year for you guys!

**Comment by gsirett** [comment]
A very happy Christmas and a peaceful New year to everybody
@blueorangutan print "Happy Christmas"

**Review by vladimirpetrov — APPROVED** [review]
Magical Christmas and a Great New Year for everyone!

**Review by GutoVeronezi — APPROVED** [review]
LGTM, just one remark about the line... I'm kidding 😁. 

Wish you all happy and safe holidays!

**Review by GabrielBrascher — APPROVED** [review]
LGTM 😄
Merry Christmas everyone! 🎄🥳
Happy and safe holidays!

**Comment by nvazquez** [comment]
LGTM - Merry Christmas and a Happy New Year!! 🎄 🎅🏼 🍻

**Review by sureshanaparti — APPROVED** [review]
LGTM, Merry Christmas and a Happy New Year!!!

**Review by shwstppr — APPROVED** [review]
Merry Christmas and a very Happy New Year to everyone!

**Comment by tampler** [comment]
Happy Holidays everyone ! Let the Power be with you :sweat_smile: :partying_face: :christmas_tree:

**Review by borisstoyanov — APPROVED** [review]
LGTM ho-ho-ho

**Comment by ravening** [comment]
LGTM :)

**Comment by apurv-1** [comment]
Merry Christmas & Happy New year everyone!🎉😀⛄🌲

**Comment by DaanHoogland** [comment]
@rhtyd , I haven't tested this, So I'll leave this to merge to someone who did ...

**Comment by steveroles** [comment]
Wishing you all a peaceful Christmas and a wonderful 2022!

**Comment by rhtyd** [comment]
Happy Christmas 🎄 and holidays everyone! Let's merge this!

**Pull request merged**
