### PR TITLE
Fix/citrix resource base packages

### PR DESCRIPTION
**Pull request by wilderrodrigues**
Hi @DaanHoogland and @bhaisaab 

I have fixed the packaging under the test directory.

All the tests classes had the package declaration pointing to a location that did not exist. For Maven it was fine, because it used a --sourcepath during build. However, when using an IDE it was complaining. Despite the IDE fact, it's not nice to have differences between source directory and package declaration.

In addition, I also renamed the package from "com.cloud.hypervisor.xenserver.resource.wrapper.citrix" to "com.cloud.hypervisor.xenserver.resource.wrapper.xenbase" 

Usual tests have been executed with the following environment:

XenServer 6.2
Tiny Linux VHD (people.apache.org/~bhaisaab/vms/)
MySQL/MariaDB 5.5.41
Management Server running CentOS 7
Component/Smoke tests: https://github.com/apache/cloudstack (test/integration/component and smoke)
Storage type: NFS shared
Isolation method: VLAN

Cheers,
Wilder

### CODE REVIEW

**Comment by wilderrodrigues** [comment]
It's a bit weird, I executed the same test agains my XenServer62:

Test system VM start ... === TestName: test_01_sys_vm_start | Status : SUCCESS ===
ok
Test system templates are ready ... === TestName: test_02_sys_template_ready | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 2 tests in 0.459s

OK
/tmp//MarvinLogs/test_secondary_storage_MUYVJ7/results.txt (END)

Now will run the same batch as Travis to see what happens:

nosetests --with-marvin --marvin-config=/data/shared/marvin/mct-zone1-xen1.cfg -s -a tags=advanced,required_hardware=false smoke/test_secondary_storage.py smoke/test_service_offerings.py smoke/test_ssvm.py smoke/test_templates.py smoke/test_over_provisioning.py

**Comment by wilderrodrigues** [comment]
All tests are passing. Don't know the reason for the failure on travis.

Test system VM start ... === TestName: test_01_sys_vm_start | Status : SUCCESS ===
ok
Test system templates are ready ... === TestName: test_02_sys_template_ready | Status : SUCCESS ===
ok
Test to create service offering ... === TestName: test_01_create_service_offering | Status : SUCCESS ===
ok
Test to update existing service offering ... === TestName: test_02_edit_service_offering | Status : SUCCESS ===
ok
Test to delete service offering ... === TestName: test_03_delete_service_offering | Status : SUCCESS ===
ok
Test List secondary storage VMs ... === TestName: test_01_list_sec_storage_vm | Status : SUCCESS ===
ok
Test List console proxy VMs ... === TestName: test_02_list_cpvm_vm | Status : SUCCESS ===
ok
Test create public & private template ... === TestName: test_01_create_template | Status : SUCCESS ===
ok
Test Edit template ... === TestName: test_02_edit_template | Status : SUCCESS ===
ok
Test delete template ... === TestName: test_03_delete_template | Status : SUCCESS ===
ok
Update & Test for template permissions ... === TestName: test_05_template_permissions | Status : SUCCESS ===
ok
Test only public templates are visible to normal user ... === TestName: test_07_list_public_templates | Status : SUCCESS ===
ok
Test System templates are not visible to normal user ... === TestName: test_08_list_system_templates | Status : SUCCESS ===
ok
test update configuration setting at storage scope ... === TestName: test_UpdateStorageOverProvisioningFactor | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 14 tests in 701.885s

OK
/tmp//MarvinLogs/test_over_provisioning_NGCU8H/results.txt (END)

**Comment by wilderrodrigues** [comment]
I merged this PR, but the mirror on github doesn't get it.

Just did a new clone from Apache git to get a fresh copy and I see the commit there:

commit b155129ae8fb9e9fe17dc558cd1b292f097d527e
Author: wilderrodrigues <wrodrigues@schubergphilis.com>
Date:   Tue May 26 10:43:38 2015 +0200

    Fixing the packaging of the Xen resource tests - The package declaration of all Test classes was point to a package that was not represented as a directory - For example: Class A had "package b.c.d;" as declaration, but the class A was under directory "c"
    
    Maven was bulding the project and executing the tests just fine because it uses "-sourcepath". However,
    with IDEs and javac it would fail.
    
    Signed-off-by: wilderrodrigues <wrodrigues@schubergphilis.com>
    
    This closes #317

@bhaisaab could you try to clone Master and see if the changes are there, please?

**Comment by xenserverarmy** [comment]
One suggestion.  In the future we may have pure Xen support, so if possible we should ensure all naming for XenServer is "XenServer" and not Xen.  So please change "com.cloud.hypervisor.xenserver.resource.wrapper.xenbase" to "com.cloud.hypervisor.xenserver.resource.wrapper.xenserverbase"

**Comment by wilderrodrigues** [comment]
Hi @xenserverarmy ,

I'm just checking what is going on that the mirror doesn't get updated, then will apply the change you suggested.

Cheers,
Wilder

**Pull request closed without merging**
