### PR TITLE
smoke/test_internal_lb.py:  Fix template not ready error

### PR DESCRIPTION
**Pull request by michaelandersen**
Add wait for template download
Refactored template section of services
Added some extra logging in the setup phase

### CODE REVIEW

**Comment by michaelandersen** [comment]
ran the following test:
```
nosetests --with-marvin --log-folder-path=/tmp/marvin/ --marvin-config=../../../mct-zone1-kvm1.cfg -a tags=advanced  test_internal_lb.py
```

with results:
```
Test to verify access to loadbalancer haproxy admin stats page ... === TestName: test02_internallb_haproxy_stats_on_all_interfaces | Status : SUCCESS ===
ok
Test create, assign, remove of an Internal LB with roundrobin http traffic to 3 vm's ... === TestName: test_01_internallb_roundrobin_1VPC_3VM_HTTP_port80 | Status : SUCCESS ===
ok
----------------------------------------------------------------------
Ran 2 tests in 1156.295s
OK
```

**Comment by miguelaferreira** [comment]
@michaelandersen you did not specify `required_hardware=true` are you sure the tests have actually ran?

**Comment by remibergsma** [comment]
LGTM, my run was also successful:

```
[root@cs2 integration]# cat /tmp//MarvinLogs/test_internal_lb_WWSD41/results.txt 
Test to verify access to loadbalancer haproxy admin stats page ... === TestName: test02_internallb_haproxy_stats_on_all_interfaces | Status : SUCCESS ===
ok
Test create, assign, remove of an Internal LB with roundrobin http traffic to 3 vm's ... === TestName: test_01_internallb_roundrobin_1VPC_3VM_HTTP_port80 | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 2 tests in 1184.388s

OK
```

Nice catch @miguelaferreira, I assume a copy/paste error @michaelandersen? When I run it with hardware set to false it doesn't run at all:

```
[root@cs2 integration]# nosetests --with-marvin --marvin-config=${marvinCfg} -s -a tags=advanced,required_hardware=false smoke/test_internal_lb.py

==== Marvin Init Started ====

=== Marvin Parse Config Successful ===

=== Marvin Setting TestData Successful===

==== Log Folder Path: /tmp//MarvinLogs//Oct_24_2015_12_12_00_4A5SNZ. All logs will be available here ====

=== Marvin Init Logging Successful===

==== Marvin Init Successful ====
```

**Comment by remibergsma** [comment]
@borisroman @DaanHoogland Can one of you review this please?

**Comment by DaanHoogland** [comment]
setting up a test env. will review when better rested

**Pull request merged**
