### PR TITLE
UI - Remove white space after detail string in Firefox

### PR DESCRIPTION
**Pull request by utchoang**
### Description

Fixes https://github.com/apache/cloudstack/issues/5444

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### Screenshots (if appropriate):
BEFORE
image
AFTER
image

### CODE REVIEW

**Comment by utchoang** [comment]
@blueorangutan ui

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
@blueorangutan ui

**Review by shwstppr — APPROVED** [review]

**Comment by shwstppr** [comment]
Tested on Firefox 92 with Ubuntu 20.04

**Comment by nvazquez** [comment]
Thanks for the fix @utchoang

**Comment by NuxRo** [comment]
Great, LGTM

**Pull request merged**
