### PR TITLE
upgrade: move 4.19.0->4.20.0 to 4.19.1->4.20.0

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR move upgrade files for 4.19.0->4.20.0 to 4.19.1->4.20.0

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
code looks good, but let's wait untill we are sure 4.19.1 is out.

**Review by rohityadavcloud — APPROVED** [review]
May need testing, but lgtm

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Review by shwstppr — APPROVED** [review]
LGTM

@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
> code looks good, but let's wait untill we are sure 4.19.1 is out.

Can we say 4.19.1 will be released before 4.20 now?
:-D

**Comment by shwstppr** [comment]
@blueorangutan test matrix

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan  test matrix

**Comment by shwstppr** [comment]
@blueorangutan test matrix

**Comment by shwstppr** [comment]
Verified presence of DB changes from 4.19.0 to 4.19.1 and 4.19.1 to 4.20.0 upgrade paths in an env with PR packages,

From 4.19.1 upgrade path:
https://github.com/apache/cloudstack/blob/dc593c543a6bb118d4db5572a1b36e96cf0e34db/engine/schema/src/main/resources/META-INF/db/schema-41900to41910.sql#L35

```
MariaDB [cloud]> describe cloud_usage.usage_networks;
+---------------------+---------------------+------+-----+---------+----------------+
| Field               | Type                | Null | Key | Default | Extra          |
+---------------------+---------------------+------+-----+---------+----------------+
| id                  | bigint(20) unsigned | NO   | PRI | NULL    | auto_increment |
| network_offering_id | bigint(20) unsigned | NO   |     | NULL    |                |
| zone_id             | bigint(20) unsigned | NO   |     | NULL    |                |
| network_id          | bigint(20) unsigned | NO   |     | NULL    |                |
| account_id          | bigint(20) unsigned | NO   |     | NULL    |                |
| domain_id           | bigint(20) unsigned | NO   |     | NULL    |                |
| state               | varchar(100)        | YES  |     | NULL    |                |
| removed             | datetime            | YES  |     | NULL    |                |
| created             | datetime            | NO   |     | NULL    |                |
+---------------------+---------------------+------+-----+---------+----------------+
9 rows in set (0.00 sec)
```
`cloud_usage.usage_networks` Table exist

https://github.com/apache/cloudstack/blob/dc593c543a6bb118d4db5572a1b36e96cf0e34db/engine/schema/src/main/resources/META-INF/db/schema-41900to41910.sql#L67
```
MariaDB [cloud]> describe cloud.user_data;
+------------+---------------------+------+-----+---------+----------------+
| Field      | Type                | Null | Key | Default | Extra          |
+------------+---------------------+------+-----+---------+----------------+
| id         | bigint(20) unsigned | NO   | PRI | NULL    | auto_increment |
| uuid       | varchar(40)         | NO   | UNI | NULL    |                |
| name       | varchar(256)        | NO   |     | NULL    |                |
| account_id | bigint(20) unsigned | NO   | MUL | NULL    |                |
| domain_id  | bigint(20) unsigned | NO   | MUL | NULL    |                |
| user_data  | mediumtext          | YES  |     | NULL    |                |
| params     | mediumtext          | YES  |     | NULL    |                |
| removed    | datetime            | YES  |     | NULL    |                |
+------------+---------------------+------+-----+---------+----------------+
8 rows in set (0.00 sec)
```
`removed` column present


From 4.20 upgrade path,
https://github.com/apache/cloudstack/blob/dc593c543a6bb118d4db5572a1b36e96cf0e34db/engine/schema/src/main/resources/META-INF/db/schema-41910to42000.sql#L23
```
MariaDB [cloud]> describe cloud.resource_limit;
+------------+---------------------+------+-----+---------+----------------+
| Field      | Type                | Null | Key | Default | Extra          |
+------------+---------------------+------+-----+---------+----------------+
| id         | bigint(20) unsigned | NO   | PRI | NULL    | auto_increment |
| domain_id  | bigint(20) unsigned | YES  | MUL | NULL    |                |
| account_id | bigint(20) unsigned | YES  | MUL | NULL    |                |
| type       | varchar(255)        | YES  |     | NULL    |                |
| max        | bigint(20)          | NO   |     | -1      |                |
| tag        | varchar(64)         | YES  |     | NULL    |                |
+------------+---------------------+------+-----+---------+----------------+
6 rows in set (0.00 sec)
```
`tag` column present

https://github.com/apache/cloudstack/blob/dc593c543a6bb118d4db5572a1b36e96cf0e34db/engine/schema/src/main/resources/META-INF/db/schema-41910to42000.sql#L84
```
MariaDB [cloud]> describe cloud.host_tags;
+---------------+---------------------+------+-----+---------+----------------+
| Field         | Type                | Null | Key | Default | Extra          |
+---------------+---------------------+------+-----+---------+----------------+
| id            | bigint(20) unsigned | NO   | PRI | NULL    | auto_increment |
| host_id       | bigint(20) unsigned | NO   | MUL | NULL    |                |
| tag           | text                | NO   |     | NULL    |                |
| is_tag_a_rule | int(1) unsigned     | NO   |     | 0       |                |
| is_implicit   | int(1) unsigned     | NO   |     | 0       |                |
+---------------+---------------------+------+-----+---------+----------------+
5 rows in set (0.00 sec)
```
`is_implicit` column present

**Comment by weizhouapache** [comment]
great, thanks @shwstppr for the verification

**Comment by DaanHoogland** [comment]
I think we should/would  wait with merging this untill 4.19.1 is out. in main a reliance on a non existing path is created now.

**Comment by shwstppr** [comment]
@DaanHoogland you may revert but this is causing test and functional failures. Also, we have added a similar change in the past as well

**Comment by DaanHoogland** [comment]
@shwstppr what failures are those?

**Comment by shwstppr** [comment]
@DaanHoogland https://github.com/apache/cloudstack/pull/8674#issuecomment-2138150833

**Comment by DaanHoogland** [comment]
ok thanks @shwstppr makes sense. Please note this @sureshanaparti @JoaoJandre , that releasing 4.19.1 before 20 is no longer an option!

**Comment by weizhouapache** [comment]
> ok thanks @shwstppr makes sense. Please note this @sureshanaparti @JoaoJandre , that releasing 4.19.1 before 20 is no longer an option!

@DaanHoogland 
I think this will not impact 4.19.1 release
I think we have consensus that 4.20 will be released after 4.19.1

**Pull request merged**
