### PR TITLE
cks: Refactor to externalize scripts

### PR DESCRIPTION
**Pull request by davidjumani**
### Description

Externalizes most scripts used by CKS into the ISO
This way in case there are issues with the scripts, there won't be a need to wait for the next release for a fix.
Instead the ISOs can be rebuilt with the patch and re-registered

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [x] Major
- [ ] Minor

### How Has This Been Tested?

```
=== TestName: test_01_invalid_upgrade_kubernetes_cluster | Status : SUCCESS ===

=== TestName: test_02_upgrade_kubernetes_cluster | Status : SUCCESS ===

=== TestName: test_03_deploy_and_scale_kubernetes_cluster | Status : SUCCESS ===

=== TestName: test_04_autoscale_kubernetes_cluster | Status : SUCCESS ===

=== TestName: test_05_basic_lifecycle_kubernetes_cluster | Status : SUCCESS ===

=== TestName: test_06_delete_kubernetes_cluster | Status : SUCCESS ===

=== TestName: test_07_deploy_kubernetes_ha_cluster | Status : SUCCESS ===

=== TestName: test_08_upgrade_kubernetes_ha_cluster | Status : SUCCESS ===

=== TestName: test_09_delete_kubernetes_ha_cluster | Status : SUCCESS ===

```

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan test

**Comment by davidjumani** [comment]
@blueorangutan test

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan test

**Comment by davidjumani** [comment]
@blueorangutan test

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
is this still relevant @davidjumani cc @shwstppr @DaanHoogland or could it be closed?

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
the kubernetes-clusters tests are failing all over so I doubt this PR is the issue, but as this is targetting these errors I think it needs more work.

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@DaanHoogland I'm not sure if this will still work and I don't have access to a cluster to test. Feel free to close this

**Comment by DaanHoogland** [comment]
@blueorangutan test alma8 kvm-alma8

**Comment by DaanHoogland** [comment]
at least 5 different error types found in those 11 failing test + failing cleanup.

closing for now I think this need a fresh start.

**Pull request closed without merging**
