### PR TITLE
Fix issues in VM Scheduler

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

When there is not enough CPU or it takes more than 1 minute of time for poll to complete, scheduled jobs are not processed or scheduled jobs are not scheduled.
This PR fixes the above issues in VM Scheduler.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan test

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by vishesh92** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@vishesh92 is this ready for merge or does it need more testing?

**Comment by vishesh92** [comment]
@DaanHoogland This is ready for merging

**Pull request merged**
