### PR TITLE
[FIX] [BACKPORT] [4.13] Rethrow takeVMSnapshot() exception

### PR DESCRIPTION
**Pull request by onitake**
## Description

Backport of #3546 to 4.13: Rethrow takeVMSnapshot() exception instead of returning null in VMSnapshotManagerImpl.

Contributes to: #3518

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

The change has been tested on the master branch for 4.14. See #3546.

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by onitake** [comment]
Are the build errors errors relevant?
I see things like
```
CloudstackAPIException: Execute cmd: listprojectaccounts failed, due to: errorCode: 431, errorText:Unable to find the project id=9
```
which doesn't look related to me at all...

**Comment by DaanHoogland** [comment]
@onitake where do you see those errors?

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by onitake** [comment]
@DaanHoogland They were in the Travis build logs linked here, which was still in "failed" state yesterday. Looks like they were from a different branch or older build?
Or maybe it was simply an intermittent failure.

**Comment by DaanHoogland** [comment]
> @DaanHoogland They were in the Travis build logs linked here, which was still in "failed" state yesterday. Looks like they were from a different branch or older build?
> Or maybe it was simply an intermittent failure.

maybe, i did re-kick travis, so... Not nice to not be able to rely on CI fully, but this is the complex eco system for you.

**Pull request merged**
