### PR TITLE
setup: pass password in quotes for cloudstack-setup-databases

### PR DESCRIPTION
**Pull request by rhtyd**
Fixes issue of passing password and management secret key with special
characters.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by rhtyd** [comment]
Suggested test cases, run the `cloudstack-setup-databases` with DB password containing special characters such as `(` and similarly pass the db secret key and management server secret key with special characters such as `&(*`. cc @Spaceman1984 @Pearl1594 @shwstppr pl help with manual test and review.

@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by shwstppr** [comment]
@blueorangutan test

**Review by shwstppr — APPROVED** [review]
LGTM, tested with cloudstack-management on centos7,

**Without change**
```
[root@srvr1 ~]# cloudstack-setup-databases cloud:'p*&assword'@localhost --deploy-as=root
Mysql user name:cloud                                                           [ OK ]
Mysql user password:******                                                      [ OK ]
Mysql server ip:localhost                                                       [ OK ]
Mysql server port:3306                                                          [ OK ]
Mysql root user name:root                                                       [ OK ]
Mysql root user password:******                                                 [ OK ]
Checking Cloud database files ...                                               [ OK ]
Checking local machine hostname ...                                             [ OK ]
Checking SELinux setup ...                                                      [ OK ]
Detected local IP address as 172.20.1.254, will use as cluster management server node IP[ OK ]
Preparing /etc/cloudstack/management/db.properties                              [ OK ]
Applying /usr/share/cloudstack-management/setup/create-database.sql             [ OK ]
Applying /usr/share/cloudstack-management/setup/create-schema.sql               [ OK ]
Applying /usr/share/cloudstack-management/setup/create-database-premium.sql     [ OK ]
Applying /usr/share/cloudstack-management/setup/create-schema-premium.sql       [ OK ]
Applying /usr/share/cloudstack-management/setup/server-setup.sql                [ OK ]
Applying /usr/share/cloudstack-management/setup/templates.sql                   [ OK ]
Processing encryption ...                                                       Traceback (most recent call last):
  File "/usr/bin/cloudstack-setup-databases", line 605, in <module>
    o.run()
  File "/usr/bin/cloudstack-setup-databases", line 594, in run
    self.processEncryptionStuff()
  File "/usr/bin/cloudstack-setup-databases", line 420, in processEncryptionStuff
    encryptDBPassword()
  File "/usr/bin/cloudstack-setup-databases", line 409, in encryptDBPassword
    self.putDbProperty('db.cloud.password', formatEncryptResult(encrypt(dbPassword)))
  File "/usr/bin/cloudstack-setup-databases", line 393, in encrypt
    return str(runCmd(cmd)).strip('\r\n')
  File "/usr/bin/cloudstack-setup-databases", line 52, in runCmd
    raise Exception(stderr)
Exception: b'/bin/sh: assword: command not found\n\nUSAGE: encrypt.sh [ARGUMENTS]\n\n  * Arguments must apply to format:\n\n      "arg1=value1 arg2=value2 arg3=value3 ..."\n\n  * Required arguments:\n\n      input\n      password\n\n  * Optional arguments:\n\n      verbose\n      algorithm\n      keyObtentionIterations\n      saltGeneratorClassName\n      providerName\n      providerClassName\n      stringOutputType\n      ivGeneratorClassName\n'
```

**With change:**
```
[root@srvr1 ~]# cloudstack-setup-databases cloud:'p*&assword'@localhost --deploy-as=root
Mysql user name:cloud                                                           [ OK ]
Mysql user password:******                                                      [ OK ]
Mysql server ip:localhost                                                       [ OK ]
Mysql server port:3306                                                          [ OK ]
Mysql root user name:root                                                       [ OK ]
Mysql root user password:******                                                 [ OK ]
Checking Cloud database files ...                                               [ OK ]
Checking local machine hostname ...                                             [ OK ]
Checking SELinux setup ...                                                      [ OK ]
Detected local IP address as 172.20.1.254, will use as cluster management server node IP[ OK ]
Preparing /etc/cloudstack/management/db.properties                              [ OK ]
Applying /usr/share/cloudstack-management/setup/create-database.sql             [ OK ]
Applying /usr/share/cloudstack-management/setup/create-schema.sql               [ OK ]
Applying /usr/share/cloudstack-management/setup/create-database-premium.sql     [ OK ]
Applying /usr/share/cloudstack-management/setup/create-schema-premium.sql       [ OK ]
Applying /usr/share/cloudstack-management/setup/server-setup.sql                [ OK ]
Applying /usr/share/cloudstack-management/setup/templates.sql                   [ OK ]
Processing encryption ...                                                       [ OK ]
Finalizing setup ...                                                            [ OK ]

CloudStack has successfully initialized database, you can check your database configuration in /etc/cloudstack/management/db.properties
```

**Review by Spaceman1984 — APPROVED** [review]

**Comment by Spaceman1984** [comment]
Tested LGTM - works as expected

**Review by sureshanaparti — APPROVED** [review]
code LGTM

**Review by Pearl1594 — APPROVED** [review]
Verified behavior. LGTM.

**Comment by rhtyd** [comment]
@blueorangutan test

**Pull request merged**
