### PR TITLE
[blocker] cloudstack: fix upgrade paths to 4.10.0

### PR DESCRIPTION
**Pull request by rhtyd**
This adds an upgrade to master since the recent 4.9 cut, adds an upgrade path to the new code version 4.10. Without this PR all PRs to master are failing due to missing upgrade path. Please merge this on priority.

Code review and Travis results should be enough to validate the changes.

/cc @karuturi @wido @ProjectMoon @abhinandanprateek

### CODE REVIEW

**Comment by karuturi** [comment]
code looks good. 
I am seeing the following travis errors
`[ERROR] Failed to execute goal on project travis-build-deps: Could not resolve dependencies for project org.apache.cloudstack:travis-build-deps:jar:1: Failure to find net.nuage.vsp:nuage-vsp-acs-client:jar:3.2.8.0 in http://repo1.maven.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of Central has elapsed or updates are forced -> [Help 1]`
`[ERROR] Failed to execute goal on project cloud-developer: Could not resolve dependencies for project org.apache.cloudstack:cloud-developer:pom:4.10.0-SNAPSHOT: Could not find artifact org.apache.cloudstack:cloud-server:jar:4.10.0-SNAPSHOT in apache.snapshots (http://repository.apache.org/snapshots) -> [Help 1]`
Can you force push please?

**Comment by rhtyd** [comment]
@karuturi thanks, I'll have a look why it failed

**Comment by rhtyd** [comment]
Looks like this unit test failed: Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.773 sec <<< FAILURE! - in org.apache.cloudstack.network.lb.ApplicationLoadBalancerTest

I've seen this unit test fail sometimes, any ideas?

**Comment by karuturi** [comment]
@blueorangutan the link doesnt work

**Comment by rhtyd** [comment]
@karuturi that's a bot account that will do packaging and testing for us soon, I was testing it :)

**Comment by rhtyd** [comment]
Looks like this unit test is known to consume a lot of memory: Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.918 sec - in org.apache.cloudstack.network.lb.ApplicationLoadBalancerTest
java.lang.OutOfMemoryError: PermGen space

**Comment by karuturi** [comment]
Where did you see the OOM error? I dont see it in travis logs 
(this is for the previous travis job) https://s3.amazonaws.com/archive.travis-ci.org/jobs/149684289/log.txt

**Comment by rhtyd** [comment]
@karuturi on the machine which was building the rpm packages

**Comment by rhtyd** [comment]
The unit test again failed with Travis:
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.821 sec <<< FAILURE! - in org.apache.cloudstack.network.lb.ApplicationLoadBalancerTest

**Comment by rhtyd** [comment]
I'm able to consistently reproduce the unit test failure on a machine with similar memory as Travis (~8GB RAM):
searchForExistingLoadBalancer(org.apache.cloudstack.network.lb.ApplicationLoadBalancerTest)  Time elapsed: 2.774 sec  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.CacheAwareContextLoaderDelegate.loadContext(CacheAwareContextLoaderDelegate.java:103)
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:122)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:109)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:75)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:321)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:211)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:288)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:284)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:231)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:88)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:174)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: file [/var/jenkins/workspace/cloudstack-pr/server/target/classes/org/apache/cloudstack/network/lb/CertServiceImpl.class]; nested exception is java.lang.OutOfMemoryError: PermGen space

**Comment by rhtyd** [comment]
@karuturi all green now, can we merge this? /cc @jburwell

**Comment by karuturi** [comment]
yup... started testing.. in progress.. will be done probably in 30 min.. 
you started automation run.. should we wait for that?

**Comment by rhtyd** [comment]
@karuturi our Trillian job has hit an internal bug so the job died, nevertheless a single run could take hours against real hypervisors (we've xen, kvm and vmware). I'll keep you posted when we've got that fixed and the PR-testing pipeline fixed. Meanwhile, we can consider Travis and your test results.

**Comment by rhtyd** [comment]
Thanks @karuturi

**Pull request merged**
