### PR TITLE
Add missing labels and sort them

### PR DESCRIPTION
**Pull request by davidjumani**
### Description

Adds missing vswitch labels and sorts en.json

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### Screenshots (if appropriate):

after

before

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan ui

**Comment by utchoang** [comment]
@blueorangutan ui

**Review by utchoang — APPROVED** [review]
LGTM!

**Review by nvazquez — APPROVED** [review]
LGTM

image

**Pull request merged**
