### PR TITLE
CLOUDSTACK-8625: Systemd profile for CloudStack Agent

### PR DESCRIPTION
**Pull request by wido**
With CentOS 7 and Ubuntu 16.04 (to be released) using systemd
it is preferred that CloudStack's Agent is also being started using
systemd.

This commit includes a service file for the CloudStack Agent with
a wrapper script which actually executes Java

It no longer uses jsvc for daemonizing and thus this requirement
has also been dropped for CentOS 7 packaging.

The Agent log output to stdout has also been modified to no longer
include the timestamp as this is done by journalctl.

This has been tested on a CentOS 7.1 machine and the Agent starts,
stops and restarts properly.

### CODE REVIEW

**Comment by remibergsma** [comment]
@wido Cool, thank you! Will test tomorrow :-)

**Comment by remibergsma** [comment]
Hey @wido.. question: I tried building the packages:
`./package.sh -d centos7`

Got this error:
```
Processing files: cloudstack-agent-4.6.0-SNAPSHOT.el7.centos.x86_64
error: File not found: /data/git/cs3/cloudstack/dist/rpmbuild/BUILDROOT/cloudstack-4.6.0-SNAPSHOT.el7.centos.x86_64/etc/init.d/cloudstack-agent

RPM build errors:
    Binaries arch (1) not matching the package arch (2).
    File not found: /data/git/cs3/cloudstack/dist/rpmbuild/BUILDROOT/cloudstack-4.6.0-SNAPSHOT.el7.centos.x86_64/etc/init.d/cloudstack-agent
RPM Build Failed
```

In `./centos7/cloud.spec` line `491` I see:
```
%attr(0755,root,root) %{_sysconfdir}/init.d/%{name}-agent
```

I assume this line needs to be removed? Or am I missing something?

**Comment by remibergsma** [comment]
@wido In order to get it to work on CentOS 7 I had to patch it like this. You may want to add it to the PR:

```
diff --git a/packaging/centos7/cloud.spec b/packaging/centos7/cloud.spec
index 0ecc406..2028981 100644
--- a/packaging/centos7/cloud.spec
+++ b/packaging/centos7/cloud.spec
@@ -488,7 +488,8 @@ fi
 %attr(0755,root,root) %{_bindir}/%{name}-setup-agent
 %attr(0755,root,root) %{_bindir}/%{name}-agent-upgrade
 %attr(0755,root,root) %{_bindir}/%{name}-ssh
-%attr(0755,root,root) %{_sysconfdir}/init.d/%{name}-agent
+%attr(0644,root,root) %{_unitdir}/%{name}-agent.service
+%attr(0755,root,root) /usr/libexec/cloudstack/cloudstack-agent-systemd-wrapper.sh
 %attr(0644,root,root) %{_sysconfdir}/profile.d/%{name}-agent-profile.sh
 %attr(0755,root,root) %{_datadir}/%{name}-common/scripts/network/cisco
 %config(noreplace) %{_sysconfdir}/%{name}/agent
```

Tested it on CentOS 7.1 KVM box and the `systemd` profile works great! If you update the PR with the above patch (or something with the same result) I'll give you my LGTM :-)

Thanks, Remi

**Comment by wido** [comment]
@remibergsma I did and made another small change. I don't have a very good CentOS dev setup here, so I wasn't able to test it very thorough.

I think this should work now.

**Comment by remibergsma** [comment]
LGTM - tested again with the new changes and the package build succeeds and the packages install fine on CentOS 7. Also tested start/stop/status and rebooted the box. All fine so GO! :+1:

**Comment by wido** [comment]
@bhaisaab Could you take a quick peek?

**Comment by bhaisaab** [comment]
LGTM :+1:

**Pull request merged**
