### PR TITLE
convert protocol names to be found as labels

### PR DESCRIPTION
**Pull request by DaanHoogland**
## Description

replace significant chars from string to find protocol labels

Fixes: #3252

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## Screenshots (if appropriate):
image

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
reviewers please consider if this is for the right milestone.

**Comment by DaanHoogland** [comment]
needs to be

**Comment by GabrielBrascher** [comment]
@DaanHoogland If we consider it as a bug then it makes sense to have it fixed on 4.13.1.0. However, if it is considered an enhancement then I don't see why not keeping the 4.14 milestone.

Looking at #3252 I would consider it as a bug on the UI; **+1** on setting it to branch 4.13 and milestone 4.13.1.0.

**Comment by DaanHoogland** [comment]
rebasing on 4.13 in #3747

**Pull request closed without merging**
