### PR TITLE
git-pr py3 compatible

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR...

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

commited manually on a local `main` and executed `git pr 6956 --force`

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by rohityadavcloud — APPROVED** [review]
LGTM - is this enough or we need to do more?

**Comment by DaanHoogland** [comment]
> LGTM - is this enough or we need to do more?

not sure, It can only be manually tested, it seems and we need it in automation. Have to think of a trick just yet.

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by davidjumani — APPROVED** [review]
CLGTM

**Comment by DaanHoogland** [comment]
testing in #6972

**Comment by rohityadavcloud** [comment]
We may need to check/fix the backend Jenkins job or make this script run with either/both py2 and py3 @DaanHoogland @davidjumani 
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan ui

**Comment by davidjumani** [comment]
@DaanHoogland @rohityadavcloud Packaging fails in this but based on my testing and https://github.com/apache/cloudstack/pull/6972 this can be merged

**Pull request merged**
