### PR TITLE
CLOUDSTACK-9208: Assertion Error in VM_POWER_STATE handler- Fixed

### PR DESCRIPTION
**Pull request by jayapalu**
This PR closes PR #1307

### CODE REVIEW

**Comment by borisstoyanov** [comment]
Thanks for this fix @jayapalu 
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by ramkatru** [comment]
@jayapalu, Please see Daan's and Wido's comments on the referenced PR #1307.

**Comment by jayapalu** [comment]
@ramkatru  I am not sure about  Daan comments. 
The tests results are positive.

**Comment by DaanHoogland** [comment]
@jayapalu your check is ok, what is not ok is that it is needed. Somehow a stop can be send to a VM for which no host is known?
I am worried about the reason of your fix and that we might obscure it. Why is a stop command attempted on a vm for which no host is known?

**Comment by jayapalu** [comment]
@DaanHoogland  In the case of VM_POWER_STATE handler, if PowerOff or PowerReportMissing state is encountered, handlePowerOffReportWithNoPendingJobsOnVM() is called. If the VM is already in stopped state, so in DB the host ID is set to NULL. But in the above function, the sendStop() is still called on the empty hostID.
So added condition in the sendStop() itself to check for the host id

**Comment by DaanHoogland** [comment]
so that is two situations
1. it is known to be powered off (no sendStop() should be performed at all)
2. it is unknown because their is no report. Wouldn't one first check the host to send the stop command to before sending it?

That said, I am +0 on this code, the check is not harming in any way.

**Comment by jayapalu** [comment]
@DaanHoogland  
When there is power-off report at time T1 and MS trying to stop the VM. Mean while the VM got stopped using the stop command and updated the host id to null at T2. After T2 vm sync (handlepoweroffreport) trying to stop the VM by the time host id was set to null.

We have seen the issue in our local setup. I have the previous logs. I am not able to reproduce it now.

 ERROR [o.a.c.f.m.MessageDispatcher] (DirectAgentCronJob-1:ctx-99d6d7e6) (logid:46851fb5) Unexpected exception when calling com.cloud.vm.ClusteredVirtualMachineManagerImpl.HandlePowerStateReport
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.cloudstack.framework.messagebus.MessageDispatcher.dispatch(MessageDispatcher.java:75)
	at org.apache.cloudstack.framework.messagebus.MessageDispatcher.onPublishMessage(MessageDispatcher.java:45)
	at org.apache.cloudstack.framework.messagebus.MessageBusBase$SubscriptionNode.notifySubscribers(MessageBusBase.java:440)
	at org.apache.cloudstack.framework.messagebus.MessageBusBase.publish(MessageBusBase.java:178)
	at com.cloud.vm.VirtualMachinePowerStateSyncImpl.processReport(VirtualMachinePowerStateSyncImpl.java:87)
	at com.cloud.vm.VirtualMachinePowerStateSyncImpl.processHostVmStatePingReport(VirtualMachinePowerStateSyncImpl.java:70)
	at com.cloud.vm.VirtualMachineManagerImpl.processCommands(VirtualMachineManagerImpl.java:2701)
	at com.cloud.agent.manager.AgentManagerImpl.handleCommands(AgentManagerImpl.java:311)
	at com.cloud.agent.manager.DirectAgentAttache$PingTask.runInContext(DirectAgentAttache.java:194)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
**Caused by: java.lang.AssertionError: Who's not checking the agent id before sending?  ... (finger wagging)**
	at com.cloud.agent.manager.AgentManagerImpl.send(AgentManagerImpl.java:405)
	at com.cloud.agent.manager.AgentManagerImpl.send(AgentManagerImpl.java:366)

**Comment by koushik-das** [comment]
Code changes LGTM

**Comment by jayapalu** [comment]
Trillian test cases and 2 LGTMs marking it as tag:mergeready

**Pull request merged**
