### PR TITLE
Adding a try catch for Xen licensing issue

### PR DESCRIPTION
**Pull request by borisstoyanov**
## Description

Adds a skip if the exception is related to licensing of the particular host
## Types of changes

- [X] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Bug fix (non-breaking change which fixes an issue)
- [X] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

Locally on a XenServer env

### CODE REVIEW

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test centos7 xenserver65

**Comment by borisstoyanov** [comment]
@blueorangutan test centos7 xenserver-65sp1

**Comment by rhtyd** [comment]
@blueorangutan test centos7 xenserver-65sp1

**Pull request merged**
