### PR TITLE
cloudstack: fix forward merge issues

### PR DESCRIPTION
**Pull request by rhtyd**
- Fixes tests path from old layout to standard maven in src/test/java/
- Removed duplicate SnapshotManagerImpl at old path `server/src/com...` (ref: 460d3127ec993eba8504f1fbcd0a69a2bb95119b)

Signed-off-by: Rohit Yadav <rohit.yadav@shapeblue.com>

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

@blueorangutan package

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@shwstppr @anuragaw @ustcweizhou @DaanHoogland - please review, thanks.

**Comment by anuragaw** [comment]
@rhtyd - SnapShotManagerImpl duplicate files are not 100% identical. I think we have removed the one that was not being executed by imports. Can you confirm?

**Comment by rhtyd** [comment]
The one we've removed is not used at all, it is outside the 'src/main/java' path.

**Comment by anuragaw** [comment]
Perfect. Thanks for confirming! LGTM

**Comment by ustcweizhou** [comment]
LGTM

**Pull request merged**
