### PR TITLE
ui: add action to delete traffic type

### LINKED ISSUE #7677: Add 'delete traffic type' option in the UI
##### ISSUE TYPE

 * Improvement Request
 

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.18
~~~

##### CONFIGURATION

ACS 4.18 with advanced zone. 

##### SUMMARY

‘deleteTrafficType’  API is available but the same is not available in the UI although add traffic type is provided. 

##### STEPS TO REPRODUCE

~~~
Click - Infrastructure->zones-> physical networks-> click physical network -> check the action buttons available. 
~~~

##### EXPECTED RESULTS

~~~
A delete traffic type button is expected in the UI for the physical networks. 
~~~

##### ACTUAL RESULTS

~~~
A delete traffic type button is not available in the UI for the physical networks.
~~~
Screenshot 2023-06-23 at 10 39 10 AM
Screenshot 2023-06-23 at 10 34 23 AM

### LINKED ISSUE #7756: Provide an option to update role of an account from the UI
ISSUE TYPE

 * Enhancement Request/Improvement Request

COMPONENT NAME

Component: UI

CLOUDSTACK VERSION

Cloudstack 4.18

SUMMARY

Provide an option to update role of an account from the UI 

Currently to update role of account is only possible from the api call 

https://cloudstack.apache.org/api/apidocs-4.18/apis/updateAccount.html

The ui only provides the option to update the name and network domain.

It would be helpfull for the admin user to update the role of an account directly from the UI ( A dropdown of various roles available in the system) 

Screenshot attached

 
Update Role

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #7677

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

#### How did you try to break this feature and the system with this change?

Screenshot from 2023-10-11 16-56-39

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by DaanHoogland** [comment]
@shwstppr in the description is says `Fixes #7756`, but that one talks about updating a user role. Should some other issue number be referenced here?

**Comment by shwstppr** [comment]
@DaanHoogland my bad. I've updated the description now

**Review by DaanHoogland — APPROVED** [review]
clgtm & 
image

**Comment by DaanHoogland** [comment]
@rajujith , can you review?

**Review by rohityadavcloud — APPROVED** [review]
LGTM -didn't test it though

**Pull request merged**
