### PR TITLE
UI: Physical Network Setup in Zone Wizard

### PR DESCRIPTION
**Pull request by utchoang**
### Description

Fixes https://github.com/apache/cloudstack/issues/4877

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### Screenshots (if appropriate):

- physical Interface 1 to bridge cloudbr01, label for management traffic (cloudbr01)

- physical Interface 2 to bridge cloudbr03, label for guest traffic (cloudbr03guest)

- physical Interface 3 to bridge cloudbr02, label for storage traffic (cloudbr02100)

RESULT:

### CODE REVIEW

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by rhtyd** [comment]
@utchoang can you change the base branch to 4.15?

**Review by rhtyd — APPROVED** [review]
LGTM, did not test it - need a manual test/review before merging this

**Comment by rhtyd** [comment]
Ping @davidjumani

**Review by davidjumani — APPROVED** [review]
LGTM. Tested with KVM and Xen labels (just on the create form)

However it the traffic label breaks for simulator (perhaps unrelated)
Screenshot from 2021-04-06 16-09-36

**Comment by rhtyd** [comment]
@Pearl1594 can you do a test against a kvm/xenserver env? See the issue ticket.

**Pull request merged**
