### PR TITLE
Update L10N files from Transifex (2016-11-27) for the new release 4.10.0.0

### PR DESCRIPTION
**Pull request by milamberspace**
I've check manually the correct display of the UI foreach language.

Don't forget to merge this before 4.10 release.

cc @jburwell @rhtyd

### CODE REVIEW

**Comment by rhtyd** [comment]
@milamberspace thanks for the PR, can you get a JIRA id for this. I'll kick one manual test to see that UI is broken.

@blueorangutan package

**Comment by milamberspace** [comment]
@rhtyd Done: CLOUDSTACK-9621

https://issues.apache.org/jira/browse/CLOUDSTACK-9621

**Comment by rhtyd** [comment]
Thanks @milamberspace can you also use that JIRA id in the git commit summary such as:
`CLOUDSTACK-xxxx: one liner...`

**Comment by milamberspace** [comment]
@rhtyd done.

**Comment by rhtyd** [comment]
LGTM, did manual tests. Cycled between various lang options, don't see any failures.

**Comment by rhtyd** [comment]
Thanks @milamberspace I'll proceed with the merge now.

**Pull request merged**
