### PR TITLE
CLOUDSTACK-8924: Enable dynamic scaling to run test_scale_vm.py test on simulator

### PR DESCRIPTION
**Pull request by sanju1010**
Simulator setup uses the config file from following location:
tools/marvin/marvin/config/setup.cfg
Added global setting parameter "enable.dynamic.scale.vm" to above config file, so that dynamic scale vm tests can be run on simulator.

### CODE REVIEW

**Comment by wilderrodrigues** [comment]
@sanju1010 ,

Did you execute the tests after the change?

Cheers,
Wilder

**Comment by pvr9711** [comment]
@sanju1010  this is not the right file - the following file needs to be updated - https://github.com/apache/cloudstack/blob/94f1ebb60af320166206c213e18b97a177bc145a/setup/dev/basic.cfg 
No Go for this change.

**Comment by remibergsma** [comment]
@sanju1010 Any update on this?

**Comment by sanju1010** [comment]
@pvr9711 can you please review this PR? I have made changes as per the review comments and rebased it with master.

**Comment by pvr9711** [comment]
LGTM, I have tested this on a private setup and is working.

**Comment by remibergsma** [comment]
@pvr9711 Can you please share the test results or explain what you did to test?

**Comment by karuturi** [comment]
Simple configuration change. Code LGTM

**Comment by bhaisaab** [comment]
LGTM

**Pull request merged**
