### PR TITLE
plugins/pom.xml: build nsx only if noredist is passed

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

The nsx plugin relies on some 3rd-party jars

It causes the failures of docker image builds. https://github.com/apache/cloudstack/actions/runs/8197923589/job/22420629450

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by nvazquez — APPROVED** [review]

**Review by Pearl1594 — APPROVED** [review]

**Comment by weizhouapache** [comment]
thanks @nvazquez @Pearl1594 for approvals


@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test matrix

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@nvazquez @Pearl1594 
I made other changes after your approvals.
This may need some re-review and testing now

**Comment by weizhouapache** [comment]
@blueorangutan test

**Review by slavkap — APPROVED** [review]
LGTM, I only tested the build

**Comment by weizhouapache** [comment]
> LGTM, I only tested the build

thanks @slavkap 


@nvazquez @Pearl1594 
can you verify the NSX changes in this PR ?

**Comment by nvazquez** [comment]
@weizhouapache changes look good, we'll test it with NSX to double check there are no regressions

**Review by rohityadavcloud — APPROVED** [review]
Didn't test but LGTM

**Review by nvazquez — APPROVED** [review]
LGTM - no regressions found on NSX workflow

**Comment by weizhouapache** [comment]
thanks @nvazquez for the testing

merging

**Pull request merged**
