### PR TITLE
CLOUDSTACK-9481: Convert MyISAM table to InnoDB for consistency

### PR DESCRIPTION
**Pull request by abhinandanprateek**

### CODE REVIEW

**Comment by rhtyd** [comment]
@abhinandanprateek can you reopen this for 4.9 branch, since it's a bugfix. LTS users should all be on innodb to avoid any replication issues, please also move the changes suitably to 4.9.0->4.9.1(.0) upgrade path sql. Otherwise LGTM.

Tried on a local setup. To list tables that are on non-InnoDb engines:
`SELECT table_schema,table_name,engine FROM information_schema.tables WHERE engine != 'InnoDB' AND table_schema NOT IN ('mysql','performance_schema','information_schema');`

Except for following tables, all should be on InnoDb engine.

table_schema | table_name    | engine
--- | --- | ---
cloud        | op_lock              | MEMORY
cloud        | op_nwgrp_work | MEMORY

**Comment by rhtyd** [comment]
LGTM. @abhinandanprateek can you edit the base branch of this PR to 4.9. Thanks.

**Comment by abhinandanprateek** [comment]
@rhtyd created another PR for 4.9 https://github.com/apache/cloudstack/pull/1670

**Comment by rhtyd** [comment]
@abhinandanprateek thanks, can you close this one?

**Comment by abhinandanprateek** [comment]
Closing as it is already merged.

**Pull request closed without merging**
