### PR TITLE
Enable Backup and Recovery for Shared Filesystems

### PR DESCRIPTION
**Pull request by abh1sar**
### Description

This PR allows Backup and Recovery operations on Shared FileSystem Instances.
- It was disallowed earlier to reduce interactions
- Prospect users suggested that it is a very useful feature to have and will negatively impact feature adoption
- Backup and Recovery works out of the box with Shared FIleSystems Instances as with any other instance. No special changes are required to support it. I only had to remove certain checks.
- This change has no interaction with any other subsystem of cloudstack.
- Tested all workflows with NAS BnR plugin.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [x] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by abh1sar** [comment]
@blueorangutan package

**Comment by abh1sar** [comment]
@blueorangutan package

**Comment by abh1sar** [comment]
@blueorangutan ui

**Review by DaanHoogland — COMMENTED** [review]
looks good, but can you provide some background @abh1sar ? (why was it disabled first and why is that no longer necessary)

**Review by rohityadavcloud — APPROVED** [review]
LGTM didn't test it

**Comment by borisstoyanov** [comment]
> looks good, but can you provide some background @abh1sar ? (why was it disabled first and why is that no longer necessary)

prospect users reported that the Shared Filesystem feature would be deemed unusable without backups enabled and we identified the functionality as blocker for the feature, that's why we decided to included it as well, I'm currently testing it. Thanks.

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Review by borisstoyanov — APPROVED** [review]
LGTM, 
I've tested this with NAS plugin setup for backups and was able to cover all of the main functions of backups (create, delete, schedule, remove etc).

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Review by DaanHoogland — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by abh1sar** [comment]
@JoaoJandre This is deemed a blocker for the Shared FileSystems feature. The change involves removing certain checks related to Shared FileSystems Instances and BnR. BnR works with Shared FS Instances like any other instance without any need for code change. This change doesn't affect other subsystems in any way.

**Comment by rohityadavcloud** [comment]
@JoaoJandre over to you to review. This is considered blocker wrt the new feature, though not necessarily a regression/blocker for normal/usual operations.
Re-running test (though not strictly required)
@blueorangutan test

**Review by JoaoJandre — APPROVED** [review]
Code LGTM. But this is not really a blocker, is it? I can see that it is important to the feature overall but not having this will not break anything. I'll merge this as it is a really simple change that has been tested by the community. But I'll change the label as from the release perspective this is not a blocker and labeling it so is misleading.

**Pull request merged**
