### PR TITLE
CLOUDSTACK-9313: Remove unused code from CloudZoneStartupProcessor

### PR DESCRIPTION
**Pull request by cristofolini**
Upon analyzing the `CloudZoneStartupProcessor` class, we noticed most of its content consisted of either commented out or unused code. To make it easier to deal with this class in the future and to improve code readability, I've taken the liberty to remove said unused code.

### CODE REVIEW

**Comment by eriweb** [comment]
For tracking purposes, would you mind creating a Jira ticket for this, and add the jira ID to the title?

**Comment by GabrielBrascher** [comment]
@eriweb, as far as I know, JIRA is used for bug/issue tracking. JIRA is a way that users have to report bugs. Based on JIRA, developers can track and fix issues. I do not see why create a JIRA ticket here.

**Comment by eriweb** [comment]
Jira is used for more than you might think.
It is used to build release notes as well as a metric in board reports for community activity.

There is no reason not to file a ticket, just mark it as improvement.

**Comment by GabrielBrascher** [comment]
@eriweb, I didn't considered JIRA looking to this point of view (track changes in the release note). With that in mind it seems an interesting approach.

**Comment by cristofolini** [comment]
@eriweb @GabrielBrascher Thanks for the suggestion! I've gone ahead and opened a ticket and updated the title of this PR.

**Comment by rafaelweingartner** [comment]
I took the liberty and fixed the conflicts of this PR.
Now everything seems ok to go

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@cristofolini if this is still valid please rebase and re-open

**Pull request closed without merging**
