### PR TITLE
engine/schema: add upgrade path for source 4.11.2.0 version

### PR DESCRIPTION
**Pull request by rhtyd**
This adds a missing upgrade path for source version 4.11.2.0. Without
this fix, 4.11.2.0 users won't be able to upgrade to 4.11.3.0.

The issue for 4.11.2.0 users will be that the expected DB upgrade exception will not be thrown around the 4.11.3 systemvmtemplate checks and post-upgrade any registered 4.11.3.0 systemvmtemplate will not be automatically used for systemvms and VRs.

We couldn't catch the bug before because an explicit upgrade from 4.11.2.0 was not tested (at least by me).

Workaround: (based on https://github.com/apache/cloudstack/blob/4.11/engine/schema/src/com/cloud/upgrade/dao/Upgrade41120to41130.java#L156)
- Set the 4.11.3 template to SYSTEM type
- Update template ID for systemvms
- Update the router.template.* for each hypervisor
- Update minreq.sysvmtemplate.version to 4.11.3
- Update template checksum (optional)

Mgmt log reference:
```
2019-06-24 12:35:26,589 INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Grabbing lock to check for database upgrade.
2019-06-24 12:35:26,611 DEBUG [c.c.u.d.VersionDaoImpl] (main:null) (logid:) Checking to see if the database is at a version before it was the version table is created
2019-06-24 12:35:26,621 INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) DB version = 4.11.2.0 Code Version = 4.11.3.0
2019-06-24 12:35:26,621 INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Database upgrade must be performed from 4.11.2.0 to 4.11.3.0
2019-06-24 12:35:26,623 DEBUG [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Running upgrade NoopDbUpgrade to upgrade from 4.11.2.0-4.11.3.0 to 4.11.3.0
2019-06-24 12:35:26,640 INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Cleanup upgrade NoopDbUpgrade to upgrade from 4.11.2.0-4.11.3.0 to 4.11.3.0
2019-06-24 12:35:26,663 DEBUG [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Upgrade completed for version 4.11.3.0
```

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@PaulAngus let's do a 4.11.3.1, or recall on 4.11.3.0 as it's not announced/published yet.
@blueorangutan test matrix

**Comment by borisstoyanov** [comment]
looks good, will check it out when we have Jenkins back up

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan test matrix

**Comment by PaulAngus** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
KVM env test failed due to backend IP-range issues, I've rekicked the test job.
Will merge this as soon as the KVM tests are in.

**Comment by rhtyd** [comment]
@PaulAngus 4.11.3.0 RC2 can be cut now out of latest 4.11 branch. Thanks.

**Pull request merged**
