### PR TITLE
api, ui: listing archived events

### LINKED ISSUE #7217: Ability to view Archived events
##### ISSUE TYPE

 * Enhancement Request

##### COMPONENT NAME

~~~
Componet:UI
Componet:api
~~~

##### CLOUDSTACK VERSION

~~~
4.18 nightly
4.17.2

~~~

##### SUMMARY

Ability to view Archived events

This is a minor ui enhancement request but good to have for the admin users for quick search of archived events

Admin user may want to view the Archived events from the UI

Currently, there is no way to view the archived events

https://cloudstack.apache.org/api/apidocs-4.17/apis/listEvents.html

The only way is from the Database, there is an archived field in the event table 

It will be good to have this feature in case the admin wants to view the archived events
archive-events

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #7217

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):

Screenshot from 2023-04-05 11-32-07

Screenshot from 2023-04-05 11-40-59

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@DaanHoogland this needs more changes. I need to add ui changes to view archived events

**Comment by DaanHoogland** [comment]
ok, if you want those in teh same PR , go ahead.

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Review by kiranchavala — APPROVED** [review]
Tested the feature LGTM

Able to see the archived events
archive1
archive

**Pull request merged**
