### PR TITLE
plugins/shutdown: fix triggerShutdown scheduling and response

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Earlier the triggerShutdown API would immediately shutdown the MS and if it is the same MS on which API is called and there are no pending jobs it would lead to error in the API call. This change adds a delay to the process so the MS would be able to send response to the API.

This should fix test failure seen in PR wrt test_safe_shutdown.py,
https://github.com/apache/cloudstack/pull/8601#issuecomment-2177437854https://github.com/apache/cloudstack/pull/8601#issuecomment-2177479552

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?
Without fix: 
```
localcloud) 🐱 > trigger shutdown managementserverid=1
🙈 Error: Get "http://1.2.3.4:8080/client/api?apiKey=LIN6rqXuaJwMPfGYFh13qDwYz5VNNz1J2J6qIOWcd3oLQOq0WtD4CwRundBL6rzXToa3lQOC_vKjI3nkHtiD8Q&command=triggerShutdown&managementserverid=1&response=json&signature=7PpZ8vp4jKIbTe41HqhNwfjVp4g%3D": dial tcp 1.2.3.4:8080: connect: connection refused
```

After fix:
```
(local) 🐱 > trigger shutdown managementserverid=1
{
  "triggershutdown": {
    "managementserverid": 1,
    "pendingjobscount": 0,
    "readyforshutdown": true,
    "shutdowntriggered": true
  }
}
```

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
nice catch @shwstppr , CLGTM

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
No issues with safe shutdown test, merging based on review / test result.

**Pull request merged**
