### PR TITLE
Use java.io.tmpdir instead of hardcoded /tmp

### PR DESCRIPTION
**Pull request by wido**
Small fix to have the tests also work on other platforms

### CODE REVIEW

**Comment by borisroman** [comment]
LGTM -> Unit test works as expected.

**Comment by pdube** [comment]
LGTM

**Comment by resmo** [comment]
LGTM

**Comment by remibergsma** [comment]
Hi @wido please don't merge stuff right now (see http://mail-archives.apache.org/mod_mbox/cloudstack-dev/201509.mbox/browser)
It also broke the build, but it was cloudstack-apidocs-master and not master so I concluded that bit too fast. Maybe you can look into it anyway and then once the VR stuff is in better shape we can consider merging it to 4.6. Thanks!

**Comment by wido** [comment]
@remibergsma Oops! I missed that e-mail while working on it this morning. I'll stay off master :)

**Comment by remibergsma** [comment]
@wido Great, thanks!

**Comment by wido** [comment]
@remibergsma This PR is marked as closed, but it was actually reverted.

Although it's not a bugfix, it is a fix for the Unit Tests on Windows. Do we want to merge this in to master?

**Comment by wido** [comment]
@remibergsma ping? ^^

**Comment by remibergsma** [comment]
@wido Please send a new PR with this commit, I tried merging it again but that gives issues. We can proceed fast with this when you link the new one to this PR. Thanks and sorry for the delay.

**Comment by remibergsma** [comment]
@wido Would be nice if the commit hash changed, so Github doesn't recognise it as already being merged.

**Pull request merged**
