### PR TITLE
Fixup e2e test_restore_vm

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR fixes e2e test for restore_vm

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by vishesh92** [comment]
@blueorangutan package

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Comment by weizhouapache** [comment]
```
======================================================================
ERROR: Test restore virtual machine
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/marvin/tests/smoke/test_restore_vm.py", line 75, in test_01_restore_vm
    self.assertEqual(root_vol.size, self.template_t1.size, "Size of volume and template should match")
AttributeError: 'Template' object has no attribute 'size'
```

and

```
======================================================================
ERROR: Test restore virtual machine with root disk in allocated state
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/marvin/tests/smoke/test_restore_vm.py", line 97, in test_02_restore_vm_allocated_root
    self.assertEqual(root_vol.size, self.template_t1.size, "Size of volume and template should match")
AttributeError: 'Template' object has no attribute 'size'
```

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan test

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan test

**Pull request merged**
