### PR TITLE
Fix attach volume error for VM - different scope for VM volume and volume disk offering

### PR DESCRIPTION
**Pull request by nvazquez**
### Description

This PR fixes an issue attaching a volume to a VM with volume on zone-wide storage pool, for target cluster-wide storage according the disk offering

Fixes: #5916 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [x] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by nvazquez** [comment]
Tested on simulator (with the use of PR #5986 to allow zone-wide storage):

Cluster 1: NFS store 1 and 2 cluster-wide stores
Cluster 2: NFS store 3 and 4 cluster-wide stores
Zone wide: NFS store 5
Disk offering: storage tag A
VM deployed cluster 1, ROOT disk on zone-wide storage 5

Case 1:
- Set NFS store 1 storage tag = A
- Create a disk with offering A
- Attach to VM -> SUCCESS

Case 2:
- Remove storage tag from NFS store 1 and set NFS store 3 tag = A
- Create a disk with offering A
- Attach to VM -> FAILURE (as the target cluster is different from the VM cluster)

@DaanHoogland @slavkap the failure on case 2 can be solved if prior to the disk attach, the VM is migrated to a host in the same cluster as the store with has the storage tag of the disk. Do you think this case should be fixed by the code as well or handled as an operational issue?

**Review by DaanHoogland — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@nvazquez I think we can offer in the UI but the API is clear cut and doesn't need this extra action. This is a scripting issue to me, and the UI could do that or terraform or some other automation framework. But the backend should not do this automatically.
€0,02

**Review by slavkap — APPROVED** [review]
LGTM manually tested, and only the 1st case works

**Comment by nvazquez** [comment]
Thanks @DaanHoogland @slavkap!
@blueorangutan test matrix

**Pull request merged**
