### PR TITLE
Upgrade netty version

### PR DESCRIPTION
**Pull request by nvazquez**
### Description

This PR upgrades netty version to a patched version - CVE: https://github.com/advisories/GHSA-p979-4mfw-53vg
Fixes: #6058 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Review by weizhouapache — APPROVED** [review]
code lgtm
need manual testing

**Comment by weizhouapache** [comment]
upload template/iso from local are tested ok.

**Review by rohityadavcloud — APPROVED** [review]
Lgtm

**Pull request merged**
