### PR TITLE
Improved perfomance on creating VM (KVM)

### PR DESCRIPTION
**Pull request by alexanderbazhenoff**
Improved perfomance on creating VM for KVM virtualization.

On a huge hosts every "ifconfig | grep" takes a lot of time (about 2.5-3 minutes on hosts with 500 machines). For example: `ip link show dev $vlanDev > /dev/null` is faster than `ifconfig |grep -w $vlanDev > /dev/null`. But using `ip` command is much better. Using this patch you can create 500s machine in 10 seconds. You don't need slow `ifconfig` prints anymore.

PS: Feel free to make the same patches for xenserver :)

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

More than 500VMs orchestration on the same host (1 x VCPU, 384 Mb ram, Linux).
Created 500 VMs using python scripts. Measured time.

2 x Xeon E5 CPU + 256Gb RAM + 2 x SSDs.
Managment, Database, baremetal agent on the same server. ZFS filesystem pool for NFS share (primary/secondary). KVM virtualization on the host.

No affects. Just replaced ifconfig with ip.

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@alexanderbazhenoff can you rebase and edit base branch to 4.11 if possible?

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by alexanderbazhenoff** [comment]
Opps, found some strange `-gt` condition.
`# is vlanBr up?`
 `ip link show dev $vlanBr > /dev/null 2>/dev/null`
` if [ $? --gt 0 ]`
Should be  `-eq` there

Please don't commit until we test and change this. Thanks.

**Comment by bwsw** [comment]
@rhtyd why don't you use 

```
grep 'veth20fd2a1:' /proc/net/dev
```

instead of calling for `ip` command?

More specifically:

```
if grep -q 'eth0:' /proc/net/dev
then
 ....
fi
```

**Comment by rafaelweingartner** [comment]
> 
> 
> Opps, found some strange `-gt` condition.
> `# is vlanBr up?`
> `ip link show dev $vlanBr > /dev/null 2>/dev/null`
> ` if [ $? -gt 0 ]`
> Should be `-eq` there.
> 
> Please don't commit until we test this. All changes will be ASAP. Thanks.

It makes sense, right? I mean, if it is not up, we set it to up.

**Comment by alexanderbazhenoff** [comment]
> It makes sense, right? I mean, if it is not up, we set it to up.

Yes, it makes sense. To be honest I don't see the reason to use the whole this construction taking milliseconds on creating VMs:

`# is vlanBr up?`
`ip link show dev $vlanBr > /dev/null 2>/dev/null`
`if [ $? -eq 0 ]`
`then`
`ip link set $vlanBr up`
`fi`
`return 0`

Just to save original code style. But:

`ip link set $vlanBr up > /dev/null 2>/dev/null`

without any condition is faster.

Also:

`ip link set $vlanDev up > /dev/null 2>/dev/null`

instead of:

`# is up?`
`ip link show dev $vlanDev > /dev/null 2>/dev/null`
`if [ $? -eq 0 ]`
`then`
`ip link set $vlanDev up > /dev/null`
`fi`

This will not fail on nonnexistent interfaces.

**Comment by alexanderbazhenoff** [comment]
@blueorangutan test

**Comment by alexanderbazhenoff** [comment]
> @alexanderbazhenoff can you rebase and edit base branch to 4.11 if possible?

https://github.com/apache/cloudstack/pull/2923

**Comment by rhtyd** [comment]
You may close this one, the 4.11 PR will ne fwd merged on master.

**Comment by alexanderbazhenoff** [comment]
> You may close this one, the 4.11 PR will ne fwd merged on master.

Which to close? This or 4.11 branch?

**Comment by rafaelweingartner** [comment]
This one.

**Pull request closed without merging**
