### PR TITLE
ui: show vpn users tab in networks section

### LINKED ISSUE #7248: Create a vpn users tab
##### ISSUE TYPE

 * Enhancement Request

##### COMPONENT NAME

~~~
Componet:UI
Componet:api
~~~

##### CLOUDSTACK VERSION

~~~
4.18 nightly
4.17.2

~~~

##### SUMMARY

Create a vpn users tab 

It will be nice if the vpn users details can be found under Network 

Network > vpn users 

Currently to manage or create vpn users and end users has to perform the following steps 

Network > Guest Networks > Public Ip Address > Source Nat IP > VPN > Manage VPN users

or 

Vpc network> Public Ip Address > VPN> Manage VPN users

https://cloudstack.apache.org/api/apidocs-4.17/apis/listVpnUsers.html

VPN users

VPN users2
ercontent.com/1401014/219573796-3b988b90-c11d-4801-b9d1-06547200d250.png)

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #7248

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by kiranchavala** [comment]
@shwstppr LGTM

vpn-user

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by DaanHoogland** [comment]
@blueorangutan ui

**Comment by DaanHoogland** [comment]
I think something is wrong with the qa env, I can't log on to verify (deal with that some other time)

**Review by kiranchavala — APPROVED** [review]
LGTM , tested the changes and its displaying the vpn users correctly

**Pull request merged**
