### PR TITLE
systemvm,vpc,vmware: fix management route

### LINKED ISSUE #6873: VPC VR can't be started on VMware due to missing routes
##### ISSUE TYPE

 * Bug Report
##### COMPONENT NAME

~~~
VR agent ?
~~~

##### CLOUDSTACK VERSION

~~~
4.17.0.0+, VMware 
~~~

##### CONFIGURATION

mgmt server is in Pod1/subnet1, 
hypervisor (and thus VR's control NIC) is in Pod2/subnet2 - thus there is a routing process between mgmt and VR's NIC IP

##### OS / ENVIRONMENT

Probably affects only VMware, but has not been tested with XS/KVM (should not be a problem, but needs checking)

##### SUMMARY

Only VPC VR affected (VR for shared or simpler Isolated network is NOT affected).
There is a patching error of the VPC VR (this might be a problem or a consequence of missing routes) - either way, route from VR to the subnet of the mgmt server (subnet1) is missing/not configured, and thus VR can't talk to the mgmt server - VR configuration never completes.  CMDLINE looks fine (all parameters look fine) but things are not applied correctly on the OS level.

##### STEPS TO REPRODUCE
~~~
For bugs, show exactly how to reproduce the problem, using a minimal test-case. Use Screenshots if accurate.

For new features, show how the feature would be used.
~~~

~~~
mgmt server in subnet1, hypervisor (and thus VR's control NIC) in subnet2 - so that VR needs to send packet to the Pod2's gateway in order to reach Pod1/mgmt server.
~~~

##### EXPECTED RESULTS

~~~
VR patched up and operational
~~~

##### ACTUAL RESULTS

~~~
VR not patched, routes not present as needed.
~~~

CMD line of the VPC VR:
image

cloud.log
image

Routing table empty (there should be multiple routes (route to the mgmt cidr should be via 10.1.32.1 for 10.1.32.0 network - see CMDLINE output)

image

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #6873
When the management server is in a different subnet than the pod in which a VPC VR is deployed, an ip route must be added just after creation of `eth0` to allow the connectivity between the VR and the management server.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [x] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan systemvmbuild

**Comment by rohityadavcloud** [comment]
@blueorangutan systemvmbuild

**Comment by rohityadavcloud** [comment]
@blueorangutan systemvmbuild

**Review by rohityadavcloud — APPROVED** [review]

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan test matrix

**Comment by rohityadavcloud** [comment]
(checked confirmed 4.17.2 template bundled with pkgs of this PR)

**Comment by rohityadavcloud** [comment]
@weizhouapache can you review/discuss with @shwstppr and merge your code in this PR if needed?

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by rohityadavcloud** [comment]
I've merged @weizhouapache 's PR and on this PR I've merged latest 4.17. Next, I'll rebuild the 4.17.2 systemvmtemplate and run the pkging + smoketests again.

**Comment by rohityadavcloud** [comment]
New systemvmtemplate built http://download.cloudstack.org/systemvm/4.17/
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan test matrix

**Comment by rohityadavcloud** [comment]
@blueorangutan test matrix

**Comment by rohityadavcloud** [comment]
@blueorangutan test matrix

**Comment by rohityadavcloud** [comment]
@blueorangutan test matrix

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Review by vladimirpetrov — APPROVED** [review]
LGTM based on manual testing.

**Pull request merged**
