### PR TITLE
CLOUDSTACK-9125: Brazilian translations

### PR DESCRIPTION
**Pull request by agneya2001**
The pull request contains brazilian translations for quota labels.

### CODE REVIEW

**Comment by milamberspace** [comment]
Hello,

The best way to translate the Web UI of CloudStack is to use the Transifex project [1] and use the script inside the cloudstack project to download and prepare the resources files (unicode/native conversion and alphabetical order) [2]

Milamber

    [1] 4.7 and Brazil: https://www.transifex.com/ke4qqq/CloudStack_UI/translate/#pt_BR/47xmessagesproperties/66301943 (left 43 strings to translate)
    [2] https://cwiki.apache.org/confluence/display/CLOUDSTACK/Update+L10N+files+from+Transifex+to+git+repo

**Comment by agneya2001** [comment]
@milamberspace will give it a try.

**Comment by GabrielBrascher** [comment]
I think it would be better to change “Quota” by “cota”. Both are correct, but Brazilians are used with “cota”.

It seems that the Jenkins had a problem. You should try forcing push it and see if the Jenkins build finishes it properly.

**Comment by agneya2001** [comment]
@GabrielBrascher Noted, I think I need to submit translation via Transfix. I am working on it.

**Comment by agneya2001** [comment]
Closing it as translations are submitted via transfix website.

**Pull request closed without merging**
