### PR TITLE
 CLOUDSTACK-9675:  Cloudstack Metrics Miscellaneous bug fixes

### PR DESCRIPTION
**Pull request by rashmidixit**
More for information refer to [CLOUDSTACK-9675](https://issues.apache.org/jira/browse/CLOUDSTACK-9675)

### CODE REVIEW

**Comment by rhtyd** [comment]
@rashmidixit please change PR's base branch to 4.9.
I'm the author/maintainer of this feature. I would like to know more about your changes, and what issues you're fixing.

**Comment by rashmidixit** [comment]
@rhtyd - There have been four things fixed here. I have explained each commit below. Your review/comments is most appreciated.

1. Goto Zone metrics or Hosts metrics. NUmerical values are not listed under Mem Usage and Mem Allocation columns. Instead 'NaN' is displayed 
- Mainly happening due to missing checks for undefined.

2. Create a Windows instance on a Xen cluster. No IOPS data is generated or shown in the Disk Usage Tab for that Instance: In some cases the diskiops from API comes back as 0. In this case, calculated it based on disk read and write values.

3. Changing storage.overprovisioning factor should cause changed values in storage metrics. This doesnt happen currently:  The disk overprovisioning factor was not considered when calculating metrics 'disk total' and 'disk allocated'. Added this in.

4. Allocated memory is not correctly calculated on Hosts Metrics page for a xen server with multiple instances: The value being returned from API was % value. The Host metric page shows this in GB. Converted it correctly.

**Comment by rashmidixit** [comment]
Added one more fix to this: 
1. List of Virtual Machines will be incorrect if the number is greater than the pagesize. Added -1 to the call of the API.

**Comment by rashmidixit** [comment]
@rhtyd Have you been able to take a look at the commits? Will appreciate your comments.

**Comment by rhtyd** [comment]
Thanks @rashmidixit I'll review them soon.

**Comment by rhtyd** [comment]
@rashmidixit can you squash your changes, thanks.

**Comment by rashmidixit** [comment]
@rhtyd Please take a look now. I have squashed the changes.

**Comment by rhtyd** [comment]
@rashmidixit I've taken your feedback and improved the feature here https://github.com/apache/cloudstack/pull/1944 -- this reimplements the frontend logic at the backend, improving the overall performance 4-40x and handling missing error cases.

**Comment by rashmidixit** [comment]
@rhtyd I will take a look. However, this pull request is to do with additional bug fixes. Can you please review.

**Comment by rhtyd** [comment]
Thanks @rashmidixit  both the PRs may be closed given the new performance improvement PR #1944 which also includes some case fixes from this PR.

**Comment by rashmidixit** [comment]
Closing this since #1944 has been merged.

**Pull request closed without merging**
