### PR TITLE
Add global configuration for max cpu/ram in service offerings

### PR DESCRIPTION
**Pull request by ustcweizhou**
…

## Description

vm.serviceoffering.cpu.cores.max and vm.serviceoffering.ram.size.max

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
code looks good, will need some testing

**Comment by Pearl1594** [comment]
@blueorangutan package

**Review by Pearl1594 — APPROVED** [review]
LGTM
Verified the fix:
1. Set "vm.serviceoffering.cpu.cores.max" to 2 and attempted to create a compute offering with CPU cores set to 4 - Failed (as expected)
image

2. Set "vm.serviceoffering.ram.size.max" to 200 and attempted to create a service offering with memory of 500 MB - Failed (as expected)
image

3. Created a service offering within the defined limits of vm.serviceoffering.cpu.cores.max = 2 and vm.serviceoffering.ram.size.max = 200 - Passed (as expected)

**Comment by Pearl1594** [comment]
@blueorangutan test

**Comment by Pearl1594** [comment]
@ustcweizhou  Custom Constrained and Custom Unconstrained service offerings do not adhere to the set global settings, and get created successfully despite having the the min and/or max cpu cores and memory values set above configured threshold - which is what is expected (I reckon).

However, with Custom Constrained Compute offering type - when the min cpu cores / min memory is set above its max values - it still successfully creates the offering - shouldn't this ideally fail? 
image

**Comment by weizhouapache** [comment]
> @ustcweizhou Custom Constrained and Custom Unconstrained service offerings do not adhere to the set global settings, and get created successfully despite having the the min and/or max cpu cores and memory values set above configured threshold - which is what is expected (I reckon).
> 
> However, with Custom Constrained Compute offering type - when the min cpu cores / min memory is set above its max values - it still successfully creates the offering - shouldn't this ideally fail?
> image

@Pearl1594 yes, you are right.
However, when you create vm with dynamic offerings, or update vm to new offerings, cpu/ram should be checked as well.

**Comment by Pearl1594** [comment]
Thanks @ustcweizhou , the check does happen when the offering is consumed during VM deployment.

**Pull request merged**
