### PR TITLE
Revert "Extract systemvm.iso using bsdtar (#3536)"

### PR DESCRIPTION
**Pull request by anuragaw**
This reverts commit 8a55c931e806a64f7f00153d4a58c4463caa7a47.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by anuragaw** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Why revert it @anuragaw - instead can we fix it to make it work?

**Comment by anuragaw** [comment]
@rhtyd - This is for testing purposes for @borisstoyanov only we will close it after testing without merge once he is done.

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@rhtyd @andrijapanicsb @anuragaw @borisstoyanov 
fyi, I faced the following issue when restarted mgt server 
```
2020-01-06 14:13:46,536 DEBUG [c.c.s.ConfigurationServerImpl] (main:null) (logid:) Executing: /bin/bash /usr/share/cloudstack-common/scripts/vm/systemvm/injectkeys.sh /var/lib/cloudstack/management/.ssh/id_rsa.pub /var/lib/cloudstack/management/.ssh/id_rsa /usr/share/cloudstack-common/vms/systemvm.iso
2020-01-06 14:13:46,543 DEBUG [c.c.s.ConfigurationServerImpl] (main:null) (logid:) Executing while with timeout : 3600000
2020-01-06 14:13:46,706 DEBUG [c.c.s.ConfigurationServerImpl] (main:null) (logid:) Exit value is 1
2020-01-06 14:13:46,707 DEBUG [c.c.s.ConfigurationServerImpl] (main:null) (logid:) .: Can't restore timeagent.zip: Can't create 'agent.zip'cloud-scripts.tgz: Can't create 'cloud-scripts.tgz'bsdtar: Error exit delayed from previous errors.
2020-01-06 14:13:46,708 INFO  [c.c.s.ConfigurationServerImpl] (main:null) (logid:) Injected public and private keys into systemvm iso with result : .: Can't restore timeagent.zip: Can't create 'agent.zip'cloud-scripts.tgz: Can't create 'cloud-scripts.tgz'bsdtar: Error exit delayed from previous errors.
2020-01-06 14:13:46,709 WARN  [c.c.s.ConfigurationServerImpl] (main:null) (logid:) Failed to inject generated public key into systemvm iso .: Can't restore timeagent.zip: Can't create 'agent.zip'cloud-scripts.tgz: Can't create 'cloud-scripts.tgz'bsdtar: Error exit delayed from previous errors.

```
I do not knw what caused it. The issue is not happening now but I have no idea how it was fixed.

**Comment by anuragaw** [comment]
@weizhouapache - are you observing this issue on master on this branch with reverted commit?

**Comment by weizhouapache** [comment]
> @weizhouapache - are you observing this issue on master on this branch with reverted commit?

@anuragaw this issue never happened before 2019 Dec. it only happened with latest master

**Comment by borisstoyanov** [comment]
I don't see this and other errors with master and with this PR, the only case that I can think of this appearing is when cloudstack-common is upgraded and management restarted. let me try to find a way to test it and will get back.

**Comment by borisstoyanov** [comment]
Confirmed, on upgrade the following error appears: 
```
z: Can't create 'cloud-scripts.tgz'bsdtar: Error exit delayed from previous errors.
2020-01-13 09:53:21,769 WARN  [o.e.j.w.WebAppContext] (main:null) (logid:) Failed startup of context o.e.j.w.WebAppContext@27c6e487{/client,file:///usr/share/cloudstack-management/webapp/,UNAVAILABLE}{/usr/share/cloudstack-management/webapp}
org.springframework.context.ApplicationContextException: Failed to start bean 'cloudStackLifeCycle'; nested exception is com.cloud.utils.exception.CloudRuntimeException: Failed to inject generated public key into systemvm iso .: Can't restore timeagent.zip: Can't create 'agent.zip'cloud-scripts.tgz: Can't create 'cloud-scripts.tgz'bsdtar: Error exit delayed from previous errors.
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:186)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:52)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:358)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:159)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:884)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552)
	at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.loadContext(DefaultModuleDefinitionSet.java:145)
	at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet$2.with(DefaultModuleDefinitionSet.java:122)
	at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:245)
	at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:250)
	at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:250)
	at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:233)
	at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.loadContexts(DefaultModuleDefinitionSet.java:117)
	at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.load(DefaultModuleDefinitionSet.java:79)
	at org.apache.cloudstack.spring.module.factory.ModuleBasedContextFactory.loadModules(ModuleBasedContextFactory.java:37)
	at org.apache.cloudstack.spring.module.factory.CloudStackSpringContext.init(CloudStackSpringContext.java:71)
	at org.apache.cloudstack.spring.module.factory.CloudStackSpringContext.<init>(CloudStackSpringContext.java:58)
	at org.apache.cloudstack.spring.module.factory.CloudStackSpringContext.<init>(CloudStackSpringContext.java:62)
	at org.apache.cloudstack.spring.module.web.CloudStackContextLoaderListener.contextInitialized(CloudStackContextLoaderListener.java:52)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:890)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:532)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:853)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:344)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1515)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1477)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:133)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:107)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.doStart(GzipHandler.java:273)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:133)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:115)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:133)
	at org.eclipse.jetty.server.Server.start(Server.java:418)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:107)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:385)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.apache.cloudstack.ServerDaemon.start(ServerDaemon.java:189)
	at org.apache.cloudstack.ServerDaemon.main(ServerDaemon.java:105)
Caused by: com.cloud.utils.exception.CloudRuntimeException: Failed to inject generated public key into systemvm iso .: Can't restore timeagent.zip: Can't create 'agent.zip'cloud-scripts.tgz: Can't create 'cloud-scripts.tgz'bsdtar: Error exit delayed from previous errors.
	at com.cloud.server.ConfigurationServerImpl.updateKeyPairs(ConfigurationServerImpl.java:675)
	at com.cloud.server.ConfigurationServerImpl.persistDefaultValues(ConfigurationServerImpl.java:303)
	at com.cloud.server.ConfigurationServerImpl.configure(ConfigurationServerImpl.java:162)
	... 51 more
```
Perhaps we'll need to fix this in a separate PR? @anuragaw @andrijapanicsb

**Comment by andrijapanicsb** [comment]
@cl-k-takahashi we will have to revert the original PR #3536 , since it causes failures in the during upgrades.

Please test by having i.e. 4.13 installation, and then upgrading to the version built from your PR.

The problem seems to be in the existance (from the previous version) of "systemvm_mnt" folder, owned by root:root, so the script can't write it's files:

> ls -lah /var/cloudstack/management/
> drwxrwx---. 4 cloud cloud 36 Jan 10 09:12 .
> drwxr-xr-x. 4 root  root  33 Jan 13 09:32 ..
> drwx------. 2 cloud cloud 36 Jan 13 09:34 .ssh
> drwxr-xr-x. 2 root  root   6 Jan 13 09:34 systemvm_mnt
> 

See below more details on the failure please:

[root@trl-163-k-M7-bstoyanov-mgmt1 ~]# runuser -l  cloud -c "/bin/bash /usr/share/cloudstack-common/scripts/vm/systemvm/injectkeys.sh /var/cloudstack/management/.ssh/id_rsa.pub /var/cloudstack/management/.ssh/id_rsa /usr/share/cloudstack-common/vms/systemvm.iso"
+ TMP=/tmp
+ MOUNTPATH=/var/cloudstack/management/systemvm_mnt
+ TMPDIR=/tmp/cloud/systemvm
+ umask 022
+ [[ 995 -ne 0 ]]
+ SUDO='sudo -n '
+ mkdir -p /var/cloudstack/management/systemvm_mnt
+ '[' 3 -ne 3 ']'
+ newpubkey=/var/cloudstack/management/.ssh/id_rsa.pub
+ newprivkey=/var/cloudstack/management/.ssh/id_rsa
+ systemvmpath=/usr/share/cloudstack-common/vms/systemvm.iso
+ '[' '!' -f /var/cloudstack/management/.ssh/id_rsa.pub ']'
+ '[' '!' -f /var/cloudstack/management/.ssh/id_rsa ']'
+ command -v mkisofs
++ command -v bsdtar
+ '[' '!' -x /bin/bsdtar ']'
+ inject_into_iso systemvm.iso /var/cloudstack/management/.ssh/id_rsa.pub
+ local isofile=/usr/share/cloudstack-common/vms/systemvm.iso
+ local newpubkey=/var/cloudstack/management/.ssh/id_rsa.pub
+ local tmpiso=/tmp/systemvm.iso
+ mkdir -p /var/cloudstack/management/systemvm_mnt
+ '[' '!' -f /usr/share/cloudstack-common/vms/systemvm.iso ']'
+ bsdtar -C /var/cloudstack/management/systemvm_mnt -xf /usr/share/cloudstack-common/vms/systemvm.iso
.: Can't restore time
**agent.zip: Can't create 'agent.zip'**
**cloud-scripts.tgz: Can't create 'cloud-scripts.tgz'**
**bsdtar: Error exit delayed from previous errors.**
+ '[' 1 -ne 0 ']'
++ basename /usr/share/cloudstack-common/scripts/vm/systemvm/injectkeys.sh
+ echo 'injectkeys.sh: Failed to extract original iso /usr/share/cloudstack-common/vms/systemvm.iso'
injectkeys.sh: Failed to extract original iso /usr/share/cloudstack-common/vms/systemvm.iso
+ clean_up
+ rm -rf --preserve-root /var/cloudstack/management/systemvm_mnt
+ return 1
+ '[' 1 -ne 0 ']'
+ exit 5

**Comment by andrijapanicsb** [comment]
@cl-k-takahashi kindly fix this and submit a new PR, we can make it for 4.14 again. Thank you!

**Comment by cl-k-takahashi** [comment]
@anuragaw @andrijapanicsb Thank you for finding out this problem and reverting the commit.
I will fix the problem.

**Comment by andrijapanicsb** [comment]
The further testing show, that this error will happen only one, and on next run of the script it would be fine (since the same folder /var/cloudstack/management/systemvm_mnt is removed at the end of the script)

**Pull request merged**
