### PR TITLE
CLOUDSTACK-10166: Get accountId and domainId from VPC when tagging a NetworkACL as a user

### PR DESCRIPTION
**Pull request by khos2ow**
This fixes the issue that a non-root user cannot tag a network ACL item
and after the fix a non-root user still cannot tag a globally defined
ACL item and only the ACLs they have access to.

### CODE REVIEW

**Comment by rafaelweingartner** [comment]
@khos2ow The only suggestion I would have is the addition of ticket identifier "CLOUDSTACK-10166" in the commit "title".

**Comment by khos2ow** [comment]
@rafaelweingartner sure will do it tomorrow. Thanks.

**Comment by khos2ow** [comment]
@rafaelweingartner would you mind review again?

**Comment by khos2ow** [comment]
@DaanHoogland @PaulAngus  @rhtyd  would you please review/merge this PR?

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@khos2ow I see a new regression in failed test `test_01_single_VPC_iptables_policies`, rest are known failures fixed in #2211. Please check and fix the PR if necessary.

**Comment by khos2ow** [comment]
@rhtyd I checked and I believe the failure is not related to the change, can you please run the CI job again?

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
LGTM based on code and tests. I'll merge since we've two code lgtms and test lgtm on this, thanks.

**Pull request merged**
