### PR TITLE
Proposal for an improved CglibThrowableRenderer

### PR DESCRIPTION
**Pull request by rafaelweingartner**
Following our discussions on mailing list, here is a PR with a proposal for an improvement on “CglibThrowableRenderer”. We would still have to define a number to limit the stack traces of causes (I randomly chose 3, just to get the code running). The test case is also not good in my opinion, but I ran out of ideas (waiting for suggestions on that).

### CODE REVIEW

**Comment by DaanHoogland** [comment]
LGTM, reviewing this I finally understand why we have a custom renderer at all. The travis failing checks are unrelated timeouts.

**Comment by rafaelweingartner** [comment]
Does anyone else have some ideas on how to test that code?
I am not comfortable with the test I coded, the test feels shallow.

**Comment by rafaelweingartner** [comment]
The tests that have failed do not seem to be related to the code that was changed.

**Comment by karuturi** [comment]
@rafaelweingartner I see windows line endings in the new test file. Can you fix that please?
Other than that, LGTM. once thats fixed I will merge

**Comment by karuturi** [comment]
since this fixes slow build, I am going to merge this PR and push another commit for line endings fix.

**Comment by rafaelweingartner** [comment]
@Karuturi, Sorry for the windows line endings (did you see that on log files? I was not able to see anything there). Sometimes I jump between OS and forget that I am coding from a Windows machine, instead of my usual Ubuntu.

BTW: I think we are in very different time zones, I just woke up. Thanks for the windows line fix.

**Comment by karuturi** [comment]
cat -v filename will show you line endings.
I figured the timezone issue. didnt want to wait for another day with broken build. hence pushed it. 
The recent build passed. Thanks :)

**Comment by rafaelweingartner** [comment]
With your comments, I fixed my Eclipse configuration on my Windows
environment, now I am using UNIX lines for ACS on windows.

On Tue, Sep 1, 2015 at 9:33 AM, Rajani Karuturi <notifications@github.com>
wrote:

> cat -v filename will show you line endings.
> I figured the timezone issue. didnt want to wait for another day with
> broken build. hence pushed it.
> The recent build passed. Thanks :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/cloudstack/pull/762#issuecomment-136698602>.
>



-- 
Rafael Weingärtner

**Pull request merged**
