### PR TITLE
CLOUDSTACK-8308: Adding automation testcases for Delta Snapshot.

### PR DESCRIPTION
**Pull request by borisroman**
CLOUDSTACK-8308: Updating automation testcases for Delta Snapshot testpath.

Reference to #384

This closes #384

### CODE REVIEW

**Comment by borisroman** [comment]
This closes #384. Squashed to commits into 1 as requested per comment.

**Comment by borisroman** [comment]
@remibergsma @bhaisaab Any more comments?

**Comment by remibergsma** [comment]
@borisroman Can you add the test output please?

**Comment by bhaisaab** [comment]
LGTM (not tested on a real infra), can you share output ?

**Comment by borisroman** [comment]
@karuturi Could you run this on your Xen-setup?

**Comment by borisroman** [comment]
Been open for 3 months, closing.

**Comment by DaanHoogland** [comment]
can't reopen will copy and steal the code for a new PR, to see if it will be accepted ;)

**Pull request closed without merging**
