### PR TITLE
Fix root disk resize (not allowed) when service offering has root disk size, only allowed through service offering change

### LINKED ISSUE #9380: Can not change size root disk instances
##### ISSUE TYPE

 * Bug Report
##### COMPONENT NAME

~~~
Volume, Instances
~~~

##### CLOUDSTACK VERSION

~~~
 4.19.0.1 
~~~

##### OS / ENVIRONMENT

Ubuntu 22.04 for KVM, VMware 8.0

##### SUMMARY

Cannot resize root disk vm when compute offering with Disk offering strictness as false

##### STEPS TO REPRODUCE

~~~
Create Compute Offering
set root disk size 
set Disk offering strictness => false
~~~

##### EXPECTED RESULTS

~~~
When resize root disk see error bellow:
Failed to resize Root volume. The service offering of this Volume has been configured with a root disk size; on such case a Root Volume can only be resized when changing to another Service Offering with a Root disk size. For more details please check out the Official Resizing Volumes documentation.
~~~

##### ACTUAL RESULTS

~~~
Root Disk is resize to new size
~~~

### PR DESCRIPTION
**Pull request by sureshanaparti**
### Description

This PR fixes root disk resize - not allowed when service offering has root disk size, only allowed through service offering change.

Fixes #9380

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### How Has This Been Tested?

Manually tested the root resize with service offering having root disk size set.

RootDisk-Resize-Fix

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Review by harikrishna-patnala — APPROVED** [review]
code LGTM. infact assumption of finding service offering with disk offering id is not valid now as we have decoupled service and disk offerings.

**Review by shwstppr — APPROVED** [review]
code lgtm

**Review by rohityadavcloud — APPROVED** [review]

**Review by vishesh92 — APPROVED** [review]
lgtm

**Comment by rohityadavcloud** [comment]
@vishesh92 can you confirm if you'd finished manual QA on this? thanks.

**Comment by vishesh92** [comment]
> @vishesh92 can you confirm if you'd finished manual QA on this? thanks.

I had an offline discussion with @sureshanaparti and there was some confusion about the expected behaviour.

As of now, if disk size is set in the offering and disk offering's size strictness is disabled, I am not able to resize the disk.

**Comment by vishesh92** [comment]
Had another discussion with @sureshanaparti . This is working as expected. Merging.

**Pull request merged**
