### PR TITLE
api,ui: vm template format, fix vm info link

### LINKED ISSUE #9084: Can't enable "Dynamically scalable" function for VM from ISO
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.19.0.0
~~~

##### SUMMARY

For new features, show how the feature would be used.
-->
When instance created from ISO I can't enable "Dynamically scalable" function, because instance "attached" to a non-existent template with ISO's id

image

Click on Template Oracle Linux 8.4

image
image

2024-05-15 17:16:56,771 ERROR [c.c.a.q.QueryManagerImpl] (qtp379645464-4368326:ctx-87c17956 ctx-34df3704) (logid:1a90ee60) Incorrect format of the template id 204
2024-05-15 17:16:56,771 INFO  [c.c.a.ApiServer] (qtp379645464-4368326:ctx-87c17956 ctx-34df3704) (logid:1a90ee60) Incorrect format ISO of the specified template id

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #9084

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):

https://github.com/apache/cloudstack/assets/153340/190e05a8-b6dc-45cc-9ba1-6f16bd9af8a7

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by weizhouapache — COMMENTED** [review]
code lgtm

nice screenshot @shwstppr

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Review by DaanHoogland — APPROVED** [review]
clgtm and tested the link in a lab env

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Pull request merged**
