### PR TITLE
Add scripts to merge PRs and release fixes forward

### PR DESCRIPTION
**Pull request by miguelaferreira**
As it is now, additions to CloudStack need to go through a GitHub PR and, if accepted, merged to the Apache remote (not in GitHub). This means that merging a PR for CloudStack is a bit more involved than merging a normal GitHub PR. In addition to that, a PR that fixes something in an older release needs to be merged against a release branch, and then forward merged up to master (if applicable).

To help with these two kinds of merges, @remibergsma, @karuturi, @DaanHoogland and myself, have created two scripts (contributed in this PR).

One script (**git-pr**) helps in merging a PR from GitHub to the Apache remote. The script will read the PR info using GitHub's API and will create a merge commit that contains the same commit message a normal GitHub PR merge commit, plus, as extra info, a list of commits that are being merged.

The other script (**git-fwd-merge**) will create a specific merge commit message that indicates a forward merge, and lists the commits being merged.

This Apache wiki [page](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61311655) describes how to use these two scripts, and points to an even more detailed [page](https://github.com/schubergphilis/cloudstack-git-tree-manipulation/wiki) that explains the merge scenarios step-by-step.

By the way, beacause both scripts follow the naming convention for git tools, as long as they are in your "path" you can execute them as simply as "git pr" and "git fwd-merge". But be aware that, in order to use these scripts, you should make sure to remove any aliases that can cause a name clash.

### CODE REVIEW

**Comment by DaanHoogland** [comment]
LGTM

**Comment by borisroman** [comment]
LGTM We've tested the git-pr script with #705 #709 #708.

**Comment by karuturi** [comment]
Thanks for the scripts @miguelaferreira and @remibergsma. It makes merging( and closing) PRs very easy. I also used this script to merge doc prs at [apache/cloudstack-docs-rn](https://github.com/apache/cloudstack-docs-rn) etc. :).  Once 4.6 is out, fwd-merge will also be very useful. 
:+1:

**Comment by remibergsma** [comment]
LGTM, I used it to merge this PR ;-)

**Comment by wido** [comment]
LGTM here as well. Used this script a couple of times

**Pull request merged**
