### PR TITLE
Handle port forward rule check for vpc and non vpc Isolated networks

### PR DESCRIPTION
**Pull request by Pearl1594**
## Description
Port forwarding rules not checked properly on Isolated networks (non-VPC)

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?
Created Isolated network and added port forward rules for the Instance created in that network
Create an Instance in a tier of a VPC network and  ran the health check from UI and cmk with performfreshchecks as true
All tests passed for both the routers

### CODE REVIEW

**Comment by andrijapanicsb** [comment]
@blueorangutan package

**Comment by andrijapanicsb** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
tested. it works fine.

**Comment by andrijapanicsb** [comment]
thx @weizhouapache, that's one thing less for me to test :))

Thx

**Pull request merged**
