### PR TITLE
pre-commit: add hook `check-merge-conflict`

### PR DESCRIPTION
**Pull request by jbampton**
Check for files that contain merge conflict strings.

https://github.com/pre-commit/pre-commit-hooks#check-merge-conflict

Another check or test we can have that can run automatically locally with `git commit`.

### Description

This PR adds another pre-commit hook expanding our framework and coverage.

The new hook `check-merge-conflict` is from the official pre-commit repos.

We do already have a GitHub Action that checks for merge conflicts but this new hook is better
since it runs both locally and on CI with pre-commit. 

If the check or test can run locally then there is faster feedback to the developer before opening a pr.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [X] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [X] Trivial

### How Has This Been Tested?

Just run the new hook:

`pre-commit run check-merge-conflict --all-files`

Run all hooks:

`pre-commit run --all-files`

### CODE REVIEW

**Comment by jbampton** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]

**Review by stephankruggg — APPROVED** [review]

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by vishesh92 — APPROVED** [review]
lgtm

**Pull request merged**
