### PR TITLE
CLOUDSTACK-10188 - Resource Accounting for primary storage is Broken when Domains are in use

### PR DESCRIPTION
**Pull request by bwsw**
https://issues.apache.org/jira/browse/CLOUDSTACK-10188

During storage expunge domain resource statistics for primary storage space resource counter is not updated for domain. This leads to the situation when domain resource statistics for primary storage is overfilled (statistics only increase but not decrease).

Global scheduled task resourcecount.check.interval > 0 provides a workaround but not fixes the problem truly because when accounts inside domains use primary_storage allocation/deallocation intensively it leads to service block of operation.

**NB: Unable to implement marvin tests because it (marvin) places in database weird primary storage volume size of 100 when creating VM from template. It might be a sign of opening a new issue for that bug.**

### CODE REVIEW

**Comment by rhtyd** [comment]
@bwsw can you fix the conflicts, thanks.

**Comment by rhtyd** [comment]
ping @bwsw

**Comment by bwsw** [comment]
@rhtyd I'll do it in a couple of days.

**Comment by bwsw** [comment]
@rhtyd Do we have a chance including it to 4.11 yet? I overviewed Travis logs and only one test fails which seems to be a timeout reason, not a real failure. We already resolved conflicts twice against moving master. I don't even imaging how much we will be asked to do so if waiting 4.12))
And I suppose it's a bug which is vital for users who use domains, because It blocks creating new VMs.

**Comment by rhtyd** [comment]
@bwsw sure, please fix the conflicts.
Ideally today we are supposed to freeze the branch to only accept critical/blocker fixes until the rc1 is put to vote. I'll start a discussion on dev@ to gather consensus. Meanwhile, if you've time/bandwidth do work on it.

**Comment by bwsw** [comment]
@rhtyd fixed. Conflict is not related to PR code, just code reformatting prevented automatic merge.

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by bwsw** [comment]
@rhtyd @borisstoyanov 
Same test [test_volumes.py/test_07_resize_fail] failed in previously merged https://github.com/apache/cloudstack/pull/2088 which includes massive volume changes. I don't see anything related to my code yet, but suppose that PR [2088] could bring a regression. Before that merge I haven't seen that test to fail.

**Comment by bwsw** [comment]
Here https://github.com/apache/cloudstack/pull/2379#issuecomment-356183984 it also fails. I suppose the regression is introduced in https://github.com/apache/cloudstack/pull/2088

**Comment by rhtyd** [comment]
Thanks @bwsw I'll investigate. meanwhile, rekick tests.
@blueorangutan package

**Comment by rhtyd** [comment]
Additional review requested - @DaanHoogland @borisstoyanov @wido @marcaurele @rafaelweingartner and others

**Comment by bwsw** [comment]
@rhtyd 
Hm, then what does it mean (copied from there):
```
test_07_resize_fail | Failure | 15.42 | test_volumes.py
```

**Comment by rhtyd** [comment]
@bwsw it means one of the test cases from `test_volumes.py` - `test_07_resize_fail`, you can analyze why it failed from the marvin test logs - Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr2362-t2073-kvm-centos7.zip. It maybe most likely env related. I'll kick test again.
@blueorangutan test

**Comment by bwsw** [comment]
@borisstoyanov, got it, not sure can find a time for additional research.

**Comment by rhtyd** [comment]
Re-kicked Travis by closing/opening the PR.

**Comment by rhtyd** [comment]
Test LGTM, merging this based on code reviews and test results.

**Pull request merged**
