### PR TITLE
Fix spelling

### PR DESCRIPTION
**Pull request by jbampton**
### Description

This PR fixes some spelling.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [X] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [X] Trivial

### CODE REVIEW

**Review by stephankruggg — APPROVED** [review]

**Comment by davidjumani** [comment]
@blueoranguran package

**Comment by davidjumani** [comment]
@blueoranguran package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
this needs a regression test and some monkey testing on createVPC in the UI, in spite of just being spelling corrections.
@blueorangutan test keepEnv

**Comment by DaanHoogland** [comment]
note: components/test_affinity_groups_project.py failed in gha. might need attention.

**Review by DaanHoogland — APPROVED** [review]
regression tests and manual test of createVPC passed, lgtm.

**Pull request merged**
