### PR TITLE
fix AssignToLoadBalancerRule input param

### PR DESCRIPTION
**Pull request by nimabm**
changed vmidipmap[0].ip to vmidipmap[0].vmip

### Description

the AssignToLoadBalancerRule has vmidipmap[0].vmip as input but in the description mentioned vmidipmap[0].ip incrrectly.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### CODE REVIEW

**Review by vishesh92 — APPROVED** [review]
clgtm

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@nimabm Can you rebase your PR against 4.19 or 4.18 and change the base branch in the PR?

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Comment by sureshanaparti** [comment]
Hi @nimabm Only API parameter description change here, seems good to go in 4.19.1. Can you rebase with 4.19 branch and change the target branch to 4.19?

**Comment by nimabm** [comment]
@vishesh92 @sureshanaparti has been changed to 4.19

**Pull request closed without merging**
