### PR TITLE
Tungsten: change conserve_mode of default network offering to 0

### LINKED ISSUE #7241: Tungsten: failed to create port forwarding and load balancing rules on Source NAT IP
got the following error

```
2023-02-16 14:14:40,100 DEBUG [c.c.a.t.Request] (API-Job-Executor-58:ctx-e5b9031a job-252 ctx-9147ab40) (logid:9e649959) Seq 7-6552455982847361137: Executing:  { Cmd , MgmtId: 32986774896912, via: 7(TungstenDevice - TF), Ver: v1, Flags: 100011, [{"org.apache.cloudstack.network.tungsten.agent.api.CreateTungstenNetworkLoadbalancerCommand":{"projectFqn":"default-domain:admin","networkUuid":"e2a6b224-bb58-4017-b83b-50091c21c887","publicNetworkUuid":"27e9008b-e6c9-4130-bc47-4c0ae06223a2","loadBalancerMethod":"ROUND_ROBIN","loadBalancerName":"loadbalancer121","loadBalancerListenerName":"loadbalancer-listener18","loadBalancerPoolName":"loadbalancer-pool18","loadBalancerHealthMonitorName":"loadbalancer-healthmonitor121","loadBalancerVmiName":"loadbalancer-vmi121","loadBalancerIiName":"loadbalancer-ii121","ruleId":"18","listMember":[{"name":"loadbalancer-member1810.1.13.203","ipAddress":"10.1.13.203","port":"24","weight":"1"}],"protocol":"TCP","srcPort":"24","dstPort":"24","privateIp":"10.1.80.222","fipName":"floating-ip-pool2","fiName":"floating-ip121","monitorType":"PING","maxRetries":"3","delay":"5","timeout":"5","wait":"0","bypassHostMaintenance":"false"}}] }
2023-02-16 14:14:40,100 DEBUG [c.c.a.m.DirectAgentAttache] (DirectAgent-57:ctx-85719167) (logid:bcb643dc) Seq 7-6552455982847361137: Executing request
2023-02-16 14:14:40,191 DEBUG [c.c.s.StatsCollector] (StatsCollector-5:ctx-43cd7d7a) (logid:751e4a49) HostStatsCollector is running...
2023-02-16 14:14:40,198 DEBUG [c.c.a.t.Request] (StatsCollector-5:ctx-43cd7d7a) (logid:751e4a49) Seq 8-8561061416654605649: Received:  { Ans: , MgmtId: 32986774896912, via: 8(kvm3), Ver: v1, Flags: 10, { GetHostStatsAnswer } }
2023-02-16 14:14:40,243 DEBUG [c.c.a.t.Request] (StatsCollector-5:ctx-43cd7d7a) (logid:751e4a49) Seq 9-3373759070853923614: Received:  { Ans: , MgmtId: 32986774896912, via: 9(kvm4), Ver: v1, Flags: 10, { GetHostStatsAnswer } }
2023-02-16 14:14:40,278 WARN  [c.c.a.m.DirectAgentAttache] (DirectAgent-57:ctx-85719167) (logid:9e649959) Seq 7-6552455982847361137: Throwable caught while executing command
java.lang.NullPointerException
        at org.apache.cloudstack.network.tungsten.service.TungstenApi.assignTungstenFloatingIp(TungstenApi.java:522)
        at org.apache.cloudstack.network.tungsten.resource.TungstenResource.executeRequest(TungstenResource.java:1063)
        at org.apache.cloudstack.network.tungsten.resource.TungstenResource.executeRequestGroup2(TungstenResource.java:329)
        at org.apache.cloudstack.network.tungsten.resource.TungstenResource.executeRequestGroup1(TungstenResource.java:299)
        at org.apache.cloudstack.network.tungsten.resource.TungstenResource.executeRequest(TungstenResource.java:268)
        at com.cloud.agent.manager.DirectAgentAttache$Task.runInContext(DirectAgentAttache.java:315)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:48)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:45)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
2023-02-16 14:14:40,279 DEBUG [c.c.a.m.DirectAgentAttache] (DirectAgent-57:ctx-85719167) (logid:9e649959) Seq 7-6552455982847361137: Response Received:
2023-02-16 14:14:40,279 DEBUG [c.c.a.t.Request] (DirectAgent-57:ctx-85719167) (logid:9e649959) Seq 7-6552455982847361137: Processing:  { Ans: , MgmtId: 32986774896912, via: 7(TungstenDevice - TF), Ver: v1, Flags: 10, [{"com.cloud.agent.api.Answer":{"result":"false","details":"java.lang.NullPointerException","wait":"0","bypassHostMaintenance":"false"}}] }
```

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~
4.18-RC1
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #7241 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by rohityadavcloud — APPROVED** [review]

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by shwstppr — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@blueorangutan package

**Pull request merged**
