### PR TITLE
VNF: fix UI bugs and polish

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes some UI bugs and polish
- vnfapp details page is empty if there is no vnfnics defined. see https://github.com/apache/cloudstack/pull/8227/commits/b042fd3370b56eda5b00532ff2a83c1ba3a42392
- Failed to add vnfapp details, no vm details options, and no tags. see https://github.com/apache/cloudstack/pull/8227/commits/36873c87367cedd9cacff8ec6721576c350fad55
- Failed to migrate vnfapp due to wrong API passed. see https://github.com/apache/cloudstack/pull/8227/commits/4fd8a07a29ade2a2f5acd7e05ac2b03f957f1cd7
- The first network is marked as Default in the summary when deploy a vnf appliance. see https://github.com/apache/cloudstack/pull/8227/commits/6261088923b1c1027ffb4addc53fd2451d6b1774
- Remove attribute 'icon' from VNF detail options as it is similar as resource icon. see https://github.com/apache/cloudstack/pull/8227/commits/ebdd67d16c24f32fc0e1ebd327530ba62d088006

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by NuxRo — APPROVED** [review]
LGMT, good job

**Review by harikrishna-patnala — APPROVED** [review]
did not test, but code LGTM

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@NuxRo @harikrishna-patnala 
thanks for review. I have made 2 more small changes to this PR
this is ready for review and merge (if everything is ok)

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by NuxRo — APPROVED** [review]
LGTM

**Comment by DaanHoogland** [comment]
@blueorangutan LLtest

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@blueorangutan package

**Pull request merged**
