### PR TITLE
cks,ui: allow changing stopped cluster offering, improvements

### LINKED ISSUE #7454: Not able to change compute offering in a Kubernetes cluster when using KVM VMs
##### ISSUE TYPE
 * Improvement Request

##### COMPONENT NAME
~~~
Kubernetes
~~~

##### CLOUDSTACK VERSION
~~~
4.18
~~~

##### CONFIGURATION
Default, following guides provided by CloudStack

##### OS / ENVIRONMENT
Ubuntu 22.04

KVM hypervisor

##### SUMMARY
Changing compute offering when scaling Kubernetes cluster results in error saying that it is not support.

".. on KVM is not supported!"

I expect to be able to change the compute offering after the cluster is created.
For a use case such as: increasing the RAM since a heavy app requires it.

##### STEPS TO REPRODUCE
~~~
- create a Kubernetes cluster on KVM VMs
- scale the cluster with a different compute offering
~~~

##### EXPECTED RESULTS
~~~
I expect to be able to change compute offering for a Kubernetes cluster
~~~

##### ACTUAL RESULTS
~~~
Error popup saying that it is not supported on KVM.
~~~

Error in code:
https://github.dev/apache/cloudstack/blob/2ac1b7e9599b048d3490577b0823752fc7a740d7/plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterScaleWorker.java#L240

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #7454

- Allows changing compute offering for a stopped cluster
- Allows compute offering change when the cluster has autoscaling enabled
 
### Types of changes
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

Using cmk:

Service offerings:
```
(localcloud) 🐱 > list serviceofferings id=5b9471db-0f98-4ad4-8e27-d31935c1d5fe 
{
  "count": 1,
  "serviceoffering": [
    {
      "cacheMode": "none",
      "cpunumber": 2,
      "cpuspeed": 1000,
      "created": "2023-05-22T08:22:32+0000",
      "defaultuse": false,
      "diskofferingstrictness": false,
      "displaytext": "CKS Instance",
      "dynamicscalingenabled": true,
      "encryptroot": false,
      "hasannotations": false,
      "id": "5b9471db-0f98-4ad4-8e27-d31935c1d5fe",
      "iscustomized": false,
      "issystem": false,
      "isvolatile": false,
      "limitcpuuse": false,
      "memory": 2048,
      "name": "CKS Instance",
      "offerha": false,
      "provisioningtype": "thin",
      "rootdisksize": 0,
      "storagetype": "shared"
    }
  ]
}
(localcloud) 🐱 > list serviceofferings id=54a44f69-2803-4a84-aeca-df7f81aa9c1b 
{
  "count": 1,
  "serviceoffering": [
    {
      "cacheMode": "none",
      "cpunumber": 2,
      "cpuspeed": 1000,
      "created": "2023-05-23T11:58:51+0000",
      "defaultuse": false,
      "diskofferingstrictness": false,
      "displaytext": "Upgrade CKS Instance",
      "dynamicscalingenabled": true,
      "encryptroot": false,
      "hasannotations": false,
      "id": "54a44f69-2803-4a84-aeca-df7f81aa9c1b",
      "iscustomized": false,
      "issystem": false,
      "isvolatile": false,
      "limitcpuuse": false,
      "memory": 2560,
      "name": "Upgrade CKS Instance",
      "offerha": false,
      "provisioningtype": "thin",
      "rootdisksize": 0,
      "storagetype": "shared"
    }
  ]
}
```

k8s cluster deployment and stopping:
```
(localcloud) 🐱 > create kubernetescluster zoneid=28693109-f77c-42ad-a3d7-e04c40800e1f name=t1 description=t1 kubernetesversionid=53bf05e1-1b7b-49f3-976b-7127a62ab8a0 serviceofferingid=5b9471db-0f98-4ad4-8e27-d31935c1d5fe size=1
{
  "kubernetescluster": {
    "account": "admin",
    "associatednetworkname": "t1-network",
    "autoscalingenabled": false,
    "controlnodes": 1,
    "cpunumber": "4",
    "created": "2023-05-23T11:57:56+0000",
    "description": "t1",
    "domain": "ROOT",
    "domainid": "06f469cb-f85b-11ed-9f8f-1e009f00014a",
    "endpoint": "https://10.0.54.163:6443/",
    "hasannotations": false,
    "id": "99c71dba-285c-48a7-942a-8e712e32e99d",
    "ipaddress": "10.0.54.163",
    "ipaddressid": "d973691c-4d20-4a29-871e-dbee002f8ba4",
    "kubernetesversionid": "53bf05e1-1b7b-49f3-976b-7127a62ab8a0",
    "kubernetesversionname": "v1.26.0",
    "masternodes": 1,
    "memory": "4096",
    "name": "t1",
    "networkid": "fa5c4f55-1897-4418-9f5b-3f654e86cf7e",
    "serviceofferingid": "5b9471db-0f98-4ad4-8e27-d31935c1d5fe",
    "serviceofferingname": "CKS Instance",
    "size": 1,
    "state": "Running",
    "templateid": "11db18e7-43b7-4e3c-991c-a3b5c2f61968",
    "virtualmachines": [
      {
        "account": "admin",
        "affinitygroup": [],
        "created": "2023-05-23T11:58:31+0000",
        "details": {
          "controlNodeLoginUser": "cloud",
          "cpuOvercommitRatio": "2.0",
          "memoryOvercommitRatio": "1.0",
          "rootdisksize": "8"
        },
        "displayname": "t1-control-1884879a45c",
        "displayvm": true,
        "domain": "ROOT",
        "domainid": "06f469cb-f85b-11ed-9f8f-1e009f00014a",
        "guestosid": "06fce009-f85b-11ed-9f8f-1e009f00014a",
        "haenable": false,
        "hasannotations": false,
        "hostcontrolstate": "Enabled",
        "hostid": "cb8a8132-ef62-46df-b5b0-8a4cbeb41ca9",
        "hostname": "pr7479-t6536-kvm-centos7-kvm2",
        "hypervisor": "KVM",
        "id": "5f3da9b7-a7d7-4d2c-946c-719923506a39",
        "instancename": "i-2-65-VM",
        "isdynamicallyscalable": false,
        "lastupdated": "2023-05-23T11:58:43+0000",
        "name": "t1-control-1884879a45c",
        "nic": [
          {
            "broadcasturi": "vlan://1629",
            "deviceid": "0",
            "extradhcpoption": [],
            "gateway": "10.1.1.1",
            "id": "27252d7f-773a-4a67-97d3-81487ab41c0b",
            "ipaddress": "10.1.1.177",
            "isdefault": true,
            "isolationuri": "vlan://1629",
            "macaddress": "02:00:4a:bc:00:02",
            "netmask": "255.255.255.0",
            "networkid": "fa5c4f55-1897-4418-9f5b-3f654e86cf7e",
            "networkname": "t1-network",
            "secondaryip": [],
            "traffictype": "Guest",
            "type": "Isolated"
          }
        ],
        "osdisplayname": "Debian GNU/Linux 5.0 (64-bit)",
        "ostypeid": "06fce009-f85b-11ed-9f8f-1e009f00014a",
        "pooltype": "NetworkFilesystem",
        "receivedbytes": 0,
        "securitygroup": [],
        "sentbytes": 0,
        "state": "Running",
        "tags": [],
        "userid": "21d66d69-f85b-11ed-9f8f-1e009f00014a",
        "username": "admin",
        "zoneid": "28693109-f77c-42ad-a3d7-e04c40800e1f",
        "zonename": "pr7479-t6536-kvm-centos7"
      },
      {
        "account": "admin",
        "affinitygroup": [],
        "created": "2023-05-23T11:58:44+0000",
        "details": {
          "controlNodeLoginUser": "cloud",
          "cpuOvercommitRatio": "2.0",
          "memoryOvercommitRatio": "1.0",
          "rootdisksize": "8"
        },
        "displayname": "t1-node-1884879d541",
        "displayvm": true,
        "domain": "ROOT",
        "domainid": "06f469cb-f85b-11ed-9f8f-1e009f00014a",
        "guestosid": "06fce009-f85b-11ed-9f8f-1e009f00014a",
        "haenable": false,
        "hasannotations": false,
        "hostcontrolstate": "Enabled",
        "hostid": "cb8a8132-ef62-46df-b5b0-8a4cbeb41ca9",
        "hostname": "pr7479-t6536-kvm-centos7-kvm2",
        "hypervisor": "KVM",
        "id": "c267ae48-b24b-45e4-a03c-d4a8d010e214",
        "instancename": "i-2-66-VM",
        "isdynamicallyscalable": false,
        "lastupdated": "2023-05-23T11:58:58+0000",
        "name": "t1-node-1884879d541",
        "nic": [
          {
            "broadcasturi": "vlan://1629",
            "deviceid": "0",
            "extradhcpoption": [],
            "gateway": "10.1.1.1",
            "id": "c8c43943-fb83-45ce-bdca-1cee12187296",
            "ipaddress": "10.1.1.2",
            "isdefault": true,
            "isolationuri": "vlan://1629",
            "macaddress": "02:00:30:c7:00:03",
            "netmask": "255.255.255.0",
            "networkid": "fa5c4f55-1897-4418-9f5b-3f654e86cf7e",
            "networkname": "t1-network",
            "secondaryip": [],
            "traffictype": "Guest",
            "type": "Isolated"
          }
        ],
        "osdisplayname": "Debian GNU/Linux 5.0 (64-bit)",
        "ostypeid": "06fce009-f85b-11ed-9f8f-1e009f00014a",
        "pooltype": "NetworkFilesystem",
        "receivedbytes": 0,
        "securitygroup": [],
        "sentbytes": 0,
        "state": "Running",
        "tags": [],
        "userid": "21d66d69-f85b-11ed-9f8f-1e009f00014a",
        "username": "admin",
        "zoneid": "28693109-f77c-42ad-a3d7-e04c40800e1f",
        "zonename": "pr7479-t6536-kvm-centos7"
      }
    ],
    "zoneid": "28693109-f77c-42ad-a3d7-e04c40800e1f",
    "zonename": "pr7479-t6536-kvm-centos7"
  }
}
(localcloud) 🐱 > stop kubernetescluster id=99c71dba-285c-48a7-942a-8e712e32e99d
{
  "success": true
}
```

Scale cluster for offering and start:
```
(localcloud) 🐱 > scale kubernetescluster id=99c71dba-285c-48a7-942a-8e712e32e99d serviceofferingid=54a44f69-2803-4a84-aeca-df7f81aa9c1b 
{
  "kubernetescluster": {
    "account": "admin",
    "associatednetworkname": "t1-network",
    "autoscalingenabled": false,
    "controlnodes": 1,
    "cpunumber": "4",
    "created": "2023-05-23T11:57:56+0000",
    "description": "t1",
    "domain": "ROOT",
    "domainid": "06f469cb-f85b-11ed-9f8f-1e009f00014a",
    "endpoint": "https://10.0.54.163:6443/",
    "hasannotations": false,
    "id": "99c71dba-285c-48a7-942a-8e712e32e99d",
    "ipaddress": "10.0.54.163",
    "ipaddressid": "d973691c-4d20-4a29-871e-dbee002f8ba4",
    "kubernetesversionid": "53bf05e1-1b7b-49f3-976b-7127a62ab8a0",
    "kubernetesversionname": "v1.26.0",
    "masternodes": 1,
    "memory": "5120",
    "name": "t1",
    "networkid": "fa5c4f55-1897-4418-9f5b-3f654e86cf7e",
    "serviceofferingid": "54a44f69-2803-4a84-aeca-df7f81aa9c1b",
    "serviceofferingname": "Upgrade CKS Instance",
    "size": 1,
    "state": "Stopped",
    "templateid": "11db18e7-43b7-4e3c-991c-a3b5c2f61968",
    "virtualmachines": [
      {
        "account": "admin",
        "affinitygroup": [],
        "created": "2023-05-23T11:58:31+0000",
        "details": {
          "Message.ReservedCapacityFreed.Flag": "false",
          "controlNodeLoginUser": "cloud",
          "cpuOvercommitRatio": "2.0",
          "memoryOvercommitRatio": "1.0",
          "rootdisksize": "8"
        },
        "displayname": "t1-control-1884879a45c",
        "displayvm": true,
        "domain": "ROOT",
        "domainid": "06f469cb-f85b-11ed-9f8f-1e009f00014a",
        "guestosid": "06fce009-f85b-11ed-9f8f-1e009f00014a",
        "haenable": false,
        "hasannotations": false,
        "hypervisor": "KVM",
        "id": "5f3da9b7-a7d7-4d2c-946c-719923506a39",
        "instancename": "i-2-65-VM",
        "isdynamicallyscalable": false,
        "lastupdated": "2023-05-23T12:21:50+0000",
        "name": "t1-control-1884879a45c",
        "nic": [
          {
            "deviceid": "0",
            "extradhcpoption": [],
            "gateway": "10.1.1.1",
            "id": "27252d7f-773a-4a67-97d3-81487ab41c0b",
            "ipaddress": "10.1.1.177",
            "isdefault": true,
            "macaddress": "02:00:4a:bc:00:02",
            "netmask": "255.255.255.0",
            "networkid": "fa5c4f55-1897-4418-9f5b-3f654e86cf7e",
            "networkname": "t1-network",
            "secondaryip": [],
            "traffictype": "Guest",
            "type": "Isolated"
          }
        ],
        "osdisplayname": "Debian GNU/Linux 5.0 (64-bit)",
        "ostypeid": "06fce009-f85b-11ed-9f8f-1e009f00014a",
        "pooltype": "NetworkFilesystem",
        "receivedbytes": 0,
        "securitygroup": [],
        "sentbytes": 0,
        "state": "Stopped",
        "tags": [],
        "userid": "21d66d69-f85b-11ed-9f8f-1e009f00014a",
        "username": "admin",
        "zoneid": "28693109-f77c-42ad-a3d7-e04c40800e1f",
        "zonename": "pr7479-t6536-kvm-centos7"
      },
      {
        "account": "admin",
        "affinitygroup": [],
        "created": "2023-05-23T11:58:44+0000",
        "details": {
          "Message.ReservedCapacityFreed.Flag": "false",
          "controlNodeLoginUser": "cloud",
          "cpuOvercommitRatio": "2.0",
          "memoryOvercommitRatio": "1.0",
          "rootdisksize": "8"
        },
        "displayname": "t1-node-1884879d541",
        "displayvm": true,
        "domain": "ROOT",
        "domainid": "06f469cb-f85b-11ed-9f8f-1e009f00014a",
        "guestosid": "06fce009-f85b-11ed-9f8f-1e009f00014a",
        "haenable": false,
        "hasannotations": false,
        "hypervisor": "KVM",
        "id": "c267ae48-b24b-45e4-a03c-d4a8d010e214",
        "instancename": "i-2-66-VM",
        "isdynamicallyscalable": false,
        "lastupdated": "2023-05-23T12:21:54+0000",
        "name": "t1-node-1884879d541",
        "nic": [
          {
            "deviceid": "0",
            "extradhcpoption": [],
            "gateway": "10.1.1.1",
            "id": "c8c43943-fb83-45ce-bdca-1cee12187296",
            "ipaddress": "10.1.1.2",
            "isdefault": true,
            "macaddress": "02:00:30:c7:00:03",
            "netmask": "255.255.255.0",
            "networkid": "fa5c4f55-1897-4418-9f5b-3f654e86cf7e",
            "networkname": "t1-network",
            "secondaryip": [],
            "traffictype": "Guest",
            "type": "Isolated"
          }
        ],
        "osdisplayname": "Debian GNU/Linux 5.0 (64-bit)",
        "ostypeid": "06fce009-f85b-11ed-9f8f-1e009f00014a",
        "pooltype": "NetworkFilesystem",
        "receivedbytes": 0,
        "securitygroup": [],
        "sentbytes": 0,
        "state": "Stopped",
        "tags": [],
        "userid": "21d66d69-f85b-11ed-9f8f-1e009f00014a",
        "username": "admin",
        "zoneid": "28693109-f77c-42ad-a3d7-e04c40800e1f",
        "zonename": "pr7479-t6536-kvm-centos7"
      }
    ],
    "zoneid": "28693109-f77c-42ad-a3d7-e04c40800e1f",
    "zonename": "pr7479-t6536-kvm-centos7"
  }
}
(localcloud) 🐱 > list virtualmachines id=5f3da9b7-a7d7-4d2c-946c-719923506a39 filter=id,name,serviceofferingid,serviceofferingname
{
  "count": 1,
  "virtualmachine": [
    {
      "id": "5f3da9b7-a7d7-4d2c-946c-719923506a39",
      "name": "t1-control-1884879a45c",
      "serviceofferingid": "54a44f69-2803-4a84-aeca-df7f81aa9c1b",
      "serviceofferingname": "Upgrade CKS Instance"
    }
  ]
}
(localcloud) 🐱 > start kubernetescluster id=99c71dba-285c-48a7-942a-8e712e32e99d 
{
  "kubernetescluster": {
    "account": "admin",
    "associatednetworkname": "t1-network",
    "autoscalingenabled": false,
    "controlnodes": 1,
    "cpunumber": "4",
    "created": "2023-05-23T11:57:56+0000",
    "description": "t1",
    "domain": "ROOT",
    "domainid": "06f469cb-f85b-11ed-9f8f-1e009f00014a",
    "endpoint": "https://10.0.54.163:6443/",
    "hasannotations": false,
    "id": "99c71dba-285c-48a7-942a-8e712e32e99d",
    "ipaddress": "10.0.54.163",
    "ipaddressid": "d973691c-4d20-4a29-871e-dbee002f8ba4",
    "kubernetesversionid": "53bf05e1-1b7b-49f3-976b-7127a62ab8a0",
    "kubernetesversionname": "v1.26.0",
    "masternodes": 1,
    "memory": "5120",
    "name": "t1",
    "networkid": "fa5c4f55-1897-4418-9f5b-3f654e86cf7e",
    "serviceofferingid": "54a44f69-2803-4a84-aeca-df7f81aa9c1b",
    "serviceofferingname": "Upgrade CKS Instance",
    "size": 1,
    "state": "Running",
    "templateid": "11db18e7-43b7-4e3c-991c-a3b5c2f61968",
    "virtualmachines": [
      {
        "account": "admin",
        "affinitygroup": [],
        "created": "2023-05-23T11:58:31+0000",
        "details": {
          "Message.ReservedCapacityFreed.Flag": "false",
          "controlNodeLoginUser": "cloud",
          "cpuOvercommitRatio": "2.0",
          "memoryOvercommitRatio": "1.0",
          "rootdisksize": "8"
        },
        "displayname": "t1-control-1884879a45c",
        "displayvm": true,
        "domain": "ROOT",
        "domainid": "06f469cb-f85b-11ed-9f8f-1e009f00014a",
        "guestosid": "06fce009-f85b-11ed-9f8f-1e009f00014a",
        "haenable": false,
        "hasannotations": false,
        "hostcontrolstate": "Enabled",
        "hostid": "cb8a8132-ef62-46df-b5b0-8a4cbeb41ca9",
        "hostname": "pr7479-t6536-kvm-centos7-kvm2",
        "hypervisor": "KVM",
        "id": "5f3da9b7-a7d7-4d2c-946c-719923506a39",
        "instancename": "i-2-65-VM",
        "isdynamicallyscalable": false,
        "lastupdated": "2023-05-23T12:23:36+0000",
        "name": "t1-control-1884879a45c",
        "nic": [
          {
            "broadcasturi": "vlan://1629",
            "deviceid": "0",
            "extradhcpoption": [],
            "gateway": "10.1.1.1",
            "id": "27252d7f-773a-4a67-97d3-81487ab41c0b",
            "ipaddress": "10.1.1.177",
            "isdefault": true,
            "isolationuri": "vlan://1629",
            "macaddress": "02:00:4a:bc:00:02",
            "netmask": "255.255.255.0",
            "networkid": "fa5c4f55-1897-4418-9f5b-3f654e86cf7e",
            "networkname": "t1-network",
            "secondaryip": [],
            "traffictype": "Guest",
            "type": "Isolated"
          }
        ],
        "osdisplayname": "Debian GNU/Linux 5.0 (64-bit)",
        "ostypeid": "06fce009-f85b-11ed-9f8f-1e009f00014a",
        "pooltype": "NetworkFilesystem",
        "receivedbytes": 0,
        "securitygroup": [],
        "sentbytes": 0,
        "state": "Running",
        "tags": [],
        "userid": "21d66d69-f85b-11ed-9f8f-1e009f00014a",
        "username": "admin",
        "zoneid": "28693109-f77c-42ad-a3d7-e04c40800e1f",
        "zonename": "pr7479-t6536-kvm-centos7"
      },
      {
        "account": "admin",
        "affinitygroup": [],
        "created": "2023-05-23T11:58:44+0000",
        "details": {
          "Message.ReservedCapacityFreed.Flag": "false",
          "controlNodeLoginUser": "cloud",
          "cpuOvercommitRatio": "2.0",
          "memoryOvercommitRatio": "1.0",
          "rootdisksize": "8"
        },
        "displayname": "t1-node-1884879d541",
        "displayvm": true,
        "domain": "ROOT",
        "domainid": "06f469cb-f85b-11ed-9f8f-1e009f00014a",
        "guestosid": "06fce009-f85b-11ed-9f8f-1e009f00014a",
        "haenable": false,
        "hasannotations": false,
        "hostcontrolstate": "Enabled",
        "hostid": "a7f5d4cc-f9fa-4177-b0a4-d1ac44a2ec95",
        "hostname": "pr7479-t6536-kvm-centos7-kvm1",
        "hypervisor": "KVM",
        "id": "c267ae48-b24b-45e4-a03c-d4a8d010e214",
        "instancename": "i-2-66-VM",
        "isdynamicallyscalable": false,
        "lastupdated": "2023-05-23T12:23:48+0000",
        "name": "t1-node-1884879d541",
        "nic": [
          {
            "broadcasturi": "vlan://1629",
            "deviceid": "0",
            "extradhcpoption": [],
            "gateway": "10.1.1.1",
            "id": "c8c43943-fb83-45ce-bdca-1cee12187296",
            "ipaddress": "10.1.1.2",
            "isdefault": true,
            "isolationuri": "vlan://1629",
            "macaddress": "02:00:30:c7:00:03",
            "netmask": "255.255.255.0",
            "networkid": "fa5c4f55-1897-4418-9f5b-3f654e86cf7e",
            "networkname": "t1-network",
            "secondaryip": [],
            "traffictype": "Guest",
            "type": "Isolated"
          }
        ],
        "osdisplayname": "Debian GNU/Linux 5.0 (64-bit)",
        "ostypeid": "06fce009-f85b-11ed-9f8f-1e009f00014a",
        "pooltype": "NetworkFilesystem",
        "receivedbytes": 0,
        "securitygroup": [],
        "sentbytes": 0,
        "state": "Running",
        "tags": [],
        "userid": "21d66d69-f85b-11ed-9f8f-1e009f00014a",
        "username": "admin",
        "zoneid": "28693109-f77c-42ad-a3d7-e04c40800e1f",
        "zonename": "pr7479-t6536-kvm-centos7"
      }
    ],
    "zoneid": "28693109-f77c-42ad-a3d7-e04c40800e1f",
    "zonename": "pr7479-t6536-kvm-centos7"
  }
}
```

Verify cluster VMs are having new offering:
```
(localcloud) 🐱 > list virtualmachines ids=5f3da9b7-a7d7-4d2c-946c-719923506a39,c267ae48-b24b-45e4-a03c-d4a8d010e214 filter=id,name,serviceofferingid,serviceofferingname,state
{
  "count": 2,
  "virtualmachine": [
    {
      "id": "5f3da9b7-a7d7-4d2c-946c-719923506a39",
      "name": "t1-control-1884879a45c",
      "serviceofferingid": "54a44f69-2803-4a84-aeca-df7f81aa9c1b",
      "serviceofferingname": "Upgrade CKS Instance",
      "state": "Running"
    },
    {
      "id": "c267ae48-b24b-45e4-a03c-d4a8d010e214",
      "name": "t1-node-1884879d541",
      "serviceofferingid": "54a44f69-2803-4a84-aeca-df7f81aa9c1b",
      "serviceofferingname": "Upgrade CKS Instance",
      "state": "Running"
    }
  ]
}
```

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Comment by shwstppr** [comment]
@blueorangutan test

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Review by vladimirpetrov — APPROVED** [review]
LGTM based on manual testing.

**Pull request merged**
