### PR TITLE
Updated upgrade paths

### PR DESCRIPTION
**Pull request by Spaceman1984**
## Description

This PR adds the 4.13.0.0 to 4.13.1.0 upgrade path and renames the 4.13.0.0 to 4.14.0.0 upgrade path to 4.13.1.0 to 4.14.0.0

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

This has been tested by installing the new system vm template, updating the agent, starting the client and checking the db version.

### CODE REVIEW

**Comment by Spaceman1984** [comment]
@orangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@andrijapanicsb i had to solve merge conflicts as predicted, of course I did it perfectly and we don't have to test, so I leave you the honour of merging ;)

**Comment by andrijapanicsb** [comment]
that's extra complex conflict @DaanHoogland - thx for solving :)

Merging now based on automated test results and manual testing from Bobby and 2 x LGTMs
(will regret later...)

**Comment by DaanHoogland** [comment]
ohw dear, this is going to haunt us

**Pull request merged**
