### PR TITLE
Add scopes to config - as it crashes master when started from empty DB

### PR DESCRIPTION
**Pull request by anuragaw**
## Description

The commit https://github.com/apache/cloudstack/commit/16527f1eb070a796732e99cf8fe466b61cf972c3 breaks building master off fresh DB.

Add scopes to config - as it crashes master when started from empty DB

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

Build master and deploy with empty DB. Watch MS failing. 
Build this branch and see it run.

### CODE REVIEW

**Comment by anuragaw** [comment]
ping @andrijapanicsb , @rhtyd , @borisstoyanov , @svenvogel - ping for review.

**Comment by anuragaw** [comment]
@blueorangutan package

**Comment by andrijapanicsb** [comment]
@blueorangutan package

**Comment by andrijapanicsb** [comment]
Putting this PR on hold @anuragaw, since @svenvogel will revert the original PR #3737 and we will continue the fix there. (probably close this PR later on)

**Comment by svenvogel** [comment]
@anuragaw can @mdominka use that for a new PR to fix our issues?

**Comment by anuragaw** [comment]
Closing as @svenvogel has reverted the commit.

**Pull request closed without merging**
