### PR TITLE
CLOUDSTACK-9453: WIP

### PR DESCRIPTION
**Pull request by abhinandanprateek**
1. Adding small sized macchinina template as built in templates
2. Adding methods so the test writers haev choice to use any of these
3. Updateing test_host_ha to use macchinina template
4. Misc fixes encoutered while running component tests

### CODE REVIEW

**Comment by serg38** [comment]
Macchinina template doesn't seem to work in vmware hypervisor. When VM deployed eth0 is not created. We probably need to make sure a template is fully operational on all 3 hypervisors to include it as a default.

**Comment by abhinandanprateek** [comment]
https://github.com/apache/cloudstack/pull/1639

**Comment by jburwell** [comment]
@abhi can this PR be closed in favor of #1639?

**Comment by rhtyd** [comment]
@abhinandanprateek ping

**Comment by jburwell** [comment]
@abhinandanprateek ping re: closing this PR in favor of #1639

**Comment by rhtyd** [comment]
@abhinandanprateek is this still wip? let me know any help from my end, also please rebase/fix conflicts?

**Comment by abhinandanprateek** [comment]
@rhtyd closing this PR as relevant portion of this are already in codebase via other VRs.

**Pull request closed without merging**
