### PR TITLE
CLOUDSTACK-8630: Fix for missing Firewall service parameter in test script

### PR DESCRIPTION
**Pull request by pavanb018**
Test Create/Delete a LB rule and verify correct usage is recorded ... === TestName: test_01_lb_usage | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 1 test in 50.564s

OK

### CODE REVIEW

**Comment by wilderrodrigues** [comment]
:-1: 

What does a "Newb" as the PR title means?

We are trying to organise the way we work and avoid such PR titles.

Please create an issue on Jira (https://issues.apache.org/jira/browse/CLOUDSTACK) and use the issue title as the PR title.

Cheers,
Wilder

**Comment by pavanb018** [comment]
Created an ACS ticket describing the changes.

**Comment by wilderrodrigues** [comment]
Thanks for the quick fix, @pavanb018 

Now it LGTM :+1: 

Please proceed with the merge.

**Comment by sanju1010** [comment]
Committed to ACS master:
commit 03e8176baba43f0394d530e64e7f96d6c841e9b2
Author: pavan018 <pavanbandarupally@gmail.com>
Date:   Mon Jul 13 18:11:24 2015 +0530

    Passing firewal service parameter for LB rule creation

    Firewall service parameter addition typos

**Pull request closed without merging**
