### PR TITLE
allow migration of all VMs with local storage on KVM

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR enables SVM migration on KVM local storage.

Fixes: #7651

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### How Has This Been Tested?

manually, by migrating SSVMs and then testing console proxying them.

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by rohityadavcloud — APPROVED** [review]
LGTM

**Comment by DaanHoogland** [comment]
> LGTM

Did you test it @rohityadavcloud ?

**Review by nvazquez — APPROVED** [review]
Code LGTM

**Comment by vladimirpetrov** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Comment by rohityadavcloud** [comment]
Tested in my local KVM local-storage env; previously clicking this form was giving error; but now I was able to live migrate
Screenshot 2023-07-18 at 12 47 41 PM

**Pull request merged**
