### PR TITLE
CLOUDSTACK-9396:fixing issue related to script test_dhcphosts

### PR DESCRIPTION
**Pull request by nitt10prashant**
fixing following
1-issue related to check_String:changed check string to "3 received" and use test_data
2-ssh to router based on hypervisor type : check if it is vmware ssh to ms else ssh to host
3-rename method : because of test_ methods were getting picked up as a test cases ,renamed them not to get picked up as a test method
4- modifying awk parameter from $2 to $3
## test result

Prashants-MacBook-Pro:test_router_dhcphosts_YDZJFT prashant$ cat results.txt 
Check that the /etc/dhcphosts.txt doesn't contain duplicate IPs ... === TestName: test_router_dhcphosts | Status : SUCCESS ===
ok

---

Ran 1 test in 385.178s

OK
[results.txt](https://github.com/apache/cloudstack/files/290716/results.txt)
[runinfo.txt](https://github.com/apache/cloudstack/files/290717/runinfo.txt)

Note: this PR require check_string to be there in test_data.py which will be brought in by another PR
https://github.com/apache/cloudstack/pull/1563 which is still in open state.

### CODE REVIEW

**Comment by bvbharatk** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 206
 Hypervisor xenserver
 NetworkType Advanced
 Passed=73
 Failed=0
 Skipped=3

_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/yj3wnzbceo9uef2/AAB6u-Iap-xztdm6jHX9SjPja?dl=0


**Failed tests:**

**Skipped tests:**
test_vm_nic_adapter_vmxnet3
test_static_role_account_acls
test_deploy_vgpu_enabled_vm

**Passed test suits:**
test_deploy_vm_with_userdata.py
test_affinity_groups_projects.py
test_portable_publicip.py
test_vpc_vpn.py
test_over_provisioning.py
test_global_settings.py
test_scale_vm.py
test_service_offerings.py
test_routers_iptables_default_policy.py
test_routers.py
test_reset_vm_on_reboot.py
test_snapshots.py
test_deploy_vms_with_varied_deploymentplanners.py
test_login.py
test_list_ids_parameter.py
test_public_ip_range.py
test_multipleips_per_nic.py
test_regions.py
test_affinity_groups.py
test_network_acl.py
test_pvlan.py
test_volumes.py
test_nic.py
test_deploy_vm_root_resize.py
test_resource_detail.py
test_secondary_storage.py
test_vm_life_cycle.py
test_disk_offerings.py

**Comment by rhtyd** [comment]
@nitt10prashant can you fix the conflicts, thanks

**Comment by rhtyd** [comment]
@nitt10prashant can you rebase against 4.9, change the base branch for the PR to 4.9. Thanks. /cc @jburwell

**Comment by nitt10prashant** [comment]
not needed

**Pull request closed without merging**
