### PR TITLE
remove unused UI field

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR removes a field from the ui that will always be empty

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by sureshanaparti — APPROVED** [review]
code LGTM

**Comment by DaanHoogland** [comment]
@blueorangutan test keepEnv

**Review by nvazquez — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@nvazquez , this is UI only. I started the test for some other experiment. I think you can merge as is.

**Pull request merged**
