### PR TITLE
ui: bump UI dependencies versions

### PR DESCRIPTION
**Pull request by rohityadavcloud**
Bumps up versions for ant and other dependencies to latest/stable minors.

This is just regular maintenance work, but not migrating to major versions of dependencies.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

Built and ran it locally using npm v16 on Mac osx arm64.

### CODE REVIEW

**Comment by rohityadavcloud** [comment]
@blueorangutan ui

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
lgtm, maybe even a higher npm version?

**Review by Pearl1594 — APPROVED** [review]

**Review by vishesh92 — APPROVED** [review]
clgtm
Did some monkey testing on the UI build and didn't see any issues.

**Pull request merged**
