### PR TITLE
Update L10N resource files on 4.5 branch with 4.5 translation strings…

### PR DESCRIPTION
**Pull request by milamberspace**
… from Transifex (20150814)

### CODE REVIEW

**Comment by terbolous** [comment]
label.local.storage.enabled is removed from multiple languages, but added to one. Is that right?

**Comment by milamberspace** [comment]
Yes it's right, the original string has been changed, so the (old) translation has been removed on Transifer.

Long version:
* Cloudstack has now 2 new options on wizard for the local storage (one for user vm and one for system vm)
* The primary language words for label.local.storage.enabled has been changed (old version was more shorter that the new, i.e. the mention to "user vm")
* So, when I have uploaded the source language to transifex, this last has removed all translations of this key.
* Fr or pt_BR (here) translators has (re)translated the key since the upload, so, you have a new string for theses languages
* But currently, the others languages doesn't have been (re)translated to bring the new version with the user vm mention.

**Comment by runseb** [comment]
LGTM

**Comment by terbolous** [comment]
LGTM

**Comment by karuturi** [comment]
I merged this only to 4.5. I though merge to master is not required based on #699. Let me know if this needs to go to master as well.

**Comment by milamberspace** [comment]
Thanks for the merge.
yes not necessary, the PR #699 make the works for master branch.

**Pull request merged**
