### PR TITLE
systemvm: update size and state of systemvm template during registration

### LINKED ISSUE #7309: Kubernetes cluster is not created successfully on XCP-ng 8.2
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
 UI
~~~

##### CLOUDSTACK VERSION

~~~
4.17.2
~~~

##### SUMMARY

Unable to start kubernetes cluster 

Create Kubernetes cluster
Command failed due to Internal Server Error

2023-03-04 04:14:15,359 WARN  [c.c.a.d.ParamGenericValidationWorker] (qtp1443435931-22:ctx-e0c381d5 ctx-aa087e41) (logid:c20b12ee) Received
 unknown parameters for command queryAsyncJobResult. Unknown parameters : projectid
2023-03-04 04:14:15,363 INFO  [c.c.v.UserVmManagerImpl] (API-Job-Executor-4:ctx-16629d81 job-12113 ctx-e5e933b4) (logid:ee408dc1) VM cannot
 be configured to be dynamically scalable if any of the service offering's dynamic scaling property, template's dynamic scaling property or
 global setting is false
2023-03-04 04:14:15,372 DEBUG [c.c.u.d.T.Transaction] (API-Job-Executor-4:ctx-16629d81 job-12113 ctx-e5e933b4) (logid:ee408dc1) Rolling bac
k the transaction: Time = 7 Name =  API-Job-Executor-4; called by -TransactionLegacy.rollback:888-TransactionLegacy.removeUpTo:831-Transact
ionLegacy.close:655-Transaction.execute:38-UserVmManagerImpl.commitUserVm:4295-UserVmManagerImpl.commitUserVm:4518-UserVmManagerImpl.create
VirtualMachine:4155-UserVmManagerImpl.createAdvancedVirtualMachine:3668-NativeMethodAccessorImpl.invoke0:-2-NativeMethodAccessorImpl.invoke
:62-DelegatingMethodAccessorImpl.invoke:43-Method.invoke:566
2023-03-04 04:14:15,384 DEBUG [c.c.a.ApiServlet] (qtp1443435931-22:ctx-e0c381d5 ctx-aa087e41) (logid:c20b12ee) ===END===  188.242.17.99 --
GET  jobId=ee408dc1-484c-4533-b23f-54a2579a2016&command=queryAsyncJobResult&response=json&projectid=eec0900f-f554-4aa9-aaf2-88ffd0bb0b98
2023-03-04 04:14:15,392 ERROR [c.c.a.ApiAsyncJobDispatcher] (API-Job-Executor-4:ctx-16629d81 job-12113) (logid:ee408dc1) Unexpected excepti
on while executing org.apache.cloudstack.api.command.user.kubernetes.cluster.CreateKubernetesClusterCmd
java.lang.NullPointerException
        at com.cloud.vm.UserVmManagerImpl.validateRootDiskResize(UserVmManagerImpl.java:4530)
        at com.cloud.vm.UserVmManagerImpl$4.doInTransaction(UserVmManagerImpl.java:4343)
        at com.cloud.vm.UserVmManagerImpl$4.doInTransaction(UserVmManagerImpl.java:4343)
        at com.cloud.vm.UserVmManagerImpl$4.doInTransaction(UserVmManagerImpl.java:4295)
        at com.cloud.utils.db.Transaction.execute(Transaction.java:40)
        at com.cloud.vm.UserVmManagerImpl.commitUserVm(UserVmManagerImpl.java:4295)
        at com.cloud.vm.UserVmManagerImpl.commitUserVm(UserVmManagerImpl.java:4518)
        at com.cloud.vm.UserVmManagerImpl.createVirtualMachine(UserVmManagerImpl.java:4155)
        at com.cloud.vm.UserVmManagerImpl.createAdvancedVirtualMachine(UserVmManagerImpl.java:3668)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.apache.cloudstack.network.contrail.management.EventUtils$EventInterceptor.invoke(EventUtils.java:107)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
        at com.cloud.event.ActionEventInterceptor.invoke(ActionEventInterceptor.java:52)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
        at com.sun.proxy.$Proxy180.createAdvancedVirtualMachine(Unknown Source)
        at com.cloud.kubernetes.cluster.actionworkers.KubernetesClusterStartWorker.createKubernetesControlNode(KubernetesClusterStartWorker
.java:228)
        at com.cloud.kubernetes.cluster.actionworkers.KubernetesClusterStartWorker.provisionKubernetesClusterControlVm(KubernetesClusterSta
rtWorker.java:317)
        at com.cloud.kubernetes.cluster.actionworkers.KubernetesClusterStartWorker.startKubernetesClusterOnCreate(KubernetesClusterStartWor
ker.java:562)
        at com.cloud.kubernetes.cluster.KubernetesClusterManagerImpl.startKubernetesCluster(KubernetesClusterManagerImpl.java:1143)
        at org.apache.cloudstack.api.command.user.kubernetes.cluster.CreateKubernetesClusterCmd.execute(CreateKubernetesClusterCmd.java:287
)
        at com.cloud.api.ApiDispatcher.dispatch(ApiDispatcher.java:163)
        at com.cloud.api.ApiAsyncJobDispatcher.runJob(ApiAsyncJobDispatcher.java:106)
        at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.runInContext(AsyncJobManagerImpl.java:620)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:48)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:45)
        at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.run(AsyncJobManagerImpl.java:568)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-04 04:14:15,402 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-4:ctx-16629d81 job-12113) (logid:ee408dc1) Complete async
 job-12113, jobStatus: FAILED, resultCode: 530, result: org.apache.cloudstack.api.response.ExceptionResponse/null/{"uuidList":[],"errorcode
":"530"}
2023-03-04 04:14:15,405 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-4:ctx-16629d81 job-12113) (logid:ee408dc1) Publish async
job-12113 complete on message bus

##### STEPS TO REPRODUCE
Login to Cloudstack UI 
create kubernetes cluster

##### EXPECTED RESULTS

~~~
Kubernetes cluster has been created successfully 
~~~

##### ACTUAL RESULTS

~~~
Kubernetes cluster has been created with error
~~~

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #7309 

We need to always update the size and state of systemvm template during registration

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by Pearl1594 — APPROVED** [review]

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@Pearl1594 , did you test or just reviewed?

**Comment by Pearl1594** [comment]
I haven't tested it @DaanHoogland

**Review by rohityadavcloud — APPROVED** [review]
LGTM didn't test, we can merge if @weizhouapache advises what/how he has tested this.

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
verified both conditions in a test env.
template size is set during zone creation
only one entry is added per template/store (i didn't know this was a thing)

ready to merge, no?

**Pull request merged**
