### PR TITLE
ui: Adding success message for DomainActionForm

### PR DESCRIPTION
**Pull request by davidjumani**
### Description

Fixes https://github.com/apache/cloudstack/issues/4984

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### Screenshots (if appropriate):

Screenshot from 2021-05-03 12-10-15

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan ui

**Review by rhtyd — APPROVED** [review]
Didn't test, lgtm

**Review by shwstppr — APPROVED** [review]
LGTM

**Review by utchoang — APPROVED** [review]
LGTM!

**Pull request merged**
