### PR TITLE
Switched to the official SolidFire SDK for Python

### PR DESCRIPTION
**Pull request by mike-tutkowski**
SolidFire has recently released an official SDK for Python.

I have converted all of the SolidFire integration tests over to making use of this new SDK.

For testing, I re-ran each test and observed success.

https://pypi.python.org/pypi/solidfire-sdk-python/1.1.0.92

### CODE REVIEW

**Comment by jburwell** [comment]
@mike-tutkowski could you please amend the test result details to this PR?

**Comment by mike-tutkowski** [comment]
TestAddRemoveHosts.py:

test_add_remove_host_with_solidfire_plugin_1 (TestAddRemoveHosts.TestAddRemoveHosts) ... === TestName: test_add_remove_host_with_solidfire_plugin_1 | Status : SUCCESS ===
ok
test_add_remove_host_with_solidfire_plugin_2 (TestAddRemoveHosts.TestAddRemoveHosts) ... === TestName: test_add_remove_host_with_solidfire_plugin_2 | Status : SUCCESS ===
ok
test_add_remove_host_with_solidfire_plugin_3 (TestAddRemoveHosts.TestAddRemoveHosts) ... === TestName: test_add_remove_host_with_solidfire_plugin_3 | Status : SUCCESS ===
ok
test_add_remove_host_with_solidfire_plugin_4 (TestAddRemoveHosts.TestAddRemoveHosts) ... === TestName: test_add_remove_host_with_solidfire_plugin_4 | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 4 tests in 3621.836s

OK

TestManagedSystemVMs.py:

test_01_create_system_vms_on_managed_storage (TestManagedSystemVMs.TestManagedSystemVMs) ... === TestName: test_01_create_system_vms_on_managed_storage | Status : SUCCESS ===
ok
test_02_failure_to_create_service_offering_with_customized_iops (TestManagedSystemVMs.TestManagedSystemVMs) ... === TestName: test_02_failure_to_create_service_offering_with_customized_iops | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 2 tests in 2637.630s

OK

TestSnapshots.py:

test_01_create_volume_snapshot_using_sf_snapshot (TestSnapshots.TestSnapshots) ... === TestName: test_01_create_volume_snapshot_using_sf_snapshot | Status : SUCCESS ===
ok
test_02_create_volume_snapshot_using_sf_volume (TestSnapshots.TestSnapshots) ... === TestName: test_02_create_volume_snapshot_using_sf_volume | Status : SUCCESS ===
ok
test_03_create_volume_snapshot_using_sf_volume_and_sf_snapshot (TestSnapshots.TestSnapshots) ... === TestName: test_03_create_volume_snapshot_using_sf_volume_and_sf_snapshot | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 3 tests in 7510.549s

OK

TestVMMigrationWithStorage.py:

test_01_storage_migrate_root_and_data_disks (TestVMMigrationWithStorage.TestVMMigrationWithStorage) ... === TestName: test_01_storage_migrate_root_and_data_disks | Status : SUCCESS ===
ok
test_02_storage_migrate_root_and_data_disks (TestVMMigrationWithStorage.TestVMMigrationWithStorage) ... === TestName: test_02_storage_migrate_root_and_data_disks | Status : SUCCESS ===
ok
test_03_storage_migrate_root_and_data_disks_fail (TestVMMigrationWithStorage.TestVMMigrationWithStorage) ... === TestName: test_03_storage_migrate_root_and_data_disks_fail | Status : SUCCESS ===
ok
test_04_storage_migrate_root_disk_fails (TestVMMigrationWithStorage.TestVMMigrationWithStorage) ... === TestName: test_04_storage_migrate_root_disk_fails | Status : SUCCESS ===
ok
test_05_storage_migrate_data_disk_fails (TestVMMigrationWithStorage.TestVMMigrationWithStorage) ... === TestName: test_05_storage_migrate_data_disk_fails | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 5 tests in 3688.422s

OK

TestVMSnapshots.py:

test_01_take_VM_snapshot (TestVMSnapshots.TestVMSnapshots) ... === TestName: test_01_take_VM_snapshot | Status : SUCCESS ===
ok
test_02_take_VM_snapshot_with_data_disk (TestVMSnapshots.TestVMSnapshots) ... === TestName: test_02_take_VM_snapshot_with_data_disk | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 2 tests in 777.188s

OK

TestVolumes.py (with resigning):

test_00_check_template_cache (TestVolumes.TestVolumes) ... === TestName: test_00_check_template_cache | Status : SUCCESS ===
ok
Attach a volume to a stopped virtual machine, then start VM ... === TestName: test_01_attach_new_volume_to_stopped_VM | Status : SUCCESS ===
ok
Attach, detach, and attach volume to a running VM ... === TestName: test_02_attach_detach_attach_volume | Status : SUCCESS ===
ok
Attach volume to running VM, then reboot. ... === TestName: test_03_attached_volume_reboot_VM | Status : SUCCESS ===
ok
Detach volume from a running VM, then reboot. ... === TestName: test_04_detach_volume_reboot | Status : SUCCESS ===
ok
Detach volume from a stopped VM, then start. ... === TestName: test_05_detach_vol_stopped_VM_start | Status : SUCCESS ===
ok
Attach a volume to a stopped virtual machine, then start VM ... === TestName: test_06_attach_volume_to_stopped_VM | Status : SUCCESS ===
ok
Destroy and expunge VM with attached volume ... === TestName: test_07_destroy_expunge_VM_with_volume | Status : SUCCESS ===
ok
Delete volume that was attached to a VM and is detached now ... === TestName: test_08_delete_volume_was_attached | Status : SUCCESS ===
ok
Attach a data disk to a VM in one account and attach another data disk to a VM in another account ... === TestName: test_09_attach_volumes_multiple_accounts | Status : SUCCESS ===
ok
Attach more than one disk to a VM ... === TestName: test_10_attach_more_than_one_disk_to_VM | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 11 tests in 2393.710s

OK

TestVolumes.py (without resigning) (One issue due to a VM not shutting down properly. I re-ran that test (results posted below these results) and it was successful.):

test_00_check_template_cache (TestVolumes.TestVolumes) ... === TestName: test_00_check_template_cache | Status : SUCCESS ===
ok
Attach a volume to a stopped virtual machine, then start VM ... === TestName: test_01_attach_new_volume_to_stopped_VM | Status : SUCCESS ===
ok
Attach, detach, and attach volume to a running VM ... === TestName: test_02_attach_detach_attach_volume | Status : SUCCESS ===
ok
Attach volume to running VM, then reboot. ... === TestName: test_03_attached_volume_reboot_VM | Status : SUCCESS ===
ok
Detach volume from a running VM, then reboot. ... === TestName: test_04_detach_volume_reboot | Status : SUCCESS ===
ok
Detach volume from a stopped VM, then start. ... === TestName: test_05_detach_vol_stopped_VM_start | Status : FAILED ===
FAIL
Attach a volume to a stopped virtual machine, then start VM ... === TestName: test_06_attach_volume_to_stopped_VM | Status : SUCCESS ===
ok
Destroy and expunge VM with attached volume ... === TestName: test_07_destroy_expunge_VM_with_volume | Status : SUCCESS ===
ok
Delete volume that was attached to a VM and is detached now ... === TestName: test_08_delete_volume_was_attached | Status : SUCCESS ===
ok
Attach a data disk to a VM in one account and attach another data disk to a VM in another account ... === TestName: test_09_attach_volumes_multiple_accounts | Status : SUCCESS ===
ok
Attach more than one disk to a VM ... === TestName: test_10_attach_more_than_one_disk_to_VM | Status : SUCCESS ===
ok

TestVolumes (without resigning) (I re-ran the test that had failed due to a VM not shutting down properly.):

Attach a volume to a stopped virtual machine, then start VM ... === TestName: test_06_attach_volume_to_stopped_VM | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 1 test in 402.412s

OK

**Comment by rhtyd** [comment]
LGTM.

**Comment by jburwell** [comment]
@mike-tutkowski is the SolidFire Python SDK available via pip?  If so, could you please add it to `requirements.txt` in the project root directory?

**Comment by mike-tutkowski** [comment]
@jburwell I just added that to requirements.txt. I also put a link to solidfire-sdk-python 1.1.0.92 in the description of this PR.

**Comment by jburwell** [comment]
@mike-tutkowski excellent -- thanks for adding that configuration bit.  I am LGTM once the Jenkins and Travis complete successfully.

@karuturi @rhtyd are you able to review for a second LGTM?

**Comment by rhtyd** [comment]
LGTM.

**Comment by karuturi** [comment]
we have two LGTMs and test run. I am merging this PR.

**Pull request merged**
