### PR TITLE
format of checksum files convenient for automated checking

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR changes the format of the md5 and sha512 files so they can be used with
```
md5sum --check <releasefile>.md5
```
and
```
sha512sum --check <releasefile>.sha512
```
respectively. 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### How Has This Been Tested?

on the command line

### CODE REVIEW

**Comment by rhtyd** [comment]
@DaanHoogland if you want this in 4.15.1.0 milestone, pl change base branch to 4.15

**Comment by DaanHoogland** [comment]
ok, I didn't intend it to be but I will

**Review by shwstppr — APPROVED** [review]
lgtm

**Comment by DaanHoogland** [comment]
@shwstppr @rhtyd I tested this but as submitter, so do one of you want to verify (or merge)?

**Review by rhtyd — APPROVED** [review]

**Pull request merged**
