### PR TITLE
remove slf4j

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR removes the references to slf4j in pom.xml, since it is no longer used.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@weizhouapache @borisstoyanov @vladimirpetrov I see the `test_vm_life_cycle.py` errors popping up on several PRs (i think only 4.18) is this explained by something environmental, or is should we look for a "guilty" merge?

**Review by rohityadavcloud — APPROVED** [review]
LGTM based on changes, need regression/automated testing

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Review by vishesh92 — COMMENTED** [review]
As per my understanding if slf4j is part of opensaml, it will start getting included in the jar after this change.
I also found this PR https://github.com/apache/cloudstack/pull/6693. Not sure if this is still valid anymore or not.

**Pull request closed without merging**
