### PR TITLE
Fixed Unable to create a domain when networkdomain is mentioned and cleared

### PR DESCRIPTION
**Pull request by FelipeM525**
### Description

This PR fixes [!9623](https://github.com/apache/cloudstack/issues/9623)

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### How Has This Been Tested?
I tested this PR by typing inside the networkdomain field in the Add domain form and then clearing it, which ended up working as expected after the proposed changes.

### CODE REVIEW

**Review by rohityadavcloud — APPROVED** [review]
didn't test, lgtm

**Comment by DaanHoogland** [comment]
loks good @FelipeM525 , can you base of the 4.19 branch?

**Review by DaanHoogland — APPROVED** [review]

**Comment by kiranchavala** [comment]
@blueorangutan ui

**Review by kiranchavala — APPROVED** [review]
LGTM, Tested the fix manually and able to create domain if the network domain entered and cleared

**Pull request merged**
