### PR TITLE
changed variable name to avoid collision in python3

### PR DESCRIPTION
**Pull request by shatoboar**
### Description

This PR...

cloudstack/tools/apidocs/gen_toc.py changed variable name to avoid namecollision with reserved name.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
@blueorangutan package

**Review by shwstppr — APPROVED** [review]

**Comment by DaanHoogland** [comment]
this is going to give some conflicts with other py3 PRs but that's fine :+1:

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Pull request merged**
