### PR TITLE
Register managed user data using POST call from UI (to support user data content > 4096 bytes)

### LINKED ISSUE #8415: Unable to create managed user data, with content > (around)3100 bytes
Failed to register user data, with content > (around)3100 bytes. Error:` User data is too long for an http GET request`

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Compute / User Data
~~~

##### CLOUDSTACK VERSION

~~~
4.18.1.0 
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

Oracle Linux Server 9.0 / KVM Hypervisor

##### SUMMARY

Unable to create managed user data, with content > (around)3100 bytes, as it is being restricted with certain bytes for the http GET request.

Also, the actual user data length is not considered to check the allowed limit.

should allow user data with GET request call?

userdata-error

##### STEPS TO REPRODUCE

- Go to Compute -> User Data section
- Register User Data with content > (around)3100 bytes

##### EXPECTED RESULTS

~~~
Able to register user data content upto 1048576 bytes (based on the setting 'vm.userdata.max.length') with POST request call, and 4096 bytes with GET request call.
~~~

##### ACTUAL RESULTS

~~~
Unable to register user data content > around 3100 bytes, with GET request call.
~~~

### PR DESCRIPTION
**Pull request by sureshanaparti**
### Description

This PR allows to register managed user data using POST call from UI (to support user data content > 4096 bytes).

Partially fixes #8415 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

#### How did you try to break this feature and the system with this change?

Manually tested managed user data (content > 4096 bytes) registration from UI.

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan ui

**Review by shwstppr — COMMENTED** [review]
Code LGTM

**Review by harikrishna-patnala — APPROVED** [review]
LGTM, verified the POST API call

**Review by shwstppr — APPROVED** [review]

**Review by kiranchavala — COMMENTED** [review]
LGTM, tested manually 

Compute> Userdata

Before fix, the call was a GET Call

Screenshot 2024-01-10 at 12 02 55 PM

After fix, the call is a post call 

Screenshot 2024-01-10 at 12 04 36 PM

**Pull request merged**
