### PR TITLE
api, ui: return default ui pagesize as part of capability response

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

listConfigurations is not available for all roles and therefore not fit to use in UI for a generic functionality.
This PR makes default ui pagesize a part for listCapabilities API response to make it available for UI across different role accounts.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [x] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

@rhtyd this is a bit elaborate fix for UI login, pagesize issue. #5430 is a short one.
If this doesn't fit 4.15.2. I can rebase it for main.

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
@blueorangutan ui

**Comment by rhtyd** [comment]
Tested lgtm

**Comment by weizhouapache** [comment]
code lgtm

**Review by weizhouapache — APPROVED** [review]

**Review by nvazquez — APPROVED** [review]
LGTM

**Comment by rhtyd** [comment]
Manually tested; upgraded 4.15.2 RC1 to this PR using pkgs.

**Pull request merged**
