### PR TITLE
Updated upgrade path for 4.19.1.0

### PR DESCRIPTION
**Pull request by sureshanaparti**
### Description

This PR updates last releases upgrade path for 4.19.1.0.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
If there are no db changes, these upgrade path are not needed . it is harmless of course.

**Comment by sureshanaparti** [comment]
> If there are no db changes, these upgrade path are not needed . it is harmless of course.

@weizhouapache we don't have upgrade path from security releases.

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
> > > If there are no db changes, these upgrade path are not needed . it is harmless of course.
> > 
> > 
> > @weizhouapache we don't have upgrade path from security releases.
> 
> @sureshanaparti it is not a problem. cloudstack will calculate the upgrade path based on existing paths. #7959 #8870

ok, thanks @weizhouapache

**Pull request closed without merging**
