### PR TITLE
marvin: fix test_data for parsing failure

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

PR #6512 seems to have broken the `test_data.py`. This PR reverts test_data to the previous commit and adds only the new keys from the PR.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

Verified there are no issues with parsing,

```
shwstppr@shwstppr-ThinkPad:~/lab/shapeblue/cloudstack|fix-test-data
⇒  sudo cp /home/shwstppr/lab/shapeblue/cloudstack/tools/marvin/marvin/config/test_data.py /usr/local/lib/python3.8/dist-packages/marvin/config/test_data.py                               
shwstppr@shwstppr-ThinkPad:~/lab/shapeblue/cloudstack|fix-test-data
⇒  nosetests --with-xunit --xunit-file=results.xml --with-marvin --marvin-config=./setup/dev/advanced.cfg -s -a tags=advanced --hypervisor=Simulator test/integration/smoke/test_vpc_vpn.py

==== Marvin Init Started ====

=== Marvin Parse Config Successful ===

=== Marvin Setting TestData Successful===

==== Log Folder Path: /tmp/MarvinLogs/Jun_07_2023_13_51_19_7V33G4 All logs will be available here ====

=== Marvin Init Logging Successful===

==== Marvin Init Successful ====
^C=== Final results are now copied to: /tmp/MarvinLogs/test_suite_R07TWX ===
```

### CODE REVIEW

**Comment by weizhouapache** [comment]
@shwstppr 
I changed the target branch to 4.18 and closed/reopened to kick the github actions. let's wait for the results.
if it works, we can change the target branch to 4.16 and merge it.

**Review by DaanHoogland — APPROVED** [review]

**Comment by DaanHoogland** [comment]
loks good @shwstppr , but in this case I would really like to see all actions pass (I know the smoketest run doesn't use this, so that makes no sense)

**Review by rohityadavcloud — APPROVED** [review]

**Comment by shwstppr** [comment]
@weizhouapache simulator CI is working fine now. Can we proceed with changing the base branch?

**Comment by weizhouapache** [comment]
> @weizhouapache simulator CI is working fine now. Can we proceed with changing the base branch?

@shwstppr 
that's great. go ahead !

**Review by weizhouapache — APPROVED** [review]

**Pull request merged**
