### PR TITLE
server: fix resource count error when upgrade a vm

### PR DESCRIPTION
**Pull request by ustcweizhou**
## Description

Steps to reproduce the issue
(1) create an account (test)
(2) create a vm with the account (test)
(3) login with admin, and upgrade the vm to another offering
(4) the resource count (cpu,memory) of admin increases, not the account (test).

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DennisKonrad** [comment]
@ustcweizhou I tried to recreate the bug with current master in a testenvironment. Are the any Domains, Projects or something else involved?

Just creating another user with an vm and increasing the VM ressources with admin did not show the bug.
I checked the resourcecount via api with
`update resourcecount domainid=xxxxx account=testuser`
and it showed the right counts.

If I can recreate the bug I can review your PR.

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
> @ustcweizhou I tried to recreate the bug with current master in a testenvironment. Are the any Domains, Projects or something else involved?
> 
> Just creating another user with an vm and increasing the VM ressources with admin did not show the bug.
> I checked the resourcecount via api with
> `update resourcecount domainid=xxxxx account=testuser`
> and it showed the right counts.
> 
> If I can recreate the bug I can review your PR.

@DennisKonrad thanks for testing.
update resource count will recalculate the resource count and update database if count is not same so the value in response is always correct.

However the count is not correct if we use listDomains or listAccounts before updateresourcecount.

**Comment by DaanHoogland** [comment]
thanks @DennisKonrad , can you review,test and/or confirm that this fixes the bug or at least is an improvement? (this need a second 👍 )

**Comment by DennisKonrad** [comment]
@ustcweizhou @DaanHoogland I was able to reproduce the bug (on current master) and this PR fixes the issue. So LGTM

**Pull request merged**
