### PR TITLE
deb: Remove Ubuntu 14.04 LTS support and update DEB dependencies

### PR DESCRIPTION
**Pull request by wido**
Ubuntu 14.04 will go EOL in April 2019. With a new CloudStack
release close to that date we can drop support for this Ubuntu
version and the master branch of CloudStack.

Ubuntu 16.04 (Xenial) and 18.04 (Bionic) both have systemd and
more recent Java versions which make it easier to run the CloudStack
KVM Agent on them.

In addition libvirt and Qemu are more up to date with features
which allow VMs to run better.

Yet to be implemented features in KVM can also leverage the newer
version of Qemu and libvirt without the need of taking older
version of them into account.

Signed-off-by: Wido den Hollander <wido@widodh.nl>

### CODE REVIEW

**Comment by rhtyd** [comment]
@wido @GaborApatiNagy can you start a thread on dev and user ML to see if anybody has any objections?

**Comment by GaborApatiNagy** [comment]
@rhtyd, did you mean @GabrielBrascher

**Comment by wido** [comment]
@rafaelweingartner Good one! Yes, we probably need to update the install/config section for libvirt on Ubuntu.

It is also lacking a section for Ubuntu 18.04 at the moment.

**Comment by rhtyd** [comment]
yes @GaborApatiNagy - sorry was for @GabrielBrascher

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Packaging LGTM, if there are no objections let's merge by end of next week.

**Comment by rafaelweingartner** [comment]
@wido can you check @khos2ow request?
Also, can you create an issue to address the doc updates? Then, if you do not have time to do that now, we at least will not forget it.

**Comment by pdion891** [comment]
+1

**Comment by rhtyd** [comment]
@wido can you also remove the build /rule from Travis yml file?

**Comment by rhtyd** [comment]
Removed 14.04 pkg job from travis, merging this now.

**Pull request merged**
