### PR TITLE
wiremock version 2.11 is incompatible with java 11

### PR DESCRIPTION
**Pull request by DK101010**
With 2.11 wire mock tests hanging and mvn can't execute in thread mode.
Update to 2.27.2(newest version)

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?
Build cs with tests and multithreading in my env.

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
@blueorangutan package

**Review by Pearl1594 — APPROVED** [review]

**Comment by rhtyd** [comment]
No unit tests failures observed in packaging or Travis's job#1

**Pull request merged**
