### PR TITLE
Specify vm snapshot uuid in response over db id in the async job response

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

This PR fixes: https://github.com/apache/cloudstack/issues/6444 , where in the async job response shows the db id for the vm snapshot created rather than its uuid.
Prior fix:
image

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

Post fix:
image

### CODE REVIEW

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by nvazquez — APPROVED** [review]

**Comment by Pearl1594** [comment]
@blueorangutan test

**Review by shwstppr — APPROVED** [review]

**Comment by weizhouapache** [comment]
@blueorangutan test ubuntu22 kvm-ubuntu22

**Comment by weizhouapache** [comment]
@blueorangutan test ubuntu22 kvm-ubuntu22

**Pull request merged**
