### PR TITLE
UI - systemVM - Fix error message `jobid` not found when moving to another host

### PR DESCRIPTION
**Pull request by utchoang**
### Description

Fixes https://github.com/apache/cloudstack/issues/5322

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by utchoang** [comment]
@blueorangutan ui

**Review by davidjumani — APPROVED** [review]
Fixed! Thanks @utchoang

**Review by shwstppr — APPROVED** [review]
Tested on simulator. LGTM!

**Comment by GabrielBrascher** [comment]
@rhtyd @utchoang @shwstppr I've seen this happening when migrating VMs with volume (local storage + KVM) in **4.15**.
Does it make sense to backporting this change to the **4.15** branch as well?
We could get it in time for **4.15.2** then.

**Pull request merged**
