### PR TITLE
[UI] Add project toggle for buckets

### LINKED ISSUE #8422: The Project toggle should be present for Buckets
ISSUE TYPE

Enhancement/Improvement request /UI 

COMPONENT NAME

Component: UI

CLOUDSTACK VERSION

Cloudstack version 4.19 RC 1

SUMMARY

The Project toggle should be present for Buckets

Navigate to 

Storage > Buckets > 

buckets

The project toggle button is present for all the resources and UI sections., we should extend it for buckets  also

### PR DESCRIPTION
**Pull request by sureshanaparti**
### Description

This PR adds project toggle for buckets, in UI.

Fixes #8422 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

Manually verified project toogle in buckets section.

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan ui

**Comment by kiranchavala** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
clgtm, toggle present in UI, toggling in QA triggers the right calls: 
image

**Review by kiranchavala — APPROVED** [review]
LGTM

Project created object store buckets are visible 

Before fix

beforefixbucket


After fix

Screenshot 2024-08-26 at 6 37 50 PM

**Pull request merged**
