### PR TITLE
Add support for zulu-11 in cloudstack 4.14

### PR DESCRIPTION
**Pull request by ustcweizhou**
## Description

Openjdk11 is not supported in Ubunt 16.04, we can use zulu-11 instead.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

Steps to install zulu-11 on Ubuntu 16.04:

sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0xB1998361219BD9C9
sudo echo 'deb http://repos.azulsystems.com/ubuntu stable main' >/etc/apt/sources.list.d/azul.list
sudo apt update
sudo apt install zulu-11 -y

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
how are we going to test this? I suppose you already did @weizhouapache .

**Comment by weizhouapache** [comment]
> how are we going to test this? I suppose you already did @weizhouapache .

@DaanHoogland yes, I have built packages, and install them on ubuntu 16.04 mgt server and hosts. it works well. did not see any issue until now.

**Comment by DaanHoogland** [comment]
great @weizhouapache formaly we need another tester but in view of the code I am not bothered, @andrijapanicsb ?

**Comment by andrijapanicsb** [comment]
@ustcweizhou as you've added zulu-11 as the dependency/to be installed, do you think this should fail if previously the proper repo/key is not added (per your instructions in this PR) ?

**Comment by rhtyd** [comment]
Packaging is okay, we can do a normal install/upgrade on Ubuntu for testing. If you see the change it's simply adding an optional package name if openjdk-11 is not available @DaanHoogland @andrijapanicsb

**Comment by weizhouapache** [comment]
> @ustcweizhou as you've added zulu-11 as the dependency/to be installed, do you think this should fail if previously the proper repo/key is not added (per your instructions in this PR) ?

@andrijapanicsb if other java11 package can be( or has been) installed, cloudstack installation/upgrade will not fail.

**Comment by andrijapanicsb** [comment]
LGTM

**Comment by DaanHoogland** [comment]
just to be sure
@blueorangutan test matrix

**Comment by andrijapanicsb** [comment]
@shwstppr can you please take a look into the failing test if related at all?

thanks

**Comment by DaanHoogland** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by shwstppr** [comment]
@andrijapanicsb failed CKS test is not related as it fails dues availability of ISO url.

**Comment by andrijapanicsb** [comment]
thx!.

VMware tests are restarted, will be merging after it's finished.

**Comment by DaanHoogland** [comment]
@andrijapanicsb the vmware failed because it was build two days ago, before the merge of #3985. I am rebuilding but don't think we should let anything depend on this.

**Comment by andrijapanicsb** [comment]
@DaanHoogland afaik it failed due to name resolution issue, but anyway has been restarted. let's wait for results before merging.

**Comment by DaanHoogland** [comment]
> @DaanHoogland afaik it failed due to name resolution issue, but anyway has been restarted. let's wait for results before merging.

No, i checked the last failed build. but it should be done, about midnight ;)

**Comment by DaanHoogland** [comment]
both trillian and travis have completely barfed. I am sure it has nothing to do with this change :(

**Comment by andrijapanicsb** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by andrijapanicsb** [comment]
@weizhouapache any change to see those failing test what is going on (test_UpdateConfigParamWithScope and test_02_cancel_host_maintenace_with_migration_jobs) ?

We seem to have identical failures on another PR (PR #3984 )

**Comment by weizhouapache** [comment]
@andrijapanicsb can you please ask the authors of related commits to have a look ?

**Comment by andrijapanicsb** [comment]
I'll try - these are tests that are failing in your and @nvazquez PR - which implies a test issue in master or so, if not mistaken?

**Comment by andrijapanicsb** [comment]
@rhtyd @nvazquez @shwstppr @davidjumani can anyone pick up please the failing tests - the same tests are failing in another PR (#3984 ) - which I believe implies those are present in master as well.

**Comment by DaanHoogland** [comment]
@rhtyd @nvazquez @shwstppr @davidjumani @andrijapanicsb @weizhouapache , small hint of which i don't know to what extend it is useful: several merges have been done over the last few weeks. I did notice these failures in 4.13 so it would be resolution of merge conflicts or the actual master commits.

**Comment by weizhouapache** [comment]
the failures with test_privategw_acl.py have been resolved in 4.14, you can ignore them, or backport the commit to 4.13

**Comment by andrijapanicsb** [comment]
As we have identical test failures on this one as on another PR #3984 - and this one just adds the dependency, I will merge it based on LGTMs/Approvals and the regression tests results.

Will hunt/fix those tests in that other PR and confirm it's all good.

**Pull request merged**
