### PR TITLE
Ensure cloudstack-usage debian package is installed after cloudstack-management

### PR DESCRIPTION
**Pull request by benj-n**
### Description

This PR ensures cloudstack-usage debian package is installed after cloudstack-management.

Post-install script in cloudstack-usage needs 'cloud' user to be present. 'Cloud' user is created in cloudstack-management post-install script.

Fixes: #7507 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [X] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@benj-n 

Normally usage server is deployed on management server host, however, it is not mandatory.

**Comment by weizhouapache** [comment]
> @weizhouapache
> 
> I can't see how this relates to the issue. Mandatory or not, IF usage is installed, it should be installed after management.

@benj-n 
I mean cloudstack-usage does not depend on cloudstack-management. You can install cloudstack-usage on a server where cloudstack-management is not installed.

**Comment by benj-n** [comment]
@weizhouapache 
I get it. Then the management of the 'cloud' user must be included in the post-install of cloudstack-usage package ...

**Comment by weizhouapache** [comment]
@DaanHoogland 
can you review ? this is related to #6825

**Comment by DaanHoogland** [comment]
> @weizhouapache I get it. Then the management of the 'cloud' user must be included in the post-install of cloudstack-usage package ...

Yes @benj-n , that is true. I wonder why this would work on other platforms without this. This needs to be fixed in the install procedure for the usage server itself and not by installing the management server. Probably an oversight.

**Comment by weizhouapache** [comment]
> > @weizhouapache I get it. Then the management of the 'cloud' user must be included in the post-install of cloudstack-usage package ...
> 
> Yes @benj-n , that is true. I wonder why this would work on other platforms without this. This needs to be fixed in the install procedure for the usage server itself and not by installing the management server. Probably an oversight.

agree.

@benj-n 
will you make changes on it ?
This need to be fix ed in 4.18.1.0. can you please rebase with 4.18 branch ?

**Comment by andrijapanicsb** [comment]
@blueorangutan LLpackage

**Comment by andrijapanicsb** [comment]
(testing, not really packaging)

**Comment by benj-n** [comment]
This PR should be superseded by https://github.com/apache/cloudstack/pull/7559

**Comment by DaanHoogland** [comment]
@benj-n can we close this one?

**Pull request closed without merging**
