### PR TITLE
potential null pointer in condition; AYAI9l8k5Irk9_td-cXb

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR fixes a sonar finding: https://sonarcloud.io/project/issues?issues=AYAI9l8k5Irk9_td-cXb&open=AYAI9l8k5Irk9_td-cXb&id=apachecloudstack

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### CODE REVIEW

**Review by nvazquez — APPROVED** [review]

**Comment by nvazquez** [comment]
@DaanHoogland can you rebase and target it to the 4.16 branch?

**Comment by DaanHoogland** [comment]
done @nvazquez

**Comment by nvazquez** [comment]
Thanks @DaanHoogland 
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by DaanHoogland** [comment]
@rohityadavcloud , before we merge, how/where do we see the sonar score improve? ;)

**Comment by GabrielBrascher** [comment]
LGTM

**Comment by rohityadavcloud** [comment]
@DaanHoogland let me explore how we can setup per-PR sonar build/analysis runs. For now, you'll need to build and upload the quality stats (a jacoco xml or csv file). I can do that manually once the PR passes, alt you can create a dummy org for yourself and upload manually.

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
@DaanHoogland ran another build/run for the sonar/jacoco analysis, you can check the issue in say about an hour if it shows up as resolved on the dashboard. I'll setup a daily run on main branch in Jenkins (soon) so sonar gets updated, for per-PR integration it requires setting up a Github secret - which I'll explore if it's at all possible.

**Comment by DaanHoogland** [comment]
great, it shows as 'closed' now

**Pull request merged**
