### PR TITLE
Allow direct download templates from IPv6 host address. 

### LINKED ISSUE #3047: Direct Download with IPv6 only fails
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
KVM Agent
~~~

##### CLOUDSTACK VERSION
~~~
master / 4.12
~~~

##### CONFIGURATION
Hypervisors are IPv6-only without a default IPv4 route to the internet.

##### OS / ENVIRONMENT
Ubuntu 18.04
OpenJDK 1.8

~~~
root@n03:~# java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1ubuntu0.18.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
root@n03:~#
~~~

##### SUMMARY
When a hypervisor has no IPv4 default route Direct Download of a template failes.

~~~
2018-11-22 14:10:50,281 DEBUG [commons.httpclient.MultiThreadedHttpConnectionManager] (agentRequest-Handler-4:null) (logid:022777d5) HttpConnectionManager.getConnection:  config = HostConfiguration[host=http://packer-templates.o.auroraobjects.eu], timeout = 0
2018-11-22 14:10:50,282 DEBUG [commons.httpclient.MultiThreadedHttpConnectionManager] (agentRequest-Handler-4:null) (logid:022777d5) Allocating new connection, hostConfig=HostConfiguration[host=http://packer-templates.o.auroraobjects.eu]
2018-11-22 14:10:50,287 DEBUG [commons.httpclient.HttpConnection] (agentRequest-Handler-4:null) (logid:022777d5) Open connection to packer-templates.o.auroraobjects.eu:80
2018-11-22 14:10:50,322 DEBUG [commons.httpclient.HttpMethodDirector] (agentRequest-Handler-4:null) (logid:022777d5) Closing the connection.
2018-11-22 14:10:50,323 INFO  [commons.httpclient.HttpMethodDirector] (agentRequest-Handler-4:null) (logid:022777d5) I/O exception (java.net.ConnectException) caught when processing request: Network is unreachable (connect failed)
2018-11-22 14:10:50,323 DEBUG [commons.httpclient.HttpMethodDirector] (agentRequest-Handler-4:null) (logid:022777d5) Network is unreachable (connect failed)
~~~

~~~
root@n03:~# ip r
169.254.0.0/16 dev cloud0 proto kernel scope link src 169.254.0.1 
172.16.0.0/24 dev cloudbr1 proto kernel scope link src 172.16.0.13 
192.168.0.0/24 dev vlan300 proto kernel scope link src 192.168.0.13 
192.168.122.0/24 dev virbr0 proto kernel scope link src 192.168.122.1 linkdown 
239.0.7.208 dev vlan300 scope link 
root@n03:~# 
~~~

~~~
root@n03:~# ip -6 r
2a00:f10:114::/64 dev enp4s0f1 proto ra metric 1024 pref medium
2a00:f10:114:2000::/64 dev brvx-2000 proto kernel metric 256 expires 2591725sec pref medium
default via fe80::a236:9fff:fe0d:abbe dev enp4s0f1 proto ra metric 1024 mtu 9000 pref medium
default via fe80::9889:27ff:fe04:896e dev brvx-2000 proto ra metric 1024 expires 1525sec hoplimit 64 pref medium
root@n03:~#
~~~

The hypervisor is IPv6 capable and the URL is reachable over IPv6 as well, but the hypervisor / KVM Agent fails to download it.

### PR DESCRIPTION
**Pull request by sureshanaparti**
### Description

This PR, extends from #5826, allows only direct download templates from IPv6 host address.

Fixes #3047 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@sureshanaparti I don't see a difference between this and #5826. why recreate the PR?

**Comment by sureshanaparti** [comment]
> @sureshanaparti I don't see a difference between this and #5826. why recreate the PR?

forgot to push the commit, check now @DaanHoogland

**Review by DaanHoogland — APPROVED** [review]
cltgm

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Review by shwstppr — APPROVED** [review]
LGTM, already tested these changes in an env having IPv6 enabled host. Direct Download template registration and thereafter VM deployment worked fine
https://github.com/apache/cloudstack/pull/5826#issuecomment-1020929718

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Review by GabrielBrascher — APPROVED** [review]
Code LGTM

**Pull request merged**
