### PR TITLE
UI: Display Firewall, LB and Port Forwading rules tab for CKS clusters deployed on isolated networks

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

This PR fixes a small UI regression to display FW, PF and LB tabs for CKS on isolated networks

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### Screenshots (if appropriate):
Before Fix:
image

After fix:
image

### CODE REVIEW

**Review by nvazquez — APPROVED** [review]
Thanks @Pearl1594 - LGTM

**Review by weizhouapache — APPROVED** [review]
code lgtm

@Pearl1594 
can you rebase with 4.18 branch (or 4.19) ?

**Comment by Pearl1594** [comment]
Done @weizhouapache

**Comment by weizhouapache** [comment]
@blueorangutan ui

**Pull request merged**
