### PR TITLE
ui: Prevent reset of port-forward rules on cancelling a form

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

Fixes https://github.com/apache/cloudstack/issues/4974
This PR prevents port forward rule details filled, from being reset on cancelling the operation

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [X] Trivial

### How Has This Been Tested?
Populated the details for adding port forward rules and cancelled the operation

### CODE REVIEW

**Comment by Pearl1594** [comment]
@blueorangutan ui

**Comment by andrijapanicsb** [comment]
Ping @Pearl1594 - thx for a quick fix - it is indeed fixed, but I can see another issue, which I'm NOT sure is related, but might be - can you please check the video: http://somup.com/crfvr1Fx7w

**Comment by Pearl1594** [comment]
@blueorangutan ui

**Comment by Pearl1594** [comment]
> Ping @Pearl1594 - thx for a quick fix - it is indeed fixed, but I can see another issue, which I'm NOT sure is related, but might be - can you please check the video: http://somup.com/crfvr1Fx7w

@andrijapanicsb Thanks for pointing it out, I've addressed the issue mentioned.

**Review by shwstppr — APPROVED** [review]
LGTM

**Review by utchoang — APPROVED** [review]

**Pull request merged**
