### PR TITLE
CLOUDSTACK-9697: Better error message in UI if user tries to shrink VM ROOT Volume size

### PR DESCRIPTION
**Pull request by rashmidixit**
Skip the API call altogether if the UI detects this case and throw a more user friendly message

Conflicts:
	client/WEB-INF/classes/resources/messages.properties
	client/WEB-INF/classes/resources/messages_ja_JP.properties
	client/WEB-INF/classes/resources/messages_zh_CN.properties
	ui/dictionary2.jsp

### CODE REVIEW

**Comment by sadhugit** [comment]
tested on my setup and Looks good to me.
Need to handle on API side  so please update the Bug description  by adding UI only

**Comment by rashmidixit** [comment]
@sadhugit I have updated the bug description based on your comments.

**Comment by ramkatru** [comment]
tag:mergeready

**Comment by karuturi** [comment]
@rashmidixit Can you rebase this to master? master doesnt have messages.properties

**Comment by rashmidixit** [comment]
Need to reopen same PR on the master branch. Will create a new PR for the same.

**Pull request closed without merging**
