### PR TITLE
CLOUDSTACK-8979: add virtio support for CentOS/RHEL 7 on KVM

### PR DESCRIPTION
**Pull request by ustcweizhou**
@borisroman @NuxRo could you test it?

### CODE REVIEW

**Comment by ustcweizhou** [comment]
(1) make the change on mysql
(2) create a template (CentOS 7) if you do not have one.
(3) create an instance with the CentOS 7 template on KVM.
(4) check the dumpxml of instance, to see if it uses virtio on disk/network

**Comment by borisroman** [comment]
@ustcweizhou I confirmed it working. Could you please force push your last commit so Jenkins will run again?

**Comment by borisroman** [comment]
Ping @remibergsma @wilderrodrigues @karuturi @bhaisaab

**Comment by borisroman** [comment]
@remibergsma All green now! LGTM :+1:

**Pull request merged**
