### PR TITLE
Remove UserVmDetailsDao duplicate field

### PR DESCRIPTION
**Pull request by dhlaluku**
## Description

Removing UserVmDetailsDao duplicate field;
Found the following repeated field in the UserVmManagerImpl class
    @Inject
    private UserVmDetailsDao _vmDetailsDao;
    @Inject
    private UserVmDetailsDao _uservmDetailsDao;

Refactored to a single field;
    @Inject
    private UserVmDetailsDao userVmDetailsDao;

Similar to this PR: https://github.com/apache/cloudstack/pull/2750/files

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

## Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
Testing
- [ ] I have added tests to cover my changes.
- [ ] All relevant new and existing integration tests have passed.
- [ ] A full integration testsuite with all test that can run on my environment has passed.

### CODE REVIEW

**Comment by dhlaluku** [comment]
@blueorangutan package

**Comment by dhlaluku** [comment]
@blueorangutan test

**Comment by dhlaluku** [comment]
@DaanHoogland the failures are known and need to be addressed in master. I will have a look and see if I can provide fixes for some of them starting with the test_usage.py.

**Comment by rhtyd** [comment]
LGTM, failures not related to the changes in the PR. Merging.

**Pull request merged**
