### PR TITLE
Show network metrics for System VMs

### PR DESCRIPTION
**Pull request by GaOrtiga**
### Description

The Network metrics segment of the UI displays the amount of data downloaded/uploaded by a specific instance. However, when the instance is a system VM (VR, CPVM or SSVM), this segment is not shown.

This behaviour has been fixed, allowing network metrics for System VMs to be viewed via UI.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### Screenshots (if appropriate):

<details><summary>Before</summary>

Console Proxy:
consoleProxyBefore

Secondary Storage:
SecondaryStorageBefore

Virtual Router:
routerBefore

</details>

<details><summary>After</summary>

Console Proxy:
consoleProxyAfter

Secondary Storage:
secondaryStorageAfter

Virtual Router:
routerAfter

</details>

### CODE REVIEW

**Comment by GaOrtiga** [comment]
@DaanHoogland @rohityadavcloud @GutoVeronezi @weizhouapache  @sureshanaparti 

Could someone review this?

**Review by weizhouapache — APPROVED** [review]
code lgtm

perfect screenshots

**Comment by DaanHoogland** [comment]
@blueorangutan ui

**Review by sureshanaparti — APPROVED** [review]
lgtm, able to see network metrics for system vms.

**Pull request merged**
