### PR TITLE
vr: fix vr in unknown state (more)

### PR DESCRIPTION
**Pull request by ustcweizhou**
## Description

This fixes similar issue with #3465 

Meanwhile change log level of CsHelper.execute2 from DEBUG to INFO and fix some typo

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by DaanHoogland** [comment]
code lgtm but it is only an improvement, is that right @weizhouapache or does it really solve a bug?

**Comment by weizhouapache** [comment]
@DaanHoogland I believe there are some issues caused by this when vpc has more than 10 tiers.
This change in STATE_COMMANDS is similar as #3465 which should be a bug fix.

The change on log level can be regarded as an improvement.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
> @DaanHoogland I believe there are some issues caused by this when vpc has more than 10 tiers.

grep eth10 or -eth11 etc, got it thanks @weizhouapache

**Comment by rhtyd** [comment]
@blueorangutan test

**Pull request merged**
