### PR TITLE
packaging: install tzdata-java on centos7/centos8

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

When install cloudstack on latest rocky8 server with java-11-openjdk-11.0.20.0.8-2.el8.x86_64, management server cannot be started due to error
```
Caused by: java.lang.Error: java.io.FileNotFoundException: /usr/lib/jvm/java-11-openjdk-11.0.20.0.8-2.el8.x86_64/lib/tzdb.dat (No such file or directory)
```

It is because the package `tzdata-java` is not automatically installed. (It was installed with java-11-openjdk-11.0.18.0.10-2.el8_7.x86_64, but not with latest java-11-openjdk-11.0.20.0.8-2.el8.x86_64)

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [x] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Comment by weizhouapache** [comment]
@blueorangutan alma8 kvm-alma8

**Review by rohityadavcloud — APPROVED** [review]

**Comment by weizhouapache** [comment]
@blueorangutan alma8 kvm-alma8

**Comment by weizhouapache** [comment]
@blueorangutan test alma8 kvm-alma8

**Review by DaanHoogland — APPROVED** [review]

**Review by harikrishna-patnala — APPROVED** [review]
Code LGTM

**Comment by weizhouapache** [comment]
test failures are not related to the PR. 
Merging

**Pull request merged**
