### PR TITLE
[wip][4.6] CLOUDSTACK-8994 Add logging for the password server.

### PR DESCRIPTION
**Pull request by borisroman**
Activity of the password server is now logged.

```
nosetests --with-marvin --marvin-config=/data/shared/marvin/mct-zone1-kvm1-basic.cfg -s -a tags=basic,required_hardware=false smoke/test_vm_life_cycle.py
```
```
==== Marvin Init Started ====

=== Marvin Parse Config Successful ===

=== Marvin Setting TestData Successful===

==== Log Folder Path: /tmp//MarvinLogs//Oct_26_2015_17_55_20_4DHFOS. All logs will be available here ====

=== Marvin Init Logging Successful===

==== Marvin Init Successful ====
=== TestName: test_deploy_vm | Status : SUCCESS ===

=== TestName: test_deploy_vm_multiple | Status : SUCCESS ===

=== TestName: test_01_stop_vm | Status : SUCCESS ===

=== TestName: test_02_start_vm | Status : SUCCESS ===

=== TestName: test_03_reboot_vm | Status : SUCCESS ===

=== TestName: test_06_destroy_vm | Status : SUCCESS ===

=== TestName: test_07_restore_vm | Status : SUCCESS ===

=== TestName: test_09_expunge_vm | Status : SUCCESS ===

===final results are now copied to: /tmp//MarvinLogs/test_vm_life_cycle_2TE6D4===
```

### CODE REVIEW

**Comment by karuturi** [comment]
LGTM. 
All the tests in BVT tests pass. (I see some failures in scalevm and deployvm from iso tests but, they are environment issues)

**Comment by karuturi** [comment]
@borisroman 
I started seeing below error messages on console and VR doesnt start. Is it related to this change?

```
[  480.108811] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  480.108966] INFO: task python:2739 blocked for more than 120 seconds.
[  480.108975] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  480.109135] INFO: task python:2741 blocked for more than 120 seconds.
[  480.109144] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  480.109308] INFO: task python:2747 blocked for more than 120 seconds.
[  480.109317] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  480.109451] INFO: task python:2748 blocked for more than 120 seconds.
[  480.109461] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  480.109627] INFO: task python:2752 blocked for more than 120 seconds.
[  480.109637] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
```

**Comment by terbolous** [comment]
How does this impact logrotating?

**Comment by borisroman** [comment]
@terbolous It doesn't effect log-rotating at all. This just let's the password_server_ip.py logs to be written to /var/log/cloud.log instead of /dev/nul

**Comment by borisroman** [comment]
@karuturi I'll check again.

**Comment by remibergsma** [comment]
@borisroman Isn't there already another process logging to `/var/log/cloud.log` ? Will this work properly if multiple processes write to it at the same time? Haven't verified it yet, so might be wrong but just wanted to check.

**Comment by borisroman** [comment]
@remibergsma I think it might be the problem, which also caused my vr to not restart... Looking into it

**Comment by remibergsma** [comment]
@borisroman FYI: I already started a test on this branch (which I rebased myself first) and it doesn't look too good:

```
nosetests --with-marvin --marvin-config=${marvinCfg} -s -a tags=advanced,required_hardware=true \
component/test_vpc_redundant.py \
component/test_routers_iptables_default_policy.py \
component/test_routers_network_ops.py \
component/test_vpc_router_nics.py \
smoke/test_loadbalance.py \
smoke/test_internal_lb.py \
smoke/test_ssvm.py \
smoke/test_network.py

```

Result:

```
Create a redundant VPC with two networks with two VMs in each network ... === TestName: test_01_create_redundant_VPC_2tiers_4VMs_4IPs_4PF_ACL | Status : SUCCESS ===
ok
Create a redundant VPC with two networks with two VMs in each network and check default routes ... === TestName: test_02_redundant_VPC_default_routes | Status : SUCCESS ===
ok
Test iptables default INPUT/FORWARD policy on RouterVM ... === TestName: test_02_routervm_iptables_policies | Status : EXCEPTION ===
ERROR
Test iptables default INPUT/FORWARD policies on VPC router ... === TestName: test_01_single_VPC_iptables_policies | Status : SUCCESS ===
ok
=== TestName: test_01_single_VPC_iptables_policies | Status : EXCEPTION ===
ERROR
Test redundant router internals ... === TestName: test_RVR_Network_FW_PF_SSH_default_routes | Status : EXCEPTION ===
ERROR
=== TestName: test_RVR_Network_FW_PF_SSH_default_routes | Status : EXCEPTION ===
ERROR
Create a VPC with two networks with one VM in each network and test nics after destroy ... === TestName: test_01_VPC_nics_after_destroy | Status : SUCCESS ===
ok
Create a VPC with two networks with one VM in each network and test default routes ... === TestName: test_02_VPC_default_routes | Status : SUCCESS ===
ok
=== TestName: test_02_VPC_default_routes | Status : EXCEPTION ===
ERROR
Test to verify access to loadbalancer haproxy admin stats page ... === TestName: test02_internallb_haproxy_stats_on_all_interfaces | Status : SUCCESS ===
ok
Test create, assign, remove of an Internal LB with roundrobin http traffic to 3 vm's ... === TestName: test_01_internallb_roundrobin_1VPC_3VM_HTTP_port80 | Status : SUCCESS ===
ok
Test SSVM Internals ... === TestName: test_03_ssvm_internals | Status : SUCCESS ===
ok
Test CPVM Internals ... === TestName: test_04_cpvm_internals | Status : SUCCESS ===
ok
Test stop SSVM ... === TestName: test_05_stop_ssvm | Status : SUCCESS ===
ok
Test stop CPVM ... === TestName: test_06_stop_cpvm | Status : SUCCESS ===
ok
Test reboot SSVM ... === TestName: test_07_reboot_ssvm | Status : SUCCESS ===
ok
Test reboot CPVM ... === TestName: test_08_reboot_cpvm | Status : SUCCESS ===
ok
Test destroy SSVM ... === TestName: test_09_destroy_ssvm | Status : SUCCESS ===
ok
Test destroy CPVM ... === TestName: test_10_destroy_cpvm | Status : SUCCESS ===
ok
=== TestName: test_10_destroy_cpvm | Status : EXCEPTION ===
ERROR
Test for reboot router ... === TestName: test_reboot_router | Status : EXCEPTION ===
ERROR
=== TestName: test_reboot_router | Status : EXCEPTION ===
ERROR
----------------------------------------------------------------------
Ran 18 tests in 33683.484s

FAILED (errors=8)
```

The 3 errors at the bottom are due to CLOUDSTACK-8991 and unrelated to this PR.

And:

```
nosetests --with-marvin --marvin-config=${marvinCfg} -s -a tags=advanced,required_hardware=false \
smoke/test_routers.py \
smoke/test_network_acl.py \
smoke/test_privategw_acl.py \
smoke/test_reset_vm_on_reboot.py \
smoke/test_vm_life_cycle.py \
smoke/test_vpc_vpn.py \
smoke/test_service_offerings.py \
component/test_vpc_offerings.py \
component/test_vpc_routers.py
```

Result:

```
=== TestName: None | Status : EXCEPTION ===
ERROR
test_privategw_acl (integration.smoke.test_privategw_acl.TestPrivateGwACL) ... === TestName: test_privategw_acl | Status : EXCEPTION ===
ERROR
=== TestName: test_privategw_acl | Status : EXCEPTION ===
ERROR
=== TestName: test_privategw_acl | Status : EXCEPTION ===
ERROR
=== TestName: test_privategw_acl | Status : EXCEPTION ===
ERROR
Test Remote Access VPN in VPC ... === TestName: test_vpc_remote_access_vpn | Status : SUCCESS ===
ok
Test VPN in VPC ... === TestName: test_vpc_site2site_vpn | Status : SUCCESS ===
ok
Test to create service offering ... === TestName: test_01_create_service_offering | Status : SUCCESS ===
ok
=== TestName: test_01_create_service_offering | Status : EXCEPTION ===
ERROR
Test for delete account ... === TestName: test_delete_account | Status : EXCEPTION ===
ERROR
Test for Associate/Disassociate public IP address for admin account ... === TestName: test_public_ip_admin_account | Status : SUCCESS ===
ok
Test for Associate/Disassociate public IP address for user account ... === TestName: test_public_ip_user_account | Status : SUCCESS ===
ok
Test for release public IP address ... === TestName: test_releaseIP | Status : EXCEPTION ===
ERROR
Test create VPC offering ... === TestName: test_01_create_vpc_offering | Status : SUCCESS ===
ok
Test VPC offering without load balancing service ... === TestName: test_03_vpc_off_without_lb | Status : EXCEPTION ===
ERROR
=== TestName: test_03_vpc_off_without_lb | Status : EXCEPTION ===
ERROR
Test VPC offering without static NAT service ... === TestName: test_04_vpc_off_without_static_nat | Status : EXCEPTION ===
ERROR
=== TestName: test_04_vpc_off_without_static_nat | Status : EXCEPTION ===
ERROR
Test VPC offering without port forwarding service ... === TestName: test_05_vpc_off_without_pf | Status : EXCEPTION ===
ERROR
Test VPC offering with invalid services ... === TestName: test_06_vpc_off_invalid_services | Status : SUCCESS ===
ok
Test update VPC offering ... === TestName: test_07_update_vpc_off | Status : EXCEPTION ===
ERROR
Test list VPC offering ... === TestName: test_08_list_vpc_off | Status : SUCCESS ===
ok
test_09_create_redundant_vpc_offering (integration.component.test_vpc_offerings.TestVPCOffering) ... === TestName: test_09_create_redundant_vpc_offering | Status : EXCEPTION ===
ERROR
=== TestName: test_09_create_redundant_vpc_offering | Status : EXCEPTION ===
ERROR
=== TestName: test_09_create_redundant_vpc_offering | Status : EXCEPTION ===
ERROR
----------------------------------------------------------------------
Ran 16 tests in 36989.192s

FAILED (errors=17)
```

The routers fail to deploy. Lots of stuff like `Failed to create VPC`.

**Comment by miguelaferreira** [comment]
@karuturi How is it possible that "All the tests in BVT tests pass on xenserver 6.5 host" and "I started seeing below error messages on console and VR doesnt start"?

**Comment by borisroman** [comment]
@remibergsma Thanks for the effort. This was what also caused my vr to not reboot... Knowing that I closed the PR yesterday. Will look into it  and test more properly.

**Comment by karuturi** [comment]
@miguelaferreira All the tests did pass except for some template related failures due to download template timeout. But, when I manually created a new network on the same setup to test some other stuff, the router never came up. I dont have the setup now to further investigate. But, I will make sure to post the test results next time. (In the current setup I have, it runs tests in parallel, its tiresome to go to individual test output dirs and copy the output because of which I tend to skip pasting the results except for failures)

**Comment by miguelaferreira** [comment]
@karuturi I would be very much interested in seeing the results of the tests that have passed in that environment were you could not get a router to come up. I assume many tests do require a router, so I wonder how did they pass. Please do ping me (us) if you have some results to share, I'll be happy to try to figure it out with you.

**Pull request closed without merging**
