### PR TITLE
api: Fix listing of Public IPs(Free & Reserved) with listall=true & projectid=-1

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

This PR fixes the issue faced when listing free & reserved  public IPs with listall=true & projectId = -1:
image

image

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [X] Trivial

### CODE REVIEW

**Comment by Pearl1594** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]

**Comment by nvazquez** [comment]
@blueorangutan test

**Review by nvazquez — APPROVED** [review]

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@Pearl1594 
this PR has changes on [AccountManagerImpl.java](https://github.com/apache/cloudstack/pull/6186/files#diff-fdd46eb6e71ed13aa5bc82ca928751e334a0e743c1142a0201a7cba7986882ff), which might have big impact (probably not).

I've found another issue listing Reserved IP in projects. this PR does not fix it.
I will create a PR to fix both issues.

**Pull request closed without merging**
