### PR TITLE
Fix `updateTemplatePermission` when the UI is set to a language other than English

### PR DESCRIPTION
**Pull request by lucas-a-martins**
### Description

When the UI is set to a language other than English, the update template permissions feature throws an exception. This PR fixes this behavior to allow updating template permissions when using the UI in any language.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### Screenshots (if appropriate):

<details>
<summary>Before changes</summary>

template-permission-before

</details>

<details>
<summary>After changes</summary>

template-permission-after

</details>

### How Has This Been Tested?

Using a private template, I tested the `Add`, `Remove`, and `Reset` permission operations in a UI set to several non-English languages.

### CODE REVIEW

**Review by FelipeM525 — APPROVED** [review]
LGTM! tested in a local environment
<details><summary>Before</summary>

image
</details>

<details><summary>After</summary>

image

</details>

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
tried in qa;  Dutch and Protugese, both work.

**Pull request merged**
