### PR TITLE
server: fix addCluster for vmware, others

### PR DESCRIPTION
**Pull request by shwstppr**
### Description
With 87ddc76, value column in cloud.cluster_details has been made non-nullable.
While adding a cluster (especially VMware), addCluster API can be called without username password. Username and password are updated in cluster details entry later after successful discovery.
This PR stores an empty string instead of a null value when the initial cluster entry is made in the DB.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?
Screenshot from 2021-09-08 16-59-12

Error in logs:
```
2021-09-08 11:26:26,300 DEBUG [c.c.a.ApiServlet] (qtp769798433-19:ctx-3ea4e9da) (logid:d2be3d41) ===START===  172.16.250.2 -- POST  command=addCluster&response=json
2021-09-08 11:26:26,304 DEBUG [c.c.a.ApiServer] (qtp769798433-19:ctx-3ea4e9da ctx-51d8fe53) (logid:d2be3d41) CIDRs from which account 'Acct[202665fc-0bda-11ec-a29c-1e0094000118-admin] -- Account {"id": 2, "name": "admin", "uuid": "202665fc-0bda-11ec-a29c-1e0094000118"}' is allowed to perform API calls: 0.0.0.0/0,::/0
2021-09-08 11:26:26,319 DEBUG [c.c.u.d.T.Transaction] (qtp769798433-19:ctx-3ea4e9da ctx-51d8fe53) (logid:d2be3d41) Rolling back the transaction: Time = 1 Name =  qtp769798433-19; called by -TransactionLegacy.rollback:888-TransactionLegacy.removeUpTo:831-TransactionLegacy.close:655-TransactionContextInterceptor.invoke:36-ReflectiveMethodInvocation.proceed:175-ExposeInvocationInterceptor.invoke:97-ReflectiveMethodInvocation.proceed:186-JdkDynamicAopProxy.invoke:215-$Proxy46.persist:-1-ResourceManagerImpl.discoverCluster:550-NativeMethodAccessorImpl.invoke0:-2-NativeMethodAccessorImpl.invoke:62
2021-09-08 11:26:26,320 ERROR [c.c.a.ApiServer] (qtp769798433-19:ctx-3ea4e9da ctx-51d8fe53) (logid:d2be3d41) unhandled exception executing api command: [Ljava.lang.String;@49908fbd
com.cloud.utils.exception.CloudRuntimeException: DB Exception on: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO cluster_details (cluster_details.cluster_id, cluster_details.name, cluster_details.value) VALUES (8, _binary'password', null)
	at com.cloud.utils.db.GenericDaoBase.persist(GenericDaoBase.java:1450)
	at com.cloud.dc.ClusterDetailsDaoImpl.persist(ClusterDetailsDaoImpl.java:111)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at com.cloud.utils.db.TransactionContextInterceptor.invoke(TransactionContextInterceptor.java:34)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy46.persist(Unknown Source)
	at com.cloud.resource.ResourceManagerImpl.discoverCluster(ResourceManagerImpl.java:550)
```

After change - **addCluster successful**:
Screenshot from 2021-09-08 17-36-57

Correct cluster details after successful addition:
Screenshot from 2021-09-08 17-40-32

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Does it affect 4.15 too @shwstppr or just main?

**Comment by shwstppr** [comment]
@rhtyd only main, as 87ddc76 from PR #5274 was merged in main

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-67u3

**Review by rhtyd — APPROVED** [review]

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Review by nvazquez — APPROVED** [review]

**Comment by nvazquez** [comment]
@blueorangutan test matrix

**Pull request merged**
