### PR TITLE
Fix SQL query for uuid wrong format

### PR DESCRIPTION
**Pull request by nvazquez**
### Description

Fixes: #6652 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [x] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
@nvazquez the question is - could it break on vmware too?
@blueorangutan package

**Comment by nvazquez** [comment]
@rohityadavcloud the original fix was for Vmware, in some cases datastore clusters seem to get the UUID in a wrong format, but needs checking for other cases in Vmware in which the same thing can happen cc.@DK101010. In my testing of the original fix I was using Vmware but didn't get pools in the wrong uuid format, and this logic was not executed

**Comment by nvazquez** [comment]
Looks like in the case of Vmware + SolidFire it may be using an IQN as the UUID and this could also affect it
image

**Comment by shwstppr** [comment]
@nvazquez cc @DK101010 is it possible to filter storage pools based on `pool_type` as #5382 mentions the issue is with datastore cluster on VMware?

**Comment by DK101010** [comment]
Hi @shwstppr @nvazquez  
yes it is possible, pool_type = "DatastoreCluster". 

We discussed at the time in which format uuids should be stored in the database and that it should always be the same format. That's why we created the sql back then.

Therefore, the code for the storage plugin and local storage should be adapted and not the uuids in the database should be used with the wrong format or am I missing something?

**Comment by nvazquez** [comment]
Thanks @DK101010 - I've updated the PR to restrict the SQL to datastore cluster only. 
@blueorangutan package

**Review by slavkap — APPROVED** [review]
Code LGTM

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
> Hi @shwstppr @nvazquez yes it is possible, pool_type = "DatastoreCluster".
> 
> We discussed at the time in which format uuids should be stored in the database and that it should always be the same format. That's why we created the sql back then.
> 
> Therefore, the code for the storage plugin and local storage should be adapted and not the uuids in the database should be used with the wrong format or am I missing something?

@DK101010 I guess it is not just the code for the storage plugins and local storage. Like @slavkap pointed out in her issue it could be manually set or could be already set and used in production env where upgrades would fail. Using pool_type filter would be safer for now. Can you please review the changes?

**Review by shwstppr — APPROVED** [review]
Code LGTM

**Comment by DaanHoogland** [comment]
would this be particular to the concept of "DataCluster" or could there be implementations of the concept that handle things differenty @nvazquez @shwstppr ? (cc @harikrishna-patnala )

Reason for my question: it seems vmware specific but I don´t see a check for that in the code.

**Comment by DaanHoogland** [comment]
> @DaanHoogland yes it seems particular to the Vmware implementation but its the only supported for the type 'DatastoreCluster'

clear, i´d say it is maybe a bit early to amend this for a hypothetical future enhancement, just wondering. CLTGM

**Comment by DK101010** [comment]
I am a little confused. 

I developed this because all storage (in VMware) uuids were stored with separators. But catastore cluster was stored without separator. 
It was said that all uuids are stored with separator in the database and that therefore the datastore cluster uuids are wrong.
Now it sounds like there is no structure to the storage uuids.

@shwstppr
if DatastoreClusters is only supported for VMware then code looks good. 
If not, then I would add **hypervisor= "VMware"**.

**Pull request merged**
