### PR TITLE
UI: Add domain and account fields to Register/Upload Template/ISO view

### PR DESCRIPTION
**Pull request by nvazquez**
### Description

This PR allows passing the optional parameters `domainid` and `account` to the registerTemplate/registerISO/uploadISO/uploadTemplate APIs (was only possible to pass these parameters through the API):

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?
- Register a template as an admin to another account in other domain -> verify domainid and account parameters are passed correctly
- Register a template as an admin without setting any domain or account -> verify domainid and account parameters are not passed
- Login as a user, verify the domain dropdown is not displayed

### CODE REVIEW

**Comment by shwstppr** [comment]
@nvazquez should similar fields be added in the ISO form?

**Comment by weizhouapache** [comment]
> @nvazquez should similar fields be added in the ISO form?

make sense
cc @nvazquez

**Comment by nvazquez** [comment]
Thanks @shwstppr @weizhouapache - I have added them to the Register/Upload ISO view as well

**Comment by nvazquez** [comment]
@blueorangutan ui

**Review by weizhouapache — APPROVED** [review]
code lgtm

registered a templae for ROOT/user on QA server, looks good
image

**Comment by weizhouapache** [comment]
@nvazquez 
can you fix the conflicts ? thanks

**Comment by nvazquez** [comment]
Done thanks @weizhouapache
@blueorangutan ui

**Review by DaanHoogland — APPROVED** [review]
looks and tests ok

**Pull request merged**
