### PR TITLE
Add all tests in /test/integration/smoke to Travis run

### PR DESCRIPTION
**Pull request by runseb**
This modified .travis.yml file to include missing tests in /test/integration/smoke.
It expands the coverage of the Travis runs.

### CODE REVIEW

**Comment by runseb** [comment]
looks like all tests passed but in fact some did not run...someone needs to check what happened exactly

**Comment by pvr9711** [comment]
Following are the tests that run on Simulator basic and adv - separately, please add ".py" to the end.
Simulator Basic -
integration.smoke.test_affinity_groups
integration.smoke.test_deploy_vms_with_varied_deploymentplanners
integration.smoke.test_disk_offerings
integration.smoke.test_global_settings
integration.smoke.test_iso
integration.smoke.test_multipleips_per_nic
integration.smoke.test_over_provisioning
integration.smoke.test_portable_publicip
integration.smoke.test_primary_storage
integration.smoke.test_reset_vm_on_reboot
integration.smoke.test_scale_vm
integration.smoke.test_secondary_storage
integration.smoke.test_service_offerings
integration.smoke.test_ssvm
integration.smoke.test_templates
integration.smoke.test_vm_life_cycle
integration.smoke.test_volumes

Simulator Adv -
integration.smoke.test_affinity_groups
integration.smoke.test_deploy_vms_with_varied_deploymentplanners
integration.smoke.test_disk_offerings
integration.smoke.test_global_settings
integration.smoke.test_guest_vlan_range
integration.smoke.test_iso
integration.smoke.test_multipleips_per_nic
integration.smoke.test_network
integration.smoke.test_nic_adapter_type
integration.smoke.test_non_contigiousvlan
integration.smoke.test_over_provisioning
integration.smoke.test_portable_publicip
integration.smoke.test_primary_storage
integration.smoke.test_privategw_acl
integration.smoke.test_public_ip_range
integration.smoke.test_pvlan
integration.smoke.test_reset_vm_on_reboot
integration.smoke.test_resource_detail
integration.smoke.test_routers
integration.smoke.test_scale_vm
integration.smoke.test_secondary_storage
integration.smoke.test_service_offerings
integration.smoke.test_ssvm
integration.smoke.test_templates
integration.smoke.test_vm_life_cycle
integration.smoke.test_volumes
ntegration.smoke.test_vpc_vpn

**Comment by runseb** [comment]
Sanjeev, good point, Travis only runs advanced zone tests. Maybe we should figure out a way to also run the tests with a basic config.

**Comment by kishankavala** [comment]
@runseb @pvr9711 @sanjeevneelarapu 
Can we include all regression simulator tests also?

**Comment by kishankavala** [comment]
@sanjeevneelarapu 
1. We should look at ways to improve the simulator to run faster.
2. We have PRs open for more than a day in most cases. I would rather wait for 6hrs than to have code which might break some functionality.

When we get CI based on real hardware in future, it'll take even more time. At that point we can look at running it once a day on latest master instead of per PR.

**Comment by borisroman** [comment]
@runseb Could you rebase and push again? If so, and Travis and Jenkins are green, we can merge.

Ping @remibergsma @karuturi

**Comment by runseb** [comment]
@borisroman yes will do tonight

**Pull request closed without merging**
