### PR TITLE
CLOUDSTACK-9858: remove midonet plugin dependency on client packaging

### PR DESCRIPTION
**Pull request by rhtyd**
This fixes packaging/build regression from #2036

Pinging for review - @wido @rafaelweingartner @DaanHoogland 

@blueorangutan package

### CODE REVIEW

**Comment by wido** [comment]
The Midonet profile stays there so we can still activate it if we want to?

Only removed as a build dependency?

**Comment by rafaelweingartner** [comment]
@wido this is exactly what I did in #2036 
From what it looks like I forgot to change the dependency  in "client/pom.xml". Probably that is why the Jenkins build failed there, but I was not able to retrieve the log files to check it.

Thanks @rhtyd.

**Comment by rhtyd** [comment]
This breaks packaging and noredist building.

On Apr 18, 2017 8:00 PM, "Wido den Hollander" <notifications@github.com>
wrote:

The Midonet profile stays there so we can still activate it if we want to?

Only removed as a build dependency?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/apache/cloudstack/pull/2051#issuecomment-294862977>,
or mute
the thread

**Comment by rhtyd** [comment]
Packaging build came out all okay, we can merge. I'll fire a test as well.

@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
Since, this is breaking master and blocking rest of the PRs. I'll proceed with my discretion and manual test results from Trillian and local env. Another issue was found with deployment on centos6/7 for cloudstack-management that has been fixed as well.

**Comment by wido** [comment]
Good @rhtyd ! Let's fix master.

**Pull request merged**
