### PR TITLE
CLOUDSTACK-10121 moveUser

### PR DESCRIPTION
**Pull request by DaanHoogland**

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@DaanHoogland can you rebase and advise if this is ready for review/test/merging?

**Comment by DaanHoogland** [comment]
@rhtyd yes, please review
@blueorangutan package

**Comment by borisstoyanov** [comment]
@DaanHoogland I think I've wrote a test for this, after your rebase I don't see my commit, is it possible that it's lost somehow?

**Comment by DaanHoogland** [comment]
@borisstoyanov yes that might well be the only answer, sorry. Do you still have it locally?

**Comment by borisstoyanov** [comment]
@DaanHoogland I think I did a bit of mess here, should we do some cherry picking to resolve this?

**Comment by DaanHoogland** [comment]
@borisstoyanov looks good now

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@DaanHoogland can you check failing tests?

**Comment by rhtyd** [comment]
@borisstoyanov merged, please re-kick tests.

**Comment by borisstoyanov** [comment]
Thanks @rhtyd,
@blueorangutan test

**Comment by rhtyd** [comment]
Tests LGTM, additional review requested for merging this.

**Comment by rhtyd** [comment]
Due to new changes on master I'll kick another round and then we can merge on pass:
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@DaanHoogland can you fix the conflicts, thanks.

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by borisstoyanov** [comment]
Same error here @DaanHoogland "NameError: global name 'get_template' is not defined\n" 
Looks like this run didn't picked up your latest changes.

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@rhtyd I see two lgtm and extensive tests so I am merging but aware that we spoke about even stricter gating. please revert if you don't think this is enough.

**Comment by rhtyd** [comment]
Lgtm, thanks.

**Pull request merged**
