### PR TITLE
ui: add custom error handling page

### PR DESCRIPTION
**Pull request by bhaisaab**
This just catches any exception and avoid showing stacktrace.

### CODE REVIEW

**Comment by DaanHoogland** [comment]
LGTM, why for 4.5 will you merge forward?

**Comment by bhaisaab** [comment]
yeah, will merge on both 4.5/master :)

**Comment by DaanHoogland** [comment]
ok, I will push to 4.5

Op di 19 mei 2015 om 00:10 schreef Rohit Yadav <notifications@github.com>:

**Comment by DaanHoogland** [comment]
you beat me

Op di 19 mei 2015 om 00:11 schreef Daan Hoogland <daan.hoogland@gmail.com>:

**Comment by bhaisaab** [comment]
oh, I did not know you were doing it :)
Pushed to master as well.

**Comment by bhaisaab** [comment]
@DaanHoogland I could be faster as I use a Github PR merging automation alias, you may try this: https://github.com/bhaisaab/dotfiles/blob/master/git/gitconfig#L46
Usage: git pr <link to github pr>

**Comment by DaanHoogland** [comment]
thanks @bhaisaab nice alias albeit of the write once read never kind, it works ;)

**Pull request closed without merging**
