### PR TITLE
Refactored NicProfile.java for readability.

### PR DESCRIPTION
**Pull request by borisroman**
Only changed names and reorganized them! No functional implementation change.

See issue CLOUDSTACK-8736 for ongoing effort to clean up network code.

### CODE REVIEW

**Comment by DaanHoogland** [comment]
:+1: this is one of the cases I would have liked to see more commits. lgtm in spite

**Comment by borisroman** [comment]
@DaanHoogland I did the following;

- Refactored NicProfile.java (in 1 go)
- Changed names in every file llinked to NicProfile to make sure no regression was in order.

How did you like more commits?

**Comment by DaanHoogland** [comment]
@borisroman first do internal restructure without changing the class interface and next change the accessors. never mind however don't do double work after I managed to review so I would need to do double work as well, let's find more support and merge

**Comment by wido** [comment]
Pending the checks LGTM

**Comment by karuturi** [comment]
looks there are compilation errors in nuage plugin. 
jenkins builds failed http://jenkins.buildacloud.org/job/build-master-noredist/4531/consoleText
http://jenkins.buildacloud.org/job/build-master-slowbuild/2086/consoleText
pull analysis also failed. but looks like a different reason.
https://builds.apache.org/job/cloudstack-pull-analysis/255/consoleText
@borisroman can you check if it is related to this?

**Comment by borisroman** [comment]
Hi @karuturi 

The pull analysis failure is unrelated. --> Checkstyle errors in code I didn't touch

The errors in the master build are being caused by a change of method names as stated in the mail I send yesterday.

http://mail-archives.apache.org/mod_mbox/cloudstack-dev/201508.mbox/%3C1558679771.80.1439832860031.JavaMail.open-xchange%40109.72.87.221%3E

**Comment by karuturi** [comment]
ok. will check PR #707. Thanks

**Pull request merged**
