### PR TITLE
UI: decode userdata in EditVM dialog

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

With PR #7749, we are able to update userdata with some characters (e.g. Chinese).

when edit the vm again, the userdata is not displayed correctly

with this PR, it works well

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan ui

**Comment by harikrishna-patnala** [comment]
@blueorangutan ui

**Review by harikrishna-patnala — APPROVED** [review]
LGTM

Checked the usual userdata listing to see if there is an issue too, but no its working fine.
image

**Review by shwstppr — APPROVED** [review]
Code LGTM

**Review by DaanHoogland — APPROVED** [review]
works with:
image

clgtm

**Pull request merged**
