### PR TITLE
api: listApis should return params based on caller

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

API params can be marked accessible to selected role types using  `authorized` values in API command class.
The existing behaviour of lisApis API was to return all parameters of the API irrespective of the caller's role type. This PR fixes it by adding checks to filter params.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

#### How did you try to break this feature and the system with this change?

Tested by setting an API param as,
```
    @Parameter(name = ApiConstants.SCOPE, type = BaseCmd.CommandType.STRING, description = "Scope of the Webhook",
        authorized = {RoleType.Admin, RoleType.DomainAdmin})
    private String scope;
```

Using cmk,

```
(localcloud) 🐱 > set username admin
(localcloud) 🐱 > sync
Discovered 766 APIs
(localcloud) 🐱 > list apis name=createWebhook filter=name,params
{
  "api": [
    {
      "name": "createWebhook",
      "params": [
        {
          "description": "an optional domainId for the Webhook. If the account parameter is used, domainId must also be used.",
          "length": 255,
          "name": "domainid",
          "related": "listDomainChildren,listDomains",
          "required": false,
          "type": "uuid"
        },
        {
          "description": "Project for the Webhook",
          "length": 255,
          "name": "projectid",
          "related": "activateProject,suspendProject",
          "required": false,
          "type": "uuid"
        },
        {
          "description": "An optional account for the Webhook. Must be used with domainId.",
          "length": 255,
          "name": "account",
          "required": false,
          "type": "string"
        },
        {
          "description": "Scope of the Webhook",
          "length": 255,
          "name": "scope",
          "required": false,
          "type": "string"
        },
        {
          "description": "Secret key of the Webhook",
          "length": 255,
          "name": "secretkey",
          "required": false,
          "type": "string"
        },
        {
          "description": "If set to true then SSL verification will be done for the Webhook otherwise not",
          "length": 255,
          "name": "sslverification",
          "required": false,
          "type": "boolean"
        },
        {
          "description": "Payload URL of the Webhook",
          "length": 255,
          "name": "payloadurl",
          "required": true,
          "type": "string"
        },
        {
          "description": "State of the Webhook",
          "length": 255,
          "name": "state",
          "required": false,
          "type": "string"
        },
        {
          "description": "Name for the Webhook",
          "length": 255,
          "name": "name",
          "required": true,
          "type": "string"
        },
        {
          "description": "Description for the Webhook",
          "length": 255,
          "name": "description",
          "required": false,
          "type": "string"
        }
      ]
    }
  ],
  "count": 1
}
(localcloud) 🐱 > set username user
(localcloud) 🐱 > sync
Discovered 340 APIs
(localcloud) 🐱 > list apis name=createWebhook filter=name,params
{
  "api": [
    {
      "name": "createWebhook",
      "params": [
        {
          "description": "an optional domainId for the Webhook. If the account parameter is used, domainId must also be used.",
          "length": 255,
          "name": "domainid",
          "related": "listDomainChildren,listDomains",
          "required": false,
          "type": "uuid"
        },
        {
          "description": "Project for the Webhook",
          "length": 255,
          "name": "projectid",
          "related": "activateProject,suspendProject",
          "required": false,
          "type": "uuid"
        },
        {
          "description": "An optional account for the Webhook. Must be used with domainId.",
          "length": 255,
          "name": "account",
          "required": false,
          "type": "string"
        },
        {
          "description": "Secret key of the Webhook",
          "length": 255,
          "name": "secretkey",
          "required": false,
          "type": "string"
        },
        {
          "description": "If set to true then SSL verification will be done for the Webhook otherwise not",
          "length": 255,
          "name": "sslverification",
          "required": false,
          "type": "boolean"
        },
        {
          "description": "Payload URL of the Webhook",
          "length": 255,
          "name": "payloadurl",
          "required": true,
          "type": "string"
        },
        {
          "description": "State of the Webhook",
          "length": 255,
          "name": "state",
          "required": false,
          "type": "string"
        },
        {
          "description": "Name for the Webhook",
          "length": 255,
          "name": "name",
          "required": true,
          "type": "string"
        },
        {
          "description": "Description for the Webhook",
          "length": 255,
          "name": "description",
          "required": false,
          "type": "string"
        }
      ]
    }
  ],
  "count": 1
}

```

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
clgtm, @shwstppr is this a facility especially for the webhook feature you are working on? It seems it would serve more purpose but I see no other reference. If it is only for webhooks, why a separate PR?

**Comment by shwstppr** [comment]
@DaanHoogland this is not only limited to webhooks feature. Other API too have params that have authorized key defined. Though I didn't get change to take logs/cmk output for them.
image
eg: `listBuckets` API has admin-only param objectstorageid but currently it is shown to a normal user as well (though the user won't be able to use that).
```
(local) 🐱 > set username user
(local) 🐱 > sync
Discovered 320 APIs
(local) 🐱 > list buckets -h
listBuckets: Lists all Buckets.
API Params               Type     Description
==========               ====     ===========
account                  string   list resources by account. Must be used w
                                  ith the domainId parameter.
domainid                 uuid     list only resources belonging to the doma
                                  in specified
id                       uuid     the ID of the bucket
ids                      list     the IDs of the Buckets, mutually exclusiv
                                  e with id
isrecursive              boolean  defaults to false, but if true, lists all
                                   resources from the parent specified by 
                                  the domainId till leaves.
keyword                  string   List by keyword
listall                  boolean  If set to false, list only resources belo
                                  nging to the command's caller; if set to
                                   true - list resources that the caller i
                                  s authorized to see. Default value is fa
                                  lse. Resources dedicated to a project ar
                                  e listed only if using the projectid par
                                  ameter.
name                     string   the name of the bucket
objectstorageid          uuid     the ID of the object storage pool, availa
                                  ble to ROOT admin only
page                     integer  
pagesize                 integer  
projectid                uuid     list objects by project; if projectid=-1 
                                  lists All VMs
tags                     map      List resources by tags (key/value pairs)
``` 

Webhooks feature is targetted for 4.20 and I feel this improvement can also be added in 4.19 branch hence a separate PR.

**Comment by shwstppr** [comment]
Tests with a 4.19 env,

Without changes (`objectstorageid` for `listBuckets` is shown to a normal user):
```
(local) 🐱 > sync
Discovered 320 APIs
(local) 🐱 > list buckets -h
listBuckets: Lists all Buckets.
API Params               Type     Description
==========               ====     ===========
account                  string   list resources by account. Must be used w
                                  ith the domainId parameter.
domainid                 uuid     list only resources belonging to the doma
                                  in specified
id                       uuid     the ID of the bucket
ids                      list     the IDs of the Buckets, mutually exclusiv
                                  e with id
isrecursive              boolean  defaults to false, but if true, lists all
                                   resources from the parent specified by 
                                  the domainId till leaves.
keyword                  string   List by keyword
listall                  boolean  If set to false, list only resources belo
                                  nging to the command's caller; if set to
                                   true - list resources that the caller i
                                  s authorized to see. Default value is fa
                                  lse. Resources dedicated to a project ar
                                  e listed only if using the projectid par
                                  ameter.
name                     string   the name of the bucket
objectstorageid          uuid     the ID of the object storage pool, availa
                                  ble to ROOT admin only
page                     integer  
pagesize                 integer  
projectid                uuid     list objects by project; if projectid=-1 
                                  lists All VMs
tags                     map      List resources by tags (key/value pairs)
(local) 🐱 > list apis name=listBuckets filter=name,params
{
  "api": [
    {
      "name": "listBuckets",
      "params": [
        {
          "description": "List by keyword",
          "length": 255,
          "name": "keyword",
          "required": false,
          "type": "string"
        },
        {
          "description": "list objects by project; if projectid=-1 lists All VMs",
          "length": 255,
          "name": "projectid",
          "related": "listProjectAccounts,activateProject,listProjects,suspendProject,updateProject",
          "required": false,
          "type": "uuid"
        },
        {
          "description": "list only resources belonging to the domain specified",
          "length": 255,
          "name": "domainid",
          "related": "createDomain,listDomainChildren,listDomains,listDomains",
          "required": false,
          "type": "uuid"
        },
        {
          "description": "the ID of the bucket",
          "length": 255,
          "name": "id",
          "related": "listBuckets",
          "required": false,
          "type": "uuid"
        },
        {
          "description": "If set to false, list only resources belonging to the command's caller; if set to true - list resources that the caller is authorized to see. Default value is false. Resources dedicated to a project are listed only if using the projectid parameter.",
          "length": 255,
          "name": "listall",
          "required": false,
          "type": "boolean"
        },
        {
          "description": "",
          "length": 255,
          "name": "pagesize",
          "required": false,
          "type": "integer"
        },
        {
          "description": "defaults to false, but if true, lists all resources from the parent specified by the domainId till leaves.",
          "length": 255,
          "name": "isrecursive",
          "required": false,
          "type": "boolean"
        },
        {
          "description": "list resources by account. Must be used with the domainId parameter.",
          "length": 255,
          "name": "account",
          "required": false,
          "type": "string"
        },
        {
          "description": "the name of the bucket",
          "length": 255,
          "name": "name",
          "required": false,
          "type": "string"
        },
        {
          "description": "List resources by tags (key/value pairs)",
          "length": 255,
          "name": "tags",
          "required": false,
          "type": "map"
        },
        {
          "description": "",
          "length": 255,
          "name": "page",
          "required": false,
          "type": "integer"
        },
        {
          "description": "the IDs of the Buckets, mutually exclusive with id",
          "length": 255,
          "name": "ids",
          "related": "listBuckets",
          "required": false,
          "type": "list"
        },
        {
          "description": "the ID of the object storage pool, available to ROOT admin only",
          "length": 255,
          "name": "objectstorageid",
          "related": "cancelStorageMaintenance,createStoragePool,findStoragePoolsForMigration,enableStorageMaintenance,syncStoragePool,updateStorageCapabilities",
          "required": false,
          "type": "uuid"
        }
      ]
    }
  ],
  "count": 1
}

```

With changes (`objectstorageid` for `listBuckets` is *not* shown to a normal user):

```
(local) 🐱 > sync
Discovered 320 APIs
(local) 🐱 > list buckets -h
listBuckets: Lists all Buckets.
API Params               Type     Description
==========               ====     ===========
account                  string   list resources by account. Must be used w
                                  ith the domainId parameter.
domainid                 uuid     list only resources belonging to the doma
                                  in specified
id                       uuid     the ID of the bucket
ids                      list     the IDs of the Buckets, mutually exclusiv
                                  e with id
isrecursive              boolean  defaults to false, but if true, lists all
                                   resources from the parent specified by 
                                  the domainId till leaves.
keyword                  string   List by keyword
listall                  boolean  If set to false, list only resources belo
                                  nging to the command's caller; if set to
                                   true - list resources that the caller i
                                  s authorized to see. Default value is fa
                                  lse. Resources dedicated to a project ar
                                  e listed only if using the projectid par
                                  ameter.
name                     string   the name of the bucket
page                     integer  
pagesize                 integer  
projectid                uuid     list objects by project; if projectid=-1 
                                  lists All VMs
tags                     map      List resources by tags (key/value pairs)

(local) 🐱 > list apis name=listBuckets filter=name,params
{
  "api": [
    {
      "name": "listBuckets",
      "params": [
        {
          "description": "list resources by account. Must be used with the domainId parameter.",
          "length": 255,
          "name": "account",
          "required": false,
          "type": "string"
        },
        {
          "description": "the name of the bucket",
          "length": 255,
          "name": "name",
          "required": false,
          "type": "string"
        },
        {
          "description": "defaults to false, but if true, lists all resources from the parent specified by the domainId till leaves.",
          "length": 255,
          "name": "isrecursive",
          "required": false,
          "type": "boolean"
        },
        {
          "description": "",
          "length": 255,
          "name": "page",
          "required": false,
          "type": "integer"
        },
        {
          "description": "the ID of the bucket",
          "length": 255,
          "name": "id",
          "related": "listBuckets",
          "required": false,
          "type": "uuid"
        },
        {
          "description": "",
          "length": 255,
          "name": "pagesize",
          "required": false,
          "type": "integer"
        },
        {
          "description": "If set to false, list only resources belonging to the command's caller; if set to true - list resources that the caller is authorized to see. Default value is false. Resources dedicated to a project are listed only if using the projectid parameter.",
          "length": 255,
          "name": "listall",
          "required": false,
          "type": "boolean"
        },
        {
          "description": "List by keyword",
          "length": 255,
          "name": "keyword",
          "required": false,
          "type": "string"
        },
        {
          "description": "List resources by tags (key/value pairs)",
          "length": 255,
          "name": "tags",
          "required": false,
          "type": "map"
        },
        {
          "description": "list only resources belonging to the domain specified",
          "length": 255,
          "name": "domainid",
          "related": "createDomain,listDomainChildren,listDomains,listDomains",
          "required": false,
          "type": "uuid"
        },
        {
          "description": "the IDs of the Buckets, mutually exclusive with id",
          "length": 255,
          "name": "ids",
          "related": "listBuckets",
          "required": false,
          "type": "list"
        },
        {
          "description": "list objects by project; if projectid=-1 lists All VMs",
          "length": 255,
          "name": "projectid",
          "related": "listProjectAccounts,activateProject,listProjects,suspendProject,updateProject",
          "required": false,
          "type": "uuid"
        }
      ]
    }
  ],
  "count": 1
}
```

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by kiranchavala — APPROVED** [review]
LGTM, tested for admin user the objectstorageid is available and for normal user it's not available 

```
(local) 🐱 > list buckets -h
listBuckets: Lists all Buckets.
API Params               Type     Description
==========               ====     ===========
account                  string   list resources by account. Must be used w
                                  ith the domainId parameter.
domainid                 uuid     list only resources belonging to the doma
                                  in specified
id                       uuid     the ID of the bucket
ids                      list     the IDs of the Buckets, mutually exclusiv
                                  e with id
isrecursive              boolean  defaults to false, but if true, lists all
                                   resources from the parent specified by
                                  the domainId till leaves.
keyword                  string   List by keyword
listall                  boolean  If set to false, list only resources belo
                                  nging to the command's caller; if set to
                                   true - list resources that the caller i
                                  s authorized to see. Default value is fa
                                  lse. Resources dedicated to a project ar
                                  e listed only if using the projectid par
                                  ameter.
name                     string   the name of the bucket
objectstorageid          uuid     the ID of the object storage pool, availa
                                  ble to ROOT admin only
page                     integer
pagesize                 integer
projectid                uuid     list objects by project; if projectid=-1
                                  lists All VMs
tags                     map      List resources by tags (key/value pairs
```


For admin user 

```
(local) 🐱 > list buckets
account=         domainid=        filter=          id=              ids=             isrecursive=     keyword=         listall=         name=            objectstorageid= page=
pagesize=        projectid=       tags=


```
For Normal user , there is no option of objectstorageid


```

(local2) 🐱 > list buckets
account=     domainid=    filter=      id=          ids=         isrecursive= keyword=     listall=     name=        page=        pagesize=    projectid=   tags=
```

**Pull request merged**
