### PR TITLE
server: update template to another template type

### PR DESCRIPTION
**Pull request by ustcweizhou**
## Description

this contains other changes
(1) add isrouting field for vm templates on UI
(2) show register URL of template/iso on UI
(3) set 'Bootable' field to changable for existing ISO

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

this provides a easy way to upload systemvm template
(1) register template
(2) update template type from USER to SYSTEM
(3) destroy ssvm/cpvm, new systemvms will be created from the new template (latest template with type=SYSTEM)
(4) change global setting router.template.kvm (or other hypervisor) to the name of new template, new VRs will be created from the new template.

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@weizhouapache marking for 4.14.1
It will need primate work for that, right? Can you add a ticket there?

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@ustcweizhou do we want to restrict this to root admin only?

**Comment by weizhouapache** [comment]
> @ustcweizhou do we want to restrict this to root admin only?

@rhtyd 
I was thinking about the following change
```
-    @Parameter(name = "templatetype", type = CommandType.STRING, description = "the type of the template")
+    @Parameter(name = "templatetype", type = CommandType.STRING, description = "the type of the template", authorized
+ = {RoleType.Admin})
     private String templateType;
```

however, when I tested with normal user or domain admin, the api succeed without templatetype change.
```
(test1) > update template id="ce3d5211-3209-4617-b569-6c533801a20c" templatetype=SYSTEM
{
  "template": {
    "account": "test1",
    "bits": 0,
    "bootable": true,
    "created": "2020-06-12T09:54:08+0000",
    "crossZones": false,
    "details": {
      "rootDiskController": "osdefault"
    },
    "displaytext": "ubuntu18-minimal-test1",
    "domain": "test1",
    "domainid": "931bc746-8a9a-45ec-8c50-776b89aed898",
    "format": "QCOW2",
    "hypervisor": "KVM",
    "id": "ce3d5211-3209-4617-b569-6c533801a20c",
    "isdynamicallyscalable": false,
    "isfeatured": false,
    "ispublic": false,
    "isready": false,
    "name": "ubuntu18-minimal-test1",
    "ostypeid": "67bad17c-186e-11ea-83e0-066004001165",
    "ostypename": "Apple Mac OS X 10.6 (32-bit)",
    "tags": [],
    "templatetype": "USER"
  }
}
```

without this change, I got following error which looks better.
```
(test1) > update template id="ce3d5211-3209-4617-b569-6c533801a20c" templatetype=SYSTEM
Error 531: Parameter templatetype can only be specified by a Root Admin, permission denied
```

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by DaanHoogland — APPROVED** [review]
code looks good. there are UI changes, can you refer to a primate ticket or pr?

**Comment by DaanHoogland** [comment]
ping @PaulAngus @rhtyd merge this?

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
I see small enhanacement/improvement, tests have passed. We probably can get away with this.

**Pull request merged**
