### PR TITLE
UI: Fix backup offering buttons for instances in data view

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR fixes backup offering buttons for instances in data view

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### Screenshots (if appropriate):
Image before the changes for a instance with a backup offering
image

Image after the changes for a instance with a backup offering
image

### How Has This Been Tested?
Assign a backup offering to an instance and check the buttons in the data view.

### CODE REVIEW

**Comment by vishesh92** [comment]
@blueorangutan ui

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Comment by sureshanaparti** [comment]
Verified fix in qa simulator env.

**Comment by DaanHoogland** [comment]
code looks good in qa but removing the offering doesn't work: 
image

I am not sure if the icon should be added if the removal of the offering is not allowed.

**Review by DaanHoogland — APPROVED** [review]
some issue found but the change works as expected

**Pull request merged**
