### PR TITLE
Veeam: Support Veeam 11 and 12

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes several issues in the testing of Veeam 11 and Veeam12
- Import Veeam.Backup.PowerShell and silently ignore the warning messages
- Fix issue when assign vm to backup offerings, which caused by separator (\r\n)
- Fix authorization failure in veeam 12a, which is because v1_4 is not supported in veeam 12a any more
- Fix exception if backup name has space
- Fix backup metrics in veeam12, which is because powershell command does not return the values needed
- Fix Incorrect datetime value, which is because powershell command returns a datetime which is not supported in Java
- Fix issue during backup restoration if VM has both ROOT and DATA disks.

This PR also has the following update
- Add integration test test/integration/smoke/test_backup_recovery_veeam.py
- Make some UI changes
- Add zone setting backup.plugin.veeam.version. If it is not set, CloudStack will get veeam version via powershell commands.
- Add zone setting backup.plugin.veeam.task.poll.interval and backup.plugin.veeam.task.poll.max.retry

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 vmware-70u3

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 vmware-70u3

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 vmware-70u3

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan LLtest rocky8 vmware-70u3

**Comment by weizhouapache** [comment]
@blueorangutan LLtest rocky8 vmware-70u3

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 vmware-70u3

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 vmware-70u3

**Comment by weizhouapache** [comment]
@blueorangutan test ubuntu22 vmware-80

**Comment by weizhouapache** [comment]
this PR has been reviewed by @rohityadavcloud @DaanHoogland 
and verified by @borisstoyanov 
thanks !

merging

**Comment by shwstppr** [comment]
@weizhouapache @DaanHoogland do we need to forward merge 4.18 branch now to cut 4.19 RC3 or can it wait for later?

**Comment by weizhouapache** [comment]
> @weizhouapache @DaanHoogland do we need to forward merge 4.18 branch now to cut 4.19 RC3 or can it wait for later?

I can wait. 4.18.2/4.19.1 is good to me.
(@rohityadavcloud might be the same)
So it is up to you.

**Comment by rohityadavcloud** [comment]
Thanks @weizhouapache - looks like this has made into 4.18 branch; but as it also forward merged for main/4.19 branch (ie. RC3) @shwstppr ?

**Pull request merged**
