### PR TITLE
Allow forward to fix port forwarding rules

### PR DESCRIPTION
**Pull request by isoutham**
Fixes a missing iptables rule that would prevent port forwarding from working.

Tested against (with hardware) smoke tests.

### CODE REVIEW

**Comment by bhaisaab** [comment]
LGTM, I guess @wilderrodrigues can merge this once his tests pass?

**Comment by wilderrodrigues** [comment]
Nice!

Travis is almost there - and I'm stuck with my KVM. So, once it's green I will test. :)

**Comment by bhaisaab** [comment]
@isoutham I'm confused to merge which one since you said in the other PR to ignore a previous PR. Can you ask @wilderrodrigues to merge it? Thanks.

**Comment by wilderrodrigues** [comment]
@bhaisaab 

I'm on it... :)

Already got the PR and will get it merged in a bit.

Cheers,
Wilder

**Pull request merged**
