### PR TITLE
Fix main branch issues

### PR DESCRIPTION
**Pull request by nvazquez**
### Description

This PR fixes issues on main branch after the merge commit: https://github.com/apache/cloudstack/commit/5bf81cf00233efe4478552e7bb13f3e96dc58ed1

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by vishesh92 — APPROVED** [review]
clgtm. waiting for tests to pass.

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
I think we can merge if packaging passes

**Review by weizhouapache — APPROVED** [review]

**Review by harikrishna-patnala — APPROVED** [review]
code LGTM

**Comment by nvazquez** [comment]
@blueorangutan package

**Review by Pearl1594 — APPROVED** [review]

**Pull request merged**
