### PR TITLE
Misc fixes to sharing templates functionality

### PR DESCRIPTION
**Pull request by anuragaw**
1. Fix populating g_allowUserViewAllDomainAccounts flag. This was
implemented incorrectly and caused flag's effect to not reflect
directly after login.
2. Filter account/project names only for add operation. update
template permissions API is implemented in such a way that it allows
removal of any account that could have had permissions but allows
only adding accounts/projects which are in caller's domain.
3. Added some checks where null variable could result in crash.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

Manual testing has been done on UI locally.

### CODE REVIEW

**Comment by anuragaw** [comment]
@blueorangutan package

**Comment by anuragaw** [comment]
pinging for review - @rhtyd , @shwstppr , @andrijapanicsb , @borisstoyanov

**Comment by rhtyd** [comment]
This is purely a UI change, manual test confirmation is necessary.

**Comment by andrijapanicsb** [comment]
All good - except that when REMOVING projects permissions, projects UUIDs are used instead of names - otherwise looks good.

**Comment by borisstoyanov** [comment]
@blueorangutan package
tahnks @anuragaw

**Comment by anuragaw** [comment]
Should be fixed @andrijapanicsb , @borisstoyanov - please retest. Thanks!

**Comment by rhtyd** [comment]
LGTM, can you test @borisstoyanov ?

**Comment by andrijapanicsb** [comment]
Merging based on 2 x LGTM

**Pull request merged**
