### PR TITLE
CLOUDSTACK-9342: Site to Site VPN PFS not being set correctly

### PR DESCRIPTION
**Pull request by Slair1**
Bug in code set PFS to the same value (yes/no) as DPD.

file.addeq(" pfs=%s" % CsHelper.bool_to_yn(obj['dpd']))

### CODE REVIEW

**Comment by kiwiflyer** [comment]
PR https://github.com/apache/cloudstack/pull/872 is going to replacing openswan with strongswan.

I believe PFS is depreciated in strongwan, so it might make sense to just remove PFS once 872 is committed.
It might be worth while looking at addressing this just in 4.7.x and 4.8.x.

Thoughts?

**Comment by Slair1** [comment]
ah, thanks @kiwiflyer .  How do i change this to 4.7.x?

Also i check PR #872 and the PFS code looks good there, it is totally re-written.

**Comment by kiwiflyer** [comment]
@Slair1 You can checkout the 4.7 branch and then create a new branch. Apply the patch and then push that new local branch back up to your github ACS fork. Then create a pull request against ACS 4.7.

**Comment by Slair1** [comment]
@kiwiflyer thanks, how do i delete this PR?

**Comment by kiwiflyer** [comment]
@Slair1 You should have a close button below the comments section.

**Comment by Slair1** [comment]
@kiwiflyer , wow i feel stupid now :-)

**Comment by swill** [comment]
@Slair1 If you create a new PR or if a different PR solves the problem you ran into, can you please post the PR number that replaces this one?  This helps me maintain my ability to track active PRs.  Thx...

**Comment by Slair1** [comment]
Create new PR #1480 in 4.7 branch

**Pull request closed without merging**
