### PR TITLE
Display public ip addresses for shared network

### PR DESCRIPTION
**Pull request by ravening**
### Description
If a vm belongs to shared network then display the list
of ip addresses available which can be used to assign for
secondary IP addresses.

Also display "Public IP addresses" tab for shared networks

List all public ip address in shared network

Screenshot 2021-02-10 at 13 16 26

Display the list of ip address while adding secondary ip instead of user input box

Screenshot 2021-02-10 at 13 17 15

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@ravening does this rely on some code changes ?

**Comment by ravening** [comment]
> @ravening does this rely on some code changes ?

@weizhouapache dont think so.. public ip address should be listed by default

**Comment by weizhouapache** [comment]
> > @ravening does this rely on some code changes ?
> 
> @weizhouapache dont think so.. public ip address should be listed by default

@ravening but listing ips in shared network does not work, right ?

**Comment by ravening** [comment]
> > > @ravening does this rely on some code changes ?
> > 
> > 
> > @weizhouapache dont think so.. public ip address should be listed by default
> 
> @ravening but listing ips in shared network does not work, right ?

@weizhouapache I can display it

```
(local) mgt01 > list publicipaddresses listall=true fordisplay=true allocatedonly=false forvirtualnetwork=true filter=ipaddress,
{
  "count": 59,
  "publicipaddress": [
```

**Comment by weizhouapache** [comment]
> > > > @ravening does this rely on some code changes ?
> > > 
> > > 
> > > @weizhouapache dont think so.. public ip address should be listed by default
> > 
> > 
> > @ravening but listing ips in shared network does not work, right ?
> 
> @weizhouapache I can display it
> 
> ```
> (local) mgt01 > list publicipaddresses listall=true fordisplay=true allocatedonly=false forvirtualnetwork=true filter=ipaddress,
> {
>   "count": 59,
>   "publicipaddress": [
> ```

@ravening ok.
I tested with 4.15.1.0, it worked.

by the way, forvirtualnetwork should be 'false', and networkid should be passed.

**Comment by rhtyd** [comment]
@ravening @weizhouapache does it make sense to change base to 4.15 to 4.15.1?

**Comment by Pearl1594** [comment]
@ravening Could you please address the conflict. Thanks.

**Comment by shwstppr** [comment]
ping @ravening

**Comment by Pearl1594** [comment]
@blueorangutan ui

**Comment by rhtyd** [comment]
ping @ravening cc @weizhouapache - any progress/update on this?

@utchoang cc @svenvogel - can you help review/test this as well?

**Comment by utchoang** [comment]
An error occurred while navigating to the IP address, network resource page

- Public IP resource:
image
image

- Network:
image
image

**Comment by ravening** [comment]
> @ravening
> An error occurred while navigating to the IP address, network resource page
> 
> * Public IP resource:
>   image
>   image
> * Network:
>   image
>   image

@utchoang @Pearl1594 can you guys test/review the code again?

**Comment by Pearl1594** [comment]
@blueorangutan ui

**Review by utchoang — APPROVED** [review]
LGTM!

**Review by weizhouapache — APPROVED** [review]

**Review by Pearl1594 — APPROVED** [review]
Verified behavior. LGTM

**Pull request merged**
