### PR TITLE
Fix vsphere storagepolicy

### PR DESCRIPTION
**Pull request by harikrishna-patnala**
### Description

This PR fixes issue #8914

Issue is when using a compute offering which is associated with a disk offering having vsphere storage policy defined.

When a VM is created with such a compute offering, vsphere storage policy defined on the disk offering should be applied to the root volume.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

1. Assign a tag on the storage on vcenter and create a storage policy with the same tag 
2. Create a disk offering with a storage policy selected
3. Create a compute offering and associate the above created disk offering in that compute offering
4. Create an instance using the above compute offering
5. The VM's root disk created on the storage pool associated with policy

### CODE REVIEW

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Review by borisstoyanov — APPROVED** [review]
LGTM, manually checked

**Comment by miko-meos** [comment]
Hello,
In the last version of cloudstack 4.20, vm policy assignment works only on data disks, but not on root disks.

Thanks.

**Pull request merged**
