### PR TITLE
CLOUDSTACK-8457: Add option to authorize SAML SSO for user when adding user

### PR DESCRIPTION
**Pull request by bhaisaab**
With SAML enabled, add user view shows option to authorize SAML SSO for a user.

### CODE REVIEW

**Comment by bhaisaab** [comment]
Screenshot:
screen shot 2015-07-10 at 2 52 18 am

**Comment by wilderrodrigues** [comment]
Hi @bhaisaab 

Code looks good and screenshot as well. :+1: 

Hints to test it manually? After hitting the check-box, what should I do?

Cheers,
Wilder

**Comment by bhaisaab** [comment]
@wilderrodrigues thanks. You can select the authorise sso checkbox and submit if you've a SAML IDP server. 

For test setup, you can follow this: https://cwiki.apache.org/confluence/display/CLOUDSTACK/SAML+2.0+Plugin#SAML2.0Plugin-Testing

**Comment by bhaisaab** [comment]
on Chrome, dev tools if you set g_idpList to null, you should see the saml stuff in the form.

**Comment by bhaisaab** [comment]
@abhinandanprateek @jburwell @wilderrodrigues ping

**Comment by abhinandanprateek** [comment]
Looks good to me.

**Comment by wilderrodrigues** [comment]
LGTM :+1:

**Comment by bhaisaab** [comment]
Thanks both, I pushed another UI change. Please see it too. This change allows admins to say if they want usernames with a domain (extracted from the IDP server).

**Comment by bhaisaab** [comment]
Squashing and merging commits.

**Pull request closed without merging**
