### PR TITLE
CLOUDSTACK-9491: incorrect parsing of device list to find ethernet index of plugged NIC

### PR DESCRIPTION
**Pull request by murali-reddy**
In VmwareResource, findRouterEthDeviceIndex() method find ethernet interface index given
the mac address. This method is used, once a nic is plugged to determine ethernet interface.
"/proc/sys/net/ipv4/conf" from the VR and looped through the devices to find the right
ethernet interface. Howver current logic read it once, and loops through the device list.
Its observerd device may not show up '/proc/sys/net/ipv4/conf' immediatly once NIC is plugged
in the VM from vCenter.

Fix ensured, while waiting for 15 sec in the loop, read the latest content from /proc/sys/net/ipv4/conf
, so that right device list is processed.

Manual tested VPC scenarios of adding new tiers which uses findRouterEthDeviceIndex, to find the guest/public network ethernet index.

### CODE REVIEW

**Comment by serg38** [comment]
@murali-reddy This issue might be related to PR1660. Do you mind testing against latest master to see if you it is addressed already?

**Comment by murali-reddy** [comment]
@serg38 Though same code path, i ran into different issue. When i was adding new tier to VPC, eth3 was plugged into VR from vCenter. As commented in the function there is delay for ethernet device to appear in the guest instance.

I could see code loops through eth0, eth1, eth2 only, because it read the '/proc/sys/net/ipv4/conf' too early.

**Comment by serg38** [comment]
@murali-reddy Thanks for the explanation. LGTM for code review

**Comment by abhinandanprateek** [comment]
The fix looks like the correct thing to do. 
@muali-reddy LGTM for code review.

**Comment by sateesh-chodapuneedi** [comment]
@murali-reddy Makes sense to get fresh listing of virtual NICs in next iteration as the first iteration might have missed the hot-plugged virtual NIC (for VPC tier being configured). Though one side effect is we will loop through all the virtual NICs, except the newly hot-plugged NIC, at least one more time. 
Can you please see if we can avoid repeating the command 'ip address show' for the virtual NICs that were already verified to be not matching.

**Comment by jburwell** [comment]
@murali-reddy have you had a chance to address @sateesh-chodapuneedi comments?

**Comment by jburwell** [comment]
@blueorangutan package

**Comment by jburwell** [comment]
@blueorangutan test centos7 vmware55u3

**Comment by jburwell** [comment]
@murali-reddy is there a way to create or update a Marvin test case to verify this fix?

**Comment by murali-reddy** [comment]
@sateesh-chodapuneedi  added optimization for now, but its better we eliminate the whole logic of finding device index from the VR.

**Comment by murali-reddy** [comment]
@jburwell function 'findRouterEthDeviceIndex' which is modified, is invoked when ever a new tier to VPC is added (virtual NIC is hot-plugged). Many VPC tests run againest the VMware environment will cover this scenario.

**Comment by murali-reddy** [comment]
@blueorangutan test centos7 vmware55u3

**Comment by sateesh-chodapuneedi** [comment]
Code LGTM, 👍 +1

**Comment by rhtyd** [comment]
LGTM, some test failures have been addressed here: https://github.com/apache/cloudstack/pull/1692

**Comment by jburwell** [comment]
@murali-reddy could you please squash your commits?

**Comment by rhtyd** [comment]
@murali-reddy can you squash your commits
@blueorangutan package

**Comment by murali-reddy** [comment]
@blueorangutan package

**Comment by murali-reddy** [comment]
@blueorangutan test centos7 vmware55u3

**Comment by murali-reddy** [comment]
@blueorangutan test centos7 vmware55u3

**Comment by jburwell** [comment]
@rhtyd could you check into the status of the test run for this PR?

**Comment by rhtyd** [comment]
Invalid params were provided, the hypervisor to be passed was vmware-55u3. I'll fix this in blueorangutan as it currently does not check/validate the hypervisor name properly. Kicked a new job manually from Jenkins.

**Comment by jburwell** [comment]
@murali-reddy could you please investigate the following test case failures:

* ``test_03_vpc_internallb_haproxy_stats_on_all_interfaces``
* ``test_01_internallb_roundrobin_1VPC_3VM_HTTP_port80``
* ``test_02_internallb_roundrobin_1RVPC_3VM_HTTP_port80``
* ``test_01_create_redundant_VPC_2tiers_4VMs_4IPs_4PF_ACL``

**Comment by jburwell** [comment]
@murali-reddy have you had a chance to investigate the [test failures](https://github.com/apache/cloudstack/pull/1681#issuecomment-257717551)?

**Comment by rhtyd** [comment]
LGTM on tests, the failures wrt VPC are known intermittent issues. I'm not sure about the internal lb failures, I'll kick another test round since there have been several changes on the base branch. 

@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware55u3

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-55u3

**Comment by rhtyd** [comment]
LGTM, failures related to vpc/rvr are known intermittent failures. We'll kick another test round on #1753, #1754 etc. and work towards fixing them for vmware and xenserver separately.  Merging this based on code reviews and tests.

**Pull request merged**
