### PR TITLE
CLOUDSTACK-8660 - StringUtilsTest.testGetPrefferedCharset() fails because the preferred charset is not always UTF-8

### PR DESCRIPTION
**Pull request by wilderrodrigues**
Test was failing due to "expected:<UTF-8> but was:<US-ASCII>"

Build is successful:

[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11:24 min
[INFO] Finished at: 2015-07-22T13:51:49+02:00
[INFO] Final Memory: 114M/927M
[INFO] ------------------------------------------------------------------------

Test report for test_vm_life_cycle will be sent  in a bit.

@DaanHoogland @bhaisaab , could you please have a look at that?

Cheers,
Wilder

### CODE REVIEW

**Comment by karuturi** [comment]
:+1:

**Comment by wilderrodrigues** [comment]
The other test in the string utils test class also failed.

I will have a look at that one as well.

Cheers,
Wilder

Sent from my iPhone

On 22 Jul 2015, at 14:25, asfbot <notifications@github.com<mailto:notifications@github.com>> wrote:


cloudstack-pull-requests #800<https://builds.apache.org/job/cloudstack-pull-requests/800/> UNSTABLE
Looks like there's a problem with this pull request

**Comment by wilderrodrigues** [comment]
Build is back to normal... keys are being created... and VMs are also fine. See details below:

@karuturi @bhaisaab @DaanHoogland: got some time for a second LGTM?

[root@kvm1 ~]# ls -lart ~/.ssh/
total 16
dr-xr-x---. 3 root root 4096 Jul 22 02:37 ..
-rw-r--r--. 1 root root  389 Jul 22 08:21 id_rsa.pub.cloud
drwx------. 2 root root 4096 Jul 22 08:21 .
-rw-------. 1 root root 1678 Jul 22 08:21 id_rsa.cloud
[root@kvm1 ~]# 

Test advanced zone virtual router ... === TestName: test_advZoneVirtualRouter | Status : SUCCESS ===
ok
Test Deploy Virtual Machine ... === TestName: test_deploy_vm | Status : SUCCESS ===
ok
Test Multiple Deploy Virtual Machine ... === TestName: test_deploy_vm_multiple | Status : SUCCESS ===
ok
Test Stop Virtual Machine ... === TestName: test_01_stop_vm | Status : SUCCESS ===
ok
Test Start Virtual Machine ... === TestName: test_02_start_vm | Status : SUCCESS ===
ok
Test Reboot Virtual Machine ... === TestName: test_03_reboot_vm | Status : SUCCESS ===
ok
Test destroy Virtual Machine ... === TestName: test_06_destroy_vm | Status : SUCCESS ===
ok
Test recover Virtual Machine ... === TestName: test_07_restore_vm | Status : SUCCESS ===
ok
Test migrate VM ... SKIP: At least two hosts should be present in the zone for migration
Test destroy(expunge) Virtual Machine ... === TestName: test_09_expunge_vm | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 10 tests in 2666.478s

OK (SKIP=1)
/tmp//MarvinLogs/test_vm_life_cycle_1JU23D/results.txt (END)

**Comment by karuturi** [comment]
looks good :+1:

**Comment by wilderrodrigues** [comment]
Thanks for the LGTM, @karuturi :)

2 LGTM, merging...

**Comment by DaanHoogland** [comment]
LGTM (2*LGTM from one person is only one LGTM;)

**Comment by wilderrodrigues** [comment]
?! I did not notice... I swear! :(

**Pull request closed without merging**
