### PR TITLE
Fix get upload params NPE

### PR DESCRIPTION
**Pull request by nvazquez**
### Description

This PR an NPE on getUploadTemplateParams for template upload
Fixes: #6071 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### How Has This Been Tested?
````
(localcloud) 🐱 > get uploadparamsfortemplate name=test displaytext=test format=ova hypervisor=vmware ostypeid=6413d8a6-a06a-11ec-86fc-1e003900042d zoneid=17923b3f-5f1a-4098-8277-50adb4e7e909 
{
  "getuploadparams": {
    "expires": "2022-03-10T13:33:08.844Z",
    "id": "a7fc1eea-ad80-4105-8a79-8e628e2571d2",
    "metadata": "nEUT1wgt9S2Bh1B7wKLq1yVOSvGnQzF+Q2esSrTZ6Q6ZDXlFZfMkyviE/RfH16pUXHBhLubLVNUCydT+IGBudRJ0re5IEct4n0X3b0/v96rjyz0dLjjaXUGcNNRhs1ZC/vOs3CEfcAeSTyhC2Tq17XCiUWkK4jKOWk3+po0gfSTzEU1/9lIE/JHaXdaZbP5E2ykuoICO6/kb/3RjNfivBqg9rJP6U+KTsVJBbd09xVmD7og/5cqtZsSZt6b6C7Vgqgg+chaQcSsKbNyrHjxOMuNCTOlCqJH5QZg7q1TVvrsz22IW+RmgF/EkVaRNLcI8ioVWOcMwAhfo9RBgTADfvWNu1GeqEiixMYcfK2S3NxwVlzwKGq59uOv/PRqjTzOpHcN5v3ebfpLBQMW1D9lVWG/3iR4qho1appclU0q+EtgOJP64UFsFE4rKBfnsF5p0+dTXbeLwynwYgjdzOkSyRobBlkvbSeb48o+xymRemSjYAvMvX12dq2EL1URNRJe376F0Zi+T2sJ8u6rca7ZvZ12ZfKBAlz/mnj6gZoGxE8pAsRbFni6IwXW9ADyGkGRTv0E8K1l8zPuq0iItX4nBoawjN+zSJAt9m2g2JTyL1hn4HC3flOvIZLppuAkXDR5m4HgEoVG4934M1C/J04QlPAOSvcVlO9YWc07CSZHy5Zc=",
    "postURL": "https://10.0.55.142/upload/a7fc1eea-ad80-4105-8a79-8e628e2571d2",
    "signature": "nJFx/0nqIrfluslTgoXhhEyo0gA="
  }
}
````

### CODE REVIEW

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by nvazquez** [comment]
@blueorangutan test

**Review by davidjumani — APPROVED** [review]

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Review by Pearl1594 — APPROVED** [review]
CLGTM

**Pull request merged**
