### PR TITLE
ui: fix display host hypervisorversion

### LINKED ISSUE #5294: Hosts details page showing incorrect data for Hypervisor Version
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15.1
~~~

##### CONFIGURATION

VMware and KVM

##### OS / ENVIRONMENT

ESXi 6.5, KVM Ubuntu 18.04

##### SUMMARY

Hosts details page showing incorrect data for Hypervisor Version.
When you press on host for brief moment it is showing correct data and then switches to Hypervisor Version 4.15.1.0 
and empty Host Tags if you press edit and ok it starts showing correct hypervisor and tags.
This is happening for KVM and Vmware hosts.

This problem is happening only in production environment I can’t reproduce it in lab with 5 host 
and in preproduction with 8 hosts.

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~
Showing Hypervisor version
~~~
1vmware
kvm1

##### ACTUAL RESULTS

~~~
Showing agent version
~~~
vmware
kvm

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #5294

Do not display host version as hypervisor version

Code in old UI was not showing host version as hypervisor version
```

                                dataProvider: function (args) {
                                    $.ajax({
                                        url: createURL("listHosts&id=" + args.context.hosts[0].id),
                                        dataType: "json",
                                        async: true,
                                        success: function (json) {
                                            var item = json.listhostsresponse.host[0];
                                            if (item && item.outofbandmanagement) {
                                                item.powerstate = item.outofbandmanagement.powerstate;
                                            }

                                            if (!item.hypervisorversion && item.details && item.details["Host.OS"]) {
                                                item.hypervisorversion =  item.details["Host.OS"] + " " +  item.details["Host.OS.Version"];
                                            }
```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan ui

**Review by nvazquez — APPROVED** [review]
LGTM

**Comment by nvazquez** [comment]
@davidjumani @utchoang can you please review?

**Review by utchoang — APPROVED** [review]
LGTM!

**Review by davidjumani — APPROVED** [review]

**Pull request merged**
