### PR TITLE
packaging: unalias cp before package upgrade

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR...

Fixes: #7544 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Comment by rohityadavcloud** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Comment by DaanHoogland** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Comment by weizhouapache** [comment]
@DaanHoogland 
is this applicable for 4.18 ?

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by weizhouapache — APPROVED** [review]
code lgtm

@DaanHoogland 
will you apply the same change on cloud.spec for centos7 as well ?

**Comment by DaanHoogland** [comment]
> code lgtm
> 
> @DaanHoogland will you apply the same change on cloud.spec for centos7 as well ?

could do @weizhouapache , but I think centos7 will not upgrade python anymore, making this change unnecessary.

**Comment by weizhouapache** [comment]
> > code lgtm
> > @DaanHoogland will you apply the same change on cloud.spec for centos7 as well ?
> 
> could do @weizhouapache , but I think centos7 will not upgrade python anymore, making this change unnecessary.

ok @DaanHoogland , make sense

**Comment by DaanHoogland** [comment]
@blueorangutan test rocky8 xcpng84

**Comment by DaanHoogland** [comment]
@blueorangutan test rocky8 xcpng82

**Comment by DaanHoogland** [comment]
@blueorangutan test rocky8

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Pull request merged**
