### PR TITLE
DB: fix wrong category id of guest os 'Other PV Virtio-SCSI (64-bit)'

### PR DESCRIPTION
**Pull request by ustcweizhou**
## Description

The guest os 'Other PV Virtio-SCSI (64-bit)' has category_id as 6 ("Windows"), which should be 7 ("Other").

```
mysql> select * from guest_os where id=275\G
*************************** 1. row ***************************
             id: 275
    category_id: 6
           name: NULL
           uuid: 5f080e85-c0fd-11ea-ba74-067606003392
   display_name: Other PV Virtio-SCSI (64-bit)
        created: 2020-07-08 09:28:24
        removed: NULL
is_user_defined: 0
1 row in set (0.00 sec)

mysql> select * from guest_os_category;
+----+---------+--------------------------------------+
| id | name    | uuid                                 |
+----+---------+--------------------------------------+
|  1 | CentOS  | 45bfdf47-c0fd-11ea-ba74-067606003392 |
|  2 | Debian  | 45c0529b-c0fd-11ea-ba74-067606003392 |
|  3 | Oracle  | 45c179a5-c0fd-11ea-ba74-067606003392 |
|  4 | RedHat  | 45c1b328-c0fd-11ea-ba74-067606003392 |
|  5 | SUSE    | 45c225de-c0fd-11ea-ba74-067606003392 |
|  6 | Windows | 45c254f2-c0fd-11ea-ba74-067606003392 |
|  7 | Other   | 45c2be11-c0fd-11ea-ba74-067606003392 |
|  8 | Novel   | 45c2efe7-c0fd-11ea-ba74-067606003392 |
|  9 | Unix    | 45c35920-c0fd-11ea-ba74-067606003392 |
| 10 | Ubuntu  | 45c387e4-c0fd-11ea-ba74-067606003392 |
| 11 | None    | 45c3f75e-c0fd-11ea-ba74-067606003392 |
+----+---------+--------------------------------------+
11 rows in set (0.01 sec)
```

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Review by GabrielBrascher — APPROVED** [review]

**Comment by rhtyd** [comment]
@ustcweizhou can you fix the conflict?

**Comment by rhtyd** [comment]
This change may affect users on upgraded, we may need to ask others for review @PaulAngus @DaanHoogland @wido @GabrielBrascher et al thnx

**Review by DaanHoogland — APPROVED** [review]

**Review by wido — APPROVED** [review]
LGTM after conflict is resolved

**Comment by DaanHoogland** [comment]
this is a good fix I don't see how it can hurt upgrades. templates that are `Other PV Virtio-SCSI (64-bit)` would now be deployed as `Windows` and should be `Other`. What is your concern, @rhtyd?

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
bo failed to upload results: no regressions:
```
Intermittent failure detected: /marvin/tests/smoke/test_privategw_acl.py
Smoke tests completed. 86 look OK, 0 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
```
merging

**Pull request merged**
