### PR TITLE
Implemented the lateral expansion of the area-box in the forms (creat…

### PR DESCRIPTION
**Pull request by LayonRibeiro**
### Description
Currently, the expansion of the textarea field in the _quota tariff_ creation and update forms is limited to vertical growth. This can make the experience unsatisfactory for entering larger texts, as the field does not expand horizontally, which can hinder the visualization and editing of the content.

Changes have been made to the UI to allow the textarea to expand in both directions (vertical and horizontal).

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### How Has This Been Tested?

1- Accessed the create form and update form for quota tariff.
2- Verified that the textarea fields now expand horizontally as well as vertically.
3- Ensured that the enhanced textarea functionality works as expected in different scenarios.

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan ui

**Comment by DaanHoogland** [comment]
@LayonRibeiro , your code looks good but I do not get to edit the quota tariff I am expecting. https://qa.cloudstack.cloud/simulator/pr/9681/#/quotatariff/ . I think there is another biug preventing me from testing the edit functionality. During create the text box epands on request as expected though.

**Comment by LayonRibeiro** [comment]
"@DannHoogland, I tested the expansion of the textarea in both the creation and update forms for the rates, and in both cases, I achieved success."

 ### Create form



### Edit form

**Review by DaanHoogland — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@JoaoJandre I think this is a good to have UI bug fix...?

**Review by rohityadavcloud — APPROVED** [review]

**Review by JoaoJandre — APPROVED** [review]

**Pull request merged**
