### PR TITLE
CLOUDSTACK-9105: Logging enhancement: Handle/reference to track API c…

### PR DESCRIPTION
**Pull request by koushik-das**
…alls end to end in the MS logs

Added logid to logging framework, now all API call logs can be tracked with this id end to end

### CODE REVIEW

**Comment by koushik-das** [comment]
Now all logs related to an operation can be traced by running something like "grep logid:62314271 <MS logs>".

Sample logs
2015-12-02 12:40:27,628 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-1:ctx-9fb051eb job-939) (logid:62314271) Executing AsyncJobVO {id:939, userId: 2, accountId: 2, instanceType: VirtualMachine, instanceId: 144, cmd: org.apache.cloudstack.api.command.admin.vm.DeployVMCmdByAdmin, cmdInfo: {"id":"144","response":"json","serviceofferingid":"0381afb2-50ab-40ca-9a57-e5d12482b5a3","ctxDetails":"{\"interface com.cloud.dc.DataCenter\":\"4cea85aa-3dda-4b03-8caf-391198777fb3\",\"interface com.cloud.vm.VirtualMachine\":\"5fb88c3e-3879-45b0-9a34-47dc1b82b8a5\",\"interface com.cloud.offering.ServiceOffering\":\"0381afb2-50ab-40ca-9a57-e5d12482b5a3\",\"interface com.cloud.template.VirtualMachineTemplate\":\"f74be2e8-73be-11e5-8882-249684d59f9c\"}","cmdEventType":"VM.CREATE","ctxUserId":"2","zoneid":"4cea85aa-3dda-4b03-8caf-391198777fb3","hypervisor":"Simulator","iptonetworklist[0].networkid":"4156249e-2b1f-49cb-b333-c2032c0792c5","templateid":"f74be2e8-73be-11e5-8882-249684d59f9c","httpmethod":"GET","_":"1449040227133","uuid":"5fb88c3e-3879-45b0-9a34-47dc1b82b8a5","ctxAccountId":"2","ctxStartEventId":"1420"}, cmdVersion: 0, status: IN_PROGRESS, processStatus: 0, resultCode: 0, result: null, initMsid: 1, completeMsid: null, lastUpdated: null, lastPolled: null, created: null}

Even the HV resource logs are tagged using the same "logid" identifier.

2015-12-02 12:40:30,263 DEBUG [c.c.a.m.DirectAgentAttache] (DirectAgent-15:ctx-99c2667b) (logid:62314271) Seq 2-852024754503155726: Response Received: 
2015-12-02 12:40:30,266 DEBUG [c.c.a.t.Request] (DirectAgent-15:ctx-99c2667b) (logid:62314271) Seq 2-852024754503155726: Processing:  { Ans: , MgmtId: 1, via: 2(SimulatedAgent.40265aab-4037-41f7-a971-230b2cf50730), Ver: v1, Flags: 10, [{"com.cloud.agent.api.StartAnswer":{"vm":{"id":144,"name":"i-2-144-QA","type":"User","cpus":1,"minSpeed":500,"maxSpeed":500,"minRam":536870912,"maxRam":536870912,"arch":"x86_64","os":"CentOS 5.3 (32-bit)","bootArgs":"","enableHA":false,"limitCpuUse":false,"enableDynamicallyScaleVm":false,"vncPassword":"fE8JPrJ_58va5JFGCvzpYg","params":{"deployvm":"true"},"uuid":"5fb88c3e-3879-45b0-9a34-47dc1b82b8a5","disks":[{"data":{"org.apache.cloudstack.storage.to.VolumeObjectTO":{"uuid":"55ca5f13-f7e3-4e04-8cfe-e35e1c4f6e7f","volumeType":"ROOT","dataStore":{"org.apache.cloudstack.storage.to.PrimaryDataStoreTO":{"uuid":"7c07ec9b-a3c6-3466-ab5a-f5669ead0b22","id":1,"poolType":"NetworkFilesystem","host":"10.147.28.6","path":"/export/home/sandbox/primary0","port":2049,"url":"NetworkFilesystem://10.147.28.6/export/home/sandbox/primary0/?ROLE=Primary&STOREUUID=7c07ec9b-a3c6-3466-ab5a-f5669ead0b22"}},"name":"ROOT-144","size":100,"path":"8f44da97-efa5-400e-8b9c-fcef0399c9e4","volumeId":150,"vmName":"i-2-144-QA","accountId":2,"format":"RAW","provisioningType":"THIN","id":150,"deviceId":0,"hypervisorType":"Simulator"}},"diskSeq":0,"path":"8f44da97-efa5-400e-8b9c-fcef0399c9e4","type":"ROOT","_details":{"managed":"false","storagePort":"2049","storageHost":"10.147.28.6","volumeSize":"100"}},{"data":{"org.apache.cloudstack.storage.to.TemplateObjectTO":{"id":0,"format":"ISO","accountId":0,"hvm":false}},"diskSeq":3,"type":"ISO"}],"nics":[{"deviceId":0,"networkRateMbps":200,"defaultNic":true,"pxeDisable":false,"nicUuid":"f6da6502-7971-4b34-903b-15ba11247338","uuid":"4156249e-2b1f-49cb-b333-c2032c0792c5","ip":"10.1.1.172","netmask":"255.255.255.0","gateway":"10.1.1.1","mac":"02:00:04:52:00:8a","dns1":"10.147.28.6","broadcastType":"Vlan","trafficId":1,"type":"Guest","broadcastUri":"vlan://108","isolationUri":"vlan://108","isSecurityGroupEnabled":false}]},"result":true,"wait":0}}] }
2015-12-02 12:40:30,266 DEBUG [c.c.a.t.Request] (Work-Job-Executor-1:ctx-5ea59ec0 job-939/job-940 ctx-73b5d0fa) (logid:62314271) Seq 2-852024754503155726: Received:  { Ans: , MgmtId: 1, via: 2(SimulatedAgent.40265aab-4037-41f7-a971-230b2cf50730), Ver: v1, Flags: 10, { StartAnswer } }
2015-12-02 12:40:30,302 DEBUG [c.c.c.CapacityManagerImpl] (Work-Job-Executor-1:ctx-5ea59ec0 job-939/job-940 ctx-73b5d0fa) (logid:62314271) VM state transitted from :Starting to Running with event: OperationSucceededvm's original host id: 2 new host id: 2 host id before state transition: 2

**Comment by DaanHoogland** [comment]
LGTM, no tests done

**Comment by remibergsma** [comment]
LGTM based on these tests:

```
nosetests --with-marvin --marvin-config=${marvinCfg} -s -a tags=advanced,required_hardware=true \
component/test_vpc_redundant.py \
component/test_routers_iptables_default_policy.py \
component/test_routers_network_ops.py \
component/test_vpc_router_nics.py \
smoke/test_loadbalance.py \
smoke/test_internal_lb.py \
smoke/test_ssvm.py \
smoke/test_network.py

```

Result:

```
Create a redundant VPC with two networks with two VMs in each network ... === TestName: test_01_create_redundant_VPC_2tiers_4VMs_4IPs_4PF_ACL | Status : SUCCESS ===
ok
Create a redundant VPC with two networks with two VMs in each network and check default routes ... === TestName: test_02_redundant_VPC_default_routes | Status : SUCCESS ===
ok
Create a redundant VPC with two networks with two VMs in each network ... === TestName: test_03_create_redundant_VPC_1tier_2VMs_2IPs_2PF_ACL_reboot_routers | Status : SUCCESS ===
ok
Test iptables default INPUT/FORWARD policy on RouterVM ... === TestName: test_02_routervm_iptables_policies | Status : SUCCESS ===
ok
Test iptables default INPUT/FORWARD policies on VPC router ... === TestName: test_01_single_VPC_iptables_policies | Status : SUCCESS ===
ok
Test redundant router internals ... === TestName: test_01_isolate_network_FW_PF_default_routes_egress_true | Status : SUCCESS ===
ok
Test redundant router internals ... === TestName: test_02_isolate_network_FW_PF_default_routes_egress_false | Status : SUCCESS ===
ok
Test redundant router internals ... === TestName: test_01_RVR_Network_FW_PF_SSH_default_routes_egress_true | Status : SUCCESS ===
ok
Test redundant router internals ... === TestName: test_02_RVR_Network_FW_PF_SSH_default_routes_egress_false | Status : SUCCESS ===
ok
Create a VPC with two networks with one VM in each network and test nics after destroy ... === TestName: test_01_VPC_nics_after_destroy | Status : SUCCESS ===
ok
Create a VPC with two networks with one VM in each network and test default routes ... === TestName: test_02_VPC_default_routes | Status : SUCCESS ===
ok
Check the password file in the Router VM ... === TestName: test_isolate_network_password_server | Status : SUCCESS ===
ok
Check that the /etc/dhcphosts.txt doesn't contain duplicate IPs ... === TestName: test_router_dhcphosts | Status : SUCCESS ===
ok
Test to create Load balancing rule with source NAT ... === TestName: test_01_create_lb_rule_src_nat | Status : SUCCESS ===
ok
Test to create Load balancing rule with non source NAT ... === TestName: test_02_create_lb_rule_non_nat | Status : SUCCESS ===
ok
Test for assign & removing load balancing rule ... === TestName: test_assign_and_removal_lb | Status : SUCCESS ===
ok
Test to verify access to loadbalancer haproxy admin stats page ... === TestName: test02_internallb_haproxy_stats_on_all_interfaces | Status : SUCCESS ===
ok
Test create, assign, remove of an Internal LB with roundrobin http traffic to 3 vm's ... === TestName: test_01_internallb_roundrobin_1VPC_3VM_HTTP_port80 | Status : SUCCESS ===
ok
Test SSVM Internals ... === TestName: test_03_ssvm_internals | Status : SUCCESS ===
ok
Test CPVM Internals ... === TestName: test_04_cpvm_internals | Status : SUCCESS ===
ok
Test stop SSVM ... === TestName: test_05_stop_ssvm | Status : SUCCESS ===
ok
Test stop CPVM ... === TestName: test_06_stop_cpvm | Status : SUCCESS ===
ok
Test reboot SSVM ... === TestName: test_07_reboot_ssvm | Status : SUCCESS ===
ok
Test reboot CPVM ... === TestName: test_08_reboot_cpvm | Status : SUCCESS ===
ok
Test destroy SSVM ... === TestName: test_09_destroy_ssvm | Status : SUCCESS ===
ok
Test destroy CPVM ... === TestName: test_10_destroy_cpvm | Status : SUCCESS ===
ok
Test Remote Access VPN in VPC ... === TestName: test_vpc_remote_access_vpn | Status : SUCCESS ===
ok
Test VPN in VPC ... === TestName: test_vpc_site2site_vpn | Status : SUCCESS ===
ok
Test for port forwarding on source NAT ... === TestName: test_01_port_fwd_on_src_nat | Status : SUCCESS ===
ok
Test for port forwarding on non source NAT ... === TestName: test_02_port_fwd_on_non_src_nat | Status : SUCCESS ===
ok
Test for reboot router ... === TestName: test_reboot_router | Status : SUCCESS ===
ok
Test for Router rules for network rules on acquired public IP ... === TestName: test_network_rules_acquired_public_ip_1_static_nat_rule | Status : SUCCESS ===
ok
Test for Router rules for network rules on acquired public IP ... === TestName: test_network_rules_acquired_public_ip_2_nat_rule | Status : SUCCESS ===
ok
Test for Router rules for network rules on acquired public IP ... === TestName: test_network_rules_acquired_public_ip_3_Load_Balancer_Rule | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 34 tests in 17507.985s

OK
```


And:

```
nosetests --with-marvin --marvin-config=${marvinCfg} -s -a tags=advanced,required_hardware=false \
smoke/test_routers.py \
smoke/test_network_acl.py \
smoke/test_privategw_acl.py \
smoke/test_reset_vm_on_reboot.py \
smoke/test_vm_life_cycle.py \
smoke/test_vpc_vpn.py \
smoke/test_service_offerings.py \
component/test_vpc_offerings.py \
component/test_vpc_routers.py
```

Result:

```
Test router internal advanced zone ... === TestName: test_02_router_internal_adv | Status : SUCCESS ===
ok
Test restart network ... === TestName: test_03_restart_network_cleanup | Status : SUCCESS ===
ok
Test router basic setup ... === TestName: test_05_router_basic | Status : SUCCESS ===
ok
Test router advanced setup ... === TestName: test_06_router_advanced | Status : SUCCESS ===
ok
Test stop router ... === TestName: test_07_stop_router | Status : SUCCESS ===
ok
Test start router ... === TestName: test_08_start_router | Status : SUCCESS ===
ok
Test reboot router ... === TestName: test_09_reboot_router | Status : SUCCESS ===
ok
Test reset virtual machine on reboot ... === TestName: test_01_reset_vm_on_reboot | Status : SUCCESS ===
ok
Test advanced zone virtual router ... === TestName: test_advZoneVirtualRouter | Status : SUCCESS ===
ok
Test Deploy Virtual Machine ... === TestName: test_deploy_vm | Status : SUCCESS ===
ok
Test Multiple Deploy Virtual Machine ... === TestName: test_deploy_vm_multiple | Status : SUCCESS ===
ok
Test Stop Virtual Machine ... === TestName: test_01_stop_vm | Status : SUCCESS ===
ok
Test Start Virtual Machine ... === TestName: test_02_start_vm | Status : SUCCESS ===
ok
Test Reboot Virtual Machine ... === TestName: test_03_reboot_vm | Status : SUCCESS ===
ok
Test destroy Virtual Machine ... === TestName: test_06_destroy_vm | Status : SUCCESS ===
ok
Test recover Virtual Machine ... === TestName: test_07_restore_vm | Status : SUCCESS ===
ok
Test migrate VM ... === TestName: test_08_migrate_vm | Status : SUCCESS ===
ok
Test destroy(expunge) Virtual Machine ... === TestName: test_09_expunge_vm | Status : SUCCESS ===
ok
Test to create service offering ... === TestName: test_01_create_service_offering | Status : SUCCESS ===
ok
Test to update existing service offering ... === TestName: test_02_edit_service_offering | Status : SUCCESS ===
ok
Test to delete service offering ... === TestName: test_03_delete_service_offering | Status : SUCCESS ===
ok
Test for delete account ... === TestName: test_delete_account | Status : SUCCESS ===
ok
Test for Associate/Disassociate public IP address for admin account ... === TestName: test_public_ip_admin_account | Status : SUCCESS ===
ok
Test for Associate/Disassociate public IP address for user account ... === TestName: test_public_ip_user_account | Status : SUCCESS ===
ok
Test for release public IP address ... === TestName: test_releaseIP | Status : SUCCESS ===
ok
Test create VPC offering ... === TestName: test_01_create_vpc_offering | Status : SUCCESS ===
ok
Test VPC offering without load balancing service ... === TestName: test_03_vpc_off_without_lb | Status : SUCCESS ===
ok
Test VPC offering without static NAT service ... === TestName: test_04_vpc_off_without_static_nat | Status : SUCCESS ===
ok
Test VPC offering without port forwarding service ... === TestName: test_05_vpc_off_without_pf | Status : SUCCESS ===
ok
Test VPC offering with invalid services ... === TestName: test_06_vpc_off_invalid_services | Status : SUCCESS ===
ok
Test update VPC offering ... === TestName: test_07_update_vpc_off | Status : SUCCESS ===
ok
Test list VPC offering ... === TestName: test_08_list_vpc_off | Status : SUCCESS ===
ok
test_09_create_redundant_vpc_offering (integration.component.test_vpc_offerings.TestVPCOffering) ... === TestName: test_09_create_redundant_vpc_offering | Status : SUCCESS ===
ok
Test start/stop of router after addition of one guest network ... === TestName: test_01_start_stop_router_after_addition_of_one_guest_network | Status : SUCCESS ===
ok
Test reboot of router after addition of one guest network ... === TestName: test_02_reboot_router_after_addition_of_one_guest_network | Status : SUCCESS ===
ok
Test to change service offering of router after addition of one guest network ... === TestName: test_04_chg_srv_off_router_after_addition_of_one_guest_network | Status : SUCCESS ===
ok
Test destroy of router after addition of one guest network ... === TestName: test_05_destroy_router_after_addition_of_one_guest_network | Status : SUCCESS ===
ok
Test to stop and start router after creation of VPC ... === TestName: test_01_stop_start_router_after_creating_vpc | Status : SUCCESS ===
ok
Test to reboot the router after creating a VPC ... === TestName: test_02_reboot_router_after_creating_vpc | Status : SUCCESS ===
ok
Tests to change service offering of the Router after ... === TestName: test_04_change_service_offerring_vpc | Status : SUCCESS ===
ok
Test to destroy the router after creating a VPC ... === TestName: test_05_destroy_router_after_creating_vpc | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 41 tests in 8676.354s

OK
```

Haven't tested the actual functionality, this just shows you didn't break anything else.

**Comment by remibergsma** [comment]
Example logs from this branch:
```
2015-12-04 18:37:14,864 DEBUG [c.c.s.StatsCollector] (StatsCollector-2:ctx-601c739d) (logid:52f7b0de) VmStatsCollector is running...
2015-12-04 18:37:15,963 DEBUG [c.c.a.m.AgentManagerImpl] (AgentManager-Handler-15:null) (logid:) Ping from 2(kvm2)
2015-12-04 18:37:15,964 DEBUG [c.c.v.VirtualMachinePowerStateSyncImpl] (AgentManager-Handler-15:null) (logid:) Process host VM state report from ping process. host: 2
2015-12-04 18:37:15,968 DEBUG [c.c.v.VirtualMachinePowerStateSyncImpl] (AgentManager-Handler-15:null) (logid:) Process VM state report. host: 2, number of records in report: 2
2015-12-04 18:37:15,968 DEBUG [c.c.v.VirtualMachinePowerStateSyncImpl] (AgentManager-Handler-15:null) (logid:) VM state report. host: 2, vm id: 63, power state: PowerOn
2015-12-04 18:37:15,969 DEBUG [c.c.v.VirtualMachinePowerStateSyncImpl] (AgentManager-Handler-15:null) (logid:) VM power state does not change, skip DB writing. vm id: 63
2015-12-04 18:37:15,969 DEBUG [c.c.v.VirtualMachinePowerStateSyncImpl] (AgentManager-Handler-15:null) (logid:) VM state report. host: 2, vm id: 62, power state: PowerOn
2015-12-04 18:37:15,969 DEBUG [c.c.v.VirtualMachinePowerStateSyncImpl] (AgentManager-Handler-15:null) (logid:) VM power state does not change, skip DB writing. vm id: 62
2015-12-04 18:37:15,971 DEBUG [c.c.v.VirtualMachinePowerStateSyncImpl] (AgentManager-Handler-15:null) (logid:) Done with process of VM state report. host: 2
2015-12-04 18:37:18,355 DEBUG [c.c.a.m.AgentManagerImpl] (AgentManager-Handler-12:null) (logid:) SeqA 6-2861: Processing Seq 6-2861:  { Cmd , MgmtId: -1, via: 6, Ver: v1, Flags: 11, [{"com.cloud.agent.api.ConsoleProxyLoadReportCommand":{"_proxyVmId":63,"_loadInfo":"{\n  \"connections\": []\n}","wait":0}}] }
2015-12-04 18:37:18,359 DEBUG [c.c.a.m.AgentManagerImpl] (AgentManager-Handler-12:null) (logid:) SeqA 6-2861: Sending Seq 6-2861:  { Ans: , MgmtId: 90520732674657, via: 6, Ver: v1, Flags: 100010, [{"com.cloud.agent.api.AgentControlAnswer":{"result":true,"wait":0}}] }
2015-12-04 18:37:19,582 DEBUG [c.c.a.m.AgentManagerImpl] (AgentManager-Handler-11:null) (logid:) Ping from 5(s-62-VM)
2015-12-04 18:37:20,637 DEBUG [c.c.a.m.AgentManagerImpl] (AgentManager-Handler-14:null) (logid:) Ping from 6(v-63-VM)
2015-12-04 18:37:22,051 INFO  [o.a.c.f.j.i.AsyncJobManagerImpl] (AsyncJobMgr-Heartbeat-1:ctx-354e88d7) (logid:910493fb) Begin cleanup expired async-jobs
2015-12-04 18:37:22,054 INFO  [o.a.c.f.j.i.AsyncJobManagerImpl] (AsyncJobMgr-Heartbeat-1:ctx-354e88d7) (logid:910493fb) End cleanup expired async-jobs
2015-12-04 18:37:23,386 DEBUG [c.c.a.m.AgentManagerImpl] (AgentManager-Handler-4:null) (logid:) SeqA 6-2863: Processing Seq 6-2863:  { Cmd , MgmtId: -1, via: 6, Ver: v1, Flags: 11, [{"com.cloud.agent.api.ConsoleProxyLoadReportCommand":{"_proxyVmId":63,"_loadInfo":"{\n  \"connections\": []\n}","wait":0}}] }
2015-12-04 18:37:23,389 DEBUG [c.c.a.m.AgentManagerImpl] (AgentManager-Handler-4:null) (logid:) SeqA 6-2863: Sending Seq 6-2863:  { Ans: , MgmtId: 90520732674657, via: 6, Ver: v1, Flags: 100010, [{"com.cloud.agent.api.AgentControlAnswer":{"result":true,"wait":0}}] }
```

screen shot 2015-12-04 at 19 42 44

@koushik-das Like it! My only remark is that some lines have an empty 'logid:' which I'd recommend leaving out (shown in log, not in image).

**Pull request merged**
