### PR TITLE
ui: refactor config update/reset notification

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Follow up from https://github.com/apache/cloudstack/pull/9628#discussion_r1743492807

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan ui

**Review by vishesh92 — APPROVED** [review]
lgtm. tested in QA. working as expected.

**Review by rohityadavcloud — APPROVED** [review]
LGTM - good refactoring, didn't test it though

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Pull request merged**
