### PR TITLE
maven: Upgrade dependency versions and to maven 3.3.9

### PR DESCRIPTION
**Pull request by bhaisaab**
Skipped: (but upgraded to latest minor release)
- Major spring framework version
- Servlet version
- Embedded jetty version
- Mockito version (beta)
- Mysql lib minor version upgrade (breaks mysql-ha plugin)

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@bhaisaab could you move the version numbers to the root pom instead of updating the project poms?

**Comment by bhaisaab** [comment]
@DaanHoogland sure will do this weekend, this was mostly edited by the maven versions plugin. Do you want to work on this, as you may have some version related changes?

**Comment by DaanHoogland** [comment]
I will integrate them, and make a PR to this PR

**Comment by bhaisaab** [comment]
@DaanHoogland how about this, I close this PR; push the branch to asf remote and you continue on that branch keeping the same PR?

**Pull request closed without merging**
