### PR TITLE
UI bug fix: Cannot deploy VM from ISO

### PR DESCRIPTION
**Pull request by ustcweizhou**
## Description

While deploy a vm from ISO on UI, the instance wizard is not working in vm overview step.

this is regression issue of #3271 

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by rhtyd** [comment]
cc @shwstppr @DaanHoogland @andrijapanicsb

**Comment by andrijapanicsb** [comment]
image

indeed... wow

**Comment by andrijapanicsb** [comment]
@nvazquez can you also take a look - the issue is valid, and I would like to make sure the OVF stuff is not broken = then merge it. thx

**Comment by nvazquez** [comment]
The workaround is clicking on Next once this appearts. I'll work on a fix

**Comment by andrijapanicsb** [comment]
the fix is there @nvazquez ?

**Comment by andrijapanicsb** [comment]
@blueorangutan package

**Comment by andrijapanicsb** [comment]
(having some nasty JS overrides in my local lab, so need to build from packages - less effort)

**Comment by andrijapanicsb** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
Yes @andrijapanicsb, thanks @ustcweizhou I haven't seen the fix sorry

**Comment by andrijapanicsb** [comment]
2 x LGTM, manual testing. Regression testing not needed since a simple JS change/not applicable.

Merging.

**Comment by andrijapanicsb** [comment]
Thanks for noticing this @weizhouapache

**Pull request merged**
