### PR TITLE
Set version 4.6.3-SNAPSHOT in 4.6 branch

### PR DESCRIPTION
**Pull request by remibergsma**
- setnextversion.sh
- upgrade path

Build succeeds:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 08:44 min
[INFO] Finished at: 2015-12-21T14:13:29+01:00
[INFO] Final Memory: 123M/1578M
[INFO] ------------------------------------------------------------------------
```

Will try upgrade soon.

### CODE REVIEW

**Comment by DaanHoogland** [comment]
looks good

**Comment by rafaelweingartner** [comment]
LGTM,
Looking at that database upgrade checker that does not just check but also upgrade the ACS schema, I got me thinking that there has to be a better way to do that. Have we started any discussions about how to improve and facilitate that process?

**Comment by remibergsma** [comment]
@rafaelweingartner True story, the faster we release versions the harder it becomes. It needs to be changed, preferably in a tool outside of CloudStack. We should investigate what's already available, because we aren't the only one with this problem. For now, I'll just do the monkey work ;-)

I can do 4.7 and master once the 4.7 branch gets mirrored to Github. Will check again tonight.

**Comment by rafaelweingartner** [comment]
I understand you; I will have a look at that, to see how other projects deal with that kind of problem. If I find something interesting I will bring that to the dev list

**Comment by remibergsma** [comment]
And it works:
```
INFO  [o.a.c.s.l.CloudStackExtendedLifeCycle] (main:null) Running system integrity checker com.cloud.upgrade.DatabaseUpgradeChecker@847ca9d
INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) Grabbing lock to check for database upgrade.
INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) DB version = 4.6.2 Code Version = 4.6.3-SNAPSHOT
INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) Database upgrade must be performed from 4.6.2 to 4.6.3-SNAPSHOT
INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) Cleaning upgrades because all management server are now at the same version
INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) Cleanup upgrade Upgrade462to463 to upgrade from 4.6.2-4.6.3 to 4.6.3
INFO  [o.a.c.s.l.CloudStackExtendedLifeCycle] (main:null) Configuring CloudStack Components
INFO  [o.a.c.s.l.CloudStackExtendedLifeCycle] (main:null) Done Configuring CloudStack Components
```

**Pull request merged**
