### PR TITLE
Updated since and validations attributes for the ikeversion and splitconnections parameters in vpn customer gateway cmd(s)

### PR DESCRIPTION
**Pull request by sureshanaparti**
### Description

This PR updates since and validations  attributes for the ikeversion and splitconnections parameters in vpn customer gateway cmd(s)

...

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by Pearl1594** [comment]
@blueorangutan package

**Review by shwstppr — APPROVED** [review]

**Review by Pearl1594 — APPROVED** [review]
LGTM

**Comment by Pearl1594** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
LGTM - let's merge after smoketest pass. Thanks @sureshanaparti

**Pull request merged**
