### PR TITLE
CLOUDSTACK-9697: Added better error message user if tries to shrink

### PR DESCRIPTION
**Pull request by rashmidixit**
the VM ROOT volume size

Skip the API call altogether if the UI detects this and throw a more user friendly message

### CODE REVIEW

**Comment by rashmidixit** [comment]
This is related to a closed merge request which I had raised on 4.9 (https://github.com/apache/cloudstack/pull/1855). Re-raising this on master branch.

**Comment by rashmidixit** [comment]
@karuturi Can you please review ?

**Comment by wido** [comment]
LGTM

**Comment by rhtyd** [comment]
LGTM

**Pull request merged**
