### PR TITLE
UI: Fix create zone wizard on mobile view

### PR DESCRIPTION
**Pull request by utchoang**
### Description
This PR for fixes create zone form in mobile view

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### Screenshots (if appropriate):
After fixed:
imageimage

### CODE REVIEW

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by rhtyd** [comment]
@blueorangutan ui

**Comment by davidjumani** [comment]
Will review after https://github.com/apache/cloudstack/pull/4764 since it has a shared commit

**Comment by davidjumani** [comment]
@utchoang Could you remove https://github.com/apache/cloudstack/pull/4764/commits/d998f2709f1cf1ea5fa957e0b90dfff1b46c17f9 and push ? Thanks

**Comment by davidjumani** [comment]
@blueorangutan ui

**Review by davidjumani — APPROVED** [review]
Working fine in mobile and desktop mode

**Comment by rhtyd** [comment]
@utchoang can you fix the conflict against latest 4.15 branch?

**Review by rhtyd — APPROVED** [review]
LGTM - basing based on David's testing and lgtm

**Pull request merged**
