### PR TITLE
engine-orchestration,vmware: hypervisor migration during start vm migration

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

This PR enables the hypervisor strategy for VM migration when a VM is to be started in a different cluster for VMware.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan test matrix

**Review by DaanHoogland — APPROVED** [review]
clgtm, can you advice on test approach @shwstppr ? I mean in addition to your added unit tests?

**Review by rohityadavcloud — APPROVED** [review]
LGTM

**Comment by DaanHoogland** [comment]
> Need to investigate the VMware failures. Though they seem unrelated as we are seeing them on other PRs as well, eg: #7404

indeed, but the test_snapshot failure is extra! I think the test_vm_deployment_planner should get there own ticket (if they persist)

**Comment by shwstppr** [comment]
Tested with latest nightly and it seems error with test_vm_deployment_planner.py were intermittent or environment related,
```
[root@ref-trl-4867-v-M7-abhishek-kumar-marvin marvin]# nosetests --with-xunit --xunit-file=results.xml --with-marvin --marvin-config=./ref-trl-4867-v-M7-abhishek-kumar-advanced-cfg -s -a tags=advanced --hypervisor=Vmware tests/smoke/test_vm_deployment_planner.py 
/usr/local/lib/python3.6/site-packages/paramiko/transport.py:32: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
  from cryptography.hazmat.backends import default_backend

==== Marvin Init Started ====

=== Marvin Parse Config Successful ===

=== Marvin Setting TestData Successful===

==== Log Folder Path: /marvin/MarvinLogs/May_10_2023_11_53_53_U8PK9N All logs will be available here ====

=== Marvin Init Logging Successful===

==== Marvin Init Successful ====
=== TestName: test_01_deploy_vm_on_specific_host | Status : SUCCESS ===

=== TestName: test_02_deploy_vm_on_specific_cluster | Status : SUCCESS ===

=== TestName: test_03_deploy_vm_on_specific_pod | Status : SUCCESS ===

=== TestName: test_04_deploy_vm_on_host_override_pod_and_cluster | Status : SUCCESS ===

=== TestName: test_05_deploy_vm_on_cluster_override_pod | Status : SUCCESS ===

=== Final results are now copied to: /marvin//MarvinLogs/test_vm_deployment_planner_0VX1NC ===
```

test_snapshots.py failed while getting template in the ^^ VMware run,
```
CRITICAL: EXCEPTION: None: ['Traceback (most recent call last):\n', ' File "/usr/local/lib/python3.6/site-packages/nose/suite.py", line 210, in run\n self.setUp()\n', ' File "/usr/local/lib/python3.6/site-packages/nose/suite.py", line 293, in setUp\n self.setupContext(ancestor)\n', ' File "/usr/local/lib/python3.6/site-packages/nose/suite.py", line 316, in setupContext\n try_run(context, names)\n', ' File "/usr/local/lib/python3.6/site-packages/nose/util.py", line 471, in try_run\n return func()\n', ' File "/marvin/tests/smoke/test_snapshots.py", line 67, in setUpClass\n assert False, "get_test_template() failed to return template"\n', 'AssertionError: get_test_template() failed to return template\n']
``

Will run VMware tests again

@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test rocky8 vmware-67u3

**Comment by rohityadavcloud** [comment]
@blueorangutan test rocky8 vmware-67u3

**Comment by shwstppr** [comment]
@blueorangutan test rocky8 vmware-67u3

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan test rocky8 vmware-67u3

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test matrix

**Comment by shwstppr** [comment]
@blueorangutan test rocky8 vmware-67u3

**Comment by DaanHoogland** [comment]
@blueorangutan test rocky8 vmware-67u3

**Review by vladimirpetrov — APPROVED** [review]
LGTM based on manual testing (tested with VMWare 7.0.3).

**Pull request merged**
