### PR TITLE
Honour promiscuous mode from networkOffering

### PR DESCRIPTION
**Pull request by Spaceman1984**
## Description

When adding a nic to a vm, the network offiring details were ignored. This change passes the network offering details to vsphere.

Fixes: #3565 
## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

This was tested by creating 2 instances on separate networks. Adding a nic to one of the instances and then verifying if promiscuous mode was not changed on vsphere.

### CODE REVIEW

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by borisstoyanov** [comment]
LGTM, tested manually when adding new VM to the network it does not change to mode. Can be merged when smoketests pass

**Comment by DaanHoogland** [comment]
@Spaceman1984 isn't this a bug fix (and shouldn't it go on 4.13)?

**Comment by Spaceman1984** [comment]
I will make the change on 4.13

**Comment by Spaceman1984** [comment]
Rebased to 4.13

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Pull request merged**
