### PR TITLE
Closing PRs older than 1 month and without activity

### PR DESCRIPTION
**Pull request by remibergsma**
As proposed here: http://cloudstack.markmail.org/search/?q=#query:+page:1+mid:rkptskqvajs7n7zj+state:results

This will close these PRs:
https://github.com/apache/cloudstack/pull/577
https://github.com/apache/cloudstack/pull/566
https://github.com/apache/cloudstack/pull/562
https://github.com/apache/cloudstack/pull/561
https://github.com/apache/cloudstack/pull/556
https://github.com/apache/cloudstack/pull/555
https://github.com/apache/cloudstack/pull/554
https://github.com/apache/cloudstack/pull/548
https://github.com/apache/cloudstack/pull/544
https://github.com/apache/cloudstack/pull/540
https://github.com/apache/cloudstack/pull/384
https://github.com/apache/cloudstack/pull/372

If you want a PR to stay open, comment to the PR and let me know.

### CODE REVIEW

**Comment by DaanHoogland** [comment]
https://github.com/apache/cloudstack/pull/508 was worked on 14 days ago by @resmo and @wilderrodrigues

**Comment by remibergsma** [comment]
@DaanHoogland That's true. Although @wilderrodrigues will take over the PR and needs to create a new one. But let's stick to the proposal indeed. I'll remove #508 from the list.

**Comment by DaanHoogland** [comment]
I did not send a :-1: to dev@. I did not omit that mail by mistake (sorry for the double negative). the proposal seems radical (17 july is phased out on 17  August) but house cleaning is needed. let's make a PR like this on a weekly basis.

**Comment by remibergsma** [comment]
@DaanHoogland Weekly basis is OK with me!

**Comment by bhaisaab** [comment]
All, let's not do this for multiple reasons;

- by closing a PR which has not got attention we risk forgetting about it and losing the contribution
- generally those of us who have worked for long in the community or have dayjob colleagues working in the community, have better chances in getting their PRs merged; for new contributors this pattern is not encouraging and certainly not welcoming if their PRs get closed just because it did not caught any attention in one month's time
- our community works on the premise that everyone is a contributor working as per their convenience, interest and time, on top of this the developer community is not very large to ensure that all PRs will get attention or review within a months time of its arrival
- the requirement of 2 LGTM on each review makes it too much process-oriented that costs time and efforts, sometimes fixes are small but getting them merged has taken more time

**Comment by remibergsma** [comment]
@bhaisaab OK, let's leave it for now and discuss later. I will close the PR.

**Comment by DaanHoogland** [comment]
@bhaisaab @remibergsma : Rohit has some good points there and some that can be avoided. Noticably a PR that hasn't gotten any attention from the community should not be closed. But when several people have given feedback and the author does not respond it is of a different case. Let's revisit if the present backlog groth continues.

**Pull request closed without merging**
