### PR TITLE
UI: Add cancel button missing on dialog

### PR DESCRIPTION
**Pull request by utchoang**
### Description
This PR for the fix to add cancel button missing on dialog

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### Screenshots (if appropriate):
After fix:
image

### CODE REVIEW

**Comment by utchoang** [comment]
Closed due to incorrect branch merging

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by rhtyd** [comment]
@blueorangutan ui

**Comment by davidjumani** [comment]
@utchoang Could you remove the commit https://github.com/apache/cloudstack/pull/4763/commits/d998f2709f1cf1ea5fa957e0b90dfff1b46c17f9 and push ?

**Comment by davidjumani** [comment]
@blueorangutan ui

**Review by davidjumani — APPROVED** [review]
LGTM!

**Pull request merged**
