### PR TITLE
VR: fix public-key is missing in VR after acquiring public IP

### LINKED ISSUE #6765: Using API's created instances gives error Permission denied (publickey) under the VPC network
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API, VPC, SSH
~~~

##### CLOUDSTACK VERSION

~~~
4.16.0, 4.17.0.1 
~~~

##### CONFIGURATION

Advanced Networking - VPC

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Not able to access the VM using the SSH keypair attached at the time of instance creation with VPC network using API's. If we reinstall such instance then it starts working.  Also if we do this with the Cloud Stack UI it is working as expected in the first attempt.

##### STEPS TO REPRODUCE

~~~
Steps followed using APIs:
1. Create project
2. Create VPC network
3. Register SSH key pair
4. Create new instance
5. Attach this instance to the VPC network
6. Acquire and associate public ip address to the VPC network and static nat with the instance
7. Try to access this instance using public ip and ssh key
Everything working fine, We can see the registered ssh key pair in the Cloud Stack UI under the instance details. But at the time of logging in using ssh it gives error  **Permission denied (publickey).**

~~~

##### EXPECTED RESULTS

SSH login should work in the first attempt if instance created under the VPC network using API's

##### ACTUAL RESULTS

Permission denied (publickey)

~~~
ssh ubuntu@ip_address
~~~

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This fixes #6765

The following command (in vm) worked before acquiring IP but did not work after that 
`root$ curl http://<gateway>/latest/meta-data/public-keys`

in VR, the file is empty:
```
root@r-40-VM:/var/www/html/metadata/<VM IP># ls -l public-keys
 -rw-r--r-- 1 root root 0 Jan 17 18:41 public-keys
```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
cltgm

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
LGTM, didn't test it.
@blueorangutan test

**Review by stephankruggg — APPROVED** [review]
CLGTM

**Comment by DaanHoogland** [comment]
@weizhouapache copying from the issue, did you test this using the below scenario?
```
Steps followed using APIs:
1. Create project
2. Create VPC network
3. Register SSH key pair
4. Create new instance
5. Attach this instance to the VPC network
6. Acquire and associate public ip address to the VPC network and static nat with the instance
7. Try to access this instance using public ip and ssh key
Everything working fine, We can see the registered ssh key pair in the Cloud Stack UI under the instance details. But at the time of logging in using ssh it gives error  **Permission denied (publickey).**
```

**Comment by weizhouapache** [comment]
> 6. Acquire and associate public ip address to the VPC network and static nat with the instance

@DaanHoogland 
yes, I have tested it. sometimes it worked, sometimes it did not work, depends on when the vm gets the ssh key from VR (before or after associating public IP). 

with this PR, the issue is gone.

**Pull request merged**
