### PR TITLE
Remove unnecessary escape method

### PR DESCRIPTION
**Pull request by BryanMLima**
### Description

Currently, the API `quotaEmailTemplateUpdate` escapes JavaScript strings in the email templates for the `subject` and `body` fields. However, when using the API `quotaEmailTemplateList` the data returned were not unescaped, causing inconsistencies in the text. This PR aims to fix this behavior by removing the escape method in the API `quotaEmailTemplateUpdate` as it was unnecessary.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### How Has This Been Tested?
This was tested in a local lab by changing the email templates in the `subject` and `body` field with special characters. After the emails arrived, the contents were correctly displayed.

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
clgtm, I would like to know why these were added in the first place and if they got obsoleted for some reason or it was a bug to add them in the first place.

**Review by JoaoJandre — APPROVED** [review]
CLGTM

**Review by GutoVeronezi — APPROVED** [review]
CLGTM

**Comment by GutoVeronezi** [comment]
@blueorangutan package

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
@BryanMLima I haven't seen the code lately, one of the concerns could be somebody could set an browser based XSS code withing the email template 
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by RodrigoDLopez — APPROVED** [review]
lgtm

**Comment by BryanMLima** [comment]
Hi @DaanHoogland, sorry for the delay, the method did not make any sense as it was only for JS strings; it did not prevent any XSS attacks.  
  
As for the XSS attack @rohityadavcloud, I investigated this concern, and tested a lot of scenarios using OWASP [Cheatsheet](https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html) as reference. Displaying the contents of the email template on the UI with malicious code did not result in any problems, as it is inside a component. However, with further investigation, there is a lack of validation upon creating domains and accounts regarding their names. Creating a domain with the name `<h1>test</h1>` and using the `${domainName}` inside the email template would result in the email client rendering that HTML tag. I tested with a simple `script` tag; however, most email clients already filter these tags, and therefore, it was totally omitted from the email.

In this case, to resolve this problem I escaped the possible HTML in the domain and account names variables to prevent any issues. Finally, it may be interesting to investigate the validation on account and domain names to block users from using any HTML tags and prevent any future problems.

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@BryanMLima can you look at the conflict and at the code smells:

> SonarCloud Quality Gate failed.    [Quality Gate failed](https://sonarcloud.io/dashboard?id=apache_cloudstack&pullRequest=6692)
> 
> [Bug](https://sonarcloud.io/project/issues?id=apache_cloudstack&pullRequest=6692&resolved=false&types=BUG) [A](https://sonarcloud.io/project/issues?id=apache_cloudstack&pullRequest=6692&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=apache_cloudstack&pullRequest=6692&resolved=false&types=BUG) [Vulnerability](https://sonarcloud.io/project/issues?id=apache_cloudstack&pullRequest=6692&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=apache_cloudstack&pullRequest=6692&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=apache_cloudstack&pullRequest=6692&resolved=false&types=VULNERABILITY) [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=apache_cloudstack&pullRequest=6692&resolved=false&types=SECURITY_HOTSPOT) [A](https://sonarcloud.io/project/security_hotspots?id=apache_cloudstack&pullRequest=6692&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=apache_cloudstack&pullRequest=6692&resolved=false&types=SECURITY_HOTSPOT) [Code Smell](https://sonarcloud.io/project/issues?id=apache_cloudstack&pullRequest=6692&resolved=false&types=CODE_SMELL) [B](https://sonarcloud.io/project/issues?id=apache_cloudstack&pullRequest=6692&resolved=false&types=CODE_SMELL) [7 Code Smells](https://sonarcloud.io/project/issues?id=apache_cloudstack&pullRequest=6692&resolved=false&types=CODE_SMELL)
> 
> [](https://sonarcloud.io/component_measures?id=apache_cloudstack&pullRequest=6692&metric=new_coverage&view=list) [73.3% Coverage](https://sonarcloud.io/component_measures?id=apache_cloudstack&pullRequest=6692&metric=new_coverage&view=list) [](https://sonarcloud.io/component_measures?id=apache_cloudstack&pullRequest=6692&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=apache_cloudstack&pullRequest=6692&metric=new_duplicated_lines_density&view=list)

**Review by stephankruggg — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Pull request merged**
