### PR TITLE
smoke test: fixes test_vm_deployment_planner

### LINKED ISSUE #7717: testClient has hypervisortype kvm when running on vmware
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
marvin
~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### SUMMARY

When running test_vm_deployment_planner.py on vmware, `test_01_deploy_vm_on_specific_host` fails with an exception because the template to deploy a VM, cannot be found. debugging found that the template for KVM is being looked for and this fails.

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR...

This doesn't fix #7717 , but removes the abundant requirement from test_vm_deployment_planner, which looks for a specific template using the wrong hypervisor. The described issue in #7717 remains that the testclient doesn't have the right type of hypervisor configured.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [x] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan test rocky8 vmware-67u3

**Comment by DaanHoogland** [comment]
@blueorangutan test rocky8 vmware-67u3

**Comment by DaanHoogland** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan test rocky8 vmware-67u3

**Comment by DaanHoogland** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by DaanHoogland** [comment]
@shwstppr @weizhouapache can you review?

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Review by shwstppr — COMMENTED** [review]
Same code `hypervisor=self.hypervisor` is used across different tests so I'm not completely sure about this change

**Comment by weizhouapache** [comment]
> Same code `hypervisor=self.hypervisor` is used across different tests so I'm not completely sure about this change

agree with @shwstppr .
code looks ok. but I am also wondering if we need this change and what the benefit is.

**Comment by DaanHoogland** [comment]
> > Same code `hypervisor=self.hypervisor` is used across different tests so I'm not completely sure about this change
> 
> agree with @shwstppr . code looks ok. but I am also wondering if we need this change and what the benefit is.

The real issue is #7717; the hypervisor is not set correctly in the test client, but for these tests it is irrelevant so no reason to set it. Just getting the template is effectively the same action. a test env with a mixed zone may not be able to execute it but only if the hypervisor type is explicitely set to one for which a template is not of the default  hypervisortype.
The test assumes intelligence that it doesn't have itself.

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test rocky8 vmware-67u3

**Comment by DaanHoogland** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by DaanHoogland** [comment]
> > > Same code `hypervisor=self.hypervisor` is used across different tests so I'm not completely sure about this change
> > 
> > 
> > agree with @shwstppr . code looks ok. but I am also wondering if we need this change and what the benefit is.
> 
> The real issue is #7717; the hypervisor is not set correctly in the test client, but for these tests it is irrelevant so no reason to set it. Just getting the template is effectively the same action. a test env with a mixed zone may not be able to execute it but only if the hypervisor type is explicitely set to one for which a template is not of the default hypervisortype. The test assumes intelligence that it doesn't have itself.

@shwstppr @weizhouapache , is this explanation enough?

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
> > > > Same code `hypervisor=self.hypervisor` is used across different tests so I'm not completely sure about this change
> > > 
> > > 
> > > agree with @shwstppr . code looks ok. but I am also wondering if we need this change and what the benefit is.
> > 
> > 
> > The real issue is #7717; the hypervisor is not set correctly in the test client, but for these tests it is irrelevant so no reason to set it. Just getting the template is effectively the same action. a test env with a mixed zone may not be able to execute it but only if the hypervisor type is explicitely set to one for which a template is not of the default hypervisortype. The test assumes intelligence that it doesn't have itself.
> 
> @shwstppr @weizhouapache , is this explanation enough?

@DaanHoogland 
I still do not understand what the PR aims to fix.
In mixed zone, if the hypervisor is incorrect, we can update test_data.py to use correct hypervisor.

with this PR, the test will get the template with random (?) hypervisor, right ?

**Comment by DaanHoogland** [comment]
> with this PR, the test will get the template with random (?) hypervisor, right ?

you can call it random, but in an env with only one hypervisor it will get the template registered instead of trying to force to get the kvm template. this is why the tests would fail on vmware.

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 vmware-67u3

**Comment by weizhouapache** [comment]
> > with this PR, the test will get the template with random (?) hypervisor, right ?
> 
> you can call it random, but in an env with only one hypervisor it will get the template registered instead of trying to force to get the kvm template. this is why the tests would fail on vmware.

ok, let's run some tests on vmware

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 vmware-67u3

**Comment by weizhouapache** [comment]
@blueorangutan test ubuntu22 vmware-70u3

**Review by weizhouapache — APPROVED** [review]

**Comment by weizhouapache** [comment]
@blueorangutan test ubuntu22 vmware-70u3

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 vmware-67u3

**Comment by weizhouapache** [comment]
@blueorangutan test ubuntu22 vmware-70u3

**Review by rohityadavcloud — APPROVED** [review]
LGTM haven't tested it

**Pull request merged**
