### PR TITLE
ui: vmware vm import-unmanage

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Adds UI for importing and unmanaging VMs.
A new navigation section - Tools has been added in the UI.

Doc PR: https://github.com/apache/cloudstack-documentation/pull/221

import-unmanage-instances

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):
Screenshot 2021-06-18 at 13-20-03 Import-Export Instances - CloudStack

Screenshot 2021-06-18 at 13-17-07 Import-Export Instances - CloudStack

Screenshot 2021-06-18 at 13-18-26 Import-Export Instances - CloudStack

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by rhtyd — COMMENTED** [review]
LGTM, basic checks, licenses in the new files and overall code. UI changes needs manual testing.

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by utchoang — APPROVED** [review]
LGTM!

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by borisstoyanov — APPROVED** [review]
LGTM, based on manual verification

**Comment by shwstppr** [comment]
Last commit unrelated to import wizard/form. A change in UI component was causing some fields not visible in AddNetworkOffering form. Fixed now.

@blueorangutan ui

**Review by rhtyd — APPROVED** [review]

**Comment by andrijapanicsb** [comment]
> 
> 
> @blueorangutan ui
> 
> Last commit added to use UI component added with [041948c](https://github.com/apache/cloudstack/commit/041948c04f8b20bebe74f34564c912d19c91bde0)

This doesn't explain much what was changed (to me at least) and it comes after LGTM from Boris (and the internal review from me) @shwstppr . Also some conflicts are there. thx

**Comment by shwstppr** [comment]
@andrijapanicsb Fixed conflicts
Commit in question b3e2ace changed the tooltip code for form items.
Screenshot from 2021-07-19 12-23-02
Before 041948c (#5133), above icon was shown with code,
```
<span slot="label">
  {{ $t('label.displayname') }}
  <a-tooltip :title="apiParams.displayname.description">
    <a-icon type="info-circle" style="color: rgba(0,0,0,.45)" />
  </a-tooltip>
</span>
```
With PR #5133, new Vue component (TooltipLabel.vue) was added which allowed above code to be refactored as,
```
<tooltip-label slot="label" :title="$t('label.displayname')" :tooltip="apiParams.displayname.description"/>
```
PR #5133 was merged into `main` after your review.

@blueorangutan ui

**Pull request merged**
