### PR TITLE
vr: Fix vpc router in UNKNOWN state

### PR DESCRIPTION
**Pull request by ustcweizhou**
## Description

If there are more than 10 vpc tiers or public ip subnets in a VPC, eth1X will be added in vpc router.
The redundant state is UNKNOWN in this case.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

creaete more than 10 vpc tiers, then vpc router will be UNKNOWN
it can be fixed by this commit.

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
I've tried kicking at least 5 environments/builds now. For some reason the systemvms fail to start with this PR, can you check @ustcweizhou

**Comment by rhtyd** [comment]
Let try again against master
@blueorangutan package

**Comment by ustcweizhou** [comment]
@rhtyd if it still fails I will update the PR to use "grep -w eth0/eth1"

**Comment by rhtyd** [comment]
Okay @ustcweizhou let me test one more time.
@blueorangutan test

**Comment by ustcweizhou** [comment]
@rhtyd I have updated the code to use "grep -w"

**Comment by ustcweizhou** [comment]
@blueorangutan package

**Comment by ustcweizhou** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@ustcweizhou the previous show dev syntax LGTM, can you put that back in?

**Comment by rhtyd** [comment]
Tests lgtm, I'll rekick one more time.
@blueorangutan package

**Comment by ustcweizhou** [comment]
@rhtyd ok

**Comment by rhtyd** [comment]
If the next run passes or does not have common errors from the previous run, we should merge this.
@blueorangutan test

**Pull request merged**
