### PR TITLE
Upgrade org.json:json version

### LINKED ISSUE #8696: cloudstack uses an org.json:json jar version that is not OSS friendly
https://github.com/apache/cloudstack/blob/8f6721ed4c4e1b31081a951c62ffbe5331cf16d4/pom.xml#L162

Please use a version from 2023/2024. There are security fixes (CVEs).

The main issue is the license. It was only made properly public domain in late 2022. Prior to that, it had a nonsensical license - that restricted its use for evil. Please read https://www.apache.org/legal/resolved.html (section about JSON license).

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR fixes #8696 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan test matrix

**Review by shwstppr — APPROVED** [review]
LGTM. I had to upgrade in #8674

**Review by sureshanaparti — APPROVED** [review]
LGTM

**Comment by DaanHoogland** [comment]
@blueorangutan test alma9 kvm-alma9

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by rohityadavcloud** [comment]
@blueorangutan test ol9 kvm-ol9

**Comment by DaanHoogland** [comment]
@blueorangutan test alma9 kvm-alma9

**Comment by DaanHoogland** [comment]
@sureshanaparti @vishesh92 , do you think we need more testing for this (cc @borisstoyanov )

**Pull request merged**
