### PR TITLE
updated install-non-oss with vmware v7.0 and v8.0

### PR DESCRIPTION
**Pull request by oferchen**
### Description

This PR...

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
thanks for the pr @oferchen 
actually more packages are needed
see https://github.com/shapeblue/cloudstack-nonoss/blob/main/install-non-oss.sh

**Comment by oferchen** [comment]
> thanks for the pr @oferchen actually more packages are needed see https://github.com/shapeblue/cloudstack-nonoss/blob/main/install-non-ossI also added vsphere and customer connect

**Comment by rohityadavcloud** [comment]
cc @nvazquez @Pearl1594 
@oferchen I think what @weizhouapache is more appropriate it’s because most of us or our CI automation don’t use this script anymore.

**Comment by oferchen** [comment]
> cc @nvazquez @Pearl1594 @oferchen I think what @weizhouapache is more appropriate it’s because most of us or our CI automation don’t use this script anymore.

As long as it is included in the repository might as well be updated and functional.

**Comment by oferchen** [comment]
This will forever fail because the files are proprietary and not available in this repo. Can someone please bypass the test?

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@rohityadavcloud @weizhouapache , I agree with @oferchen that we should not keep an outdated version in the repository if we can help it. So we need to apply this or remove it in my opinion. What do you think?

**Review by rohityadavcloud — APPROVED** [review]
LGTM, however, this file isn't maintained.

**Pull request merged**
