### PR TITLE
Throwing error if boot type or boot mode specified while deploying VMs on VMware

### PR DESCRIPTION
**Pull request by davidjumani**
## Description
VMware does not honour boot type or boot mode for templates, so throwing an error if it is passed

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?
TODO

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by andrijapanicsb** [comment]
Let's please move this one on top of the PR4307, as it is very related - easier to test. THx

**Comment by DaanHoogland** [comment]
looks good but agree with @andrijapanicsb , this is (only) valuable in combination with that PR, @davidjumani

**Comment by davidjumani** [comment]
Added https://github.com/apache/cloudstack/pull/4307/commits/d0180fb0260d9f05c277ade935861024913fa95b

**Pull request closed without merging**
