### PR TITLE
 	CLOUDSTACK-9980: Fix for DNS after network restart with clean up.

### PR DESCRIPTION
**Pull request by fmaximus**
Executing /opt/cloud/bin/configure.py without parameters, gives IndexError: Index out of range
May not be necessary to configure everything, as only these 2 are deferred.

### CODE REVIEW

**Comment by fmaximus** [comment]
Fixes [CLOUDSTACK-9980](https://issues.apache.org/jira/browse/CLOUDSTACK-9980)

**Comment by ustcweizhou** [comment]
code LGTM
not tested

**Comment by ustcweizhou** [comment]
actually I fixed the issue by
```
diff --git a/systemvm/patches/debian/config/opt/cloud/bin/configure.py b/systemvm/patches/debian/config/opt/cloud/bin/configure.py
index 958f797..556f768 100755
--- a/systemvm/patches/debian/config/opt/cloud/bin/configure.py
+++ b/systemvm/patches/debian/config/opt/cloud/bin/configure.py
@@ -968,10 +968,9 @@ class CsForwardingRules(CsDataBag):

 def main(argv):
     # The file we are currently processing, if it is "cmd_line.json" everything will be processed.
-    process_file = argv[1]
-
-    # process_file can be None, if so assume cmd_line.json
-    if process_file is None:
+    if len(sys.argv) > 1:
+        process_file = argv[1]
+    else:
         process_file = "cmd_line.json"

     # Track if changes need to be committed to NetFilter
diff --git a/systemvm/patches/debian/config/opt/cloud/bin/vr_cfg.sh b/systemvm/patches/debian/config/opt/cloud/bin/vr_cfg.sh
index 01d11ea..92ddcef 100755
--- a/systemvm/patches/debian/config/opt/cloud/bin/vr_cfg.sh
+++ b/systemvm/patches/debian/config/opt/cloud/bin/vr_cfg.sh
@@ -87,6 +87,11 @@ do
             echo $line >> $file
         done
         log_it "VR config: create file success"
+        filename=$(echo $file |cut -d'/' -f5)
+        if [ "$filename" == "vm_dhcp_entry.json" ] || [ "$filename" == "vm_metadata.json" ]
+        then
+            DEFER_CONFIG2=YESPLZ
+        fi
         continue
     fi
 done < $cfg
@@ -95,8 +100,12 @@ done < $cfg
 mv $cfg /var/cache/cloud/processed/

 unset DEFER_CONFIG
-# trigger finish_config()
-/opt/cloud/bin/configure.py
+if [ "$DEFER_CONFIG2" != "" ]
+then
+    log_it "VR config: finish configuration"
+    /opt/cloud/bin/configure.py vm_dhcp_entry.json
+    /opt/cloud/bin/configure.py vm_metadata.json
+fi

 # Flush kernel conntrack table
```

Anyway, I think you change fixes it as well.

**Comment by prashanthvarma** [comment]
Extended our feature Internal DNS Marvin test automation to test this fix (i.e. CLOUDSTACK-9980):

Added Marvin test code PEP8 and PyFlakes compliance:
$ pep8 test/integration/plugins/nuagevsp/*.py
$ pyflakes test/integration/plugins/nuagevsp/*.py

Marvin test failures without this fix:

$ nosetests --with-marvin --marvin-config=/path-to-marvin-config/marvin_test.cfg /test/integration/plugins/nuagevsp/test_nuage_internal_dns.py

Verify InternalDns on Isolated Network ... === TestName: test_01_Isolated_Network_with_zone | Status : SUCCESS ===
ok
Verify InternalDns on Isolated Network with ping by hostname ... === TestName: test_02_Isolated_Network | Status : SUCCESS ===
ok
Verify InternalDns on Isolated Network with restart networks and ... === TestName: test_03_Isolated_Network_restarts | Status : FAILED ===
FAIL
Verify update NetworkDomain for InternalDns on Isolated Network ... === TestName: test_04_Update_Network_with_Domain | Status : SUCCESS ===
ok
Verify update NetworkDomain for InternalDns on Isolated Network ... === TestName: test_05_Update_Network_with_Domain | Status : SUCCESS ===
ok
Verify InternalDns on VPC Network ... === TestName: test_06_VPC_Network_With_InternalDns | Status : SUCCESS ===
ok
Verify InternalDns on VPC Network by ping with hostname ... === TestName: test_07_VPC_Network_With_InternalDns | Status : SUCCESS ===
ok
Verify InternalDns on VPC Network with restarts and ping by ... === TestName: test_08_VPC_Network_Restarts_With_InternalDns | Status : FAILED ===
FAIL

[failed_plus_exceptions.txt](https://github.com/apache/cloudstack/files/1108341/failed_plus_exceptions.txt)
[results.txt](https://github.com/apache/cloudstack/files/1108340/results.txt)
[runinfo.txt](https://github.com/apache/cloudstack/files/1108342/runinfo.txt)

Passing Marvin tests with this fix:

$ nosetests --with-marvin --marvin-config=/path-to-marvin-config/marvin_test.cfg /test/integration/plugins/nuagevsp/test_nuage_internal_dns.py

Verify InternalDns on Isolated Network ... === TestName: test_01_Isolated_Network_with_zone | Status : SUCCESS ===
ok
Verify InternalDns on Isolated Network with ping by hostname ... === TestName: test_02_Isolated_Network | Status : SUCCESS ===
ok
Verify InternalDns on Isolated Network with restart networks and ... === TestName: test_03_Isolated_Network_restarts | Status : SUCCESS ===
ok
Verify update NetworkDomain for InternalDns on Isolated Network ... === TestName: test_04_Update_Network_with_Domain | Status : SUCCESS ===
ok
Verify update NetworkDomain for InternalDns on Isolated Network ... === TestName: test_05_Update_Network_with_Domain | Status : SUCCESS ===
ok
Verify InternalDns on VPC Network ... === TestName: test_06_VPC_Network_With_InternalDns | Status : SUCCESS ===
ok
Verify InternalDns on VPC Network by ping with hostname ... === TestName: test_07_VPC_Network_With_InternalDns | Status : SUCCESS ===
ok
Verify InternalDns on VPC Network with restarts and ping by ... === TestName: test_08_VPC_Network_Restarts_With_InternalDns | Status : SUCCESS ===
ok

Ran 8 tests in 4407.077s

OK

[results.txt](https://github.com/apache/cloudstack/files/1108347/results.txt)
[runinfo.txt](https://github.com/apache/cloudstack/files/1108346/runinfo.txt)


@karuturi @ustcweizhou @wido @The-Loeki

**Comment by karuturi** [comment]
Thanks for the marvin tests :) 👍 
@wido @The-Loeki Can you review?

**Comment by wido** [comment]
I think that @ustcweizhou fix is better since it does a proper check on the length in Python.

The original fix proposed is OK, but Python scripts shouldn't error on a keyerror like that.

**Comment by cloudmonger** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 912
 Hypervisor xenserver
 NetworkType Advanced
 Passed=106
 Failed=7
 Skipped=12

_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/r2si930m8xxzavs/AAAzNrnoF1fC3auFrvsKo_8-a?dl=0

**Failed tests:**
* test_deploy_vm_iso.py

 * test_deploy_vm_from_iso Failing since 5 runs

* test_volumes.py

 * test_06_download_detached_volume Failed

* test_vm_life_cycle.py

 * test_10_attachAndDetach_iso Failing since 5 runs

* test_routers_network_ops.py

 * test_01_isolate_network_FW_PF_default_routes_egress_true Failing since 38 runs

 * test_02_isolate_network_FW_PF_default_routes_egress_false Failing since 38 runs

 * test_01_RVR_Network_FW_PF_SSH_default_routes_egress_true Failing since 38 runs

 * test_02_RVR_Network_FW_PF_SSH_default_routes_egress_false Failing since 38 runs


**Skipped tests:**
test_vm_nic_adapter_vmxnet3
test_01_verify_libvirt
test_02_verify_libvirt_after_restart
test_03_verify_libvirt_attach_disk
test_04_verify_guest_lspci
test_05_change_vm_ostype_restart
test_06_verify_guest_lspci_again
test_static_role_account_acls
test_11_ss_nfs_version_on_ssvm
test_nested_virtualization_vmware
test_3d_gpu_support
test_deploy_vgpu_enabled_vm

**Passed test suits:**
test_deploy_vm_with_userdata.py
test_affinity_groups_projects.py
test_portable_publicip.py
test_vm_snapshots.py
test_over_provisioning.py
test_global_settings.py
test_scale_vm.py
test_service_offerings.py
test_routers_iptables_default_policy.py
test_loadbalance.py
test_routers.py
test_reset_vm_on_reboot.py
test_deploy_vms_with_varied_deploymentplanners.py
test_network.py
test_router_dns.py
test_non_contigiousvlan.py
test_login.py
test_list_ids_parameter.py
test_public_ip_range.py
test_multipleips_per_nic.py
test_metrics_api.py
test_regions.py
test_affinity_groups.py
test_network_acl.py
test_pvlan.py
test_nic.py
test_deploy_vm_root_resize.py
test_resource_detail.py
test_secondary_storage.py
test_disk_offerings.py

**Comment by karuturi** [comment]
@wido since your review isn't -1 and there is no response from nuage team, I am merging this in the current state(so that I can create next RC).

**Pull request merged**
