### PR TITLE
CLOUDSTACK-8301: Enable configuring local storage use for system VMs …

### PR DESCRIPTION
**Pull request by bhaisaab**
…at zone level

Backported from #263 for 4.5 branch
More information on https://issues.apache.org/jira/browse/CLOUDSTACK-8301

Signed-off-by: Rohit Yadav <rohit.yadav@shapeblue.com>

### CODE REVIEW

**Comment by bhaisaab** [comment]
Created PR, still testing on KVM/4.5

**Comment by bhaisaab** [comment]
@koushik-das I've backported your fix from master to 4.5 using the PR #263, please review

**Comment by bhaisaab** [comment]
Tests fixed, hoping this will pass Travis now

**Comment by bhaisaab** [comment]
Did functional testing with two KVM hosts, across two Advance Zones with VLAN isolation:

screen shot 2015-08-06 at 2 34 24 pm

The permutation was; Zone 1 with shared storage for user vms and local storage enabled for systemvms at the time of adding the zone, and Zone 2 with local storage for user vms and shared storage for systemvms (keeping the global setting use.systemvm.local.storage to false/default).

Infra looked like this, two hosts across two zones with both primary and secondary (zone wide) storages.

screen shot 2015-08-06 at 2 34 17 pm

- Saw that systemvm and user vms disks were allocated on respective storage type as expected
- When Zone 1's setting use.systemvm.local.storage was set to false, new systemvm (VRs) came up on shared storage
- When global use.systemvm.local.storage was set to true, Zone2's VRs came up on local storage
- When use.systemvm.local.storage of Zone2 was set to true, VRs came up on local storage

**Comment by koushik-das** [comment]
Changes LGTM. Make sure travis is green.

**Comment by bhaisaab** [comment]
@koushik-das thanks, looks like Travis failed due to some timeout issue and in other case due to dependency/jar issue. Will force push again to re-kick the travis job

**Comment by wido** [comment]
LGTM

**Comment by bhaisaab** [comment]
Travis is green and 2LGTM, merging now.

**Pull request closed without merging**
