### PR TITLE
ui: fix instance and functionality

### PR DESCRIPTION
**Pull request by NicoWohlfarth**
## Description

* Fixed a bug, where after sorting a column of the instance list view the multi select action buttons wouldn't show up after selecting one ore more entries of the table.
* Added a behavior, so that an already starting/running/stopped/stopping instance of the instance view will (when multi selected alone or together with other instances) not create an API request if it already has the desired state.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

Deployed to local environment and tested functionality.

### CODE REVIEW

**Comment by svenvogel** [comment]
@rhtyd can you run checks please.

ping @DaanHoogland

**Comment by svenvogel** [comment]
ui behaviour before the change: (bug)
1. nothing sorted or selected
Bildschirmfoto 2019-06-10 um 21 52 08
2. select any virtual machine (red - buttons come up)
Bildschirmfoto 2019-06-10 um 21 52 22
3. sort any column (blue) and select again any virtual machine (red), you dont see the buttons (red)
Bildschirmfoto 2019-06-10 um 21 52 41

**Comment by svenvogel** [comment]
This is a UI only change, manual testing/screenshot is only needed. Smoketests not necessary.

**Comment by svenvogel** [comment]
@shwstppr can you also take a look here?

**Comment by shwstppr** [comment]
@NicoWohlfarth Is it possible to change the behavior of showing stop confirmation/host selection dialog when selected instance(s) are already in stopped/running state.
Although the start/stop VM is not called in this case but UI shows dialog unecessarily

Screenshot from 2019-06-12 11-19-34

Screenshot from 2019-06-12 11-19-39

Otherwise LGTM!

**Comment by NicoWohlfarth** [comment]
> @NicoWohlfarth Is it possible to change the behavior of showing stop confirmation/host selection dialog when selected instance(s) are already in stopped/running state.
> Although the start/stop VM is not called in this case but UI shows dialog unecessarily

@shwstppr Yes, one could certainly do this, but i though it would then also be strange to have a button you can click and nothing would happen.
I think we should assume that no one would necessarily try to start/stop an already started/stopped machine and then be surprised that nothing happens. 😄

**Pull request merged**
