### PR TITLE
UI - Zone Wizard - Fixes the IP range form fields are too narrow

### PR DESCRIPTION
**Pull request by utchoang**
### Description

Fixes https://github.com/apache/cloudstack/issues/5286

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by utchoang** [comment]
After changes
Screenshot_1

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by davidjumani** [comment]
@utchoang The fields are larger but still not large enough. On Firefox.
Try and get `000.000.000.000` to fit since any range is smaller than that width wise

Screenshot from 2021-08-06 14-05-40

**Comment by utchoang** [comment]
@davidjumani My Firefox still renders fine, but I'll make the field a little wider for your case
image

**Comment by utchoang** [comment]
@blueorangutan ui

**Review by shwstppr — APPROVED** [review]
LGTM

Screenshot from 2021-08-07 01-26-34

**Review by davidjumani — APPROVED** [review]

**Pull request merged**
