### PR TITLE
CLOUDSTACK-8879: Depend in rados-java 0.2.0

### PR DESCRIPTION
**Pull request by wido**
This should fix the CloudStack Agent from crashing when it has to
handle more then 16 RBD snapshots on one Volume.

### CODE REVIEW

**Comment by K0zka** [comment]
LGTM :+1:

**Comment by runseb** [comment]
LGTM, small change.
@wido what tests can be run to check for this.

**Comment by wido** [comment]
@runseb No, not really. All my Unit tests are succeeding on rados-java itself. It should work as expected. But I have no in CloudStack test

**Comment by remibergsma** [comment]
@wido maybe @borisroman can execute smoke/test_vm_life_cycle.py to do a quick check?

**Comment by borisroman** [comment]
Will do.


Best regards,

Boris Schrijver

TEL: +31633784542
MAIL: boris@pcextreme.nl

**Comment by remibergsma** [comment]
@borisroman thank you!

**Comment by borisroman** [comment]
@remibergsma @runseb I've ran the test_vm_lifecycle.

[root@cs1 smoke]# nosetests --with-marvin --marvin-config=/data/shared/marvin/mct-zone1-kvm1-basic.cfg -s -a tags=basic,required_hardware=false test_vm_life_cycle
==== Marvin Init Started ====

=== Marvin Parse Config Successful ===

=== Marvin Setting TestData Successful===

==== Log Folder Path: /tmp//MarvinLogs//Oct_01_2015_10_11_33_MFQA0G. All logs will be available here ====

=== Marvin Init Logging Successful===

==== Marvin Init Successful ====
=== TestName: test_deploy_vm | Status : SUCCESS ===

=== TestName: test_deploy_vm_multiple | Status : SUCCESS ===

=== TestName: test_01_stop_vm | Status : SUCCESS ===

=== TestName: test_02_start_vm | Status : SUCCESS ===

=== TestName: test_03_reboot_vm | Status : SUCCESS ===

=== TestName: test_06_destroy_vm | Status : SUCCESS ===

=== TestName: test_07_restore_vm | Status : SUCCESS ===

=== TestName: test_09_expunge_vm | Status : SUCCESS ===

===final results are now copied to: /tmp//MarvinLogs//16ORAQ===

**Comment by wilderrodrigues** [comment]
Perhaps a manual test to fire the BackupSnapshot command?

Is there any integration test that we can execute to cover it?

Cheers,
Wilder

**Comment by wido** [comment]
@wilderrodrigues A proper integration test for Ceph is still on my whishlist, but to do that we need a running Ceph cluster which we can talk against.

I wrote rados-java btw and I solved some bugs in those bindings. They are passing all my unit tests which actually talk to a Ceph cluster.

**Comment by borisroman** [comment]
@remibergsma @wilderrodrigues I ran the requested tests, passing successfully. Integration tests aren't yet around, mocking Ceph (or using a real deployment) and writing those tests will take a lot of time. We confirmed it worked be manually testing it.

As 4.6 release is close I would like this to be merged before release. The PR has three LGTM's including one with test results.

**Comment by remibergsma** [comment]
Agree to merge this small bugfix. Thanks for running the lifecycle test to be sure.

**Pull request merged**
