### PR TITLE
CLOUDSTACK-8357 Add Test cases for vMotion support on VMFS as primary st...

### PR DESCRIPTION
**Pull request by abhinavroy02**
This commit has the vMotion related test cases. Following are the tests  

1. Create a VM and migrate it.
2. Migrate only ROOT volume of VM and check for vmx and vmdk files in storage.
3. Migrate VM and its ROOT volume and check for vmx and vmdk files in storage.
4. Attach Data disk to VM and then migrate VM and all its volumes followed by the check for files.
5. Upload a volume, attach it to VM and then migrate VM and all its volumes followed by the check for files.
6. Take Volume snapshots of all the volumes then migrate VM and all its volumes followed by the check for files.
7. Resize the Data disk then migrate VM and all its volumes followed by the check for files.
8. Restore the VM then migrate VM and all its volumes followed by the check for files.

All these are part of a test path so there is a single test written which has all the cases.

Here is the output after executing them locally:
Migrate VMs/Volumes on VMware with VMFS storage ... === TestName: 
test_01_migrate_root_and_data_disk_live | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 1 test in 855.918s

OK

### CODE REVIEW

**Comment by wilderrodrigues** [comment]
Hi @abhinavroy02,

Against which environment did you execute your tests?

I had a look at the code, and all looks fine, but just wanted to know if you tested it against XenServer/KVM or simulator only.

Cheers,
Wilder

**Comment by abhinavroy02** [comment]
Hi @wilderrodrigues ,

I have tested it on VMware environment as it is for the vMotion support on VMFS type primary storage.

Thanks,
Abhinav

**Comment by wilderrodrigues** [comment]
Hi Abhinav,

Cool! :)

I will close it.

Cheers,
Wilder

**Comment by abhinavroy02** [comment]
Thanks @wilderrodrigues :)

**Pull request merged**
