### PR TITLE
CLOUDSTACK-8545 make reboot on out of band migration configurable

### PR DESCRIPTION
**Pull request by DaanHoogland**

### CODE REVIEW

**Comment by anshul1886** [comment]
We should generate alert when out of band router VM migration is detected. This will help user take appropriate action in those scenarios.

**Comment by DaanHoogland** [comment]
@remibergsma makes sense, will do
@anshul1886 feel free to amend, I do not consider your proposed extension part of this blocker though it makes perfect sense from a functional perspective.

**Comment by resmo** [comment]
@DaanHoogland thanks for picking it up, btw do you port plan to fix it in 4.5 and master as well?

**Comment by DaanHoogland** [comment]
travis timeout, will ignore again. hoping the pull request builder does better.

@resmo to 4.5 yes, to master no. master has persistant config and routers will respin fully configured there.

**Comment by DaanHoogland** [comment]
@anshul1886 would the following satisfy your needs (had some extra time)
+        } else {
+            if (isOutOfBandMigrated(opaque)) {
+                final String title = "Router has been migrated out of band: " + vo.getInstanceName();
+                final String context =
+                        "An out of band migration of router " + vo.getInstanceName() + "(" + vo.getUuid() + ") was detected. No automated action was performed.";
+                _alertMgr.sendAlert(AlertManager.AlertType.ALERT_TYPE_DOMAIN_ROUTER, vo.getDataCenterId(), vo.getPodIdToDeployIn(), title, context);
+            }

**Comment by anshul1886** [comment]
Yes.

**Pull request closed without merging**
