### PR TITLE
server: skip max guest limit check for KVM host

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Addresses #3015 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Review by rhtyd — APPROVED** [review]

**Review by rhtyd — APPROVED** [review]
Check for KVM only LGTM

**Review by nvazquez — APPROVED** [review]
LGTM

**Pull request merged**
