### PR TITLE
CLOUDSTACK-8631 :changing if condition to update to zero when needed in component/test_ss_max_limit…

### PR DESCRIPTION
**Pull request by nitt10prashant**
test result
========
Test Try to deploy VM with admin account where account has not used ... === TestName: test_01_deploy_vm_domain_limit_reached | Status : SUCCESS ===
ok
Test Try to deploy VM with admin account where account has used ... === TestName: test_02_deploy_vm_account_limit_reached | Status : SUCCESS ===
ok
Test TTry to deploy VM with admin account where account has not used ... === TestName: test_03_deploy_vm_project_limit_reached | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 3 tests in 440.349s

### CODE REVIEW

**Comment by sanju1010** [comment]
Can you please specify the reason for changing the if condition for the benefit of others?

**Comment by nitt10prashant** [comment]
its there in ticket

**Comment by DaanHoogland** [comment]
I agree with Sanju. please ammend to something like 
CLOUDSTACK-8631: changing if condition to update to zero when needed

**Comment by DaanHoogland** [comment]
thanks LGTM

**Pull request closed without merging**
