### PR TITLE
Is the project attempting a fork on Github of Apache Cloudstack?

### PR DESCRIPTION
**Pull request by chrismattmann**
Why in the world is Apache Cloudstack creating an organization externally on Github? At a minimum, you can't use the Apache Cloudstack logo?

### CODE REVIEW

**Comment by chrismattmann** [comment]
Sorry was talking about this: https://github.com/cloudstack/cloudstack which I saw pop up.

**Comment by swill** [comment]
We are actively discussing the role it will play on the dev list.  We are currently exploring our options for potentially using it for CI and distributed integration testing since apache is not giving us any way to do this with the current repository.

You can get more information on the types of problems we are trying to solve here:  https://issues.apache.org/jira/browse/INFRA-11429

**Comment by runseb** [comment]
@chrismattmann how about you send email to private@ before sending some dummy PR.
thank you

**Comment by runseb** [comment]
Which ironically we can't close, so I hope @chrismattmann  you will close it, thank you

**Comment by eriweb** [comment]
You could close it by pushing a dummy commit. But yes, I have to agree that sending a PR is some weird communication form!

**Comment by rgardler** [comment]
private@ is not the right place for a discussion about community in an Apache project (though the PR approach is somewhat unusual)

**Comment by chrismattmann** [comment]
Hi, I will go ahead and jump on the dev list and discuss it. I tried to open up an issue in the forked project, but it took me here, sorry.

**Comment by swill** [comment]
@chrismattmann would you mind closing this PR since we can't and we don't need extra clutter in here.  Thx.

**Comment by chrismattmann** [comment]
closed.

**Pull request closed without merging**
