### PR TITLE
CLOUDSTACK-8766: Fix infinite scrolling pagination for zonal template…

### PR DESCRIPTION
**Pull request by bhaisaab**
… listing

Uses listViewDataProvider to implement pagination on listTemplates API
requests in the UI, when a template's zone tab is viewed.

### CODE REVIEW

**Comment by karuturi** [comment]
:+1:  as per #740 (I havent tested it on 4.5)

**Comment by bhaisaab** [comment]
thanks @karuturi the screenshots are from a 4.5 env, I've tested this on 4.5

**Comment by bhaisaab** [comment]
I've add a similar fix for listing iso/zone page and also added code that would de-dupe any isos and templates in the main list view.

**Comment by remibergsma** [comment]
LGTM

**Pull request merged**
