### PR TITLE
ui: fix filtering readonly details while VM update

### LINKED ISSUE #5724: Regular domain admin account cannot change nicAdapter “Request Failed (431)”
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15.2
~~~

##### SUMMARY

Regular domain admin account cannot change nicAdapter “Request Failed (431)” in new UI in OLD it works.
acs_nic

##### STEPS TO REPRODUCE

~~~
Edit nicAdapter settings
~~~

##### EXPECTED RESULTS

~~~
Regular domain admin account can change nicAdapter
~~~

##### ACTUAL RESULTS

~~~
Regular domain admin account cannot change nicAdapter
~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #5724

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):
Before fix (filtering of readonly details not working properly and updateVirtualMachine is called with rootDiskController setting)
Steps to reproduce:
- On a VMware env, as a regular user deploy a VM, stop it after deployment. Template shouldn't have nicAdapter specified
- Try to update VM with nicAdapter from UI by adding the new setting.
- Observe updateVirtualMachine API is called with rootDiskController in the details
Screenshot from 2022-01-24 14-05-44

After fix:
Screenshot from 2022-01-24 14-06-35

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan ui

**Review by sureshanaparti — APPROVED** [review]
Verified fix. LGTM

**Comment by DaanHoogland** [comment]
code looks good, but can you give a short brief as to how and why this solves the issue? It looks to be functionally the same, the filter only starting on the other end of the list.

**Comment by shwstppr** [comment]
@DaanHoogland I've changed loop to iterate from end of the list. As it was removing elements from the list in the loop, original code was having issues while removing multiple items.

**Review by utchoang — APPROVED** [review]
LGTM!

**Review by GutoVeronezi — APPROVED** [review]
LGTM

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by sureshanaparti** [comment]
@shwstppr when i add a read-only detail, it is ignored. please check.

**Comment by shwstppr** [comment]
@blueorangutan ui

**Review by Pearl1594 — APPROVED** [review]
LGTM

**Comment by sureshanaparti** [comment]
Verified latest changes. LGTM.

**Review by sureshanaparti — APPROVED** [review]

**Pull request merged**
