### PR TITLE
Remove unsupported params from API calls on the UI

### PR DESCRIPTION
**Pull request by BryanMLima**
### Description

Currently, the ACS has a lot of API call with unsupported parameters. While this does not cause any problems, as any unsupported parameters are discarded, there are a lot of messages with similar content: `WARN ... Received unknown parameters for command listZones. Unknown parameters : listall`. Therefore, it can be confusing for beginner operators. Moreover, if the API does not support the parameter, it should not be used regardless.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?
This was tested in a local lab traversing the UI while monitoring the Management logs if there were any `WARN ... Received unknown parameters for command <API>. Unknown parameters : <param>`.

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
clgtm
tested in qa

**Review by utchoang — APPROVED** [review]
LGTM!

**Comment by rohityadavcloud** [comment]
cc @shwstppr @DaanHoogland could cause potential regression as some APIs may require listall passed when account is not an admin account. Has anybody verified and tested this for normal account and domain admin if/wherever applicable?

**Comment by rohityadavcloud** [comment]
cc @DaanHoogland milestone missing

**Pull request merged**
