### PR TITLE
tools: fix Dockerfile

### PR DESCRIPTION
**Pull request by resmo**
Build a docker image did not work anymore for various reasons. This is how I fixed it

### CODE REVIEW

**Comment by rhtyd** [comment]
LGTM. @pdion891 would you like to review?

**Comment by pdion891** [comment]
Could you look if it conflict with #1435 ?  Because I made a pull request to automatically increment version in docker file when changing release of master via ```tools/build/setnextversion.sh```.

**Comment by wido** [comment]
Changes look good to me, but waiting for @pdion891 to tell us more :)

**Comment by resmo** [comment]
I didn't test #1435 yet, but code looks good. The only difference I see is:
~~~
pip install cryptography --force-reinstall
~~~

And I used the mysql connector from MySQL.com but would prefer to take it from distribution (as in #1435)

**Comment by pdion891** [comment]
So, should we go forward and merge #1435 + #1769  to master?
I might just need to rebase and update version number of the current commit.

With those 2 PR, we would have master back online on dockerhub so we can get an updater docker image for the simulator!

**Comment by pdion891** [comment]
@resmo  could you do a PR on top of #1435 ? or this have to be merged first? so we can get your chances and some of mine.

**Comment by resmo** [comment]
@pdion891 I would say merge #1435 first

**Comment by pdion891** [comment]
ok, I'll update the PR and merge it I think the PR go all required LGTM. I'll confirmed with John, in case he is in a code freeze period.

**Comment by rhtyd** [comment]
@resmo now that PR by @pdion891 is merge, can this be closed? Thanks.

**Comment by pdion891** [comment]
Hi @resmo,  I've made some changes on the Docker file so it might not be possible to merge this PR in the current state.

Thanks!

**Comment by resmo** [comment]
ok, np closing for now

**Pull request closed without merging**
