### PR TITLE
UI: Fix VM state column

### LINKED ISSUE #5489: UI: Instances list view format after adding comments
Minor UI issue: The comments icon on the instance list view makes the VM state text exceed the column width if there is a VM with a default name that has a comment 

Before adding a comment on a VM with default name:
AAAbefore

After adding a comment;
AAAAfter

##### ISSUE TYPE
 * Improvement Request

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION
~~~
4.16 (main)
~~~

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Once a VM with a default name gets a comment, the comments icon makes the State column word-break

##### STEPS TO REPRODUCE
~~~
- Create a VM, leave the name field empty
- Add a comment on the VM
- List instances
~~~

##### EXPECTED RESULTS
~~~
Table maintains its format for each column
~~~

##### ACTUAL RESULTS
~~~
Word break on VM state
~~~

### PR DESCRIPTION
**Pull request by nvazquez**
### Description

This PR fixes #5489 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### CODE REVIEW

**Comment by nvazquez** [comment]
@blueorangutan ui

**Review by utchoang — APPROVED** [review]
LGTM!

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
@nvazquez the comments is now under Tools section - should that be moved to something appropriate?
cc @Pearl1594 @davidjumani can you one of you test, the qa.cloudstack.cloud can't be used for testing this as it doesn't have the backend db/api changes

**Review by Pearl1594 — APPROVED** [review]
Verified - LGTM
Prior fix:
image

With Fix:
image

**Review by davidjumani — APPROVED** [review]

**Comment by nvazquez** [comment]
Thanks for testing @Pearl1594 @davidjumani. @rhtyd no, that section does not need to be moved

**Pull request merged**
