### PR TITLE
ListFirewallEgressRulesCmd: extend from BaseListTaggedResourcesCmd an…

### PR DESCRIPTION
**Pull request by resmo**
…d cleanup

Fixes API duplicate parameter in docs and makes it more clear.
Fixes a bunch of typos.

### CODE REVIEW

**Comment by bhaisaab** [comment]
@resmo can you check and fix the build issue? Travis is failing too while building.

**Comment by resmo** [comment]
@bhaisaab It's been a while since I coded JAVA, have no clue, why it is failing. May I ask you for a hint?

**Comment by bhaisaab** [comment]
@resmo looks like an interface/type issue, see the error here: https://builds.apache.org/job/cloudstack-pull-requests/160/console I can help fix it next week, but if you've an IDE just fix the type and interface usage

**Comment by resmo** [comment]
@bhaisaab a good IDE helps indeed.

**Comment by bhaisaab** [comment]
@resmo looks good to me, Travis is green too. Will merge tonight or tomorrow after some build tests. Thanks.

**Comment by bhaisaab** [comment]
Builds fine, merging.

**Pull request closed without merging**
