### PR TITLE
ui: Allow editing VM and template settings

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

This PR fixes the issue seen when attempting to update template / VM settings where in users aren't unable to change the existing value.

image

image

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### How Has This Been Tested?
Post Fix:
image

### CODE REVIEW

**Comment by Pearl1594** [comment]
@blueorangutan ui

**Review by utchoang — APPROVED** [review]
LGTM!

**Review by slavkap — APPROVED** [review]
LGTM, manually tested

**Review by weizhouapache — APPROVED** [review]
tested ok

**Pull request merged**
