### PR TITLE
server: update default value of setting 'expose.dns.externally' to 'false"

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes the issue that the DNS is exposed publicly by default.

related to:
https://github.com/apache/cloudstack/commit/6a72e6e9f83145f20364c00e95c4d918f0de86e0
https://github.com/apache/cloudstack/pull/1663

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [x] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
this is a critical issue
@rohityadavcloud @NuxRo @DaanHoogland @JoaoJandre

**Review by rohityadavcloud — APPROVED** [review]

**Review by NuxRo — APPROVED** [review]
LGTM

**Review by JoaoJandre — APPROVED** [review]
CLGTM

**Comment by JoaoJandre** [comment]
Merging based on approvals and CI result

**Pull request merged**
