### PR TITLE
CLOUDSTACK-10363: Change method names.

### PR DESCRIPTION
**Pull request by BruceKuiLiu**
…findXXX".

These three methods are not direct getter or list.
They try to find the target objects with the related arguments.
So that, renaming them as "findXXX" should be more intuitive.

### CODE REVIEW

**Comment by nitin-maharana** [comment]
Hi @BruceKuiLiu, Thanks for the change, now the method names are more meaningful. Would be nice if you club all the similar PRs to one. (#2600, #2601, #2602)

**Comment by BruceKuiLiu** [comment]
Hi @nitin-maharana ,
I think that #2600, #2061, #2602 can be classified into three different changes.
If it is necessary, I will merge them into one commit.

**Comment by nitin-maharana** [comment]
I think it would be good to merge them into one. Let's wait for others view.

**Comment by BruceKuiLiu** [comment]
@rafaelweingartner Thanks.

**Comment by rhtyd** [comment]
This is a pure name refactoring with no effective overall logic/code changed. Merging this based on Travis pass and reviews by others.

**Pull request merged**
