### PR TITLE
CLOUDSTACK-10255: Fix agent logrotate

### PR DESCRIPTION
**Pull request by fmaximus**
Renamed `cloudstack-agent.logrotate` to `cloudstack-agent.logrotate.in`, 
so Ant will run the filterchain while copying.
This made the ant run copy block of `cloudstack-agent.logrotate` unnecessary,
so this is removed.

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
Since this is packaging related issue, clearly causing failures on logrotation we can consider this towards 4.11.0 milestone. /cc @DaanHoogland @wido @rafaelweingartner @borisstoyanov and others.

**Comment by DaanHoogland** [comment]
4.11.0 i concur

**Comment by rhtyd** [comment]
Okay, will move it to 4.11.0 milestone.

**Pull request merged**
