### PR TITLE
Update L10N resource files with 4.10 strings from Transifex (20160925)

### PR DESCRIPTION
**Pull request by milamberspace**
Please merge the #1619 before.

And please merge this current PR before 4.10.0.0 release.

cc @jburwell

### CODE REVIEW

**Comment by jburwell** [comment]
@blueorganutan package

**Comment by jburwell** [comment]
LGTM for code

**Comment by jburwell** [comment]
@rhtyd any objections to this change?

**Comment by jburwell** [comment]
@rhtyd @karuturi we need a second LGTM to merge this PR for 4.10.0.0

**Comment by rhtyd** [comment]
LGTM. Since it's a translation change, we've enough votes to merge this. I'll proceed with merging this on master.

**Pull request merged**
