### PR TITLE
UI: Show iso urls

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR shows the url in the iso details...

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan ui

**Comment by weizhouapache** [comment]
It looks the java changes have no impact, right ? @DaanHoogland

**Comment by DaanHoogland** [comment]
> It looks the java changes have no impact, right ? @DaanHoogland

no, that's right. just cleaning of the source

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by weizhouapache** [comment]
verified on QA server (both admin and user)

**Pull request merged**
