### PR TITLE
vm: Reset deviceId to fix missing nic with vm

### PR DESCRIPTION
**Pull request by ustcweizhou**
## Description

This PR aims to fix the issue which can be reproduced as below:

1. create a vm with 3 networks
2. remove the 2nd network from the vm
3. stop the vm
4. start the vm

Expected result: vm is started with 2 nics (on 1st network and 3rd network)
Actual result: vm is started with only first nic (on 1st network).

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

With this PR, the vm is started with all nics.

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Can you check build/Travis failures @ustcweizhou ?

**Comment by rhtyd** [comment]
@ustcweizhou please check and address Travis failures

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@ustcweizhou can you review the failures?

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan test

**Pull request merged**
