### PR TITLE
[master] noVNC Console Integration

### PR DESCRIPTION
**Pull request by ustcweizhou**
## Description

This feature provides novnc console for virtual machines.

It is developed based on
(1) noVNC 1.1.0
(2) latest websockify
Some  changes in cloudstack
(1) add a new servlet /novncconsole
(2) a websocket proxy based on websockify will be launched in CPVM.
(3) add vnc password authentication in websockify
(4) generate 'path' and decrypt it in websockify to connect to server/port and check vnc password.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?
(1) it works with ubuntu 16.04/qemu 2.5 
(2) If consoleproxy.sslEnabled is changed, please restart management server and CPVM (or cloud service in CPVM). It determines http or https will be used in novnc console
(3) If novnc.console.default is true,novnc console will be default console on UI. If it is false, we still can access novnc console via /novncconsole?cmd=access&vm=XXX
(4) global setting novnc.encryption.key is hidden, it can be changed via cloudmonkey. Restart CPVM (or cloud service in CPVM) if it is changed.

## TODOs

- [ ] Test on KVM (CentOS + Ubuntu)
- [ ] Test on VMware
- [ ] Test on XenServer and XCP-NG
- [ ] Fix license declarations etc
- [ ] Fix end-to-end TLS/security on Chrome + Firefox

### CODE REVIEW

**Comment by ustcweizhou** [comment]
For someone still use cloudstack 4.11.2 in production, #3283

**Comment by DennisKonrad** [comment]
@ustcweizhou To migrate from an existing installation, do we need to build a new systemvm template? Or are the changes to the CPVM applied online somehow?

**Comment by ustcweizhou** [comment]
@DennisKonrad 
python-numpy is required in CPVM. It would be nice to have it pre-installed in systemvm template. However, if CPVM has internet connection it is not a problem, because python-numpy will be installed when noVNC is launched in CPVM.

**Comment by ustcweizhou** [comment]
@rhtyd @svenvogel 
This PR has not conflict with master branch, could you test it when you have time ?
especially on xenserver/vmware

**Comment by DennisKonrad** [comment]
@ustcweizhou @svenvogel We already built the code and that worked fine. We are planning to try the feature next week.

Then we can give feedback and test.

**Comment by rhtyd** [comment]
Thanks @ustcweizhou I'm busy with work for at least two more weeks but I'll certainly review and help test the PR (and possible fix issues wrt xenserver/vmware testing).

**Comment by rhtyd** [comment]
@ustcweizhou can you check and fix the pylint issues: (refer https://travis-ci.org/apache/cloudstack/jobs/524837786)
```
+'[' 1 -gt 0 ']'
+echo 'Pylint failed, please check your code'
Pylint failed, please check your code
+exit 1
```
It's probably best if we can fix the build to ignore novnc related source file and websockify python codebase
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by DennisKonrad** [comment]
@ustcweizhou @svenvogel I did a small test with this last week but couldn't get it to work. I'm not sure but just deploying a new management server with this PR didn't work. Is there anything I needed to do to make it work?

**Comment by ustcweizhou** [comment]
@DennisKonrad have you uploaded ssl certificate for console , and made some changes in global setting for domain suffix ?

**Comment by DennisKonrad** [comment]
@ustcweizhou We do have:
consoleproxy.sslEnabled set to true
consoleproxy.url.domain is also set

I somewhere uploaded a certificate but can't remember right now where one has to do that. But yes, we uploaded a certificate.

If you mean internatl domain suffix: that's unchanged (still 'cloud.internal')
Can you provide me some more information on what steps to take to get this working?

**Comment by ustcweizhou** [comment]
@DennisKonrad  
see steps as below
(1) set consoleproxy.url.domain to *.domain.suffix (or domain.suffix, depends on your dns settings), and consoleproxy.sslEnabled to true, then restart management server
(2) upload ssl certificate, cpvm and ssvm will be restarted
(3) reboot cpvm if you change global settings again

by the way, what hypervisor do you use ?

**Comment by DennisKonrad** [comment]
@ustcweizhou So the steps you provided. We have the setup like you described it already in place.

Like i wrote: 
(1) consoleproxy.url.domain is already set
(2) our certificate is already uploaded
(3) no need to reboot 

How can we use the novnc console without settings up things we already have in place? 
We use KVM

**Comment by ustcweizhou** [comment]
@DennisKonrad 
do you get error on console ? if so, could you please attach a screenshot ?

or do you still see the native console ? novnc.console.default should be true in global setting.

**Comment by DennisKonrad** [comment]
@ustcweizhou No error, just not loading anything. I will try this again tomorror and report back.

I'm not sure anymore if I correctly set the global variable. But the variable is present. If you have any questions I should check on please feel free to ask.

**Comment by rhtyd** [comment]
@ustcweizhou can you fix build failure, see https://travis-ci.org/apache/cloudstack/jobs/524837786
Likely the new noVNC assets need to be removed from license and lint related checks.

**Comment by ustcweizhou** [comment]
@rhtyd 
rebased with latest master.
upgraded websockify to latest v0.9.0

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Sorry @ustcweizhou I got caught up with work and couldn't progress/test this on Xen/VMware. I'll see what we can do towards 4.14.

**Comment by andrijapanicsb** [comment]
@weizhouapache @rhtyd any change to progress this one for 4.14? Looks more like 4.15 to me?

**Comment by rhtyd** [comment]
Yes I think unfortunately we won't have time to stablise and include this for 4.14, there are also outstanding tasks on this PR such as to support/report the load on the CPVM. It's best to be attempted towards 4.15 that would ship with Primate and would be great if we can ship novnc with it.

**Comment by DennisKonrad** [comment]
@ustcweizhou I'm tying to get this running in a test environment. Can you give me some indications on what maybe wrong. I'm using [master with this PR merged ](https://github.com/DennisKonrad/cloudstack/tree/novnc).

It seems to me after or during the upgrade to a websocket connection something fails with the novnc console.

<details>
  <summary>Screenshots</summary>

image
 
image

The old cs console works fine when I set `novnc.console.default` to `false` and reboot the console system vm.
image
</details>

**Comment by weizhouapache** [comment]
@DennisKonrad thanks for testing. I will have a look

**Comment by weizhouapache** [comment]
@DennisKonrad 
is consoleproxy.sslEnabled true ?

can you please try the following in CPVM ?
1. add "--log-file=/var/log/novnc.log" after "--web=/root/noVNC" in /usr/local/cloud/systemvm/noVNC_daemons.sh and /usr/local/cloud/systemvm/noVNC_daemons_ssl.sh
2. restart cloud service via "systemctl restart cloud"
3. access a vm console, and check /var/log/novnc.log in CPVM

I have set up around 10 testing environments, the ssl/non-ssl novnc console work fine.

**Comment by weizhouapache** [comment]
rebased with latest master

**Comment by rhtyd** [comment]
Thanks @ustcweizhou 

cc @andrijapanicsb @DaanHoogland @PaulAngus @borisstoyanov @nvazquez @shwstppr @Pearl1594 @davidjumani - let's build some support around this for 4.15 to remove/deprecate the legacy console proxy.

**Comment by weizhouapache** [comment]
> @ustcweizhou I'm tying to get this running in a test environment. Can you give me some indications on what maybe wrong. I'm using [master with this PR merged ](https://github.com/DennisKonrad/cloudstack/tree/novnc).
> 
> It seems to me after or during the upgrade to a websocket connection something fails with the novnc console.
> 
> (After reading the older comments again: No certificate uploaded in this environment and guest.domain.suffix is `test.kvm` )
> 
> 
> The old cs console works fine when I set `novnc.console.default` to `false` and reboot the console system vm.


@DennisKonrad I just recall the issue that novnc console does not work if you open the normal console few minutes ago.

the vnc port is occupied when we open the normal console. the port is free again and novnc console should work when the connection is closed after idling for 180 seconds.

https://github.com/apache/cloudstack/blob/master/services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxyGCThread.java#L34

I set up a fresh installation with master + novnc yesterday . it works fine.

**Comment by svenvogel** [comment]
@weizhouapache small question in the discussion. should we create for this idle timeout value and "ConfigKey" like ```novnc.max.session.idle```? i might missed something.

**Comment by weizhouapache** [comment]
> @weizhouapache small question in the discussion. should we create for this idle timeout value and "ConfigKey" like `novnc.max.session.idle`? i might missed something.

@svenvogel Unfortunately novnc does not manage the session . This can be done by reverse proxies.
similar issue in openstack: https://bugzilla.redhat.com/show_bug.cgi?id=1500136

**Comment by DennisKonrad** [comment]
@ustcweizhou You mentioned multiple times that I need to provide a ssl certificate. It seems to me it is necessary to use a certificate to get this running. Is that correct?
That could be the reason it's not working for me

**Comment by weizhouapache** [comment]
> @ustcweizhou You mentioned multiple times that I need to provide a ssl certificate. It seems to me it is necessary to use a certificate to get this running. Is that correct?
> That could be the reason it's not working for me

@DennisKonrad ssl certificate is not prerequisite.
You can choose if ssl is enabled or not in global setting. if yes, you have to upload a ssl certificate.

**Comment by DennisKonrad** [comment]
So the error seems to be "Invalid client ip address" after looking in the novnc.log... Is this some security feature? @ustcweizhou 
```
root@v-1-VM:~# tail -f /var/log/novnc.log 
WebSocket server settings:
  - Listen on :8080
  - Web server. Web root: /root/noVNC
  - No SSL/TLS support (no cert file)
  - Backgrounding (daemon)
  - proxying from :8080 to None:None
172.20.0.1 - - [19/Feb/2020 10:41:36] 172.20.0.1: Plain non-SSL (ws://) WebSocket connection
172.20.0.1 - - [19/Feb/2020 10:41:36] 172.20.0.1: Path: '/accc60e6[...]2f9bd836fc5'
172.20.0.1: Not accepted: Invalid client ip address
```

**Comment by rhtyd** [comment]
@ustcweizhou do you have any plans on this? Our @davidjumani is going to work on it towards 4.15 milestone.

**Comment by weizhouapache** [comment]
> So the error seems to be "Invalid client ip address" after looking in the novnc.log... Is this some security feature? @ustcweizhou
> 
> ```
> root@v-1-VM:~# tail -f /var/log/novnc.log 
> WebSocket server settings:
>   - Listen on :8080
>   - Web server. Web root: /root/noVNC
>   - No SSL/TLS support (no cert file)
>   - Backgrounding (daemon)
>   - proxying from :8080 to None:None
> 172.20.0.1 - - [19/Feb/2020 10:41:36] 172.20.0.1: Plain non-SSL (ws://) WebSocket connection
> 172.20.0.1 - - [19/Feb/2020 10:41:36] 172.20.0.1: Path: '/accc60e6[...]2f9bd836fc5'
> 172.20.0.1: Not accepted: Invalid client ip address
> ```

yes @DennisKonrad 
in novnc it checks if the source ip to novnc server and management server are the same.
```
        # Check client ip address
        if self.client_ip != self.client_address[0]:
            self.send_close()
            raise self.server.EClose('Not accepted: Invalid client ip address')
```
(self.client_ip is source ip to management server, self.client_address[0] is source ip to novnc)

If you use reverse proxy or load balancer (nginx, haproxy, pfsense,etc), it might be an issue.

**Comment by weizhouapache** [comment]
> @ustcweizhou do you have any plans on this? Our @davidjumani is going to work on it towards 4.15 milestone.

@rhtyd We will include current source code in our next version. it works fine for many years on our productions.

**Comment by DennisKonrad** [comment]
@rhtyd Could you elaborate on what needs to be done by @davidjumani?

**Comment by DennisKonrad** [comment]
@ustcweizhou I'll check why those ip's differ in my testing environment

**Comment by svenvogel** [comment]
>@rhtyd We will include current source code in our next version. it works fine for many years on our productions.

@weizhouapache this sounds good. 👍we support this! this is a nice feature. is this console a multilanguage?

**Comment by rhtyd** [comment]
@weizhouapache that's good to know.

@DennisKonrad this PR is far from complete for general consumption, and possibly requires the following (and more): /cc @PaulAngus @davidjumani 

- Test and support XenServer, VMware in addition to KVM
- Support TLS/secured vnc connection when libvirtd is secured by CA-framework for KVM
- Validate the token exchange and security concerns (I've a bunch of test cases, plan in mind)
- Add support for active session management (allow only one view per VM), the active sessions reported by CPVM agent is used by the management server to add/remove more CPVMs in a zone
- I personally prefer a java-based websockets proxy http/https server which can work with ^^ and give us more control over connection validation and security (esp with the CA framework), we probably want to reduce additional packages/dependencies. I'm also not sure if/how could python/websockify provide a way to track active sessions and manage connection security.
- Support for multiple keyboards (like the current console proxy, for example jp, uk, us, fr etc)
- While Hyper-V largely does not working out of the box, but legacy console proxy proxies RDP (I think) on Hyper-V and therefore we also need to find suitable replacement for rdp-vnc cross-over, or if newer HyperV can support native VNC (needs checking @PaulAngus)
- Provide an upgrade path for users and discuss whether in the next release we want to deprecate and remove the current console proxy or simply remove in the next (unless all existing requirements of legacy console proxy are replaced and novnc is tested in various environments, it's not best to simply remove the legacy console proxy)

**Comment by DennisKonrad** [comment]
@rhtyd  I think novnc should be added as option and not as a complete replacement for the current console. The only change for that would be to not set novnc as the default in the global settings.

<details><summary>If you have a complete replacement of the current console in mind that should be done by additional PRs and not by moving this PR into the far future. I responded to the complete list but to see it you have to click-open.</summary>
<p>


> * Test and support XenServer, VMware in addition to KVM

I'll test KVM extensively. Also I think the community will pick up this PR for the other hypervisors. Never the less I know a lot of features that are merged for usage with single hypervisor with remark to the possibilty to expand them later (just take a look at vm ingestion merged by you and boris).

> * Support TLS/secured vnc connection when libvirtd is secured by CA-framework for KVM

This one I would like you to explain in more detail. If one uses CA framework you want it automatically to activate TLS for novnc? How would this work for a more complex setup like load balancing where TLS gets terminated at the load balancer?

> * Validate the token exchange and security concerns (I've a bunch of test cases, plan in mind)

That's great. We also have in mind to check this now that we figured out why the console was not working in our test env.

> * Add support for active session management (allow only one view per VM), the active sessions reported by CPVM agent is used by the management server to add/remove more CPVMs in a zone

In my opinion that is a feature to add later. Having multiple views per VM seems to be desirable. 

> * I personally prefer a java-based websockets proxy http/https server which can work with ^^ and give us more control over connection validation and security (esp with the CA framework), we probably want to reduce additional packages/dependencies. I'm also not sure if/how could python/websockify provide a way to track active sessions and manage connection security.

It more or less sounds like you do want to reimplement this PR in java so it works with the CA framework? I understand the concers for security but let's do not mix that with the integration in the CA framework.

> * Support for multiple keyboards (like the current console proxy, for example jp, uk, us, fr etc)

That would indeed be great but in the "legacy" console this isn't working right now as well.

> * While Hyper-V largely does not working out of the box, but legacy console proxy proxies RDP (I think) on Hyper-V and therefore we also need to find suitable replacement for rdp-vnc cross-over, or if newer HyperV can support native VNC (needs checking @PaulAngus)

This PR implements novnc as option and I think it has to be off as default as well. It's cool that you want to implement HyperV support but I don't get why the milestone of this PR moves because of that?

> * Provide an upgrade path for users and discuss whether in the next release we want to deprecate and remove the current console proxy or simply remove in the next (unless all existing requirements of legacy console proxy are replaced and novnc is tested in various environments, it's not best to simply remove the legacy console proxy)

Like written above this PR is not replacing the "legacy" console. Why do you suggest deprecating the "legacy" console?

</p>
</details>

**Comment by DennisKonrad** [comment]
> @DennisKonrad this PR is far from complete for general consumption, and possibly requires the following (and more): /cc @PaulAngus @davidjumani

This PR at no time seems like a drop-in replacement to me. But I'm sure it cannot even become one if we block it.

**Comment by weizhouapache** [comment]
> @weizhouapache that's good to know.
> 
> @DennisKonrad this PR is far from complete for general consumption, and possibly requires the following (and more): /cc @PaulAngus @davidjumani
> 
> * Test and support XenServer, VMware in addition to KVM
> * Support TLS/secured vnc connection when libvirtd is secured by CA-framework for KVM
> * Validate the token exchange and security concerns (I've a bunch of test cases, plan in mind)
> * Add support for active session management (allow only one view per VM), the active sessions reported by CPVM agent is used by the management server to add/remove more CPVMs in a zone
> * I personally prefer a java-based websockets proxy http/https server which can work with ^^ and give us more control over connection validation and security (esp with the CA framework), we probably want to reduce additional packages/dependencies. I'm also not sure if/how could python/websockify provide a way to track active sessions and manage connection security.
> * Support for multiple keyboards (like the current console proxy, for example jp, uk, us, fr etc)
> * While Hyper-V largely does not working out of the box, but legacy console proxy proxies RDP (I think) on Hyper-V and therefore we also need to find suitable replacement for rdp-vnc cross-over, or if newer HyperV can support native VNC (needs checking @PaulAngus)
> * Provide an upgrade path for users and discuss whether in the next release we want to deprecate and remove the current console proxy or simply remove in the next (unless all existing requirements of legacy console proxy are replaced and novnc is tested in various environments, it's not best to simply remove the legacy console proxy)

@rhtyd good you have many nice ideas !
Maybe we can create a SIG for it.

**Comment by weizhouapache** [comment]
> > @rhtyd We will include current source code in our next version. it works fine for many years on our productions.
> 
> @weizhouapache this sounds good. 👍we support this! this is a nice feature. is this console a multilanguage?

we had some research to support multiple language keyboard in the past.
it is based on a open source project https://github.com/ustcweizhou/mok-project
however it is not deployed to our production.

**Comment by weizhouapache** [comment]
> > @DennisKonrad this PR is far from complete for general consumption, and possibly requires the following (and more): /cc @PaulAngus @davidjumani
> 
> This PR at no time seems like a drop-in replacement to me. But I'm sure it cannot even become one if we block it.

@rhtyd @DennisKonrad @DaanHoogland @PaulAngus @svenvogel 
just a proposal, can we add some features or improvements as "Beta features"  or "Alpha features"?

**Comment by rhtyd** [comment]
@ustcweizhou a SIG may not be necessary as this would most likely require few weeks (not months), once @davidjumani start this sometime next week any collaboration would be welcomed on the public PR.

**Comment by DaanHoogland** [comment]
> @rhtyd @DennisKonrad @DaanHoogland @PaulAngus @svenvogel
> just a proposal, can we add some features or improvements as "Beta features" or "Alpha features"?

@weizhouapache I am all for it :+1:. We don't do that enough. However we must think of a way to clearly mark features like than, and not be afraid to retract them if they turn out not ok. The, or an important thing to note there is that retracting is a backward incompatibility that we take on.

**Comment by weizhouapache** [comment]
> a SIG may not be necessary as this would most likely require few weeks (not months), once @davidjumani start this sometime next week any collaboration would be welcomed on the public PR. The bare minimum requirement would be that it works on all hypervisors with SSL/TLS certificates, in addition to the legacy console proxy.

@rhtyd good. expect to see it in coming few weeks.

**Comment by rhtyd** [comment]
@ustcweizhou just to update @davidjumani has already started work on it and I'll be supporting him, we'll most likely start a draft PR in a week's time.

**Comment by weizhouapache** [comment]
> @ustcweizhou just to update @davidjumani has already started work on it and I'll be supporting him, we'll most likely start a draft PR in a week's time.

@rhtyd good, thanks.

**Comment by DaanHoogland** [comment]
@weizhouapache I'm closing this in favour of #3296. please re-open if I'm at fault.

**Pull request closed without merging**
