### PR TITLE
Marvin: change some vlans in test_data.py

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes the test failures with test_nic.py in some trillian tests.

see errors below:
```
test_01_nic (tests.smoke.test_nic.TestNic): DEBUG: Exception during NIC test SETUP!: Execute cmd: createnetwork failed, due to: errorCode: 431, errorText:The VLAN tag to use for new guest network, 1201 is already being used for dynamic vlan allocation for the guest network in zone pr5201-t2497-vmware-70u1
```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@nvazquez could you please review it ?

**Review by DaanHoogland — APPROVED** [review]

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
cc @davidjumani @nvazquez @sureshanaparti @weizhouapache pl check why BO isn't picking requests?

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan help

**Comment by davidjumani** [comment]
@blueorangutan hello

**Comment by nvazquez** [comment]
@blueorangutan test matrix

**Review by rhtyd — APPROVED** [review]

**Review by sureshanaparti — APPROVED** [review]

**Pull request merged**
