### PR TITLE
[CLOUDSTACK-10197] Update DisplayText of XenServer tools ISO entry in the database when it already exists

### PR DESCRIPTION
**Pull request by rafaelweingartner**
Changes here were suggestions made to #2365, but for some reason, the PR was merged without considering them. Both the update of the ‘displayText’  value and unit test cases were suggested as improvements in that PR.

After coding, I also when through those classes and removed unused variables.

@khos2ow can you take a look here?

### CODE REVIEW

**Comment by khos2ow** [comment]
@rafaelweingartner It seems you have some "trailing spaces" issues on `XcpServerDiscovererTest.java` and couple of variable name issues. The latter one is really annoying, because it forces to have `^_?[a-zA-Z0-9]*$` for final variables.

**Comment by rafaelweingartner** [comment]
@khos2ow thanks for the review.
And yes, those check-style rules are quite annoying. We need to discuss and change them to better fit the common practice nowadays.

**Comment by rafaelweingartner** [comment]
What do you think @DaanHoogland, do wee need to wait for integration tests here?

**Comment by DaanHoogland** [comment]
@rafaelweingartner doesn't hurt does it?
@blueorangutan package

**Comment by DaanHoogland** [comment]
@rhtyd can you review this, please?

**Comment by rafaelweingartner** [comment]
@DaanHoogland no it does not ;)

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by rafaelweingartner** [comment]
@DaanHoogland is this "test_hostha_enable_ha_when_host_in_maintenance" an intermittent error? I have seen this on #2425, which is a very different PR.

**Comment by DaanHoogland** [comment]
Yes @rafaelweingartner , I've seen this one a lot and seen it pass as well. Your code here is not related to that test afaik.
@rhtyd @PaulAngus can you give second and third opinions?

**Comment by rafaelweingartner** [comment]
@DaanHoogland this one seems to be ready. Would you like to wait for a third and fourth eyes here?

**Comment by DaanHoogland** [comment]
@rafaelweingartner no it is fine

**Pull request merged**
