### PR TITLE
PowerFlex/ScaleIO volume live migration - use usable bytes from source disk to format the destination disk

### PR DESCRIPTION
**Pull request by sureshanaparti**
### Description

This PR improves the ScaleIO volume live migration, uses usable bytes from source disk to format the destination disk.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

Tested PowerFlex/ScaleIO volume live migration across storage clusters, with volumes of varied sizes, normal & encrypted volumes (with 32MB & 128MB reserve), with/without data.

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Review by kiranchavala — APPROVED** [review]
LGTM, Tested the fix and its working fine

Steps to reproduce the issue

1.  Create env with 4.18.1, with packages from pr 246)
2.  Add PowerFlex pools of different storage clusters with storage tag, say pflex
3.  Create disk offering with that storage tag, in step (2) with encryption and thin provisioning enabled
4.  Create volume with that disk offering, in step (3), this creates volume on any of the PowerFlex pool
5.  Attach the volume to a running VM, and verify the size of the data disk
 
```
[root@ref-trl-6807-k-Mr8-kiran-chavala-kvm1 ~]# qemu-img info /dev/disk/by-id/emc-vol-033a5b4e7e9e6a0f-77a95b0e00000007
image: /dev/disk/by-id/emc-vol-033a5b4e7e9e6a0f-77a95b0e00000007
file format: qcow2
virtual size: 64 GiB (68673077248 bytes)
disk size: 0 B
encrypted: yes
cluster_size: 65536
Format specific information:
```


6. Live migrate the volume with/without data across different PowerFlex storage cluster - should work (as the reserve is the same for source & destination volumes, i.e. 32 MB)

7. To Reproduce Issue - Upgrade env to 4.19 and Live migrate the volume - fails (as the destination volume created with updated reserve 128 MB)

Logs

```
2024-06-12 06:47:24,237 INFO  [resource.wrapper.LibvirtMigrateVolumeCommandWrapper] (agentRequest-Handler-5:null) (logid:61c82c80) Block copy has started for the volume vdb : 046bc3d60000000a:vol-4-a139-22ae
2024-06-12 06:47:24,250 DEBUG [resource.wrapper.LibvirtMigrateVolumeCommandWrapper] (agentRequest-Handler-5:null) (logid:61c82c80) Volume vdb : 046bc3d60000000a:vol-4-a139-22ae block copy progress: 0.0% current value:0 end value:0
2024-06-12 06:47:24,250 INFO  [resource.wrapper.LibvirtMigrateVolumeCommandWrapper] (agentRequest-Handler-5:null) (logid:61c82c80) Block copy completed for the volume vdb : 046bc3d60000000a:vol-4-a139-22ae
2024-06-12 06:47:24,253 WARN  [resource.wrapper.LibvirtMigrateVolumeCommandWrapper] (agentRequest-Handler-5:null) (logid:61c82c80) Migrate volume failed due to org.libvirt.LibvirtException: invalid argument: disk vdb does not have an active block job
org.libvirt.LibvirtException: invalid argument: disk vdb does not have an active block job
        at org.libvirt.ErrorHandler.processError(Unknown Source)
        at org.libvirt.ErrorHandler.processError(Unknown Source)
        at org.libvirt.Domain.blockJobAbort(Unknown Source)
        at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtMigrateVolumeCommandWrapper.checkBlockJobStatus(LibvirtMigrateVolumeCommandWrapper.java:177)
        at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtMigrateVolumeCommandWrapper.migratePowerFlexVolume(LibvirtMigrateVolumeCommandWrapper.java:144)
        at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtMigrateVolumeCommandWrapper.execute(LibvirtMigrateVolumeCommandWrapper.java:81)
        at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtMigrateVolumeCommandWrapper.execute(LibvirtMigrateVolumeCommandWrapper.java:70)
        at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtRequestWrapper.execute(LibvirtRequestWrapper.java:78)
        at com.cloud.hypervisor.kvm.resource.LibvirtComputingResource.executeRequest(LibvirtComputingResource.java:1903)
        at com.cloud.agent.Agent.processRequest(Agent.java:683)
        at com.cloud.agent.Agent$AgentRequestHandler.doTask(Agent.java:1106)
        at com.cloud.utils.nio.Task.call(Task.java:83)
        at com.cloud.utils.nio.Task.call(Task.java:29)
```


8. Fix Check - Upgrade env with PR fix and the migration of the volume succeded

Logs

```
2024-06-12 07:04:42,202 INFO  [resource.wrapper.LibvirtMigrateVolumeCommandWrapper] (agentRequest-Handler-3:null) (logid:aa7b96b2) Block copy has started for the volume vdb : 046bc3d60000000a:vol-4-a139-22ae
2024-06-12 07:04:42,208 DEBUG [resource.wrapper.LibvirtMigrateVolumeCommandWrapper] (agentRequest-Handler-3:null) (logid:aa7b96b2) Volume vdb : 046bc3d60000000a:vol-4-a139-22ae, block copy progress: 0.0%, current value: 0 end value: 68673077248, job info - type: 2, bandwidth: 0
2024-06-12 07:04:43,220 DEBUG [resource.wrapper.LibvirtMigrateVolumeCommandWrapper] (agentRequest-Handler-3:null) (logid:aa7b96b2) Volume vdb : 046bc3d60000000a:vol-4-a139-22ae, block copy progress: 0.3771467398565468%, current value: 258998272 end value: 68673077248, job info - typ


2024-06-12 07:09:21,230 DEBUG [resource.wrapper.LibvirtMigrateVolumeCommandWrapper] (agentRequest-Handler-3:null) (logid:aa7b96b2) Volume vdb : 046bc3d60000000a:vol-4-a139-22ae, block copy progress: 100.0%, current value: 68673077248 end value: 68673077248, job info - type: 2, bandwidth: 0
2024-06-12 07:09:21,230 INFO  [resource.wrapper.LibvirtMigrateVolumeCommandWrapper] (agentRequest-Handler-3:null) (logid:aa7b96b2) Block copy completed for the volume vdb : 046bc3d60000000a:vol-4-a139-22ae

```

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
Changes LGTM, thanks for testing @kiranchavala 
Merging based on manual QA and smoketests and reviews.

**Pull request merged**
