### PR TITLE
CKS: remove details when delete a cks cluster

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR removes the cks cluster details from kubernetes_cluster_details table, when the cluster is removed.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
looks good as in definately an improvement. I wonder what in case of exceptions though?

**Review by shwstppr — APPROVED** [review]

**Review by stephankruggg — APPROVED** [review]
CLGTM

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test keepEnv

**Comment by DaanHoogland** [comment]
tested in a lab env, details are removed, merging

**Pull request merged**
