### PR TITLE
UI: Restored the Basic Networking

### PR DESCRIPTION
**Pull request by utchoang**
### Description

Fixes https://github.com/apache/cloudstack/issues/4863

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### Screenshots (if appropriate):
image

### CODE REVIEW

**Comment by utchoang** [comment]
@blueorangutan ui

**Review by rhtyd — APPROVED** [review]
LGTM tested basic zone deployment using QA env: http://qa.cloudstack.cloud:8080/client/pr/4882/#/zone/50803617-5cc7-4754-b5ab-0658b53ad239

Was able to deploy dummy VM

**Comment by shwstppr** [comment]
Looks good. @utchoang can you please resolve conflict

**Comment by shwstppr** [comment]
@blueorangutan ui

**Review by shwstppr — APPROVED** [review]

**Pull request merged**
