### PR TITLE
[CLOUDSTACK-10189] Adding nuage VSD managed network support to CloudStack.

### PR DESCRIPTION
**Pull request by sgoeminn**
Co-Authored-By: Sigert Goeminne sigert.goeminne@nuagenetworks.net
Co-Authored-By: Raf Smeets raf.smeets@nuagenetworks.netVSD Managed Networks

Design doc: https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=74690626
Ticket: https://issues.apache.org/jira/browse/CLOUDSTACK-10189

### CODE REVIEW

**Comment by krissterckx** [comment]
@borisstoyanov can you launch trillian to this one as well ? Thanks

**Comment by borisstoyanov** [comment]
@krissterckx can you please remind be over the weekend, cause we're running pretty hot at our lab at the moment.

**Comment by krissterckx** [comment]
@borisstoyanov can we pls try for tomorrow Friday. Thanks

**Comment by krissterckx** [comment]
@rhtyd can you initiate reviews please; thank you.

**Comment by krissterckx** [comment]
@borisstoyanov as requested, kind reminder :-)

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by krissterckx** [comment]
@borisstoyanov can you clarify the question for jira number. You mean adding to the PR title ?

Note that all info is mentioned above:

Co-Authored-By: Sigert Goeminne sigert.goeminne@nuagenetworks.netCo-Authored-By: Raf Smeets raf.smeets@nuagenetworks.netVSD Managed NetworksDesign doc: https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=74690626Ticket: https://issues.apache.org/jira/browse/CLOUDSTACK-10189

**Comment by borisstoyanov** [comment]
Yeah, sorry @krissterckx, I've just noticed that as well... usually we make the title of the PR look like: [jira][title]. Let me run some tests.
@blueorangutan test

**Comment by sgoeminn** [comment]
@borisstoyanov I added the JIRA ticket to the title.

**Comment by rhtyd** [comment]
Tests LGTM, ignoring known intermittent failure. I skimmed through the codebase don't see any blockers and most changes in nuage-specific plugin. LGTM.

I'll merge this based on 3 lgtms and test results.

**Pull request merged**
