### PR TITLE
ui: Add 'on / off' to status icon and make it case insensitive

### PR DESCRIPTION
**Pull request by davidjumani**
### Description

Fixes https://github.com/apache/cloudstack/issues/5255

Adds 'On' to the success case of the status icon

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### Screenshots (if appropriate):

Screenshot from 2021-08-05 10-56-39

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan ui

**Comment by shwstppr** [comment]
@davidjumani conflicts here. And what about having it in 4.15?

**Comment by davidjumani** [comment]
@blueorangutan ui

**Review by shwstppr — CHANGES_REQUESTED** [review]
@davidjumani can you please also add 'Off' state

**Comment by davidjumani** [comment]
> @davidjumani can you please also add 'Off' state

The default state is takes care of it (grey icon)

**Review by utchoang — APPROVED** [review]

**Comment by shwstppr** [comment]
@davidjumani Off is not the default state I think. In code we have 4 states defined here, https://github.com/apache/cloudstack/blob/4.15/api/src/main/java/org/apache/cloudstack/outofbandmanagement/OutOfBandManagement.java#L90-L93

**Comment by davidjumani** [comment]
@blueorangutan ui

**Comment by shwstppr** [comment]
@blueorangutan ui

**Review by shwstppr — APPROVED** [review]
LGTM. Tested with simulator
Screenshot from 2021-08-05 12-40-44

**Review by utchoang — APPROVED** [review]

**Review by nvazquez — APPROVED** [review]
Code LGTM

**Pull request merged**
