### PR TITLE
vmware, ui: update portgroup on network update

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Enhanced update network form in the UI.
On network offering change for an isolated network,

- VMware portgroup should be updated accordingly.
- VMs on the network should be placed on the correct VMware portgroup based on the network rate, https://docs.cloudstack.apache.org/en/latest/adminguide/service_offerings.html#network-throttling.
 
### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):
offchangewarning

### CODE REVIEW

**Comment by shwstppr** [comment]
Splitting work from #5181 

@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware65u2

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-65u2

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Comment by sureshanaparti** [comment]
@blueorangutan test matrix

**Comment by alexandremattioli** [comment]
LGTM

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test matrix

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
The vmware issue/failure exists on main branch as seen in https://github.com/apache/cloudstack/pull/5201
Merging this.

**Pull request merged**
