### PR TITLE
Improve the description of config password.policy.minimum.digits

### PR DESCRIPTION
**Pull request by winterhazel**
### Description

Some operators interpret "minimum digits" as "minimum number of characters" and confuse the setting password.policy.minimum.digits with password.policy.minimum.length. This PR changes the description of password.policy.minimum.digits and three other related settings to make the distinction clearer.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

### How Has This Been Tested?

I applied the changes in a local lab and verified the descriptions were updated through the UI.

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]

**Review by kiranchavala — APPROVED** [review]
LGTM, the description looks fine

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
code lgtm

@winterhazel 
could you like to improve description of special characters as well ?

**Review by stephankruggg — APPROVED** [review]
CLGTM, not manually tested

**Review by harikrishna-patnala — APPROVED** [review]

**Comment by DaanHoogland** [comment]
> @winterhazel could you like to improve description of special characters as well ?

@winterhazel , will you honour this request? (I don't think it is a blocking request for change but a good suggestion to complete the improvement) We can always do it later, if we remember ;)

**Comment by weizhouapache** [comment]
> > code lgtm
> > @winterhazel could you like to improve description of special characters as well ?
> 
> @weizhouapache sure, I have changed the description of `password.policy.minimum.special.characters` to indicate which characters are considered special.

thanks @winterhazel 
code lgtm

**Comment by DaanHoogland** [comment]
textual changes only => merging

**Pull request merged**
