### PR TITLE
CLOUDSTACK-9679:Allow master user to manage subordinate user uploaded…

### PR DESCRIPTION
**Pull request by pdumbre**
… template

### CODE REVIEW

**Comment by pdumbre** [comment]
Test Results Passed:
https://travis-ci.org/apache/cloudstack/builds/184533080

**Comment by cloudmonger** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 345
 Hypervisor xenserver
 NetworkType Advanced
 Passed=101
 Failed=3
 Skipped=7

_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/yj3wnzbceo9uef2/AAB6u-Iap-xztdm6jHX9SjPja?dl=0


**Failed tests:**
* test_routers_network_ops.py

 * test_01_RVR_Network_FW_PF_SSH_default_routes_egress_true Failed

 * test_02_RVR_Network_FW_PF_SSH_default_routes_egress_false Failed

 * test_03_RVR_Network_check_router_state Failing since 2 runs


**Skipped tests:**
test_01_test_vm_volume_snapshot
test_vm_nic_adapter_vmxnet3
test_static_role_account_acls
test_11_ss_nfs_version_on_ssvm
test_nested_virtualization_vmware
test_3d_gpu_support
test_deploy_vgpu_enabled_vm

**Passed test suits:**
test_deploy_vm_with_userdata.py
test_affinity_groups_projects.py
test_portable_publicip.py
test_over_provisioning.py
test_global_settings.py
test_scale_vm.py
test_service_offerings.py
test_routers_iptables_default_policy.py
test_loadbalance.py
test_routers.py
test_reset_vm_on_reboot.py
test_deploy_vms_with_varied_deploymentplanners.py
test_network.py
test_router_dns.py
test_non_contigiousvlan.py
test_login.py
test_deploy_vm_iso.py
test_list_ids_parameter.py
test_public_ip_range.py
test_multipleips_per_nic.py
test_regions.py
test_affinity_groups.py
test_network_acl.py
test_pvlan.py
test_volumes.py
test_nic.py
test_deploy_vm_root_resize.py
test_resource_detail.py
test_secondary_storage.py
test_vm_life_cycle.py
test_disk_offerings.py

**Comment by pdumbre** [comment]
Issue Description: Domain admin can not view templates uploaded by his domain users.Only root admin can view templates uploaded by all domain users.

Fix:  Code changes are done to make templates uploaded by domain users visible to domain admin.

**Comment by koushik-das** [comment]
Code changes LGTM

**Comment by karuturi** [comment]
merging

**Comment by pdion891** [comment]
@pdumbre @karuturi @syed 
I thinks this introduce an issue where a domain admin cannot get a template by id. 
a domain admin can list feature template and get a template via `ids=` but not with `id=`
The example bellow is perform with a domain admin account to list public+featured template at root domain:

```
(beta2r1-ninja) > list templates templatefilter=featured filter=name,id
count = 9
template:
+--------------------------------------+---------------------------------+
|                  id                  |               name              |
+--------------------------------------+---------------------------------+
| 513b3a6d-c011-46f0-a4a3-2a954cadb673 |      CoreOS Alpha 1367.5.0      |
| 0c04d876-1f85-45a7-b6f4-504de435bf12 |    Debian 8.5 PV base (64bit)   |
| 285f2203-449a-428f-997a-1ffbebbf1382 |           CoreOS Alpha          |
| 332b6ca8-b3d6-42c7-83e5-60fe87be6576 |          CoreOS Stable          |
| 3b705008-c186-464d-ad59-312d902420af |   Windows Server 2016 std SPLA  |
| 4256aebe-a1c1-4b49-9993-de2bc712d521 |       Ubuntu 16.04.01 HVM       |
| 59e6b00a-b88e-4539-aa3c-75c9c7e9fa6c | Ubuntu 14.04.5 HVM base (64bit) |
| 3ab936eb-d8c2-44d8-a64b-17ad5adf8a51 |          CentOS 6.8 PV          |
| 7de5d423-c91e-49cc-86e8-9d6ed6abd997 |          CentOS 7.2 HVM         |
+--------------------------------------+---------------------------------+
(beta2r1-ninja) > list templates templatefilter=featured id=7de5d423-c91e-49cc-86e8-9d6ed6abd997 filter=name,id
Error 531: Acct[b285d62e-0ec2-4a7c-b773-961595ec6356-Ninja-5664] does not have permission to operate within domain id=c9b4f83d-16eb-11e7-a8b9-367e6fe958a9
cserrorcode = 4365
errorcode = 531
errortext = Acct[b285d62e-0ec2-4a7c-b773-961595ec6356-Ninja-5664] does not have permission to operate within domain id=c9b4f83d-16eb-11e7-a8b9-367e6fe958a9
uuidList:
(beta2r1-ninja) > list templates templatefilter=featured ids=7de5d423-c91e-49cc-86e8-9d6ed6abd997 filter=name,id
count = 1
template:
+--------------------------------------+----------------+
|                  id                  |      name      |
+--------------------------------------+----------------+
| 7de5d423-c91e-49cc-86e8-9d6ed6abd997 | CentOS 7.2 HVM |
+--------------------------------------+----------------+
```

**Pull request merged**
