### PR TITLE
UI - Add clear all notification button

### PR DESCRIPTION
**Pull request by utchoang**
### Description

Fixes https://github.com/apache/cloudstack/issues/5538

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### Screenshots (if appropriate):
image

### CODE REVIEW

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by davidjumani** [comment]
@utchoang The notifications cover the usermenu and the clear all icon
Screenshot from 2021-10-05 10-25-38

**Comment by utchoang** [comment]
@davidjumani Please refresh or clear cache, I have the same problem as you in QA server but after ctrl+f5 it works fine.
image

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by davidjumani** [comment]
@blueorangutan ui

**Comment by rhtyd** [comment]
The UX is weird, it won't be obvious for first-time users what the new icons does. Should there be a floating widget on the top saying clear all? (something like that seen in phones?)

**Comment by utchoang** [comment]
@rhtyd cc @davidjumani  I also noticed this inconvenience. But still can't find a better solution. What do you think?

**Comment by utchoang** [comment]
Close because it doesn't solve the problem because the notifications will automatically turn off after duration 5s.

**Comment by utchoang** [comment]
Another solution for the clear notification button
cc @rhtyd @DaanHoogland @davidjumani 
image

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by utchoang** [comment]
@davidjumani Currently, I have not found any interference with the ant design notification library. Do you have a good way to do that?

**Comment by DaanHoogland** [comment]
How about an item in the notifications menu, near 'clear all', @utchoang ?

**Comment by utchoang** [comment]
@DaanHoogland I don't think that's reasonable. What do you think about the position of clear button as below image?
image

**Comment by utchoang** [comment]
@DaanHoogland I don't think that's reasonable. What do you think about the position of clear button as below image?
image

**Comment by utchoang** [comment]
> @utchoang Would it be possible to add a clear all button on just the first notification ? Screenshot from 2021-10-06 09-29-50

@davidjumani 
I have tried your case. But there is a problem as the following case:
Step 1: There is more than 1 notification and clear all button is displayed on the first notification
Step 2: Turn off the first notification with the close button.
Result: The remaining notifications are still displayed but there is no clear all button (because the clear all button only show when notification display)

**Comment by utchoang** [comment]
@blueorangutan ui

**Comment by DaanHoogland** [comment]
> @DaanHoogland I don't think that's reasonable. What do you think about the position of clear button as below image?
I like my idea better ;)
/me not making a fuzz about it.

**Comment by rhtyd** [comment]
@blueorangutan ui

**Comment by sureshanaparti** [comment]
@blueorangutan ui

**Review by shwstppr — APPROVED** [review]
Works as expected. Though I don't like the idea of clear button in the first notification. A separate button at the top of the notifications would have made more sense, as shown earlier by @utchoang, 
image

**Comment by utchoang** [comment]
@shwstppr I reverted the clear all button back to the top of the notification. You can check and we can merge.
image

**Comment by utchoang** [comment]
@blueorangutan ui

**Review by rohityadavcloud — APPROVED** [review]

**Pull request merged**
