### PR TITLE
New API endpoint to update pod management network IP range

### PR DESCRIPTION
**Pull request by sureshanaparti**
### Description

This PR introduces a new API endpoint to update pod management network IP range.

Currently, pod management IP range can only be expanded under the same subnet. Editing the current pod IP management range is a challenge, especially as the list of IP ranges is greater than one. The purpose of this feature is to allow ADMINS to be able to update size of IP range of management pod, upwards or downwards.

This PR extends from #4010

- Updatepodmanagementnetworkiprange will update already existing IP ranges. Will not create a new IP range.
- Will increase/reduce available IPs within the range.
- PodID/Currentstartip/CurrentendIp are mandatory fields. Newstartip and Newendip are optional fields and one of them should be specified. When anyone is left blank, Newstartip will be set to Currentstartip and Newendip will be set to Currentendip.
- API only available to root admin and does not have any sensitive information passed.
- Will output success response -true/false
- Does not alter structure of DB, but will update contents.

**When to use**

- Reducing size of existing IP range
- Increasing size of existing IP range

**How to use**

Run `list pods` command to see existing IP ranges
```
> list pods
{
  "count": 1,
  "pod": [
    {
      "allocationstate": "Enabled",
      "endip": [
        "172.16.15.210",
        "172.16.15.204"
      ],
      "forsystemvms": [
        "0",
        "0"
      ],
      "gateway": "172.16.15.1",
      "id": "1407da22-a131-4dbd-86a3-45210a26897e",
      "name": "POD0",
      "netmask": "255.255.255.0",
      "startip": [
        "172.16.15.205",
        "172.16.15.2"
      ],
      "vlanid": [
        "vlan://untagged",
        "vlan://untagged"
      ],
      "zoneid": "3ab731d6-efd5-418c-ab2b-cacbfc4b88f0",
      "zonename": "Sandbox-simulator"
    }
  ]
}
```
2. Update the IP range you'd like to change. In our case, we want to increase the range `172.16.15.205-172.16.15.210` to `172.16.15.205-172.16.15.215`. Use the command `update podmanagementnetworkiprange`

```
> update podmanagementnetworkiprange podid=1407da22-a131-4dbd-86a3-45210a26897e currentstartip=172.16.15.205 currentendip=172.16.15.210 newendip=172.16.15.215
{
  "success": true
}
```
To reduce size of range to `172.16.15.205-172.16.15.207`
```
> update podmanagementnetworkiprange podid=1407da22-a131-4dbd-86a3-45210a26897e currentstartip=172.16.15.205 currentendip=172.16.15.215 newendip=172.16.15.207
{
  "success": true
}
```
Confirm by running `list pods` again
```
> list pods 
{
  "count": 1,
  "pod": [
    {
      "allocationstate": "Enabled",
      "endip": [
        "172.16.15.207",
        "172.16.15.204"
      ],
      "forsystemvms": [
        "0",
        "0"
      ],
      "gateway": "172.16.15.1",
      "id": "1407da22-a131-4dbd-86a3-45210a26897e",
      "name": "POD0",
      "netmask": "255.255.255.0",
      "startip": [
        "172.16.15.205",
        "172.16.15.2"
      ],
      "vlanid": [
        "vlan://untagged",
        "vlan://untagged"
      ],
      "zoneid": "3ab731d6-efd5-418c-ab2b-cacbfc4b88f0",
      "zonename": "Sandbox-simulator"
    }
  ]
}
```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

**Manual Tests** (with PR# 4010)
- Test for invalid parameters for Currentstartip/Currentendip/Newstartip/Newendip
- Test for invalid current IP range
- Test for overlapping IP range extensions
- Test for non-existent IP range
- Test for Newstartip>Newendip
- Test for duplicate IP range
- Test for invalid Pod ID
- Test to reduce existing IP range to not include already allocated IPs

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Review by rhtyd — APPROVED** [review]
Lgtm, this will need testing

**Review by DaanHoogland — APPROVED** [review]
cltgm

**Review by nvazquez — APPROVED** [review]
LGTM - Tested OK

Screenshot from 2021-09-20 18-15-20

Before recreating system VMs:

````
MariaDB [cloud]> select * from op_dc_ip_address_alloc;
+----+------------+----------------+--------+--------+--------------------------------------+---------------------+-------------+--------------+------+
| id | ip_address | data_center_id | pod_id | nic_id | reservation_id                       | taken               | mac_address | forsystemvms | vlan |
+----+------------+----------------+--------+--------+--------------------------------------+---------------------+-------------+--------------+------+
|  1 | 10.0.36.21 |              1 |      1 |      3 | 97435d30-f32f-41ad-a803-b9cbb2a0ad01 | 2021-09-20 19:31:26 |          21 |            0 | NULL |
|  2 | 10.0.36.22 |              1 |      1 |      6 | 2d22af30-058d-471c-b76e-92b2b93b0b81 | 2021-09-20 19:31:26 |          22 |            0 | NULL |
|  3 | 10.0.36.23 |              1 |      1 |   NULL | NULL                                 | NULL                |          23 |            0 | NULL |
|  4 | 10.0.36.24 |              1 |      1 |   NULL | NULL                                 | NULL                |          24 |            0 | NULL |
|  5 | 10.0.36.25 |              1 |      1 |   NULL | NULL                                 | NULL                |          25 |            0 | NULL |
|  6 | 10.0.36.26 |              1 |      1 |   NULL | NULL                                 | NULL                |          26 |            0 | NULL |
|  7 | 10.0.36.27 |              1 |      1 |   NULL | NULL                                 | NULL                |          27 |            0 | NULL |
|  8 | 10.0.36.28 |              1 |      1 |   NULL | NULL                                 | NULL                |          28 |            0 | NULL |
|  9 | 10.0.36.29 |              1 |      1 |   NULL | NULL                                 | NULL                |          29 |            0 | NULL |
| 10 | 10.0.36.30 |              1 |      1 |   NULL | NULL                                 | NULL                |          30 |            0 | NULL |
| 11 | 10.0.36.31 |              1 |      1 |   NULL | NULL                                 | NULL                |          31 |            0 | NULL |
| 12 | 10.0.36.32 |              1 |      1 |   NULL | NULL                                 | NULL                |          32 |            0 | NULL |
| 13 | 10.0.36.33 |              1 |      1 |   NULL | NULL                                 | NULL                |          33 |            0 | NULL |
| 14 | 10.0.36.34 |              1 |      1 |   NULL | NULL                                 | NULL                |          34 |            0 | NULL |
| 15 | 10.0.36.35 |              1 |      1 |   NULL | NULL                                 | NULL                |          35 |            0 | NULL |
| 16 | 10.0.36.36 |              1 |      1 |   NULL | NULL                                 | NULL                |          36 |            0 | NULL |
| 17 | 10.0.36.37 |              1 |      1 |   NULL | NULL                                 | NULL                |          37 |            0 | NULL |
| 18 | 10.0.36.38 |              1 |      1 |   NULL | NULL                                 | NULL                |          38 |            0 | NULL |
| 19 | 10.0.36.39 |              1 |      1 |   NULL | NULL                                 | NULL                |          39 |            0 | NULL |
| 20 | 10.0.36.40 |              1 |      1 |   NULL | NULL                                 | NULL                |          40 |            0 | NULL |
| 21 | 10.0.36.41 |              1 |      1 |   NULL | NULL                                 | NULL                |          41 |            1 | NULL |
| 22 | 10.0.36.42 |              1 |      1 |   NULL | NULL                                 | NULL                |          42 |            1 | NULL |
| 23 | 10.0.36.43 |              1 |      1 |   NULL | NULL                                 | NULL                |          43 |            1 | NULL |
| 24 | 10.0.36.44 |              1 |      1 |   NULL | NULL                                 | NULL                |          44 |            1 | NULL |
| 25 | 10.0.36.45 |              1 |      1 |   NULL | NULL                                 | NULL                |          45 |            1 | NULL |
| 26 | 10.0.36.46 |              1 |      1 |   NULL | NULL                                 | NULL                |          46 |            1 | NULL |
| 27 | 10.0.36.47 |              1 |      1 |   NULL | NULL                                 | NULL                |          47 |            1 | NULL |
| 28 | 10.0.36.48 |              1 |      1 |   NULL | NULL                                 | NULL                |          48 |            1 | NULL |
| 29 | 10.0.36.49 |              1 |      1 |   NULL | NULL                                 | NULL                |          49 |            1 | NULL |
| 30 | 10.0.36.50 |              1 |      1 |   NULL | NULL                                 | NULL                |          50 |            1 | NULL |
+----+------------+----------------+--------+--------+--------------------------------------+---------------------+-------------+--------------+------+
30 rows in set (0.00 sec)
````

After recreating system VMs:

````
MariaDB [cloud]> select * from op_dc_ip_address_alloc;
+----+------------+----------------+--------+--------+--------------------------------------+---------------------+-------------+--------------+------+
| id | ip_address | data_center_id | pod_id | nic_id | reservation_id                       | taken               | mac_address | forsystemvms | vlan |
+----+------------+----------------+--------+--------+--------------------------------------+---------------------+-------------+--------------+------+
|  1 | 10.0.36.21 |              1 |      1 |   NULL | NULL                                 | NULL                |          21 |            0 | NULL |
|  2 | 10.0.36.22 |              1 |      1 |   NULL | NULL                                 | NULL                |          22 |            0 | NULL |
|  3 | 10.0.36.23 |              1 |      1 |   NULL | NULL                                 | NULL                |          23 |            0 | NULL |
|  4 | 10.0.36.24 |              1 |      1 |   NULL | NULL                                 | NULL                |          24 |            0 | NULL |
|  5 | 10.0.36.25 |              1 |      1 |   NULL | NULL                                 | NULL                |          25 |            0 | NULL |
|  6 | 10.0.36.26 |              1 |      1 |   NULL | NULL                                 | NULL                |          26 |            0 | NULL |
|  7 | 10.0.36.27 |              1 |      1 |   NULL | NULL                                 | NULL                |          27 |            0 | NULL |
|  8 | 10.0.36.28 |              1 |      1 |   NULL | NULL                                 | NULL                |          28 |            0 | NULL |
|  9 | 10.0.36.29 |              1 |      1 |   NULL | NULL                                 | NULL                |          29 |            0 | NULL |
| 10 | 10.0.36.30 |              1 |      1 |   NULL | NULL                                 | NULL                |          30 |            0 | NULL |
| 11 | 10.0.36.31 |              1 |      1 |   NULL | NULL                                 | NULL                |          31 |            0 | NULL |
| 12 | 10.0.36.32 |              1 |      1 |   NULL | NULL                                 | NULL                |          32 |            0 | NULL |
| 13 | 10.0.36.33 |              1 |      1 |   NULL | NULL                                 | NULL                |          33 |            0 | NULL |
| 14 | 10.0.36.34 |              1 |      1 |   NULL | NULL                                 | NULL                |          34 |            0 | NULL |
| 15 | 10.0.36.35 |              1 |      1 |   NULL | NULL                                 | NULL                |          35 |            0 | NULL |
| 16 | 10.0.36.36 |              1 |      1 |   NULL | NULL                                 | NULL                |          36 |            0 | NULL |
| 17 | 10.0.36.37 |              1 |      1 |   NULL | NULL                                 | NULL                |          37 |            0 | NULL |
| 18 | 10.0.36.38 |              1 |      1 |   NULL | NULL                                 | NULL                |          38 |            0 | NULL |
| 19 | 10.0.36.39 |              1 |      1 |   NULL | NULL                                 | NULL                |          39 |            0 | NULL |
| 20 | 10.0.36.40 |              1 |      1 |   NULL | NULL                                 | NULL                |          40 |            0 | NULL |
| 21 | 10.0.36.41 |              1 |      1 |      9 | 735afd76-eae0-44d4-8554-8963f732d359 | 2021-09-20 21:16:56 |          41 |            1 | NULL |
| 22 | 10.0.36.42 |              1 |      1 |   NULL | NULL                                 | NULL                |          42 |            1 | NULL |
| 23 | 10.0.36.43 |              1 |      1 |   NULL | NULL                                 | NULL                |          43 |            1 | NULL |
| 24 | 10.0.36.44 |              1 |      1 |   NULL | NULL                                 | NULL                |          44 |            1 | NULL |
| 25 | 10.0.36.45 |              1 |      1 |   NULL | NULL                                 | NULL                |          45 |            1 | NULL |
| 26 | 10.0.36.46 |              1 |      1 |     12 | b439a631-5375-4d00-a88c-27bb58028b82 | 2021-09-20 21:17:25 |          46 |            1 | NULL |
| 27 | 10.0.36.47 |              1 |      1 |   NULL | NULL                                 | NULL                |          47 |            1 | NULL |
| 28 | 10.0.36.48 |              1 |      1 |   NULL | NULL                                 | NULL                |          48 |            1 | NULL |
| 29 | 10.0.36.49 |              1 |      1 |   NULL | NULL                                 | NULL                |          49 |            1 | NULL |
| 30 | 10.0.36.50 |              1 |      1 |   NULL | NULL                                 | NULL                |          50 |            1 | NULL |
+----+------------+----------------+--------+--------+--------------------------------------+---------------------+-------------+--------------+------+
30 rows in set (0.00 sec)
````

**Pull request merged**
