### PR TITLE
api: remove empty response parameters

### PR DESCRIPTION
**Pull request by marcaurele**
## Description
Remove response parameters missing a description, and which are not used, creating an empty entry in `listApis` call (see the empty `{}` below):

```json
      "related": "listZones,createZone",
      "response": [
        {
          "description": "the allocation state of the cluster",
          "name": "allocationstate",
          "type": "string"
        },
        {},
        {
          "description": "the first DNS for the Zone",
          "name": "dns1",
          "type": "string"
},
```

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

## Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

Testing
- [ ] I have added tests to cover my changes.
- [ ] All relevant new and existing integration tests have passed.
- [ ] A full integration testsuite with all test that can run on my environment has passed.

### CODE REVIEW

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
Hi @marcaurele, thanks for this fix. Can you please share some examples how you've tested it?

**Comment by marcaurele** [comment]
@borisstoyanov I simply did a local compilation but I pushed before checking it went fine. I missed a line removal. I just force pushed an amend.

To test: you can check the actual empty parameters with the cs python lib:
`cs listApis | grep "{}"` and you should get 2 of them (based on the fork we're using).

**Comment by borisstoyanov** [comment]
Thanks @marcaurele, let me try that and will run smoketests as well

**Comment by DaanHoogland** [comment]
looks good, Marc-aurele but are we sure they are really never filled in a response?

**Comment by marcaurele** [comment]
@DaanHoogland yes, otherwise the code won't compile.

**Comment by DaanHoogland** [comment]
not if reflection is somehow used. not to blame you but I am a bit wary with these kind of left-overs. Actually in this case I think you are right.

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Pull request merged**
