### PR TITLE
UI : Fix SSL certificate submit button not working

### PR DESCRIPTION
**Pull request by dhslove**
### Description

This PR fixes an issue where clicking the Submit button in the SSL Certificates dialog in the Infrastructure Summary UI did not work.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### Screenshots (if appropriate):

image

### CODE REVIEW

**Comment by Pearl1594** [comment]
@blueorangutan ui

**Review by Pearl1594 — APPROVED** [review]
LGTM

**Review by utchoang — APPROVED** [review]
LGTM

**Comment by rhtyd** [comment]
LGTM, @dhslove can you rebase to 4.16 branch - much needed fix towards 4.16.1

**Comment by dhslove** [comment]
> LGTM, @dhslove can you rebase to 4.16 branch - much needed fix towards 4.16.1

Rebased to 4.16.

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by rhtyd** [comment]
@blueorangutan ui

**Comment by GabrielBrascher** [comment]
:arrow_right: Not related only to this PR:
> UI build: heavy_check_mark Live QA URL: http://qa.cloudstack.cloud:8080/client/pr/5682 (SL-JID-832)

I am having trouble to log in into thee `qa.cloudstack.cloud` recently. Is it just me?

```
Error
Exception caught while discovering features
```

Responses look good (OK 200). But there is the above error message.

**Comment by rhtyd** [comment]
I'll check and restart it @GabrielBrascher

**Comment by hstan77** [comment]
I am facing the same issue , i installed on Ubuntu 20,  do I need to do wait for 4.16.1 ? or  any patch to solve this .

**Comment by DaanHoogland** [comment]
@hstan77 If you can patch yourself you can apply the commit in https://github.com/apache/cloudstack/commit/a8e7315e53b3539d336b35fc127c2dd34624d413

**Comment by hstan77** [comment]
@DaanHoogland this is patch to the source and recompile it right ?

**Comment by DaanHoogland** [comment]
It is part of the source for the UI yes.

**Pull request merged**
