### PR TITLE
CLOUDSTACK-9353: [XenServer] Fixed VM migration with storage

### PR DESCRIPTION
**Pull request by anshul1886**
In turn this also fixes VM migration with local storage

This PR is created against 4.7 and can be forward merged to future branches also.

### CODE REVIEW

**Comment by remibergsma** [comment]
Same approach as proposed in #925, although both address different problems. I'd say let's test this stuff and get it in to resolve these issues. We may want to look to the other PR as well, although we cannot merge both without some tweaks.

**Comment by anshul1886** [comment]
@remibergsma #925 is no more valid after fix of #1336. This PR handles the broken case i.e. migration with storage with cluster is currently broken.

**Comment by remibergsma** [comment]
@anshul1886 Ok, thanks. I think we should close that old one, shouldn't we?

**Comment by swill** [comment]
This should probably get int0 4.9 right?  If this is broken we should try to get the fix in as early as possible right?  There are other potential issues pending, so we have not pushed forward on the 4.9 RC yet.

**Comment by anshul1886** [comment]
@remibergsma Yes, we can close old one. @swill This PR is created against 4.7 so it can be forward merged to all branches.

**Comment by swill** [comment]
### CI RESULTS

```
Tests Run: 85
  Skipped: 0
   Failed: 0
   Errors: 0
 Duration: 4h 02m 49s
```



**Associated Uploads**

**`/tmp/MarvinLogs/DeployDataCenter__Jun_27_2016_22_57_23_SVYGMK:`**
* [dc_entries.obj](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1596/tmp/MarvinLogs/DeployDataCenter__Jun_27_2016_22_57_23_SVYGMK/dc_entries.obj)
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1596/tmp/MarvinLogs/DeployDataCenter__Jun_27_2016_22_57_23_SVYGMK/failed_plus_exceptions.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1596/tmp/MarvinLogs/DeployDataCenter__Jun_27_2016_22_57_23_SVYGMK/runinfo.txt)

**`/tmp/MarvinLogs/test_network_346OKD:`**
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1596/tmp/MarvinLogs/test_network_346OKD/failed_plus_exceptions.txt)
* [results.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1596/tmp/MarvinLogs/test_network_346OKD/results.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1596/tmp/MarvinLogs/test_network_346OKD/runinfo.txt)

**`/tmp/MarvinLogs/test_vpc_routers_YO70GO:`**
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1596/tmp/MarvinLogs/test_vpc_routers_YO70GO/failed_plus_exceptions.txt)
* [results.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1596/tmp/MarvinLogs/test_vpc_routers_YO70GO/results.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1596/tmp/MarvinLogs/test_vpc_routers_YO70GO/runinfo.txt)


Uploads will be available until `2016-08-28 02:00:00 +0200 CEST`

*Comment created by [`upr comment`](https://github.com/cloudops/upr).*

**Comment by swill** [comment]
Ok, this is coming back clean.  Do you guys agree I should merge this into 4.9 as it fixes issues?  Thanks...

**Pull request merged**
