### PR TITLE
cks: fix k8s version upgrade

### LINKED ISSUE #6514: cks: k8s version not changed after upgrade
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
CKS, UI
~~~

##### CLOUDSTACK VERSION

~~~
4.17
~~~

##### CONFIGURATION

CKS plugin enabled

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Kubernetes cluster version is not updated after upgrade.

##### STEPS TO REPRODUCE

~~~
1. Create a kubernetes cluster version 1.23.3 (for example)
2. Verify the version using kubectl --kubeconfig kube.conf get nodes --all-namespaces
3. Upgrade cluster to a newer version - 1.24.0 (for example)
4. Verify the version both in ACS UI and using the kubectl command again.
~~~

##### EXPECTED RESULTS

~~~
The kubernetes cluster version must be updated.
~~~

##### ACTUAL RESULTS

~~~
Before upgrade:

$ kubectl --kubeconfig kube.conf get nodes --all-namespaces
NAME                       STATUS   ROLES                  AGE   VERSION
kube-control-181aa9c195d   Ready    control-plane,master   16m   v1.23.3
kube-node-181aa9c4efa      Ready    <none>                 16m   v1.23.3

After upgrade:

$ kubectl --kubeconfig kube.conf get nodes --all-namespaces
NAME                       STATUS   ROLES                  AGE   VERSION
kube-control-181aa9c195d   Ready    control-plane,master   33m   v1.23.3
kube-node-181aa9c4efa      Ready    <none>                 32m   v1.23.3

According to ACS UI:
~~~
image

### PR DESCRIPTION
**Pull request by shwstppr**
### Description
Fixes #6514 

On latest systemvm template used for CKS `/usr/sbin` is not present in the `$PATH` for normal user used during upgrade. This leads to failure for `blkid` command. Due to this during k8s version upgrade ISO is not being able to mount on the k8s cluster VMs and upgrade process is not carried out.
This PR fixes mounting of k8s version ISO and also returns failure for script when ISO mounting is failed.
Same failure is not seen during deployment of the cluster because `setup-kube-system` workflow is executed as ROOT user and it has a different value for $PATH.
From `/etc/login.defs`:
```
ENV_SUPATH	PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV_PATH	PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

By deploying a k8s cluster with version 1.23.3 and upgrading it to 1.24.0

k8s cluster and version
```
(localcloud) 🐱 > list kubernetesclusters filter=id,name,kubernetesversionid,kubernetesversionname,ipaddress
{
  "count": 2,
  "kubernetescluster": [
    {
      "id": "8ee0e819-0a59-4417-ab79-e0daee6bb6d9",
      "kubernetesversionid": "8429a514-38cb-4c9e-a81c-7d3491ad8f6a",
      "kubernetesversionname": "v1.23.3",
      "name": "t1",
      "ipaddress": "10.0.52.23"
    },
    {
      "id": "7684079e-bf0a-4260-8102-57f7cad800cf",
      "kubernetesversionid": "8429a514-38cb-4c9e-a81c-7d3491ad8f6a",
      "kubernetesversionname": "v1.23.3",
      "name": "t2",
      "ipaddress": "10.0.52.24"
    }
  ]
}
(localcloud) 🐱 > list kubernetessupportedversions filter=id,name,semanticversion
{
  "count": 2,
  "kubernetessupportedversion": [
    {
      "id": "8429a514-38cb-4c9e-a81c-7d3491ad8f6a",
      "name": "v1.23.3",
      "semanticversion": "1.23.3"
    },
    {
      "id": "302266c2-6414-467a-97a7-d866d59568d9",
      "name": "v1.24.0",
      "semanticversion": "1.24.0"
    }
  ]
}
```

Upgrade k8s cluster t1
```
(localcloud) 🐱 > upgrade kubernetescluster id=8ee0e819-0a59-4417-ab79-e0daee6bb6d9 kubernetesversionid=302266c2-6414-467a-97a7-d866d59568d9
{
  "kubernetescluster": {
    "account": "admin",
    "associatednetworkname": "t1-network",
    "autoscalingenabled": false,
    "controlnodes": 1,
    "cpunumber": "4",
    "description": "t1",
    "domain": "ROOT",
    "domainid": "2e8b5f3a-f71a-11ec-87b5-1e0057000461",
    "endpoint": "https://10.0.52.23:6443/",
    "hasannotations": false,
    "id": "8ee0e819-0a59-4417-ab79-e0daee6bb6d9",
    "ipaddress": "10.0.52.23",
    "ipaddressid": "a70d3bdb-892f-42bc-8c47-cb35b31e28ee",
    "kubernetesversionid": "302266c2-6414-467a-97a7-d866d59568d9",
    "kubernetesversionname": "v1.24.0",
    "masternodes": 1,
    "memory": "4096",
    "name": "t1",
    ...
  }
```

Test upgraded k8s cluster - **k8s cluster internals not upgraded** 
```
[root@ref-trl-3339-v-M7-abhishek-kumar-mgmt1 ~]# ssh cloud@10.0.52.23 -p 2222 -i /var/cloudstack/management/.ssh/id_rsa
Linux t1-control-181ac014de0 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
cloud@t1-control-181ac014de0:~$ sudo /opt/bin/kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
cloud@t1-control-181ac014de0:~$ sudo /opt/bin/kubectl get nodes -A
NAME                     STATUS   ROLES                  AGE   VERSION
t1-control-181ac014de0   Ready    control-plane,master   44m   v1.23.3
t1-node-181ac01ab0f      Ready    <none>                 43m   v1.23.3
cloud@t1-control-181ac014de0:~$ 
```

**Upgrade env to the PR packages and then upgrade the second k8s cluster**

Upgrade cluster t2
```
(localcloud) 🐱 > upgrade kubernetescluster id=7684079e-bf0a-4260-8102-57f7cad800cf kubernetesversionid=302266c2-6414-467a-97a7-d866d59568d9
{
  "kubernetescluster": {
    "account": "admin",
    "associatednetworkname": "t2-network",
    "autoscalingenabled": false,
    "controlnodes": 1,
    "cpunumber": "4",
    "description": "t2",
    "domain": "ROOT",
    "domainid": "2e8b5f3a-f71a-11ec-87b5-1e0057000461",
    "endpoint": "https://10.0.52.24:6443/",
    "hasannotations": false,
    "id": "7684079e-bf0a-4260-8102-57f7cad800cf",
    "ipaddress": "10.0.52.24",
    "ipaddressid": "fcd69e09-c219-4f7f-9ec9-9fd426b24d51",
    "kubernetesversionid": "302266c2-6414-467a-97a7-d866d59568d9",
    "kubernetesversionname": "v1.24.0",
    "masternodes": 1,
    "memory": "4096",
    "name": "t2",
    ...
  }
}
```

Testing control node of the upgraded cluster - **k8s cluster internals upgraded** 
```
[root@ref-trl-3339-v-M7-abhishek-kumar-mgmt1 ~]# ssh cloud@10.0.52.24 -p 2222 -i /var/cloudstack/management/.ssh/id_rsa
The authenticity of host '[10.0.52.24]:2222 ([10.0.52.24]:2222)' can't be established.
ECDSA key fingerprint is SHA256:834gnw/UfwR/sNwEMv8+aHWDcDzrG8/oN4Q7wgRgIYY.
ECDSA key fingerprint is MD5:43:f7:f2:57:38:1b:d8:02:d3:9a:a7:4f:81:52:ef:3d.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '[10.0.52.24]:2222' (ECDSA) to the list of known hosts.
Linux t2-control-181ac07e622 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
cloud@t2-control-181ac07e622:~$ sudo /opt/bin/kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:38:19Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
cloud@t2-control-181ac07e622:~$ sudo /opt/bin/kubectl get nodes -A
NAME                     STATUS   ROLES           AGE   VERSION
t2-control-181ac07e622   Ready    control-plane   49m   v1.24.0
t2-node-181ac084a0d      Ready    <none>          49m   v1.24.0
```

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Review by vladimirpetrov — APPROVED** [review]
LGTM based on manual testing.

**Review by rohityadavcloud — APPROVED** [review]

**Pull request merged**
