### PR TITLE
cks: fix k8s cluster deployment with host tagged offering

### LINKED ISSUE #6657: Create Kubernetes Cluster fails when using Service Offering with more than one host tags
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Kubernetes, CKS, KubernetesClusterManagerImpl
~~~

##### CLOUDSTACK VERSION

~~~
4.17.0.1
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

KVM based hypervisor

##### SUMMARY

Creating a Kubernetes Cluster fails with error message "Creating Kubernetes cluster failed due to insufficient capacity" when the Service Offering has more than one host tag, comma separated.

##### STEPS TO REPRODUCE

1. If no host with more than one host tag exists, assign one or more hosts more than one host tag, comma separated, for example
performance,nowindows

2. If not existing yet, create a Kubernetes ISO with min CPU 2 and min Memory 2048 MB

3. Create a Service Offering with multiple host tags, matching the host tags of the first step, in our example
performance,nowindows
and which is fitting the minimum kubernetes requirements of step two, in our example more than 2 vCPU and more than 2048 MB Memory

4. Chose "Compute / Kubernetes / Create Kubernetes Cluster" and select the Compute Offering with more than one host tag, created earlier.

The deployment will fail with the error message
"Request failed. (530) Creating Kubernetes cluster failed due to insufficient capacity for 2 nodes cluster in zone : xxxx with service offering xxxx"

The management server log will show
```
2022-08-18 17:34:06,835 DEBUG [c.c.u.AccountManagerImpl] (qtp262366552-3231:ctx-aaf26d13 ctx-13c55a78) (logid:6ff75d8d) Access to Acct[xxxxxxx-xxxxxxx] -- Account {"id":
 60, "name": "xxxxxxx", "uuid": "xxxxxxx"} granted to Acct[xxxxxxx-xxxxxxx] -- Account {"id": 60, "name": "xxxxxxx", "uuid": "xxxxxxxxxx"} by DomainChecker
2022-08-18 17:34:06,958 INFO  [c.c.k.c.KubernetesClusterManagerImpl] (qtp262366552-3231:ctx-aaf26d13 ctx-13c55a78) (logid:6ff75d8d) Suitable hosts not found in datacenter ID: f2665eef-1073-4c50-8d3a-076d4
4036fcc for node 1 with offering ID: 1b2c036e-d7c6-470e-820c-83b34f8d5af7
2022-08-18 17:34:06,958 WARN  [c.c.k.c.KubernetesClusterManagerImpl] (qtp262366552-3231:ctx-aaf26d13 ctx-13c55a78) (logid:6ff75d8d) Cannot find enough capacity for Kubernetes cluster(requested cpu=8000 me
mory=8589934592) with offering ID: 1b2c036e-d7c6-470e-820c-83b34f8d5af7
2022-08-18 17:34:06,959 ERROR [c.c.k.c.KubernetesClusterManagerImpl] (qtp262366552-3231:ctx-aaf26d13 ctx-13c55a78) (logid:6ff75d8d) Creating Kubernetes cluster failed due to insufficient capacity for 2 no
des cluster in zone : Zone-01 with service offering : Medium
2022-08-18 17:34:06,959 INFO  [c.c.a.ApiServer] (qtp262366552-3231:ctx-aaf26d13 ctx-13c55a78) (logid:6ff75d8d) Creating Kubernetes cluster failed due to insufficient capacity for 2 nodes cluster in zone :
 Zone-01 with service offering : Medium
2022-08-18 17:34:06,961 DEBUG [c.c.a.ApiServlet] (qtp262366552-3231:ctx-aaf26d13 ctx-13c55a78) (logid:6ff75d8d) ===END===  79.205.55.140 -- GET  name=test-kube-01&description=test-kube-01&zoneid=f2665eef-1073
-4c50-8d3a-076d44036fcc&kubernetesversionid=764c7c5a-f08b-48ad-9a0a-da4924030fc3&serviceofferingid=1b2c036e-d7c6-470e-820c-83b34f8d5af7&size=1&noderootdisksize=8&keypair=ssh-key-ed25519&command=create
KubernetesCluster&response=json
```

The log clearly shows it's not a capacity issue, it's not even checking a single hosts capacity, because no host is found suitable in the cluster.

Using exactly the same Service Offering to create a normal instance works fine.

Using a Service Offering with none or one host tag assigned to create a Kubernetes Cluster works fine.

##### EXPECTED RESULTS

As with normal instances, creating a kubernetes cluster should work with service offerings, which have more than 2 host tags comma separated assigned, as well.

##### ACTUAL RESULTS

Creating the Kubernetes Cluster fails with the error message

~~~
"Request failed. (530) Creating Kubernetes cluster failed due to insufficient capacity for 2 nodes cluster in zone : xxxx with service offering xxxx"
~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #6657 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

Deployed a k8s cluster with service offering having hosttag as tag1 and the hypervisor host having tags a tag1,tag2,tag3.

Hypervisor hosts
```
> list hosts type=Routing filter=id,name,hosttags
{
  "count": 2,
  "host": [
    {
      "id": "80492e2e-017c-497e-8291-3f4baaf57501",
      "name": "10.0.35.44"
    },
    {
      "hosttags": "tag1,tag2,tag3",
      "id": "8dc82fb8-ee97-4a7e-94e2-977c82a7bdd9",
      "name": "10.0.33.154"
    }
  ]
}
```

Service offering
```
> list serviceofferings id=49e553d7-a1d7-4ef3-a139-a90a5a0f3003 filter=id,name,hosttags,
{
  "count": 1,
  "serviceoffering": [
    {
      "hosttags": "tag1",
      "id": "49e553d7-a1d7-4ef3-a139-a90a5a0f3003",
      "name": "CKS Instance"
    }
  ]
}
```

k8s Cluster with node VMs deployed on the desired host,
```
> create kubernetescluster zoneid=9a95cda0-12fa-4f98-ab4b-ad386ca4ecb0 serviceofferingid=49e553d7-a1d7-4ef3-a139-a90a5a0f3003 name=ck-1 description=ck-1 kubernetesversionid=5cb1cdfa-9fe1-48b1-a568-4ba6c1093e4c size=1
{
  "kubernetescluster": {
    "account": "admin",
    "associatednetworkname": "ck-1-network",
    "autoscalingenabled": false,
    "controlnodes": 1,
    "cpunumber": "4",
    "created": "2022-08-22T06:51:28+0000",
    "description": "ck-1",
    "domain": "ROOT",
    "domainid": "ecc52a37-1a08-11ed-981f-1e00f100018f",
    "endpoint": "https://10.0.56.186:6443/",
    "hasannotations": false,
    "id": "21238222-f574-4ed7-b586-928f90f12ee7",
    "ipaddress": "10.0.56.186",
    "ipaddressid": "f2198222-187c-4b2b-9222-c319c74cb64a",
    "kubernetesversionid": "5cb1cdfa-9fe1-48b1-a568-4ba6c1093e4c",
    "kubernetesversionname": "v1.20.9",
    "masternodes": 1,
    "memory": "4096",
    "name": "ck-1",
    "networkid": "c7fa997f-58e3-430a-b69d-e9fae9eb775e",
    "serviceofferingid": "49e553d7-a1d7-4ef3-a139-a90a5a0f3003",
    "serviceofferingname": "CKS Instance",
    "size": 1,
    "state": "Running",
    "templateid": "870e415e-6a2c-41ab-86f2-e15a1b4285d8",
    "virtualmachines": [
      {
        "account": "admin",
        "affinitygroup": [],
        "created": "2022-08-22T06:52:21+0000",
        "details": {
          "controlNodeLoginUser": "cloud",
          "cpuOvercommitRatio": "2.0",
          "dataDiskController": "osdefault",
          "memoryOvercommitRatio": "1.0",
          "rootDiskController": "scsi",
          "rootdisksize": "8"
        },
        "displayname": "ck-1-control-182c452de9d",
        "displayvm": true,
        "domain": "ROOT",
        "domainid": "ecc52a37-1a08-11ed-981f-1e00f100018f",
        "guestosid": "ecdf4647-1a08-11ed-981f-1e00f100018f",
        "haenable": false,
        "hasannotations": false,
        "hostid": "8dc82fb8-ee97-4a7e-94e2-977c82a7bdd9",
        "hostname": "10.0.33.154",
        "hypervisor": "VMware",
        "id": "973dbd74-13ef-44c4-b7a1-841a2c804268",
        "instancename": "i-2-100004-VM",
        "isdynamicallyscalable": true,
        "lastupdated": "2022-08-22T06:52:48+0000",
        "name": "ck-1-control-182c452de9d",
        "nic": [
          {
            "broadcasturi": "vlan://2123",
            "deviceid": "0",
            "extradhcpoption": [],
            "gateway": "10.1.1.1",
            "id": "c6ce6f63-5b9d-4f8c-8d3f-9781386a61e8",
            "ipaddress": "10.1.1.37",
            "isdefault": true,
            "isolationuri": "vlan://2123",
            "macaddress": "02:00:41:06:00:02",
            "netmask": "255.255.255.0",
            "networkid": "c7fa997f-58e3-430a-b69d-e9fae9eb775e",
            "networkname": "ck-1-network",
            "secondaryip": [],
            "traffictype": "Guest",
            "type": "Isolated"
          }
        ],
        "osdisplayname": "Other Linux (64-bit)",
        "ostypeid": "ecdf4647-1a08-11ed-981f-1e00f100018f",
        "pooltype": "NetworkFilesystem",
        "receivedbytes": 0,
        "securitygroup": [],
        "sentbytes": 0,
        "state": "Running",
        "tags": [],
        "userid": "0c92d0b2-1a09-11ed-981f-1e00f100018f",
        "username": "admin",
        "zoneid": "9a95cda0-12fa-4f98-ab4b-ad386ca4ecb0",
        "zonename": "pr6276-t4676-vmware-67u3"
      },
      {
        "account": "admin",
        "affinitygroup": [],
        "created": "2022-08-22T06:52:48+0000",
        "details": {
          "controlNodeLoginUser": "cloud",
          "cpuOvercommitRatio": "2.0",
          "dataDiskController": "osdefault",
          "memoryOvercommitRatio": "1.0",
          "rootDiskController": "scsi",
          "rootdisksize": "8"
        },
        "displayname": "ck-1-node-182c45349ac",
        "displayvm": true,
        "domain": "ROOT",
        "domainid": "ecc52a37-1a08-11ed-981f-1e00f100018f",
        "guestosid": "ecdf4647-1a08-11ed-981f-1e00f100018f",
        "haenable": false,
        "hasannotations": false,
        "hostid": "8dc82fb8-ee97-4a7e-94e2-977c82a7bdd9",
        "hostname": "10.0.33.154",
        "hypervisor": "VMware",
        "id": "ddb1a7df-bf2a-4bca-9001-6eaeaa55a083",
        "instancename": "i-2-100005-VM",
        "isdynamicallyscalable": true,
        "lastupdated": "2022-08-22T06:53:07+0000",
        "name": "ck-1-node-182c45349ac",
        "nic": [
          {
            "broadcasturi": "vlan://2123",
            "deviceid": "0",
            "extradhcpoption": [],
            "gateway": "10.1.1.1",
            "id": "d869b49a-c9be-46ab-be30-2aee0b06b134",
            "ipaddress": "10.1.1.80",
            "isdefault": true,
            "isolationuri": "vlan://2123",
            "macaddress": "02:00:77:42:00:03",
            "netmask": "255.255.255.0",
            "networkid": "c7fa997f-58e3-430a-b69d-e9fae9eb775e",
            "networkname": "ck-1-network",
            "secondaryip": [],
            "traffictype": "Guest",
            "type": "Isolated"
          }
        ],
        "osdisplayname": "Other Linux (64-bit)",
        "ostypeid": "ecdf4647-1a08-11ed-981f-1e00f100018f",
        "pooltype": "NetworkFilesystem",
        "receivedbytes": 0,
        "securitygroup": [],
        "sentbytes": 0,
        "state": "Running",
        "tags": [],
        "userid": "0c92d0b2-1a09-11ed-981f-1e00f100018f",
        "username": "admin",
        "zoneid": "9a95cda0-12fa-4f98-ab4b-ad386ca4ecb0",
        "zonename": "pr6276-t4676-vmware-67u3"
      }
    ],
    "zoneid": "9a95cda0-12fa-4f98-ab4b-ad386ca4ecb0",
    "zonename": "pr6276-t4676-vmware-67u3"
  }
}
```

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Comment by shwstppr** [comment]
@blueorangutan test

**Review by rohityadavcloud — APPROVED** [review]

**Review by Pearl1594 — APPROVED** [review]
Verified Fix. LGTM

**Pull request merged**
