### PR TITLE
Deprecated changeServiceForVirtualMachine API and replaced all the oc…

### PR DESCRIPTION
**Pull request by harikrishna-patnala**
### Description

This PR fixes issue #6150 to deprecate changeServiceForVirtualMachine API. Going forward the idea is to use scaleVirtualMachine API for both stopped and running VMs which we are already doing from UI.

I've also changed the API in all the tests to use scaleVirtualMachine API.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Comment by harikrishna-patnala** [comment]
@blueorangutan test matrix

**Comment by harikrishna-patnala** [comment]
@blueorangutan test vmware-65u2

**Comment by harikrishna-patnala** [comment]
@blueorangutan test centos7 vmware-65u2

**Comment by harikrishna-patnala** [comment]
> clgtm we should go through the test files and assess whether all tests make sense/are valid. `test_deploy_vgpu_vm` seems excesive in comparison to its niche. The minimal change is certainly in line with the scope of this PR though!

Yes @DaanHoogland, I've gone through them and made the changes in the test files. By code and usage both APIs look similar. Let's wait for the smoke test results.

**Comment by DaanHoogland** [comment]
> > clgtm we should go through the test files and assess whether all tests make sense/are valid. `test_deploy_vgpu_vm` seems excesive in comparison to its niche. The minimal change is certainly in line with the scope of this PR though!
> 
> Yes @DaanHoogland, I've gone through them and made the changes in the test files. By code and usage both APIs look similar. Let's wait for the smoke test results.

Don't worry @harikrishna-patnala I do not mean for this PR to change but just to put a mental note to us all.

**Comment by rohityadavcloud** [comment]
@blueorangutan test centos7 vmware-65u2

**Comment by rohityadavcloud** [comment]
@blueorangutan test centos7 vmware-67u3

**Pull request merged**
