### PR TITLE
CLOUDSTACK-9460: For long running transactions, if the connection is

### PR DESCRIPTION
**Pull request by abhinandanprateek**
timed out by the mysql server then refresh it

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by murali-reddy** [comment]
LGTM from the code change.

**Comment by cloudmonger** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 104
 Hypervisor xenserver
 NetworkType Advanced
 Passed=101
 Failed=2
 Skipped=4

_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/yj3wnzbceo9uef2/AAB6u-Iap-xztdm6jHX9SjPja?dl=0


**Failed tests:**
* test_ssvm.py

 * test_03_ssvm_internals Failed

* test_routers_network_ops.py

 * test_02_RVR_Network_FW_PF_SSH_default_routes_egress_false Failed


**Skipped tests:**
test_vm_nic_adapter_vmxnet3
test_static_role_account_acls
test_3d_gpu_support
test_deploy_vgpu_enabled_vm

**Passed test suits:**
test_deploy_vm_with_userdata.py
test_affinity_groups_projects.py
test_portable_publicip.py
test_over_provisioning.py
test_global_settings.py
test_scale_vm.py
test_service_offerings.py
test_routers_iptables_default_policy.py
test_loadbalance.py
test_routers.py
test_reset_vm_on_reboot.py
test_snapshots.py
test_deploy_vms_with_varied_deploymentplanners.py
test_network.py
test_router_dns.py
test_non_contigiousvlan.py
test_login.py
test_deploy_vm_iso.py
test_list_ids_parameter.py
test_public_ip_range.py
test_multipleips_per_nic.py
test_regions.py
test_affinity_groups.py
test_network_acl.py
test_pvlan.py
test_volumes.py
test_nic.py
test_deploy_vm_root_resize.py
test_resource_detail.py
test_secondary_storage.py
test_vm_life_cycle.py
test_disk_offerings.py

**Comment by borisstoyanov** [comment]
@blueorangutan help

**Comment by borisstoyanov** [comment]
@blueorangutan test centos6 kvm-centos6

**Comment by rhtyd** [comment]
@abhinandanprateek ping, how severely do we need this for upcoming release?
@blueorangutan package

**Comment by jburwell** [comment]
@rhtyd this issue impacts any user with long-running secondary storage jobs.  I think it is a valuable fix for all users as the only recourse to fix these errors is to manually cleanup the database.

@abhinandanprateek I would like to get this PR merged in time for 4.8.2.0.  Could you please change the base branch of this PR to 4.8 and rebase it to pull in the most recent Marvin enhancements/fixes?

**Comment by rhtyd** [comment]
LGTM. I'll re-kick tests.
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
Tests LGTM.

**Comment by nathanejohnson** [comment]
Code LGTM

**Pull request merged**
