### PR TITLE
removal of unused interfaces

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR deletes some unused interfaces

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### CODE REVIEW

**Review by harikrishna-patnala — COMMENTED** [review]
Thanks @DaanHoogland 

I see no usages for DirectoryService also in the same directory. can we delete that as well.

**Comment by DaanHoogland** [comment]
> I see no usages for DirectoryService also in the same directory. can we delete that as well.

no, `org.apache.directory.server.core.api.DirectoryService` is used (in test code at least)

**Comment by harikrishna-patnala** [comment]
> > I see no usages for DirectoryService also in the same directory. can we delete that as well.
> 
> no, `org.apache.directory.server.core.api.DirectoryService` is used (in test code at least)

I think this is from a different package/library, the one we have and unused is from org.apache.cloudstack.engine.service.api. Just realized EntityService has also no usages. 

Sorry for asking more @DaanHoogland but just found the others while reviewing the usages.

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
> > > I see no usages for DirectoryService also in the same directory. can we delete that as well.
> > 
> > 
> > no, `org.apache.directory.server.core.api.DirectoryService` is used (in test code at least)
> 
> I think this is from a different package/library, the one we have and unused is from org.apache.cloudstack.engine.service.api. Just realized EntityService has also no usages.
> 
> Sorry for asking more @DaanHoogland but just found the others while reviewing the usages.

You are right, will try and compile it with all three, @harikrishna-patnala and update if it does.

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by rohityadavcloud — APPROVED** [review]
LGTM - didn't test myself if there are usage/references

**Review by weizhouapache — APPROVED** [review]

**Review by harikrishna-patnala — APPROVED** [review]
LGTM

**Pull request merged**
