### PR TITLE
VPC VR: fix empty iptables if there is no vpc tier

### LINKED ISSUE #8729: VPC keeping virtual router running without firewall rules
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
VR
~~~

##### CLOUDSTACK VERSION
~~~
4.19.0
~~~

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
n/a

##### SUMMARY
When having a VPC without associated vms, there are no firewall rules defined (iptables). And that's a problem because it leaves the vrouter vulnerable to receiving a packet on port 35999, and if that happens, HAProxy will start logging in a loop until it fills the vrouter's disk.

##### STEPS TO REPRODUCE
Create a new VPC with default VPC network offering
Send a package to 35999 port of VPC vrouter public IP. Example: `telnet <public-ip> 35999`
Conect to vrouter shell and check `/var/log/haproxy.log`

##### EXPECTED RESULTS
That applies the iptables rules even when there are no vms associated with the VPC, or that there is no virtual router running if there are no vms associated with the VPC (just as it is in isolated networks).

##### ACTUAL RESULTS
Virtual router running in a VPC even when there are no vms associated with it and its network offering is not as persistent and without defined firewall rules.

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #8729

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [x] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by rohityadavcloud — APPROVED** [review]

**Comment by weizhouapache** [comment]
@blueorangutan test matrix

**Review by vishesh92 — APPROVED** [review]
code lgtm

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@JoaoJandre , please merge at your will

**Comment by JoaoJandre** [comment]
@weizhouapache does this still need work? Also, could you share your test results?

**Comment by weizhouapache** [comment]
> @weizhouapache does this still need work? Also, could you share your test results?

here is the iptables rules of a VPC VR without any tier in my testing
```
root@r-1277-VM:~# iptables-save
# Generated by iptables-save v1.8.9 (nf_tables) on Fri Mar 15 19:30:53 2024
*mangle
:PREROUTING ACCEPT [474:70400]
:INPUT ACCEPT [473:70360]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [458:70506]
:POSTROUTING ACCEPT [458:70506]
-A OUTPUT -p udp -m udp --dport 68 -j CHECKSUM --checksum-fill
COMMIT
# Completed on Fri Mar 15 19:30:53 2024
# Generated by iptables-save v1.8.9 (nf_tables) on Fri Mar 15 19:30:53 2024
*filter
:INPUT DROP [7:1099]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [458:70506]
:FW_EGRESS_RULES - [0:0]
-A INPUT -d 224.0.0.18/32 -j ACCEPT
-A INPUT -d 225.0.0.50/32 -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -i eth0 -p tcp -m tcp --dport 3922 -m state --state NEW,ESTABLISHED -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
COMMIT
# Completed on Fri Mar 15 19:30:53 2024
# Generated by iptables-save v1.8.9 (nf_tables) on Fri Mar 15 19:30:53 2024
*nat
:PREROUTING ACCEPT [30:2675]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [51:4079]
:POSTROUTING ACCEPT [51:4079]
COMMIT
# Completed on Fri Mar 15 19:30:53 2024
```

which is same as

https://github.com/apache/cloudstack/blob/7b02c4cc482a97fe5efcf243a20f04769109e056/systemvm/debian/etc/iptables/iptables-vpcrouter#L18-L42

**Comment by weizhouapache** [comment]
@JoaoJandre 
please test it by yourself or ask someone else to test it.
It is required to test it manually (except the author)

**Comment by JoaoJandre** [comment]
@KlausDornsbach could you test this and share your test steps/results?

**Comment by KlausDornsbach** [comment]
Tested and clgtm @JoaoJandre

**Comment by KlausDornsbach** [comment]
Tested as described on #8729 without and with the changes in this PR:
Running the version without changes, I sent packets to the public IP address at port 35999 of the a newly created VPC VR and the HA Proxy logs got flooded, with the changes I did the same process and the VR did not accept the packets, logs were not being flooded anymore.

**Review by KlausDornsbach — APPROVED** [review]

**Pull request merged**
