### PR TITLE
Update L10N resource files with 4.9 strings from Transifex (20160607)

### PR DESCRIPTION
**Pull request by milamberspace**
cc @swill before the 4.9 release. Just only the latest FR translation.

### CODE REVIEW

**Comment by rhtyd** [comment]
LGTM

**Comment by swill** [comment]
### CI RESULTS

```
Tests Run: 85
  Skipped: 0
   Failed: 1
   Errors: 0
 Duration: 3h 57m 41s
```

**Summary of the problem(s):**
```
FAIL: test_03_vpc_privategw_restart_vpc_cleanup (integration.smoke.test_privategw_acl.TestPrivateGwACL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/git/cs2/cloudstack/test/integration/smoke/test_privategw_acl.py", line 274, in test_03_vpc_privategw_restart_vpc_cleanup
    self.performVPCTests(vpc_off, restart_with_cleanup = True)
  File "/data/git/cs2/cloudstack/test/integration/smoke/test_privategw_acl.py", line 345, in performVPCTests
    self.check_pvt_gw_connectivity(vm1, public_ip_1, [vm2.nic[0].ipaddress, vm1.nic[0].ipaddress])
  File "/data/git/cs2/cloudstack/test/integration/smoke/test_privategw_acl.py", line 704, in check_pvt_gw_connectivity
    "Ping to VM on Network Tier N from VM in Network Tier A should be successful at least for 2 out of 3 VMs"
AssertionError: Ping to VM on Network Tier N from VM in Network Tier A should be successful at least for 2 out of 3 VMs
----------------------------------------------------------------------
Additional details in: /tmp/MarvinLogs/test_network_M15ZOD/results.txt
```



**Associated Uploads**

**`/tmp/MarvinLogs/DeployDataCenter__Jul_15_2016_21_09_29_Z55XW7:`**
* [dc_entries.obj](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1583/tmp/MarvinLogs/DeployDataCenter__Jul_15_2016_21_09_29_Z55XW7/dc_entries.obj)
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1583/tmp/MarvinLogs/DeployDataCenter__Jul_15_2016_21_09_29_Z55XW7/failed_plus_exceptions.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1583/tmp/MarvinLogs/DeployDataCenter__Jul_15_2016_21_09_29_Z55XW7/runinfo.txt)

**`/tmp/MarvinLogs/test_network_M15ZOD:`**
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1583/tmp/MarvinLogs/test_network_M15ZOD/failed_plus_exceptions.txt)
* [results.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1583/tmp/MarvinLogs/test_network_M15ZOD/results.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1583/tmp/MarvinLogs/test_network_M15ZOD/runinfo.txt)

**`/tmp/MarvinLogs/test_vpc_routers_4V87YS:`**
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1583/tmp/MarvinLogs/test_vpc_routers_4V87YS/failed_plus_exceptions.txt)
* [results.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1583/tmp/MarvinLogs/test_vpc_routers_4V87YS/results.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1583/tmp/MarvinLogs/test_vpc_routers_4V87YS/runinfo.txt)


Uploads will be available until `2016-09-17 02:00:00 +0200 CEST`

*Comment created by [`upr comment`](https://github.com/cloudops/upr).*

**Comment by swill** [comment]
I have run this set of tests twice in two different environments, both with the same error.  I don't really understand how this change could cause this error, so hopefully someone can comment on this for me.  Any ideas?  False negative?

**Comment by milamberspace** [comment]
@swill I do not see why changes on the L10N resource files have an impact on the VPC behavior ... This looks like a false positive ...

**Comment by swill** [comment]
Thanks, I couldn't either, but wanted to get a second opinion.  I am running CI against it for the 3rd time to see if the same thing pops again.

**Comment by swill** [comment]
### CI RESULTS

```
Tests Run: 85
  Skipped: 0
   Failed: 0
   Errors: 0
 Duration: 4h 03m 22s
```



**Associated Uploads**

**`/tmp/MarvinLogs/DeployDataCenter__Jul_18_2016_20_28_35_16N8QD:`**
* [dc_entries.obj](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1583/tmp/MarvinLogs/DeployDataCenter__Jul_18_2016_20_28_35_16N8QD/dc_entries.obj)
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1583/tmp/MarvinLogs/DeployDataCenter__Jul_18_2016_20_28_35_16N8QD/failed_plus_exceptions.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1583/tmp/MarvinLogs/DeployDataCenter__Jul_18_2016_20_28_35_16N8QD/runinfo.txt)

**`/tmp/MarvinLogs/test_network_SOO9Z7:`**
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1583/tmp/MarvinLogs/test_network_SOO9Z7/failed_plus_exceptions.txt)
* [results.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1583/tmp/MarvinLogs/test_network_SOO9Z7/results.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1583/tmp/MarvinLogs/test_network_SOO9Z7/runinfo.txt)

**`/tmp/MarvinLogs/test_vpc_routers_IFX6VI:`**
* [failed_plus_exceptions.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1583/tmp/MarvinLogs/test_vpc_routers_IFX6VI/failed_plus_exceptions.txt)
* [results.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1583/tmp/MarvinLogs/test_vpc_routers_IFX6VI/results.txt)
* [runinfo.txt](https://objects-east.cloud.ca/v1/e465abe2f9ae4478b9fff416eab61bd9/PR1583/tmp/MarvinLogs/test_vpc_routers_IFX6VI/runinfo.txt)


Uploads will be available until `2016-09-18 02:00:00 +0200 CEST`

*Comment created by [`upr comment`](https://github.com/cloudops/upr).*

**Pull request merged**
