### PR TITLE
VPC: support LB in multiple vpc tiers if LB provider is VpcVirtualRouter

### LINKED ISSUE #5553: Several public IP with load balancer rules overwrite each other
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME
VR: LOAD BALANCER RULE

##### CLOUDSTACK VERSION
4.15.1.0

##### SUMMARY
When having at least 2 public IPs configured with load balancer rules, the configuration overwrite each other and
only one set of rules on 1 public IP are usable. 

##### STEPS TO REPRODUCE
1. Assign 2 public IPs
2. Create 3 rules on IP one
3. Create 1 rule on IP two

Then the rules on step 2 disappear, I could test it entering to the haproxy.cfg file and realized they're gone

##### EXPECTED RESULTS
Having multiple IP each with multiple load balancer rules

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #5553 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Pull request merged**
