### PR TITLE
[CLOUDSTACK-10020] Changes to make marvin work with projects and VPCs

### PR DESCRIPTION
**Pull request by syed**
Currently there are a lot of problems when running Marvin with projects and VPCs enabled. Most of them are related to the fact that some functions don't take the projectid or the vpcid parameter. This PR is an attempt to fix those problems and have better testability of setups with VPC and projects.

### CODE REVIEW

**Comment by cloudmonger** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 1031
 Hypervisor xenserver
 NetworkType Advanced
 Passed=95
 Failed=17
 Skipped=12

_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/r2si930m8xxzavs/AAAzNrnoF1fC3auFrvsKo_8-a?dl=0

**Failed tests:**
* test_routers.py

 * test_03_restart_network_cleanup Failing since 10 runs

 * test_04_restart_network_wo_cleanup Failing since 10 runs

 * test_05_router_basic Failing since 10 runs

 * test_06_router_advanced Failing since 10 runs

 * test_08_start_router Failing since 10 runs

 * test_09_reboot_router Failing since 10 runs

* test_network.py

 * test_reboot_router Failing since 10 runs

* test_router_dns.py

 * test_router_dns_guestipquery Failed

* test_deploy_vm_iso.py

 * test_deploy_vm_from_iso Failing since 85 runs

* test_list_ids_parameter.py

 * ContextSuite context=TestListIdsParams>:setup Failing since 48 runs

* test_volumes.py

 * test_06_download_detached_volume Failed

* test_nic.py

 * test_01_nic Failing since 10 runs

* test_vm_life_cycle.py

 * test_10_attachAndDetach_iso Failing since 85 runs

* test_routers_network_ops.py

 * test_01_isolate_network_FW_PF_default_routes_egress_true Failing since 118 runs

 * test_02_isolate_network_FW_PF_default_routes_egress_false Failing since 118 runs

 * test_01_RVR_Network_FW_PF_SSH_default_routes_egress_true Failing since 115 runs

 * test_02_RVR_Network_FW_PF_SSH_default_routes_egress_false Failing since 115 runs


**Skipped tests:**
test_vm_nic_adapter_vmxnet3
test_01_verify_libvirt
test_02_verify_libvirt_after_restart
test_03_verify_libvirt_attach_disk
test_04_verify_guest_lspci
test_05_change_vm_ostype_restart
test_06_verify_guest_lspci_again
test_static_role_account_acls
test_11_ss_nfs_version_on_ssvm
test_nested_virtualization_vmware
test_3d_gpu_support
test_deploy_vgpu_enabled_vm

**Passed test suits:**
test_deploy_vm_with_userdata.py
test_affinity_groups_projects.py
test_portable_publicip.py
test_vm_snapshots.py
test_over_provisioning.py
test_global_settings.py
test_router_dnsservice.py
test_scale_vm.py
test_service_offerings.py
test_routers_iptables_default_policy.py
test_loadbalance.py
test_reset_vm_on_reboot.py
test_deploy_vms_with_varied_deploymentplanners.py
test_non_contigiousvlan.py
test_login.py
test_public_ip_range.py
test_multipleips_per_nic.py
test_metrics_api.py
test_regions.py
test_affinity_groups.py
test_network_acl.py
test_pvlan.py
test_deploy_vm_root_resize.py
test_resource_detail.py
test_secondary_storage.py
test_disk_offerings.py

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
Additional review requested -- @nvazquez @DaanHoogland @borisstoyanov

**Comment by syed** [comment]
@borisstoyanov We have tests that are internal where we use Projects and VPCs. I'll post those tests to the community as they get more mature

**Comment by DaanHoogland** [comment]
@syed is this still actual? are you still working on it?

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
let's see if this still works
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by GabrielBrascher — APPROVED** [review]
Code LGTM

**Pull request merged**
