### PR TITLE
CLOUDSTACK-9048: Fix typo for public network description

### PR DESCRIPTION
**Pull request by Carles-Figuerola**

### CODE REVIEW

**Comment by DaanHoogland** [comment]
lgtm. I am sure native english speaker appreciate this one.

**Comment by pdube** [comment]
LGTM

**Comment by wido** [comment]
LGTM

Trivial fix

**Comment by remibergsma** [comment]
LGTM, just to be sure run all integration tests against this branch. They all passed.

screen shot 2015-11-22 at 12 55 37

**Pull request merged**
