### PR TITLE
test: sleep 30s after restarting mgt server in test_kubernetes_supported_versions.py

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes test failure with test_secondary_storage.py

mgmt server is restarted in cleanup of test_kubernetes_supported_versions.py as last step.

in some smoke tests, test_secondary_storage.py is run behind test_kubernetes_supported_versions.py. 
but in  test_secondary_storage.py it checks if all hosts are Up as first step.
sometimes, the mgmt server is Up, but hosts are still in Connecting state. this causes the test failure with test_secondary_storage.py

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Review by rohityadavcloud — APPROVED** [review]

**Review by shwstppr — APPROVED** [review]

**Review by sureshanaparti — APPROVED** [review]

**Review by DaanHoogland — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@sureshanaparti i think we don't need testing of these changes, leaving it up to you.

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Pull request merged**
