### PR TITLE
CLOUDSTACK-9949 - add ability to specify mac address

### PR DESCRIPTION
**Pull request by nathanejohnson**
Added ability to specify mac in deployVirtualMachine and
addNicToVirtualMachine api endpoints.

Validates mac address to be in the form of:
aa:bb:cc:dd:ee:ff , aa-bb-cc-dd-ee-ff , or aa.bb.cc.dd.ee.ff.

Ensures that mac address is a Unicast mac.

Ensures that the mac address is not already allocated for the
specified network.

### CODE REVIEW

**Comment by jayapalu** [comment]
@nathanejohnson 
The current mac address generation pattern 'getNextAvailableMacAddressInNetwork' is skipped with the user passed mac address. 
Can you please propose this feature in the community.

**Comment by nathanejohnson** [comment]
@jayapalu , I have made a proposal to the list.  But in brief, by necessity for this to work I have to skip auto generation of the mac if I'm going to allow it to be passed in.  Is your concern for a potential collision if the specified mac is within the same prefix as the generated macs?

**Comment by remibergsma** [comment]
@nathanejohnson Tested it, works great! LGTM

I'd check the spelling of MAC address, it's not fully consistent.

image

image

**Comment by nathanejohnson** [comment]
@remibergsma Thanks for testing!

**Comment by PaulAngus** [comment]
Any chance of adding ability to change the MAC ? :)

@blueorangutan package

**Comment by nathanejohnson** [comment]
@PaulAngus I assume you mean to be able to change a mac once the VM is deployed?  For now you'd have to remove the NIC and then add another.  I might be able to tweak the updateVmNicIp call to accept a mac, but I'll have to get back to you.

**Comment by PaulAngus** [comment]
thanks

@blueorangutan test

**Comment by kiwiflyer** [comment]
ping @syed @swill You guys might be interested in this. It will make migration to the cloud easier.

**Comment by PaulAngus** [comment]
@blueorangutan test matrix

**Comment by rhtyd** [comment]
LGTM, test LGTM as well, I don't see any new failures.

**Pull request merged**
