### PR TITLE
List CPU Sockets Metrics API: Combines CPU Socket Metrics For All Hypervisors

### PR DESCRIPTION
**Pull request by kioie**
## Description

Picks up on the work of @niteshsarda on PR #2440
Separating API work from UI changes, for easier management and review

**Requirement :**

Introduce a new API to collect and list CPU Sockets Metrics information for each hypervisor. Currently, listHosts API is fired for each hypervisor seprately to retrieve the count of CPU sockets. So, with this fix instead of multiple API execution, single API query will be executed to reterieve information for all the hypervisors.

**Implementation :**

1. Introduced a new API namely "listCpuSocketsMetrics", which will fetch details of CPU Sockets for all the hypervisors in a single run.
2. In this API, a query will be fired on a host table to fetch details based on grouping of Hypervisor type and Hypervisor version.
3. This API will prevent multiple calls of listHosts API and thus will improve performance of the infrastructure tab.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

`list cpusocketsmetrics`

### CODE REVIEW

**Comment by kioie** [comment]
ping @borisstoyanov @GabrielBrascher @rafaelweingartner @niteshsarda 
@blueorangutan package

**Comment by kioie** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@kioie Do you still want this (in 4.15 or beyond)?

**Comment by kioie** [comment]
Hi Dan, no, not really. Feature included in PR #1944

**Pull request closed without merging**
