### PR TITLE
ui: Show displayname in compute list view

### PR DESCRIPTION
**Pull request by davidjumani**
### Description

Adds displayname in the compute list view

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

### Screenshots (if appropriate):

Screenshot from 2021-03-10 14-57-16

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan ui

**Comment by utchoang** [comment]
@davidjumani can you change the base branch of the PR and rebase your PR branch to 4.15?

**Comment by davidjumani** [comment]
@utchoang Done!
@blueorangutan ui

**Review by utchoang — APPROVED** [review]
LGTM!

**Comment by rhtyd** [comment]
LGTM

**Pull request merged**
