### PR TITLE
CLOUDSTACK-9267: String is not localized on create instance wizards.

### PR DESCRIPTION
**Pull request by nitin-maharana**
Repro Steps: 
==========
1. Setup basic environments as normal.
2. Open a browser, go to Web Console.
3. Upload a iso template.
4. Go to "Instances" page and add new instance.
5. Check the strings on create instance wizards.

Expected Result:
=============
All the strings should be localized on create instance wizards.

Actual Result:
===========
Some strings are not localized on create instance wizards.

Language:
========
JA -> Fail
SC -> Fail

Fix:
===
Fixed the hard coded string.

### CODE REVIEW

**Comment by DaanHoogland** [comment]
more explanation then code, but makes sense. mostly cosmatic: LGTM

**Comment by nitin-maharana** [comment]
I thought of making a small explanation. But I follow this template while making a PR so that it would be easy for committer to review very fast. Anyway Thanks @DaanHoogland

**Comment by nitin-maharana** [comment]
There is one more localised issue in the project page, So instead of creating a new one adding it to this PR only.

**Comment by DaanHoogland** [comment]
LGTM as well

**Comment by rafaelweingartner** [comment]
@nitin-maharana, 
Your changes LGTM.
I just noticed that function “_l”, is that something we have created?

**Comment by nitin-maharana** [comment]
@rafaelweingartner : Its already present in our code. It translates the dictionary keys.

**Comment by rafaelweingartner** [comment]
@nitin-maharana have you tested everything? @DaanHoogland  Can we merge this? And then forward it to master

**Comment by nitin-maharana** [comment]
@rafaelweingartner : I have tested all changes.

**Comment by DaanHoogland** [comment]
@rafaelweingartner go ahead, if you LGTM as well.

**Comment by rafaelweingartner** [comment]
merged to 4.7, and then forwarded to master

**Comment by swill** [comment]
Do we need to add a resources file to the Jenkins box to provide translations for these entries?

I believe this is the cause of the recent jenkins failure.  Does that make sense?

http://markmail.org/message/svyyit7klk6ixvya?q=list:org%2Eapache%2Eincubator%2Ecloudstack-%2A+Build+failed+in+Jenkins:+build-master-slowbuild+%233320

**Comment by rafaelweingartner** [comment]
@swill those entries already exist.
That failure in Jenkins seems to be happening even before Feb. 24th
It seems that I do not have access to Jenkins, can someone with access provide us with the log of that new warning that was generated.

**Comment by swill** [comment]
Thanks.  I will dig a bit deeper and and see if I can figure out why the failures are happening in jenkins.

**Comment by swill** [comment]
Sorry for the false alarm here.  I didn't dig deep enough initially.  It seems that the Jenkins slave is out of disk space which is resulting in errors.

**Comment by bvbharatk** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 101
 Hypervisor xenserver
 NetworkType Advanced
 Passed=104
 Failed=10
 Skipped=4

**The follwing tests have known issues**
test_vpc_remote_access_vpn
test_vpc_site2site_vpn
test_01_test_vm_volume_snapshot
test_02_vpc_privategw_static_routes
test_03_rvpc_privategw_static_routes
test_04_change_offering_small
ContextSuite context=TestNiciraContoller>:setup
test_01_primary_storage_iscsi
test02_internallb_haproxy_stats_on_all_interfaces
test_01_internallb_roundrobin_1VPC_3VM_HTTP_port80
ContextSuite context=TestDeployVM>:setup
test_04_extract_template
test_04_extract_Iso
test_07_list_default_iso


_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/yj3wnzbceo9uef2/AAB6u-Iap-xztdm6jHX9SjPja?dl=0


**Failed tests:**
* integration.smoke.test_privategw_acl.TestPrivateGwACL

 * test_01_vpc_privategw_acl Failed in this run

* integration.smoke.test_guest_vlan_range.TestDedicateGuestVlanRange

 * test_dedicateGuestVlanRange Failed in this run


**Skipped tests:**
test_vm_nic_adapter_vmxnet3
test_deploy_vgpu_enabled_vm
test_06_copy_template
test_06_copy_iso

**Passed test suits:**
integration.smoke.test_deploy_vm_with_userdata.TestDeployVmWithUserData
integration.smoke.test_affinity_groups_projects.TestDeployVmWithAffinityGroup
integration.smoke.test_portable_publicip.TestPortablePublicIPAcquire
integration.smoke.test_over_provisioning.TestUpdateOverProvision
integration.smoke.test_global_settings.TestUpdateConfigWithScope
integration.smoke.test_scale_vm.TestScaleVm
integration.smoke.test_service_offerings.TestCreateServiceOffering
integration.smoke.test_loadbalance.TestLoadBalance
integration.smoke.test_routers.TestRouterServices
integration.smoke.test_reset_vm_on_reboot.TestResetVmOnReboot
integration.smoke.test_snapshots.TestSnapshotRootDisk
integration.smoke.test_deploy_vms_with_varied_deploymentplanners.TestDeployVmWithVariedPlanners
integration.smoke.test_network.TestDeleteAccount
integration.smoke.test_non_contigiousvlan.TestUpdatePhysicalNetwork
integration.smoke.test_deploy_vm_iso.TestDeployVMFromISO
integration.smoke.test_public_ip_range.TestDedicatePublicIPRange
integration.smoke.test_multipleips_per_nic.TestDeployVM
integration.smoke.test_regions.TestRegions
integration.smoke.test_affinity_groups.TestDeployVmWithAffinityGroup
integration.smoke.test_network_acl.TestNetworkACL
integration.smoke.test_pvlan.TestPVLAN
integration.smoke.test_volumes.TestCreateVolume
integration.smoke.test_ssvm.TestSSVMs
integration.smoke.test_nic.TestNic
integration.smoke.test_deploy_vm_root_resize.TestDeployVM
integration.smoke.test_resource_detail.TestResourceDetail
integration.smoke.test_secondary_storage.TestSecStorageServices
integration.smoke.test_vm_life_cycle.TestDeployVM
integration.smoke.test_disk_offerings.TestCreateDiskOffering

**Comment by bvbharatk** [comment]
### ACS CI BVT Run
 **Sumarry:**
 Build Number 102
 Hypervisor xenserver
 NetworkType Advanced
 Passed=104
 Failed=13
 Skipped=4

**The follwing tests have known issues**
test_vpc_remote_access_vpn
test_vpc_site2site_vpn
test_01_test_vm_volume_snapshot
test_02_vpc_privategw_static_routes
test_03_rvpc_privategw_static_routes
test_04_change_offering_small
ContextSuite context=TestNiciraContoller>:setup
test_01_primary_storage_iscsi
test02_internallb_haproxy_stats_on_all_interfaces
test_01_internallb_roundrobin_1VPC_3VM_HTTP_port80
ContextSuite context=TestDeployVM>:setup
test_04_extract_template
test_04_extract_Iso
test_07_list_default_iso


_Link to logs Folder (search by build_no):_ https://www.dropbox.com/sh/yj3wnzbceo9uef2/AAB6u-Iap-xztdm6jHX9SjPja?dl=0


**Failed tests:**
* integration.smoke.test_guest_vlan_range.TestDedicateGuestVlanRange

 * test_dedicateGuestVlanRange Failing since 2 runs

 * ContextSuite context=TestDedicateGuestVlanRange>:teardown Failed in this run

* integration.smoke.test_loadbalance.TestLoadBalance

 * test_01_create_lb_rule_src_nat Failed in this run


**Skipped tests:**
test_vm_nic_adapter_vmxnet3
test_deploy_vgpu_enabled_vm
test_06_copy_template
test_06_copy_iso

**Passed test suits:**
integration.smoke.test_deploy_vm_with_userdata.TestDeployVmWithUserData
integration.smoke.test_affinity_groups_projects.TestDeployVmWithAffinityGroup
integration.smoke.test_portable_publicip.TestPortablePublicIPAcquire
integration.smoke.test_over_provisioning.TestUpdateOverProvision
integration.smoke.test_global_settings.TestUpdateConfigWithScope
integration.smoke.test_scale_vm.TestScaleVm
integration.smoke.test_service_offerings.TestCreateServiceOffering
integration.smoke.test_routers.TestRouterServices
integration.smoke.test_reset_vm_on_reboot.TestResetVmOnReboot
integration.smoke.test_snapshots.TestSnapshotRootDisk
integration.smoke.test_deploy_vms_with_varied_deploymentplanners.TestDeployVmWithVariedPlanners
integration.smoke.test_network.TestDeleteAccount
integration.smoke.test_non_contigiousvlan.TestUpdatePhysicalNetwork
integration.smoke.test_deploy_vm_iso.TestDeployVMFromISO
integration.smoke.test_public_ip_range.TestDedicatePublicIPRange
integration.smoke.test_multipleips_per_nic.TestDeployVM
integration.smoke.test_regions.TestRegions
integration.smoke.test_affinity_groups.TestDeployVmWithAffinityGroup
integration.smoke.test_network_acl.TestNetworkACL
integration.smoke.test_pvlan.TestPVLAN
integration.smoke.test_volumes.TestCreateVolume
integration.smoke.test_ssvm.TestSSVMs
integration.smoke.test_nic.TestNic
integration.smoke.test_deploy_vm_root_resize.TestDeployVM
integration.smoke.test_resource_detail.TestResourceDetail
integration.smoke.test_secondary_storage.TestSecStorageServices
integration.smoke.test_vm_life_cycle.TestDeployVM
integration.smoke.test_disk_offerings.TestCreateDiskOffering

**Pull request merged**
