### PR TITLE
CKS: create HA cluster with 3 control VMs instead 2

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes the test failures with CKS HA-cluster upgrade.
In production, the CKS HA cluster should have at least 3 control VMs as well.
The etcd cluster requires 3 members to achieve reliable HA. The etcd daemon in control VMs uses RAFT protocol to determine the roles of nodes. During upgrade of CKS with HA, the etcd become unreliable if there are only 2 control VMs.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan test matrix

**Review by DaanHoogland — COMMENTED** [review]
clgtm

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
The ISOes are used by all trillian tests after Tue Dec 5 14:43 CET. 
no need to run marvin tests for this PR

**Review by shwstppr — APPROVED** [review]
Code LGTM

I was not sure of the java change but only to find out that `--delete-local-data` has been deprecated now.

Running HA k8s cluster would mean 5 VMs now introducing further load on the test env. At some point we should move some of the test into component directory.

**Comment by weizhouapache** [comment]
> Code LGTM
> 
> I was not sure of the java change but only to find out that `--delete-local-data` has been deprecated now.
> 
> Running HA k8s cluster would mean 5 VMs now introducing further load on the test env. At some point we should move some of the test into component directory.

Yes, if everything is ok, 5 kubernetes VMs with 2U/2GB Ram can be deployed in the envs with 2 hosts with 8G RAM.
No need to add more host.

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by weizhouapache** [comment]
@blueorangutan test matrix

**Comment by shwstppr** [comment]
Failures are env related

**Comment by zap51** [comment]
This fixes https://github.com/apache/cloudstack/issues/7537. Thanks!

**Pull request merged**
