### PR TITLE
Split travis tests to avoid timeout

### PR DESCRIPTION
**Pull request by GabrielBrascher**
## Description

A few tests have been failing constantly due to timeout.
This PR has purpose to evaluate Travis's behavior when splitting a few of the "problematic" tests.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by rhtyd** [comment]
Good idea, but looks like Travis failed can you check @GabrielBrascher thnx

**Comment by GabrielBrascher** [comment]
One of the tests still has the same issue, thanks for ping @rhtyd. I will re-check it and soon kick Travis again.

**Comment by GabrielBrascher** [comment]
@rhtyd Travis CI Build is passing fine. Jenkins got issues on `NiciraNvpGuestNetworkGuruTest`; however, those issues are not related to this PR.

I will be re-running Travis a couple more times to check.

**Comment by GabrielBrascher** [comment]
Travis tests are looking good. After last commit Travis had no issues.

**Comment by GabrielBrascher** [comment]
Two more tests were terminated by maximum log length:

```
TESTS="smoke/test_accounts smoke/test_affinity_groups smoke/test_affinity_groups_projects smoke/test_async_job smoke/test_backup_recovery_dummy smoke/test_create_list_domain_account_project smoke/test_create_network smoke/test_deploy_vgpu_enabled_vm smoke/test_deploy_vm_extra_config_data smoke/test_deploy_vm_iso smoke/test_deploy_vm_root_resize smoke/test_deploy_vm_with_userdata smoke/test_deploy_vms_with_varied_deploymentplanners"
```
&
```
TESTS="smoke/test_scale_vm smoke/test_secondary_storage smoke/test_service_offerings smoke/test_snapshots smoke/test_ssvm smoke/test_staticroles smoke/test_templates smoke/test_update_security_group smoke/test_usage smoke/test_usage_events" 
```

I will do a few more changes.

**Comment by rhtyd** [comment]
Re-kicked travis

**Comment by GabrielBrascher** [comment]
Thanks for Re-kicking travis @rhtyd I will re-check the failures. It still not good : (

**Pull request closed without merging**
