### PR TITLE
CLOUDSTACK-10215: Excessive log4j debug level in CPVM could lead to FS overflow

### PR DESCRIPTION
**Pull request by bwsw**
Jira reference: https://issues.apache.org/jira/browse/CLOUDSTACK-10215

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@rhtyd I think we can add this to 4.11, no?

**Comment by rhtyd** [comment]
@DaanHoogland sure, squash merge should be fine to remove the 'merge' commits. I'll kick a round of test.
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
Test LGTM, all the failures are env related and not with this PR.
Using Daan's comment, consider this as LGTM as squash merge will remove the merge commits, I'll merge this based on two lgtms (code review) and test.

**Pull request merged**
