### PR TITLE
Honor the forced parameter for stopVirtualMachine api call

### PR DESCRIPTION
**Pull request by nathanejohnson**
CLOUDSTACK-9451

https://issues.apache.org/jira/browse/CLOUDSTACK-9451

### CODE REVIEW

**Comment by karuturi** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@karuturi @jburwell test keyword has been disabled due to infrastructural issues, I'll try to get this fixed today. Also, we need to run package first, to evaluate build/test/package checks before running Trillian test as each Trillian test is relatively more expensive.

@blueorangutan package

**Comment by rhtyd** [comment]
@nathanejohnson LGTM, but this bug affects 4.9 as well; please close this PR and reopen against 4.9. Your PR when accepted will be merged on 4.9 and fwd-merged on master. Thanks.

**Comment by ProjectMoon** [comment]
It goes all the way back to 4.7. Isn't the oldest supported release currently 4.8 at the moment? If so, it should be opened against 4.8, right?

**Comment by rhtyd** [comment]
@ProjectMoon With our current branch support policy, we should merge bugfixes/changes on master and the last release branch (i.e. 4.9 and also since 4.9 is current/to-be lts branch). I'm fine with sending the PR for 4.7/4.8 as well.

**Comment by ProjectMoon** [comment]
I thought it was: new features -> master, bug fixes -> oldest supported release branch? 4.7 is no longer supported but as far as I know 4.8 is still supported (I could be wrong on this).

**Comment by karuturi** [comment]
@ProjectMoon Thats correct. bugfixes should go to 4.8, the oldest supported branch.

**Comment by nathanejohnson** [comment]
@karaturi @ProjectMoon @rthyd I will close and reopen against 4.8, thanks

**Pull request closed without merging**
