### PR TITLE
Infra25725 add codecov token to workflow

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR...

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [x] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by rohityadavcloud — APPROVED** [review]

**Comment by weizhouapache** [comment]
@DaanHoogland 
is the codecov token needed for simulator CI ?

**Comment by weizhouapache** [comment]
great, it works 
image


good job @DaanHoogland  !

**Comment by DaanHoogland** [comment]
> @DaanHoogland is the codecov token needed for simulator CI and UI build ?
> 
> ```
> $ git grep codecov-action
> .github/workflows/ci.yml:      - uses: codecov/codecov-action@v3
> .github/workflows/codecov.yml:      - uses: codecov/codecov-action@v3
> .github/workflows/ui.yml:      - uses: codecov/codecov-action@v3
> ```

they probably are, thanks

**Review by weizhouapache — APPROVED** [review]

**Review by sureshanaparti — APPROVED** [review]
LGTM

**Pull request merged**
