### PR TITLE
Fix: check root disk offering tagged limits during VM deploy

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR fixes a scenario in tagged limits checking. When user provides `overriderootdiskoffering` during `deployVirtualMachine`, the limits for this root disk aren't checked.

#### Steps to reproduce
Can be reproduced in Simulator. Begin by setting up a new Simulator zone, ready to deploy VMs.

1. create a test domain and account
2. create an NFS storage pool with a tag, e.g. "fast"
3. enable `resource.limit.storage.tags` for "fast" storage
4. create a disk offering with custom size, and storage tag "fast"
5. set primary storage limit for test domain and storage tag "fast", e.g. 5 GiB limit
6. launch a VM, using override root disk offering pointing to the "fast" offering, and size that goes beyond user's "fast" limit.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

Applied this patched and tried to reproduce the issue with different scenarios.

### CODE REVIEW

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan test

**Review by rohityadavcloud — APPROVED** [review]

**Review by borisstoyanov — APPROVED** [review]
LGTM, manually tested it

**Pull request merged**
