### PR TITLE
Improves CPU usage info

### PR DESCRIPTION
**Pull request by RodrigoDLopez**
### Description

The information provided about the statistics caused doubts to the operators, as these were not clear enough. These messages have been changed in order to simplify their understanding. In addition, a new message was added regarding the displayed graphics. These are the new messages in EN

Graphics info icon:
image

Graphics information:
image

CPU usage information:
image

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by JoaoJandre — APPROVED** [review]
CLGTM

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@RodrigoDLopez in http://qa.cloudstack.cloud:8080/client/pr/6784/#/vm/ce767d15-6294-4dfa-ad88-052c86c6ac1f?tab=stats I do not see the changed ui elements as you have in your screenshots. Is there any precondition the qa env might be missing?

**Comment by RodrigoDLopez** [comment]
> @RodrigoDLopez in http://qa.cloudstack.cloud:8080/client/pr/6784/#/vm/ce767d15-6294-4dfa-ad88-052c86c6ac1f?tab=stats I do not see the changed ui elements as you have in your screenshots. Is there any precondition the qa env might be missing?
> 
> erratum: the infor for the cpu is there, but the generic message seems to be missing.

@DaanHoogland thanks for the test, now the icon and message are there

**Review by stephankruggg — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
cc @shwstppr are you lgtm on this?

**Comment by shwstppr** [comment]
@blueorangutan ui

**Review by shwstppr — APPROVED** [review]
LGTM cc @DaanHoogland @rohityadavcloud

**Review by GutoVeronezi — APPROVED** [review]
CLGTM

**Comment by GutoVeronezi** [comment]
Merging this one based on the approvals and test results.

**Pull request merged**
