### PR TITLE
cleanup for resources left by test_accounts and test_project

### PR DESCRIPTION
**Pull request by DaanHoogland**
## Description

pertaining to #3693 (only fixes part)
- [X] test_accounts
- [x] test_projects

## Types of changes

- [x] Cleanup (Code refactoring and cleanup, that may add test cases)
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by andrijapanicsb** [comment]
@DaanHoogland can you advise on the status on this one?

**Comment by DaanHoogland** [comment]
it is tests only and needs a bit of cleaning as part of it was already merged. No priority to go in any release and only important for CI like trillian.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@andrijapanicsb @PaulAngus this one is low priority but will help us reusing test envs a bit, as it implements a bit of cleanups in the tests. have a look please

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
ping @andrijapanicsb

**Comment by rhtyd** [comment]
ping @andrijapanicsb @borisstoyanov @PaulAngus

**Pull request merged**
