### PR TITLE
Move Devcloud4 into main repository

### PR DESCRIPTION
**Pull request by imduffy15**
Hi All,

As per the discussion on the mailing list I want to bring devcloud4 into a community place.
This PR exists to do that.

I have tested all versions, basic, advanced, binary installation basic and binary installation advanced. I only tested from a OSX machine.

I believe I've placed the apache license header on all appropriate files.

### CODE REVIEW

**Comment by runseb** [comment]
@imduffy15 can you squash those commits..?

**Comment by imduffy15** [comment]
Will do once I get back on a machine

**Comment by imduffy15** [comment]
Does this look OK to people? :)

**Comment by runseb** [comment]
LGTM, you can merge it

**Pull request closed without merging**
