### PR TITLE
Do remove volume only on expunge

### PR DESCRIPTION
**Pull request by sureshanaparti**
### Description
This PR includes the changes to remove volume only on expunge.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### How Has This Been Tested?

Manually tested destroy and recover volumes.

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
cltgm

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Review by shwstppr — APPROVED** [review]

**Comment by sureshanaparti** [comment]
Merging this based on approvals and test results.

**Pull request merged**
