### PR TITLE
Fix failure test with ConfigKeyScheduledExecutionWrapperTest

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes the test failure with ConfigKeyScheduledExecutionWrapperTest

see 
https://github.com/apache/cloudstack/actions/runs/9171106108/job/25214722629
https://github.com/apache/cloudstack/actions/runs/9171320792/job/25215400678
https://github.com/apache/cloudstack/actions/runs/9180519825/job/25261374756

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
build passes, only unit-test but I'll do a packaging anyway to be double sure

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
Hi @weizhouapache I think the fix should be in a NPE check, let me raise another PR (I found this and fixed in a different way, in a private R&D PR)

**Pull request merged**
